### ISSUE TITLE
backtick bahavior in embedded strings in interpolated subexpressions

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#10045]
# Steps to reproduce

```powershell
"$('`' -replace '[`"]', '$0$0')" # produces single backtick, expected double
'`' -replace '[`"]', '$0$0' # produces double backticks
"$('`' -replace '[``"]', '$0$0')" # produces double backticks
"$('`' -replace '[`]', '$0$0')" # produces double backticks
```

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.18922
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I am sure this is a tokenizer issue during the subexpression tokenizing, similar to how a closing ')' can end a single line comment or even an embedded string within an interpolated subexpression.

**Comment by mklement0** [comment]
At least at first glance, this _may_ have the same root cause as #3039.

**Comment by UberKluger** [comment]
May be #3039? It ***is*** #3039 (and #10413). These are all the same thing. The parser (or whatever) is processing subexpressions within expandable strings as if they were part of the string and not a completely separate syntactic context. As such, any double quote escapes  (`" or "") within the subexpression are being evaluated and replaced ***before*** the subexpression is parsed (evaluated?). Thus your examples are being silently changed as follows (silently because there is no mention of this in the documentation)
```
"$('`' -replace '[`"]', '$0$0')" # produces single backtick, expected double
becomes -> "$('`' -replace '["]', '$0$0')" # `" is an escaped ", replace fails, string unchanged

'`' -replace '[`"]', '$0$0' # produces double backticks because it is not an embedded subexpression

"$('`' -replace '[``"]', '$0$0')" # produces double backticks
becomes -> "$('`' -replace '[`"]', '$0$0')" # `" replaced but initial ` remains so replace succeeds

"$('`' -replace '[`]', '$0$0')" # produces double backticks because there is no escaped " to consume the `
```
Further examples to "prove" it
```
"$('`' -replace '["`]', '$0$0')" # produces double backticks even though the character class seems to be equivalent

"$('[``"] [`x`"] [``x"]')" # produces [`"] [`x"] [``x"] showing that the ` does not escape itself or the x, only the "
```

In #3039 there are those saying that this should not be fixed (too much of a breaking change) but it should at least be ***thoroughly*** documented (when and why this occurs). Even if it does get fixed (one day) the documentation should still mention it for historical continuity (breaking changes are bad but ignoring the past is worse).
