### ISSUE TITLE
Updating System.ServiceProcess.ServiceController to its .Net Core 3-preview6 version breaks 2 tests

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#10067]
Updating the 2 NuGet package [System.ServiceProcess.ServiceController](https://www.nuget.org/packages/System.ServiceProcess.ServiceController) (or `Microsoft.Windows.Compatibility`, which is depending on it) from `4.5.0` (.Net Core 2.1) to `4.6.0-preview6.19303.8` (.Net Core 3-preview6)  breaks 2 tests and the reason for their failure seems to be unclear (i.e. whether it is a problem of PowerShell itself that is now being exposed or a regression in the `System.ServiceProcess.ServiceController`  NuGet package itself), therefore their update was deferred in PR 9888

# Steps to reproduce

Update the `System.ServiceProcess.ServiceController` NuGet package to `4.6.0-preview6.19303.8`

# Expected behavior

All tests pass.

# Actual behavior

There are 2 failures on Windows:

- Set/New/Remove-Service cmdlet tests.Set-Service can accept a ServiceController as positional input:
```
Expected strings to be the same, but they were different.
String lengths are both 14.
Strings differ at index 0.
Expected: 'newdisplayname'
But was:  'testsetservice'
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Management\Set-Service.Tests.ps1: line 321
321:             $service.DisplayName | Should -BeExactly $newdisplayname
```
It is worthwhile noting that the first Windows service test throws an `ObjectDisposedException` before it fails:
```
		Set-Service : Cannot access a disposed object.
Object name: 'ServiceController'.
At C:\Users\cberg\git\PowerShell\test\powershell\Modules\Microsoft.PowerShell.Management\Set-Service.Tests.ps1:318 char:25
+ ...       $script = { Set-Service $service -DisplayName $newdisplayname }
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (:) [Set-Service], ObjectDisposedException
+ FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.SetServiceCommand
```
![image](https://user-images.githubusercontent.com/9250262/59588305-31da2f00-90df-11e9-952d-be655ff6deae.png)

- Get-WinEvent.Get-WinEvent can retrieve events.Get-WinEvent can use the simplest of filters
```
Cannot convert argument "value", with value: "System.Diagnostics.Eventing.Reader.EventLogRecord", for "TryAdd" to type "System.Diagnostics.Eventing.Reader.EventLogRecord": "Cannot convert the "System.Diagnostics.Eventing.Reader.EventLogRecord" value of type "System.Diagnostics.Eventing.Reader.EventLogRecord" to type "System.Diagnostics.Eventing.Reader.EventLogRecord"."
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Diagnostics\Get-WinEvent.Tests.ps1: line 61
61:                 $testEventDict.TryAdd($te.Id, $te)
```

# Environment data

Windows

**Comment by iSazonov** [comment]
I looked at history of the source code and I don't see any changes. I guess root of the issue in another place. New-Service disposes the object before write to pipeline. Perhaps GC was updated in Preview6.

**Comment by daxian-dbw** [comment]
For the first failure, it's caused by [this line](https://github.com/dotnet/corefx/blame/master/src/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs#L482), which was added by https://github.com/dotnet/corefx/pull/32072 in .NET Core 3.0.
Simply put it, before .NET Core 3, `ServiceController.ServiceName` returns a string even if the object has been disposed. In .NET Core 3, the call to `GetDataBaseHandleWithConnectAccess` causes it to throw `ObjectDisposedException` when the object has been disposed.
This looks like a change by design, and we just need to update our test.

For the second failure, it's more problematic. The new NuGet package [System.Diagnostics.EventLog](https://www.nuget.org/packages/System.Diagnostics.EventLog/4.6.0-preview7.19362.9) includes a new more namespaces than the `4.5.0` version, including `System.Diagnostics.Eventing.Reader`, which has `EventLogRecord` type. However, our `Microsoft.PowerShell.CoreCLR.Eventing.dll`, which contains the ported .NET code for `EventProvider` also contains that type. So there is a conflict now.

**Comment by iSazonov** [comment]
> This looks like a change by design, and we just need to update our test.

Why do we dispose only in one cmdlet?
https://github.com/PowerShell/PowerShell/blob/17fb524adb85566aa5cb6041db279905c2700e6d/src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs#L2276-L2281

**Comment by iSazonov** [comment]
> our Microsoft.PowerShell.CoreCLR.Eventing.dll, which contains the ported .NET code for EventProvider also contains that type. So there is a conflict now.

For reference https://github.com/Microsoft/referencesource/blob/master/System.Core/System/Diagnostics/Eventing/Reader/EventLogRecord.cs - at first look it is the same code as in PowerShell repo.

**Comment by daxian-dbw** [comment]
> Why do we dispose only in one cmdlet (New-Service)?

Good question. No idea why doing that. Seems wrong to me.

**Comment by iSazonov** [comment]
> Good question. No idea why doing that. Seems wrong to me.

Wrong that we dispose in New-Service?

**Comment by daxian-dbw** [comment]
Yes, it seems wrong to me that we dispose the `ServiceController` object in `New-Service`. I'm not sure if that's on purpose though ... See this is why we need good comment in code.
