### ISSUE TITLE
Microsoft.Powershell.SDK does not include "Microsoft.Powershell.ConsoleHost.dll" reference assembly

### ISSUE THREAD

**Issue by asrosent** [PowerShell/PowerShell#10179]
hey guys,

as par with #8121 , it seems like the Microsoft.Powershell.SDK nuget is missing the "Microsoft.Powershell.ConsoleHost.dll"reference assembly

Is this intended or should be fixed?

Thanks!

**Comment by BrucePay** [comment]
@asrosent The console host was never intended to be part of the API. It was expected that host implementers would implement _all_ of the host classes. That said, there are two aspects to the console host - the host itself and the set of services provided to the running script through `$PSHost`. The latter is definitely useful/reuseable by _other_ console hosts even if the former is not. (We never really expected anyone would write another console host. Clearly we were wrong :-)  Interestingly, there are Win32 things that work in the console host that do not work in the PowerShell API:
```powershell
 [powershell]::create().AddCommand("notepad").Invoke()
```
hangs where
```powershell
notepad
```
does not. In practice there is a complex bit of logic (I know it's complex because i wrote it.) that the console host uses on Windows to detect when a GUI process should automatically go into the background. It would be nice if that logic was projected into the API.

**Comment by SeeminglyScience** [comment]
> @asrosent The console host was never intended to be part of the API.

What about `ConsoleShell`, `StartTranscriptCommand` and `StopTranscriptCommand`?

**Comment by BrucePay** [comment]
@SeeminglyScience 

Back at the BOT (beginning of time), the console host implementation was not intended to be part of the API. In fact `StartTranscriptCommand` and `StopTranscriptCommand` are officially not APIs as they derive from `PSCmdlet` not `Cmdlet`.  But things evolve. For myself, I would love to see more of the console functionality exposed through the APIs. Now wrt the Std API. I believe it only contains things that are universal. But i don't really remember all that clearly. @JamesWTruher should be able to answer more authoritatively.
