### ISSUE TITLE
Piping a module property to Get-Command which allows -Module ByProperytName doesn’t work

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#10191]
# Steps to reproduce

```powershell
Get-Module -ListAvailable -Name microsoft.* | 
    Select-Object -Property @{l='Module';e={$_.Name}} | 
    Get-Command
```

# Expected behavior

```none
> Get-Command -Module (Get-Module -ListAvailable -Name microsoft.* | Select-Object -ExpandProperty name)       

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Compress-Archive                                   1.2.3.0    Microsoft.PowerShell.Archive
Function        Expand-Archive                                     1.2.3.0    Microsoft.PowerShell.Archive
Cmdlet          Add-Content                                        6.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Add-Member                                         6.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Add-Type                                           6.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Clear-Content                                      6.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Clear-Item                                         6.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Clear-ItemProperty                                 6.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Clear-Variable                                     6.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Compare-Object                                     6.1.0.0    Microsoft.PowerShell.Utility

```

# Actual behavior

```none
Get-Command : The term 'Microsoft.PowerShell.Archive' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:47
+ Get-Module -ListAvailable -Name microsoft.* | Get-Command
+                                               ~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Microsoft.PowerShell.Archive:String) [Get-Command], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand
 
Get-Command : The term 'Microsoft.PowerShell.Host' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:47
+ Get-Module -ListAvailable -Name microsoft.* | Get-Command
+                                               ~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Microsoft.PowerShell.Host:String) [Get-Command], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand
 

```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.2
PSEdition                      Core
GitCommitId                    7.0.0-preview.2
OS                             Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
# Addition Information

```
 get-help -parameter Module get-command                                                                       

-Module <string[]>
    
    Required?                    false
    Position?                    Named
    Accept pipeline input?       true (ByPropertyName)
    Parameter set name           (All)
    Aliases                      PSSnapin
    Dynamic?                     false
```

**Comment by TravisEz13** [comment]
verified this is the same in 6.2

**Comment by vexx32** [comment]
If I recall correctly, this is an issue that's been raised before. Essentially, the pipeline binder preferentially binds objects ByValue before it ever looks for ByPropertyName even when it sometimes doesn't make sense -- didn't @KirkMunro raise an issue like that for the breakpoint cmdlets recently?

**Comment by KirkMunro** [comment]
Yes, #10188, but that issue was about parameter binding prioritizing default parameter sets over being smart about what is piped into the command. This seems similar, but I'm out and about so I can't check right now.

**Comment by KirkMunro** [comment]
Just following up, this is very similar to #10188, but it's not exactly the same in my opinion. Here's why:

* The default parameter set in `Get-Command` is `CmdletSet`.
* The `Name` parameter in `Get-Command` accepts pipeline input by value and by property name, and belongs to the `AllCommandSet` parameter set (i.e. not the default one).
* The `Module` parameter in `Get-Command` accepts pipeline input by property name and is in all parameter sets.

When you invoke `@{Module = 'Microsoft.PowerShell.Utility'} | Get-Command` (a pithy equivalent of the example used in the OP), you're passing in a PSObject with only a `Module` property on it. Since `Module` is a parameter that accepts pipeline input by value on any parameter set, logic seems to indicate that PowerShell should bind it to that parameter, but it does not. Instead, I think the logic goes more like this in this particular case:

- since the parameter being piped into does not have any parameters in the invocation that can uniquely tie it to a specific parameter set, look at the pipeline input by itself and see if it can do something with the default parameter set
- while looking at the default parameter set, since the command accepts pipeline input by value into a string parameter, it just converts the input into string and doesn't look any further (this is the logic that I believe is flawed in this case)

Regardless, there is a risk of a breaking change here as well if any of this behavior is changed, whether the current implementation is illogical or not.
