### ISSUE TITLE
placement of sha256 checksums on releases page

### ISSUE THREAD

**Issue by ghost** [PowerShell/PowerShell#10209]
sha256 checksums are not in a properly formatted files(or a file).
this makes it difficult to use them.

---

<details>

<summary>in case more information is required</summary>

<p>
example file( https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/SHA256SUMS ) with proper formatting.

```
58405101948aff46d5261e0a4d3e8f98ea3dc5366a9ada881ebe921eafd5f737  debian-edu-10.0.0-amd64-netinst.iso
de14801ab29ea71e606ff516e87b1ca68499de21098f994778f77121ea41323d  debian-mac-10.0.0-amd64-netinst.iso
```

---

most recent affected releases:
https://github.com/PowerShell/PowerShell/tree/v7.0.0-preview.2
https://github.com/PowerShell/PowerShell/releases/tag/v6.2.2
https://github.com/PowerShell/PowerShell/releases/tag/v6.1.5

---

current workaround(incomplete, not preferred):
1. Scroll up or down till you find it. Select the checksums on releases page and click `Inspect Element` and the copy the contents of 

```HTML
<ul>...</ul>
```

2. Remove the useless text ...

note- its not preferred because most people don't expect this to be how a popular project to provide checksums.
</p>
</details>

**Comment by iSazonov** [comment]
@TravisEz13 Is it possible to put all checksums in a file?

**Comment by TravisEz13** [comment]
@snow8gaia Can you contribute a PowerShell script which takes a directory and uses Get-FileHash to generate the format you want?

**Comment by snow8gaia** [comment]
thanks for powershell. sorry, can't do that; change of plans.

<details>

<summary> this may not be the best place to start; **may not work** </summary>

<p>

for eg: directory is stored in $x and is known, `cd $x` and ->

```powershell
foreach ( $file in gci -File *.*  )
{ echo ( (Get-FileHash $file).Hash + '  ' + $file.name )  >> checksums.SHA256 }
```

use `gci -Path x` for a target directory x. works without echo.

the format is more due to what is easy to do with the checksum 
utilities in coreutils (https://www.gnu.org/software/coreutils/coreutils.html)
and Powershell has no alternative as of 26 Jul 2019.

---
links used -
https://askubuntu.com/questions/867246/sha1sum-of-files-in-a-directory 
especially
https://ss64.com/ps/foreach.html

has a dark theme -
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-filehash?view=powershell-6#examples

---

might not respond to any future events.

**Comment by vexx32** [comment]
Would we need a single file or multiple checksum files, one for each zipfile? 🤔

**Comment by TravisEz13** [comment]
I think a single file is adequate as the file has the filenames in it.

**Comment by vexx32** [comment]
If we assume we're doing something like the [md5sum](https://en.wikipedia.org/wiki/Md5sum) format we can fairly easily do this:

```powershell
$Path = "/folder/path"
$OutputPath = Join-Path $Path 'hashes.md5'
Get-ChildItem -Path $Path |
    Get-FileHash |
    ForEach-Object { "$($_.Hash) $($_.Path | Split-Path -Leaf)" } |
    Set-Content -Path $OutputPath
```

**Comment by TravisEz13** [comment]
This is what @snow8gaia  provided.  The syntax needs to be fixed, but we should use SHA256
```powershell
foreach ( $file in gci -File *.*  )
{ echo ( (Get-FileHash $file).Hash + '  ' + $file.name )  >> checksums.SHA256 }
```

**Comment by TravisEz13** [comment]
```powershell
$Path = "/folder/path"
$OutputPath = Join-Path $Path 'hashes.sha256’
Get-ChildItem -Path $Path |
    Get-FileHash -Algorithm SHA256 |
    ForEach-Object { "$($_.Hash) $($_.Path | Split-Path -Leaf)" } |
    Set-Content -Path $OutputPath
```

**Comment by annoying258** [comment]
>  we're doing something like the [md5sum](https://en.wikipedia.org/wiki/Md5sum) format we can fairly easily do

and it would **avoid any errors that are only there when** this https://github.com/PowerShell/PowerShell/issues/10209#issuecomment-515634742 is used.

well, the files would need to be verified with sha256sum on Linux distros and also on Windows. Its easy to get sha256sum on Windows using either->

scoop https://github.com/lukesampson/scoop/wiki/Example-Setup-Scripts
chocolatey https://chocolatey.org/packages?q=coreutils
git  https://gitforwindows.org/
https://www.msys2.org/
https://www.cygwin.com/

And Windows users do so because all projects only provide instructions to verify hashes using shasum or mdsum utilities. and they have become more popular due to WMF installation issues.

**Comment by annoying258** [comment]
>Would we need a single file or multiple checksum files, one for each zipfile?

well multiple files would be better as the user can just do 

`sha256sum -c file.SHA256` if they only need to verify one file. assuming they only need one file to install.

whereas for one single checksum file, they need to do
`sha256sum --ignore-missing -c file.SHA256`  to get a clean output instead of cluttered output that contains the string `OK` in it.

---

It would also be easier to manage multiple files in CI in case, there needs to be a rebuild of assets for one platform. As only the relevant file hashes will need to be updated.

Also, the builds could be only done for one platform at a time; if CI server is already at a certain %age of load. 

I think the multiple files approach would  certainly decouple the hashes, but maybe more complicated than just appending to one file. Until you consider that there maybe errors while verifying hashes due to formatting.

So overall, I prefer the multiple files approach. It is actually simpler. 

---

And choosing SHA256 is a good idea; it keeps useless discussions away.

**Comment by TravisEz13** [comment]
I think having one hash file per file would be confusing.  I don't think that is a viable option.  The format clearly supports multiple files in the hash file, so we can have one file with all the hashes.

**Comment by Chuxel** [comment]
Any update on this?  I am having to download arm64 for Debian because there's no apt package in the Microsoft pool.  There's no great way to verify automatically unless we parse html.

**Comment by TravisEz13** [comment]
I created https://github.com/PowerShell/PowerShell/pull/16147 to add the sha256 hashes.

**Comment by TravisEz13** [comment]
One difference, according to the file spec, we are supposed to add an `*` before the file name for binary files.

**Comment by TravisEz13** [comment]
Please provide feedback before the release of 7.2.  After the release of 7.2, we will only backport changes which are not breaking.

I only implemented sha256.  If you want to implement another hash format, you have the file location and can look at the final code (a bug was found during the release so look at the file in master not the PR), and implement another hash.

**Comment by Chuxel** [comment]
SHA256 is fine from my perspective!

**Comment by TravisEz13** [comment]
We are going to be required to provide this format for the contents of our packages.
Generating this should be simple as we will have a task to just generate this.
Imagine this for packages, how much more difficult would this be to use?

```json
{
    "Outputs": [
        {
            "Source": "/Accessibility.dll",
            "AzureArtifactsHash": "044D5A90000300000004000000FFFF0000B800000000000000400000000000000000",
            "Sha256Hash": "CF21AA06D52BE85EE2C995BC475E0A90E773AC59B9621D95A53C172FD98DB87F"
        },
        {
            "Source": "/api-ms-win-core-datetime-l1-1-0.dll",
            "AzureArtifactsHash": "044D5A90000300000004000000FFFF0000B800000000000000400000000000000000",
            "Sha256Hash": "913EAAA7997A6AEE53574CFFB83F9C9C1700B1D8B46744A5E12D76A1E53376FD"
        },
        {
            "Source": "/zh-Hant/WindowsFormsIntegration.resources.dll",
            "AzureArtifactsHash": "044D5A90000300000004000000FFFF0000B800000000000000400000000000000000",
            "Sha256Hash": "143F539D34A0653DF145CF3592AA64D60A05147F00ABAC14A6F43E2B59708EC1"
        }
    ],
    "CloudBuildId": "101010",
    "Repo": "https://github.com/powershell/powershell",
    "Branch": "doentexist",
    "CommitId": "6ee476e9c6d25f12257f5f97635c77b586bff314",
    "Version": "7.2.10",
    "Timestamp": 1633150231
}
```
