### ISSUE TITLE
XPath text() Function in SelectNode Returns First Text Node For Each Element Matched

### ISSUE THREAD

**Issue by bigboy-pdb-spam** [PowerShell/PowerShell#10222]
# Steps to reproduce

```powershell
$x = [xml]'<r><e>1</e>2</r>'
ForEach ($s In ('a','b')) {
    $x.DocumentElement.FirstChild.AppendChild($x.CreateTextNode($s)) | Out-Null
}
ForEach ($s In ('c','d')) {
    $x.DocumentElement.AppendChild($x.CreateTextNode($s)) | Out-Null
}
# Document is now: <r><e>1ab</e>2cd</r> (where 1,2,a,b,c, and d are separate text nodes)
$x.SelectNodes('//text()') | select value
```

# Expected behavior

```none
Value
-----
1
a
b
2
c
d
```

# Actual behavior

```none
Value
-----
1
2
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by HumanEquivalentUnit** [comment]
I can't comment on the expected XML behaviour, but `[xml]` is `[System.Xml.XmlDocument]` which is part of the .Net framework that PowerShell is built on, rather than being part of PowerShell itself.

That's in https://github.com/dotnet/corefx/ with the [SelectNodes() code starting somewhere here](https://github.com/dotnet/corefx/blob/a6f76f4f620cbe74821c6445af3f13e048361658/src/System.Private.Xml/src/System/Xml/Dom/XmlNode.cs#L68).

It's probably more appropriate to raise it as an issue there.

**Comment by bigboy-pdb-spam** [comment]
Thanks. I realized that I needed to [open the issue elsewhere](https://github.com/dotnet/corefx/issues/39831) after creating it. I didn't want to close this one until there was a response.
