### ISSUE TITLE
Debug-Job no longer works on parent jobs

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#10254]
I am not sure when this broke, but it works correctly on Windows PowerShell 5.1.  It may have been when removing workflows and workflow jobs.  Debugging single jobs still appears to work however.

# Steps to reproduce

```powershell
$ss = (nsn),(nsn),(nsn)
$job = Invoke-Command -Session $ss -ScriptBlock { 1..100 | foreach { sleep 1; "Output: $_" } } -asjob
$job | Debug-Job
```

# Expected behavior

```none
Break into the debugger and step through each running job as breakpoints hit, similar to debugging multiple threads in a traditional code debugger.
```

# Actual behavior

```none
Debugger break occurs in a single job, but stepping through the code doesn't work, and it is not possible to exit without breaking the console (prompt no longer works).
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by KirkMunro** [comment]
Thanks @iSazonov. I saw this when it was logged, and took a quick look then. It isn't apparent to me when this stopped working or what change broke it. Also, since Windows PowerShell is not open source, I unfortunately can't go read the old code and build/step through it to see how it used to work. I would like to see this fixed though, so may cycle back to it later if I have time to do so.

**Comment by iSazonov** [comment]
Did it work in 6.0 GA?
