### ISSUE TITLE
There's no reliable way to read and suppress terminal output

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#10327]
When dealing with VT terminals I need to be able to Read-Host from the terminal input, without waiting for {Enter}, and on Windows, we use `$Host.UI.RawUI.ReadKey("NoEcho")` for that, but it's failing elsewhere.

# Steps to reproduce

On Windows, the following allows me to read responses from the terminal (without having them show up):

```posh
function Read-Terminal {
[CmdletBinding()]
param([string]$EscSequence)
  $Host.UI.Write($EscSequence)
  -join $(while ($Host.UI.RawUI.KeyAvailable) { 
    $Host.UI.RawUi.ReadKey("NoEcho,IncludeKeyDown").Character
  })
} 
```

So for instance, the CSI code 6n causes the terminal to report the cursor location, and we can read our X, Y from the terminal like this:

```posh
$answer = Read-Terminal "`e[6n"
"Row {0}, Column {1}" -f @($answer -split ';' -replace '\D')
```

Will get something like:
```none
Row 29, Column 1"
```
# Actual behavior

But when I try to run the same code on linux (even in the WSL terminal) the `$Host.UI.RawUI` seems to echo no matter what I do, so the terminal's response is completely unsuppressable.

```none
PS /root> cls; $answer = Read-Terminal "`e[6n"
^[[1;1R
````

I would be remiss not to point out that in addition to this being unreadable, the escape sequence is being shown as ^[ instead of the expected `e

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Linux 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by oising** [comment]
Just for context, using the `read` built-in with bash (wsl or native linux), we'd use something like `read < <(echo -e -n "\e[6n"); echo "The reply is ${REPLY}"` 

(`REPLY` is the default token when you don't specify one in `read`)

**Comment by SeeminglyScience** [comment]
> But when I try to run the same code on linux (even in the WSL terminal) the $Host.UI.RawUI seems to echo no matter what I do, so the terminal's response is completely unsuppressable.

Before core 3.0, terminal input echo was always enabled on Unix, unless `ReadKey(intercept: true)` was running.  We had a similar issue in PowerShellEditorServices, so I stripped out the native code corefx uses to disable echo (and otherwise prep `termios`) and put it in the [UnixConsoleEcho](https://github.com/SeeminglyScience/UnixConsoleEcho) package.  That works, but I'd recommend just requiring PowerShell 7 instead, shipping native binaries isn't fun. Plus you have to be *very* careful about reverting, because it'll affect child processes.

Note that the problem isn't `$Host.UI.RawUI.ReadKey`, it's that `ReadKey` isn't running when input is pressed.  Since you're waiting until a key is available to read it, input will still be enabled at the time of the key press.

Also, can't text on *nix atm, but avoiding `KeyAvailable` should work:

```powershell
$Host.UI.Write("$([char]27)[6n")
$chars = while (($key = $Host.UI.RawUI.ReadKey('NoEcho, IncludeKeyDown')).Character -ne 'R') {
    $key.Character
}

$y, $x = -join $chars.Where($null, 'Skip', 2) -split ';'
```

**Comment by oising** [comment]
Nice workaround Patrick. Pity about needing to know about a terminating character. I suppose another alternative would be to make it timeout based, but spinning up threads while blocking on input causes hell on corefx on windows. I tried to make psreadline's argumentcompleters more robust by having them timeout some years ago but it was deadlock prone and flaky AF.

**Comment by SeeminglyScience** [comment]
> I suppose another alternative would be to make it timeout based, but spinning up threads while blocking on input causes hell on corefx on windows.

That has some fun side effects on unix too 😄  ([More info](https://github.com/PowerShell/PSReadLine/pull/626#issue-165255865))
