### ISSUE TITLE
Package 'PowerShell 6.2.2' has a package type 'DotnetTool' that is not supported by project 'myProject'.

### ISSUE THREAD

**Issue by johnykes** [PowerShell/PowerShell#10379]
Hi!
I have a recently created C# win forms application using .Net Framework 4.7.2.
When I try to install Powershell NuGet I get the following error 
"Package 'PowerShell 6.2.2' has a package type 'DotnetTool' that is not supported by project 'myProject'."

Nothing added to this project yet (no other NuGets, libraries, etc...)

**Comment by vexx32** [comment]
PowerShell 6.2.2 isn't supported under .NET Framework -- it's built, tested, and runs on .NET Core 2.x; you cannot use PowerShell versions 6.x and above with .NET Framework, to my understanding. 🙂

**Comment by rjmholt** [comment]
@johnykes the package you're linking to is the [PowerShell dotnet global tool](https://devblogs.microsoft.com/powershell/introducing-powershell-as-net-global-tool/), which isn't designed for use in projects -- it's a global tool for the `dotnet` CLI (unfortunately they require a NuGet package like this to consume).

If you're targeting only Windows PowerShell (version 5.1) you might be looking for https://www.nuget.org/packages/Microsoft.PowerShell.5.ReferenceAssemblies/. Otherwise, if you want your application to target PowerShell 7 as well, you should retarget your application to .NET Standard 2.0 and depend on https://www.nuget.org/packages/PowerShellStandard.Library/.

**Comment by johnykes** [comment]
I have another project c# win forms application using .NET Framework 4.6.1 and NuGet "PowerShell" by Nasim
![image](https://user-images.githubusercontent.com/48965850/63345150-c3be1c80-c35a-11e9-8612-d689cfa39152.png)
I can't find anymore this NuGet (by Nasim)

**Comment by johnykes** [comment]
But using https://www.nuget.org/packages/Microsoft.PowerShell.5.ReferenceAssemblies/
I can use powershell like in the stackoverflow example
https://stackoverflow.com/questions/19601043/how-do-i-run-powershell-command-in-windows-form-application

Thanks!
