### ISSUE TITLE
`[short]0xffff` should return -1, but it generates an error instead

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#10375]
cc: @vexx32 (I think you're the contributor who added short; otherwise, please ignore this cc)

The new `[short]` type accelerator is signed, but it does not convert to negative values like other signed type accelerators do.

# Steps to reproduce

```powershell
[int]0xffffffff # returns -1
[int]0xfffffffe # returns -2
[int]0xfffffffd # returns -3
[long]0xffffffffffffffff # returns -1
[long]0xfffffffffffffffe # returns -2
[long]0xfffffffffffffffd # returns -3
[short]0xffff # generates an error
[short]0xfffe # generates an error
[short]0xfffd # generates an error
```

# Expected behavior

```none
-1
-2
-3
-1
-2
-3
-1
-2
-3
```

# Actual behavior

```none
-1
-2
-3
-1
-2
-3
Cannot convert value "65535" to type "System.Int16". Error: "Value was either too large or too small for an Int16."
At line:7 char:1
+ [short]0xffff # generates an error
+ ~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvalidCastIConvertible

Cannot convert value "65534" to type "System.Int16". Error: "Value was either too large or too small for an Int16."
At line:8 char:1
+ [short]0xfffe # generates an error
+ ~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvalidCastIConvertible

Cannot convert value "65533" to type "System.Int16". Error: "Value was either too large or too small for an Int16."
At line:9 char:1
+ [short]0xfffd # generates an error
+ ~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvalidCastIConvertible
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.2
PSEdition                      Core
GitCommitId                    7.0.0-preview.2-76-g86461f3f35fe7ffe470377fd178c4a71bf1037da
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Not an error, this is (unfortunately) by design. Also, you mention *un*signed, but these are all the signed variants. 🙂 

Hexadecimal numerals are handled in the tokenizer before anything else. These numerals are all parsed and their value determined before the cast operation is even fully defined by the parser and compiler.

`0xFFFFFFFF` is always parsed as `-1`, regardless of context, when the hex sequence is entered as a bare string/numeral. However, the sign bit is only recognised at lengths of multiple 8. If we always recognise the upper bit as a sign bit, any number beginning with 0xA-0xF values will always be registered as negative, and any length of `0xFF` values will always be -1.

In short, only `0xFFFFFFFF` (8 digits) and `0xFFFFFFFFFFFFFFFF` (16 digits) are recognised as `-1`; all other values with an `0xF` bit treat it as numeric. This has been documented for the PS7 documentation. This is the same behaviour as Windows PowerShell if you attempt to cast to `[int16]`, the `[short]` accelerator isn't special.

--------

This was done due to the pre-existing behaviour from Windows PowerShell. There, it was more an accident of the way the numerals were parsed (each being parsed by either `int.Parse()` or `Int64.Parse()`), but the committee decision on my PRs was we should mimic existing behaviour.

My personal preference was leaning more towards consistent parsing of all values, either being:

1. Respect the sign bit _always_ for hex values, despite the inconvenience of always needing to prefix a leading zero (e..g, `0x0F`) in order to get any positive values from the hex syntax.
2. Never utilise a sign bit for hex values, and always assume they're unsigned (possibly with some additional suffix tag to indicate they want them parsed as signed).

Neither of the above was something the Committee wanted, but it was discussed at length in my PRs. 🙂 

----

The immediate solution is to simply parse the hex from string into `[short]` so that PowerShell's custom parsing doesn't affect it: `[short]'0xFFFF'`

I am open to discussing the logic of the parsing modes here if need be, but in general I think that neither of the alternatives I can think of is especially great. We could potentially add a case for each common type, so that the following values _all_ get `-1` treatement:

- `0xFF`
- `0xFFFF`
- `0xFFFFFFFF`
- `0xFFFFFFFFFFFFFFFF`

However, note that this would be _regardless_ of what you attempt to cast them to; these would always be parsed that way. I think this solution was also previously raised to the Committee during my PRs, but ultimately also rejected as it did not match up with Windows PowerShell behaviour.

**Comment by KirkMunro** [comment]
Meh, I like consistency, but I'm not going to invest energy in going against existing behaviour at this point. Thanks for the detailed explanation.
