### ISSUE TITLE
Double quotes inside subexpression

### ISSUE THREAD

**Issue by iSnackyCracky** [PowerShell/PowerShell#10413]
Using the String.Replace() Method inside a subexpression to remove (replace with "") parts of a string gives unexpected results.
For me, this looks related to #3039 and #4543 

# Steps to reproduce
```powershell
"foo $( "bar".replace("bar", "") )"
```

# Expected behavior

```none
foo 
```

# Actual behavior
In newer PS versions, the command doesn't even work, in older versions there are different error messages about missing ending characters (like '"' and ')')

# Environment data

```none
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
---
The line works though, if you replace the empty double quotes with single quotes, or add a third (or even fourth) double quote:
```powershell
C:\> "foo $( "bar".replace("bar", '') )" # single quotes
foo 
C:\> "foo $( "bar".replace("bar", """) )" # three double quotes
foo 
C:\> "foo $( "bar".replace("bar", """") )" # four double quotes
foo 
```

Side note: to replace the string with one doublequote (without escaping or putting it inside single quotes) you need 7 double quotes in your replace() call:
```powershell
C:\> "foo $( "bar".replace("bar", """"""") )" # seven double quotes
foo "
```

**Comment by chuanjiao10** [comment]
it is badly subexpression  ：
```
"foo $( "
+


bar
+


".replace("


+
bar

+
", "

+
") )"
```

**Comment by UberKluger** [comment]
Already commented about the cause of this in #10045 but comment here explains this observed behaviour (for those who like detailed explanations).

The problem appears to be that simple expandable strings are not treating an embedded subexpression as an independent syntactic context. Any pair of double quotes ("") anywhere within the string (even inside a subexpression) is assumed to represent an embedded singular double quote (") and is replaced, apparently ***BEFORE*** evaluating (or even parsing) the subexpression. This explains the observations. Demonstration follows (the replaced paired "s are highlighted between !!):
```
"foo $( "bar".replace("bar", !""!) )" # should be syntactically correct (ignoring the !s)
```
becomes
```
"foo $( "bar".replace("bar", ") )" # definitely not
```
and
```
"foo $( "bar".replace("bar", '') )" # single quotes so no substitutions

"foo $( "bar".replace("bar", !""!") )" # three double quotes
becomes -> "foo $( "bar".replace("bar", "") )" # looks better

"foo $( "bar".replace("bar", !""!!""!) )" # four double quotes
becomes -> "foo $( "bar".replace("bar", "") )" # ok
```
and the final example
```
"foo $( "bar".replace("bar", !""!!""!!""!") )" # seven double quotes
becomes -> "foo $( "bar".replace("bar", """") )"
# so when the subexpression is evaluated the replacement string is "!""!" i.e. a single "
```
This is supported by the fact that 8 quotes also works. All even numbers of quotes are equivalent to the preceding odd number since the last quote in the odd sequence remains unpaired and so is not substituted.

I hope that anyone reading this is now less confused about whatever problem they have that led them to this issue page. I would recommend looking also at #10045 since it deals with a slightly different issue with (apparently) the same root cause.
