### ISSUE TITLE
Compare-Object returns incorrect results

### ISSUE THREAD

**Issue by SQLvariant** [PowerShell/PowerShell#10459]
Compare-Object returns incorrect results

# Steps to reproduce
I have run through several permutations of the steps below, but no matter how I change things around, I keep getting the wrong results from the Compare-Object cmdlet. 
```powershell
Import-Module -Name MicrosoftPowerBIMgmt -MaximumVersion 1.0.613;
Get-Command -Module MicrosoftPowerBIMgmt* -CommandType Cmdlet | SELECT Name, Source |
Export-Excel Import-Excel C:\temp\PowerBI_Commands.xlsx -WorksheetName 1.0.613;
Remove-Module MicrosoftPowerBIMgmt*

Import-Module -Name MicrosoftPowerBIMgmt -MinimumVersion 1.0.726;
Get-Command -Module MicrosoftPowerBIMgmt* -CommandType Cmdlet | SELECT Name, Source |
Export-Excel Import-Excel C:\temp\PowerBI_Commands.xlsx -WorksheetName 1.0.726


$613Commands = Import-Excel C:\temp\PowerBI_Commands.xlsx -WorksheetName 1.0.613 | SELECT Name
$726Commands = Import-Excel C:\temp\PowerBI_Commands.xlsx -WorksheetName 1.0.726 | SELECT Name

$Diffs = Compare-Object -ReferenceObject $613Commands -DifferenceObject $726Commands -PassThru

$Diffs
```

# Expected behavior

```powershell
Export-PowerBIDataflow
Get-PowerBIDataflow
Get-PowerBIDataflowDatasource
Set-PowerBIDataset
Get-PowerBIWorkspaceMigrationStatus
```

# Actual behavior

```powershell
Name                             SideIndicator
----                             -------------
Set-PowerBICapacityEncryptionKey =>
Set-PowerBIDataset               =>
Set-PowerBITable                 =>
Set-PowerBIWorkspace             =>
Switch-PowerBIEncryptionKey      =>
```

# Environment data

I can repro this on both PSCore 6.2.2 & PSCore 7-Preview3

```powershell
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.3
PSEdition                      Core
GitCommitId                    7.0.0-preview.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Since you're using `Select-Object` and not `Select-Object -ExpandProperty`, you're comparing arrays of `[pscustomobject]` instances (that have a `.Name` property), not _strings_ (mere names).

You have two options:

* Use `Select-Object -ExpandProperty Name`

*  Add `-Property Name` to your `Compare-Object` call.

As for the specific symptom:

 `[pscustomobject]` instances _as a whole_ (which is what you did) currently _all compare the same_, irrespective of their specific structure:

```powershell
PS>  Compare-Object ([pscustomobject] @{ foo = 1 }) ([pscustomobject] @{ bar = 2 }
# no output, because the [pscustomobject] instances are considered equal
```

I have not verified this, but I think that it is a consequence of #6163 (`.ToString()` invoked on `[pscustomobject]` instances returns the _empty string_, and since all reference-type instances are compared by their `.ToString()` values, all `[pscustomobject]` instances compare the same).

**Comment by SQLvariant** [comment]
Excellent info @mklement0, thanks for the assist!  Looks like I have 3 options.  I added ` -Property Name` to my `Compare-Object` and it came back with the correct results.

```powershell
Compare-Object -ReferenceObject $613Commands -DifferenceObject $726Commands -PassThru -Property Name
```
