### ISSUE TITLE
PowerShell Core get-help online points to wrong version

### ISSUE THREAD

**Issue by towerbe** [PowerShell/PowerShell#10490]
When running the command

Get-Help <insert command name here>-online

from PSCore 6.2.2, it opens the web page for the Powershell **5.0** documentation for the command.  One would think this should open the version-specific version of the documentation.  Not only has this caused issues for me, but I've also had experience where Microsoft support personnel were quoting from the wrong version of documentation because they didn't realize what was happening.

**Comment by towerbe** [comment]
FYI, I just looked at PS7.  Same issue.

**Comment by vexx32** [comment]
Have you run the `Update-Help` command to ensure you have the latest copy of the help & forwarding links? 🙂

**Comment by towerbe** [comment]
I'd love to do that in PSCore 6.x, but considering that proxy doesn't work in 6.x and isn't going to be fixed (see https://github.com/PowerShell/PowerShell/issues/9495) I can't.  And yes I have in 7. Same issue.

Apologies in advance for the snarkiness.

**Comment by sdwheeler** [comment]
For PS v6, this should be fixed already. Just need to run `Update-Help -Force`.

**Comment by towerbe** [comment]
@sdwheeler, I was able to temporarily set the proxy for my PS v6 installation and force an update-help.  It is indeed fixed.  Thanks for that.  I did the same thing for PS v7, and it is now pointing at the  v6 online documentation instead of the v5 online documentation as before.

Progress.

**Comment by vexx32** [comment]
Correct me if I'm wrong here @sdwheeler but I don't think the PS7 help is live yet, is it? Are we waiting for PS7 release to push that to the public docs pages?

**Comment by sdwheeler** [comment]
PSv7 content has been published to the live website. It started with a copy of PSv6 content. Somecmdlet reference has been updated for PSv7 but only if a) the code PR for the change was merged in the PowerShell source repo, and b) somebody wrote the doc updates.

For PSv6 and PSv7, I created all new FWLinks to point to the correct online content. You have to download the latest help files to get those links. However, I don't think we are building and hosting updateable help CABs for PSv7 yet. So if you try `Update-Help` in PSv7 you probably get PSv6 content. Publishing PSv7 CABs will get turned on for the GA release.

I did not fix any FWLink problems for PS5.1 and below since we are not publishing updated CABs at this time. There several MS-internal technical and procedural issues we have to solve to publish new CABs for PS5.1 and below.

One way to get updated help for any version is to build the CAB files yourself from the markdown source using PlatyPS and then install them from a local folder. This would be similar to the `Save-Help`/`Update-Help` scenario.
