### ISSUE TITLE
Feature Request: add [Ordered] type accelerator

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#10513]
Add  `System.Collections.Specialized.OrderedDictionary` as  `Ordered` to the PowerShell type accelerators <sub>(not sure if this request is related or similar to: #9512)</sub>.

Currently the the`-is` operator returns an error for the `Ordered` type although I am able to use it in the constructor:

```PowerShell
$Ordered = [Ordered]@{a=1}
$Ordered -is [Ordered]

Unable to find type [Ordered].
At line:1 char:14
+ $Ordered -is [Ordered]
+              ~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Ordered:TypeName) [], RuntimeException
+ FullyQualifiedErrorId : TypeNotFound
```

As with e.g. the `semver` type, I would expect to be able to use the same type (accelerator) for comparison as for the constructor:

```PowerShell
$Semver = [semver]'1.2.3'
$Semver -is [semver]
True
```

**Comment by daxian-dbw** [comment]
Link to another Engine WG discussion conclusion regarding a similar issue about `[ordered]`: https://github.com/PowerShell/PowerShell/issues/17308#issuecomment-1125459917. We agreed to make `[ordered]` a true type accelerator there.

**Comment by vexx32** [comment]
WG-Engine discussed this today.

We agree that it makes sense to add a type accelerator here so that [ordered] can be used for `-is` comparisons and for directly constructing an OrderedDictionary with `[ordered]::new()`. This is a fairly straightforward change so we're happy to mark this as up for grabs.

Note that there is a parser check that prevents the usage of `[ordered]$a` for anything other than a hashtable literal (`[ordered]@{ a = 1 }`) which we agree should remain in place for the following reasons:

1. There is currently no usable direct casts to an OrderedDictionary that this code path could take
2. Casting a non-ordered Dictionary/hashtable type to OrderedDictionary is always going to result in the same unordered keys as can be gotten from the non-ordered Dictionary type anyway; going from an unordered type to an ordered type after the dictionary has been constructed does not make sense.

Given this, we think that simply adding a new type accelerator with no other changes makes sense here. It will enable the desired scenario and requires minimal changes.
