### ISSUE TITLE
unhandled nullreferenceexception when closing PowerShell 6.2.3

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#10579]
# Steps to reproduce

Open, but before the prompt appears, close the newly opened PowerShell console window.

![image](https://user-images.githubusercontent.com/26179051/65291831-a2e41500-db1a-11e9-9fba-a76726fe025b.png)

# Environment data

PowerShell 6.2.3
Windows 10 18980 Insiders
Posh-Git and a unreleased PSReadline are part of the user profile.

This very well could be some part of PSReadLine, not expecting to close before its even shown the prompt.

**Comment by msftrncs** [comment]
Just installed 7 preview 4, and was able to repeat the same thing.

![image](https://user-images.githubusercontent.com/26179051/65292025-5816cd00-db1b-11e9-93ff-629e3916ca65.png)

**Comment by iSazonov** [comment]
@msftrncs I download 7.0 Preview4 zip and do not see the problem.
 Could you please review your profile and find root of the issue? We need clear repo steps.

**Comment by SeeminglyScience** [comment]
Looks like a race condition where you need to close it between static field initialization and the first actual `PSConsoleReadLine.ReadLine` invocation.  I've seen it before, but it's very difficult to reproduce due to the timing required.

The cause is that the wait handle that `OnBreak` calls is created in [`DelayedOneTimeInitialize`](https://github.com/PowerShell/PSReadLine/blob/2e12332d58951a889bbdca742539041f7a85d303/PSReadLine/ReadLine.cs#L806) (which is only called on the first `ReadLine` call) and the break handler is set in [`PlatformWindows.OneTimeInit`](https://github.com/PowerShell/PSReadLine/blob/2e12332d58951a889bbdca742539041f7a85d303/PSReadLine/PlatformWindows.cs#L140) (which is ran when the singleton is created during static field initialization.

**Comment by msftrncs** [comment]
This is being tracked in https://github.com/PowerShell/PSReadLine/issues/1177, with a PR at https://github.com/PowerShell/PSReadLine/pull/1179.   I'll close this.
