### ISSUE TITLE
PowerShell preview Pinned Taskbar Icon is lost after upgrade

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#10589]
I am still experiencing an issue where the icon (not the shortcut itself) is lost on the shortcut pinned on the task bar when upgrading PowerShell 7 preview versions.   (side note, 6.2.3 still lost the entire shortcut when upgrading from 6.2.2)   I just upgraded from preview 3 to preview 4.

![image](https://user-images.githubusercontent.com/26179051/65366205-831a2300-dbe6-11e9-871a-4ec31fe7ee04.png)

Windows 10, Insiders build (currently 18980).

Reference #8918, #6088

**Comment by iSazonov** [comment]
@msftrncs Could you please also check 6.2.3 -> 7.0Preview4 upgrade?

**Comment by iSazonov** [comment]
I think we will need to test 6.2.3 -> 7.0 upgrade before release. /cc @SteveL-MSFT @TravisEz13

**Comment by TravisEz13** [comment]
Yes, this will occur due to how MSI works.  If this is a feature request that we actually support a real upgrade, I would suggest that we only do that with a different installer technology.

**Comment by msftrncs** [comment]
It would be nice  when upgrade from 6.x to final 7, that the user does not lose the shortcut/icon, but I don't expect that as much as I expect to upgrade minor versions without loss of shortcut/icon.

If the icon is going to be lost, and there is no real resolution to it (I think there is, a process should simply set the shortcut icon to the correct one instead of the MSI installer based icon, then when that shortcut is pinned it won't be using the installer icon), then keeping the shortcut around during the upgrade isn't that much use  … because now I have to unpin and repin the shortcut anyway.

**Comment by iSazonov** [comment]
A reference to the icon looks like `%SystemRoot%\Installer\{8BC1F0C3-BB77-46F7-BE0F-34A81E60509E}\PowerShellExe.ico`. Can we preserve the GUID? (The shortcut is in `C:\Users\username\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar` forlder)
Also we integrate the icon in exe file too. So the reference could be `%ProgramFiles%\PowerShell\7-preview\pwsh.exe`. In the case we can not upgrade from preview to release.

**Comment by TravisEz13** [comment]
This already occurs for non-previews, but we can make no such guarantees for previews builds without manually changes the guid often:
https://github.com/PowerShell/PowerShell/commit/f5fc0535ac8a04edd2cf3ed6d4b901d949f16f52

**Comment by bergmeister** [comment]
I've already fixed the problem with the shortcuts pinned to the task bar and in previews release of v7 it already works fine for me and other people (with the only small exception being the windows icon). I guess using an Insiders Windows build resets certain things during an upgrade which causes your problem.
Generally speaking, due to the default installation path changing between v6 and v7 shortcuts will need to be re-pinned anyway, remember guys: This is something external to the installation that is hard to manage and with WiX we are pretty much at the limit what is possible, MSIX should make things better.

**Comment by iSazonov** [comment]
Clear about 6 -> 7 but @msftrncs reports that issue is with 7Preview3 -> 7Preview4

**Comment by msftrncs** [comment]
@bergmeister, it is true, the shortcut remains.  Also, maybe I should be more careful to post that I am using Win 10 Insiders.  I do use two machines, and when the issue happens on both of them, its very likely I will be posting from the Insiders machine, and I do not consider needing to indicate that I have demonstrated the issue on multiple installations with different versions.

**Comment by msftrncs** [comment]
Evidently I accidently hit tab and space, closing my last comment and the issue …  :(

So if I understand this whole thing correctly, it boils down to a GUID, which is allowed to change for each preview build, but will not be for the final version (or stable build) and its updates.

**Comment by bergmeister** [comment]
@msftrncs The improvement has only gone into v7. The improvement means that for patch (and I also think minor or major) upgrades of the MSI, the shortcut will be preserved. In any situation where the default installation path changes like e.g. from v6 to v7, I'd expect to change the GUID by design because the shortcut will point to the old, wrong location anyway. In a nutshell: The first upgrade from v6 to v7 will require a re-pin but any further minor or patch updates to v7 will not suffer from this problem.

**Comment by SteveL-MSFT** [comment]
I didn't observe this from PS7 P3->P4.  As @bergmeister noted, this fix was not backported to PSCore6.x
