### ISSUE TITLE
Resolve file paths before passing to native commands

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#10675]
# Summary of the new feature/enhancement

On Windows, the `~` is only understood by PowerShell.  So if you try: `notepad ~\foo.txt`, it complains it can't find the file path.  On Windows and non-Windows PSDrives have no meaning outside of PowerShell, so you can't do something like `pico temp:/temp.txt` with expectation that you're creating a file in the temp drive.

# Proposed technical implementation details (optional)

The problem is determining if the file path should be resolved or if it's a literal string being passed to the native command.  In most cases, it would seem that resolving the path would be fine.  Literal strings can have quotes around them making it explicit.

**Comment by mklement0** [comment]
Resolving PSDrive-based paths to native filesystem paths on all platforms sounds like a nice enhancement.

Yes, on Unix quoting is already being used to distinguish between a (potential) filesystem path to be `~`-resolved _and globbed_ (unquoted) and a literal argument (quoted), a nod to POSIX-like shells.

However, the automatic globbing is probably not a good idea on Windows, where it is up to the target command to expand globs (wildcard expressions).

So that leaves us with the following - is that what you had in mind?

* All platforms:
  * Expand _unquoted_ (token-initial) `~` (as before, only if followed by a path separator or nothing at all)
  * Convert an _unquoted_ path that starts with a PS-only drive spec to a native filesystem path

* Unix-like platforms only:

  * Perform globbing (expansion to individual filename arguments based on wildcard patterns) on _unquoted_ paths.
