### ISSUE TITLE
Feature Request: In the installer, tell me which app is hosting PowerShell process which is open

### ISSUE THREAD

**Issue by SQLvariant** [PowerShell/PowerShell#10744]
When installing PowerShell Core on Windows, there is a screen that stops you if it detects pwsh running.  The problem is that it doesn't tell you which app/program is hosting that pwsh process.  It could be the new Windows Terminal, VS Code, Azure Data Studio, heck even SQL Server / SQL Agent could have kicked off a pwsh process.  Please give me more info about what I need to close.

**Comment by bergmeister** [comment]
Sorry, this is MSI, i.e. the installation handler of Windows itself. There is nothing that this repo can do. This improvement needs to be made in Windows itself. You can either use SysInternals to find the process that you want to kill or otherwise just open an elevated Window PowerShell session and execute `Stop-Process pwsh`
