### ISSUE TITLE
difference between “foreach-object -inputobject $array” and ”$array | foreach-object“

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#10771]
difference between "-inputobject $array” and ”$array | foreach-object"

on manual：
```
$computerNames = 'computer1','computer2','computer3','computer4','computer5'
$job = ForEach-Object -ThrottleLimit 10 -InputObject $computerNames -TimeoutSeconds 1800 -AsJob -Parallel {
    Get-Logs -ComputerName $_
}
$logs = $job | Wait-Job | Receive-Job
```

Steps to reproduce
------------------

```
$a = 1..100
ForEach-Object -ThrottleLimit 4 -InputObject $a -Parallel {
	Write-Host $_
	Start-Sleep -Seconds 3
}
```

```
#normal
$a = 1..100
$a | ForEach-Object -ThrottleLimit 4  -Parallel {
	Write-Host $_
	Start-Sleep -Seconds 3
}
```

Expected behavior
-----------------
same

Actual behavior
---------------
#-InputObject problem
difference between up two scriptblock

Environment data
----------------
centos76 + ps v7.0 preview4

reporter
----------------
By the chinese powershell study & research group. QQ group No. is 183173532

**Comment by iSazonov** [comment]
@chuanjiao10 Can you share results and/or screenshots?

**Comment by chuanjiao10** [comment]
problem:
![a](https://user-images.githubusercontent.com/8968667/66693980-897d5580-ece1-11e9-9fe4-e139dba7654b.gif)

normal:
![b](https://user-images.githubusercontent.com/8968667/66693981-913cfa00-ece1-11e9-8a6d-810e7f097d99.gif)

**Comment by vexx32** [comment]
This has been raised as an issue at least a few times before. I believe in all previous cases the conclusion from the PS team is that this is by design; `InputObject` is not typed as an array parameter, and is designed to be used with the pipeline; passing values directly to it is not always (or even often) supported.

I don't have the existing issue numbers to hand, but I do recall @mklement0 may have been the author of at least one of the previous issues around this behaviour.

For clarity, this is an issue of _design_ that is shared by most if not all of the cmdlets shipped in PowerShell.

**Comment by chuanjiao10** [comment]
> For clarity, this is an issue of design that is shared by most if not all of the cmdlets shipped in PowerShell. It is not specific to ForEach-Object.

agree

**Comment by mklement0** [comment]
Thanks, @vexx32 - see  #4242
