### ISSUE TITLE
Modern coloring design

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#10780]
# Summary of the new feature/enhancement

We have started to add coloring (Select-String, error ConciseView, ...) without a general design.

Coloring is very sensitive area for our eyes. MSFT has accessibility team so that we maintain our health and work with great looking Windows and Office. Today they can do little here because here is no flexibility and tools.

Direction for discussion:
- We need to support color schemas.
- We need to recognize terminals (features supported by terminals) in our conhost.
- We need to have cmdlets to manage coloring and color schemas.
- We need to have a generic support of coloring in engine/formatting subsystem.
- We need ...

# Proposed technical implementation details (optional)

The issue is for initial discussion. Then RFC is expected.

**Comment by rkeithhill** [comment]
Yeah, this color scheme for progress info is just ... bad (really poor contrast for reading):

![image](https://user-images.githubusercontent.com/5177512/66706941-b8ea8d00-ecf6-11e9-84c1-9eaa89e9d39a.png)

I'd prefer something with better contrast e.g.:

![image](https://user-images.githubusercontent.com/5177512/66706931-922c5680-ecf6-11e9-989e-b33694923b10.png)

**Comment by rkeithhill** [comment]
On a system with `SupportsVirtualTerminal` set to `$true`, I could consider **not** using one of the ConsoleColor indices because those can be configured for bad contrast and **many** (most?) folks do not know how to adjust these colors.  I would use a specific set of VT 256 colors for ProgressFore/BackgroundColor.  Actually, I would consider doing the same for all the PS colors (when the terminal supports it) and that is where we get into using color schemes.

**Comment by Jaykul** [comment]
see  #11890
