### ISSUE TITLE
Breaking API removal in #10338

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#10799]
https://github.com/PowerShell/PowerShell/pull/10338 removed the `ScriptDebugger.SetBreakpoints()` API, allowing .NET code to set breakpoints.

Although previous PowerShells didn't have a convenient way to create a breakpoint object, removing this API means there's no way to avoid reflection when setting a breakpoint in a PowerShell module targeting anything prior to PS 7.

This is an issue for PowerShellEditorServices, where good debugging APIs are already scarce. A break like this will crash PSES unexpectedly (since PSStandard doesn't pick it up) and the only fix is to use reflection to find the right call at runtime (nullifying the reason to use PSStandard).

**Comment by SteveL-MSFT** [comment]
@rjmholt can you submit a PR to bring back that public API?

**Comment by KirkMunro** [comment]
Sorry about that @rjmholt.

For reference if you don't have them already, here is [the related discussion](https://github.com/PowerShell/PowerShell/pull/10338#discussion_r313133585) and the [commit where that API was removed](https://github.com/PowerShell/PowerShell/pull/10338/commits/d32abedc0263b2b009691d6274672801f63a5d45).

Since we're putting this back, we should probably have it call the other APIs for setting breakpoints since they are connected through all of the debugger layers (local debugger, remote debugger, etc.).

**Comment by rjmholt** [comment]
> Sorry about that @rjmholt.

No need to be sorry. We ought to have tooling to check this.

> Since we're putting this back, we should probably have it call the other APIs for setting breakpoints since they are connected through all of the debugger layers (local debugger, remote debugger, etc.).

I agree, but those APIs don't take a Breakpoint object. If the caller is expecting their breakpoint to be the one registered in the debugger, with referential equality intact, that may mean we need to use a different call path.

**Comment by iSazonov** [comment]
Fixed in #10808
