### ISSUE TITLE
Change in behaviour of -Debug common parameter

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PowerShell#10873]
In PowerShell up to 5.1 `-Debug `set the debug preference to Inquire which allowed the code being run to drop into a nested prompt. 
In 6 and 7 it sets it to continue which makes` write-debug` similar to `write-verbose` . Inquire has to be set via` $debugActionPreference `

Further: "Inquire" offers a _suspend_ option (drop to nested prompt) which can't be set via `$debugActionPreference` and `$debugActionPreference` offers _break_ (drop to debugger) which can't be selected via the inquire prompt 

Are these by design ?  If so what's the logic of `-debug` printing messages but not providing access to debugging ?

**Comment by vexx32** [comment]
@KirkMunro can probably explain it much better than I'm able to, since he wrote all that lovely code. 😊

**Comment by rjmholt** [comment]
See https://github.com/PowerShell/PowerShell/pull/8195

**Comment by KirkMunro** [comment]
@jhoneill Good questions. Here are the answers in no particular order:

1. `ActionPreference.Suspend` was for workflows and workflows only. We don't have workflows anymore, ergo, no `ActionPreference.Suspend` support. We're still keeping the enumeration around, but it's reserved for future use at this time.

1. The `Suspend` option in the handling of `ActionPreference.Inquire` is different than `ActionPreference.Suspend`. In the context of the `Inquire` prompt, `Suspend` drops you into a nested prompt. Nested prompts offered a way to do some inspection in PowerShell in v1, before PowerShell had a debugger. When it comes to debugging, today they offer much less value than the built-in debugger support. See also #9755.

1. `ActionPreference.Debug` was always about outputting debug messages. In PowerShell v1, when we didn't have a debugger, it also provided a way to get into a nested prompt so that you could look around and troubleshoot some things. It was not an actual debugger though -- you would be in a nested prompt (different scope), and you couldn't step through code, look at the code you were debugging using a debugger command, etc.

    Given the very limited usefulness of entering a nested prompt vs actually debugging, we added `ActionPreference.Break` for those times when you want to break into a debugger and troubleshoot. This is what you should use if you want to enter the debugger and troubleshoot something.

    Further, since `Write-Debug` would result in interactive prompting, users who wanted to output messages in PowerShell that were not shown by default would always use `Write-Verbose`, but that's not a great model, and has resulted in too much messaging being pumped through the `Verbose` stream. `Verbose` messages are for extra messages that should help an end user figure out what is going wrong when something isn't working. `Debug` messages are for extra messages that should help a developer figure out exactly what is happening when something is going wrong with a script or command they authored that is being run on another system.

### To sum up:

|Feature|PowerShell 5.1|PowerShell 7+|
|--|--|--|
|`-Debug`|Output debug messages in an interactive prompt that would allow you to enter a nested prompt (but not actually a debugger) to troubleshoot|Output debug messages so that we can have to levels of extra output when necessary (one for `Verbose` and one for `Debug`)|
|`ActionPreference.Break`|N/A|Break into the debugger when a specific type of message is generated, the moment that message is generated (e.g. `-ErrorAction Break`)|

In both cases, `ActionPreference.Inquire` still exists, but is of questionable usefulness.

Other items related to this discussion that you may want to be aware of:

1. #10238 - this PR adds `-DebugAction`, `-DebugVariable`, `-VerboseAction`, `-VerboseVariable`, `-ProgressAction`, and `-ProgressVariable`. These common parameters bring consistency to the common parameter set for handling messages. Once this is merged, if you want something like the old `-Debug`/`ActionPreference.Inquire` behaviour, you could invoke a command with `-DebugAction Break`, which would enter the debugger any time a debug message was generated. You can do that now in the latest preview using `$DebugPreference = [S.M.A.ActionPreference]::Break` as well.

1. https://github.com/PowerShell/PowerShell-RFC/pull/219 - this RFC proposes adding `ScriptBlock` support to `-*Action` common parameters, and `$*Action` preference variables, so that what they do can be decided on at runtime based on the actual `*Record` or `Exception` that caused the `ScriptBlock` to be invoked.

**Comment by jhoneill** [comment]
Thanks all (esp @KirkMunro)  for the detail. I was checking something I'd written a while back and found the behaviour had changed. I rarely use write-debug for exactly the reasons given as a rationale for the change :-)  so I hadn't spotted it before.  
Initially I didn't think `-debug `as "super verbose" was a good idea, but having read the links above (Kirk again) it makes more sense than the other options. Inquire is of limited use, especially as it doesn't offer to drop into debug, only the nested prompt, and the number of times we need 
`<<message>> Stop or Continue ?` messages as part of debugging is small. 

The more I think about it the more its seems any problem here is that this change is so long overdue. I'm assuming other have grown used to something has worked, but quite poorly, so when it is made to work better, the change jars. Now I've read the docs, I think that's OK.  

3 observations   

- The error message when setting the preference to "suspend" in 6 and later could be better. 
- The message printed by write-debug only appears when execution returns from the debugger, it should really appear first. . 
- The debugger doesn't have the equivalent of "yes to all" in inquire, but as a work-round setting $debugpreference in the debugger sets it for the local scope, which is OK. 
  
But since the question is answered, and there is no bug so I'm going to close this issue.

**Comment by KirkMunro** [comment]
> * The error message when setting the preference to "suspend" in 6 and later could be better.

The current message is "The Suspend ActionPreference value is reserved for future use and is not supported at this time. For more information about preference variables, see the Help topic, "about_Preference_Variables." What do you think is missing from that message?

> * The message printed by write-debug only appears when execution returns from the debugger, it should really appear first. .

This is by design. PowerShell breaks into the debugger the moment the message is created so that you can look around at that point. Having it break into the debugger once the message is written to the host means unwinding the stack more and so you may lose some visibility on what was going on. That said, in addition to showing the breakpoint line, we could consider showing the message text or some details about the trigger object (which is just an `ErrorRecord`, `Exception`, `DebugRecord`, etc.) when we enter the debugger based on a message, so that users see the stream message that triggered the breakpoint.

> * The debugger doesn't have the equivalent of "yes to all" in inquire, but as a work-round setting $debugpreference in the debugger sets it for the local scope, which is OK.

You're right. There are things that could be done here. Continue without breaking on other Error/Debug/etc. messages, or making the `detach (d)` debugger command work for local script debugging as a way to tell PowerShell to disable the debugger until the current execution completes, running the command to completion without other breakpoints being triggered. I was already thinking I would add the latter at some point. The former may be useful as well.

**Comment by jhoneill** [comment]
> > * The error message when setting the preference to "suspend" in 6 and later could be better.
> 
> The current message is "The Suspend ActionPreference value is reserved for future use and is not supported at this time. For more information about preference variables, see the Help topic, "about_Preference_Variables."" What do you think is missing from that message?

It's not so much missing, it's a tautology (Reserved for the future means not supported _now_) and back to front, it is there for legacy reasons. "Suspend is no longer supported" or if it might return "Suspend is not supported in this version of PowerShell" is shorter and clearer.   
"At this time" is usually filler as well - it's technically wrong, it isn't a facet of the day on which you run it but the version - but leaves the question of _when_ will it be supported. 

> 
> > * The message printed by write-debug only appears when execution returns from the debugger, it should really appear first. .
> 
> This is by design.
> 
> PowerShell breaks into the debugger the moment the message is created so that you can look around at that point. Having it break into the debugger once the message is written to the host means unwinding the stack more and so you may lose some visibility on what was going on.
> 
> That said, in addition to showing the breakpoint line, we could consider showing the message text or some details about the trigger object (which is just an `ErrorRecord`, `Exception`, `DebugRecord`, etc.) when we enter the debugger based on a message, so that users see the stream message that triggered the breakpoint.

That would be ideal. If I have  
` if (something involving $x and $y) { Write-debug "X is now $x and Y is $Y"}` 
seeing the values which dropped me into the debugger is a plus :-)  

> > * The debugger doesn't have the equivalent of "yes to all" in inquire, but as a work-round setting $debugpreference in the debugger sets it for the local scope, which is OK.
> 
> You're right. There are more things that could be done here, such as:
> 
> * continue without breaking on other Error/Debug/etc. messages
> * making the `detach (d)` debugger command work for local script debugging as a way to tell PowerShell to disable the debugger until the current execution completes, running the command to completion without other breakpoints being triggered.
> 
> I was already thinking I would add the latter at some point. The former may be useful as well.

Agree.  The first thing I tried was detaching the debugger and it says no :-)

**Comment by KirkMunro** [comment]
There's one other thing I forgot to mention that I have planned. I wrote my `DebugPx` module with its `Enter-Debugger` command around the same time that the PowerShell Team wrote `Wait-Debugger`. One key feature that `Enter-Debugger` offered over `Wait-Debugger` is a `scriptblock` parameter that is used as a condition. It also has a string `-Message` parameter so that a specific message gets shown in the debugger when it enters a breakpoint based on a condition.

It is my intention to bring forward the functionality I've built-up in that module into PowerShell itself as native functionality. I've outlined that plan in #10448. I'd appreciate your thoughts on that plan as well @jhoneill, because I think between the functionality it provides, and with `scriptblock` support in `ActionPreference` parameters as described in https://github.com/PowerShell/PowerShell-RFC/pull/219, those would be better suited for the conditional debugging scenario you highlight in your edit above.
