### ISSUE TITLE
Powershell Core Preview 7.0.0-preview.5 null coalescing

### ISSUE THREAD

**Issue by mgoldshteyn** [PowerShell/PowerShell#10897]
A very simple/question issue regarding the new coalescing operator:

\# This parses properly and works as expected
`$MyVar ??= "if null set to this"`

This doesn't:
\# The two question marks become part of the variable name
`$MyVar??="if null set to this"`
\# The code is parsed as:  `${MyVar??} = "if null set to this"`

Why is a space before the first question mark absolutely necessary?

**Comment by rkeithhill** [comment]
Because, believe it or not, `?` are valid characters for a variable name.  So what you think doesn't work actually is parsed like this:
```
$MyVar?? = "if null set to this"
```
So, according to PowerShell, this works as expected.  

There's been a discussion about disallowing `?` in variable names in PS7 for this reason but the worry is breaking existing scripts that use `?` in variable names.
