### ISSUE TITLE
MSIX Preview package adds itself BEFORE the PATH variable of pwsh.exe therefore overriding it

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#10894]
cc @SteveL-MSFT 

# Steps to reproduce

Install MSIX v7 preview 5 from private preview in MS store. It appends its PATH variable BEFORE the already installed pwsh RTM installation, it should be AFTER it.
# Expected behavior

```pwsh
> where.exe pwsh
C:\Program Files\PowerShell\6\pwsh.exe
C:\Program Files\WindowsApps\Microsoft.PowerShellPreview_7.0.5.0_x64__8wekyb3d8bbwe\pwsh.exe
```

# Actual behavior

```pwsh
> where.exe pwsh
C:\Program Files\WindowsApps\Microsoft.PowerShellPreview_7.0.5.0_x64__8wekyb3d8bbwe\pwsh.exe
C:\Program Files\PowerShell\6\pwsh.exe
```

# Environment data

 MSIX v7 preview 5 from private preview in MS store.

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-Preview.5
PSEdition                      Core
GitCommitId                    7.0.0-Preview.5
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
There's nothing in the manifest manipulating PATH, this seems to be the behavior of AppX pkgs.  However, if I run `pwsh` from cmd, it still starts 6.2.3.

**Comment by bergmeister** [comment]
You're right it does work in `cmd.exe` but when I execute `pwsh -version` in PowerShell 6.2.3, then it returns `PowerShell 7.0.0-Preview.5`, which is a no-go. Somehow this does not happen in PowerShell 5.1

**Comment by kilasuit** [comment]
I don't get this in 6.2.3 or 5.1
however I get a nice random assortment as below

`5.1` returns `6.2.3` - expected
`6.2.3` returns `6.2.3`   - expected
`7p5 MSIX` returns `7.0.0.Preview.5` - expected
`7p5 MSI` returns `6.2.3`  - unexpected should return `7.0.0.preview.5` as should be on the

**Comment by Erquint** [comment]
The discussion of the reported issue gotten derailed into version reporting mismatch.  
Issue closed without solution.  
The originally-reported issue is still a major bug ages since.  

I've been suffering stubbornly through it and employing workarounds for years, but this must be fixed eventually.  
I could ditch the MSStore installation in favor of WinGet, but, as a matter of principle, if it's so fundamentally broken and nobody wants to fix it — it better be pulled off MSStore. And we know that's not gonna happen.  

```pwsh
PowerShell 7.6.5
PS C:\Windows\System32> [Environment]::GetEnvironmentVariable('Path','Machine') -match 'Microsoft.PowerShell_7.6.5.0_x64__8wekyb3d8bbwe'
False
PS C:\Windows\System32> [Environment]::GetEnvironmentVariable('Path','User') -match 'Microsoft.PowerShell_7.6.5.0_x64__8wekyb3d8bbwe'
False
PS C:\Windows\System32> Test-Path $PROFILE.AllUsersAllHosts
False
PS C:\Windows\System32> Test-Path $PROFILE.AllUsersCurrentHost
False
PS C:\Windows\System32> Test-Path $PROFILE.CurrentUserAllHosts
False
PS C:\Windows\System32> Test-Path $PROFILE.CurrentUserCurrentHost
True
PS C:\Windows\System32> cat $PROFILE.CurrentUserCurrentHost
. G:\Projects\ps1\Invert-CIDR-set.ps1
Set-Alias -Name incidr -Value Invoke-CIDRSetInversion
Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
PS C:\Windows\System32> $env:Path -split ';' | Select-Object -First 1
C:\Program Files\WindowsApps\Microsoft.PowerShell_7.6.5.0_x64__8wekyb3d8bbwe
PS C:\Windows\System32> where.exe pwsh
C:\Program Files\WindowsApps\Microsoft.PowerShell_7.6.5.0_x64__8wekyb3d8bbwe\pwsh.exe
C:\Users\Erquint\AppData\Local\Microsoft\WindowsApps\pwsh.exe
PS C:\Windows\System32> Get-Command pwsh | Format-Table -AutoSize

CommandType Name     Version Source
----------- ----     ------- ------
Application pwsh.exe 7.6.5.0 C:\Program Files\WindowsApps\Microsoft.PowerShell_7.6.5.0_x64__8wekyb3d8bbwe\pwsh.exe
```

Any child process inherits this environment.  
The protected AppX directory is inaccessible to children, since they do not inherit package identity.  
Children are unable to invoke `pwsh`, because the AppX directory injected earlier shadows the reparse point `%LocalAppData%\Microsoft\WindowsApps\pwsh.exe` in the MSStore link collection.  
Resolver happily grabs the first path without checking permissions.  
As the result, a common occurrence in programmatic automation, typically failing silently under the hood, is simply illustrated as follows…  

```cmd
Microsoft Windows [Version 10.0.19045.6456]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>pwsh
PowerShell 7.6.5
PS C:\Windows\System32> cmd
Microsoft Windows [Version 10.0.19045.6456]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\System32>pwsh
Failed to load [C:\Program Files\WindowsApps\Microsoft.PowerShell_7.6.5.0_x64__8wekyb3d8bbwe\hostfxr.dll], HRESULT: 0x80070005
The library hostfxr.dll was found, but loading it from C:\Program Files\WindowsApps\Microsoft.PowerShell_7.6.5.0_x64__8wekyb3d8bbwe\hostfxr.dll failed
```

I'm not sure, but this might also be why in particular it's impossible to use `pwsh` normally in Task Scheduler without wrapping it in `cmd /C`.  

I suggest either not injecting bogus ACL-inaccessible paths into the PATH envar or excluding them from inheritance.  

@SteveL-MSFT, I ask the issue is reopened or I may open a new one if that's preferred.
