### ISSUE TITLE
LICENSE file should not be named with a TXT extension

### ISSUE THREAD

**Issue by StEvUgnIn** [PowerShell/PowerShell#10904]
Could you remove the extension for a better suppport of the file reading inside Git Hub

**Comment by kilasuit** [comment]
Considering the license can still be read in GitHub easily enough I fail to see any need for a rename. 
Having a txt extension allows the license file to be shared with the repo and the packed up executable and be opened easily on varieties of operating systems.

**Comment by SteveL-MSFT** [comment]
Looks like GitHub does some additional rendering if it's just a LICENSE file, see https://github.com/PowerShell/PSReadLine/blob/master/LICENSE

However, the LICENSE.txt is actually included in the package so keeping .txt also makes sense.  Since Windows relies on extensions, that file will open, by default, in Notepad rather than being asked for the app to open it.

**Comment by iSazonov** [comment]
Can we close as external?
