### ISSUE TITLE
Couldn't download for network issue in China

### ISSUE THREAD

**Issue by chenyj796** [PowerShell/PowerShell#10901]
When I download the releases, it always report a network issue.

The actual address looks like https://github-production-release-asset-2e65be.s3.amazonaws.com/49609581/9c2c2f80-d567-11e9-9766-65a0a1635f77?X-A...

I guess this is caused by the amazonaws.com domain.
Is there any other approach to download the releases?

**Comment by SteveL-MSFT** [comment]
The Linux releases are available from https://packages.microsoft.com if you follow [these instructions](https://docs.microsoft.com/powershell/scripting/install/installing-powershell-core-on-linux).  macOS is also published to Homebrew.  Windows releases will eventually be published to the Microsoft Store (targeting Preview.6 for PS7).  Is it primarily Windows that you are having an issue since typically you would need to download it from our Releases page?

**Comment by chenyj796** [comment]
I need install it on Windows and Linux offline, so I hope it can be download like dotnet

**Comment by chuanjiao10** [comment]
one key install powershell for linux
https://github.com/chuanjiao10/kasini3000_agent_linux

for win
https://github.com/PowerShell/PowerShell/releases/download/v7.0.0-preview.5/PowerShell-7.0.0-preview.5-win-x64.msi

等一会重试，，Wait a moment, try again

**Comment by chuanjiao10** [comment]
https://github.com/aria2/aria2/releases/download/release-1.35.0/aria2-1.35.0-win-64bit-build1.zip

dl.ps1
```
param 
(
	[string]$url
)
Invoke-Expression "aria2c.exe  --split=9  --max-connection-per-server=9 --dir=d:\you_download_folder  --continue=true '$url'"
```

**Comment by chenyj796** [comment]
@chuanjiao10 The tool you provided is prefect. Thanks very much!
