### ISSUE TITLE
-bnot operator returns signed datatype when unsigned datatype is supplied.

### ISSUE THREAD

**Issue by BronsonMagnan** [PowerShell/PowerShell#11018]
# Steps to reproduce

```
$operand = [byte]0xFF
$result = -bnot $operand
$result
```

# Expected behavior

```
I would expect the return value to be 0x00

```

# Actual behavior

```
-256
```
Which when casts into a [byte] results in an error, because it is signed.

I would like to request an unsigned version of the bitwise operator, if this is in fact the expected behavior. I spoke with Tyler Leonhardt about this at Microsoft Ignite conference.

# Environment data

```
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
:thinking: yep, this should definitely preserve the input data type (as long as it is one of the integer data types; not sure what it would do if the data type is double, float, or decimal, though.

Also not sure if we should have provision for `[bigint]` here? A `-bnot` on bigint would be rather inherently unpredictable due to its arbitrary size.

**Comment by SeeminglyScience** [comment]
It's worth noting that C# behaves the same way ([SharpLab example](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQcDMACR2DC2A3utmbkgGy4As2AsgIYCWUAFAJTGnm9xIBONvU4cA3DzIBfSdllYK1APYAjAFYBTAMbAGnbml68AQgE9gG7CuwBebAAYAHgDNnEw0bJwA7NgB+Ku68MmhSQA)).

This behavior is defined by the EMCA spec, the `not` CIL opcode is defined to work with only operands valid in "Integer Operations" which only accepts `int`, `long` and `IntPtr` ([EMCA III.1.5 Table III.5](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf#page=329&zoom=100,0,742)).

Note: I'm not arguing for or against any proposed changes, just providing context.

**Comment by vexx32** [comment]
That seems kinda strange to me, especially since I would think one of the primary use cases for a binary NOT operator would be the lower integer types like byte and short.

**Comment by SeeminglyScience** [comment]
I can't find a source for this specific instance but typically the reason you see instructions defined for 32 bit integers but not smaller is due to processors being much better optimized to handle them.  So behind the scenes C# would probably have to promote the `byte` to 32bits anyway, this way it's obvious that that's being done.

The bigger problem is that there's no real way to do an unchecked explicit conversion between `int` and `byte` in PowerShell the same way you can in C#.  PowerShell uses the `IConvertible` interface methods, C# uses the `conv.u1` CIL instruction.  The latter more or less reinterprets the same bits as said type, instead of trying to convert/validate it.  So `(byte)(~(byte)0xff)` returns `0` where `[byte](-bnot ([byte]0xff))` throws because the *value* `-256` isn't valid for a `byte`.

**Comment by vexx32** [comment]
So a possible fix would be to check the input type and do an explicit cast in the `-bnot` operator itself back to the input type, I suppose? 🤔

**Comment by SeeminglyScience** [comment]
If it's determined to be something that has to change, yeah.  It'd be a bit of a pain to do that arbitrarily for all possible input types, but not impossible.  It would be a breaking change though, and would not exactly be expected behavior for C# folks (who would be the folks most likely to use one's complement).

Personally I'd rather see an easy way to do an unchecked explicit conversion.

**Comment by vexx32** [comment]
`$value -to [byte]` perhaps? A more "forceful" version of `-as`? 😁

**Comment by BronsonMagnan** [comment]
To clarify my use case, I am only working with [byte] and [uint16].  The behavior to me is strange because this method which uses -bnot works as expected:
```
[void]clearBit([byte]$position)  { $this.value = $this.value -band -bnot (0x01 -shl $position) }
```
as this is my current workaround for -bnot (these are class method snippets)
```
[void]not(){ 
        for ([byte]$i=0;$i -lt 8; $i++) { $this.toggleBit($i)}
    }
[void]toggleBit([byte]$position) { $this.value = ($this.value -bxor (0x01 -shl $position))    }
```

**Comment by BronsonMagnan** [comment]
Still a problem on :

```
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
