### ISSUE TITLE
PS 7 Preview 5 Windows MSIX x64 Install does not work

### ISSUE THREAD

**Issue by vwent** [PowerShell/PowerShell#11090]
# Steps to reproduce

1. Download PowerShell 7 Preview 5 MSIX Package for Windows x64
2. Execute it from Downloads Folder
3. Press "Install"
4. Get an error message 😐
![image](https://user-images.githubusercontent.com/57833880/68993482-e936c580-0878-11ea-8cec-a43fc00b80b5.png)

# Expected behavior

PowerShell 7 Preview 5 installs.

# Actual behavior

Get Error Message from MSIX installer before Installation starts.

# Environment data

Output of 
```
Get-ComputerInfo
```
[env.txt](https://github.com/PowerShell/PowerShell/files/3854192/env.txt)

**Comment by vexx32** [comment]
Currently the MSIX can only be installed via `Add-AppXPackage -Path $msixPath` - note that you must also have Developer Mode enabled in the Windows settings for it to allow the install. I don't recall that the exact issue with the MSIX was, but I think @SteveL-MSFT and team managed to sort it out for the next release, if I'm not mistaken? 🤔

**Comment by SteveL-MSFT** [comment]
@vexx32 talking to the AppX team, it seems that because our pkg requires unvirtualized resources (because it's a shell!), it won't allow installing by simply double clicking on the pkg.  Using `Add-AppXPackage` is required to install the msix pkg.  The msix is planned to be available in the MS App Store by Preview.6.  However, for anyone doing offline installs of the msix, they will still need to use `Add-AppXPackage`.

I'll submit a PR to update https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-6 with instructions for installing the MSIX.

**Comment by vwent** [comment]
@vexx32 @SteveL-MSFT Thanks guys for clarifying, awesome!
