### ISSUE TITLE
Feature Request Make power shell commands colorful

### ISSUE THREAD

**Issue by harshnagarkar** [PowerShell/PowerShell#11107]
# Summary 

By this feature, users get to see color in their command outputs such as git init.
A user should be able to set the colors using commands or script theme packs they have written.
An example can be to let all my file paths be shown with a green color.

# Proposed technical implementation details (optional)
I don't know much about the implementation, but I know you can color text in PowerShell for output now we have to come up with a user-friendly way to set the commands for certain types. Like 'ls' commands show directories in blue and files in red.

**Comment by rkeithhill** [comment]
Have a look at the `DirColors` module in the PowerShell Gallery.

**Comment by jhoneill** [comment]
On cmd or wsl git init doesn't output in color . In Powershell Git status (for example) works in colour. 

there are plenty of ways to add color. Most seem like a good idea only the to people implementing them at the time.  Because the console host does colour with escape sequences redirecting to a file or the clipboard doesn't give "clean" output but something "polluted" with escape sequences.  So for every person you please by making files a different color you've annoyed 2 others, one who actively wants monochrome (or at least no escape sequences) and one who doesn't mind color in principle but objects to the chosen color scheme.

**Comment by harshnagarkar** [comment]
@rkeithhill Got it.
@jhoneill  I get the point you are talking about. 
Guys lets say I want to build a color pack(a script people can download and install the theme in Powershell) How can I do so after. I get I have to probably look into modules like DirColors.
What all I need to know to make it work?

**Comment by jhoneill** [comment]
@harshnagarkar  - the thing to look at is format.xml files - in Windows PowerShell all the formatting is in those, in PowerShell core they are compiled into DLLs, so it isn't quite so easy to see them, but you can change the format to pretty much anything you want. That means if you have an accessibility issue, you can engineer your own to suit your needs. If you have strong aesthetic tastes you do something which pleases you. 
Generally things should be always be able to be overridden by those files.

**Comment by harshnagarkar** [comment]
Got it Will do. If I need help I will reopen this ticket.
Thanks, guys. @jhoneill @rkeithhill
