### ISSUE TITLE
Suppressing stderr output with 2>$null or redirecting it to a file causes stderr lines to be recorded in $Error

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#11133]
Closely related: #4002; see also: #4332

By design, stderr output from external programs is _not_ recorded in `$Error` by default.

Paradoxically, when you use `2>$null` in order to explicitly _suppress_ stderr output, it then _is_ recorded in `$Error`, which is obviously not the intent.

Note: It also happens when you redirect to an actual file.

# Steps to reproduce

```powershell
$Error.Clear()
# Call `whoami` with an invalid argument, which produces stderr output (all platforms)
whoami badarg 2>$null
$Error.Count | Should -Be 0
```

# Expected behavior

The test should succeed.

# Actual behavior

The test fails with something like:

```none
Expected 0, but got 1
```

That is, stderr output was unexpectedly recorded in `$Error`.

# Environment data

```none
PowerShell Core 7.0.0-preview.5
```

**Comment by iSazonov** [comment]
I think it is expected as -ErrorAction SilentlyContinue behavior.

**Comment by mklement0** [comment]
@iSazonov:

* Stderr output doesn't belong in PowerShell's error stream, because it cannot be assumed to represent _errors_ - that's why it prints straight to the host by default.

* Using `2>$null` should mean: _discard_ stderr output. That it would _then_ show up in `$Error` is certainly not the intent.

* That stderr output goes through the error stream with redirection `2>`  is also highly problematic with respect to suddenly being subject to `$ErrorActionPreference = 'Stop'` - see #4002.

Providing an easy way to collect stderr lines is the subject of #4332.

**Comment by BrucePay** [comment]
@mklement0 Logically standard error output belongs in PowerShell's output stream because because that's where executables write their errors. Unfortunately over the years more and more *NIX binaries use stderr for a bunch of things that have nothing to do with errors. This is annoying and unfortunate. PowerShell's output stream is strongly typed so whatever gets written into it has to get wrapped in an `ErrorRecord` unlike the subprocess pipe which is just an undifferentiated stream of bytes so you get very different behavior. (Wrapping the output into an error object is also important because that's how `Out-Default` demultiples the merged output stream.)

> That it would then show up in $Error is certainly not the intent.

It most certainly *is* the intent, specifically $error is intended to be an in-memory log of *all* the errors that occur during execution, suppressed or not. It's purpose, like any error log, is to allow forensic analysis of the execution.

> That stderr output goes through the error stream with redirection 2> is also highly problematic

I didn't understand this statement. WRT the linked issue, errors are either exceptions (terminating errors) or something written to the error stream (non-terminating errors.) `-ErrorAction Stop` changes a non-terminating error into a terminating error. Thus error action only applies to things being written to the error stream.. Consequently, if you redirect the error stream to the output stream, the error action preference no longer has any effect.

**Comment by mklement0** [comment]
@BrucePay:

> Unfortunately over the years more and more *NIX binaries use stderr for a bunch of things that have nothing to do with errors. This is annoying and unfortunate.

The root problem is that native programs only have _2_ output streams at their disposal: stdout and stderr.
This is an unfortunate limitation, which PowerShell - commendably - has overcome _in its own realm_.

Given this limitation, native programs have no choice but to write anything that isn't _data_ to stderr, lest they pollute the data output stream (stdout).
It is a longstanding practice that is the best approach within the confines of the stated limitation.

Because the presence of stderr output can therefore _not_ be assumed to represent error conditions, PowerShell's console host's default behavior is the right approach:

* print stderr lines to the host
* do not record stderr lines in `$Error`

_If needed_, stderr output can be targeted selectively with a `2>` redirection; currently, aside from `2>$null` discussed below, you can only redirect to a _file_; it would be nice to have an analog to `-ErrorVariable` for capturing stderr lines in a _variable_, which is what #4332 proposes.

----

> It most certainly _is_ the intent, specifically `$error` is intended to be an in-memory log of all the errors that occur during execution, suppressed or not.

As explained above, for good reasons that doesn't apply to _stderr_ output, which is passed through to the host.

That it would suddenly apply when you use `2>$null` to explicitly signal the intent to _discard_ stderr can't be anyone's intent, least of all the user's.

---

> Thus error action only applies to things being written to the error stream.. 

Not only should `2>$null` not touch the error stream at all, that a redirection designed to _discard_ the stream's output, would  - situationally, based on `$ErrorActionPreference` - trigger aborting execution as if it were _writing_ to the error stream is obviously the opposite of the user's intent.

Even with true error stream output from PowerShell commands `2>$null` is currently broken:

* Like `-ErrorAction SilentlyContinue` it still records the error in `$Error` (which I think is problematic - see below).

* Unlike `-ErrorAction SilentlyContinue` (or `-ErrorAction Ignore`), it unexpectedly throws a runspace-terminating error when `$ErrorActionPreference = 'Stop'` happens to be in effect:

```powershell
$ErrorActionPreference = 'Stop'

# OK: No error output, but $Error is still populated.
Get-Item /NoSuch -ErrorAction SilentlyContinue

# Kaboom! A runspace-terminating error occurs.
Get-Item /NoSuch 2>$null
```

Even if `2>$null` were made fully equivalent to `-ErrorAction SilentlyContinue`, it seems like the wrong way to go.

The syntax `2>$null` clearly suggests the intent to _discard_ the error stream's output (as its native cousins `2>/dev/null` and `2>NUL` do), and should therefore be the equivalent of `-ErrorAction Ignore`.

**Comment by mklement0** [comment]
Closed in favor of https://github.com/PowerShell/PowerShell/issues/3996#issuecomment-666495478
