### ISSUE TITLE
New-PPSession: This parameter set requires WSman

### ISSUE THREAD

**Issue by Zebzx** [PowerShell/PowerShell#11159]
Hey,

I have an issue running this command to link to my Office 365 exchange and needed some support in connecting.

PS /Users/ztariq> $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $Credentials -Authentication Basic –AllowRedirection                                           
New-PSSession : This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.
At line:1 char:12
+ $Session = New-PSSession -ConfigurationName Microsoft.Exchange -Conne ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (:) [New-PSSession], PSRemotingTransportException
+ FullyQualifiedErrorId : System.Management.Autom

Could someone help me?. I am running PSVersion 6.0.4 and am on Mojave 15.1 OSX.

Cheers,

Zeb

**Comment by iSazonov** [comment]
Please see https://github.com/PowerShell/PowerShell/issues/5561#issuecomment-429130271

**Comment by antonywm** [comment]
Hi this issue is still a problem for me. I followed #5561 which recommended using posh version 6.0.4 (I had 7.0.0 loaded) but I still get the error:

PS /Users/antony> $PSVersionTable                                                                                                   

Name                           Value                                                                                               
----                           -----                                                                                               
PSVersion                      6.0.4                                                                                               
PSEdition                      Core                                                                                                
GitCommitId                    v6.0.4                                                                                              
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jan 23 07:05:23 PST 2020; root:xnu-4570.71.69~1/R...
Platform                       Unix                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                             
PSRemotingProtocolVersion      2.3                                                                                                 
SerializationVersion           1.1.0.1                                                                                             
WSManStackVersion              3.0                                                                                                
PS /Users/antony> 
PS /Users/antony> 
PS /Users/antony> $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection                                                    
New-PSSession : This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.

**Comment by VonZubinski** [comment]
Temporary solution found here:
https://github.com/PowerShell/PowerShell/issues/5561#issuecomment-639101511
and here
https://github.com/PowerShell/PowerShell/issues/5561#issuecomment-592476131

**Comment by flowl** [comment]
How is downgrading openssl a solution to `no supported WSMan client library was found`?
If powershell needs "openssl" why don't you call it openssl, why do you invent "WSMan" ?
What is WSMan? Why does Microsoft invent its own terminology for stuff that has been arround universally for half a decade?

I don't see a solution in the linked comments.

**Comment by jkroepke** [comment]
> How is downgrading openssl a solution

Typical solution for deprecated libraries: https://github.com/PowerShell/PowerShell/issues/10600#issuecomment-610565488 

I'm going to use a docker images which contains all correct libraries instead downgrade something on my system.

```
docker run  \
  -v $HOME:$HOME \
  -v $HOME/.local/share/powershell/:/root/.local/share/powershell/  \
  -v $HOME/.cache/powershell/:/root/.cache/powershell/  \
  -it mcr.microsoft.com/azure-powershell pwsh
```

Just install the Exchange Online Module once, it will be persist on disk.

Additionally, you could raise a shell alias to call this:

```
alias pwsh="docker run -v $HOME:$HOME -v $HOME/.local/share/powershell/:/root/.local/share/powershell/ -v $HOME/.cache/powershell/:/root/.cache/powershell/ -it mcr.microsoft.com/azure-powershell pwsh"
```

**Comment by nippyin** [comment]
@jkroepke Do you have any suggestion for connecting to On-Prem Active directory as well? As you might be aware that we cannot run windows images on Mac in docker as runtime is only linux. any magic you can point towards?

**Comment by viniciusferrao** [comment]
For macOS 12.4 here is the solution:

Considering you already have Powershell installed do the following:

```
sudo pwsh
Install-Module -Name PSWSMan
Install-WSMan
```

After that you can properly issue `Connect-ExchangeOnline` for instance and it will work. Even if you have MFA enabled. A Safari window will open where you can authenticate.
