### ISSUE TITLE
SSH remoting with two hosts fails when prompting for credentials

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#11204]
# Steps to reproduce

```powershell
Invoke-Command –ScriptBlock {Get-Process } -HostName localhost,localhost
```

# Expected behavior

should prompt from pubkey password and run the command twice
```none

```

# Actual behavior

```none
Invoke-Command –ScriptBlock {Get-Process } -HostName localhost,localhost
Enter passphrase for key '/Users/aoe/.ssh/id_rsa': Enter passphrase for key '/User/aoe/.ssh/id_rsa': 
Enter passphrase for key '/Users/aoe/.ssh/id_rsa': 
Enter passphrase for key '/Users/aoe/.ssh/id_rsa': 
Enter passphrase for key '/Users/aoe/.ssh/id_rsa': 
Enter passphrase for key '/Users/aoe/.ssh/id_rsa': 
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by PaulHigin** [comment]
Password entry for multiple sessions is not currently supported, unfortunately.  The reason is that SSH client writes directly to the console/terminal to prompt for a password.  If multiple computer targets are specified, there is an SSH client session for each trying to prompt for a password at the same time.

A possible fix would be to force session connection to be performed sequentially rather than in parallel.  But this would be a performance hit for cases that don't require prompt (e.g., user keys).

Workarounds:
1. Use user keys for authentication and bypass password prompt.
2. Create remote session individually and pass already created sessions to Invoke-Command instead of computer names.
