### ISSUE TITLE
ConverTo-SecureString does not work when running under a standalone managed service account

### ISSUE THREAD

**Issue by mazhar10** [PowerShell/PowerShell#11218]
Standalone managed service accounts are defined at [https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/service-accounts](url)

This includes accounts that an app pool on IIS runs under by default.
If you have PS code that calls `ConverTo-SecureString`, you will see that this cmdlet always returns back an empty string. Running under other accounts, even localsystem etc., makes this cmdlet work fine.

In my case, after wasting hours in debugging, I set my app pool to run under localsystem instead of the default standalone managed account (which has the same name as the app pool itself), and everything started working fine.

**Comment by iSazonov** [comment]
Oh, it is not user friendly. I guess the API behavior is "by-design" (/cc @TravisEz13 ) but perhaps we could write a warning message if current account is MSA or gMSA.

**Comment by mazhar10** [comment]
Thanks iSazonov. Where can I find any documentation as to the reasoning behind why it is designed like this? Just for my curiosity.

**Comment by iSazonov** [comment]
I hope @TravisEz13 or @PaulHigin add more info what the fix could be.

**Comment by PaulHigin** [comment]
Security Working Group:
This is by design.  `ConvertTo-SecureString` uses Windows DP API, which does not work with GMSA accounts.

**Comment by iSazonov** [comment]
@PaulHigin Can (make sense?) we write an non-terminating error if the account is gMSA/MSA and being more user friendly?

**Comment by TravisEz13** [comment]
Does this parameter set work?
```
ConvertTo-SecureString
              [-String] <String>
              [[-SecureKey] <SecureString>]
```

> Can (make sense?) we write an non-terminating error if the account is gMSA/MSA and being more user friendly?

Making a failure cause an error makes sense to me.

**Comment by iSazonov** [comment]
We could use `NetQueryServiceAccount` API. Examples:
https://github.com/JamesTryand/pash-1/blob/70225c2e542036819f3f87585ea5e358d798f411/Modules/ActiveDirectory/Microsoft.ActiveDirectory.Management/Microsoft.ActiveDirectory/Management/Commands/TestADServiceAccount.cs#L27-L42
https://github.com/beatcracker/Powershell-Misc/blob/d0704cea3d1eb948f9720dc8826a630e86150c08/Use-ServiceAccount.ps1#L293-L294

Possible place for the fix https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Security/security/SecureStringCommands.cs#L302

**Comment by JAK1047** [comment]
For my automation at my work I exclusively use gMSAs to run all my Powershell tasks. Every now and then though you do need the script to call an actual account (for example connecting to VMWare), so in these situations I've always made the gMSA use ConvertTo-SecureString and ConvertFrom-SecureString to then saved the encrypted value in a location like an Azure Key Vault. Works fine and the result hash can only be decrypted by the gMSA that ran it on the server that ran it which leads me to think that's using DPAPI. Quick example of how I make my various gMSAs encrypt and save the password for later use since you can't directly run Powershell using them without a task.

```
$Command = @'
    $User = $(([Security.Principal.WindowsIdentity]::GetCurrent()).Name.Replace("$ENV:USERDOMAIN\",'') -replace '\$')
    #Connect to AZ to add password to Key Vault    
    Connect-AzAccount -Identity

    $Password = 'PasswordGoesHere'
    #Convert to secure string for ConvertFrom-SecureString to take advantage of DPAPI
    $SecurePassword = ConvertTo-SecureString -String $Password -AsPlainText -Force
    #Conversion
    $EncryptedPassword = ConvertFrom-SecureString -SecureString $SecurePassword
    #Convert hash back to a secure string because Set-AzKeyVaultSecret won't take a regular string
    $EncryptedSecurePassword = ConvertTo-SecureString -String $EncryptedPassword -AsPlainText -Force
    #Add to vault
    Set-AzKeyVaultSecret -VaultName 'Automation' -Name "Admin-$User" -SecretValue $EncryptedSecurePassword
'@

#Make a PS1 with the above script
$Command | Out-File -FilePath C:\Update.ps1

#Generate new task action
$Action = New-ScheduledTaskAction -Execute 'Pwsh.exe' -Argument '-File C:\Update.ps1'

$GMSAArray = 'ACEPKIGMSA$',     
'ACEWebGMSA$',     
'ACEADGMSA$',      
'ACEStreemGMSA$',    
'ACEO365GMSA$',    
'ACEExchangeGMSA$',
'ACEMiscGMSA$',    
'ACEAzureGMSA$',     
'ACECitrixGMSA$'  

#For all my gMSAs create the task and run it
Get-ADObject -ldapfilter '(&(name=*GMSA*))' -SearchBase 'OU=ACEGMSA,OU=GMSA,DC=contoso,DC=com' -Properties SamAccountName | ForEach-Object -Process {
    If ($_.SamAccountName -in $GMSAArray) {
        $Principal = New-ScheduledTaskPrincipal -UserID Contoso\$($_.SamAccountName) -LogonType Password

        $null = Register-ScheduledTask -TaskName 'Update GMSA' -Action $Action -Principal $Principal
        $null = Start-ScheduledTask -TaskName 'Update GMSA' 
        While ((Get-ScheduledTask -TaskName 'Update GMSA').State -ne 'Ready') { Start-Sleep -Seconds 1 }
        Unregister-ScheduledTask -TaskName 'Update GMSA' -Confirm:$False
  
        "Updating $($_.SamAccountName)"
    }
}

Remove-Item -Path C:\Update.ps1 -Force
```

Been working fine for me in both Powershell 5.1 and Pwsh 7.1. Does DPAPI work fine with a gMSA but not a MSA?

**Comment by iSazonov** [comment]
> save the password for later use

I wonder why do you want to save a password of MSA account.
You can create a scheduled PowerShell task and run it in scheduler with a gMSA account and you do not need to explicitly assign a password, since the system will do everything for you.

**Comment by JAK1047** [comment]
The password is not of the gMSA there's no way to retrieve a gMSA password. The passwords are for the various times I need other accounts where integrated authentication cannot be used such as with VMWare. In this case I encrypt the password for that other account in the manner above unique to the gMSA running the scheduled task then in whatever script itself when I need the password for the VMware account I can retrieve it.

I digress though the point is with PowerShell running under the context of a gMSA I'm fully able to use ConvertTo-SecureString and ConvertFrom-SecureString. It sound like though it shouldn't be able to work with DPAPI?

**Comment by iSazonov** [comment]
MSA is local only and I guess it has no password at all.
MSA is local only and it makes no sense to store a secret for them in Cloud (you can not use it on another system) - you can use local vault in your scenario. Perhaps you could benefit from https://github.com/PowerShell/SecretManagement for both local and Cloud scenarios.

**Comment by JAK1047** [comment]
Whether I store the passwords in a Key Vault, Registry, CyberArk, or even a text file doesn't matter we have no issues with our setup. I was just making a point to the focus of this issue that ConvertTo-SecureString was not working when run under the context of a gMSA, but I have several examples where it runs without any issue. If DPAPI really does not work when run under a gMSA I should be getting an empty string the same as mazhar10, but I cannot recreate that.

My goal was to say generating an error when ConvertTo-SecureString is run under a gMSA would be a breaking change for my company at least because it works as intended at the moment.

**Comment by mazhar10** [comment]
My testing was all under MSA, and not gMSA.
From what I understand, ConvertTo-SecureString uses DPAPI. Here is what I think PS should do:
1) if DPAPI is available, then invoke, return back whatever DPAPI returns, be it success or error etc.
2) if DPAPI is not available, then return back an error message.
This will take care of JAK's and my use cases, The issue I see if that (by design or not), PS is returning a success with an empty string when DPAPI is NOT available - this, to me, is wrong, as the invoker would not know what happened.

**Comment by JAK1047** [comment]
Makes sense to me. I'd like to try and get an affirmative if possible on whether DPAPI works for gMSA like we're seeing and fails to work on a MSA like mazhar saw just to rule out any outside factors, but seems the most likely case. I've done some searching and found other references particularly to using DPAPI that were are all for gMSAs.

So long as an error isn't forced in a situation where the cmd may work as intended that's all I want to avoid.

**Comment by iSazonov** [comment]
I found that DPAPI needs the user profile loaded to work but Task scheduler has a limitation and load user profile only partially. Perhaps the [workaround ](https://docs.microsoft.com/en-us/troubleshoot/windows-server/system-management-components/scheduled-tasks-reference-incorrect-user-profile) helps.

Also perhaps the scenario (I see it is very popular) with impersonating to sMSA/gMSA to protect a password could be addressed in https://github.com/PowerShell/SecretManagement

**Comment by JAK1047** [comment]
If there's an issue with it working with the task scheduler we haven't seen it because it's exclusively how we use the gMSA to run the scripts and DPAPI works fine. And in Mazhar's case where it didn't work they were using it in an IIS app pool. So most likely scenario is still a gMSA vs MSA difference,

The new SecretManagement only assists in the storage of secrets which doesn't seem to be a concern for anyway on this thread as far as I can see at least. The conversion of plain text to a secure encrypted format was the issue. In my opinion mazhar's last post summarizes things fairly well.

**Comment by iSazonov** [comment]
@JustinGrote could comment about possible implementation in https://github.com/PowerShell/SecretManagement too.

**Comment by JustinGrote** [comment]
Haven't seen anything specific to MSA or gMSA, but the issue as described here is ConvertTo-SecureString returning a null ('silently failing') rather than the expected "encrypted" string. Nothing about this is secretmanagement specific unless I"m missing something.

In a secretmanagement extension vault you occasionally convert plaintext from the "vault" to a securestring, so checks can be added there and throw errors, that will be extension vault specific however, because it's perfectly valid to return a null secret in some circumstances.

@iSazonov I don't think it's unreasonable to add a check to ConvertTo-SecureString if DPAPI is available, or if content *was* provided to convertto-securestring but it returned a null result for whatever reason, to throw a non-terminating error (or even warning). This might be considered a breaking change however because of implementations that may be "working" due to this silently failing that would now "break" even though they probably should have broken to begin with.

**Comment by iSazonov** [comment]
@JustinGrote My question is not about the cmdlets and DPAPI limitations. It is about implementation the scenario in SecretManagement module. (1) The scenario is used many users, (2) the users have to use a complex workaround with a script, task scheduler and impersonation to an MSA account. All this could be implemented in an SecretManagement cmdlet. What do you thing?

**Comment by JustinGrote** [comment]
@iSazonov I mean within secretmanagement's core there could theoretically be a Set-Secret -AsUser option that would impersonate to the user/gmsa/msa context, but honestly you could just psexec a powershell session and then run set-secret to do the same thing (this is what I typically do when configuring secretmanagement for secret accounts)

Secretmanagement uses a registry manifest in the user profile directly to direct to registered vaults, so if the user/service account doesn't have a profile, secretmanagement won't work.

I'd defer to @PaulHigin whether it's something he may want to put on the secretmanagement 2.0 roadmap. Agreed it's a very common scenario to want to configure a secret management vault for a service account or other noninteractive "runas" account so that it can retrieve required secrets, and currently the process is somewhat arduous at best and impossible at worst.

**Comment by JustinGrote** [comment]
It's also something that could exist as a wrapper to secretmanagement as a separate module if there was a way to virtually specify the manifest, or otherwise supply it to secretmanagement via a specific path, in the scenario of an account without a profile. With a profile it would mostly just be a matter of registering the vault within the context of the user which could be done simply by deploying the manifest file into the users profile without needing to run "as" the user.

As long as the service account can also authenticate and "unlock" the vault in the script using whatever means the vault extension requires. I've typically used Credential Manager to store this unlock credential if it isn't implicit to the login context (either managed service identity in azure, or the domain account credential context)

**Comment by iSazonov** [comment]
If @PaulHigin agrees then we could close the issue and continue in https://github.com/PowerShell/SecretManagement/issues/118

**Comment by iSazonov** [comment]
Main reason does not directly use  SecureString https://github.com/dotnet/designs/pull/147 - .Net team plans to obsolete the API and replace it with new modern API.

This absolutely convinces that the solution must be in PowerShell/SecretManagement#118
