### ISSUE TITLE
When calling cmd script, comma in string is not preserved 

### ISSUE THREAD

**Issue by jiasli** [PowerShell/PowerShell#11295]
# Steps to reproduce

Create a batch file `mybatch.cmd` containing:
```cmd
@echo off
echo %1
echo %2
```

In PowerShell call it with
```powershell
PS C:\Users\me> .\mybatch.cmd "a,b"
a
b
PS C:\Users\me> .\mybatch.cmd 'a,b'
a
b
PS C:\Users\me> .\mybatch.cmd --% "a,b"
"a,b"
ECHO is off.  # this is expected in cmd
PS C:\Users\me> .\mybatch.cmd --% 'a,b'
'a
b'            # this is expected in cmd
```

# Expected behavior

Comma inside the string should be preserved, like when calling it in cmd:

```cmd
mybatch.cmd "a,b"
"a,b"
ECHO is off.
```

# Actual behavior

Comma is parsed as [array](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-6#comma-operator-).

# Environment data

```none
$PSVersionTable 

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
It isn't PowerShell that parses the argument as an array, it is _cmd_ that interprets unquoted token `a,b` as _two_ arguments, because not only _spaces_ but also `,` and `;` can serve as argument separators.

PowerShell performs re-quoting as needed behind the scenes, and in the absence of _spaces_ inside arguments, it currently decides that enclosing the value in double quotes is _not_ necessary, so that both `.\mybatch.cmd "a,b"` and `.\mybatch.cmd 'a,b'` end up getting called as `.\mybatch.cmd a,b`, at which point cmd considers `a` and `b` separate arguments.

This re-quoting logic does not special-case calling `cmd.exe` or batch files, and is currently generally broken - see #1995 

**The workaround is to use _embedded_ double quoting**:

```powershell
.\mybatch.cmd '"a,b"'
.\mybatch.cmd "`"a,b`""
```

You can use the `iep` function defined [here](https://github.com/PowerShell/PowerShell/issues/1995#issuecomment-562334606) to automate this quoting  and to compensate for the other ways in which re-quoting is broken.

Note that the planned fix for #1995, detailed in [this RFC](https://github.com/PowerShell/PowerShell-RFC/pull/90), will _break_ the workaround (as it will break all other current workarounds) and - unless `cmd.exe` / batch-file calls are special-cased - would offer no alternative (other than the limited `--%` approach) - see [this comment](https://github.com/PowerShell/PowerShell-RFC/pull/90#issuecomment-552231174).
