### ISSUE TITLE
Support sudo <PowerShell cmdlet> 2

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#11343]
# Summary of the new feature/enhancement

Summarize #3232 to get working _in the same way on all platforms_:

`sudo Remove-Item foo.txt` where foo.txt is owned by root

[See also](https://github.com/PowerShell/PowerShell/issues/3232#issuecomment-565936036)

We have two common scenario for sudo - run a native command and run a script.

1. Run a native command
This can be easily implemented like:
```powersherll
Start-Process <nativecommand> -ArgumentList … -Credential $userCred -Wait
```
Side effect on Windows: new window will be opened because:
- Windows does not allow elevate current process
- Windows does not allow attach elevated process to current console
 [.Net Core](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.createnowindow?view=netframework-4.8#remarks) (and I guess Windows API too) doesn't allow to run new process attached to the same console.
So we can not get elevated `Start-Process pwsh -NoNewWindow -Credential $cred`

2. Run a script
2.1. We could implement this as for native command:
```powersherll
Start-Process pwsh -ArgumentList "-c","<scriptblockstring>" -Credential $userCred -Wait
```

2.2. We could implement this in most power way using PowerShell remoting:
```powersherll
Invoke-Command -ComputerName LocalHost -ScriptBlock <scriptblock> -Credential $userCred -ArgumentList ...
```

#### Current implementation proposal is 2.2.
Alternative proposal - [start another pwsh process](https://github.com/PowerShell/PowerShell/issues/3232#issuecomment-500506716)

#### Proposed name

- __pssudo__ to avoid a conflict with Unix native sudo.
- Invoke-AsUser

#### Proposed UX behavior

- interactively ask for credentials at first run
- store credentials for a time and doesn't ask in follow runs

It is still not clear:
- PowerShell remoting to localhost by default has disabled elevated accounts in WinRM loopback - how could we address this in the context sudo? Even if PowerShell remoting does not allow us to do sudo by default, we could implement it turned off by default or allow only for an interactive session.
- PS sudo implementation should works over any transport - WinRM and SSH. But again there is a question about elevation in loopback -  regardless of a protocol, security should remain at the same level, which implies that SSH loopback should behave the same as for WinRM taking in account how Windows internals work but currently SSH loopback works (with manual connection).

**Comment by iSazonov** [comment]
@SteveL-MSFT @joeyaiello My current conclusion is that we have only single way to implement cross-planform sudo - using PowerShell remoting like @anmenaga implemented Windows Compatibility.
We gathered a lot of information in #3232 and now MSFT team could have been brainstorming to make a conclusion.

**Comment by rjmholt** [comment]
This has been discussed on and off.

There are a few thoughts that I haven't seen in the other thread. Since that one is focused more on the UX, I'll do the dump on implementation here.

Basically because PowerShell runs everything except for native commands in-process, this is very tricky.

There are essentially two options, both with significant drawbacks.

1. `sudo` becomes an alias to a remote/subprocess invocation in PowerShell to an Administrator/root process, where it runs the given command and gives back the result. This works fine for native commands, but for cmdlets only gives back deserialised objects. It also means that to make things performant we basically need to set up a persistent remote root session to host those commands. The main drawback is then the deserialisation (`sudo` cmdlets work subtly differently from non-sudo), with the two other drawbacks of having to override `sudo` (makes sense, but not ideal) and having to manage the security boundary and lifetime of the administrator remote host.

2. PowerShell itself becomes a `setuid` command and `sudo` works in process as a builtin (again we must override the util), becoming an administrator process when a `sudo` command is run. The major drawbacks here are (1) being a `setuid` command makes PowerShell more dangerous and requires authentication to use in whatever scenario and (2) upgrading the entire process to root does not cater to the abstraction of runspaces or just any other threads.

Given the two options, I really don't like either of them, but certainly think (2) is the more flawed and should be excluded at the outset.

This is just a braindump off the top of my head, so feel free to share, expand on or poke holes in implementation ideas here.

**Comment by iSazonov** [comment]
@rjmholt If you continue your thinking you will finish on a kind (JEA?) of  "PowerShell remoting" as implementation like me.

1. We should have the same UX on all platforms.
- We can not use Process.Start() (or Start-Process) even for native commands because on Windows new windows will be opened.
2. We should run script blocks that assumes having PowerShell context
- We can not use single elevated process because we need to have per user/per session/per runspace/per scope powershell context

**Comment by rjmholt** [comment]
Yeah I think we agree that the best path would be an implementation using a kind of “remoting as security boundary” architecture.

The part I don’t like about it is the lifetime of the elevated session. If we spin a new one up every time, it could be terribly slow. If we keep one open indefinitely, it leaves open a large attack surface.

Anyway, @jameswtruher @paulhigin @stevel-msft might have thoughts here

**Comment by iSazonov** [comment]
> If we spin a new one up every time, it could be terribly slow.

Yes, it is the same as "ForEach -Parallel" - it is slow for inappropriate scenarios but works great for target scenarios.
I guess we get acceptable response time for interactive sessions (pwsh startup time is ~400 ms, with -NonInteractive it is less). For background, non-interactive scenarios I believe that using of pssudo is not right thing.

**Comment by rjmholt** [comment]
Sounds like we want `sudo` to be an entry point into a wider effort to allow offloading to and management of an elevated PowerShell worker process

**Comment by gerardog** [comment]
> Windows does not allow attach elevated process to current console
.Net Core (and I guess Windows API too) doesn't allow to run new process attached to the same console.
> So we can not get elevated Start-Process pwsh -NoNewWindow -Credential $cred

Sudo implementations in the wild resolve this by spawing a new hidden process, then using the AttachConsole Api to show the current process output to the caller. Check [Luke Sampson's sudo.ps1](https://github.com/lukesampson/psutils/blob/master/sudo.ps1) implementation. This doesnt work if you want to redirect StdIn/StdOut. So on my own implementation [gsudo](https://github.com/gerardog/gsudo) (windows-only) I did a workaround for this scenario capturing StdIn/Out/Err and streaming via RPC to the non-elevated instance (when redirected, as in 'gsudo dir > somefile'.

**Comment by SteveL-MSFT** [comment]
Looks like @gerardog is willing to contribute his code to a cmdlet in PowerShell (for Windows).  We should discuss the cmdlet design first.  I'm ok with a `pssudo` alias, but the cmdlet still needs a verb-noun and adding a new parameterset to `Start-Process` might not be the way to go.

**Comment by vexx32** [comment]
I'd go for something like `Invoke-ElevatedCommand` perhaps?

**Comment by gdoenlen** [comment]
Is there any thought of an additional common parameter to elevate a cmdlet instead of a specific cmdlet that does it?

**Comment by sba923** [comment]
The hidden elevated helper process should allow getting a close as possible to 'same UX on all platforms', shouldn't it?

**Comment by SteveL-MSFT** [comment]
We definitely want pipeline support and also between cmdlets and native tools to work as expected.  We could add a `-Elevated` type switch to `Invoke-Command` and have a wrapper `pssudo` function make use of that since PowerShell aliases are a bit limited today rather than having a separate cmdlet just for sudo-type operation.  We should also keep in mind that this should work on non-Windows as well where we would have to sudo the pwsh process and handle redirection.  The limitation of deserialized objects in the pipeline vs live objects is an acceptable limitation in my mind.

**Comment by iSazonov** [comment]
> The limitation of deserialized objects in the pipeline vs live objects is an acceptable limitation in my mind.

sudo scenario assumes executing "a whole job". So I guess the serialization may not be a problem because we must send/receive only data but not elevated methods .

Thinking about security I believe PSSudo implemented by remoting should allow only to connect to __local__ endpoint. (In the case we could use binary serialization for _data_)

**Comment by PaulHigin** [comment]
This looks very cool to me, but I am unclear as to what the design will be.  Will it be based on remoting or @gerardog spawning a new process?  Should we have an RFC to discuss?  I would prefer not using remoting since it adds overhead.  The serialization system can be used outside of remoting.

Also I don't like the idea of using Invoke-Command since it has so many parameter sets already.  I would prefer a new cmdlet like 'Invoke-AsElevated'.

I am more concerned than @SteveL-MSFT  about returning deserialized PSObjects, and I think it may trip up a lot of users, e.g.,

```powershell
psudo Get-Process "pwsh" | Foreach-Object { $_.Kill() }
```

**Comment by JamesWTruher** [comment]
I agree that this is very nice, but I'm trying to wrap my head around a cmdlet implementation. Would there be an issue with a cmdlet using dotnet core (rather than 4.7.1) due to the "can't attach to the console" notes above, or would that just dictate the specific implementation.

**Comment by iSazonov** [comment]
Perhaps we could find how implement "process fork" version on both platforms but it causes huge problems. 1. It is double work. 2. It is obviously impossible to get the same behavior on all platforms and as result 3. we will get many negative feedbacks (bug issues).

If we look .Net Core team experience they re-write some native code things on C# get same behavior on all platforms (ex., libcurl history).
I would like to avoid different implementations for each platformю

> I am more concerned than @SteveL-MSFT about returning deserialized PSObjects, and I think it may trip up a lot of users, e.g.,
> psudo Get-Process "pwsh" | Foreach-Object { $_.Kill() }

pssudo should accept a script block and execute it elevated.

**Comment by gerardog** [comment]
Yes, we need double implementations (unless the double code is moved to .Net Core):

On Unix/Linux
* using `sudo` means an interactive password text prompt will appear. (IMHO the preferred, standard Unix way). The user can still opt-in to configure `sudoers` for silent elevation.
* using `setuid` on a helper process would be an administrative nightmare: (configuration, controlling who can and can't use the `pssudo`, requiring root access during installation to set `setuid`...)

On Windows: 
* Correct me if I am wrong but elevation with user and password (no UAC popup) is not possible (shouldn't be, right, otherwise would be a UAC Bypass?), unless some change is done on WinRM/loopback, and I believe that is undesirable. (I would like to hear a word from Microsoft/PowerShell team about this). And then: Is it ok/desirable to just ask for user password on a console? 
* A simple `Start-Process -Verb RunAs` to launch the helper process will show one UAC pop-up. Given that Remote PS Sessions already can run as admin and (i think) we are targeting local system interactive sessions only, this looks acceptable to me.

That being said, starting the elevated session will be interactive (either text or UAC), so I wonder how people will be using elevation on scripts and handle the 'interactive step'. Probably providing an easy way to fail fast if the user refuses to elevate would be a good idea:  

`Start-PSElevatedSession -NonInteractive` --> Test if the elevated session is already available. Provides a way to throw 'This script requires admin privileges'.

I think Microsoft should update us here on a list of what is acceptable or not to do from a security **compliance** perspective. That is required to define the user experience specs first. The technical challenges should be addressed later (e.g. if we hypothetically can't launch an elevated process in the current console we can do a workaround to attach the non-elevated into the elevated one). This team can provably get help from other MS teams to find new ways to overcome those limitations.

**Comment by agowa338** [comment]
> Correct me if I am wrong but elevation with user and password (no UAC popup) is not possible (shouldn't be, right, otherwise would be a UAC Bypass?), unless some change is done on WinRM/loopback, and I believe that is undesirable. (I would like to hear a word from Microsoft/PowerShell team about this). And then: Is it ok/desirable to just ask for user password on a console?

I want to point you towards this:
https://github.com/PowerShell/PowerShell/issues/3232#issuecomment-565839733

KB4480116 introduced this limitation *only* for powershell, 3rd party libraries are not affected, therefore I'd say we should just undo that KB.

**Comment by PaulHigin** [comment]
I spent some time reading through the various links.  This is great investigatory work.  AFAIK there is no way to bypass UAC other than disabling it system wide, so for Windows this will have to be part of the experience.  

I don't immediately see a security issue with passing an elevated console through the un-elevated console, when it is the same user only elevated.  Only admin users can elevate.  I don't know about supporting a RunAs option, where alternate credentials would be passed in, and could be a security concern.  But in any case a full security review would have to be done on the final design.

At this point, I think an RFC document should be created that outlines the feature, user experience and different design approaches.

**Comment by SeeminglyScience** [comment]
> Only admin users can elevate. I don't know about supporting a RunAs option, where alternate credentials would be passed in, and could be a security concern.

Worth noting that UAC can prompt for credentials depending on how [UAC: Behavior of the elevation prompt for standard users](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/user-account-control-group-policy-and-registry-key-settings#user-account-control-behavior-of-the-elevation-prompt-for-standard-users) is configured.  It's pretty common to be configured as something other than "Automatically deny elevation requests".

**Comment by agowa338** [comment]
I don't see a problem by attaching an elevated command prompt to an non elevated one. Also the UAC is not a security feature. There are multiple ways to bypass it in a network. Even without credential delegation.
1. Do powershell remoting from A to B.
2. Create a scheduled task at B (you're full admin at B, even though you're invoker at A) that runs with Administrative rights and that connects back to A and performs your action...

Or simpler using a non standard winrm client to connect via loopback to it, as mentioned in one of the links I attached earlier.

Also another thing to consider: If there are two persons, one with a limited user account and the other with an administrative one, why should the 2nd person enter his credentials into a non trusted session of the first one? This is the only case where detaching the terminal really would change anything, but the 1st user could as well just intercept the keyboard using a hardware accessory.

_of topic: He has physical access and regarding Microsoft security concepts it is game over, he could even get System rights by just applying windows updates, even if bitlocker disk encryption is on, yes that vulnerability is publicly known and Microsoft refused to patch it..._

back to topic what are possible threads:
For the scenario where the user is compromised using e.g. (what is currently popular?) lets say Emoted, but it was not able to get system rights yet, what could it do? Right, it could connect to the command prompt running with the same user credentials in the same session. So if we attach the administrative one it could hijack the connection. *But* with that permissions if we spawn a new console/window it would just intercept the creation of that process and append some parameters to it so that the administrator is tricked into acknowledging it...

Now see how unix systems handle these threads:
Processes with user rights cannot initiate communication with the sudo process (except for stdin) which is only attached to the terminal. Therefore the administrator has to check *before* he grants access using his credentials that:
1. The sudo binary is not overwritten (or use full path)
2. The command that he wants to elevate is trustworthy.

What was uac designed for regarding enterprises?
From what I've read it was designed to help admins to "not shoot them selves into the food that easily", e.g. "del /S /Q C:\" in the search bar... Basically it provides a kind of "-WhatIf".
And regarding private and/or standalone computers?
It just inadvertently helps to obey good security habits of two separate user accounts for non administrative and administrative tasks. For the advantage of having separate contexts at all.

I'd be totally fine with the attach to unprivileged process solution, as it provides the same guarantee uac currently does, but also for comandline applications. Also it is a feature that could be made to be disableable, like uac.

But anyway, we do not need to start from scratch for the security part, there is already something similar that we can hook onto its called *UIAccess* *Applications*: https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-account-control-allow-uiaccess-applications-to-prompt-for-elevation-without-using-the-secure-desktop

**Comment by ecovio1** [comment]
UAC=entire admin therefore the system shell. (psExec !)
the whole point of **sudo on windows** is :        
                                                    (i.) must not require UAC/admin credentials in the first place. 
                                                    (ii.) must be specific commands based per non-admin user , not the entire admin shell.                                      
                                                   (iii.) must open in the current running non-admin shell.

it seems, Windows lets elevation with two basic ways.  
                                                             ➡**UAC**.
                                                             ➡getting help from **an already running elevated** **process/service**. (many people call it as UAC bypass, but IMO /by definition, it is not.)

**now , if we have to go through UAC , then what's the point of sudo ?** 

 getting help from **an already running elevated** **process/service** seem to be three ways :

(1.) "Injections with system components based" (needless to say dangerous)
(2.) "Loopback based" (which is unsecure in the first place) = WinRM or SSH. 
(3.) "Token Overwriting" based  on  an already running admin service(IPC) that elevates user processes on successful authentication.



finally, implementing some real sudo stuff (Caching  the users' tokens for a while/prompt timeout for example or sudoers file with commands).


this is the amount of knwledge so far public has given. the Rest is MSFT's hands.

**Comment by minecraftchest1** [comment]
Reading about UAC elevating the current shell, what about creating a new subshell, elevating that shell, running the specified command, then exiting that shell.

**Comment by agowa338** [comment]
@minecraftchest1 UAC doesn't allow you to pass input into the new shell. You could only spawn a new window. Or alternatively you would need to go through e.g. IPC to let both processes talk to each other. It's not as simple as "just spawning" another shell.

**Comment by minecraftchest1** [comment]
So no matter how it gets done, it will require a modification to windows to do it cleanly?



Sent from my T-Mobile 4G LTE Device

**Comment by agowa338** [comment]
@minecraftchest1 The cleanest implementation would be an addition to windows internals it self. It would provide the most standardized way of handling this especially because this is a core functionality that not only PowerShell is looking for.

But that said there are different ways to implement it.
1. The pipe based one I explained above.
2. Create a service that either runs with LocalSystem privileges or with an user having SeTcbPrivilege (Act as part of the operating system) and that service than could perform the call to GetTokenInformation/SetTokenInformation with TokenLinkedToken (or even full impersonation) on behalf of the actual application and therefore bypass UAC (the official way) and elevating the already running application/thread (after checking permissions of course).

**Comment by minecraftchest1** [comment]
I understand. I shared this with the ReactOS project to ask what they could do. I personally don't have the patience to do things like this.

**Comment by Akarinnnnn** [comment]
I perfer to open UAC popup on Windows personly, just like the installers.
In my envisage, `pssudo` have following design:
- Start an evaluated pwsh process by `sudo pwsh ...` or RunAs equalvent, and specify IPC channel, lifetime(if we have subsequent command to sudo), communication token(maybe not necessary), etc. on command line parameters. For example `sudo pwsh -SudoMode -SudoLifetime 5min -SudoToken 1234567890abcdef  -SudoIpcPipe pipename`
- Send variables and command to elevated instance through IPC channel, and receive result.
- Signal the elevated instance to exit, if subsequnt elevated commands are executed.

**Comment by gerardog** [comment]
Hi! just wanted to let you know that **`gsudo`** ships with an [**`Invoke-gsudo`**](https://gerardog.github.io/gsudo/docs/usage/powershell#invoke-gsudo-cmdlet) cmdlet to elevate like the `pssudo` proposal.

It runs a `ScriptBlock` on an elevated PS instance, so it is a different lexical scope: the `ScriptBlock` can't access your `$variables`, but you can use `$using:variable` to apply it´s serialized value. Pipeline inputs and outputs are automatically serialized and deserialized.

Example usage from the [docs](https://gerardog.github.io/gsudo/docs/usage/powershell#invoke-gsudo-cmdlet).

> ``` powershell
> # Accepts pipeline input.
> Get-process SpoolSv | Invoke-gsudo { Stop-Process -Force }
> 
> # Variable usage
> $folder = "C:\ProtectedFolder"
> Invoke-gsudo { Remove-Item $using:folder }
> 
> # The result is serialized (PSObject) with properties.
> (Invoke-gsudo { Get-ChildItem $using:folder }).LastWriteTime
> ```
> 

(The cmdlet is optional, you can still just prepend `gsudo` to [elevate a command string](https://gerardog.github.io/gsudo/docs/usage/powershell))

Sorry if I am spamming this thread. I thought that mentioning it here once was on-topic. My apologies if it's not.
I created [this discussion](gerardog/gsudo#139) at gsudo's repo for anyone interested in discussing the cmdlet design, usage, troubleshooting, etc.

**Comment by RokeJulianLockhart** [comment]
Apologies for the spam - commenting to prevent https://github.com/PowerShell/PowerShell/issues/3232#issuecomment-1836767812
