### ISSUE TITLE
Distribution Support Request

### ISSUE THREAD

**Issue by mvelezwhiteSBS** [PowerShell/PowerShell#11436]
The comment I'm leaving here is due to my not comprehending what the nature of this next GA release will be. As I read through all the release notes and the marketing hype, I can't find an answer to a pretty basic question. Hopefully, someone can enlighten me here. Is version 7 of PowerShell going to be a 'full' product (with IDE and all the GUI bells and whistles) or is this just going to be another 'core only' version. We've not had a new GUI since version 5. With all the announcements and talk about how great it's going to be, I thought that this upgrade would really be 'big'. I'd appreciate it immensely if someone could give me a final word on this. I feel like a complete and utter 'noob', but I really wanted to know. TIA and LLAP

**Comment by mvelezwhiteSBS** [comment]
The comment I'm leaving here is due to my not comprehending what the nature of this next GA release will be.  As I read through all the release notes and the marketing hype, I can't find an answer to a pretty basic question.  Hopefully, someone can enlighten me here.  Is version 7 of PowerShell going to be a 'full' product (with IDE and all the GUI bells and whistles) or is this just going to be another 'core only' version.  We've not had a new GUI since version 5.  With all the announcements and talk about how great it's going to be, I thought that this upgrade would really be 'big'.  I'd appreciate it immensely if someone could give me a final word on this.  I feel like a complete and utter 'noob', but I really wanted to know.  TIA and LLAP

**Comment by mvelezwhiteSBS** [comment]
The comment I'm leaving here is due to my not comprehending what the nature of this next GA release will be. As I read through all the release notes and the marketing hype, I can't find an answer to a pretty basic question. Hopefully, someone can enlighten me here. Is version 7 of PowerShell going to be a 'full' product (with IDE and all the GUI bells and whistles) or is this just going to be another 'core only' version. We've not had a new GUI since version 5. With all the announcements and talk about how great it's going to be, I thought that this upgrade would really be 'big'. I'd appreciate it immensely if someone could give me a final word on this. I feel like a complete and utter 'noob', but I really wanted to know. TIA and LLAP

**Comment by iSazonov** [comment]
PowerShell 7 (aka PowerShell Core) is new generation of PowerShell.
It works on Windows, MacOs and some Unix-s.
All new features will be added only to PowerShell Core, not to Windows PowerShell (it is frozen).

> We've not had a new GUI since version 5.

We had. VS Code has an extension with PowerShell Core support. It supports syntax highlighting, references, debugging and more https://github.com/PowerShell/PowerShellEditorServices.

In last year we get many modules being compatible with PowerShell Core from MSFT and community.   In next year I'd expect that most of popular modules will be ported to PowerShell Core if not jet.

**Comment by doctordns** [comment]
The question: "Is version 7 of PowerShell going to be a 'full' product (with IDE and all the GUI bells and whistles) or is this just going to be another 'core only' version." suggests you may not fully understand how PowerShell is going forward.

1. Windows PowerShell 5.1 and associated ISE are at end of life. They are feature complete and are only ever likely to be updated to fix bugs.
2. Going forward, PowerShell is PowerShell Core or in due course PowerShell 7. That code, as such, as no GUI - the GUI is VS Code.

So the next release will be a PowerShell Core update - if you want the GUI, then use VS Code.

I hope this is clear and you do not see my comments as markting.

**Comment by mvelezwhiteSBS** [comment]
Yes, that’s what I gathered from the other post.  I’ll give the VS Code option a try.  Thank you for adding some clarity to all of that.  When Ilya messaged me that “Windows PowerShell is frozen”, I pretty much knew that it meant “End of Life”.

Question:  I understand that VS Code is the ‘GUI’ now for PowerShell.  Does that also work in full Visual Studio?  If not, then I’m content with VS Code, but it would be pretty awesome if that works in full Visual Studio 2019 as well.  That could open up some really creative implementations.

Please let me know if you have a  chance and thank you again for the enlightenment.

LLAP 🖖,
Miguel
[cid:image001.jpg@01D5BC9B.A496B2B0]

**Comment by vexx32** [comment]
@mvelezwhiteSBS The PowerShell extension that is built and maintained by the PowerShell team themselves only works in VS Code at the present. I do not know if there are any plans to expand to Visual Studio, though I'm sure doing so would be most likely an entirely separate project.

However, I think there are some community-maintained extensions for Visual Studio that may work for you. 🙂

**Comment by mvelezwhiteSBS** [comment]
@vexx32  Many thanks for that info.  I’ll look into it today.

Miguel Velez-White
SBS
334-353-0760

**Comment by iSazonov** [comment]
All MSFT product teams plan to port to PowerShell Core but these plans is not public.

**Comment by jhoneill** [comment]
> 1. Windows PowerShell 5.1 and associated ISE are at end of life. They are feature complete and are only ever likely to be updated to fix bugs.

Up to a point. Windows PowerShell 5 is not being enhanced any further, much like CMD or VBScript. However the plan of record is that they will continue to ship in the box with windows and be supported (meaning bug fixes). Some clients will continue to use the version which comes in the box, rather than the version which needs to be downloaded.  

> 2. Going forward, PowerShell is PowerShell Core or in due course PowerShell 7. That code, as such, as no GUI - the GUI is VS Code.

The GUI editor / IDE of choice is indeed VS code. However the dropping of the word "core" is primarily because 7 is not the bare-bones thing which PowerShell Core 6 was. It can print. It can display windows forms, it has Out-Gridview and get-help -show Window. It's better at using 5 under the covers to provide functionality. So I think it sells 7 short to say it has no GUI - it might be a bit to marketing to call it "best of both" because it isn't 100%  It feels to me that 6 was only 80% and 7 is 99% but those numbers are feel, and totally unscientific.

**Comment by vexx32** [comment]
@jhoneill I could be wrong, but my understanding is that only security-critical bugs warrant fixing in Windows PowerShell. There are plenty of pretty annoying bugs in WinPS that will never be fixed, but are already resolved in pwsh. 🙂 

But yeah, I'd agree. 7 mightn't have a native IDE editor but it is decently capable where GUI is concerned, at least as much as Windows PowerShell was. And with things like GraphicalTools cropping up once in a while, it's even pretty good on Unix platforms there too. \o/

**Comment by jhoneill** [comment]
@vexx32  I think that is pretty much the _intent_. However with my ex-Microsoftie hat on I think the definition of "supported" hasn't changed, and means ultimately PSS can get a hotfix for a bug if it is needed. There are all sorts of dances done to say it can be worked around or isn't really a bug so a hotfix isn't needed.  And at this stage no-one should expect long standing bugs to be fixed. Windows PowerShell 5 is in the same place as CMD or VB script ... except of course CMD has had ansi support added, notepad has been updated for the first time since Windows 2000, and flight-sim is back from the dead.  But it would be a departure from the plan of record to do a Windows PowerShell 5.2

The newer .net core and the ability to support the same GUI things on windows which 5 supported means everything I care about works again. 6 was a necessary stepping stone, 7 is (I think) what people want and (I think) it will strengthen old friendships and make a whole pile of new ones. The ISE is still there when it is appropriate, but that's less and less often.

**Comment by vexx32** [comment]
From all that I've heard, a 5.2 is no longer in the plans (if indeed it ever was?), but that would be something that's really up to @SteveL-MSFT and the rest of the team. 🙂

**Comment by he852100** [comment]
The comment I'm leaving here is due to my not comprehending what the nature of this next GA release will be. As I read through all the release notes and the marketing hype, I can't find an answer to a pretty basic question. Hopefully, someone can enlighten me here. Is version 7 of PowerShell going to be a 'full' product (with IDE and all the GUI bells and whistles) or is this just going to be another 'core only' version. We've not had a new GUI since version 5. With all the announcements and talk about how great it's going to be, I thought that this upgrade would really be 'big'. I'd appreciate it immensely if someone could give me a final word on this. I feel like a complete and utter 'noob', but I really wanted to know. TIA and LLAP

yes,It should be called powershell core 1.1. ;)
