### ISSUE TITLE
ssh from powershell core to ESXi and type dcui

### ISSUE THREAD

**Issue by vinod-ps** [PowerShell/PowerShell#11451]
ssh from powershell to ESXi and type DCUI, It will not be able to display the DCUI console.
This works fine in putty.

# Steps to reproduce
SSH to an VMWare ESXi host from powershell (either windows or from PSCore) and after logging in, type the command "dcui", It should display the DCUI options/menu. 
This is working fine if we are using putty.exe .

```powershell

```

# Expected behavior

See the below screenshot for expected behavior:

![image](https://user-images.githubusercontent.com/20023949/71552523-c4f80800-2a24-11ea-8984-6fc5f05984ce.png)

```

# Actual behavior
Even though if we use PS Core,Windows powershell or in Windows terminal, the results are same as in the below screenshot.
 
![image](https://user-images.githubusercontent.com/20023949/71552559-844cbe80-2a25-11ea-8dd5-46b843f29f98.png)



```

# Environment data

```none

```

**Comment by jhoneill** [comment]
The screen shot hasn't appeared. Since you have windows terminal what happens if you do the same from CMD (in Windows terminal or otherwise) . putty is a terminal emulator rather than a command line host. .

**Comment by vinod-ps** [comment]
Please browse the below URL for the screenshot, not sure why it is not working in the above post.
https://user-images.githubusercontent.com/20023949/71552559-844cbe80-2a25-11ea-8dd5-46b843f29f98.png
https://user-images.githubusercontent.com/20023949/71552523-c4f80800-2a24-11ea-8984-6fc5f05984ce.png
I have tried this in command prompt and result is the same ie: its not working.

**Comment by jhoneill** [comment]
so is there anywhere that you can run ssh.exe and get the desired result. 
Or does it only work if you run a fully fledged terminal emulator ? Because it's not seeming to be a PowerShell problem.

**Comment by lucaberta** [comment]
@vinod-ps I have run into the exact same issue as you did, and it has nothing to do with PowerShell.

It's an issue with the terminal capabilities set by the Linux OS on which ESXi runs. There are few termcaps available in ESXi, and the environment negotiation of the SSH session fails in many cases.

I have been having the same issue on MacOS terminal, and also on Putty on Windows 10.

The following command makes things work fine:

`TERM=screen; dcui`

On terminals which support the Linux termcaps, this works better:

`TERM=linux; dcui`

Please note that in order to exit the DCUI instance you have to use CTRL-C.

Also, if there are no Function keys on your keyboard or they do not get sent from the terminal software, you can use ESC + 2 for F2.

Hope this helps.

Bye, Luca
