### ISSUE TITLE
its possible to include x option with all regexes by default

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11468]
its possible to include x option with all regexes by default

for example instead of:

`$r = [regex]'(\d{3})-[a-z]\1+'`

or

```
$r = [regex]@'
(x)
 (\d{3})
  -
 [a-z]
 \1+
'@
```

for more lisibility

`$r = [regex]'(\d{3}) - [a-z] \1+'`

or 

```
$r = [regex]@'
 (\d{3})
  -
 [a-z]
 \1+
'@
```

**Comment by jhoneill** [comment]
This would break any existing regex which used " " rather than \s which covers more characters
Although attractive for the -match / -replace operators it would lead people to write expressions which behave differently in different places. (e.g. PowerShell won't change the default behavior of the underlying .NET regex engine) 
It's generally accepted expressions ignore spaces only if (?x) is specified.

**Comment by SeeminglyScience** [comment]
> It's generally accepted expressions ignore spaces only if (?x) is specified.

You can even specify that inline:

```powershell
$r = [regex]'(?x)
    (x)
    (\d{3})
    \p{Zs}-\p{Zs}
    [a-z]
    \1+'

$r.Match('x123 - ax')
# Groups   : {0, 1, 2}
# Success  : True
# Name     : 0
# Captures : {0}
# Index    : 0
# Length   : 9
# Value    : x123 - ax
```

(Also use `(?xi)` instead for case insensitive)

**Comment by jhoneill** [comment]
@SeeminglyScience  that's what I meant. 
In some places the only option is put (?x) in the regex itself. 
In others (like the .net object) it is possible to specify single-line/multi-line case [insensitive] and ignore whitespace outside of the expression

**Comment by he852100** [comment]
@jhoneill jhoneill
So under what circumstances is built-in? Is there a strict law of logic?

If not, do i need to provide another option?

**Comment by jhoneill** [comment]
> So under what circumstances is built-in? Is there a strict law of logic?
> 
> If not, do need to provide another option.
The only option which is built in is -match and -replace are actually -iMatch and -iReplace. 
[regex]::match("a","A") does not match because .net regex is case-sensitive (like most other regex implementations -cMatch and -cReplace keep the case sensitive behaviour, and the i versions specify the case-insensitive options. Since equals and like are case insentive, replace and match follow the same principle. 

Now...  it would be possible to have (say) Smatch and Sreplace with are space insensitive, but these would also need C and I versions.  I'm not sure it is really necessary.  I think that if you learn to write regexes which are complicated enough to need to be split for readability, then you probably pickup how to specify ignore white-space as well.

**Comment by vexx32** [comment]
Aye, I don't see a whole lot of value here in just being able to specify `(?x)` in PowerShell v.s. being able to set it in the regular expression itself.

**Comment by he852100** [comment]
There is a very simple question. What to do if you need to match the spaces?

`[ValidatePattern({^[A-Z]{3,4}})]` The default is case insensitive, which puzzles me.

Use general standard regex.  Actually ignore case.  Amaze me!

**Comment by SeeminglyScience** [comment]
> There is a very simple question. What to do if you need to match the spaces?

Use `\p{Zs}` to match a literal space.  See [Supported Unicode general categories](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#SupportedUnicodeGeneralCategories).

> `[ValidatePattern({^[A-Z]{3,4}})]` The default is case insensitive, which puzzles me.
> 
> Use general standard regex. Actually ignore case. Amaze me!

It's to stay consistent with everything else in PowerShell.  Note that `[regex]'pattern'` isn't really a PowerShell thing, that's just calling the constructor.  If you need it to be case sensitive (which if possible you should avoid for parameter validation) you can add `(?-i)` to be beginning of the pattern.
