### ISSUE TITLE
 its possible to implement new empty coallesing operator

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11557]
### steps to reproduce

```
PS C:\> $nul_var = $null
PS C:\> $empty_var=''
PS C:\> $nul_var ?? 'var is null'
var is null
PS C:\> $empty_var ?? 'var is empty'
#nothing
PS C:\> $empty_var ?! 'var is empty'
var is empty
PS C:\> $myinput = Read-Host
# No input
PS C:\> $myinput ?? "null"
# nothing
PS C:\> $myinput ?? "empty"
# nothing
PS C:\> $myinput ?! "empty"
empty
PS C:\>
```

suggestion to operator ### ?!

**Comment by vexx32** [comment]
The null-coalescing operators only operate on whether a value is null or not. They do not operate on empty strings, this is by design. `Read-Host` by design always emits a string, even with empty input. 🙂

**Comment by p0W3RH311** [comment]
empty coallesing operator ?! it not the same null-coalescing operators it not test null but empty string

**Comment by jhoneill** [comment]
> Given this feature's initial implementation was pitched as a transitionary tool for C# developers

I'm not sure where this desire to add many many new operators comes from. 

A couple of things have been added to help recovering C# users to write terse code which isn't self expanatory which just increases what people need to know to understand code by written by others.  Some of us think that rather than lashing on some un-powershelly stuff from C#, it would be better to say "Just use and If or if ... else. At least it can be justfified with the idea that people think what works in one .NET langauge should carry over to another; inventing new ones cannot.

**Comment by vexx32** [comment]
That one's already done. 🤷‍♂ 

I'm neither here nor there on it, there are cases where it helps, there are definitely many cases where its use is a really bad idea.

But in terms of _another_ operator to also handle empty string... I don't think there's a lot of value there. You can already use the ternary operator for this kind of purpose if you really want to:

```powershell
$value = [string]::IsNullOrEmpty($var) ? $valueIfEmpty : $otherValue
```

**Comment by jhoneill** [comment]
> That one's already done. 🤷‍♂

I know. And I'm really not a fan. 

> But in terms of _another_ operator to also handle empty string... I don't think there's a lot of value there.
That was my point :-)
