### ISSUE TITLE
Feature Request New-Item should offer parameters to specify owner and ACL's

### ISSUE THREAD

**Issue by m8ram** [PowerShell/PowerShell#11565]
# Summary of the new feature/enhancement

When a new directory is created the user should be able to specify the owner and ACL for the new directory.
Specific use case is the creation of target directory for our users endpoint backups. The user needs read-only access, the backup software account needs full Access. Adding these permissions after creation of the directories (using `Set-Acl` or alternatives is proving problematic and Powershell does not seem to offer a way to change the owner).

# Proposed technical implementation details

One option is to add parameters like those of `New-SmbShare`: `-FullAccess` and `-ReadAccess`.
On linux an implementation similar to `install` (Options `-o`, `-g`, `-m`)

**Comment by jhoneill** [comment]
Really, this shouldn't be bolted onto new-item. New-Item is there to create a new <anything> depending on the drive. If there are problems with set-acl  and ownership on an existing item they should be resolved, rather than fixing them only as part of creating an item.  
The mkdir command _could_ (and perhaps should) be adapted to do ownership and permissions along with calling New-item.

**Comment by KalleOlaviNiemitalo** [comment]
If `New-Item` set the security, then the operation could be atomic, like in <https://github.com/dotnet/corefx/issues/41614>.
