### ISSUE TITLE
PS 7-RC1 WMI Commands not available in Microsoft.PowerShell.Management Module

### ISSUE THREAD

**Issue by brad-charboneau** [PowerShell/PowerShell#11605]
# Steps to reproduce

```powershell
(Get-Module Microsoft.PowerShell.Management).ExportedCommands
```

# Expected behavior

```none
Should List:
Get-WMIObject
```

# Actual behavior

```none
Function/Module is not in the list and therefore not availble. Does not import from 5.1 
which is installed, likely due to Module Conflict of Module with same name.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
@brad-charboneau the WMI commands have been deprecated since v3 of Windows PowerShell.

This functionality is provided via the CIM cmdlets in both Windows PowerShell v3+ and PowerShell 6+. 🙂 

Most commands using `Get-WmiObject` can be changed to `Get-CimInstance` with minimal or zero modification to the command parameters. Some more complex workflows may need a bit more attention, but by and large the CIM cmdlets are a more effective and faster replacement for the WMI cmdlets. 🙂

**Comment by brad-charboneau** [comment]
Good to know. at now least it is documented here in issue history for any others looking for the answer.
