### ISSUE TITLE
Stop-parsing symbol is unexpectedly half-interpreted as such when quoted: it is removed, yet string interpolation still takes place

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#11608]
Usually, quoting a token ensures that it isn't interpreted as a parameter name; e.g.:

```powershell
PS> Write-Output '-InputObject' 
-InputObject
```

However, this approach doesn't work for the stop-parsing symbol (`--%`).

Note: I'm  using a call to an external program to demonstrate, given that `--%` only makes sense in external-executable calls.

# Steps to reproduce

On Windows:

```powershell
# OK: an unquoted --% is recognized as the stop-parsing symbol and therefore removed.
cmd /c echo --% hi | Should -Be ' hi '

# BROKEN: Due to quoting, '--%' should be passed through as-is, but it is still interpreted as the stop-parsing symbok.
cmd /c echo '--%' hi| Should -Be '--% hi'
```

# Expected behavior

Both tests should pass.

# Actual behavior

The 2nd test fails with the following error:

```none
Expected strings to be the same, but they were different.
Expected length: 7
Actual length:   3
Strings differ at index 0.
Expected: '--% hi'
But was:  ' hi'
```

```none
PowerShell Core 7.1.0-preview.5 # originally reported for PowerShell Core 7.0.0-rc.1
```

**Comment by mklement0** [comment]
Additionally, even though `--%` as an argument is _removed_, suggesting that the stop-parsing symbol _is_ (unexpectedly) recognized, its usual behavior does _not_ kick in, in that string interpolation still _does_ take place:

```powershell
# OK - literal use of --% causes the remainder of the command line to be passed as-is:
PS> cmd /c echo --% $PSVersionTable.PSVersion
 $PSVersionTable.PSVersion
```

```powershell
# !! The *quoted* --% is HALF treated as the stop-parsing symbol:
# !!   * it is NOT passed to the target process
# !!   * however, normal string interpolation still takes place.
PS> cmd /c echo '--%' $PSVersionTable.PSVersion
 7.2.0-preview.2
```

**Comment by davidBar-On** [comment]
The only solution I was able to find that works well both for `PS echo` and `Linux /bin/echo` is the following workaround :

1. In [GetCommandArgumentExpression](https://github.com/PowerShell/PowerShell/blob/8f8ddc3fb76a03dad93f5664314c2795dd69f390/src/System.Management.Automation/engine/parser/Compiler.cs#L4199): if the parameter is `--%` which is `SingleQuoted`, then return `'--%'` (i.e. add back the `'`).
2. In [InvokePipeline](https://github.com/PowerShell/PowerShell/blob/8f8ddc3fb76a03dad93f5664314c2795dd69f390/src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs#L416): if one of the parameters is `'--%'`, change it back to `--%` (i.e. remove the `'`).

Since this is patchy and very specific solution (and may not be the right approach in any case) I understand that it may not  be worth considering.  I am still describing this solution as maybe it may help with finding a solution.
