### ISSUE TITLE
Read-host

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#11636]
Slow, chaotic

```
Read-host 'testxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
```
String
```
https://login.live.com/oauth20_desktop.srf?lc=2052#access_token=EwAYA61DBAAUzl/nWKUlBg14ZGcybuddC4/OHFdfEAAQl00nZLuQLO9cKBfuMB1YShJAv1p6igIE3m3JPbxxqfIVoM6wegCRoCuDB08w3hVyMgX9AM2AFGz86Fo5kZoRb3CO2OdfjL184flhHmCjqQzsyf3VeezJ7w9103Q%2bWtrmzymuXbwk%2bCKTYW1CrOMZDOsctpnM05lw0rByY0%2bPGMb3Z%2bt3fELUJ94ZzVREnNiJGBON%2bbAU2LxQGOYT5mZ%2bxl2zCW8RyqykYN9npMoGZN4eMGA8ThmQi7%2bPBG1cLWjImfgRP9Ey/w5Ee6748tS6qiIzfiDoF1NEtvnTXZVIbbVQE3w%2be9VWCjdxp2L8NtC32AG1oE%2bRc7XySofXmJT2oDZgAACKVYt/Sl2OP16AGMJAJP/e5ELknJQTER1e5MxDI6eQHTA17RveFCzFsTvXiXjXGYvzcoGpqOwpDj4WFU0tBL0VtfzzpQVzBdDXJGu18rKovS2TXxaW8eu2PURt8yVLGihAH7CRKaXEwcVgNMslhkPEIoJ5j5PDGdzC5jqkwRBCl1uC7ayvPBbCgYiukuBPWnfNWGfGOkRz16nI1gbhbQ4TMZEONzFm7zwx6kkvjMBod1oghIj/ZAmbBIwjgIPwBG4ugHU7NHQk7jmWT076x1/7we1KAi8/VpCBZyZ3CA5TajiKlbo6CfOeqyYImF6CSoACM15gzRNcSqsorlapDKJOyAGlPm4tjs2bOpdiWy4B/1iuS80sIhamC9tgWTQfzKTelEgS6cxPF6hqh0f0AT/h5hLRHiQP6uEHz6SNjkD7j2JfSfXaJG9fIbhpvFxoeRBizqh4rb2CnZ%2bKngmXl5xyB2xVsPdTpaKg0mxY3eo2vvM11AheTEyA7u5AHxBriOWpf5U711Y268pCEdD6PRjFNr7esGn5m33IiSL/td%2bBgt3EdwgoefOb0DFrcY%2b9MQ%2bnSajVts9NsnLfbvZHAZNpI6qupaYZvOnARTuvU9wi3fgTHKzZ%2bm7UIRb6/UKhXbAyp2//Z8uAXq06GHzOqYWEPyzBIC&token_type=bearer&expires_in=3600&scope=onedrive.readwrite%20Files.ReadWrite.All&authentication_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6IjEifQ.eyJ2ZXIiOjEsImlzcyI6InVybjp3aW5kb3dzOmxpdmVpZCIsImV4cCI6MTU3OTU4NTY4NywidWlkIjoiQUFBQUFBQUFBQUFBQUFBQUFBQUFBRGU2V1U4ZGZSeXFmSUQwU0lNZnc2RSIsImF1ZCI6ImFwaTovLzkzOTk0MzgxLTJhOGEtNDZkNy04NTI0LTk1OWUwN2M2Mzk1MCIsInVybjptaWNyb3NvZnQ6YXBwdXJpIjoiYXBwaWQ6Ly85Mzk5NDM4MS0yYThhLTQ2ZDctODUyNC05NTllMDdjNjM5NTAiLCJ1cm46bWljcm9zb2Z0OmFwcGlkIjoiMDAwMDAwMDA0MDM2ODAwNCJ9.75MM-6gtQwO5wO-jGYTDnMSva2kgzclITAhQuCIYnMs&user_id=AAAAAAAAAAAAAAAAAAAAADe6fWU8dfRyqfID0SIMfbw6E
```
![20200120_172352](https://user-images.githubusercontent.com/26913892/72714583-ea061380-3ba9-11ea-9ca3-34371cd87ebd.gif)
```
TotalDays         : 0.000550366123842593                          
TotalHours        : 0.0132087869722222                            
TotalMinutes      : 0.792527218333333                             
TotalSeconds      : 47.5516331                                    
TotalMilliseconds : 47551.6331
```

**Comment by he852100** [comment]
@iSazonov 
![20200126_111051](https://user-images.githubusercontent.com/26913892/73130086-bc4b1f80-402c-11ea-98aa-37dfbbef1164.gif)

**Comment by iSazonov** [comment]
Please use Issue template to report. You should share more info. What is PowerShell version and platform? Can you repo without PSReadline?

**Comment by he852100** [comment]
```
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Linux 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fr…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Regardless of 'PSreadline', it does not handle the characters entered by 'read-host。

Related

<https://github.com/PowerShell/PowerShell/issues/11306>

**Comment by iSazonov** [comment]
What term do you use?

**Comment by SteveL-MSFT** [comment]
@iSazonov it's not TERM related.  On Unix, the console prompt has a different code path than Windows which just uses some win32 api's.  The problem is this [set of lines](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L1808-L1811) which basically assumes the input hasn't caused the screen buffer to scroll.  Easier to repro by making the console window small, `read-host 'type a long prompt message'` then starting typing until you get to the edge of the console.  Fixing just this paste issue would be to know when the cursor has moved from one edge to 0 (the other edge) which means the buffer scrolled, but to properly fix while still allowing cursor control within the input is much more complicated.  Then dealing with what happens if the input has scrolled off the top of the screen buffer.  PSReadLine has already solved many of these problems, might be better to see if we can have consolehost call into PSReadLine to handle this if it's loaded.

**Comment by iSazonov** [comment]
@SteveL-MSFT Thanks for clarify! We could use a plugin approach here to allow not only PSReadline injection.
