### ISSUE TITLE
$ENV in using module

### ISSUE THREAD

**Issue by MaynardMiner** [PowerShell/PowerShell#11682]
# Summary of the new feature/enhancement

Using $ENV variables in ``using module`` statement

# Proposed technical implementation details (optional)

My interest is to see the ability for using an environment variable for the using module statement:

``using module $env:MY_DIR\build\module.psm1``

The variables already exist prior to running powershell, and I imagine they have to be loaded prior to modules, so I would *assume* that such would be possible, but I am not sure how the back end works on this subject.

**Comment by SeeminglyScience** [comment]
The problem with this is that `using module` is a parse time concept.  So that means:

1. Allowing the path to be dynamic would increase the time to parse the document, which greatly slows down editors.  `using module` already makes parsing really slow, but it's worth mentioning
1. The variable would be evaluated at parse time, not runtime.  That may not sound like a big deal in theory, but in practice it would feel *really* bad.  That's part of why so few people even know about dynamic keywords, as a parse time only concept they feel terrible.

> The variables already exist prior to running powershell, and I imagine they have to be loaded prior to modules, so I would assume that such would be possible, but I am not sure how the back end works on this subject.

They might exist, but they're not constants.  They'll still be pulled on every request because you can change them at any point.

Also it's worth noting that you can use `using module .\path\relative\to\file.psm1` and the <kbd>.</kbd> will work like `$PSScriptRoot`. Everything else in PowerShell uses that to refer to the current working directory except `using` statements.

**Comment by TheIncorrigible1** [comment]
> <kbd>.</kbd> will work like `$PSScriptRoot`

I didn't know that - not relative to `$PWD` like most other directory access?  Given that it would cause a rewrite in how the parser works, I'm not sure the feature request adds anything.

**Comment by SeeminglyScience** [comment]
> > . will work like `$PSScriptRoot`
> 
> I didn't know that - not relative to `$PWD` like most other directory access?

Yup 🙂, except when using forward slashes due to a bug (#7424), then it's relative.

Super confusing, but tbh I'm not sure what else they could have done.  Maybe treat `PSScriptRoot` and only `PSScriptRoot` as a constant, but 🤷‍♂ that'd be confusing too.

**Comment by TheIncorrigible1** [comment]
> except when using forward slashes due to a bug (#7424), then it's relative

I don't even know what to say.  I'm surprised that's not a higher priority bugfix for 7.0 GA.  To stay on-topic: I think you make good points for why this isn't feasible as it would make for a miserable authoring experience moving forward (although I've seen mixed adoption of the `using` statement in general due to knowing the nuances this deep)

**Comment by MaynardMiner** [comment]
I understand.

I've learned you can also use `..\path` to get a parent, etc

Its just when you are writing different runtime scripts, and importing modules often, especially in different points of the program, and potentially while being in different directories, it gets hard to keep track of it. It's more of a convenience suggestion, if it was possible.

**Comment by TheIncorrigible1** [comment]
@MaynardMiner If you need the dynamic behavior, I'd recommend sticking to `Import-Module` and importing your class definitions using `Invoke-Expression` to avoid the parse-time errors associated with PowerShell v5 classes.
