### ISSUE TITLE
Write-host Example of color

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#11683]
# Steps to reproduce

```powershell
Write-host -foregroundcolor <tab>
```

# Expected behavior

```none
Write-host -foregroundcolor <tab>
```
![Screenshot_20200126_161836](https://user-images.githubusercontent.com/26913892/73132566-c6cede80-4057-11ea-8b70-61392eab6a8a.jpg)

# Actual behavior

```none
Black        DarkCyan     DarkRed      Magenta
Blue         DarkGray     DarkYellow   Red
Cyan         DarkGreen    Gray         White
DarkBlue     DarkMagenta  Green        Yellow
```

# Environment data

```none

```

**Comment by jhoneill** [comment]
Currently  tab expansion for parameters cycles through the names in enum types, in this case 
 [consolecolor] -  `[enum]::GetNames([consolecolor])`  shows the names which  things like "Green", not "\e[92mGreen\e[0m. 

Since you would be expecting the parameter to be coloured in the command line this causes all kinds of problems. it conflicts with syntax colouring by PSReadline, since to be consistent you would also want backgroundColor to show in the color it would make the parameter values invisible or hard to read in a lot of cases.

**Comment by doctordns** [comment]
I agree with @jhoneill that the behaviour here is consistent - no colour changes occur with any tab expansion. 

At the same time, I agree it might be nice to see Pink in PInk. How about a -GetColoursample parameter to Get-HBost, that displays the colours that match the parameter value IN their colour?

And a command or parameter that shows the Ascii escape character values would be nice too.
