### ISSUE TITLE
VSCode manual install instructions don't work from PS7 RC.1

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#11715]
# Steps to reproduce
Open up PS7 in a RedHat7 terminal.  Follow the instructions on this page to install VSCode:

https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions

The specific command that chokes is this:
```powershell
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
```

# Expected behavior

The file `/etc/yum.repos.d/vscode.repo` is created.

# Actual behavior

The file is not created.  Specifically, PS7 seems to have issues with the spaces in "Visual Studio Code" and the `\n` are not translated into newlines by sh.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Linux 3.10.0-862.el7.x86_64 #1 SMP Wed Mar 21 18:14:51 EDT 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rkeithhill** [comment]
BTW the workaround is to **exit PowerShell** and execute the command directly from sh.  :-(

**Comment by mklement0** [comment]
Unfortunately, this is the fundamentally broken quoting of arguments passed to external programs rearing its head again, and it affects _all_ PowerShell versions to date, as now summarized in https://github.com/PowerShell/PowerShell/issues/1995#issuecomment-562334606.

```powershell
PS> sh -c 'echo -e "Visual Studio Code"'
```

breaks down into the following arguments:

```none
$1=[sh]
$2=[-c]
$3=[echo -e Visual]
$4=[Studio]
$5=[Code]
```

The net effect is that only `'Visual'` is echoed.

(As an aside: `echo`'s `-e` option is not POSIX-compliant and shouldn't be used with `sh`; on macOS and Ubuntu, for instance, the `-e` _prints_ instead of being interpreted as an option - POSIX `echo` supports no options at all.)

The reason is that the intermediate, re-quoted version of the command constructed behind the scenes looks like this, which is broken, due to lack of `\`-escaping of the embedded `"` chars.:

```sh
# !! Broken quoting.
sh -c "echo -e "Visual Studio Code""
```

The workaround is to _manually_ perform the `\`-escaping, which, of course would break once the underlying problem is fixed (which therefore can't be done without breaking backward compatibility:


```powershell
# Sadly, the \-escaping is necessary.
PS> sh -c 'echo -e \"Visual Studio Code\"'
```
