### ISSUE TITLE
-@ untrapped error, or design choice ? 

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PowerShell#11739]
I lost most of yesterday to not being able to see a - sign in VS code because colour choices I'll be dealing with over there.  I had managed to enter, but could not see something like this

```
function foo  {
 [cmdletbinding()]
  param ($a , $b) 
  "a is '$a' and b is '$b;' " 
}

$h = @{
   a = 1
   b = 2
} 

foo -@h
```

So I am trying to splat the hash H into foo, but I have a stray - sign before the @ And I get the output  
`a is '-@h' and b is '' `

 With the ISE theme in VS code by default it looks like this 
![image](https://user-images.githubusercontent.com/16209593/73527107-64d0f900-440a-11ea-9106-3fca15a487c1.png)
which camouflagesit quite well. So after leaving work 2 hours late I started thinking 

**Why** is` -@h` not considered to be a parameter  ? If I typed -atH 
 I would have got 
`Invoke-RestMethod : A parameter cannot be found that matches parameter name 'atH'.`
and I would have found the bug in two seconds not two hours. 

In a previous item @SeeminglyScience  (IIRC - I can find it now) explained that `--`  has a special undocumented suppression function. And I'm trying to work out if there is a case where `-@x `should be a parameter's value without needing quotes but for `-xx ` to be the _value_ rather than the _name_  it needs quotes.  Having been caught by this **of course I think** this should cause an error, but maybe someone can point the case where it is legitimate, anyone ? anyone ? Bueler ? Anyone ?

**Comment by mklement0** [comment]
Without having looked at the source code, it seems that **only if `-` is followed by an (English) letter or `_` (notably, not a _digit_) is it interpreted as a parameter name**.

The following calls succeed, because the `-<char>` sequences are _not_ treated as parameters (and therefore positionally bind to `-bar`):

```powershell
function foo { [CmdletBinding()]param($bar) "[$bar]" }
[char[]] '~`!@#$%^*+0<>./\[]' | % { iex "foo -$_" }
```

Note that while `` ` `` works in principle, it retains its escaping function, so something like ``-`a`` rings the bell, and `` -`n `` passes `-<newline>`.

(Perhaps surprisingly, given that `@` and `$` work), `{` / `}` and `(` / `)` don't work.

Neither do the quoting chars., `"` and `'`.

As you state, `-` doesn't work (`--` makes the binder treat all remaining tokens as _positional_ arguments, so that `foo -- -unknownswitch` works, for instance).

Non-prefix metacharacters `,`, `;`, `|`, and `&` still have their usual meaning and also cannot be used.

`-?` is intercepted and always shows help.

---

As an aside: Using `-%`, to form `--%`, the stop parsing symbol, is recognized as such even with additional characters immediately following it, because its special treatment of the remaining command line kicks in _instantly_.

Curiously, it breaks the invocation altogether, because no arguments are then recognized anymore (granted, `--%` is for _external programs_, but the behavior is still curious):

```powershell
# Without --%, these would succeed.
foo --% a # fails
foo --% -bar baz # fails
```

Another `--%` problem: #11608

**Comment by jhoneill** [comment]
<tips hat>  at the response. 

> (Perhaps surprisingly, given that `@` and `$` work), `{` / `}` and `(` / `)` don't work.
> 
> Neither do the quoting chars., `"` and `'`.
if $x is 1 , foo -$  assumes -$ is a value but -$x is -($x) and -1 is passed  

I'm not sure if the behavior is by design or by accident. If it is right, and even if it is wrong if people depend on it . It certainly feels wrong to me but I'm not sure I should be judging. 

`->x.txt `
is another odd one. Is it ever _meant_ or only ever a typo for >x.txt

**Comment by mklement0** [comment]
> I'm not sure if the behavior is by design or by accident. 

I hope someone else can speak to that; my intent was simply to document the current behavior, which definitely has quirks and is hard to predict.

There are several other problems related to parameter parsing:

* #6291 
* #6292
* #6360
* #11646
* #11608 (mentioned above)
