### ISSUE TITLE
Windows console host must set virtual terminal mode after running external commands

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#1177]
External tools like less.exe change the console mode.  A shell is responsible for restoring and flags it cares about after running such tools.

**Comment by dahlbyk** [comment]
I believe I'm running into this on https://github.com/dahlbyk/posh-git/pull/304#issuecomment-247516226 in an attempt to resolve https://github.com/Jaykul/PowerLine/issues/1. Repro is pretty simple (`"$([char]27)[32mhello$([char]27)[0m"` is my basic test string).

<img width="358" alt="powershell_2016-09-15_23-22-30" src="https://cloud.githubusercontent.com/assets/133987/18575462/940cd984-7b9d-11e6-954e-23e2e0efdd27.png">

**Comment by Jaykul** [comment]
I can't seem to repro that in PS 5.1 or 6a10 using the less.exe that pscx shipped ... is this fixed?

**Comment by lzybkr** [comment]
@Jaykul, are you using conemu?

**Comment by dahlbyk** [comment]
I'm using PS 5.1.14393.103 on Win10 x64, and can reproduce on another machine with the same. I can also reproduce with ConsoleZ; I have not tried conemu.

**Comment by Jaykul** [comment]
@lzybkr I tried it in ConEmu and out, actually, because at first I thought maybe ConEmu was the reason it worked. Actually, I just retried it in 6a9 and I couldn't repro there, so ... I have no idea. I guess I'm just special.

![image](https://cloud.githubusercontent.com/assets/192942/18656388/bc3490cc-7ebe-11e6-8961-2482a820e2d0.png)

**Comment by powercode** [comment]
Please backport this to desktop edition!
