### ISSUE TITLE
Code OK on V5.1 does not run on V7.0.0RC2

### ISSUE THREAD

**Issue by RG255** [PowerShell/PowerShell#11782]
```
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

The code in the attached script runs OK on V5 but generates the following error on V7:
```
MethodInvocationException: S:\PowerShellScripts\TestUserIngroup_1.ps1:5
Line |
   5 |  … t -Process {$_.GetType().InvokeMember('Name', 'GetProperty', $null, $ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "InvokeMember" with "5" argument(s): "Unknown name. (0x80020006 (DISP_E_UNKNOWNNAME))"
```
#### The script:
```powershell
$user = $env:USERNAME
$group = 'Users'
$groupObj = [ADSI]"WinNT://./$group,group"
$membersObj = @($groupObj.psbase.Invoke('Members'))
$members = ($membersObj | ForEach-Object -Process {$_.GetType().InvokeMember('Name', 'GetProperty', $null, $_, $null)})

If ($members -contains $user) 
{Write-Host -Object "$user exists in the group $group"}
Else 
{Write-Host -Object "$user does not exists in the group $group"}
```

[TestUserIngroup_1.zip](https://github.com/PowerShell/PowerShell/files/4160919/TestUserIngroup_1.zip)

**Comment by iSazonov** [comment]
@SeeminglyScience Have you any thoughts?

**Comment by RG255** [comment]
I am somewhat new to GitHub so I am not sure what you are expecting when you say "Have you any thoughts" My only thought at this time would be expecting it to work on PSV7* or there to be a better/alternative way to achieve the same result?

**Comment by iSazonov** [comment]
@RG255 References like "@RG255" means contacting the owner of this name. So my question was for @SeeminglyScience who could share useful thoughts about the issue.

**Comment by SeeminglyScience** [comment]
@iSazonov Looks like PowerShell isn't able to determine that [`IADsMembers`](https://docs.microsoft.com/en-us/windows/win32/api/iads/nn-iads-iadsmembers) (the collection returned by `Members`) is enumerable.  So instead of `$membersObj` enumerating into member objects like in Windows PowerShell, the attempt is made to call a `Name` property on the `IADsMembers` interface which doesn't exist.

You can kinda see this by attempting to get the property `Count` instead, which will throw not implemented instead of unknown name.

**Comment by SeeminglyScience** [comment]
So playing with it a bit, my guess is that this happens because if you query `IDispatch.GetIDsOfNames` with the names `_NewEnum` and `ppEnumerator` then that exception is thrown.  *However*, if you *manually* invoke `GetIDsOfNames` with a preserved sig (no automatic HResult handling) you'll see the HResult above returned, but it'll also show [`DISPID_NEWENUM`](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/automat/dispid-constants) for `_NewEnum`.  If `_NewEnum` was really not found, it would be `-1`.

Not sure atm where this needs to be fixed though.

<details>
<summary>Tested with this code, click to expand</summary>

```powershell
Add-Type -TypeDefinition '
    using System;
    using System.Runtime.InteropServices;
    using System.Runtime.InteropServices.ComTypes;

    namespace Testing
    {
        public class DispatchWrapper
        {
            private readonly IDispatch _real;

            internal DispatchWrapper(IDispatch real) => _real = real;

            public static DispatchWrapper Create(object obj) => new DispatchWrapper((IDispatch)obj);

            public int GetTypeInfoCount(out int info) => _real.GetTypeInfoCount(out info);

            public int GetTypeInfo(int iTInfo, int lcid, out ITypeInfo ppTInfo) => _real.GetTypeInfo(iTInfo, lcid, out ppTInfo);

            public int GetIDsOfNames(Guid iid, string[] rgszNames, int cNames, int lcid, int[] rgDispId)
                => _real.GetIDsOfNames(iid, rgszNames, cNames, lcid, rgDispId);

            public void Invoke(
                int dispIdMember,
                Guid iid,
                int lcid,
                INVOKEKIND wFlags,
                DISPPARAMS[] paramArray,
                out object pVarResult,
                out EXCEPINFO pExcepInfo,
                out uint puArgErr)
                => _real.Invoke(
                    dispIdMember,
                    iid,
                    lcid,
                    wFlags,
                    paramArray,
                    out pVarResult,
                    out pExcepInfo,
                    out puArgErr);
        }

        [Guid("00020400-0000-0000-c000-000000000046")]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        [ComImport]
        internal interface IDispatch
        {
            [PreserveSig]
            int GetTypeInfoCount(out int info);

            [PreserveSig]
            int GetTypeInfo(int iTInfo, int lcid, out ITypeInfo ppTInfo);

            [PreserveSig]
            int GetIDsOfNames(
                [MarshalAs(UnmanagedType.LPStruct)] Guid iid,
                [MarshalAs(UnmanagedType.LPArray, ArraySubType = UnmanagedType.LPWStr)] string[] rgszNames,
                int cNames,
                int lcid,
                [MarshalAs(UnmanagedType.LPArray, ArraySubType = UnmanagedType.I4)] [Out] int[] rgDispId);

            void Invoke(
                int dispIdMember,
                [MarshalAs(UnmanagedType.LPStruct)] Guid iid,
                int lcid,
                INVOKEKIND wFlags,
                [MarshalAs(UnmanagedType.LPArray)] [In] [Out] DISPPARAMS[] paramArray,
                out object pVarResult,
                out EXCEPINFO pExcepInfo,
                out uint puArgErr);
        }
    }'

$group = 'Users'
$groupObj = [ADSI]"WinNT://./$group,group"
$membersObj = @($groupObj.psbase.Invoke('Members'))
$disp = [Testing.DispatchWrapper]::Create($membersObj[0])
$nullGuid = [activator]::CreateInstance([guid])
$enUS = [cultureinfo]::CurrentCulture.LCID
$namesToQuery = '_NewEnum', 'ppEnumerator'
$dispIds = [int[]]::new($namesToQuery.Length)
$hr = $disp.GetIDsOfNames($nullGuid, $namesToQuery, $namesToQuery.Length, $enUS, $dispIds)

'HResult: 0x{0:X}' -f $hr
for ($i = 0; $i -lt $namesToQuery.Length; $i++) {
    '{0} ID: {1}' -f $namesToQuery[$i], $dispIds[$i]
}
```

Should return:

```raw
HResult: 0x80020006
DispIDs: -4, -1
```
</details>

**Comment by SeeminglyScience** [comment]
Another update, here's the code that needs to change:

https://github.com/PowerShell/PowerShell/blob/e2f838e3c5baabffc4d14fa747902d18628044bc/src/System.Management.Automation/engine/COM/ComUtil.cs#L426-L439


It fails because `IADsMembers` implements `IDispatch`, but throws `E_NOTIMPL` when trying to get type info.  The other members work fine though.

Instead of (or in addition to) querying type info, it needs to directly invoke `GetIDsOfNames` with two names. The first has to be `_NewEnum` and the second can apparently be anything.  It needs two though, otherwise it returns unknown. If the first ID is `DISPID_NEWENUM` then `_NewEnum` can be invoked.

Example invoke using the above code in the `details` pane:

```powershell
$results = $null
$excep = [Activator]::CreateInstance([Runtime.InteropServices.ComTypes.EXCEPINFO])
$argErr = 0u;
$disp.Invoke(-4, $nullGuid, $enUS, 'INVOKE_PROPERTYGET', @(), [ref] $res, [ref] $excep, [ref] $argErr)

# yield
$results
```

Which returns:

```raw
System.__ComObject
System.__ComObject
System.__ComObject
System.__ComObject
System.__ComObject
System.__ComObject
```

**Comment by iSazonov** [comment]
@SeeminglyScience Thanks for your investigations! 
I think we need to have more tests for COM interactions.

**Comment by daxian-dbw** [comment]
Thanks @SeeminglyScience for analyzing the issue and pinpoint the cause ❤️ 

The `ComEnumerator` was introduced back in early .NET Core 2.0 preview period of time (#4553), because `GetEnumerator()` didn't work on COM object even if the object can be cast to `IEnumerable` and .NET Core team said it was by design at the time (https://github.com/dotnet/runtime/issues/21690).
With .NET Core 3.1, `GetEnumerator()` works on the COM objects that can be cast to `IEnumerable` 🎉

however, for the COM object that can be cast to `IEnumerator`, exception is thrown when calling `MoveNext()` on it. 
So we still need the `ComEnumerator`, but much simplified to just cover the case that the COM object implements `COM.IEnumVARIANT` interface.

PR was submitted: #11795
