### ISSUE TITLE
Integrate Azure App Insights natively into PowerShell Host

### ISSUE THREAD

**Issue by petercovach** [PowerShell/PowerShell#11822]
Bring Azure App Insights native into the PowerShell Host.  When launching powershell.exe, pass the Insights ID and BOOM; you're off to the races tracing the information and errors your scripts are generating.

As the amount of scripts used in my environment grows, the management of those scripts has started to become more intimidating.  A larger strategy is necessary to understand dependencies and errors that are occurring in the application.  There are ways to bring the Application Insights imported dlls directly into the runspace, but this would require a lot of re-work of code.  Additionally, any native function that outputs to the native output streams would potentially be lost if the programmer did not explicitly capture the output.  I want a low barrier entry to easily track all of my environment's scripts.  When information is added to any of the PowerShell streams managed by the host, the host could asynchronously send that information back to App Insights.

# Proposed technical implementation details
The PowerShell host should allow native support of Azure App Insights.  When launching powershell.exe, pass the App Insights token to begin effortlessly logging information and exceptions.  Anything written to the PowerShell streams should get automatically added to App Insights.  Conversely, exposing the functionality in the .Net implementation would allow for applications that did not use the native PowerShell host to take advantage of the functionality.

Current Option:

```
Clear-Host   
Add-Type -Path "[Your_Assembly_Path]\Microsoft.ApplicationInsights.dll" 
$client = New-Object Microsoft.ApplicationInsights.TelemetryClient  
$client.InstrumentationKey="xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx"  

$eventName = "Hello Event"  
$client.TrackEvent($eventName, $null)  

try  
{  
    $fileContent = Get-Content -Path "C:\Test.txt" -ErrorAction Stop  
}  
catch  
{  
    $telemtryException = New-Object "Microsoft.ApplicationInsights.DataContracts.ExceptionTelemetry"  
    $telemtryException.Exception = $_.Exception  
    $client.TrackException($telemtryException)  
}
```

Proposed Option:

`powershell.exe C:\test.ps1 -AppInsightsToken "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx"`

OR

```
$host.AppInsights.Enabled = $true
$host.AppInsights.InstrumentationKey="xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx"

$host.AppInsights.TrackEvent("My Event",$null)

$host.AppInsights.Flush()
```

Any logging could automatically be sent to App Insights based how it hits the Information, Warning, Verbose, Debug, Error, Output, and host streams.

Here is the credit for the code:
https://www.c-sharpcorner.com/article/using-azure-application-insights-in-powershell/

**Comment by iSazonov** [comment]
I do not think that this should be exclusively in host because hosting applications exist and could benefit from the feature. 
If we migrated to ILogger API we could expose it publicly including ApplicationInsights (with Microsoft.Extensions.Logging.ApplicationInsights provider). All developers would have to do is edit a config file.

**Comment by kilasuit** [comment]
Whilst this may sound like the right idea PowerShell already has App Insights integration for the PowerShell Team to get some basic telemetry and at present App Insights does not allow you to connect to multiple instances and segregate the data going between them, something I do not think is planned.

You could of course recompile the PowerShell exe with your own App Insights key and force use of your own events but I would **seriously** recommend against this path because then you'd have a high amount of pain on repackaging and then distributing repackaged exe on each updated version the PowerShell team release.

There is however an already existing Low barrier approach, which is to use Transcription which you can read up on in https://docs.microsoft.com/en-gb/powershell/module/microsoft.powershell.core/about/about_logging?view=powershell-5.1 & also at https://devblogs.microsoft.com/powershell/powershell-the-blue-team/ using the Over The Shoulder Transcription method in that post pushing all transcripts to a central location.

**Comment by petercovach** [comment]
In regards to App Insights, I cannot comment on the complexity of the task at hand.  I leave that in the hands of the very capable architects of PowerShell like yourself.  I do think that there should be an easy real time way to capture the output of your PowerShell code and analyze it at an enterprise level.

I agree with you that compiling my own version of PowerShell is a non-starter.  The distribution is too complex.  Additionally I want my user statistics to go to Microsoft so that our experience is recorded and goes toward making the product better.

We have toyed with the concept of creating a centralized logger.  Again, I would not consider this a low barrier approach because the back end infrastructure to analyze the results would need to be created.  It would serve the purpose to create a centralized logging store, but dashboard, analysis, statistics would all need to be developed.  That is where I was hoping Azure App Insights could fill the gap.

**Comment by iSazonov** [comment]
We have transcription, tracing, debugging, logging, App Insights... This all has an effect on performance, even when turned off. It makes us think about ILogging.
Perhaps @daxian-dbw could share thoughts about this.
