### ISSUE TITLE
implement return-parsing symbol

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11889]
steps to reproduce

`icacls X:\VMS --% /grant Dom\HVAdmin:(CI)(OI)F ---% ; write-host hello`

return-parsing symbol _---%_  directs PowerShell to return interpreting input as PowerShell commands or expressions.

**Comment by vexx32** [comment]
What benefit does this provide? 🤔 

I can't say I've ever needed to worry about what I'm putting after a stop-parsing symbol other than a line break.

**Comment by mklement0** [comment]
@vexx32, the potential benefit is in overcoming the following limitations of current `--%` syntax (I'm not advocating for the change, just providing background information; to me, the only truly problematic limitation is the redirection case).

* You cannot use redirections - they are passed as _literal arguments_ to the target program (if the target program happens to be a shell, _it_ would interpret it).
* You cannot enclose the command line in `(...)` - because the closing `)` is interpreted as a literal part of the command line.
* (As implied in the OP) You cannot follow the command line with `;` and another statement - because the `;` is interpreted as a literal part of the command line.
* You cannot use `--%` inside a _single-line_ script block - because the closing `}` is interpreted as a literal part of the command line.
