### ISSUE TITLE
Attributing Text Effects

### ISSUE THREAD

**Issue by theJasonHelmick** [PowerShell/PowerShell#11890]
# Summary of the new feature/enhancement

Text Effects (font customization) allow you to place emphasis on text to lower or raise awareness to
the user and improve data comprehension. They include, but not limited to, foreground and background
colors, bold, highlighting, strikethrough, and blinking.

PowerShell should support Text effects in views and interactive sessions for data
comprehension and Accessibility. PowerShell should support, as most modern terminals, 24-bit True
Color.  Below are two scenario's for this need:

As a PowerShell user, I want to interactively use Text Effects for reporting and color emphasis. For
example, when a value exceeds defined limits to enhance data comprehension.

As a PowerShell Module builder, I want to take advantage of Text Effects for colorization, and
create views for cmdlets to aid in data comprehension and overall Accessibility.

# Proposed technical implementation details (optional)

For PowerShell users, Text Effects can be set in interactive sessions with calculated properties for
the purpose of accenting data with specific defined results. A new attribute `texteffect`, that is
abbreviated `t`, follows the previous pattern for `alignment` (al) and avoids contention.

```powershell
Get-Service -Name bits | Select-Object -Property Name, @{n='State';e={$_.status};t={...}}
```

For advanced module builders, Text Effects may be added to the formatting system PowerShell
currently has in place. A new xml tag **TextEffect** will contain a script block.

```powershell
<TableControl>
  <TableHeaders>
    <TableColumnHeader>
      <Label>AvailableSpace</Label>
      <Width>7</Width>
      <Alignment>right</Alignment>
    </TableColumnHeader>
  </TableHeaders>

  <TableRowEntries>
    <TableRowEntry>
      <TableColumnItems>
        <TableColumnItem>
          <ScriptBlock>[String]($_.Freespace / 1024)</ScriptBlock>
          <TextEffect>if ( $_.Freespace/1024 -lt 100mb ) { "red" }</TextEffect>
         </TableColumnItem>
      </TableColumnItems>
    </TableRowEntry>
  </TableRowEntries>
</TableControl>
```

**Comment by vexx32** [comment]
I like this idea quite a bit.

I do, however, question the priority... format files requiring XML is quite cumbersome. The C# APIs, in comparison, are quite easy to work with internally. 

Can we perhaps also look at exposing those APIs to powershell users in some fashion so that we can define formats in _script_ rather than just in XML?

**Comment by ThomasNieto** [comment]
I like this idea of adding color to output based on a condition. The only consideration I can think of is changing the color based on color blindness and where the color chosen will not work well with non-default console background color. It falls into a wider concern of color themes for PowerShell. 

This https://github.com/PowerShell/PowerShell-RFC/pull/241 RFC proposes a DSL for creating formatting definitions without using XML.

**Comment by SeeminglyScience** [comment]
> I do, however, question the priority... format files requiring XML is quite cumbersome. The C# APIs, in comparison, are quite easy to work with internally.

Writing the XML is also quite easy to work with *assuming* you go through the sort of tedious steps of setting up schema support from #7749.  I wonder if shipping those settings as an extension would be a workable middle group for the time being.

Something to consider anyway, I'm *definitely not* saying those API's shouldn't be exposed or that a DSL shouldn't be created.

**Comment by JamesWTruher** [comment]
I've got this prototyped not in xml, but via `format-table -property $properties`
```
$props = @{ L = "UnixMode"     ;E={$_.unixmode}      ;TEXTEFFECT={if ( $_.unixmode -match "^d" ) { "44" } }; W = 10},
@{ L = "User"         ;E={$_.user}          ;T={if ( $_.user -match "jimtru" ) { "7" }}; W = 16},
@{ L = "Group"        ;E={$_.Group}         ;T={if ( $_.user -match "root" ) { "41;1;33" }}; W = 18},
@{ L = "LastWriteTime";E={$_.lastwritetime} ;T={if ( $_.lastwritetime -lt "1/1/2020" ) { "4;1;36" } }; W = 20 ; F = "{0:MM}/{0:dd}/{0:yyyy} {0:hh}:{0:mm}" },
@{ L = "Size"         ;E={$_.size}          ;T={if ( $_.size -gt 100kb ) { "1;41;33" } elseif ( $_.size -gt 10kb ) { "1;31" } }; W = 10 },
@{ L = "Name"         ;E={$_.name}          ;T={if ( $_.Name -match "^a" ) { "31" } elseif ( $_.Name -match "^b" ) { "1;35" } elseif ( $_.Name -match "readme" ) { "5" } else { "1;34"} }}
```
which renders to this (note that one of the filenames is blinking :) :
![Screen Shot 2020-02-26 at 12 20 49 PM](https://user-images.githubusercontent.com/10214008/75384229-98306780-5892-11ea-8ac9-3bc2b61744f9.png)

**Comment by Jaykul** [comment]
I think the proposal to do color via formatting and the format commands makes a lot of sense, but ...

## First: Let's get this out of the way: please don't support blink. 

Thankfully, many terminals won't support it anyway. But there's a reason that was deprecated from HTML. 

When I worked on this, I actually left off the text effects (underline, bold, strikethrough, _and_ blinking). I think _underline is the only one that's supported in most terminals_ anyway (terminals treat "bold" as a "bright" modifier for the _color_ --which only affects the base 8 colors-- not as a font modifier, since they're designed to be used with bitmap fonts). So I just decided it was not worth the effort for my prototype to support underlining.


## Second, there's a usability need

@theJasonHelmick's example is too simple (is that foreground or background red? And remember that over on Linux (or in Windows Terminal) they don't call it "Red" and "DarkRed" it's "BrightRed" and "Red" ...
```powershell
if ( $_.Freespace/1024 -lt 100mb ) { "red" }
```

@JamesWTruher's example is too obscure. I think if we're going to write escape sequences, you're not helping enough, and we might as well just keep writing them the way we are now (e.g. [devblackops/Terminal-Icons](https://github.com/devblackops/Terminal-Icons)).
```powershell
if ( $_.size -gt 100kb ) { "1;41" }
```

My proposal (obviously) is that we should bring in the code I wrote to prototype this stuff for #2381 (wow, 8000 issues ago?). Basically, we should expose:
1. An `RgbColor` class for full color support
2. A variable/provider syntax for foreground vs background colors, so instead of writing `"red"` or `"1;31"` or `"1;41"` you can write `$fg:red` or `$bg:red` or `$bg:ee0518` or even `$fg:firebrick` (remember the color pallette names?)
3. A similar provider syntax for additional formatting (e.g. underline, inverse?) 

That way you have discoverability!  E.g. you can get a list of them (In the 256 color model, there about 76 reds plus 44 magentas):
![image](https://user-images.githubusercontent.com/192942/75577167-6d2f4a80-5a2f-11ea-8979-0ba8132edfd7.png)

We could alter that a bit, and make the _provider_ a "text effect" and the drive "text" and make "background" (and "bg") and "foreground" (and "fg") as folders, so you could `Write-Host "${text:fg\red}${text:bg\white}${text:underline}Hello World"` or use _that_ in the format files and cmdlets ... or we could make it castable: `[TextEffect]@{ fg = "red"; bg = "white"; underline = $true}` or ... whatever. **My point** is that I think PowerShell deserves a more user-friendly model than just VT sequences (which we can already use, and which don't help with accessibility).

## Thirdly:  There's an accessability need

The _whole point_ of supporting this as a _separate_ entity in the formatting **should be** that a user can set a preference variable (e.g. `$PSColorSupport`) which allows something like: `Full` or `None` or `HighContrast` -- where the formatting engine would ensure that dark foreground colors were shifted to light colors (perhaps to the nearest 8 "bright" console colors, so the user can at least specify a theme), and the background was always black... 

The code I wrote doesn't support _that_ preference variable yet, but I did write the color model to support forcing colors to the nearest match in a specified color palette.

Did I mention not supporting blink?

## Fourthly: About backward compatibility

I assume that any module that uses this in it's formatting file will have to ship PS5-specific format files.

If there's any way that we can make the formatting engine _warn on import_, but ignore elements it doesn't recognize, instead of blowing up, that would be really nice, and future you will thank past me for thinking of it 😉😁

**Comment by theJasonHelmick** [comment]
@Jaykul I really appreciate the detail of your thoughts and appreciate your time.  Let me start by saying that we are very early days in investigating colorization and text effects.  Just so I can clarify for everyone, this means that nothing is ‘on’ or ‘off’ the table at this time in our thinking process- we are open to all discussions and ideas.

Jakul, let me briefly respond to your 4 main points directly here. 

First:  In regards to blink and other specific effects. Just in general, we intend to follow the Accessibility guidance that we are given.  I will start that process a little further down the road and report back here - but your point about blink was noted ;)

Second:  Yes, the examples in this early stage or simplified, and do not show any tooling or additional support. To your point about the syntax and coloring, we are looking at ways to simplify this, maybe  a `color-picker`?  - but nothing defined yet.  That doesn’t mean I disagree with your suggestion in anyway, just not there yet. Your point that PowerShell deserves a more friendly model than just VT seq is understood and noted.

Third: Accessibility is a major part to this focus.  I agree with your view but we haven’t moved to those discussions yet. 

Fourth: Regarding backward compat - I see your point.  As we get further into implementation we will be able to address those concerns more clearly.

Thanks Jakul for taking the time to respond.

**Comment by theJasonHelmick** [comment]
For anyone that wishes to explore some of these ideas, I'm including some instructions here.  
To test, you will need Jim Truher's Github repo and branch:

- Fork: https://github.com/JamesWTruher/PowerShell-1
- Checkout Branch: **FormatWithAttributes**
- Build (Will get PS 6.0 Alpha)
  - `Import-Module .\build.psm1`
  - `Start-PSBootstrap`
  - `Start-PSBuild`
  - `&(get-psoutput)`

I then created a simple function, you can make your own, but here is mine:
`
function Get-Dir {

    dir | ft UnixMode,User,Group,
        @{N="LastWriteTime";E={$_.LastWriteTime};T = {
            if ($_.lastwritetime -lt "1/1/2020"){"36;4"} }},Size,
        @{N ="Name"; T = { if ($_.extension -eq ".md") {"31;1"}}; E={$_.Name}}
}
`

**Comment by StartAutomating** [comment]
I think the heart of the proposal is in the right place, and the suggested implementation _is not_ the right approach.

# Recognizing the Breadth of the Need

As suggested, this fix addresses a very slim subsection of the need.  It allows you to color a particular column.  Surely this isn't _all we want_.

If we look at the formatters more broadly, we can format any object any way we'd like.  What we're hoping to do is to allow for more advanced colorization and interactivity.  To that end, having a rule that just returns a color in the XML ignores a lot of scenarios.   What if I wanted to make it Bold or Underlined?  What if it were a link and I'd like to render as such in a webpage or notebook?  What if I wanted to be able to make my tables markdown tables?  What if I wanted to display text in a grid?  What if I wanted to justify it?

You hopefully are getting the point.  This idea is nifty and all, but it's hardly all we want to do, even if we are limiting it to "text effects".  Given that the formatter can also produce things that are not text (e.g. you can have a formatter that writes XAML, or feeds data to a UI), even having the issue title as simple as "Attributing Text Effects" is inherently limiting.

I'd suggest a more appropriate title would be "Enhancing Formatting".

# Leveraging the formatting engine as it exists

Since we cannot make changes to the format schema without breaking formatting for down-level versions, it makes the most sense to leverage the formatting subsystem within PowerShell now.

A few major capabilities are worth highlighting:
* You can override the display of any property with a ScriptBlock.  This can be used to support colorization directly within a table, including the above HeatMap example.
* Custom formatters can do almost anything, and already have the concept of a "Control" 
* Controls can also be used to display a group header on a given set of formatters

To give a couple of practical examples, here are some screenshots of formatting built with [EZOut](https://github.com/StartAutomating/EZOut):

Here's a Process HeatMap:
![Process Heatmap](https://github.com/StartAutomating/EZOut/raw/master/Assets/Process.Heatmap.gif)

Here's colorized XML:
![Colorized XML](https://github.com/StartAutomating/EZOut/raw/master/Assets/ColorizedXml1.gif)

Here's a file tree formatter:
![File Trees](https://github.com/StartAutomating/EZOut/raw/master/Assets/FileTreeFormatter.gif)

Another module I wrote for RegEx ([Irrregular](https://github.com/StartAutomating/Irregular) uses EZOut to build syntax highlighting for RegEx:

![Regex Syntax Highlighter](https://github.com/StartAutomating/Irregular/raw/master/Assets/RegexSyntaxHighlighting.gif)

To give a much crazier example of what you can do with formatters, I point you to [PowerArcade](https://github.com/StartAutomating/PowerArcade) (which is built using EZOut):

![Nibbles2020](https://github.com/StartAutomating/PowerArcade/raw/master/Assets/Nibbles2020.2.gif)

This formatting will work in any PowerShell where $host.SupportsVirtualTerminal.

Thus I believe that we can accomplish this scenario in a way that works for every PowerShell user, not just for Core.  Furthermore, we have the opportunity to solve this scenario in ways that are more forward-looking than simply tweaking a table.

# How EZOut does it

It's only been fairly recently that I've dusted off EZOut and began adding advanced formatting scenarios.

To get colorized properties in Tables and Lists, I create a -VirtualProperty in a formatter that prepends the text with colorization and appends text that clears the colorization.

Originally, I did this inline, which made the formatter files get larger than I would like.

I've since switched to using a \Parts subdirectory, which contains little script files they can use to directly style.  The used \Parts are then placed in the .format.ps1xml, and loaded as a side-module when the formatter first needs them.

With this in hand, I can write formatters that change colors dynamically within the same control, by using code in my formatter like . $SetOutputStyle -ForegroundColor '#ff0000' -Bold -Underline ; 'My Red output'; . $clearOutputStyle

While this has expanded _a lot_ in terms of capability (e.g. bolding, underline, and dual-mode formatting (ANSI/HTML)), it's not yet as elegant and discoverable as I tend to like PowerShell to be.

# A More Elegant Suggestion and an underused verb

After much reflection, I think the _right_ move here is to create a set of advanced formatting commands, for instance:

~~~
# Formats text in RED
Format-RichText -ForegroundColor '#ff0000' -Content "My Red Output"
~~~

Or:

~~~
# Formats a value into a heatmap.  Hot and Cool are the color when -ge maximum or -le minimum, respectively.  Values in between will have a color between these two points.
Format-HeatMap -Value 5 -Min 3 -Max 7 -Hot '#ff0000' -Cool '#00ff00'
~~~
This would be more discoverable than the example above, and, gives us a forward-looking way to present things.  If there's any way we'd like to write fancy output for a given object, we can use Format-X to do so.

We could either produce an additional module of fancy formatting that can ship to all versions of PowerShell, or more and more of this functionality can be added to EZOut, with more and more demos on how to use it interactively.

Either way, if we decide to meet this need by providing a module full of Format- commands, we get the following benefits:

* Backwards compatibility
* Extending the formatting engine without moving heaven and hearth
* Potentially Multi-platform output
* Ease of discoverability
* Ease of interactive use

**Comment by SteveL-MSFT** [comment]
Fixed via https://github.com/PowerShell/PowerShell/pull/13758
