### ISSUE TITLE
Update Notification shows only the next immediate version instead of latest

### ISSUE THREAD

**Issue by kvprasoon** [PowerShell/PowerShell#11930]
Below is the update notification when checked from RC.1 . It shows the notification for RC.2 even after RC.3 is released. Correcting this will help for future versions.

![image](https://user-images.githubusercontent.com/12897753/75096947-ddbb0f00-55ca-11ea-9e69-c00b7b6e6257.png)

**Comment by daxian-dbw** [comment]
@kvprasoon The subsequent pwsh sessions will show the notification of rc.3, right?
This is because the pwsh on your machine hasn't got a chance to find that rc.3 is released.
The rc.2 release was previously detected and cached locally. When pwsh starts, it shows the cached information and then query for the latest information, which will be used the next time pwsh starts.

From the user's perspective, you have been seeing this rc.2 message for quite a while.
Even though for this startup, it shows an out-dated information, but the correct information will be shown on the next pwsh startup. So there won't be much delay before you see the latest update information.

Also, it's called out in the [RFC](https://github.com/PowerShell/PowerShell-RFC/blob/master/5-Final/RFC0052-Notification-On-Version-Update.md#non-goals) the following is not a goal:
> Notification shows up right after a new version of `pwsh` is released.
