### ISSUE TITLE
Add ExchangeOnline and AzureAD modules to Compatibility Deny list

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell#11932]
# Summary of the enhancement

With RC3 comes the compatibility deny list to stop modules we know can't work in PWSH7 from being loaded. There are currently three modules in the deny list. I believe this is a great feature that stops the user from seeing things they can't fix. 

I would like to suggest adding **AzureAD** and **ExchangeOnline** modules to the deny list. 

As noted in #11903, the AzureAD module results in errors when used. It is better to just not load them than to expose the user to the results of incompatibility.  The Exchange Online module also fails in the same way. If you add this module, then adding the MSOnline module too. While MSOnline is 'old'. it is I am sure in use.  

Not allowing modules we know do not work seems a safer approach.

# Proposed technical implementation details (optional)

Add ExchangeOnline, AzureAD modules to the deny list.
Consider adding MSOnline

**Comment by alexandair** [comment]
Both, AzureAD and ExchangeOnlineManagement modules work in PowerShell 7 RC3 (see attached images).
<img width="554" alt="AzureAD" src="https://user-images.githubusercontent.com/3135708/75112568-65ddfa80-5645-11ea-9a6a-bfe610bbb6b6.png">
<img width="623" alt="ExchangeOnlineManagement" src="https://user-images.githubusercontent.com/3135708/75112576-6c6c7200-5645-11ea-8ebb-da7962dc794a.png">

**Comment by sassdawe** [comment]
I've just ran into this.

The `AzureAD` module was imported fine without `-UseWindowsPowerShell`, but then I got a cryptic `could not load type` error when I tried `Connect-AzureAD`... Google led me here, so I tried again using `-UseWindowsPowerShell`, and it worked \o/

Naturally, after successfully connecting to AzureAD I wanted to use a method which was left off thanks to the deserialization.

I get that these modules are _importable_ by PowerShell but **I agree with the idea** to put them on the Deny list, and that's what I'm going to do on the machines I manage, because deserialization breaks all my scripts.

**Comment by JAK1047** [comment]
From my company's internal contact with Microsoft we have been instructed that there are no current intentions to make the AzureAD module core compatible as the current goal is a replacement by the MS.Graph module. As for ExchangeOnline that has of course already been replaced by the EXO V2 module of ExchangeOnlineManagement which is already core compatible.

Both work when imported using compatibility to load them in Windows Powershell, but just wanted to share that information in case anyone else stumbles across this thread since the future compatibility of the AzureAD module seems to be a popular subject.

**Comment by kilasuit** [comment]
Instead of adding them to a deny list we could improve potentially the logic in Import-Module to auto import them using the `-UseWindowsPowerShell` parameter & mitigate the user having to call that themselves.
Possibly not the cleanest way to do it but resolves users needing to remember to do so but would make the user journey more consistent with original designs that it will do what it can to make users lifes easier

**Comment by sassdawe** [comment]
> Instead of adding them to a deny list we could improve potentially the logic in Import-Module to auto import them using the `-UseWindowsPowerShell` parameter & mitigate the user having to call that themselves. 

Some of object which are being returned by **AzureAD** could be impacted by the deserialization which makes their usage less than idea, l so I stopped using it with PowerShell 7. This could be on thing to consider.

**Comment by doctordns** [comment]
I have elsewhere suggested that the startup JSON have a section listing modules we KNOW have to be loaded using compatibilty mode.  This would look much like the current DENY list, but listing modules which Import-Module will by default load using compatibility mode.

There are regular issues in this repo raised when modules don't load normally, but work fine if you use `-UseWindowsPowerShell` - It would be nice to get a more elegant solution.
