### ISSUE TITLE
pwsh doesn't parse positional negative integer parameters correctly

### ISSUE THREAD

**Issue by curegit** [PowerShell/PowerShell#11939]
I found the `pwsh` command doesn't parse positional integer parameters as expected when they are negative. This doesn't happen if you use the `powershell` command in windows cmd.

# Steps to reproduce

`script.ps1` is as below.
```powershell
Param([Int]$number)
Write-Host $number
```

# Expected behavior

```none
$ pwsh script.ps1 -1
-1
```

# Actual behavior

```none
$ pwsh script.ps1 -1
0
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.4
PSEdition                      Core
GitCommitId                    6.2.4
OS                             Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
@curegit can you verify the behaviour when explicitly using `-Command` v.s. `-File` parameters for pwsh and powershell?

```
pwsh -Command Script.ps1 -1
powershell -Command Script.ps1 -1

pwsh -File Script.ps1 -1
powershell -File Script.ps1 -1
```

**Comment by curegit** [comment]
@vexx32 

```bat
>powershell -Command script.ps1 -1
-1

>powershell -File script.ps1 -1
0

```

```sh
$ pwsh -Command ./script.ps1 -1
-1
$ pwsh -File ./script.ps1 -1
0
```

It doesn't make sense to me. I think all characters appeared after the File parameter are interpreted as script parameters from seeing the `pwsh` help.

**Comment by vexx32** [comment]
Yeah, I'm not clear on why there's this difference here. @mklement0 I think has run into this before and might have some insight here...

But the reason for the difference between pwsh and powershell when not specifying -Command or -File I think is due to the default action being changed between WinPS and pwsh.

**Comment by mklement0** [comment]
Thanks, @vexx32 : indeed, the default CLI parameter has changed from `-Command` to `-File` in PowerShell Core, so as to properly support Unix shell scripts with shebang lines.

`-File` fundamentally processes the arguments that follow the target script path differently than `-Command`:

`-File` interprets the arguments _verbatim_ rather than subjecting them to the usual in-process parameter-parsing and binding (which `-Command` also does).

However - and this appears to be the bug at hand - `-File` apparently _blindly_ interprets `-`-prefixed tokens as parameter _names_, even though `-1` is during regular (in-process) parsing is _never_ considered a parameter _name_, because parameter names starting with a _digit_ aren't supported.

In effect, it seems, `-1` is mistakenly treated as an _undeclared (switch) parameter_, which is collected in `$args` rather than being bound _positionally_, as a _number_, to parameter `-number`.

You can verify this by declaring `script.ps1` as follows, using the `[CmdletBinding()]` attribute to cause _undeclared_ parameters / arguments to cause an _error_:

```powershell
[CmdletBinding()]
param([Int]$number)
"-number: [$number]"
```

-> `A parameter cannot be found that matches parameter name '1'`

The only workaround is to use `-number -1` (_named_ argument passing) instead of `-1`; `(-1)` is _not_ an option, due to the aforementioned _verbatim_ interpretation of the arguments.

Note that a variation of this issue has come up before with respect to Booleans passed to `[switch]` / `[bool]` parameters and has _partially_ been fixed in https://github.com/PowerShell/PowerShell/pull/4178/files, though #10838 remains unsolved.
