### ISSUE TITLE
Link to global session state silently fails to invoke from non-top scopes

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#11951]
When PowerShell is executing within a module session state that is linked to the global session state it invokes only commands found in the top scope of the global session state.  ~~It's not clear to me whether that is the design intent.~~ _(Edit: [This is is indeed the design intent.](https://github.com/PowerShell/PowerShell/issues/11951#issuecomment-591044394))_  The relevant background seems to be as follows:

* The behavior of the link to global session state changed somewhere between PowerShell 5.1 and 7.0.  As much can be observed by invoking the below repro in 5.1 and 7.0.
* [@Izybkr provided his interpretation of design intent with respect to searching session states](https://github.com/PowerShell/PowerShell/issues/6139#issuecomment-364262570)  but not with respect to searching child scopes of the global session state.

---
Update:

The issue that remains is that when a function exists only in a non-top scope of the global session state PowerShell seems to find that function but silently _not_ invoke it.  This is demonstrated in the repro by `f` neither being invoked nor an error message begin produced.

---

# Steps to reproduce

```powershell
function e {'e'}
& {
    function f {'f'}
    New-Module {
        function a { e }
        function b { f }
        function c { g }
    } | Import-Module
    a
    b
    c
}
```

# Expected behavior

```none
e
f
g: C:\\test.ps1:7
Line |
   7 |          function c { g }
     |                       ~
     | The term 'g' is not recognized...
```

# Actual behavior PowerShell 7

```none
e
g: C:\test.ps1:7
Line |
   7 |          function c { g }
     |                       ~
     | The term 'g' is not recognized...
```

# Actual behavior PowerShell 5.1

```none
e : The term 'e' is not recognized as the name...
...
At C:\test.ps1:5 char:22
+         function a { e }
+                      ~
...

g : The term 'g' is not recognized as the name...
...
At C:\test.ps1:7 char:22
+         function c { g }
+                      ~
...
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0.}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
You may want to try to write this up a little more clearly -- with single letter function names and returns, this is a bit confusing. Maybe add a mention that it's expected `g` should be found 

But what you seem to be saying is that the function `b` should not be able to find the function  `f` and should error out... but the error is missing (though the lack of output indicates it still can't find it).

The additional error from 5.1 looks like another bug that has since been fixed, I think.

Interesting... makes me wonder how defining a module with `New-Module` is _supposed_ to work -- i.e., what are the actual design expectations of the cmdlet in terms of how it handles a module that tries to reference things that aren't available from the global session state. It seems more logical to me that it simply can't see them, since it is after all a module, but it looks like the fact that `f` is both defined and then called from the same scope (albeit via the module, which _should_ only see the global scope) is definitely an edge case that's not been accounted for properly.

**Comment by bpayette** [comment]
@alx9r  The description @lzybkr provided is pretty complete.

> it invokes only commands found in the top scope of the global session state. It's not clear to me whether that is the design intent.

Yes - it is definitely the design intent. The goal was that the dynamic environment of the calling function should not interfere with the module command being called. That said, modules are coupled to the global session state because to do otherwise would be prohibitively expensive. Every module would have to include it's own private copy of the cmdlet table, etc.

WRT the example output, I get:
```powershell
e
f:
Line |
   6 |         function b { f }
     |                      ^ The term 'f' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
g:
Line |
   7 |         function c { g }
     |                      ^ The term 'g' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
So - a is executed and emits 'e' as expected, and b (f) and c (g) result in errors because they are not in scope for the module functions. Everything is as expected.

**Comment by alx9r** [comment]
>Yes - it is definitely the design intent. The goal was that the dynamic environment of the calling function should not interfere with the module command being called. That said, modules are coupled to the global session state because to do otherwise would be prohibitively expensive. Every module would have to include it's own private copy of the cmdlet table, etc.

Got it @bpayette.  Thanks for the clarification.

It looks like you and I are not seeing the same results from the repro.  I get no output or error from the call to `f`.  You get 

```
e
f:
Line |
   6 |         function b { f }
     |                      ^ The term 'f' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
g:
Line |
   7 |         function c { g }
     |                      ^ The term 'g' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

while I get

```
e
g: C:\test.ps1:7
Line |
   7 |          function c { g }
     |                       ~
     | The term 'g' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
     | spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Can you post your `$PSVersionTable`?

**Comment by alx9r** [comment]
@vexx32 

>Interesting... makes me wonder how defining a module with New-Module is supposed to work...

I think you'll find some answers to the questions your were wondering about in [this post (beginning at "A scriptblock...")](https://github.com/PowerShell/PowerShell/issues/6139#issuecomment-364262570) and [this post](https://github.com/PowerShell/PowerShell/issues/11951#issuecomment-591011031).

Is there any chance you could post your output and `$PSVersionTable` from the repro?  The output that @bpayette and I are seeing differs.  I'm looking for clues about the cause of the difference.

**Comment by bpayette** [comment]
@alx9r  I've tried it in 5.1, 6.2.4 and headrev sync'ed and built about an hour ago. All three cases produces the same results: a(e) works fine and I get errors on b(f) and c(g). The fact that you are getting a different result is very strange. Probably a stupid question but are you sure you don't have an 'f' command or script in your environment?

**Comment by alx9r** [comment]
@bpayette 
> Probably a stupid question but are you sure you don't have an 'f' command or script in your environment?

Not a stupid question at all.  That was indeed the culprit: A function named 'f' in a module I used for another repro.  Thanks for your help.
