### ISSUE TITLE
Out-Gridview not included in Microsoft.PowerShell.Utility for pwsh 7.0

### ISSUE THREAD

**Issue by yobyot** [PowerShell/PowerShell#12018]
# Steps to reproduce

```
# Check pwsh version
$PSVersionTable
# Look for OGV in Microsoft.PowerShell.Utility
If (!(gcm -Module Microsoft.PowerShell.Utility | ? Name -like Out-GridView)) {"No OGV!"}
```

# Expected behavior

`[Microsoft.PowerShell.Utility]`
(https://docs.microsoft.com/en-us/powershell/scripting/whats-new/cmdlet-versions?view=powershell-7#microsoftpowershellutility) states `Microsoft.PowerShell.Utility` contains `Out-GridView`.

# Actual behavior

```
'out-gridview' is not recognized as the name of a cmdlet, function, script file, or operable program.
```
See screenshot below.

# Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
<img width="1099" alt="2020-03-04_19-27-06" src="https://user-images.githubusercontent.com/14332263/75935764-2f2a9000-5e4e-11ea-9390-cd27cc023475.png">

**Comment by rjmholt** [comment]
Classic `Out-GridView` is only available for Windows, since it's WPF code. It's been brought back for compatibility purposes but there are no plans to ship a cross-platform version in the base installation.

The recommended way to go is to [install Microsoft.PowerShell.GraphicalTools](https://www.powershellgallery.com/packages/Microsoft.PowerShell.GraphicalTools/0.2.0), as PowerShell is moving to modularise the base installation better.

In light of https://github.com/PowerShell/PowerShell/issues/11179 I have opened https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5522.

**Comment by rjmholt** [comment]
I've also opened https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5523
