### ISSUE TITLE
Where is the AD modules an AdminCenter

### ISSUE THREAD

**Issue by ohlssrog** [PowerShell/PowerShell#12065]
# Summary of the new feature/enhancement
Where is the ActiveDirectory modules for Linux PS and does PS 7 support Windows Admin Center?

# Proposed technical implementation details (optional)

**Comment by doctordns** [comment]
My understanding is that the AD cmdlets do not run natively on non-Windows platforms. And if this is to happen, it is the AD Team that, probably, would need to do the work.

**Comment by vexx32** [comment]
Yep, the APIs used by the ActiveDirectory module do not function under Linux and likely never will, unless someone wants to add similar capabilities into the Linux operating systems and/or kernel itself.

At least, that's my understanding. The ActiveDirectory team(s) may have some ideas how that could be worked around (one possible idea is to rewrite the module to work with PSRemoting to the DC instead of using platform-specific protocols to communicate with the DC), but that is at best a blind guess. I've not had the chance to really look through the source code, and I'm not sure we ever will (I don't think it's been published anywhere, least not that I've been able to find up till now).

As a result, this discussion is kind of moot and entirely reliant on the ActiveDirectory team to figure something out, as it were. 🙂 

I hope that answers some of your questions, but the PowerShell team themselves don't maintain or probably even have access to this module's source code, so all they can do is poke the AD team(s) and ask them to Git Gud(tm). 😄
