### ISSUE TITLE
Tasks in linux

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#12090]
There is no way to create a persistent local task, the session will be closed or disconnected and the task will terminate.

In addition, `nohup` has `&` characters and cannot be used in powershell
# Steps to reproduce

```powershell

```

# Expected behavior

```none

```

# Actual behavior

```none

```

# Environment data

```none

```

**Comment by mklement0** [comment]
If you would like to see a PowerShell-native solution, I suggest you flesh out your proposal with more details and use cases.
Generally, please use the right issue template, and fill in the section templates.

> In addition, nohup has & characters and cannot be used in powershell

The `nohup` utility doesn't itself use `&`; it is typically called with _Bash_'s postpositional `&` operator so as to launch the program passed to `nohup` _in the background_, given that `nohup` itself executes synchronously.

While using _PowerShell's_ `&` background operator (or `Start-Job`) isn't an option, because terminating the job will also terminate child processes launched from it, you can use `Start-Process` to achieve the desired effect.

The following example launches a background PowerShell instance that stays alive even after you close the launching terminal; it emits a `.`  every second, and `nohup` collects both stdout and stderr output in file `nohup.out` in the current directory:

```powershell
Start-Process nohup 'pwsh -nop -c "while ($true) { write-host . -nonewline; sleep 1 }"'
```

**Comment by he852100** [comment]
It does not have a consistent experience, so what is the significance of the existence of powershell?

**Comment by mklement0** [comment]
To recap:

* Your initial post contained a cursory reference to a scenario that currently isn't natively supported in PowerShell (and generally has no direct, tool-based implementation _on Windows_).

   * I encouraged you to detail the scenario, make a case for it, and perhaps suggest a design / implementation. I personally can see that providing PowerShell-specific, cross-platform support (including in Windows) for this scenario could be useful.

* Your initial post also contained misleading information about `nohup`, which I've tried to correct, along with showing how make `nohup` work in PowerShell, after all.

  * If you disagree with the correction or have a problem with the workaround, please argue specific points.

As you can see, there are constructive ways to respond to the feedback you've been given; your previous comment doesn't fall into that category.

**Comment by kasini3000** [comment]
@mklement0 

1 Why should I use ‘nohup + bash’ in powershell?
My main powershell process needs to exit, and keep subprocess run（bash）
using bash -c instead of pwsh -c, mainly because pwsh occupies more memory.

2 How to use nohup + & in powershell?
$nohupargs = @"
bash -c "docker pull xxx"> /dev/null 2>&1 &
"@
Start-Process -FilePath /usr/bin/nohup -ArgumentList $nohupargs

3 What's wrong with this use?
This usage is not perfect, "> /dev/null" does not work,"nohup.out" file always found.
if main process is bash ,"> /dev/null" will work.

**Comment by kasini3000** [comment]
oh,I was the one who just got stuck. With start-process, nohup is not needed.

**Comment by mklement0** [comment]
@kasini3000 

You _do_ need `nohup` if you want the process to stay alive after exiting the originating shell.

It is only on Windows you don't need it, because `Start-Process` can create separate console windows there, which you can hide with `-WindowStyle Hidden`; e.g.:

```powershell
# Runs for 2 minutes and collects all output in ./out.txt
Start-Process -WindowStyle Hidden pwsh '-c "1..120 | % { Write-Output . >> out.txt; sleep 1 }"'
```

---

There's no need to involve `bash` in your example, assuming you don't mind collecting output in `nohup.out`:

```powershell
# Short for: Start-Process -FilePath /usr/bin/nohup -Args 'docker pull xxx'
Start-Process /usr/bin/nohup 'docker pull xxx'
```

If you do want to suppress all output, you can do what you did, except you don't need the trailing `&`, and you must place the redirections inside the `-c` argument:

```powershell
Start-Process /usr/bin/nohup 'bash -c "docker pull xxx >/dev/null 2>&1"'
```

However, note that `nohup` _always_ creates a `nohup.out` file - even if no output is produced.
(If there _is_ output and a `nohup.out` file already exists, it is _appended_ to.)

**Comment by kasini3000** [comment]
It turned out to be so, thank you
