### ISSUE TITLE
Feature Request: Efficient remoting implementation

### ISSUE THREAD

**Issue by m5x** [PowerShell/PowerShell#12123]
While exploring possibility to use PowerShell remoting for distribution of binary data I noticed current implementation is quite inefficient for such usage. I estimate something between 1/4 and 1/3 of data overhead because chatty SOAP/XML is used and especially because binary data are sent as base64 encoded strings.

I understand its a heritage from the old days but the overhead is quite big so it would be great to have a more efficient alternative. I'd give all my votes to adding a extensible remoting interface that would allow for custom transport providers to be developed but if that's not feasible then at least a binary protocol with binary serializer as mentioned in #2852 would be great .

**Comment by doctordns** [comment]
At the time PowerShell came into existence, WInRM, Soap, etc were all the rage.  XML was a great solution (at the time) for serialization of complex objects. It works and works well - although there is some overhead.

If we knew then what we know now,  things might have been implemented differently, but we are where we are.  

And you can use SSH to remote but it does need some setup.

**Comment by iSazonov** [comment]
PowerShell remoting is very sensitive area because of compliance and security requirements.
PowerShell remoting is based on some standard protocols (PSPR, WSMan). Changing (or replacing) these protocols is very complex and long time task. In fact, this is not realistic to change for reasons of backward compatibility too.

All this does not exclude the use of alternative solutions, modules, designed specifically to solve this problem. I can’t indicate specific solutions, but I hope they exist. The capabilities of PowerShell allow you to utilize the capabilities of almost any API.
