### ISSUE TITLE
Get-Content -AsByteStream -Raw causes pwsh to hang

### ISSUE THREAD

**Issue by DanielSSilva** [PowerShell/PowerShell#12131]
# Steps to reproduce

```powershell
Get-Content -AsByteStream ./powershell-7.0.0-linux-arm32.tar.gz -Raw
```

# Expected behavior

```none
The bytes being dumped into the console, like what happens without the -Raw switch
```

# Actual behavior

```none
pwsh hangs and crashes. When on pi, I have to do CTRL+Z to stop the process. @SteveL-MSFT reports that on mac the pwsh crashes.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Linux 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
This issue results after [this](https://twitter.com/DanielSilv9/status/1237501514215837696) twitter thread

**Comment by NoMoreFood** [comment]
Cannot reproduce under Windows.

**Comment by DanielSSilva** [comment]
I can reproduce under Windows as well
![image](https://user-images.githubusercontent.com/6862119/76754211-a24ed300-6779-11ea-9bce-01ed98f10b98.png)

Might be relevant that the file is 45mb. with 1.8mb zip (1image) it hangs for a little bit and then starts dumping.
It behaves like the -Raw switch is loading the content into a buffer and after finishing it it starts dumping, whereas without the -Raw switch it starts dumping immediately

**Comment by daxian-dbw** [comment]
Just tried on mac, it didn't crash, but took a long time to write out all bytes.

**Comment by mklement0** [comment]
@DanielSSilva, that's indeed the difference: 

Without `-Raw`, the bytes are _streamed_, i.e. emitted _one by one_, as individual `[byte]` instances _as they're being read_

With `-Raw`, by design, a `[byte[]]` array comprising all bytes in the input file is created in memory first, which is then emitted _as a whole_, as a single object.

In the streaming case, letting PowerShell collect the output in an array (`$bytes = Get-Content -AsByteStream ...`) will (a) result in an `[object[]]` array (that happens to contain `[byte]` values) and (b) will be much slower than using `-Raw`.
