### ISSUE TITLE
Strict Typing

### ISSUE THREAD

**Issue by strawgate** [PowerShell/PowerShell#12156]
# Summary of the new feature/enhancement

I'd love to see a strict mode or some other language feature to enforce strict typing (and at the same time remove the implicit casting that occurs sometimes).

Things like avoiding this:
```
[string] $test = ""
$test = @{}
$test
System.Collections.Hashtable
```

```
[string] $test = ""
$test = 7
$test
7
$test.gettype()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     String                                   System.Object
```

**Comment by iSazonov** [comment]
PowerShell is a script language and it does huge implicit castings for better UX.

**Comment by strawgate** [comment]
Agreed -- but as we start to use PowerShell for programming it would be nice to limit some of the casting, or be able to add linter checks with type hints in order to reduce unexpected run-time behavior.

Figured I'd file an issue to see what others think :)

**Comment by vexx32** [comment]
Some of that could be done quite well by PSScriptAnalyzer rules, I suppose? 🤔

**Comment by Tragen** [comment]
I also thought about this. When I explicitly tell PS that the variable is a string, it's type should never change.

**Comment by vexx32** [comment]
That is the case already:

```ps1
[string]$variable = "hello"

$variable = Get-Date

$variable.GetType() # string
```

What can cause some confusion, however, is the implicit conversions that often take place.

**Comment by mklement0** [comment]
`[string]` is especially tricky with respect to the implicit conversions, because _anything_ can be converted to a string in PowerShell.

The closest approximation of what you're asking with the current features is to use a `[ValidateScript()]` attribute (which, although not widely known, can also be applied to _variables_ not just to _parameters_ (parameter variables):

```powershell
PS> [ValidateScript({ $_ -is [string] })] $foo = 'hi'; $foo = 42
MetadataError: The variable cannot be validated because the value 42 is not a valid value for the foo variable.
```

The primary problem is that this is still only enforced at _runtime_.

The secondary problem is the unhelpful abstract error message; even though `ValidateScript` now supports an `ErrorMessage` property, it isn't used (it is only used for _parameters_) - arguably a bug.

---

> Some of that could be done quite well by PSScriptAnalyzer rules, I suppose? 

The problem is that presumably more often than not you _do_ want PowerShell's implicit conversions, as they are typically helpful. Warning about every type discrepancy could get very distracting.
