### ISSUE TITLE
Automatically convert SecureString to String in parameter binder

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#12188]
# Summary of the new feature/enhancement

If a cmdlet takes an apikey as a string, then currently you would need to know to use `Get-Secret -AsPlainText` (if using SecretManagement module) or `ConvertFrom-SecureString -AsPlainText` if the secret is stored as a SecureString.  If you forget to use `-AsPlainText`, then PowerShell will convert the object to a string (to match the parameter type) by using `ToString()`, this will result in the typename to be passed as the apikey.

As more people use the SecretManagement module, this may make it easier.

# Proposed technical implementation details (optional)

Proposal is to add a `[SecureStringToString]` attribute (hopefully someone comes up with a better name) that indicates to the parameter binder that this parameter accepts SecureStrings but automatically converts it to the plaintext string.  This prevents a `SecureString` type from accidentally being written to the console or logs and makes this conversion explicit requested by the cmdlet.

Example:

```csharp
[Parameter(ConvertFromSecureString)]
string NugetApiKey;
```

or

```csharp
[Parameter()]
[SecureStringToString]
string NugetApiKey;
```

**Comment by jhoneill** [comment]
Sounds like a good use for argument transformer classes.

**Comment by vexx32** [comment]
Hmm. I _would_ tend to prefer this were implemented as a standard transformation attribute, but that would mean the parameter's target type will show up as `[string]` rather than `[securestring]` which seems a little counter to the goal here.

Perhaps the argument transformation attribute could be extended to allow for it to define a "presenting" type, which represents expected input, which can be shown in the help preferentially to the actual parameter type and how it behaves internally in the cmdlet or function.

**Comment by jhoneill** [comment]
@vexx32 that's another reasons to prefer leaving parameters untyped. Specifying [string] or [secureString] and then passing the other gives bad results (type name or error). 
A transformer means you can say "Here's a string" or "Heres a secure string" and not worry about what is going on inside the function. `

**Comment by vexx32** [comment]
In my opinion @jhoneill an untyped parameter does the user a disservice. They can't make reasonable deductions about what input it expects without reading the help. And as much as I encourage folks to read the help when they're not sure, seeing an `[object]` typed parameter is just being unkind to users having a bad day, imo. 🙂

**Comment by jhoneill** [comment]
> In my opinion @jhoneill an untyped parameter does the user a disservice. They can't make reasonable deductions about what input it expects without reading the help. And as much as I encourage folks to read the help when they're not sure, seeing an `[object]` typed parameter is just being unkind to users having a bad day, imo. 🙂

Ah, perhaps you have spent too long in real programming
The user should not have to care ... they expect to be able to do something like 
`Stop-Vm $V `

If $V _must_ be a VM name, or the GUID which represents a VM or an object which represents the VM **that** is doing the user a disservice because they have to know they must write 
`Stop-VM (Get-VMObject -Name $V) `
or 
`Stop-VM $V.ID`

It's the programmer's job to write cmdlets and functions which serve their users , not the users job to learn how functions work on the inside in order to give the input the programmer first thought of.  And PowerShell sets that expectation. 
You can do 
```
$p = resolve-path '..\builds to workitems.txt'                                                                                                                              
$q = Get-ChildItem ..\DeadBranches.xlsx  
$r = '..\pipelines.xlsx'                                                                                                                                                    
copy $p,$q,$r -Destination temp 
```
And pass an array with a string, a fileinfo and a path Info. 
Setting the type of FileInfo causes a bunch of failures. "foo.txt"  will convert to a read-only non-existent file in a system directory if you say [FileInfo]$TextFile and the user assumes the can pass a path a string holding a path. 

Typing parameters used wisely can help both user and programmer. If there is a command which takes a count saying the $count is [int32] is fine because there is no way it could be a secure string. But often they are a sign of someone who hasn't considered that the people who will use the finished code will want flexibility. In the end it comes down to are functions APIs or User interfaces ? Of course they are both, but an acceptable API can be a horrible and frustrating UI. A good UI rarely makes a poor API

[end rant]

**Comment by vexx32** [comment]
Flexibility is a good thing @jhoneill but there are limits, depending on how the code is designed.My point is not that there _shouldn't_ be flexibility -- I make extensive use of transformation attributes for better UX. However, I do think that the help metadata attached to a cmdlet (which the parameter type is _always_ a part of, whether you like it or not; it's reported by Get-Help and forms part of the implicit documentation for a command).

I'm a fan of it being as flexible as is reasonably possible, but I'd also prefer as specific a type given to the cmdlet parameter from a user perspective as is reasonable. Users that see `[securestring]` typically can infer the purpose of the input and that it will require potentially sensitive information passed in. 

Allowing the flexibility to input a string is great for some applications (and yes, securestring isn't secure, that's a whole other topic; I'm talking about user expectations here), but if we type the parameter itself as `[string]` or `[object]` and that's what shows up in the `Get-Help` or `Get-Command -Syntax` result for that parameter, we're doing the user a disservice by not properly communicating that the command may be handling sensitive data.

**Comment by daxian-dbw** [comment]
Always allowing a `SecureString` object to be converted to a string during parameter binding might be too loose.
Imagining a helper function `Write-Log [-message] <string>`, the auto SecureString-to-string conversion in parameter binding could accidentally result in plain text password being written to the log.
 
How about having a heuristic check on the parameter name, just like what Lee did to scrub sensitive command lines from history?
So the auto conversion happens only when the parameter name looks like something that accepts a sensitive string.

**Comment by JamesWTruher** [comment]
Can we get a real example on how you think this should look? What does the user have, and what does he type, and how does he use it? How would it deal with being handed a real `securestring`?

**Comment by SteveL-MSFT** [comment]
Example of a case where transformation would improve the experience:

Currently:
```powershell
Publish-Module -Name foo -NugetApiKey (Get-Secret mykey -AsPlainText)
```

Desired:
```powershell
Publish-Module -Name foo -NugetApiKey (Get-Secret mykey)
```

**Comment by SteveL-MSFT** [comment]
Alternate proposal would to automatically, within the parameter binder, always convert a `SecureString` to a `string` by extracting the plain text secret rather than using `ToString()`.  This does mean that scripts would not be portable between 7.1+ and downlevel, but users may decide this tradeoff is worthwhile and have a `#requires -version 7.1` at the top of script.  However, it seems that there may be some security concerns doing this but I don't have any specific examples where this could be a problem.  Thoughts?

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this, we have some concerns:

- requiring an attribute limits adoption to module authors that only target 7.1+
- allowing automatic conversion from SecureString to String means you can't share scripts with older versions of PowerShell so also limits usage to 7.1+ runtime
- requiring `-AsPlainText` makes it clear for anyone reading the script that the output will be a string

Decision is to not make any changes for this.

**Comment by jhoneill** [comment]
I will might work the following up into a blog post, unless someone tells me it is a very bad idea. 

```Powershell
class UnSecureString : System.Management.Automation.ArgumentTransformationAttribute  {
    [object] Transform([System.Management.Automation.EngineIntrinsics]$EngineIntrinsics, [object] $InputData) {
        if ($InputData -is [securestring]) {
            $InputData =  New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList 'Placeholder', $InputData
        }
        if ($InputData -is  [pscredential]) {
            $InputData =  $InputData.GetNetworkCredential().password
        }
        return ($InputData)
    }
}

Function Demo {
   [cmdletBinding()]
   param(
   [UnSecureString()]
   [string]$ApiKey
   )

   "Your API key is $ApiKey"

}
```

Results:

```
>demo "api12345key"

Your API key is api12345key

>$ss = ConvertTo-SecureString -AsPlainText "api34567key" -Force
>demo $ss

Your API key is api34567key

>$cred = New-Object pscredential "NoRealName", $ss
>demo $cred

Your API key is api34567key

```

Works on 7.0 and 5.1 :-)

**Comment by vexx32** [comment]
👍 

@SteveL-MSFT you could just make a small binary module and ship that to the gallery since it can work for both versions. It'd just be in-box in 7.1+
