### ISSUE TITLE
ConvertFrom-Json includes $null element on output if input starts with blank line

### ISSUE THREAD

**Issue by krishnayalavarthi** [PowerShell/PowerShell#12229]
# Steps to reproduce

```powershell
PS D:\> @('{"common":[1,2]}' | ConvertFrom-Json).Length
PS D:\> @('','{"common":[1,2]}' | ConvertFrom-Json).Length
PS D:\> @('','','{"common":[1,2]}' | ConvertFrom-Json).Length
PS D:\> @('{"common":','[1,2]}' | ConvertFrom-Json).Count
```

# Expected behavior

```
PS D:\> @('{"common":[1,2]}' | ConvertFrom-Json).Length
1

PS D:\> @('','{"common":[1,2]}' | ConvertFrom-Json).Length
1

PS D:\> @('','','{"common":[1,2]}' | ConvertFrom-Json).Length
1

PS D:\> @('{"common":','[1,2]}' | ConvertFrom-Json).Count
1
```

# Actual behavior

```
PS D:\> @('{"common":[1,2]}' | ConvertFrom-Json).Length
1

PS D:\> @('','{"common":[1,2]}' | ConvertFrom-Json).Length
2

PS D:\> @('','','{"common":[1,2]}' | ConvertFrom-Json).Length
2

PS D:\> @('{"common":','[1,2]}' | ConvertFrom-Json).Count
1
```

# Environment data

```none

```

**Comment by strawgate** [comment]
As far as I can tell this is by-design for the json cmdlets.

Essentially they can operate in two modes:
1. What you've passed is a series of stringified json elements that you'd like each converted from json into objects
2. What you've passed is a series of "lines" of a json document that you'd like concatenated and converted from json into objects

This allows you to do things like:
`Get-Content .\file.json | convertfrom-json`

Without having to first join the "lines" of the file.

To do this, the cmdlet tries to convert the first element you passed it and if that element is valid json on its own then it assumes every element you pass is valid json on its own. If it is not valid json it assumes you want the cmdlet to concatenate the results and convert that to json.

**Comment by iSazonov** [comment]
I guess main question is for 3d case - we send 2 empty string but get result as for 2d case with 1 empty string. Then `@('','' | ConvertFrom-Json).Length` return 2 too.

**Comment by strawgate** [comment]
I see the bug -- there is a bug in the logic when there is more than 1 element passed in and the first element in the sequence is a null.

Basically the code tests the first element that is passed in to decide whether it should treat each entry as a json object or if it should join them. It gets the first element and attempts to convert it from json, this works so it emits the first object into the pipeline (a null).

The current logic, slightly shortened:

```
                        // Try to deserialize the first element.
                        successfullyConverted = ConvertFromJsonHelper(_inputObjectBuffer[0]);
                        // if this is passed a json null it will write that null to the pipeline
                        // but it will fail the next if check and pass to a function that doesnt know you already wrote something to the pipeline
                   
                    if (successfullyConverted)
                    {
                        for (int index = 1; index < _inputObjectBuffer.Count; index++)
                        {
                            ConvertFromJsonHelper(_inputObjectBuffer[index]);
                        }
                    }
                    else
                    {
                        // Process the entire input as a single Json content.
                        ConvertFromJsonHelper(string.Join(System.Environment.NewLine, _inputObjectBuffer.ToArray()));
                    }
```


Now that the first entry has worked we proceed to the next step. The next step checks to see if the first step worked by checking what it returned. Under normally circumstances this would be a 5 or something and then it would proceed to treating all the other entries as discrete json objects. But when the first json value is actually a null it thinks this means it failed the conversion and then it concatenations all of the entries and converts them together. It has no idea that the test-parse emitted a null into the pipeline.

So the 2 count is it writing the first null element into the pipeline and then followed by the object that was emitted.

It looks like this could be fixed by adding an `out error` to `ConvertFromJsonHelper` and that would allow `EndProcessing()` to check the error state instead of checking the value returned from json parsing.

**Comment by iSazonov** [comment]
I believe current magic behavior was designed for multi-line Json input - scenario like `Get-Content | ConvertFrom-Json`.
Another common scenario - every input string is full and correct Json.
I think we should preserve the scenarios.

Are there other so popular scenarios we should preserve too? I do not know such ones.

Current heuristic is very buggy. The issue demonstrate this. We can easily think other broken scenarios. Automatic merging of input objects may also be undesirable. Then I see the cmdlet can throw terminating error while enumerating - it is wrong behavior.

This force me think we should add new switch to disable auto merge input strings - NoInputCollect.

/cc @mklement0 Have you thoughts?

**Comment by mklement0** [comment]
Makes sense, @iSazonov; alternative name suggestion for the new switch: `-Each`?

As a general tip: Using `Get-Content -Raw .\file.json | ConvertFrom-Json` both eliminates ambiguity and noticeably improves performance.

**Comment by strawgate** [comment]
How do we decide when we add a parameter to the cmdlet versus just providing a workaround?

I believe something like:
`@('','5','','','','') | %{ convertfrom-json $_}`

Would prevent the auto-merging of input strings if that were desirable

**Comment by mklement0** [comment]
That certainly works, but amounts to a significant slowdown - though perhaps that's not a concern in practice (I have no good sense of how common this use case is, and I don't feel strongly either way).

**Comment by strawgate** [comment]
The current behavior is that it only concatenates them if there is an issue with the first element. So an -each would print an error for the first element and continue deserializing the remaining elements?

**Comment by mklement0** [comment]
Yes, that would be in line with the error-handling guidelines: an error with _one_ input object that doesn't prevent processing additional input objects should result in a _non-terminating_ error.

**Comment by iSazonov** [comment]
Thinking more about the cmdlet I concluded we need to make a mandatory breaking change.

_Main reason is the cmdlet has unpredictable behavior in a pipeline._

Although the intention of the current design is clear - it covers scenarios like `Get-Content "file.json" | ConvertFrom-Json` - in all other scenarios the heuristics used leads to unpredictable and broken behavior.
Examples:
1. See OP
```powershell
@('','{"common":[1,2]}' | ConvertFrom-Json).Length    # Returns 2
@('','','{"common":[1,2]}' | ConvertFrom-Json).Length  # Returns 2 (!)
```
2. Process many files
```powershell
dir -Path "file*.json" | Get-Content | ConvertFrom-Json
```
Some files will be merged in unpredictable ways depending on their contents!

It would be even worse if the files were sorted before processing:
```powershell
dir -Path "file*.json" | Sort-Object -Property LastWriteTime | Get-Content | ConvertFrom-Json
```

Let's see [Json standard](https://datatracker.ietf.org/doc/html/rfc8259#section-2). `JSON text` is defined by two conditions:
1. A JSON text is a sequence of `tokens`.
2. A JSON text is a serialized `value`.

Note the `value` is in the _singular_.
Thus, each input string (including a multiline string) must contain a single JSON value.

The key question is, are there any well known scenarios (other than `Get-Content | ConvertFrom-Json`) where a string like this is broken into parts?
I don't know of any and can't find of any. All known configuration files are `JSON object`-s. If someone does serialization, they get a whole single string and we should expect it to be deserialized in its entirety.

So my proposal is:
1. Remove the heuristic at all
2. Process every input string separately as an JSON value.
2.1 We get predictable, standard-compliant behavior 
2.2 We can write correct non-terminating errors for broken input strings
3. If there is a concern that `Get-Content | ConvertFrom-Json` scenario is too frequent we could directly address it in code and documentation.
(Although the following will work differently `$a = Get-Content; $a | ConvertFrom-Json` - would be documented too).

**Comment by mklement0** [comment]
Two real-world impressions from my Stack Overflow activities:

* `Get-Content ... | ConvertFrom-Json` is common, unfortunately - even though the intended semantics - and performance - would call for `-Raw` (it is similar to the likewise inefficient, but also functional `[xml] (Get-Content ...)` idiom), so I'd say that breaking that is a no.
  * [This query](https://stackoverflow.com/search?q=%5Bpowershell%5D+get-content+convertfrom-json)  should give you a sense (though note that it includes false positives).

* I've personally never come across a use case where _multiple_ files are being sent to a single `ConvertFrom-Json` call.

---

What we could consider, as bucket 3 breaking changes, are tweaks to the heuristic:

* Do not emit a `$null` if there are one or more leading empty or blank input strings, because they trigger collect-all-input-first mode in which such lines should be considered incidental whitespace.

* In treat-each-input-as-self-contained-JSON mode, report _non_-terminating errors for each malformed input.

**Comment by iSazonov** [comment]
> I've personally never come across a use case where multiple files are being sent to a single ConvertFrom-Json call.

Because this cmdlet doesn't work in this scenario :-)
Although JSON is designed more for configurations, people are using it more and more to represent data, replacing other formats (primarily XML). So the scenario with multiple file processing is quite realistic.

As for breaking changes I think current design and used heuristic are _fundamentally_ broken. The only real scenario that falls under the breaking change `Get-Content | ConvertFrom-Json`, but we can add a special processing for it.

**Comment by mklement0** [comment]
> Because this cmdlet doesn't work in this scenario :-)

Good point, but I've never even seen people _try_.

So - anecdotally speaking -  no, I don't think this scenario is realistic, and even with increasing use of JSON for config files I don't see the need for processing _multiple_ ones. But if someone really needs it, it can easily be made to work by adding `-Raw`.

> I think current design and used heuristic  are _fundamentally broken_.

No argument there, but given that I think _removing_ it is not an option, what I proposed in my previous comment at least makes it work more consistently and predictably.

**Comment by strawgate** [comment]
So to summarize:
1. Remove the heuristic
2. No longer coalesce inputs and stop processing them in the endprocess() block
3. Process every input string separately as an JSON value
4. Convert the cmdlet to not throw terminating errors
5. Update documentation to suggest using -raw with get-content.
6. Look into adding special handling (using the NoteProperties get-content adds?) specifically for get-content and convertfrom-json to remain backwards compatible

Would a `-join` switch on the cmdlet make sense to allow a user to select the behavior they are interested in if they are using something other than get-content?

**Comment by iSazonov** [comment]
> 1. Remove the heuristic

Current proposal from @mklement0 is to improve the heuristic with minimal risk of a breaking change. https://github.com/PowerShell/PowerShell/issues/12229#issuecomment-874319626


Removing the heuristic we could consider later for new implementation of the cmdlet.

**Comment by iSazonov** [comment]
> Thanks, @iSazonov, though I do think we should consider strawgate's proposal, if #6 allows for a non-breaking, backward-compatible solution:

I reviewed manually some pages in GitHub search and found other scenarios where this could be broken: (1) cmdlets from Az module, (2) there are native exe-s with `-json` switch - PowerShell enumerates their output in pipeline.
On the other hand, surprisingly Get-Content is used more often with `-Raw` switch in `Get-Content -Raw | ConvertFrom-Json`.

**Comment by mklement0** [comment]
Excellent point, @iSazonov; I hadn't considered that PowerShell always reports a native executable's stdout output as a _stream of lines_.

So if we were to get rid of the heuristics (with special-casing for backward compatibility), the consistent default behavior would have to be collect-all-strings-first, and a previously discussed `-Each` switch would be required for (unconditional) per-input-object parsing.

But the question is whether that is worth the effort and special-casing. 

I'm now again inclined to think that the tweaks to the existing heuristic proposed above (https://github.com/PowerShell/PowerShell/issues/12229#issuecomment-874319626) are sufficient.

A compromise would be to combine the tweaks with a new `-Each` switch, so that _unconditional_ per-input-object parsing can be requested (which you'd get with a correctly formed (self-contained) first input string anyway, however); otherwise, the only advantages would be a clear signaling of the intent and error messages that better match that intent).

**Comment by iSazonov** [comment]
> I'm now again inclined to think that the tweaks to the existing heuristic proposed above ([#12229 (comment)](https://github.com/PowerShell/PowerShell/issues/12229#issuecomment-874319626)) are sufficient.

I think the tweak is best fix for _current_ cmdlet.
For new experimental cmdlet I'd start with simple rule: one string - one JSON, without any complications with heuristics and new switches.

**Comment by mklement0** [comment]
> For new experimental cmdlet I'd start with simple rule: one string - one JSON

That is tempting, for consistency's sake, but your native-executable example convinced me that defaulting to collecting all strings is the better default for  this _particular_ cmdlet - even though it deviates from the usual pipeline-input handling.

For instance, say I use a `curl` call (`curl.exe` on Windows) to retrieve JSON; with the proposed per-input-object processing, the following would then malfunction, and require inserting an `Out-String` call, which is both cumbersome and obscure:

```sh
curl ... | Convert-FromJson
```

**Comment by jessehouwing** [comment]
Bumped into this issue yesterday. Out of 100s of json documents, one started with a comment and blew up my logic. Adding `-raw` fixed things, but it's a bit non-obvious. It's probably with a suggestion in Vscode to add that extra switch as it looks like that's the intended behavior in most cases.

https://stackoverflow.com/q/71025659/736079

**Comment by seansaleh** [comment]
I just ran into this issue by following the Powershell Docs. If I understand this issue properly my fix, https://github.com/MicrosoftDocs/PowerShell-Docs/pull/9184 should help others avoid it in the future.


Does anyone from this thread see an issue with updating the suggested docs from:
```powershell
Get-Content JsonFile.JSON | ConvertFrom-Json
```
to
```powershell
Get-Content -Raw JsonFile.JSON | ConvertFrom-Json
```

**Comment by mklement0** [comment]
That's a good idea, @seansaleh , because using `-Raw` not only avoids the issue at hand but is preferable from a _performance_ standpoint as well.
