### ISSUE TITLE
`exit` causes obscure error in ScriptMethod ETS methods

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#12235]
Note: Calling `exit` from a function or method is unusual, but it works in functions and in _class_ methods, but not from `ScriptMethod` methods on custom objects, where it fails with an obscure error.

# Steps to reproduce

```powershell
pwsh -noprofile -c '($obj = [pscustomobject]::new()) | Add-Member -MemberType ScriptMethod Foo { exit 5 }; $obj.Foo()'
$LASTEXITCODE | Should -Be 5
```

# Expected behavior

There should be no output, and the test should succeed. 

# Actual behavior

An error is reported, and the test fails, because the `exit` statement wasn't effective (the exit code was implicitly set by the unexpected statement-terminating error, to `1`):

```none
MethodInvocationException: Exception calling "Foo" with "0" argument(s): "System error."
InvalidResult:
Line |
   1 | $LASTEXITCODE | Should -Be 5
     | Expected 5, but got 1.
```

# Environment data

```none
PowerShell Core 7.0.0
```

**Comment by bpayette** [comment]
Hi @mklement0  Here's what's happening. The `exit` keyword throws a special exception to indicate that the engine is exiting. As currently implemented, this exception is being caught by the implementation of `PSScriptMethod` in  `PSScriptMethod.Invoke()` and wrapped in a `MethodInvocationException`. Looking at the inner exception, you'll see the original exception:
```PowerShell
PS[1] (41) > $e.Exception.InnerException.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    ExitException                            System.Management.Automation.FlowControlException

PS[1] (42) >
```
IIRC this rather interesting exception handling strategy was done so that you could use script methods in F&O without worrying about infinite recursion if a method used in formatting errors had an error.
