### ISSUE TITLE
use event handler to handle errors 

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12252]
in powershell we can use **$ExecutionContext.InvokeCommand** to use different events

```
PS C:\> $ExecutionContext.InvokeCommand

CommandNotFoundAction   :
PreCommandLookupAction  :
PostCommandLookupAction :
LocationChangedAction   :

```
its usefull  but it will be  great to generalize this to errors.
example

```
# execute lambda  if error occur
PS C:\> $ExecutionContext.InvokeCommand.errorCommandAction

# execute lambda if error occur with  certain command type
PS C:\> $ExecutionContext.InvokeCommand.errorCommandbyTypeAction

```
for example:

 ```
$ExecutionContext.InvokeCommand.errorCommandbyTypeAction = $nulll
 $ExecutionContext.InvokeCommand.errorCommandbyTypeAction = {
    param($cmd, $objsender)
    
    if($cmd.name  -eq 'kill-soomething' -and $cmd.commandtype -eq 'cmdlet' )   {
           // todo
     }
 }
```

**Comment by rkeithhill** [comment]
This is similar to the suggestion I made on the RFC for Native Command Exit Error - https://github.com/PowerShell/PowerShell-RFC/pull/88#issuecomment-501386832

**Comment by bpayette** [comment]
I believe @jpsnover opened a related issue quite a while back along the lines of allowing the `-*action` parameter to take scriptblocks handlers instead of just enum values.  WRT this proposal, I'm not completely sure of the utility of what's being proposed. In most cases, `try/catch` or `trap` already address the majority of the scenarios. The one that isn't covered is creating a durable handler that survives for the whole session.  This might be interesting in an interactive session but as a global shared binding, it couldn't  be used in a reusable script safely (since more than one script might set it). Also, depending on what you're trying to do, there might be better ways to achieve it. @p0W3RH311  can you provide a practical (useful) example of how you see this being used and what problems it might solve? Thanks.  Oh - and one more clarification - would it work for non-terminating errors, terminating errors or both? Ok two clarifications - what happens after the handler runs - does the script resume, terminate or skip the remaining statements?

**Comment by vexx32** [comment]
@bpayette I'd imagine whether the script resumes or terminates following the error handler would be based on what the handler does itself. If you throw in the error handler, treat it as terminating. If not, don't.

**Comment by bpayette** [comment]
@vexx32 Currently `trap` allows you to use `break` and `continue` in the `trap` block. For example:
```powershell
 trap { write-host "trapped it"; continue } 1/0; write-host "Dude!"
```
This will catch the exception, print out the string and then resume execution _after the command that caused the exception._ On the other hand
```powershell
 trap { write-host "trapped it"; break } 1/0; write-host "Dude!"
```
breaks execution after the problematic command (this is the default behaviour).

`try/catch` works differently with execution continuing after the `try/catch` statement instead of at the next line.

This proposal is yet another way of trapping errors. Without knowing the intended scenarios, it will be hard figuring out the right semantics. For example, is it involved in non-terminating errors or only terminating ones?
