### ISSUE TITLE
Add more methods to directly add a `CommandInfo` to a `PSCommand`

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#12295]
# Summary of the new feature/enhancement

Currently `PowerShell` has a method that allows this, `AddCommand(CommandInfo)`. However, there's no supported way to add a `CommandInfo` to a `PSCommand` instance directly. PowerShellEditorServices (and likely other projects) construct a `PSCommand` instance well before actually getting to the internal `PowerShell` object, so working with `CommandInfo` directly can only be done with reflection.

# Proposed technical implementation details (optional)

```csharp
using System.Management.Automation.Runspaces;

namespace System.Management.Automation
{
    public partial sealed class PSCommand
    {
        public PSCommand AddCommand(CommandInfo commandInfo)
        {
            return AddCommand(new Command(commandInfo));
        }
    }
}
```

```diff
namespace System.Management.Automation.Runspaces
{
    public sealed class Command
    {
-       internal Command(CommandInfo commandInfo) : this(commandInfo, false)
+       public Command(CommandInfo commandInfo) : this(commandInfo, false)
        {
        }
    }
}
```

/cc @TylerLeonhardt @rjmholt

**Comment by TylerLeonhardt** [comment]
Yes, we have to use reflection to achieve this in PowerShell Editor Services:

https://github.com/TylerLeonhardt/PowerShellEditorServices/commit/cc241624f419bd81d86cac6b903b778a700b8ac2#diff-fa9220ea78f2263973eaab89e4e26572

There should be better API surface area here.

**Comment by iSazonov** [comment]
The new public API should be approved by PowerShell Committee.
/cc @SteveL-MSFT @daxian-dbw

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this, the `PowerShell` class already exposes a method `AddCommand()` that takes a `CommandInfo` so some concerns regarding passing in a `CommandInfo` from one runspace into another that may be out of date is already an issue, so from that perspective, it seems there is no concern about making this public since it's already public via the `PowerShell` class.

**Comment by bpayette** [comment]
@TylerLeonhardt `InvocationIntrinsics` has a bunch of methods for creating `CommandInfo`  objects: `GetCmdlet()`, `GetCmdletByTypename() `, `GetCommand()`, etc. and the `PowerShell` object has an `AddCommand()` overload that takes `CommandInfo`. So there's  really no need to explicitly create `PSCommand' objects.

@SeeminglyScience 
> construct a PSCommand instance well before actually getting to the internal PowerShell object, 

That seems kind of backwards. Why don't you create the `PowerShell` object first, then pass *it* around instead of the command objects? A `PowerShell` API object is really just a future computation that's reified when you call `Invoke()`. The intent of the `PowerShell` class was to hold all of the metadata for that computation.

**Comment by SeeminglyScience** [comment]
> @TylerLeonhardt `InvocationIntrinsics` has a bunch of methods for creating `CommandInfo` objects: `GetCmdlet()`, `GetCmdletByTypename() `, `GetCommand()`, etc. and the `PowerShell` object has an `AddCommand()` overload that takes `CommandInfo`. So there's really no need to explicitly create `PSCommand' objects.

Can't make a `CommandInfo` of just a generic script though.  Also can't add parameters, multiple statements, or multiple pipeline elements.

> @SeeminglyScience
> 
> > construct a PSCommand instance well before actually getting to the internal PowerShell object,
> 
> That seems kind of backwards. Why don't you create the `PowerShell` object first, then pass _it_ around instead of the command objects?

One so that we can cache instances, two so that state details like nested vs remote vs local type state can be determined way later in the code path.

> A `PowerShell` API object is really just a future computation that's reified when you call `Invoke()`. 
 The intent of the `PowerShell` class was to hold all of the metadata for that computation.

True but it's got a lot more metadata than just the command that needs to be invoked.  It's got all the streams, whether it's nested, what runspace it's going on, current invocation state.

**Comment by TylerLeonhardt** [comment]
I don't want to derail this discussion - but for context, in PSES we have this helper method to get `CommandInfo`'s for use in Intellisense help:
https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices/Services/PowerShellContext/Utilities/CommandHelpers.cs#L64-L105

because it's:
* thread safe (ish)
* the only public way of retrieving `CommandInfo`'s

I stumbled upon this internal API [`CommandDiscovery.LookupCommandInfo`](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/CommandDiscovery.cs#L728-L731) and was wondering if this could be leveraged instead since it:

* doesn't involve invoking PowerShell
* will be much faster

however... I have concerns about thread safety with that API...

@bpayette any thoughts?

**Comment by SeeminglyScience** [comment]
@TylerLeonhardt We'd still need to be on the pipeline thread or we'd hit some pretty nasty race conditions.  All of the slowness problems we have are around managing execution on that thread, I don't think skipping the command execution specifically would save us much.
