### ISSUE TITLE
I want to get out of the loop...i want unloop

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12311]
as a powershell user i want  feature uniq to powershell...i  want unloop  the loop  (this feature is implemented in Regex virtual machine loop/unloop  '**backtraking**')

powershell has enriched its language with a lot of technique from other languages ​​like splating (ruby), operators (perl/bash), a lot of feature c# , ...etc. 
it is time for other languages ​​to take idea and feature from powershell
  

```
$range =  1..100

foreach($i  in $range) {
     echo  $i
     if($i -eq 50)  {
        unloop ( $i -gt 20; $i+=2 ) {
            echo "$i"
        }
     }
}
```

in this example the second _loop_ "**unloop**" backtrack  **2 step** every "_loop_" and  stop if **$i -gt 20**

**Comment by jhoneill** [comment]
Something which can already be done with while or for, without trying to explain inverted or outside loops to new developers.

**Comment by p0W3RH311** [comment]
operator like foreach / while /until  / foreach-objeect / for  /  do while /do until.....all can already loop but its exiist minor ddifference between them  with "unloop" first its not  loop ass others loop second it more easier and more understand ffor new and  advanced developper .

**Comment by vexx32** [comment]
I can't say I've ever seen a use case for a construct like this. If you need it, you can just do a `for` loop and manually modify your index variable within the loop, with less confusing code.

What are the expected practical use cases for something like this?

**Comment by SeeminglyScience** [comment]
It's also for the most part impossible to move backwards without heavily altering the code generated for a `foreach` statement.

This code:

```powershell
foreach ($a in 0...10) {
    $a
}
```

Gets translated roughly to:

```powershell
$enumerator = (0..10).GetEnumerator()
try {
    while ($enumerator.MoveNext()) {
        $a = $enumerator.Current
        $a
    }
} finally {
    ($enumerator -as [IDisposable])?.Dispose()
}
```

`IEnumerator` doesn't have a `MovePrevious` method.  Implementing `unloop` would require either switching the code gen to use indexing *only* when that's possible and throwing otherwise, or allocating a whole new array just to support it.  It would also probably have to do this for every single `foreach` statement even if no `unloop` was used, or be very strict in how it can be used (no nested script blocks).
