### ISSUE TITLE
cursor is not at end after script completes

### ISSUE THREAD

**Issue by kzhui125** [PowerShell/PowerShell#12312]
Hello,

After my script complete, I want the cursor is at the end.
But now the cursor is mixed with my script output.
How to fix this issue? Thanks,

[Capture_20200415.mp4.zip](https://github.com/PowerShell/PowerShell/files/4476571/Capture_20200415.mp4.zip)

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by rjmholt** [comment]
Hello!

**Comment by mklement0** [comment]
Please note that this repo is not for reporting _Windows PowerShell_ issues (PowerShell versions up to 5.1); use the Windows PowerShell [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell) forum for that.

If you (also) see the issue in a [currently supported _PowerShell [Core]_ version](https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-7#powershell-releases-end-of-life), including the current preview version, please provide minimal sample code that reproduces the problem, directly in your original post (not via a link to code elsewhere).

On a general note (may not apply in your case, but we don't know yet):

For general PowerShell questions - as opposed to finding a problem with PowerShell itself - the following community resources should be used instead of posting here.

* The [Slack](https://join.slack.com/t/powershell/shared_invite/enQtMzA3MDcxNTM5MTkxLTBmMWIyNzhkYzVjNGRiOTgxZmFlN2E0ZmVmOWU5NDczNTY2NDFhZjFlZTM1MTZiMWIzZDcwMGYzNjQ3YTRkNWM) and [Discord](https://discordapp.com/invite/AtzXnJM) community chat forums (they seamless talk to each other).
 
* Q & A site [StackOverflow.com](https://stackoverflow.com/questions/tagged/powershell) and the [PowerShell.org](https://powershell.org/forums/) forum for searching or posting questions about PowerShell.
