### ISSUE TITLE
multi-types instead  of ArgumentTransformtionAttribue 

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12359]
with  ParameterSets and **ArgumentTransformtionAttribue** we can change  the type of one or more attribute but its lots of typing and sometimes its not easy

Given the dynamically typed nature of Powershell there are lots of cases where multi-types can be useful. multi  types are a collection of two or more types which indicate that either one of those can be used.
```

#  prototype
function foo {
  param(
    [unionType('int','datetime','string')]
    $myhappyparam
  )
```
}

**Comment by vexx32** [comment]
When would you use this in a practical case? PowerShell is pretty permissive when it comes to converting types, but in general I'd pretty much expect that you're only going to end up duplicating code that would otherwise go in the transformation attribute, so I'm not sure what this would really be adding overall?

**Comment by p0W3RH311** [comment]
for example:

```
function foo {
  param(
    [unionType('int','System.Management.Automation.PSModuleInfo')]
    $module
  )
  proceess {

     # code
  }
}

```
works in all caases 


```
PS>  get-module mymodule
PS> foo -module  mymodule
PS> 'mymddule'  |  foo
```

**Comment by SeeminglyScience** [comment]
A `string` and a `PSModuleInfo` are pretty different.  How would you use them as if they were the same?

**Comment by p0W3RH311** [comment]
@SeeminglyScience 

the idea is like  ArgumentTransformtionAttribue transform type of attribbute but in easy way

**Comment by SeeminglyScience** [comment]
Right but with that attribute you're transforming it into the real expected type.  Here it's just going to be any one of those without any transformation.  So since `$module` will either be `string` or `PSModuleInfo`, can you give an example of how you would expect interacting with it to look?

**Comment by p0W3RH311** [comment]
the logic in body of this  function is same as the logic of body of ArgumentTransformtionAttribue.
we tests the type of  $module 

`if string then ... else if PSmoduleInfo ....`


also with parametersets is the same mechanism we tests the parametersets 

this is a prototype...maybee samee chaange  occuurs...

the goal  is to simplify  the convertion between multiple type 

sorry  for my english

**Comment by jhoneill** [comment]
That's not how types work with parameter  
```
[String]$p1 
[int]$p2
[system.io.file]$p3
```

Says "Convert P1 to a string" , "Convert P2 to an int"  and "Convert p3 to a file" 
The third case does some really stupid things (like creating a reference to a non-existent read only file in \windows\system). 
If you say $p4 **might be a string or an int** , what does it do with 3.14 ? Make it a "3.14" or 3 

`[int]$p2 `says if it is a string try to make it an int. If that fails we get an error. 
If you want to say $P might be a name, and ID or an object (which is good !) then you specify no conversion attribute and check inside the function to see what you were passed and proceed accordingly.

**Comment by SeeminglyScience** [comment]
> pseudo-code
> `if string then ... else if PSmoduleInfo ....`

If you need to do that logic manually anyway, I think typing the parameter as `[psobject]` will do what you want.  I could see the value in an attribute that describes the types that a `[psobject]` typed parameter can accept, but if it was anything other than purely documentation it would make parameter binding really hard to reason about.

> sorry for my english

No worries, your english is excellent 🙂

**Comment by p0W3RH311** [comment]
@SeeminglyScience 

thanks you.
but why [psobject] work and the baseobject [object] not work ?

**Comment by mklement0** [comment]
It looks like there are two distinct aspects:

(a) **Making argument type _transformation_ easier** - where, as with `ArgumentTransformationAttribute`, you always end up with the single declared parameter type.

Taking the `System.Management.Automation.PSModuleInfo` / `string` example, I can see how it would be nice to have a simpler way to implement a transformation, namely via  a script block:

```powershell
function foo {
  param(
     # Wishful thinking: If a [string] with a module name or path is given, 
     # transform it to a PSModuleInfo instance.
     [Transform([string], { Get-Module -ListAvailable $_  })]
     [System.Management.Automation.PSModuleInfo] $Module
  )
}
```
 
(Of course, you could argue that `[System.Management.Automation.PSModuleInfo] '/path/to/module'` should be supported by default, but that's a separate issue.)

---

(b) **Allowing a parameter to be limited to a fixed set of types**, with command-internal logic to examine the type ultimately passed.

Given the manual effort needed to examine the type inside the function anyway, and given @SeeminglyScience's point about how enforcing the set of types would make parameter binding hard to reason about, I think **this would call for a different solution**:

**Distinct, strongly typed, mutually exclusive parameters.**

Of course, that's what _parameter sets_ are for - but implementing this logic is currently quite cumbersome.

For instance, the following implements two mutually exclusive, positional parameters that target something either by a numeric ID or a name string, so that you can call `foo 42` or `foo bar`, and the former will bind to `-ID`, the latter to `-Name` (as an aside: `Wait-Process` already works that way, but not `Get-Process` / `Stop-Process` - see #6551).

```powershell
function foo {
  [CmdletBinding(DefaultParameterSetName='Name')]
  param(
    [Parameter(Position=0)]
    [int] $ID
    ,
    [Parameter(Position=0, ParameterSetName='Name')]    
    [string] $Name
  )
  "[$ID] [$NAME]"
}
```

That's a lot of ceremony, and I wonder if we should allow a more succinct expression of this concept.

We have thought about this before, namely in the context of this since-withdrawn RFC: https://github.com/PowerShell/PowerShell-RFC/blob/master/X-Withdrawn/RFC0001-Mutual-Exclusion-Parameters-and-Properties.md

---

> why [psobject] work and the baseobject [object] not work ?

`[object]` would work, and in fact I suggest using _it_ rather than `[psobject]`, because from a scripter's perspective `[psobject]` should really be considered an invisible helper type not to be used directly.

**Comment by SeeminglyScience** [comment]
> `[object]` would work, and in fact I suggest using _it_ rather than `[psobject]`, because from a scripter's perspective `[psobject]` should really be considered an invisible helper type not to be used directly.

I usually recommend `psobject` because in some circumstances `object` can strip ETS properties, and in others it can result in (a very minor) amount of overhead when unwrapping and rewrapping. Plus that's typically what cmdlets type their parameters as so I like the consistency.

**Comment by mklement0** [comment]
(If what was originally discussed here is to go anywhere, I feel (a) and (b) would have to become new issues anyway, so I hope it's OK to continue the tangent here):

I think the presence of `[psobject]` in PowerShell code is ultimately more confusing and harmful than beneficial.

Even in cmdlets I wish parameters - and especially output objects - weren't `PSObject`s - see #5551 and #5579.

Note that _not_ typing a parameter does _not_ result in an extra `[psobject]` wrapper.
That is, omitting a type is equivalent to `[object]` typing, not `[psobject]`:

```powershell
# Ditto with `[object] $p`
PS> & { param($p) $p -is [psobject] } 42
False 

# vs.
PS> & { param([psobject] $p) $p -is [psobject] } 42
True
```

As for ETS members getting stripped; @lzybkr alludes to that [here](https://github.com/PowerShell/PowerShell/issues/5551#issuecomment-384784596), but I can't actually get that to happen:

```powershell
PS> (Get-Item / | add-member -passthru  -NotePropertyName foo -NotePropertyValue bar),
('other' | add-member -passthru  -NotePropertyName foo -NotePropertyValue bar),
(42 | add-member -passthru  -NotePropertyName foo -NotePropertyValue bar),
($false | add-member -passthru  -NotePropertyName foo -NotePropertyValue bar) | % {
    & { param($p) $p.foo } $_
  }

# ETS property .foo was passed through in all cases.
bar
bar
bar
bar
``` 

Are there still cases where they get stripped?

**Comment by SeeminglyScience** [comment]
> I think the presence of [psobject] in PowerShell code is ultimately more confusing and harmful than beneficial.

Eh I see where you're coming from but I disagree.  I remember very early on just thinking "oh it's a PowerShell object, it makes objects do PowerShell things".  I know that's just anecdotal but I don't think most ps users would think about it much last that. Though I could understand it being confusing for C# folks maybe.

>Are there still cases where they get stripped?

The one that comes to mind is method parameters where the object will not be rehydrated the same (such as when `StoreTypeNameAndInstanceMembersLocally` is true).  I believe there are more, but none other readily remember-able.

```powershell
class Test {
    static [object] GetMembers([object] $obj) {
        return Get-Member -InputObject $obj
    }
}

[Test]::GetMembers($profile) | ? MemberType -eq  NoteProperty
```

In that example only certain types and pso instances will be stripped of ETS properties because in most cases they will be rehydrated correctly.  That said, if the method is binary it will not. That's why `PSSerializer.Serialize` *always* strips ETS.

The reason for that (and the reason it can't be fixed) is because most dotnet API's have no awareness of `psobject`.  They won't know that they need to (or if they don't need to) unwrap it.  They also don't typically know how to enumerate the properties since just using straight up reflection won't yield much useful.

Is it super likely that you'll ever run into one of these scenarios? Nah, but if it does it'll be real hard for most to troubleshoot and I personally don't think there's a downside.

**Comment by mklement0** [comment]
Thanks, @SeeminglyScience.

>  I don't think most ps users would think about it much last that.

With the presumably accidental extra words in that sentence I'm not sure I got the gist of this. Did you mean to say that most PS users don't think about it much and are accustomed to using `[psobject]`?

I know that _historically_ `[psobject]` was often used, notably with `New-Object PSObject` - before the `[pscustomobject] @{ ... }` syntax sugar was introduced in v3. Even before that, `New-Object PSCustomObject` would have made more sense conceptually.

Still, I think we would benefit in the long run if `[psobject]` became a truly invisible, transparent-to-the-scripter type. The way it currently peeks from behind the curtain - situationally, in ways that are virtually unpredictable to the casual user - will remain a pain point.

---

In that vein (thanks for the method example): Do you think it's possible in principle to make a non-breaking change that prevent the occasional loss of ETS member _without_ having to use `[psobject]` variables explicitly?

> In that example only certain types and pso instances will be stripped of ETS properties

What causes the loss with `$PROFILE`, specifically? Looking at the source code, it appears _not_ to use `StoreTypeNameAndInstanceMembersLocally`

Also,  `StoreTypeNameAndInstanceMembersLocally` appears to be a v2 legacy feature anyway (see https://github.com/PowerShell/PowerShell/issues/7768#issuecomment-426154780), and its continued use causes the problem in #7937, for instance.

**Comment by SeeminglyScience** [comment]
> Thanks, @SeeminglyScience.
> 
> > I don't think most ps users would think about it much last that.
> 
> With the presumably accidental extra words in that sentence I'm not sure I got the gist of this.

Supposed to be past instead of last, I'll fix that ty :)

> Did you mean to say that most PS users don't think about it much and are accustomed to using `[psobject]`?

I think they won't think much about it other than "use psobject instead of object because it does ps things".

> Still, I think we would benefit in the long run if `[psobject]` became a truly invisible, transparent-to-the-scripter type. The way it currently peeks from behind the curtain - situationally, in ways that are virtually unpredictable to the casual user - will remain a pain point.

It's a nice thought, but I fear that would end up being a more impactful and confusing version of what happened to `AutomationNull`.

> In that vein (thanks for the method example): Do you think it's possible in principle to make a non-breaking change that prevent the occasional loss of ETS member _without_ having to use `[psobject]` variables explicitly?

Unfortunately no.  If you change the member binder to pass the `PSObject` wrapper instead of the base object, a whole lot of code will still failing.

> What causes the loss with `$PROFILE`, specifically? Looking at the source code, it appears _not_ to use `StoreTypeNameAndInstanceMembersLocally`

Strings are treated like that member is `true` implicitly, probably because of string interning.

> Also, `StoreTypeNameAndInstanceMembersLocally` appears to be a v2 legacy feature anyway (see [#7768 (comment)](https://github.com/PowerShell/PowerShell/issues/7768#issuecomment-426154780)), and its continued use causes the problem in #7937, for instance.

I don't see where in that issue (including the linked comment) where that's said, did you link the right one?

**Comment by mklement0** [comment]
As always, I appreciate the deep dive, @SeeminglyScience.

> Strings are treated like that member is true implicitly, probably because of string interning.

Let's try to narrow this down: Is `[string]` the _only_ type to which that applies?
That does appear to be the case:

```powershell
class Test {
    static [object] GetMembers([object] $obj) {
        return Get-Member -InputObject $obj
    }
}

# .foo resurfaces; ditto with `$true | Add-Member ...`
[Test]::GetMembers((42 | Add-Member foo bar -PassThru)) | ? MemberType -eq  NoteProperty
```

I think the larger point is that attaching ETS instance members to strings and value types is generally a bad idea, and the `$PROFILE` implementation - a _string_ with `NoteProperty` members - always struck me as awkward and obscure.

If a `[string]` instance with `NoteProperty` members is the only case where `[psobject]` is needed, I'd say that hardly warrants its use.

> I don't see where in that issue (including the linked comment) where that's said, did you link the right one?

The [linked comment](https://github.com/PowerShell/PowerShell/issues/7768#issuecomment-426154780) states:

> in V3 when we changed the underlying representation of instance members.

That suggests to me that a _better_ mechanism was introduced that _supersedes_ the old one was introduced, and the linked comment details the improvements.

Conversely, the _old_ mechanism is both obscure and can cause problems, as #7937 demonstrates, and as summarized int [this comment](https://github.com/PowerShell/PowerShell/issues/7768#issuecomment-426649706) by someone I implicitly trust (just kidding):

> Generally, the - seemingly legacy - mechanism of associating instance member with a - usually invisible - [psobject] wrapper rather than the wrapped object itself strikes me as highly obscure


Let me ask the opposite: why do you think it's still useful (leaving aside true [edge cases](https://github.com/PowerShell/PowerShell/issues/11122#issuecomment-555736430))?

**Comment by SeeminglyScience** [comment]
> Let's try to narrow this down: Is `[string]` the _only_ type to which that applies?

Think so

> I think the larger point is that attaching ETS instance members to strings and value types is generally a bad idea, and the `$PROFILE` implementation - a _string_ with `NoteProperty` members - always struck me as awkward and obscure.

🤷 won't stop folks from doing it.

> If a `[string]` instance with `NoteProperty` members is the only case where `[psobject]` is needed

Also pso's with `StoreTypeNameAndInstanceMembersLocally`.

> I'd say that hardly warrants its use.

Between the two `psobject` handles some niche cases better.  If you personally don't like `psobject` for style or philosophical reasons, yeah the world for sure isn't going to end if you use `object`.

> The [linked comment](https://github.com/PowerShell/PowerShell/issues/7768#issuecomment-426154780) states:
> 
> > in V3 when we changed the underlying representation of instance members.
> 
> That suggests to me that a _better_ mechanism was introduced that _supersedes_ the old one , and the linked comment details the improvements.

He's saying that they added resurrection tables and then describes the benefits of them. `StoreTypeNameAndInstanceMembersLocally` is how you purposefully skip resurrection tables.

> Let me ask the opposite: why do you think it's still useful (leaving aside true [edge cases](https://github.com/PowerShell/PowerShell/issues/11122#issuecomment-555736430))?

No matter how I feel about it personally, it's still used.

I do kinda wish it was used more though.  Resurrection is really annoying with types that are cached for instance.  For example, making a provider that outputs `Type` objects, now every literal has `PSPath` attached to it.  You could argue that you should create a wrapper type, but then you have to reimplement all of the methods on `Type`, etc.  Or lets say you're just trying to add a property or type name for formatting, now everywhere that instance is used is changed.  It's like global variables imo, I don't want to dirty up global scope.

**Comment by mklement0** [comment]
Let's try to summarize:

* For _function_ parameters (the premise of this issue) _omitting_ a type constraint or using `[object]` works fine in all cases - ETS members are never  lost, so there's no need for `[psobject]`.

* For _method_ parameters in _PowerShell_ classes, _omitting_ a type constraint or using `[object]` works fine, _except_ in the following edge case:

   * `PSObject` instances that have _instance_ ETS members _and_ whose private `StoreTypeNameAndInstanceMembersLocally` property is `true`, i.e. whose ETS instance members are associated with the _incidental `PSObject` wrapper_ rather than the wrapped objects themselves (via the v3+ resurrection tables); to  support such objects, you must declare your parameter as `[psobject]`. Such objects are created under the following conditions:

      * _Invariably_, for technical reasons (the CLR's string interning), when attaching ETS instance members to `[string]` instances.

         * It is generally not advisable to create such wrapped `[string]` instances, because the ETS properties are hard to discover, given that the `[psobject]` wrapper still prints like a string by default; it is unfortunate that the automatic `$PROFILE` variable uses this technique; similarly, the strings output by `Get-Content` are wrapped this way, currently without an opt-out - see #7537. Such wrapped strings can conversely surface their ETS instance members in unexpected situations - see #5797.
        
         * For the same reasons it is not advisable to add instance ETS members to instance of .NET primitive types (such as most number types, `[char]`, and  `[bool]`) (even though they _are_ passed through to methods); additionally, the engine caches certain _literals_, so `$v = 42; $v | Add-Member foo bar` doesn't just make `$v.foo` return `'bar'`, but also associates the property with the _literal_:  
`& { param($p) $p.foo } 42` then prints `'bar'`.

      * _Potentially_, by _engine-internal_ code that _opts-into_ the v2 behavior; the - sensible - default in v3+ is to leave `StoreTypeNameAndInstanceMembersLocally`  at `false`, i.e. to associate the ETS instance members with the the wrapped object themselves. (Note that _user code_ cannot opt-into v2 behavior, because the [static method that creates a `PSObject` with `StoreTypeNameAndInstanceMembersLocally` set to `true` is `internal`](https://github.com/PowerShell/PowerShell/blob/2c8955eaebfa147e6973e24ef8495afc6d6ef104/src/System.Management.Automation/engine/MshObject.cs#L1050).) See below.

Note that for a method in _compiled code_ the _only_ way to receive an object with ETS members - whether instance or type-level, whether with `StoreTypeNameAndInstanceMembersLocally` set to `true` or not - is to declare the parameter as `PSObject`. 

By contrast, a _cmdlet's_ parameters - which are implemented as .NET type _properties_ - _do_ receive `PSObject` wrappers as such even for `object`-typed parameters = properties (not just for `PSObject`-typed ones).

---

**Instances of wrapper-only instance members  in the engine code as of PowerShell Core 7.1.0-preview.1** (`StoreTypeNameAndInstanceMembersLocally` set to `true`):

Note: Obtained via regex `PSObject.AsPSObject([^)]+?,.+?)`, with false positives weeded out.

https://github.com/PowerShell/PowerShell/blob/022c14917f266818ca5d1e9c08955d85a0b70a87/src/Microsoft.PowerShell.Commands.Utility/commands/utility/Get-Error.cs#L79

> Or lets say you're just trying to add a property or type name for formatting, now everywhere that instance is used is changed

The above use avoids that, and constitutes  the aforementioned [edge case](https://github.com/PowerShell/PowerShell/issues/11122#issuecomment-555736430); it is a legitimate use that should have no impact on user code and is unlikely to raise questions, given that the context is _for-display_ formatting.

https://github.com/PowerShell/PowerShell/blob/022c14917f266818ca5d1e9c08955d85a0b70a87/src/Microsoft.PowerShell.Commands.Utility/commands/utility/Select-Object.cs#L536

https://github.com/PowerShell/PowerShell/blob/022c14917f266818ca5d1e9c08955d85a0b70a87/src/Microsoft.PowerShell.Commands.Utility/commands/utility/Select-Object.cs#L553

This is the _bug_ reported in #7937.

---

> I do kinda wish it was used more though. Resurrection is really annoying with types that are cached for instance. For example, making a provider that outputs Type objects, now every literal has PSPath attached to it.

I think we can cross that bridge when we get to it. Instance members showing up on cached instances is already a problem with cached number literals, as shown above, but adding instances members to instance of such types is ill-advised anyway.

Overall, I think it is important _not_ to use per-wrapper instance members anymore, so as to spare users the confusion of members disappearing in ways that are hard to reason about and may seem inexplicable altogether to the casual user.

It's technically different, but the behavior described in #4347 sows similar confusion.

**Comment by scriptingstudio** [comment]
In the light of this discussion what is the better (preferred,safe,right...) way of using `generic.list`?
`[System.Collections.Generic.List[psobject]]` or `[System.Collections.Generic.List[object]]`?

**Comment by mklement0** [comment]
Use `[System.Collections.Generic.List[object]]` - there is no need for `[psobject]` wrappers around the elements.

* In PowerShell code, the wrappers will mostly not be noticeable (though can cause side effects, as shown in #5579), but they're unnecessary.

* In compiled code, if you pass something like `[System.Collections.Generic.List[psobject]] @(1, 2)` to a `System.Collections.Generic.List<object>`-typed parameter, that code will see the list elements as `[psobject]`, not `[int]`.

---

Let me try to summarize at a higher level (my personal assessment):

* From the perspective of code _written in  PowerShell_, `[psobject]` should never have entered the picture: it should always have been an _invisible helper type, used only behind the scenes_ (Compiled (C#) code for cmdlets, by contrast, _does_ need to be aware of `PSObject` and use it on occasion - by no means always - see #5551). To put it differently: The presence of `[psobject]` in Powershell code amounts to a _leaky abstraction_.

* There are unfortunate historic reasons that promoted the visibility and use of `PSObject`:

  * The unfortunate technical conflation of `[pscustomobject]` and `[psobject]`: they _both_ point to `System.Management.Automation.PSObject` - even though there is a distinct `System.Management.Automation.PSCustomObject` type (see #4344). Only the latter should be visible to PowerShell code. The conflation causes a number of problems, such as #4343 and #11921

  * Early PowerShell code - before the availability of syntactic sugar `[pscustomobject] @{ ... }`, which notably does _not_ work in the form `[psobject] @{ ... }` - often used `New-Object PSObject`, even though `New-Object PSCustomObject` would have been the conceptually appropriate form from the beginning.

  * Syntax diagrams for cmdlets with "untyped" parameters show `<PSObject>` (which is technically correct, but from a PowerShell user's perspective `<Object>` would make more sense - it would be a beneficial "lie", just like `([psobject] 42) -is [int]` being `$true` is).

  * (Note that hidden members such as `.psobject` are obviously useful for advanced tasks, but, given that they're automatically available on any value directly, they don't require dealing with `[psobject]` as a whole.)

While `[psobject]` cannot _technically_ be banished anymore from PowerShell code due to backward compatibility concerns:

* we can fix the aforementioned bugs resulting from the conflation of `[pscustomobject]` and `[psobject]`, as well as the bugs that cause different behavior in the presence of incidental `[psobject]` wrappers.

* we can _document_ that direct use of `[psobject]` is virtually never necessary (see below), thereby discouraging its use.

Eliminating `[psobject]` from PowerShell code simplifies the "object ontology" for PowerShell users: Objects fall into only one of two categories:

* instances of .NET types that PowerShell optionally decorates with additional members, the implementation of which you needn't know or care about.

* dynamically constructed ad hoc objects ("property  bags") in the form of `[pscustomobject]` / `System.Management.Automation.PSCustomObject` instances.

That both these features are ultimately implemented via `[psobject]` is purely an implementation detail.

---

To recap the _only_  scenario in which you currently truly _need_ `[psobject]` in PowerShell code:

* If you define a _method_ in a _PowerShell class_ that accepts what is conceptually a `[string]` parameter _and_ that parameter needs access to a given string's ETS _instance_ members (which would apply if you pass `$PROFILE` and need access to the `AllUsersAllHosts` property, for instance, or if you pass a `Get-Content`-output string and need access to the `.ReadCount` property, for instance), you must define that parameter as `[psobject]`.

  * This conceptually obscure requirement solely exists due to a _technical limitation_ that is outside PowerShell's control.

* As stated, `[psobject]`-wrapped instances of _other_ types work fine (except, potentially, due to the _bug_ described in  #7937), and in _functions_ / _scripts_ / _script blocks_ even `[string]` works fine, so there is _never_ a need to type a parameter `[psobject]` there.

**Comment by scriptingstudio** [comment]
@mklement0 thanks for a detailed response. It is clear and cool.

**Comment by mklement0** [comment]
I'm glad to hear the comment was helpful, @scriptingstudio, and I appreciate the feedback.

@SeeminglyScience, per the protocol we had agreed on - expressing  an overall sentiment of dissent via a thumbs-down emoji - I've already marked your previous comment accordingly, but, given that the follow-up comments were lengthy, perhaps a focused summary is helpful:

>  I remember very early on just thinking "oh it's a PowerShell object, it makes objects do PowerShell things".

That something has a long history of usage is not per se justification for continuing that usage.

> 🤷 won't stop folks from doing it.

Showing indifference toward ill-advised usage is problematic in general, but especially in the context of recommending related usage explicitly on the grounds of accommodating the ill-advised usage.

> I do kinda wish it was used more, though.

Advocating for increased use of a feature that represents a step backward and decreases the predictability of the language for end users is problematic.

**Comment by mklement0** [comment]
P.S., @SeeminglyScience: perhaps you can shed light on the behavior described in #12411.
