### ISSUE TITLE
Implement ~username expansion on Windows and Linux

### ISSUE THREAD

**Issue by rkitover** [PowerShell/PowerShell#12387]
In UNIX shells it is common to refer to the home directories of specific users as `~username`, this is very convenient for many things.

Currently this doesn't work on either Windows or Linux in powershell.

Following up on discussion in #11386.

**Comment by doctordns** [comment]
You can use the "~" character just fine, like this:

```powershell
PS C:\Windows> Set-Location -Path ~
PS C:\foo> Get-ChildItem -path ~\xml
...
```

And to set that path in advance, you can do this:

```powershell
$Provider = Get-PSProvider Filesystem
$Provider.Home="c:\foo"
```
Seems to me you have what you are asking for already.

**Comment by rkitover** [comment]
@doctordns no this is a different thing, `~` is the profile path of the current user, while `~user` would be the profile path of a specific user, e.g. `~bob/` would be `C:\Users\bob`.

**Comment by doctordns** [comment]
That is going to be hard, I suspect. 

If you want **~\<username>**, what format is user name going to take and how would you differentiate a domain vs local user? `~\domain\user` probably would not work for obvious reasons, also `~\User@domain` is also possibly problematic.

What is the use case?

Seems to me you could just do a variation on this:
```powershell
$Cred = Get-Credential    # Enter the username/password
$Location = Invoke-Command -computername localhost -credential $Cred -scriptblock {cd ~;Get-location}
```

**Comment by mklement0** [comment]
@rkitover,  can you please make the following clear in the original post?
We're talking about more fully emulating  `~` expansion for _native utilities_ (external programs), so that it works like in POSIX-like shells.

@doctordns, the use case is to have a convenient shorthand for referring to a different user's home directory path.

(For _PowerShell_ commands, `~` works fundamentally differently: in the native-utility emulation, it is the _engine_ that expands the `~`, whereas in the case of PowerShell commands the command / provider receives the `~` as-is, and it is then _its_ responsibility to interpret the `~` as _its_ home location. That is, to provider-based PowerShell commands `~` does _not_ necessarily refer to `$HOME` (the file-system), and to other commands `~` has no special meaning. Note that some providers do _not_ define home locations; compare `Get-Item filesystem::~` to `Get-Item variable::~`. In short: the `FileSystem` provider specifically would have to implement the `~<username>` logic.)

While the desired behavior on Unix-like platforms is clear (make it work like in POSIX-like shells such as `bash`), @doctordns has a point about needing to define the appropriate behavior on _Windows_.

Note that one option is _not_ to support this on Windows.
While the asymmetry would be somewhat unfortunate, we already _have_ asymmetries: globbing (wildcard expansion) only works on Unix-like platforms; e.g., `someutility *.txt` passes matching filenames on Linux, while `someutility.exe *.txt` on Windows performs no expansion and passes `*.txt` verbatim; then again, perhaps that asymmetry is also worth revisiting.

If we do want to support this on Windows (which is preferable for cross-platform consistency), I suppose one potential approach could be:

* support mere user names only, i.e.. without a domain component; e.g, `~jdoe`, but _not_ `~foo\jdoe` or `~jdoe@foo.com`

* support the names of local users and those in the current user's logon domain, if applicable (don't know how expensive such a lookup would be)
   * Note that POSIX-like shells pass `~jdoe` through as-is, if a local `jdoe` user doesn't exist, so in order to emulate this behavior we'd need to know if the given user name refers to an existing user.

* if a custom home directory is configured for a given target user, that would have to be taken into account as well.

**Comment by doctordns** [comment]
@mklement0 makes a good point and I see what the OP is driving at. I am not familiar with Linux sufficiently!

In the cases I've seen, the '~' is part of a file path that is provided to the -Path parameter  (or similar). So it makes sense for consistency if nothing else is if the '~' as provided to one of the path parameters is handled by PowerShell (ie without any username syntax). That is the current behaviour.

Could PowerShell use the `--%` parameter to pass the '~' to the program/command without expansion for the program to handle (eg: `someothercommand --% -Path ~\markmike\foo`). That would just pass the '~' as is? 




Is this a case where --% style logic might work?

**Comment by mklement0** [comment]
While you _can_ use `--%` to pass an unquoted `~` as-is, all you need to do is to _quote_ the `~` when calling an external program, which tells the engine to treat it literally: `/bin/echo '~'` passes `~` verbatim. 

(Generally,  `--%` is a stopgap with many limitations, especially on Unix. You could argue that `--%` should do the _opposite_ and that `--%` should be the required _opt-in_ for emulating the platform-native shell's features (`~` expansion, globbing), but that ship has sailed.)

In POSIX-like shells `~` is purely a shell construct, and it is the shell that expands it before target programs see the paths - the target programs are _not_ expected to interpret `~` themselves.

On Unix, PowerShell already emulates this POSIX-shell function with unquoted `~` _alone_ (though doesn't always recognize it properly - see #11386), and **this issue asks that emulation be made _more complete_, by also supporting `~<user>`** - do note that there's _no_ path separator between `~` and `<user>`.

if we limit ourselves to supporting `~` expansion for external programs on _Unix_ - as we have so far - there's nothing more to do.

---

If we want to bring this functionality to _Windows_ too:

* To extend the existing `~` support, which is limited to  _provider-based cmdlets only_ (and can refer to non-file-system locations), the `FileSystem` provider would have to recognize and resolve `~<user>` paths - _whether they're quoted or not_, because `Get-Item ~` works the same as `Get-Item '~'` - that'll have to remain a difference to the native emulation.

* Also bringing `~` support to calling _external programs_ on Windows - which isn't currently supported, just as globbing isn't - would amount to a _breaking change_, unfortunately.

  * It would change the behavior of existing command lines that have unquoted `~` arguments; e.g., `someutility.exe ~` would no longer pass `~` verbatim; in addition to the technical change, this is problematic because`~` is primarily a Unix construct and on Windows cannot generally be assumed to be a stand-in for the user's home directory.

  * The same applies if, for consistency, we tried to bring native globbing to Windows as well: ` `someutility.exe *.txt` currently passes `*.txt` verbatim and would suddenly start passing  multiple file-name arguments.

**Comment by mklement0** [comment]
As for the _Windows_ angle: support for `~` _in general_ is now being discussed in https://github.com/PowerShell/PowerShell/issues/20750#issuecomment-1843232925

---

One subtlety, discovered by @rhubarb-geek-nz, is that `ksh` and `zsh` also support _variable_-based expansions, e.g. `$user = 'jdoe'; /bin/echo ~$user`
 
By contrast, the POSIX spec [POSIX spec](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_01) supports only _verbatim_ usernames and so does `bash` (`/bin/echo ~jdoe`)

While one option is to limit PowerShell to emulating the POSIX-compliant / Bash behavior and therefore allowing _verbatim_ usernames only, the support for variables makes the feature more flexible and therefor usable in _scripts_ rather than just interactively.

To also support variables, the logic would have to be (as implied by the usual quoting rules of POSIX-compatible shells), with `$user = 'jdoe'`:

* `~jdoe`, `~$user`, `~"$user"` should expand to `jdoe`'s home dir. (but only - as usual - if either followed by _no_ additional characters or an _unquoted `/`_)
* Any other forms shouldn't  (e.g., `'~jdoe'`, `"~$user"`)
