### ISSUE TITLE
object exported (Export-Clixml) and imported (Import-Clixml) resulting in different objects

### ISSUE THREAD

**Issue by Conan1989** [PowerShell/PowerShell#12389]
Hi,
This could just be me not understanding something important about what's going on under the pwsh hood. If so, sorry.

I'm attempting to export and import some state to file. Getting a serialization error, which seems to indicate the export / importing is not working as described.
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/export-clixml?view=powershell-7
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/import-clixml?view=powershell-7

object [System.Data.DataTable] exported and imported with Export-Clixml and Import-Clixml resulting in differing objects

$DataTableOriginal

col1      : test
RowError  :
RowState  : Added
Table     : {System.Data.DataRow}
ItemArray : {test}
HasErrors : False

$DataTableImported

col1 : test

# Steps to reproduce

```
$DataTableOriginal = [System.Data.DataTable]::new()
$DataTableOriginal.Columns.Add('col1', [string]) | Out-Null
$row = $DataTableOriginal.NewRow()
$row.col1 = 'test'
$DataTableOriginal.Rows.Add($row)
$DataTableOriginal | Export-Clixml -LiteralPath    "C:\temp\delete\ExportImport_DataTable\state1.xml"

$DataTableImported = Import-Clixml -LiteralPath "C:\temp\delete\ExportImport_DataTable\state1.xml"
# errors with:  Method invocation failed because [Deserialized.System.Data.DataRow] does not contain a method named 'NewRow'
$RowNew = $DataTableImported.NewRow()
```

# Expected behavior

```
would expected the methods to carry over between export and imports
```

# Actual behavior

```
Method invocation failed because [Deserialized.System.Data.DataRow] does not contain a method named 'NewRow'
```

# Environment data

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.1
PSEdition                      Core
GitCommitId                    7.1.0-preview.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```none

```

**Comment by vexx32** [comment]
@Conan1989 deserialization of objects is expected behaviour. When you export data to a file, you're _always_ losing some of the data, this isn't avoidable. .NET objects have a lot of metadata in their live state that can't be restored directly.

When constructing a .NET object, we're entirely limited to what their design allows us to provide in terms of data. If we were to try re-creating a live object from every deserialized object, we'd need a pretty complex algorithm to attempt to recreate the object using its available constructors and settable properties, and even then it would most likely fail to be a faithful recreation a majority of the time.

When you load an object that has been serialised like that, it's pulled back in as (effectively) a PSCustomObject with a typename referencing the original type. There aren't really many or any effective ways around that. If you want to try recreating the original object with the available data from the deserialised object, you are more than welcome to try. Typically the results are fairly lacklustre, but it may be enough for your specific use case. 🙂

**Comment by mklement0** [comment]
@Conan1989, if you want a high-level overview of what happens during serialization / deserialization, see https://stackoverflow.com/a/59180367/45375
