### ISSUE TITLE
transcription more better

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12390]
start-transcript is awesome but its more better if we add more granularity and security 

`[-Exclude <string[]>]`

with this switch we add to the transcription more granularity and maybe more security

for example:

exclude any word credential and securestring from transcription
`start-transcript -exclude 'credential','securestring'`

exclude from transcript any command that begin with verb Remove
`start-transcript -exclude @(gcm -Verb remove | % name)`

**Comment by bpayette** [comment]
@p0W3RH311 Once again, I'm not sure what the purpose of this. How does filtering out the words 'credential' or ''securestring' help with security? If there's a password or hash in the transcript, you're not going match them this way. Removing random bits of information from the transcript will significantly decrease the utility of the transcript feature since the whole purpose of the transcript is to catch everything that happened.

**Comment by p0W3RH311** [comment]
Hi @bpayette 

if a person enter in the terminal for example:

`PS C:\> 'mypassword' | ConvertTo-SecureString -AsPlainText -Force`

the transcription catch this line and the password is clear in the transcription_file

**Comment by iSazonov** [comment]
You could do 
```powershell
'mypassword' | `
    ConvertTo-SecureString -AsPlainText -Force
```
and filter will pass.

**Comment by jcotton42** [comment]
The point of a transcript is to capture everything that happened in a console session. If sensitive things happen in that session then the correct course of action is to secure that transcript.
