### ISSUE TITLE
cast VS convertion VS coarecion

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12408]
in powershell why are we talking about coarecion and not cast or convertion ?

**Comment by vexx32** [comment]
Please use the appropriate issue template and provide some more details; these terms are heavily contextual and it's not especially useful to explain them devoid of context.

In essence, **coercion** is implicit; `"5" + 10` results in the string `"510"` rather than a numeral `15` or an error. Conversion or casting is typically explicit: `[int]'5'` gets you back the actual number to work with rather than a string.
