### ISSUE TITLE
Select-Object -ExpandProperty combined with -Property fails to add ETS instance members to non-primitive value types

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#12411]
Note: I would expect this problem to go away once #7937 is fixed.

For better or worse, if you combine `-ExpandProperty` with `-Property`, the properties passed to `-Property` are added as ETS _instance members_ to the object returned by `-ExpandProperty` (as `NoteProperty` members, as with `Add-Member`). (The way these instance members are added is flawed, as discussed in #7937.)

If the object returned happens to be an instance of a _value type_ (check with `[<type>].IsValueType`) that _isn't also a .NET primitive type_ (check with `[<type>].IsPrimitive`) - e.g., `[datetime]` - these instance members are _not_ added.

This _may_ be related to the fact that wrapping such types in `[psobject]` seems not to work _when saved to a variable_: e.g., `$v = [psobject] [datetime]::now; $v -is [psobject]` returns `$false`, even though for a reference-type instance (e.g., `[IO.DirectoryInfo]::new('/')`) or a .NET primitive type (e.g., `42`) it would return `$true`.

# Steps to reproduce

```powershell
$o = [pscustomobject] @{ one = [datetime]::now; two = [IO.DirectoryInfo]::new('/') }

# OK: reference-type instance [IO.DirectoryInfo] is properly decorated
#     with the [datetime] instance as NoteProperty 'one'
$newValue = $o | Select-Object -ExpandProperty two -Property one
$newValue.one | Should -BeOfType System.DateTime

# BROKEN: The non-primitive [datetime] value-type instance is NOT
#         decorated with the [IO.DirectoryInfo] instance as property 'two'.
#                  Note: The Select-Object return value *must be saved in a variable*
#                        for the bug to surface.
$newValue = $o | Select-Object -ExpandProperty one -Property two
$newValue.two | Should -BeOfType System.IO.DirectoryInfo
```

# Expected behavior

Both tests should succeed.

# Actual behavior

The second test fails:

```none
Expected the value to have type [System.IO.DirectoryInfo] or any of its subtypes, but got $null with type $null.
```

The reason is that the `[datetime]` instance stored in `$newValue` did _not_ receive the `.two` NoteProperty member.

# Environment data

```none
PowerShell Core 7.1.0-preview.1
```

**Comment by SeeminglyScience** [comment]
So during variable assignment, any struct that PowerShell thinks *might* be mutable gets explicitly unboxed and reboxed.  This is only during variable assignment, for example `([psobject](Get-Date)) -is [psobject]` returns true.

The conditions which cause PowerShell to assume the struct is mutable are:

1. The type is not a primitive or enum (which is interesting because enums *are* mutable)
1. There are any public instance fields (even if they're init only)
1. Any public instance properties with a set accessor
1. Any public instance method (since it's not possible to tell if the method mutates the struct internally)

This is done because assigning a struct is supposed to copy the struct not the reference to it.  Since the struct is boxed in order to assign it to `object PSVariable.Value`, if this wasn't done all non-primitive structs would essentially act like reference types in PowerShell.

**Comment by mklement0** [comment]
I appreciate the illuminating explanation, @SeeminglyScience.

So if I understand correctly, the problem occurs when the `[psobject]`-wrapped `[datetime]` instance with its _wrapper-attached_ ETS member (`storeTypeNameAndInstanceMembersLocally` is `$true`) is saved to a variable, because the wrapper is lost.

Therefore, fixing  #7937 will indeed fix this particular problem too: if the ETS member is no longer attached to the wrapper and uses the resurrection tables instead, the problem will go away.

Can I ask you to create a separate issue for the suggested enhancements to detecting whether a non-primitive value-type instance (struct) is mutable?

@iSazonov, can you please label #7937 a bug?
If @SeeminglyScience agrees with my assessment, we can close this one and simply link here from #7937.

---

> which is interesting because enums _are_ mutable

`[enum].IsValueType` is `$false`, but from what I gather only because it is an _abstract_ class; for the same reason, its base class, `[ValueType]` - somewhat paradoxically - reports `$false` for  `[ValueType].IsValueType` as well.

Any _concrete_ enum / value-type implementation again self-reports as a value type (e.g., `[PlatformId].IsValueType`), so it shouldn't be mutable, right?

**Comment by SeeminglyScience** [comment]
> I appreciate the illuminating explanation, @SeeminglyScience.
> 
> So if I understand correctly, the problem occurs when the `[psobject]`-wrapped `[datetime]` instance with its _wrapper-attached_ ETS member (`storeTypeNameAndInstanceMembersLocally` is `$true`) is saved to a variable, because the wrapper is lost.
> 
> Therefore, fixing #7937 will indeed fix this particular problem too: if the ETS member is no longer attached to the wrapper and uses the resurrection tables instead, the problem will go away.

Resurrection tables would actually make it worse sorta.  They work by reference, so in this case the key would be the boxed struct.  Since the struct is explicitly unboxed and reboxed, the reference isn't the same anymore.
 
> Can I ask you to create a separate issue for the suggested enhancements to detecting whether a non-primitive value-type instance (struct) is mutable?

👍 

> Any _concrete_ enum implementation (and any concrete value type in general) self-reports as a value type (e.g., `[PlatformId].IsValueType`), so it shouldn't be mutable, right?

Structs can be (and often are) mutable (struct refers to any value type that isn't a primitive iirc).

But yeah concrete enums are definitely technically mutable.  Languages just hide that.

```powershell
$a = [Reflection.BindingFlags]::Instance
$a.value__ = 30
$a.ToInt32($null)
# 30
```

**Comment by SeeminglyScience** [comment]
Also I feel like I should mention that while enums are technically mutable structs, in all other languages they're treated more like constants.  For instance, in C# this method:

```csharp
public static BindingFlags M()
{
    return BindingFlags.Instance;
}
```

Is translated into these CIL instructions:

```cil
.method public hidebysig static 
    valuetype [System.Private.CoreLib]System.Reflection.BindingFlags M () cil managed 
{
    // Method begins at RVA 0x2050
    // Code size 2 (0x2)
    .maxstack 8

    IL_0000: ldc.i4.4
    IL_0001: ret
}
```

Where `ldc.i4.4` means "load an int32 with a value of 4 to the stack".

In PowerShell, the actual struct is passed around instead.

**Comment by bpayette** [comment]
@SeeminglyScience  WRT to the copying of value types, the goal was to be efficient. Copying all value types (e.g. `int`) was a significant performance. hit. Fortunately the .NET team guidance was to make value types immutable, so there wouldn't be many. So a quick check for mutability was all that was needed. Accidently copying an immutable value type was fine - it just slowed things down a bit. But not copying a mutable type was bad. Ultimately what drove all of this was the fact that the PowerShell console API used mutable value types..  Without the copy fix you couldn't use the PowerShell APIs from PowerShell.  (Note: this is very old code from _before_ CLR 2 was released.)

**Comment by mklement0** [comment]
Thanks, @bpayette  and @SeeminglyScience.

@SeeminglyScience, I had mistakenly conflated the fundamental inability to obtain a _reference_ to a value-type instance with the in/ability of a value-type instance to modify _itself_ (via methods and settable properties).

I've used the `.value__` property in the past, never knowing that you can also _set_ it; incidentally, it seems that this property is undocumented - or am I missing something?

**Comment by SeeminglyScience** [comment]
> I've used the `.value__` property in the past, never knowing that you can also _set_ it; incidentally, it seems that this property is undocumented - or am I missing something?

It's documented in [EMCA 335 §I.8.5.2](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf#page=53&zoom=100,0,96) under `CLS Rule 7`.

That said, the name is an implementation detail.  Naming the field `value__` is required for CLS compliance, but the CLR itself only requires that the concrete type implement exactly one instance field.

**Comment by mklement0** [comment]
@SeeminglyScience:

> Resurrection tables would actually make it worse sorta. They work by reference, so in this case the key would be the boxed struct

But that means that we should clone the resurrection-table entry for the new boxed value, just as you suggested copying the wrapper-attached ETS members (which with the fix for #7937 would all but go away)?

If so, it sounds like we should probably create another issue, to complement #12430:

On variable assignment, when a mutable struct is detected and re-boxing is necessary:
* copy any wrapper-attached ETS members 
* copy any resurrection-table entries.

If you agree, could you please create this issue?

Also, is the following edge case unavoidable?

```powershell
PS> Add-Type 'public struct Foo { public int Bar; }'; ($val = [Foo]::new()).Bar = 1; $val.Bar
0
```

I presume that a copy was created on assignment to $val, which doesn't see the assignment performed on the original value, in the context of the expression.

**Comment by SeeminglyScience** [comment]
> * copy any resurrection-table entries.
> 
> If you agree, could you please create this issue?

Mmm, that's getting real messy. I don't think I want that so I'll leave that to you.

> Also, is the following edge case unavoidable?

Yeah

> I presume that a copy was created on assignment to `$val`, which doesn't see the assignment performed on the original value, in the context of the expression.

I haven't looked into the specifics of that interaction in the binder, but I can tell you why that appears to be the behavior I would expect.  Value types are just that, a value. They aren't necessarily a reference to a specific place in memory like a reference type is.  If you aren't specifically setting a member of a reference to the value type (in PS that pretty much only means a variable expression, in C# it's any managed pointer or memory location like a local, a `ref`, a field, etc), then you're interacting with a copy.

**Comment by mklement0** [comment]
> Mmm, that's getting real messy. I don't think I want that

* If this is a _philosophical_ objection, please elaborate - to me it seems like the PSv3+ equivalent to your copy-the-wrapper-attached-ETS-members suggestion.

* If you think the _implementation_ would be tricky - that's precisely why I asked for your help.

As for the edge case:

To be clear: I think it's probably too exotic a scenario to worry about, but I wanted to understand the underpinnings.

Unlike C#, PowerShell enables constructs such as `($var = ...).property = ...`, i.e., also _assigning_ to the expression on the LHS, and it is reasonable to assume that the instance captured in variable `$var` inside the `(...)` is also the one operated on by  the assignment.

**Comment by SeeminglyScience** [comment]
> > Mmm, that's getting real messy. I don't think I want that
> 
> * If this is a _philosophical_ objection, please elaborate - to me it seems like the PSv3+ equivalent to your copy-the-wrapper-attached-ETS-members suggestion.

It's different.  One is just cloning a wrapper, the other is stuffing more data in a static lookup table.  Just feels messy.  I realize that's not super helpful but I wouldn't post that as a reason not to do it, just as a reason why I don't personally want to spend time on it.

> irrespective of whether it's a value-type or reference-type instance.

That's a reasonable expectation when you're used to mostly dealing with reference types, but that's not how value types work.

In the same why that you may expect this example to be different:

```powershell
$a = [ValueTuple]::Create(10)
$b = $a
$b.Item1 = 30

$a.Item1
# still 10
$b.Item1
# 30
```

**Comment by SeeminglyScience** [comment]
@mklement0 BTW it's worth noting that it's not necessarily just a PS problem.  While PS has it's own funkiness with structs, they confuse most C# developers as well.  Because of those wild behavior differences, it's explicitly advised against creating mutable structs [in the official design guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/struct).

Of course that doesn't mean there are zero reasons to define a mutable struct.  They're great in incredibly performance sensitive code and interop, but without intimate knowledge of their behavior they're confusing for everyone.

**Comment by mklement0** [comment]
@SeeminglyScience 

Re copying resurrection-table entries:

> just as a reason why I don't personally want to spend time on it.

Understood; as it turns out, there is no need: it looks like the behavior is already implemented:

```powershell
Add-Type 'public struct Foo { public int x; }'
$v1 = [Foo]::new(); $v1.x = 1; $v1 | Add-Member foo bar
$v2 = $v1
$v1.x = 2; $v1.foo = 'new'
$v1, $v2
```

The result shows that the variable values are independent (re-boxing occurred) and that the ETS instance member was copied too:

```none
foo x
--- -
new 2
bar 1
```

This means that fixing  #7937 will also fix this issue (I just tried), and I personally see no need to deal with wrapper-attached ETS members, given that they will be all but eliminated with this fix, so I'm closing this.

**Comment by mklement0** [comment]
As for value types: 

Yes, mutable ones can get confusing, and it is unfortunate that when you define `struct`s they are mutable _by default_, and that you have to go out of your way to indicate immutability (`readonly`).

Your `[ValueTuple]` example is a different scenario: `$b = $a` clearly creates a copy of `$a`, and there's no mystery.

My concern was that if the following works:

```powershell
Add-Type 'public struct Foo { public int x; }'
$v = [Foo]::new(); $v.x = 1; $v.x # -> 1
```

by the worldview _that PowerShell presents_, the following should be equivalent, but isn't:

```powershell
Add-Type 'public struct Foo { public int x; }'
($v = [Foo]::new()).x = 1; $v.x # -> !! 0
```

There is no good _conceptual_ reason for variable `$v` to receive a _copy_ of the instance produced by the expression - you should be operating on a single instance that, as a side effect, you store in a variable.

By sheer coincidence, #12470 was just reported, which shows a less exotic scenario that is a more obvious head-scratcher:

In C#, this works as expected (you can run this as-is in `dotnet-script`):

```csharp
// -> 1, as expected.
public struct Foo { public int x; } var arr = new Foo[1]; arr[0].x = 1; arr[0].x
```

That is, the value-type instance that is part of the array could be modified in place.

The seemingly equivalent PowerShell code malfunctions:

```PowerShell
# -> !! 0
Add-Type 'public struct Foo { public int x; }'; $arr = [Foo[]]::new(1); $arr[0].x = 1; $arr[0].x
```

@vexx32 has [pointed out](https://github.com/PowerShell/PowerShell/issues/12470#issuecomment-618735729) that you _can_ make this work:

```PowerShell
# -> 1, thanks to the [object[]] (!) type constraint.
Add-Type 'public struct Foo { public int x; }'; [object[]] $arr = [Foo[]]::new(1); $arr[0].x = 1; $arr[0].x
```



Needless to say, this is both highly obscure and shouldn't be necessary.

**Comment by vexx32** [comment]
Part of the issue is that PS's indexing operator is a bit of a custom implementation since it supports things like `$arr[-1]` to get the last item, as `$arr[0..4]` to get multiple entries (similar to a slice).

WIth a value-type array, this means every indexing operation you do is inherently boxed, which has to copy the original value, so `$array[0]` in that particular case gets you a _copy_ of the item in that index and not the original item. 

Not sure that's really avoidable without re-architecting a significant amount of PS's engine code.

**Comment by SeeminglyScience** [comment]
> by the worldview _that PowerShell presents_, the following should be equivalent, but isn't:
> 
> ```powershell
> Add-Type 'public struct Foo { public int x; }'
> ($v = [Foo]::new()).x = 1; $v.x # -> !! 0
> ```
> 
> There is no good _conceptual_ reason for variable `$v` to receive a _copy_ of the instance produced by the expression - you should be operating on a single instance that, as a side effect, you store in a variable.

You can't return a *reference* to the value, that's the difference. `($v = [Foo]::new())` is basically sugar for `$($v = [Foo]::new(); $v)`.  You're no longer performing a member access on the *variable* you're performing a member access on the variable's *output*, which is a copy.

> By sheer coincidence, #12470 was just reported, which shows a less exotic scenario that is a more obvious head-scratcher:
> 
> In C#, this works as expected (you can run this as-is in `dotnet-script`):

So it works in C# because by default it's accessing a *reference* to the value.

For instance, take a look [at this SharpLab](https://sharplab.io/#v2:C4LglgNgPgAgTARgLACgYGYAE9MGFMDeqmJ2WMCAbJgCoCmAzsANoC6mAagIYQCujAbmKkM2ACyYAsgAowAO2CZ5AEzoAPADRKFmAG49+ASkLDSpbn0bMV61gDoAGpgC8eg3SEozAX1S+UqKJMAE68AMaK9EwmXiJY8ooOnt5AA=).

```csharp
public class C {
    public static Test[] Values;

    public void M(int index, int value) {
        Values[index].X = value;
    }
}

public struct Test {
    public int X;
}
```

Look at the CIL generated for the method `M`:

```
IL_0000: ldsfld valuetype Test[] C::Values
IL_0005: ldarg.1
IL_0006: ldelema Test
IL_000b: ldarg.2
IL_000c: stfld int32 Test::X
IL_0011: ret
```

Specifically notice it's using [ldelema](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.ldelema?view=netframework-4.8) or "Load Element Address".  In order to modify the same data stored in the array, you need to operate on the specific place in memory where it resides.  C# can do this easily because it's static and has the whole picture of what is going to be done to it.

The way the PowerShell compiler works, you can't do that.  Every element is processed as a individual piece.  So when you're compiling that index operation, if you wanted to enable modifying the struct you would need to return the managed pointer.  Unfortunately, you can't box a managed pointer.  Even if you could, the rest of the compiler would have to know how 1. that it needs to do an indirect access, 2. what data the reference is pointing to, 3. when to access it or when to continue to pass it as a ref.

Even if all that was solved, the API that PowerShell relies *heavily* on in the compiler (`System.Linq.Expressions.Expression`) doesn't support ref variables.  It just throws if you try to make one.

**Comment by mklement0** [comment]
Thanks, @vexx32 and @SeeminglyScience  - as always, I appreciate the technical deep dive.

> You can't return a _reference_ to the value, that's the difference. `($v = [Foo]::new())` is basically sugar for `$($v = [Foo]::new(); $v)`. You're no longer performing a member access on the _variable_.

That's the _technical_ explanation, and there may be no way around it, but it strikes me as much more likely that a user will conceive of `($v = [Foo]::new()).foo = 1` as follows: set the `.foo` property on a new `Foo` instance that is in the process also stored in variable `$v`.

In other words: 
* That the value stored in `$v` is not the value acted upon in the property assignment is counter-intuitive.
* It amounts to a _broken promise of an l-value_: your assignment is essentially _discarded_ (another instance of a leaky abstraction).

The same goes for the array example - again, good technical reasons notwithstanding.

The only silver lining is that mutable value types aren't common, and you don't have the problem with reference types.

But when the problem does happen, PowerShell users not intimately familiar with PowerShell's implementation and possibly not even with the value-type/reference-type dichotomy - something you normally do _not_ have to worry about in PowerShell - will be at a loss to  make sense of the behavior.

It sounds like _documenting these limitations_ is called for; please see:

* https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5833 (array case)

* https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5834 (in-expression assignment)

Please review and comment there, as necessary. 
Also, are there other scenarios that should be documented?
