### ISSUE TITLE
Attempting to upload large file (>1GB) using HttpWebRequest results in System.OutOfMemoryException within PowerShell 7

### ISSUE THREAD

**Issue by ChrisLynchHPE** [PowerShell/PowerShell#12423]
# Steps to reproduce

I am using a script ([here](https://stackoverflow.com/a/48323495/3399822), that is slightly modified to support web form file upload) that works just fine in PowerShell 5.0 and 5.1 within Windows, which uploads files to a web service.  It reads the file in chunks, and transfers the bytes to the target web service. This is the file I am trying to transfer:

```powershell
[posh-worker1]: PS C:\Testing> $file | fl

    Directory: \\fileserver\share\dir1

Name           : isoimage1.iso
Length         : 1379500032
CreationTime   : 2/24/2019 10:47:19 PM
LastWriteTime  : 2/24/2019 10:18:15 PM
LastAccessTime : 2/24/2019 10:47:19 PM
Mode           : -a---
LinkType       :
Target         :
VersionInfo    : File:             \\fileserver\share\dir1\isoimage1.iso
                 InternalName:
                 OriginalFilename:
                 FileVersion:
                 FileDescription:
                 Product:
                 ProductVersion:
                 Debug:            False
                 Patched:          False
                 PreRelease:       False
                 PrivateBuild:     False
                 SpecialBuild:     False
                 Language:
```

When I run this in either PowerShell Core using a Remote PSSession (when setting `$PSSessionConfigurationName = 'PowerShell.7'` to ensure the remote is PowerShell 7) from a Windows 10 to Windows 10 (both 1909) system, I get the following:

```powershell
ErrorRecord                 : Exception of type 'System.OutOfMemoryException' was thrown.
WasThrownFromThrowStatement : False
TargetSite                  : Void Throw()
StackTrace                  :    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate
                              (Object input)
                                 at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                 at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
Message                     : Exception of type 'System.OutOfMemoryException' was thrown.
Data                        : {}
InnerException              : System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
                                 at System.IO.MemoryStream.set_Capacity(Int32 value)
                                 at System.IO.MemoryStream.EnsureCapacity(Int32 value)
                                 at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
                                 at CallSite.Target(Closure , CallSite , Object , Byte[] , Int32 , Object )
HelpLink                    :
Source                      : System.Private.CoreLib
HResult                     : -2146233087
```

I found some folks talking about how PowerShell limits the amount of RAM allocated to the remote session, which is 150MB.  I adjusted it using the following on the remote system:

```powershell
Set-Item WSMan:\localhost\Shell\MaxMemoryPerShellMB 1000000
Set-Item WSMan:\localhost\Plugin\Microsoft.PowerShell\Quotas\MaxMemoryPerShellMB 1000000
Restart-Service WinRM
```

The very same code is successful without setting `$PSSessionConfigurationName = 'PowerShell.7'` before initiating an Enter-PSSession command.

This obviously did not help.  So not sure where else to turn.

You may ask why I'm not using something like Invoke-WebRequest?  Well, I need additional progress indicator and HTTPS cert validation that Invoke-WebRequet and Invoke-RestMethod just cannot provide.

# Expected behavior

I should be able to take the same code I wrote for PowerShell 5.1 to work within PowerShell 7, when using a PS Remote Session.

# Environment data

```powershell

# When setting $PSSessionConfigurationName = 'PowerShell.7' from the initiating client
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

# When NOT setting $PSSessionConfigurationName = 'PowerShell.7' from the initiating client
Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by iSazonov** [comment]
.Net MSFT team recommends to migrate to .Net Core. So it's time to migrate Windows PowerShell scripts to PowerShell 7. 
In PowerShell 7 web cmdlets was optimized for many scenarios and do not consume large memory. These optimizations will be never ported to Windows PowerShell.
(If you see issues with these cmdlets please report.)
So you can continue to use Windows PowerShell while you can but it is recommended to begin migration to PowerShell 7.

@PaulHigin Have you thoughts about the backward compatibility scenario?

**Comment by fMichaleczek** [comment]
> I found some folks talking about how PowerShell limits the amount of RAM allocated to the remote session, which is 150MB. I adjusted it using the following on the remote system:
> 
> ```powershell
> Set-Item WSMan:\localhost\Shell\MaxMemoryPerShellMB 1000000
> Set-Item WSMan:\localhost\Plugin\Microsoft.PowerShell\Quotas\MaxMemoryPerShellMB 1000000
> Restart-Service WinRM
> ```
Can you verify the output of this command  on the remote server  ?
`Get-Item WSMan:\localhost\Plugin\*\Quotas\MaxMemoryPerShellMB`

I think you have set the MaxMemory for Windows PowerShell but not for PowerShell 7.

**Comment by PaulHigin** [comment]
There haven't been any changes that I am aware of in PS7 remoting affecting max allowed memory.  The default values are the same for either Windows PowerShell ("microsoft.powershell") or PowerShell 7 ("powershell.7").  In both cases the default value is unlimited ([int]::MaxValue).

But you can check the configuration on the target machine, to see if it has changed from the default value, as @fMichaleczek  points out.  You should check both the individual endpoint plugin, but also the overall quota setting for the machine:

```powershell
# Individual powershell.7 plugin
dir WSMan:\localhost\Plugin\Microsoft.PowerShell\Quotas\MaxMemoryPerShellMB

# Machine wide max shell memory
dir WSMan:\localhost\Shell\MaxMemoryPerShellMB
```

**Comment by fMichaleczek** [comment]
@PaulHigin I think you're wrong. There is a dedicated plugin configured for each version of PowerShell. (And if i remember, it was the same with PS2.0 + PS3-5.1) and the value of 1Gb is hardcoded in Install-PowerShellRemoting.ps1.

This is the result of my previous command on my computer :
```
PS> Get-Item WSMan:\localhost\Plugin\*\Quotas\MaxMemoryPerShellMB | Select PSPath, Value

PSPath                                                                           Value
------                                                                           -----
WSMan::localhost\Plugin\microsoft.powershell\Quotas\MaxMemoryPerShellMB          2147483647
WSMan::localhost\Plugin\microsoft.powershell.workflow\Quotas\MaxMemoryPerShellMB 2147483647
WSMan::localhost\Plugin\microsoft.powershell32\Quotas\MaxMemoryPerShellMB        2147483647
WSMan::localhost\Plugin\PowerShell.7\Quotas\MaxMemoryPerShellMB                  1024
WSMan::localhost\Plugin\PowerShell.7.0.0\Quotas\MaxMemoryPerShellMB              1024
```

This is conform to the file Install-PowerShellRemoting.ps1

```
PS> Get-Content $PSHome\Install-PowerShellRemoting.ps1 | Where { $_ -like "*MaxMemoryPerShellMB*" -or $_ -like "*\Plugin\*" }

$regKey = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WSMAN\Plugin\$pluginEndpointName"
    <Quotas IdleTimeoutms="7200000" MaxConcurrentUsers="5" MaxProcessesPerShell="15" MaxMemoryPerShellMB="1024" MaxShellsPerUser="25"
```

**Comment by PaulHigin** [comment]
Yes, there is a quotas setting for each endpoint (plugin) configured on the target machine.  But there is also a machine wide setting that sets max values allowed for each individual plugin.  In any case the default quota values is unlimited for the latest versions of PowerShell (Windows PowerShell 5.1, PS 6, PS 7).  Earlier versions of PowerShell had arbitrary fixed default values, but this was opened up for later versions.

**Comment by fMichaleczek** [comment]
@PaulHigin this is my report and test. 

## Protocol

I use this simple code to reproduce the memory consumption
`1..50|%{$x=1}{[array]$x+=$x}`

I monitor the memory of the wsmprovhost.exe process

The Shell config is default : 
```
PS C:\Windows\System32> dir WSMan:\localhost\Shell\MaxMemoryPerShellMB
   WSManConfig: Microsoft.WSMan.Management\WSMan::localhost\Shell

Type            Name                           SourceOfValue   Value
----            ----                           -------------   -----
System.String   MaxMemoryPerShellMB                            2147483647
```

## PowerShell.7 / MaxMemoryPerShellMB = 1Gb (default)

"OperationStopped: Exception of type 'System.OutOfMemoryException' was thrown"
wsmprovhost.exe consume less than 1Gb

## PowerShell.7 / MaxMemoryPerShellMB = 4Gb

"Array dimensions exceeded supported range."
wsmprovhost.exe consume over 3Gb

## Machine wide setting

When I change the quota, I see this warning : 
```
The updated configuration is effective only if it is less than or equal to the value of global quota WSMan:\localhost\Shell\MaxMemoryPerShellMB. 
Verify the value for the global quota using the PowerShell cmdlet "Get-Item WSMan:\localhost\Shell\MaxMemoryPerShellMB".
```

## Windows PowerShell 5.1 default quota

In theory and practical, I think there is no quota for Windows PowerShell 5.1 on Win10 Updated and  i found that very very dangerous (i will have to verify default quota on Windows Server...)

**Comment by PaulHigin** [comment]
>> In theory and practical, I think there is no quota for Windows PowerShell 5.1 on Win10 Updated and i found that very very dangerous (i will have to verify default quota on Windows Server...)

That is only the default setting.  You can set the quotas to whatever makes sense for your needs.

**Comment by fMichaleczek** [comment]
@PaulHigin @iSazonov

- I think the PowerShell Comitee will have to examine if we stay like that or if we have to align PowerShell on Windows to Windows PowerShell ?  Introduce an additional step to the PowerShell installer when you choose to enable PSRemoting should be a great idea (to force people to know what they do) but i understand it costs a lot of works.

- There is also a need to update about_session_configurations for PowerShell 6+ because it give wrong information who apply to Window PowerShell (SessionName = Microsoft.PowerShell).
[about_session_configurations/V7](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_session_configurations?view=powershell-7)

I dislike the idea to give unlimited memory with a long time out (2h). If you want to reproduce my issue, i give bellow an example who could consume unlimited memory (limited for 3Gb in this example) for 2h on Windows PowerShell. SSH protocol has a KeepAlive mecanism, so it's easy to have a small timeout on openssh-server. PSRemoting over WinRM is a popular thing, I think adding a KeepAlive mecanism on client side, could resolve the issue and doesn't need a change on the protocol.

## Comparaison PSRemoting

| Parameters                    | Windows PowerShell over WinRM | PowerShell over WinRM | PowerShell over OpenSSH |
| ----------------------------- | ----------------------------- | --------------------- | ----------------------- |
| IdleTimeoutms                 | 7200000                       | 7200000               | 3000 (1)                |
| MaxConcurrentCommandsPerShell | 2147483647                    | 1000                  | N/A                     |
| MaxConcurrentUsers            | 2147483647                    | 5                     | N/A                     |
| MaxIdleTimeoutms              | 2147483647                    | 43200000              | N/A                     |
| MaxMemoryPerShellMB           | 2147483647                    | 1024                  | N/A                     |
| MaxProcessesPerShell          | 2147483647                    | 15                    | N/A                     |
| MaxShells                     | 2147483647                    | 25                    | N/A                     |
| MaxShellsPerUser              | 2147483647                    | 25                    | N/A                     |

(1) source : [What is the default idle timeout for OpenSSH?](https://unix.stackexchange.com/questions/150402/what-is-the-default-idle-timeout-for-openssh)

## Issue with a long time out and unlimited memory

From an admin pwsh.exe :  
```
& {
# start a process of pwsh which connect to Windows PS Endpoint and execute a high memory job
$proc = start pwsh @("-noexit", "-c", 'icm -session (nsn localhost -conf Microsoft.PowerShell) { try {1..50|%{$x=1}{[array]$x+=$x}} catch {$_} }') -Win Hidden -Pass

# wait a little that the invoke command have consume enough memory
sleep -s 60

# kill the process
kill $proc.ID

# verify the wsmprovhost memory consumption
gps wsmprovhost | select Name,@{N='WorkingSetInMb';E={[Math]::Round($_.ws/1MB)}}

}
```

Result : 
```
Name        WorkingSetInMb
----        --------------
wsmprovhost           2876
```

The memory come back after the WinRM timeout the session (2h).

**Comment by iSazonov** [comment]
>  Introduce an additional step to the PowerShell installer when you choose to enable PSRemoting should be a great idea

I think we should keep Installer simple otherwise it will confuse and annoying users.

> There is also a need to update about_session_configurations for PowerShell 6+

Please open new issue in PowerShell-Docs repo or pull PR there.

Also I think we could increase MaxMemoryPerShellMB up to 2 Gb for PowerShell Core - modern computers have usually 2 and more Gb memory. Although it was more correct to make it more frugal.

**Comment by ChrisLynchHPE** [comment]
I'm closing this issue, as it appears to be related to the DotNet legacy API not handling 2GB or larger objects properly during IO read stream operations, and have since opened a new question (#13721).
