### ISSUE TITLE
add  Export-History

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12445]
Hi

in traditional way  if  we want export history:
```

 Get-History | Export-Csv c:\testing\history.csv
 Import-Csv c:\testing\history.csv | Add-History
```
its great but  it will  better if we add  export-History specific for history

forr example:
```

Export-History [-Path] <string>  [[-Id] <long[]>] [[-Count] <int>] [-AsXml] [-AsCSV] [<CommonParameters>]

Export-History [Inputobject]  [-Path] <string>  [[-Id] <long[]>] [[-Count] <int>] [-AsXml] [-AsCSV] [<CommonParameters>]
```

this command is  more clean :
```

PS > get-history -count 5 | export-history -asxml  -path  ./foo.xml
PS> export-history -ascsv  -count 4 -path  ./hh.csv

```

**Comment by jhoneill** [comment]
So. You know that thing in PowerShell where you have small composable cmdlets ? And you put two or more together to get the result you want. That's the reason we don't have Export-Process. Export-Service, Export-AdUser etc. If you need frequently it is the work of a moment to add it to your profile.

**Comment by p0W3RH311** [comment]
@jhoneill 

thanks,

a lots of command have an exportable composite form

```
PS C:\> gcm export-*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Export-BCCachePackage                              1.0.0.0    BranchCache
Function        Export-BCSecretKey                                 1.0.0.0    BranchCache
Function        Export-ODataEndpointProxy                          1.0        Microsoft.PowerShe…
Function        Export-ScheduledTask                               1.0.0.0    ScheduledTasks
Cmdlet          Export-Alias                                       7.0.0.0    Microsoft.PowerShe…
Cmdlet          Export-BinaryMiLog                                 7.0.0.0    CimCmdlets
Cmdlet          Export-Certificate                                 1.0.0.0    PKI
Cmdlet          Export-Clixml                                      7.0.0.0    Microsoft.PowerShe…
Cmdlet          Export-Counter                                     3.0.0.0    Microsoft.PowerShe…
Cmdlet          Export-Csv                                         7.0.0.0    Microsoft.PowerShe…
Cmdlet          Export-FormatData                                  7.0.0.0    Microsoft.PowerShe…
Cmdlet          Export-ModuleMember                                7.0.0.0    Microsoft.PowerShe…
Cmdlet          Export-PfxCertificate                              1.0.0.0    PKI
Cmdlet          Export-PSSession                                   7.0.0.0    Microsoft.PowerShe…
Cmdlet          Export-StartLayout                                 1.0.0.0    StartScreen
Cmdlet          Export-TlsSessionTicketKey                         2.0.0.0    TLS
Cmdlet          Export-WindowsDriver                               3.0        Dism
Cmdlet          Export-WindowsImage                                3.0        Dism
```


and this not break the rule you have mentioned

**Comment by jhoneill** [comment]
Export-Csv, Export-Clixml are cmdlets for doing the export. 

 Export-PSSession are is not the same as Get-PsSession | export-Csv 
I don't know every one of those commands from memory, but since you quoted them which `Export-THING` cmdlets are equivalent to  `Get-THING  |  Out-File`  or `Get-THING | export-Csv`

**Comment by vexx32** [comment]
Yeah, I'm pretty sure all of those are each a specific format for the data needed or expected.

**Comment by p0W3RH311** [comment]
@jhoneill 

then we must delete export-alias or if its breaking change say its a mistacke from the team of powershell

**Comment by jhoneill** [comment]
> you have to generalize in all situations
generalization are general. Exceptions are specific. Between them the cover everything. 
Export-Alias is not the same as
` get-alias |  export-csv `
or 
`get-alias | out-file`
Because it outputs with a header.  And it has a companion `Import-Alias` which can read that format and skip the header.
It's value is absolutely tiny and if it were proposed now I imagine it wouldn't be accepted. Taking it out would upset someone. But it certainly doesn't amount to a precedent
Generalizing would mean every object which has a Get-Thing command should also implement Import-Thing and Export-Thing. 
  
To me this is another case of your use of this _issues_ area not to log an issue which is either a _bug_ or or an _enhancement_ which the project needs to take on but as a _chat_ area for your own knowledge development.  I'll just quietly salute the official team members for being open to this - other projects would ask that such things be taken somewhere else.

**Comment by p0W3RH311** [comment]
Hi @jhoneill 

 _Generalizing would mean every object which has a Get-Thing command should also implement Import-Thing and Export-Thing._

no i mean..export-* must be generalize but at the same time must be in a command family like *-alias ...etc. and *-history because history also has a family but which is not complete

PS C:\> gcm  -noun history
```

CommandType     Name
-----------     ----
Cmdlet          Add-History
Cmdlet          Clear-History
Cmdlet          Get-History
Cmdlet          Invoke-History
```
if you find that this has no value, others will see the opposite ... everything will have value sooner or later

**Comment by jhoneill** [comment]
Sooner or later. Well I think I started with PowerShell in 2006. I worked for Microsoft at the time, and met Jeffrey Snover at Tech-ed before I had any idea who he was. In 14 years - 4 of them still at Microsoft evangelizing PowerShell, through setting up some of the first user groups speaking  at more conferences than I can count. This is the first time someone has expressed any desire for this function. Now OK, I've spent those years talking people who get that it is both OK and expected to join Get-X  to Export-Csv, because there's no built in command for that. 
 
Just as an aside my prompt has looked something like this for at least 8 or 9 years
![image](https://user-images.githubusercontent.com/16209593/80283339-aa9e1480-870e-11ea-8056-0bebad673f48.png)
The number is the history number so I can do \[\#\]540[tab] to get a line back, and long before it was in PSreadline it had persistent history so my history starts at 500. 

I have this in my profile which I blogged about in 2012
```powershell 
Import-Csv -Path $logfile | Select-Object -last $truncateLogLines  | tee-object -variable history | Add-History -ErrorAction silentlyContinue
$history | Export-Csv -path $logfile -encoding unicode -NoTypeInformation
Remove-Item -Path variable:\History
```

And my prompt has this 
```Powershell
$hid       = $myinvocation.HistoryId
if    ($hid -gt 1 -and -not $debugging) {Get-History -Id ($hid -1 ) | ConvertTo-Csv | Select-Object -last 1 | Add-Content -Encoding ascii -Path $logfile}
```

So I have probably called Get-History | convertTo-CSV more times than anyone else alive!
I must have called Add-history tens of thousands of times. So if someone says exporting history needs a special command. No, it does not. 

They only way to add items to the History is with the Add command. And the only way to delete from the history is with the clear command. (Again if one is a purist removing one item by ID should really be remove-history)
Out of four basic operations Create, read, update, Delete, we have 3 and update doesn't make sense, and then we have invoke you can't do `Get-History | invoke-Command `   (A purist would say Invoke-command is broken and needs fixing). And if you know the ID  \[\#\] ID [tab] [enter] is two fewer keystrokes than [i][h][y][space]id[enter].  The only thing you'd want Invoke to do is run multiple items... 
If you want to find something in the history there isn't a Select-History because you use get-history | where. And so on. 
Similarly we don't have export-service , though often on a server we want a file with a list of services. Do we think the service family is missing a member it has get- new- remove- restart- set- start- stop- suspend- , why no export ? Because it doesn't need it. 
Local user has enable- disable- get- net- remove- rename- set- but - oh, the horror - no export ? Seeing a pattern ? 
You raised aliases , which might go back a  long way to people wanting to share aliases in PS V1 - but there is no Export-PSDrives, or export-Variables ? 
And if you do have an export-Thing command it's always going to be the wrong format. I do a lot of work on the export- part of the importExcel module. OK not everyone wants their stuff in .XLSx . But people want it in .CSV, XML, HTML, JSON and YAML.  Hence Get | Convertto-Format  or Get | export-Format. 

Like I say, fundamental stuff.  I like to quote this from Snover, and he was talking about what was wrong with piping in unix
_You pipe A to B to C … because A doesn't do what you want it to do. [Why …?] Because A tightly couples three separate steps into one. A gets a set of objects, it processes those objects, it outputs the objects as text. So, when you say A doesn't do what you want it to do what you're really saying is “I didn't get the right objects”, “I didn't process them the way I wanted to” or “I didn't output them to text the way I wanted to”. So, then piping it to B and C is really the process of trying to take the text and reverse engineer your way back to the beginning of the pipeline to do one of the steps differently. And the heart of PowerShell was [to keep the pipeline model] and output text only when you need to._

The founding philosophy is not to do the tight coupling you're asking for.
