### ISSUE TITLE
Add new parameters in the command Select-Object

### ISSUE THREAD

**Issue by Max441-IMP** [PowerShell/PowerShell#12484]
1.
"AAA", "aaa", "bb", "bb","BB" | select -Unique
AAA
aaa
bb
BB
Add several parameters for example -NotCasenSesitive
You need to get the output case-insensitive, as output to the Sort-Object cmdlet
AAA
bb

2. Add several parameters (only lowercase letters or only upper letters)
for example -UpperCase and -LowerCase
"AAA", "aaa", "bb", "bb","BB" | select -UpperCase
AAA
BB

"AAA", "aaa", "bb", "bb","BB" | select -LowerCase
aaa
bb
bb

**Comment by vexx32** [comment]
I'm not sure this really makes sense to add to Select-Object. It's intended to be a general purpose cmdlet with features that are largely universally usable. A `-Lowercase` or similar switch would only be useful for strings, and essentially nothing else. Even if you tried to implement it for some more complex objects, it's not at all clear what the expected behaviour would be.

**Comment by scriptingstudio** [comment]
("AAA", "aaa", "bb", "bb","BB").foreach{$_.toupper()} | select -Unique

**Comment by p0W3RH311** [comment]
maybe :

` [Linq.Enumerable]::Distinct`

with `[System.StringComparer]`

**Comment by iSazonov** [comment]
Select-Object is very complex and sensitive. I would not change it without urgent need.
Notice, Get-Unique has the same behavior.

**Comment by scriptingstudio** [comment]
@iSazonov not at all the same if you want to get unique by particular property
