### ISSUE TITLE
ValidateScript does not work for class properties

### ISSUE THREAD

**Issue by bluikko** [PowerShell/PowerShell#12517]
# Steps to reproduce

```powershell
# not working
class TestClass {
    [ValidateScript({ $_ -le 10 })]
    [Int]$ClassVar
}
```
Output:
```
ParserError: 
Line |
   2 |      [ValidateScript({ $_ -le 10 })]
     |                      ~~~~~~~~~~~~~
     | At line:2 char:21 +     [ValidateScript({ $_ -le 10 })] +                     ~~~~~~~~~~~~~
Attribute argument must be a
     | constant.
```
```powershell
# working
class TestClass {
    [ValidateRange(0,10)]
    [Int]$ClassVar
}
$cl = [TestClass]::new()
$cl.ClassVar = 10
$cl.ClassVar
```
Output:
```
10
```

# Expected behavior
It should be possible to use ValidateScript in classes the same way as for function parameters.

If there is a technical limitation why the behavior is expected then it should be documented somewhere - I could not find anything in documentation about this.

# Actual behavior
All validations except ValidateScript work as expected in classes.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```none
Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by p0W3RH311** [comment]
perhaps class is by design static scoping  and scriptblock with validateScript  is interpreted dynamically...maybe you can create your own attribute with class [System.Management.Automation.ValidateArgumentsAttribute]

**Comment by vexx32** [comment]
In this specific case you could use `[ValidateRange(0, 10)]` or `[ValidateRange([int]::MinValue, 10)]` depending on your needs.

But yeah, classes are handled at parse time, so attributes have some extra restrictions. I'm not sure there's a way around that? Might be, but I would _guess_ there probably isn't much that's really doable there.

**Comment by bluikko** [comment]
@vexx32 The simple example is just that - a simple example. My need for ValidateScript is obviously much more complex.

Could you point me to the documentation where this is listed as expected behavior since you are not surprised about this behavior?

I could not find many relevant matches doing a web search about validatescript and class but several did have other people wondering about ValidateScript and this problem. So it would not seem to be very well documented.

It is disappointing. If class methods are not static like this then I might be able to figure out an ugly workaround if I have to.

**Comment by vexx32** [comment]
I'm mainly not surprised because I've seen it before, both in PS and (more importantly) in C# itself. In compiled code you can't have non-constant/non-primitive values for attributes. It's actually part of the [attribute language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/attributes#attribute-parameter-types) which states:

> The types of positional and named parameters for an attribute class are limited to the attribute parameter types, which are:
>
> - One of the following types: `bool`, `byte`, `char`, `double`, `float`, `int`, `long`, `sbyte`, `short`, `string`, `uint`, `ulong`, `ushort`.
> - The `type` object.
> - The type `System.Type`.
> - An `enum type`, provided it has public accessibility and the types in which it is nested (if any) also have public accessibility (Attribute specification).
> - Single-dimensional arrays of the above types.
>
> A constructor argument or public field which does not have one of these types, cannot be used as a positional or named parameter in an attribute specification.

I think there are _similar_ underlying requirements for dynamically compiled assemblies, and .NET in the more general case as well. I'm pretty sure the only reason `[ValidateScript()]` is even a thing is because PowerShell script can do more or less whatever it want, as long as it's willing to handle things on its own. `[ValidateScript()]` is possible in PS probably because PS isn't directly compiling functions, it's doing it piecemeal and can handle attributes however differently it wants, more or less.

Classes in PS are a different story entirely, and have to be compiled as-is at parse time, meaning there's no deferred compilation or special handling of attributes for the most part, they just behave very much like C# / .NET attributes.

**Comment by rjmholt** [comment]
Yeah @vexx32 has hit it on the head. It looks like we should handle this more gracefully.

I anticipate that this is "expected if you think about the implementation and extrapolate", but has not been anticipated by the existing implementation.

Currently classes are compiled into dynamic .NET assemblies, and won't tolerate attributes that do something that .NET doesn't like, namely use values that can't be embedded into .NET static metadata.

I don't see `ValidateScript` ever working as an attribute for classes, but I also don't see that as a big issue since classes don't need to do parameter binding. Instead the validation can be done in the method body (similar to how it would be done for a C# method).

I think we should:

- Emit a parse-time semantic error when this attribute is used on a class method
- Update documentation to explicitly document how attributes work with classes

**Comment by sdwheeler** [comment]
@rjmholt Are there any other Validation attributes that don't work with classes?

I am guessing that ValidateDrive and ValidateUserDrive might be a problem. Can you confirm?

**Comment by vexx32** [comment]
Those should work, I think the main issue with ValidateScript is that it has to take a non-constant value (a scriptblock) to do its job.

At least, "work" in the sense that the attribute can be applied to the class property. Whether the PS engine will recognise them on a class member or not... is another matter entirely. Not sure there, tbh.

**Comment by bluikko** [comment]
Interesting discussion. I would still like to see this limitation documented since my original research turned up several other similar questions.

After the explanation above it is obvious why such a limitation exists but many users out there, like me, do not have as deep understanding of PowerShell as you do.

My original planned use case for this was doing data binding or simple manual storage&validation of data from a GUI. It is my first attempt at doing more advanced GUI things so it may have been a bad/impossible idea in any case even if the ValidateScript would have worked.

**Comment by bluikko** [comment]
> @rjmholt Are there any other Validation attributes that don't work with classes?
> 
> I am guessing that ValidateDrive and ValidateUserDrive might be a problem. Can you confirm?

Seem to work just fine.

**Comment by jantari** [comment]
I just ran across this when trying to disallow `[TimeSpan]` properties. Neither of these work:

```powershell
class Repro {
	[ValidateRange([TimeSpan]::Zero, [TimeSpan]::MaxValue)]
	[TimeSpan]$SomeDuration
}

class Repro {
	[ValidateScript($_ -gt [TimeSpan]::Zero)]
	[TimeSpan]$SomeDuration
}
```

which is kind of annoying. Both error with `Attribute argument must be a constant.`

Would it be possible to extend ValidateRange support to TimeSpan as well?

**Comment by SeeminglyScience** [comment]
@jantari The term `constant` in this context means it can be embedded as a raw value in a binary file. That is only supported by [the CLR](https://learn.microsoft.com/en-us/dotnet/standard/clr) for primitives and a handful of special cased types (like `Type`). Structs like `TimeSpan` cannot be as their raw value is an implementation detail subject to change, even if they happen to be a thin wrapper around a primitive like `TimeSpan` is.

That said, naturally PowerShell somewhat makes its own rules in this area, and might be able to fake it *outside* of classes. Inside classes would be a lot harder though since at the end of the day it needs to be encoded into metadata (even if only in memory). I'd recommend opening a different issue for the subject of allowing `[TimeSpan]::Zero|MaxValue` in `ValidateRange`
