### ISSUE TITLE
auto-completion for subcommands

### ISSUE THREAD

**Issue by JannikEmmerich** [PowerShell/PowerShell#12534]
# Summary of the new feature/enhancement
If you use git bash, you can use auto-complete to complete subcommands as shown in the screenshot.

![image](https://user-images.githubusercontent.com/22866859/80716668-38f00d00-8af8-11ea-9dc1-ef633bdca032.png)

This is not possible in the PowerShell, instead the auto-complete suggests the folders in the current directory.

**Comment by iSazonov** [comment]
I guess @rjmholt has great news for your.

**Comment by rkeithhill** [comment]
For Git specifically, checkout `posh-git` https://github.com/dahlbyk/posh-git

**Comment by JannikEmmerich** [comment]
@rkeithhill works fine for git! 
But it would be nice to have such a feature integrated in PowerShell for every subcommands.

**Comment by jcotton42** [comment]
Native command completion comes down to people having written completers. PowerShell is able to do that automatically for cmdlets and functions because it has all the necessary metadata, but this not true for native (i.e. external to PowerShell) commands.
`posh-git` just so happens to register a completer for `git` when you import it.

**Comment by rjmholt** [comment]
Take a look at https://www.powershellgallery.com/packages/Microsoft.PowerShell.UnixCompleters
