### ISSUE TITLE
add class property to module cmdlet

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12533]
Hi

its possible to add class property  to import-module  and export-modulemember :

steps to reproduce (pseudo code)
```

PS> cat  test.psm1

class  test1 {  $p1 }
class  test2 {  $p2 }
export-moduleMember  -class test2

PS> import-module test.psm1
```

yes, its possible to use  the pragma **using**

`using module test.psm1`

 but  with **import-module** its add more granularity

**Comment by vexx32** [comment]
We would also need to add a `ClassesToExport` key to the module manifest to complete the pattern.

I think this should be done, but I'm not sure if there are logistical challenges with doing this.

**Comment by jhoneill** [comment]
We had another discussion about this, and the answer was, you must put your classes directly in the PSM1 file, not . source them in, and you must load with USING module, instead of import module and ... and .. and.. 
It's a mess, it needs cleaning up, it might be difficult but classes in modules should not be like Forest Gump's chocolates, you should ALWAYS know what you're going to get. 

There is a risk that this breaks existing modules, (i.e. if 7.2 or 8.0 stops exporting classes from the PSM1 with Using) and the ideal would be that the if there is a new manifest entry it adds functionality without taking any away. (Unknown keys in the manifest are ignored, so it shouldn't reduce what is there for down-level users). 

I have no idea of the practicalities but I'd call this highly desirable.

**Comment by alx9r** [comment]
The popularity of ["how to export a class in powershell v5 module"](https://stackoverflow.com/q/31051103/1404637) over on stackoverflow suggest that many people would like this functionality.  I have found that [the workarounds](https://stackoverflow.com/a/40441684/1404637) aren't too bad though.  Implementing this wouldn't really enable encapsulating classes in modules as that is already (somewhat awkwardly) possible.  But this feature would make doing so more convenient.

**Comment by vexx32** [comment]
Yeah, I've used the `ScriptsToProcess` approach myself in [PSKoans](https://aka.ms/pskoans). It works, right up until you need to unload and reload the module in the same session; it'll explode because there are already defined classes by those names. To work around that, I have my `ScriptsToProcess` handle it by checking if the type name already exists, and quietly preventing the classes from being re-defined.

It's definitely not ideal, and it'd be awesome if this were possible.

**Comment by alx9r** [comment]
>It works, right up until you need to unload and reload the module in the same session; it'll explode because there are already defined classes by those names.

Right.  It sounds like you're describing #2505 (and [stackoverflow 42838107](https://stackoverflow.com/questions/42838107)).  

I expect PowerShell classes will continue to be expensive to support and painful to develop with.  Because of that I'm reluctant to recommend native PowerShell classes beyond their use with DSC; we already have full-blown C# classes for free.  In my own work I have found few scenarios where PowerShell classes turned out to be the right choice.

C# classes added during module loading with Add-Type are available everywhere in the PowerShell session via `[Namespace.MyClass]`, so no export feature like this is required.  That strategy puts some strain on your module loading structure, but I have found the benefits of getting that right to be worth the effort.
