### ISSUE TITLE
Disable autoloading of specific modules

### ISSUE THREAD

**Issue by bender-the-greatest** [PowerShell/PowerShell#12545]
# Summary of the new feature/enhancement
As a user, I want to be able to mark modules as "never auto-import", which would require a programmer to use `Import-Module` in order to use it. Today, there are only two ways to go about this:

1. Use the `$PSModuleAutoloadingPreference` which modifying widely enough could force massive refactor of existing PowerShell code across an organization/enterprise
2. Save the module to a non-standard path and add the path to `$env:PSModuleImport`. This works, but requires a moderate amount of custom coding, and adds complexity when the runtime could just allow us to either mark the module as "not suitable for auto-import" or allow us to build the module as the same.

# Proposed technical implementation details (optional)
At a high level, one way to implement would be to allow the module creator to add a property to its `psd1` that marks the module as "not suitable for automatic import".

Another approach could be to allow an operational user to select specific modules that PowerShell does not automatically load, and must be loaded using `Import-Module`.

Neither suggestion above is mutually exclusive and such a setup could co-exist, allowing modules to manage whether they are automatically loaded and allowing a devops team to fine-tune the modules which should or should not be automatically loaded.

If this idea is well-received, this is something I could implement.

**Comment by SeeminglyScience** [comment]
> As a user, I want to be able to mark modules as "never auto-import", which would require a programmer to use `Import-Module` in order to use it.

Could you elaborate on some of the use cases/motivations for this?

**Comment by doctordns** [comment]
I like module autoload. I just use a command, the module is loaded, and everything works. 

If for some reason I want a module to be explicitly loaded, and NOT autoloaded. I'd just move it to a nonstandard location then use Import-Module and specify the full path. 

That being said, I can't think of a good reason why I might want to do that, except for testing.

LIke @SeeminglyScience , I'd be interested in seeing use cases.

**Comment by jahmai-ca** [comment]
I'll give you a good reason. Modules like Az.Storage that load versions of Azure.Storage.Blob/Common/Queue or Microsoft.Bcl.Interfaces that are different to the ones that my own cmdlet loads, that become impossible to reconcile because my cmdlets are NET5 based, but the Az.* modules are not, yet when I run "pwsh", every Az.* module is automatically loaded, making it such that I simply cannot run my own Cmdlets that use these references, due to it resulting in "MissingMethodException" or "TypeLoadException" due to the fact that pwsh has pre-loaded versions of assemblies that are incompatible with my cmdlet, despite me not needing to use the Az.Storage module at all for those scripts.

If I could simply tell pwsh to NOT load Az.Storage, or any other conflicting module (however, I do need Az.Accounts, so I'm not simply going to uninstall Az.*), then I believe this would help me resolve my issue.

**Comment by kilasuit** [comment]
@jahmai-ca  this `yet when I run "pwsh", every Az.* module is automatically loaded` is only true if you have it in your profile script to do so, else the only time they will be autoloaded is if you run a command that forces them to be loaded (perhaps in the Azue Cloud shell) 


you can do this by making use of your [profile](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.2) to load things you need every time, as well as within it getting it to prompt you about what other things you may want to load as required if you are in interactive use.

But auto-loading does not just load in modules on running pwsh without something else requiring them, like a profile script

**Comment by jahmai-ca** [comment]
@kilasuit Hm. Ok I'll take another look to see what might be loading Az.Storage and causing my pain. When attaching via Visual Studio, I can see that `Microsoft.Bcl.AsyncInterfaces.dll` is already loaded twice, once by powershell base application (v5), and once by Az.Storage already (some odd v4 version). My cmdlet references the exact same Azure.Storage.Blob/Common/Queue versions as Az.Storage, but also references the v4 version of AsyncInterfaces which when I attempt to instantiate something from the Azure.Storage.Blob assembly inside my cmdlet, causes a TypeLoadException, seemingly because AsyncPageable type returned by Azure.Storage.Blob is implementing the v4 version of IAsyncEnumerable but my cmdlet is referencing the v5 version of it.

Anyway thanks for the tip and I'll see if Az.Storage is being loaded by something else. Is it possible it is being loaded by some other Az.* module? Anyway to trace that?

**Comment by ThomasNieto** [comment]
@petervandivier you can specify the required Pester versions by using a `#requires` statement.

### Pester 4
```powershell
#Requires -Modules @{ ModuleName="Pester"; MaximumVersion="4.99" }
```

### Pester 5
```powershell
#Requires -Modules @{ ModuleName="Pester"; ModuleVersion="5.0" }
```
