### ISSUE TITLE
My bug report

### ISSUE THREAD

**Issue by TristanJamesBall** [PowerShell/PowerShell#12565]
When parsing a JSON object with ISO 8601 date strings, Powershell 7 does not convert the date Correctly
If it's relevant, calling [datetime]::parse() directly on either 5.1 or 7 does work
# Steps to reproduce

```powershell
$datePs1 = [PSCustomObject]@{
    "Date" = "2020-05-03T15:13:01Z"
}

$dateJSON =  $datePs1 | convertto-json

write-host "Powershell Version: " $PSVersionTable.PSVersion
write-host "Original Date String: "  $datePS1.date
write-host "Parsed Original Date: "  ([datetime]::parse($datePs1.date))
write-host "Json Object: " $dateJSON
$dateFromJson = $dateJson | ConvertFrom-Json

write-host "`nConverted JSON Date String: "  $dateFromJson.date
write-host "Converted JSON Date Type: "  $dateFromJson.date.gettype().name
if($PSVersionTable.PSVersion -ne "7.0.0" ) {
    write-host "Parsed Converted JSON Date: "  ([datetime]::parse($dateFromJson.date))
}
```

# Expected behavior

```none
Powershell Version:  5.1.18362.628
Original Date String:  2020-05-03T15:13:01Z
Parsed Original Date:  4/05/2020 1:13:01 AM
Json Object:  {
    "Date":  "2020-05-03T15:13:01Z"        
}

Converted JSON Date String:  2020-05-03T15:13:01Z
Converted JSON Date Type:  String
Parsed Converted JSON Date:  4/05/2020 1:13:01 AM
```

# Actual behavior

```none
Powershell Version:  7.0.0
Original Date String:  2020-05-03T15:13:01Z
Parsed Original Date:  4/05/2020 1:13:01 AM
Json Object:  {
  "Date": "2020-05-03T15:13:01Z"
}

Converted JSON Date String:  3/05/2020 3:13:01 PM
Converted JSON Date Type:  DateTime
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3    
SerializationVersion           1.1.0.1
WSManStackVersion              3.0    
```

**Comment by vexx32** [comment]
This is expected behaviour. You're passing an object with a string property to `ConvertTo-Json`. It has no choice but to keep it as a string.

If you want the JSON cmdlets to handle the date conversions for you, your input to `ConvertTo-Json` must contain an actual `DateTime` object. It's not going to assume whether the content of an arbitrary string should be automatically converted to a date. It's just going to keep it as a string, since that's what you provided.

**Comment by TristanJamesBall** [comment]
I think you've misunderstood - Powershell 7 is not keeping it as a string (which is what Powershell 5.1 does - that's what I got the expected output from) - it's converting it to a DateTime object _and_ it's converting it incorrectly.

**Comment by vexx32** [comment]
Yeah, I'm not really following. I'd agree that the data should come back as string, but you've lost me here in terms of the behaviour you're expecting:
```
Converted JSON Date String:  2020-05-03T15:13:01Z
Converted JSON Date Type:  String
Parsed Converted JSON Date:  4/05/2020 1:13:01 AM
```

In what calendar system does `2020-05-03` parse to a datetime of `4/05/2020`? Are you expecting it to handle the UTC offset to local time?

If so, you're probably better off using `[datetimeoffset]` which is designed to handle UTC offsets. DateTime isn't really meant for handling that, and I'm surprised that ever worked as you expected.

That aside, the main issue appears to be that conversion to and from json is resulting in a datetime object rather than the original string... @iSazonov is this something you've seen? Perhaps we should check to see how the newer .NET JSON APIs are handling this kind of case?

**Comment by TristanJamesBall** [comment]
OK - this is my confusion then - I actually expected the resulting date to be presented in local time - this is what [datetime]::parse actually does (Sunday, May 3, 2020 3:13:01 PM UTC == Monday, May 4, 2020 1:13:01 AM local time here in Melbourne/Australia)

Separately, I had actually tried to do that conversion, but got badly wrong results - but that's clearly a bug on my side.. 

OK - thats my bad... if I use a .tolocaltime() on the converted date, I get the correct local time.

Sorry everyone.

**Comment by iSazonov** [comment]
I hope in next release we will be on new .Net Json API.
