### ISSUE TITLE
PowerShell 7 Web Access

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#12587]
# Summary of the new feature/enhancement

Just curious if there's going to be a PowerShell 7 version of the Windows PowerShell Web Access.
Are there any plans?

# Proposed technical implementation details (optional)

**Comment by iSazonov** [comment]
I guess the answer will be the same as for Windows PowerShell future.
"Windows PowerShell is frozen and supported until Windows is supported and all new development is in PowerShell Core version project." 
PowerShell Web Access is Windows component based on Windows PowerShell and the answer would be true for it too.

For future we could expect to get portable solution but I think it is under big question because vendors prefer to develop integrated web management environments and integrate web consoles into them - on Windows it is Windows Admin Center, on Linux it is [Cockpit](https://cockpit-project.org/).
If MSFT had a plan to enhance Windows Admin Center to Linux (or to integrate into Cockpit) they could think about creating OSS project for  PowerShell 7 Web console. The project would be under big security compliance pressing.
Thus, creating an separated and ported version of PowerShell 7 Web console is a big question.

**Comment by MaximoTrinidad** [comment]
@iSazonov 

Thank you for your comments!
