### ISSUE TITLE
K.I.S.S. for Powershell installs

### ISSUE THREAD

**Issue by kennetherland** [PowerShell/PowerShell#12627]
Why is finding the download for powershell so difficult?  I literally had to click through 20 pages to finally get to the download.  Please keep this simple for end users.  I should not have to wade through GitHub to find a download of powershell.

**Comment by thlac** [comment]
There's a, in my opinion, pretty simple [matrix](https://github.com/PowerShell/PowerShell#get-powershell) on the front page with direct downloads. Are you by chance being linked here from the Microsoft Docs?

Because I see their [documentation](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows) does link directly to the releases page.

**Comment by doctordns** [comment]
I just use the Install-PowerShell script on GItHub:

On Windows just do this:
```powershell
# Download PowerShell 7 installation script
Set-Location C:\Foo
$URI = "https://aka.ms/install-powershell.ps1"
Invoke-RestMethod -Uri $URI | 
  Out-File -FilePath C:\Foo\Install-PowerShell.ps1
c:\foo\install-powerShell.ps1 -useMSI -Quiet
```

**Comment by iSazonov** [comment]
@kennetherland Do you have a more specific suggestion?

**Comment by he852100** [comment]
I think he wants to list the one-click download and installation script on the homepage.

E.g
```
bash <(curl -s -L https://raw.../install.sh)
...
or 
yum install xxx
...
```
