### ISSUE TITLE
WebAdministration : no IIS drive

### ISSUE THREAD

**Issue by sirber** [PowerShell/PowerShell#12634]
# Steps to reproduce

```powershell
Import-Module WebAdministration
Get-PSDrive
```

# Expected behavior

```none
see IIS drive
```

# Actual behavior
```none
no IIS drive
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.19569
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
All non-compatible modules can be reported in https://github.com/PowerShell/PowerShellModuleCoverage

**Comment by doctordns** [comment]
Speaking for myself, I am disappointed that so many Microsoft Windows Server modules are NOT PowerShell Core compatible. I totally understand how a very few modules, such as the WSUS one, will be VERY hard if not impossible to fix since the entire WSUS infrastructure  is reliant on older technology (SOAP)) and can't be converted easily. It is easy to say that that team made some poor design decisions, but we are where we are.

But other modules, like BPA, AD Deployment, and many others, should be fairly straightforward to convert (i would hope!!!!). In the two or so years since Windows Server 2019 shipped, I see no indication of improvements. To me, reporting them as you ask is just a black hole. And as anyone who has tried to use User Voice will know - that too seems a write-only medium.

Until and unless the Windows Server Feature team start fixing these modules, I am not sure what actual value there is in asking users to report these incompatible modules. From where I sit, reporting them achieves little. 

How do we get Microsoft to move forward? And if the Windows Server Team does not want to step up, why not just open source these modules and let the community fix them. That would have the added benefit, eg for AD, to get updated modules working on older OSs.
