### ISSUE TITLE
Get-WinEvent Not capable of traversal

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#12642]
# Steps to reproduce
It can only query one record at a time

Assuming there are 10,000 results, then its time will be:0.0693924*1000=69.3924
```powershell
$xmlQuery = @'
<QueryList>
  <Query Id="0" Path="Security">
    <Select Path="Security">*[System[(EventID=4625)]]</Select>
  </Query>
</QueryList>
'@
Measure-Command{ Get-WinEvent -FilterXML $xmlQuery -max 10}
```

# Expected behavior

```none
Measure-Command{ Get-WinEvent -FilterXML $xmlQuery -max 10000}
TotalSeconds      < 10
```

# Actual behavior

```none
Measure-Command{ Get-WinEvent -FilterXML $xmlQuery -max 10}
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 69
Ticks             : 693924
TotalDays         : 8.03152777777778E-07
TotalHours        : 1.92756666666667E-05
TotalMinutes      : 0.00115654
TotalSeconds      : 0.0693924
TotalMilliseconds : 69.3924
Measure-Command{ Get-WinEvent -FilterXML $xmlQuery -max 10000}
Days              : 0
Hours             : 0                                                 
Minutes           : 1                                                 
Seconds           : 12                                                
Milliseconds      : 368                                               
Ticks             : 723689937                                         
TotalDays         : 0.00083760409375                                  
TotalHours        : 0.02010249825
TotalMinutes      : 1.206149895                                       
TotalSeconds      : 72.3689937                                        
TotalMilliseconds : 72368.9937
```

# Environment data

```none
Ps7.1
```

**Comment by he852100** [comment]
https://github.com/PowerShell/PowerShell/issues/10649

**Comment by iSazonov** [comment]
> Assuming there are 10,000 results, then its time will be:0.0693924*1000=69.3924

Maybe 0.0693924***10000**=693.924

**Comment by Robo210** [comment]
When testing this myself, without delving into the code:
- Events are retrieved from the service in batches
  - Events in each batch could be operated on in parallel, but that would likely not improve anything.
  - You wouldn't like it if every time you asked for a single event, pwsh ate all of your CPU time pre-computing the next thousand or more events in the background, even if it could possibly improve this specific calling pattern.
- There are multiple calls to EvtFormatMessage per event
  - In my test, almost 8000 calls per batch of events, or **over 100 per event**
  - The overhead for all those RPC calls is tremendous. Fully 50% of the total time is spent setting up RPC call data structures and marshalling data between the service and pwsh.
- Of the remaining 50% of the time, 25% is spent in FormatMessageW (as expected), and 25% is spent doing misc. work in the service around the FormatMessageW call.

Eliminate the excessive calls to EvtFormatMessage, and get-winevent should be about as fast as can reasonably be expected. Unfortunately, these calls appear to be coming from .Net's System.Diagnostics.Eventing.Reader class, rather than the cmdlet itself.

_To truly improve the performance of this cmdlet, it should be re-written to call the native Evt APIs directly rather than bumble through the .Net wrapper classes. Doing so would not only bypass many of the design flaws in the wrapper classes, but also would allow the event properties (and their corresponding RPC calls) to be retrieved on-demand. I'm sure such a rewrite would be a breaking change, however, since the cmdlet currently returns System.Diagnostics.Eventing.Reader.EventLogRecord objects._

**Comment by iSazonov** [comment]
@Robo210 Thanks for your investigations!

The code is here:
https://github.com/PowerShell/PowerShell/blob/a7ce7883ceb2e4251babdcd8ec372eb283f31948/src/Microsoft.PowerShell.Commands.Diagnostics/GetEventCommand.cs#L903-L915

We do three slow action:
1. Wrapping in PSObject
2. Formatting (it is slow).
3. Adding new noteproperty

We could add new switch parameter to suppress these actions.
