### ISSUE TITLE
Dedup feature behving strange in PowerShell Core

### ISSUE THREAD

**Issue by Evengard** [PowerShell/PowerShell#12702]
I tried to use PowerShell Core with the Get-DedupStatus and Get-DedupVolume.

First of all, in an unelevated shell it just shows "A general error has occured" without more specific message (like Windows PowerShell does, from this message it is possible to understand that we got an ACCESS DENIED error).

Now, in an elevated shell the table formatting is buggy. I.e. for Get-DedupStatus the columns "FreeSpace" and "SavedSpace" are just empty (while they are filled in Windows PowerShell), the same for Get-DedupVolume (columns SavedSpace and SavingsRate are empty) and Get-DedupSchedule (column "StartTime" is also empty).

This is not really deal-breaking, but seeing this type of bugs when Windows PowerShell nags to try out PowerShell Core makes me wondering if it is really ready for this...

**Comment by iSazonov** [comment]
@Evengard Please share .psd1 file of the module.

**Comment by Evengard** [comment]
I can't share it as it is a feature of MS Windows system, it is a system component. Even if I managed to pull it off my system somehow, I'm not sure it would work "as is".
It is the Windows Server deduplication system component.

**Comment by Evengard** [comment]
Pulled the files from the system directories...

**Comment by Evengard** [comment]
[remoteIpMoProxy_Deduplication_2.0.0.0_localhost_13d1805e-fb86-4596-9492-04e48eaaffba.zip](https://github.com/PowerShell/PowerShell/files/4641333/remoteIpMoProxy_Deduplication_2.0.0.0_localhost_13d1805e-fb86-4596-9492-04e48eaaffba.zip)

Pulled the files from the system directories...

**Comment by vexx32** [comment]
If this module shipped with a Windows feature, it's quite possible the module has not been updated to work correctly in PowerShell 7. 

The Windows component modules are generally owned by the respective product teams rather than the PowerShell team, so there's a limit to what we can do from PowerShell itself, especially if the module happens to require some .NET API that did not get reimplemented in .NET Core.

I'd give it a try with an explicit `Import-Module -UseWindowsCompatibility` for the relevant module to see if it can be handled that way without losing too much functionality, but beyond that your best bet is usually filing a UserVoice ticket for the relevant feature so the team is aware that there is demand for the module to continue to be updated.

**Comment by Evengard** [comment]
I've actually tried to load the module with `Import-Module -SkipEditionCheck Deduplication` and... Well, it actually worked! The FreeSpace, SavedSpace and all other columns actually DID appear in the output!

Can it be that the bug is in the WinPSCompatSession remoting session?

**Comment by Evengard** [comment]
[Deduplication.zip](https://github.com/PowerShell/PowerShell/files/4641380/Deduplication.zip)

Pulled the actual module files from C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Deduplication

**Comment by vexx32** [comment]
> Can it be that the bug is in the WinPSCompatSession remoting session?

Yes and no. 😄 

Essentially whenever you have to go over a remoting session, PS has to serialize the data between the sessions, it's not able to just reach in and read the memory or whatever to see what's up. In some cases, that doesn't play well with how something needs to work, methods on the objects are typically missing, and the object type ends up changing, because oftentimes they don't have public constructors so you can't re-instantiate objects.

So... yeah, depending on how reliant the original code is on the objects being precisely as they originally were, passing objects over a remoting session absolutely can break things.

If it's able to work as-is in pwsh with just a -SkipEditionCheck that's probably the best way to handle it, but a lot of the Windows modules don't play so well with that either.

**Comment by Evengard** [comment]
Is there any way to force skipping edition check "on the fly" for some modules (some kind of per-module configuration)? Because this exact module is actually made available "by default" by the system, and usually no Import-Module is needed for using it.

**Comment by iSazonov** [comment]
> Is there any way to force skipping edition check "on the fly" for some modules 

The module is OS component so it should be tested and marked as Core compatible by MSFT.
You could use UserVoice site and/or Windows 10 Feedback tool to send the request to the module owners.

**Comment by Evengard** [comment]
So is there not a "hack" how to make it "marked" on my end only, by patching some files and whatnot?

**Comment by iSazonov** [comment]
WinCompat feature has not enable/disable lists today.

**Comment by Evengard** [comment]
https://windowsserver.uservoice.com/forums/295047-general-feedback/suggestions/40450393-make-deduplication-powershell-commands-compatible

Made a UserVoice related topic: https://windowsserver.uservoice.com/forums/295047-general-feedback/suggestions/40450393-make-deduplication-powershell-commands-compatible

**Comment by vexx32** [comment]
@Evengard if the module in question has a `PSD1` file you can look to add the `PSEdition` field in the manifest with `'Desktop', 'Core'` values in order for pwsh to always attempt to import it directly rather than via remoting.

YMMV though, but worth a shot I suppose. 🙂

**Comment by Evengard** [comment]
There is nothing of the sorts. The only thing which may be kinda close is `PowerShellVersion="3.0"`, but there os nothing abot PSEditions

**Comment by vexx32** [comment]
Yeah, you'll need to add the key to the manifest, it doesn't usually exist on older modules.

**Comment by Evengard** [comment]
Yup, adding `CompatiblePSEditions="Core","Desktop"` actually worked. Although I'm a bit worried about Windows System File Protection...

**Comment by vexx32** [comment]
Not that I'm aware of. You could opt to copy the module completely into a powershell 7-specific modules directory with the modified manifest and leave the system copy untouched?

**Comment by Evengard** [comment]
Yep, that actually worked! 
Actually I went even further:
`mklink /J %userprofile%\Documents\PowerShell\Modules\Deduplication C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Deduplication`
After this I didn't even needed to edit the module definition file at all! It just loaded natively.
I consider this kinda "workarounded" for now.

**Comment by rjmholt** [comment]
> Is there any way to force skipping edition check "on the fly"

This is deliberate, since it's not really something we want to encourage.

You could create a wrapper module with the same manifest. Then add a psm1 with the single line: `Import-Module <path-to-system-module> -SkipEditionCheck`. That way, if the module is updated in some way, everything will still work.

**Comment by Evengard** [comment]
I guess a junction link would act similarly after all, except that we would also use the actual module definition?

**Comment by rjmholt** [comment]
Yeah a link should work fine. The issue there is that the manifest expects things to be loaded alongside, so the PSM1 with some stars in the exports might be easier. You might also consider opening an issue in https://github.com/PowerShell/WindowsCompatibility so we can track the need to port the module

**Comment by Evengard** [comment]
Opened the issue in there too (https://github.com/PowerShell/WindowsCompatibility/issues/83)
