### ISSUE TITLE
Consistent release package naming

### ISSUE THREAD

**Issue by mhamri** [PowerShell/PowerShell#12718]
![image](https://user-images.githubusercontent.com/8991783/82297192-e1510d00-99e4-11ea-9d37-92d6a6a5acb1.png)

I noticed that the package release doesn't follow the correct naming. if the release is `7.0.1` the name shoudlnt' include `-1`. it cause our script break, when we only update an environment variable updating the PS version. our script is reading the ubuntu version and PS version dynamically based on the OS.

**Comment by mhamri** [comment]
I noticed some release mark the package with `lts` some without it
some with `preview` prefix some doesn't 

I suggest define a format and follow that religiously. it makes it much more predictable for the end-user

**Comment by iSazonov** [comment]
@mhamri Can you point the name convention you mean?

**Comment by vexx32** [comment]
I think the typical expectation is that the version in the package name should be a semver format, just like it's shown in `$PSVersionTable.PSVersion`.

**Comment by iSazonov** [comment]
>  the typical expectation

This does not work. There is a history. See https://www.linuxtopia.org/online_books/linux_system_administration/debian_linux_guides/debian_linux_reference_guide/ch-system.en_019.html

**Comment by KalleOlaviNiemitalo** [comment]
According to <https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-version>, if the upstream_version contains a hyphen (as in `7.1.0-preview.3`), then the syntax requires a debian_revision (such as `1.debian.11`).

**Comment by iSazonov** [comment]
> So the whole idea is the release for different platforms should follow same
pattern.

Previously we resolved some issues with package names because various distributions and repositories have specific requirements. So we can not unify the names and remove the `-1` in the specific name.
If you think it is critical we could try to fix this in new PR but before you _should_ check that you can publish packages in all repositories MSFT uses for publications.

**Comment by mhamri** [comment]
why not mix and match then?

so the main idea is the release names follow a predictable pattern. I I don't have any preference with what that pattern would be,

for example 
- all the `lts` versions use `lts` prefix for all the platforms. 
- if one need to use `-1` , put -1 for all of them not only those that need. the problem isn't having `-1` or not. but not being consistent through different platforms. 
- if one of the releases require to be lowercase, make all of them lowercase.

a general pattern that is predictable and can apply to all the platforms. there should be a minimum that can be met by all the distros and platforms

**Comment by KalleOlaviNiemitalo** [comment]
Instead of having your script parse or guess file names, can you use the [GitHub Releases API](<https://developer.github.com/v3/repos/releases/> "Releases | GitHub Developer Guide") to get the name of each file in each release?

…although the metadata available from there does not formally say which file is intended for which operating system, so the script would still have to rely on how that information is encoded in the file names.

**Comment by mhamri** [comment]
I don't think it would be possible without hardcoding the rules...
