### ISSUE TITLE
Removing a large tree with Remove-Item takes ~50% longer than cmd

### ISSUE THREAD

**Issue by BillyONeal** [PowerShell/PowerShell#12800]
In the following test I cloned LLVM twice, and measured how long it took to delete that repository with cmd's `rmdir /s /q` and pwsh's `Remove-Item -Recurse -Force`. cmd took ~4 seconds and pwsh took ~7.

![image](https://user-images.githubusercontent.com/1544943/82937886-c7b04800-9f45-11ea-9053-f01267a25973.png)

This is on a Ryzen Threadripper 3970X system (32c/64t), and the target disk is an Intel Optane SSD 900P. Both pwsh and cmd are limited by single threaded performance in this test (the SSD is nowhere near breaking a sweat and cmd or pwsh are constantly at ~5% CPU which is one core)

**Comment by BillyONeal** [comment]
Related: https://github.com/PowerShell/PowerShell/issues/11962

**Comment by SteveL-MSFT** [comment]
Looking at the code, it seems that it was a design decision to not use the .NET API to do the recursion but to do it within the FileSystemProvider so that ctrl+c can stop the operation.  An alternative might be to have the deletion on a separate thread, but killing a thread is always a bad idea as it can leave things in an undetermined state.

**Comment by BillyONeal** [comment]
cmd is able to do it with working ctrl+c and without needing to use `TerminateThread` 🤷
