### ISSUE TITLE
How to set PowerShell 7 as the default PowerShell?

### ISSUE THREAD

**Issue by nawfalhasan** [PowerShell/PowerShell#12872]
# Summary of the new feature/enhancement

As a user, it confuses me to see multiple versions of PowerShell in my machine (Windows 10). I want to get rid of old PowerShell (5/6/core/x86/x64/whatever) from Windows 10 and have only PowerShell 7.

If it's not possible, I want to set PowerShell 7 as the default shell. E.g. When I shift right click in File Explorer and clicks on "Open PowerShell window here" in the context menu, I want PowerShell 7 to come up.

**Comment by jhoneill** [comment]
There are likely to be things which use powershell.exe and rely on it being on the path, so you would need to replace PowerShell with pwsh in those cases. A small number of things will only run in Windows PowerShell. And Microsoft aren't very keen on switching the version from [win] + x to the download from the in-box version.  "PowerShell here" on the file menu in explorer is, I think. hard-coded. Anything can add to the context menu is via the registry registry hack.

**Comment by nawfalhasan** [comment]
Hmm, I think this ticket should be raised against Windows than PowerShell, then :) 

Just wondering if PowerShell team can pull this off. There should be something they can do to set it as default at least.

**Comment by thlac** [comment]
So there's a bunch of pretty long and convoluted reasons as to why this isn't the case for right now, but to keep a long story short, all of this is definitely on the radar but requires a bunch of collaboration between the .Net/PowerShell/Windows(/Windows Terminal) teams.

1. `pwsh` was decided back in like the original 6.0 beta days, so you probably won't see it changed to `powershell` ever, this is, among other things, to maintain compatibility with software relying on Windows PowerShell.
2. PowerShell has been based on .Net core, hence why it was previously known as PowerShell Core, this allowed it to be cross-platform, but at cost of compatibility and shorter support cadences. Powershell 7 already has pretty high compatibility, but is still limited by .Net Core 3.1 support cadences, .Net 5 will be the one singular .Net going forward, and therefor be supported for the lifetime of a given Windows release, which is crucial to potentially bundle PowerShell with Windows.
3. Changing the Win-X menu to allow different shells and/or consoles is also a discussion the Windows Terminal team is familiar with, again it requires OS support from the Windows team, but the same applies for PowerShell

Anyway PowerShell 7.1 should be releasing on .Net 5, so hopefully we'll learn more soon, but bear in mind I don't work for Microsoft or on any of the teams mentioned, so don't take it as me saying it's coming with PowerShell 7.1 because I rightly don't know.

**Comment by iSazonov** [comment]
The request is for Windows.

**Comment by promisepreston** [comment]
I had this same concern when working with Azure Powershell. My machine was running Powershell 4, and I wanted to upgrade it to Powershell 7. I installed Powershell 7, but it felt like a different application from Powershell 4, as I had 2 Powershell programs on my machine. I only wanted to upgrade Powershell 4 to Powershell 7.

Figured out later, that Powershell 4 and Powershell 7, act like 2 different programs with different application directories. All I had to do was to install Powershell 5.1 using this link [Microsoft Download Center](https://www.microsoft.com/download/details.aspx?id=54616). Powershell 5.1 replaced Powershell 4, and then I uninstalled Powershell 7, since Powershell 5.1 was okay for me to run Azure Powershell cmdlets.

I hope this helps.
