### ISSUE TITLE
Argument Autocompletion for user input

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShell/PowerShell#12893]
## Argument Autocompletion for user input
Until now, argument completion is defined by engind or code author, not the user. That’s why there is no arg completion for parameters like -Computername and -Credential which would be very helpful to have.
Can you add attributes to the engine that can be used to decorate parameters and cache all user input plus use the cached data to provide completion, similar to this proof of concept: https://powershell.one/code/14.html

This should go well together with the new Powershell prediction feature: can you consider taking parameter values from command history and use them to provide automatic argument completion for any parameter that has no completer?

## Proposed technical implementation details (optional)

Here is fully working sample code:

https://powershell.one/code/14.html

Note that this example is deriving from a transformation and from a completion attribute to enable caching and completion. This could and should of course combined in one new attribute.

**Comment by iSazonov** [comment]
@daxian-dbw Where could the idea be implemented in PowerShell or in PSReadline?

**Comment by SeeminglyScience** [comment]
It would need to be in PowerShell.  PSReadLine gets all of it's tab completion from `CommandCompletion.CompleteInput`.

**Comment by jhoneill** [comment]
I think this suggestion has a more generic form. 
Parameter attribute classes should be able to support multiple methods so that one attribute declaration can specify a completion action and a transformation/validation action.  Code I'm working on at the moment needs to specify completer and either transformer or validator. It's possible to do it as it stands, but it is harder than it needs to be and makes for uglier code. 

In this case the idea is the function author gets to say "cache values for this attribute", and there was an implied question about whether PSReadline should be doing this - the latter gives more space for the user to determine what is and isn't cached, and doesn't need functions to be updated. How to choose what to cache (which implies ignoring default completer values) would need to be worked out.... 

There are other things which should be looked at. It would help writers or transformers if they had a better view of other parameters which have been given (this value is only OK if that parameter is one of these values) , and at present a validationSet gets used in preference to a completer and enums fields in preference to either, so it's possible to say "Only these values from the enum are allowed here" or "These values are preferred , and those are also allowed". And various other things to do with behaviour of classes from modules - I'd like to load a module from @TobiasPSP  with this in, and use it in my functions but there many traps on the way to doing that.
