### ISSUE TITLE
Can't do a simple cd to a folder? 

### ISSUE THREAD

**Issue by gekidoslair** [PowerShell/PowerShell#12900]
## Steps to reproduce

```powershell

Open powershell, type cd C:\Program Files\

Press enter. Fails. 

## Expected behavior

I expect that a command line tool can actually do simple operations like changing a directory without exploding. 

## Actual behavior

Throws 'invalid argument exception' 

## Environment data

<!-- provide the output of $PSVersionTable -->

Windows 10


<img width="864" alt="2020-06-04 09_37_41-Windows PowerShell" src="https://user-images.githubusercontent.com/4552687/83786076-139a7580-a647-11ea-818b-436e03be61d6.png">

**Comment by kilasuit** [comment]
this works if you do 

`cd C:\pr` then hit tab (to tab complete) where it will wrap this to the correct path which is `'C:\Program Files\'` in PowerShell and has been the case since v1

**Comment by rkeithhill** [comment]
Specifying an argument to a command that has spaces in it can be accomplished in two ways.  First, you can quote the arg e.g.:
```
cd 'C:\Program Files\'
```
In fact, if you type `C:\Prog<tab>`, PowerShell will tab-complete the path and add the quotes for you.  You can also escape the path e.g.:
```
cd C:\Program` Files\
```
Now you could argue that this one command could be made a wee bit smarter and not require either quotes or escaping.  This can be done.  In the PSCX extension, we supply a `Set-LocationEx` that works the way you expect.

**Comment by jhoneill** [comment]
Bash gives "too many arguments" if the name has a space and no quotes. Most shells need quotes around most parameters with spaces in. However cd , dir and a few interneal 
CMD is odd because `cd program files`  doesn't need quotes , but `Dir program files` won't work unless quotes are added.  I'd take a guess that hasn't changed since OS/2 (and then NT3.1) allowed spaces in file names.

**Comment by iSazonov** [comment]
I guess we could implement the magic for Set-Location. This will block adding new positional parameters but it will work with great UX if user pastes such path. Cons - users will expect such behavior for other cmdlet too which is not always possible.
Another thought is to make PowerShell so smart to understand current paste context and if it is a path than quote inserted string.

**Comment by jhoneill** [comment]
@iSazonov  is there any need?
 If you type rather than tab complete a path with a space in, then CMD knows that cd takes only 1 parameter and everything after `"cd[space]"` is the directory to change to. dir takes parameters and CMD can't pull the same trick. Running `notepad C:\program files\foo\foo.ini` won't join the two parts of the path together. CD only works because cmd, inherited (via command.com) the cp/m trick of doing some actions inside the command line handler, PSReadline could do it, but "quote things with spaces in" is pretty widely understood and quickly learned whereas creating an exception which applies to a single command sets bad expectations.

**Comment by vexx32** [comment]
Yeah I don't really see a need to fix this. It behaves according to all expectations from existing commands. The one exception that was created over 20 years ago isn't a good enough reason to kludge things into working IMO.

**Comment by rkeithhill** [comment]
I agree that this doesn't need to be "fixed" in PowerShell.  If someone really wants this, there are ways **they** can implement the functionality.

**Comment by KalleOlaviNiemitalo** [comment]
> it uses `$UnboundArguments` to construct the space-separated path.

I see, it uses `[Parameter(ValueFromRemainingArguments=$true)] [string[]] $UnboundArguments` and then `$UnboundArguments -join ' '`.  But this collapses consecutive spaces, unlike `CD` in cmd.exe.

```
C:\temp>MKDIR "hey  there"

C:\temp>CD hey  there

C:\temp\hey  there>
```

How would one implement a PowerShell `CD` command that preserves the number of spaces?

**Comment by rkeithhill** [comment]
Alternatively, you could pick out the path from `$MyInvocation.Line`.

**Comment by SeeminglyScience** [comment]
> Alternatively, you could pick out the path from `$MyInvocation.Line`. Beware though that the `Line` can have other command before and/or after your cd command e.g. `get-date; mycd C:\Foo Bar; get-uptime`

Yeah here's a really basic and flimsy version (partially because it's not carefully written and partially because it uses a non-public API)

<details>

<summary>Set-LocationProxy (click to expand)</summary>

```powershell
using namespace System.Management.Automation
using namespace System.Management.Automation.Language

function Set-LocationProxy {
    [CmdletBinding()]
    param(
        [Parameter(ValueFromRemainingArguments)]
        [string[]] $UnboundArgs
    )
    process {
        $extent = [InvocationInfo].
            GetProperty('ScriptPosition', [System.Reflection.BindingFlags]'NonPublic, Instance').
            GetValue($MyInvocation)

        $ast = [Parser]::ParseInput(
            $extent.StartScriptPosition.GetFullScript(),
            $extent.File,
            [ref] $null,
            [ref] $null)

        $commandAst = $ast.Find(
            {
                param($a) end {
                    return $a -is [CommandAst] -and
                        $a.Extent.StartOffset -eq $extent.StartOffset -and
                        $a.Extent.EndOffset -eq $extent.EndOffset
                }
            },
            <# searchNestedScriptBlocks: #> $true)

        $binding = [StaticParameterBinder]::BindCommand($commandAst)
        $elements = $binding.BoundParameters['UnboundArgs'].Value.Elements
        $spacesBefore = [int[]]::new($elements.Count)
        for ($i = 1; $i -lt $spacesBefore.Length; $i++) {
            $prev = $elements[$i - 1]
            $current = $elements[$i]

            # Doesn't account for comments and probably other things that would skew this.
            $spacesBefore[$i] = $current.Extent.StartOffset - $prev.Extent.EndOffset
        }

        $sb = [System.Text.StringBuilder]::new()
        for ($i = 0; $i -lt $UnboundArgs.Length; $i++) {
            $spacesToAdd = $spacesBefore[$i]
            if ($spacesToAdd) {
                $null = $sb.Append(' '[0], $spacesToAdd)
            }

            $null = $sb.Append($UnboundArgs[$i])
        }

        return $sb.ToString()
    }
}
```

</details>

**Comment by gekidoslair** [comment]
gotta say that I find it hilarious that I'd need to use that giant script, figure out how to run it etc just so that I can copy and paste a directory path properly into a command line tool. 

it's 2020, tools should do stuff for people, not the opposite.

**Comment by KalleOlaviNiemitalo** [comment]
Too bad that this does not work:

```PowerShell
New-Alias -Name cd -Force -Option AllScope -Value "Set-Location --%"
```

Although I suppose such a feature would make PowerShell scripts even harder to parse without running them, as any command might then turn out to be an alias that changes how the rest of the line has to be parsed.

If the exceptional `cd` syntax is only for interactive use, then perhaps it would be best implemented in PSReadLine as a transformation that happens before PowerShell proper parses the command. If I understand correctly, PowerShell calls `PSConsoleHostReadLine` only to read commands, not to read parameters.

**Comment by kilasuit** [comment]
> gotta say that I find it hilarious that I'd need to use that giant script, figure out how to run it etc just so that I can copy and paste a directory path properly into a command line tool.

Where are you copying the path from? 
Also whilst this may not be a current feature it is something that I do think should be included in the wider PowerShell experience, but it should not be added in here, it should be added within PSReadLine Module (which is shipped with PowerShell anyway)

> it's 2020, tools should do stuff for people, not the opposite.
Yes, but the right tool needs to be where the changes get made, and directly in PowerShell is not IMO the right place for this.

> Too bad that this does not work:
> 
> ```powershell
> New-Alias -Name cd -Force -Option AllScope -Value "Set-Location --%"
> ```
> 
> Although I suppose such a feature would make PowerShell scripts even harder to parse without running them, as any command might then turn out to be an alias that changes how the rest of the line has to be parsed.
> 
> If the exceptional `cd` syntax is only for interactive use, then perhaps it would be best implemented in PSReadLine as a transformation that happens before PowerShell proper parses the command. If I understand correctly, PowerShell calls `PSConsoleHostReadLine` only to read commands, not to read parameters.

Totally agree and I started to comment something similar, but then rebooted and can't find the recovered tab with that comment. But I have raised this over in PSReadline module in https://github.com/PowerShell/PSReadLine/issues/1593 to be continued to be tracked as a UX improvement, which I do believe to be better lived in PSReadline than within the PowerShell Engine

**Comment by eugenesvk** [comment]
> This will block adding new positional parameters

not really, you can still add a special logic if they're added at the beggining, e.g.
`cd -P C:\path\with space`, where `-P` is a parameter (and there can't be a path that starts with a `-P`, so it can only be a parameter)

But otherwise I'd just want to add my voice to support the special case of `cd` being able to treat everything after it as a raw string path also ignoring all the `[]` and stuff, so that this would work when copy&pasted from an explorer
`cd -P C:\path\with space\and [brackets]`
(with the exception of `-P`-like parameters that can never appear as a natural result of a user's copy&paste operation)

I believe `cd` is so special that it can behave in such an exceptional way! :)

**Comment by eugenesvk** [comment]
> The one exception that was created over 20 years ago isn't a good enough reason to kludge things into working IMO.

The reason is not this old exception, but rather the fact that `cd` is unique and frequently used enough to warrant such an exception even today

**Comment by jhoneill** [comment]
@eugenesvk  
Yes, CD in cmd.exe works differently from copy or any other command or from cd in unix shells. Exceptions are (generally) bad. _Make a command less like the same command on linux, AND less like other PowerShell commands to make it more like MS-DOS_ is likely to fall on deaf ears.   
BTW if you are copying from explorer use "copy as path" and it puts double quotes round the path in the clipboard.   

CD is an _alias_ and since V1 I've been changing the default to "Push-Location" instead of "Set-Location", I now use a function which I've shared https://gist.github.com/jhoneill/47f5151b22a1dabb4ddc79c083162f77 
If you _want_ to make CD different you can add `ValueFromRemainingArguments=$true` to the Path parameter and add `$path = $path -join ' '` - which will work for most cases like `program files` but not for multiple spaces. Whether you want to take my additions to make "cd ...."  into `cd ..\..\..` make `cd ~` tab complete make `cd =` tab through your directory stack etc is your choice :-)

**Comment by eugenesvk** [comment]
> Exceptions are (generally) bad.

Except when they are awesome! And then we have to go back to the specific case of `cd` and discuss where it belongs

> _Make a command less like the same command on linux, AND less like other PowerShell commands to make it more like MS-DOS_ is likely to fall on deaf ears.

Yeah, let's not invoke the spirit of that awful old shell to make it easier on our ears! :) But otherwise this has been a pain point in all the other systems as copy&paste of a path to a cd is system-agnostic ;)

> BTW if you are copying from explorer use "copy as path" and it puts double quotes round the path in the clipboard.

Thanks, but it's a) a bit inconvenient and b) a bit "dumb" (e.g. it doesn't escape square brackets, which is needed in pwsh, though a custom cd alias fixes this one)

> CD is an _alias_ and since V1 I've been changing the default to "Push-Location" instead of "Set-Location", I now use a function which I've shared https://gist.github.com/jhoneill/47f5151b22a1dabb4ddc79c083162f77
> ...

Thanks for the suggestion, but I'm already using `cd` as an alias to a simple command `Set-Location -LiteralPath ($args -join ' ' | Out-String -NoNewline)`, which solves most of my issues by allowing me to simply paste my paths to get there, but as you correctly mentioned, two spaces would break it and then I'd have to quote
(also, I'm using `..` to go up, which is more convenient than `cd ..`)

Anyway, there seems to be two general avenues to achieve the desired behavior: 
- with support from a shell: I've recently encountered [xonsh](https://xon.sh) shell and it does seem to have the ideal solution — the `cd! ` macro that treats all input as a  raw string, allowing you to paste arbitrary path without any quoting or other escaping (and it's possible with a simple, but not yet available addon, to convert all `cd ` calls into `cd! ` ones, making this the default)!

- with support from a terminal: autoescaping on paste. That'd be similar to what is already possible with e.g. WSL in Conemu with some bridge magic, where all paths are converted to linux format and escaped on copy&paste. So strangely enough using a "foreign environment" on Windows is more convenient than using the native one!
