### ISSUE TITLE
ScriptBlock.InvokeWithContext mutates variable lists passed as arguments

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#12928]
If passed a variable that is (for lack of established term afaik) intrinsic to the scope, the variable entry will be removed from the list passed in `variablesToDefine`.  This includes vars such as `$this`, `$input`, `$_` and `$PSItem`.

## Steps to reproduce

```powershell
$list = [System.Collections.Generic.List[psvariable]]@(
    [psvariable]::new('_', $null),
    [psvariable]::new('something-not-scope-intrinsic', $null))

{}.InvokeWithContext($null, $list, @())
$list
```

## Expected behavior

```none
Name                           Value
----                           -----
_
something-not-scope-intrinsic
```

## Actual behavior

```none
Name                           Value
----                           -----
something-not-scope-intrinsic
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.2
PSEdition                      Core
GitCommitId                    7.1.0-preview.2
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by bpayette** [comment]
@SeeminglyScience  Correct and by design. Intrinsic variables already have a set of rules for when and how they are bound. This API was not intended to change those rules. What it does is allow you to provide ambient context to the script block when it executes. This is used by DSC internally to define the set of resources (functions) available inside a configuration (function). For example, if you want to make a function available to a scriptblock without setting it in the current scope and thus making it visible to everything you do, you can use this API. It's particularly useful in modules where you can't use dynamic scoping to provision an execution environment. Does that make sense?

**Comment by bpayette** [comment]
@SeeminglyScience  Correct and by design. Intrinsic variables already have a set of rules for when and how they are bound. This API was not intended to change those rules. What it does is allow you to provide ambient context to the script block when it executes. This is used by DSC internally to define the set of resources (functions) available inside a configuration (function). For example, if you want to make a function available to a scriptblock without setting it in the current scope and thus making it visible to everything you do, you can use this API. It's particularly useful in modules where you can't use dynamic scoping to provision an execution environment. Does that make sense?

**Comment by SeeminglyScience** [comment]
@bpayette It works, you can set intrinsic variables with this API.  The API iterates the `List<PSVariable>` looking for intrinsic variables and removes them to be handled separately (through `InvokeWithPipe` parameters).

This issue is just about the `List<>` argument getting mutated because of internal logic.  I would have expected a copy of the list to have been made if changes were needed before it passed the list to `InvokeWithPipe`.
