### ISSUE TITLE
Access Remote Computer Via A Proxy Server In PS

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#12969]
## Summary of the new feature/enhancement
I am not sure whether it works with New-PSSessionOption
In my enterprise env,
My computer is A-COMPUTER, my server is B-SERVER, production computers is ALL-COMPUTERS (located in different subnet).

From A-COMPUTER, I can access B-SERVER,  from B-SERVER, I can access ALL-COMPUTERS.
But I can not access All-COMPUTERS from A-COMPUTER.
But I want to access All-COMPUTER from A-COMPUTER directly.

Can I make B-SERVER as a proxy , then A-COMPUTER use S-SERVER as a gateway to access All-COMPUTERS.

But what kind of proxy I need to setup on B-SERVER , and how to use this proxy within PS.

I know how to use credssp to access send hop , but seems only can manipulate the send hop using some kind of cmdlet like invoke-command , I can't enter a new PSSession within an exist PSSession

**Comment by iSazonov** [comment]
You can use explicit user/password for second hop.

**Comment by daxian-dbw** [comment]
I don't think double hop is allowed in PowerShell remoting. /cc @PaulHigin for comments.

**Comment by PaulHigin** [comment]
> I can't enter a new PSSession within an exist PSSession

PowerShell used to restrict double hop within the Enter-PSSession cmdlet.  However, this restriction was removed in PowerShell version 6-something by I think @SteveL-MSFT.  Invoke-Command always allowed a double hop.

However, Windows OS itself prevents a second hop since the WinRM remoting session is based on Kerberos credential-less log on.  So there is no way to do a second hop without providing credentials, either via credssp or PSCredential.  But this is not recommended since the credentials passed to the target machine are vulnerable even though an attempt is made to be keep them secure.

**Comment by iSazonov** [comment]
Doc reference https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ps-remoting-second-hop?view=powershell-7
