### ISSUE TITLE
PSReadLine: expired certificates?

### ISSUE THREAD

**Issue by StefanRickli** [PowerShell/PowerShell#13000]
## Steps to reproduce

- Install latest PowerShell Core release 7.0.2
- Set the execution policy to "AllSigned": In an elevated PS session: `Set-ExecutionPolicy -ExecutionPolicy AllSigned -Scope LocalMachine`
- After closing the elevated PS window, open a new PS window

## Expected behavior

Directly get to the command prompt of the PS window.

## Actual behavior

Instead, before getting to the command prompt, I get the following certificate warnings:

```
PowerShell 7.0.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.


Do you want to run software from this untrusted publisher?
File C:\program files\powershell\7\Modules\PSReadLine\PSReadLine.format.ps1xml is published by CN=Microsoft
Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US and is not trusted on your system. Only run scripts
 from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): r

Do you want to run software from this untrusted publisher?
File C:\program files\powershell\7\Modules\PSReadLine\PSReadLine.psm1 is published by CN=Microsoft Corporation,
O=Microsoft Corporation, L=Redmond, S=Washington, C=US and is not trusted on your system. Only run scripts from trusted
 publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): r
PS C:\Users\StefanRickli>
```

## Environment data

Here's the signature of the two files in question:
![image](https://user-images.githubusercontent.com/19881323/85182874-43be5700-b28a-11ea-95d5-94728f45ab92.png)

You can see that the certificate expired on 02.05.2020. Might this be the problem?

```
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by KalleOlaviNiemitalo** [comment]
I don't think this is caused by certificate expiration; the file has a timestamp countersignature. From the source code, it seems that the "untrusted publisher" prompt appears if the signature is valid but the certificate is not in the Trusted Publishers store.  <https://github.com/PowerShell/PowerShell/blob/01d37887121f5cba743573c40f9d1827adc25a98/src/System.Management.Automation/security/SecurityManager.cs#L279-L293>

**Comment by KalleOlaviNiemitalo** [comment]
I was wondering why Windows PowerShell manages to load its version of PSReadLine without prompting, even when -ExecutionPolicy AllSigned is specified and the certificate is not in the Trusted Publishers store.

In PowerShell 7.1.0-preview.3, PSAuthorizationManager.CheckPolicy skips the signature checks if the execution policy is Unrestricted and SecuritySupport.IsProductBinary returns true: <https://github.com/PowerShell/PowerShell/blob/01d37887121f5cba743573c40f9d1827adc25a98/src/System.Management.Automation/security/SecurityManager.cs#L186-L191>

However, the ExecutionPolicy.AllSigned case does not seem to call SecuritySupport.IsProductBinary. Besides, SecuritySupport.IsProductBinary now returns false for the PSReadLine files.

Windows PowerShell 5.1 on Windows 10 Version 2004:

```
PS C:\> (Get-Module -Name PSReadLine).Path
C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.0.0\PSReadLine.psm1
PS C:\> [System.Management.Automation.Internal.SecuritySupport]::IsProductBinary("C:\Program Files\WindowsPowerShell\Modules\psreadline\2.0.0\PSReadLine.psm1")
True
```

PowerShell 7.1.0-preview.3 on Windows 10 Version 2004:

```
PS C:\> (Get-Module -Name PSReadLine).Path
C:\program files\windowsapps\microsoft.powershellpreview_7.1.3.0_x64__8wekyb3d8bbwe\Modules\PSReadLine\PSReadLine.psm1
PS C:\> [System.Management.Automation.Internal.SecuritySupport]::IsProductBinary("C:\program files\windowsapps\microsoft.powershellpreview_7.1.3.0_x64__8wekyb3d8bbwe\Modules\PSReadLine\PSReadLine.psm1")
False
PS C:\> [System.Management.Automation.Internal.SecuritySupport]::IsProductBinary("C:\Program Files\WindowsPowerShell\Modules\psreadline\2.0.0\PSReadLine.psm1")
False
```

Utils.IsUnderProductFolder returns true: <https://github.com/PowerShell/PowerShell/blob/01d37887121f5cba743573c40f9d1827adc25a98/src/System.Management.Automation/security/SecuritySupport.cs#L394-L400>

```
PS C:\> [System.Management.Automation.Cmdlet].Assembly.GetType("System.Management.Automation.Utils",$true).GetMethod("IsUnderProductFolder", [System.Reflection.BindingFlags]"Static,NonPublic").Invoke($null, @("C:\program files\windowsapps\microsoft.powershellpreview_7.1.3.0_x64__8wekyb3d8bbwe\Modules\PSReadLine\PSReadLine.psm1"))
True
```

I guess SignatureHelper.GetSignature then does not set fileSignature.IsOSBinary.

Because Utils.IsUnderProductFolder considers PowerShell 7 the product, I think SecuritySupport.IsProductBinary should be changed to return true for binaries that are installed from the PowerShell 7 package, even if they are not OS binaries.

**Comment by iSazonov** [comment]
What is PSReadline version you use?

/cc @daxian-dbw

**Comment by KalleOlaviNiemitalo** [comment]
@iSazonov on Windows, this is reproducible with the PSReadLine 2.0.1 that installs with PowerShell 7.1.0-preview.3. <https://github.com/PowerShell/PowerShell/blob/01d37887121f5cba743573c40f9d1827adc25a98/src/System.Management.Automation/security/SecuritySupport.cs#L402-L405>

**Comment by daxian-dbw** [comment]
> I was wondering why Windows PowerShell manages to load its version of PSReadLine without prompting, even when -ExecutionPolicy AllSigned is specified and the certificate is not in the Trusted Publishers store.

What PSReadLine version is Windows PowerShell using? The one that shipped in-box of Windows?

**Comment by KalleOlaviNiemitalo** [comment]
Yes, I think this the in-box version of PSReadLine:

```
PS C:\> Get-Module -Name PSReadLine

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...


PS C:\> (Get-Module -Name PSReadLine).Path
C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.0.0\PSReadLine.psm1

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

And PowerShell 7 should likewise not prompt when loading the version of PSReadLine that was installed as part of PowerShell 7.

**Comment by daxian-dbw** [comment]
OK, that explains it. The PSReadLine that's shipped in-box of Windows is Windows catalog signed (because it's part of the Windows), so it's trusted by default.
The `PSReadLine` shipped with PS 7 or installed from PowerShell Gallery is Microsoft signed, but that certificate is not trusted by default, and you need to add it to the trusted publisher to make it work smoothly with `AllSigned` execution policy.

**Comment by KalleOlaviNiemitalo** [comment]
That's the explanation, but I don't think the behavior makes sense.
If the files are part of the PowerShell installation package, then PowerShell should trust them.

**Comment by daxian-dbw** [comment]
> That's the explanation, but I don't think the behavior makes sense.
If the files are part of the PowerShell installation package, then PowerShell should trust them.
In contrast, if a user later installs a newer version of PSReadLine from PowerShell Gallery, then I think it's okay to prompt for trust.

We can further discuss that behavior. Loop in our security SMEs @TravisEz13 and @PaulHigin to comment on this.

**Comment by TravisEz13** [comment]
> We can further discuss that behavior. Loop in our security SMEs @TravisEz13 and @PaulHigin to comment on this.

Unlike with windows, we have no way of verifying if a file comes from the installation package.  Therefore, the PowerShell execution policy zero trust stance is in effect.  If you want this to change, I would suggest that you file an [feature requests](https://github.com/PowerShell/PowerShell/issues/new?assignees=&labels=Issue-Enhancement&template=Feature_Request.md&title=Feature+Request), with the reasoning and let people discuss the pros and cons.  You can mention this specific issue, but the issue is really all modules.  

I would recommend the issue be something like this

```
Title: Update execution policy to trust the Windows and Microsoft Certificates by default

Description:

All the modes of execution policy that rely on certificates will prompt if the certificate is not trusted, making these features less useful.
< further explanation >
```

Or perhaps someone can come up with a better design, but living outside of windows, we don't have system file production (the catalog signing only enabled system file protection) and cannot trust the files that come with the installation.

**Comment by KalleOlaviNiemitalo** [comment]
Should PowerShell 7 with `-ExecutionPolicy AllSigned` implicitly trust the PSReadLine module that is in-box in Windows, when there is nothing related in the user's Trusted Publishers or Untrusted Certificates certificate stores? Currently, PowerShell 7.0.2 prompts for trust when loading that, but Windows PowerShell 5.1 loads it without prompting.

```
C:\>"C:\Program Files\PowerShell\7\pwsh.exe" -ExecutionPolicy AllSigned
PowerShell 7.0.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.


Do you want to run software from this untrusted publisher?
File C:\program files\powershell\7\Modules\PSReadLine\PSReadLine.format.ps1xml is published by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond,
 S=Washington, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): D
Cannot load PSReadline module.  Console is running without PSReadline.
PS C:\> Get-AuthenticodeSignature -LiteralPath "C:\program files\powershell\7\Modules\PSReadLine\PSReadLine.format.ps1xml"


    Directory: C:\program files\powershell\7\Modules\PSReadLine

SignerCertificate                         Status  StatusMessage        Path
-----------------                         ------  -------------        ----
62009AAABDAE749FD47D19150958329BF6FF4B34  Valid   Signature verified.  PSReadLine.format.ps1xml

PS C:\> Get-AuthenticodeSignature -LiteralPath "C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.0.0\PSReadLine.format.ps1xml"


    Directory: C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.0.0

SignerCertificate                         Status  StatusMessage        Path
-----------------                         ------  -------------        ----
A4341B9FD50FB9964283220A36A1EF6F6FAA7840  Valid   Signature verified.  PSReadLine.format.ps1xml

PS C:\> exit

C:\>"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy AllSigned
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\> (Get-Module PSReadLine).Path
C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.0.0\PSReadLine.psm1
PS C:\> Get-AuthenticodeSignature -LiteralPath "C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.0.0\PSReadLine.psm1"


    Directory: C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.0.0


SignerCertificate                         Status  Path
-----------------                         ------  ----
A4341B9FD50FB9964283220A36A1EF6F6FAA7840  Valid   PSReadLine.psm1
```

(edited to minimize whitespace in tables)

**Comment by daxian-dbw** [comment]
Reopen the issue given @KalleOlaviNiemitalo's question in the last comment.

**Comment by TravisEz13** [comment]
> Should PowerShell 7 with -ExecutionPolicy AllSigned implicitly trust the PSReadLine module that is in-box in Windows, when there is nothing related in the user's Trusted Publishers or Untrusted Certificates certificate stores? 

No, PowerShell Execution Policy is zero-trust.  This was answered [here](https://github.com/PowerShell/PowerShell/issues/13000#issuecomment-656825362)

> Therefore, the PowerShell execution policy zero trust stance is in effect.

**Comment by pobin6** [comment]
May try different version, I meet the same problem in the lastest version, and in the 2.3.4 is ok.
