### ISSUE TITLE
Code copied from Microsoft Docs often has characters removed when pasting into PowerShell, resulting in syntax errors

### ISSUE THREAD

**Issue by jdrch** [PowerShell/PowerShell#13102]
## Steps to reproduce

1. Copy PS code from, e.g. [here](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/deploy-standalone-storage-spaces#windows-powershell-equivalent-commands-for-creating-storage-pools_)
2. Paste it into an elevated PS by right-clicking in the PS window

## Expected behavior

Code is pasted verbatim

## Actual behavior

Dashes and quotes are stripped from code, resulting in syntax errors when the command is run.

## Environment data

```
PS C:\Windows\System32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
IIRC this is a [PSReadLine](../../PSReadLine) issue, something to do with how it reads/handles Unicode characters (sometimes the docs pages include things like emdash instead of hyphens, etc.)

See these existing issues: https://github.com/PowerShell/PSReadLine/issues/1603 and https://github.com/PowerShell/PSReadLine/issues/760

If you've any more detail that isn't yet captured in those issues, please add it! For now I'll mark this one as external since PSReadLine itself isn't maintained in this particular repository itself. 😊

**Comment by daxian-dbw** [comment]
@jdrch With `PSReadLine` imported, can you correctly copy/paste with <kbd>Crtl+v</kbd>?

**Comment by jdrch** [comment]
@daxian-dbw Yeah I realized after the fact that the keyboard combo works. Thanks!

**Comment by daxian-dbw** [comment]
Just FYI, this is likely a bug in dotnet core. I opened https://github.com/dotnet/runtime/issues/38966
