### ISSUE TITLE
ConvertTo-JSON adds both ObjectGUID and ObjectGuid properties, causing different casing error in resulting JSON

### ISSUE THREAD

**Issue by brentashley** [PowerShell/PowerShell#13145]
## Steps to reproduce

```powershell
# get any AD group
$g = Get-ADGroup Administrators

"=== group object"
$g

$json = $g | convertto-json

"=== json - note there are both ObjectGuid and ObjectGUID properties"
$json

# generates error when trying to convert back to object
$gj = $json | convertFrom-json 
```

## Expected behavior

only one ObjectGUID property with original object's casing

## Actual behavior

```
[DBG]: PS C:\Users\Administrator\work\ad-automation> .\casing.ps1

=== group

DistinguishedName : CN=Administrators,CN=Builtin,DC=test,DC=local
GroupCategory     : Security
GroupScope        : DomainLocal
Name              : Administrators
ObjectClass       : group
ObjectGUID        : 5bfb3b7d-8dd0-41df-9c82-7e92c1585619
SamAccountName    : Administrators
SID               : S-1-5-32-544

=== json
{
    "GroupScope": 0,
    "GroupCategory": 1,
    "SamAccountName": "Administrators",
    "SID": {
      "BinaryLength": 16,
      "AccountDomainSid": null,
      "Value": "S-1-5-32-544"
    },
    "DistinguishedName": "CN=Administrators,CN=Builtin,DC=test,DC=local",
    "Name": "Administrators",
    "ObjectClass": "group",
==> "ObjectGuid": "5bfb3b7d-8dd0-41df-9c82-7e92c1585619",
    "PropertyNames": [
      "DistinguishedName",
      "GroupCategory",
      "GroupScope",
      "Name",
      "ObjectClass",
      "ObjectGUID",
      "PSShowComputerName",
      "SamAccountName",
      "SID"
    ],
    "AddedProperties": [],
    "RemovedProperties": [],
    "ModifiedProperties": [],
    "PropertyCount": 9,
==> "ObjectGUID": "5bfb3b7d-8dd0-41df-9c82-7e92c1585619",
    "PSShowComputerName": []
}

ConvertFrom-Json: C:\Users\Administrator\work\ad-automation\casing.ps1:11:15
Line |
  11 |  $gj = $json | convertFrom-json
     |                ~~~~~~~~~~~~~~~~
     | Cannot convert the JSON string because it contains keys with different casing. Please use the
     | -AsHashTable switch instead. The key that was attempted to be added to the existing key 'ObjectGuid'
     | was 'ObjectGUID'.

```

## Environment data

```Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
(same experience with PowerShell 5.1)

## Note

Note that the ADGroup object has an ObjectGuid property but in its PropertyNames collection, it is spelled "ObjectGUID".  This is the same when I look at an ADUser object.  

This may indicate that the source of the problem is with the AD library (if you concur, please cross-post there or ask me to), however I contend that the JSON routines should recognize that this is an anomaly which is going to result in malformed JSON and throw a warning or error.

**Comment by mklement0** [comment]
I would definitely alert the AD team to the inconsistency.

As for the JSON representation: it seems that the properties named in the `.PropertyCollection` are also surfaced as top-level properties, in addition to the type-native ones, and the case variation is then considered a distinct property - I personally don't know enough about `ConvertTo-Json` to know why and where that happens.

While certainly undesired here, note that the result _is_ well-formed JSON, where - unlike in PowerShell - identifiers are case-_sensitive_, so case variations of the same property name - however ill-advised - _are_ allowed.

As the error message suggests, the way to work around the issue is to use `-AsHashtable` with `ConvertFrom-Json`, which returns a `[hashtable]` instance with case-_sensitive_ key definitions and lookups (unlike regular PowerShell hashtables).

Note that another thing that JSON allows is property names that are the _empty string_. There too `ConvertFrom-Json` cannot be used, and `-AsHashtable` is required.

**Comment by brentashley** [comment]
Thanks for the analysis.  I agree that it's valid JSON, so I suppose my intent was to suggest that if the export is going to result in JSON that the import is going to complain about, a warning at the export side might also help.

For now I am avoiding the issue by selecting specific properties when exporting.  I will, however, seek to alert the AD team.
