### ISSUE TITLE
PowerShell 7.0.3 - Get-Package cmdlet not working

### ISSUE THREAD

**Issue by Barney87** [PowerShell/PowerShell#13225]
## Steps to reproduce

Get-Package
or
Get-Package -Provider Programs -IncludeWindowsInstaller

```

## Expected behavior

Lists all installed applications on the machine working on below version

Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\WINDOWS\system32> Get-Package -ProviderName Programs -IncludeWindowsInstaller

Name                           Version          Source                           ProviderName
----                           -------          ------                           ------------
Windows Driver Package - Cr... 01/23/2018 3....                                  Programs
Greenshot 1.2.10.6             1.2.10.6                                          Programs
Logitech Unifying Software ... 2.10.37                                           Programs
Microsoft Visual Studio 201... 10.0.60825                                        Programs
Mozilla Firefox 75.0 (x64 e... 75.0                                              Programs
Mozilla Maintenance Service    75.0                                              Programs
Notepad++ (64-bit x64)         7.8.7                                             Programs
Microsoft Office 365 ProPlu... 16.0.12527.20880                                  Programs
Intel(R) Network Connection... 22.9                                              Programs
Sophos Endpoint Agent          2.7.8                                             Programs
VLC media player               3.0.10                                            Programs
PowerShell 7-x64               7.0.3.0                                           Programs


PS C:\WINDOWS\system32>

```

## Actual behavior

PS C:\Program Files\PowerShell\7> Get-Package
PS C:\Program Files\PowerShell\7>

or 

PS C:\Program Files\PowerShell\7> Get-Package -Provider Programs -IncludeWindowsInstaller
Get-Package: Unable to find package providers (Programs).
PS C:\Program Files\PowerShell\7>

```

## Environment data

<!-- provide the output of $PSVersionTable -->

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by ThomasNieto** [comment]
@iSazonov should this be moved to the oneget repo?

**Comment by iSazonov** [comment]
@ThomasNieto I added /cc to owners - they can move if needed.

**Comment by whitTech** [comment]
Hi all,

Has there been any progress on this issue? Alternatively, can someone explain the reason for the issue, and/or recommend some workarounds.

Many thanks.

**Comment by whitTech** [comment]
Hi all,

Has there been any progress on this issue? Alternatively, can someone explain the reason for the issue, and/or recommend some workarounds?

Many thanks.

**Comment by whitTech** [comment]
Also, potential dupe of #7844?

**Comment by jamacoe** [comment]
Still not working on PS Core 7.1.4 on 25th Sep. 2021

**Comment by whitTech** [comment]
Thanks very much for the clarification, @SteveL-MSFT. Initial testing of importing the older version of the `PackageManagement` module is yielding success.

> You can always install the relevant package providers to get the same behavior as WinPS.

If I am interpreting you correctly, you are suggesting that I can continue to use the latest version of `PackageManagement` and simply install the `msi` package provider. This would appear be cleanest solution, as I get the `msi` provider without having to use the very outdated version of 1.0.0.1 of the module.

Unfortunately, I'm unable to find a way to install a package provider such as `msi`, as it is not available via `Find-PackageProvider`. Do you have a line or two of code you could suggest that would achieve this?

**Comment by A9G-Data-Droid** [comment]
Note to future readers; when @SteveL-MSFT says "working as designed" he means that the functionality was removed on purpose.

If you run the old PowerShell 5 you will find it's using the older version of the PackageManagement which contains the functionality you are looking for.

Unfortunately, that leads you to run into this issue:
https://github.com/OneGet/oneget/issues/435

Where you see that the ability to uninstall is broken in the older version. 
So instead of fixing the problem, they removed the feature.

Long story short: Don't expect to use Microsoft Package Management tools to manage installed programs. WinGet is also broken. That's right, Microsoft has two new tools "WinGet" and "OneGet" that are both broken. Even the older "Get-WmiObject" doesn't work as it can't see all installed applications. You will find plenty of examples of software that doesn't show up despite appearing in control panel. Not to mention "Metro Apps" or whatever they are called today.

You will need to download 3rd party tooling to manage installed applications.

**Comment by ThomasNieto** [comment]
@A9G-Data-Droid Microsoft has deprecated OneGet, and due to that I have created a replacement module called [AnyPackage](https://anypackage.dev). It has a [Programs](https://www.powershellgallery.com/packages/AnyPackage.Programs) provider that can retrieve Add/Remove programs. It doesn't have uninstall capabilities at the moment but is being tracked in AnyPackage/AnyPackage.Programs#6 but you won't run into the issue where it silently fails.

**Comment by A9G-Data-Droid** [comment]
> I have created a replacement module called [AnyPackage](https://anypackage.dev)

How does this compare to Chocolatey, Scoop, Ninite, AppGet, Npackd, and OneGet?

And why not just join one of those projects?

I'm consistently baffled by the fact that the Linux world has more than 6 fully functional package managers to choose from and there isn't a single one that can get it right on Windows.

**Comment by ThomasNieto** [comment]
@A9G-Data-Droid like OneGet, AnyPackage is not a package manager its self but a way to interface with various package managers. Currently there is Chocolatey, Scoop, WinGet providers.

**Comment by NetMage** [comment]
> If you want the WInPS behavior with those providers, you should explicitly import that one under "C:\Program Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\PackageManagement.psd1" (root drive and version could be different).

Import-Module C:\Program Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\PackageManagement.psd1

Import-Module: Assembly with same name is already loaded

A more helpful answer would have been appreciated.
