### ISSUE TITLE
Powershell 7.0.3 - [Linq.Enumerable]::Distinct

### ISSUE THREAD

**Issue by alexvergilis** [PowerShell/PowerShell#13241]
## Steps to reproduce

```
[Linq.Enumerable]::Distinct([string[]]@('a','b')).Where({$_})
```

## Expected behavior

```
a
b
```

## Actual behavior

```
$null
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by SeeminglyScience** [comment]
The enumerator that gets returned (`Enumerable+DistinctIterator<string>`) happens to have a public `Where` method even though the type itself is non-public.  It doesn't have a `ForEach` method though, so as a work around you can do:

```powershell
[Linq.Enumerable]::Distinct([string[]]@('a','b')).
    ForEach{ $_ }.
    Where{ $_ }
```

**Comment by vexx32** [comment]
This is working as designed.

The confusion comes from here:
```ps1
PS C:\Users\me> [Linq.Enumerable]::Distinct([string[]]@('a','b')).Where

OverloadDefinitions
-------------------
System.Collections.Generic.IEnumerable[string] Where(System.Func[string,bool] predicate)
```

That is, the `Where` method that is found is _not_ the typical `Where` "magic" method that is provided by default on arrays in PowerShell, it's a method implemented by the IEnumerable class. If you want to use the usual `.Where` for this, you can wrap the expression in `@()` first:

```ps1
@([Linq.Enumerable]::Distinct([string[]]('a','b'))).Where{$_}
```

Alternatively, you can just use the IEnumerable version of Where like this:

```ps1
# use $args to access Func arguments
[Linq.Enumerable]::Distinct([string[]]@('a','b')).Where{ $args[0] }

# Or define a param block to give input args their own name
[Linq.Enumerable]::Distinct([string[]]@('a','b')).Where{ param($string) $string }
```

Because PowerShell is not really in control of the arguments being passed, and the delegate type being bound to is a Func (which can have _many_ input arguments), `$_` is not automatically provided to the scriptblock as input. If you want arguments to be named (and yes, you can technically use `$_` for this if you want, e.g. `{ param($_) $_ }`) you'll need to use a param() block to name them yourself. 🙂

**Comment by alexvergilis** [comment]
If PowerShell 7,x is meant to be an in place replacement of PowerShell 5.1 this is a breaking behavior, as this:
`[Linq.Enumerable]::Distinct([string[]]@('a','b')).Where{ param($string) $string }
`does not produce the same result in 5.1

**Comment by SeeminglyScience** [comment]
That change could have happened even in a minor .NET framework update since the .NET team doesn't consider that to be under their change contract.  There's nothing PowerShell can really do about that.

**Comment by alexvergilis** [comment]
@SeeminglyScience Thank you.

**Comment by SeeminglyScience** [comment]
@alexvergilis np 🙂 FWIW `([string[]][Linq.Enumerable]::Distinct([string[]]@('a','b'))).Where{ $_ }` should be pretty immune to similar changes, and should work in 5.1 too.
