### ISSUE TITLE
Invoke-WebRequest: The error message is damaged beyond repair

### ISSUE THREAD

**Issue by yecril71pl** [PowerShell/PowerShell#13251]
## Steps to reproduce

```powershell
iwr 'http://github-production-release-asset-2e65be.s3.amazonaws.com/'
```

## Expected behavior

```none
Invoke-WebRequest: Forbidden

Error:
    Code: AccessDenied
    Message: Access Denied
    RequestId: 229E67C9F0B26053
    HostId: kUI8bnH/eZxSAjznVy7+RQpaBv1yHVAP7w9Vh/Z2LYdrrPfn1E8E3y176OHzhKwwdkRMZ0RygbQ=
```

## Actual behavior

```none
Invoke-WebRequest:
AccessDeniedAccess Denied4GEN7KFG5Q8QAT8J/8ZJ9JizWnxWHeo0m3wU/rl7Kh7xzbV89arVlDlaSbYwEGELtFblhWEQAKxeaWmeY61sUti5ISk=
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by KalleOlaviNiemitalo** [comment]
```
PS Temp:\> (iwr 'http://github-production-release-asset-2e65be.s3.amazonaws.com/' -SkipHttpErrorCheck).Content
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>AY9Q4P8SDQCRCNAJ</RequestId><HostId>teel4p+MFOck+dIyvQtwFzXV+jYfLOnyyp6wJBq1wTo9SUHLU+fG+lQtr3WYP9B/4ZND/nP9SzQ=</HostId></Error>
```

Then it helpfully removes the XML tags and leaves only the content: <https://github.com/PowerShell/PowerShell/blob/dd73c303a86ee04afca54a2be949c18299f2d8ed/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L1548-L1549>

Perhaps that should trigger only if Content-Type is text/html or application/xhtml+xml. This response has application/xml.

**Comment by yecril71pl** [comment]
I expect XML to be handled in a user-friendly way.  Blindly removing tags is not user-friendly and leaving them as they are is not either.  Remember that XML is an application format, not a text format.

**Comment by vexx32** [comment]
Sure. Error messages, however, come in text format. 🤷

**Comment by yecril71pl** [comment]
And that is why we must use a formatter to get something we can throw.

**Comment by KalleOlaviNiemitalo** [comment]
[Microsoft.Rest.HttpResponseMessageWrapper](https://github.com/Azure/azure-sdk-for-net/blob/8dfd3b317af57a3c3a3942105748bbce2f964465/sdk/mgmtcommon/ClientRuntime/ClientRuntime/HttpResponseMessageWrapper.cs) referenced [in PowerShellCore_format_ps1xml.cs](https://github.com/PowerShell/PowerShell/blob/dd73c303a86ee04afca54a2be949c18299f2d8ed/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs#L793-L797) unfortunately does not have code for converting the HTTP response body to properties that could then be nicely formatted.

**Comment by yecril71pl** [comment]
I would not expect them too, consider the error page response body can be in any form, including Adobe Illustrator, because why not.  However, we should be prepared handle the cases that are common, at least HTML and XML.
The right way to format HTML is to render it to a text document with scripts disabled.
The right way to format XML is as indicated in the issue.

**Comment by KalleOlaviNiemitalo** [comment]
> The right way to format HTML is to render it to a text document with default style

I'll be surprised if an HTML renderer is added to PowerShell, especially if it is then used for errors only.
On the other hand, ConvertFrom-Markdown surprised me as well.

> format as YML

Do you mean [YAML](https://yaml.org/)? Your "Expected behavior" does not have any indentation to indicate nesting of elements.

> That still means we have to honour inline DTDs, including text entities.

Wasn't there some security problem with inline DTDs, too? Perhaps it was just a denial of service that could be mitigated by setting [XmlReaderSettings.MaxCharactersFromEntities](https://docs.microsoft.com/dotnet/api/system.xml.xmlreadersettings.maxcharactersfromentities). Regardless, a web server that required DTD processing of error responses would only hurt its compatibility with client software, so I don't believe many servers do that.

> I know, some XML formats do not think much of this theory—it will be their fault.

Pragmatically though, the error summary displayed by PowerShell should try to help the user solve the error.

**Comment by yecril71pl** [comment]
> > format as YML
> 
> Do you mean [YAML](https://yaml.org/)? Your "Expected behavior" does not have any indentation to indicate nesting of elements.

I am sorry, I am not a DevOps guy.  Is it better now?

> 
> > That still means we have to honour inline DTDs, including text entities.
> 
> Wasn't there some security problem with inline DTDs, too? Perhaps it was just a denial of service that could be mitigated by setting [XmlReaderSettings.MaxCharactersFromEntities](https://docs.microsoft.com/dotnet/api/system.xml.xmlreadersettings.maxcharactersfromentities). Regardless, a web server that required DTD processing of error responses would only hurt its compatibility with client software, so I don't believe many servers do that.

Yes, you can very easily go exponential with DTD entities.  DOS can (and should) be mitigated by limiting the total length of the result.

> 
> > I know, some XML formats do not think much of this theory—it will be their fault.
> 
> Pragmatically though, the error summary displayed by PowerShell should try to help the user solve the error.

Pragmatically, putting relevant content into attributes is actively preventing users from seeing it.  The purpose of PowerShell is not to save the world.

**Comment by KalleOlaviNiemitalo** [comment]
If the HTTP server returns an error response in XML or JSON format, then the provider of the HTTP server presumably intends the response to be parsed by dedicated client software, rather than a generic web browser.

If the user of PowerShell is writing a script that sends requests to such an HTTP server, then the user presumably has access to documentation of the error response format and would benefit from seeing the response in that format. Raw XML or JSON would be fine in that case, optionally indented by PowerShell.

However, if the user of PowerShell is running a script provided by someone else and is not familiar with the intended API, then it might be better to display the response in a different format, like YAML.

I don't think the original response body should be stored in the TargetObject, if it is large. Errors accumulate in the $Error variable and could take up too much memory.

Likewise, when PowerShell shows the error response to a user, it should not blast out many pages of text and should escape or filter out terminal control characters. A user who wants the exact error response can rerun the request with Invoke-WebRequest -SkipHttpErrorCheck. That is also what scripts should do if they need to parse the error response.

**Comment by yecril71pl** [comment]
You assume that re-running the request is cheap, which need not be the case.  I have already reported one issue with excessive error messages.  We have agreed that `TargetObject` is the way to go.  If `$ERROR` takes too much memory, there should be a way to GC it.

**Comment by KalleOlaviNiemitalo** [comment]
>  We have agreed that `TargetObject` is the way to go.

The decision was apparently in <https://github.com/PowerShell/PowerShell/issues/2193#issuecomment-280187451>. But it turns out that ErrorRecord.TargetObject is the HttpRequestMessage, rather than HttpResponseMessage. ErrorRecord.Exception may be an HttpResponseException that then carries the response.
