### ISSUE TITLE
.FORWARDHELPTARGETNAME: cannot forward to ABOUT

### ISSUE THREAD

**Issue by yecril71pl** [PowerShell/PowerShell#13283]
## Steps to reproduce

```powershell
FUNCTION NEW-EVIDENCE {
# .FORWARDHELPTARGETNAME ABOUT_COMMENT_BASED_HELP
HELP ABOUT_COMMENT_BASED_HELP -S
}
HELP NEW-EVIDENCE -S
```

## Expected behavior

```none
ABOUT COMMENT BASED HELP
```

## Actual behavior

```none
Synopsis
    

Syntax

```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by yecril71pl** [comment]
It seems that `HelpFileHelpProvider` should implement `ProcessForwardedHelp`.

**Comment by SeeminglyScience** [comment]
What's the use case for making a command's help redirect to an `about_`? Usually it's used for proxy commands (and remoting I think).

**Comment by yecril71pl** [comment]
It is not my use case but everyone seems to want just that.  See the referenced PR.

**Comment by vexx32** [comment]
What PR? I don't see any references.

**Comment by SeeminglyScience** [comment]
@vexx32 it's right above my comment, #13176.  They want it for `prompt` which I understand on one hand but... it really only makes sense for `prompt` and even then only kinda.

**Comment by vexx32** [comment]
Github must be having issues, I don't see it at all. 😄 

But yeah, `prompt` is a bit of a special case in that it's _designed_ for users to override it in the first place. Doesn't make a lot of sense for anything else IMO.

**Comment by yecril71pl** [comment]
In other words, `PROMPT` is a callback.  If we ever have another callback, we are going to bump into the same problem.

**Comment by SeeminglyScience** [comment]
> In other words, `PROMPT` is a callback. If we ever have another callback, we are going to bump into the same problem.

It's a callback that is intended to be able to be called by anyone who needs to display (or otherwise retrieve) the user's prompt string.  That's why it should be documented as any other command imo, with just a "also see" link to `about_Prompts`.  Same for `TabExpansion2` which is a similar callback (with an even stronger case since it has parameters).

> OTOH, maybe we never get another one, as `PROMPT` itself should an event handler for `Idle` rather than a callback.

All the `prompt` function does is return a string, the caller is responsible for how it's displayed.  It can't be an event handler because it doesn't make sense for multiple handlers to be registered, and it wouldn't be able to be raised outside of the event handler class.  

Also not important but it doesn't get invoked on `Idle`.  When and how it's invoked is determined by the current `PSHost` typically.  Fun fact, the `OnIdle` event will actually fire even in the middle of `PSConsoleReadLine.ReadLine`.

**Comment by yecril71pl** [comment]
> That's why it should be documented as any other command imo, with just a "also see" link to `about_Prompts`.

Sure, I almost said it myself.  I failed to convince anyone though.  I find myself lacking your clarity of expression 🙁

**Comment by sdwheeler** [comment]
.FORWARDHELPTARGETNAME cannot forward to content that does not have a HelpUri. About topics don't have HelpUris because they are text files and not compiled into MAML.

**Comment by yecril71pl** [comment]
I fail to get the connexion, given that `HelpUri` is for remote help.  Moreover, I boldly claim to have identified the part that is missing, and it does not have anything to do with `HelpUri` either.  But if you are right, fixing it would require #8230.

**Comment by sdwheeler** [comment]
@yecril71pl You are probably right about the `HelpUri`. The real issue is that About files are text files and not compiled into MAML.

**Comment by yecril71pl** [comment]
I am sorry, this one is also real, as long as the people in power insist on having this particular redirect in place,
