### ISSUE TITLE
Powershell SDK Get-Disk OperationalStatus returns array instead of value for Windows Server 2019

### ISSUE THREAD

**Issue by erenturkm** [PowerShell/PowerShell#13297]
I am using Powershell SDK in c# code. When I am parsing output of Get-Disk objects and looking into Operational Status, I get an array (Uint16[]) instead of (Uint16) Only for Windows Server 2019 (It works as expected for Windows Server 2012 R2)

## Steps to reproduce
Below PSObject is one of the Disk Objects returned by get-disk
```
public static Int GetOperationalStatus(PSObject obj)
        {
            Int OpStatus = obj.Properties.Match("OperationalStatus")[0].Value;
             return OpStatus;
}
```
## Expected behavior

```
obj.Properties.Match("OperationalStatus")[0].Value should return type of UInt16 on Windows Server 2019
```
But it returns
## Actual behavior

```
obj.Properties.Match("OperationalStatus")[0].Value returns type of UInt16[] on Windows Server 2019
```

## Environment data

```none
PSVersion=7.0.2
PSEdition=Core
WSManStackVersion=3.0
PSRemotingProtocolVersion=2.3
```

**Comment by iSazonov** [comment]
Get-Disk is in Storage module and you could compare the output of the cmdlet on both server versions.

**Comment by erenturkm** [comment]
Are you suggesting comparing the Powershell Console output with Powershell SDK versions? If so I cant. Target servers do not have Powershell Core installed, I am connecting remotely from c# code.

**Comment by iSazonov** [comment]
I guess Storage module changes the behavior in new version.

**Comment by erenturkm** [comment]
1) Microsoft Get-Disk documentation points to ROOT/Microsoft/Windows/Storage/MSFT_Disk in which this value is UInt16.
2) I dont see any reason for them to do this. It doesn't make sense to have HealthStatus as array for a single disk.

How can we get a definitive answer?

**Comment by iSazonov** [comment]
>  It doesn't make sense to have HealthStatus as array for a single disk.

I ask you to check this. I guess it is a bug in new version of the module. If so it is Windows bug.

**Comment by erenturkm** [comment]
I dont understand. I checked, I reported it as a Powershell bug to the Powershell Issues. What else do you want me to do?

**Comment by iSazonov** [comment]
If you run Get-Disk and get different results on different Windows versions my conclusion is that it is Windows bug and should be reported to Windows team by other channels (support case, forums, Windows Feedback tool, UserVoice site).

**Comment by jborean93** [comment]
The issue is this module isn't written by the PowerShell team. If there's a change in behaviour across versions then there is a good chance it's because of a change on their end or something they are relying on. The Storage module is also a CDXML module so the cmdlets are based on the underlying WMI class, you can see the `CDXML` definition at `C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Storage\Disk.cdxml` on your Windows box. Ultimately the value that it returns is based on what WMI actually provides and based on the class metadata it's set to a `UInt16Array`

```powershell
$class = Get-CimClass -ClassName MSFT_Disk -Namespace ROOT\Microsoft\Windows\Storage
$class.CimClassProperties | Where-Object Name -eq OperationalStatus | Select *

# Name               : OperationalStatus
# Value              :
# CimType            : UInt16Array
# Flags              : Property, Required, ReadOnly, NullValue
# Qualifiers         : {read, Required, ValueMap}
# ReferenceClassName :
```

I've also used `wbemtest.exe` to view the underlying configuration of the class outside of PowerShell. The `OperationalStatus` property is set with a `CIM_FLAG_ARRAY` of the underying type `CIM_UINT16` so what PowerShell is reporting is correct.

![image](https://user-images.githubusercontent.com/8462645/88740996-e0c1b900-d181-11ea-89f3-5cb829df2314.png)

This means what is documented at [MSFT_Disk](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/stormgmt/msft-disk) does not match up with what the WMI provider on the host is set to. There's nothing PowerShell or should do about this.

**Comment by erenturkm** [comment]
Thank you for chiming in, this was a much better answer. I am really trying to understand Powershell teams perspective, bare with me.
1. As long as Powershell cmdlet Get-disk is not doing what is given in the cmdlet documentation page, it needs to be fixed. I understand that you as the Powershell Core team are not responsible for cmdlets outside Microsoft.PowerShell.Core, most of the command/property definitions have drifted considerably from what is available on the web. Note that users do not care about Powershell Core, its all the modules under it that helps them do their job. We need to be able to access information on how it is intended to be used. (Ex: Why is OperationalStatus need to be an array? )  

2.  Thank you for providing an alternative way to reverse-engineer what the module developer  has changed but this is too much to ask to hunt down what is changing from version to version for all properties of all cmdlets that we use on a day to day basis using this. We need to have a much better developer experience. Maybe you can integrate this information to get-help module that will query this info and provide it as part of the message.

**Comment by iSazonov** [comment]
> Maybe you can integrate this information to get-help module that will query this info and provide it as part of the message.

Oh, I think it is impossible to track all changes in all modules/APIs. 
The best you can do is achieve full test coverage of your application.

**Comment by jborean93** [comment]
I was having a further look into this recently, the `OperationalStatus` value is `ScriptProperty`

```powershell
$disk = Get-Disk
$disk.PSObject.Properties | Where-Object Name -eq OperationalStatus

GetterScript    : $_status = @();
                            foreach( $status in $this.psBase.CimInstanceProperties["OperationalStatus"].Value )
                            {
                              switch ( $status )
                              {
                                1 { $_status += "Other" }
                                2 { $_status += "OK" }
                                3 { $_status += "Degraded" }
                                4 { $_status += "Stressed" }
                                5 { $_status += "Predictive Failure" }
                                6 { $_status += "Error" }
                                7 { $_status += "Non-Recoverable Error" }
                                8 { $_status += "Starting" }
                                9 { $_status += "Stopping" }
                                10 { $_status += "Stopped" }
                                11 { $_status += "InService" }
                                12 { $_status += "No Contact" }
                                13 { $_status += "Lost Communication" }
                                14 { $_status += "Aborted" }
                                15 { $_status += "Dormant" }
                                16 { $_status += "Supporting Entity in Error" }
                                17 { $_status += "Completed" }
                                18 { $_status += "Power Mode" }
                                19 { $_status += "Relocating" }
                                53264 { $_status += "Online" }
                                53265 { $_status += "Not Ready" }
                                53266 { $_status += "No Media" }
                                53267 { $_status += "Offline" }
                                53268 { $_status += "Failed" }
                                Default { $_status += "Unknown" }
                              }
                            }
                            $_status;
SetterScript    :
MemberType      : ScriptProperty
IsSettable      : False
IsGettable      : True
Value           : Online
TypeNameOfValue : System.Object
Name            : OperationalStatus
IsInstance      : False
```

This `ScriptProperty` is defined at `C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Storage\Storage.types.ps1xml` as part of the extended type data for `Microsoft.Management.Infrastructure.CimInstance#MSFT_Disk`. This means the value is part of the extended type set (ETS) that is loaded for that type with the `Storage` module.

What's happening here is it looks like the extended type data is being stripped out or at least wasn't present when `Get-Disk` was run so when you get the instance from the PowerShell pipeline you are getting the raw properties of that object. Those properties are directly mapped from what WMI returns which in this case is `UInt16[]` on 2019 and `UInt16` on 2012 R2. Why the ETS isn't present I have no idea, I can only replicate this when using a remote PSSession and not importing the `Storage` module like

```powershell
$session = New-PSSession -UseWindowsPowerShell
$disk = Invoke-Command -Session $session -ScriptBlock {
    Get-Disk
}
$session | Remove-PSSession
$disk.OperationalStatus
```

Still this here is somewhat expected because the ETS is part of the `Storage` module and in this particular example I never loaded that so PowerShell doesn't know there's extended types to apply.

What I don't fully understand is how this applies to objects being output from a C# `.Invoke()` call that's in your example. I do have a potential workaround that may work, when calling `Get-Disk` pipe it into `Select-Object -Property *` like

```powershell
Get-Disk | Select-Object -Property *
```

This will have that CimInstance being converted to a PSCustomObject with the `ScriptProperties` becoming `NoteProperties` which should traverse the .NET <-> PowerShell boundary. That way you can just look at the string value instead of trying to deal with the changing types. Apart from that there's not too much else PowerShell can do here, the component that changed the type is multiple layers outside of PowerShell itself and there are too many components for the team to really keep track of everything.

**Comment by erenturkm** [comment]
I understand that tracking all changes made by all other teams are out of scope, but remember if you dont, we as your users will have to. It should be the changers resposibility to document what is changing and why. End users should not be digging on this. This makes a really bad quality API. So lets try to make necessary changes/upgrades in Powershell Core to lessen the burden on all of us.
1) I think your suggestion is a step in the right direction. NoteProperties can somewhat shield the changes. I will try to use it moving forward.
2) Other teams will have to rewrite management functions sooner or later (Moving to ARM etc). Please use this to craft an understanding between the teams so that they will be required to have an automated way to propogate the **change documentation** through tools/Infrastructure provided by PS Core. 
3) Have better support on Powershell SDK to query and tranform types between .NET and Powershell so we can build libraries easier to handle this.
