### ISSUE TITLE
Test-Json fails for valid Json.

### ISSUE THREAD

**Issue by tstoian** [PowerShell/PowerShell#13318]
## Steps to reproduce

OpenAPI-3.0.schema.json:
[https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v3.0/schema.json](url)

api.json:
```json
{
    "openapi": "3.0.0",
    "info": {
        "title": "myTitle",
        "version": "1.0"
    },
    "paths": {
        "/resource": {
            "get": {
                "responses": {
                    "200": {
                        "description": "myDescription"
                    }
                }
            }
        }
    }
}
```

```powershell
$schema = Get-Content 'OpenAPI-3.0.schema.json' -Raw
$value = Get-Content 'api.json' -Raw
Test-Json -Json $value -Schema $schema
```

## Expected behavior

```
True

```

## Actual behavior

```
Test-Json: C:\Git\APIM\APIM-Service\apim-pipeline-scripts\parse-spec.ps1:3:1
Line |
   3 |  Test-Json -Json $value -Schema $schema
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot parse the JSON.

False

```

## Environment data

```Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by rjmholt** [comment]
I can reproduce this in just NJsonSchema alone:

```powershell
$json = @'
{
    "openapi": "3.0.0",
    "info": {
        "title": "myTitle",
        "version": "1.0"
    },
    "paths": {
        "/resource": {
            "get": {
                "responses": {
                    "200": {
                        "description": "myDescription"
                    }
                }
            }
        }
    }
}
'
$schema = [NJsonSchema.JsonSchema]::FromUrlAsync('https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v3.0/schema.json').GetAwaiter().GetResult()
$schema.Validate($json, @())
```

Based on that, I think this should be migrated to an issue in NJsonSchema

**Comment by tstoian** [comment]
I created an issue in the NJsonSchema project.
https://github.com/RicoSuter/NJsonSchema/issues/1225

I thereafter found another similar issues reported one year earlier, which is still open:
https://github.com/RicoSuter/NJsonSchema/issues/1034

I feel confused to see support for a Microsoft product pointing to a third-party library. Especially since this NJsonSchema library comes installed by default with PowerShell 7.

**Comment by vexx32** [comment]
@iSazonov has submitted PRs to convert the implementation to the newer .NET implementation (System.Text.Json), but to my knowledge the PowerShell team are currently unwilling to shift the implementation as there are some behavioural differences.

However, if this issue doesn't surface in the .NET implementation, perhaps that might be a reason to look at switching over once again (cc @SteveL-MSFT / @joeyaiello)

**Comment by rjmholt** [comment]
> I feel confused to see support for a Microsoft product pointing to a third-party library. 

This is the modern open-source world.

Not only does the PowerShell team not have any business writing a Json schema implementation, but if we did it would take (a lot of) time away from working on PowerShell itself.

Instead, people in the .NET community work hard to create and maintain libraries that we all get to reuse and can contribute back to freely. Rather than us insisting that only Microsoft can build good software, we participate in the ecosystem and in doing so de-fragment solutions to problems.

Does that mean there will be bugs? Sure, but there were bugs before too. Where once you might have filed a ticket that got internally bounced around into oblivion, this time support involves you communicating directly with the engineers who build the product, and if you don't like their response you still have the option of going to the original library to open an issue or even a PR.

So I understand your confusion, especially since PowerShell traditionally being a Windows product meant a certain form of product feedback. But now we're building PowerShell as a community out in the open, and that involves reuse, collaboration and pitching in.

**Comment by iSazonov** [comment]
.Net team actively enhance JSOM support but it seems .Net 5 has not still API for JSOM scheme validation.

**Comment by GlenAppleton** [comment]
Checking to see if this issue is still being actively researched / addressed.  I'm having the same issues with validating both the OpenAPI schemas and the ARM template schemas.

If it's not, is there an alternative way using C# instead of PowerShell that will work?  I'm currently using PowerShell Core 7.x on my build servers for Azure DevOps CI builds, but if it's possible create a console utility in C# that will work, I'll go that route.

**Comment by iSazonov** [comment]
@GlenAppleton Please vote in NJsonSchema for https://github.com/PowerShell/PowerShell/issues/13318#issuecomment-667050507

**Comment by gregsdennis** [comment]
The JSON Schema implementation has been recently updated to JsonSchema.Net and is available in the latest Powershell snapshot. Please retest this to see if it is still a problem.

This works as expected on https://json-everything.net/json-schema.

One thing to note, however, is that in the latest JSON Schema, `dependencies` has been split into `dependentRequired` (your usage) and `dependentSchemas`.  You can resolve this by either:

- adding `"$schema": "http://json-schema.org/draft-07/schema#"` to your schema to specify that you want draft 7 (where `dependencies` is still a thing)
- changing `dependencies` to `dependentRequired` and letting the validator interpret your schema as the latest version.

**Comment by gregsdennis** [comment]
The JSON Schema implementation has been recently updated to JsonSchema.Net and is available in the latest Powershell snapshot.

That said, JsonSchema.Net doesn't support draft 4 of JSON Schema, which is required for OAS 3.0.x and prior.  (OAS 3.1 uses draft 2020-12 directly.)

I do have unpublished code that enables support for OAS 3.0 (but not 2.0) documents.  I have a proposal with OpenAPI.Net to onboard my validator instead of them using they're internal one to support OAS 3.1, but that work has stalled.

I'm open to seeing how some of that work could be utilized by PowerShell to support this use case.

**Comment by iSazonov** [comment]
How long they will support OAS 3.0 and how many users use the version? If they actively migrated to 3.1 it makes no sense to support old version in PowerShell. 
Also support of different json schema drafts would require us to add a new parameter, but this is UX complication of dubious usefulness.

**Comment by gregsdennis** [comment]
It's not a matter of OpenAPI.Net's support for 3.0 (but they plan on continuing to support it and 2.0).  Their library is disjoint from Powershell.

That said, it might not be a bad idea to port some of that support over here since OpenAPI (the spec) is still recommending people use 3.0 until there's more tooling support for 3.1 in the API space.  (I'm considering publishing some OAS support in a seperate package, but for now it can just be built in.)

> Also support of different json schema drafts would require us to add a new parameter, but this is UX complication of dubious usefulness.

I'm not sure we'd need to add a parameter.  JSON Schema uses the `$schema` keyword to determine which draft a schema should be written for.  If the schema is missing a `$schema` keyword, it will process under 2020-12 rules.

**Comment by gregsdennis** [comment]
I have recently published [STJ.OpenApi.Models](https://www.nuget.org/packages/STJ.OpenAPI.Models), which provides serialization support for OpenAPI v3.0 and v3.1.  (v3.0 requires that draft 4 support you're looking for; it's built into the package.)  I'm not sure what effort would be required to integrate that here.

**Comment by gregsdennis** [comment]
> How long they will support OAS 3.0 and how many users use the version?

I have word from the project maintainers that they intend to keep supporting back to v2.0 (Swagger).
