### ISSUE TITLE
Move-Item explodes contents of first top-level folder

### ISSUE THREAD

**Issue by yohosuff** [PowerShell/PowerShell#13352]
## Steps to reproduce

Run the script below in a new folder.

```powershell
if (Test-Path src){
	remove-item src -force -recurse
}

if (Test-Path dest){
	remove-item dest -force -recurse
}

New-Item -ItemType directory -Path src | out-null
New-Item -ItemType directory -Path src\foo | out-null
New-Item src\foo.txt | out-null
New-Item src\foo\foo.txt | out-null

move-item -path "src\*" -Destination "dest"
```

It will create a simple folder structure like this...

![image](https://user-images.githubusercontent.com/41205049/89348768-5b02a980-d66a-11ea-9906-612ff981916d.png)

...and then move the contents of `src` into a new folder  `dest`.

## Expected behavior

![image](https://user-images.githubusercontent.com/41205049/89348972-afa62480-d66a-11ea-801a-35fb40464718.png)

## Actual behavior

We end up with a folder structure like this...

![image](https://user-images.githubusercontent.com/41205049/89348637-1b3bc200-d66a-11ea-8b7b-3888bd630dc0.png)

...as well as the following error.

![image](https://user-images.githubusercontent.com/41205049/89348462-d31c9f80-d669-11ea-9558-38fc6f0d9b0a.png)

I assume the error appears because when `foo` is moved, the contents are moved instead of the whole folder, so `foo.txt` is moved directly under `dest`. When the root level `foo.txt` is then attempted to be moved, there is already a `foo.txt` in its destination path.

## Environment data

![image](https://user-images.githubusercontent.com/3869624/89429782-399dce00-d6fb-11ea-812b-876575515ca1.png)

**Comment by mkht** [comment]
In this case, Move-Item performs a two-step operation in sequence.
First, it RENAMES the `src/foo` folder to the `dest` folder.
Next, it tries to MOVE the `src/foo.txt` file to the `dest` folder. However, there is already a `foo.txt` file in the `dest` folder and an error occurs.

That is, Move-Item will "move" the item if the destination already exists, but otherwise it will "rename" the item.
I don't know if this behavior is intended or if it's a bug. Please wait for reply from PowerShell Pros. :-(

An easy workaround is to create a `dest` folder before you run Move-Item. This will allow you to achieve the behavior you expected.

```PowerShell
if (Test-Path src){
	remove-item src -force -recurse
}

if (Test-Path dest){
	remove-item dest -force -recurse
}

New-Item -ItemType directory -Path src | out-null
New-Item -ItemType directory -Path src\foo | out-null
New-Item src\foo.txt | out-null
New-Item src\foo\foo.txt | out-null

# Create a dest folder explicitly
New-Item -ItemType directory -Path dest | out-null

# Then, move items
move-item -path "src\*" -Destination "dest"
```

**Comment by jdhitsolutions** [comment]
Couldn't `Move-Item` be modified to first create the destination if it doesn't exist? If it did, would that solve the original problem?

**Comment by iSazonov** [comment]
I see we need to review move-item design. I don't think it works as such alternative tools.
/cc @mklement0 if you have an interest.

**Comment by mklement0** [comment]
We could follow the lead of the Unix `mv` utility:

* If there are _multiple_ source items,  the target item must (a) exist and (b) must be a directory - otherwise an error occurs (that is, @mkht's workaround is the proper solution to avoid this problem).

Additionally, @jdhitsolutions' proposal - creation of a target folder on demand (unless a _file_ by that name already exists) - should probably be _opt-in_, via a switch such as `-Force` (though making `-Force` do many different things is problematic, I'm not aware of anything that it currently does in the file-system provider, so perhaps that is an option),

**Comment by danielniccoli** [comment]
I think I'm running into a similar behaviour here. I am trying to move all contents of a folder "$geeksPackage\dist\assets\*"` to a folder `$PROJECT_ROOT\app\static\geeks`. 

```powershell
# The folder "geeks" inside "$PROJECT_ROOT\app\static\" does not exist when I run the following cmdlet:
Move-Item "$geeksPackage\dist\assets\*" "$PROJECT_ROOT\app\static\geeks"
```

However, this turn the folder structure at the source:
![grafik](https://github.com/PowerShell/PowerShell/assets/2971735/1a63a24f-7353-4fac-a5e4-9f1a8ad09b88)
Into the following at the destination:
![grafik](https://github.com/PowerShell/PowerShell/assets/2971735/e8a43e18-9476-4ae1-be58-5f09552d2d2a)

**At best, this is unintuitive, but I hope it is just a bug! 🙏**

```powershell
# Creating the folder beforehand will make it work.
New-Item "$PROJECT_ROOT\app\static\geeks" -ItemType Directory
Move-Item "$geeksPackage\dist\assets\*" "$PROJECT_ROOT\app\static\geeks"
```` 

PowerShell 7
```
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by BrDewit** [comment]
I also run into the same issue. I run `Move-Item * ".\\destination folder"`

This consistently does not copy over the first folder of the directory, and the file contained in that directory gets dropped top-level in the destination folder.

It consistently shows this behaviour, except if the folder already exists, just like with the commenters above.
If I run `New-Item -ItemType directory -Path "destination folder"` before running `Move-Item * ".\\destination folder"` then it consistently works as expected.
