### ISSUE TITLE
Caching of the original string representation of parsed-as-numbers bareword arguments is broken for type suffixes 'd' and 'n'

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13380]
From what I understand, in argument mode the parameter binder pre-parses _bareword arguments_ that _look like number literals_ as numbers.

If that argument is then bound to an _untyped_ parameter (no type specified (PowerShell code), `[object]`, or `[psobject]`), it isn't clear whether the argument was indeed meant to be a number or was meant to be a string that just happens to look like a number.

In order to still enable later use of the argument _as a string_, its _original string representation_, exactly as it was specified on the command line, must be preserved.

To that end, the number is wrapped in a `PSObject` instance that _caches_ the original string representation.

This cached string representation can be accessed via `.psobject.ToString()`, and it is also used implicitly during output formatting (curiously, it is _not_ used with `.ToString()` or in string interpolation - see https://github.com/PowerShell/PowerShell/issues/9157#issuecomment-491423258).

However, as an optimization, this wrapping-in-`PSObject` happens _only_ if the original string representation differs from the _default_ string representation of the number.

With arguments that look like numbers _with data-type suffixes_ - such as `L` for `[long]` - wrapping _must_ happen, given that the default string representations of the resulting numbers never include a type suffix.

Currently, this works for all type suffixes except for `d` (`[decimal]`) and `n` (`[bigint]`)
What these two types have in common is that they're not .NET primitive types.

## Steps to reproduce

```powershell
# These strings, when used as barewords, are parsed as *numbers*, because
# they *look like number literals*.
$barewords = '1y', '1uy', '1s', '1us', '1l', '1u', '1ul', '1d', '1n', '1e2', '1.22000'

$roundTrippedAsStrings = $barewords | % {
    iex "& { param(`$p) `$p.psobject.ToString()  } $_"  
  }

Compare-Object $barewords $roundTrippedAsStrings -OutVariable result

$result.Count | Should -Be 0
```

## Expected behavior

All tests should pass.

## Actual behavior

```none
InputObject SideIndicator
----------- -------------
1           =>
1           =>
1d          <=
1n          <=

Expected 0, but got 4.
```

That is, `1d` (`[decimal]`) and `1n` (`[bigint]`) did not preserve their original string representations.

## Environment data

```none
PowerShell Core 7.1.0-preview.5
```

**Comment by vexx32** [comment]
Hmm, I thought I fixed this already.... I think this is a slightly different code path; the stuff I fixed before handles it for when the parameter type is `[string]` and that sorts it out there. But I think this problem may be in PSObject's ToString() method itself. The fix should be similar, though... although I'm surprised _decimal_ doesn't work, since that suffix has been around much longer than some of the others that do seem to work. 🤔

**Comment by vexx32** [comment]
Had a bit of a poke around, and it seems like the code in PSObject's ToString() doesn't really discriminate; if it has a TokenText attached it'll use it.

Guess that somewhere in the parameter binder there it's deliberately discarding the token text information because it's apparently not there at all by the time the ToString() is called, as far as I can see from a quick glance.
