### ISSUE TITLE
Higher version of Unicode is not supported

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#13609]
## Steps to reproduce

```powershell
[char]'𩏻'
[char]'0x293FB'
```

## Expected behavior

```none

```

## Actual behavior
![image](https://user-images.githubusercontent.com/26913892/92681585-a0e51880-f360-11ea-833a-6aa4e5f16b18.png)
```none

```

## Environment data

```none

```

**Comment by iSazonov** [comment]
Do you mean `"`u{293FB}"`?

**Comment by jborean93** [comment]
A .NET [char](https://docs.microsoft.com/en-us/dotnet/api/system.char?view=netcore-3.1) is documented

> Represents a character as a UTF-16 code unit.

If a unicode character cannot fit into a single UTF-16 code point then it must be represented by multiple chars when used in a string. Technically it can represent any value between 0 and 65535 (`[UInt]::MaxValue`) but your character exceeds that size.

For example `𩏻` is part of the [CJK Unified Ideographs Extension B](https://unicode-table.com/en/blocks/cjk-unified-ideographs-extension-b/) set and the UTF-16 encoded byte value of that is `0x64 0xD8 0xFB 0xDF`. This is known as a surrogate pair in UTF-16.

You might consider using the new [Rune](https://docs.microsoft.com/en-us/dotnet/api/system.text.rune?view=netcore-3.1) type that is designed to handle unicode values. Otherwise we would need to know more about what you are trying to achieve here to help you reach your goal.

**Comment by jborean93** [comment]
Oh I also forgot to mention, you can see that your character uses 2 chars by running `'𩏻'.Length`. It will output 2 as String.Length just returns the number of chars it used for the string and it doesn't take into account things like surrogate pairs or other composite glyphs in Unicode.
