### ISSUE TITLE
"-split" operator doesn't handle "|" correctly.

### ISSUE THREAD

**Issue by schuelermine** [PowerShell/PowerShell#13625]
## Steps to reproduce

```powershell
"Hello| Yellow" -split "|"
```

## Expected behavior

```none
Hello
 Yellow
```

## Actual behavior

```none

H
e
l
l
o
|

Y
e
l
l
o
w

```

## Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

## Note

```powershell
"Hello| Yellow".Split("|")
```

produces

```
Hello
 Yellow
```

**Comment by vexx32** [comment]
As is documented in the `about_Split` and `about_Regular_Expressions` help topics, `-split` uses regex matching unless you explicitly opt-out by specifying the `SimpleMatch` option.

`|` in regex is a bit like a logical OR, so that query is similar to `""` OR `""` which will cause a split between every character of the input string.

You can either escape regex metacharacters by using `[regex]::Escape('|')` before using them in a `-split` pattern, manually escape them (`$string -split '\|'`), or use SimpleMatch as I mentioned above: `$string -split '|', 0, 'SimpleMatch'`

**Comment by schuelermine** [comment]
OK
