### ISSUE TITLE
Import-CliXML Too Nested

### ISSUE THREAD

**Issue by Pekka-Kalevi** [PowerShell/PowerShell#13663]
## Steps to go wrong
Created a New-Object -TypeName 'PSObject'
Added  members by Add-Member from pre calculated values from PowerShell assets for
PowerShell releases, using browser_download_uri, name, created_at fields

My new object had property types
 [URI] Uri
 [String] Name
 [DateTime] Created

## So far, so good 
Then exported object to file by using Export-CliXml cmdlet.
No errors.

## Problems started, when I tried to import the xml file by Import-CliXml cmdlet

Got exception: Nested too deeply line xx, etc.

## Need documentation info
How deeply you can import? If export succeed, why import struggles?
Should Import-CliXml have a -Test switch to check the consistency of tags and nesting level?

**Comment by mklement0** [comment]
`Import-CliXml` has _no_ `-Depth` parameter, it should accept whatever depth it finds. Only `Export-CliXml` has `-Depth`, where it defaults to `2`, which, however, only applies to objects _other_ than nested collections, hash tables and `[pscustomobject]` instances; note that values greater than `2` can quickly get out of hand.

Please add a minimal reproducible case to your original post, because trying to reconstruct one from your description does _not_ reproduce the symptom:

```powershell
# Works fine in 5.1, 7.0.3, 7.1.0-preview.7
[pscustomobject] @{
    uri = [URI] 'http://example.org'
    name = [string] 'hi'
    datetime = [datetime]::now
} | Export-Clixml test.clixml

Import-Clixml test.clixml
```
