### ISSUE TITLE
Install-Module UseWindowsPowerShell not found?

### ISSUE THREAD

**Issue by mikaelsand** [PowerShell/PowerShell#13668]
## Steps to reproduce

```powershell
Install-Module -Name LogicAppTemplate -UseWindowsPowerShell

```

## Expected behavior

```none
Done
```

## Actual behavior

```none
Install-Module: A parameter cannot be found that matches parameter name 'UseWindowsPowerShell'.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
That parameter is on `Import-Module`

**Comment by doctordns** [comment]
Whenever you get an issue like this, just:

```powershell
Get-Command <comand name> -Syntax
```
As you would discover, the Install-Module has not such a parameter.  And if you think about it, that makes sense since Install-Module does not actually load the module, the cmdlet just copies your chose module from the repo you are using to the local file store. It's IMPORT-MODULE you need to say -UsePowerShell.

**Comment by mikaelsand** [comment]
Wow! My incompetence is for everyone to see :-)
Thank you very much for the quick help.

**Comment by doctordns** [comment]
if it is any consolation, I know for a fact you are not the first person to trip over this...
