### ISSUE TITLE
PowerShell hangs when script is run in parallel from multiple sessions

### ISSUE THREAD

**Issue by prasanthialluMSFT** [PowerShell/PowerShell#13696]
Problem statement:

Powershell hangs when powershell scripts are run in parallel from multiple powershell consoles simultaneously .

Technical Details:

This problem is a kind of deadlock. A thread which is calling DrainPendingActions is actually the thread that invokes actions in ActionQueue. Therefore, DrainPendingActions will never finish if there are one or more actions in ActionQueue.

Create-Session and Remove-PSSession respectively are used to create and remove a connection to Exchange server.

When Remove-PSSession is executed, the connection to Exchange server is closed, and subscribed events are triggered and added to ActionQueue. Because it is a queue, the events will be triggered in the same order of arrival.

The problem here is that events are arriving in a different order of event occurrence. Specifically, the subscribed event for the status change to Closed is arriving before the subscribed event for the status change to Closing.

When the subscribed event for Closed is triggered, the thread executes Unregister-Event command, then call DrainPendingActions and will never come back possibly because its getting stuck in the while loop.

**Comment by PaulHigin** [comment]
This may be related to #4003

I am not very familiar with engine events, but I think it needs a review.  Other parts of the engine rely on engine events so making changes here will be risky.

**Comment by SeeminglyScience** [comment]
@PaulHigin That was my first thought too, but since it's different processes I'm hesitant to attribute it to that.

@prasanthialluMSFT were you able to determine some repro steps or is it too intermittent?

**Comment by prasanthialluMSFT** [comment]
@SeeminglyScience  I do not have a consistent repro.

**Comment by PaulHigin** [comment]
Removing Area-Remoting tag.  This is an engine events issue.  The incorrect order of events is causing the hang, and appears to be a threading problem:

**This problem is a kind of deadlock. A thread which is calling DrainPendingActions is actually the thread that invokes actions in ActionQueue. Therefore, DrainPendingActions will never finish if there are one or more actions in ActionQueue.**

Without a customer repro, all we can do is examine the code and try to come up with one.
