### ISSUE TITLE
Feature Request: Default profile for powershell

### ISSUE THREAD

**Issue by EArminjon** [PowerShell/PowerShell#13709]
Hi,

I spent always long minutes to setup terminal for people and i didn't understand why the following profile is not the default one for powershell :

```
Import-Module PSReadLine

Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete
Set-PSReadlineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadlineKeyHandler -Key DownArrow -Function HistorySearchForward
Set-PSReadLineOption -predictionsource history
Set-PSReadLineOption -HistorySearchCursorMovesToEnd 
```

It requiert "PSReadLine 2.1.0-beta2"
(didn't know why these features are just in beta, because they exist on every other OS since many years, but that's not the point.)

**Comment by vexx32** [comment]
The only one in beta currently as far as I'm aware is the `-PredictionSource` option.

As for the rest, the default settings are handled by PSReadLine itself, so it might be better to ask in [that repository](/PowerShell/PSReadLine/issues) instead of this one. 🙂

**Comment by EArminjon** [comment]
PSReadLine is added by default on powershell right ?

**Comment by vexx32** [comment]
Yeah it's pulled into the default build. 🙂

**Comment by jhoneill** [comment]
Those have been the default options for PowerShell since windows PowerShell V1. On linux default tab behaviour is different and setting edit mode allows you to get a different one. 
TBH, it is so ingrained for every existing PowerShell user , and included in so many documents that changing it to someone else's preference has very little chance of happening.  I'd leave users to set their own preferences, most of us have our own customizations and I would impose mine on my user community.
