### ISSUE TITLE
Test-Connection fragmented output

### ISSUE THREAD

**Issue by danielniccoli** [PowerShell/PowerShell#13913]
When having to ping multiple IP addresses, PowerShell 7 does fragment the output. This was different and much easier on the eyes in PowerShell 5.1 and should be changed to reflect how it worked in PS5.

## Steps to reproduce

```powershell
Test-Connection -ComputerName 1.1.1.1,8.8.8.8 -Count 1
```

## Expected behavior

```none
Source        Destination     IPV4Address      IPV6Address                              Bytes    Time(ms)
------        -----------     -----------      -----------                              -----    --------
MYCOMPUTER    1.1.1.1         1.0.0.1          xxxx:xxxx:xxxx::xxxx                     32       19
MYCOMPUTER    8.8.8.8         8.8.4.4          xxxx:xxxx:xxxx::xxxx                     32       24
```

## Actual behavior

```none
   Destination: 1.1.1.1

Ping Source           Address                   Latency BufferSize Status
                                                   (ms)        (B)
---- ------           -------                   ------- ---------- ------
   1 MYCOMPUTER       1.1.1.1                        20         32 Success

   Destination: 8.8.8.8

Ping Source           Address                   Latency BufferSize Status
                                                   (ms)        (B)
---- ------           -------                   ------- ---------- ------
   1 MYCOMPUTER       8.8.8.8                        21         32 Success
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by doctordns** [comment]
FWIW, this behaviour is also present in 7.1 RC1.

Additionally, if you try to force it to be a formatted table, this command still produces curious output, for example:

```powershell
Test-Connection -ComputerName 1.1.1.1,8.8.8.8 -Count 1 | Format-Table

   Destination: 1.1.1.1
Ping Source    Address Latency(ms) BufferSize(B) Status
---- ------    ------- ----------- ------------- ------
   1 cookham24 1.1.1.1           6            32 Success

   Destination: 8.8.8.8
Ping Source    Address Latency(ms) BufferSize(B) Status
---- ------    ------- ----------- ------------- ------
   1 cookham24 8.8.8.8           6            32 Success
````

**Comment by vexx32** [comment]
Yeah, the grouping by hostname is intentional, if I recall correctly.

Essentially, because there's no way for the formatter to know when it's processing the first couple records returned whether there will be more records from one or more hosts, it's instructed to group by hostname so that if you do that with `-Count 3` or whatever the data isn't all mixed together.

Personally I find it more readable in this way, but you could do `Format-Table -GroupBy Ping` if you wanted to, I suppose. Or any other property. Not sure if there's an explicit way to completely disable a builtin grouping format, though `| Select-Object * | Format-Table` will generally work _okay_ (though it will also expose normally hidden properties that don't look nice in a table typically)
