### ISSUE TITLE
Add $lastExitCodeErrorPreference so $lastexitcall != 0 will produce an exception

### ISSUE THREAD

**Issue by per-oestergaard** [PowerShell/PowerShell#13916]
## Summary of the new feature/enhancement

As a user, I want to be able to fail scripts automatically when $LASTEXITCODE becomes larger then 0 so that I can capture these as easy as errors I can capture with $ErrorActionPreference='stop'

When external executables are called, we have to remember to add `if ($lastexitcode)` statements all over. As this is easy to forget, it can result in unexpected results. Furthermore, it pollutes code and depending on the setup, the script writer may not be aware of whether say a certain alias is a script or an external executables.

This will make error handling more uniform.

## Proposed technical implementation details (optional)

Whenever an external command is executed (NativeCommandProcess.cs, I assume) and _nativeProcess.ExitCode != 0 && LastExitCodeErrorPreference == 'stop' stop the script like Write-Error does.
The exception thrown should contain the exitCode so that a catch construct can evaluate it in those cases where a non-zero value should be handled.

**Comment by mklement0** [comment]
There's a pending [RFC](https://github.com/PowerShell/PowerShell-RFC/pull/261/files) that covers this topic.

In the meantime there's a slightly easier per-command solution, using the new pipeline-chain operators:

```powershell
whoami -nosuchoptions || $(exit $LASTEXITCODE)
```

* The unfortunate syntactic need for `$(...)` is explained in the comments by @rjmholt  in #10967.
* Also, unlike in POSIX-like shells, `exit` does require an explicit argument, otherwise it will report `0`.

If you want to take a page out of Perl's book, you can ease the pain with a helper function:

```powershell
function die { exit $LASTEXITCODE }

whoami -nosuchoptions || die
```
