### ISSUE TITLE
del, rmdir, Remove-Item are deleting wrong file/folder in CaseSensitiveInfo enabled folders

### ISSUE THREAD

**Issue by pee-tu** [PowerShell/PowerShell#13939]
## Steps to reproduce

```powershell
fsutil file setCaseSensitiveInfo d:\ca
D:\ca> mkdir HH
D:\ca> mkdir hh
D:\ca> rmdir hh
```

## Expected behavior

```none
Lowercase named object 'hh' is removed.
D:\ca> dir
HH
```

## Actual behavior

```none
Uppercase named object 'HH' is removed instead of 'hh'. The same observed for 'Remove-Item' and 'del'. Also for files.
D:\ca> dir
hh

```

## Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.1.0-rc.2
PSEdition                      Core
GitCommitId                    7.1.0-rc.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
So I think the problem lies in https://github.com/PowerShell/PowerShell/blob/7e145ef2da91f2ac49e9a4d4a988f309a02007ad/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L173.

When the FileSystemProvider is given a path it tries to normalise it which involves a few steps like converting file system separators from the alt to the actual separator. The current code is designed to get the actual casing of the path item, so if you did `Get-Item -Path C:\WinDowS | Select Name, FullName' it will be `Windows` and not the one specified in the cmdlet parameter.

The trouble in this case is that `[IO.Directory]::GetFileSystemEntries('D:\ca', 'hh')` is case insensitive on Windows regardless of the folder settings and it will return both folders, for example:

```powershell
PS C:\temp\ca> gci


    Directory: C:\temp\ca

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          30/10/2020 11:31 AM                HH
d----          30/10/2020 11:31 AM                hh

PS C:\temp\ca> [IO.Directory]::GetFileSystemEntries('C:\temp\ca', 'hh')
C:\temp\ca\HH
C:\temp\ca\hh
```

Now when `GetFileSystemEntries` returns 1 or more elements the current code just returns the first one, in your case `HH` https://github.com/PowerShell/PowerShell/blob/7e145ef2da91f2ac49e9a4d4a988f309a02007ad/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L174-L177.

It sounds like we need a more stringent check when multiple elements are returned here. I'm not sure if this code path is also meant to handle wildcard in the path but it does explain this issue. While the code has changed a bit, the use of normalising the path was introduced with https://github.com/PowerShell/PowerShell/commit/6bc2b55fdf99bf70cf11bbc2a37ffa20aa9881d5 and  part of the 7.0.0 release.

**Comment by pee-tu** [comment]
Thanks for prompt response. 
I guess the simplest fix for now would be to replace line 176 with following piece:

```none
if( entries.Length == 1) 
{
    // This one here is a little bit complicated case:
    // CaseSensitiveInfo might be still enabled but requested "item" is not matched case against folder entry.
    // Therefore it is rather tentative fix. Permament fix would required to check
    // whether folder is Case-enabled which would indicate match case is required otherwise a blind delete is OK
    exactPath = entries[0];
}
else
{
    // >1 indicates that CaseSensitiveInfo is enabled and there are multiple entries,
    // item must match case - no other option possible.
    foreach(entry in entries)
    {
        if(entry == item)
        {
           exactPath == item;
        }
    }
   // here the error would be requred if nothing is matching case. Deleting a random item woud not be a good idea.
}
```

**Comment by vexx32** [comment]
That sounds like a pretty good medium, assuming wildcards aren't going to cause complications. It would be good for the error message to mention the file/folder names that were found so the user knows it's a casing issue.

**Comment by pee-tu** [comment]
One issue with that piece of code: it will only works in Windows. For linux everything must go case-sensitive.

**Comment by jborean93** [comment]
> One issue with that piece of code: it will only works in Windows. For linux everything must go case-sensitive.

On Linux at least `GetFileSystemEntries()` is case sensitive so it will match the entries exactly. What I don't know is if that's dependent on the file system being case sensitive or if it's just a global rule. Unfortunately that sits in another repo but I would hope it's the latter.
