### ISSUE TITLE
PowerShell docker container security module

### ISSUE THREAD

**Issue by vrpalla-rms** [PowerShell/PowerShell#13987]
## PowerShell docker container security module
Availability of complete security module in docker PowerShell container

## Technical details
To enforce permissions on our network file shares, we are using the security module within PowerShell. The following commands (get-acl, set-acl) are used to acquire the permissions from root of the share and push them onto the subfolders and files. These commands are released in Windows PowerShell version3. 

Researching online, as only the core version of PowerShell is supported on Linux as of now, these commands aren't available. It appears these are only supported on the full version.

Availability of the complete security module in PowerShell container would be crucial for our use case. Else, if it is possible to install the module in container, please feel free to point me to the documentation.

Please find the details of PowerShell container used
PowerShell container: mcr.microsoft.com/powershell:7.0.0-preview.6-centos-7

**Comment by jborean93** [comment]
There are 2 issues I see with supporting the `*-Acl` cmdlets on that Docker container because it runs on Linux

* Accessing paths would need to be mounted
    * Linux does not natively support the UNC paths that you expect on Windows like `\\server\share\path`
    * You usually use something like [smbclient](https://www.samba.org/samba/docs/current/man-html/smbclient.1.html) to map the network path to a local path like `/mnt/server/share/path`
    * So while possible it requires some more system packages and set up for you to access these paths in PowerShell
* The underlying .NET classes that the `*-Acl` cmdlets use are heavily dependent on Windows specific structures like [SECURITY_DESCRIPTOR](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-security_descriptor), [ACEs](https://docs.microsoft.com/en-us/windows/win32/secauthz/ace), [Security Identifiers](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/security-identifiers)
    * While it's possible to craft this stuff outside of Windows it requires a lot of work to just implement
    * SMB does support getting/setting the security descriptor of an object but it's up to the client to expose this functionality
    * The way this is done can differ based on the client that has mounted the path
* Even if the above is handled, translating Security Identifiers to an actual account name requires even more work
    * This might be provided by the client but will need even more configuration to be able to make the RPC calls to the domain controller

All this work is technically outside the realm of PowerShell. I'm sure it is all theoretically possible but would require a lot of ground work to be done and even then it may be difficult to set up properly. Your best bet is to

* Run a Windows container that runs PowerShell Core
    * This will have the required .NET libraries and give you the ability to access UNC paths like you normally expect on Windows
* Use the native tools available on Linux to mount and edit the SDs through the binaries they provide

**Comment by vrpalla-rms** [comment]
@jborean93 Thank you for the detailed technical explanation and the quick response.

The explanation makes complete sense as to why it would be difficult to achieve this in a Linux docker environment.

Does it mean if we have a Windows docker environment, running the same PowerShell container would work there as it would have the underlying libraries (or) would it still be the same?

**Comment by jborean93** [comment]
> Does it mean if we have a Windows docker environment, running the same PowerShell container would work there as it would have the underlying libraries (or) would it still be the same?

Will work for a Windows container as the .NET libraries and the underlying system can understand all that.

**Comment by iSazonov** [comment]
You could use PowerShell remoting to connect to a Windows system and run needed commands there.
