### ISSUE TITLE
Add correct hashbang executon and handling for various languages

### ISSUE THREAD

**Issue by eabase** [PowerShell/PowerShell#14009]
Back in the beginning of time there was an issue dealing with the way powershell handles (executable) script files, most often seen in anything made in a native *nix environment. The idea is to be able to run hashbanged scripts from pwsh. 

Q: What is a hashbanged script?  
A: Pretty much any script starting with something like:

```python
#!/usr/bin/env python3
# mypyscript -- This is any random python coded script executable from command line
print('Don't let hashbang issues disappear like teardrops in the sea!')
...
```
<sub>Yes, so you noticed this hashbang is not for windows. Well, yes a no. It is correct for WSL, but powershell doesn't understand it for the obvious reason, it is *supposed to be path*. However, if Windows powershell would like to maintain any compatibility with any future script handling, pwsh developers need to rethink this "path": `/usr/bin/env` and handle it as a virtual path like any of the other [special windows paths](https://ss64.com/nt/syntax-variables.html).</sub> 

Two things for sure.  
1. It should not, under any circumstances, change what's in the original code. 
2. Windows/Powershll dev's should not start putting their own Windows paths there. 
(Instead consider removing the path altogether, by using just the interpreter's name, like `#!python3`, but maintaining full compatibility with the 20+ year `/usr/bin/env` and `/bin/<interpreter>` formats. 

## Steps to reproduce

```powershell
./mypyscript

# doesn't work
```

## Expected behavior

```powershell
./mypyscript

Don't let hashbang issues disappear like teardrops in the sea!
```

We should be able to dot-execute any scripted code from powershell command line, when that code contain the correct hashbang for the scripting engine. (Eg. `.ps1 .py .go .js etc.`) 

## Actual behavior

* Doesn't work:   
Opens a window dialog, asking what you want to use to open this file.

* A secondary issue, is that:  
some installers actually modify the original code's first hashbang line.  
**This should never be allowed to happen!**

---

A longer and far more technical and detailed discussion of this, was made in this issue:
* https://github.com/PowerShell/PowerShell/issues/9430

But it's title is perhaps not ideal, to make it a very relevant issue, although it is the essence. 
(Issue pertains to handling of **`.`** (dot) in the `$env:PATHEXT`. )

Furthermore there was an honest attempt by @mklement0 to provide a CMD-based work-around
 as discussed in this SO question: 

* https://stackoverflow.com/questions/55601446/how-to-run-a-python-program-from-powershell-based-on-python-hashbang

**Comment by jborean93** [comment]
IIRC [shebangs/hashbangs](https://en.wikipedia.org/wiki/Shebang_(Unix)) are really handled in the kernel and not the shell and the Win32 subsystem on the NT kernel doesn't have a concept of shebangs. For non-executable files, Windows really uses the extension of the file to determine what program to use to open the file itself so when you do `./mypyscript` with a shebang of `#!/usr/bin/env python3` Windows has no idea what to do with it. Even trying to add support for interpreting Unix shebangs will be fraught with danger and IMO too magical, using `#!/usr/bin/env python3` as an example:

* On Windows Python is just installed with `python.exe` so there will be no `python3.exe` in the `PATH`
* Even if there was, what Python 3 interpreter will be used if there are multiple present
* If it was also just `#!/usr/bin/python3` then it's the same issue, probably even more so because it's a hardcoded path and on Unix it won't rely on the `PATH`

Personally I think this would require too much magic and maintenance to achieve.

**Comment by mklement0** [comment]
@eabase, while I like the idea in principle, I think @jborean93 is correct - we can't just do this _automatically_.

What may be worth considering is to propose a _PowerShell-specific_ feature: something along the lines of a dedicated new filename extension, say `.psx`, with perhaps a custom shebang-line format that covers all platforms, and that PowerShell (only) would allow you to call _without the filename extension_ even on Unix-like platforms.

On Unix-like platforms, for security reasons, the executable bit would have to be set too.

If this sounds interesting to you, I encourage you to open a new feature request and flesh this idea out (though I can't guarantee that others may find it interesting / unproblematic).

**Comment by eabase** [comment]
@mklement0 

> What may be worth considering is to propose a _PowerShell-specific_ feature: something along the lines of a dedicated new filename extension, say `.psx`, with perhaps a custom shebang-line format that covers all platforms, and that PowerShell (only) would allow you to call _without the filename extension_ even on Unix-like platforms.

I don't quite understand what you mean there. Are you proposing to handle *files* with a new extension like, `myscript.psx` or are you proposing a hashbang, like `#!/usr/bin/enx psx`?

I think maybe you're proposing the former, but regardless, from a portability perspective, I disagree with both. The whole point here, being that we should be able to execute any script (regardless platform) using the dot method. 

> On Unix-like platforms, for security reasons, the executable bit would have to be set too.

Yes, that is also needed, but I have no Widows experience for this, as all my Windows machines are completely permission free. The very first thing I do on **any** vanilla Windows machine is to turn off UAC, and enable Admin on all my shells by default. As a non-corporate sysop, I just find my life unbearable having those (sorry, but rather useless) productivity blocking features on. So until the day that windows group/file/execute policy/permissions become a one-click operation, that is how I will continue to operate. And in those few cases I have ran into file ownership trouble, Cygwin has come to the rescue and been my best friend for the last 20 years!  

-- So yes, latest development Windows 10 version, always has Cygwin installed! (And no, WSL will never replace the lightness of Cygwin with all it's bloated VM features and gigabyte installs.)

> If this sounds interesting to you, I encourage you to open a new feature request and flesh this idea out (though I can't guarantee that others may find it interesting / unproblematic).

I think the hacks presented in the linked SO post will have to do for now.

**Comment by mklement0** [comment]
> Are you proposing to handle files with a new extension like, `myscript.psx`?

Yes.

> Windows machine is to turn off UAC, and enable Admin on all my shells by default.

Understood, but just to spell it out: You're choosing to bypass the platform's security features.
It is the equivalent of running all scripts on Unix with `sudo` / as `root`.

> The whole point here, being that we should be able to execute any script (regardless platform) using the dot method.

Cross-platform abstractions are a wonderful thing, and I welcome them in general.

It is why I created the hack in the linked SO post, but it is just that: a _hack_.

Here, the only safe and predictable way forward is to create an abstraction _in the realm of PowerShell_, hence my suggestion.

The alternative on Windows is to _stay in the realm of WSL_ and install PowerShell _there_ - but that's not a true cross-platform solution.
However, you'll even be able to execute shebang-based scripts stored in the _Windows_ file-system, as long as these script use LF-only newlines rather than Windows CRLF ones (WSL2 seemingly implicitly considers all Windows file-system files _executable_).

**Comment by mklement0** [comment]
A terminology caveat:

> dot-execute

This sounds like [_dot-sourcing_](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Operators#dot-sourcing-operator-), which is entirely unrelated to the issue at hand.
It is a general requirement in PowerShell, for security reasons, to explicitly signal the intent to invoke executables located in the _current directory_, using a _path_, which in the simplest case means prefixing the file name with `.\` or `./`.

**Comment by mklement0** [comment]
> Instead consider removing the path altogether, by using just the interpreter's name, like #!python3

Note that this is tantamount to calling for a _PowerShell-specific_ abstraction, given that Unix shebang lines require _full_ paths - and breaking the _native_ shells on Unix-like platforms - which rely on the _kernel_'s interpretation of the shebang lines, which would then fail - is ill-advised.

**Comment by eabase** [comment]
> This sounds like dot-sourcing, which is entirely unrelated to the issue at hand.

Not sure what you're saying here, but I mean that with proper shebang behavior, you can execute the script with same method as in Powershell, with `./myscript.py`, **`in the current scope`**, and without additional source dot in front. AFACT, this is how *nix behaves.

> Note that this is tantamount to calling for a _PowerShell-specific_ abstraction, given that Unix shebang lines require _full_ paths - and breaking the _native_ shells on Unix-like platforms - which rely on the _kernel_'s interpretation of the shebang lines, which would then fail - is ill-advised.


Yes, Indeed. I didn't really like that, but it was not my idea, it was mentioned as a [comment](https://stackoverflow.com/questions/55601446/how-to-run-a-python-program-from-powershell-based-on-python-hashbang#comment97901358_55601446) by `Eryk Sun` in that SO link.

**Comment by mklement0** [comment]
> Not sure what you're saying here

This was primarily a terminology quibble: we're talking about regular PowerShell invocation of _external executables_ here, nothing to do with "dots", which makes people think of dot-sourcing, which is limited to in-process execution of _PowerShell code_ directly in the caller's scope instead of a child scope.

> in the current scope

Shebang-based scripts invariably run in a _child process_, the concept of a PowerShell scope therefore doesn't apply.

---

Here's how I could _potentially_ see this happen without introducing new PowerShell constructs such as `.psx`, relying on PowerShell to directly act on Unix shebang lines (and note that I'm just a fellow PowerShell user, these are just my thoughts):

* For backward compatibility and security reasons, an _opt-in_ would be required:

  * The hack in the SO answer _implicitly_ uses such an opt-in, by requiring `.` to be added to `$env:PATHEXT` in order to mark extension-less files as executable; however, given that the interpretation of such files would be PowerShell-specific, it's better not to modify an _environment_ variable that other shells such as `cmd.exe` would see too, and instead use a PowerShell _preference_ variable.
 
  * The security challenge there is that either way this would be a _global_ switch, unlike in the Unix world, where each shebang-line-based script must _individually_ have executable permission bit(s) set.
    * _Conceivably_, NTFS alternate data streams could be used, they way they are for blocking scripts downloaded from the internet, but that sounds obscure and cumbersome.

* For security and predictability reasons, only `#!/usr/bin/env <utility>` would be supported - not also direct paths such as `/usr/bin/python` - and PowerShell would interpret that as having to look for `<utility>` in `$env:PATH`.

  * The upshot is that any cross-platform shebang-based scripts would have to be created using the form `#!/usr/bin/env <utility>`

I'm no security expert, so others will have to weigh in whether a global opt-in is acceptable or not.

**Comment by eabase** [comment]
Just for reference, this is what the Python3.8 Docs [says about shebang](https://docs.python.org/3.8/using/windows.html?highlight=shebang#shebang-lines): 

> To allow shebang lines in Python scripts to be portable between Unix and Windows, this launcher supports a number of ‘virtual’ commands to specify which interpreter to use. The supported virtual commands are:

```gitignore
/usr/bin/env python
/usr/bin/python
/usr/local/bin/python
python
```

and ...

> For example, a shebang line of `#!python` has no version qualifier, while `#!python3` has a version qualifier which specifies only a major version.
> 
> If no version qualifiers are found in a command, the environment variable `PY_PYTHON` can be set to specify the default version qualifier. If it is not set, the default is “3”. The variable can specify any value that may be passed on the command line, such as “3”, “3.7”, “3.7-32” or “3.7-64”. (Note that the “-64” option is only available with the launcher included with Python 3.7 or newer.)

**Comment by mklement0** [comment]
Interesting, @eabase; didn't know about Python's shebang support.
Two observations:

* Since Python is not a shell, it still relies on the underlying shell for invocation of scripts, which means that scripts have to have the `.py` extension in order to be executable (hacks aside) - something we would want to avoid.

* Overlaying Windows-only functionality on a Unix concept - e.g. `#!python3` and version/bit-ness specifiers - strikes me as ill-advised.

---

* `/usr/bin/env <binary>` is _unequivocally_ an expression of the intent to defer to `$env:PATH` to locate the binary.

* `/usr/bin/ <binary>` (Linux) and `/usr/local/bin/ <binary>` (macOS) are _defensibly_ so, though they aren't _strictly_, given that it is possible to preempt these locations in `$env:PATH`. Still, overall it makes sense to me to also defer to `$env:PATH`.

* All others paths I still recommend _not_ be supported, because there's no sensible _guessing_ as to the intent, and with something like `/bin/sh` - signaling the intent to use the platform's _default shell_ - there is no analog on Windows, and executing an arbitrary `sh.exe` somewhere in the path could be considered a security risk.

---

To flesh out the need for an _opt-in_: Without it, at least hypothetically, things may start executing that didn't execute before:

* If you have a currently dormant extension-less shebang script somewhere in `$env:PATH`, calling it by file name only will start executing it - even if an `*.exe` file or file with any other extension listed in `$env:PATHEXT` with the same base name is also present.

  * Note: if there _isn't_ a true executable with the same base name also present, you already do get execution of sorts: such a file is unexpectedly opened _as a document_, which I consider a bug that should be addressed separately - see #12632.

* Similarly, if both a shebang script `foo` and `foo.ps1` are present in the current directory, `./foo` will then start executing `foo`, given that its file name is an exact match (this is how it already works on Unix).

**Comment by eabase** [comment]
@mklement0 
I agree on all part in section A and B, as for the last section C, I don't have anything to add. 

Perhaps we need to get someone into this thread, that doesn't agree and may have some sensible counter arguments?

**Comment by mklement0** [comment]
@eabase, my recommendation is to open a _new_ issue, of type "Feature Request/Idea", and to make a focused case based on our shared understanding, leaving the security / opt-in issue as an open question, soliciting feedback.
