### ISSUE TITLE
7.1 installed from the Microsoft Store bugs

### ISSUE THREAD

**Issue by user8446** [PowerShell/PowerShell#14059]
#Steps to reproduce
1. Install v7.1 from the Microsoft Store

## Expected behavior
1. Installed v7.0 should upgrade to 7.1.
2. 'pwsh' should bring up 7.1 but the environment variable isn't updated. It brings up the installed 7.0. However, 'pwsh.exe' brings up v7.1.
3. VS code also doesn't recognize the update

## Actual behavior
See above

```

## Environment data

<!-- provide the output of $PSVersionTable -->

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by fMichaleczek** [comment]
@user8446
> Installed v7.0 should upgrade to 7.1.

MSIX vs MSI (Windows Store VS Control Panel ) : https://www.advancedinstaller.com/msix-limitations.html
I would say by design ? 

> 'pwsh' should bring up 7.1 but the environment variable isn't updated. It brings up the installed 7.0. However, 'pwsh.exe' brings up v7.1.
- On my setup, I install first the 7.1 msi then the 7.1 Store.
- In the Windows Terminal, it detects PowerShell as the Store Version and PowerShell 7.1 as the MSI version
- My where.exe : 
```
C:\Users\X>where.exe pwsh
C:\Program Files\PowerShell\7\pwsh.exe
C:\Users\X\AppData\Local\Microsoft\WindowsApps\pwsh.exe
```

Maybe better to continue to the MSIX thread https://github.com/PowerShell/PowerShell/issues/10894

> My VS code doesn't find the store version

- The same on my steup
- MSIX is not tested see end of the issue. Maybe better to continue to this thread https://github.com/PowerShell/vscode-powershell/issues/2147 

- My Workaround 
```
    "powershell.powerShellAdditionalExePaths": [
        {
            "exePath": "C:\\Users\\Flavien\\AppData\\Local\\Microsoft\\WindowsApps\\pwsh.exe",
            "versionName": "PowerShell Store"
        }
    ],
    "terminal.integrated.shell.windows": "C:\\Users\\Flavien\\AppData\\Local\\Microsoft\\WindowsApps\\pwsh.exe",
    "powershell.powerShellDefaultVersion": "PowerShell Store"
```

I would say duplicate thread, you should close it and continue on each subthreads.

**Comment by user8446** [comment]
Thank you for the information. I don't know enough about msix vs msi even after reading that if msix can't do an in-place upgrade of existing apps or if just wasn't written when it was packaged up. Maybe someone on the team can give some insight.
I'm not sure if https://github.com/PowerShell/vscode-powershell/issues/2147 applies as that was for a preview and now we are talking about a release so we actually want the PATH variable.
Thank you for the VS Code workaround!

**Comment by fMichaleczek** [comment]
@user8446 The main covered scenario is a new install with only the msix version, everything different need to be configured manually. No bugs, only additionnals config and a need fof a better autodetect  configuration in tools. But nothing related to PowerShell Core.

Most of limitations are in the Windows Sdk, so outside this repository. It's actively developed right now, Windows Teams has open an insiders feed. And the powershell work on the subject. People will found this issue as a workaround. Close this one and ask the others teams in charge of tooling. They need testers too.

**Comment by kilasuit** [comment]
> Installed v7.0 should upgrade to 7.1.

@user8446  - The PowerShell version in the store prior to 7.1.0 was actually PowerShell Preview & not the Stable version - so this wouldn't have actually been possible. 
I will admit that I had been expecting the same on the release day & was in and out of the Store checking for updates ( I blame the lack of coffee for not putting the difference of preview/stable as why it wouldn't auto install)


> VS code also doesn't recognize the update

I can't say that I'm seeing this & must be a localised issue with your install of vscode if you click the following (bottom right)
![image](https://user-images.githubusercontent.com/6355225/99148539-167ea500-2680-11eb-89e0-f6673e7bb5a6.png)

Do you get this show

Code insiders 
![image](https://user-images.githubusercontent.com/6355225/99148456-9eb07a80-267f-11eb-8b9a-f23ce36f7362.png)


Code (note this is the same as insiders above)

![image](https://user-images.githubusercontent.com/6355225/99148464-abcd6980-267f-11eb-8ac6-2eb02a568649.png)

**Comment by user8446** [comment]
Hi @kilasuit - sorry I didn't leave enough info. I wasn't on the MS Store preview, I was on an MSI installed v7.0. I had hoped that the MS Store/MSIX installer would have detected that and do an upgrade.

I ended up updating the MSI installed version through VS Code (1 click upgrade) so I actually have both now.

I'll close and post for the Windows Teams per the comment above

**Comment by kilasuit** [comment]
Ah yes that's not actually possible as they are different installation methods

**Comment by juvtib** [comment]
user8446 wrote: 
> [I]f msix can't do an in-place upgrade of existing apps or if just wasn't written when it was packaged up. Maybe someone on the team can give some insight.

user8446 wrote: 
> I was on an MSI installed v7.0. I had hoped that the MS Store/MSIX installer would have detected that and do an upgrade.
> 
> I ended up updating the MSI installed version through VS Code (1 click upgrade) so I actually have both now.

kilasuit wrote: 
> Ah yes [upgrading a MSI with MSIX is] not actually possible as they are different installation methods

For clarity, the Store app (MSIX) cannot upgrade previous versions of PowerShell (MSI). You're making the reasonable assumption that PowerShell 7.1 will upgrade and replace 7.0. But MSI and MSIX don't talk to each other. This is by design. They are two different silos. This also explains why it is possible to have two, side-by-side installations of 7.1: MSI (Web/VSCode) and MSIX (Microsoft Store). Without realizing it, you've crossed a technology border in going from PowerShell 7.0 (MSI) to 7.1 (MSIX). 

If your intent is to standardize on the Store version, the proper way would be to uninstall the MSI versions and to get PowerShell only from the store. Because Settings might not differentiate between MSI and MSIX, I recommend uninstalling all PowerShell 6.0+ versions and then installing from the Store. This will make it easier to get back on track. 

Another point of confusion might be that regardless of which PowerShell 6.0+ version you're using, PowerShell 5.1 will always be installed. The technical reason for this is 5.1 has cmdlets and compatibility not present in PowerShell 6.0+. PowerShell 5.1 is 'Windows&nbsp;PowerShell'. And PowerShell 6.0+ is 'cross-platform&nbsp;PowerShell'.

**Comment by user8446** [comment]
Thank you, I wasn't aware that the MSIX pkg was not configurable to install over the MSI installed one.
The whole goal here was to have one more program on 'package management' that you don't have to mess with like on linux.

**Comment by juvtib** [comment]
As you found out, there are two options. 

You can rely on the update check when you launch VSCode. That will update the MSI. There should also be a reminder when you launch PowerShell. 

![A reminder to upgrade PowerShell shows on launch.](https://i.imgur.com/UGh4IU0.png)

Or the package from the Store should [automatically update](https://www.thewindowsclub.com/microsoft-store-apps-not-updating-automatically-in-windows-10).
