### ISSUE TITLE
Study sync HttpClient opportunity

### ISSUE THREAD

**Issue by fMichaleczek** [PowerShell/PowerShell#14058]
## Summary of the new feature/enhancement

Starting net5.0, HttpClient can be sync.

See 
https://github.com/dotnet/runtime/pull/34948
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/

Sample : 
![alt text](https://pbs.twimg.com/media/EmDSM2pXEAESoTH?format=png&name=900x900)

![image](https://pbs.twimg.com/media/EmDUBH1X0AAEG5w?format=png&name=small)

**Comment by iSazonov** [comment]
@fMichaleczek It is not clear what you are asking.

**Comment by fMichaleczek** [comment]
- Replace async method to sync to  improve stability and compatibility. (remove awaiter etc..)
- Verify that the new methods can be cancelled
- Document the API in PowerShell as an universal workaround to close all weird issues to web. The goal of the works in the new API, if I understand well, was to give a sync API not only for HttpClient but also all necessairies types to consume it.

At the opposite, HttpClient is broken on Blazor WebAssembly because Async method are mandatory and awaiter forbidden. net6.0 bring native Android, Wasm on top of Xamarian and maybe UWP

 All these new platforms need a httpclient first strategy in the Dependency Injection because authentification/CORS/security/crypto. For example, If i want a file from my compiled project, I need to download the file first (text, md, hlp, ps*) and copy to the inmemory filesystem. 

@iSazonov How do you want I organize the issue ? one or for each platform ?

**Comment by iSazonov** [comment]
@fMichaleczek If you say about porting PowerShell on these platforms we need to ask PowerShell Committee. If they confirm MSFT interest in the work I guess they will ask you to create a conceptual RFC. Today is good time for such RFC since MSFT team plans to split PowerShell Engine on some subsystems in next milestone (at least start) and they might think about compatibility of the subsystems with other platforms.

**Comment by fMichaleczek** [comment]
I am working only with the Microsoft.PowerShell.Sdk, I mean embedded PowerShell. I'm not briging more web to PowerShell, there is some requirements, not a lot, and it's mostly net5.0 improvements in old areas. I'm working on a NoName.PowerShell.Sdk, I have bug with SMA that need to be resolved and if an API is broken in a core module, I want to resolve it. 

A important point, Web mean 3rd parties and breaking changes. I see how my WebAssembly PR is complicated because I use a standard template from the aspnet team. Imagine, if someone dislike Dependency injection, another trimming etc.. Well, i only want to said Web is opiniated, Asp.Net is opiniated and a shell object... 

Microsoft open source management for projects which had moved from netframework was a little bit too much strict in general. I understand it's a complicated move, the result is nice. Now in the net6.0 timeline, there is also a global move to be more relax with contributions. Microsoft is aware open source management à la Winform/WPF is toxic. What people ask is interface, di, provider, logs, configuration, options and a good sdk, nothing complicated.

 Asp.net core is a bright result from a technical point of view and community is very happy. I am adapting owerShell inside Asp.Net, not in the other way, so I want to keep a cool Web mindset, not the Windows PowerShell old school. I think it's very important to say it, because to implement the other way, PowerShell should be a real language at core, it maybe will happen in 10 years and need PowerShell's Committee.

Technicaly, I would prefer a real msbuild sdk. It's easy to create it,  dotnet team have a lot (dotnet, worker, aspnet, blazor, webassembly, android etc..). It build embedded app, but I keep in mind it's complicated without a power-notshell committee ? "A shell and a language" are still a kind of problem to define to each platform. (Should Android but be a launcher in Android world and fetch my mail ?).

For the first quarter of the net6.0 timeline, I need to open issues on Path & FileLess, HttpClient and planned obsolescence in net5.0 to make any demos later. I open the issues, wait for feedback, update with the last technical info, discuss and will post some PR.

A RFC is a very good idea. I don't see any reason to not ask community too, but I'm still thinking PowerShell is a bad name when we approach this area. People will ask for things that don't even exist in the available sandbox... 

If you have any feedback to provide, i'm interested too. There is twitter's discussions with @SteveL-MSFT, I hope the discussion tab on github will be open soon, I would prefer to open there. Or join us on Twitter,  with 2.7k issues here, it can be a place to speak about innovations. 😅

**Comment by fMichaleczek** [comment]
see peachpie php sdk :
https://github.com/peachpiecompiler/peachpie-templates/blob/master/src/Content/web/Website/Website.msbuildproj

**Comment by iSazonov** [comment]
> There is twitter's discussions with @SteveL-MSFT, I hope the discussion tab on github will be open soon, I would prefer to open there. Or join us on Twitter, with 2.7k issues here, it can't be a place for free speech about innovations.

People may prefer different forums for discussion, but this repository is the right place to bring them all together to work on a project. You could share a reference to the discussion here. 
MSFT team creates working groups (read their blog post about this) and you can do work in a group like the WG-DevEx-SDK or become the leader of another group. So a lot of open issues is not a problem (we use labels).

>  I mean embedded PowerShell.

I think we can summarize what you are talking about - **"PowerShell should be modernized for better supporting modern hosting scenarios in modern frameworks."**

If so and if you want to move forward, then you definitely need (1) to create Meta RFC and the following more specific RFCs, (2) create a work group. I hope there are many interested people.

Historically, PowerShell had only two hosts - conhost and graphical host (removed from the repo), and "limited" hosting support due to closedness and work only on Windows. Conhost did not evolve due to limitations of earlier versions of .Net Core. .Net Core is now richer and _the PowerShell hosting area is a great area for innovation_.
We have already encountered limitations in this area and eliminated some of them. But this work was more spontaneous than a well thought out plan. This is why I am talking about the working group and RFCs.

**Comment by fMichaleczek** [comment]
> If so and if you want to move forward, then you definitely need (1) to create Meta RFC and the following more specific RFCs, (2) create a work group. 

Agree. 2 groups : WG-DevEx-SDK & WG-DevEx-SDK-Experimental
I don't want to resolve legacy things in the first cycle (net 6.0), as Microsoft (not the PS Team) continues to build new host without make a better shared framework so I will not run after the rabbit.

**"~~PowerShell~~ SMA should be modernized for ~~better supporting~~ modern hosting ~~scenarios in modern frameworks.~~"**
PowerShell means so much backyard and legacy scenario, I prefer we don't use this name for the project. I mean, if later PowerShell want to use this new API as an SDK, there will have some works and a lot of folks asking for 2k of bugs because they want compatibility. Shell is an app. App is not a shell. I would more happy with "make your own PowerShell".

In 2020, my phone has 6Gb of RAM and the new arm processor of Apple is faster than an Intel i9, so with the 7.2 release, we should be able to use the plugin system and trim legacy dependencies (Win32, Registry, Network, etc..) , if I have a 2MB of SMA.dll (the size of the BCL in Mono.Wasm), the job will be done, it will be easy to embedded in any hardware, OS, dotnet compiled language and browser.
