### ISSUE TITLE
ParameterBindingArgumentTransformationException while attempting to pass an array of class objects to a function

### ISSUE THREAD

**Issue by mmisztal1980** [PowerShell/PowerShell#14250]
## Steps to reproduce

**Module.psm1**
```powershell
class CosmosDbDatabase {
  [string]$Name;
  [bool]$Autoscale;
  [int]$Throughput;

  CosmosDbDatabase() {
  }

  CosmosDbDatabase([string]$Name, [bool]$Autoscale, [string]$Throughput) {
    $this.Name = $Name;
    $this.Autoscale = $Autoscale;
    $this.Throughput = $Throughput;
  }
}

function Invoke-MyFunction() {
  [CmdletBinding()]
  param(
    [Parameter(Mandatory = $True)][CosmosDbDatabase[]]$Databases
  )

 # do stuff inside
}
```

**Script.ps1**
```powershell
using module Module.psm1

Import-Module Module.psm1 -Force;

[hashtable]$arguments = @{
  "Databases" = @(
      # [CosmosDbDatabase]::new("Database1", $true, 4000),
      # [CosmosDbDatabase]::new("Database2", $false, 400)
    (New-Object CosmosDbDatabase -Property @{
      "Name"        = "Database1";
      "Autoscale"   = $true
      "Throughput"  = 4000;
    }),
    (New-Object CosmosDbDatabase -Property @{
      "Name"        = "Database2";
      "Autoscale"   = $false
      "Throughput"  = 400;
    })
  );
};

Invoke-MyFunction @arguments;
```

## Expected behavior

I'm expecting the function to be invoked with all parameters bound successfully, given the fact that I'm using strong typing.

## Actual behavior

I'm getting a ParameterBindingArgumentTransformationException saying
```none
Cannot process argument transformation on parameter 'Databases'. Cannot convert the "CosmosDbDatabase" value of type "CosmosDbDatabase" to type "CosmosDbDatabase".
```

```powershell
Trace-Command -Name ParameterBinding -Expression {Deploy-AzureCosmosDB @arguments} -PSHost;
```

yields

```none
DEBUG: 2020-11-24 18:14:04.4883 ParameterBinding Information: 0 :     BIND arg [System.Object[]] to parameter [Databases]
DEBUG: 2020-11-24 18:14:04.4884 ParameterBinding Information: 0 :         Executing DATA GENERATION metadata: [System.Management.Automation.ArgumentTypeConverterAttribute]
DEBUG: 2020-11-24 18:14:04.4887 ParameterBinding Information: 0 :             ERROR: DATA GENERATION: Cannot convert the "CosmosDbDatabase" value of type "CosmosDbDatabase" to type "CosmosDbDatabase".
```

Apparently I'm attempting to pass a `[System.Object[]]` ? How can I ensure that the type is as expected?
I've checked `Write-Host ($arguments["Databases"].GetType().FullName);` before the invocation of my function and got `[CosmosDbDatabase[]]` in return as expected. Could this be happening during the splatting?

**Callstack**
```
"   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)"
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Oc…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mmisztal1980** [comment]
I've made some progress, but the behavior is still odd...

```powershell
using module Module.psm1

Import-Module Module.psm1 -Force;

[hashtable]$arguments = @{
  "Databases" = @(
      [CosmosDbDatabase]::new("Database1", $true, 4000),
      [CosmosDbDatabase]::new("Database2", $false, 400)
  );
};

Trace-Command -Name ParameterBinding -Expression { Invoke-MyFunction @arguments} -PSHost;
```

yields:

```none
DEBUG: 2020-11-24 20:17:16.4799 ParameterBinding Information: 0 :     BIND arg [CosmosDbDatabase[]] to parameter [Databases]
DEBUG: 2020-11-24 20:17:16.4799 ParameterBinding Information: 0 :         Executing DATA GENERATION metadata: [System.Management.Automation.ArgumentTypeConverterAttribute]
DEBUG: 2020-11-24 20:17:16.4802 ParameterBinding Information: 0 :             ERROR: DATA GENERATION: Cannot convert the "CosmosDbDatabase" value of type "CosmosDbDatabase" to type "CosmosDbDatabase".
```
Is this bind failure expected ?

**Comment by SeeminglyScience** [comment]
Does your example repro the problem for you? I can't get it to error.

Anyway, my guess without repro is that it's related this these lines:

```powershell
using module Module.psm1

Import-Module Module.psm1 -Force
```

Try taking out the `Import-Module` line.  There are some circumstances where you could be creating two instances of the module, importing the types from the first, and importing the commands from the second.  That shouldn't really happen outside of design time though.

**Comment by mmisztal1980** [comment]
@SeeminglyScience I think you've hit the nail in the head. It started to work.

I recall that I've added the `Import-Module` in order to reload changes I've made during development - I don't think the same effect is possible with `using module` - is it?

**Comment by SeeminglyScience** [comment]
@mmisztal1980 Yeah unfortunately you can't.  Even with `Import-Module -Force` it's not super consistent in whether it actually loads the new types.  For now the best workflow is a refresh session.

I do something like this:

```powershell
PS> cd to/project/directory
PS> pwsh # enter nested shell
PS> PS> & ./script.ps1
PS> PS> exit
PS> pwsh # hit up arrow
# repeat
```

**Comment by jazzdelightsme** [comment]
Can we please re-activate this Issue? I came to github today to find-and-upvote or file an Issue for this exact problem. I also believe it's due to the "Import-Module [...] **-Force**" to reload the module. And just like re-executing `Add-Type` for a snippet of C# code that has not changed, reloading a module that uses classes should also continue to work.

This does *not* only come up during development scenarios. For example, I have a module that auto-updates itself, and then instructs the end user to run "Import-Module [...] -Force" to pick up the changes.

**Comment by jazzdelightsme** [comment]
I should also note that key to the repro is touching the file where the class is defined (before re-importing the module). You don't have to change the class definition; just add some whitespace somewhere else in the file. Which makes me think that the logic out there for deciding whether to generate a new runtime type for the class is making its decision based on whether the containing file has changed or not, but could do better by looking at just the extent where the class is defined.

**Comment by jazzdelightsme** [comment]
Here is solid repro code:

```powershell
mkdir Repro_gh_14250 | Out-Null
pushd Repro_gh_14250
New-ModuleManifest -Path .\Repro.psd1 -RootModule Repro.psm1

@'
$script:data = [ordered] @{
    First = @("Primo", 123)
    Second = @("Secundo", 456)
}

class ReproType
{
    [string] $Name
    [int] $Number
}

$TheList = @()
foreach( $key in $script:data.Keys )
{
    $newThing = [ReproType]::new()
    $newThing.Name = $script:data[ $key ][ 0 ]
    $newThing.Number = $script:data[ $key ][ 1 ]

    $TheList += $newThing
}

function Get-TheList
{
    [CmdletBinding()]
    param()

    process { return $TheList }
}
'@ > Stuff1.ps1

@'
function Show-TheList
{
    [CmdletBinding()]
    param( [ReproType[]] $TheItems )

    process
    {
        foreach( $item in $TheItems )
        {
            Write-Host $item.Name -Fore Cyan -NoNewline
            Write-Host ": " -NoNewline
            Write-Host $item.Number -Fore Yellow
        }
    }
}

function Repro
{
    [CmdletBinding()]
    param()

    $stuff = @( Get-TheList )
    Show-TheList $stuff
}
'@ > Stuff2.ps1

@'

. "$PSScriptRoot\Stuff1.ps1"
. "$PSScriptRoot\Stuff2.ps1"

'@ > Repro.psm1

ipmo .\Repro.psd1 -Force
Repro
'# nothing' >> .\Stuff1.ps1
ipmo .\Repro.psd1 -Force
Repro    # EXPECTED: it works. ACTUAL: Cannot process argument transformation on parameter 'TheItems'. Cannot convert the "ReproType" value of type "ReproType" to type "ReproType".
```

**Comment by mmisztal1980** [comment]
@jazzdelightsme what does `Trace-Command -Name ParameterBinding -Expression { Invoke-MyFunction @arguments} -PSHost;` tell you?

**Comment by jazzdelightsme** [comment]
I think it is basically what is expected (given the bug). For my repro code, the trace command should be:

```powershell
Trace-Command -Name ParameterBinding -Expression { Repro } -PSHost
```

The relevant snippet of output:

```none
BIND POSITIONAL cmd line args [Show-TheList]
    BIND arg [System.Object[]] to parameter [TheItems]
        Executing DATA GENERATION metadata: [System.Management.Automation.ArgumentTypeConverterAttribute]
            result returned from DATA GENERATION: System.Object[]
        Binding collection parameter TheItems: argument type [Object[]], parameter type [ReproType[]], collection type Array, element type [ReproType], no coerceElementType
        Arg is IList with 2 elements
        Creating array with element type [ReproType] and 2 elements
        Argument type System.Object[] is IList
        COERCION REQUIRED: Did not attempt to coerce collection element from type ReproType to type ReproType
        BIND arg [System.Object[]] to param [TheItems] SKIPPED
    BIND arg [System.Object[]] to parameter [TheItems]
        Executing DATA GENERATION metadata: [System.Management.Automation.ArgumentTypeConverterAttribute]
            ERROR: DATA GENERATION: Cannot convert the "ReproType" value of type "ReproType" to type "ReproType".
```

**Comment by mmisztal1980** [comment]
@jazzdelightsme I think I know what's going on:

```powershell
$stuff = @( Get-TheList )
```

replace with 

```powershell
$stuff = [ReproType[]]( Get-TheList )
```

And see what `Trace-Command` gives you

**Comment by jazzdelightsme** [comment]
Yes, that makes the "cannot convert" error happen earlier, before parameter binding. But of course it doesn't matter whether I hit the problem during parameter binding or just trying to manually cast; I think it should work.

**Comment by mmisztal1980** [comment]
Thing is the `@` character causes the array to be cast to `[Object[]]` irregardless of types within :)

**Comment by jazzdelightsme** [comment]
With or without the `@`, I get the "cannot convert" error, so I am confused why you bring it up.

**Comment by plastikfan** [comment]
I haven't tested your code sample, but as I'm also developing classes inside modules, I have seen similar confusing errors as you have reported. (I'm actually in the process of trying to find a work-around for a class issue, hence me perusing the PowerShell issues. I noticed this one and thought I should give my 2 pence worth, so just bear with me)

There are some really important notes you should bear in mind when it comes to classes in PowerShell.

1) Unlike functions, once a class is defined in a PS session it can NOT be modified. This is a real problem that I hope the PS team will resolve one day. The only way to fix the issue is to restart your session then re-do your import. But let's say you have some Pester tests that imort the module under development. This will work the first time in one way, but if you modify the c;lass defintion and thn re-run the tests, the class definition will not change and you get errors very similar to the one you have reported and that I have experienced. Restart the session and you should pick up the new class definition. This is a problem because it implies that every time you re-run these tests, you first need to restart the session (which clearly is very onerous on the developer).

2) If the module you are developing is imported in your profile, then if you start making changes to the classes in the module, you will run into the same problem as 1) above except that restarting the session will no longer fix the issue. Remove the import from the sesssion (note there is another VSC specific session file: *Microsoft.VSCode_profile*) and leave the import to the Pester unit test, eg:

```powershell
  BeforeAll {
    InModuleScope ModuleUnderTest {
      Get-Module ModuleUnderTest | Remove-Module -Force
      Import-Module .\Output\ModuleUnderTest\ModuleUnderTest.psm1 `
        -ErrorAction 'stop' -DisableNameChecking
    }
  }
```

3) You need to be very caeful how you structure your powershell code if it contains classes. In your example (*CosmosDbDatabase *), with the function Invoke-MyFunction, this will work ok as long as they reside in the SAME file.

If Invoke-MyFunction is defined inside a different file to CosmosDbDatabase then the line containing the parameter definition:

> [CosmosDbDatabase[]]$Databases

will not work; the type CosmosDbDatabase can't be resolved unless there is a using module <ModuleUnderTest> statement at the top of the file. But a common pattern for constructing powershell modules is to have a build stage that concatenates all sources into the .psm file, which means you can't use the using module technique, unless your build stage has some logic in it to strip out alll using statements before combining them into the psm file,, then injecting the required using statements at the top of the file. (PS: the using statements inside the original source files would stop VSC from reporting errors in the text editor, but need to be injected into the top of the psm file as stated already)

A technique I've had to start using is to create a new module (for the purposes of this discussion, lets call this new class module *CosmosDbDatabaseClass* and the client code which contains Invoke-MyFunction resides in module *CosmosDbDatabaseClient*). (By the way, I am not suggestting you have 1 class per module, that clearly is ridiculous, I'm just explaining the technique). The purpose of CosmosDbDatabaseClass module is to contain only the class definitions and develop this module independently. Then CosmosDbDatabaseClient module has a dependency on CosmosDbDatabaseClass module. With this new arrangemnt in place, now what you can do is have CosmosDbDatabaseClient have a _using module CosmosDbDatabaseClass_ statement in its psm1 file, and you can safely declare variables of type CosmosDbDatabase or CosmosDbDatabase[] ok. This won;t fix the issue of classes not being able to be modified inside the current session, but you can declare variables to be of that class type. I'm not that happy about having to extract out my class code like this, but at least it allows me to use class references easily.

It looks like you and others are aware of the issue of class definition requiring a session restart, but I thought I would contribute, sharing my experience may help to find a way forward. Of course, the best way forward would be for The PS team to fix this class issue once and for all, but I'm sure they would have done so already if it was easy and not breaking existing code. However, because of the real problems of classes in modules, I would hope that the PS team would at some stage make a breaking change, because the status quo is almost intolerable and (arguably it is already in a broken state) needs a resolution to avert extravagent work arounds.

**Comment by SeeminglyScience** [comment]
> 1. Unlike functions, once a class is defined in a PS session it can NOT be modified.

It's a little bit more complicated than that.  They *can* be modified (well sort of, a new type is generated and type resolution is changed to point to the new version) if they weren't imported using `using module X`.  For example, if the class is used purely for internal module logic and not exposed as a public API, `Import-Module X -Force` will work in most cases. The new module session state will point to the new class just like expected.

On the subject of adding a `using module X -Force`, the complication there is that it's a *parse* time concept.  There are a lot of bits in the compiler where the type is currently cached that would need to be invalidated.  That's not impossible, but getting that to work right is a large work item.

Another problem that would need to be solved is subclasses. Lets say you have these files:

```powershell
# ModuleX.psm1
class Foo { }
```

```powershell
# Bar.ps1
using module ModuleX
class Bar : Foo { }
```

```powershell
# Bar2.ps1
using module ModuleX -Force
class Bar2 : Foo { }
```

```powershell
# Main.ps1
. ./Bar.ps1
. ./Bar2.ps1

Update-Module ModuleX
. ./Bar2.ps1
```

After the last line of `Main.ps1`, what does `Bar` inherit now? Is the type recreated because `Bar2.ps1` has `-Force`? Or are they just now incompatible with each other?  What if the new version has breaking changes that `Bar2.ps1` expects, but `Bar.ps1` doesn't?

**Comment by plastikfan** [comment]
Its a shame that these details are not widely known and documented. This article: [About Classes](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_classes?view=powershell-7.1) is woefully deficient and this article [About Using](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_using?view=powershell-7.1) has only a small entry relating to classes.

**Comment by jazzdelightsme** [comment]
@mmisztal1980 Why close this Issue?
