### ISSUE TITLE
meta: Codacy PR review

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#14263]
It appears the Codacy PR review check is no longer running for new PRs.

I wonder whether this is intentional as I don't see any discussion of the change.

**Comment by iSazonov** [comment]
@TravisEz13 Could you please answer?

**Comment by ameliavp** [comment]
Hey! Amélia at Codacy here. Can you please confirm if the project is still in Codacy? We checked and it seems like it's not and that may be the reason why it's not running for new PRs. Thank you! @xtqqczze @iSazonov @TravisEz13

**Comment by xtqqczze** [comment]
@ameliavp The project is at https://app.codacy.com/manual/slee/PowerShell/dashboard

**Comment by ameliavp** [comment]
Thank you @xtqqczze. When looking into it, it's probably because the new checks are not turned on. Can you check this from your side, please? The page we have with this information is very straightforward, I'll leave it here so you can take a look: https://docs.codacy.com/faq/repositories/how-do-i-set-codacy-as-a-required-check-to-merge-prs/ please let me know if this helps, otherwise, I'll make sure to take this issue internally and get back to you. Thank you!

**Comment by iSazonov** [comment]
CodeQL is used now.
