### ISSUE TITLE
Cannot P/Invoke a function named "Process()"

### ISSUE THREAD

**Issue by 035** [PowerShell/PowerShell#14267]
## Steps to reproduce

Define the following function in C and compile as a DLL:
```c
__declspec(dllexport) int Process()
{
    return 42;
}
```

Run the following in PowerShell with the path to the DLL in the DllImport:
```powershell
$type=Add-Type -MemberDefinition @'
[DllImport("C:\\PathToRepro.dll")]
public static extern int Process();
'@ -Name TestProcess -PassThru

$type::Process()
```

## Expected behavior

Function returns `42`.

## Actual behavior

The following error occurs:
`The result type 'System.Int32' of the dynamic binding produced by the object with type 'System.Management.Automation.PSObject' for the binder 'PSInvokeMember: static Process ver:0 args:0 constraints:<>' is not compatible with the result type 'System.Object' expected by the call site.`

Changing the name of the function to something else such as `Process2()` works as expected.

I was not able to reproduce this when using a C# program instead of PowerShell.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.20231
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I guess PowerShell is not designed to call directly native dll-s. I suggest to wrap in C# code.

**Comment by 035** [comment]
From the PowerShell documentation ([link](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/add-type?view=powershell-7.1#parameters)), it sounds like the `-MemberDefinition` parameter should support this. As I mentioned, this error only happens if the function is named `Process`. It appears to work correctly for other function names.

**Comment by iSazonov** [comment]
PowerShell Extended Type System defines extensions for System.Diagnostics.Process type and I guess PowerShell binding catches this. So you could try either wrap in C# code or put the code in _custom_ namespace.

**Comment by 035** [comment]
How do I wrap in C# code? I tried the following, but it gives the same error:
```powershell
$typeDefinition=@"
using System;
using System.Runtime.InteropServices;

namespace Sample{
    public static class SampleClass
    {
        [DllImport("C:\\PathToRepro.dll")]
        public static extern int Process();
    }
}
"@

Add-Type -TypeDefinition $typeDefinition

[Sample.SampleClass]::Process()
```

Setting the `-Namespace` parameter to `Add-Type` does not appear to make a difference either.

**Comment by SeeminglyScience** [comment]
Looks like it's any static method named either `Process`, or `End` (incidentally, not `Begin` because it has a void return) without arguments that returns a value type.

Easier repro:

```powershell
Add-Type -TypeDefinition 'public class Test { public static int Process() => 10; }'
[Test]::Process()
```

I would guess that it's caused by the special casing here:

https://github.com/PowerShell/PowerShell/blob/db94377b3a69511280d329e64375475f6d7513b8/src/System.Management.Automation/engine/runtime/Binding/Binders.cs#L6915-L6927

It's not immediately obvious *how* that's happening, but it sure seems like it is.

/cc @daxian-dbw you might find this interesting.  Looks like the binder is somehow returning `true` here and exiting early, skipping the cast to `object` right afterwards.

**Comment by iSazonov** [comment]
Since no workaround works I set `Issue-Bug`.

**Comment by iSazonov** [comment]
@SeeminglyScience From your example `Begin` should work the same?

**Comment by SeeminglyScience** [comment]
> Since no workaround works I set `Issue-Bug`.

Reflection or an intermediate C# method with a different name can serve as a workaround.  Definitely a bug though.

> @SeeminglyScience From your example `Begin` should work the same?

So because the method `SteppablePipeline.Begin` has a void return, the expression generated will be something like `{ target.Begin(); return null }`. That skips the whole "this call site should return object but doesn't box the int" business.

**Comment by SeeminglyScience** [comment]
Oh also probably a better repro:

```powershell
class Test {
    static [int] Process() {
        return 10
    }
}

[Test]::Process()
```

**Comment by 035** [comment]
Still able to reproduce in PowerShell 7.3.9.
