### ISSUE TITLE
It takes very long time to display prompt for entering commands

### ISSUE THREAD

**Issue by kishanhathiwalaCS** [PowerShell/PowerShell#14266]
After installing v7.0.3 or v7.1.0 or even v7.2.0-preview.1, my powershell (including powershell 5.x) takes very long time to display prompt for entering commands. Powershell 5.x comes back to normal after I uninstall powershell v7.x and restart the system.

**Comment by hathiwala** [comment]
The same thing happens after I open terminal in Visual Studio,
![image](https://user-images.githubusercontent.com/60079091/100292365-617baf00-2fd4-11eb-96fb-f8ef5ad2c81f.png)

My powershell 
![image](https://user-images.githubusercontent.com/60079091/100292424-8839e580-2fd4-11eb-86b4-f526f17d0e41.png)

**Comment by iSazonov** [comment]
Try run pwsh -NoProfile

**Comment by hathiwala** [comment]
Waiting 

> Try run pwsh -NoProfile

I did run that but the result was same. 

Although it's not happening any more. I am not sure why?

**Comment by iSazonov** [comment]
We need repro steps to investigate an issue.

**Comment by mklement0** [comment]
Anecdotally I can confirm that the startup of the very first session - only - after an installation takes much longer (haven't paid attention to how that interacts with Windows PowerShell).

**Comment by iSazonov** [comment]
> Anecdotally I can confirm that the startup of the very first session - only - after an installation takes much longer (haven't paid attention to how that interacts with Windows PowerShell).

If you say about Windows I guess pwsh creates explorer menu items at first run time. It could be moved to install time...

**Comment by doctordns** [comment]
Is the code for all those .NET assemblies which PWSH loads on startup in IL, or have they been precompiled somehow into native code. There appears to be no GAC as such for the .NET 5 assemblies.

**Comment by iSazonov** [comment]
@doctordns We benefit from ReadyToRun (R2R) - all assemblies is crossgened.

**Comment by kilasuit** [comment]
> Anecdotally I can confirm that the startup of the very first session - only - after an installation takes much longer (haven't paid attention to how that interacts with Windows PowerShell).

This is Expected behaviour due to the building of the ModuleAnalysisCache which powers Get-Command/Get-Help/Get-Module which is always slow on the first run post install & has been the same since PowerShell 5.1 when they rejigged the ModuleAnalysisCache as part of the 5.1 release

**Comment by Silex** [comment]
I have the same issue, and it's happening all the time.

Running `pwsh -NoProfile` does not change anything. It takes around 8-10 seconds for the prompt to come.

When using `-Command` the result is display instantly.

Here's what happen with normal use:

```
PS C:\Users\foo> pwsh
PowerShell 7.1.0
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\ext-adm-pva> 2+2                                # Previous text was displayed instantly, prompt took ~10 seconds to come
4
```

This PC is inside an organisation that has heavy policies and network restrictions, so it's probably because of this.

How can I debug this further? IMHO it's clearly PSReadline that takes a while to arrive.

**Comment by Silex** [comment]
I have the same issue, and it's happening all the time.

Running `pwsh -NoProfile` does not change anything. It takes around 8-10 seconds for the prompt to come.

When using `-Command` the result is display instantly.

Here's what happen with normal use:

```
PS C:\Users\foo> pwsh
PowerShell 7.1.0
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\foo> 2+2       # Previous text was displayed instantly, prompt took ~10 seconds to come
4
```

This PC is inside an organisation that has heavy policies and network restrictions, so it's probably because of this.

How can I debug this further? IMHO it's clearly PSReadline that takes a while to arrive.

**Comment by iSazonov** [comment]
@Silex If you think it is PSRL you can run without it by `pwsh -NoInteractive`.

**Comment by Silex** [comment]
@iSazonov: yes, using `pwsh -NonInteractive` works instantly.

What should I do to debug this further?

**Comment by iSazonov** [comment]
@Silex Please open new issue in [PSReadline ](https://github.com/PowerShell/PSReadLine) repository and @daxian-dbw would work with you.
I'd suggest you to use Wireshark to collect network traffic and investigate DNS issues.
