### ISSUE TITLE
silent failure pwsh -c "{hi"

### ISSUE THREAD

**Issue by felix9** [PowerShell/PowerShell#14284]
## Steps to reproduce

```
PS> pwsh -c '{hi'
PS> pwsh -c '}hi'
ParserError:
Line |
   1 |  }hi
     |  ~
     | Unexpected token '}' in expression or statement.
PS>
```

## Expected behavior

I expect both pwsh invocations to report an error.

## Actual behavior

The first pwsh invocation exits with failure status but doesn't report any error.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by doctordns** [comment]
Try:
```powershell
pwsh -c "'}hi'"
```

**Comment by mklement0** [comment]
@doctordns, I think that @felix9's concern is that a syntax error is being quietly ignored.

@iSazonov, without looking at the source code all I can say is that this bug surfaces only via the CLI - `Invoke-Expression '{hi'` and  `[powershell]::Create().AddScript('{hi').Invoke()` both report the syntax error, as expected.

**Comment by iSazonov** [comment]
@mklement0 I guess it is a command line escaping or quotation marks, no?

**Comment by mklement0** [comment]
@iSazonov, no, it's not related to quoting (argument parsing); what the CLI sees verbatim as the `-c` argument after argument parsing in this case is `{hi`, which it parses and executes as PowerShell code, which should therefore result in a syntax (parser) error, just like with`Invoke-Expression '{hi'`

As @felix9's counter example in the OP implies, the problem must be related to parsing something _as a  script block_, given that something that doesn't look like a script block, such as `pwsh -c '}hi'`, properly reports a syntax error.

---

Pragmatically speaking, something like `pwsh -c '{get-date}'` doesn't make sense, because the script block is merely _created_, not _executed_, causing its verbatim contents to be merely _echoed_, but the problem also occurs when you prepend `& ` to effect execution:

```powershell
# Equally broken: also fails silently
pwsh -c '& {get-date'
```

As an aside: Of course, even `pwsh -c '& {get-date}'` is unnecessary, given that there's never a need to construct a script block explicitly, given that the whole `-c` argument is _implicitly_ a script block (`pwsh -c 'get-date'` will do).
