### ISSUE TITLE
Process got stopped when running in background

### ISSUE THREAD

**Issue by dingmeng-xue** [PowerShell/PowerShell#14339]
Issue is copied from https://github.com/Azure/azure-powershell/issues/13652

I am using powershell+ADL in ubuntu, there are multiple pwsh commands in my bash script. When running this script in foreground, no problem. All these commands got executed correctly. But if running this bash script in background like "bash script.sh &", after finishing the first pwsh command, process automatically got stopped. You have to use foreground running to finish all of them.

## Steps to reproduce

```
# cat pwsh.sh
pwsh -Command "Get-Module  -ListAvailable"
pwsh -Command "Get-Module  -ListAvailable"
pwsh -Command "Get-Module  -ListAvailable"
pwsh -Command "Get-Module  -ListAvailable"

# bash pwsh.sh > pwsh.log 2>&1 &
```

You will see only the first line executed, then process automatically got stopped.

```
# jobs
[1]+  Stopped                 bash pwsh.sh > pwsh.log 2>&1
```

## Expected behavior

Pwsh should be executed according to script in Bash

```none

```

## Actual behavior

You will see only the first line executed, then process automatically got stopped.

```none

```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Linux 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by hoodedfoxtailz** [comment]
Its a manager

**Comment by SteveL-MSFT** [comment]
This doesn't repro on macOS, but on Linux, it appears that background processes will automatically be stopped if it attempts to read from stdin.  Workaround for now is:

```sh
pwsh -command "Get-Module -ListAvailable" < /dev/null
```

The input redirection will effectively close stdin, so the process won't be stopped.  It appears that Linux will send a SIGTTIN signal to the process if it tries to read from the console, but is not in the foreground.  However, pwsh doesn't handle signals (because .NET doesn't expose it).  Related to https://github.com/PowerShell/PowerShell/issues/11215
