### ISSUE TITLE
Invoke-DscResource fail to update a service

### ISSUE THREAD

**Issue by rifftual** [PowerShell/PowerShell#14370]
## Steps to reproduce
```powershell
Invoke-DscResource -Name Service -Method Set -Property @{Ensure = 'Present'; Name = 'foo'; StartupType = 'Disabled'; State = 'Stopped'; Path = 'C:\foo.exe' } -ModuleName PSDesiredStateConfiguration
```

## Expected behavior

The service would be updated idempotically.

## Actual behavior

```none
PowerShell DSC resource MSFT_ServiceResource  failed to execute Set-TargetResource functionality with error message:
The service 'foo' to create already exists with path 'C:\foo.exe'
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
```

## Environment data

```none
PSVersion                      5.1.17763.1490
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1490
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by gaelcolas** [comment]
This one should be closed, as I just replied in the other issue:

You misunderstood my point, you should probably be using `PSDscResources` or better, `xPSDesiredStateConfiguration` module.

The built-in resources are not updated.
The `PsDscResources` module can be fixed in some cases but does not accept non-critical changes.

The Community-maintained `xPSDesiredStateConfiguration` module is the most up to date, and probably the best for you to use.
https://github.com/dsccommunity/xPSDesiredStateConfiguration/
