### ISSUE TITLE
pwsh.exe executable does not work in Windows Task Scheduler

### ISSUE THREAD

**Issue by erenturkm** [PowerShell/PowerShell#14477]
Hi,

I was using powershell.exe for my current script  in task scheduler without problems. I installed Powershell 7.1 through Microsoft Store and when I look at add/remove files I see it as installed. When I changed the program/script to pwsh.exe I started getting file not found errors, reading issue #13302, I thought it was the path that was the problem. When I run where pwsh.exe I get 2 paths:
```
1) C:\Program Files\WindowsApps\Microsoft.PowerShell_7.1.0.0_x64__8wekyb3d8bbwe\pwsh.exe
2) C:\Users\user1\AppData\Local\Microsoft\WindowsApps\pwsh.exe
```
Looking at user1's Path, I see no 2, which provides why it runs interactively. Looking at system path, none are listed, which is why task scheduler fails. I am not clear on how to solve this. if I enter no 1 in system's path, whenever application is automatically upgraded, it will become invalid and script will fail. if I enter no 2, it depends on user1 being available which I think is the best approach. 

Could somebody propose the best action here?

## Environment data

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
```none

```

**Comment by jborean93** [comment]
It seems like you have installed PowerShell through the Windows store and while the true executable is at `C:\Program Files\WindowsApps\Microsoft.PowerShell_7.1.0.0_x64__8wekyb3d8bbwe\pwsh.exe` there's a lot of stuff that goes on in the background here.

The folder `C:\Program files\WindowsApps` is a special folder that restricts the users that can open it up and enumerate the contents and execute things

![image](https://user-images.githubusercontent.com/8462645/102823241-4b6fdb80-4426-11eb-8f50-ea4830235379.png)

You can see that Administrators can only list the contents and only a subset of others can read/execute. The `Users` groud does have this right but only when that particular condition is met. To deal with this, Windows creates an AppExecLink in `C:\Users\<username>\AppData\Local\Microsoft\WindowsApps` which points to the relevant executable in `C:\Program Files\Windows\Apps\<app id>`. Because the `WindowsApps` in your useer's appdata path is in the PATH for that user when they call `pwsh.exe` Windows will pick up that AppExecLink do some trickery with your logon token so the `WIN://SYSAPPID` condition can now be met and it's able to open `pwsh` in `C:\Program Files`. This is a reason why Windows Store apps must be installed per user account as opening programs like this must be done through that AppExecLink which is stored in the user's profile.

So when running it as a scheduled task then it should be running as the account the Windows Store/appx pwsh was installed to. If you are wanting to run as SYSTEM you could potentially hard code the full path to `pwsh.exe` in `C:\Program Files\WIndowsApps` but that would mean you need to update your path everytime it is updated. You might even be able to install the appx in the context of the SYSTEM account using something like psexec but I honestly wouldn't be surprised if that doesn't work. You could also just install it like a normal msi and have it work like `powershell.exe`.

**Comment by doctordns** [comment]
Why not just use the Install-PowerShell script on GitHub and either install it with the MSI, or into the folder you want. That avoids all the store stuff.

**Comment by erenturkm** [comment]
Basicly what you are saying, If you want to use PS 7.x from Microsoft store (that automatically upgrades itself) you can't use it from Task Scheduler. <sigh> back to chocolatey then.

**Comment by doctordns** [comment]
That is a remarkably silly conclusion in my view. 

I have Pwsh 7.1 installed on a bunch of domain servers and all can use it just fine even with task scheduler. Try using the **Install-PowerShell** script on GitHub. Get it at https://github.com/PowerShell/PowerShell/blob/master/tools/install-powershell.ps1.

IMHO, the store is for consumer apps - not serious domain tools. If you want to manage a domain, install it from the real source. Chocolately is a non-supported repository. If support matters, use a more supported approach.

**Comment by erenturkm** [comment]
Thomas,

I respect your opinion but marking sombody's opinion as silly, not grown up is not professional and should not be part of this forum, especially not knowing the specifics of their environment, and the problems they are trying to solve. Contribute only if it benefits this community.

The real problem here is how to keep Powershell updated which is a systems management problem not an installation problem. @jborean93's answer is elaborate but does not resolve this issue.  I am sure you know pretty well that if you are managing a domain you would never use the mentioned URL to update your 100's of servers/clients individually. Installing it from the Microsoft store for business or using a system management tool such as chocolatey are two different ways to solve this. Above answer is important as it highlights a pitfall for Office365 users who want to leverage Microsoft store app for their system management.

**Comment by HotCakeX** [comment]
> The real problem here is how to keep Powershell updated 

Hi,
it gets automatically updated with Microsoft update now.

![image](https://user-images.githubusercontent.com/118815227/211047279-4e78aac6-9a62-4833-92dd-0c119118d306.png)


p.s A Windows update is specifically for the Windows OS and drivers. Whereas a Microsoft Update is for more Microsoft products and apps like Office and others, in this case, PowerShell too.

**Comment by doctordns** [comment]
One small issue using WU. If you are using a LTS version  (eg 7.2.x), WU does not update your version to a 7.3.x release.  A small thing but you can work around it if necessary.
