### ISSUE TITLE
Array changes when object taken from array gets changed

### ISSUE THREAD

**Issue by Ba4bes** [PowerShell/PowerShell#14474]
Not sure if this is a bug or if I just don't understand the behavior:
You start with an array with objects in them.
You assign a variable for one of these objects.
When you change that object, the original array is changed as well.

## Steps to reproduce

Example1:
```powershell
# Set up an array with two objects in it
$SourceArray = @(
    [PSCustomObject]@{
        Name = "Value1"
        property1 = "blieb"
        property2 = "blaab"
        property3 = "bloeb"
    }
    [PSCustomObject]@{
        Name = "Value2"
        property1 = "blieb"
        property2 = "blaab"
        property3 = "bloeb"
    }
)

# Create a variable based on an object in the array
$IssueObject = $SourceArray[0]
# Add a member to the object
$IssueObject | Add-Member -MemberType NoteProperty -Name "ExtraProperty" -Value "blaib" -Force
# So we have the object with an extra property
$IssueObject

# Now if we call the same object from the source array,
# I wouldn't expect an extra member, as I created a new variable for the changed object
$sourcearray[0]
# Turns out the object in the variable has changed as well??


# Looking further: Let's create the variable again but add | select-object *
$IssueObject = $sourcearray[1]  | Select-Object *
# Do the same thing as before
$IssueObject | Add-Member -MemberType NoteProperty -Name "ExtraProperty" -Value "blaib" -Force
$IssueObject 

# Call the object form the array again
$SourceArray[1]
# And results are as expected: without the extra member.
```

Example2 (run as admin to reproduce):
```powershell

# Collect all the services in an array
$Services = Get-Service

# Collect the status of the time service
$Services | Where-Object {$_.Name -eq "W32Time"}

# Save the Time service in a new variable
$Time = $Services | Where-Object {$_.Name -eq "W32Time"}

# Start the time service (or stop if it was already started)
$Time | Start-Service

# The time service is now running. But I did not touch the Services variable.
# So I would expect the status in the Services Variable to still be Stopped.
# But it now comes back as running...
$Services | Where-Object {$_.Name -eq "W32Time"}

```

## Expected behavior

I would expect the array to change when I define a new variable to work with. I would also not expect a difference when Select-Object is used.

## Actual behavior

![image](https://user-images.githubusercontent.com/43912004/102776314-d0a7b180-438e-11eb-88fc-6f712246702b.png)

## Environment data
Tested on multiple devices (all Windows), on PowerShell 7.1.0, 7.2.0 as well as Windows PowerShell

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.2
PSEdition                      Core
GitCommitId                    7.2.0-preview.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
In short: The behavior is by design.

Also, unless you're reasonably sure that you've found a problem with PowerShell itself, please don't post here and use one of the following resources instead, at least until you're sure you've found an actual problem: 

* The [Slack](https://join.slack.com/t/powershell/shared_invite/enQtMzA3MDcxNTM5MTkxLTBmMWIyNzhkYzVjNGRiOTgxZmFlN2E0ZmVmOWU5NDczNTY2NDFhZjFlZTM1MTZiMWIzZDcwMGYzNjQ3YTRkNWM) and [Discord](https://discordapp.com/invite/AtzXnJM) community chat forums (they seamless talk to each other).
 
* Q&A site [StackOverflow.com](https://stackoverflow.com/questions/tagged/powershell) and the [PowerShell.org](https://powershell.org/forums/) forum for searching or posting questions about PowerShell.

---

Re example 1:

* After assignment `$IssueObject = $SourceArray[0]`, both `$IssueObject` and `$SourceArray[0]` by design point to the very same `[pscustomobject]` instance.

* Creating a new variable is not the same as creating a _copy_ of the RHS value - that only applies to .NET _value types_, whereas `[pscustomobject]` is an instance of a _reference type_.
   * See [this Stack Overflow answer](https://stackoverflow.com/a/45071111/45375) for more information.

* To create a (shallow) copy of a `[pscustomobject]` instance, call its `.psobject.Copy()` method.

* `Select-Object`, when used with `-Property` (positionally implied) always creates a _new_ (`[pscustomobject]`) instance (except if `-ExpandProperty` is passed), but note that `Select-Object *` with an `[pscustomobject]` input isn't always the same as calling `.psobject.Copy()` on that input, because only _properties_ are copied; also, the new object reports its type name as `Selected.System.Management.Automation.PSCustomObject`.

Note that both methods of copying properties create _shallow_ copies, which means the property values are copied as-is, so that again you get _data copies_ for value-type instances and _reference copies_ for reference-type instances.

There is no general mechanism for _deep_ copying (cloning), though individual types may implement one.

Re example 2:

What `Get-Service` outputs are so-called _live objects_ (of type [`System.ServiceProcess.ServiceController`](https://docs.microsoft.com/en-US/dotnet/api/System.ServiceProcess.ServiceController)) . 
That is, their properties reflect the _current state_ of the resource being pointed to instead of taking a _snapshot_ of the state.

It is up to each type to implement one behavior or the other, and this aspect is independent of the question of when a copy of the actual data vs. a reference to the same object is created.

An easy way to get a snapshot of a service-info object is to use `Select-Object *` to create a `[pscustomobject]` whose properties then contain _static_ copies of those properties in the original that are _calculated properties_ (properties whose value is determined dynamically, on very access) - but note that for non-calculated properties whose values happen to be instance of reference types you'll again get copies of the _references_.

**Comment by alexandair** [comment]
@mklement0 This is a perfect place to ask this kind of question. If you don't like, ignore it. Please, it's not on you to tell anyone to post somewhere else.

**Comment by mklement0** [comment]
@alexandair:

* It isn't the perfect place to ask such questions, for the reasons stated - and as also reflected in the types of issue templates offered when you create an issue (bug reports, feature request, ...).

* Someone who has questions such as this one is far better served by asking them in the communities that I linked - the likelihood of getting a satisfying answer is much greater there (even though in this particular case I (hopefully) happen to have provided one here).

Or did I miss a decision to turn this into a general-purpose PowerShell support forum?

I don't think so, but even if I did, I think that would be a mistake, as it would generate far too much noise for a repository focused on fixing bugs and developing new features.

As a community, we should have clarity on what does and doesn't belong here - unfortunately, the bug-report template doesn't do a good job of communicating that - despite having a very obvious _name_: _bug report_.

The very opening statement of this issue, "Not sure if this is a bug or if I just don't understand the behavior" is an indication that _conceptual clarity should be sought first_ before reporting something as a bug, and sites like Stack Overflow are the perfect place for that.

You seem to think of this as _dismissing_ the OP, I think of it as _helpful guidance_.

Unless I hear convincing arguments to the contrary or see an official decision that general support questions are now acceptable, I will continue to provide this type of guidance.

Unless you want to engage in an actual _discussion_ of the issue, I suggest you take your own advice: "if you don't like, ignore it".

**Comment by SeeminglyScience** [comment]
> * It isn't the perfect place to ask such questions, for the reasons stated - and as also reflected in the types of issue templates offered when you create an issue (bug reports, feature request, ...).

That's more for "how do I do X". OP thought they found might have found a bug, that's good enough here. Won't be many folks reporting bugs if we require them to know for certain it's actually a bug before posting.

> You seem to think of this as _dismissing_ the OP, I think of it as _helpful guidance_.

I'm sure you didn't intend it to, but your original reply does read a bit like you're annoyed.  Even if you are, leaving that in usually just incites defensive replies. Also if you're going to answer anyway there's not a whole lot of point in mentioning it.

**Comment by mklement0** [comment]
> Also if you're going to answer anyway there's not a whole lot of point in mentioning it.

The point is to extend a courtesy _this time_ - given that the issue has already been posted - as well as to provide guidance _for the future_.

> I'm sure you didn't intend it to, but your original reply does read a bit like you're annoyed.

Indeed I didn't intend to, and I can't take responsibility for that interpretation: It needed saying (see below) and it provided helpful information (unless you disagree that the places I linked to are good places for asking such questions).

> OP thought they found might have found a bug

That's a _formal_ criterion that is too easily satisfied.

While there are ultimately no hard and fast rules, the _specific nature_ of this issue suggests an unfamiliarity with fundamental .NET concepts, and I hope we can agree that:

* This isn't the place to teach them.
* Issues of this type could end up _ignored_ here, for that reason ...
* ... unlike on platforms such as Stack Overflow - hence the recommendation to ask there.

**Comment by SeeminglyScience** [comment]
> Indeed I didn't intend to, and I can't take responsibility for that interpretation: It needed saying (see below) and it provided helpful information (unless you disagree that the places I linked to are good places for asking such questions).

We're all responsible for how we're interpreted.  Unless you're specifically looking for conflict, putting some effort into less aggressive wording would be advisable.

> That's a _formal_ criterion that is too easily satisfied.

And that's great!

> While there are ultimately no hard and fast rules, the _specific nature_ of this issue suggests an unfamiliarity with fundamental .NET concepts, and I hope we can agree that:

That's right, like the vast majority of the PowerShell community. Bug reporting shouldn't be gate kept, it's already hard enough to get folks to report things.

**Comment by mklement0** [comment]
>  We're all responsible for how we're interpreted. 

Only to a degree. If someone wants to take offense, they will.

> putting some effort into less aggressive wording would be advisable.

Commendable, and certainly something I strive for in general.

Re-reading my comment, I could have done better in this case.
I can only hope that my having taken the time to answer the question with care (as a one-time courtesy) served to indicate that I was well-intentioned.

>  And that's great!
>  shouldn't be gate kept,

It isn't great, and mistaking _proper guidance_  for gate-keeping is unfortunate.

What I think would be helpful, _to everyone involved_, is to communicate the following clearly, as part of the bug-report template (an earlier version had more of that, but it was taken out):

---

* If you're seeing behavior that deviates from the intended behavior, as documented, report it here.
 
* If you're not sure what the intended behavior is or you have questions about PowerShell in general, please seek help from the community via the following forums:
  * The [Slack](https://join.slack.com/t/powershell/shared_invite/enQtMzA3MDcxNTM5MTkxLTBmMWIyNzhkYzVjNGRiOTgxZmFlN2E0ZmVmOWU5NDczNTY2NDFhZjFlZTM1MTZiMWIzZDcwMGYzNjQ3YTRkNWM) and [Discord](https://discordapp.com/invite/AtzXnJM) community chat forums (they seamless talk to each other).
 
  * Q&A site [StackOverflow.com](https://stackoverflow.com/questions/tagged/powershell) and the [PowerShell.org](https://powershell.org/forums/) forum for searching or posting questions about PowerShell.

**Comment by Ba4bes** [comment]
Ok, few responses:

- The explanation and provided link is very clear, thank you for that.
- The recommendation did feel a bit reprimanding and I'm glad that was cleared up.
- I posted here as I thought this could be a bug, or at least unwanted behavior. I personally find this very counter-intuitive. The two examples here came from two different people who were as confused as I was. So even if it isn't a bug, I thought it was useful to be mentioned here as behavior that raises questions.

As my wondering has been cleared up I will close this issue, thank you all for your responses

**Comment by mklement0** [comment]
Thanks for the feedback, @Ba4bes - point re feeling reprimanded taken; glad to hear the information was helpful.

As for providing better guidance via the bug-report template: I've created a PR at https://github.com/PowerShell/PowerShell/pull/14479.

**Comment by SteveL-MSFT** [comment]
I agree with @SeeminglyScience that OP posted what they thought was unexpected behavior, so open an issue (if one doesn't already exist) is the right thing.  I appreciate @mklement0 responding with correct information and pointers.  In general, we are considering enabling GitHub Discussions for general type of discussions not specific to the code of this project, but we won't get to that til next year.

On the internet where all you see is text and no body language, sometimes one may presume the worst, but many times I find that was not the intent (which is clear in this case by @mklement0's response later in the thread).  Overall, it looks like everything worked out and I appreciate the discussion.
