### ISSUE TITLE
New OlderThan and NewerThan parameters for Get-ChildItem cmdlet

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#14496]
## Summary of the new feature/enhancement

Today, to find elements of the file system older than (or newer than) the specified date, we are forced to do something like
```powershell
$Path = "C:\temp"
$Daysback = "-30"
 
$CurrentDate = Get-Date
$DateOlderThan = $CurrentDate.AddDays($Daysback)
Get-ChildItem $Path -Recurse ( | Where-Object { $_.LastWriteTime -lt $DateOlderThan }
```

At the same time, Test-Path cmdlet supports the parameters `-OlderThan <datetime>` and `-NewerThan <datetime>`

### Proposal

Add `-OlderThan <datetime>` and `-NewerThan <datetime>` parameters to `Get-ChildItem` cmdlet of the FileSystem provider.

As result we get more short form and more fast and efficient filtering without extra file object retrieving and piping.

```powershell
$Path = "C:\temp"
$Daysback = "-30"
 
$CurrentDate = Get-Date
$DateOlderThan = $CurrentDate.AddDays($Daysback)
Get-ChildItem $Path -Recurse -OlderThan $DateOlderThan
```

## Proposed technical implementation details (optional)

Example of the parameters definition https://github.com/PowerShell/PowerShell/blob/281b437a65360ae869d40f3766a1f2bbba786e5e/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L7805

Place for new parameters https://github.com/PowerShell/PowerShell/blob/281b437a65360ae869d40f3766a1f2bbba786e5e/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L7531

Place for injection new filtering code (for Recurse parameter) https://github.com/PowerShell/PowerShell/blob/281b437a65360ae869d40f3766a1f2bbba786e5e/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L1779

**Comment by iRon7** [comment]
You might also consider to accept (besides a `DateTime` type) a `TimeSpan` type:

```PowerShell
$Path = 'C:\temp'
$Daysback = New-TimeSpan -Days -30

Get-ChildItem $Path -Recurse -OlderThan $Daysback
```

**Comment by iSazonov** [comment]
> You might also consider to accept (besides a `DateTime` type) a `TimeSpan` type:

We could have this but with other parameter names.

**Comment by lukeb1961** [comment]
VMS had a great set of options for commands like DIR where you could say /Since=YESTERDAY or /Since=THURSDAY or /Since=<TIME>, /SINCE=BOOT, /SINCE=BACKUP, /SINCE=LOGIN, etc.  I used to find them immensely useful and Powershell really fails in this area. I would love to see this  <Timespan> problem addressed.

**Comment by iSazonov** [comment]
> VMS had a great set of options for commands like DIR where you could say /Since=YESTERDAY

I believe it is for discussion in #12305. After we get a conclusion in #12305 we could add a transformation attribute to OlderThan and NewerThan parameters.

**Comment by thecliguy** [comment]
Is the proposal that `-OlderThan` and `-NewerThan` would be hardwired to operate against `LastWriteTime` or could they also be used against `CreationTime` and `LastAccessTime`?

**Comment by iSazonov** [comment]
> Is the proposal that `-OlderThan` and `-NewerThan` would be hardwired to operate against `LastWriteTime` or could they also be used against `CreationTime` and `LastAccessTime`?

The proposal is for `LastWriteTime`. For `CreationTime` and `LastAccessTime` we could consider another "switch" parameter or do you have another idea?

**Comment by thecliguy** [comment]
A switch parameter sounds fine.

Regarding the parameter names `-OlderThan` and `-NewerThan`, they are somewhat ambiguous... It's not totally obvious whether a comparison is performed against `LastWriteTime` or `CreationTime`.

The [documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-path?view=powershell-7.1) of these parameters in relation to `Test-Path` is currently very poor:

```
-NewerThan

Specify a time as a DateTime object.
```

```
-OlderThan

Specify a time as a DateTime object.
```

So whatever the final implementation of these new parameters is, it would be great if  there's some meaningful documentation to accompany them.

**Comment by TobiasPSP** [comment]
The cmdlet WG has thoroughly discussed this suggestion and came to this conclusion:
From a performance perspective, there is "server" and "client" side filtering. Currently, the way `Get-ChildItem` uses the API, filtering by age cannot be done "server side" in a way that we'd see performance benefits. So adding date and time filters would be for convenience reasons only. 


Since `Get-ChildItem` is a very generic cmdlet and does not work with just the filesystem provider but can also return completely different data, filter parameters would either need to be dynamic (applicable only when the filesystem provider is used), or require implementations for different providers and adjustments for the data they deliver.


This leads to a more generic challenge: date and time filtering may be a frequently requested operation, yet users may want to filter for modification, creation, or access, and they may want to do this using local time or UTC time, and they may want to filter based on various timespan units like hours or days. So providing adequate filters in a generic and descriptive way is complex and in the end may feel arbitrary.


Generic client-side filter using `Where-Object` still seems to be the most flexible and descriptive approach. At the same time, `Where-Object` is fairly simple to use (works like SQL) while at the same time highly adjustable and self-descriptive:


```powershell
Get-ChildItem -Path $env:windir -Filter *.log  -Recurse -ErrorAction Ignore | 
  Where-Object CreationTime -gt (Get-Date).AddHours(-12)`
```

The cmdlet WG decided to close this issue for now. Should the API implementation of `Get-ChildItem` at some point allow substantial performance benefits using "server side" filtering, we are open to revisiting this idea.
