### ISSUE TITLE
PSSession return local environment variable, not remote variable

### ISSUE THREAD

**Issue by fredliex** [PowerShell/PowerShell#14511]
I have two server, server1 and server2.
I invoke command on server1 and want to get machine environment on server2 by remoting. 
ex: `[Environment]::GetEnvironmentVariable("path", "machine")`
but return the environment variable on server1.

I changed `GetEnvironmentVariable` to `MachineName` and had the same problem.

## Steps to reproduce

```powershell
PS C:\Users\abc>Enter-PSSession server2
[server2]: PS C:\Users\abc\Documents> [Environment]::MachineName
[server2]: PS C:\Users\abc\Documents> Write-Output ([Environment]::MachineName)
[server2]: PS C:\Users\abc\Documents> $env:COMPUTERNAME
[server2]: PS C:\Users\abc\Documents> Write-Output ($env:COMPUTERNAME)
[server2]: PS C:\Users\abc\Documents> Write-Output ([Environment]::MachineName + "," + $env:COMPUTERNAME)
```

## Expected behavior

```powershell
server2
server2
server2
server2
server2,server2
```

## Actual behavior

```powershell
server2
server1      # <-- diff here, Write-Host ([Environment]::MachineName)
server2
server2
server2,server2
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
It's not the environment _variable_ doing it, it's  write-* with [environment]

```
>  $s = New-PSSession -ComputerName localhost -EnableNetworkAccess -ConfigurationName microsoft.powershell32
>  Enter-PSSession -Session $s

> ([environment]::Is64BitProcess)
False
> write-verbose -Verbose ([environment]::Is64BitProcess)
VERBOSE: True

> [environment]::Version

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      30319  42000

> write-output ([environment]::Version)

Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      0      -1
```

**Comment by fredliex** [comment]
I'm confused,
Is this by design or is it a bug?
If it is designed, are there any documents or information to read?

thanks

**Comment by jhoneill** [comment]
IT seems some sort of short-circuit evaluation happens for  `Write-` commands in remote sessions. **could someone with deeper knowledge of the internals comment whether this is by design.**  

```
>  $s = New-PSSession -ComputerName localhost -EnableNetworkAccess -ConfigurationName microsoft.powershell32
>  Enter-PSSession -Session $s
> ([environment]::Is64BitProcess)
False
> write-output ([environment]::Is64BitProcess)
True
> write-output ([environment]::Is64BitProcess) > deleteme
> type deleteme
False
```
If it needs to write to a file, the value comes from the remote session, 

```
> write-output ("$PID " + [environment]::Is64BitProcess )
20576 False
> write-output (" " + [environment]::Is64BitProcess )
 True
```
If it adds a _variable_ the expression is evaluated remotely session, but if it adds a string _constant_ the value comes from the parent session.  

To work around this you can put the value in a variable before outputting it. 

```
> $x = [environment]::Is64BitProcess
> write-output $x
False
```

**Comment by vexx32** [comment]
cc @PaulHigin

**Comment by PaulHigin** [comment]
This is actually by design for `Enter-PSSession`.  The argument for `Write-Output ([Environment]::MachineName)` is evaluated on the client. The evaluated argument ("server1") is then packaged with `Write-Output` and sent to the remote session to execute there.

`$x = [Environment]::MachineName; Write-Output $x` evaluates `[Environment]::MachineName` on the remote session and stores it in a variable in that session, so it provides the expected result.

Admittedly this is strange behavior on the interactive command line, but unfortunately is just the way that PowerShell parses and executes remote commands.

Some workarounds are:
```powershell
[server2]: PS > [System.Environment]::MachineName
[server2]: PS > [System.Environment]::MachineName | Write-Output
[server2]: PS > "$(Write-Output ([System.Environment]::MachineName))"
```

**Comment by SeeminglyScience** [comment]
@PaulHigin Out of curiosity, would you happen to know off the top of your head where to look for the code behind this behavior?

**Comment by vexx32** [comment]
Also, I think Patrick was looking at it earlier and the behaviour seems to persist for Invoke-Command which is... problematic at _best_, surely?

**Comment by SeeminglyScience** [comment]
> Also, I think Patrick was looking at it earlier and the behaviour seems to persist for Invoke-Command

Yeah seems to work the same way.

> which is... problematic at _best_, surely?

I'd be interested to hear the reasons behind the design in general.  I'm inclined to say it might be worth a breaking change to modify the behavior unless there are some particularly strong use cases.

I'm pretty sure this is the source of some distrust in various .NET API's.  Like for example I knew at one point early on that `Environment.Is64BitProcess` and `OperatingSystem` gave inconsistent results but I didn't understand why until now.

**Comment by PaulHigin** [comment]
The argument is evaluated in the ScriptBlockToPowerShellConverter, while packaging the command to be sent over to the remote session.

https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs#L678

I think it would be a pretty big breaking change, but I'll mark this for committee review.

**Comment by SeeminglyScience** [comment]
> The argument is evaluated in the ScriptBlockToPowerShellConverter, while packaging the command to be sent over to the remote session.

OHHHHHH okay that all makes sense now.  To clarify, when you say it's by design do you mean that the behavior itself was considered desirable at the time or was it more of a technical limitation/implementation detail?

---

Some more examples that will force invocation on the remote machine:

```powershell
$s = New-PSSession -ComputerName localhost -ConfigurationName microsoft.powershell32

# Invokes property getter locally (returns True).
icm -Session $s { echo ([Environment]::Is64BitProcess) }

# These force invocation in remote session (returns False).
icm -Session $s { ''; echo ([Environment]::Is64BitProcess) }
icm -Session $s { (echo ([Environment]::Is64BitProcess)) }
icm -Session $s { echo ([Environment]::Is64BitProcess) | % { $_ } }
```

Basically anything that forces a change from `AddCommand` to `AddScript`.

> I think it would be a pretty big breaking change, but I'll mark this for committee review.

❤️

**Comment by PaulHigin** [comment]
Yes, this client side evaluation was implemented on purpose.  But I wasn't part of the decision at the time and can only speculate as to why this was done.  So I think it makes sense to let the committee review and confirm this is the behavior we want.

**Comment by SteveL-MSFT** [comment]
Looks like a dupe of https://github.com/PowerShell/PowerShell/issues/13108

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee has reviewed this, in general we stand by our original decision to change the behavior so that expressions are evaluated on the remote side as users would expect.  However, we are concerned about JEA scenarios with no language mode which will no longer work.  We'll be reaching out to some internal partners that rely on JEA to get more data.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee discussed this further and agree that expressions should be evaluated on the remote side with the exception where the remote side is using no language mode then to support those scenarios, like JEA, we need to continue to evaluate those on the client.  This needs to be clearly documented.

**Comment by mklement0** [comment]
I'm glad to hear that problem will be fixed (when?), but I don't think it is _ever_ appropriate to use client-side evaluation, especially not in `Invoke-Command` calls.

Even if the client-side evaluation was once by design, the fact that it can easily bypassed - fortunately - enables a simple _workaround_; quoting from [this Stack Overflow answer](https://stackoverflow.com/a/75176980/45375), where @zett42 ran into unexpected behavior with `Invoke-Command` (the workaround applies analogously to `Enter-PSSession`):

----

The **problem seems to be specific to a script block with the following characteristics**:
 * containing a _single_ statement 
 * that is a _cmdlet_ call (possibly with additional pipeline segments) 
 * whose arguments involve *.NET method calls*, which are then unexpectedly performed on the _caller_'s side.

**Workaround**: 
 * Make sure that your remotely executing script block contains _more than one statement_.
 * A simple way to add a no-op dummy statement is to use `$null++`:

```powershell
# This makes [System.IO.Path]::GetTempPath() *locally* report
#  'C:\temp\'
# *Remotely*, the *original* value should be in effect, even when targeting the 
# same machine (given that the env. var. modification is process-local).
$env:TMP = 'C:\temp'

Invoke-Command -ComputerName MyRemoteMachine -ScriptBlock {
  Write-Output ([System.IO.Path]::GetTempPath()); $null++ # <- dummy statement.
}
```

Other workarounds are possible too, such as enclosing the cmdlet call in `(...)` or inserting a dummy variable assignment  
(`Write-Output ($unused = [System.IO.Path]::GetTempPath())`)
