### ISSUE TITLE
PowerShell 7.1 -> 5.1 inconsistency with Get-ScheduledTask

### ISSUE THREAD

**Issue by allister-grange** [PowerShell/PowerShell#14595]
## Steps to reproduce

```pwsh
Get-ScheduledTask
```

## Expected behavior

I would expect the 'state' property to be the same across PowerShell 5.1 and PowerShell 7. 

This would mean I am returned a state of (Disabled|Ready|Running). 

## Actual behavior

I am returned an integer, I assume this is an enum.

## Environment data

```none
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by doctordns** [comment]
Just tested this in 5.1, 7.1, and 7.2 P2 (and for good measure today's daily build) and can not reproduce.
In all 4 tests, I see the same output which begins..
```powershell
S C:\Foo> get-scheduledtask

TaskPath                                       TaskName                          State
--------                                       --------                          -----
\                                              nWizard_{B2FE1952-0186-46C3-BAEC… Ready
\                                              OneDrive Standalone Update Task-… Ready
\                                              TaskName                          Ready
\                                              User_Feed_Synchronization-{D8911… Ready
\Microsoft\Office\                             Office Automatic Updates 2.0      Ready
\Microsoft\Office\                             Office ClickToRun Service Monitor Ready
```
For brevity, I have snipped the list 10 163 tasks but all tasks show a text state value.

**Comment by allister-grange** [comment]
It must be an issue with 2012 R2 servers. 

I just tested on a 2019 and could not reproduce the bug.

**Comment by jborean93** [comment]
The issue here is most likely due the `ScheduledTask` module not being PowerShell Core compatible on that Windows build. In this case the module is loaded in an implicit remoting session that is connected to a Windows PowerShell process which is what is hosting the module. Because the ScheduledTask module isn't loaded into the current session there is no special type data to convert the raw int value the MSFT_ScheduledTask returns.

You can see the `State` value for the CIM class that hosts this information is a signed integer ([`int32]`) so a raw WMI query will return an integer

```powershell
$cimParams = @{
    ClassName = 'MSFT_ScheduledTask'
    Namespace = 'ROOT\Microsoft\Windows\TaskScheduler'
}
(Get-CimClass @cimParams).CimClassProperties |
    Where Name -eq State
```

```
Name               : State
Value              :
CimType            : SInt32
Flags              : Property, ReadOnly, NullValue
Qualifiers         : {read, ValueMap, Values}
ReferenceClassName :
```

Where the PowerShell magic comes in is that it has extended type data to make the data more readable

```
# Run this on Windows PowerShell
(Get-TypeData '*MSFT_ScheduledTask').Members.State
```

```
GetScriptBlock
--------------
[Microsoft.PowerShell.Cmdletization.GeneratedTypes.ScheduledTask.StateEnum]($this.PSBase.CimInstanceProperties['State'…
```

This type data is automatically applied to any type that matches the type name (caveats do apply) so on Windows PowerShell the `State` property as exposed by PowerShell is automatically converted to an enum when it is accessed.

Going back to the point where the `ScheduledTask` module is run in an implicit remoting session. The module is now loaded in the Windows PowerShell session whereas your PS Core one does not have any type data. Therefore the State will continue to be the raw Int32 value. Newer Windows builds contain an updated `ScheduledTask` module which now loads on PS Core and therefore contain the type data to automatically expose the enum instead.

**Comment by jborean93** [comment]
Just an FYI in the future the default bug report title is quite generic. It makes it easier to search for issues (especially historical ones) if the title reflects the actual bug.

**Comment by allister-grange** [comment]
Thank you very much for the help. This looks to be something that will not be remediated, so I will close the issue. 

I do appreciate the full answer, this would explain a couple of other issues I've noticed with 2012 R2 Task Scheduler and PowerShell Core.
