### ISSUE TITLE
`xsel` copies a newline in powershell

### ISSUE THREAD

**Issue by gogsbread** [PowerShell/PowerShell#14628]
## Steps to reproduce

`echo -n "bar" | xsel -i -b`

## Expected behavior

Should copy to clipboard buffer **without** a newline at the end

## Actual behavior

Copies to clipboard buffer **with** a newline at the end

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Linux 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
The issue here is that `echo -n "bar"` is calling `Write-Output -NoEnumerate -InputObject "bar"` and piping that to the native binary `xsel`. It seems like PowerShell's default behaviour when sending a string to a binary application is to add the newline. I'm not sure if there is a way to change this behaviour.

**Comment by iSazonov** [comment]
Dup #14444
