### ISSUE TITLE
(Powershell) copy-item is much slower than SMB  (protocol)

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#14646]
## Steps to reproduce

```powershell

$shps | foreach -Parallel {Copy-Item -Path C:\path\to\openvpn-connect-3.2.2.1455_signed.msi -Destination c:\software\openvpn -ToSession $_ -Verbose} -ThrottleLimit 10 -Verbose
or
Copy-Item -Path C:\path\to\openvpn-connect-3.2.2.1455_signed.msi -Destination c:\software\openvpn -ToSession $myps -Verbose
```

## Expected behavior

```none
Use all bandwidth of my server or client 
```

## Actual behavior

```none
My server has 10Gbps bandwidth , my client has 100Mbps bandwidth.
When coping files , on the client side, the bandwidth is around 20-30Mbps , on the server side the bandwidth less than 200Mbps . If copy files for individual client via SMB, the full bandwidth of client will be use.
Is the protocol limit the bandwidth , could we adjust it to suit my need?
```

## Environment data

```none
PS C:\Work\OpenVPN> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
Using the `-ToSession` or `-FromSession` means all the data is being encapsulated inside a PowerShell object which is then serialized to XML, base64 encoded, chunked to smaller sizes, then finally transferred over the connection you've defined for that transport. You also have the overhead of setting up the Runspace Pool and Pipeline which I believe happens multiple times due to a file transfer limit set for each pipeline.

Compare this to SMB where the raw bytes of your data is not encapsulated in any container and the protocol is specifically designed for that task. I don't think there is much that can be done here, if you have SMB access then I would use that to copy the file, if you don't then you are limited to what is currently available.

**Comment by tlsalex** [comment]
@jborean93 thanks , to my experience, it may be something else cause that slowness. for more detail , when using copy-item inside foreach , 
If there is one client , the bandwidth at server side is 20-30mbps, if there are 2 clients , the bandwidth at server side is (20-30)*2 mbps, if there are N clients (parallel transfer),  the bandwidth at server side is (20-30)*N , seems like there is some limitation on the source. and that's why I use -ThrottleLimit 10 to utilize more bandwidth at server side.

**Comment by SteveL-MSFT** [comment]
@jborean93 is correct that `-ToSession` means it's going over PowerShell remoting which adds lots of overhead for simply transferring files.  It's really only intended to be used if direct SMB is not available.
