### ISSUE TITLE
-NewLine Parameter to customize line separator for Get-Content

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#14647]
By default `Get-Content` (and `switch -File`) streams lines on either CR, CRLF, _or_ LF newlines, which is a good thing as it allows to interchange (large) text files between Operating Systems. The point is though that in some cases a more specific line terminator is required (e.g. _only_ a `CRLF`) which could possible lead to not being able to stream lines (using standard cmdlets to prevent out of memory exceptions) if it concerns very large text files.
See: StackOverflow [Powershell - Count number of carriage returns line feed in .txt file](https://stackoverflow.com/a/65814922/1701026)

An additional Parameter as `-Newline <string>` (e.g. ``-Newline "`r`n"``) could resolve this and might also allow to stream a (large) text file on a completely different character (combination) as e.g. a tab: ``-Newline "`t"``.

**Related**

- [Powershell Count lines extremely large file](https://stackoverflow.com/q/54893310/1701026)
- #14638 [`Out-String -Stream` unexpectedly does not split multi-line input strings into individual lines too](https://github.com/PowerShell/PowerShell/issues/14638)

**Comment by mklement0** [comment]
Note that `Get-Content` already has a `-Delimiter` parameter that serves this purpose: it accepts any literal string as the string to split the file content by, using _terminator_ logic rather than _separator_ logic (that is, if the content ends in the given string, _no_ additional, empty element is reported).

`-Delimiter` is  a _dynamic_ parameter of the `FileSystem` provider.

**Comment by iRon7** [comment]
I have completely missed this `-Delimiter` parameter
