### ISSUE TITLE
Get-Help removing space on first code line in examples

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/PowerShell#14656]
## Steps to reproduce

Have a function with example formatted as such:

```powershell
    .EXAMPLE
    PS> $session = New-TssSession -SecretServer https://alpha -Credential $ssCred
    PS> Disable-TssSecret -TssSession $session -Id 93

    Disables secret 93
```

Import the module and running `Get-Help Disable-TssSecret -Examples` is removing the space on the first code line:

![image](https://user-images.githubusercontent.com/11204251/105612558-9ca32000-5d82-11eb-9498-7fcdf6b56f6d.png)

## Expected behavior

The output of the example to match that coded in function.

## Actual behavior

Space is removed on the first line of code, not matching the example as coded.

## Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

> Note I did find it does this in Windows PowerShell as well.

**Comment by mklement0** [comment]
The behavior is definitely undesirable, but let point out that you needn't provide a prompt string explicitly at all:
If the first line - only - doesn't start have a prefix that ends with `>`, prefix `PS > ` (sic) is automatically prepended.

If there _is_ a prefix that ends with `>`, as in your case,  any whitespace that follows it is unexpectedly stripped - that is the bug.

I think two fixes are called for:

* The default prefix should be `PS> `, not `PS > `, to be consistent with existing _cmdlet_ help - PR #7255 made the prefix platform-agnostic, but introduced the undesirable space before `>`.

* An existing prefix with `>` should be left alone, but _only_ if it starts with `PS`; otherwise, an unprefixed example command that happens to use `>`  as the redirection operator (e.g., `foo > bar.txt`) would unexpectedly not receive the default prefix.

**Comment by wsmelton** [comment]
> but let me point out that you needn't provide a prompt string explicitly at all

Yeah, but this just looks wrong when you are viewing it from the code on GitHub:

```
    .EXAMPLE
    $session = New-TssSession -SecretServer https://alpha -Credential $ssCred
    PS> Disable-TssSecret -TssSession $session -Id 93

    Disables secret 93
```

It also causes this to happen when the module is used in Windows PowerShell (prepending the wrong prompt):

![image](https://user-images.githubusercontent.com/11204251/105617408-ab4dff00-5da3-11eb-932e-434d01fb02a5.png)

If that was consistent through both then I'd agree, but since it is not we have no choice but to always include it.

**Comment by iSazonov** [comment]
It seems to be more convenient if this code was copyable and executable - remove "PS>" prefix and add "#" before text.
