### ISSUE TITLE
implement indexer in loop

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#14724]
Hi guys !

loops in powershell is various and its awesome but it missing an indexer for example:
```

foreach($index,$item in $list) {
    "$index = $item"
}
```

is more elegant and short:

```
$index =  0
foreach($item in $list) {
    "$index = $item"
     $index++
}


```

**Comment by doctordns** [comment]
What specific problems does this solve?
Wasn't this suggestion recently made and declined?

**Comment by p0W3RH311** [comment]
> 
> 
> What specific problems does this solve?
> Wasn't this suggestion recently made and declined?

@doctordns 

What specific problems does this solve in many languages like python, ruby, perl, rust, javascript, Go, Scala, Php....etc

**Comment by mklement0** [comment]
I like the idea; it complements @iRon7's proposal to introduce an automatic `$PSIndex` variable in the _pipeline_: #13772

@doctordns, it's helpful syntactic sugar; just a couple of use cases off the top of my head; I'm sure there are more.

```powershell
# Parellel array processing
$a = 'foo', 'bar'
$b = 'baz', 'qux'
$c = 'and' 'so on'
foreach ($i, $aElem in $a) { # WISHFUL THINKING
  $bElem, $cElem = $b[$i], $c[$i]
  # ...
}

# Get only every 2nd element
$a = 'foo', 'bar', 'baz', 'quux'
foreach ($i, $aElem in $a) { # WISHFUL THINKING
  if ($i % 2) { continue }
}
```

As a largely moot aside: Quite some time ago, in #3830, I had proposed allowing syntax such as `foreach ($a) { ... }` - not having to specify an iteration variable explicitly and defaulting to `$_` / `$PSItem`; the proposal was rejected, but it would have allowed us a unified approach with respect to an automatic `$PSIndex` as well.

**Comment by rkeithhill** [comment]
I'd move that indexer variable to **after** the condition and if it's optional you don't break existing code e.g.:
```powershell
foreach ($item in $items, $ndx) { ... }
```
FWIW it do not like the idea of an automatic variable like `$PSIndex`.  That falls apart in nested loops.

**Comment by mklement0** [comment]
@rkeithhill, `foreach ($item in $items, $ndx) { ... }` is not an option due to ambiguity - such a statement already works, and loops over the _array_ `$items, $ndx`.

However, `;` as the separator would work (currently a syntax error):  `foreach ($item in $items; $ndx) { ... }`

> falls apart in nested loops.

In nested loops, `$PSIndex` could refer to the respective _enclosing_ loop.
If referencing indices across the loop hierarchy is needed, the explicit index-variable syntax proposed here can be used.

**Comment by rkeithhill** [comment]
Good point on the `,` versus `;`.  In nested loops, it is not uncommon at all to want to access the indexer of outer loops which is tricky with a single variable e.g.:
```
foreach ($item in $items; $ndx1) {
     foreach ($child  in $item.Children; $ndx2) {
         ....
     }
 }

**Comment by p0W3RH311** [comment]
`$psindex` in my opinion as _magic variable_ is better because:

it's not break change and it not break the loop:

```
foreach($item in $list) {
   "$psindex => $item"
}
```

**Comment by rkeithhill** [comment]
IMO PowerShell already has too many magic variables.

**Comment by p0W3RH311** [comment]
@rkeithhill 

yes ps has many magic variable but it not has an _indexer magic variable_

**Comment by p0W3RH311** [comment]
another idea is to implement an indexer in _$foreach_ enumerator

```
foreach($item in $list) {
   $foreach.index
}
```

**Comment by rkeithhill** [comment]
I think you wouldn't get too far before folks demanded a way to access an outer loop's indexer.  At that point, I don't think you need (or want) two ways to access indexers.

**Comment by mklement0** [comment]
Agreed, @rkeithhill, but my point was that you would have the _choice_, i.e. I was advocating for _both_ proposals to be implemented: if you _do_ need cross-hierarchy index access, use the _explicit_ syntax; otherwise, rely on `$PSIndex` for convenience. But, again: this is really a moot point, because `$PSIndex` should only be implemented _in tandem_ with allowing `foreach ($collection) { ... }` (implicit iterator variable `$_` / `$PSItem`), which, as stated has been rejected.

In short: I think we can conclude this part of the discussion, unless enough people feel strongly enough to revisit this, in a _separate_ proposal.

---

Come to think of it: `foreach ($item in $items; $ndx) { ... }` (`;` as the separator, index variable specified _after_) is preferable due to avoiding potential conceptual confusion due to `$ndx, $item in $items` looking like a  _destructuring assignment_.

Also, it would leave the door open for a further, separate enhancement that could further simplify the parallel-collection enumeration by using a destructuring assignment as follows (which could still be combined with an explicit index variable):

```powershell
$a = 'foo', 'bar'
$b = 'baz', 'qux'
$c = 'and' 'so on'
foreach ($aElem, $bElem, $cElem in $a, $b, $c) { # WISHFUL THINKING
   # $aElem is $a[<ndx>]
   # $bElem is $b[<ndx>]
   # $cElem is $c[<ndx>]
}
```

The _largest_ among the RHS collections would drive the number of iterations, and the iterator variables would contain `$null` for those collections that have run out of items.

**Comment by p0W3RH311** [comment]
@rkeithhill 

I think the common point is that powershell lacks an indexer variable like many other languages ​​... now how to implement this indexer ... there are several ways on the designated side: 

powershell way 

```
foreach($item in $list) {
   $foreach.index # another property
}
```

or
```
foreach($item in $list) {
   $PSindex # magic variable
}
```

the traditional way

```
foreach($i, $item in $list) {
   $foreach.index
}
```

**Comment by rkeithhill** [comment]
@p0W3RH311 I'm with you on the "common point".  I like the feature suggestion.  I'm just not a fan of using a magic variable for the indexer.  🤷‍♂️

**Comment by 237dmitry** [comment]
> another idea is to implement an indexer in _$foreach_ enumerator
> 
> ```
> foreach($item in $list) {
>    $foreach.index
> }
> ```

It probably won't work with `$foreach`. What will `$foreach.index` be in the case of `$foreach.Reset()`?

```
$ind = 0; foreach ($i in 'a','b','c')    
 {                                       
     $foreach.Current                    
     if ($ind -eq 1) { $foreach.Reset() }
     $ind++                              
 }                                       
```

**Comment by SeeminglyScience** [comment]
> What specific problems does this solve in many languages like python, ruby, perl, rust, javascript, Go, Scala, Php....etc

This isn't a very compelling argument imo.  There are a lot of patterns in other languages that just don't make as much sense in PowerShell.

It's definitely useful occasionally to have an index in PowerShell, but with the way pipelines work it's significantly less important. Personally I worry that this would be used too infrequently to warrant language changes.

**Comment by mklement0** [comment]
Agreed re the general point that not all patterns are a good fit for PowerShell, however:

> the way pipelines work it's significantly less important.

Can you elaborate on how the pipeline mechanism makes this feature less important? 

#13772 makes  a pretty good case for a an automatic `$PSIndex` variable in the _pipeline_; for symmetry alone it makes sense to provide an analogous feature in `foreach` statements (with an _explicit_ index variable, analogous to how you need an _explicit_ iterator variable).

To me, it's a useful enhancement, both in `ForEach-Object` / `Where-Object`-based pipelines (and, by extension, in the `.ForEach()` and `.Where()` methods) and `foreach` loops.

* In the former case, implementing `$PSIndex` is trivial - no new syntax needed, just a new variable you're free to use or not.

* In the latter case, explicit (opt-in) syntax is needed, but `foreach ($name in 'foo', 'bar'; $ndx) { ... }` strikes me as a perfectly reasonable extension to the current syntax (the `;` should already be familiar from `for` loops).

**Comment by SeeminglyScience** [comment]
> Can you elaborate on how the pipeline mechanism makes this feature less important?

In other languages it's very common to allocate an array up front and then populate it.  Or mutate an array in place.  In PowerShell it's significantly easier to just let the pipeline make one for you.

> #13772 makes a pretty good case for a an automatic `$PSIndex` variable in the _pipeline_;

With the exception of "Combine single arrays into columns" I don't really see any real world examples in that issue.  I think it's just as unlikely to see all that much usage.

> for symmetry alone it makes sense to provide an analogous feature in `foreach` statements

Symmetry is nice, but I disagree that it's a compelling enough reason on it's own.

**Comment by mklement0** [comment]
* An automatically maintained index provides utility irrespective of whether it us used in a streaming pipeline or during iteration of an in-memory array.

* Because it is useful in both scenarios, it should be implemented in both.

**Comment by mklement0** [comment]
I've created a new issue for the separate `foreach ($aElem, $bElem, $cElem in $a, $b, $c) { ... }` proposal mentioned [above](https://github.com/PowerShell/PowerShell/issues/14724#issuecomment-774709735) (enumerating multiple collections in tandem): #14732

Also, to make it more obvious how people feel about _this_ issue, I encourage everyone who was commented so far to give the _initial_ post here a thumbs-up or -down.

**Comment by SeeminglyScience** [comment]
> * An automatically maintained index provides utility irrespective of whether it is used in a streaming pipeline or during iteration of an in-memory array.

Sorry, to clarify, I was giving examples of some of the most common scenarios one would use an index in other languages. Scenarios that are significantly less common in PowerShell.

**Comment by mklement0** [comment]
I see, but the fact there are _additional_ scenarios in other languages where indices are not only useful but _required_ as an _intrinsic part of the enumeration_ is ultimately a moot point. To put it differently: this argument doesn't preclude utility in PowerShell scenarios.

The relevant question is: Is the feature useful _in PowerShell_?

It is to me, and I have personally wished for it in the past; we'll see how the community feels over time.

**Comment by SeeminglyScience** [comment]
> I see, but the fact there are _additional_ scenarios in other languages where indices are not only useful but _required_ as an _intrinsic part of the enumeration_ is ultimately a moot point. To put it differently: this argument doesn't preclude utility in PowerShell scenarios.

That's correct.  It was in response to your question asking why the pipeline makes it less important in PowerShell.

> It is to me, and I have personally wished for it in the past; we'll see how the community feels over time.

I think one of the best ways to show the utility would be to point to some examples of existing code that would greatly benefit from this.  Like some code in an already published module or script that would be simplified significantly.

I don't doubt that it has uses.  I've wanted it myself a few times, but in all of those few times either a `for` loop, incrementing my own var or just a different pattern was perfectly suitable.  Remember that language changes need a pretty dramatic effect to be worth it.

**Comment by p0W3RH311** [comment]
> 
> 
> > What specific problems does this solve in many languages like python, ruby, perl, rust, javascript, Go, Scala, Php....etc
> 
> This isn't a very compelling argument imo. There are a lot of patterns in other languages that just don't make as much sense in PowerShell.
> 
>  Personally I worry that this would be used too infrequently to warrant language changes.

in PS there are many variable too infrequently  used like $^ and $$ but this variable exist...indexer is usefull and perphaps is more usefull in future....

**Comment by mklement0** [comment]
@SeeminglyScience:

Fair point, but I was confused by your mentioning the pipeline specifically, because enumeration of collections with `foreach ($element in $collection)` too obviates the need for indices (as it does in the equivalent C# statement, for instance), if (read-only) enumeration _alone_ is needed.

_Optionally_ - if the business logic rather than the technical underpinnings requires it - having an automatically maintained index at one's disposal, without having to forgo the convenience of `foreach ($element in $collection)` seems beneficial to me.  

>  need a pretty dramatic effect to be worth it.

Point taken, but even though we are undoubtedly talking about _syntactic sugar_ here, such sugar is often important for sweetening the developer experience, if you will.

I'll see if I can come up with examples in published code and/or additional compelling examples.
I'm hoping others will too.

**Comment by SeeminglyScience** [comment]
> Fair point, but I was confused by your mentioning the pipeline specifically, because enumeration of collections with `foreach ($element in $collection)` too obviates the need for indices (as it does in the equivalent C# statement, for instance), if (read-only) enumeration _alone_ is needed.

Ah yes sorry it wasn't obvious what I was referring to, but most things use the pipeline plumbing at some point.  For example:

```powershell
$a = foreach ($b in (0..30)) { $b }

# or 

$a = gci

# or 

$a = $(gci; gci)
```

Behind the scenes that'll use a very *similar* code path to build `$a` even though there is no `PipelineAst` language wise.  I guess it would be more accurate to refer to it as "output semantics" maybe?

**Comment by mklement0** [comment]
Good point, @SeeminglyScience, and thanks for clarifying.

Even though it's technically not entirely accurate, I generally suggest using  and interpreting the term "pipeline" as informal shorthand for "connecting _commands_ with a _pipe symbol_" (including the case where the _first_ segment is an _expression_; e.g. `1..10 | ForEach-Object { "[$_]" }`),  as distinct from the world of _expressions_ (e.g. `1 + 1`) and _statements_
(e.g. `foreach ($num in 1..10) { "[$num]" }`).

Here, we have the contrast between the `ForEach-Object` _command_ with its (invariably) _implicit_ iterator variable, `$_` (`$PSItem`) and the `foreach` _statement_ with its (invariably) _explicit, user-chosen_ iterator variable.

Therefore, in the pipeline (loosely speaking), the proposed automatic index variable must be implicit too, with a name such as `$PSIndex`, as proposed by @iRon7 in #13772.

(As stated, it would make sense to me to allow _implicit_ iterator variables in `foreach` _statements_ too - 
`foreach (1..10) { "[$_]" }` - but only if `$_` / `$PSItem` were to be supported - which was rejected - would it make sense to me to also support `$PSIndex`)

---

The following uses cases are more directly relevant to #13772, but since the unified discussion seems to be happening here, here goes:

In the pipeline, it isn't just `ForEach-Object` and `Where-Object` that would benefit from `$PSIndex`, but also:

* delay-bind script blocks
* calculated properties

In both cases the script blocks run in a _child_ scope - see #7157 - which makes maintaining a cross-invocation index variable via the _parent_ scope both obscure and cumbersome:

Consider the scenario of renaming files to names that incorporate a sequence number via a _delay-bind script block_ (a real-world scenario that comes up repeatedly on Stack Overflow):

```powershell
# Delay-bind script block
# Cumbersome and obscure, because you must refer to the $i variable in the *parent* scope.
# Renames the input files to "file1.txt", "file2.txt", ...
$i = 0
Get-Item *.txt | Rename-Item -NewName { "file" + ++(Get-Variable -Scope 1 i).Value + ".txt" } -WhatIf
```

With `$PSIndex` this simplifies to:

```powershell
# WISHFUL THINKING.
Get-Item *.txt | Rename-Item -NewName { "file" + (1 + $PSIndex) + ".txt" } -WhatIf
```

The same applies to a (script block-based) _calculated property_; consider the case of wanting to create sequence number-based identifiers via `Select-Object`:

```powershell
# WISHFUL THINKING.
Get-Item *.txt | Select-Object @{ n='Id'; e={ 1 + $PSIndex } }, FullName
```

While the scoping problem doesn't arise with the `foreach` _statement_, an automatic indexer still makes for a nice, expressive simplification:

```powershell
# WISHFUL THINKING
foreach ($file in Get-item *.txt; $i) {
  [pscustomobject] @{
    Id = 1 + $i
    FullName = $file.FullName
  }
}
```

**Comment by SeeminglyScience** [comment]
> Here, we have the contrast between the `ForEach-Object` _command_ with its (invariably) _implicit_ iterator variable, `$_` (`$PSItem`) and the `foreach` _statement_ with its (invariably) _explicit, user-chosen_ iterator variable.

Yeah it doesn't use the pipeline for enumeration, though it can emit to an output pipe still.


> ```powershell
> # Delay-bind script block
> # Cumbersome and obscure, because you must refer to the $i variable in the *parent* scope.
> # Renames the input files to "file1.txt", "file2.txt", ...
> $i = 0
> Get-Item *.txt | Rename-Item -NewName { "file" + ++(Get-Variable -Scope 1 i).Value + ".txt" } -WhatIf
> ```

If you're renaming files, aren't you going to want to keep the number of the existing name? Like if you're renaming `FileX.txt` to `SomethingX.txt` you probably don't want the index to be based on the order they're returned in most cases. The only time I can really think of that I've needed to do this is creating test files, where you typically do `0..10 | % { New-Item File$_.txt }` anyway.

The rest of the examples are similar in that while it **is** an example of how it could be used, it's not clear why you'd need to.

**Comment by mklement0** [comment]
> though it can emit to an output pipe still.

If I understand correctly, _directly_ only stand-alone (possibly in the context of an assignment); in a pipeline (with `|`), only via `$()` / `@{)` (collecting all output up front) or via `& { ... }` / `. { ... }` (streaming), but I think we have clarity now on the syntactic scenarios we want to contrast.

> If you're renaming files, aren't you going to want to keep the number of the existing name?
> it's not clear why you'd need to.

* There may be no numbers (lexical order), or the numbering may be different (e.g., start with an offset) and/or may have gaps.
* Renaming files is just one example; needing to produce _sequence numbers_ is a common requirement in many different scenarios, as is _index-based filtering_.

**Comment by SeeminglyScience** [comment]
> If I understand correctly, _directly_ only stand-alone (possibly in the context of an assignment); in a pipeline (with `|`), only via `$()` / `@{)` (collecting all output up front) or via `& { ... }` / `. { ... }` (streaming), but I think we have clarity now on the syntactic scenarios we want to contrast.

Anything that isn't captured or in a class method is emitted to the pipeline.

For example:

<details>

<summary>This is what the script `0` compiles to</summary>

```csharp
private static void <ScriptBlock>(FunctionContext funcContext)
{
    try
    {
        context = funcContext._executionContext;
        locals = ((MutableTuple<object, Object[], object, object, PSScriptCmdlet, PSBoundParametersDictionary, InvocationInfo, string, string, Null, Null, Null, Null, Null, Null, Null>)funcContext._localsTuple);
        funcContext._functionName = @"<ScriptBlock>";
        funcContext._currentSequencePointIndex = 0;

        context._debugger.EnterScriptFunction(funcContext);
        try
        {
            funcContext._currentSequencePointIndex = 1;
            if (context._debuggingMode > 0)
            {
                context._debugger.OnSequencePointHit(funcContext)
            }

            funcContext._outputPipe.Add(((object)0));
            context.QuestionMarkVariableValue = true;
        }
        catch (Exception exception)
        {
            ExceptionHandlingOps.CheckActionPreference(funcContext, exception);
        }

        funcContext._currentSequencePointIndex = 2;
        if (context._debuggingMode > 0)
        {
            context._debugger.OnSequencePointHit(funcContext);
        }
    }
    finally
    {
        context._debugger.ExitScriptFunction();
    }
}
```

</details>

The relevant line being:

```csharp
funcContext._outputPipe.Add(((object)0));
```

> * There may be no numbers (lexical order), or the numbering may be different (e.g., start with an offset) and/or may have gaps.
> * Renaming files is just one example; needing to produce _sequence numbers_ is a common requirement in many different scenarios, as is _index-based filtering_.

My suggestion if your aim is to convince someone to pick up this work (or convince someone that this should be brought up with the committee) would be to use real world examples.  Theoretical examples aren't as helpful for determining the level of impact a feature could provide.

**Comment by mklement0** [comment]
> Anything that isn't captured or in a class method is emitted to the pipeline.

Yes, but my point was that you can't do `foreach ($i in 1..3) { $i } | Measure-Object`, for instance - you need `& { foreach ($i in 1..3) { $i } } | Measure-Object`, for instance; that is, you cannot use a _statement_ in a multi-segment pipeline - see https://github.com/PowerShell/PowerShell/issues/10967#issuecomment-561843650

> My suggestion if your aim is to convince someone to pick up this work (or convince someone that this should be brought up with the committee) would be to use real world examples. 

Honestly, to me the examples given so far - both concrete and abstract - are so self-evidently compelling that I don't see value in spending more time on finding real-world examples.

Perhaps others feel inspired to do so, and perhaps the count of thumbs-up on the issue will make a statement of its own over time.

The primary hurdle, I'd say, is to get this committee-reviewed; I wouldn't want anyone spending time on an implementation without knowing that the feature will be approved.
@iSazonov, any thoughts?

**Comment by iSazonov** [comment]
Just yesterday, I thought PowerShell is at the same conceptual level as it was 20 years ago and is still at the foot of a magnificent tower - we haven't even climbed one floor in all this time. One must have limitless inspiration to develop primary ideas to these new heights.
Thinking so, I believe that it makes no sense to invest too much in traditional operators, but in PowerShell pipeline makes sense.

**Comment by mklement0** [comment]
Thanks, @iSazonov. I too value the conceptual elegance of PowerShell's OO pipeline and welcome improvements to it, but, as is often the case, this is not an _either-or_ proposition (more on that later).

Unquestionable, what was initially proposed _here_ in the context of the `foreach` _statement_ and what is proposed with respect to the _pipeline_ (loosely speaking) in #13772 can be decided on _separately_ - even though I personally think that if it's worthwhile in one context, it is worthwhile in the other (see below).

So, if you already think #13772 is worthwhile, please tag it for committee review.

(The generalization of #13772, which started with a focus on `ForEach-Object` and `Where-Object` is: provide an automatic index variable in any collection-processing script-block context where `$_` / `$PSItem` is defined, which also includes calculated properties and delay-bind script-block arguments, the `.ForEach()` and `.Where()` _methods_, the `switch` _statement_, and the `-replace` _operator_ (possibly more).)

---

>  it makes no sense to invest too much in traditional operators

Cmdlets such as `ForEach-Object` and language statements such as `foreach` loops  _complement_ each other and are appropriate for _different scenarios_.

Neither is going away.

Both should provide an expressive developer experience _with (fundamental) feature parity_ (which, regrettably, already falls short in one case: the `.Where()` _method_ has useful features that `Where-Object` lacks: see #13834)

A `foreach` loop far outperforms a `ForEach-Object`-based solution, and that alone makes it indispensable. This is especially pronounced with collections that are already in memory in full, but it even applies to `foreach ($obj in <command>)`; it also outperforms the `.ForEach()` _method_.

It comes down to a tradeoff between memory use and performance, and while in many cases you may be able to choose _any_ of these without too much real-world impact, there are cases where are _forced_ to choose one (`foreach` for performance) or the other (`ForEach-Object` to avoid running out of memory).

All three serve the same fundamental purpose: iterating over something enumerable (loosely speaking; strictly speaking, it is the _pipeline itself_ that does the enumeration in the case of `ForEach-Object`)

All three are _expressive_ in that you needn't worry about the _details_ of the enumeration: is it an index-based collection or a (potentially lazy) enumerable?

`ForEach-Object` / `.ForEach()` do not even require you to _pick a variable name_ for the enumeration element at hand; the name is fixed in the form of the automatic `$_` / `$PSItem` variable.

Providing an automatic index indicating the `0`-based position of the element at hand in the enumeration therefore similarly calls for such a variable, `$PSIndex`, as proposed in #13772 

By contrast, `foreach` _does_ require you to pick an iterator variable name - `$_` / `$PSItem` isn't supported.
Therefore, it makes sense to also require picking an variable name for the automatic index - unlike with `$PSItem`, this necessitates an addition to the _syntax_, the proposed `foreach ($element in $enumerable; $index) { .. }`.

If such an automatically maintained index makes sense with `ForEach-Object` (among others), it also makes sense in a `foreach` loop - especially given that, as stated, sometime you have no choice but to use `foreach` over `ForEach-Object`.

---

I've said it before: the examples in #13772 and here to me amply demonstrate that such an automatic index is called for as _expressive syntactic sugar_ that serves real-world needs, which, as @p0W3RH311, has pointed out, several other languages have recognized too (notably [including the _systems_ programming language Rust](https://www.programming-idioms.org/idiom/7/iterate-over-list-indexes-and-values/415/rust))

Syntactic sugar isn't a luxury; it's what makes a language fun to use.

And here's a secret: `foreach ($element in $enumerable) { $element }` is _itself_ syntactic sugar:

* In the case of an index-based enumerable, it is syntactic sugar for:
 `for ($i=0; $i -lt $enumerable.Count; ++$) { $enumerable[$i] }`

* In the case of an enumeration-interface-based enumerable, it is syntactic sugar for:
 `while ($element = $enumerable.MoveNext()) { $element }`

And with `foreach` you don't even have to worry which kind of enumerable you're dealing with.

Also note how the `for` loop _forces_ you to deal with indices - even though you may not actually need them.
Conversely, if you _do_ need them in the `.MoveNext()` `while` loop, you have to _add them manually_.

* `foreach` already takes the drudgery out of the enumeration part.

* Wouldn't it be nice if it also took out the drudgery of the _index_ part, _if and when_ you actually need an index, for _business-logic reasons_, not as a syntactic necessity?

**Comment by Jaykul** [comment]
I have to say that whenever I've needed something like this, I've just changed to a `for(){}` loop, or added a counter variable.

I don't mind the idea of adding syntax to `foreach(){}` to define a counter variable to be incremented for me, but I'm not convinced the savings are worth it. I mean, is this:

```PowerShell                                              
foreach($item in @($List); $index) {           
  $item | add-member Index $index -PassThru    
}                                              
```

Really better than this:
```PowerShell
$index=0; foreach($item in @($List)) {         
  $item | add-member Index ($index++) -PassThru
}
```

Remember that it's not just about saving you a few keystrokes, it's also about clarity and readability ...

**Comment by mklement0** [comment]
> Really better than this

To me it is unequivocally better:

* no need to declare a variable _outside_ the loop (even though based on PowerShell's scoping rules even the syntactic-sugar index variable would live on beyond the loop, as the iteration variable already does, but that's a separate issue)

* no messing with `$index++` for incrementing, which is notoriously error-prone.

> Remember that it's not just about saving you a few keystrokes, it's also about clarity and readability ...

Agreed, but to me `foreach($item in @($List); $index)` fulfills that criterion (syntactically simple, easily documented and remembered) - even though it isn't as verbose as `-counter index`, but I am wary of this mixing of PowerShell's parsing worlds (argument vs. expression mode):

Yes, `switch` is the precedent, but the only one, and an awkward one at that; e.g., in `switch -File file.txt { ... }`, `file.txt` is parsed as an argument and may therefore - despite being a _string_ - be _unquoted_; by contrast, a direct input object must be supplied inside (`...`), which forces a new parsing context where a bareword string is _not_ supported, as it would be interpreted as a _command_; e.g., `switch (mystring) { ... }` looks for a _command_ named `mystring`. Similar confusion can arise in the branch conditions - see #3668.

**Comment by rjmholt** [comment]
After discussing this with the Engine working group, we don't think this should be baked in at the language/syntax level. This is probably best accomplished with a function like Python's [enumerate](https://python-reference.readthedocs.io/en/latest/docs/functions/enumerate.html). This could be implemented in an external module and later evaluated for inclusion in PowerShell.
