### ISSUE TITLE
Feature Request - Make New-PSDrive -Persist option available for local folders and drives

### ISSUE THREAD

**Issue by IkerGimenez** [PowerShell/PowerShell#14744]
## Summary of the new feature/enhancement

One way I like to work with programming projects is to `subst` a virtual drive to the root of the workspace I'm using. It solves a lot of issues like having extremely long paths that build tools often can't process. `subst` isn't persistent though, so once you shutdown the computer it's lost. There's workarounds, like adding a script to the startup process that sets up the drives, but reducing the amount of work needed by just having it available when using `-Persist` with `New-PSDrive` would be very nice to have.

## Proposed technical implementation details (optional)

`New-PSDrive -Name "X" -PSProvider "Filesystem" -Root "C:\My\Really\Long\And\Inconveniently\Nested\Folder\Path" -Persist -Scope Global`
After running the above, the path at root should be accessible as drive "X:\"

Considerations:
`-Name` argument will need sanitizing for valid drive names
`-PSProvider` not sure if it would make sense for this to be available for arguments that aren't `"Filesystem"`

**Comment by jborean93** [comment]
I believe this is not in place today because `subst` just creates the [DosDevice](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/introduction-to-ms-dos-device-names) and because those devices are unique per session they are lost when you enter a new session. Mapped drives work in a similar fashion where they are just a `DosDevice` that maps the drive letter with the SMB provider but they also provide a functionality to persist across logon session through the `HKCU:\Network` register key. This key is special because the Winlogon process knows to enumerate these values and create the `DosDevices` for that logons session. I'm not aware of `subst` offering that ability and anything that does just rely on autorun features like the `Run` key in the registry to run the `subst` command manually.

**Comment by IkerGimenez** [comment]
I see, I didn't realize it was tied to the OS like that. I can close this if you feel it's inappropriate for the PowerShell project.
