### ISSUE TITLE
Tab completion regression in ordering (does not match Linux shells, Windows explorer, or cmd)

### ISSUE THREAD

**Issue by jessey-git** [PowerShell/PowerShell#14757]
## Steps to reproduce

```powershell
mkdir test
cd test

echo "" > foo.exe
echo "" > foo_bar.cmd
echo "" > foo_bar_zar.cmd
mkdir foo

.\f <tab> <tab> <tab> <tab> ...
```

## Expected behavior

```none
Expected tab completion order as follows -- matches pwsh 7.0.x, windows explorer, cmd, AND linux Bash
.\foo\  .\foo.exe  .\foo_bar.cmd  .\foo_bar_zar.cmd
```

## Actual behavior

```none
Regression in ordering
.\foo\  .\foo_bar_zar.cmd  .\foo_bar.cmd  .\foo.exe
```

Do the right thing and fix the regression.

**Comment by mklement0** [comment]
There was indeed a change in behavior between Windows PowerShell and PowerShell (Core), in support of cross-platform consistency, so I don't think it's a regression (though I cannot speak to what extent there was awareness that the behaviors diverged as a result).

The PowerShell (Core)-internal change between 7.0.5 and 7.1 is owed to a change in .NET itself outside PowerShell's control (presumably, just moving to a new .NET version did it - I have no information what prompted the change in .NET).

```powershell
# Reports "! . _" in 7.0.5 vs. "_ ! ." in 7.1 and later on a US-English machine.
[string[]] $a = '!', '_', '.'; [Array]::Sort($a, [StringComparer]::CurrentCultureIgnoreCase); $a -join ' '
```

However, even 7.05 didn't sort the same as `cmd.exe` with respect to non-ASCII characters:

It is also important to note that there is _no_ consistent behavior across the other shells and GUI file managers such as File Explorer.

The summary is:

* Each platform individually exhibits different behaviors in the (native-shell) terminal vs. in the GUI file manager (notably, natural sorting of trailing numbers).

* Different Unix-like platforms behave differently (macOS vs. Linux).

* Windows PowerShell exhibits different behavior with `Get-ChildItem` (ordinal sorting (by code-point value), as reported by the .NET file-enumeration APIs) vs. with tab-completion (lexical) - an unfortunate inconsistency.

* PowerShell (Core) now uses lexical sorting consistently, on all platforms, which means case-insensitive, current-culture-sensitive sorting; on Unix-like platforms it _must_ do its own sorting, because the underlying system APIs enumerate files unsorted.

---

I see the following options:

* (a) Leave everything as is, which has two benefits:
  * Simple implementation.
  * Consistent behavior across all platforms - even if it doesn't match any platform's native sorting.

* (b) Try to emulate the native shells _platform-specifically_, which would mean: 
  * Increased implementation complexity.
  * Ordinal sorting on Windows and macOS.
  * _Modified_ lexical sorting on Linux (emulating the specifics may be tricky, unless it is provided by a system call)

* (c) Stick with consistent cross-platform behavior, but switch to the "majority" sorting, which would be ordinal, because 2 out of 3 platforms - Windows and macOS - use it, but in terms of actual PowerShell usage Linux is probably the more important platform.

From a PowerShell (Core) perspective (alone), (b) and (c) would be breaking changes, given that a change wouldn't just affect the interactive experience (tab-completion) but also the order in which files are listed with `Get-Item` / `Get-ChildItem`.

---

For anyone who wants to experiment with the sort orders, here's test code:

<details>
```powershell
& {
  Push-Location ($td = New-Item -Force -ItemType Directory (Join-Path ([io.path]::GetTempPath()) $PID))

  $names = 'foo', 'foo_bar.cmd', 'foo_bar_cmd', 'foo_bar!cmd', 'föo', 'foo10', 'foo2'

  $null = New-Item -Force $names

  '-- Ordinal sort'
  [Array]::Sort($names, [StringComparer]::OrdinalIgnoreCase); $names

  '-- Lexical sort (current culture)'
  [Array]::Sort($names, [StringComparer]::CurrentCultureIgnoreCase); $names

  '-- Tab-completion'
  (TabExpansion2 -inputScript 'Get-Item ' -cursorColumn 9).CompletionMatches.CompletionText

  '-- Get-ChildItem' # also applies to -Path and -Filter wildcards
  (Get-ChildItem).Name

  if ($env:OS -eq 'Windows_NT') {
    "-- cmd /c dir (Windows)"
    cmd /c dir /b

  } else {
    "-- ls ($(uname))"
    ls -1
  }

  Invoke-Item . # Show the folder in the platform's GUI file manager.

  Read-Host '-- GUI File Manager launched; press Enter to clean up and exit; to test tab-completion in the native shell, press Ctrl-C now, and enter a native shell; rerun the script without aborting later to clean up'

  Pop-Location; Remove-Item $td -Recurse
}
```
</details>

**Comment by jessey-git** [comment]
Any movement here?  I don't see why, in any universe, '_' should come before '.' for file listing or tab-completion...

**Comment by ckruegerkpmg** [comment]
@jessey-git
It's at least consistent with the output of get-childitem.

**Comment by jessey-git** [comment]
@ckruegerkpmg Not really. Get-ChildItem always used to match.

Here's the *correct* output from 7.0.6 in a real directory and which matches with tab-completion behavior.
```
Get-ChildItem *blender*


    Directory: F:\source\blender-git\blender-20211022-asan\bin\Debug

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          10/22/2021  2:39 PM                blender.crt
-a---           11/5/2021  4:30 PM      529417728 blender.exe
-a---           11/5/2021  4:30 PM           2026 blender.exp
-a---          10/22/2021  2:43 PM           3740 blender.lib
-a---           11/5/2021  4:30 PM      286814208 blender.pdb
-a---           3/11/2021  1:43 PM            832 blender_debug_gpu.cmd
-a---           4/19/2020  2:48 PM            871 blender_debug_gpu_glitchworkaround.cmd
-a---           4/19/2020  2:48 PM            821 blender_debug_log.cmd
-a---           4/19/2020  2:48 PM            806 blender_factory_startup.cmd
-a---           4/19/2020  2:48 PM            554 blender_oculus.cmd
-a---           11/5/2021  4:29 PM           2040 blender_test.exp
-a---           11/4/2021  2:59 PM           3924 blender_test.lib
-a---          10/30/2021 12:02 AM        1103360 blender-launcher.exe
-a---          10/30/2021 12:02 AM        1003520 blender-launcher.pdb
```

Here is what 7.2.0 believes is the way to sort for no good reason... hilariously bad:
```
Get-ChildItem *blender* 

    Directory: C:\Users\fxgltf\test

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           4/19/2020  9:48 PM            871 blender_debug_gpu_glitchworkaround.cmd
-a---           3/11/2021  9:43 PM            832 blender_debug_gpu.cmd
-a---           4/19/2020  9:48 PM            821 blender_debug_log.cmd
-a---           4/19/2020  9:48 PM            806 blender_factory_startup.cmd
-a---           4/19/2020  9:48 PM            554 blender_oculus.cmd
-a---           11/5/2021 11:29 PM           2040 blender_test.exp
-a---           11/4/2021  9:59 PM           3924 blender_test.lib
-a---          10/30/2021  7:02 AM        1103360 blender-launcher.exe
-a---          10/30/2021  7:02 AM        1003520 blender-launcher.pdb
-a---           11/5/2021 11:30 PM      529417728 blender.exe
-a---           11/5/2021 11:30 PM           2026 blender.exp
-a---          10/22/2021  9:43 PM           3740 blender.lib
-a---           11/5/2021 11:30 PM      286814208 blender.pdb
```

**Comment by theJasonHelmick** [comment]
Thank you for the issue -- The WG reviewed this issue and believes it is a change to .NET (as stated by @mklement0) https://github.com/PowerShell/PowerShell/blob/7b3e5444de9b1740677ed70c42fac03556855bc1/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L1633 
As noted, it is not a goal of PowerShell to be consistent with other shells or file managers.

**Comment by jessey-git** [comment]
For anyone in the future coming across this utter nonsense for file listing and tab completion, there's a workaround available in: https://github.com/PowerShell/PowerShell/issues/19736

**Comment by ckrueger1979** [comment]
> As noted, it is not a goal of PowerShell to be consistent with other shells or file managers.

What a dumb idea.

**Comment by mklement0** [comment]
Note:

* I'm not weighing in on whether the decision was the right one, I just want to provide some more background information and to correct some inaccuracies in my previous comment (since amended).

* To summarize the opt-in to the old PowerShell _Core_ behavior on Windows (based on the Windows-native NLS APIs), from [.NET globalization and ICU](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu):
   * Set the environment variable `DOTNET_SYSTEM_GLOBALIZATION_USENLS` to `1` (or `true`), which must be done _before_ starting a PowerShell session.
   * **Caveat**: By configuring PowerShell with the NLS opt-in you'll fundamentally change how string sorting works in your session, along with other behaviors (the areas are affected are listed near the top of the linked help topic). 

* The findings below are based on the test code in my [previous comment](https://github.com/PowerShell/PowerShell/issues/14757#issuecomment-781616637) (expandable "Details" section).

---

> At least it must be consistent with `get-childitem`

* Tab-completion _is_ consistent with `Get-ChildItem` in PowerShell Core (using _linguistic_ (lexical; current-culture, case-insensitive) sorting based on ICU on all platforms in v7.1+, and  in v7.0- on Windows  based on NLS)
* Is _inconsistent_ in Windows PowerShell (_ordinal_ sorting in `Get-ChildItem`, _lexical_ NLS sorting with tab-completion)

---

**Summary:**

* .NET 5 switched its globalization APIs on Windows from the native NLS APIs to the cross-platform ICU APIs (as previously already used on Unix-like platforms), as described in [.NET globalization and ICU](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu) 

* PowerShell 7.1+ is based on .NET 5+, and therefore _implicitly_ started using ICU rules, which notably differ in that `_` now sorts before `.`, which is what #19736 is focused on.
  * As discussed at the top, an NLS opt-in is available, but it affects all code in the session (except applications that explicitly control this behavior as part of their configuration).

As will become clear below, the platform-native behaviors all differ, along the dimensions of:
* Do accented characters such as `ö` sort alongside their base letter, `o`?
* Do symbols (e.g., `_` and `.`) sort _as a group_ (linguistic) or purely based on their Unicode code point (ordinal), in which case `.` sorts _before_ digits (e.g., `1`) and letters (with case-insensitive sorting also for lowercase letters),  but `_` sorts _after_ them?
* What is the relative sort order _among symbols_? (`.` before `_` vs. `_` before `.`)

The only thing the platform-native behaviors have in common is that `.` sorts before `_`, for instance, which PowerShell v7.1+ now deviates from.

**Behavior of PowerShell (Core), on all platforms:** 

* Linguistic sorting (current culture, case-insensitive) based on ICU rules in v7.1+ (`_` before `.`); in v7.0-, sorting was based on NLS rules:  (`.` before `_`)
* Applies to `Get-ChildItem`, globbing (wildcard expansion), as well as tab-completion order.

**Platform-native / Windows PowerShell behavior:**

* **Note**: 
  * The descriptions below are in part _inferred_ from the observed behaviors; I have not tried to dig deeper.
  * Among the native utilities, the macOS Finder (GUI file manager) is the only one that sorts `_` before `.`; with the exception of the natural number sorting, its sort oder seems to match that of ICU (i.e. .NET 5+ / PowerShell 7.1+)

* **macOS**:
  * `ls`: _modified ordinal_ sorting: ordinal with respect to symbols, linguistic with respect to letters (`.` before `_`,  but not adjacent)
  * GUI file manager (Finder): _linguistic_, modified with natural number sorting (`_` before `.`)

* **Windows**:
  * `cmd`'s `dir`: _ordinal_ (`.` before `_`, but not adjacent)
  * Windows PowerShell:
    * `Get-ChildItem`, globbing: _ordinal_ (`.` before `_`, but not adjacent)
    * Tab-completion: _linguistic_ (NLS)
  * GUI file manager (File Explorer): _linguistic_ (NLS), modified with natural number sorting

* **Linux**:
  * `ls`: _modified linguistic_: symbols sort together, but _after_ numbers (`.` before `_`) and _before_ letters (`.` before `_`)
  * GUI file manager: n/a (there is no single file manager across Linux distros)

Screen shots from running the test code with culture `en-US` (Windows) / `en_US.UTF-8` (macOS) / `en_US.utf8` (Linux) in effect, from left to right - the top two sections (`-- Ordinal sort` and `-- Lexical sort (current culture`) are just for reference and show .NET API behaviors: 
* PowerShell 7.3 on Windows 11
* PowerShell 7.3 on Windows 11 with NLS opt-in
* Windows PowerShell on Windows 11 
* PowerShell 7.3 on Linux (WSL, Ubuntu 20.04)
* PowerShell 7.3 on macOS Ventura

<img width="1220" alt="7__#$!@%!#__Pasted Graphic" src="https://github.com/PowerShell/PowerShell/assets/588825/add207c0-c9f3-42a5-aedd-b4e2bc67e25e">
