### ISSUE TITLE
Command for Set-Clipboard (-Path and -LiteralPath) parameter no longer exist

### ISSUE THREAD

**Issue by stephen147** [PowerShell/PowerShell#14758]
In version 5.0 and 5.1 there was a `-Path` and `-LiteralPath` parameter for `Set-Clipboard`.

Why was `-LiteralPath` and `-Path` removed or is that an oversight not to include them?

**Comment by mklement0** [comment]
_De facto_ I can tell you that _PowerShell Core_ supports only copying _plain text_ to the clipboard, which  you can see in https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Management/commands/management/Clipboard.cs

That is, all parameters relating _other_ data types that are supported in _Windows PowerShell_ are no longer present, namely:

* `-LiteralPath` and `-Path` for  copying _references to files_ to the clipboard.

* `-AsHtml` for copying HTML as such (rather than as plain text that happens to contain HTML markup) to the clipboard.

---

Given how `Set-Clipboard`  is implemented on _Unix-like platforms_, via external programs (`pbcopy` on macOS, `xclip` on Linux), support there is _inherently_ limited to plain text.

However, _on Windows_ I believe it is still _technically_ possible to support the same functionality as in Windows PowerShell.

I can't speak to what the design rationale was, however.

A possible motivation may have been to pare down the parameters to the lowest common denominator of functionality that is supported on _all_ platforms.

**Comment by mklement0** [comment]
A related issue is that for `Get-Clipboard`'s  Windows-specific `-Format`  and `-TextFormatType` parameters are no longer supported either - see #12290.

**Comment by mklement0** [comment]
Additionally,  it should  be possible to support `-LiteralPath` / `-Path` on those Linux platforms that support `xclip` (the only ones we currently support), because the `xclip` apt-get package additionally comes with utilities that support file-reference copying and pasting: `xclip-copyfile`, `xclip-cutfile`, and `xclip-pastefile`.

By contrast, the (preinstalled) `pbcopy` utility on macOS does _not_ support this.

**Comment by MartyIX** [comment]
Copying a file to clipboard was really useful. I hope it will come back one day.

**Comment by KalleOlaviNiemitalo** [comment]
For X11, [Inter-Client Communication Conventions Manual  (ICCCM) version 2.0 section 2.6.2](https://tronche.com/gui/x/icccm/sec-2.html) mentions the `FILE_NAME` target atom, which could be used for `Set-Clipboard -LiteralPath`. The xclip program appears to support `-target FILE_NAME`.

**Comment by KalleOlaviNiemitalo** [comment]
> utilities that support file-reference copying and pasting: xclip-copyfile, xclip-cutfile, and xclip-pastefile.

Those are unlikely to be interoperable with other applications because:

- They use the `SECONDARY` selection. Paste functions in other applications are advised to use the `CLIPBOARD` or `PRIMARY` selection, in <https://freedesktop.org/wiki/Specifications/ClipboardsWiki/>.
- They transfer not only file references but also the file contents, in tar.gz format. Regardless, they use the `STRING` target, which means _"ISO Latin-1 (+TAB+NEWLINE) text"_ according to the ICCCM. Other applications are unlikely to decode tar.gz, especially if mislabelled like this.

**Comment by KalleOlaviNiemitalo** [comment]
Instead of `FILE_NAME`, one could use [`text/uri-list`](https://www.iana.org/assignments/media-types/text/uri-list) with [File URI Specification](https://freedesktop.org/wiki/Specifications/file-uri-spec/), like in [Drag-and-Drop Protocol for the X Window System (XDND)](https://freedesktop.org/wiki/Specifications/XDND/). This would be suitable for copying multiple file references. Or even use both `FILE_NAME` and `text/uri-list` target atoms, but that would require changes in xclip, which currently supports only one target atom at a time.
