### ISSUE TITLE
Microsoft store version powershell should be up-to-date

### ISSUE THREAD

**Issue by Wongboo** [PowerShell/PowerShell#14772]
I've noticed that powershell version in GitHub, Nuget and Winget distribution are all up-to-date to 7.1.2.
I just can't believe that powershell version in microsoft store distribution is still 7.1.1, while preview sticks to v7.2.0-preview.2.And winget's  preview sticks to v7.2.0-preview.2 as well.
I thought that ms store and winget are designed to be official package manager in Windows 10, but ❓. I think microsoft official should better ensure version up-to-date on microsoft own distribution channel
It is really unhappy to see 
```
   A new PowerShell stable release is available: v7.1.2
   Upgrade now, or check out the release page at:
     https://aka.ms/PowerShell-Release?tag=v7.1.2
```
while you have no way to deal with it in microsoft-store-delivered powershell

**Comment by 237dmitry** [comment]
Today (7-8 hours ago) I updated it without any problems (to 7.1.2). The update was waiting to be installed, probably due to the fact that pwsh is always running.

**Comment by 237dmitry** [comment]
Sorry, It was update of Windows Terminal... ((

**Comment by Wongboo** [comment]
@237dmitry  yep, wt update today as well, in Microsoft Store. But that's not the case of powershell

**Comment by adityapatwardhan** [comment]
Its coming in a few days. Sorry for the delay.

**Comment by kilasuit** [comment]
This is a Monthly Reoccuring issue that gets raised & each time I mention that this is a known *non-issue* (because it's not a PowerShell issue) because the release pipeline that includes pushing the publishing request to the store has additional checks done for all software that is released in the store & as such means there is a known delay in new versions of PowerShell showing as available in the Store. 

you can read more in this comment - https://github.com/PowerShell/PowerShell/issues/14615#issuecomment-760601227

@adityapatwardhan - I think this can be closed as it's not a PowerShell Issue and we can't do more in PowerShell to make the release and availability in the store any quicker

**Comment by Wongboo** [comment]
But somehow windows terminal can update microsoft-store version the day github releases, I think there might be something to do with it. It's just a personal opinion

**Comment by danielwagn3r** [comment]
I think this get's attention because a new PowerShell instance informs about the newer release available, which isn't delivery through the store yet. With other distribution methods, like manual install [scoop](https://github.com/lukesampson/scoop) the update would be available already.

**Comment by DHowett** [comment]
> But somehow windows terminal can update microsoft-store version the day github releases, I think there might be something to do with it. It's just a personal opinion

This is because the store or store package is the _only_ supported way to get Terminal; we do not have an MSI or ZIP install, so we don’t run the risk of them getting out-of-sync.

**Comment by Wongboo** [comment]
@DHowett ,But "Microsoft.PowerShell-Preview" in winget isn't up-to-date even now, so maybe some automation can be done for winget-pkgs, more exactly it should be another issue
