### ISSUE TITLE
why i hate :base() in classes

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#14796]
he Guys !!

i hate this :base() in classes for multiple reasons:

1) its infrastructure code 
2) its not fluent with classes
3) other programmer dont understand this concept unique to PS 
4) why inheritence its not full supported
5) ...etc

**Comment by SeeminglyScience** [comment]
Are you talking about `: base()` like this?

```powershell
class B : A {
    B([int] $a) : base($a) {
    }
}
```

> 1. its infrastructure code
> 2. its not fluent with classes
> (...)
> 4. why inheritence its not full supported

Not sure what you mean, please elaborate.

> 3. other programmer dont understand this concept unique to PS

I haven't really heard many folks complaining about this specifically.  It doesn't come up super often, and typically only comes up when implementing existing .NET classes without a default constructor (and there's nothing PS can really do about that). Also it's not unique to PS. The same syntax is lifted from C# pretty directly, and the concept of calling base constructors exists in many languages.

**Comment by p0W3RH311** [comment]
@SeeminglyScience 

in other languages the inheritence is full supported. i mean when a class  inherit to a parent class it inherit automatically parent constructors. in PS we must use :base()

thanks

**Comment by SeeminglyScience** [comment]
Only if you define a constructor in the base class.  If you do that, there's no default constructor, so you have to tell it how to call the parent's constructor.  That's how the .NET runtime works and isn't something PowerShell can change.

**Comment by SpiritualBoss** [comment]
> he Guys !!
> 
> 
> 
> i hate this :base() in classes for multiple reasons:
> 
> 
> 
> 1) its infrastructure code 
> 
> 2) its not fluent with classes
> 
> 3) other programmer dont understand this concept unique to PS 
> 
> 4) why inheritence its not full supported
> 
> 5) ...etc
> 
> 
> 
>

**Comment by mklement0** [comment]
To build on @SeeminglyScience's comments with a **succinct summary of when you _must_ call `: base(...)` in a derived class' constructor in PowerShell (as well as in C#)**:

* You _must_ call a base-class constructor explicitly with `: base(...)` if the base class lacks an accessible _parameterless_ constructor. (Of course, if other accessible base-class constructors exist, you _may_ call them.)

* Conversely, if you do _not_ use `: base(...)`(and can get away with it), the (then by definition accessible) _parameterless_ base-class constructor is _implicitly_ called.

As such, the deciding factor is not whether the base class has a _default_ constructor, but whether there is an _accessible parameterless_ constructor - irrespective of whether this constructor is _implicit_ (the default constructor) or _explicit_, as it must be if the base class also defines _other_ constructors (which derived classes do _not_ inherit), by definition _with_ parameters.

* In PowerShell, classes (which includes `enum`s) and their members are _invariably_ `public` and therefore accessible to anyone; PowerShell classes lack support for access modifiers altogether.

   *  However, classes as a whole can _in effect_ be inaccessible due to existing in _different PowerShell scopes_ (which can be overcome with dot-sourcing for classes declared in _scripts_, and with `using module` for classes declared in _modules_).

   * With respect to class _members_, PowerShell only supports _hiding_ members with the `hidden` keyword, which, however, doesn't prevent _access_ and is only honored by the PowerShell engine and select cmdlets (a notable exception is #9847).

* In C#, the only way to make a base-class constructor _inaccessible_ to derived classes is by declaring it with one of the following access modifiers:

  * `private` (the default), which makes it inaccessible to _all_ derived classes.
  * `private protected` (C# 7.2+), which makes it inaccessible to derived classes _located in other assemblies_.

---

@p0W3RH311, given @SeeminglyScience's conclusion:

> That's how the .NET runtime works and isn't something PowerShell can change.

I think it makes sense to close this issue.
