### ISSUE TITLE
Row Data copied from excel is malformed from Clipboard 

### ISSUE THREAD

**Issue by phatmandrake** [PowerShell/PowerShell#14802]
MacOS and 7.1.2

## Steps to reproduce

Create a new blank Excel (16.47) Sheet and add data to 3 rows in a column:

![image](https://user-images.githubusercontent.com/24230425/107897352-6fb7d800-6efe-11eb-83ea-acc0c544cb0a.png)

Copy to the rows.

## behavior

```
(Get-Clipboard)[0].length

Returns 6

```

Should return length of string **5**.

![image](https://user-images.githubusercontent.com/24230425/107897706-6a0ec200-6eff-11eb-8303-3be3c44981d5.png)

There is a blank char (ASCII 13 Carriage Return) added to the end of the string. This causes text operators like -join to misbehave. Data copied from Google sheets does not have this issue and this is also not an issue for Powershell 7.1.2 on Windows.

## Environment data

![image](https://user-images.githubusercontent.com/24230425/107897859-df7a9280-6eff-11eb-9ada-4b533340a2c5.png)

**Comment by mklement0** [comment]
The problem is that when `Get-Clipboard` splits the text on the clipboard into individual lines (as it does, except if `-Raw` is passed), it only recognizes LF-only newlines as newlines, and retains the CR in Windows-style CRLF as _part of the lines_.

The problem is here:

https://github.com/PowerShell/PowerShell/blob/11a5d940c4f797be2b6f61c1bf619ccd3a667ce4/src/Microsoft.PowerShell.Commands.Management/commands/management/GetClipboardCommand.cs#L71-L72

That is, instead of exhibiting the usual _platform-agnostic_ newline treatment - recognizing CR-only, LF-only, and CRLF _interchangeably_ - only the _platform-native_ newline sequence is recognized.

Seemingly, Excel uses CRLF newlines even on macOS, which causes the problem.

A simpler way to reproduce the problem on macOS:

```powershell
PS> sh -c 'printf ''line 1\r\nline 2\r\n'' | pbcopy'; (Get-Clipboard) -replace "`r", '\r'
line 1\r
line 2\r

```

Also note the empty line at the end, which represent an extra, empty output string, which points to an unrelated secondary problem that isn't platform-specific and is also present in Windows PowerShell - see #14810
