### ISSUE TITLE
Add #Reqiures -CaseSensitive

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#14809]
## Summary of the new feature/enhancement
Having `#Requires -CaseSensitive` would help developers on case insensitive platforms ensure that the code will work on case sensitive platforms.

**Comment by jborean93** [comment]
AFAIK the only thing that is really case sensitive is the file system provider. Everything else, from accessing properties, calling methods, variable names, etc are case insensitive regardless of the platform. I'm not sure how effective making the filesystem case sensitive on a case insensitive fs would be considering the files themselves are not guaranteed to be the same case (or the same files altogether) across the various platforms. It would add more processing overhead to the fs provider which is already slowed down by all the other stuff it adds.

**Comment by Liturgist** [comment]
Because Windows filesystems are typically case insensitive, many developers are lulled into a "it-really-doesn't-matter" or "whatever" approach to both naming and referring to files. When the need to run the code on a case sensitive platform occurs, developers are stuck with a myriad of failures.

Yes, you can say it is their own darn fault. But the result is that it is a barrier to cross-platform PowerShell code. Yes, the build pipe should include testing on multiple platforms. The reality is that not all build environments have that capability.

I do not portend to know how such would be implemented in a FileSystem provider. But, I wonder if it would remove the need to monocase filenames for comparison with .ToUpper()/.ToLower(). Would this not improve speed performance?

Short of having `#Requires -CaseSensitive`, could PowerShell have an invocation switch on the executable to enable case sensitivity for testing?

**Comment by jborean93** [comment]
> many developers are lulled into a "it-really-doesn't-matter" or "whatever" approach to both naming and referring to files.

IMO that's what tests are for, test your code on the platforms it runs and you will pick up these issues. If you are building paths dynamically then it shouldn't matter as it's based on what is already there when your code runs. If you are building paths based on some project structure that you package up then yes this could be a problem but I personally don't think it's something PowerShell should care about. Testing honestly isn't that hard and if you are building modules or code then you really should invest more time in getting that set up right.

> But, I wonder if it would remove the need to monocase filenames for comparison with .ToUpper()/.ToLower(). Would this not improve speed performance?

I don't think so, it's not PowerShell that is making things case insensitive on Windows but rather Windows itself that is doing it. PowerShell is sending the request to .NET which then goes to Win32 [CreateFile](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew) which ultimately gets sent as a request to the NTFS driver and that does the lookup. This is where the case insensitive matching comes into place so to achieve what you are looking for you now need to add an extra check in PowerShell to validate the path taking up more CPU cycles. Granted this shouldn't be too expensive but it's definitely something to consider.

A potential work around for this use case is to enable case sensitivity on an NTFS folder so that any operations inside that folder are case sensitive. This is enabled on the file system layer and you can use [fsutil](https://devblogs.microsoft.com/commandline/per-directory-case-sensitivity-and-wsl/) to enable this on the dir(s) of your choice.

The filesystem case (in)sensitivity stems from layers deep down and not something PowerShell itself controls. To do so would require more code to validate the paths whenever it calls .NET which would happen in many locations. There's bound to be areas where this will be missed and PowerShell will not be able to guarantee 3rd party code will even respect this option leading to a bad UX when people complain the option doesn't work.

This is just my opinion and the PowerShell team may think differently, I just thought I would share why I don't think this is a good idea to implement.

**Comment by Liturgist** [comment]
Ok. Using `fsutil.exe` will probably be adequate.

https://devblogs.microsoft.com/commandline/per-directory-case-sensitivity-and-wsl/
https://www.windowscentral.com/how-enable-ntfs-treat-folders-case-sensitive-windows-10
