### ISSUE TITLE
Localhost Remoting doesn't work if you use Microsoft Accounts

### ISSUE THREAD

**Issue by LeeHolmes** [PowerShell/PowerShell#14866]
When logged on to your machine using a Microsoft Account (something that Microsoft is pushing on very hard), WinRM generates an error when you try to use loopback remoting (i.e.: for experimentation): “Connecting to remote server localhost failed with the following error message : WinRM cannot process the request. The following error with errorcode 0x8009030e occurred while using Negotiate authentication: A specified logon session does not exist. It may already have been terminated.”

You can work around this by “-EnableNetworkAccess” (which you shouldn't have to do), or using a local account. This also happens with Windows PowerShell, but is for sure a regression from some point in the past.

**Comment by jborean93** [comment]
Are you running as administrator beforehand? I know 2 or so years ago Microsoft stopped this from working with normal accounts due to a CVE that allows a limited access token to elevate to the admin token. I don’t fully agree with the CVE as UAC is not meant to be a security boundary but I doubt this will go back to the way it was before. More details are in https://devblogs.microsoft.com/powershell/windows-security-change-affecting-powershell/.

**Comment by LeeHolmes** [comment]
Yep - different error messages. This is a difference between Microsoft Accounts and local accounts.

**Comment by jborean93** [comment]
Ah my apologies, I wonder if it also affects a
non-loop back scenario, I.e from another windows host with the Microsoft account credentials. I know that NTLM has special behaviour when it comes to authenticating the implicit credentials over localhost so knowing whether it’s just the loop back scenario would help track that down.

Ultimately I don’t think the issue is with PowerShell itself as the logon process is all handled by the WinRM service and that’s where the error message is coming from. PowerShell could try and bypass it by automatically adding the `-EnableNetworkAccess` in this situation.

**Comment by SteveL-MSFT** [comment]
The authentication and logon is handled by WinRM and not directly by PowerShell.  This would have to be taken up by the owners of WinRM.
