### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sumandutta8877** [PowerShell/PowerShell#14911]
## Input Redirection Operator, have a limited capacity of input from a text file.

It can be implemented in such a way, that the capacity can be increased up to what the RAM can support.

**Comment by mklement0** [comment]
Can you please update your post to clarify what you're proposing? PowerShell doesn't have an input redirection operator (`<`).

**Comment by sumandutta8877** [comment]
Get-Content input.txt | program > output.txt

@mklement0

I am asking about this

**Comment by mklement0** [comment]
By default, `Get-Content` reads a file _line by line_ and sends each line through the pipeline as it is being read.

If you want to read more of a given file at once, to improve performance:

* You can read a file _as a whole_ with the `Get-Content -Raw` switch, which then outputs a _single, multiline_ string.
   * However, _external_ programs still receive individual lines.

* You can read a text file in _blocks of lines_ with the `Get-Content -ReadCount $numberOfLines`, but note that downstream _PowerShell commands_ then receive _arrays_ as input objects, not individual lines.
   * However, _external_ programs still receive individual lines.

If this is not what you're looking for, please clarify your use case and suggested improvement.

**Comment by sumandutta8877** [comment]
@mklement0 
The problem is with the number of lines that need to be read, and the length of the line.

It is limited, and cannot read a 3000*3000 2-D matrix entry.

**Comment by mklement0** [comment]
**Re number of lines:** 

There's no problem per se with reading a file with `3000*3000` == `9000000` == `9e6` == 9 million lines (though your matrix comment perhaps means that only `3000` lines exist, with `3000` columns each):

```powershell
Set-Content test.txt -Value (1..9e6) # create file with 9 million lines, sequentially numbered
(Get-Content -ReadCount 0 test.txt)[-1] # correctly outputs the last line, `9000000`
```

Note that `-ReadCount 0` is what makes this perform acceptably, because all lines are read into an array at once.

There is a _performance problem_, if you don't use `-ReadCount 0` (or `-Raw`), and the line-by-line processing is only part of it; a big part is the fact that each output line is decorated with ETS instance properties - see proposal #7537, which asks that an _opt-out_ from this decorating be implemented. To give a sense of the relative performance: with `-ReadCount 0`, the command finished in about 4 seconds on my machine; without it, it took almost 17 minutes(!).



**Re length of the line**:

I haven't looked at the source code, but there's no practical limit on the line length that I can detect:

```powershell
Set-Content test.txt -Value ('x' * 9e6) # create a single-line file with 9 million characters.
@(Get-Content test.txt)[0].Length # correctly outputs `9000000`
```

---

Please add a reproducible example to your initial post to show what isn't working, and what you would think should be done about it.

**Comment by sumandutta8877** [comment]
@mklement0 

You will just get what I am trying to say, only by looking in the two text file (input_test.txt & test.txt)

[https://drive.google.com/drive/folders/1XnUC5gTwKBB-xNtMFCtJiLFD5EiBlFAn?usp=sharing](url)
In this given folder, you will find one executable(helloCUDA_input_test.exe) file and one input(input_test.txt) file.

Get-Content -Raw input_test.txt | ./helloCUDA_input_test.exe
If you try to run with this command in PowerShell, then you get an error, due to the limit of PowerShell to read line

Get-Content -Raw test.txt | ./helloCUDA_input_test.exe
Where as here, the code runs easily, since it has not crossed the limit.

**Comment by mklement0** [comment]
That sounds more like a problem with your custom executable. I suggest you update the initial post with a reproducible example that uses only PowerShell commands or standard executables to demonstrate an actual problem with PowerShell itself.
