### ISSUE TITLE
-Exclude parameter on Get-Variable not working as expected

### ISSUE THREAD

**Issue by Giant-Kraken** [PowerShell/PowerShell#14935]
PowerShell version used: 7.1

commands:
`> $variables_to_exclude = (Get-Variable).Name`
`> $another_variable = "ABC"`
`> $b = "b"`
`> Get-Variable -Exclude $variables_to_exclude`

output:
`Name                           Value`
`----                           -----`
`another_variable               ABC`
`variables_to_exclude           {?, ^, $, args…}`

expected output should include variable $b too

**Comment by mklement0** [comment]
The problem seems to be limited to _single-character_ variable names.

**Comment by SteveL-MSFT** [comment]
The problem is that `(Get-Variable).Name` includes the `$?` variable.  However, `?` is a wildcard character for a single character.  So the cmdlet creates a collection of patterns based on `-exclude` which includes `?` matching any single character variable.  Since `-Exclude` explicitly accepts wildcard characters, this seems to be be-design.
