### ISSUE TITLE
BitsJob object can't be used by BITS-functions

### ISSUE THREAD

**Issue by AX502** [PowerShell/PowerShell#14948]
While working completely fine in pre installed PowerShell, I can't use the BitsJob object returned by Get-BitsTransfer or Start-BitsTransfer for other operations like Set-BitsTransfer or Remove-BitsTransfer.

## Steps to reproduce

```powershell
$bitsJobs = Get-BitsTransfer
Remove-BitsTransfer -BitsJob $bitsJobs 
```
OR
```powershell
Get-BitsTransfer | Remove-BitsTransfer
```

## Expected behavior

Get-BitsTransfer receives all existing BITS-Jobs and Remove-BitsTransfer removes them

## Actual behavior

BITS-Jobs can't be removed, because Remove-BitsTransfer doesn't accept the output from Get-BitsTransfer as input.

Using variable:
Remove-BitsTransfer: Error: "Value "Microsoft.BackgroundIntelligentTransfer.Management.BitsJob" of type "Deserialized.Microsoft.BackgroundIntelligentTransfer.Management.BitsJob" can't be converted to type "Microsoft.BackgroundIntelligentTransfer.Management.BitsJob"."

Using pipe: 
Remove-BitsTransfer: The input object cannot be bound to any parameters of the command because the command does not accept pipeline input or the input and its properties do not match any of the parameters that accept pipeline input. 

This behavior can also be observed in all other BITS-functions.

## Environment data

PSVersion                                 7.1.2
PSEdition                                  Core
GitCommitId                            7.1.2
OS                                           Microsoft Windows 10.0.17763
Platform                                  Win32NT
PSCompatibleVersions             {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion    2.3
SerializationVersion                 1.1.0.1
WSManStackVersion               3.0

**Comment by jborean93** [comment]
The issue here is the BITS module is run in an implicit remoting session because it doesn’t advertise that it can run in PowerShell. Implicit remoting starts a Windows PowerShell process and created proxy commands for the modules commands which just transfer the input and parameter to the remote session and outputs the data back to the local one. Unfortunately this boundary involves serialisation which converts the live objects to a dead deserialised object. It’s these deserialise objects that can no longer be pipelined like the BITS commands are expecting.

There are a few things you can do

* Run the whole statement with your pipelines in 1 script in the remote PSSession
* try and import the BITS module with `-SkipEditionCheck` so it’s loaded in PowerShell
* Petition the BITS team to make their modules compliant with PowerShell

**Comment by daxian-dbw** [comment]
@AX502 You can also try the experimental feature `PSImplicitRemotingBatching`. This feature examines the command typed in the shell, and if all the commands are implicit remoting proxy commands that form a simple pipeline, then the commands are batched together and invoked as a single remote pipeline. [See the details and an example here.](https://docs.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.1#psimplicitremotingbatching).
