### ISSUE TITLE
exponent as string

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#14958]
Hi Guys !!

this is a issue with various language and the display:

![Capture](https://user-images.githubusercontent.com/36144546/110250841-6c7a9f80-7f32-11eb-9f00-efa9b6fc7a98.PNG)

as you can see in different languages the display is not cutted (don't worry with awk)...in PS the manipulation of the display is not easy...fo example triying working to programming bitcoin signature verfication is not easy with this syntax...

please implement i new operator exponential like "**" or even "^" or add a method to display the number as is.

thanks

**Comment by p0W3RH311** [comment]
i found i solution:

```
PS C:\> [bigint][math]::Pow(2,256)
115792089237316195423570985008687907853269984665640564039457584007913129639936
PS C:\>
```

but its not _fluent_

**Comment by mklement0** [comment]
I like the idea of an exponentiation _operator_, but the idea was rejected quite some time ago: #3603

In this particular case, an operator could situationally, with a `[bigint]` operand, choose `[bigint]::pow()` over the always-`[double]` `[math]::Pow`,  which would implicitly solve your _display_ problem:

```powershell
PS> [bigint]::Pow(2n, 256)
115792089237316195423570985008687907853269984665640564039457584007913129639936
```

Seemingly, PowerShell simply uses (culture-sensitive) `.ToString("G")` number display formatting (see https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings), which in the case at hand results in exponential notation:

```powershell
PS> 115792089237316195423570985008687907853269984665640564039457584007913129639936
1.15792089237316E+77
```

In the case of _integers_, your `[bigint]` cast is a quick workaround; otherwise, use something like `.ToString('f')`:

```powershell
PS> $d = 115792089237316195423570985008687907853269984665640564039457584007913129639936; $d.ToString('f')
115792089237316195423570985008687907853269984665640564039457584007913129639936.000
```

---

At least hypothetically, tackling the display problem by changing the default number formatting to be more helpful is an option, given that specific display formats aren't considered part of the public contract, but I see two concerns:

* performance
* getting consensus on when to spell out the digits (and how many decimal places) vs. when to use exponential notation.

**Comment by 237dmitry** [comment]
`iex "1$('*2' * 256)n"` :)

**Comment by vexx32** [comment]
WG-Engine:

We recognise this would be useful to some users, but we don't feel as though it is a priority to tackle at present. There are existing workaround via .NET methods that are already available both for double and BigInteger types.

However, we would definitely consider accepting a PR for an exponentiation operator `**` from the community, with the caveat up-front that it would also most likely be a fairly low priority to review and get merged. It would also need review from the Language WG as it would be a language level change.

Marking this as up for grabs for now. 🙂

**Comment by earthdiver** [comment]
If the use case is solely to use the PowerShell console as a calculator, creating a function like the one I wrote ( available at https://qiita.com/earthdiver1/items/1eb0ceec7fd54b80d892#pscalcpsm1 ) might be a temporary solution, at least for the time being.
