### ISSUE TITLE
set-content and get-content's -encoding parameter doesn't tab complete to all options

### ISSUE THREAD

**Issue by jszabo98** [PowerShell/PowerShell#15000]
## Steps to reproduce

I think this inhibits discovery.

```powershell
set-psreadlineoption -editmode emacs
'hi there' | set-content file -encoding #press tab

# for example this works for ebcdic (or ibm037):
'hi there' | set-content file -encoding ebcdic-cp-us
```

## Expected behavior

```none
# many encodings, more than listed by [System.Text.Encoding]::GetEncodings()
```

## Actual behavior

```none
ascii             bigendianutf32    unicode           utf8              utf8NoBOM
bigendianunicode  oem               utf7              utf8BOM           utf32
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
On Windows ` ([System.Text.Encoding]::GetEncodings()).count` returns 116 - this is too much to be useful.

**Comment by jszabo98** [comment]
I don't think this is too horrible if tab shows all options at once.  Plus there's the benefit of knowing this improvement actually exists.  It's like pressing tab after get-childitem in a folder with at least 100 files.  It can be limited by typing the first few characters.  It will ask first if you want to display all possibilities.  (based on https://adamtheautomator.com/powershell-tab-completion/)

```powershell
function Do-Thing {
    [CmdletBinding()]
    param(
        [Parameter()]
        [string]$Name
    )
    $Name
}

$scriptBlock = { [System.Text.Encoding]::GetEncodings().name }

Register-ArgumentCompleter -CommandName Do-Thing -ParameterName Name -ScriptBlock $scriptBlock


do-thing -name #tab

Display all 138 possibilities? (y or n) _

# 87x35

IBM037                   IBM01146                 x-cp20001                iso-8859-1
IBM437                   IBM01147                 x-Chinese-Eten           iso-8859-2
IBM500                   IBM01148                 x-cp20003                iso-8859-3
ASMO-708                 IBM01149                 x-cp20004                iso-8859-4
DOS-720                  utf-16                   x-cp20005                iso-8859-5
ibm737                   utf-16BE                 x-IA5                    iso-8859-6
ibm775                   windows-1250             x-IA5-German             iso-8859-7
ibm850                   windows-1251             x-IA5-Swedish            iso-8859-8
ibm852                   Windows-1252             x-IA5-Norwegian          iso-8859-9
IBM855                   windows-1253             us-ascii                 iso-8859-13
ibm857                   windows-1254             x-cp20261                iso-8859-15
IBM00858                 windows-1255             x-cp20269                x-Europa
IBM860                   windows-1256             IBM273                   iso-8859-8-i
ibm861                   windows-1257             IBM277                   iso-2022-jp
DOS-862                  windows-1258             IBM278                   csISO2022JP
IBM863                   Johab                    IBM280                   iso-2022-kr
IBM864                   macintosh                IBM284                   x-cp50227
IBM865                   x-mac-japanese           IBM285                   EUC-CN
cp866                    x-mac-chinesetrad        IBM290                   euc-kr
ibm869                   x-mac-korean             IBM297                   hz-gb-2312
IBM870                   x-mac-arabic             IBM420                   GB18030
windows-874              x-mac-hebrew             IBM423                   x-iscii-de
cp875                    x-mac-greek              IBM424                   x-iscii-be
shift_jis                x-mac-cyrillic           x-EBCDIC-KoreanExtended  x-iscii-ta
gb2312                   x-mac-chinesesimp        IBM-Thai                 x-iscii-te
ks_c_5601-1987           x-mac-romanian           koi8-r                   x-iscii-as
big5                     x-mac-ukrainian          IBM871                   x-iscii-or
IBM1026                  x-mac-thai               IBM880                   x-iscii-ka
IBM01047                 x-mac-ce                 IBM905                   x-iscii-ma
IBM01140                 x-mac-icelandic          IBM00924                 x-iscii-gu
IBM01141                 x-mac-turkish            EUC-JP                   x-iscii-pa
IBM01142                 x-mac-croatian           x-cp20936                utf-7
IBM01143                 utf-32                   x-cp20949                utf-8
IBM01144                 utf-32BE                 cp1025
IBM01145                 x-Chinese-CNS            koi8-u
```

**Comment by iSazonov** [comment]
> It's like pressing tab after get-childitem in a folder with at least 100 files.

If you want speculate I do too :-) and I can argue that 99.99999% of systems, users, and scripts in modern World use Unicode and they haven't need to transcode, specially in interactive sessions, and specially using 116 locales at the same time. Of course, there may still be outdated applications that use an old encoding, but most of them fall under the OEM encoding.
Thus, you condemn to look for Utf8 in a huge list, which will only annoy most users.

As for the statement
> It's like pressing tab after get-childitem in a folder with at least 100 files.

we have already an issue with a request to improve this because the behavior for large folders is annoying users.

**Comment by jszabo98** [comment]
Point taken.  I would says most people use ascii or utf-8, not the ambiguous term unicode or utf16-le, unless they're using it accidentally in powershell 5 by using the ">" operator.

**Comment by mklement0** [comment]
The status quo:

The tab completions are currently limited to a set of hard-coded values, mirroring the public [`Microsoft.PowerShell.Commands.FileSystemCmdletProviderEncoding`](https://docs.microsoft.com/en-US/dotnet/api/Microsoft.PowerShell.Commands.FileSystemCmdletProviderEncoding) enum that was used in WinPS to type the `-Encoding` parameters.

Since these enum values, with the exception of `Unicode`, aren't directly supported by `System.Text.GetEncoding()`, a custom transformation for obtaining the relevant `Encoding` instance is used.

As an aside: a notable omission from this enumeration is `ANSI`, as an analog to WinPS' `Default` - see https://github.com/PowerShell/PowerShell/issues/6562#issuecomment-576812956

---

I do think it would be helpful to tab-complete _all_ available encodings, as along as it doesn't harm completion performance - the proof-of-concept below demonstrates that it doesn't.

That a _great number_  of completions may result is no argument against enumerating all valid values:

* It's not an issue if you type a *prefix* of the desired value to sufficiently narrow down the matching completion, such as `un<tab>`

* It's not an issue with editing modes `Windows` (default on Windows) and `vi`, because the completions are cycled through _in-line_; the predefined PS enumeration values can be cycled through _first_ (as also demonstrated below).

* With `emacs` editing mode, it can be inconvenient, but that issue should be solved _generically_, as a tab-completion _UI issue_ - which is a separate debate.

---

The following proof-of-concept creates a sample `Get-Foo` cmdlet ad hoc, whose `-Encoding` parameter cycles through all available encodings, starting with the PS-only enumeration values.

Note:
  * `.Name` and `.CodePage` values are used for completion, so that you can also do something like
`Get-Foo -Encoding 12<tab>` to cycle through available ANSI code pages such as `1252`.
 * I don't know what it would take to support _aliases_ such as `'ebcdic-cp-us'`, because they're _not_ part of the `System.Text.EncodingInfo` instances returned by `System.Text.GetEncodings()`; the `.Name` property value of this encoding is `IBM037`.

As you'll see, there's no performance problem.

```powershell
Add-Type @'
using System;
using System.Management.Automation;
using System.Text;
using System.Linq;

namespace demo
{

  // Define an argument completer for all available encodings.
  class ArgumentCompletionsCalculated: ArgumentCompletionsAttribute
  {
      private static readonly string[] PsEncodingNames = {
        "Ascii", "BigEndianUnicode", "BigEndianUtf32", "OEM", "Unicode", "Utf7", "Utf8", "Utf8Bom", "Utf8NoBom", "Utf32"
      };

    // Static method that calculates the arguments.
    private static string[] GetValues()
    {
      var encodings = Encoding.GetEncodings();
      return PsEncodingNames.Concat(encodings.Select(e => e.Name)).Concat(encodings.Select(e => e.CodePage.ToString())).ToArray();
    }
    // Call the base constructor with the return value from the static method.
    public ArgumentCompletionsCalculated() : base(GetValues()) 
    {
    }

  }

  // Define cmdlet 'Get-Foo'
  [Cmdlet("Get", "Foo")]
  public class GetFooCmdlet : PSCmdlet {
    Encoding _encoding = null;

    [Parameter(Position=0)]
    [ArgumentCompletionsCalculated]
    public object Encoding { get { return _encoding; } set { _encoding = value as int? != null ? System.Text.Encoding.GetEncoding((int) value): System.Text.Encoding.GetEncoding(value.ToString()); } }

    protected override void ProcessRecord() {
      WriteObject(Encoding);
    }
  }
  

}
'@  -PassThru | % Assembly | Import-Module
```

**Comment by SeeminglyScience** [comment]
> * It's not an issue with editing modes `Windows` (default on Windows) and `vi`, because the completions are cycled through _in-line_; the predefined PS enumeration values can be cycled through _first_ (as also demonstrated below).

It's still a pain with <kbd>Ctrl</kbd> + <kbd>Space</kbd> though. Most of the time I'm hitting that first to get an idea what I'm even lookin' for.

I think adding more completion options that very few folks are ever going to need is going to hinder more folks than it helps. A ton of completion options isn't necessarily always a bad thing, but it isn't harmless and I just don't know what benefit it really adds here to offset that.  Those who want it can easily add it to their profile with:

```powershell
Register-ArgumentCompleter -CommandName Get-Content -ParameterName Encoding -ScriptBlock {
	"Ascii"
	"BigEndianUnicode"
	"BigEndianUtf32"
	"OEM"
	"Unicode"
	"Utf7"
	"Utf8"
	"Utf8Bom"
	"Utf8NoBom"
	"Utf32"
	[Text.Encoding]::GetEncodings().Name
}
```

**Comment by mklement0** [comment]
Note: While this issue in isolation may not be all that important in the grand scheme of things, I think it's important to get clarity on how to solve this problem _in general_.

---

> It's still a pain with Ctrl + Space though.

That's the _UX problem_ that needs solving, irrespective of the specific completion at hand:

* Using the current features, as a stopgap, the simpler solution that doesn't take away from showing _all_ available values is to put something like the following in one's profile to increase the threshold for the "display n possibilities?" prompt: 
`Set-PSReadLineOption -CompletionQueryItems 1000` 

* `PSReadLine` could be improved, however:
  * It could handle the default threshold - currently hard-coded at `100` - more intelligently, such as basing it on the console window dimensions.
  * If the count of completions doesn't fit at once, _show as many as will fit at once_ as defined by the threshold, indicating the fact that the listing is incomplete, and offering _in-place paging_ (like `more`, but in a fixed part of the window).

---

As for the specific case of `-Encoding`:

* Especially on Unix, and increasingly on Windows, having to use `-Encoding` at all is rare, given the prevalence of UTF-8.
* Conversely, when you _do_ need it, it may be with a less common encoding, and that's completing _all_ valid values is helpful.

**Comment by jszabo98** [comment]
A bit of a sidenote, but the displaynames of the encodings of the docs are completely different.  Over 30 kinds of ebcdic!  https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding?view=net-5.0#list-of-encodings

**Comment by p0W3RH311** [comment]
> 
> 
> On Windows ` ([System.Text.Encoding]::GetEncodings()).count` returns 116 - this is too much to be useful.

its good if the list its too long to add a pause in every screen

**Comment by mklement0** [comment]
I've created a PSReadLine feature request at https://github.com/PowerShell/PSReadLine/issues/2306.

**Comment by joeyaiello** [comment]
@JamesWTruher as FYI, him and I worked closely on the original work to define the current encoding values in the `Microsoft.PowerShell.Commands.FileSystemCmdletProviderEncoding` enum that @mklement0 referenced

Throwing an External label on this one as it does appear to be a PSReadline thing.

**Comment by mklement0** [comment]
Thanks, @joeyaiello:

* In terms of _what completions to offer_, it is a PowerShell thing.

* in terms of _how to present them to the user_, it is a PSReadLine thing.
