### ISSUE TITLE
PowerShell class should have an InvokeAndClear() method

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#15008]
## Summary of the new feature/enhancement

A classic pitfall of the `PowerShell` class is doing something like this:

```csharp
using (var pwsh = PowerShell.Create())
{
    DateTime? firstDate = pwsh.AddCommand("Get-Date").Invoke<DateTime?>().FirstOrDefault();
    DateTime? secondDate = pwsh.AddCommand("Get-Date").Invoke<DateTime?>().FirstOrDefault();

    Console.WriteLine($"1: {firstDate}");
    // secondDate is null??
    Console.WriteLine($"2: {secondDate}");
}
```

In this scenario, the PowerShell object's state is affected by the first `AddCommand()` call and we need to clear the commands. This is easily seen here but when `pwsh` is a field being shared between calls it can be subtle.

In a lot of my code I end up writing this:

```csharp
static class PowerShellExtensions
{
    public static Collection<PSObject> InvokeAndClear(this PowerShell pwsh) => pwsh.InvokeAndClear<PSObject>();

    public static Collection<T> InvokeAndClear<T>(this PowerShell pwsh)
    {
        try
        {
            return pwsh.Invoke<T>();
        }
        finally
        {
            pwsh.Commands.Clear();
        }
    }
}
```

We should consider adding that to the PowerShell SDK, since I suspect this is a very common use case.

**Comment by SeeminglyScience** [comment]
Also the error, verbose, etc streams

**Comment by mklement0** [comment]
Just to spell it out, because the fact that your sample code actually _does_ work confused me:

The commands _accumulate_ in the `pwsh.Commands` collection, and subsequent `.Invoke()` calls try to execute them _all_, in addition to accumulating stream output in `pwsh.Streams` across calls, as @SeeminglyScience  points out.

Your second `.Invoke()` call is therefore roughly equivalent to:

```powershell
[powershell]::Create().AddCommand("Get-Date").AddCommand("Get-Date").AddArgument('1970-01-01').Invoke()
```

which in turn is equivalent to:

```powershell
Get-Date | Get-Date
```

and the latter just _happens_ to work, because `Get-Date` also accepts a `[datetime]` instance via the pipeline, so this pipeline is in effect the same as just calling `Get-Date` alone.
Adding a `-Date` argument to the 2nd `GetDate` call would surface the problem, however, because something like `Get-Date | Get-Date 1970-01-01` indeed fails.

---

As for the API surface and your extension method:

If the intent is to also clear the _streams_, you cannot include `.Streams.ClearStreams()` in the `.InvokeAndClear()` method, as you would instantly wipe out the `.Invoke()` call's non-success stream output.

So I wonder if something along the following lines is called for instead:

A fluent `.Reset()` method that calls `.Commands.Clear()` and `.Streams.ClearStreams()` and returns the PowerShell instance itself, as the existing methods do.

This means that resetting can then either be performed stand-alone:

```csharp
pwsh.Reset();  // same as: .Commands.Clear(); .Streams.ClearStreams(); return this;
```

Or, fluently, as part of recurring invocations on a reusable `PowerShell` instance:

```csharp
pwsh.Reset().AddCommand("Get-Date").Invoke<DateTime?>().FirstOrDefault();
```

**Comment by Fs00** [comment]
I would definitely love to see a `PowerShell.Reset()` method as proposed by @mklement0!
I've found myself doing `pwsh.Commands.Clear(); pwsh.Streams.ClearStreams();` too (and once discovered the hard way that I had to).

**Comment by rjmholt** [comment]
Quick thought since I have the issue open:

```csharp
[Flags]
public enum PowerShellClearOptions
{
    None = 0x0,
    Commands = 0x1,
    Streams = 0x2,
}

...

public PowerShell Reset() => Reset(PowerShellClearOptions.Commands);

public PowerShell Reset(PowerShellClearOptions clearOptions)
{
    if (clearOptions.HasFlag(PowerShellClearOptions.Commands))
    {
        Commands.Clear();
    }

    if (clearOptions.HasFlag(PowerShellClearOptions.Streams))
    {
        Streams.Clear();
    }
    
    return this;
}
```

I suggest that because in various scenarios, I don't want to clear the streams.
