### ISSUE TITLE
([PSCustomObject]@{}).Count returns 1

### ISSUE THREAD

**Issue by wikiped** [PowerShell/PowerShell#15021]
## Steps to reproduce

```
([PSCustomObject]@{}).Count
```

## Expected behavior

```
0
```

## Actual behavior

```
1
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
`.Count` is not a property of the created object. `[PSCustomObject]@{}` creates one object with zero properties attached. Ergo, you have a count of 1. 

This is by design for how the `.Count` auto-property works; if you don't have a collection object, `.Count` will be `1` for non-null objects, and `0` for null.

**Comment by wikiped** [comment]
Gotcha.
Thanks for clarifying this.
