### ISSUE TITLE
Expand-PSLanguage cmdlet  to expand the PS language with PS

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#15045]
hi Guys !!

yes its crazy but the idea is like a framework its use _Dynamic AST keyword_ , string manipulation and the _event-typing_:
```

PS C:\> $ExecutionContext.SessionState.InvokeCommand.CommandNotFoundAction
PS C:\> $ExecutionContext.SessionState.InvokeCommand.PreCommandLookupAction
PS C:\> $ExecutionContext.SessionState.InvokeCommand.PostCommandLookupAction
PS C:\> $ExecutionContext.SessionState.InvokeCommand.LocationChangedAction

```
create a json file with predefined keyword (json schema maybe ?) keyword like: MetaKeyword (the name of the new keyword) , MetaArguments (the arguments of MetaKeyword with type if necessarly), String (the string expanded by the macro MetaKeyword), Code ( in json key: the code typed by the user and in there value: the code transformation) 
for example with simple example  `'unless ($condition) { $body }': 'if (!($condition)) { $body }'` in this example i use $condition and $body its a special variable to determine an unspecified code.

then we use the new pre-processor Cmdlet `Expand-PSLanguage -JsonFile $json` 

this feature will add more meta programming within PS

**Comment by vexx32** [comment]
While the implementation differs in your suggestions, dynamic language keywords are already something that is built into the engine.

I can't say I'd really recommend using them, though. Neither the current dynamic keyword implementation nor your suggestion really seems to differ much from simply creating a function to do that directly:

```ps
function unless {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory, Position = 0)]
        [bool]
        $Condition,

        [Parameter(Mandatory, Position = 1)]
        [scriptblock]
        $Body
    )
    if (-not $condition) {
        & $Body
    }
}
```

There would be scoping differences, but those are not entirely insurmountable, and you still have more flexibility in terms of how you choose to implement any aspect of it.

**Comment by p0W3RH311** [comment]
@vexx32 

thanks, but this pre-processor technic are expanded before the execution of the code (like in c with `string ` json key), function can't because it gets called at runtime

```
some code
my_new_metakeyword_contains_text # change in a text
some code
```

The downside to implementing this pre-processor engine instead of a function is that pre-processor definitions are more complex than function definitions because you’re writing powershell code that writes powershell code...but in final it offers new capabilities

**Comment by SeeminglyScience** [comment]
`DynamicKeyword` was an interesting experiment.  Really cool idea, but it highlights how nearly insurmountable of a challenge it is to get the UX right for "parser extensions" in PowerShell.  Your extension would need to be registered *before any script utilizing it is parsed for the first time*. Dynamic loading is also probably out since it would require implicit code invocation at parse time which is sort of a nightmare to secure.

As much as I would absolutely *love* for there to be a way to extend the parser, it's such a huge challenge for such a small audience that I don't see it happening.

---

The closest we're going to get is if someone writes a transpiler with add-on support. A build step eliminates all of those problems.

There are a lot of potential use cases for a transpiler, but that work would likely need to be a separate project.  Similar to typescript > javascript.
