### ISSUE TITLE
dir *.  has no output

### ISSUE THREAD

**Issue by UnkleUnkle** [PowerShell/PowerShell#15076]
```dir *.exe``` or ```dir *.*``` works as intended. However, the expected output of ```dir *.``` (displaying all folders in the current working directory) is not functioning. Instead, a workaround is to type ```cmd /c "dir *."```

## Steps to reproduce

In pwsh, go to a folder with subfolders.
enter command ```dir *.```

## Expected behavior

displays all subfolders in cwd (and no other file types)

## Actual behavior

No output, no errors

## Environment data

PSVersion = 7.1.3
PSEdition = Core
GitCommitId = 7.1.3
OS = Microsoft Windows 10.0.19042
Platform = Win32NT
PSCompatibleVersions = {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion = 2.3
SerializationVersion = 1.1.0.1
WSManStackVersion = 3.0

**Comment by vexx32** [comment]
I can see the logic here, but I think the `dir *.` behaviour in cmd.exe is more of a workaround for not having an explicit directory filter than anything else.

For the same in PowerShell, use the -Directory flag; `Get-ChildItem -Directory` / `dir -d`

**Comment by doctordns** [comment]
As DIR is just an alias to Get-ChildItem, you could j ust do this:

```console
PS C:\Foo> Get-ChildItem -Directory

    Directory: C:\Foo

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          05/10/2019    16:11                .rcedit
d----          25/05/2018    10:47                .vscode
d----          22/01/2018    11:55                3rdParty
d----          23/10/2020    14:51                7zip
d----          04/11/2020    14:31                Archive
d----          05/12/2020    15:23                AUDIT
d----          22/01/2018    11:55                azure
...
```

**Comment by mklement0** [comment]
Good point, @vexx32, but note that alias `-d` for `-Directory` doesn't actually work and will be removed - see #14700

@UnkleUnkle, for listing _directories_, @vexx32's solution is the best approach (your command would also include _files_ that happen to have _no filename extension_), but just to explain your symptom:

The fundamental problem is that in `cmd.exe` and in the WinAPI file-enumeration APIs wildcard expressions have special behavior built in that _PowerShell_'s [wildcard expressions](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Wildcards) do not.

If you want to get the same behavior as in `cmd.exe`, use the `-Filter` parameter rather than the (positionally implied) `-Path` parameter (the latter uses only PowerShell's wildcards):

```powershell
gci -Filter *.  # by contrast `dir *.` is the same as  `gci -Path *.` and therefore `Get-ChildItem -Path *.`
```

(I've used alias `gci` for [`Get-ChildItem`](https://docs.microsoft.com/powershell/module/microsoft.powershell.management/get-childitem), because using the alias `dir` can cause confusion, notably the expectation that everything works as in `cmd.exe`
You can shorten `-Filter` to `-fi`, which is the shortest prefix that unambiguously identifies the `-Filter` parameter; generally, aliases and parameter-name prefixes should only be used interactively, not in scripts).

---

As for why PowerShell's wildcard expressions behave differently: they are not specific to matching _file names_, but are used pervasively throughout PowerShell and therefore match any input string as-is, without making assumptions about a `.` being special, for instance.

Therefore, wildcard `*.` matches any string that _ends in a verbatim `.`_, which file names generally don't do.
E.g., `'foo' -like '*.'` is `$false`, whereas `'foo.' -like '*.'` and `'.' -like '*.'` are `$true`.

**Comment by UnkleUnkle** [comment]
Hmm, I see. Very good explanation of how and why it does this, and I'll go ahead and close the issue  I wouldn't be surprised if others open issues about this later, and personally I think that when PowerShell uses older cmd/dos style commands, it should try to emulate its output rather than just alias a standard PowerShell command.

**Comment by mklement0** [comment]
@UnkleUnkle, I hear you, but since PowerShell never intended to fully emulate the behavior and syntax of legacy shell commands, the better approach would have been to never introduce aliases that falsely suggest just that - unfortunately, that ship has sailed.

I recommend using only the aliases that are based on PowerShell's own naming conventions, such as `gci`.
The `g` part  - the verb - is standardized, while the noun part isn't, however (it can't be, given that it's open-ended).

To see what alias prefix corresponds to which [approved verb](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands), use the [`Get-Verb`](https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/get-verb) cmdlet; e.g. (note the `AliasPrefix` column):

```powershell
PS> Get-Verb Get

Verb AliasPrefix Group  Description
---- ----------- -----  -----------
Get  g           Common Specifies an action that retrieves a resource
```
