### ISSUE TITLE
Feature Request: add parameter -CurrentUser for Get-Process

### ISSUE THREAD

**Issue by FredVH** [PowerShell/PowerShell#15093]
Hi

Sometimes I need to check if a process is running for the current user (non-admin on terminal server). Now I use `get-process -Name "ProcessName" | ? { $_.SI -eq $([System.Diagnostics.Process]::GetCurrentProcess().SessionId) }`. But it would be much easier if I could use `get-process -Name "ProcessName" -CurrentUser`.

Kind regards
Frederik.

**Comment by mklement0** [comment]
Making this easier sounds like a good idea, but for consistency with other cmdlets we should probably use a `-Scope` parameter with enumeration values such as `AllUsers` (default), `CurrentUser`, and,  perhaps also, `OtherUsers`.

Also, we need to ensure cross-platform consistency:

`Get-Process  | ? { $_.SI -eq $([System.Diagnostics.Process]::GetCurrentProcess().SessionId) }`, which can be simplified to `Get-Process | ? SI -eq (Get-Process -Id $PID).SI` presents two problems:

* On _Windows_, it includes _additional_ processes that are _not_ owned by the current user.

* On _Unix_-like platforms, it is in effect limited to the calling PowerShell sessions and child processes directly launched from it.

_Conceptually_, what we're looking for (for `-Scope CurrentUser`)  is this:

```
Get-Process -IncludeUserName | ? UserName -eq (whoami)
```

This works well on _Unix_-like platforms, but - unfortunately - requires _elevation_ on Windows.

**Comment by jborean93** [comment]
> requires elevation on Windows.

That's just what `Get-Process` states but it's not the whole truth. Yes you need elevation to get the username of processes run by other users (or elevated ones of the current user) but it is still possible to get the token information for the majority of the processes run by the current user.

```powershell
Add-Type -TypeDefinition @'
using Microsoft.Win32.SafeHandles;
using System;
using System.Runtime.InteropServices;

namespace Win32
{
    public class NativeHelpers
    {
        [StructLayout(LayoutKind.Sequential)]
        public struct TOKEN_USER
        {
            public SID_AND_ATTRIBUTES User;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct SID_AND_ATTRIBUTES
        {
            public IntPtr Sid;
            public int Attributes;
        }
    }
    
    public class NativeMethods
    {
        [DllImport("kernel32.dll", SetLastError = true)]
        public static extern bool CloseHandle(
            IntPtr hObject);

        [DllImport("Advapi32.dll", SetLastError = true)]
        public static extern bool GetTokenInformation(
            SafeHandle TokenHandle,
            int TokenInformationClass,
            IntPtr TokenInformation,
            int TokenInformationLength,
            out int ReturnLength);

        [DllImport("Advapi32.dll", SetLastError = true)]
        public static extern bool OpenProcessToken(
            SafeHandle ProcessHandle,
            int DesiredAccess,
            out IntPtr TokenHandle);
    }

    public class SafeNativeHandle : SafeHandleZeroOrMinusOneIsInvalid
    {
        public SafeNativeHandle() : base(true) { }
        public SafeNativeHandle(IntPtr handle) : base(true) { this.handle = handle; }

        protected override bool ReleaseHandle()
        {
            return NativeMethods.CloseHandle(handle);
        }
    }
}
'@

$currentUser = [Security.Principal.WindowsIdentity]::GetCurrent().User

Get-Process | Where-Object {
    if (-not $_.SafeHandle -or $_.SafeHandle.IsInvalid -or $_.SafeHandle.IsClosed) {
        return
    }

    $rawAccessToken = [IntPtr]::Zero
    $res = [Win32.NativeMethods]::OpenProcessToken(
        $_.SafeHandle,
        0x00000008,  # TOKEN_QUERY
        [ref]$rawAccessToken
    ); $err = [Runtime.InteropServices.Marshal]::GetLastWin32Error()

    if (-not $res) {
        $exp = [ComponentModel.Win32Exception]$err
        Write-Warning -Message "Failed to open access token for $($_.Id): $($exp.Message)"
        return
    }

    $accessToken = [Win32.SafeNativeHandle]::new($rawAccessToken)
    try {
        $userLength = 0
        $tokenUserId = 1  # TOKEN_USER

        $null = [Win32.NativeMethods]::GetTokenInformation(
            $accessToken,
            $tokenUserId,
            [IntPtr]::Zero,
            0,
            [ref]$userLength
        )
        $tokenInfo = [Runtime.InteropServices.Marshal]::AllocHGlobal($userLength)
        try {
            $res = [Win32.NativeMethods]::GetTokenInformation(
                $accessToken,
                $tokenUserId,
                $tokenInfo,
                $userLength,
                [ref]$userLength
            ); $err = [Runtime.InteropServices.Marshal]::GetLastWin32Error()

            if (-not $res) {
                $exp = [ComponentModel.Win32Exception]$err
                Write-Warning -Message "Failed to get TOKEN_USER for $($_.Id): $($exp.Message)"
                return
            }

            $tokenUser = [Runtime.InteropServices.Marshal]::PtrToStructure(
                $tokenInfo, ([type][Win32.NativeHelpers+TOKEN_USER]))

            $processUser = [Security.Principal.SecurityIdentifier]::new($tokenUser.User.Sid)

            $processUser.Equals($currentUser)
        }
        finally {
            [Runtime.InteropServices.Marshal]::FreeHGlobal($tokenInfo)
        }
    }
    finally {
        $accessToken.Dispose()
    }
}
```

The DACL of a standard/limited access token gives query/read access to the following accounts

![image](https://user-images.githubusercontent.com/8462645/112414779-62e49a80-8d6e-11eb-80a9-c4f3a2ad9221.png)

and the following for an admin one

![image](https://user-images.githubusercontent.com/8462645/112414863-8a3b6780-8d6e-11eb-8728-62b1f8a90826.png)

There are other complications when it comes to getting a copy of the process token (not the same as the access token) which stops you from getting the access token of elevated processes.

> it includes additional processes that are not owned by the current user.

In addition to this, filtering by the session id means you will miss out on processes for that user that are run in a separate session (task scheduler, network logon/winrm, services).

**Comment by mklement0** [comment]
Thanks, @jborean93, great information.

So it sounds like it's also worth reconsidering the behavior of `-IncludeUserName`, to make it work in a best-effort manner when running without elevation.

Using `-Scope CurrentUser` _without elevation_ would then not include same-user processes running _with_ elevation, if I understand correctly.

The question then becomes how to handle inaccessible processes: reporting them all as _errors_ would generate a lot of noise even in the case where you know the limitations of the call.

So - unless _specific_ PIDs or names are also asked for - perhaps a single blanket _warning_ could be emitted, along the lines of (borrowing in part from the `Get-Process -IncludeUserName` error message):

`WARNING: Results may be incomplete due to lack of permissions. To see complete results, run the command  in a session that has been opened with elevated user rights (that is, Run as Administrator).`

**Comment by jborean93** [comment]
What you propose sounds like sane behaviour to me.

**Comment by iSazonov** [comment]
> perhaps a single blanket _warning_ could be emitted, along the lines of (borrowing in part from the `Get-Process -IncludeUserName` error message):

We attach the process user names as _strings_ (not a token object) - so we can output "<Unknown>" without any warning. This looks good on screen and it is easily processed in scripts.

**Comment by mklement0** [comment]
* For `-IncludeUserName` _alone_ that _may_ be an option.

* With `-Scope CurrentUser`, however, where the implicit promise is that _all_ the user's processes are returned, I think a warning is called for, given that this promise cannot be fulfilled predictably.

However, even with `-IncludeUserName` you may want to know, given that  a subsequent filtering command (e.g. `| ? UserName -eq jdoe`) may also rely on this implied promise.

Speaking of: Perhaps instead of `-Scope CurrentUser` we should follow the model of the `ps`  Unix utility's `-u` option and offer a `-Username <string>` parameter, perhaps complemented by a current-user shortcut switch (which would take us back to  @FredVH's `-CurrentUser`).

**Comment by JamesWTruher** [comment]
I don't really feel that providing the parameter is _really_ that useful, I think that get-process should just _always_ return the username (`ps -j`). What I really think we should do is to fix _that_ behavior (and it looks like that code was kindly supplied above). If the username was present, then we could just `gps | ? username -eq jimtru` and be done. Also, I'm not really a fan about adding `-u` equivalent since the PS philosophy is to _not_ combine operations (`ps -u` is the combination of data acquisition and data filtering).

**Comment by rkeithhill** [comment]
> I think that get-process should just always return the username

Seems reasonable to me as long as it doesn't adversely impact performance.  And that would be consistent with the info I see in Task Manager.

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets agrees we should add a `-CurrentUser` parameter that returns only processes owned by the current user. If the owner of a process cannot be resolved, we agree that it doesn't make sense to throw an error or warning, as it's assumed that users have access to know which processes they own. Additionally, the current behavior of IncludeUsername is to return null with no error or warning.

Adding the `Up-for-grabs` label as this is not currently a high priority for us.
