### ISSUE TITLE
-in  operators

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#15113]
Hi Guys !!

`-in` operator and here variant  are great but it perform only in list and its  checks only for membership:

```
PS C:\> 'b' -in 'a','b','c'
True
```

but its great to support  to checks for substrings and to keys in dictionnary:

**### substring**:

```
PS> "shell" -in "powershell"
True


PS> "b" -in "earth"
False


PS> "shell" -notin "powershell"
False
```

**### checks keys in dictionnary:**

```

PS> 'b' -in @{a=5; b=2}
True # actually it return False
```

**Comment by vexx32** [comment]
I don't think reusing the operator in this way makes sense; it creates ambiguity for something like `$a -in $b` -- you have no way of knowing if `$b` is a string or an array, or a hashtable, without going to find both variables to see what's going on.

Also, why would it only be used to target keys in dictionaries rather than values? The usage in that case has an extra layer of ambiguity.

**Comment by daxian-dbw** [comment]
Language working group:
We agree with @vexx32's comment above, and will close this issue.
