### ISSUE TITLE
System.Management.Automation.PowerShell returns warning messages as error messages

### ISSUE THREAD

**Issue by BethanyZhou** [PowerShell/PowerShell#15115]
## Steps to reproduce

```powershell

```

## Expected behavior

```none
 PowerShell redirects warning messages to warning streams
```

## Actual behavior
Directly invoke cli:
![image](https://user-images.githubusercontent.com/19869716/112799230-aad22d00-90a0-11eb-8d5b-27f7441af3db.png)
invoke through powershell:
![image](https://user-images.githubusercontent.com/19869716/112799274-b887b280-90a0-11eb-9d82-5b33f2471171.png)

It turns out PowerShell redirects warning messages to error streams
## Environment data
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```none

```

**Comment by jborean93** [comment]
It looks like this is just something that `bicep` (native application) wrote to `stderr` and thus was treated as an error record. Native applications have no concepts of the extra streams that PowerShell supports and thus `stdout` goes to the output stream and `stderr` goes to the error stream. There's not much PowerShell can do about this as it's working as expected.

**Comment by BethanyZhou** [comment]
Thanks for your response @jborean93 . I suspected that this is caused by the stream redirection of the native application. However, No error has been caught when I invoke bicep through a System.Diagnostics.Process directly.
![image](https://user-images.githubusercontent.com/19869716/112818947-a7e23700-90b6-11eb-8dd4-66b15be29122.png)

**Comment by jborean93** [comment]
That part doesn't make much sense to be, here is something else that I know for sure wrote to `stderr`

```powershell
$proc = [Diagnostics.Process]::new()
$proc.StartInfo.FileName = 'powershell.exe'
$proc.StartInfo.Arguments = "-Command [Console]::Error.WriteLine('stderr'); [Console]::Out.WriteLine('stdout')"
$proc.StartInfo.UseShellExecute = $false
$proc.StartInfo.RedirectStandardError = $true
$proc.StartInfo.RedirectStandardOutput = $true

$proc.Start()
$proc.WaitForExit()

$stdout = $proc.StandardOutput.ReadToEnd()
$stderr = $proc.StandardError.ReadToEnd()

"STDOUT: {0}`nSTDERR: {1}`nRC: {2}" -f $stdout, $stderr, $proc.Exitcode
```

You can see that running this same command writes the stderr to the error stream

```powershell
$ps = [PowerShell]::Create()
$stdout = $ps.AddScript('powershell.exe -Command "[Console]::Error.WriteLine(''stderr''); [Console]::Out.WriteLine(''stdout'')"').Invoke()[0]

$stderr = $ps.Streams.Error[0]

"OUTPUT: {0}`nERROR: {1}`nHAD_ERRORS: {2}" -f $stdout, $stderr, $ps.HadErrors
```

I unfortunately don't have `bicep` installed or an environment set up to tes tit out but using these examples show how `stderr` data is sent to the error stream.

**Comment by mklement0** [comment]
Note that in the _console_ (terminal) stderr output from external processes is by default _not_ routed through PowerShell's error stream - instead, it prints straight to the display - _without_ being highlighted in a different color.

In other words: in a terminal, you won't be able to tell stdout lines apart from stderr lines, which you can verify with `cmd /c 'echo stdout & echo stderr >&2'` (Windows) / `sh -c 'echo stdout & echo stderr >&2'` (Unix).

The rationale is that stderr output cannot be assumed to indicate actual _errors_, given that it must be used for anything that is _not data_, such as status information and warnings, as in this case.

If you see different coloring - and if `$Errors` reflects the stderr lines after execution - the implication is that you're using _a PowerShell host that doesn't behave like PowerShell's `ConsoleHost`_.

Note that, unfortunately, even the `ServerRemoteHost` host that PowerShell uses for its remoting does _not_ behave like a terminal in this respect (more on that below).

What host are _you_ using, i.e. how are you invoking the CLI?

---

As an aside:

_On demand_ you can redirect or suppress stderr output, using `2>`, as usual, though note that each stderr line is wrapped in a [`System.Management.Automation.ErrorRecord`](https://docs.microsoft.com/en-US/dotnet/api/System.Management.Automation.ErrorRecord) instance.

As of v7.1, unfortunately, such a redirection causes the lines to be _routed through PowerShell's error stream_, which has two unwanted side effects:

* the lines are unexpectedly recorded in `$Error`
* more importantly, if `$ErrorActionPreference = 'Stop'` happens to be in effect, the first stderr line emitted by the external process causes execution to _abort_.

The current preview versions (of v7.2) have an _experimental feature_ named `PSNotApplyErrorActionToStderr` that opts out of this behavior; while I personally hope this will become an official feature, that's not a given.

Additionally, even the feature becomes official, the problem in the context of _remoting_ will persist; e.g., on Windows (assuming remoting is set up on the local machine; run from an _elevated_ session):

```
# Run as admin.
PS> Invoke-Command -ComputerName . { cmd /c 'echo stdout & echo stderr >&2'; 'more' } -ErrorAction Stop
stdout
stderr   # !! This will print in red, and 'more' never prints, because execution aborted at the first stderr line.
```

Note that even without `-ErrorAction Stop` the word `stderr` would print in _red_, because it is received via PowerShell's error stream.

**Comment by mklement0** [comment]
Sorry, I neglected to address the aspect of your using the PowerShell SDK:

The answer is that with SDK use the `Default Host` is used, which indeed appears _not_ to act like a terminal, similar to the `ServerRemoteHost`.

You can verify this with:

```powershell
PS> [powershell]::create().addScript(' $host.name ').Invoke()
Default Host
```

The other points stand, however.

**Comment by mklement0** [comment]
Sorry again for the noise - I realize I focused on an incidental aspect - host behavior - that should be addressed elsewhere.
I think @jborean93's comments have it all covered (the little mystery about _event_-based stderr collection with direct use of `System.Diagnostics.Process` notwithstanding), but to elaborate on the conceptual aspect:

* As for the expectation to have warnings emitted through an external process' stderr stream be routed through PowerShell's _warning_ stream: Unfortunately, given that stderr is used for _anything other than data_, there's no telling what a particular stderr line represents (and _guessing_ by the presence of the word `warning` would be too brittle).

* Routing all stderr output through PowerShell's _error_ stream is what the `Default Host` used by the PowerShell SDK does by design - this is defensible in the SDK, but can have unwanted side effects (collection of stderr lines in `$Error`, sensitivity to `$ErrorActionPreference = 'Stop'`)
  * It is more problematic in the case of the `ServerRemoteHost` used for PowerShell remoting and background jobs, whereas _terminal_-based hosts, notably `ConsoleHost`, do _not_ perform this routing and instead print straight to the display.

**Comment by BethanyZhou** [comment]
Thank you all @jborean93 , @mklement0 for explanation!!! Will communicate with bicep team and close this issue.
