### ISSUE TITLE
Switch unable to evaluate output from Get-Content using an empty file

### ISSUE THREAD

**Issue by krowlandson** [PowerShell/PowerShell#15135]
## Steps to reproduce

When loading an empty file into PowerShell using the `Get-Content` command, the returned object is a `null-valued expression`.

This makes it impossible to correctly evaluate against a `switch` statement.

Content of `emptyFile.json`:
```json
```

> NOTE: This must be a completely empty file. Any characters or whitespace changes the behaviour.

### Example 1

PowerShell Code:
```powershell
$fileContent = (Get-Content ./emptyFile.json)
switch ( $fileContent )
{
    $null
    {
        'Value is null'
    }
    default
    {
        'Value is not null'
    }
}
```

Output:
```shell

```

In this example, we see that the `switch` statement fails to evaluate `$fileContent`, providing no output. This means the `switch` statement is also failing to return the `default` case.

### Example 2

PowerShell Code:
```powershell
$fileContent = ((Get-Content ./emptyFile.json) ?? "")
switch ( $fileContent )
{
    $null
    {
        'Value is null'
    }
    default
    {
        'Value is not null'
    }
}
```

Output:
```shell
Value is not null
```

In this example, the null-coalescing operator correctly identifies that the output of `Get-Content ./emptyFile.json` to `null`, replacing the value with an empty string, resulting in the response `Value is not null`.

### Example 3

PowerShell Code:
```powershell
$fileContent = ((Get-Content ./emptyFile.json) ?? $null)
switch ( $fileContent )
{
    $null
    {
        'Value is null'
    }
    default
    {
        'Value is not null'
    }
}
```

Output:
```shell
Value is null
```

In this example, the null-coalescing operator correctly identifies that the output of `Get-Content ./emptyFile.json` to `null`, replacing the value with `$null`, resulting in the response `Value is null`.

This shows that although [switch can evaluate a `null` value](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-switch?view=powershell-7.1#null), the `null-valued expression` returned by `Get-Content ./emptyFile.json` doesn't get evaluated but also doesn't generate any errors.

### Additional context

In our case we are actually using the `ConvertFrom-Json` function to convert the content of the file (expected to be valid JSON) into an object.

We have also noted the following:

```powershell
# Command:
Get-Content ./emptyFile.json | ConvertFrom-Json
# Response (none):
# 

# Command:
$null | ConvertFrom-Json
# Response:
# ConvertFrom-Json: Cannot bind argument to parameter 'InputObject' because it is null.

# Command:
"" | ConvertFrom-Json
# Response (none):
# 

# Command:
(Get-Content ./emptyFile.json).GetType()
# Response:
# InvalidOperation: You cannot call a method on a null-valued expression.
```

As you can see, despite the output of `Get-Content ./emptyFile.json` being a null-valued expression, this doesn't cause the `ConvertFrom-Json` function to throw an error. This in turn also means the output is the parsed to the `switch` statement as a null-valued expression, but switch appears not to be able to evaluate this input, unlike a standard `if` statement.

## Expected behaviour

Expected behaviour is for `Get-Content` to return either a properly initialized `$null` or empty string value as the response when successfully loading an empty file.

## Actual behaviour

 `Get-Content` returns a `null-valued expression` when parsing an empty file.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by powercode** [comment]
This is by design. You can force the use of an array by using the array sub-expression `@()`

```powershell
$fileContent = @((Get-Content ./emptyFile.json) ?? $null)
switch ( $fileContent )
{
    $null
    {
        'Value is null'
    }
    default
    {
        'Value is not null'
    }
}

#output

Value is null
```

**Comment by 237dmitry** [comment]
```
switch ( $fileContent -eq $null )
{
    $true
    {
        'Value is null'
    }
    default
    {
        'Value is not null'
    }
}

```

**Comment by krowlandson** [comment]
> ```
> switch ( $fileContent -eq $null )
> {
>     $true
>     {
>         'Value is null'
>     }
>     default
>     {
>         'Value is not null'
>     }
> }
> ```

Thank you for your response @237dmitry. Unfortunately in our case we need to evaluate the content of `$fileContent` so evaluating the result of the evaluation within the switch will not meet our needs. My examples above are highly simplified to illustrate the issue we're facing.

**Comment by krowlandson** [comment]
Thank you for your response @powercode.

Please can you explain what you mean by:

> This is by design. You can force the use of an array by using the array sub-expression @()

I'm struggling to understand why a file with no content returns an object type which is inconsistent with when the file has content, and why this would be by design? This would be like making an empty string, not a string? Or have I misunderstood something?

Also, what is the purpose of forcing the use of an array? If I remove the null-coalescing operator (which I already know resolves the issue without the array), I still get the same outcome as without the array?

**Comment by bpayette** [comment]
Some (hopefully clarifying) notes:

First, the `switch` statement is an iterator (i.e. a loop). For example:
```powershell
switch (1,2,3,4) { {$_ % 2} {"odd"} default {"even"}}
```
returns `odd,even,odd,even`. 

Second, `Get-Content emptyfile.txt` returns `""` not `$null` so do:
```powershell
{master}PSCore (1:35) >  switch (gc emptyfile.json) { "" {"empty"} default {"default"}}
empty
```
Now if you actually pass null. it works as expected:
```powershell
{master}PSCore (1:37) >  switch ($null) { $null {"null"} default {"default"}}
null
```
Finally. if somewhat orthogonally. `switch` has a `-file` parameter that lets you iterate through the lines of a file:
```powershell
switch -file c:\temp\empty.txt { "" {"empty"} default {"default"}}
```
so you don't actually need to call `Get-Content`.

**Comment by mklement0** [comment]
To add to the existing comments:

This comes down to the distinction between bona fide `$null` and the _situationally_ equivalent `[System.Management.Automation.Internal.AutomationNull]::Value` singleton, which is used _behind the scenes_ to represent the case when a PowerShell command (cmdlet, function, script, script block) returns _no output_ (which is most easily created with `& { }`).

* In _expression_ contexts, `$null` and this special singleton are considered _equal_:

  * `$null -eq [System.Management.Automation.Internal.AutomationNull]::Value` returns `$true`

* In _enumeration_ contexts - notably in a _pipeline_ _and also in a `switch` statement_, these values behave _differently_: `$null` _is_ enumerated - as itself, whereas `[System.Management.Automation.Internal.AutomationNull]::Value` is _not_; that is, it behaves like an _empty collection_ in this context:
  * `$null | ForEach-Object { 'hi, mom' }` -> `hi, mom`
  *  `& {} | ForEach-Object { 'why won''t anybody call me?' }` -> no output, because the script block is never invoked (the statement as a whole again "outputs" `[System.Management.Automation.Internal.AutomationNull]::Value` 

Without all this - undocumented - background information, I'm not surprised at all that questions arose for you.

For that very reason, #13465 proposes implementing `-is [AutomationNull]` as a simple test to distinguish `$null` from `[System.Management.Automation.Internal.AutomationNull]::Value`.

A stopgap solution for detecting `[System.Management.Automation.Internal.AutomationNull]::Value` in, say, a variable `$var` is:

```powershell
$null -eq $var -and $var -is [psobject]
```

Slightly less obscure:

```powershell
$null -eq $var -and @($var).Count -eq 0
```

**Comment by mklement0** [comment]
To clarify, @bpayette: `Get-Content emptyfile.txt` doesn't return `""`, it outputs "nothing", i.e. `[System.Management.Automation.Internal.AutomationNull]::Value`, which explains the `switch` behavior (it receives no input, and therefore doesn't evaluate its branches).

While you would expect that `""` is returned when you use `-Raw` - i.e. asking for the entire file _as a single string_ - surprisingly you get `[System.Management.Automation.Internal.AutomationNull]::Value` too - see #3911

**Comment by mklement0** [comment]
> Also, what is the purpose of forcing the use of an array? 

Technically, you don't actually need to do that, `(Get-Content ./empty.txt) ?? $null` is enough.

In fact, that `[System.Management.Automation.Internal.AutomationNull]::Value` _behaves like an empty array_, causing `switch` to enumerate _nothing_, is the problem to begin with.

`(Get-Content ./empty.txt) ?? $null` is the equivalent of `[System.Management.Automation.Internal.AutomationNull]::Value ?? $null` and - somewhat ironically - it is the fact that `[System.Management.Automation.Internal.AutomationNull]::Value` _is_ considered `$null` _in this expression context_ that makes the expression return the actual `$null`.

And the actual `$null` - as a scalar of sorts - _is_ processed by `switch`. That is, in terms of _enumeration_, `$null` behaves like `@($null)`, i.e. a collection of size 1 whose only element is `$null`, and that element is evaluated against the `switch` branches; that's why the `@(...)` makes no difference in this scenario.

**Comment by mklement0** [comment]
Final thoughts:

* Because `[System.Management.Automation.Internal.AutomationNull]::Value` behaves like an empty collection, its `.Count` property value is `0`, so `0 -eq $fileContent.Count` tells you whether the file is empty.

* If #3911 gets implemented, `'' -eq $fileContent` could be used after `$fileContent = Get-Content -Raw ./emptyFile.json` - note the test against the _empty string_ rather than `$null`, because `[string]`-typed values in PowerShell are never `$null` (unless you use the `[NullString]::Value` singleton, which should be limited to .NET API calls).

What currently already works is to rely on PowerShell's _implicit to-Boolean conversions_; that is, with `$fileContent` filled either without or with `-Raw`, `-not $fileContent` indicates an empty file.

This works reliably, because any _nonempty string_ is implicitly `$true` in a Boolean context, irrespective of the string's content.

There is pitfall with respect to how _nonempty collections_ are interpreted as Booleans, however: something like `[bool] @($null)` is `$false`, because any _single-element_ collection is unwrapped before converting, and `[bool] $null` is `$false`; _multi_-element collections, by contrast, are _always_ `$true`, irrespective of the data type and values of their elements; e.g., `[bool] ($null, $null)` is `$true`.

**Comment by 237dmitry** [comment]
```powershell
 > New-Item empty.txt | Out-Null
 > (Get-Item empty.txt).Length  
0 
                              
 > & {                          
  :     switch (${c:empty.txt})     
  :     {                           
  :         $null   { 'null' }            
  :         default { 'default' }       
  :     }                           
  : }                           
null
                            
 > '1' >> empty.txt             
 > (Get-Item empty.txt).Length  
3 
                             
 > & {                          
  :     switch (${c:empty.txt})     
  :     {                           
  :         $null   { 'null' }            
  :         default { 'default' }       
  :     }                           
  : }                           
default                         
```
Instead of `c:` you can create PSDrive and use it's name. `${name:empty.txt}`

**Comment by mklement0** [comment]
Thanks, @237dmitry. It's certainly interesting that using _namespace variable notation_ with files yields bona fide `$null` with an empty file, however:

* Since `${c:empty.txt}` is effectively the same as `Get-Content c:empty.txt`, it should instead return `[System.Management.Automation.Internal.AutomationNull]::Value`, as the latter does.

* As useful as namespace notation is with drives such as `Env` (e.g., `$env:HOME`), with _file-system_ drives it has severe limitations, which is probably why you rarely see it in the wild: no fully relative paths (need a least a drive spec), no support on Unix by default (no drive spec exists), no _variable_-based paths, no control over the encoding, `[` and `]` are invariably treated as wildcard metacharacters; see also:  https://github.com/PowerShell/PowerShell/issues/2268#issuecomment-283755725

**Comment by krowlandson** [comment]
Thank you all... some fascinating responses and amazing to better understand the behaviour we are observing.

So for now, my take away is to actually base our solution on my Example 2 above (as we need to be able to parse an empty file into `ConvertFrom-Json` which will fail with a `$null` input, and then process the individual object created from this as per the following:

```powershell
$fileContent = ((Get-Content ./emptyFile.json) ?? "") | ConvertFrom-Json -AsHashTable
switch ( $fileContent )
{
    $_ <condition_1>
    {
      <process_condition_1>
    }
    $_ <condition_2>
    {
      <process_condition_2>
    }
    $_ <condition_3>
    {
      <process_condition_3>
    }
    default
    {
      <process_default_condition>
    }
}
```

However this still raises a question as to whether one of the "modes" of `Get-Content` should support returning an empty file as an empty string? Would anyone else find this useful? In my mind this should have been the behaviour of `raw` based on the documentation but it sounds like there may be reasons why the author of this function chose to return `[System.Management.Automation.Internal.AutomationNull]` in this scenario.

**Comment by mklement0** [comment]
>  whether one of the "modes" of Get-Content should support returning an empty file as an empty string?

Yes, `Get-Content -Raw` should, as argued in #3911.

> as we need to be able to parse an empty file into ConvertFrom-Json which will fail with a $null input,

Note that no actual `$null` is piped to `ConvertFrom-Json`, irrespective of whether you use 
`Get-Content ./emptyFile.json | ConvertFrom-Json -AsHashTable` or `Get-Content -Raw ./emptyFile.json | ConvertFrom-Json -AsHashTable`, so both commands work - the latter is preferable, because it is much faster (with larger files) - but, since `ConvertFrom-Json` then receives _no input_ (due to `Get-Content` "returning" `[System.Management.Automation.Internal.AutomationNull]::Value`), `$fileContent` too ends up as `[System.Management.Automation.Internal.AutomationNull]::Value`.

Therefore, if you do want to evaluate the result as a direct part of your `switch` statement, you indeed do need the `?? ""` part, because only then does `ConvertFrom-Json` output an actual `$null` that you can process with `switch`.

**Comment by mklement0** [comment]
Re-reading your previous comment: 

> which will fail with a $null input

Yes, `$null` as _input_ to `Convert-FromJson` fails, whereas the _empty string_ as input actually produces `$null` _as output_, which you can then process with `switch`.

**Comment by mklement0** [comment]
Final thought, take 2:

A perhaps conceptually clearer approach to end up with a true `$null`, using `-Raw` for better performance (note that `ConvertFrom-Json` must collect all text input up front anyway):

```powershell
$fileContent = (Get-Content -Raw ./emptyFile.json | ConvertFrom-Json -AsHashTable) ?? $null
```

If / when #3911 gets fixed, the `?? $null` part will no longer be necessary (when combined with `-Raw`).

**Comment by User843212** [comment]
"mklement0" brought me to this idea:
$Segments | ForEach-Object { Get-Content $_ **-Encoding 1252** | Add-Content "Video.ts" **-Encoding 1252** 

This works only almost correctly because every '"CR" 0xD' is translated to "CR/LF"  '0xD/'0xA'.
Using "Add-Content" with "**-NoNewline**" removes every '0xD'.
Is there a convenient way to not translate a CR into Windows style?
