### ISSUE TITLE
Feature Request : Find TimeStamp of a Variable creation/update in PowerShell

### ISSUE THREAD

**Issue by Prakash82x** [PowerShell/PowerShell#15134]
## Summary of the new feature/enhancement

I was working with some API query using Invoke-WebRequest and felt the need of retrieving timestamp when a particular variable was assigned/initialized.

Alhough I think there are different other workarounds available to get the date/time but I think it out of the box might be a fair idea and if it can be made available as a property/extended property of a Variable and Creation/Update timestamp of the variable can be retrieved from there.

## Proposed technical implementation details : Example
Example will be like this:
I am getting auth token from an API which is valid for 60 minutes and assigning that to a variable, using that token I can make several other queries untill that token gets expired.

Upon Every query I want to check if the token is still valid based on the Token generation time from the Variable's timestamp and if it is found that 60 minutes has passed since it was initialized then regenerate the token otherwise continue using it.

**Comment by bpayette** [comment]
Setting a time stamp every time a variable is assigned would probably have some serious performance implications. It would also be somewhat awkward to use since the property would be on the PSVariable object not the value. You would probably have to do something like:
```powershell
if ((Get-Variable "myvar").TimeSet -gt $targetTime) { ... }
```
As an alternative, we could add a synthetic "@TimeFetched" property to the objects retrieved by `Invoke-WebRequest` i.e. to the value not the variable. This might look like
```powershell
if ($myvar."@TimeFetched" -gt $targetTime) { ... }
```
Would this work for you?

**Comment by iSazonov** [comment]
> Example will be like this:
I am getting auth token from an API which is valid for 60 minutes and assigning that to a variable, using that token I can make several other queries untill that token gets expired.
Upon Every query I want to check if the token is still valid based on the Token generation time from the Variable's timestamp and if it is found that 60 minutes has passed since it was initialized then regenerate the token otherwise continue using it.

@PaulHigin It is seem a scenario for your great module.

**Comment by Prakash82x** [comment]
> 
> 
> Setting a time stamp every time a variable is assigned would probably have some serious performance implications. It would also be somewhat awkward to use since the property would be on the PSVariable object not the value. You would probably have to do something like:
> 
> ```powershell
> if ((Get-Variable "myvar").TimeSet -gt $targetTime) { ... }
> ```
> 
> As an alternative, we could add a synthetic "@TimeFetched" property to the objects retrieved by `Invoke-WebRequest` i.e. to the value not the variable. This might look like
> 
> ```powershell
> if ($myvar."@TimeFetched" -gt $targetTime) { ... }
> ```
> 
> Would this work for you?

Hey Bruce, Thanks for looking into this..
I agree to the point you raised regarding performance implications and that's why I mentioned if it can be made available in the extended properties of a variable or something can be thought as it (timestamp) is added as an additional object **on demand** or something at the time when variable is being initialized/assigned.

For now I can very well use workarounds like adding a custom property containing timestamp to the variable or a separate variable altogether too and that should work for me to check the validity of the token.
