### ISSUE TITLE
Get-Command bug for "?" alias

### ISSUE THREAD

**Issue by loxia01** [PowerShell/PowerShell#15162]
## Steps to reproduce
`Get-Command ?` or `Get-Command "?"`
```powershell

```

## Expected behavior
Show output for the `Where-Object` alias `"?"`
```none

```

## Actual behavior
In addition to showing output for the `Where-Object` alias `"?"`, output for the `ForEach-Object` alias `"%"`, the `Get-History` alias `"h"` and the `Invoke-History` alias `"r"` is also shown.
```none

```

## Environment data

PSVersion                                 7.1.3
PSEdition                                  Core
GitCommitId                             7.1.3
OS                                            Microsoft Windows 10.0.19042
Platform                                   Win32NT
PSCompatibleVersions              {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion                   1.1.0.1
WSManStackVersion                 3.0
```none

```

**Comment by mklement0** [comment]
`Get-Command`'s (implied) `-Name` parameter accepts wildcard patterns (as many parameters across PowerShell cmdlets do).

While file-processing cmdlets have separate `-LiteralPath` parameters that allow you to explicitly distinguish between a pattern and a verbatim argument, `Get-Command` only has `-Name`, so in order to prevent `?` from being interpreted as a pattern, you must _escape_ it - which isn't too obvious, unfortunately:

```powershell
PS> Get-Command '`?'  # or: ``?

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           ? -> Where-Object                                             
```

That is, the `` ` `` must be a literal part of the name passed to `Get-Command` - it is literal from a string-processing perspective, but in the context of wildcard-pattern matching then serves as the escape character.

Conceptually, the above is the equivalent of:

```powershell
Get-Command ([WildcardPattern]::Escape('?'))
```

**Comment by loxia01** [comment]
Thanks for fast reply and clarification.
I am closing this issue.
