### ISSUE TITLE
Access Denied for call over WinRM

### ISSUE THREAD

**Issue by erenturkm** [PowerShell/PowerShell#15207]
I am using Powershell 7.1.3 to WinRM to a remote Windows Server 2019 and do a WUAScan. I am using elevated prompts, using  new-pssession to open the session, and checking that powershell is running as elevated. However  below code is giving me access denied. The script runs fine on local machine as elevated (Windows 10 1909, Powershell 7.1.3) and on Remote (Windows Server 2019, Powershell 5) through RDS. 
-->

## Steps to reproduce

```powershell
    $UpdateSession = New-Object -ComObject Microsoft.Update.Session
    $UpdateServiceManager  = New-Object -ComObject Microsoft.Update.ServiceManager 
    $UpdateService = $UpdateServiceManager.AddScanPackageService("Offline Sync Service", $file, 1) 
```

## Expected behavior
Functioning $UpdateService object

## Actual behavior

```
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
At C:\store\WUAScan\WUAScan.ps1:13 char:5
+     $UpdateService = $UpdateServiceManager.AddScanPackageService("Off ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException

```

## Environment data

```
Local machine:
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Remote Server:
Name                           Value
----                           -----
PSVersion                      5.1.17763.592
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.592
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by iRon7** [comment]
Try: `net user administrator /active:yes`

**Comment by jborean93** [comment]
The Windows Update API is one of those APIs that restrict being called from a `Network` logon. There is nothing PowerShell can do about this as it is working "by design". It's a frustrating restriction that I have no idea why the WUA team implemented it this way but it is what it is.

Essentially the only way you can get this working is to change the logon type from `Network` to something else. You can do this in many ways

* Create a scheduled task to run the code
  * The [PSScheduledJob](https://docs.microsoft.com/en-us/powershell/module/psscheduledjob/?view=powershell-5.1) module is a nice way to easily integrate this in PowerShell
  * Otherwise the standard [ScheduledTasks](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/?view=windowsserver2019-ps) module can help you create the scheduled task and call the PowerShell code needed but this is more low level
* Use psexec to start a new process as `SYSTEM` or another account with explicit credentials
  * Fairly simple but requires a non-builtin tool
* Implement your own PInvoke code to do the above
  * You can either duplicate an existing `SYSTEM` token or
  * Call [LogonUser](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-logonuserw) to get a non Network logon token
  * With these token you can call [CreateProcessWithToken](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createprocesswithtokenw) to run your new process

Obviously the scheduled task way is the easiest route and is how 3rd party modules like `PSWindowsUpdate` working when run remotely.
