### ISSUE TITLE
Target type detection (file/directory) for relative symlinks is still broken, even on Windows

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PowerShell#15235]
https://github.com/PowerShell/PowerShell/pull/12797#issuecomment-819889789

## Intro & context
Symlink target may be a relative path, which is then resolved by the filesystem as a relative path from parent directory of the symlink. Example:
We have the following 2 files:
```
    Directory: D:\test

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
la---          2021-04-15    00:41              0 file_link.txt -> .\file.txt
-a---          2021-04-15    00:41              0 file.txt
```
`file_link.txt` is a file symlink, which resolves to `D:\test\file.txt`. It might be created with `New-Item -Type SymbolicLink .\file_link.txt -Target .\file.txt`.

There's a difference between a symlink to a file and to a directory, and attempting to traverse a directory symlink pointing to a file does not work (and same for trying to read from a file symlink pointing to a directory).

To correctly create the symlink, PowerShell checks whether the target is a file or a directory. Originally, this check was broken for relative target paths, because the process-wide .NET working directory was used to resolve the target (so the above command would check for a target path like `C:\Windows\System32\file.txt` - that path doesn't exist, so `pwsh` defaults to creating a file symlink). This was supposedly fixed in #12797.

With this "fix", working directory of PowerShell is now used instead of the .NET working directory. **This is however still incorrect**, because we don't want to resolve the target relative to CWD, but relative to the symlink itself.

## Reproduction
(I'll use `D:/test` as our testing directory to make it clear when I'm talking about absolute paths)

### 1)
```
mkdir D:/test
mkdir D:/test/dir
cd D:/
ni -Type SymbolicLink D:/test/dir_link -Target ./dir
```
Expected: directory symlink to `D:/test/dir`, with target `./dir`
Got: **file** symlink to `D:/test/dir`, with target `./dir`
The target type detection code checks the relative path `./dir` (`D:/dir`), which doesn't exist, so the symlink incorrectly defaults to **file symlink**.

### 2)
```
mkdir D:/test
mkdir D:/test/dir
cd D:/test
ni -Type SymbolicLink D:/test/dir_link -Target ./dir
```
Expected: directory symlink to `D:/test/dir`, with target `./dir`
Got: what I expected
Only difference from previous example is the `cd D:/test` on line 3. This correctly creates a directory symlink, because the code checks type of target for `./dir` (`D:/test/dir`), which now matches the real target.

### 3)
```
mkdir D:/test/subdir
mkdir D:/test/item # <-- directory
ni D:/test/subdir/item # <-- file
cd D:/test
ni -Type SymbolicLink D:/test/subdir/item_link -Target ./item
```
Expected: file symlink to `D:/test/subdir/item`, with target `./item`
Got: **directory** symlink `D:/test/subdir/item`, with target `./item`
The the file `D:/test/item` is used for target check, it's a directory, so a directory symlink is created (but the actual target is `D:/test/subdir/item`, which is a file).

## Proposed fixes
There are 2 possible correct behaviors I see here:
1) Always resolve symlink target to an absolute path in `New-Item`. This effectively prevents PowerShell from creating symlinks with relative paths to target. 
2) Allow relative paths, but when checking for target type (file/directory), use the path `Join-Path $Path $Target` internally, but still write `$Target` as provided by user (relative) into the symlink itself. This is imo the better solution, allows the user to create symlinks with relative paths, but still correctly detects the type.

## Environment data
```none

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.4
PSEdition                      Core
GitCommitId                    7.2.0-preview.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Thanks for writing this up.

Re behavior 1. (resolving to full paths before creating the symlink):

We do _not_ want this, because defining symlinks that reference their targets via _relative_ paths is an important feature, which enables moving such symlinks - along with their targets - to a different location without breaking things.

Therefore - I agree with your preference - we want behavior 2.

With that in mind, we want:

* preserving relative targets _as specified_ in the symlink's actual _definition (potentially after normalizing path separators to the platform-native form).

* for the sake of _validating_ the target on creation, an _existence check_ relative to the _symlink_'s directory.

  * Currently, such checks are _not_ performed, except if the target is specified as a _full path_ AND that path starts with a nonexistent _drive_ specification or a nonexistent _UNC share_.

   * Conversely, you may  want to - by way of _opt-in_ - create a symlink to a target that you _know not to exist yet_. 
     * For _technical_ reasons, _on Windows_ this additionally requires explicitly indicating the target's file-system _type_ (_file_ vs. _directory_).
  * See https://github.com/PowerShell/PowerShell/issues/9067#issuecomment-470140963 for a discussion of these issues.

**Comment by mklement0** [comment]
If this gets fixed as suggested, the following is a moot point, but just to prevent additional confusion:  

#12797, which, as you state, was conceptually the wrong fix, only _partially_ achieved what it tried to do: a target path such as `.\foo` _is_ recognized as a relative path and resolved against `$PWD`, but the equivalent `foo` (no `.\` prefix) is not, and is currently still resolved against the _process_' current directory (`[Environment]::CurrentDirectory`); see #15161 for a repro (since closed, because it will implicitly also be resolved by resolving _this_ issue).

**Comment by daxian-dbw** [comment]
The Engine WG spent about 25 minutes discussing about this issue. We agreed that the proposed fix no.2 is reasonable (quoted below), namely a relative path specified for `-Target` should be resolved using the path to the symbolic link, instead of powershell's current working directory.

> Allow relative paths, but when checking for target type (file/directory), use the path `Join-Path $Path $Target` internally, but still write `$Target` as provided by user (relative) into the symlink itself. This is imo the better solution, allows the user to create symlinks with relative paths, but still correctly detects the type.

This makes sense because when accessing a file/directory symbolic that is associated with a relative path, such as `Get-Content <symlink>`, the relative path is resolved using the symlink path. So, we should be consistent in resolving the target relative path when creating a symbolic link with `New-Item`.

This proposed fix would be a breaking change to PowerShell 7.1. It feels like the right thing to do, but we need to evaluate the impact before proceeding.

----------------------------

Interestingly, our discussion led to another idea when comparing `New-Item` with `mklink`, which we want to throw out here for more discussion.

When creating a symbolic using [`mklink`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink), `mklink` doesn't check the existence of the specified `<target>` path. It creates a file symbolic by default, and creates a directory symbolic when `/d` is specified.

As is shown in the screenshot below, `myfolder` is an existing directory, but `mklink my-link c:\arena\tmp\test-2\myfolder` creates a file symbolic, even though the target path is an existing directory.

![image](https://user-images.githubusercontent.com/127450/121633364-7df2ac80-ca37-11eb-84df-da09f53c5d20.png)

So, maybe `New-Item` should work similarly as `mklink` in creating a symbolic link?
    - does not check on the existence of `target` path
    - create file symbolic by default, and add a new `switch` parameter for creating directory symbolic

This would be a breaking change too, in that if target points to an existing directory, a directory symbolic will be create with the current behavior, but a file symbolic will be created if we change to the `mklink` behavior.

**Comment by iSazonov** [comment]
If it is a bug why we would say "breaking change"? :-)

**Comment by dogancelik** [comment]
Junction example:

Pwsh version: `7.1.4`
```pwsh
New-Item '.\node_modules\example-project-base\' -ItemType Junction -Value '.\example-project-base\'
# New-Item: Could not find item .\example-project-base\.
```

PowerShell version: `5.1.19041.1023`:
```pwsh
New-Item '.\node_modules\example-project-base\' -ItemType Junction -Value '.\example-project-base\'
#    Directory: C:\example-project\node_modules
# Mode                 LastWriteTime         Length Name
# ----                 -------------         ------ ----
# d----l        2021.08.23     23:27                example-project-base
```

**Comment by lahma0** [comment]
My god this is a distasterous mess... You'd think doing something as simple as creating a relative symlink to a parent directory/file (..\..\etc) would be a simple matter but you would be very, very wrong.

**Comment by MatejKafka** [comment]
> My god this is a distasterous mess... You'd think doing something as simple as creating a relative symlink to a parent directory/file (....\etc) in Powershell would be a simple matter but you would be very, very wrong.

This comment is not helpful to the discussion, please refrain from commenting just to vent your (understandable) frustration. Instead, if the issue bothers you, why not either a) contribute something meaningful to the discussion, b) write the code that fixes it?

**Comment by mbs-c** [comment]
> So, maybe `New-Item` should work similarly as `mklink` in creating a symbolic link?

Since no other user seems to have replied yet: I don't think this is an either-or question. Both behaviors might be desirable: When using PowerShell interactively, or if you are expecting POSIX-like semantics, you probably want it to choose the type of symlink automatically based on the target. But in a script or in exceptional cases, you may want to explicitly create a file or directory symlink, e.g. because the target is not guaranteed to exist or may not currently be reachable (network drive).

So, I would propose the following:
* `New-Item -Type SymbolicLink` should be fixed as outlined above.
* Two new item types `FileSymbolicLink` and `DirectorySymbolicLink` should be introduced to make the equivalent of `mklink` and `mklink /D` available in PowerShell. On non-Windows systems, they would be treated as synonyms of `SymbolicLink`, and on Windows PowerShell would skip the target check and create the specified type of symbolic link.

(In an ideal world, `mklink` would have a similar interface with an explicit `/F` switch and target detection when no switch is specified.)

**Comment by mbs-c** [comment]
Commenting to prevent the bot from closing an issue that is still relevant.

**Comment by mbs-c** [comment]
Dear bot, this is still relevant.

**Comment by kodra-dev** [comment]
Is there any solution to this? What's the true Powershell equivalent of `mklink /D` now?

**Comment by msftrncs** [comment]
> * Two new item types `FileSymbolicLink` and `DirectorySymbolicLink` should be introduced to make the equivalent of `mklink` and `mklink /D` available in PowerShell. On non-Windows systems, they would be treated as synonyms of `SymbolicLink`, and on Windows, PowerShell would skip the target check and create the specified type of symbolic link.

Ideally, PowerShell should still check the link type, and report errors if it finds the target but the type is wrong.

Also, there seems to be more wrong with the original fix than I found discussed here.  Interactively, the previous fix seems to work as described using the CWD, but in a script, it does not appear to use the CWD to resolve the relative link.  CD/Set-Location/Push-Location do not help the New-Item command correctly interpret the relative path and resolve the target.   As long as the target is relative to the path PowerShell (pwsh.exe) was originally started in at the point the script was executed, then it works fine.
