### ISSUE TITLE
TypeData member: DefaultArgumentCompleter

### ISSUE THREAD

**Issue by Stroniax** [PowerShell/PowerShell#15267]
## Summary of the new feature/enhancement

For many types, the path argument completion will never be useful. I have found myself wishing that I could define a default argument completer for a specific type. Any parameter of that type would use this as its argument completer, unless an argument completer was explicitly defined for the type.

The default argument completer should accept `ScriptBlock`, `IArgumentCompleter`, or `IArgumentCompleterFactory`.

## Proposed technical implementation details (optional)

Use case would be similar to the following.
```
function Get-MyUser {
    [OutputType([MyNamespace.MyUser])]
   param(
      [System.String]$UserName,
      [MyNamespace.PhoneNumber]$PhoneNumber
    )
    process {
        # call API to retrieve instance of MyNamespace.MyUser
    }
}
Update-TypeData -TypeName MyNamespace.PhoneNumber -MemberType DefaultArgumentCompleter -Value ([MyNamespace.PhoneNumberCompleter])

# Should have the same result as if the $PhoneNumber parameter was decorated with 
# [ArgumentCompleter([MyNamespace.PhoneNumberCompleter])]
Get-MyUser -PhoneNumber <tab>
```

**Comment by iSazonov** [comment]
There is an issue to remove the file completion fallback and introduce new attribute for Path parameters so that explicitly mark parameters where file completion is useful.

**Comment by powercode** [comment]
I like the idea. `DateTime` could have completions for `a day ago`, 'two days ago` ... `a year ago` etc.

**Comment by mklement0** [comment]
I definitely like the idea of type-level argument completers.

As for existing issues (tangent alert):

* The issue that asks for filename tab-completion _not_ to be applied to non-`[string]` (but specifically typed) parameters is #14147.

* But, indeed, having a way to explicitly designate parameters as representing a PS provider path (of which _file-system_ paths are one example) and limiting filename completion to those would be even more helpful:
  * https://github.com/PowerShell/PowerShell/issues/14745#issuecomment-776282779 proposes a `[PSPathInfo]` type that could also be used in parameter declarations to both provide useful functionality _and_ to signal the fact that it represents a provider path for the purpose of tab completion.
  
* For backward compatibility and as more helpful _fallback_ behavior, in case no other completer is in effect and the parameter is `[string]` or untyped:
  * Applying filename completion could be _inferred_ from the  presence of the words `File` or `Path` in a parameter's _name_ (which wouldn't work for localized parameter names).
  * Otherwise, use filename completion only if the user typed a `.` or `/` or, on Windows additionally something like `C:`, before pressing the Tab key.

**Comment by cfrederickson-kpbsd** [comment]
I think there’s too much focus on what I mentioned about the path argument completer. This suggestion isn’t about removing it at all - I have no problem with it being a fallback, but for some types - when the only helpful completion is custom to the type - the only current options (`[ArgumentCompleter()]` and `Register-ArgumentCompleter`, which each apply to a single parameter of a single command at a time) don’t provide a great way of doing this.

**Comment by Stroniax** [comment]
I think there’s too much focus on what I mentioned about the path argument completer. This suggestion isn’t about removing it at all - I have no problem with it being a fallback, but for some types - when the only helpful completion is custom to the type - the only current options (`[ArgumentCompleter()]` and `Register-ArgumentCompleter`, which each apply to a single parameter of a single command at a time) don’t provide a great way of doing this.

**Comment by mklement0** [comment]
> I think there’s too much focus

That's why I said "tangent alert"; it was in response to @iSazonov's mentioning of an existing issue re filename completion, which in turn was prompted by this statement in your initial post: "for many types, the path argument completion will never be useful."

But, point, taken, and I've hidden my tangential thoughts inside a collapsible element. Similarly, I encourage you to hide your previous comment, as I will hide this one.
