### ISSUE TITLE
Incorrect arg splitting when using .. syntax for git log

### ISSUE THREAD

**Issue by DanielSSilva** [PowerShell/PowerShell#15279]
```powershell
$latestTag = git describe --tags --abbrev=0
git log $latestTag..HEAD --oneline
```

## Expected behavior
Git log output such as 
```none
ac9ca9d (HEAD -> main, origin/main, origin/HEAD) added tree
7834bff indentation
```

## Actual behavior
```none
nothing is returned 
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.3
PSEdition                      Core
GitCommitId                    7.2.0-preview.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Additional info

Using 
```powershell
{ echo $tag..HEAD }.Ast.EndBlock.Statements[0].PipelineElements[0].CommandElements

StringConstantType : BareWord
Value              : echo
StaticType         : System.String
Extent             : echo
Parent             : echo $tag..HEAD

VariablePath : tag
Splatted     : False
StaticType   : System.Object
Extent       : $tag
Parent       : echo $tag..HEAD

StringConstantType : BareWord
Value              : ..HEAD
StaticType         : System.String
Extent             : ..HEAD
Parent             : echo $tag..HEAD
```
It's interpreting as two different parameters
As mentioned in [this Twitter thread](https://twitter.com/DanielSilv9/status/1384148636582379533), this can be solved by using double quotes like so
```powershell
 git log "$latestTag..HEAD" --oneline
```

**Comment by iSazonov** [comment]
Does this work before 7.2.0-preview.3? In 7.1?

**Comment by mklement0** [comment]
It's definitely surprising and unhelpful behavior that has been in place since v3 (in v2 you get a "Missing property name after reference operator." error).

Just to provide some background:

An argument that looks like a _property access_ is usually treated as such:

```powershell
PS> cmd /c echo $PSHOME.Length # with .HEAD, $null would result, and no argument would be passed.
35  # e.g.
```

Seemingly, if what follows the first `.` isn't a syntactically valid property name, the argument is simply broken in two at the first `.` (and the variable reference is expanded and stringified _as a whole_), whereas it would make much more sense to implicitly treat the argument as an _expandable string_ (as if it were enclosed in `"..."`), which is what otherwise happens, e.g., with 
`cmd /c echo /$PSHOME..HEAD` (because the token doesn't start with `$`).

The rules around how unquoted compound tokens are parsed and sometimes broken up in argument mode are surprisingly complex, and there are other surprises - see #6467 and https://github.com/MicrosoftDocs/PowerShell-Docs/issues/3440#issuecomment-478206280

You've already stated the workaround - double-quoting - which is always a way to avoid ambiguity, but it would certainly be nice if that weren't necessary.

**Comment by SteveL-MSFT** [comment]
With the new 7.2-preview.5 native command parameter binding tracing, the problem is that `git` is being sent the value of `$tag` and `..HEAD` as two parameters instead of one:

```console
PS> $tag = git describe --tags --abbrev=0
PS> trace-command -Option ExecutionFlow -Name ParameterBinding -Expression { git log $tag..HEAD --oneline } -PSHost
DEBUG: 2021-04-20 06:52:38.3359 ParameterBinding Information: 0 : BIND NAMED native application line args [/usr/bin/git]
DEBUG: 2021-04-20 06:52:38.3468 ParameterBinding Information: 0 :     BIND cmd line arg [log] to position [0]
DEBUG: 2021-04-20 06:52:38.3475 ParameterBinding Information: 0 :     BIND cmd line arg [v7.2.0-preview.5] to position [1]
DEBUG: 2021-04-20 06:52:38.3475 ParameterBinding Information: 0 :     BIND cmd line arg [..HEAD] to position [2]
DEBUG: 2021-04-20 06:52:38.3475 ParameterB
```

Replacing the variable with a literal shows what is expected:

```console
PS> trace-command -Option ExecutionFlow -Name ParameterBinding -Expression { git log v7.2.0-preview.5..HEAD --oneline } -PSHost
DEBUG: 2021-04-20 06:53:39.0736 ParameterBinding Information: 0 : BIND NAMED native application line args [/usr/bin/git]
DEBUG: 2021-04-20 06:53:39.0754 ParameterBinding Information: 0 :     BIND cmd line arg [log] to position [0]
DEBUG: 2021-04-20 06:53:39.0755 ParameterBinding Information: 0 :     BIND cmd line arg [v7.2.0-preview.5..HEAD] to position [1]
DEBUG: 2021-04-20 06:53:39.0762 ParameterBinding Information: 0 :     BIND cmd line arg [--oneline] to position [2]
DEBUG: 2021-04-20 06:53:39.1816 ParameterBinding Information: 0 : CALLING BeginProcessing
```

**Comment by SeeminglyScience** [comment]
@SteveL-MSFT The issue has existed since version 3 (as noted by @mklement0 above) and happens with any command (e.g. `$i = '10'; echo $i..HEAD`).

@IISResetMe mentioned on twitter that it seems to occur at the tokenizer.  In argument mode the tokenizer doesn't correctly revert back to a single expandable string when it hits the second period and instead creates a variable token and a literal string token.

**Comment by mklement0** [comment]
Thanks for the clarification, @SeeminglyScience; indeed, the problem also happens in regular parameter binding, not just when calling native executables.

Given that a native executable happened to be the messenger, if you will, in this case, perhaps @SteveL-MSFT merely meant to showcase the new-in-preview.5 ability to also trace parameter binding when calling native executables, which is indeed good to know (though incidental here).

**Comment by SeeminglyScience** [comment]
> Given that a native executable happened to be the messenger, if you will, in this case, perhaps @SteveL-MSFT merely meant to showcase the new-in-preview.5 ability to also trace parameter binding when calling native executables, which is indeed good to know (though incidental here).

Ahh good point! Didn't know that was new, I definitely misread that.
