### ISSUE TITLE
New-ScheduledTaskTrigger incorrect return type on Windows Server 2012 6.2.9200

### ISSUE THREAD

**Issue by henry-js** [PowerShell/PowerShell#15316]
## Steps to reproduce

1. Run the same command on Win10 and Server 2012
```powershell
$trigger = New-ScheduledTaskTrigger -Weekly -WeeksInterval 1 -DaysOfWeek Monday -At 9am
$trigger.GetType()
```

## Expected behavior
|IsPublic | IsSerial | Name          |BaseType
|---------|---------|--------------|---------
|True      | False    |CimInstance |System.Object

## Actual behavior

|IsPublic | IsSerial | Name      |BaseType
|---------|---------|------------|--------
|True      | True     | PSObject | System.Object

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 6.2.9200
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

It appears the ModuleType of ScheduledTasks on the server is Script:
```none
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.0                   ScheduledTasks                      {Disable-ScheduledTask, Enable-ScheduledTask, Export-ScheduledTask, Get-ClusteredScheduledTask…}
```
Whereas on Win10 it's a Manifest:
```none
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   1.0.0.0               ScheduledTasks                      {Disable-ScheduledTask, Enable-ScheduledTask, Export-ScheduledTask, Get-ClusteredScheduledTask…}
```

**Comment by jborean93** [comment]
This is because the scheduled task module hasn’t been marked as compatible with PSCore so it runs in an implicit remoting session. Any objects exchanged are serialised and thus the type information is mostly lost. You basically have a read only snapshot as a PSObject.

On newer Windows builds the scheduled task module has been marked as compatible with PSCore and thus it is loaded directly in the session and no serialisation occurs. There’s really not much you can do here as I doubt Microsoft will update the modules on older Windows versions for the sake of a product that didn’t ship with that version.

**Comment by jborean93** [comment]
One thing you could try is `Import-Module ScheduledTasks -SkipEditionCheck` but that just tries to force the import into pwsh without the implicit remoting. If the module itself doesn't work with pwsh then unfortunately you need to use the implicit remoting setup.
