### ISSUE TITLE
Script via STDIN does not exit with error code and does not stop correctly

### ISSUE THREAD

**Issue by Scordo** [PowerShell/PowerShell#15331]
## Steps to reproduce

Link to a related Problem in GitLab:
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27830#note_564599211

Test.ps1:
```powershell
$ErrorActionPreference = 'Stop'
just bogus
Write-Host 'hello'
```

Batch-Call (working correctly with file)
```none
pwsh -File Test.ps1
```
Exit-Code: 1

Batch-Call (working correctly with stdin)
```none
type Test.ps1 | pwsh -noprofile -noninteractive -command "$input | iex"
```
Exit-Code: 1

Batch-Call (not working correctly with stdin)
```none
type Test.ps1 | pwsh -Command -
```
Exit-Code: 0

## Expected behavior

```none
Powershell quits with non zero exit code and does not print "hello", but an exception for "just bogus"
```

## Actual behavior

```none
Powershell does execute all statement even though $ErrorActionPreference is set to "stop"
```

**Comment by Scordo** [comment]
Maybe you should introduce new parameters in 7.2 to fix the issues an remain compatible to all the usages living with the current buggy behavior.

**Comment by Scordo** [comment]
Yes `-stdin` as a new parameter would be fine. It should behave exactly the same as when running a .ps1 file. Respecting $ErrorActionPreference and so on. It would be perfect if we could also pass parameters to the script that was provided via `-stdin.

**Comment by mklement0** [comment]
@SteveL-MSFT, the current behavior of `-Command -` and especially `-File -` is unlikely to be relied upon in code with long-term stability concerns - it isn't suited to robust scripting.

Therefore, let me suggest we consider fixing the existing parameters as an acceptable [bucket 3: Unlikely Grey Area](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area) breaking change.

 To minimize the impact, fixing  `-File -` to work as @Scordo  describes would be sufficient - though I suggest including argument support while we're at it (`-Command -` has no counterpart in POSIX-compatible shells; `-` as the (positionally implied) script file name treats stdin input as if it were the content of a script).

Conversely, a `-Stdin` parameter would not only be nonstandard (not aligned with POSIX-compatible shells), but add to the already sizable number of parameters.

**Comment by JamesWTruher** [comment]
I think in this case, you could use a trap statement - here's an example of something that may serve you.

```
PS /> echo "trap { write-host `$_; exit 2 } `$ErrorActionPreference = 'stop';get-date;just bogus;get-location" | pwsh -nopro -command -       

Friday, April 30, 2021 12:57:55 PM
The term 'just' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

or a more complicated example:
```
PS /> echo "trap { write-host `$_;if ( `$ErrorActionPreference -eq 'continue') {continue}else{exit 2} } `$ErrorActionPreference = 'continue';get-date;just bogus;get-location" | pwsh -nopro -command -  

Friday, April 30, 2021 12:59:53 PM
The term 'just' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Drive        : /
Provider     : Microsoft.PowerShell.Core\FileSystem
ProviderPath : /
Path         : /

```

**Comment by jborean93** [comment]
You could also try running it in it's own statement like the following.

```
PS /> echo '& { $ErrorActionPreference = "stop"; get-date; just bogus; get-location }' | pwsh -nopro -command -
```

**Comment by daxian-dbw** [comment]
The `Enter-AzShell` cmdlet from the powershell sub kernel in .NET Interactive [depends on](https://github.com/dotnet/interactive/blob/2fb7a259874b2d3341d0145ec9485d0a8d0f74ce/src/Microsoft.DotNet.Interactive.PowerShell/AzureShellConnection.cs#L158-L160) the current behavior of `-File -`. It depends on the behavior that `-File -` prints the prompt to direct the end of a command line execution.

There may be other uses that depend on the current behavior of `-command -` and `-file -`, so I think we should keep it unchanged and adding new syntax for reading the whole stdin content as file content. Maybe `-file --`?

**Comment by mklement0** [comment]
@daxian-dbw:

(On a technicality, I claim that the silence promised in https://github.com/PowerShell/PowerShell/pull/10238#issuecomment-830406280, doesn't take effect until after 11:59:59 PM US EDT.)

While I can appreciate your due diligence here, what you're pointing out here is evidence of a fundamentally broken culture:

A different department _in the same company_ decided to release an _official feature_ based on _working around obviously broken/useless  behavior_ in a product released by a different department in the same company - rather than seeking a shared understanding and joint resolution.

**Comment by pedropombeiro** [comment]
> You could also try running it in it's own scriptblock like the following.
> 
> ```
> PS /> echo '& { $ErrorActionPreference = "stop"; get-date; just bogus; get-location }' | pwsh -nopro -command -
> ```
> 
> This will encapsulate the command you want to run as 1 scriptblock and execute that rather than each statement as 1 line.

This might work for small scripts, but if one is running 3rd-party scripts (such as in a CI solution), there's no telling how long those lines could become, so this doesn't seem like an all-round solution.

**Comment by jborean93** [comment]
It doesn’t matter, you don’t even need to have it in one line. The fact that it’s wrapped in `& { ... }` means it’s parsed as scriptblock and executed like a normal scriptblock. You can have literal new lines just like any other sbk.

**Comment by SeeminglyScience** [comment]
It seems like this feature was very specifically designed to enable emulating an interactive REPL over stdin. I doubt `Enter-AzShell` is the only thing depending on this behavior.

**Comment by mklement0** [comment]
That's a good point, @SeeminglyScience, but to me a stdin-based REPL emulation only makes sense with the _`-Command`_ parameter, not with the _`-File`_ parameter.

To fundamentally change the semantics of `-File` only because the file's content happens to come from stdin (`-`) to me is a broken feature.

And once you allow others to build features on top of broken features, the backward-compatibility trap has sprung shut, as has happened here.

It appears to be yet another instance of the legacy of having trained users not to be listened to and not to expect fixes, and these users then building their solutions with workarounds that _rely on the broken behavior_, and which a fix would therefore break - #1995 is a prime example.

**Comment by mklement0** [comment]
And here's a quick prototype showing that what Azure does with `-File -` can at least in principle also be done with the current `-Command -` functionality:

Instead of:

```sh
stty -echo && cat | pwsh -noninteractive -f -
```

plus redefinition of the `prompt` function in the session, you can use an `awk` command to do your own prompt simulation  and let `-commmand -c` merely output the results (using default prompt string `PS> ` in this example; works with macOS `awk`, GNU `awk` (`gawk`) and `mawk`, though `gawk` complains about a broken pipe on exit):

```sh
# Run from a POSIX-compatible shell, e.g. `bash`.
awk 'BEGIN { pr="PS> "; printf pr; cmd="pwsh -noninteractive -c -" } { print $0 "; [Console]::Write(\"" pr "\")" | cmd; fflush(cmd) } END { close(cmd) }'
```

The only wrinkle - which sounds like it can be overcome - is that the simulated prompt string doesn't print / print properly with _tabular_ output without / with associated formatting data; the former problem sounds like our old friend, the async 300-msec delay for determining column widths, which is definitely worth fixing: see #13985 and #4594.

(This not contributing anymore is turning out to be much more work than anticipated. Perhaps PowerShell is like the Hotel California? "You can check out anytime you like, but you can never leave.")

**Comment by Scordo** [comment]
> It doesn’t matter, you don’t even need to have it in one line. The fact that it’s wrapped in `& { ... }` means it’s parsed as scriptblock and executed like a normal scriptblock. You can have literal new lines just like any other sbk.
> 
> This is the same behaviour if you were to copy and paste the same contents that span multiple lines.

Sorry that's simply wrong. I've already tried it.

Put the following lines in a file called Test1.ps1:
```
& {
    $ErrorActionPreference = 'Stop'
    just bogus
    Write-Host 'hello'
}
```
And execute it on windows like that:
`type Test1.ps1 | pwsh -noprofile -noninteractive -command -`

When having the surrounded script block, nothing is printed/done at all.

**Comment by SeeminglyScience** [comment]
Looks like the logic for handling `IncompleteInput` parse errors isn't there.  That should probably be it's own issue (if it isn't already).  Also probably should print parse errors for that matter.

**Comment by Scordo** [comment]
Found out, that with 2 linebreaks behind the command it is working:
```
& {
    $ErrorActionPreference = 'Stop'
    just bogus
    Write-Host 'hello'
}


```

Just 2 empty lines begind the closing bracket and it is working.

The other working one is:
```
$pwshcode = {
    $ErrorActionPreference = 'Stop'
    just bogus
    Write-Host 'hello'
}

& $pwshcode
```

**Comment by mklement0** [comment]
@Scordo, to quote from the previously linked #3223, with respect to `-Command -` and `-File -`

> they require pipelines that are spread across multiple lines  for readability to be terminated with _two_ newlines (see below) - as would be necessary _interactively_, if `PSReadLine` weren't loaded.

I'm stating this in order to bring closure to my rants above (apologies if they were too harsh, but there was some pent-up frustration):
We have known about these issues for 4+ years, yet nothing was done.

Also, revisiting the comments there @iSazonov made an interesting point at https://github.com/PowerShell/PowerShell/issues/3223#issuecomment-487820506:

> `-File -` is not documented so we could change its behavior as we need.

Unfortunately, it _has_ since been documented.

That is, instead of fixing the broken behavior, it was made official.

I think I've said all I have to say, and I'm unsubscribing from this thread.

**Comment by jborean93** [comment]
> Found out, that with 2 linebreaks behind the command it is working

Ah that is right I remember coming across this and being confused as to why this failed for us, we stripped the new lines. So by adding the 2 new lines at the end it started working for us which was annoying :(. Thanks for clarifying.

**Comment by aaronla-ms** [comment]
> Maybe you should introduce new parameters in 7.2 to fix the issues and remain compatible to all the usages living with the current buggy behavior.

I mean, 5.1 -> 6.0 already borked all our scripts with the heavy breaking changes. Honestly, this would just as likely fix a script the user didn't realize was broken.

**Comment by FaustinCarter** [comment]
Is there any movement on this? This is making using pwsh on docker containers in Gitlab completely unusable.

**Comment by jborean93** [comment]
I wouldn't say it's completely unusable there are definite workarounds. The method I usually use is this

```bash
docker run \
  --rm \
  --interactive \
  mcr.microsoft.com/powershell pwsh -Command - << 'EOF'
& {
    if ($true) {
        echo "hi"
    }
}

EOF

Basically make sure there is an empty line between `}` and `EOF` so the input is accepted by pwsh and also put all your code inside a `&{}` block to ensure it is run as 1 script rather than the line by line parser that is the standard console input code.

**Comment by FaustinCarter** [comment]
That's fine for when I'm the one launching the image. The real issue is when I'm trying to use GitLab's pipeline features where I don't really have control over how they launch the image and inject the script. I just get to add lines to a script tag in a yaml file that gets executed by a runner.

**Comment by SteveL-MSFT** [comment]
@mklement0 I understand the desire to fix the behavior of `-file -` to align with precedent of other shells, but given the examples of using it as a REPL, it seems less likely to be a bucket 3 item.

I think the best solution at this time is to document the workaround as the supported way to have a multi-line script executed at once vs line-by-line.  This would work on all versions of PowerShell whereas a new switch would only work on the latest while the workaround can still be used anyways.

**Comment by FaustinCarter** [comment]
@SteveL-MSFT Do  you mind summarizing what the recommended way to handle this is? There have been a few suggestions in this thread so far, but it's not entirely clear to me what the right way to proceed is.

**Comment by SteveL-MSFT** [comment]
@FaustinCarter I think the best practice would be to have the script in a `.ps1` and execute it that way instead of using STDIN.  @jborean93 has a viable workaround https://github.com/PowerShell/PowerShell/issues/15331#issuecomment-1016942586 for cases where you can't write to a temporary `.ps1`
