### ISSUE TITLE
PSCustomObject properties with specific names fail

### ISSUE THREAD

**Issue by NotNotWrongUsually** [PowerShell/PowerShell#15370]
If an array of `PSCustomObject` contains specific property names Powershell gets confused. "Clone", as in the example below is one, but I'm going to take a guess that this goes for all method names on System.Object (only tested with "Equals", personally, but that displays similar behaviour).

Example of actual problem caused by this: when using Invoke-RestMethod with Bitbucket's API, a field named "clone" in the JSON is used to indicate the url needed for cloning a specific repo. Trying to fetch all the clone-links from the object returned by Invoke-RestMethod fails (can be worked around by creative usage of `Select-Object`)

## Steps to reproduce

```powershell
# If only one object, things are fine:
PS > $object = [PSCustomObject]@{Clone = "1"}
PS > $object.Clone
1

# Multiple objects cause strange behaviour
PS > $objects = [PSCustomObject]@{Clone = "1"}, [PSCustomObject]@{Clone = "2"}
PS > $objects.Clone

OverloadDefinitions
-------------------
System.Object Clone()
System.Object ICloneable.Clone()
```

## Expected behavior
Would have expected the output of $objects.Clone to be
```none
1
2
```

## Actual behavior
Output is
```none
OverloadDefinitions
-------------------
System.Object Clone()
System.Object ICloneable.Clone()
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
`Clone` is a method on `object[]` itself which will take priority over members of items contained within it. You'd need to manually enumerate with the pipeline, `foreach` or `$objects.ForEach('Clone')`.

**Comment by NotNotWrongUsually** [comment]
@SeeminglyScience - I understand _why_ this is happening and how to work around it. But isn't it still a bug from a usage perspective, though?

It seems inconsistent that `$myArray.Property1` and `$myArray.Property2` are not necessarily unrolled the same way. Unrolling like this also makes it a potentially breaking change when .NET adds members to the Array class (e.g. if I addressed some data from an API like `$data.values.findfirst` and the FindFirst method is later added into .NET, my code will stop working).

Adding to the confusion, the default behaviour on a single object would be to hide the original member and expose the one I overwrote it with. Unrolling a collection of those objects then decides that the property from the Array class is more important.

I think this is unexpected behaviour from the perspective of most users.

**Comment by vexx32** [comment]
PowerShell can't automatically unroll a property name if a matching method or property name exists on the collection. That's sort of by design, I guess.

It can't know ahead of time what you want. If you had a property called `Length` or `Count` on your individual objects, how would it know whether you'd want to look for the property on the collection (to find how many elements are in said collection) or the individual properties on the objects?

The situation is ambiguous, and there's not a way to resolve that. PowerShell opts to prioritise the parent object here, and I don't think it's the wrong behaviour. If it didn't, there would be absolutely no way to really find the data on the parent object. As it is, it's sometimes a little confusing (so perhaps there is room for improvement in telling the user how to find the information they _might_ be looking for in some fashion, not sure how that would work) but in the end you can still access both the parent collection's properties/methods as well as the child objects' properties/methods.

Sure, you have to iterate the collection in a case where maybe you weren't expecting to need to, but it doesn't actively prevent you from accessing either. "Fixing" this would mean effectively that child objects' properties could actively prevent you from using properties on the parent collection.

**Comment by NotNotWrongUsually** [comment]
Good points.

For what it is worth, what seems intuitive to me in the context of unrolling would be:
`$myCollection.Count` => give me the Count property from individual members of the collection _if such a property exists_, otherwise the Count of the parent object.
`,$myCollection.Count` => Always gives the Count from the parent object.

I can see how this could lead to some other confusing scenarios though (and intuitive to me might very well be illogical to someone else).

With that, I am closing the task. Maybe someone will come up with a brilliant idea for how to go about this and suggest an enhancement at some point. A bug it isn't.
