### ISSUE TITLE
Weird behavior with -replace and array indexing I have no words to describe this

### ISSUE THREAD

**Issue by ironyman** [PowerShell/PowerShell#15394]
## Steps to reproduce
This seems to only repro in a file. If I paste this pwsh then there are no issues.
```powershell

$table = @"
first
second
"@.split("`n")

$a ="test words replaceme"

echo $a
echo "replacing with $($table[0])"

# ok index into table, this output is weird
$a -replace "replaceme", "$($table[0])................"
# expect this
$a -replace "replaceme", "$("first")................"
```

## Expected behavior
```none

test words replaceme
replacing with first
test words first................
test words first................
```

## Actual behavior
Outputs the following, the first -replace operation doesn't work with array indexed replacement value
```none
test words replaceme
replacing with first
................
test words first................
```

## Environment data

```none
pwsh -version
PowerShell 7.1.3

os build 21314.1002
```

**Comment by vexx32** [comment]
This works fine for me in 7.1.3 on Windows. Can you list what version/OS you're seeing this with?

**Comment by ironyman** [comment]
Hi you're right. I updated the issue.

This seems to only repro in a file. If I paste this pwsh then there are no issues.

I also updated to pwsh 7.1.3 and it still repros. It has to be in executed in a file to repro.

**Comment by vexx32** [comment]
Oh, that explains it, I see.

You're replacing `'n` -- in a console, that's fine, because it generally won't bother to include the `` `r`` carriage return that most files have. On Windows in most cases (unless you go out of your way to avoid it / use an editor that's configured to avoid it) you will have `` `r`n`` as the line endings in files rather than just `` `n``.

If you change your ``.Split("`n")`` to something like `-split '\r?\n'` it should be safe on pretty much every modern platform (most use `\n` or `\r\n` as line endings in files, and that pattern matches both).

What's happening is that the newline is being removed in the split, but the carriage returns are not, so when you do that replace, it ends in a `` `r``, which triggers the console to move back to the start of the line and keep writing characters -- effectively overwriting and hiding the beginning characters in the string from your view.

**Comment by ironyman** [comment]
AH OK! Thank you!
