### ISSUE TITLE
ConvertTo-Json still outputs a warning when WarningAction is set to 'Stop'

### ISSUE THREAD

**Issue by donlassini** [PowerShell/PowerShell#15397]
When I try to suppress warning output from ConvertTo-Json, and use -WarningAction Stop, I still get the Warning message sent to the Warning stream.
I would expect the Warning message to be suppressed and contained in the generated exception instead.
-WarningAction SilentlyContinue works as expected.

## Steps to reproduce

```powershell
$x = (Get-ChildItem | ConvertTo-Json -Depth 2 -WarningAction Stop)
```

## Expected behavior

Throws an exception and outputs the text
```none
"ConvertTo-Json: The running command stopped because the preference variable "WarningPreference" or common parameter is set to Stop: Resulting JSON is truncated as serialization has exceeded the set depth of 2."
```

## Actual behavior

Throws an exception and outputs the text
```none
WARNING: Resulting JSON is truncated as serialization has exceeded the set depth of 2.
ConvertTo-Json: The running command stopped because the preference variable "WarningPreference" or common parameter is set to Stop: Resulting JSON is truncated as serialization has exceeded the set depth of 2.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
You can try the following
```
function test {
[cmdletbinding()]
Param()

Write-Warning "warning"
Write-error   "error"
Write-host    "Host"

}

```

` test  -ErrorAction stop  `
Prints the error message and stops
` test  -WarningAction Stop` 
Prints the warning message and stops. 

https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.actionpreference?view=powershellsdk-7.0.0 
should say explicitly that the messages are printed. 

This is by design, stopping because of an error / warning condition - but doing so silently, meaning the user doesn't know what has happened would generally be considered to be a bad thing.

**Comment by donlassini** [comment]
"This is by design, stopping because of an error / warning condition - but doing so silently, meaning the user doesn't know what has happened would generally be considered to be a bad thing."

Isn't that what the ErrorVariable and WarningVariable parameters are for? I don't think you'd want to use "-warningaction stop" if you're in an interactive prompt, hence there's no need to display that to the user.
If the user is smart enough to ask for a full stop, the user should also be smart enough to use these options.

I resolved my issue by redirecting the warning stream to $null

**Comment by jhoneill** [comment]
@donlassini  

Well there are a couple of assumptions, one is that you would specify and check warning variable every time you used -warningAction stop in the script and report the issue as needed.  The second is not using -stop interactively - it's not common but it is used. 
Redirecting the message is the right way to go. 

However I did find one thing checking on this 
with that test function 
`try {test } catch {"boo"}`    
Outputs everything     
`try {test -ErrorAction Stop} catch {"boo"}`    
Outputs "boo" _instead of_ the error message,
`try {test -WarningAction Stop} catch {"boo"}`
Outputs "boo" _in addition to_ the warning message - and the error in the catch block is not the warning message but the " The running command stopped because the preference variable "WarningPreference" or common parameter is set to Stop: warning"
