### ISSUE TITLE
Allow Get-Random -Count to return duplicates

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#15401]
## Summary of the new feature/enhancement

Get-Random should be able to return the same result multiple times when the Count parameter is specified.  
Today when you run: 
`1..10 | Get-Random -Count 10`  
you will always get one of each number from 1-10 but you should be able to get any number multiple times.  
This would also fix an issue where you get fewer items than you expected because there weren't enough inputobjects:  
`1..10 | Get-Random -Count 20`  

## Proposed technical implementation details (optional)
A switch parameter like -Unique or -AllowDuplicates could be added to control this behavior VS the current one.  
I like the "Unique" parameter name, but having a switch that is enabled by default (for backwards compatibility) is a bad user experience IMO.

**Comment by 237dmitry** [comment]
> This would also fix an issue where you get fewer items than you expected because there weren't enough inputobjects

What is the problem to increase number of input objects?
```
(1..10) * 2 | Get-Random -Count 10
```
or
```
Get-Random -SetSeed 100 -Maximum 10 -Minimum 1 -Count 10
```

**Comment by MartinGC94** [comment]
Multiplying input objects is a neat trick I didn't think about, but I don't think it solves the problem.  
It forces you to add your own logic to multiply the input object count if it's lower than the Count parameter and won't feel very random as you are still limited to getting the same item twice or whatever you multiplied with.

I don't get the point of setting the seed in the other example but using the Minimum/Maximum parameters works like I want but it's not as convenient to use that + indexing than it is to use inputobject.

**Comment by jhoneill** [comment]
@MartinGC94  
I think this working as designed at present.  

If you want numbers between 1 and 10 with possible repetitions, then 
```
get-random -Minimum 1 -Maximum 10 -Count 10` 
```
does the trick. But if you want the _first n of a randomly ordered set_ this returns it . 
```
get-verb | get-random -count 10
```
And  works for any object. 

Note that this 
`Get-Random -InputObject @('Heads','Tails') -Count 10`
Stops after two. There is no error if count > set_size. 

@237dmitry 's example with 2* actually needs to be count * so (e.g) the verb "Set" can appear 10 times. 

But if you want the option to select items in the set more than once these are better 
```
$v = get-verb
get-random -Minimum 0 -Maximum $v.Count -Count 20 | ForEach-Object {$v[$_]} 
```
or 
```
 1..10 | % {Get-Random -InputObject @('Heads','Tails') }
```

A switch `-allowduplicates` which only applies when `-inputObject` is specified would clean this up.

**Comment by jazzdelightsme** [comment]
The technical term that I am familiar with for the requested mode of operation is "selection **with replacement**". If a parameter were to be added, I think I might vote for -WithReplacement. (I also think renaming this Issue would be helpful--something like "Allow `Get-Random` to do selection with replacement"--because when I read the title I thought it was referring to the non-input case, where not returning duplicates would be surprising and very much worse.)

**Comment by MartinGC94** [comment]
Maybe it's because I'm not a native English speaker or I'm simply an uneducated pleb 😁 but I've never heard of that term and if I saw it as a parameter I would have to google it or read the help page to get any idea of what it does.

On one hand Powershell is supposed to be easy to understand but on the other hand stuff like the approved verb system has set a precedent for educating users in using correct terminology.

**Comment by jazzdelightsme** [comment]
It's true; I learned the term in a college class (don't remember if it was a straight-up CS course or a required-for-CS stats course).

The etymology of the term is simple, though: suppose you are drawing some colored marbles out of a sack, one at a time. From this you can pose the question "what is the chance you will draw N of the same color in a row" or somesuch. Naturally this depends on the numbers of different-colored marbles in the sack, but it also depends on your drawing behavior: after drawing a marble, do you put it back into the sack before drawing the next one? (i.e. do you *replace* it?)

Hence "selection WITH replacement" (putting the marbles back as you draw them), or "selection WITHOUT replacement" (don't put any marbles back in).

If *I* saw an `-AllowDuplicates` parameter here, I might also be confused. I could wonder if it meant that if there are duplicates in the input, then without this param I will get an error? (because otherwise they are not "allowed")

So I feel like the better tradeoff would be to use the more precise technical term. Yes, people might have to read the doc if they haven't had a stats course; but better to raise the general educational level of everyone than keep the confusing term for everyone (honestly, everyone would probably have to read the doc to understand what `-AllowDuplicates` would actually mean for this cmdlet, too).
