### ISSUE TITLE
Cannot get required symbol EVP_rc2_cbc from libssl

### ISSUE THREAD

**Issue by icebluey** [PowerShell/PowerShell#15411]
Powershell: [powershell-7.1.3-linux-x64.tar.gz](https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/powershell-7.1.3-linux-x64.tar.gz)
OS: ubuntu 16.04
```
$ ./pwsh 
PowerShell 7.1.3
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

Cannot get required symbol EVP_rc2_cbc from libssl
Aborted
```
```
$ readelf -a libssl.so.1.0.0 | grep EVP_rc2_cbc
0000002660f8  007a00000007 R_X86_64_JUMP_SLO 0000000000000000 EVP_rc2_cbc@OPENSSL_1.0.0 + 0
   122: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND EVP_rc2_cbc@OPENSSL_1.0.0 (7)

$ readelf -a libcrypto.so.1.0.0 | grep EVP_rc2_cbc
  3571: 00000000001265d0     8 FUNC    GLOBAL DEFAULT   13 EVP_rc2_cbc@@OPENSSL_1.0.0

```

Any ideas to resolve this issue or get more error output for details?

**Comment by jborean93** [comment]
IIRC the EVP functions are stored in `libcrypto` which `libssl` is linked to. You can try some of the following to track down more info

```bash
objdump -TC /path/to/libcrypto.so | grep EVP_rc2_cbc

ldd --verbose /path/to/libssl.so
ldd --verbose /path/to/libcrypto.so
```

You can also do `LD_DEBUG=all pwsh -Command echo "hi" &> debug.txt` to print out all the binding/linking information in the process. Beware this is a lot of information but I would search for `EVP_rc2_cbc` in that output and try and determine what actual libraries are being loaded and searched in. Other things that are important to know is the actual `libssl` and `libcrypto` files that are being loaded by pwsh/.NET. This can help track down whether it's trying the system provided ones at `/lib/x86_64-linux-gnu/lib[ssl|crypto].so` or some other one that's taking priority.

I also cannot replicate this problem in an Ubuntu 16.04 docker container so sounds like there's some conflict happening with your specific setup. You could try doing `pwsh -NoProfile` to rule out any commands being run in your profile.

**Comment by icebluey** [comment]
This issue cab be reproduced in ubuntu 16.04 docker container when openssl-1.1.1 is installed with "no-rc2 no-rc4 no-rc5".
```
apt update -yqqq && apt upgrade -fy -qqq
apt install -yqqq curl wget vim openssl libssl-dev libicu-dev perl make gcc g++
ldconfig

cd /tmp
wget https://www.openssl.org/source/openssl-1.1.1k.tar.gz
tar -xf openssl-1.1.1k.tar.gz
cd openssl-1.1.1k

./Configure --prefix=/usr/local/openssl-1.1.1 \
zlib enable-tls1_3 threads shared \
no-mdc2 no-ec2m \
no-rc2 no-rc4 no-rc5 \
no-sm2 no-sm3 no-sm4 \
enable-ec_nistp_64_gcc_128 \
linux-x86_64 

make all
rm -fr /usr/local/openssl-1.1.1
make install_sw

echo '/usr/local/openssl-1.1.1/lib' > /etc/ld.so.conf.d/openssl-1.1.1.conf
ldconfig
```

```
# must delete ~/.local/share/powershell sometimes
rm -fr ~/.local/share/powershell
/opt/microsoft/powershell/7/pwsh

Cannot get required symbol EVP_rc2_cbc from libssl
Aborted (core dumped)
```

But when I delete /etc/ld.so.conf.d/openssl-1.1.1.conf and update the ldconfig cache, pwsh works.
```
rm -f /etc/ld.so.conf.d/openssl-1.1.1.conf
ldconfig
rm -fr ~/.local/share/powershell
/opt/microsoft/powershell/7/pwsh

PS /tmp>
```

PowerShell should be linked to lib[ssl|crypto].so.1.0.0 , why does openssl-1.1.1(libssl.so.1.1, libcrypto.so.1.1) matter?

**Comment by 237dmitry** [comment]
Check your symlinks in $PSHOME directory, and change there target if it is necessary. I did something to fix stalelinks, but I don't remember what exactly.
```
 $ (dir $PSHome) -match 'lib(ssl|crypto).*'

    Directory: /opt/microsoft/powershell/7

UnixMode   User             Group                 LastWriteTime           Size Name
--------   ----             -----                 -------------           ---- ----
lrwxrwxrwx root             root               04.04.2021 10:29             25 libcrypto.so.1.0.0 -> /usr/lib/libcrypto.so.1.0.0
lrwxrwxrwx root             root               04.04.2021 10:30             22 libssl.so.1.0.0 -> /usr/lib/libssl.so.1.0.0
```

**Comment by icebluey** [comment]
pwsh aborted even that
/opt/microsoft/powershell/7/libcrypto.so.1.0.0 was linked to /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
/opt/microsoft/powershell/7/libssl.so.1.0.0 was linked to /lib/x86_64-linux-gnu/libssl.so.1.0.0
when /usr/local/openssl-1.1.1/lib was added to ldconfig cache
```
echo '/usr/local/openssl-1.1.1/lib' > /etc/ld.so.conf.d/openssl-1.1.1.conf
ldconfig
rm -fr ~/.local/share/powershell

```

**Comment by jborean93** [comment]
The libcrypto and libssl symlinks in the pwsh dir are used for libmi (WSMan). Im fairly certain that the .NET side does not use these libraries from this location and they use the SSL libs provided by the system.

**Comment by icebluey** [comment]
```
# /opt/microsoft/powershell/7/pwsh -Command echo hello
hello

# /opt/microsoft/powershell/7/pwsh
PowerShell 7.1.3
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

Cannot get required symbol EVP_rc2_cbc from libssl
Aborted

```
It's weird.

**Comment by 237dmitry** [comment]
Was you trying to install *.deb for 16.04 or snap (I do not know if it is in 16.04)?

**Comment by icebluey** [comment]
I have tried , and got the same issue.

**Comment by jborean93** [comment]
Thanks for the reproducer I'm able to replicate the problem in a docker container myself. I can see that the `/opt/microsoft/powershell/7/libSystem.Security.Cryptography.Native.OpenSsl.so` library is the one that's dynamically loading the `libssl` library which in turn loads the `libcrypto` library. You can see this by doing `LD_DEBUG=all pwsh` and looking at this in the output

```
     14282:     calling init: /opt/microsoft/powershell/7/libSystem.Security.Cryptography.Native.OpenSsl.so
     14282:
     14282:
     14282:     file=libssl.so.1.1 [0];  dynamically loaded by /opt/microsoft/powershell/7/libSystem.Security.Cryptography.Native.OpenSsl.so [0]
     14282:     find library=libssl.so.1.1 [0]; searching
     14282:      search cache=/etc/ld.so.cache
     14282:       trying file=/usr/local/openssl-1.1.1/lib/libssl.so.1.1
     14282:
     14282:     file=libssl.so.1.1 [0];  generating link map
     14282:       dynamic: 0x00007f517ee6fd60  base: 0x00007f517ebe1000   size: 0x0000000000293780
     14282:         entry: 0x00007f517ebfe710  phdr: 0x00007f517ebe1040  phnum:                  7
     14282:
     14282:
     14282:     file=libcrypto.so.1.1 [0];  needed by /usr/local/openssl-1.1.1/lib/libssl.so.1.1 [0]
     14282:     find library=libcrypto.so.1.1 [0]; searching
     14282:      search cache=/etc/ld.so.cache
     14282:       trying file=/usr/local/openssl-1.1.1/lib/libcrypto.so.1.1
     14282:
     14282:     file=libcrypto.so.1.1 [0];  generating link map
     14282:       dynamic: 0x00007f517ebd9d08  base: 0x00007f517e6e5000   size: 0x00000000004fb3a0
     14282:         entry: 0x00007f517e75b000  phdr: 0x00007f517e6e5040  phnum:   
```

It shows that it is correctly looking in the `ld.so.cache` fo `libssl.so.1.1` and because there's now a match it uses the custom ssl library and not the one the system provides. You can see in the native code that the OpenSSL shim `libSystem.Security.Cryptography.Native.OpenSsl.so` setups up tries a whole bunch of versions using `dlopen` so you won't see a direct dependency when checking through `ldd` https://github.com/dotnet/runtime/blob/64303750a9198a49f596bcc3aa13de804e421579/src/libraries/Native/Unix/System.Security.Cryptography.Native/opensslshim.c#L78-L133.

Also in that code you can see that during the init phase defined in [InitializeOpenSSLShim](https://github.com/dotnet/runtime/blob/64303750a9198a49f596bcc3aa13de804e421579/src/libraries/Native/Unix/System.Security.Cryptography.Native/opensslshim.c#L136) it first checks if `SSL_State` is defined to determine if the linked OpenSSL lib is based on 1.0.0 or not. We can see in the LD logs that this happens and fails because the loaded OpenSSL library is based on 1.1.x

```
     14335:     symbol=SSL_state;  lookup in file=/usr/local/openssl-1.1.1/lib/libssl.so.1.1 [0]
     14335:     symbol=SSL_state;  lookup in file=/usr/local/openssl-1.1.1/lib/libcrypto.so.1.1 [0]
     14335:     symbol=SSL_state;  lookup in file=/lib/x86_64-linux-gnu/libpthread.so.0 [0]
     14335:     symbol=SSL_state;  lookup in file=/lib/x86_64-linux-gnu/libc.so.6 [0]
     14335:     symbol=SSL_state;  lookup in file=/lib/x86_64-linux-gnu/libz.so.1 [0]
     14335:     symbol=SSL_state;  lookup in file=/lib/x86_64-linux-gnu/libdl.so.2 [0]
     14335:     symbol=SSL_state;  lookup in file=/lib64/ld-linux-x86-64.so.2 [0]
     14335:     /usr/local/openssl-1.1.1/lib/libssl.so.1.1: error: symbol lookup error: undefined symbol: SSL_state (fatal)
```

It then goes on to check that a whole bunch of functions that are required by the .NET OpenSSL shim are present and we can find [EVP_rc2_cbc](https://github.com/dotnet/runtime/blob/189105a302766b4d71c99c8fe0d6458476a53568/src/libraries/Native/Unix/System.Security.Cryptography.Native/opensslshim.h#L357). Because `EVP_rc2_cbc` is a required function the .NET code goes to look up that symbol and we get this error in the LD_DEBUG log

```
     14335:     symbol=EVP_rc2_cbc;  lookup in file=/usr/local/openssl-1.1.1/lib/libssl.so.1.1 [0]
     14335:     symbol=EVP_rc2_cbc;  lookup in file=/usr/local/openssl-1.1.1/lib/libcrypto.so.1.1 [0]
     14335:     symbol=EVP_rc2_cbc;  lookup in file=/lib/x86_64-linux-gnu/libpthread.so.0 [0]
     14335:     symbol=EVP_rc2_cbc;  lookup in file=/lib/x86_64-linux-gnu/libc.so.6 [0]
     14335:     symbol=EVP_rc2_cbc;  lookup in file=/lib/x86_64-linux-gnu/libz.so.1 [0]
     14335:     symbol=EVP_rc2_cbc;  lookup in file=/lib/x86_64-linux-gnu/libdl.so.2 [0]
     14335:     symbol=EVP_rc2_cbc;  lookup in file=/lib64/ld-linux-x86-64.so.2 [0]
     14335:     /usr/local/openssl-1.1.1/lib/libssl.so.1.1: error: symbol lookup error: undefined symbol: EVP_rc2_cbc (fatal)
```

If any one of these symbols don't exist then .NET prints out the error message you see and calls [abort](https://man7.org/linux/man-pages/man3/abort.3.html) https://github.com/dotnet/runtime/blob/64303750a9198a49f596bcc3aa13de804e421579/src/libraries/Native/Unix/System.Security.Cryptography.Native/opensslshim.c#L154 bringing down the whole application. We can even prove that the `libcrypto.so` compiled and added to the ld cache doesn't contain the symbol when the system library one does.

```bash
root@165e3b6118e9:/# objdump -TC /usr/lib/x86_64-linux-gnu/libcrypto.so | grep EVP_rc2_cbc
00000000001265d0 g    DF .text	0000000000000008  OPENSSL_1.0.0 EVP_rc2_cbc

root@165e3b6118e9:/# objdump -TC /usr/local/openssl-1.1.1/lib/libcrypto.so | grep EVP_rc2_cbc
```

Ultimately what this means is that a library provided by .NET requires the dynamically loaded OpenSSL lib have this symbol amongst others to be present for it to work. This isn't someting controlled by the PowerShell team and a requirement from dotnet themselves.

The only aspect I don't fully understand is why `pwsh -Command ...` doesn't fail. My only guess is an interactive session preloads the .NET assemblies whereas `-Command` does them on demand. In the end it doesn't matter as much, you are trying to use pwsh/.NET with an OpenSSL install that wasn't compiled with the OpenSSL symbols required. As for why .NET has a hard requirement of these functions you would have to open an issue on their end to get an answer.

**Comment by icebluey** [comment]
Thank you @jborean93 .
I found a solution from debug information:

> ...
32227: file=libssl.so.1.1 [0];  dynamically loaded by /opt/microsoft/powershell/7/libSystem.Security.Cryptography.Native.OpenSsl.so [0]
32227: find library=libssl.so.1.1 [0]; searching
32227:  search path=/opt/microsoft/powershell/7/netcoredeps/tls/x86_64:/opt/microsoft/powershell/7/netcoredeps/tls:/opt/microsoft/powershell/7/netcoredeps     (RPATH from file /opt/microsoft/powershell/7/pwsh)
32227:   trying file=/opt/microsoft/powershell/7/netcoredeps/tls/x86_64/libssl.so.1.1
32227:   trying file=/opt/microsoft/powershell/7/netcoredeps/tls/libssl.so.1.1
32227:   trying file=/opt/microsoft/powershell/7/netcoredeps/libssl.so.1.1
...
32227: file=libcrypto.so.1.1 [0];  needed by /usr/local/openssl-1.1.1/lib/libssl.so.1.1 [0]
32227: find library=libcrypto.so.1.1 [0]; searching
32227:  search path=/opt/microsoft/powershell/7/netcoredeps/tls/x86_64:/opt/microsoft/powershell/7/netcoredeps/tls:/opt/microsoft/powershell/7/netcoredeps     (RPATH from file /opt/microsoft/powershell/7/pwsh)
32227:   trying file=/opt/microsoft/powershell/7/netcoredeps/tls/x86_64/libcrypto.so.1.1
32227:   trying file=/opt/microsoft/powershell/7/netcoredeps/tls/libcrypto.so.1.1
32227:   trying file=/opt/microsoft/powershell/7/netcoredeps/libcrypto.so.1.1

We build custom openssl 1.1.1 only for powershell and copy libssl.so.1.1 and libcrypto.so.1.1 to /opt/microsoft/powershell/7/netcoredeps/tls/x86_64/ .

PowerShell and .NET work fine.
