### ISSUE TITLE
Give more completion context info to argument completers

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#15437]
## Summary of the new feature/enhancement

Argument completers get the following parameters: $commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters

This is great but I would like to also get: $cursorPosition, ref $replacementLength, ref $replacementIndex  
This will enable completion for substrings, like the string you provide to the Filter parameter for Get-CimInstance.

Example: `Get-CimInstance Win32_Process -Filter "Name = 'pwsh.exe'"`  
If my cursor is in the "Name" area my argument completer would show Win32_Process properties and if my cursor is in the "=" area it would show operators.

If you want to do this today you either have to assume the cursor is always at the end of the line or just show all possible options with no regard for the cursor position.

## Proposed technical implementation details (optional)
Add the cursorPosition parameter to the list of parameters given to argument completers and if passing objects by reference is possible do that for replacementLength and replacementIndex.  
If it's not possible to set the replacement length/index from the argument completer then argument completers will just have to keep that in mind and use the whole string as a completion result.

**Comment by powercode** [comment]
I've also been missing this for a long time!

**Comment by jhoneill** [comment]
I suspect changing the parameters for the completeArgument() method may turn out to be a non starter. 

There's a pattern of filter or where clause that allows us to specify `"Name = $Procname and (memory >y or starttime < 'z')` 
this gets quite nasty, because your completer is needs to  figure out brackets, variables whatever else is inside the ""

But usually we only want the filter to be something like `-Where <<one-fieldname>> -eq <<one-value>>`
It might make more sense to implement a proxy function with `where` and  `eq/ne/gt/lt/like` etc parameters and use the existing style of completer for the values for `where`.    It means the syntax is very like `where-0bject`   
I have a getSQL module and it will allow 
`get-sql "Select * from sales where customer = 42 and value > 100"`    
or  
`get-sql  -table sales " where  customer = 42 and value > 100"`    
or 
`get-sql  -table sales  -where  customer -eq 42`  

The table name table completes and once we have the table name the fields in `where`  also tab complete

**Comment by MartinGC94** [comment]
A simple argument completer is better than nothing at all and knowing the position of the cursor will allow you to write a pretty decent completer for a WMI filter with very little effort.

The filter was also just an idea of where it could be useful, I'm sure there are other examples where knowing the position of the cursor would be useful for completions.

**Comment by jhoneill** [comment]
If this had been anticipated a long time ago, it would be useful to have. Having written quite a lot of completers in my time (initially promoting  @lzybkr 's TabExpansion++ for PowerShell 3 and more recently with PowerShell and C# classes) I haven't needed it and it's very easy to fall into the trap of "I don't so no-one does".  
However the complete operation is a method which takes a set of parameters - you can't just call it with a couple of extra ones, so a way to work round the problem is needed. 

Anything which has a string parameter which breaks into multiple parts could  benefit - where clauses or whole queries being the obvious case.  Staying with CIM/WMI we can have a WQL query for example    
`Get-CimInstance -Query "select name,processID from win32_process where name like 'pwsh%' " `    

But it isn't trivial to write a something which sees `"Select  From [tab]"` 
And offers me `"Select  From {classes}"` and then lets me go back and do   `"Select [tab]  From win32_process "`   
 and gives me `"Select {cim class properties}  From win32_process "`     
(Full on SQL gets even more complicated). 
 
Now, as you say, simple is better than nothing because most cases **are** simple.  Most of the time we don't write a full WQL statement we just write a simple `where` clause which gets built into one.  
```
Get-CimInstance -Filter  " (name like 'pwsh%') or (name like 'powershell') "  -ClassName win32_process -Verbose
VERBOSE: Perform operation 'Query CimInstances' with following parameters, '
'queryDialect' = WQL,
'queryExpression' = SELECT * FROM win32_process WHERE  (name like 'pwsh%') or (name like 'powershell') ,
'namespaceName' = root\cimv2'.
```

So I come back to saying "Let the command assemble the string from multiple parameters". So for SQL I have table, select, where, sort which are easy to write completers for. (select, where and sort all use the same one).  I have -EQ, -NE etc which get converted to SQL operators. 

I'd have dynamic parameters `-Where` appears if `classname` is present `-eq` , `-like` etc appear if where is present.  I'd create a template proxy function (automatic) from Get-CimInstance and drop the parameters in   A completer for where produces the fields for the class name (and namespace if present) without needing to worry about the cursor position,; operators being parameter names don't need a completer. Then it's a switch statement to change `-eq  value`  to `= 'value'`  and a string join or two and job done. 

I might write this up as a blog post and share it as gist

**Comment by MartinGC94** [comment]
I'm a little confused about what your point is. First you say it would have been useful if it was added sooner and right after you say you haven't felt a need for it after writing a ton of argument completers.

I like the idea of building queries dynamically but I don't think that means people shouldn't have the option of creating their own argument completers that use the cursor position because queries aren't the only place where this would be useful, an argument completer for a hashtable would benefit as well.

Adding this feature is simple, it's just a matter of adding the cursor position to the list of arguments given to the argument completer: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs#L2434 the harder part is setting the replacementIndex/Length from PS I haven't really looked into that.

**Comment by vexx32** [comment]
It's not as simple as just adding a parameter there; adding a new mandatory parameter to that method will break existing code, mostly likely.

However, adding a new overload that can be used might be a workable solution, though I'm unsure exactly how that would be used from the PS side of adding argument completers and whether additional handling may be needed to ensure the new overload is picked for scriptblocks that support enough parameters.

**Comment by jhoneill** [comment]
If it had been included at the start we would, no doubt, have found places to use it.
But it wasn't. Working with what was there has been OK, I've produced all those completers and never thought "What  I need to be doing is building string parameters". 

You can't "just add the cursor position"
Here's an example of a completer 
```PowerShell
function ListFonts {
    [CmdletBinding()]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingEmptyCatchBlock", "")]
    param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameter)
    if (-not $script:FontFamilies) {
        $script:FontFamilies = @("","")
        try {
            $script:FontFamilies = (New-Object System.Drawing.Text.InstalledFontCollection).Families.Name
        }
        catch {}
    }
    $script:FontFamilies.where({$_ -Gt "" -and $_ -like "$wordToComplete*"} ) | ForEach-Object {
        New-Object -TypeName System.Management.Automation.CompletionResult -ArgumentList "'$_'" , $_ ,
        ([System.Management.Automation.CompletionResultType]::ParameterValue) , $_
    }
}

Register-ArgumentCompleter -CommandName New-ExcelStyle  -ParameterName FontName -ScriptBlock $Function:ListFonts
```

```
listFonts  "" ""  "ar" $null $null 7            
ListFonts: A positional parameter cannot be found that accepts argument '7'.`
```

Or here's one using a c# class I wrote 
```powerShell
 $c = [vsteam_lib.ProjectCompleter]::new()
$c.CompleteArgument("","","", $null, $null, 7)
MethodException: Cannot find an overload for "CompleteArgument" and the argument count: "6".
```

How to use pre-existing argument completers. There are thousands of them 

> I don't think that means people shouldn't have the option  ...

That's where I said it would have been good if this had been designed in at the time of PowerShell 2 or 3. But retro fitting it now is a problem which is probably bigger than benefit. 

There is a whole class of problems which the query / query-clause exemplifies where we say here is compound parameter expressed as another data type you could have 
```
@{ fieldname = 'ProcessName' ; operator = 'equals' ; value = 'pwsh.exe'}
Or write it as text in JSON, CSV, XML or "code" format  - you can freely translate although "code" needs parsing and the more complex the string the more awkward it gets to code it all in one monolithic piece.  Helping the user with the code still requires them to know something about the underlying API - for example a rest API might use `EQ` and `NE` instead of `=` or `<>` , which in other places might be `==` and `!=` it needs them to that here CIM/WMI use sql-like syntax and % is the wildcard not *.  

The compound parameter is sometimes  unavoidable to keep from a stupid number of parameters e.g. I have     
`New-GraphUser ...  -Fields `  and fields is a hash table because I don't want parameters for every Azure AD field (and it's easier to send to the underlying API if everything is a hash).  
 
But suppose for a simple case the hash table above we could splat it into the function. What we really want is something which says `get-ciminstance win32_process -where processname -like pwsh*`  don't we?  
Something inside should figure out  that WQL means the * has to be changed to a % and so on. Sometimes we want to need or prefer to use a complex filter which we'll write by hand. But if we jump between functions which call LDAP,  SQL, REST - and sometimes different ways of expressing what we want in two SQL or REST implementations.  I wouldn't say that string helpers are bad - though they may need to be inside psreadline rather than argument completion per-se.

**Comment by MartinGC94** [comment]
Look closer at the code I linked, it's not a method it's just an object array.  
Existing argument completers that use a param block shouldn't be affected because the new parameter will simply not be bound to any of their parameters. The only way I can see this affecting existing argument completers is if they use $args instead of a param block to access the parameters and even that would only be a problem if they count backwards for some reason `$fakeBoundParameters = $args[-1]` or iterate over them.

**Comment by vexx32** [comment]
I'm happy to be proven wrong, but as far as I recall, additional parameters don't get _dropped_ so much as squashed in if you're naming the parameters. For example, currently if you declare a param block with:

```powershell
param($Command, $Parameter, $WordToComplete, $CommandAst, $FakeBoundParams)
```

Currently, this would work just fine for an argument completer scriptblock. If that invocation is changed and an additional argument _added_, then I think the last declared parameter would end up with _multiple_ things in it rather than just the one that's expected.

So it's got a decent possibility to break something here, imo.

**Comment by MartinGC94** [comment]
It works like I described before and this can easily be demonstrated with this snippet:
```
Register-ArgumentCompleter -CommandName Get-ChildItem -ParameterName Path -ScriptBlock {
    param($commandName)
    $Global:CompletionDemo = $commandName
}
```
Try to tab complete a value for the Path parameter for Get-ChildItem and check the variable $CompletionDemo it will only contain the command name (in this case Get-ChildItem).

If you can build PS locally you can try to change the line I linked to earlier to this: `new object[] { commandName, parameterName, wordToComplete, commandAst, GetBoundArgumentsAsHashtable(context), context.CursorPosition },` and see that it works perfectly fine.

**Comment by vexx32** [comment]
Oh, good. Thanks for the clear illustration!

I'm still not sure about the C# side of things and non-scriptblock argument completers. Currently you have to override an existing method ([example](https://github.com/vexx32/PSWordCloud/blob/main/Module/src/PSWordCloud/Completers/FontFamilyCompleter.cs)) with a set # of parameters. 

Ideally we'd make this available to C# completers as well, but I'm not sure the best path to follow for that. Just an extra overload to override? Someone with more experience in how this system works would probably need to take a look and see if there's something else that needs done to make it work beyond just adding an overload that can be overridden, without breaking anything that already uses that API.

**Comment by powercode** [comment]
I think we would need to add a new interface `IArgumentCompeleter2` with the required methods.

The engine would first check for the new interface and fall back to the old.

**Comment by SeeminglyScience** [comment]
DIM would also work, but would be much harder to polyfill when targeting netstandard2.0.  `IArgumentCompleter2` is probably the way to go.

**Comment by jhoneill** [comment]
> It works like I described before and this can easily be demonstrated with this snippet:
> 
> ```
> Register-ArgumentCompleter -CommandName Get-ChildItem -ParameterName Path -ScriptBlock {
>     param($commandName)
>     $Global:CompletionDemo = $commandName
> }
> ```

I think that example is fine because script block doesn't have cmdletBinding  specified. That's not always the case  Here's one which I think would break in the importExcel module (most popular version has 250K downloads) 
```powershell
function ListFonts {
    [CmdletBinding()]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingEmptyCatchBlock", "")]
    param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameter)
    if (-not $script:FontFamilies) {
        $script:FontFamilies = @("","")
        try   {$script:FontFamilies = (New-Object System.Drawing.Text.InstalledFontCollection).Families.Name}
        catch {}
    }
    $script:FontFamilies.where({$_ -Gt "" -and $_ -like "$wordToComplete*"} ) | ForEach-Object {
        New-Object -TypeName CompletionResult -ArgumentList "'$_'" , $_ , ([CompletionResultType]::ParameterValue) , $_
    }
}
Register-ArgumentCompleter -CommandName New-ExcelStyle  -ParameterName FontName -ScriptBlock $Function:ListFonts
Register-ArgumentCompleter -CommandName Set-ExcelColumn -ParameterName FontName -ScriptBlock $Function:ListFonts
Register-ArgumentCompleter -CommandName Set-ExcelRange  -ParameterName FontName -ScriptBlock $Function:ListFonts
Register-ArgumentCompleter -CommandName Set-ExcelRow    -ParameterName FontName -ScriptBlock $Function:ListFonts
```
If the completer is a class then calling the method with an extra parameter will fail, - @SeeminglyScience 's suggestion seems to work around that.  It would need something similar to say explicitly "this script block can take additional parameters".

**Comment by SeeminglyScience** [comment]
> I think that example is fine because script block doesn't have cmdletBinding specified.

With the way that the scriptblock is called (`ScriptBlock.Invoke`), `CmdletBinding` is ignored.  Shouldn't be an issue.

**Comment by theJasonHelmick** [comment]
This is very interesting and we see the value of this work.  We would be happy to review a PR from the community.

**Comment by powercode** [comment]
Draft PR here for discussion: #17358

**Comment by powercode** [comment]
I have not yet considered how it should be exposed to scripts
