### ISSUE TITLE
Powershell 7 arm64 version reported that "CN=Microsoft Corporation" is untrusted publisher

### ISSUE THREAD

**Issue by mithrandir** [PowerShell/PowerShell#15440]
## Steps to reproduce
Unzip [Powershell 7.1.0 arm64](https://github.com/PowerShell/PowerShell/releases/download/v7.2.0-preview.5/PowerShell-7.2.0-preview.5-win-arm64.zip) or [7.2.0 preview 5 arm64](https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/PowerShell-7.1.3-win-arm64.zip)
And execute pwsh.exe. 

## Expected behavior
It shouldn't have such problem.

## Actual behavior

```
Do you want to run software from this untrusted publisher?
File C:\users\user\powershell-7.2.0-preview.5-win-arm64\Modules\PSReadLine\PSReadLine.format.ps1xml is published by
CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US and is not trusted on your system.
Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):

```

## Environment data
ARM64 Windows 10 on ARM64 PC (Galaxy Book S). 
And interestingly, x86 version is totally ok.

**Comment by TravisEz13** [comment]
Security Working group

This is by design.  PowerShell Core [execution policy](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.1) by default doesn't trust anything by default it is up to you decide what you trust.

This is may be because you downloaded the zip using a Windows Microsoft browser and you can use [`unblock-file`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/unblock-file?view=powershell-7.1#:~:text=The%20Unblock%2DFile%20cmdlet%20lets,the%20computer%20from%20untrusted%20files.) or the Windows GUI to unblock the files. It is better if you unblock the zip file before you extract it so you only have one file to unblock.
