### ISSUE TITLE
Script module scope variables not available to module commands invoked through script

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#15465]
Originally reported to me by @FriedrichWeinmann.

Module script-scope variables are supposed to be available across functions within a module (kind of like private module fields).

However, if you define two module functions where one executes a provided script file that's supposed to invoke another, the script variable isn't available to the inner function.

See the repro for a full explanation.

## Steps to reproduce

In `mod.psm1`:
```powershell
$script:Counter = 0

function Invoke-Script
{
    param($Script)

    Write-Host "Pre-invoke: ${script:Counter}"

    & $Script

    Write-Host "Post-invoke: ${script:Counter}"
}

function Add-Counter
{
    Write-Host "Incrementing: ${script:Counter}"
    $script:Counter++
}
```

In `run.ps1`:
```powershell
Import-Module ./mod.psm1
Invoke-Script ./inner.ps1
```

In `inner.ps1`:
```powershell
Add-Counter
```

Then run this with `./run.ps1`.

Compare with invoking a scriptblock, which works:

```powershell
Import-Module ./mod.psm1
Invoke-Script { Add-Counter }
```

## Expected behavior

```none
￼￼Pre-invoke: 0
Incrementing: 0
Post-invoke: 1
```

## Actual behavior

```none
Pre-invoke: 0
Incrementing: 
Post-invoke: 0
```

## Environment data

PowerShell 7.2-preview.5

Also seen in Windows PowerShell 5.1.

**Comment by Vacant0mens** [comment]
@rjmholt It seems like the issue comes from passing in a _scriptblock_ rather than a _script file_. The script block would get executed in the `script` scope of the `run.ps1` script, while the script file (`inner.ps1`) would have its code run in its own separate `script` scope that doesn't know anything about the `Counter` variable. (which would essentially be calling `$null++`)

This would also explain why it reacts the same between v5.1 and v7.2+

Unless this issue is more complicated than it seems, my guess, is that if you used [dot-sourcing](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scripts?view=powershell-7.3#script-scope-and-dot-sourcing) both the script block and the `inner.ps1` script would end up with the same results.
(e.g. in the `Invoke-Script` function use `. $Script` instead of `& $Script`)
