### ISSUE TITLE
Establish a known, cross-platform ordering of output from Get-ChildItem and provide a parameter to opt out of sorting

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#15476]
## Summary of the new feature/enhancement

From https://github.com/PowerShell/PowerShell/issues/15304.

`Get-ChildItem` should provide output in a consistent ordering across platforms if possible, and if implemented should add a switch to opt out of the overhead of sorting.

One important question around this ordering is whether it should be case-sensitive or not across platforms. Currently it is sorted with `CurrentCultureIgnoreCase`:

https://github.com/PowerShell/PowerShell/blob/c857392c34613fc8ece1432ceb89a5310d9e5fd9/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L1617-L1618

However, it may be desirable on *nix platforms or on case-sensitive filesystems to make the ordering discern case-sensitivity.

**Comment by iSazonov** [comment]
No need to complicate the cmdlet. It is wrong design intention. All cosmetics must be in formatting subsystem if needed and they could be switchable. For scripts we should use explicit formatting where need using Sort-Object cmdlet or .Net methods.
Don't kill PowerShell performance at whole for the sake of pink in the output.

**Comment by jborean93** [comment]
I personally feel like pwsh shouldn’t be ordering at all and just output the objects as they are retrieved from the file system. This is more performant when dealing with large structures as it doesn’t need to collect everything to then sort. If the end user desires it to be sorted they can pipe the output into `Sort-Object` and sort as they wish.

**Comment by vexx32** [comment]
To be clear; we're _already_ sorting this, have been since... probably 6.0. The formatting system currently does not support actual sorting of objects.

Consider also if the formatting system was the only thing doing sorting. Users could `Get-ChildItem`, see the results, try to `Get-ChildItem | Select -First 1` or `$items[0]` and the item they end up with is not the one they saw in the output. I don't think sorting in formatting is the answer here, it only leads to more confusion.

Yes, there are performance concerns because of that, most likely. However, it's probably not unreasonable to say that some kind of sorted output is _expected_, especially on MacOS or Linux systems, whose filesystems do not tend to order by default. The `ls` utility sorts by name by default, so I think it's not unreasonable for folks to generally expect that PS's Get-ChildItem does the same.

It you call `[System.IO.Directory]::EnumerateFileSystemEntries($path)` on Mac/Linux from PS, you can see what I mean. There is essentially no intrinsic ordering at all, so if we didn't order things it would be a complete mess and Get-ChildItem would pretty much always have to be paired with Sort-Object when used interactively, which isn't really ideal. 

Adding an opt-in to more performant behaviour is definitely not _ideal_ (I would kinda prefer that as the default, really), but I think it's not an unreasonable concession to have slightly less performant behaviour for a cmdlet that's often used interactively. I think users will complain if they have to constantly reach for `gci | sort-object name` instead of just `gci` when working at a console.

For cases where the interactive behaviour is not necessary or particularly important, an option that can be provided (even as a default via $PSDefaultParameterValues) is an OK compromise in my opinion.

**Comment by iSazonov** [comment]
> The ls utility sorts by name by default, so I think it's not unreasonable for folks to generally expect that PS's Get-ChildItem does the same.

Every time I see an appeal to Unix it makes me nervous. 
Whatever part of Unix we touch, we always find in its history discussions or even claims that it works wrong but it doesn't get fixed because it's been working for _years_.
I sometimes get the feeling that Unix consists entirely of deviations from concepts, violations of standards and bugs in implementation which are declared as Unix standards! 😺 

_PowerShell 1.0 appeared as a rethinking of previous experiences (including Unix) based on the most advanced concepts of the time._
Is it worth referring to Unix as the benchmark in this situation (I am not talking about minor inconsistencies in implementation, but about concepts)? No.

Unfortunately the conceptual development process of PowerShell stopped a long time ago. It got bogged down in the swamp of everyday life and backward compatibility. Although the number of incompatible changes is already so great that it makes no sense to talk about backward compatibility.

_We should be discussing and trying to implement modern innovative concepts more than pink colored letters or ala old school Unix behavior._

**Comment by vexx32** [comment]
I don't disagree with your points @iSazonov but I think some concession for usability in `Get-ChildItem` which is very often used interactively is not unreasonable here. 🙂

**Comment by jessey-git** [comment]
The sorting extends beyond display, to tab-completion as well -- which 7.1 broke spectacularly (#14757) and is why I won't upgrade to it as long as possible.

**Comment by jessey-git** [comment]
Any movement here?  I don't see why, in any universe, '_' should come before '.' for file listing or tab-completion at least as per the issue noted in my above comment.

**Comment by iSazonov** [comment]
After we get new .Net API we will use it in FileSystem Provider v2 (FSPv2). As result, the sorting will be removed from the provider. We will consider moving the sorting to Formating Subsystem.

**Comment by SteveL-MSFT** [comment]
The FileSystemProvider already sorts output by Directories followed by Files and for each they are case-insensitive sorted https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L1633.
