### ISSUE TITLE
Test-Json : Add parameter for JSON data file

### ISSUE THREAD

**Issue by GlenAppleton** [PowerShell/PowerShell#15544]
## Summary of the new feature/enhancement

The Test-Json command already allows for both a file or a string for the schema definition.  Please do the same for the actual JSON data being tested.  For example:

Test-Json -JsonFile .\MyData.json -SchemaFile .\MySchema.json

## Proposed technical implementation details (optional)

This new parameter would be an alternative method to having to load the data in a separate command into a variable using Get-Content -Raw, and it would be consistent with the alternative method already provided for the schema data.

**Comment by ArmaanMcleod** [comment]
Following up from https://github.com/PowerShell/PowerShell/pull/19042#discussion_r1091830388.

Need to also confirm behaviour of paths, especially with including `-LiteralPath`. In the draft PR I showed how it can be done with `-Path`.

If we just keep `-Path`, the parameter sets would be:

```powershell
Test-Json [-Json] <string> [<CommonParameters>]

Test-Json [-Json] <string> [-Schema] <string> [<CommonParameters>]

Test-Json [-Json] <string> [-SchemaFile] <string> [<CommonParameters>]

Test-Json [-Path] <string> [<CommonParameters>]

Test-Json [-Path] <string> [-Schema] <string> [<CommonParameters>]

Test-Json [-Path] <string> [-SchemaFile] <string> [<CommonParameters>]
```

If we include both `-Path` and `-LiteralPath`, the parameter sets would be:

```powershell
Test-Json [-Json] <string> [<CommonParameters>]

Test-Json [-Json] <string> [-Schema] <string> [<CommonParameters>]

Test-Json [-Json] <string> [-SchemaFile] <string> [<CommonParameters>]

Test-Json [-Path] <string> [<CommonParameters>]

Test-Json [-Path] <string> [-Schema] <string> [<CommonParameters>]

Test-Json [-Path] <string> [-SchemaFile] <string> [<CommonParameters>]

Test-Json [-LiteralPath] <string> [<CommonParameters>]

Test-Json [-LiteralPath] <string> [-Schema] <string> [<CommonParameters>]

Test-Json [-LiteralPath] <string> [-SchemaFile] <string> [<CommonParameters>]
```

Also would need to consider if the path parameters would be using `ValueFromPipelineByPropertyName`. The `Json` parameter currently uses `ValueFromPipeline` so that would have to stay. 

What would be the most sensible path pattern for `Test-Json` to follow? Just throwing out some ideas since I think path support for this cmdlet would be super useful. Happy to make an RFC when a direction is decided (if at all).

@GlenAppleton @iSazonov @SteveL-MSFT.

**Comment by iSazonov** [comment]
It seems it is close to Test-Path. So I'd expect we have Path and LiteralPath, and also support ValueFromPipelineByPropertyName.
