### ISSUE TITLE
Distribution Support Request: PowerShell for Android

### ISSUE THREAD

**Issue by hez2010** [PowerShell/PowerShell#15556]
## Details of the Distribution

- Name of the Distribution: Android
- Version of the Distribution: Android 11
- Package Types
    - [ ] Deb
    - [ ] RPM
    - [ ] Tar.gz
    - [x] apk
- Processor Architecture (One per request): ARMv8
- The following is a requirement for supporting a distribution **without exception.**
    - [ ] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).
- The following are requirements for supporting a distribution.
  Please write a justification for any exception where these criteria are not met and
  the PowerShell committee will review the request.
    - [x] The version of the Distribution is supported for at least one year.
    - [x] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

## Progress

- [ ] ~An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker~ Docker images are not needed

### For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by iSazonov** [comment]
Please use Distribution Support Request template to create such request.

**Comment by hez2010** [comment]
@iSazonov Done. Should I create separate issues for Android and iOS?

**Comment by iSazonov** [comment]
Yes, please create separate issues.

**Comment by hez2010** [comment]
Done

**Comment by fMichaleczek** [comment]
@iSazonov 
I had success there is one year one on Android with a modified SMA. (when I was testing WASM)

![alt text](https://pbs.twimg.com/media/EcmQiByXYAAm9xM?format=png&name=large)

The problem is ... there is no Console at all.

Possible workaround : 
- use XtermJS as a Blazor Hybrid app (so same code base as WASM) but had a lot of bugs because XtermJS in a process or in a browser is not the same 
- use termux (I haven't any idea how to mix it with Xamarian Forms) 

@hez2010 Do you work on the subject ? 

For iOS, it doesn't work : "Since applications using Xamarin.iOS are compiled to static code, it is not possible to use any facilities that require code generation at runtime."
source : https://docs.microsoft.com/en-us/xamarin/ios/internals/limitations

**Comment by hez2010** [comment]
@fMichaleczek I found a C# port of XtermJS may be able to work on Android: https://github.com/xamarin/XtermSharp

**Comment by fMichaleczek** [comment]
@hez2010 I will have a look. 

There is 3 ways : Blazor or Maui or a mix of both. 
Because I am working on the wasm port, I am more interested by Blazor Shared  Components. 

But there is limitation until net7.0/8.0 on the Blazor/Maui gateway, so the standalobe Maui port is the better candidate for tomorrow.

**Comment by fMichaleczek** [comment]
@hez2010 It's not a port of Xterm.JS, it's a port of TerminalUI on top on an existant PTY. Android is a web OS, so pty is not a native API, so embedded XtermJS in a Blazor Shared Component exposed to Maui is still the roadmap for me. I'm still monitor the progression of aspnet teams, but it's still in experimental features (the MAUI/Blazor  samples)

**Comment by TravisEz13** [comment]
This does not meet the distribution support requirements in the template.  Specifically .NET does not support this.
