### ISSUE TITLE
Get-WmiObject not available

### ISSUE THREAD

**Issue by superbonaci** [PowerShell/PowerShell#15565]
Can't run this command on PS 7
````
PowerShell 7.1.3
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\> Get-WmiObject
Get-WmiObject: The term 'Get-WmiObject' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
````

**Comment by jborean93** [comment]
This is expected (and [documented](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/breaking-changes-ps6?view=powershell-7.1#wmi-v1-cmdlets)). The WMI cmdlets have been replaced with the CIM cmdlets since v3 came out and it was in v6 that the WMI ones were ultimately removed. To be compatible with both you should use the CIM cmdlets. In this case it's `Get-CimInstance -Class Name MyClass`.

**Comment by superbonaci** [comment]
So no bug working as intended. Thanks for the info wasn't aware.
