### ISSUE TITLE
Powershell Core (7.1.3) and (7.2.0-preview.7) crashing on Ubuntu 21.04 - no usable libssl

### ISSUE THREAD

**Issue by najeebanwer** [PowerShell/PowerShell#15608]
## Steps to reproduce
Powershell and Powershell-Preview installed as snaps on Ubuntu 21.04
![Screenshot from 2021-06-18 13-54-01](https://user-images.githubusercontent.com/34123660/122605804-910c0a80-d03d-11eb-964a-13cb6b3d23e8.png)

## Expected behavior
Powershell enters interactive mode.

## Actual behavior
Powershell crashes with the message:
"No usable version of libssl was found
Aborted (core dumped)"

## Environment data
![Screenshot from 2021-06-18 14-04-11](https://user-images.githubusercontent.com/34123660/122606164-1a234180-d03e-11eb-89c5-ac5c5896a0dc.png)

**Comment by toeserve** [comment]
I can confirm this. Ubuntu 21.04. Did snap install powershell. I get error no libssl found. Then core dump.

**Comment by megamorf** [comment]
Related to #15567, #15101 and #15029

**Comment by kilasuit** [comment]
From the docs Ubuntu 21.04 is not currently supported - https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1

![image](https://user-images.githubusercontent.com/6355225/124516542-d0767d00-ddd9-11eb-848b-b8de1bcac635.png)

**Comment by diddledani** [comment]
There are symlinks in the snap package at `opt/powershell/libcrypto.so.1.0.0` and `opt/powershell/libssl.so.1.0.0` which point relatively to `usr/lib/[architecture-triplet]/libcrypto.so.1.0.01` and `usr/lib/[architecture-triplet]/libssl.so.1.0.0` respectively. The snap does not include the two files referenced, so the symlinks are broken. This is likely causing issues elsewhere and the only reason it works at all on some distros is because due to classic confinement the linker can find a usable library from the host (which is bad snap practice!)
