### ISSUE TITLE
$input type in advanced functions

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#1563]
We have a test for `$input` type behavior in advanced functions (functions that are cmdlets).

``` powershell
It '$input Type should be enumerator' {
        function from_begin { [cmdletbinding()]param() begin { Write-Output -NoEnumerate $input } }
        function from_process { [cmdletbinding()]param() process { Write-Output -NoEnumerate $input } }
        function from_end { [cmdletbinding()]param() end { Write-Output -NoEnumerate $input } }

        (from_begin) -is [System.Collections.IEnumerator] | Should Be $true
        (from_process) -is [System.Collections.IEnumerator] | Should Be $true
        (from_end) -is [System.Collections.IEnumerator] | Should Be $true
    } 
```

https://github.com/PowerShell/PowerShell/blob/b731549a198c538d0e5e3ca4c50183f988b5f7e2/test/powershell/Language/Parser/AutomaticVariables.Tests.ps1#L3

This tests works fine in PS v2. Since then, the behavior changed to this

``` powershell
        (from_begin) -is [System.Collections.ArrayList] | Should Be $true
        (from_process) -is [System.Collections.ArrayList] | Should Be $true
        (from_end) -is [System.Object[]] | Should Be $true
```

Which is pretty inconsistent, but exists since v3.

@lzybkr was trying to fix it (back to v2 behavior) and it broke a couple customer scenarios.

Plan: we will gover feedback about this issue and may consider go thru breaking change process.
Meanwhile, I'm marking the test as `-Skip`

**Comment by iSazonov** [comment]
If we plan a breaking change it is better make it before RTM.

**Comment by daxian-dbw** [comment]
scripts to summarize the differences
--------
```powershell
function from_begin { begin { @{"simple function Begin block" = $input.GetType().FullName} } }
function from_process { process { @{"simple function Process block" = $input.GetType().FullName} } }
function from_end { end { @{"simple function End block" = $input.GetType().FullName} } }


function cmdlet_from_begin { [cmdletbinding()]param() begin { @{"script cmdlet Begin block" = $input.GetType().FullName} } }
function cmdlet_from_process { [cmdletbinding()]param() process { @{"script cmdlet Process block" = $input.GetType().FullName} } }
function cmdlet_from_end { [cmdletbinding()]param() end { @{"script cmdlet End block: {0}" = $input.GetType().FullName} } }

. { from_begin; from_process; from_end; cmdlet_from_begin; cmdlet_from_process; cmdlet_from_end }
```
resutls on PowerShell V2
-------
```none
Name                           Value
----                           -----
simple function Begin block    System.Collections.ArrayList+ArrayListEnumeratorSimple
simple function Process block  System.Collections.ArrayList+ArrayListEnumeratorSimple
simple function End block      System.Collections.ArrayList+ArrayListEnumeratorSimple
script cmdlet Begin block      System.Collections.ArrayList+ArrayListEnumeratorSimple
script cmdlet Process block    System.Collections.ArrayList+ArrayListEnumeratorSimple
script cmdlet End block: {0}   System.Array+SZArrayEnumerator
```
results on PowerShell V3 and newer
-------
```none
Name                           Value
----                           -----
simple function Begin block    System.Collections.ArrayList+ArrayListEnumeratorSimple
simple function Process block  System.Collections.ArrayList+ArrayListEnumeratorSimple
simple function End block      System.Collections.ArrayList+ArrayListEnumeratorSimple
script cmdlet Begin block      System.Collections.ArrayList
script cmdlet Process block    System.Collections.ArrayList
script cmdlet End block: {0}   System.Object[]
```
Some context I found from an early email:
------
> `$input` is documented in the language specification as being an enumerator (`IEnumerator`), and that’s how it’s implemented in V2.
> V3 unintentionally changed the type of `$input` in a script cmdlet to an `ArrayList` or `Array` (depending on when you ask).
>
> I thought it was a relatively safe fix to make because the use of `$input` in a script cmdlet should be uncommon because it’s usually better to use a parameter that has `ValueFromPipeline` or to just use `$_`.
>
> It turns out I was wrong.  We have reverted the change and the fix is scheduled to be delivered as part of the ZDP for the Windows 10 Anniversary Update.
>
> That does leave us in this weird place – scripts that target V2 and later might not work correctly if they use `$input` in a script cmdlet.
> It also means the `$input` is different in a script cmdlet and ordinary function.
>
> So we may revisit this in the future, but if we do, we’ll do a better job notifying people about the change in behavior.

**Comment by daxian-dbw** [comment]
@PowerShell/powershell-committee This issue is ready to be reviewed again.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agreed it doesn't make sense to make this change back to v2 behavior at this time since v3+ users would be broken

**Comment by dmidlo** [comment]
* I have to clarify.... The project I was telling you about last night... by all appearances; none of that was with intent...  just...  cowardice maybe?
as far as I can tell; just ... not knowing how, still saying yes...  
and then years of irresolute, backburner 'We have to do something' that never materialized;  
lack of ownership and inability.

Um... I haven't been able to get back to this code; because there's another project  
with a slightly smaller human footprint which should be done this week;  
but a much larger spread geography (therefore topology is more complex, and nearly as degraded...  
work stalled out nearly two years ago on this one  
*again, just through discovery, trying my best to manage responsible disclosure when in client one-on-ones,  
ad-hoc researching the history of a particular box as I'm passing by it.) 

I'm not out to smear anyone;  
my current writing style I... guess... is a redirection of that to the tooling.  
(you boys got me to realize that without realizing they were helping in that way)

Not even mad, not really; sleep-deprived and snappy I think...  
just… holding the weight of too many dropped threads.

Three folks are all related; father/son & son-in-law;  
these guys are oblivious to the job  
(I really like them as people, save some casual racism that didn't show up until they felt more comfortable with me...  
The idea here is that they know my wife and children are PoC....  
that's frustrating... but my idea around that is; well, what has my wife been through? more.  
so inescapable to some degree.

they over-invested in passive-income strategies and fake-it-till-you-make-it ideas.

The only other guy there who has/had a shot at wrapping up has a decade on me;  
if I track it.. he started out in telecom;  
then used that to get in a gig to manage a service desk which then got acquired,  
moved to being a trainer during the MSCE days....

this is absolutely the wrong framing; but he's my supervisss... 'handler'. It feels that way...

About once every other week; I can see he'll log my burnout...  
I'll ask him context questions for whatever and he'll say  
"never touched that project, this *family* wouldn't let me;"  
then I'll be digging through the system seeing many several tickets where he was clearly banging his head against it....

I directly called him out on it before the new year, finger pointed at his name on the screen; clicking through tabs of his tickets; he doubled down an said, "I don't remember every project I've worked on; if you've been in this industry as long as I have...."  

We're not that big for that to even be real....  

Like once a week he reminds me of his accomplishments... he tells this story about how his peers in tech education always gave him a hard time  
that his labs were broken; which he says he did that on purpose to the bright students to give them more of a challenge; that it was his 'trick' for getting the highest pass rate among them;  
but I think he might have just been a dumps feeder.

My 'orientation' was him leaning against the threshold of my door for two-hours everyday for the first month  
saying how lazy and incompetent the other three were....  
um.... I couldn't get anything done;

"parity-what-it-means-to-be-an-ijsec-practitioner-its-not-me-its-you"  on dev.to

I wrote this article in september  
in the hope he was somehow monitoring me and would get the message and lay off  
so I could fix what seems to be his mess....

but he didn't see it; and kept standing there, apparently throwing a smoke screen and redirection.  
He never saw the article....

anyway; the stages of grief skipped straight to acceptance at when he said he couldn't remember and refused to be refreshed by his own handwriting....  I've just been heads down after that... realizing my only teammate was going to be an LL-fucking-M. 

um I wrote up that jupyter notebook over in #AI  
because I hadn't been able to log my tickets according to my ritual  
with him there every morning ranting....

a lot of my tone and style is by being the average of those around you right now too I guess.

I think he saw it after I published "The Problem: Powershell's Hashing Illusion".  
I wrote that because I've been kinda regressing away into the keyboard  
and not being my normal "people-oriented" person...

my... tongue has been shutting down...  
not just like siliconvalley post-zone verbal-lameness...  
I had to figure out a way to describe the problem I was working on  
and was struggling during our virtual-standups to articulate from my broken mouth  
to their less-acquainted experience. My supa has been not showing up to work after that; but I think he's managing hospice for his parents and trying not to fall off the wagon and I feel for the guy.

Matt C here said "Charles Bukowski" because I needed to share some of these details with someone in the thread.... or at least I felt like I did.... I thought I might get kicked out; nothing personal; some discord servers are like that.... and yeah getting kicked out is way better then how people used to act on IRC.

In those lifetimes ago...  
It all—tricking my parents into letting me go solo for weeks in Germany when I was 16...
I was the kid who tore apart computers. Small town. Manually brute forced a BIOS password when I was 9 on our first Micron to play “Monster Truck Madness”.... you know what the password was ‘snow’ ... it took forever.

9th grade my best friend (and only other nerd) bought Red Hat in a box, from Best Buy.

We were neighbors and in cub-scouts and boy-scouts together, and he was brilliant... I never dreamed of the stuff.
​
He and I didn’t re-meet until 9th grade... one day the Secret Service literally showed up at the middle school and hauled him off.... he was printing fake money. So off to the alternative learning center he went.
​
I took Visual Basic, C++, two years of Cisco Networking Academy, graphic desgin... only to hang with him.

Formally, I've had three years of German, Two years of Spanish, a year of French (all lost to time now);  

I'm getting acquainted with Colloquial Egyptian Arabic after years with my wife....

Basically highschool was "Languages" of one sort or another for me.

That and welding; biggest game in my small town financed an amazing welding program for our school...

When I was 19; that’s when Hurricane Katrina hit the coast.... I sold everything I had.... my car... my clothes... my tech.... everything except my guitar and hitchhiked from Minnesota to Mississippi with something like $5000 bucks in cash.... learned how to swing a hammer from Mennonite Volunteers.... I worked until I ran out of money.... I had an envelope with just enough cash set aside for a Greyhound. 16 families... their houses their lives... me and the guy I finally found who was on the way for the same reason stayed in a rundown house.... somehow we ended up getting a small word out (that all was Rick...) and soon had a steady supply of semi-trucks dropping off clothes, chainsaws, building materials.... 16 families. When I came home, I had learned a trade and kept working in it. By the time I got back, my best friend had given himself over to meth... I never touched the stuff... having an ‘al naturale’ approach to life, grass was it, I was the one who introduced it to him... slowed me down. But he took it too far, and I was off trying to save the world, so we drifted apart obviously... Kept swinging hammers for a few years until one day I heard he wasn’t doing well. He was the most brilliant guy I ever knew.... and it wasn’t even the drugs.... he found out he had melanoma and three months later I found out. The day I did I found out he was already back at his folks in hospice; I told him I’d be there every day after I got off work... and I was. but he only gave me three days; on the third I drove up expecting to see what I saw with my grandparents... I thought I made a longer commitment. I showed up late... it was one of those hammer-swinging sun-up, sun-down days, but looking through their half-basement’s sliding glass door I saw that moment I saw just the same with my grandparents... it was dark; and his folks were right up against him.... they told me he waited for me; that he was basically gone for hours. I pulled in, they made way, I held his hand and said, “Cory I’m here.. sorry I’m late” and he was gone gone in less than my five minutes of being there...
​
I kept swinging hammers for a while... but... yeah... it just wasn’t doing it for me... So, I chopped off my nice sub-contracting thing; was doing fine... bout 70 after taxes... felt like a king before taxes... I quit that and took the first tech job that would give me a shot.... 72 applications from a hammer-swinger and the only place that would give me a shot was Best Buy as a seasonal employee. First day on the job was Black Friday and I broke the store’s record for new PC setups.... moved two giant empty shelves and unboxed every last computer we were about to sell and just kept my fingers moving and popping disks in trays.

I forgot to mention music-school, taking out a personal mortgage  
to start a live-in home so I could mentor homeless and at-risk kids.... and....  
 Bukowski...  I've... lol... literally never seen the movie; but I get that from time to time...

I removed televisions from my life just out of high school  
after I realized I could stay awake and get 100% completion on Final Fantasy games  
in one sitting on mountain-dew and marijuana.... I got to 100% in FFX in 5 1/2 days without sleep.

I think my resume made them think I was like them;  
and their folksy rural-meets-metro made me think they were like me.

I was a stay at home dad until six months ago....

my oldest is starting 9th grade next year; she's a wonderful illustrator,  
we just did high-school orientation and she'll be starting off with pre-calc....  
she goes to a classical academy and will have four years of latin;

next in line is my step-son (his dad saw him once or twice a year);  
I've been there since Adam was three....

My wife was finishing up a nursing program when we met;  
her childhood; was not good; and it's not mine to share beyond that....  
let's just say it all culminated in a physically coerced marriage perpetrated by her parents.  
she didn't really know how to be a mom early on; so I didn't become a stay at home until Adam needed me.

He got screened for a gifted and talented school in third grade  
(now going on eighth, two oldest are a year apart)  
and was doing really good;  
but his dad came back and now he's not doing homework;

we just had really good breakthroughs this month on that, he and I;  
His brain is now developed enough to start accepting some more advanced wisdom;  
so the tales I elucidate here have been able to articulate:

"how to learn from other people's mistakes  
so you can make your own new beautiful and creative ones"

Our youngest two:  
Kindergarten, then the other in pre-school at a French immersion; they love life! but they're freedom is theirs to be children atm; we're doing the all the stuff; but it's to early to see who it is they might want to be.

I've been just trying to find the signal in the noise; but less and less.

I'm here because I've found myself literally building an embeddable versioning system for powershell objects; so I can make sure I don't get scapegoated as responsible for all this....

And I've been coping inside of box; I may have a wide range of experiences, but I've seen them all through in due course.... and I feel like I'm going to be made the fall-guy becasue in Q3-Q4 of I see cliff-edges coming up; that me, my LLM, and all the tooling we can build together is just not enough.  I've tried to set up meetings for strategic planning.... built systems.

I work nights open sourcing my work because they don't deserve rights to the IP; this way I can bring my MIT code back in and stay productive....  <- this feels dishonest to me; and I don't know that you can tell; but I don't do well with gray ethics internally....   "discretion", unless we're talking about hurt feelings tears apart my very being. 

I'm going to say what I've been hiding from myself and dancing around:

I haven't been putting out applications because I keep thinking about the scope of impact of a sudden departure on their clients-employees' families; and; honestly if you can't tell by the propensity to overshare; I'm not neurotypical. Having only been diagnosed with ADHD as I was coming on 35, I've been learning a lot about myself in recent years;  Anyway if there's I fire it is quite literally all my brain can focus on....  My kinda people (probably several of us) kept our early ancestors safe in those cold dark nights....

If anyone can even fucking match a 74k with no-healthcare, benefits, or retirement package of any kind,  at a company that hasn't lost three major clients in a single quarter to other MSP.   I want time to do really good work; I want to continue learning.  I want others to be empowered to create and dig in. I'll onboard tomorrow.  I don't want to become roadkill for caring enough to step into traffic....  

We all know how this goes; I know this is a message in a bottle...  and I can't bring myself to go back through to read it to see if I even am making any sense.

All I really wanted to say; was thanks for focusing on the tech and code review early this morning.  If I did my job I don't think I've left much to the imagination as to how much it means to talk to more than the 'Juniper' voice layer and my wife about all this.
