### ISSUE TITLE
Invoke-Item.Tests.ps1 should close test file

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#1568]
After a `Start-PSPester`, file `testfile.txt` is left open.

cc @ealexjordan @andschwa

**Comment by iSazonov** [comment]
The test start child powershell and then interactive process Notepad (it is a default assoc for .txt) which never stops(!) and keeps the file open. The test wait the child powershell process but not control Notepad. So the test really dont test Invoke-Item at all. Bug.

I suggest using a custom association for custom file ext:
```
$testfile = "testfile.!!testext!!"
remove-item $renamedtestfile
new-item $testfile
cmd.exe /c assoc !!testext!!=rename %0 $renamedtestfile
invoke-item $testfile
test-path $renamedtestfile | Should Be $true
cmd.exe /c assoc !!testext!!=
```

**Comment by andschwa** [comment]
There is really nothing to be done about this. You cannot control the association in a cross platform manner, and as such you cannot know what process to kill. PowerShell delegates to cmd/xdg-open/open which then all launch what they determine to be the associated app. By the time the app is opened, PowerShell has zero knowledge of what it is.

**Comment by lzybkr** [comment]
The parent/child process relationship could be used. It's not 100% reliable on Windows (if the parent exits, you can draw false conclusions) but that shouldn't be a problem for us here.

**Comment by andschwa** [comment]
Won't work for `xdg-open`, the parent of the spawned process is `/sbin/upstart` (in my quick test of a .txt file on Ubuntu 16.04).

**Comment by andschwa** [comment]
(This is the expected behavior since `xdg-open` just starts the child process and immediately exits.)

**Comment by ealexjordan** [comment]
I definitely remember having serious issues with this test, but it was written in response to a reported failure that was occurring on MacOS and Linux (and I believe Windows as well?).

The main problem I hit is that Invoke-Item has no return value, which means I can't get a PID back to close down what was opened. I can't guarantee the file association/process, nor do I think it's a good idea to alter those in any way on a user's system.

If anyone has an alternate solution, I think it would be fantastic, I agree it's not ideal at all.

**Comment by iSazonov** [comment]
I repeat to be exact...

> Invoke-Item
> Performs the default action on the specified item.

How to check the **_default action_** without knowing that this action is? No way!
The current test causes any _**unknown**_ action. What if it's always print or beep? The current test will always be positive.

We need to know _**exactly the result**_ to verify its correctness (more precisely, correctness of an action that would lead to it).

We can either figure out the default action from OS, or configure it. The first option cannot help us, because the default actions usually cause an interactive process, which we can't verify. (We can check that Word is started but what if the Word pop up a interactive window "Cannot open file" because of  Invoke-Item send broken file name?) The second option is useful to us, because we can set a specific action (for example, rename the file) and exactly check the result.

Of course we will have to make such a test separately for _**each**_ platform. I can make PR for Windows now.
