### ISSUE TITLE
Cannot call method of a (C# class) object when a property of the same name exists

### ISSUE THREAD

**Issue by mamidenn** [PowerShell/PowerShell#15689]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to the [known issues](https://docs.microsoft.com/powershell/scripting/whats-new/known-issues-ps6).

### Steps to reproduce

* Create a class explicitly implementing an interface so that it has a property and a method of the same name.
```ps1
Add-Type @"
public interface MyInterface
{
    string Turncoat { get; }
}

public class MyClass : MyInterface
{
    string MyInterface.Turncoat { get { return "Property"; } }

    public string Turncoat() { return "Method"; }
}
"@
```
* Create an object of that class and try to call the method
```ps1
$myObject = [MyClass]::new()
$myObject.Turncoat()
```

The method is in kind of a limbo-state. `$myObject | Get-Member` lists it, it can be called via Reflection, but simply calling it like `$myObject.TurnCoat()` yields an `InvalidOperation`.

### Expected behavior

1. I expect to be able to call the method

```ps1
$myObject.Turncoat()
```
```console
Method
```

2. I expect *not* to be able to access the property (and get the method's info instead)
```ps1
$myObject.Turncoat
```
```console
MemberType          : Method
OverloadDefinitions : {string Turncoat()}
TypeNameOfValue     : System.Management.Automation.PSMethod
Value               : string Turncoat()
Name                : Turncoat
IsInstance          : True
```

### Actual behavior

1. I am *not* able to call the method
```ps1
$myObject.Turncoat()
```
```console
Method invocation failed because [MyClass] does not contain a method named 'Turncoat'.
```

2. I *am* able to access the property
```ps1
$myObject.Turncoat
```
```console
Property
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mamidenn** [comment]
Vaguely related to #8235.

**Comment by SeeminglyScience** [comment]
Note that changing this would be a breaking change.  An example is `JProperty` from Newtonsoft.Json:

```csharp
class JProperty
{
    // inherited
    T Value<T>(object key);

    JToken Value { get; set; }
}
```

Maybe the binder should prioritize methods over explicitly implemented interface properties rather than *any* property.  Though that would still be breaking change, I can't quickly find an example of an existing API with a realistic use case that would be broken.

Personally I think this comes up infrequently enough that a workaround of `$obj.psobject.Methods['MethodName'].Invoke($args)` is probably good enough.

**Comment by vexx32** [comment]
That example also wouldn't be as much of a problem if #12412 was merged, since you could specify the type parameter for the method.... at least I _think_ that'd work properly 🤔

**Comment by SeeminglyScience** [comment]
> That JProperty example also mightn't be as much of a problem if #12412 was merged, since you could specify the type parameter for the method.... at least I _think_ that'd work properly 🤔

Technically it would be possible for the binder to target the method without requiring generic args since the `()` should be enough to signal intent.  That wouldn't be the most difficult of changes, but still non-trivial due to how some of the `DotNetAdapter` APIs are structured.

However returning the overload definitions instead of invoking the property getter as requested in the OP is probably a too risky of a change.

**Comment by vexx32** [comment]
Yeah, I'd agree... if we were going to fix this in any way, I would personally prefer that `$obj.Name()` calls the method and `$obj.Property` calls the property getter. Overload definitions would be hidden, but all functionality would work as expected otherwise... and overload definitions could still be retrieved via reflection if needed, I think?

**Comment by SeeminglyScience** [comment]
> and overload definitions could still be retrieved via reflection if needed, I think?

Reflection or just `$obj.psobject.Methods['MethodNameHere']`

**Comment by mamidenn** [comment]
> However returning the overload definitions instead of invoking the property getter as requested in the OP is probably a too risky of a change.

It's not that that necessarily *want* to get the overload definitions instead of invoking the getter. That was just the behavior I expected. I would be totally fine with invoking the getter here.
