### ISSUE TITLE
Something is broken in PowerShell 7 (in Get-ADUser?)

### ISSUE THREAD

**Issue by petrasteri** [PowerShell/PowerShell#15687]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to the [known issues](https://docs.microsoft.com/powershell/scripting/whats-new/known-issues-ps6).

### Steps to reproduce

Hello,

The following code, when run under PowerShell 7, is "broken".  But when it's run in PowerShell 5 (Windows Server 2016), it runs perfectly.

`$employeeNumber = "000"`
`Get-ADUser -Filter {employeeNumber -eq $employeeNumber}  | select name`

PowerShell 7 Version 7.1.3

The error message is
_**Get-ADUser: Variable: 'employeeNumber' found in expression: $employeeNumber is not defined.**_

I'll attach a screen shot to show the difference.

### Expected behavior

```console
Not broken and returns some AD users
```

### Actual behavior

```console
Error message:
Get-ADUser: Variable: 'employeeNumber' found in expression: $employeeNumber is not defined.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/12992229/123802180-4b77f900-d8eb-11eb-94a1-914784e094bf.png)

**Comment by Northman-de** [comment]
According to this https://docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2019-ps `-filter` is of type string and not a scriptblock.
This works:
`Get-ADUser -Filter "employeeNumber -eq '$employeeNumber'"`

**Comment by vexx32** [comment]
Check `Get-Module ActiveDirectory`; I suspect pwsh is loading it in a compatibility session, which will make it run inside a hidden PSv5.1 process and thus a separate environment than your actual pwsh session, so the variable won't be found. If it is, you'll see the ActiveDirectory module reported as a script module with (I think?) a version reported as `0.0.0` or similar.

You can try importing the module into pwsh directly with `Import-Module ActiveDirectory -SkipEditionCheck` and see if you get better results there. From memory, on newer servers the ActiveDirectory module has been updated and should auto-import correctly.

You may still have issues on a 2016 box, though, even with forcing the module to be imported; there were some outstanding bugs in the module running on .NET Core that needed to be fixed, if memory serves.

Another option is to ignore all of the above and simply change your filter syntax. As @Northman-de mentions, scriptblock syntax is (at best) a bit of a lie, and the documentation should never have been written that way IMO. The AD module converts it to a string and then re-parses the string manually looking for variables, which just flat out breaks around the edges. Changing the parameter syntax as they suggest should allow the values to be properly evaluated by pwsh instead of the AD module, and generally has a better success rate in general.

**Comment by jborean93** [comment]
Windows 10 Build 14393 is from 2016 which is most likely not marked as comptaible with .NET core and as @vexx32 says it will load in an implicit remoting session. AFAIK it was in Server 2019 that the ActiveDirectory module was updated to support .NET Core and will run natively in PowerShell. Any of it's operations are run in a separate process and runspace and does not have access to any of your vars so it won't be able to find `$employeeNumber` when it converts that scriptblock to the LDAP filter.
