### ISSUE TITLE
Introduce 'Escape' parameter for commands that yield paths (eg Get-ChildItem)

### ISSUE THREAD

**Issue by plastikfan** [PowerShell/PowerShell#15734]
### Summary of the new feature / enhancement

Ever since beginning to use PowerShell I have been plagued by the problem of square brackets appearing in file system paths. However, I have since learned to use an effective but incorrect workaround. Instead of using **-Path**, I have exclusively been using **-LiteralPath**, but this cuts me off from being able to use wildcards.

It appears to me that **-LiteralPath** was introduced to 'fix' this, but actually I now realise that this was not the correct fix to implement (unless there is some other issue of which I'm not currently aware). Instead of using **-LiteralPath**, I should instead have been using -Path but then escaping the returned paths using [[System.Management.Automation.WildcardPattern]::Escape](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.wildcardpattern.escape?view=powershellsdk-7.0.0),

eg

```powershell
gci | % { [System.Management.Automation.WildcardPattern]::Escape($_.FullName) }
```

The next item in the pipeline (not shown), can now use the pipeline item with a -Path parameter. However, this is cumbersome and highlights to me that the LiteralPath solution was a misnomer.

I know the LiteralPath can't be removed because of legacy reasons, but its presence has caused me to write a lot of incorrect code, which I should probably go back and update.

EDIT: this was the original request but not was was intended, see my updated comment
```
Instead, why can't we have a third option that actually replaces the use of **Path**/**LiteralPath**, ___EscapedPath___ (they could be deprecated without being removed). This would mean the the user can retain the use of wildcards using a single parameter. I would like to see this parameter to be introduced to all those standard powershell commands that use **Path**/**LiteralPath**, including but not limited to:

+ Rename-Item
+ Move-Item
+ Remove-Item
+ Copy-Item

Paradoxically, **New-Item** does not use LiteralPath, so I'm not sure how it handles wilcard characters in file system paths.
```

Other commands like Get-ChildItem/Get-Item should be updated to return pre-escaped Paths.

**Comment by plastikfan** [comment]
Actaully, I've realised that my request is not quite right. There is no need to introduce a new parameter **EscapedPath**. rather, we can abandon *LiteralPath* and any function that yields a path, should just return it already escaped, so that means that commands like **Get-ChildItem**/**Get-Item** would need to be changed, and the other commands that I have mentioned would remain unchanged. Or you could introduce a new switch parameter to **Get-ChildItem**/**Get-Item** let's call it ___Escape___  which would invoke the escaping of paths.

**Comment by jborean93** [comment]
There are a lot of use cases mixed in with paths and I think returning the wildcard escaped variant for the output here is wrong. I could be using the full path for many things unrelated to these cmdlet, e.g. calling a .NET function, writing the value to a file, etc. All these values don't understand the concept of wildcards and it would be wrong for them to contain them IMO. 

One of the methods to avoid all this pain is to pipe the objects into each other, e.g.

```powershell
$item = Get-Item -LiteralPath 'C:\temp\[folder]'

# Do stuff with $item

$item | Remove-Item
```

This works because the `-LiteralPath` accept input by property name and it has an alias `PSPath` that matches to the `PSPath` outputted by `Get-Item`. This means that it's essentially the same as doing `Remove-Item -LiteralPath $item.PSPath`.

> Paradoxically, **New-Item** does not use LiteralPath, so I'm not sure how it handles wilcard characters in file system paths.

It's simple, `New-Item` creates something and thus doesn't have a concept of wildcards at all. Wildcards are only useful when you are trying to interact with existing objects

**Comment by iSazonov** [comment]
I guess we could add an flag in source cmdlet if an object comes from file system (vs from user) so that cmdlet consumer can see if it really need to do globbing for Path parameter.
