### ISSUE TITLE
continue behaves like break with foreach-object

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [PowerShell/PowerShell#15762]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

With `foreach-object`, `continue` completely exists the loop, not just current iteration, not like with normal `foreach`. I see it in both old PowerShell 5 and latest version of PowerShell Core.

### Expected behavior

```console
PS C:\WINDOWS\system32> @(1,2,3,4,5) | % {
>> if ($_ -eq 3) {continue}
>> $_
>> }
1
2
4
5
```

### Actual behavior

```console
PS C:\WINDOWS\system32> @(1,2,3,4,5) | % {
>> if ($_ -eq 3) {continue}
>> $_
>> }
1
2
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                           Value
----                           -----
PSVersion                      5.1.19041.1023
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1023
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by vexx32** [comment]
Both `continue` and `break` only function correctly with the language-level loops. `ForEach-Object` isn't one of those, so like if you call `continue` or `break` anywhere else in a script, they will terminate all execution until either they find an enclosing loop to continue/break or all execution is halted.

`return` functions like `continue` for the purposes of ForEach-Object, but the only way to `break` is to throw an exception. There is no other method to terminate a pipeline early, with the exception of `Select-Object -First $x`, which basically just throws an exception inside the engine that the user never sees in order to terminate the pipeline early.

**Comment by 237dmitry** [comment]
As I know, for this purpose in `ForEach-Object` is always used `return`.  
`continue` is for loops.

**Comment by IlyaFinkelshteyn** [comment]
Ah, OK, thanks for the clarification!
