### ISSUE TITLE
[Microsoft.Powershell.SDK] Invoking Dism (or any) Modules commands return 0

### ISSUE THREAD

**Issue by krishnan-unni** [PowerShell/PowerShell#15816]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am trying to invoke dism cmdlets to get the windows updates installed in a machine. So I'm running my .Net 5 concole app with Microsoft.Powershell.SDK 7.1.3. Here is my test code:

```
static void Main(string[] args)
        {
            using (var powerShell = PowerShell.Create())
            {
                // returns 
                var coms = powerShell
                    .AddCommand("get-command")
                    .AddParameter("Module", "Dism")
                    .Invoke();

                var dism = powerShell
                    .AddCommand("import-module")
                    .AddParameter("Name", "Dism")
                    .Invoke();

                var results = powerShell
                    .AddCommand("get-windowspackage")
                    .AddParameter("online")
                    .Invoke();

                
                // Display each result object.
                foreach (PSObject result in results)
                {
                    //parse results
                }

                System.Console.WriteLine("Hit any key to exit...");
                System.Console.ReadKey();
            }
        }
```

I can run the same command in Powershell directly and I see the results just fine.

### Expected behavior

```console
I should be able to see the results with installed updates in my running OS.
```

### Actual behavior

```console
The Invoke for import and Get-WindowsPackage -Online commands return 0 count on PSObject list.

![image](https://user-images.githubusercontent.com/14880339/126570423-3ed8712f-d41a-4bbc-9e40-f0bd7a0fcd32.png)
```

### Error details

```console
There is no error. Although if I misspell the cmdlet name or the module, then it clearly throws exception. So it is clear that the cmdlet is detected and so is the module.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/14880339/126570423-3ed8712f-d41a-4bbc-9e40-f0bd7a0fcd32.png)

**Comment by bergmeister** [comment]
I'll try take a look at this the next few days

**Comment by bergmeister** [comment]
Hi, this is because you do not clear the commands between executions. Adding a `powerShell.Commands.Clear();` between your invocation blocks will make it work.
Having said that, you can reduce your example to just one invocation because one does not need to manually import PowerShell modules that are on the `PSModulePath` environment variable, which is the case with modules that are installed or part of the OS like e.g. `Dism`.
If you still have to execute multiple commands, then you could make your own `InvokeAndClear` extension method to keep your code DRY like e.g. here: https://github.com/PowerShell/PSScriptAnalyzer/blob/58c44234d44dfd0db35bb532906963e08fde8621/PSCompatibilityCollector/Microsoft.PowerShell.CrossCompatibility/Utility/PowerShellExtensions.cs#L12
Also please note that if you want to execute something more complex later on, there is also an `AddScript` method. You are probably already aware but running `get-windowspackage -online` requires admin rights, therefore when you invoke your compiled binary, you will need to run as admin.

**Comment by krishnan-unni** [comment]
@bergmeister Thank you and for pointing out the extension. That sorted out the problem. And yes, the run as admin is expected in this case, I'm aware. 2 questions - is there an official documentation on this Invoke and Clear approach? 
What is the reasoning behind this design? To have a command be cleared every time its invoked? Why is it not an automatic behavior? 
P.S: I am closing the issue since its resolved and the questions are for my own curiosity.
