### ISSUE TITLE
Memory leak in Invoke-Command: PowerShell memory consumption increases with the number of executed commands

### ISSUE THREAD

**Issue by nascarsayan** [PowerShell/PowerShell#15827]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Create a `New-PSSession` to a remote PC.
2. Do any `Invoke-Command` on the PSSession which returns a significant size of stdout.
3. Run Garbage Collectors to release as much memory as possible. I am running this : <br/> `[System.GC]::Collect(); [GC]::Collect(); [GC]::WaitForPendingFinalizers();`
4. Run steps 2 and 3 multiple times, the memory keeps on increasing with the number of executions.

### Expected behavior

```console
Memory consumption should reach a limit, and not increase thereafter.
```

### Actual behavior

```console
Memory consumption keeps on increasing with the number of executions.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

[This][1] clip shows the repro

[1]: https://youtu.be/8xsdyyG5A7E

**Comment by mkozaaczka** [comment]
Hello
I also like confirmed that issue is visible on Linux docker with.net core 3.1, PowerShell SDK 7.0.6 and as well on .net standard 5.0 , PowerShell SDK 7.1.4. I run following code https://docs.microsoft.com/en-us/powershell/scripting/developer/hosting/creating-remote-runspaces?view=powershell-7.1 that is run in continuous loop with rate 1 command per sec. After 1.5hour of working memory get leaked to 2 gigabytes level. I took memory dump and managed memory heap + loaded dlls (analyzed thru using sos) is fine up to 50 megabyte so I believe, that  leak is appearing in unmanaged code. 

Can some one look on this issue ?
![image](https://user-images.githubusercontent.com/63739355/130230628-361d2fc7-ce0b-4552-8c78-b623d4b155e4.png)

**Comment by PaulHigin** [comment]
@WG-Remoting
Remoting working group: What we need is a simple repro script that demonstrates the problem.  Since accurately determining true memory/handle leaks in managed code is difficult, we require a solid repro along with correct memory analysis.

**Comment by nascarsayan** [comment]
Hi @PaulHigin, the memory leak does not depend what script we are running. It is always happening, both from PowerShell and from C# code. Is there any way, the cached items can be disposed of? Or do we need to follow up with some other team? Please let me know, as this is a very concerning issue for my team (Azure Arc for SCMM).

**Comment by iSazonov** [comment]
> Create a New-PSSession to a remote PC.

Is the connection WinRM or SSH?

**Comment by PaulHigin** [comment]
@nascarsayan This issue is lacking important details such as which parameter set is being used, which determines what connection type is used (WinRM or SSH).  Also the running script does make a difference as it could be collecting data on the client end.  Please provide the repro test script, and steps to run the script that exhibits the problem.  Also note that WinRM based remoting is not supported on non-Windows platforms, only SSH remoting is officially supported.

**Comment by nascarsayan** [comment]
Sorry for the late reply.

@iSazonov , the connection is over WinRM.

@PaulHigin , I have created a concrete working program, that you can run from either Linux or Windows, in a docker container, or on k8s.
Please find the repo and code here:
https://github.com/nascarsayan/TestPSSession

The code is pretty small. It just opens a `WInRM` connection to some remote PC, executes `return` and disposes the session.
**The leak is happening only in Linux, and not on Windows.**
**I tried analyzing the heap dump, as I have written in the `README.md` of the repo, and I observed that it is most likely **native memory leak**, since the Heap Memory usage was pretty much the same.

Please let me know if any other information or analysis is to be done on my end.

Will be thankful if we can find the root cause. Thanks a lot!

**Comment by iSazonov** [comment]
> The code is pretty small. It just opens a `WInRM` connection to some remote PC, executes `return` and disposes the session.
> **The leak is happening only in Linux, and not on Windows.**

WinRM is not supported on Unix systems.

**Comment by PaulHigin** [comment]
Please see:
https://github.com/PowerShell/PowerShell/issues/17390
