### ISSUE TITLE
Extensions of non-PowerShell scripts (such as .pl for Perl scripts etc.) must be listed in PATHEXT in order for the script to be run in the same console.

### ISSUE THREAD

**Issue by ReneNyffenegger** [PowerShell/PowerShell#15854]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When trying to run a non-PowerShell script whose filename extension is associated with a script interpreter, for example using the `cmd.exe` commands `ftype` and `assfoc`, the script extension (for example `.pl` for Perl scripts), this extension must be listed in the `PATHEXT` environment variable in order for this script to be run in the *same* console as the one from which the script was started (if the script is started without specifying the interpreter executable). If this extension is not listed in `PATHEXT`, PowerShell will open a new console and run the script in this new console. (See also [this Stackoverflow question](https://stackoverflow.com/q/68606397/180275) and  [its accepted answer](https://stackoverflow.com/a/68607090/180275)).

### Expected behavior

```console
I would have expected the script to be run in the current console regardless of its extension being listed in `PATHEXT`.
```

### Actual behavior

```console
Executing the script opens a new Console
```

### Error details

```console
none
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1023
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1023
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by MatejKafka** [comment]
Encountered the same behavior. I consider it a bit surprising, given that PowerShell behaves differently from `cmd` here.

I'm not sure it's an issue, it could be an intended behavior, but I'd love to see it documented and hear a rationale for why it works this way. I don't see why I'd want to have a file type associated with a console application, but open it in a new console window.

At the same time, the original purpose of PATHEXT is different (which extensions are looked up in PATH when a native command is specified without extension), and PowerShell adds a different, mostly unrelated purpose (which extensions open in the current console window), which is a bit odd.

**Comment by MatejKafka** [comment]
I think the checking is done here:
https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/NativeCommandProcessor.cs#L1557

The function is used here:
https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/NativeCommandProcessor.cs#L1294

**Comment by rkeithhill** [comment]
The Engine WG discussed this issue today.  

The current behavior is by design however, we agree that documentation is needed (assuming it's not already documented in the help somewhere).

Rationale:
PowerShell is using `PATHEXT` to determine if a file is executable on Windows.  This usage is documented [here](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc737438(v=ws.10)) on the Microsoft Docs site.  It says:

![image](https://user-images.githubusercontent.com/5177512/141396308-838d9011-166a-4619-ba26-941f2d0dab50.png)

When PowerShell determines that a file is not executable then it hands it over to Windows via `ShellExecute = true` to process.  Windows handles looking up the file association and executing the default verb for the extension.  That may start Perl in a separate console, or open Excel with the given .xlsx file.

The prescribed solution for this is to add the extension to `PATHEXT`.  Of course, you can also invoke the interpreter directly e.g. `perl hello.pl`.  Note: that once you've added `.PL` to `$env:PATHEXT`, you can invoke it with just `.\hello` unless there is another `hello.bat|exe|com` in the same dir and those extensions appear before `.PL` in `PATHEXT`.

**Comment by iSazonov** [comment]
Who will open doc issue? :-)

**Comment by rkeithhill** [comment]
I will - https://github.com/MicrosoftDocs/PowerShell-Docs/issues/8346

**Comment by rkeithhill** [comment]
The Docs issue was closed via this PR - https://github.com/MicrosoftDocs/PowerShell-Docs/pull/8356
