### ISSUE TITLE
Unexpected Behavior When using switch parameter 

### ISSUE THREAD

**Issue by 2Deep2Dive** [PowerShell/PowerShell#15927]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When using a switch parameter in a function, when some of the parameters are not used the value of 'True' is assigned to the parameter declared above the switch parameter, if the I disable PositionalBinding then an error produced and all is working correctly, if I call the function with all declared parameters, the error is properly produced
This is a very bad behavior and the "FirstParm" Should never be assigned the value 'True' and an error should be produced 

`function Get-Param {
    [CmdletBinding()]
    param (
        [string]$FirstParam ="",
        [Parameter(Mandatory=$true)]
        [switch]$SecondParam,
        [Parameter(Mandatory=$true)]
        [string]$ThirdParam
    )
    begin {
        Write-Output $FirstParam   
    } 
    process {
        if($FirstParam){
            Write-Output $ThirdParam
        }
    }
    end {}
}
Get-param   -ThirdParam 'Param3' -SecondParam $true`

### Expected behavior

```console
Get-Param : A positional parameter cannot be found that accepts argument 'True'.
At D:\@GitRepos\PS_Tests\switch_parameter_test.ps1:26 char:1
+ Get-param   -ThirdParam 'Param3' -SecondParam $true
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Param], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Get-Param
```

### Actual behavior

```console
True
Param3
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core 
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
As you found, if you want to disable positional binding, you need to do so explicitly.

What I think you may be misunderstanding here is that switch parameters don't take values like other parameters do. A function call like `Get-Thing -Switch $true` doesn't pass `$true` to the switch parameter -- ever. Providing the name of the switch parameter **is** providing a value, intrinsically, it doesn't expect another value to be bound to it.  So this command call:

```ps1
Get-param -ThirdParam 'Param3' -SecondParam $true
```

Passes the expected value to $ThirdParam, passes an implicit $true to $SecondParam because it's a switch parameter, and then PS attempts to find a parameter that can take the positional value $true, and picks the first parameter.

If you want to pass a value explicitly to a switch parameter, you need to use different syntax:

```ps1
Get-param -ThirdParam 'Param3' -SecondParam:$true
```

The `:` forces PS to bind the value to the named parameter, even if it is a switch parameter.

**Comment by 2Deep2Dive** [comment]
Hi @vexx32  Thank you for your prompt reply and explanation, I agree with you, what I misunderstood was that, I thought PowerShell well use either PositionalBinding or the parameter name but not both, but I was wrong.
as you mentioned it uses both depending how the parameter was called with the name or without, I was aware of the `:` but I needed to understand why was this happening.

Thank you again for the info, much appreciated
