### ISSUE TITLE
7.1.4 global tool is not on NuGet

### ISSUE THREAD

**Issue by mikenunan** [PowerShell/PowerShell#15930]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

We are now 2 days after release but no sign of the NuGet package yet:

https://www.nuget.org/packages/PowerShell/
![image](https://user-images.githubusercontent.com/8653660/129445124-e4e3217d-b5dd-449f-98dd-63d82456fad6.png)

This is a recurrence of [#15011](https://github.com/PowerShell/PowerShell/issues/15011) except this time the choco package is missing as well:

https://community.chocolatey.org/packages/powershell.portable
![image](https://user-images.githubusercontent.com/8653660/129445175-2707359a-63c5-4e91-9b09-cee974cc434a.png)

@adityapatwardhan guess there's something amiss with your fix from that previous go-around?  The new version is available via winget though, I noted. 

### Expected behavior

```console
New version available as dotnet global tool update and on Chocolatey within around 24 hours of release
```

### Actual behavior

```console
No new version on either distribution platform after two days.
```

### Environment data

```powershell
Not applicable
```

**Comment by Stelzi79** [comment]
Well last few updates weren't pushed in a timely manner to Nuget automatically either.

Question: Is the release channel of Powershell at Nuget deprecated?

**Comment by MaximoTrinidad** [comment]
@Stelzi79 

For me, this delay is normal. I always wait a few weeks and use the following command to update the dotnet PowerShell tool:
```
dotnet tool update -g powershell
```
this always works for me!
I wish that later on, the update can be close to the new version release date.

**Comment by TBBle** [comment]
According to the same issue for 7.1.3 (https://github.com/PowerShell/PowerShell/issues/15011#issuecomment-801932202), the delay is _not_ normal, but 7.1.3 had a pipeline bug that was believed fixed for 7.1.4.

7.1.2 was available on nuget.org within a day, based on tag dates.

I also note that the none of the 7.2.0 previews since 7.2.0-preview.5 have been published either, but I did see some discussion elsewhere that publishing the previews to nuget.org wasn't desired.

I have very little context on this, but https://github.com/PowerShell/PowerShell/blob/7d53fbbdf7032c1f293da21108bd287cbe6e00db/tools/releaseBuild/azureDevOps/templates/release-ReleaseToNuGet.yml#L32-L33 suggests that auto-upload of the PowerShell Global Tool package is currently disabled pending name reservation; the name reservation appears to have been done, so perhaps this is just a missing update to the pipeline?

**Comment by jonstelly** [comment]
> Question: Is the release channel of Powershell at Nuget deprecated?

I hope not.  I can't run the APT package because of #14055 but the dotnet tool install works fine.

**Comment by daxian-dbw** [comment]
Sorry for the delay and the global tool packages for 7.1.4 and 7.0.7 are now available in nuget.org.
Apparently, the release pipeline fix was missed in the 7.1.4 and 7.0.7 release branches ... I have sent out PRs to bring the fix in those 2 branches, so as to make sure the next servicing release branch will contain the fix.

Also opened PR #15961 to get it fixed in master.

**Comment by jonstelly** [comment]
Awesome, thanks!  I see the package on nuget.org (sometimes the nuget.org website and API is delayed a bit) and the dotnet tool update found and updated to 7.1.4 as expected.

**Comment by mikenunan** [comment]
That's great, thanks for sorting that out 🙏

**Comment by MaximoTrinidad** [comment]
@daxian-dbw 

It's confirmed! dotnet PowerShell tool was updated to 7.1.4.
```
dotnet tool update -g powershell
```
Awesome!

I always wait at least a week after it's released.

Thanks!!

**Comment by daxian-dbw** [comment]
> I always wait at least a week after it's released.

Sorry for that :( It will be published along with other `nupkg` packages the next servicing release.
