### ISSUE TITLE
Get-Item file attributes numeric

### ISSUE THREAD

**Issue by jamesr42** [PowerShell/PowerShell#15974]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a desktop.ini file that somehow got attributes 1572902:

```
$file1 = gi -force .\bin\desktop.ini
$file1.Attributes
1572902
```

Which according to WinNT.h is: FILE_ATTRIBUTE_HIDDEN, FILE_ATTRIBUTE_SYSTEM, FILE_ATTRIBUTE_ARCHIVE (expected) and also 0x80000 and 0x100000 which are unknown.

Normal desktop.ini files return this:

```
$file2 = gi -force .\desktop.ini
$file2.Attributes
Hidden, System, Archive
```

Trouble is, the first file does not return the correct answer from a test like this:

```
$file1.Attributes -match 'hidden'
False
```

Where the normal file does:

```
$file2.Attributes -match 'hidden'
True 
```

Even though the problem file has strange attributes, should not the "known" attributes return properly?

### Expected behavior

```console
$file2.Attributes -match 'hidden'
True
```

### Actual behavior

```console
$file1.Attributes -match 'hidden'
False
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
Looking at the raw value you have the following flags set:

* FILE_ATTRIBUTE_HIDDEN - 0x00000002
* FILE_ATTRIBUTE_SYSTEM - 0x00000004
* FILE_ATTRIBUTE_ARCHIVE - 0x00000020
* FILE_ATTRIBUTE_PINNED - 0x00080000
* FILE_ATTRIBUTE_UNPINNED - 0x00100000

```powershell
PS /home/jborean> 1572902 -eq (0x00000002 -bor 0x00000004 -bor 0x00000020 -bor 0x00080000 -bor 0x00100000)
True
```

The latter two seem to be somewhat undocumented in places and aren't defined as part of the [System.IO.FileAttributes](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileattributes?view=net-5.0) enum so instead of getting a nice and friendly human readable label the value is just a pure int. You cannot even cast it yourself as it will fail saying some values aren't valid

```powershell
PS /home/jborean> [System.IO.FileAttributes]1572902
InvalidArgument: Cannot convert value "1572902" to type "System.IO.FileAttributes" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration values are "ReadOnly,Hidden,System,Directory,Archive,Device,Normal,Temporary,SparseFile,ReparsePoint,Compressed,Offline,NotContentIndexed,Encrypted,IntegrityStream,NoScrubData".
```

When I say it's undocumented there is an entry for these masks under [MS-FSCC](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/ca28ec38-f155-4768-81d6-4bfeb8586fc9)

> FILE_ATTRIBUTE_PINNED   0x00080000
> This attribute indicates user intent that the file or   directory should be kept fully present locally even when not being actively   accessed. This attribute is for use with hierarchical storage management   software.<165>

> FILE_ATTRIBUTE_UNPINNED   0x00100000
> This attribute indicates that the file or directory   should not be kept fully present locally except when being actively accessed.   This attribute is for use with hierarchical storage management software.<166>

Why you have both masks set I have no idea as they seem complimentary but that's what the filesystem is returning. To fix this problem these flags need to be added to the .NET FileAttributes class so that PowerShell can represent them correctly. I  see an open issue about it https://github.com/dotnet/runtime/issues/39831 but there hasn't been much activity on it recently.

For your test I recommend using bitwise flags operations to test the present of the mask instead

```powershell
$attr = 1572902

if ($attr -band [System.IO.FileAttributes]::Hidden) { $true } else { $false }
```

This works in both situations where the attributes is the enum value and when it's the raw integer.

**Comment by jamesr42** [comment]
Well, this is a good work-around, not a solution.

**Comment by rkeithhill** [comment]
The solution would be to add these values to the `FileAttributes` enum but that type is in the `.NET Runtime` repo here:  https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/FileAttributes.cs

**Comment by jamesr42** [comment]
Well, problem is that is not future-proof ... if Windows starts using new attributes, then the call fails again. Perhaps Powershell should only return values that are actually in the enum.

**Comment by rkeithhill** [comment]
> that is not future-proof

It is **if** you use @jborean93 suggestion:
```powershell
$file2.Attributes -band [System.IO.FileAttributes]::Hidden
# OR
($attr -band [System.IO.FileAttributes]::Hidden) -ne 0
```
As for `-match` not working in this scenario, I suppose that is the crux of your issue here, right?  That might be worth opening in a separate issue or  you could rename it this issue.  

I see that C# handles this situation better than PowerShell e.g.:

![image](https://user-images.githubusercontent.com/5177512/130482625-4f9525e9-c5c2-4afe-af2a-5c4d54815c77.png)

Specifically, note that C# does not error on the typecast of 1572901 to `FileAttributes`.  Also note that even though a typecast in PS fails, you can create this enum:
```powershell
PS> $attr = [enum]::ToObject([System.IO.FileAttributes], 1572902); $attr.GetType().FullName
System.IO.FileAttributes
```
`-band` works on the result but `-match` does not.
```
PS> $attr -band [System.IO.FileAttributes]::Hidden
Hidden

PS> $attr -match 'Hidden'
False
```

**Comment by jamesr42** [comment]
I think it should return the enum's that it knows, but whatever ... yes, I have fixed my code to assume int return.

**Comment by puxu-msft** [comment]
Got a similar problem for FILE_ATTRIBUTE_PINNED 0x00080000

I found the docs here, but nowhere else: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/ca28ec38-f155-4768-81d6-4bfeb8586fc9
