### ISSUE TITLE
Setting the TERM environment variable to 'xtermm' or 'xterm-mono' breaks command-line editing on Unix-like platforms

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#16060]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Related: #16059

Note: While setting the `NO_COLOR` environment variable is the best choice for disabling VT (ANSI) escape sequence use by PowerShell's output-formatting system. without affecting terminal functionality, there's no reason why setting `TERM` to  `xtermm` or `xterm-mono` or unknown values should break command-line editing on Unix-like platforms.

```powershell
# On Unix
sh -c 'TERM=xterm-mono pwsh -nop -noexit -c ''Get-Item /'''
```

Note: 

* `xtermm` is less ill-behaved with respect typing commands on the command line, but still broken with respect to command recall, for instance.

* an _unknown_ value, such as `nosuch`, produces yet different symptoms.

### Expected behavior

* The `Get-Item /` command's output should print without colors.

* Command-line editing should function normally.

### Actual behavior

* Command-line editing is broken.

### Environment data

```powershell
PowerShell Core 7.2.0-preview.9, on Unix.
```

**Comment by rkeithhill** [comment]
I debugged this in PowerShell - make sure to launch with `-noni` so PowerShell is handling user input.  The problems lies in this code:

https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L1855-L1861

Specifically what I think is happening is that this line:
```csharp
Console.CursorLeft = cursorLeft;
```
Is attempting to move the cursor back to the beginning of where the user started typing the command then this line output the accumulated user text entered so far:
```csharp
Console.Out.Write(s);
```
But is obvious, even though the value of `Console.CursorLeft` after setting it would indicate the cursor has moved to the desired position, it really hasn't.  From what I can tell, the cursor moves only one position to the left. So the resulting display of entered text comes out looking like a mess.

BTW I was able to repro this in `6.2.7` so it's not a new issue in v7.   Here is a simple C# repro I compiled with `net6.0 rc.2`:

```csharp
﻿using System.Text;

// See https://aka.ms/new-console-template for more information
Console.WriteLine($"TERM set to: {Environment.GetEnvironmentVariable("TERM")}");

var sb = new StringBuilder();

while (true)
{
    ConsoleKeyInfo keyInfo = Console.ReadKey(true);

    if (keyInfo.Key == ConsoleKey.Enter) break;

    sb.Append(keyInfo.KeyChar);

    var currentCursor = Console.CursorLeft;
    Console.CursorLeft = 0;
    Console.Out.Write(sb.ToString());
    Console.CursorLeft = currentCursor + 1;
}

Console.WriteLine($"\nYou typed: '{sb.ToString()}'");
```

This outputs:

![image](https://user-images.githubusercontent.com/5177512/139557050-9b27d7ef-83b5-43ab-aaaa-b8afc2c61a70.png)

While it would be nice to figure out a way to fix this since `bash` doesn't exhibit this problem with a bogus `TERM` value, I don't think the problem lies in PowerShell. This seems to be a .NET issue with how `Console.CursorLeft` works (or doesn't work) with a bogus `TERM` value.

**Comment by rkeithhill** [comment]
@mklement0  If you concur, I think I'll mark this `resolution-external` unless you have an idea of how this could be fixed in PowerShell.  That said, any such fix is likely to be marked "up-for-grabs" since this issue appears to be a corner-case with a trivial workaround.

**Comment by iSazonov** [comment]
> This seems to be a .NET issue with how `Console.CursorLeft` works (or doesn't work) with a bogus `TERM` value.

https://github.com/dotnet/runtime/blob/46a3bfeffec2fb6b33bfd152d33f33b544e401c9/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L234

**Comment by vexx32** [comment]
Digging a layer or two deep into that seems to indicate that .NET needs to know the terminal type to be able to manipulate the cursor position. I doubt there's a good way to fix that, except maybe defaulting to "the most common" way of setting the cursor position when the term value is unknown... and even then, it's not really a good solution.

**Comment by iSazonov** [comment]
> Digging a layer or two deep into that seems to indicate that .NET needs to know the terminal type to be able to manipulate the cursor position. I

.Net loads TermInfo database from underlying OS. So question is - has the TermInfo the terminal description? is the description correct?

**Comment by vexx32** [comment]
In a scenario where the TERM value is nonsensical? No, it won't have anything of use. `infocmp` on Mac reports:

```
infocmp: environment variable TERM not set
```

**Comment by iSazonov** [comment]
If I understand correctly 'xtermm' or 'xterm-mono' are not in TermInfo database?

**Comment by vexx32** [comment]
I believe those are, yeah. As @rkeithhill mentioned (https://github.com/PowerShell/PowerShell/issues/16060#issuecomment-953521523) it currently works as expected for those, but the issue persists if the TERM value is missing/corrupt/nonsensical/etc.

I don't think it's something PowerShell can fix, though.
