### ISSUE TITLE
Protected Event Logging for Module Logging

### ISSUE THREAD

**Issue by webarchitect0** [PowerShell/PowerShell#16111]
### Summary of the new feature / enhancement

Implemented Protected Event Logging for Pipeline/Module Logging(Event 4103 and 800).  

### Proposed technical implementation details (optional)

Protected Event Logging has been implemented for Script Block Logging but not Pipeline/Module Logging(Event 4103 and 800).

**Comment by TravisEz13** [comment]
@wg-security This probably requires some design: 
* If we encrypt both events based on the same policy, this might break people that relied on the old behavior.
* If we add a new policy, how do we create it, so we don’t keep adding policy for each new event.

Otherwise, this seems like something we should consider.
