### ISSUE TITLE
Add a switch to allow empty reference/difference objects in Compare-Object

### ISSUE THREAD

**Issue by Willem-J-an** [PowerShell/PowerShell#16184]
### Summary of the new feature / enhancement

As a user I want to be able to do a full compare between two lists of objects. When one of the lists is empty, that would mean all the objects in the other list are different. This functionality can be used to build a sync deployment feature, where there is a defined list and an implemented list. 

On first run the implemented list would be empty, and the defined list is not empty. Run it through the compare and use the SideIndicators to determine which items should be created, and which items should be removed. On further runs, the compare will still work to add new defined items, and remove items that are no longer defined.

Currently an empty difference or reference object returns nothing, and $null returns an error. To avoid breaking issues, the new behavior could be implemented with a switch Compare-Object -AllowNullOrEmpty.

### Proposed technical implementation details (optional)

``` pwsh
@(@{v=1}) |
  Compare-Object `
    -ReferenceObject @(@{v=1},@{v=2},@{v=3}) `
    -PassThru `
    -IncludeEqual |
 select v, SideIndicator

# Existing behavior:
v SideIndicator
- -------------
1 ==
2 <=
3 <=
```
``` pwsh
@() |
Compare-Object `
    -ReferenceObject @(@{v=1},@{v=2},@{v=3}) `
    -Passthru `
    -IncludeEqual |
select v, SideIndicator

# existing behavior returns

# wanted behavior returns 
v SideIndicator
- -------------
1 <=
2 <=
3 <=
```

``` pwsh


$null |
Compare-Object `
    -ReferenceObject @(@{v=1},@{v=2},@{v=3}) `
    -Passthru `
    -IncludeEqual |
select v, SideIndicator

# existing behavior returns
Cannot bind argument to parameter 'DifferenceObject' because it is null.
# wanted behavior returns 
v SideIndicator
- -------------
1 <=
2 <=
3 <=

**Comment by mklement0** [comment]
I agree that `Compare-Object` should accept `$null` and treat that the same as an empty array.

Arguably, that should be the _default_ behavior, but that could conceivably break existing scripts that rely on catching errors when `$null` is used.

Empty arrays _do_ work, but you need to provide them as _arguments_, not via the pipeline (an empty array is _enumerated_ in the pipeline, so that _nothing_ is sent to `Compare-Object`, which makes it an effective no-op).

```powershell
# OK - reports all elements from 1..3
Compare-Object @() (1..3)
```

A pragmatic workaround for the `$null` problem is to use `?? @()`:

```powershell
# OK - reports all elements from 1..3
$possiblyNull = $null
Compare-Object ($possiblyNull ?? @()) (1..3)
```

---

As an aside: 

Your first snippet only _seemingly_ works, given that hashtables such as `@{v=1)` are instances of .NET _reference types_ and therefore compared with _reference equality_ (only `$true` if both values are the very same instance).

You'll see the problem if you change  `@(@{v=1})` to `@(@{v=2})` - it'll still report that `1` is the equal value.
You need to add `-Property v` in order to compare the hashtables by their `v` values.
