### ISSUE TITLE
Program output with progress updates in interactive remote session is broken

### ISSUE THREAD

**Issue by Nino-kun** [PowerShell/PowerShell#16321]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

If I run Robocopy, or other program with similar status/progress update, in interactive remote session to WinPC, it's output is broken.

etsn user@remote-pc -ssh (with WinRM-connection problem persist)
Robocopy.exe d:\downloads e:\pictures *.jpg /J (copy all JPEG files from d:\downloads to e:\pictures)

### Expected behavior

```console
Updating percentages on screen should be like when running locally - in one line.
```

### Actual behavior

```console
Each percentage update showing on new line.
```

### Environment data

```powershell
Both local and remote PC have same $PSVersionTable:
Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
The issue here as I understand it is that when you start a process locally without capturing output the program will write directly to the console buffer so things like progress percentages is handled by that app. When you start a process like this through a remoted session PowerShell will always redirect and capture the `stdout` so now it's being processed by PowerShell and output line by line. This is similar to doing something like `robocopy.exe ... | Out-String` as now the output is process by PowerShell itself and output as string objects per line.

I'm not sure if this can really be changed to progress records, similar to `Write-Progress` as each executable would have it's own method of displaying progress. Potentially PowerShell could somehow handle the backspace the native app will be writing but even then I don't think it's really possible or feasible to do this.  You see a similar problem when running tools like this in CI with progress indicators spamming the output because the CI log is not an actual console output.

There are some people who have implemented a wrapper around robocopy to read the output itself and convert it to a progress record which is most likely going to be the best way forward if you want progress records https://stackoverflow.com/questions/13883404/custom-robocopy-progress-bar-in-powershell. Also just as an FYI while you have an "interactive" PSSession when you use `Enter-PSSession` the actual session isn't going to work when calling binaries that have interactive prompts like `sudo`, `diskpart`, etc. These binaries expect an interactive console that is streamed to the client and requires input whereas a PSSession doesn't work in a way where that's possible.

**Comment by Nino-kun** [comment]
Last sentence in your post make me try pure SSH remoting, not PS-Remoting with SSH transport. And it display copy progress like I want it.

It will be sad if PS-Remoting couldn't work like SSH in the future, but I can live with that.

I close issue, thank you all.
