### ISSUE TITLE
Add -FormatEnumerationLimit parameter to Format-List and Format-Table

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell#16360]
### Summary of the new feature / enhancement

With PowerShell, you sometimes get objects which have properties that are actually an array of objects. The Threads and Modules Properties on System.Diagnostics.Process object. When Format-List/Format-Table formats these parameters, they only include up to a certain number of occurrences, by default 4. The number of enumerations shown is determined by the automatic variable $FormatEnumerationLimit. So if you want more, you just update that variable, typically in a $Profile.

Here is the current behaviour:

```powershell
PS> $FormatEnumerationLimit
4
PS> Get-Process | Select-Object -Property Name, Threads -First 4

Name                    Threads
----                    -------
AggregatorHost          {5240}
ApplicationFrameHost    {16968, 2848, 18728}
AppVShNotify            {9164}
Atom.SDK.WindowsService {4064, 4908, 4912, 19144…}

PS> $FormatEnumerationLimit = 1
PS> Get-Process | Select-Object -Property Name, Threads -First 4

Name                    Threads
----                    -------
AggregatorHost          {5240}
ApplicationFrameHost    {16968…}
AppVShNotify            {9164}
Atom.SDK.WindowsService {4064…}
```

I propose adding a new parameter to both Format-List and Format-Table, -FormatEnumerationLimit which overrdes the value of $FormatEnumerationLimit, but just for this command. Like this:

```powershell
PS> Get-Process | Select-Object -First 4 | Format-Table Name, Threads -FormatEnumerationLimit 2

Name                    Threads
----                    -------
AggregatorHost          {5240}
ApplicationFrameHost    {16968, 2848…}
AppVShNotify            {9164}
Atom.SDK.WindowsService {4064, 4908…}
```

### Proposed technical implementation details (optional)

* Update each cmdlet with the extra parameter
* Change the logic for handling enumeration limit by using the parameter value if it is specified.
* Retain the default value and default variable handling.

**Comment by jhoneill** [comment]
Two thoughts. 
One would be to have this as a custom item property. That way it could be different in different columns. 

The other is I'm certain that at one time FormatEnumerationLimit decided the number of columns PowerShell would go to before it switched from a table view to a list view when it had nothing else to guide it 
 It doesn't do that _now_ it did it change ?

**Comment by doctordns** [comment]
Thanks @jhoneill.

Not about a custom item property - not sure what it would look like?

I'd like to see this to enable a format-Table/Format-List to format a different number of iterations without having to change `$FormatEnumerationLimit`. Just like you can, on a cmdlet by cmdlet basis, override ErrorAction (e.g. `-ErrorAction Stop`).

Regarding your last point - I am pretty sure FormatEnumerationLimit was there from V1. I could be wrong. But whatever it was, enumeration on a cmdlet by cmdlet basis would be useful. I know it was this way in V2 in 2011 when I gave a [talk at the PowerShell Deep dive in Frankfurt](https://devblogs.microsoft.com/powershell/powershell-deep-dive-lineup). Later [Jeff Hicks posted an article about that talk](https://mcpmag.com/articles/2012/01/05/powershell-enum-limit.aspx).

**Comment by jhoneill** [comment]
I think my misunderstanding  of the number of columns, vs the number of items in a column goes back to then.  
As for a custom property  you can have this today 
`dir | ft @{n='Time'; e='LastWriteTime'; f="ddd dd MM yyyy";w=20},name `

So why not have `i[tems]=`

**Comment by doctordns** [comment]
Well - a simple parameter would work in the cases I see and be pretty simple I think.

As an aside, where IS the code for the Format-List and Format-Table commands. My google fu must be weak because I can't find the actual code where the formatenumerationlimit variable is actually obtained and used.

**Comment by sdwheeler** [comment]
@doctordns `$FormatEnumerationLimit` is a preference variable. It is documented at https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_preference_variables#formatenumerationlimit

Your suggestion to add a parameter would affect the enumeration for all properties in the output. The suggestion from @jhoneill allows you to specify a different enumeration limit for each property.

**Comment by jhoneill** [comment]
@sdwheeler  I think I first learned of FormatEnumerationLimit  from a talk @doctordns  did 10+ years ago, but I've had it my head ever since that it controls how many columns there were, not how many items there were in a column, I'm sure I blogged something to that effect. What's in the help definitely matches the current behaviour (items per column, no effect on number of columns)  I'm wondering now if that was ever true, or if Thomas needs to tell me off for not listening in class :-) 

@doctordns  yes a parameter would work, but I've been doing something this week where if I could customize it I would want all 10 items in one column, but a maximum of 2 or 3 items in another, hence the custom property idea.

**Comment by doctordns** [comment]
I presented this at the Experts Conference in 2011 (wish I could find the slides!!). I am pretty sure I was clear that the variable just handled the number of objects enumerated. In all my work-around that time delivered the same message. I apologise if I did not explain that clearly enough.

I _hope_ we both agree that the ability to control the enumeration limit on a cmdlet by cmdlet basis would be a useful addition to PowerShell.  I prefer a simple parameter but like the addition of using a hash table with a new key.

Having a `-FormatEnumerationLimit` parameter would be easy for both the cmdlet developer and the user.  And probably covers most use cases. But controlling it on a property by property basis is a great solution too.

How about both?

**Comment by jhoneill** [comment]
@doctordns  you know me, not listening properly in class. I've been scrabbling round to find out if I've passed on that error, or if I've just been carrying it silently.   

Having  both a switch and a custom object would work,  (switch is simpler to use and implement,  custom object has more flexibility) if it can only be one - there are arguments on both sides.

**Comment by rkeithhill** [comment]
Given that this proposal is limited to the `Format-*` command, the `Format` in the parameter name seems redundant.  You could shorten the parameter name to `-EnumerationLimit`.

**Comment by jhoneill** [comment]
@doctordns  stumbling around I've found that the default number of columns goes in types.xml, and I'll write a blog post about it ( I see you recently posted on format enumeration limit :-)  )

**Comment by doctordns** [comment]
Yes indeed - you can do that, although editing types.xml is not a good practice. Create your own MYtypes.type.ps1xml file and import it in your $profile file.

Also, types.xml does not exist, as such, in PowerShell 7 so you have to import it manually.

If you DO do a blog post, consider posting it to the [PowerShell Community Blog]( https://devblogs.microsoft.com/powershell-community).  :-)

**Comment by jhoneill** [comment]
@doctordns   "a" types.xml, not "the types.xml" :-)  
The default isn't actually present in the PS5 Types.xml, I always tell people to to **read** the file and note the warning "Don't edit this it's signed". Most modules I ship have their own types.ps1xml file. 
 
Of course with the 6 and 7 you need to use the v5 file or export the type information - I suspect because people would leave the one on $pshome alone ! 
Much blogable content there and I've got a not to offer stuff to the PS community blog.

**Comment by daxian-dbw** [comment]
Reassign the issue to the Cmdlet WG to decide if the new parameter is desired.

**Comment by iSazonov** [comment]
Having this in FormatData would be better.

**Comment by jhoneill** [comment]
> Having this in FormatData would be better.

If it is also added to the XML schema for `format.ps1xml` files that would be good in work I am doing at the moment. 

There is one caveat. Unexpected XML isn't ignored at present so that means a module which ships a format file which specifies this won't load on older PowerShell; someone trying to adapt such a module for a down-level version of PowerShell can fix "error at line x" when an extra  parameter or an extra key in a custom property hash table is the issue, but mending format or types files will be too daunting. That's a very weak argument against the improvement.

**Comment by iSazonov** [comment]
> That's a very weak argument against the improvement.

Our only policy is to keep backward compatibility. And even this is already unbelievable

**Comment by doctordns** [comment]
> Having this in FormatData would be better.

This is a ‘scripting wall’ kind of issue. You can write your own XML,  but for most IT Pros, that is way too hard.  Just like -errorAction over rides -ErrorActionPreference. Yes by all means allow the XML to be imported, but also expose enumeration on the Format cmdlets.

**Comment by jhoneill** [comment]
> > That's a very weak argument against the improvement.
> 
> Our only policy is to keep backward compatibility. And even this is already unbelievable
It has limits. Any new switch for an existing cmdlet breaks things. Old scripts run on new PWSH (with relatively few exceptions)  but I've used things from PS 5 and found the customer's servers hadn't been upgraded from 4, I'm writing today in 7.2 and testing in 5 because it's Windows PowerShell only on these machines, so I can't use convertFrom-Secure string or the new operators etc. etc. 
"Don't use X if you want the script to work down-level" is OK advice. It's certainly better than "You can't have X because then you can't run the script somewhere that you wouldn't want to :-)

**Comment by pencoe** [comment]
I do like the idea from @jhoneill with the additional formatting property on custom properties the most: maximum flexibility, minimum impact on existing cmdlets.

**Comment by doctordns** [comment]
It sounds like there is agreement over extending `Format-List` and `Format-Table` to have a format enumeration limit overriding the default set in the `$FormatEnumerationLImit` automatic variable.  

There are TWO ideas on the table: A SIMPLE one (adding an *-EnumerationLimit* parameter to the cmdlets that override the auto variable. The second one, more complex, is to extend the hash table used to form a column to specify the enumeration limit for just one property.

I can live with either. But in keeping with the best traditions of PowerShell, can we have both?

**Comment by doctordns** [comment]
Any more suggestions here?

Is there any interest in improving the Format-* cmdlet. Sadly, I do not have the skills to do the coding.

**Comment by iSazonov** [comment]
@doctordns This code is too confusing and poorly covered by tests. The creation of new features there is most likely unjustified due to the complexity. Perhaps it is worth rethinking the accumulated experience and new ideas (like PSMore) and design a new more flexible formatting subsystem.

**Comment by mattcargile** [comment]
A shame to lose the thread on this. Having `PSMore` and what not seems cool along with this feature.
