### ISSUE TITLE
`Test-Path -PathType $type '*'` depends on some order

### ISSUE THREAD

**Issue by Quaentor** [PowerShell/PowerShell#16375]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
New-Item -Type File 'test_file'
New-Item -Type Dir 'test_dir'
Test-Path -PathType Leaf *
Test-Path -PathType Container *
```

### Expected behavior

```console
PS> Test-Path -PathType Leaf *
False
PS> Test-Path -PathType Container *
False
```

### Actual behavior

```console
PS> Test-Path -PathType Leaf *
True
PS> Test-Path -PathType Container *
False
```

### Environment data

```powershell
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
I don't understand why do you expect "false" when there is file?

> \- Leaf. An element that does not contain other elements, such as a file.

**Comment by Quaentor** [comment]
@237dmitry why is it "False" with `Directory` then?

**Comment by Quaentor** [comment]
@237dmitry 
>  I don't understand why do you expect "false" when there is file?

As per documentation, as I understand it, **all** matching items must meet the criteria. Otherwise, it's poorly documented.

> The Test-Path cmdlet determines whether all elements of the path exist.

**Comment by jhoneill** [comment]
> @237dmitry why is it "False" with `-PathType Directory` then?

I think most people would say that behaviour is wrong. Except that it doesn't always do that ..

If `pathtype` is specified  **the first item returned** _before sorting_ determines whether `test-path` returns true or false.  You can get the opposite result by creating the directory before the file. 

If `test-path` gives different results depending on the sequence the items are created, and it seems to, that would be a **bug**

**Comment by 237dmitry** [comment]
> I don't understand why do you expect "false" when there is file?

>> I think most people would say that behaviour is wrong.

Expected `True` for both `Leaf` and `Container`. But `True` returned if only single element is in current directory.

**Comment by jhoneill** [comment]
> > I don't understand why do you expect "false" when there is file?
> 
> > > I think most people would say that behaviour is wrong.
> 
> Expected `True` for both `Leaf` and `Container`. But `True` returned if only single element is in current directory.


That's not the behaviour. 

- If you create any number of files in an empty folder `leaf *` is true   
- If you add any number of folders `leaf *` is still true and `container *` is false (expected true, right ?) 
**But**
- If you create any number of folders in an empty folder `container *` is true
- If you add any number of files `container *` is still true and `leaf *`is false  

If a mix of files and folders matches the wildcard, the first one created sets the behaviour of `leaf` or `container`

**Comment by iSazonov** [comment]
Default parameter of the cmdlet is LiteralPath. So the script in the OP don't globbing but search exactly '*' - expected result is False.

**Comment by jhoneill** [comment]
```
mkdir "blah[0]"
Test-Path "blah[0]" [-PathType Container]
False
```
This is a different problem see #17106

mkdir creates a  folder which includes [ and ] in the name
Test-path sees `[]` as a wild card set and is looking for blah followed by any of the letters in []  so here only blah 0 will match
You need  
```
Test-path 'blah`[0`]'  
```
Or with double quotes the escaping ` needs to be doubled up.
```
Test-path "blah``[0``]"  
```


The behaviour with `Test-Path`  is _If a mix of files and folders matches the wildcard, the first one created sets the behaviour of leaf or container_   As such it has been _answered_ but I'm not sure this behaviour can be _by design_ @iSazonov can we reopen this. I'll take to cmdlet working group, because I can see that people expect that if e.g. 
`Get-ChildItem -Directory *`   returned items `Test-Path -container *` returns true , but I can't see anyone relying on the behaviour relying on the order of creation. (So a recursive copy might give different results from the source depending on copy order)

**Comment by k9wazere** [comment]
@jhoneill I was simply demonstrating that LiteralPath is not the default parameter set for Test-Path.

If it was, then Test-Path "blah[0]" would return True, not False. I deliberately did not explicitly specify -Path. And yes, I am aware that [ and ] when used with -Path act as wildcards.

I've since opened my own bug 17134.

Ultimately, Test-Path should return True if Get-Item would return a result. It's really that simple, to me. A situation where Test-Path returns False and Get-Item is getting something is totally counter-intuitive.

**Comment by jhoneill** [comment]
@iSazonov   that answer of Dec 3rd is wrong
```
 PS > (get-command test-path).ParameterSets | ft

Name        IsDefault Parameters
----        --------- ----------
Path             True {Path, Filter, Include, Exclude…}
LiteralPath     False {LiteralPath, Filter, Include, Exclude…}
````

The original problem as stated was 
If you have an empty directory  and run 
```
New-Item -Type File 'test_file'
New-Item -Type Dir 'test_dir'
Test-Path -PathType Leaf *
Test-Path -PathType Container *
```
Then the leaf returns TRUE and the Container returns false. 
What I've found is the if the creation order is reversed, then  in another empty directory. 
```
New-Item -Type Dir 'test_dir'
New-Item -Type File 'test_file'
Test-Path -PathType Leaf *
Test-Path -PathType Container *
```
leaf will return false and container is true. 

It seems Test-Path looks at the first matching item for a wildcard search.
