### ISSUE TITLE
`Set-StrictMode 2`: False positive for references to the `Count` property

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#16427]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```PowerShell
Set-StrictMode -Version Latest
$TempFile = New-TemporaryFile
$TempPath = Join-Path $Env:Temp ('Folder_' + [Guid]::NewGuid())
$TempFolder = New-Item -ItemType Directory -Path $TempPath
Copy-Item -Path $TempFile -Destination $TempFolder
$TempFolder |Should -Exist
(Get-ChildItem $TempFolder).Count |Should -Be 1
```

### Expected behavior

No Error

### Actual behavior

> PropertyNotFoundException: The property 'Count' cannot be found on this object. Verify that the property exists.

### Error details

With `Set-StrictMode -Off` the `(Get-ChildItem $TempFolder).Count ` return `1` which shows that the property does exist

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by PaulHigin** [comment]
@WG-Security

@iRon7  This is by design.  Strict mode emits errors when you reference a property that does not exist.  As a workaround you can coerce the result into an array type:

```powershell
@(Get-ChildItem $TempFolder).Count 
```

**Comment by iRon7** [comment]
@PaulHigin,

Thanks for the answer.

> As a workaround you can coerce the result into an array type:

**What is the catch?**

What is the difference behind the scene?
Apparently there is no *direct* relation with member enumeration as this doesn't give an error:
``` PowerShell
([PSCustomObject]@{ Count = 3 }).Count
```

So I guess it has something to do with an deferred execution.
I used to state that assigning a pipeline or using parenthesis will break it, now I have second thoughts whether this is always the case for using parenthesis. I suspect now that:
```PowerShell
(Get-ChildItem $TempFolder) |ForEach-Object { ... }
```
is smart and actually still emitting each item one by one despite the parenthesis.
And only when it is forced to an array it will choke the pipeline:
```PowerShell
@(Get-ChildItem $TempFolder) |ForEach-Object { ... }
```
Or???

**Comment by PaulHigin** [comment]
There is no catch.  The above syntax simply wraps the object in an array so that the `Count` property is valid, when in strict mode.  PowerShell has rules about when to unwrap an array type.

https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-arrays?view=powershell-7.2

**Comment by SeeminglyScience** [comment]
`Count` is also a binder construct though, similar to the `ForEach` and `Where` methods. It's supposed to exist on any object including scalars. I'm not necessarily trying to assert that it shouldn't error, I just want to make sure that's taken into account.

**Comment by penser-jata** [comment]
`Count` not only exists on every object, it is also explicitly (and magically) present on no object at all.
`$null.Count` gives 0 
The behavior of `.Count`, (0 for null, 1 on any scalar object, the number of elements in collections) is _intended_, extremely _useful_, and _documented_.
StrictMode is not aware of the very special semantics of `.Count`, so you basically can't use the two of them at the same time.

**Comment by iRon7** [comment]
Thanks for the answers and information.
It took me a while to see this thru but `Get-ChildItem $TempFolder` could potentially return nothing ([System.Management.Automation.Internal.AutomationNull](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.internal.automationnull)) and `()` indeed doesn't have a `Count` property

I have closed the issue (**`Resolution-Answered`**).

**Comment by penser-jata** [comment]
But you can use Count on 'nothing' and it will return zero.
And for a single object you get one.
No 'real' property is needed .
That is the beauty of the feature.

This wasn't there for the first five years but was added in version 3.
Experience showed that you often had to use the work around suggested above by @PaulHigin where you create an array for single objects. (A little ugly and with non-zero perf cost)

In that version we also got the equally magic feature where where you can treat any object like an array, so this works and gives 1:
```
$a = 1
$a[0]

```
Interestingly, StrictMode seems to be aware of this 'synthetic indexing operator' and does not complain, but barfs on the the closely related 'synthetic Count property'

This issue is really a valid bug report and deserves to stay open.

**Comment by iRon7** [comment]
Ok, I am not able to qualify this further. To prevent that I have reopen/close it repeatedly, I will leave it up to you (@SeeminglyScience, @iSazonov ?) to change it again.

**Comment by SeeminglyScience** [comment]
I don't have permissions to reopen but the `Count` engine intrinsic property works fine on autonull in non-strict (returns `0`) so I'm  inclined to say it should do the same in strict.  If it returned nothing I would say the error makes sense.

**Comment by vexx32** [comment]
That makes sense to me. If strict mode is intended to by design restrict usage of otherwise ubiquitous properties provided by the engine, that should be well documented. Given that it's not, I would be inclined to assume it's more of an accident of implementation and we should see if it's feasible to rectify the issue.

**Comment by iRon7** [comment]
Something similar happens with default array parameters

```PowerShell
function Test {
    [CmdletBinding()] param(
        [String[]]$StringArray
    )
    $StringArray.Count
}
Set-StrictMode -Version Latest
Test
```

> `The property 'Count' cannot be found on this object. Verify that the property exists.`

The workaround is to default it to an empty array: `[String[]]$StringArray = @()`

**Comment by PaulHigin** [comment]
@WG-Security
We do not see a security issue here, as strict mode is not a security feature.  This is a language issue and we will update the label.

**Comment by mklement0** [comment]
Note that this problematic behavior was first reported in
* https://github.com/PowerShell/PowerShell/issues/2798

#15526 also discusses the inconsistency, but argues for the _opposite_ resolution; to borrow from [my comment there](https://github.com/PowerShell/PowerShell/issues/15526#issuecomment-883592333):

Engine-supplied members such as `.Count`, `.Length`, scalar `[...]`, `.psobject`, `ForEach()`, .... now have an official name:  [_intrinsic members_](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Intrinsic_Members).

It makes much more sense to make them _consistently_ available, _irrespective of strict mode_.

This is _already true for most of them,_ but inexplicably not for `.Count` and `.Length` (`[pscustomobject]` being the only exception), despite their tremendous usefulness in unified handling of scalars and collections.

Simplest repro:

```powershell
# .Count fails on all types without their own .Count property  *except* [pscustomobject]`
# Applies analogously to .Length
& { Set-StrictMode -Version 2; [pscustomobject] @{ foo=1 }.Count; 'foo'.Count; $null.Count }
```

@iRon7, your `[string[]] $StringArray` parameter example can be reduced to `$null.Count`, because unbound reference-type parameters (without default values) are `$null`.

**Comment by iRon7** [comment]
I guess this issue should be marked as <kbd>Issue-Bug</kbd>.
Anyways I have closed this one, assuming that the linked issue #2798 stays open.
