### ISSUE TITLE
Support 0xRRGGBB colors on Write-Host

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#16442]
### Summary of the new feature / enhancement

As a user I want Write-Host to support specifying full RGB colors on the -Foreground and -Background parameters.

I would also like to be able to specify any of the X11 named colors by name

### Proposed technical implementation details (optional)

Instead of needing to write `$($PSStyle.Foreground.FromRgb(0xa020f0))` into the string to set a purple color, I want to specify `-Foreground A020F0` or `-Foreground 0xa020f0` or `-Foreground Purple`

**Comment by doctordns** [comment]
If you do accept an Ansi colour, can you also accept a named colour (eg "darkred")?

**Comment by SeeminglyScience** [comment]
I think it's worth discussing from an implementation stand point how this would change `HostInformationMessage`.  I think there are a few options.

1. Make a new object similar to `HostInformationMessage` but specific to rich color
2. Add new string properties to `HostInformationMessage` for prefix and suffix escape sequences
3. Add new int properties to `HostInformationMessage` and allow the host to translate it (since while uncommon, GUI hosts do exist)
4. Just put the escape sequences into `HostInformationMessage.Message`

**Comment by Jaykul** [comment]
> I think it's worth discussing from an implementation stand point how this would change `HostInformationMessage`. I think there are a few options.

There was some discussion of this years ago on #2381 and I still like the idea of [adding objects like RGBColor and Text](https://github.com/PowerShell/PowerShell/issues/2381#issuecomment-300687702).

Of course, the current implementation is spaghetti. E.g. `$PSStyle.OutputRendering ="PlainText"` will strip **all** ANSI out, but doesn't strip colors added by `Write-Host`. If we changed Write-Host so it uses escape sequences, it would then be affected by `OutputRendering = "PlainText"` ...

Side note: I really hate that PowerShell is stripping escape sequences from the output of _other things_,

**Comment by jdhitsolutions** [comment]
Added to the Cmdlet Working Group list for review and consideration.

**Comment by jhoneill** [comment]
> I really hate that PowerShell is stripping escape sequences from the output of _other things_, However, it doesn't strip colors added by `Write-Host`. If we changed Write-Host so it uses escape sequences, it would then be affected by `OutputRendering = "PlainText"` ...

@Jaykul  
Things like `git log` and `git diff` still output  with colour - which I'm fairly sure is ansi  - do you mean PowerShell itself is stripping sequences from functions / cmdlets which aren't part of the core package ? 

It's a "what do users expect ? " question.  If I say I want **plaintext** rendering , what's the **scope** of that ?
The rendering of Error, verbose etc is now done with ANSI. so the plain-text option displays them plain, but `Write-Host` keeps whatever its parameters specify (ANSI sequences in the text to be written _are_ blocked). That allows a developer to impose colours the user doesn't want and create accessibility problems so one question here is, **Should the foreground and background in Write-Host also send ANSI ?** 

To the wider point: 

- Each console host defines, via user settings, what R,G,B values to use for 16 colours (Black, White, RGB, YMC  in Bright/Dark variants)  people may remember Windows PowerShell redefining DarkMagenta in the console host for the PowerShell blue background. Different hosts have different defaults for these 16 - compare the output of `$psStyle` in VSCode and Windows Terminal.
- The 16 are embedded in `[consoleColor]` - unfortunately its naming of "Yellow"/"DarkYellow" is out-of step with the ANSI names "BrightYellow"/"Yellow".    
- `[system.drawing.color]` supports most X11 named colours (some are missing) and defines what RGB values they should be.  These _don't_ include Bright/dark versions of everything and has some named "light" instead. So "Yellow" has ANSI, ConsoleColor and Drawing.Color meanings 
- `Write-host` uses `[consoleColor]`. Any change needs to support the existing names and values. e.g. `write-host -f 14 "This is Yellow"`  still needs to translate 14 to 'yellow' and yellow to mean whatever the brighter Yellow has been defined as, NOT an absolute 0xFFFF00 

There's a choice betwen "add  new parameters to `write-host`" or **"Just use ANSI"**. I wrote and extension for `[system.drawing.color]` to accept text and wrap it in the ansi codes - see below - I'm sure it can be improved, but **why wouldn't we go the "Just ansi" route** ? Stopping users managing their colours isn't a good reason :-)    

```
<?xml version="1.0" encoding="utf-8" ?>
<Types>
  <Type>
    <Name>System.Drawing.Color</Name>
    <Members>
      <ScriptMethod>
        <Name>Foreground</Name>
        <Script>
            param ($Text)
            ("$([char]27)[38;2;{0};{1};{2}m" -f $this.r, $this.g , $this.b ) + $Text.ToString() +"$([char]27)[0m"
        </Script>
      </ScriptMethod>
      <ScriptMethod>
        <Name>Background</Name>
        <Script>
            param ($Text)
            ("$([char]27)[48;2;{0};{1};{2}m" -f $this.r, $this.g , $this.b ) + $Text.ToString() +"$([char]27)[0m"
        </Script>
      </ScriptMethod>
    </Members>
  </Type>
</Types>
```
After doing `Update-TypeData -AppendPath .\DrawingColor.Types.ps1xml` It's called like this 

```
using namespace 'System.Drawing'

[color]::yellow.Background( [Color]::Red.foreground("This is red"))
```
For nicer syntax. The following  Allows `foreground Gold "Always believe in your soul"   `

```PowerShell
function foreground {
param(
[ArgumentCompleter({
    param ($CommandName, $ParameterName, $WordToComplete, $CommandAst, $FakeBoundParameters)
    [enum]::GetNames([System.Drawing.KnownColor]).where({$_ -like "$WordToComplete*"}) } ) ]
    [System.Drawing.Color]$Color,
    
    $Text 
)  
    $Color.Foreground($Text)
}
```

**Comment by Jaykul** [comment]
> Things like git log and git diff still output with colour - which I'm fairly sure is ansi - do you mean PowerShell itself is stripping sequences from functions / cmdlets which aren't part of the core package ?

Just so, @jhoneil yes.

For what it's worth, I think you're presenting a **false choice** between extending and compatibility. My [PANSIES](/PoshCode/PANSIES) module's `Write-Host` **already** handles all the colors compatibly -- and a little more than you listed, because it handles the x11 palette (aka the web-safe color palette) by index ... or by name:
![image](https://user-images.githubusercontent.com/192942/154823630-523adf1f-f2d3-4520-9b22-7f9b1decf840.png)

What it doesn't handle (because it's the "PowerShell ANSI Escape Sequences" module) is falling back to API calls when `$PSStyle.OutputRendering = "PlainText"` so that it can still output text in color, the way the the built-in Write-Host does when you ask for "Plain Text" output. As a result, PowerShell throws out it's color if you set "PlainText" rendering:
 
![image](https://user-images.githubusercontent.com/192942/154821841-07c30e0d-2a9a-4b07-a926-c0d90d39d257.png)

**Comment by jhoneill** [comment]
@Jaykul  - It wasn't intentionally a false choice - you've found a workable to request a specific green. 
We still have the problem of not being quite sure what "Green" will give, it RGB value 0-max-0? Or the 3rd of 16 defined colours for the terminal, or the 11th? (Which could be re-defined to something where the hue isn't green).
 
The key question is the user expectation one I posed above 

>  If I say I want **plaintext** rendering , what's the **scope** of that ?
> The rendering of Error, verbose etc is now done with ANSI, so the plain-text option displays them plain, but `Write-Host` keeps whatever its parameters specify (ANSI sequences in the text to be written _are_ blocked). That allows a developer to impose colours the user doesn't want and create accessibility problems, so one question here is, **Should the foreground and background in Write-Host also send ANSI ?**

The initial question about plaintext stopping _your_ code from displaying formatting... if I want it that way, and plaintext doesn't do it, how do I get what I want? Because currently one method works for all ansi -  I haven't checked if setting NO_COLOR turns off colours in Write-Host.  

With `write-host` and basic ansi colours using the Palette of 16 if the user has changed the palette for accessibility or any other reason it's reasonable to assume cyan will display OK, even if it is some other colour. That's a dangerous assumption if you pick X11 Teal. So I think it's good practice to specify absolute colours in anything someone else will use.

**Comment by Jaykul** [comment]
I feel like you're arguing a completely different issue, without bothering to do a basic check of your assumptions, @jhoneill

You said that "currently, one method works for all ansi" -- but the fact is it only works on output that goes through the PowerShell text pipeline for output. **There is no way** to globally disable color in PowerShell, since Write-Host isn't affected by `$PSStyle.OutputRendering`. There is no way to disable color in the terminal either, that's why `git log` (and it's pagers) and PSReadLine still output color, even when you set OutputRendering ...

Like I said, the current implementation is spaghetti. I guess you need _the terminal_ to handle ignoring colors.

### I still don't understand why we're talking about that

I'm not proposing to change color rendering (at least, I'm not in this issue). That's irrelevant to the question of whether we should **allow** more color options on the Write-Host command. 😣

**Comment by jhoneill** [comment]
> I feel like you're arguing a completely different issue, without bothering to do a basic check of your assumptions, @jhoneill

Ouch. 
It wouldn't be the first time I have gone off at a tangent, but I'm trying to check some assumptions here.  Because (a) I would leave Write-Host frozen in its present state (b) I think when developers make use of colour they do so badly more often than not (c) Specifying absolute r,g,b colours without knowing what other colours are in use will lead to problems. Taking these three if I go into a working group session to talk about doing this my initial assumption is doing it is a poor use of resource. BUT I'm looking to be persuaded otherwise.  
   
I started by saying 
> Things like git log and git diff still output with colour - which I'm fairly sure is ansi - 
So
> You said that "currently, one method works for all ansi" -
Yes, yes, all being "all generated entirely within PowerShell". 

> the current implementation is spaghetti. 
It is, and I'm also trying to get a clear picture of where we should get to.

1. Should ANSI codes be removed from output of external .EXEs ?
2. Should Write-Host switch to using ANSI? Is there a valid reason for preventing a user turning off its colour rendering ?
3. And linked to 2 should Write-Host support absolute colours ?

Right now the answer is "use ANSI" for anything where the combination of basic palette and `Write-host -foreground / -background` isn't suitable. 
As far as I can see this request is to allow output to be forced in colour when the user has expressed a preference (not fully observed) for none, and I'm not seeing how that's a good thing.

**Comment by Jaykul** [comment]
> > You said that "currently, one method works for all ansi" -

> Yes, yes, all being "all generated entirely within PowerShell".

Unless it's PSReadLine, or Write-Host, or Microsoft.PowerShell.ConsoleGuiTools, or, or, or...

### PowerShell should not remove escape sequences produced by other apps that happen to run in a PowerShell session. 

Because [Virtual Terminal Escape Sequences](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) **are the API of the terminal**, and stripping them breaks the contract that apps think they have with the terminal. Even whe you do it, you are completely wrecking apps like [delta](https://github.com/dandavison/delta), [Out-ConsoleGridView](https://devblogs.microsoft.com/powershell/introducing-consoleguitools-preview/), htop, and everything else built on top of ncurses, gui.cs, PANSIES, etc.

Hypothetically, you can try to remove SGR sequences (that's ```e[...m``) which do color/bold/italics without totally breaking things -- but you might still break apps that depend on color contrast for frames, pop-ups, etc.

### Color should always be output using VT ESC sequences.

Because only escape sequences can pass across a remote ssh session or the sort of remote terminal sessions created by WSL, docker, kubectl, nerdctl, etc. In the modern world of cloud computing and containers, escape sequences are your only hope of providing something more than ASCII text.

### Write-Host should support full RGB colors.

Because _most terminals do_. Because Windows's conhost and terminal do. Because the current situation makes Write-Host outdated and frankly, **slower** than the one in PANSIES 🤨

### The proposed change would not force color on the user. 

**IF** PowerShell's preference variable strips SGR sequences from PowerShell output, then making `Write-Host` use SGR sequences would actually _correct_ the bug that Write-Host outputs color even when users have asked for no color. But in any case, this change literally just makes things easy which are already possible. I'm asking to change:

```PowerShell
Write-Host "$($PSStyle.Foreground.FromRgb(0xa020f0))Purple Rain$($PSStyle.Reset)"
```

To:
```PowerShell
Write-Host -Foreground 0xa020f0 "Purple Rain"
```

**Comment by jhoneill** [comment]
@Jaykul  OK,   I think that's better, consistent and do-able. I think this is on the list for the next Working group meeting so we can talk about it sensibly. There's a counter argument that the contract the user has with PowerShell or their terminal comes above the the one that apps think they have, but that's a side issue. I think work items (1) Write-Host moving to ANSI and (2) Adding support for bold/underline etc and absolute colours to an ansi-based Write-Host    should be ring fenced otherwise fixing all the present spaghetti.

**Comment by Jaykul** [comment]
Fwiw, @jhoneill here's a concrete example of useful color in the `docker build` output through PowerShell in the VS Code terminal:
![image](https://user-images.githubusercontent.com/192942/155857157-47a51de7-5a82-485c-b254-13f7661eeab5.png)

Note that the blue isn't very readable, but that's just because the VSCode palette wasn't set to my usual 😉

I think if this was missing color completely, it would be _much harder_ to easily tell what was happening:
- Blue lines are complete
- White ones are still running (you can tell without color if you look closely, because the numbers continue to change)
- Grey lines are a rolling buffer of the output of the white line directly above them

When that gets multiple downloads going and multiple tasks running at the same time, the only thing that keeps it sane is the distinction between the white and gray. Worse, if there was no way to reposition and update specific parts of the text buffer, they would have to abandon updating you on the download states...

**Comment by jhoneill** [comment]
@Jaykul  FWIW I never said that all use of colour is bad.  

However. We teach programmers that the job of programs is to print text on the console (e.g. Hello, World), and even when the programming task is scripting, not systems programming there is still a desire to print WAY too much : - one recent issue is to  print the time to process the profile less often:  I can judge fast enough or too slow, without knowing to the millisecond how long it took, I'm no more informed by the message being there , so why is it shown by default.  Way too much that is printed (like the long hashes in your example) is nothing but chaff that the poor user needs to wade through. 
   
The felony is compounded by Programmers who - with no particular skills in UI design being brought to bear on the problem - decide that we'd like our headings in green, or Zip files picked out in red or some such (or for an example on a recent issue, an external executable prints file names in dark magenta - a problem for Windows PowerShell on the default windows host).    
It's not always bad: git helps me see changes by using of colour, but in the colours git log are just what devs thought was a good idea at the time.  Picking out warnings and errors is good, and what you've shown basically has two classes of "recede into the background" and one class of "Pay attention to this". We're better off with that.  But the devs let lose with crayons kind of colouring in is something we should be spared.

**Comment by iSazonov** [comment]
Yes, you can notice how the Windows Event Viewer is made - we see a color (one of the three) and short message, if we want more we can click the line and see more, if we want even more we can open the XML tab and examine the raw information.
In the console our possibilities are limited to the first one, everything else should be in the log if it is important.

I have repeatedly voted that the formatting system should be improved to support color schemes. Then anyone could change the default scheme or use schemes from the community.

Also keep in mind that what we output to the console is often the same as what we output to the log file where there should be no control console codes. (And if we can't always automatically determine the target (console or file) but what should be the priority?)
Also keep in mind that Write-Host writes to Informational Stream too. (This can be both a solution and a problem)

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets discussed this a bit and don't have a specific resolution yet as we believe there's additional discussion that needs to happen:

- We agree that `Write-Host` should not by-pass the `OutputRendering` filter and the `-ForegroundColor` and `-BackgroundColor` should leverage PSStyle to emit ANSI instead of calling the console APIs to set colors.  In this way from an accessibility standpoint, users should get `plaintext` if that is what they require.
- We agree to support the range of [256 color names](https://en.wikipedia.org/wiki/X11_color_names).  However, we wonder how to expose this via `PSStyle`.  Should we extend the enum so that `$PSStyle.Foreground.<tab>` shows 256 completions?
- For extended color names, we would only support access via `PSStyle`
- Should we consider using the [Web color names](https://en.wikipedia.org/wiki/Web_colors) instead of X11 as some of them aren't the same and is more modern?

**Comment by Lo0oG** [comment]
You may want to use the colortable code from Windows Terminal as they made some optimisations to the data to reduce the size of storing all the different color variants.
Utils::ColorFromXOrgAppColorName
https://github.com/microsoft/terminal/blob/main/src/types/colorTable.cpp

**Comment by Jaykul** [comment]
> * Should we consider using the [Web color names](https://en.wikipedia.org/wiki/Web_colors) instead of X11 as some of them aren't the same and is more modern?

Definitely NOT. 😉

For three reasons:
1. This is the terminal. We are older than the web, and we aim to be **compatible with xterm**, not mosaic.
2. The web colors change some of the common names that are part of the existing 16 colors. E.g. cyan became aqua, magenta became fuchsia...
3. The web colors are sRGB color-space specific, and you don't have that luxury ;-)

**Comment by poidah** [comment]
Please, just add HEX values as an option and be done with it.

Do not make this harder than it needs to be just so you can show off how much you know. 

You can show off by making this as easy as possible for the use-user (coder) :)

[Link to related post](https://github.com/PowerShell/PowerShell/issues/16441#issuecomment-1419894235)
