### ISSUE TITLE
When pwsh is set the default shell in Linux, how to turn off the logo message, e.g. -nologo?

### ISSUE THREAD

**Issue by garymaxallen** [PowerShell/PowerShell#16444]
### Summary of the new feature / enhancement

I set pwsh as the default shell in Ubuntu with "chsh -s /bin/pwsh", Obviously every time I open the shell, it displays the powershell logo. How can I turn that off?

ps. When using Bash in Ubuntu, you can create a .hushlogin file to turn off the welcom message.

### Proposed technical implementation details (optional)

Is there a config file to do this?

**Comment by 237dmitry** [comment]
I dont like the idea to set pwsh as a default shell.
Maybe in `$profile` add `Clear-Host` command?

**Comment by ALIENQuake** [comment]
@garymaxallen As you said: add -NoLogo to pwsh: `pwsh -NoLogo` 😃

**Comment by 237dmitry** [comment]
> add -NoLogo to pwsh

Only if it is permissible to write arguments for the shells in /etc/shells

**Comment by garymaxallen** [comment]
> I dont like the idea to set pwsh as a default shell. Maybe in `$profile` add `Clear-Host` command?

tried, not working.

**Comment by garymaxallen** [comment]
> @garymaxallen As you said: add -NoLogo to pwsh: `pwsh -NoLogo` 😃

**Comment by garymaxallen** [comment]
> @garymaxallen As you said: add -NoLogo to pwsh: `pwsh -NoLogo` 😃

It seems you cant add "-NoLogo" to  "chsh -s /bin/pwsh"

**Comment by garymaxallen** [comment]
sorry, I misclosed my issue

**Comment by neuhaus** [comment]
@237dmitry `Clear-Host` will clear the screen which is very annoying because you lose your screen content and obviously not the same as not showing the banner.

I second @garymaxallen 's request. There should be a config file or an environment variable that allows this without having to add the `-nol` option to every single invocation.

It's a bad idea to display the copyright notice on every invocation. It's like a watch that shows you an advert every time you look at it! 
If someone wants to know about the copyright, they should read the documentation or use `pwsh --help` which currently does **not** show the copyright information.

By the way, the Linux implementation of `.hushlogin` in `login` is nice, it will only show /etc/motd, /etc/issue or /etc/issue.net if it is more recent than the file. None of the UNIX shells (or even CMD.EXE) echo copyright notices on every launch.

My suggestion: Change this issue to ask for the default copyright notice on every launch to be removed.

**Comment by Merlin8000** [comment]
Could this be something that gets supported as an option in powershell.config.json?  I came here looking for the same solution and to me, that's what makes the most sense all around.

**Comment by arcticoder** [comment]
This worked for me (tested on Windows 10.0.22000.0, Ubuntu 20.04.3 LTS, WSL 2)

PS> @"
#!/opt/microsoft/powershell/7/pwsh

/opt/microsoft/powershell/7/pwsh -Login -nol
"@ | sudo tee /opt/microsoft/powershell/7/pwsh.nologo
PS> sudo chmod +x /opt/microsoft/powershell/7/pwsh.nologo
PS> "/opt/microsoft/powershell/7/pwsh.nologo" | sudo tee -a /etc/shells
PS> chsh -s /opt/microsoft/powershell/7/pwsh.nologo

**Comment by Merlin8000** [comment]
This workaround is usable to me too. I never fully understood how the -Login parameter comes in to play. Would it make sense to add $args to the command line in the wrapper script?

**Comment by arcticoder** [comment]
@Merlin8000 
PS> pwsh -? | sls -case "-Login" -context 0,7 | ? linenumber -gt 2

\> -Login | -l

      On Linux and macOS, starts PowerShell as a login shell, using /bin/sh to
      execute login profiles such as /etc/profile and ~/.profile. On Windows,
      this switch does nothing.

      [!IMPORTANT] This parameter must come first to start PowerShell as a login
      shell. The parameter is ignored if passed in any other position.

Regarding the $args to the command line, do you mean pass the args to chsh? That's not a feature that chsh seems to support. If it did, I think the $args option would be moot because this workaround wouldn't be necessary, you'd could probably just put "-nol" in /etc/shells.

**Comment by Merlin8000** [comment]
I was suggesting that $args be inside the pwsh.nologo script to provide the same arguments which get passed into the script over to the actual cmdline. 

I get what the login parameter does, what I don't get is when it's used.  If I look at the cmdline of the process, I don't see a -Login or -l parameter specified. I would expect that parameter to be present on the cmdline of the script in the output of ps -f.  More directly,  what I'm saying is should -Login really always be present?

**Comment by YanceyChiew** [comment]
Windows users who use the system optional function OpenSSH are also plagued by this, because OpenSSH does not accept parameters when specifying the default shell. Using a proxy shell to pass parameters is indeed a workaround, but it is not elegant, we deserve better.

**Comment by rkeithhill** [comment]
Try PowerShell 7.30-preview-3.  It does not display the logo by default.  This was addressed by a PR for issue #15644.

**Comment by YanceyChiew** [comment]
> Try PowerShell 7.30-preview-3. It does not display the logo by default. This was addressed by a PR for issue #15644.

Thanks, in this version the banner is only shown a single line as `PowerShell 7.3.0-preview.3`, much better than before. Personally I just expect to be able to pass the `-nologo` setting in someway other than a startup parameter, after all, it is not too late to display the banner after processing `settings.json` or even `profile.ps1`.

Anyway, the one-line banner in this preview build is not annoying, I am very happy to see this change, 
it makes `-nologo` flag less important a lot of the time.

**Comment by rkeithhill** [comment]
> it is not too late to display the banner after processing settings.json or even profile.ps1.

Actually, for `profile.ps1` it is too late.  My profile takes about 1.5 seconds to process and not seeing anything get displayed for 1.5 secs is a bit disturbing.  Note that you don't want to display the prompt before processing `profile.ps1` because a lot of folks (including myself) have customized prompt functions.  That said, settings.json may get read in much earlier. But still, not seeing anything displayed for a second or two doesn't make for a great user experience.

I wonder if PS could benefit from the ANSI/VT equivalent of a "Splash Screen"?  That was the whole point of having a splash screen i.e. "assure the user that the app is really starting up - just taking a while to get the main window up".  🤣
