### ISSUE TITLE
In ability to set location of folders whose filename starts with an angle bracket

### ISSUE THREAD

**Issue by nebzz** [PowerShell/PowerShell#16476]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Name any folder with th first character starting with and angle brakcet, eg. [MyFolder]

no just to cd in this path: cd /path/to/[Myfolder]

is unreliable and will almost always eventually fail.

As you can see on the attached screenshot, I could initial cd into the folder
but after sometime the path can't be found, even as printing the folder contents show its present

![pw](https://user-images.githubusercontent.com/6778757/141932387-3ed23123-42de-4a18-aebc-703dec1fef15.png)
nt

### Expected behavior

```console
PS c: cd /path/to/[Myfolder]
PS /path/to/[Myfolder]:
```

### Actual behavior

```console
PS c: cd /path/to/[Myfolder]
Set-Location: Cannot find path '/path/to/[Myfolder]' because it does not exist.
```

### Error details

```console
Set-Location: Cannot find path '/path/to/[Myfolder]' because it does not exist.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![pw](https://user-images.githubusercontent.com/6778757/141932674-b4a43f12-6d42-4551-9fbe-13799780d115.png)

**Comment by kborowinski** [comment]
@nebzz : This is why *Set-Location* and similar cmdlets have **LiteralPath** parameter:
```
> cd -LiteralPath D:\TMP\[Student]\
D:\TMP\[Student] >
```

**Comment by nebzz** [comment]
But this is not obvious, for instance, 

I was compiling my java files using vscode java pack.  vscode (not commands I type) would try to compile and run the java files, and would run into the same problem... considering these are legal file names would it not be best to adapt PS to be able to handle such file names

**Comment by vexx32** [comment]
The adaptation is `-LiteralPath`, that's how PS handles them.

The reason this particular adaptation is necessary is mainly historic; wildcard patterns on Windows (and even DOS) have always accepted `[abc]` and similar patterns as a wildcard expression when searching or filtering items.

There is a lot of work that can be done to make this interface friendlier, and there are a number of existing issues around PS's specific implementations and edge cases where things aren't quite as nice (see #7999 for a decently comprehensive breakdown).

It's possible that `Set-Location` specifically could be updated to not use wildcards at all, but I suspect it was implemented as a convenience feature to minimise the amount of typing required to navigate. I'm unsure how likely it would be to expect this to change in the future, but typically features like this with a long history are difficult to change due to the risk of breaking existing code.

**Comment by nebzz** [comment]
Noted, thank you.

**Comment by MartinGC94** [comment]
You can add this to your $profile to replace the cd alias with a function: 
```
Remove-Item -LiteralPath Alias:\cd
function cd ([string]$Path)
{
    Set-Location -LiteralPath $Path
}
```

**Comment by nebzz** [comment]
Great, thank you!

**Comment by rkeithhill** [comment]
`LP` is an alias for the `LiteralPath` parameter, so this:
```
> cd -LiteralPath D:\TMP\[Student]\
```
can be shortened to:
```
> cd -lp D:\TMP\[Student]\
```
