### ISSUE TITLE
Invoke-RestMethod -verbose does not show URL

### ISSUE THREAD

**Issue by Fabaderheld** [PowerShell/PowerShell#16481]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Since upgrading to PS 7.2 `Invoke-RestMethod -Verbose` does not output the URL in the verbose message.

### Expected behavior

```console
Invoke-RestMethod -Uri https://www.microsoft.com/ -Verbose | Out-Null
VERBOSE: GET https://www.microsoft.com/ with 0-byte payload
```

### Actual behavior

```console
Invoke-RestMethod -Uri https://www.microsoft.com/ -Verbose | Out-Null
VERBOSE: GET with 0-byte payload
```

### Environment data

```powershell
>> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Any logging of URL is security dangerous because the url can contain an authentication key or something like.

**Comment by jhoneill** [comment]
> Any logging of URL is security dangerous because the url can contain an authentication key or something like.

Sorry this deserves the kind of blunt Anglo-Saxon words which we refrain from using in the forums :-) 

1. "Security" is the catch-all excuse for "We did something, don't argue". Sorry, I'm going to argue
2. Anything which puts authentication keys in the URL is - almost by definition - not secure
3. Was there any background of people complaining about the possible breach? In other words was this done _in response to customer requests_  or was it just something which seemed to a dev some to be a _good idea at the time_? Because this dev-ocracy which doesn't check with people before merging some different behaviour into the code delivers  things that aren't well though through to customers. 
4. When the cmdlet doesn't write it , a proxy function can  https://gist.github.com/jhoneill/f8ddd4e4e0a25c22d77749166d6f14fe  it hasn't been made "secure", it has just means the way to see what the call is going is now confined to those who know a cmdlet called by an unqualified name can be intercepted (by design). If this were used maliciously it would capture headers and bodies where secure information tends to live. Net things are less secure.

**Comment by PaulHigin** [comment]
WG-Security
Original issue: https://github.com/PowerShell/PowerShell/issues/14417

This was determined to be a low severity information disclosure issue when writing the URI by default.  The original change was to never write the URI, but we could add a parameter to optionally write it.  @jhoneill please create a feature request for this.

**Comment by jhoneill** [comment]
> WG-Security Original issue: #14417
> 
> This was determined to be a low severity information disclosure issue when writing the URI by default. The original change was to never write the URI, but we could add a parameter to optionally write it. @jhoneill please create a feature request for this.

Thanks Paul. I've commented to #14417  - that asked for something **optional**  -verbose:false would do the job when you know you're creating an API with sensitive info in it, not to break things for REST developers ... all teams make good and bad decisions, the powershell team has plenty in the "good column", but this ain't one. The change wants undoing, when I see complaints I'll point people to that proxy function.
