### ISSUE TITLE
Remove-NfsShare always displays confirmation prompt

### ISSUE THREAD

**Issue by acohenOT** [PowerShell/PowerShell#16554]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Running Remove-NfsShare displays confirmation prompt even without the -Confirm parameter. Expected to only prompt when -Confirm switch parameter is used.

Deploy NFS using these instructions: https://docs.microsoft.com/en-us/windows-server/storage/nfs/deploy-nfs

Create nfs share
`New-NfsShare -name nfs1 -Path C:\shares\nfsfolder`

Remove nfs share
`Remove-NfsShare -Name nfs1`

### Expected behavior

```console
No confirmation prompts
```

### Actual behavior

```console
Remove-NfsShare -Name nfs1

Confirm
Are you sure you want to perform this action?
Performing operation "Remove Share" on Target "C:\shares\nfsfolder".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
The cmdlet is not in the repo. Please use Windows Feedback Hub app to report the issue.

**Comment by acohenOT** [comment]
Done

https://aka.ms/AAf39bt

**Comment by jborean93** [comment]
Just as an FYI the reason why it's always prompting you for this is because the impact for `Remove-NfsShare` is set to `HIgh`

![image](https://user-images.githubusercontent.com/8462645/144789136-ef128554-b612-48d0-b332-280174b99163.png)

If the impact is equal to or higher than what `$ConfirmPreference` is set to (default is `High`) then PowerShell will prompt you for confirmation before continuing. You can find more details on `$ConfirmPreference` at https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.2#confirmpreference.

There are 2 ways to work around this prompt:

* Either set `$ConfirmPreference = 'None'`, or
* Add `-Confirm:$false` to the `Remove-NfsShare` call

The first disables the confirmation prompt for everything in that scope, the latter disables it just for that specific call.

**Comment by acohenOT** [comment]
Understood, thank you for details. In that case, should the [docs](https://docs.microsoft.com/en-us/powershell/module/nfs/remove-nfsshare) be fixed? It says the default value for -Confirm is false.

**Comment by jborean93** [comment]
`-Confirm` is a bit of a weird one, it's technically a switch but acts like a bool parameter as it has 3 states

* Not set - the actual default of `-Confirm`
* $false - turns off all confirmation for that cmdlet call
* $true - always prompts for confirmation for that cmdlet call

Maybe the general template used when generating the docs could better explain/document this for the `-Confirm` parameter but I'm unsure where this process actually lives.

**Comment by acohenOT** [comment]
Ah I see. That's definitely not clear when reading the documentation, but it makes sense now. Thanks for the explanation. I agree that the template for `-Confirm` should probably be updated to explain this.
