### ISSUE TITLE
functions with `-` on the name wrongfully selected for tab completion

### ISSUE THREAD

**Issue by LuanVSO** [PowerShell/PowerShell#16577]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
n/a
```

### Screenshot

![image](https://user-images.githubusercontent.com/43626415/145265891-7aefd45e-b332-43a7-bd8d-b0dcb1523d60.png)

### Environment data

```console
PS Version: 7.2.0
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.0-beta4
PSReadLine EditMode: Windows
OS: 10.0.19041.1288 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 35
```

### Steps to reproduce

1. in a clean pwsh declare any function with a `-` in it's name, i used:
```poweshell
function test-{}
function test-2{}
```
2. type any command (preferably one that doesn't have any completer) followed by a `-`
3. press `tab` or `ctrl+space`

### Expected behavior

nothing?

### Actual behavior

the functions with `-` in the name gets inserted

**Comment by MartinGC94** [comment]
This is caused by the Abbreviation Expansion feature, if you run Get-Command you will see those same functions `Get-Command -Name '-' -UseAbbreviationExpansion`  
Maybe Get-Command should be updated to handle this since a single dash can't really be considered an abbreviation? The fix for the completion code is here: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs#L1332 just update the if statement so it doesn't look for commands if the wordToComplete is just a single dash.

**Comment by ayousuf23** [comment]
@MartinGC94 I will try and solve this issue.

**Comment by ayousuf23** [comment]
@daxian-dbw @iSazonov I created a PR  (#16781) for this issue.
