### ISSUE TITLE
Support read and write Json5 file

### ISSUE THREAD

**Issue by WingDust** [PowerShell/PowerShell#16590]
### Summary of the new feature / enhancement

Support read and write Json5 file

**Comment by iSazonov** [comment]
@WingDust Current pwsh is based on NewtonSoft.NET (frozen project) and it would be great to migrate PS cmdlets to new .Net Json API.
So .Net repository is right place to request Json5 support. After we megrate to new .Net API we get all new features automatically.

**Comment by daxian-dbw** [comment]
@iSazonov Where did you see [Newtonsoft.Json](https://github.com/JamesNK/Newtonsoft.Json) became a frozen project?
I couldn't find any words like that in either the repository or its web page https://www.newtonsoft.com/json.

**Comment by iSazonov** [comment]
@daxian-dbw  Newtonsoft.Json is very old project and has very complex code which makes adding new features unnecessarily difficult.
.Net team recommends to use new .Net Json API in new projects.
The API was designed and implemented as modern and very fast replacement of Newtonsoft.Json.
No doubt Newtonsoft.Json will be supported for many more years until the community switches to .Net Json.

From https://devblogs.microsoft.com/dotnet/whats-next-for-system-text-json/
> We considered contributing changes to Newtonsoft.Json, but this was deemed infeasible without either breaking existing Newtonsoft.Json users or compromising on the performance we could achieve.

.Net Runtime already hasn't dependcy on Newtonsoft.Json. For pwsh today it is appropriate time to migrate Json cmdlets to new .Net Json API so that has more time for user adoption before next LTS release.
Also we could migrate our code for config file manipulations since .Net Json now support writable DOM.
