### ISSUE TITLE
Allow specifying multiple function parameters without comma

### ISSUE THREAD

**Issue by majkinetor** [PowerShell/PowerShell#16669]
### Summary of the new feature / enhancement

Specifying comma at the end is common error. I personally use PowerShell from version 2 and still have this issue frequently. 

I propose new line to be delimiter equivalent to `,`. This currently errors so I think it doesn't break compatibility

```powershell
function foo {
   parms(
      [string] $x
      [string] $y
      [string] $z
   )
}
```

As equivalent to 

```powershell
function foo {
   parms(
      [string] $x,
      [string] $y,
      [string] $z
   )
}
```

Another idea to minimize this error would be to tolerate trailing `,` on last parameter:

```powershell
function foo {
   parms(
      [string] $x,
      [string] $y,
      [string] $z,
   )
}
```

**Comment by MartinGC94** [comment]
Duplicate of https://github.com/PowerShell/PowerShell/issues/8873

**Comment by MatejKafka** [comment]
I would like to resurrect this feature request. The PR for #8873 was rejected, because allowing trailing commas was deemed to break consistency with the rest of list-like constructs in the language.

However, making the comma optional is consistent with mutliline array/hashtable literals and still avoids the need for a visual special case for the last item.
