### ISSUE TITLE
Unexpected output in stderr while running Powershell EncodedCommand without pseudo-tty

### ISSUE THREAD

**Issue by recolic** [PowerShell/PowerShell#16678]
### Background and Description

I'm trying to run `Write-Error boomed` with `pwsh -EncodedCommand VwByAGkAdABlAC0ARQByAHIAbwByACAAYgBvAG8AbQBlAGQA`, and I'm expecting the following output: 

```
Write-Error: boomed
```

And it works pretty well. However, running this command without pseudo-tty, will cause it to print some meaningless characters. I'm using `ssh -T localhost xxx` to run without tty, and `ssh -tt localhost xxx` to run with tty. And I'm getting the following test results: 

||with tty (-tt)|without tty (-T)|
|---|---|---|
|Windows powershell 5.1|good|messed up|
|Linux powershell 7|good|messed up|

### Steps to reproduce

Run 

```bash
ssh -T localhost pwsh -EncodedCommand VwByAGkAdABlAC0ARQByAHIAbwByACAAYgBvAG8AbQBlAGQA
```

### Expected output in stderr

```console
Write-Error: boomed
```

### Actual output in stderr

```console
#< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="Error">_x001B_[91mWrite-Error: _x001B_[91mboomed_x001B_[0m_x000A_</S></Objs>
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 5.15.10-hardened1-1-hardened #1 SMP PREEMPT Fri, 17 Dec 2021 20:16:31 +0000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

# Note that this problem also exists in powershell 5.1 on Windows.
```

### Visuals

![image](https://user-images.githubusercontent.com/19610256/147651227-5b5c9820-7c36-4742-ad9c-20b98c249f53.png)

### What have I tried

I have tried setting `$WarningPreference = "SilentlyContinue"`. After setting this variable, I can run  `[Console]::Error.WriteLine('xxx')` with `pwsh -EncodedCommand` without any issue. But `Write-Error xxx` is still messing up the terminal. 

### Ref

<https://github.com/ansible/ansible/issues/67964>

<https://stackoverflow.com/questions/51634308/start-process-using-encodedcommand-outputs-to-standard-error>

**Comment by recolic** [comment]
The template is preventing me from adding more information. Please wait before I added more info...

**Comment by recolic** [comment]
I have finished my modification to my post. You may look at it. 
(the issue template was preventing me from adding more details... So I have to modify it after creation)

**Comment by PaulHigin** [comment]
@WG-Remoting
Remoting working group: removing WG-Remoting label as this is not a PowerShell remoting issue.  Instead, this appears to be an issue with PowerShell running within a SSH remoting session.

**Comment by SteveL-MSFT** [comment]
It looks like due to the logic here: https://github.com/PowerShell/PowerShell/blob/bcde806724b765dcf8a854cadacfac60a7bb1031/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#L1349-L1364

The workaround is to specify the outputformat:

```powershell
ssh -T localhost pwsh -EncodedCommand VwByAGkAdABlAC0ARQByAHIAbwByACAAYgBvAG8AbQBlAGQA -outputformat text
```

The problem is because there is no tty, pwsh interprets that as non-interactive.  Console is redirected as it's redirected by ssh.  No output format was specified and the command was encoded.  So I don't see a way to change this without breaking existing usage.

**Comment by fflaten** [comment]
Seeing similar behavior in Azure DevOps pipeline etc. after moving from `powershell.exe -command ..` to `-encodedCommand`(https://github.com/pester/Pester/commit/3d05da013946589b0cdf77c1c2daf966fafe23b1). Suddenly getting clixml output instead of text for InformationRecord, WarningRecord etc. We've not specified `-NonInteractive` but I guess it's auto-detected somehow in Azure Pipelines.

If this is intended behavior, please update about_PowerShell.exe / about_pwsh.exe as it really is unexpected.
