### ISSUE TITLE
Support for -contains and -notcontaints for ForEach-Object for pipelines

### ISSUE THREAD

**Issue by rkitover** [PowerShell/PowerShell#16707]
### Summary of the new feature / enhancement

I would like to be able to do:

```powershell
1,2,3,4,5,6 | % -contains 3

# instead of

(1,2,3,4,5,6) -contains 3
```

this would be different from the already proposed single value operation of `Where-Object` in that, it would operate on the entire collection instead of each single value, e.g.:

```powershell
'foobarbaz','quux' | ? -match 'bar'
# 'foobarbaz'

'foo','bar','baz' | % -contains 'bar'
# True
```

**Comment by jborean93** [comment]
What's wrong with just the following?

```powershell
1,2,3,4,5,6 -contains 3
```

Not sure if I'm missing something but this works and will output `$true` because it is operating on the collection itself rather than each member as requested. If you wish to pipe in an array as an actual object rather than each individual members you need to use the unary comma operator https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.2#comma-operator-. This is essentially the same as `Write-Object .. -NoEnumerate` where it tells PowerShell not to output each IEnumerable members as distinct objects but rather output the IEnumerable object as 1 individual value.

Not sure if I'm missing something with the request?

**Comment by rkitover** [comment]
My example did not demonstrate this, but the issue is that this won't work with longer pipelines, e.g.:

```powershell
'foo','bar','baz' | %{ $_.toupper() } -contains 'BAR'

# will not work, I have to do:

('foo','bar','baz' | %{ $_.toupper() }) -contains 'BAR'
```

so this feature would allow not parenthesizing a potentially large command with many pipelines.

**Comment by scriptingstudio** [comment]
why do you need piping?
```powershell
('foo','bar','baz').toupper() -contains 'BAR'
True
```

**Comment by rkitover** [comment]
That was just an example, I meant any arbitrary pipeline chain.

**Comment by rkitover** [comment]
This is what I mean:

```powershell
function contains($what) { $input -contains $what }

1,2,3,4 | contains 3
# True
```

the operation is on the pipeline input, as opposed to a collection object.

**Comment by iSazonov** [comment]
> Where-Object [-Property] <string> [[-Value] <Object>] -Contains [-InputObject <psobject>] [<CommonParameters>]

Where-Object already support many operation including `-Contains`. Only limitation is `Property` is mandatory.

**Comment by rkitover** [comment]
> The Where-Object already support many operation including -Contains. Only limitation is Property is mandatory.

The difference is that `Where-Object` operates on each element in the collection represented by the pipeline input rather than the collection as a whole.

**Comment by jborean93** [comment]
> The difference is that Where-Object operates on each element in the collection represented by the pipeline input rather than the collection as a whole.

That's not something specific to `Where-Object`. PowerShell always enumerates the value when creating pipeline output which is why it operates on each member. By using the comma operator you output the object without enumeration.

```powershell
# Each array member is output individually
@(1, 2, 3) | ForEach-Object { "Entry - $_" }

Write-Output @(1, 2, 3)  | ForEach-Object { "Entry - $_" }

# The array is output as a single object
,@(1, 2, 3) | ForEach-Object { "Entry - $_" }

Write-Output @(1, 2, 3) -NoEnumerate | ForEach-Object { "Entry - $_" }
```

@iSazonov point still stands in that `Where-Object` must have a property name specified to use `-Contains`

**Comment by rkitover** [comment]
I didn't know that, but that doesn't help with not having to parenthesize the command, that is actually even worse.

Also, now that I think about, it should also have `-join`, to do e.g.:

```powershell
some | long | pipe | line | % -join ','
# 1,2,3,4,5
```

**Comment by rkitover** [comment]
Also, and I brought this up before on the discord, if we have a syntax to *NOT* enumerate collections that are enumerated in a pipeline, why do we not have the inverse, to *DO* enumerate collections that are not enumerated in a pipeline, such as strings and hashes.

**Comment by jborean93** [comment]
> Also, now that I think about, it should also have -join, to do e.g.:

IMO what you want is already achievable with the grouping syntax

```powershell
(some | long | pipe | line) -join ','
```

I see no benefits of somehow adding support for this in a normal pipeline as it goes against the grain of how things typically work. You could even argue that it adds another way of achieving the same thing making things complicated for newcomers learning PowerShell. If you really want something like this then just define your own `join`, `contain`, etc function that behaves as you wish.

> Also, and I brought this up before on the discord, if we have a syntax to NOT enumerate collections that are enumerated in a pipeline, why do we not have the inverse, to DO enumerate collections that are not enumerated in a pipeline, such as strings and hashes.

Because things always do that by default with the sole exception of `String` and `IDictionary` objects. There's no reason why there isn't AFAIK except that it hasn't been implemented and I don't really see a complelling reason for that over just a simple `.GetEnumerator()` call for those 2 exceptions.

**Comment by jhoneill** [comment]
```
function contains  {
param ($value)
$Input -contains $value
}

ps > 1,2,3,4,5,6 |  contains 3
True

ps > 1,2,3,4,5,6 | contains 7
False
```

Does what you want and saves you 3 keystrokes into the bargain. 


Do `where -?`  and have a look at how horrible the parameter sets have become to understand why people won't want to lash this onto `ForEach-Object`.

**Comment by rkitover** [comment]
Having these functions or something like this would solve the problem of not having to parenthesize long pipelines. I was just thinking it would be a nice thing to have in the core language, regardless of the method. If not, it could be a gallery module.

**Comment by rkitover** [comment]
Now that I think about it more, `ForEach-Object` would be the wrong place to do this.

What would really be nice is a function or some kind of syntax to group a pipeline into the collection object to do arbitrary operations on. This is already possible with a scriptblock, e.g.:

```powershell
1,2,3,4,5,6,7 | &{ $input -contains 3 }
# True
```

But it may be worthwhile to have a nicer way to do this for interactive one-liner use etc..

Somethjing like this maybe:

```powershell
1,2,3,4,5,6,7 >@ -contains 3
# True
1,2,3,4,5,6,7 >@ -join ','
# 1,2,3,4,5,6,7
```

it would be fairly obvious what happens here.

**Comment by iSazonov** [comment]
Don't forget about `@(1,2,3,4,5,6,7).Where({$_ -eq 3})` and `@(1,2,3,4,5,6,7).ForEach({$_ -eq 3})`
