### ISSUE TITLE
Support flags for regex operators like -match and -replace

### ISSUE THREAD

**Issue by rkitover** [PowerShell/PowerShell#16706]
### Summary of the new feature / enhancement

Things like `sed` allow you to do things like this:

```powershell
write 'X X X X' | sed 's/X/Y/2'
# X Y X X
```

pwsh could also do things like:

```powershell
'X X X X' -replace 'X','Y',2
# X Y X X
```

just as an example, this may not be how you'd implement this specific option, but in general, any parameters starting at the third position for `-replace` or e.g. the second position for `-match` could be flags/options to modify the operation. They wouldn't have to be a single string, they could be a list.

**Comment by jhoneill** [comment]
This is probably better done as a cmdlet or function than by modifying the operator - as your example shows, sooner or later someone will want to pipe into it. 
It doesn't look like something that would be very hard to write

**Comment by vexx32** [comment]
I'm pretty sure the underlying regex engine (System.Text.RegularExpressions.Regex) can already do this kind of thing, so if you don't mind using that, you can write code to do that pretty easily, and package it as a function as jhoneill mentioned.

**Comment by rkitover** [comment]
I'll give a better example where this could be very convenient. Suppose you want to make only the first replacement in a string, instead of all occurrences. This is the default behavior of unix substitute commands in things like sed without `/g`.

The way to do this now is:

```powershell
'X X X X' | %{ [regex]$r = 'X'; $r.replace($_,'Y',1) }
# Y X X X
```

Now if this feature was available, it would be as simple:

```powershell
'X X X X' | %{ $_ -replace 'X',"Y',1 }
# Y X X X
```

**Comment by kasini3000** [comment]
Discard sed, discard complex syntax, and regular.
Share: [Find-Replace] script tool written by me.
============
$f ='/etc/selinux/config'
/tmp/psed.ps1 -infile $f -find'SELINUX=enforcing' -replace'SELINUX=disabled'
============
I can’t learn sed. I struggled to learn a little bit, but I can’t remember sed. In order to treat this disease of mine, I wrote a small script "Ps Finding Calculation Replacing.ps1", you can rename it to psed.ps1
It is very simple to use; it is also common to win and linux; it does not support regularity; it does not need to escape characters; it can kill sed under linux 99%.
Slogan=Simple to die for you! People who specialize in academics can’t remember sed. Solve the pain points that sed is difficult to learn and use.
Complicated functions can be solved through the callback function written by yourself.
Script download address:
[https://gitee.com/chuanjiao10/powershell/tree/master/win-linux通用] 
Manual & Example: In the download address---[ps找算替_v3_readme.html]
