### ISSUE TITLE
select-string does unexpected behavior when supplying a parameter via interactive

### ISSUE THREAD

**Issue by hdformat** [PowerShell/PowerShell#16772]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I was expected the same results from both a/b commands
a.
```
get-process | select-string -pattern edge" and 
```
b.
```
"get-process | select-string

cmdlet Select-String at command pipeline position 2
Supply values for the following parameters:
Pattern[0]: edge
```
but they show differrent results. 

### Expected behavior

```console
PS> get-process | select-string -pattern edge

System.Diagnostics.Process (msedge)
System.Diagnostics.Process (msedge)
System.Diagnostics.Process (msedge)

PS> get-process | select-string

cmdlet Select-String at command pipeline position 2
Supply values for the following parameters:
Pattern[0]: edge
Pattern[1]:

System.Diagnostics.Process (msedge)
System.Diagnostics.Process (msedge)
System.Diagnostics.Process (msedge)
```

### Actual behavior

```console
PS> get-process | select-string -pattern edge

System.Diagnostics.Process (msedge)
System.Diagnostics.Process (msedge)
System.Diagnostics.Process (msedge)

PS> get-process | select-string

cmdlet Select-String at command pipeline position 2
Supply values for the following parameters:
Pattern[0]: edge
Pattern[1]:

Select-String: Cannot bind argument to parameter 'Path' because it is null. This failure might be caused by applying the default parameter binding. You can disable the default parameter binding in $PSDefaultParameterValues by setting $PSDefaultParameterValues["Disabled"] to be $true, and retry. The following default parameter was successfully bound for this cmdlet when the error occurred: -Encoding
Select-String: Cannot bind argument to parameter 'Path' because it is null. This failure might be caused by applying the default parameter binding. You can disable the default parameter binding in
```

### Environment data

```powershell
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           ¨1.0, 2.0, 3.0, 4.0…¼
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/869339/150052680-534d76a5-e119-4098-b725-dbf2f10a1126.png)

**Comment by jhoneill** [comment]
It's not specific to `select-string`

AIUI what happens is when a command has multiple parameter-sets (`Select-String` has 6) and the parameters given aren't sufficient to select one,  PowerShell will try to use the default set - which is the "File" parameter set for `Select-String`.  It will prompt for any missing parameters in that set (in this case the `file` set is missing the `pattern` parameter) and tries to continue. 

In the case of `select string`,  the default set has a `path` parameter which looks to get a `path` property from the whatever is piped and things go south from there... 

The following works  because the objects arriving at `Select-String` have a path property: 
![image](https://user-images.githubusercontent.com/16209593/150118924-056fc77d-238f-48a8-ad7c-f7a064a74977.png)

However; using `dir *.ps1 |  select-string` , will produce an error for each file, because File objects don't have a `path` property - they have `name`, `parent`, and `fullname` and the author of `Select-String` didn't allow for this case by giving the path parameter an alias of "FullName" 

If you **do** specify a parameter, then when something is piped in `Select-String` selects the `Object` parameter set because that will take whatever is piped in. If the object is a file, `Select-String` reads the file, if it is anything else it converts the object to a string  so    
` dir *.ps1 | Resolve-Path | select-string profile` 
will return  
`Microsoft.PowerShell.Core\FileSystem::C:\Users\ ... \profile.ps1`.
I.e. it no longer uses the path property to get the file. 

For `Select-String` the parameter sets can **probably** be altered so that 
1.  `Select-string "foo" *.ps1`   which needs the File parameter set still works but...
2.  The Object parameter set is the default.
