### ISSUE TITLE
Please allow to disable Variable inheritance for Functions

### ISSUE THREAD

**Issue by schittli** [PowerShell/PowerShell#16794]
### Summary of the new feature / enhancement

Hello

### The issue
in our daily work (we've created more than 5k PowerShell Scrips) we mostly have runtime errors because functions do not initialize variables in all code-paths and then the value of the parent (or even global!) variable with the same name is used.

#### The benefit of inherited variables in functions
Professional scripts almost never want to access global variables in functions
If they do:
- it is very rare
- they usually need single variables, which can then be explicitly addressed in the function

#### The Workarounds
I know, there are workarounds to manually disable inheritance in functions, e.g. by creating a local variable of every global variable and initializing them to $null. Or by creating a new PowerShell process. Or by using ScriptBlocks, Jobs, etc.
In the end, however, they are all very tedious.

I have added some ideas for the technical implementation below.

Thanks a lot, kind regards,
Thomas

### Ideas for discussion
As always, it's tricky to choose an elegant, sustainable concept for such requirements - and PowerShell has great architects, thank goodness. I'll give a few concept ideas anyway:

Variable inheritance into Functions could be disabled by:
- a `#Command` similar to: `#Requires -Version 7`
- by the `private:` scope like: `Function private:My-Func() {} `

### By the way, the implementation of this requirement should be quite simple:

As soon as a variable is accessed in a function for the 1st time, 
PowerShell does not copy the value from an existing parent
but simply initializes it by the default value.

**Comment by kasini3000** [comment]
1 Unique variable name in sub function
or
2 $private:foo in function

**Comment by jhoneill** [comment]
> 1 Unique variable name between function and sub function
> or
> 2 variable name 【$private:foo】in function

or 3 fix the code which so that it does initialize its variables.

> in our daily work (we've created more than 5k PowerShell Scrips) we mostly have runtime **errors because functions do not initialize variables in all code-paths** and then the value of the parent (or even global!) variable with the same name is used.

The problem is that the people who use non-unique names AND also don't ensure their variables don't get initialized  AND don't mark them local: or private:   don't understand that they are doing something wrong so they won't apply a flag to a function to say "This has that kind of variable".  And the people who understand the flag would write code which didn't need it.

Sweeping generalizations like _"Professional scripts almost never want to access global variables in functions"_  bother me a bit, because quite a lot of scripts refer to $pwd. or $psversionTable, or $host, or $isWindows, or the various preference variables. Environment variables are, by definition, global, and that's where we for go username, computerName and various paths.  In many cases information needed by many functions - or by multiple calls to the same function (e.g. remote session details) lives in script-scoped variables. Some information is global in nature.  
 That's very different from saying "don't use globals to do the job of parameters" and "don't access working variables which belong to other bits of code" - neither of those _are_ global in nature.

When we get a lecture on what "Professional scripts" do and don't do, it invites the response that professional scripts take a bit more trouble about initializing variables.

**Comment by 237dmitry** [comment]
> we mostly have runtime errors because functions do not initialize variables in all code-paths and then the value of the parent (or even global!) variable with the same name is used.

It's hard for me to imagine such a mess. I hope these variables are not constant and are not read-only. In my opinion, this is a management problem.
