### ISSUE TITLE
`Read-Host -AsSecureString` should not allow to paste from clipboard

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#16805]
### Summary of the new feature / enhancement

The [**SecureString operations**](https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=net-6.0#securestring-operations) warning:

> ⚠ Important
>
> A SecureString object should never be constructed from a String, because the sensitive data is already subject to the memory persistence consequences of the immutable String class. The best way to construct a SecureString object is from a character-at-a-time unmanaged source, such as the Console.ReadKey method.

Also implies that a SecureString object should never be constructed from a ***clipboard* string**.
Therefore `Read-Host -AsSecureString` should not allow to for clipboard pasting (or have at least have a switch for this*)

* e.g. `-AllowClipboardPaste`, meaning that I recommend to disallow by default
This will make developers aware of this security risk.
* In "disallow" mode, an additional `Write-Warning` to the user might be given that placing passwords on the clipboard is a potential security risk.

Related (contradicted) issue: [`#3511` Read-Host -AsSecureString failing on pasting value into it](https://github.com/PowerShell/PowerShell/issues/3511)

**Comment by SeeminglyScience** [comment]
It doesn't really have a way to read clipboard input. If you're successfully pasting into `Read-Host -AsSecureString`, then it's the terminal you're using sending the clipboard text as input.

That doesn't create a string in the same way that the `SecureString` docs are referencing. Even if it did though, PowerShell just gets the input as if they were key presses.

**Comment by jhoneill** [comment]
Pasting a secret from the clipboard is a requirement in many places, API keys are often impractical to type because it is assumed they will be pasted - they are also too long and random for most people to commit to memory. Azure Devops creates  API keys of >50 characters and typically they need to be copied from a web page, pasted, and saved in some secure-at-rest form (secure string fills this role nicely).  
The advice that secrets should not be in memory as clear text is all very fine and good but if something is capable of being copied to the clipboard, having the user read it in one window and type it and type it another still has a clear version in memory but adds exposure to key loggers.

**Comment by iRon7** [comment]
@SeeminglyScience 
>It doesn't really have a way to read clipboard input. If you're successfully pasting into Read-Host -AsSecureString, then it's the terminal you're using sending the clipboard text as input.

I wasn't aware of that, issue: [`#3511` Read-Host -AsSecureString failing on pasting value into it](https://github.com/PowerShell/PowerShell/issues/3511) gave me the (incorrect) feeling that it was controlled by the cmdlet.

I have closed the issue as I understood that this can't actually be implemented
