### ISSUE TITLE
Get-ItemPropertyValue should have an option to not expand REG_EXPAND_SZ value when reading registry

### ISSUE THREAD

**Issue by cadegenn** [PowerShell/PowerShell#16812]
### Summary of the new feature / enhancement

`Get-ItemPropertyValue` automatically expand `REG_EXPAND_SZ` value when fetching one from the windows registry.
With this behavior, the coder cannot read a value, modify it, and write it back to the registry. It is a problem since juste READING a value actually MODIFY the value.

I would suggest to add an option to just read the value as-is. For example `-Raw` to get it simple. Or if you want a `-Options` with an object of type `RegistryValueOptions`.

I would prefer a simple `-Raw` option (like in `Get-Content -Raw`) to be used like this :
`Get-ItemPropertyValue -Path "HKLM:\SYSTEM\CurrentControlSet\Session Manager\Environment" -Name "Path" -Raw`

### Proposed technical implementation details (optional)

This post https://stackoverflow.com/questions/51776242/how-to-retrieve-original-unresolved-unexpanded-registry-value give a workaround : 
```
(Get-Item -Path HKCU:\Environment).GetValue(
  'PATH',  # the registry-value name
  $null,   # the default value to return if no such value exists.
  'DoNotExpandEnvironmentNames' # the option that suppresses expansion
)
```
But it is far way more complicated and unintuitive in comparison of just `Get-ItemPropertyValue -Path HKCU:\Environment -Name PATH -Raw` (I think).

Thank you

**Comment by iSazonov** [comment]
This could be dynamic parameter from Registry provider.

**Comment by cadegenn** [comment]
I'm not a huge fan of `-NoXY` parameters in general because it inverse logic. 
If you want to write the whole thing, you have to use `-NoExpand:$true` to enable deactivation of expansion and use `-NoExpand:$false` to disable the deactivation (so to enable expansion). To me it is counter-intuitive.

The logic at the beginning would have been to read raw value by default (because it is the real value, unexpanded) and either call `Get-ItemPropertyValue` with an optional `-Expand` parameter or pipe it to an expansion function. But I'm aware that it would probably break things if we change the default behavior now.

All that said, if the feature is implemented with a `-NoExpand` parameter, I'll welcome it with pleasure ;)

**Comment by iSazonov** [comment]
> you have to use `-NoExpand:$true` to enable deactivation of expansion

We can use `-NoExpand` without "suffix".
We had discussions about `Raw` and it is not so good name too.

The name is not critical if you want to pull PR now. (We can continue to discuss the name in PR)

Ping WG-Cmdlets to make a conclusion about the request.

**Comment by cadegenn** [comment]
>  We can use -NoExpand without "suffix".

Yes I know, I just gave my point of view.

> The name is not critical if you want to pull PR now.

Unfortunately, I am not skilled enough in c# to initiate a PR. sorry

If this request is going to become true, I will thankfully welcome it, whatever the name of the option is.
Thank you.

**Comment by jhoneill** [comment]
The example given is not a good one because `path` is a string not an expanded string. `Temp` works better.

```
ps> $I = get-item "HKCU:\Environment"
ps> $I.GetValueKind("Path")
String

ps> $I.GetValueKind("Temp")
ExpandString

 $I.GetValue("Temp",$null,'DoNotExpandEnvironmentNames')
%USERPROFILE%\AppData\Local\Temp

ps> $I.GetValue("Temp")
C:\Users\xxxxx\AppData\Local\Temp
```
The default behaviour is expand. So it is reasonable for `Get-ItemPropertyValue` have the same default, but not so reasonable to have no other option. 

The `Get-ItemProperty` cmdlet creates a custom object with the selected Property/properties as members.  These are also expanded. 

```
ps> $p = Get-ItemProperty -Path  "HKCU:\Environment" -Name "Temp"
ps> $p

TEMP         : C:\Users\xxxx\AppData\Local\Temp
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER\Environment
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER
PSChildName  : Environment
PSDrive      : HKCU
PSProvider   : Microsoft.PowerShell.Core\Registry


> $p | gm

   TypeName: System.Management.Automation.PSCustomObject

Name         MemberType   Definition
----         ----------   ----------
Equals       Method       bool Equals(System.Object obj)
GetHashCode  Method       int GetHashCode()
GetType      Method       type GetType()
ToString     Method       string ToString()
PSChildName  NoteProperty string PSChildName=Environment
PSDrive      NoteProperty PSDriveInfo PSDrive=HKCU
PSParentPath NoteProperty string PSParentPath=Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER
PSPath       NoteProperty string PSPath=Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER\Environment
PSProvider   NoteProperty ProviderInfo PSProvider=Microsoft.PowerShell.Core\Registry
TEMP         NoteProperty string TEMP=C:\Users\xxxx\AppData\Local\Temp
```

If any changes are to be made, `Get-ItemProperty` and  `Get-ItemPropertyValue` should both support the same dynamic parameter. See below on names but  `-Raw`,  `-NoExpand`  or something else based on the values of the `RegistryValueOptions`  enum could all work. There are only two values for `RegistryValueOptions` btw, `None` and `DoNotExpandEnvironmentNames` 

Whether it _really_ is or not I always thought of  `Get-ItemPropertyValue  -Path X -Name Y` to be `(Get-ItemProperty -path X -name Y).Y`  under the surface and their behaviour should be the same.  This would mean that a call to  `Get-ItemProperty` which returns more than one ExpandString treats them ALL the same way, which is fine. 

Overall it looks like a good idea to me - which isn't to say it is practical, but it seems to break nothing and move things in the right direction. 


**Switch parameter Names**  Are best as `-DoSomethingNonDefault`  the _absence_ of the switch always conveys  "do nothing  / do the default" and where possible the name gives some idea what the default is. 
This means we might have `New-Account -Disabled` - accounts are enabled by default.   `Set-` commands often follow their `New` or `Add-`  counterparts giving `Set-Account -disabled`.  People don't like `-disabled:$false` to say "Undo changing from the default".  That doesn't apply to "Get X in the non-default way" operations like this. 
 
There are precedents for inverting the name to `NoDefaultBehaviour`  15 or so are used once and these used at least twice.
   2 NoProxy              
   2 NoEnumerate                
   3 NoEncryption         
   3 NoTypeInformation    
   5 NoServiceRestart     
   5 NoNewline            
   6 NoClobber            

One _can_ use `command | out-file -NoClobber:$false ...`  but in practice people omit the parameter completely and they write `-NoClobber` in preference to `-NoClobber:$true`  (a boolean `-Clobber  $false` would be the worst of all).  "
It's usually better to avoid  "Yes, I don't want..."   but  the double negative is seldom a problem.

**Comment by SeeminglyScience** [comment]
> The example given is not a good one because `path` is a string not an expanded string. `Temp` works better.

That's actually part of the problem. `PATH` *can* be expandable, but the .NET API for environment variables doesn't give you the option to not expand. So any .NET based installer that adds an entry to path more than likely forces it to `REG_SZ`. This thread has more info dotnet/runtime#1442

**Comment by SeeminglyScience** [comment]
The Engine WG discussed this yesterday. We agree it would be nice to have as a dynamic parameter for the registry provider. Marking as up for grabs.

**Comment by bb010g** [comment]
@SeeminglyScience Could you reopen this? This is still a valid issue.

**Comment by urbans0ft** [comment]
I ran into the same issue and wrote a wrapper function around `reg query`:
```powershell
> $keys = Get-RegistryKey "HKCU\Environment"
> $keys.Path.Data
# sample output
%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Apps\vscode\bin

> $keys = Get-RegistryKey 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment'
> $keys.Path.Data
# sample output
%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Program Files\PowerShell\7\
```

# Get-RegistryKey

```powershell
function Get-RegistryKey
{
    param(
        [Parameter(Mandatory)]
        [string]$KeyName,
        [string]$ValueName,
        [ValidateSet('REG_SZ', 'REG_MULTI_SZ', 'REG_EXPAND_SZ',
        'REG_DWORD', 'REG_QWORD', 'REG_BINARY', 'REG_NONE')]
        [string]$Type,
        [string]$Data
    )
    reg query $KeyName | # split the reg result up in name, type and data
    Select-String '^(?<Name>.*)(?<Type>REG_((NONE|BINARY|DWORD|QWORD)|((((MULTI|EXPAND)_)?SZ)))) +(?<Data>.*)$' |
    Select-Object -ExpandProperty Matches |
    ForEach-Object {
        [PSCustomObject]@{
            'Name' = $_.Groups['Name'].Value.Trim()
            'Type' = $_.Groups['Type'].Value
            'Data' = $_.Groups['Data'].Value
        }
    } |
    Where-Object {
        # filter the results if ValueName was set
        if ($PSBoundParameters.ContainsKey('ValueName')) {$_.Name -ilike $ValueName} else {$true}
    } |
    Where-Object {
        # filter the results if Type was set
        if ($PSBoundParameters.ContainsKey('Type')) {$_.Type -ieq $Type} else {$true}
    } |
    Where-Object {
        # filter the results if Data was set
        if ($PSBoundParameters.ContainsKey('Data')) {$_.Data -ilike $Data} else {$true}
    } |
    ForEach-Object {
        # create a hashtable instead of an array of objects
        $registryKey[$_.Name] = [PSCustomObject]@{
            'Type' = $($_.Type)
            'Data' = $($_.Data)
        }
    } -Begin {$registryKey = @{}} -End {$registryKey}
}
```
The function is not expected to be fail-proof.
