### ISSUE TITLE
Feature Request: Native support for YAML

### ISSUE THREAD

**Issue by 8YdEo37** [PowerShell/PowerShell#16819]
### Summary of the new feature / enhancement

My personal use case is configuration files, but would be perfect to ingest any yaml structure without extra modules with stale development and with official support for PS +7

- https://github.com/cloudbase/powershell-yaml
- https://github.com/Phil-Factor/PSYaml

In my opinion, Yaml is getting mature enough to bring it natively to Powershell without hassle around JSON

PS: Thanks for pushing hard forward and making Powershell so good nowadays ! ;)

**Comment by vexx32** [comment]
There are multiple issues for this already: 

- #2109
- #3607
- #3613
- #16785

**Comment by jhoneill** [comment]
> There are multiple issues for this already:
> 

A couple of points before this one is marked as closed, 
- It would be good to have an official statement - even if just team blog post entitled "Why doesn't PowerShell ship a YAML module" this has been rumbling along for five years now and people will keep asking. 
- There is a community module. https://www.powershellgallery.com/packages/powershell-yaml/0.4.2  With 18 million downloads it has become the de-facto way to add YAML support, the OP terms it stale (last update was May 2020) others might call it stable :-)  It uses https://github.com/aaubry/YamlDotNet which has been pull from nuget over 30 million times, and has been updated more recently.  

 What would people like the PowerShell team to do ?  
1. Find a way to ship the community module with PowerShell 7.x  ? (Possibly fork the code and maintain it, but it means taking a dependency on a third party YAML library for .NET with which comes with that)
2. Build a "clean clone" version of the community module? i.e. the same commands work, the same YAML library is doing the work under the surface (same dependency issues)  but the module code comes from the team
3. Lobby the powers-that-be on the .NET team to add YAML support (much as Json support was added after years of relying on 3rd party libraries),  and when they do add cmdlets to leverage it 
4. Write their own parser (which requires significant effort, and would likely be dropped if/when YAML support goes into .NET)

None of these would allow PowerShell to do something it can't do now using a 3rd party module, or to do it very much better, than the third party module ; they  address the problem that **some people using PowerShell want all modules they use to be first-party ones**; I have worked for customers who make the processes to adopt 3rd party modules an onerous one so I understand that this can be for good reason. If the PowerShell team took a dependency on YamlDotNet, things could be made easier for those customers. But it is easy to see this could be repeated for many, many things - more than the team could ever have capacity for. That's why the default position is these additions should come from the community - people can make a case that X should not follow that default, but to date the case made for YAML hasn't convinced the people it needs to.

**Comment by vexx32** [comment]
[This comment](https://github.com/PowerShell/PowerShell/issues/3607#issuecomment-901288121) in one of the linked issues above discusses the reasoning / stance of the pwsh team. As far as I know it hasn't changed much. 🙂

**Comment by jhoneill** [comment]
@vexx32    Indeed.  I'm remined of 

> "I eventually had to go down to the cellar...  with a torch."   (flashlight)
>  _'The lights had probably gone.’_ 
> "So had the stairs."
> '_You found the notice didn’t you?'_
>  "Yes I did. It was on display in the bottom of a locked filing cabinet stuck in a disused lavatory with a sign on the door saying 'Beware of The Leopard'."

Instead of having the teams position in a comment to a closed issue on github it might be helpful to give it a bit more, you know,  _prominence_  :-)
