### ISSUE TITLE
PowerShell should support file named `NUL` or other DOS reserved name

### ISSUE THREAD

**Issue by huoyaoyuan** [PowerShell/PowerShell#16841]
### Summary of the new feature / enhancement

See more detail at https://github.com/dotnet/runtime/issues/62943

In short words: PowerShell can list the existence of such file, but not manipulating it.
Such file is unsupported in many cases (including Windows explorer and notepad). Supporting in PowerShell makes manipulating it easier.

### Proposed technical implementation details (optional)

The linked .NET issue gives a solution, and explained why they don't want to enable it at their side.

**Comment by iSazonov** [comment]
Historically PowerShell explicitly exclude DOS name from manipulations
https://github.com/PowerShell/PowerShell/blob/434b238d1a81590185f899545f0ffb2223743147/src/System.Management.Automation/engine/Utils.cs#L1256-L1261

I created the nul file by an utility and run `dir` in PowerShell:
```
Exception             :
    Type       : System.IO.IOException
    TargetSite :
        Name          : EnsureDataInitialized
        DeclaringType : System.IO.FileSystemInfo
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : The parameter is incorrect. : '\\.\nul'
    Source     : System.Private.CoreLib
    HResult    : -2147024809
    StackTrace :
   at System.IO.FileSystemInfo.EnsureDataInitialized()
   at System.IO.FileSystemInfo.get_Attributes()
   at Microsoft.PowerShell.Commands.FileSystemProvider.GetFileSystemItem(String path, Boolean& isContainer, Boolean showHidden) in C:\Users\1\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Automation\namespaces\FileSystemProvi
der.cs:line 1376
   at Microsoft.PowerShell.Commands.FileSystemProvider.GetItem(String path) in C:\Users\1\Documents\GitHub\iSazonov\Pow
erShell\src\System.Management.Automation\namespaces\FileSystemProvider.cs:line 1300
TargetObject          : C:\tmp\nul
CategoryInfo          : ReadError: (C:\tmp\nul:String) [Get-ChildItem], IOException
FullyQualifiedErrorId : GetItemIOError,Microsoft.PowerShell.Commands.GetChildItemCommand
InvocationInfo        :
    MyCommand        : Get-ChildItem
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 3
    Line             : dir c:\tmp\n*
    PositionMessage  : At line:1 char:1
                       + dir c:\tmp\n*
                       + ~~~~~~~~~~~~~
    InvocationName   : dir
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

As you see .Net return an error. Since PowerShell based on .Net API we can not do more then .Net does.

@adamsitnik Have you (.Net team) an interest in fixing the issue I accidentally found?

**Comment by jhoneill** [comment]
I think the correct answer has been given on  https://github.com/dotnet/runtime/issues/62943 

>I don't believe that expanding all paths by default just to make special DOS file names work is worth it. It increases the code complexity, chances for bugs, and perf regressions (it's extra work). Those who for some reason want to use such names need to do the research and provide the right prefix. If that is too much, they should give up on this idea.

It's not obvious how one uses the prefix in PowerShell or if it is even possible. 
```
ps> dir \ > "\\?\$pwd\Nul"
Out-File: Cannot perform operation because the wildcard path \\?\C:\Users\xxxxx\Nul did not resolve to a file.
```
? is treated as a wild card, unless it is escaped but escaping causes a different error. 
```
ps> dir \ > "\\``?\$pwd\Nul"
Out-File: The filename, directory name, or volume label syntax is incorrect. : '\\`?\C:\Users\xxxxx\Nul'
```

This maybe because escaping wildcards isn't well handled. 
```
ps> dir >  "[stuff]"
Out-File: Cannot perform operation because the wildcard path [stuff] did not resolve to a file.
ps> dir \ > "``[stuff``]"
ps> dir

   Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          04/02/2022    12:06            761 `[stuff`]
``` 
So it creates a file with back-ticks in the file name.  **BUG?**

```
ps> del "``[stuff``]"
Remove-Item: Cannot find path 'C:\Users\xxxx\[stuff]' because it does not exist.
```
But when it tries to delete the back ticks are removed _Correct?_



**In addition** behaviour changed between 5.x and 7.2 

In 5.x 
```
>  dir \ > nul
out-file : FileStream was asked to open a device that was not a file. ....
> dir | export-csv -Path con
export-csv : FileStream was asked to open a device that was not a file. ....
```
In 7.2 
```
>dir \ > nul
>
```
No output
```
dir | export-csv -path con
```
Writes to the console.  Using `PRN` or `LPT1` in place of `con`/`nul` gives `Could not find file '\\.\prn'.`

Now that `nul` and `con` are trapped, at least in some cases, it would be a **breaking change** to treat them as filenames. There are two conflicting requirements  `> nul` discards output as it does in the Unix and cmd.exe worlds  Vs `> nul` creates a file named nul.  The latter has never been the case AFAIK,

**Comment by iSazonov** [comment]
> ```
> ps> dir \ > "\\?\$pwd\Nul"
> Out-File: Cannot perform operation because the wildcard path \\?\C:\Users\xxxxx\Nul did not resolve to a file.
> ```
>   
>   
> ? is treated as a wild card, unless it is escaped but escaping causes a different error.

It is not correct. If path starts with `\\` it is _Provider Direct Path_ and design intention is to pass it to low API as-is but really it is not fully implemented.
