### ISSUE TITLE
Range operator doesn't work in surrogate pairs character

### ISSUE THREAD

**Issue by EtemenNiguru** [PowerShell/PowerShell#16858]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm proceed Japanese text in PowerShell with range operator(..)

Generally, range operator used like as "a" .. "c".
```PowerShell
PS> "a".."c"
a
b
c
```
Therefore range operator can also be used Japanese Kanji.
```PowerShell
PS > "一".."七"
一
丁
丂
七
```
That characters Unicode code point is "一" to U+4E00, "七" to U+4E03 at CJK unified ideographs in Unicode 14.0.0 .
However, a bit Kanji and symbol (include Emoji) cannot represent by single char type. These are called surrogate pairs character.

Examples follow:
```PowerShell
PS> "`u{29E3D}"
𩸽
PS> "`u{1F600}"
😃
```

Then it is cannot cast string to char type.
```PowerShell
# Normal Kanji.
PS> [char]"`u{4E00}"
一
# Surrogate pairs character.
PS> [char]"`u{29e3d}"
InvalidArgument: Cannot convert value "𩸽" to type "System.Char". Error: "String must be exactly one character long."
😃
PS> [char]"`u{1F600}"
InvalidArgument: Cannot convert value "😀" to type "System.Char". Error: "String must be exactly one character long."

```
Please look at the page [Character encoding in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-encoding-introduction)

To excerpt from the page.
> However, for some languages and for some symbols and emoji, it takes two char instances to represent a single character. 

For that reason, I think that the range operator can only be using characters which can be cast to char type. But I think surrogate pairs characters should also be supported at the context of semantics.

Sorry for my bad english.

### Expected behavior

```console
PS> "一".."一"
一
PS> "`u{4E00}".."`u{4E00}"
一
PS> "𩸽".."𩸽"
𩸽
PS> "`u{29e3d}".."`u{29e3d}"
𩸽
```

### Actual behavior

```console
PS> "一".."一"
一
PS> "`u{4E00}".."`u{4E00}"
一
PS> "𩸽".."𩸽"
OperationStopped: Input string was not in a correct format.
PS> "`u{29e3d}".."`u{29e3d}"
OperationStopped: Input string was not in a correct format.
```

### Error details

```console
PS> Get-Error
Exception             :
    Type       : System.FormatException
    TargetSite :
        Name          : ThrowOverflowOrFormatException
        DeclaringType : System.Number, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : Input string was not in a correct format.
    Data       : System.Collections.ListDictionaryInternal
    Source     : System.Private.CoreLib
    HResult    : -2146233033
    StackTrace :
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ToInt32(Object value)
   at System.Management.Automation.ParserOps.RangeOperator(Object lval, Object rval)
   at System.Management.Automation.Interpreter.FuncCallInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : OperationStopped: (:) [], FormatException
FullyQualifiedErrorId : System.FormatException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : "`u{29e3d}".."`u{29e3d}"
    PositionMessage  : At line:1 char:1
                       + "`u{29e3d}".."`u{29e3d}"
                       + ~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS> > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Linux 5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
hex:29E3D == 171581
The .net framework can only handle characters smaller than 65535, I don't know if it has changed in .net 6 now.
If not, I am pessimistic that this problem will never be solved.

**Comment by JamesWTruher** [comment]
I agree with @kasini3000, this seems to be a behavior with .net
```
PS> "`u{29e3d}"           
𩸽
PS> [char]"`u{29e3d}"   
InvalidArgument: Cannot convert value "𩸽" to type "System.Char". Error: "String must be exactly one character long."
```

**Comment by vexx32** [comment]
WG-Engine:

There are a few ways we could potentially go about implementing this as an enhancement, all of which would likely involve use of the new(ish) System.Text.Rune type:

- Change the object types returned from `"a".."z"` and all string ranges like this from `[char]` to `[System.Text.Rune]`, and enumerate a numeric range over the rune values, return a set of values with Runes. This would be a breaking change, as it would mean usages like `[string]::new('a'..'z')` would stop working.
- Introduce the above behaviour only for ranges that definitely exceed the `[char]` value range. This would avoid breakages but introduce some inconsistency in how the lower and upper ranges are handled. Also up for question would be how do we handle ranges that attempt to cross this 'barrier' range.
- Do something along the lines of the above, but convert the generated runes to strings before returning them. This would be a little more compatible than the first option, a bit more consistent than the second option, but would still be a significant change from the original implementation.

There are other possible options, but we felt these represented the most likely cases. Some possible concerns raised were:

- We're unsure how useful this kind of feature may end up being if the Unicode character ranges aren't as contiguous as they are for the lower values. None of us have the necessary familiarity with all the Unicode code pages, so ultimately we don't feel this is a huge concern, but nor do we think it's wise to define custom ways for the ranges to work, it would have to stick by the ordering presented by .NET for the contiguous integer values of Runes.
- The formatting system currently doesn't render raw Rune values, instead it defaults to a List format view showing the Rune's properties. This is something we might want as follow up work if this feature is extended in this way. (Rendering them is fairly simple, calling .ToString() on the Runes suffices.)
- The formatting system is not very well set up for rendering these kinds of characters currently, so it may be a little more likely to surface any issues there with how it's designed.

Ultimately, we're unsure if this is something we want to provide in this way as yet. It would be good to see if there's more community interest in this request before we commit to providing this. We're inclined to leave this issue open for discussion for a few months before we assess it again.

---

Since I was playing with it a bit, here's a function that provides similar behaviour that may be of interest to folks who want to play with what this might potentially end up looking like and see how it suits their use cases:

```ps1
function Get-Runes {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [ValidatePattern('^.\.\..$', ErrorMessage = "Invalid format for character range")]
        [string]
        $Range
    )

    $start, $end = $Range -split '\.\.'
    [System.Text.Rune]$startRune = $start.EnumerateRunes() | Select -First 1
    [System.Text.Rune]$endRune = $end.EnumerateRunes() | Select -First 1

    ($startRune.Value)..($endRune.Value) -as [System.Text.Rune[]]
}
```
