### ISSUE TITLE
Support running a native command with alternate output encoding

### ISSUE THREAD

**Issue by segevfiner** [PowerShell/PowerShell#16868]
### Summary of the new feature / enhancement

Powershell currently defaults to the console output encoding when running a native command. ([NativeCommandProcessor.cs:1330](https://github.com/PowerShell/PowerShell/blob/186d6be47d858460a3d0ba6abd81f779cb633b55/src/System.Management.Automation/engine/NativeCommandProcessor.cs#L1330)). This is the right default for most programs, but some software chooses to output a different encoding instead (Most commonly UTF-8). e.g. Rust programs, or programs that use [`activeCodePage`](https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#activeCodePage) in their manifest.

The problem is that there is no way to specify an alternate encoding using Powershell syntax. This leads to either having to temporarily change `[Console]::OutputEncoding`, or to run the process using the .NET `Process` class directly: [starship/src/init/starship.ps1:26-65](https://github.com/starship/starship/blob/e6a921b5b2a54ffd81368f9b3a573e49b5af1c9a/src/init/starship.ps1#L26-L65).

It would help if there was a builtin way to do this concisely.

### Proposed technical implementation details (optional)

Either a parameter to some cmdlet (`Start-Process`? Not sure if that one allows reading output, not to a file, though... ) that allows setting the `StandardOutputEncoding`). Or some new syntax for it, such as a special cast.

**Comment by kasini3000** [comment]
## Proposed technical implementation details (optional) 
My addition:
1 Never use $OutputEncoding
2 Add a new command:
xxx | convertfrom-encoding 936
3 Preferably a third-party module command so that powershellv5 can also be used.
4 It must enter a -command_output_encoding parameter, specifying the encoding of the output. It converts the encoding to ps default. For psv5 it is the default encoding, for powershell v7 it is utf8

**Comment by kasini3000** [comment]
## Proposed technical implementation details (optional) 
My addition:
1 Never use $OutputEncoding
2 Add a new command:
xxx | convertfrom-encoding 936
3 Preferably a third-party module command so that powershellv5 can also be used.
4 It must enter a -command_output_encoding parameter, specifying the encoding of the output. It converts the encoding to ps default. For psv5 it is the default encoding, for powershell v7 it is utf8

**Comment by segevfiner** [comment]
Trying to convert output that has been misinterpreted as a different encoding is likely not to produce correct results unless the wrong encoding uses a specialized error strategy meant to preserve bytes it cannot understand, e.g. It can be reversed.

**Comment by mklement0** [comment]
Great idea; see also:

* https://github.com/PowerShell/PowerShell/issues/15123#issuecomment-810550355

The linked comment points to a Gist with a custom `Invoke-WithEncoding` function that can serve as a stopgap; it runs a given script block with a given encoding temporarily in place.

Making PowerShell ship with such a cmdlet would address the issue at hand for direct invocation (synchronous execution in the same console window, with the child process' standard streams connected to PowerShell's).

Adding an `-Encoding` parameter to `Start-Process` would be helpful too, for launching console applications in a new console window (supported on Windows only; a less common scenario in general).
