### ISSUE TITLE
ThrottleLimit not respected by ForEach-Object $SCRIPTBLOCK -Parallel -InputObject $INPUTOBJECT -ThrottleLimit 8 -AsJob

### ISSUE THREAD

**Issue by penalvch** [PowerShell/PowerShell#16898]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing a problem with ForEach-Object Parallel where -ThrottleLimit is not respected as documented at:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/foreach-object?view=powershell-7.2

Utilizng the below psuedo code where the number of objects in $results_r is 1000, the number of Running jobs is 1000 (i.e. not possible?!):
```
$scriptpath_r='c:\scripts'
$datadict_r=New-Object 'System.Collections.Generic.Dictionary[String,object]'
$null=$datadict_r.add('$filehashes_r',$filehashes_r)
$null=$datadict_r.add('$scriptpath_r',$scriptpath_r)
$process_r=[scriptblock]::create((get-content "$scriptpath_r\gp-process.ps1" -raw))
for($i_r=0;$i_r -lt $results_r.count;$i_r++){
    $datadict_r['$i_r']=$i_r
    $null=foreach-object -parallel $process_r -inputobject $datadict_r -throttlelimit 8 -AsJob
}
do{
    $null=start-sleep -s 2
    $gj_r=get-job
    $gjc_r=($gj_r | where-object {$_.State -eq 'Running'}).count
    $null=$gj_r | where-object {$_.State -eq 'Completed' -or $_.State -eq 'Failed'} | remove-job
    write-host $gjc_r
}while($gjc_r -gt 0)
```

As a clunky workaround, I put the following inside the for loop:
```
do{
    $null=start-sleep -m 500
}while((get-job -State Running).count -gt 8)
```

### Expected behavior

```console
What is expected is that setting -ThrottleLimit 8 causes the number of Running jobs to never exceed 8.
```

### Actual behavior

```console
What happens instead is that the number of Running jobs is equal to the maximum number of iterations of the for loop.
```

### Error details

```console
N/A
```

### Environment data

```powershell
$psversiontable


Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
I believe this is a misunderstood question.
-ThrottleLimit 8 refers to the number of pipes processed concurrently by the foreach-object command. instead of the maximum number of jobs to run simultaneously.


--------------------
Welcome to try the powershell batch operation and maintenance framework I developed

[kasini3000](https://gitee.com/chuanjiao10/kasini3000)    
win,linux devops automation batch script framework.(It is similar to Puppet，Ansible，pipeline) 
Open source, free, cross-platform 
English manual: https://gitee.com/chuanjiao10/kasini3000/blob/master/docs/kasini3000_manual.xlsx

[kasini3000_agent_linux](https://gitee.com/chuanjiao10/kasini3000_agent_linux) Shell script,one click install powershell on linux,modify sshd_config for PsRemote.

2 Multi-process batch execution. default timeout:30min max:10day max-process:99,change from create user_config.ps1
k-commit.ps1 -ip 1.1.1.1 -scriptblock {command_on_node} -allparameter $a,$b
k-commit.ps1 -ip 1.1.1.1 -file 'd:\script_file_on_master.ps1' -allparameter $a,$b
./kt.ps1 #table
./kl.ps1 #list

3 Multi-thread batch execution. default timeout:10min max:1hour max-threaded:50per process,no max limit.change from create user_config.ps1 #need powershell module poshrsjob
k-commit-rs.ps1 -ip 1.1.1.1 -scriptblock {command_on_node} -allparameter $a,$b
k-commit-rs.ps1 -ip 1.1.1.1 -file 'd:\script_file_on_master.ps1' -allparameter $a,$b 
./kt-rs.ps1 #table
./kl-rs.ps1 #list
./kt-rs -ip '192.168.168.223' #select ip from sqlite 
./kt-rs -remark 'xxx' 
./kt-rs -begin_time '2021-11-11 15:05:01' 
./kt-rs -end_time '2021-11-11 16:05:01'

**Comment by penalvch** [comment]
@kasini3000, thanks for the comment. Another datapoint that also leads to my original expectation:
https://devblogs.microsoft.com/powershell/powershell-foreach-object-parallel-feature/ 

"The -ThrottleLimit parameter limits the number of script blocks running in parallel at a given time..."

"The primary addition is the ability to limit the number of concurrent scripts running at a given time with the -ThrottleLimit parameter. Throttling is accomplished by a PSTaskPool class that holds running tasks (running scripts), and has a settable size limit which is set to the throttle limit value. An Add method allows tasks to be added to the pool, but if it is full then the method blocks until a new slot becomes available."

Given this, if one sets the ThrottleLimit, one naturally expects to see no more than that number of jobs in the Running state as per get-job.

Regarding your suggested workarounds, the PWSH workaround provided in my original comment is highly preferred over the two suggestions you provided as:
1) It's OS agnostic.
2) Stalling for 5 seconds to run each iteration leads to longer then necessary script exection. Even doing 1 second stalling as I originally provided ended up being to high in comparison to 500 ms. Going from 500 ms to 250 ms does provide modest execution time gains, but at high CPU utilization in comparison to 500ms+.

Thanks anyways!

**Comment by jhoneill** [comment]
> "The -ThrottleLimit parameter limits the number of script blocks running in parallel at a given time..."

I think you have confused script blocks and jobs.  This
```
 $null=foreach-object -parallel $process_r -inputobject $datadict_r -throttlelimit 8 
```

 **does not run** `process_r`   for each object in `$datadict_r`  with up to 8 copies running concurrently. 
It runs ONE copy of `process_r` which receives the whole of  `$datadict_r` 

Specifying `-AsJob` sends it off to run as a job. 

Something like this 
```
1..32 | ForEach-Object -Parallel { sleep 10 ; "$_  " + [datetime]::Now.ToString() }  -AsJob -ThrottleLimit 8
```
creates a job with 32 script blocks to run, run in parallel, 8 at a time. 

```
foreach ($i in 1..10) {
1..32 | ForEach-Object -Parallel { sleep 10 ; "$_  " + [datetime]::Now.ToString() }  -AsJob -ThrottleLimit 8
}
```
Creates 10 jobs, each of which has 32 script blocks to run, run in parallel, 8 at a time.  Giving 80 concurrent script blocks/threads,

The text you quoted is misleading because it does not say **"in that instance of for each parallel**"  you can probably imagine it is difficult for `foreach` in one job to know if `foreach` is running in other jobs and how many threads are being used when it is.

**Comment by penalvch** [comment]
@jhoneill, thanks for the comment. While I didn't confuse script blocks or jobs, the text quoted appears the source of confusion. 

Hence, it would be helpful for PWSH users if https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/foreach-object?view=powershell-7.2 is updated to clarify it does not throttle creation of jobs or something like that.
