### ISSUE TITLE
PS 7 for Windows 11 ARM?

### ISSUE THREAD

**Issue by rstolpe** [PowerShell/PowerShell#16913]
### Summary of the new feature / enhancement

Supported version of PS 7 to Windows 11 ARM

**Comment by iSazonov** [comment]
There is already Windows ARM distributive. Have you any problems with it?

**Comment by iSazonov** [comment]
Ah, you ask about ARM32. PowerShell 7 follows .Net support https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md. Current public .Net 6.0 hasn't ARM32 support on Windows.

**Comment by MartinGC94** [comment]
No I think he is asking about 64 bit ARM, he just can't find it because the table on the readme page doesn't have them.  
@rstolpe you need to look under releases: https://github.com/PowerShell/PowerShell/releases you can find all download links under "assets" under each release. Look for `win-arm64.zip` to find it.

**Comment by adityapatwardhan** [comment]
They are listed lower down in the third table:

![image](https://user-images.githubusercontent.com/12820925/155895255-b427dcb6-8257-4470-8853-c24c057f5e13.png)
