### ISSUE TITLE
Standardized context for PowerShell

### ISSUE THREAD

**Issue by Tarjei-stavanger** [PowerShell/PowerShell#16938]
### Summary of the new feature / enhancement

I want my and other PowerShell script to not be dependent on the current culture that the user is using. Frankly, it also applies to my CMD scripts as well.

**Examples** 
With the local culture being "nb-NO".
The local "Administrators" group is called "Administratorer" and that applies to scripts as well.
The Firewall display group "Remote Desktop" is "Eksternt Skrivebord".

It would be nice to have a way of indicating that a script should be run in a standard environment where the local culture names don't apply.

I think such an environment should have the date as standard being YYYY-MM-DD. Such dates are instantly sortable right out of the box.

Having exceptions opens a can of worms. It might be better to be able to specify culture for human readable output. 

$fishNumber = $fishNumber.Culture( Get-Culture );

### Proposed technical implementation details (optional)

I think that a standardized environment should be dependent on a statement. Either included with the current culture settings or as a statement.

e.g. Set-Script-Culture  'PS-standard';  ( As a matter of principle I would prefer Script-Culture-Set  'PS-Standard' )

**Comment by jhoneill** [comment]
`Get-Culture "" ` 
Returns the "Invariant" culture, which is mostly  US English with stupid least significant in the middle dates, but with 24 clock instead of 12 hour.
In your profile or in a script you can put 
```
[System.Threading.Thread]::CurrentThread.CurrentCulture = Get-Culture ""
```
To make it use that culture or 
```
[System.Threading.Thread]::CurrentThread.CurrentCulture = Get-Culture "nb-NO"
```
To be consistently Norwegian

**Comment by MartinGC94** [comment]
This is a Windows problem not a PowerShell problem. Local users/groups have their real name changed in localized versions of Windows, that's why even if you install an English language pack the group names keep their localized name. If you want to do something with the built-in groups you need to use their wellknown SIDs. This also prevents you from running into issues on systems where people have manually renamed the groups/users.  
As for the firewall displayname, I think it uses the MUI files for the current language to get the name and even if you could force it to use English, you would still need to actually install those language files.

**Comment by iSazonov** [comment]
As @MartinGC94 said it is how Windows works. It is impossible to change this in PowerShell and in any application. For well-known group and account names you could use workarounds like using SID.

**Comment by jhoneill** [comment]
>  it is how Windows works. It is impossible to change this in PowerShell and in any application. 

> Just because the problem originates in Windows does not mean that it is not a PowerShell problem.

It is problem which **affects** PowerShell. It is not a problem where the solution is in PowerShell's hands.  

@iSazonov  there is an issue with script portability,  because so much PowerShell is created on Windows in an English version (and we have "Time zone for the clock", "country you're in", "Language to speak to you with", "how your data should be formatted" as subtly different things) , some shared code won't use language independent names. 
The OP is probably going to write better scripts knowing that most of the world doesn't use "Eksternt Skrivebord" but authors working in English assume "Remote Desktop" is universal. That's a problem for the broader ecosystem, but not something PowerShell itself can fix.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Is somebody able to forward this to the developers of Windows?
