### ISSUE TITLE
Unexepected behavior evaluating statements in comma-based list literals

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#17128]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
$a, $b = 0,1; $a; $b
"---"
$a, $b = $true, $false; $a; $b
"---"
$a, $b = 0,1+1; $a; $b
"---"
$a, $b = 0,1*2; $a; $b
"---"
$a, $b = 0,2*5-1; $a; $b
"---"
$a, $b = @(
    0,
    2*5-1
)
$a; $b
"---"
$a, $b = @(
    0
    2*5-1
)
$a; $b
```

### Expected behavior

```console
0
1
---
True
False
---
0
2
---
0
2
---
0
9
---
0
9
---
0
9
```

### Actual behavior

```console
0
1
---
True
False
---
0
1
1
---
0
1
0
1
---
InvalidOperation: C:\temp\literalissue.ps1:9:1
Line |
   9 |  $a, $b = 0,2*5-1; $a; $b
     |  ~~~~~~~~~~~~~~~~
     | Method invocation failed because [System.Object[]] does not contain a method named 'op_Subtraction'.

0
1
0
1
---
InvalidOperation: C:\temp\literalissue.ps1:11:1
Line |
  11 |  $a, $b = @(
     |  ~~~~~~~~~~~
     | Method invocation failed because [System.Object[]] does not contain a method named 'op_Subtraction'.

0
1
0
1
---
0
9
```

### Error details

```console
Exception             : 
    Type        : System.Management.Automation.RuntimeException
    ErrorRecord : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Method invocation failed because [System.Object[]] does not contain a method named 'op_Subtraction'.
            HResult : -2146233087
        TargetObject          : op_Subtraction
        CategoryInfo          : InvalidOperation: (op_Subtraction:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : MethodNotFound
        InvocationInfo        : 
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : -1
            Line             : $a, $b = 0,2*5-1; $a; $b
            PositionMessage  : At line:1 char:1
                               + $a, $b = 0,2*5-1; $a; $b
                               + ~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite  : 
        Name          : CallMethod
        DeclaringType : System.Management.Automation.ParserOps, System.Management.Automation, Version=7.2.2.500, Culture=neutral,       
PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : Method invocation failed because [System.Object[]] does not contain a method named 'op_Subtraction'.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  : 
   at System.Management.Automation.ParserOps.CallMethod(IScriptExtent errorPosition, Object target, String methodName, 
PSMethodInvocationConstraints invocationConstraints, Object[] paramArray, Boolean callStatic, Object valueToSet)
   at System.Management.Automation.ParserOps.ImplicitOp(Object lval, Object rval, String op, IScriptExtent errorPosition, String        
errorOp)
   at CallSite.Target(Closure , CallSite , Object , Int32 )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : op_Subtraction
CategoryInfo          : InvalidOperation: (op_Subtraction:String) [], RuntimeException
FullyQualifiedErrorId : MethodNotFound
InvocationInfo        : 
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : $a, $b = 0,2*5-1; $a; $b
    PositionMessage  : At line:1 char:1
                       + $a, $b = 0,2*5-1; $a; $b
                       + ~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
Exception             : 
    Type        : System.Management.Automation.RuntimeException
    ErrorRecord : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Method invocation failed because [System.Object[]] does not contain a method named 'op_Subtraction'.
            HResult : -2146233087
        TargetObject          : op_Subtraction
        CategoryInfo          : InvalidOperation: (op_Subtraction:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : MethodNotFound
        InvocationInfo        : 
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : -1
            Line             : $a, $b = @(

            PositionMessage  : At line:1 char:1
                               + $a, $b = @(
                               + ~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite  : 
        Name          : CallMethod
        DeclaringType : System.Management.Automation.ParserOps, System.Management.Automation, Version=7.2.2.500, Culture=neutral,       
PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : Method invocation failed because [System.Object[]] does not contain a method named 'op_Subtraction'.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  : 
   at System.Management.Automation.ParserOps.CallMethod(IScriptExtent errorPosition, Object target, String methodName,
PSMethodInvocationConstraints invocationConstraints, Object[] paramArray, Boolean callStatic, Object valueToSet)
   at System.Management.Automation.ParserOps.ImplicitOp(Object lval, Object rval, String op, IScriptExtent errorPosition, String        
errorOp)
   at CallSite.Target(Closure , CallSite , Object , Int32 )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : op_Subtraction
CategoryInfo          : InvalidOperation: (op_Subtraction:String) [], RuntimeException
FullyQualifiedErrorId : MethodNotFound
InvocationInfo        : 
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : $a, $b = @(

    PositionMessage  : At line:1 char:1
                       + $a, $b = @(
                       + ~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
Comma is evaluated before arithmetic operators  (+ and * also have string and array functions obviously) 

so `1,2 + 3`  is `@(1,2) + 3`   i.e.` @(1,2,3)`
and `0,2*5-1` is `(@(0,2) * 5) - 1`  which becomes ` @(0,2,  0,2, 0,2,  0,2,  0,2)  -1 `  - and you can't subtract from an array. 
    

I was writing this up recently (copy/paste  )
1.	.Members and ::StaticMembers
2.	[Type Casting]
3.	Array operations
4.	Arithmetic
5.	Text operators (-f [format], -join, -split, -match and -replace )
6.	Bitwise operators ( -band, -bor, -bxor, -bnot )
7.	Type operators ( -is, -isnot, -as )
8.	Comparison operators ( -eq, -ne, -gt, -lt, -le, -ge )
9.	Logical operators ( -and, -or, -xor, -not, ! )
10.	Assignment operators	(=, +=, -=, *=, /=, %=)
11.	Redirection operators	(>, >>, 2>, 2>, 2>&1 etc)

**Comment by vexx32** [comment]
Yeah, I think this is documented in the precedence article: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operator_precedence?view=powershell-7.2#long-description

Might be a good idea to also document some of the sometimes surprising consequences of operator precedence.

**Comment by markekraus** [comment]
To be clear, I am well aware of the precedence, but I do not think this is intended or good behavior at all. Especially since this makes PowerShell behave completely unlike any other language that does something similar.

**Comment by vexx32** [comment]
Aye, I can't say I disagree with that assessment, PowerShell's operator precedence can be quite unintuitive at times compared to many other languages.

**Comment by jhoneill** [comment]
> To be clear, I am well aware of the precedence, but I do not think this is intended or good behavior at all. Especially since this makes PowerShell behave completely unlike any other language that does something similar.

The original title, and the examples you posted didn't suggest an awareness of the precedence: it hasn't  changed over 15 years of PowerShell, so it's fairly safe to say it is the designers intended.  And I'll defer to _their_ knowledge on other languages, (I have 40 years experience but I've forgotten most of what I knew most of the score of languages I've used.) Like it or hate it , agree with their reasoning or not, it's too deeply embedded to change it.  

When + is used for both string and array concatenation and for providing the sum of two values, there is inevitably going to be a question of what, for example,  "A", "B" + "C", "D"   should do - does **+** combine two arrays to make a 4 element array, or does it  combine two strings giving a 3 element array with "BC" as the middle element? I don't think that is obvious which and would always put `@("A","B")  + @("C","D")` or `"A", ("B" + "C"), "D",`  although only the latter version is required. 
To be honest I when someone says, "What I want to write needs () in it and I think the what I didn't want to write should be the version that needs them" it never gets anywhere.

**Comment by dnnyg** [comment]
Kind of a funny situation isn’t it?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by markekraus** [comment]
> it hasn't changed over 15 years of PowerShell, so it's fairly safe to say it is as the designers intended.

As someone who has done extensive contributions to PowerShell, I can say this is _not_ a safe assumption. :)

> Like it or hate it , agree with their reasoning or not, it's too deeply embedded to change it.

This is also not true per my experience contributing to the language. :)

**Comment by jhoneill** [comment]
@markekraus  for all the "Don't you know who I am", two facts remain.
(1) You posted under the title "unexpected behavior..."  and in the "Expected" you said that expected `0,1 + 1` to be `0, (1+1)` and `0,1 *2` to be `0,(1*2)` when PowerShell has always treated them as `(0,1) + 1` , and  `(0,1) *2` 
And when it PowerShell's longstanding behaviour was pointed out you said you were well aware of the order of precedence ... aware of it, and yet it is unexpected ? 
If you wanted to start a discussion with "PowerShell's order of precedence is, and always has been, wrong" that would be another matter...

(2)  Array membership is processed before array / string concatenation or arithmetic addition, because in 2005 or 2006 Payette, Truher, et al would have decided that was the way to do to implement it and not through some accident which has been overlooked for the last 15 years. 

What I meant by _too embedded to change_ is precedence is fairly fundamental, and changing it will break an unknowable number of scripts.

I'm guessing you think this is wrong too
```
PS > [string]5 * 4 
5555
```
Surely arithmetic should be done first and it should be a string contain "20" not "5" repeated 4  times, so making this stuff "right" requires quite a big reshuffle and there's too much breakage to just to save you an unexpected set of ()

**Comment by markekraus** [comment]
@jhoneill I think this is getting unproductive. I will attempt to bring this back to the intent of my post, and I ask that you do the same.

I'm challenging that this is _not_ intended behavior regardless of how long it has been this way. I'm basing this on one of the examples I provided not matching the others:

```powershell
$a, $b = @(
    0,
    2*5-1
)
$a; $b

$a, $b = @(
    0
    2*5-1
)
$a; $b
```
Those _should_, (in my opinion informed by exposure to many programming languages that offer similar functionality) be the same and _should_ (in my opinion informed by exposure to many programming languages that offer similar functionality) provide the result:

```text
0
9
0
9
```

Anyone new to PowerShell would have a reasonable expectation (in my opinion informed by exposure to many programming languages that offer similar functionality) that `2*5-1` would be evaluated before being inserted into the array and _would not_ have a reasonable expectation  (in my opinion informed by exposure to many programming languages that offer similar functionality) that it would be treated as performing duplication and attempted subtraction of an array.

This language can and has changed and evolved. Breaking changes with significant consequences can and have been made regardless of the effort. I do not wish to surrender to argumentum ad antiquitatem and appeals to complexity. I wish to improve the language so that users (new and experienced) can fall into puts of success.

In the best-case scenario, this behavior _is_ changed to be more user-friendly and intuitive. At worse, the documentation will be updated to reflect this behavior more clearly.

**Comment by jhoneill** [comment]
I'm not sure how well you understand the role of @() , and line break. 
Try, 
```
$x =  @(
hostname
whoami
$psversiontable.
 os
)
```
Notice there is a a line break between  the member operator and the member name.   Like other operators the  ,  can be followed by LF or CR/LF 

Your example 
```
$a, $b = @(
    0,
    2*5-1
)
```
Shows that you can insert line breaks into  `@(0, 2*5-1 )`   (Where, incidentally the `@()`  is redundant) it doesn't matter whether you write `4,3*2+1` OR 
```
4,
3*
2+
1 
```
They are the same statement with different white space.  And without the comma
```
    0
    2*5-1
``` 
Are two values  which become an array by wrapping in `@().`  My example  won't work as `$x = hostname, whoami` : to remove the line break between the statements needs a semi-colon - a comma would cause an error. 

**You're saying that**  `0,1*2`  **and** `@(0;1*2)`  **should arrive at the same result** - the former by how it groups one expression and the latter by processing two expressions.  That's not how it works, but it isn't an unreasonable thing to believe. 
 
We can trade years of experience and number of languages used. TBH most of the languages I've used didn't treat a comma separated list without any begin/end markers as an array. And back when I did my computer science degree we were taught that overloaded operators were bad, so+ should not be _both_ concatenation and arithmetic.  Given that 1,2,3,4 -gt 2 applies the greater than operator to all 4 array members,  my computer science lecturers would probably say 1,2,3,4  + 5 should return 6,7,8,9.  And the chances of _that_ change ever being made would be Zero.  
 
Off the top of my head I can't say which languages treat `0,1*2` ,  `(0,1) * 2` and `0, (1*2)` all as legal ways to get an array/list/set.  What someone coming to PowerShell _expects_ would be shaped by other languages they have used, so I wouldn't like to say what the _most common_ expectation is. As above I think there are multiple expectations which are reasonable, but only one can be what actually happens. And I'm not sure even  PowerShell experts would always correctly predict the result of
```
"A" + "B", "C" -join "D" + "E"
```
The 4 operations can arranged in 24 sequences (4!)  all are possible: whether you want    
`((("A" + "B"), "C") -join "D") + "E"`     
or `"A" + ("B", "C" -join ("D" + "E"))`       
or `("A" + ("B","C")) -Join ("D" +"E) `      
you can write it that way and _even if the way you want happens to be default_ I would say you should include the brackets for clarity  

The more time that passes with the language working one way, the more scripts there are which depend on that way of working and the greater the cost of changing. Your not talking about a change which would stop scripts running in all affected cases, but one that can result in different data being modified / deleted on  different versions of PowerShell. It would lead to "Upgrading to  Version X corrupted our data" experiences when what you see as wrong is (a) by design and (b) fixed by putting () in the right place.

**Comment by doctordns** [comment]
While I understand the issue,  I am not sure it is one that needs fixing. The time for that discussion would have been pre Powershell 2. We have managed so far with the current behaviour I am nervous at potential for breaking existing scripts.  So I am reluctant to want to 'fix' this.

And a second point. The original problematic code is rather obscure and in my view not appropriate in production code.  I'd argue such code be made clearer than to try to change powershell. :-) Mileage probably varies on that point.

**Comment by markekraus** [comment]
Closing this issue as I don't care enough to continuously fight against "this is how it's always been" and "this could be hard."

I still think this is worth fixing to make it easier for people new to PowerShell and more symmetrical with other PowerShell language features. But some people in this thread make it inhospitable to watch this issue and provide feedback.

To the current collaborators and maintainers of this project: this unwelcoming behavior is problematic, and I hope you can improve the experience for others.
