### ISSUE TITLE
PWSH -settingsFile argument does not have an impact on the $env:PSModulePath variable

### ISSUE THREAD

**Issue by sdg002** [PowerShell/PowerShell#17243]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

# Create a custom settings file

- Use the folder `c:\users\<currentuser>\demo1`
- Name the file `demo.config.json`
- The contents should be as follows:
```
{
  "PSModulePath": "C:\\Program Files\\PowerShell\\6\\Modules;c:\\blah"
}
```
- Save the file

# Launch PWSH with -settingsFile

- Launch a new CMD
- For the purpose of reference, print the value of the environment variable by typing `echo %PSModulePath%`
- This will display the value of the environment variable `PSModulePath`
- Run the command `pwsh -settingsFile c:\users\<currentuser>\demo1\demo.config.json`
- Now examine the value of the environment variable by typing `$env:PSModulePath`
- 

### Expected behavior

```console
The environment variable `PSModulePath` should take the value specified in the file `demo.config.json`
```

### Actual behavior

```console
The environment variable `PSModulePath` retains most of the original value.
```

### Error details

```console
My objective was to override the environment variable $PSModulePath as much as possible by using a settings file.  I wanted to bypass `c:\users\<currentuser>\documents\PowerShell\Modules` completely.
This was not met.  I was following the documentation [documentation here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_config?view=powershell-7.2) 

The documentation on the `settingsFile` needs clarity on the extent of overriding that can be carried out by using the `-settingsFile` argument. If there are caveats then those should be clearly documented.
```

### Environment data

```powershell
Windows 10
PowerShell core 7.1.3
```

### Visuals

Contents of my config file:

![image](https://user-images.githubusercontent.com/20245330/166246184-179e66aa-50b9-463b-8c15-b9447930a849.png)

**Comment by fMichaleczek** [comment]
@sdg002 The documentation said "<ps-module-path> is the absolute path to a module directory". You had specified 2 paths in your configuration. Could you try again with only one path to verify it's working as expected ? Then you should ask to support more than one path.

**Comment by jhoneill** [comment]
> My objective was to override the environment variable $PSModulePath as much as possible by using a settings file.  I wanted to bypass `c:\users\<currentuser>\documents\PowerShell\Modules` completely.
> This was not met.  I was following the documentation [documentation here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_config?view=powershell-7.2) 
> The documentation on the `settingsFile` needs clarity on the extent of overriding that can be carried out by using the `-settingsFile` argument. If there are caveats then those should be clearly documented.

The settings file adds to the values, rather than replacing them 
On a clean system I get `echo %psmodulepath%`  in cmd shows   
`C:\Program Files\WindowsPowerShell\Modules;`    
`C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules ` 

When I start PowerShell 7, it prepends 3 directories. 
`<userProfile> \Documents\PowerShell\Modules`   
`C:\Program Files\PowerShell\Modules`   
`<install dir> \Modules`   

Adding a directory in the settings file adds it after these 3 but before the existing 2.  With more than one directory both were added _in reverse order_

The documentation says 
>  **Overrides** the PSModulePath settings for this PowerShell session. If the configuration is for the current user, sets the CurrentUser module path. If the configuration is for all users, sets the AllUsers module path.

There have been other cases where people have said PSModulePath is not doing what they expect. **Override** in the docs suggests either the setting in the file replaces, or at least has higher priority than, the setting added by pwsh. The behaviour and docs don't match. The behaviour may be as intended (meaning the docs need an update and possibly a feature request for something different), or there may one or more bugs

**Comment by JustinGrote** [comment]
Related, @fMichaleczek or @SeeminglyScience is the CurrentUser module path exposed anywhere for modules to consume?

Scenario: I want to use this config to cease the use of $HOME/Documents/PowerShell/Modules as a path in Windows, because OneDrive syncs that in an undesirable manner. However, today, there's no way to explicitly detect that the default currentuser path was changed, only "best guess" parsing of $ENV:PSModulePath. Therefore, install tools (PSGetv2 and PSGetv3) still install to what appears to be this hardcoded Documents path, rather than it being configurable.
