### ISSUE TITLE
ExecutionPolicy cannot be modified with PowerShell 7.2.2 / 7.2.3

### ISSUE THREAD

**Issue by griesi007** [PowerShell/PowerShell#17242]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Modifying ExecutionPolicy with PowerShell 7.2.2 does not work correctly. When I set ExecutionPolicy to Unrestricted using "Set-ExecutionPolicy Unrestricted" the RegistrySetting Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell\ExecutionPolicy is still set to "Restricted", even after refreshing / rebooting and all ps scripts are blocked. When checking with Get-ExecutionPolicy -List the result is "Unrestricted" for local maching and undefined for all other scopes, so obviously the setting is somehow set but does not have any effect

When I do the same using PowerShell 5.1 everything works as expected. 

Also when running Get-ExecutionPolicy -List in both versions different results are displayed

![Screenshot 2022-05-02 115035](https://user-images.githubusercontent.com/2854973/166216231-2b35a68c-3960-4e93-a281-01b729894e96.png)

### Expected behavior

```console
PowerShell 7.2.2 should identically work as PowerShell 5 when modifying/Listing ExecutionPolicy
```

### Actual behavior

```console
PowerShell 7.2.2 not modifies ExecutionPolicy correctly
```

### Environment data

```powershell
Windows 10 Professional 19043, Single unmanaged Workstation (not part of a domain or AD)

Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

https://user-images.githubusercontent.com/2854973/166218680-bfb3b0a5-290e-4b54-b665-15d3ea0b05da.mp4

**Comment by jborean93** [comment]
How did you install pwsh? If it was through the Windows Store then I believe this is a known problem https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2#installing-from-the-microsoft-store

A UWP application has a virtualized registry hive and some registry hives, like HKLM, are overlayed on top of the actual hive so changes made in pwsh are not applied globally but to that application's "sandbox".

**Comment by griesi007** [comment]
@jborean93 it is installed through winget.

**Comment by jborean93** [comment]
I'm not sure, they seem to have an entry for both msi and msix/appx https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/PowerShell/7.2.3.0/Microsoft.PowerShell.installer.yaml. I have no idea what winget uses to select the package here but this could potentially still apply. The path in the screenshot might indicate you are using just the msi install and my comment doesn't apply though.

**Comment by griesi007** [comment]
@jborean93 winget states it´s using the mix installer https://github.com/PowerShell/PowerShell/releases/download/v7.2.3/PowerShell-7.2.3-win-x64.msi

**Comment by jborean93** [comment]
Awesome, thanks for confirming. Scratch my idea, I'm not sure what is happening with your case sorry.

**Comment by jhoneill** [comment]
I think PowerShell 7 writes the execution Policy to powershell.config.json (machine policy is in the $psHome directory) where Windows PowerShell uses to the registry. 
If I don't have write access to $Pshome I get an error `Access to the path 'C:\Program Files\PowerShell\7\powershell.config.json' is denied.`  if I try to set execution policy for the machine.

**Comment by griesi007** [comment]
@jhoneill of course it must be written to the registry. Anything else would not make any sense

**Comment by jhoneill** [comment]
Maybe someone else will confirm but as I understand it: 5 is windows only, so it uses the registry.  7 being  cross platform _could_ use the registry on windows, but in practice it uses the same settings files on all platforms. 

You're seeing the policy change, but no change in the registry , correct ? Is  the change written to `$pshome\powershell.config.json` ?

**Comment by griesi007** [comment]
@jhoneill yes exactly. But this does not make any practical sense? Which sense does it make for the Set-ExecutionPolicy cmdlet to write into powershell.config.json? In that case Set-ExecutionPolicy cmdlet should either be removed from Powershell 7 or write as expected into the registry. I assumed PowerShell 7 is a replacement for PowerShell 5?

**Comment by jhoneill** [comment]
@griesi007  How would you implement execution policy on Linux ? 

Because it is possible to have multiple side by side installs for PowerShell core it is also possible that a setup demands signed for the default (on-the-path) version and has something different for testing older / pre-release versions. So a file in the the same directory as the executable is a simple way of getting that. 

64 bit and 32 bit Windows PowerShell put these setting in different parts of the registry so execution policy needs to be changed twice to cover both. So there is a precedent for saying two side by side versions do not interfere with each other. 

You're right that there is an argument that on Windows the settings should go under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\6` or  `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\7` but there is an equal and opposite argument different platforms should avoid special behaviours.  That is the argument which minimizes the amount of work for implementation and testing :-)  If the policies work correctly the storage mechanism isn't important.

**Comment by griesi007** [comment]
@jhoneill Yes you are right. But shouldn´t a default Windows install work similar to PowerShell 5 and write to the registry? As the msi package is platform agnostic this could easily be configured there. Also I understand your argument for other use cases. But shouldn´t this be an optional configuration option? Can PowerShell 7 currently be configured to write into the registry similar as PowerShell 5 does? At least the documentation of PowerShell 7 should mention this different behaviour clearly. I assume most people are not aware of the fact that PowerShell 7 foes not write to the registry, so all cmdlets which modify the registry in PowerShell 5 are pretty useless if one uses PowerShell 7 as a replacement for 5.

**Comment by jhoneill** [comment]
The MSI is Windows specific, you can't install it on Linux, and the 64 bit MSI won't work on 32 bit Windows.   (The 32 bit MSI will work on 64 bit Windows and is needed in a few situations). 

6 and 7 on Windows do have registry providers so (on Windows) registry commands still do what they always did.  It is simply a question of where PowerShell reads current user and local machine configuration information from when it starts.  AIUI group policy still supported so a Windows version of PowerShell 7 does read the registry for _some_ execution policy 

A Windows-only app _should_ keep its configuration in the registry, but the new Windows Terminal app uses a JSON file so parts of Microsoft don't follow that rule. The unix world has never had a central configuration store so apps there use various sorts of text file.    
Should a cross-platform app use the registry on Windows or use the same config files everywhere?  The case for either is roughly as strong as the other.  Since we use the cmdlets to view/change the settings we probably shouldn't care very much about how things are stored - such things can change between versions.

**Comment by griesi007** [comment]
@jhoneill I am on Windows and PowerShell 7 registry commands e.g. Set-ExecutionPolicy do not what they always did. As I have shown initially PowerShell 7 does not modify the registry settings in question as it does PowerShell 5. So obviously there is some sort of bug

**Comment by jhoneill** [comment]
@griesi007  

1.  `Set-ExecutionPolicy` was not a "registry command" nor has it become a "file command".  It is a command to set a policy. The implementation changed from storing localmachine and currentuser policies in the registry, to storing them in a JSON files.  
2. To the best of my knowledge using the registry to get or set the execution policy was always in the "works but isn't supported" category - meaning the registry path could change, value names and the data itself could change,  and there was no guarantee the registry would always be used. 
3. PowerShell 7 on Windows has the same ability to work with registry as its predecessors. It just keeps some of its own configuration elsewhere, by design. The PowerShell 7 of some functionality is free to choose not to use the registry, but the ability is still there.

**Comment by griesi007** [comment]
@jhoneill 
1. I am modifying a policy to have any effect. Stroing it in JSON files does not have any effect. So this is pretty useless
2. That´s not true. Alle official MS Documentation refers to the powershell for configuring the ExecutionPolicy, which implies that this modifies the appropriate registry settings. Otherwise it would not have any effect
3. Could you please advise what needs to be configured so PowerShell 7 ExecutionPolicy cmdlet modifies the appropriate registry settings

**Comment by jhoneill** [comment]
> @jhoneill
> 
> 1. I am modifying a policy to have any effect. Storing it in JSON files does not have any effect. So this is pretty useless

**PowerShell 7 reads the JSON and Group Policy Settings**. As you have shown:

-  When you run Set-ExecutionPolicy in 64 bit PowerShell 5 it sets the policy for 64 bit PowerShell 5, but not for 32 bit PowerShell 5 or Powershell 6 and later.  
- When you run Set-ExecutionPolicy in 32 bit PowerShell 5 it sets the policy for 32 bit PowerShell 5, but not for 64 bit PowerShell 5 or Powershell 6 and later.  
- When you run Set-ExecutionPolicy in PowerShell 6 or 7 it sets the policy for that installation of PowerShell 6/7 (there may be more than one). 

At no time has Set-ExecutionPolicy been a global setting for all different versions of PowerShell. 

In PowerShell 5 normal users have read-only access to the Registry key holding the machine setting.    
In PowerShell 6/7 Normal users have read-only access to the JSON file holding the machine setting. 

As the image below shows running Set-Execution policy changes the json. Changing the JSON causes an issue with an untrusted file in PSReadline, and won't load my unsigned profile. **Clearly the policy IS effective.**  

![image](https://user-images.githubusercontent.com/16209593/166689845-6b387e58-03ab-406d-a1cd-fa4e30f40c23.png)

Here's a second screen shot showing that if you edit the JSON the policy changes - and this is PowerShell 6 
![image](https://user-images.githubusercontent.com/16209593/166692508-3acfe148-991d-499f-a824-2a4fd431920a.png)

Note that this is not supported. The text in the JSON might change, the location of the file might change. In version 8 it could be YAML or XML format, or back in the registry.  The only supported way to read or write the policy is with cmdlet for that version of PowerShell. 

> 2. That´s not true. All official MS Documentation refers to the powershell for configuring the ExecutionPolicy, which implies that this modifies the appropriate registry settings and that this is supported. Otherwise it would not have any effect

All official documentation  that I am aware of **refers to the `set-ExcutionPolicy` cmdlet.** Which sets the policy (via json) for 6/7 and via registry for 5 and earlier. I'm pretty sure there is no official advice to use `reg.exe  <something>` to set set a policy by merging in a .REG file, nor to run `regedit` and navigate to `HKLM:\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell\ExecutionPolicy`,     
nor to use `Get-ItemProperty hklm:\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell -name ExecutionPolicy`  
but if you know different please share. 

There **is** an error in the on-line help which still says the policy is stored in the registry, but does not give a path or recommend accessing the registry directly. 

> 3. Could you please advise what needs to be configured so PowerShell 7 ExecutionPolicy cmdlet modifies the appropriate registry settings

**PowerShell 7 doesn't get its execution policy from the registry but from a JSON file.**  there is no "appropriate registry setting" for execution policy in PS 7.   If the cmdlet changed a registry setting pwsh.exe would still look at the JSON not the registry.  You can hack the registry for the PowerShell 5 policy setting from PowerShell 7 (e.g. with` Set-ItemProperty`)  I don't know how many different ways I can put that.

**Comment by griesi007** [comment]
@jhoneill Thanks for clarifying this. My misconception was, that ExecutionPolicy is a global system wide setting. But in fact it is a PowerShell specific setting, which must be configured in each PowerShell used. You can close the issue

**Comment by jhoneill** [comment]
@griesi007  - you're welcome.  You're not the first to have that misconception, and I'm sure you won't be the last.
