### ISSUE TITLE
Please add support for x509 SSH certificates 

### ISSUE THREAD

**Issue by queglay** [PowerShell/PowerShell#17286]
### Summary of the new feature / enhancement

Currently I believe ssh in Powershell only supports SSH public key identification, but all the projects I work on use X509 SSH Certificates.

I'd really like to use Powershell more but without this ability its not possible for me to transition towards it, I'd love to see this feature implemented.

**Comment by PaulHigin** [comment]
@WG-Remoting
This is a good enhancement, but not a high priority.  Because resources for new features is limited, we feel this may be a good time for the community to take advantage of the recent [Custom Remote Connections](https://github.com/PowerShell/PowerShell-RFC/blob/master/Archive/Draft/RFC0063-Custom-Remote-Connections.md).  

The community could create a new custom remote connection module, for SSH connections, that supports more desired SSH features, such as certificate authentication.

**Comment by PaulHigin** [comment]
@WG-Remoting
We are marking this feature request as 'Resolution-Declined' because we feel the enhancement can be created externally from the PowerShell code base, using custom remote connections as mentioned above.
