### ISSUE TITLE
Programmatically configure serialization rehydration

### ISSUE THREAD

**Issue by ssteiner** [PowerShell/PowerShell#17300]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm working with the MicrosofTeams PS Module v4.3.0.
My software is using the PS SDK 7.2.2 to send commands to configure MS Teams, e.g. managing a users calling settings. So one command I'd like to run using the SDK is this

`[Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.ICallGroupMembershipDetails[]]$gmd = @(
	[Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.ICallGroupMembershipDetails]@{CallGroupOwnerId='user20@contoso.com';NotificationSetting='Banner'}
	[Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.ICallGroupMembershipDetails]@{CallGroupOwnerId='user30@contoso.com';NotificationSetting='Mute'}
)
Set-CsUserCallingSettings -Identity user10@contoso.com -GroupMembershipDetails $gmd`

Now, if I run this in the SDK, instead of the real object with type `Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.ICallGroupMembershipDetails` I'm getting a generated object. 

Is there a way to programmatically configure the `PSTypeSerializer` to get me the right object? So something along [these lines](https://devblogs.microsoft.com/powershell/how-objects-are-sent-to-and-from-remote-sessions/) but doing it programmatically so that the runspaces I'm opening with the PS SDK will get me the `Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.ICallGroupMembershipDetails` filled out

### Expected behavior

```console
(Get-CsUserCallingSettings -Identity user4@contoso.com).GroupMembershipDetails
gets me an array of `Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.ICallGroupMembershipDetails`
```

### Actual behavior

```console
(Get-CsUserCallingSettings -Identity user4@contoso.com).GroupMembershipDetails

gets me an array of `Deserialized.Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.ICallGroupMembershipDetails`
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
It's not clear if you're using remoting, or if this is a result of putting things in different runspaces on the same machine. 

Serialization has two benefits - firstly if you call a remote server which has the components installed to recognized a `[Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.ICallGroupMembershipDetails]` object from a machine that does not, the Deserialized object is understood rather than causing an error.  And secondly even if the object type is understood, the caller does not have the session that was used to get the object so it can't (reliably) do something like "get this object's parent", or "modify this object" because those expect to be run in the same context as the object was fetched. Something like export-clixml / import-clixml will rehydrate as the same type of object but that isn't possible for every type of object - you need the equivalent of `New-Object  -property @{names=values}  ` (some properties are read-only, and some objects can't be conjured up with New-object) . 

You haven't said what problem being serialized is causing, but the initial frustration is usually "I got a widget _there_ and I want to to call it's "foo" method _here_ but the method has gone in the serialization process". Whilst that is the symptom, the foo method often wouldn't work, even if widget objects are understood here.

**Comment by ssteiner** [comment]
I'm not sure what the PS Module this command is for ([MicrosoftTeams](https://www.powershellgallery.com/packages/MicrosoftTeams/4.3.0) does. I just Import it using an `InitialSessionState` using

```
    var initial = InitialSessionState.CreateDefault();
    initial.ImportPSModule(new string[] { path to module here });
    initial.ExecutionPolicy = Microsoft.PowerShell.ExecutionPolicy.Unrestricted;
    var myRunspacePool = RunspaceFactory.CreateRunspacePool(initialState);
    myRunspacePool .Open();
```
I then connect using 

```
    var ps = PowerShell.Create();
    ps.RunspacePool = myRunspacePool ;
    var myCommand = new Command("Connect-MicrosoftTeams");
    if (!string.IsNullOrEmpty(Config.Login) && Config.Password != null)
    {
         var cred = new PSCredential(Config.Login, Config.Password);
         var param = new CommandParameter("Credential", cred);
          myCommand.Parameters.Add(param);
     }
    ps.Commands.AddCommand(myCommand);
    var result = ps.Invoke();
```

So your standard 'run PS command'.

Once connected I'd like to run the command I posted above.

If I run `Get-CsUserCallingSettings -Identity user4@contoso.com`, I get a PSObject back which has a bunch of properties. Most of them are simple, so they're easy to work with. The property `GroupMembershipDetails` is an array of Objects - that's where the problems start.

I need to fetch the right item of that list, and modify one of it's property (setting it to another value) and then use the entire modified object that `Get-CsUserCallingSettings` returned as input to another commandlet `Set-CsUserCallingSettings`. The latter won't accept an input of `Deserialized.Whatnot`, but expects the same type that it gave me as return of `Get-CsUserCallingSettings`. No methods will be called... I just need to pick the right item from the list, and modify a single property, then send the entire thing back.

**Comment by daxian-dbw** [comment]
It sounds the problem is with the `MicrosoftTeams` module, in that it doesn't support the scenario where result of the `Get-CsUserCallingSettings` can be used as input to another cmdlet `Set-CsUserCallingSettings`.

@StevenBucher98 and @SydneyhSmith, do either of you knows how to provide feedback to the owner of `MicroosftTeams` about this?

**Comment by daxian-dbw** [comment]
@ssteiner I found that opening issue in https://github.com/MicrosoftDocs/office-docs-powershell can get the attention from the `MicrosoftTeams` module owner, one example issue: https://github.com/MicrosoftDocs/office-docs-powershell/issues/9420.
So, please open an issue about this in that repo, and you will be more likely to get help from the right folks.

**Comment by JensTrier** [comment]
@ssteiner Thanks for the feedback. 

Set-CsUserCallingSettings does support setting GroupMembershipDetails using the output from Get-CsUserCallingSettings, when run directly in PS. Example 6 in https://docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingsettings?view=teams-ps shows how to do it (fyi, the Index cmd is wrong in the example, since sip: is missing from the user, but I'm in the process of updating the doc).

I'm not sure why the returned object is different, when running the cmdlet in the SDK. Feel free to contact me offline with more details at jens.trier snablea microsoft.com
