### ISSUE TITLE
7.2.3: ServerCertificateValidationCallback throws There is no Runspace available to run scripts in this thread

### ISSUE THREAD

**Issue by Hamsterman** [PowerShell/PowerShell#17340]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The following code fails on PS 7.2.3 but works just fine on PS 5.1.19041.1682 (Windows 10 version)

    $req = [System.Net.HttpWebRequest]::Create('https://' + $Domain)
    $req.AllowAutoRedirect = $true
    $req.ServerCertificateValidationCallback = [System.Net.Security.RemoteCertificateValidationCallback] { return $true }
    $resp = $req.GetResponse()

### Expected behavior

```console
No errors and any validation errors are hidden
```

### Actual behavior

```console
Exception is thrown
```

### Error details

```console
"There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was:  return $true "
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
It's a .NET change that makes the callback runs on thread pool thread now. Here are some duplicates issues: https://github.com/PowerShell/PowerShell/issues/15688, https://github.com/PowerShell/PowerShell/issues/13597

**Comment by jborean93** [comment]
There are 3 main ways you can bypass this. The simplest is to just use [Invoke-WebRequest](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.2) with the `-SkipCertificateCheck`. There are many more options on that cmdlet and it is quite advanced since it was rewritten in the pwsh v6/7 days. It also uses the [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-6.0) class internally which is recommended today over the `HttpWebRequest` class.

The 2nd options is to use `Add-Type` to compile the C# code containing your delegate:

```powershell
Add-Type -TypeDefinition @'
using System;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;

namespace HTTP
{
    public class Validator
    {
        public static bool MyTlsValidator(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
        {
            return true;
        }
    }
}
'@

$req = [System.Net.HttpWebRequest]::Create('https://' + $Domain)
$req.AllowAutoRedirect = $true
$req.ServerCertificateValidationCallback = $certDelegate
$resp = $req.GetResponse()
```

The benefit of this approach is you can store the responses on the class for later retrieval or easily change it up and add conditional validation logic.

The 3rd option is to use a Linq Expression to build the delegate yourself. It's a bit more involved but saves you having to compile the code inline and this expression is quite simple

```powershell
$certDelegate = [System.Linq.Expressions.Expression]::Lambda(
    [System.Net.Security.RemoteCertificateValidationCallback],
    [System.Linq.Expressions.Expression]::Block(
        [System.Linq.Expressions.Expression]::Constant($true)
    ),
    [System.Linq.Expressions.ParameterExpression[]](
        [System.Linq.Expressions.Expression]::Variable([object]),
        [System.Linq.Expressions.Expression]::Variable([System.Security.Cryptography.X509Certificates.X509Certificate]),
        [System.Linq.Expressions.Expression]::Variable([System.Security.Cryptography.X509Certificates.X509Chain]),
        [System.Linq.Expressions.Expression]::Variable([System.Net.Security.SslPolicyErrors])
    )
).Compile()

$req = [System.Net.HttpWebRequest]::Create('https://' + $Domain)
$req.AllowAutoRedirect = $true
$req.ServerCertificateValidationCallback = $certDelegate
$resp = $req.GetResponse()
```

Ultimately unless `Invoke-WebRequest` or `Invoke-RestMethod` didn't have a feature you needed you should really stick with the cmdlets as they do all this for you.

**Comment by Hamsterman** [comment]
Invoke-Webrequest is not really working either: see issue #17333
But it would be much better if it did :)
