### ISSUE TITLE
Recursive Globstar

### ISSUE THREAD

**Issue by cerealXDD** [PowerShell/PowerShell#17347]
### Summary of the new feature / enhancement

I have a need for recursive globbing in powershell. Similarly how in bash you can do \<dir>/**/* to insert a recursive list of files on the command line, can the same be done in powershell?

**Comment by jhoneill** [comment]
PowerShell uses .NET wildcards so `**`  is the same as `*` or `****`  - it doesn't have a special meaning of "recurse"  when dealing with the file system.  The file system and registry providers both treat `*/*`  - as all items "1 level down the tree" and `*/*/*` as "All items 2 levels down" and so on - the Certificate Store provider will allow `dir */*` but not `dir */*/*`   `**/*` 

If you are running pwsh on linux and execute ` ls **/*`   the `ls` executable does the same thing with `**/*` as it would when run from bash   - both pass the parameter on as literal text
If you are running pwsh on windows and run a native windows command in most cases it will use a parameter rather than a special path to request recursion and will probably error if given `**\*` - as it would from cmd or a port of bash running on Windows (or even from wsl launching a windows command).  Again the parameter is literal text.  
PowerShell commands will typically have a `-Recurse` switch and/or accept file objects from the pipeline so the typical route  is to use Get-ChildItem (or one of its aliases dir / gci) with the options to exactly the required files and/or directories as objects and pipe them into another command which needs to do something with a bunch of files. 

Since you don't say what you'd do with magic paths elsewhere it's not really possible to give a "do it this way" command line.

**Comment by cerealXDD** [comment]
> PowerShell uses .NET wildcards so `**` is the same as `*` or `****` - it doesn't have a special meaning of "recurse" when dealing with the file system. The file system and registry providers both treat `*/*` - as all items "1 level down the tree" and `*/*/*` as "All items 2 levels down" and so on - the Certificate Store provider will allow `dir */*` but not `dir */*/*`
> 
> `**/*` will be processed differently depending on the command being run
> 
> If you are running pwsh on linux and execute ` ls **/*` the `ls` executable does the same thing with `**/*` as it would when run from bash - both pass the parameter on as literal text If you are running pwsh on windows and run a native windows command in most cases it will use a parameter rather than a special path to request recursion and will probably error if given `**\*` - as it would from cmd or a port of bash running on Windows (or even from wsl launching a windows command). Again the parameter is literal text. PowerShell commands will typically have a `-Recurse` switch and/or accept file objects from the pipeline so the typical route is to use `Get-ChildItem` (or one of its aliases `dir` /`gci`) with the options to get exactly the required files and/or directories as objects and pipe them into a command which does something with files.
> 
> Since you don't say what you'd do with magic paths elsewhere it's not really possible to give a "do it this way" command line.

I'm using a video player.  I want to be able to play all of the files in a specific folder with all of the files from its subdirectories as well. In bash I'd do \<video_player_binary> \<folder_path>/**/* with globstar option enabled to achieve this. In powershell I can't do this.

**Comment by daxian-dbw** [comment]
@cerealXDD Can you try `<video_player_binary> (dir /home/daxian/**/* | % FullName)` and see if that works?

**Comment by jhoneill** [comment]
> I'm using a video player. I want to be able to play all of the files in a specific folder with all of the files from its subdirectories as well. In bash I'd do `<video_player_binary> <folder_path>/**/*` with globstar option enabled to achieve this. In powershell I can't do this.
> 
> Or maybe my video player is parsing the **/*? Is this what you mean?

That's what I believe, yes. As I understand it bash can do the work to translate mydir/**/* to a set of filenames, but for `video_player_binary> <folder_path>/**/*`  that path isn't being expanded and is just passed as a string.    

If I'm wrong, and you do need to run `video_player_binary path1 path2 path3 ` where the paths are put there by the shell     
 `(gci -r  path_to_dir -File).FullName`  or `(gci -r  path_to_dir -File| % fullname)` will do that for you. 

@daxian-dbw  `dir **/*` is all equivalent to  `dir */*` in effect `dir -recurse -depth 1 *` if it needs "any depth" it will need to be `-recurse` instead.

**Comment by cerealXDD** [comment]
> @cerealXDD Can you try `<video_player_binary> (dir /home/daxian/**/* | % FullName)` and see if that works?

It doesn't work. I get this error :

Program '\<binary>' failed to run: The filename or extension is too longAt line:1 char:1
+ \<binary> (dir \<dir>/**/* | % FullName)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ \<binary> (dir \<dir> | % FullName)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

**Comment by cerealXDD** [comment]
> > I'm using a video player. I want to be able to play all of the files in a specific folder with all of the files from its subdirectories as well. In bash I'd do `<video_player_binary> <folder_path>/**/*` with globstar option enabled to achieve this. In powershell I can't do this.
> > Or maybe my video player is parsing the **/*? Is this what you mean?
> 
> That's what I believe, yes. As I understand it bash can do the work to translate mydir/**/* to a set of filenames, but for `video_player_binary> <folder_path>/**/*` that path isn't being expanded and is just passed as a string.
> 
> If I'm wrong, and you do need to run `video_player_binary path1 path2 path3 ` where the paths are put there by the shell `(gci -r path_to_dir -File).FullName` or `(gci -r path_to_dir -File| % fullname)` will do that for you.
> 
> @daxian-dbw `dir **/*` is all equivalent to `dir */*` in effect `dir -recurse -depth 1 *` if it needs "any depth" it will need to be `-recurse` instead.

`Ok, ``(gci -r path_to_dir -File).FullName``` works, but only for paths without spaces or special characters. When special characters are involved I get the error above.

**Comment by jhoneill** [comment]
Not sure what the cause is :  this works for me ... 

```
> $env:editor
C:\Program Files\Notepad++\notepad++.exe
> & $env:Editor  (gci  'C:\Program Files\PowerShell\Modules\Microsoft.PowerShell.Crescendo\*.ps1' -File -Recurse ).fullname

```
Notice when I do "gci"  and the path has spaces. etc _that_ needs quotes round the path, but the file names I'm pushing into notepad++ don't need quotes - if I put quotes round them I can error that says the path "'C:\....'" isn't valid or ""c:\..."" if I use double quotes. But if I force an error by omitting the quotes the error message says 

If   `<binary>  "<problem file path>"` doesn't work from the PowerShell prompt, we need to look at how the app wants the path to be written . But if it does can you try 
```
$x = "<problem file path>"
<binary> $x 
```
and  if that works 
```
<binary> @($x  ,$x) 
```

**Comment by cerealXDD** [comment]
> Not sure what the cause is : this works for me ...
> 
> ```
> > $env:editor
> C:\Program Files\Notepad++\notepad++.exe
> > & $env:Editor  (gci  'C:\Program Files\PowerShell\Modules\Microsoft.PowerShell.Crescendo\*.ps1' -File -Recurse ).fullname
> ```
> 
> Notice when I do "gci" and the path has spaces. etc _that_ needs quotes round the path, but the file names I'm pushing into notepad++ don't need quotes - if I put quotes round them I can error that says the path "'C:....'" isn't valid or ""c:..."" if I use double quotes. But if I force an error by omitting the quotes the error message says
> 
> If `<binary> "<problem file path>"` doesn't work from the PowerShell prompt, we need to look at how the app wants the path to be written . But if it does can you try
> 
> ```
> $x = "<problem file path>"
> <binary> $x 
> ```
> 
> and if that works
> 
> ```
> <binary> @($x  ,$x) 
> ```

Ok, I figured out the cause. The folder I'm passing has about 1000 files. It will print all the files if I do an echo, but not when I use the video player. I'm not sure how to get around this.
