### ISSUE TITLE
include file only once. So "." have to include only one time

### ISSUE THREAD

**Issue by avmaksimov** [PowerShell/PowerShell#17352]
### Summary of the new feature / enhancement

I wrote some files for me and the problem is that some files included another and other can include another and so on. So better if files can included only once.

### Proposed technical implementation details (optional)

I make the global variable: path to included files and include files via it from a main script and in other files include another files with this path, so I include always absolute paths. So may be it's not a problem to include files only one time especially if they include with full path.

**Comment by daxian-dbw** [comment]
The dot sourcing operator is for [invoking a script within the current scope](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.2#dot-sourcing-operator-) and it doesn't track if a script has already been invoked. Its behavior is by design and changing that would be a breaking change.

Maybe you can organize your scripts in modules. Running `Import-Module` on the same module the second time won't really import the module again because it will simply return after seeing the module is already loaded.

**Comment by avmaksimov** [comment]
> The dot sourcing operator is for [invoking a script within the current scope](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.2#dot-sourcing-operator-) and it doesn't track if a script has already been invoked. Its behavior is by design and changing that would be a breaking change.
> 
> Maybe you can organize your scripts in modules. Running `Import-Module` on the same module the second time won't really import the module again because it will simply return after seeing the module is already loaded.

Thank you. Yes, I read about modules but I didn't know that modules haven't to be installed before using. I will try and return.

**Comment by avmaksimov** [comment]
Hello. Modules don't solve the problem when one module depends on another and one of them depends on the previous imported. Powershell can't work this way - it try recursvely add modules and stops running with it.

So I added check if this module was added by some variable initialization, but there is a problem. If I run my script via IDE I have to remove this variables before adding modules. It's inconvenient. And there is no difference between Import-Module or simply adding by '.\scrips.ps1'. So if no diff I prefer point.

I use my script library and change it from time to time. Also I use it from different computers. That's why importing to computer is inconvenient too.
