### ISSUE TITLE
PowerShell should not run follow-up commands before `Format-Table` has finished output

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/PowerShell#17392]
### Summary of the new feature / enhancement

`Format-Table`, which is implicitly called by a number of Cmdlets, tries to calculate the width of display columns in a separate thread for approx. 300 ms before displaying content.

`Start-Sleep` pauses the main thread and, thus, a previous command's output, still in the pipeline for being displayed, won't be displayed before `Start-Sleep` elapses.

([See here for a description of the problem.](https://stackoverflow.com/questions/59330539/weird-delay-of-the-output-of-an-object-when-followed-by-start-sleep-or-until-sc))

This is undesired, unpredictable, confusing, unwanted, … behavior.

### Proposed technical implementation details (optional)

I suggest to implement a semaphore into `Format-Table`/`Start-Sleep` that will keep `Start-Sleep` from pausing the current thread until `Format-Table` has finished displaying its output (in case such output is still pending).

**Comment by jhoneill** [comment]
I think "Start-Sleep pauses ...  a previous command's output" is not the case the in a single threaded world. The output gets processed before the  Start-Sleep is run .  Here's a simple test. 

```
 dir | select -last 5 -Property name,LastWriteTime | % {$_ ; Write-host "." ; sleep 1 }  

.
Name                  LastWriteTime
----                  -------------
UIAutomationTypes.dll 15/03/2022 19:29:54
vcruntime140_cor3.dll 07/03/2022 15:19:38
.
WindowsBase.dll       15/03/2022 19:29:56
.
WindowsFormsIntegrat… 15/03/2022 19:29:56
.
wpfgfx_cor3.dll       15/03/2022 17:39:36
.
```
The Write-host "."  and the sleep get processed after the output has been written.  EXCEPT for the first item So we see the "." for the first item, then the  output of TWO items - because 300ms has elapsed. Then we get the second item's "." then the third item followed by its "." and so on.  Format-Table has waited for the second item (or the end of input) before outputting anything and this is commonly seen in debugging.  

If we shorten the time we get multiple "." output until `format-table` has been waiting 300 ms, then it generates output with as many items as it has received upto that point - followed by the "." and the sleep operation    

```
> dir | select -last 5 -Property name,LastWriteTime | % {$_ ; Write-host "." ; sleep -Milliseconds 80 } 

.
.
.
Name                        LastWriteTime
----                        -------------
UIAutomationTypes.dll       15/03/2022 19:29:54
vcruntime140_cor3.dll       07/03/2022 15:19:38
WindowsBase.dll             15/03/2022 19:29:56
WindowsFormsIntegration.dll 15/03/2022 19:29:56
.
wpfgfx_cor3.dll             15/03/2022 17:39:36
.
``` 

So the delay to wat for a minimum of 2 items AND  300ms, 

I had a version of this to test the how slow catastrophic backtracking regexes can get 

```
$r = [regex]::new("(.*)+x", "Compiled")  
$s = "A" * 24   
foreach ($i in (25..28)) {  
    $s+= "A" ;  
    [PSCustomobject]@{Count=$i;time= (measure-command {$r.IsMatch($s)}).TotalMilliseconds.tostring("N1")}
}
```

On my machine the first object gets output after ~2 seconds, and I see a blank line which is format table waking up. The next one takes ~4 seconds and at that point I get the first two objects. The thread doesn't get back to format-table until the second object is written, and the (AFAIK) the 300ms timer can't suspend the regex and get format-table to output the first item.

**Comment by SetTrend** [comment]
Here's a simple example:

https://stackoverflow.com/questions/72305908/no-output-when-script-is-launched-using-start-process

**Comment by jhoneill** [comment]
And ?  
```
get-location  ;  foreach ($a in 1..10000) {$b += "x"*50}
```

As I said it won't output anything until there are TWO items AND 300ms has elapsed. Give it one item and it just waits.  There is nothing special about the delay being a sleep command . 

```
$b= $null;  get-location ; foreach ($a in 1..10000) {$b += "x"*50} ; get-location ; foreach ($a in 1..1000) {$b += "x"*50};  get-location ; foreach ($a in 1..1000) {$b += "x"*50}; 
```

So you get no output after the first - 1 item queued 300ms hasn't elapsed.
Delay
2 items output after the second - 2 items queued , 300ms has elapsed
Delay
3rd item output immediately
Delay
Prompt returns.

If you still think that Format-Table's timer is paused by the sleep command try this. 
```
$x= "" +( Get-date) ; Get-Location ;  sleep 1 ; $x+=Get-date ; sleep 10  ; $x+=Get-date ; sleep 10
```
If it were the sleep timer delaying format-table, when timer expires and another command runs execution would find its way back to ft - but it doesn't. Format-table doesn't get to do anything until either another item goes in the the command ends, and if a terminating error occurs before that happens the output is lost. 
```
 Get-Location ; throw "No output"
```
1 item queued or 300ms not elapsed
``` 
Get-Location ; Get-Location ; throw "No output"
```
but 
```
Get-Location ; sleep -Milliseconds 400 ; get-location; throw "some output"
```

**Comment by SetTrend** [comment]
OK, so the sleep timer isn't the source for the delay.

Still, this delay is unexpected and a source of misunderstanding. So, then shouldn't `Format-Table` output before other commands continue to be evaluated?

**Comment by jhoneill** [comment]
The behaviour is a compromise. 
In early versions of PowerShell if autosize wasn't specified the sizing was just screen-width/number of columns, so (IIRC) it did output the first row immediately.  That sizing wasn't good so another solution was tried.  
Things getting stuck in the buffer is annoying - especially when debugging, and potential to lose the data in the buffer isn't good. Do those things outweigh the better use of space?  I don't know enough about other people's experience; I'll live with it to get better formatting most of the time

**Comment by SetTrend** [comment]
I see.

So, I'd very much appreciate the better layout, too. Yet, I suppose PowerShell should not run another command before `Format-Table` has finished outputting.

From your excellent explanation I believe, the current issue title doesn't correctly reflect the situation anymore. Would you agree to rename this issue to: _"PowerShell should not run follow-up commands before `Format-Table` as finished output"_?

**Comment by SetTrend** [comment]
As far as I read, the implicit call to `Format-Table` – and that's what this thread is mainly about – [is only done when _**displaying**_ the result](https://stackoverflow.com/questions/59330539/weird-delay-of-the-output-of-an-object-when-followed-by-start-sleep-or-until-sc#answer-59331305). So, when piping the output, `Format-Table` shouldn't get called, as far as I understood?

**Comment by jhoneill** [comment]
I have just read the question two different ways, so hopefully this covers both :-) 

At the weekend someone tweeted this (old) article by Jeffery Snover on "what really happens" https://devblogs.microsoft.com/powershell/how-powershell-formatting-and-outputting-really-works/  
I think it's still valid - because you can define Out-Default with `Function out-default {$null = $null}` and nothing goes to the screen anymore -   the way I visualize it is commands get processed as  `  & { << command you entered >>  } | Out-Default`    

Out-Default sends strings straight to out-host  and forks other objects to format table or format list, so yes -  the implicit call to format table / format-list won't happen until something which needs to be displayed goes into Out-Default.
 It is easier to explain with  explicit calls to format-table - I imagine Out-Default creates a steppable pipeline for format-table or format-list when it knows which it will use, calls its begin and process blocks for the first item, and then calls the pipeline's end block from its own end block.

**Comment by SetTrend** [comment]
I read that thread … It's very interesting, yet, unfortunately, it doesn't add value to this current thread.

**Comment by daxian-dbw** [comment]
I think @jhoneill had great explanation on the observed behavior differences between `Get-Location ; Get-Location ; throw "No output"` and `Get-Location ; sleep -Milliseconds 400 ; get-location; throw "some output"`, and called out that the `Start-Sleep` command is not related to the delay behavior when `Format-Tab` is used for the implicit formatting. Thank you, @jhoneill!

The delay and waiting-for-2-objects behaviors are by design to `Format-Table`, for better table view calculation. Also as called out in https://github.com/PowerShell/PowerShell/issues/17392#issuecomment-1135104280, it's a compromise.

**Comment by jhoneill** [comment]
@daxian-dbw  You're welcome :-)

**Comment by SetTrend** [comment]
Yes, I'm not disputing the delay and the waiting-for-2-objects behavior.

I'm supposing subsequent commands to ***wait*** for `Format-Table` to finish its job.

All the discussion in here doesn't engage with the issue itself, but only with how `Format-Table` works. But that's not the acutal issue described here.

Again: I supposed to have PowerShell ***wait** for for `Format-Table` to finish its job before continuing to execute other commands.

**Comment by jhoneill** [comment]
> Yes, I'm not disputing the delay and the waiting-for-2-objects behavior.
> 
> I'm supposing subsequent commands to _**wait**_ for `Format-Table` to finish its job.

Nothing is interrupting Format-Table. It accepts one item, queues it, and allows the other commands to run  

> All the discussion in here doesn't engage with the issue itself, but only with how `Format-Table` works. But that's not the actual issue described here.

The two are the same thing. An item is sent to format-table. Format-table puts in a queue and waits for the next item. If you want the first item sent to be output immediately Format-Table would need to work in a different way - sizing columns after the first  item

> Again: I supposed to have PowerShell _**wait**_ for for `Format-Table` to finish its job before continuing to execute other commands.

Format-Table signals "I have done everything with _that_ item. Send me the next one"

**Comment by SetTrend** [comment]
I don't know where I'm giving false leads …

> If you want the first item sent to be output immediately

NOOOOO, I DON'T want the first item sent to be output immediately. That's what I'm writing here over and over and over again.

I want subsequent commands to ***wait*** for `Format-Table` to finish – you see: WAIT. Where's the misunderstanding in the term "wait"?

**Comment by jhoneill** [comment]
Nothing can "wait for format-table to finish" because it declares it _has_ done all its work after putting the first item (and others received before 300ms has elapsed) in a queue.  If it queues _anything_ and waits for more items, then a delay and possible data loss is the result. 

I think you're saying in a piece of code like this 
```
get-process -id $pid  | select name,WS 
sleep 3 
get-process -id $pid  | select name,WS 
sleep 3 
get-process -id $pid  | select name,WS 
sleep 3
```
The output from the first line should emerge before the first sleep and the second should have it's own instance of format table, if you convert it to  
```
 get-process -id $pid  | select name,WS  | ft
sleep 3 
get-process -id $pid  | select name,WS  | ft
sleep 3 
get-process -id $pid  | select name,WS  | ft
sleep 3
```
_that_ works finishes each of the FTs before getting to the sleep  but the first version is doing
```
& {
 get-process -id $pid  | select name,WS  
sleep 3 
get-process -id $pid  | select name,WS  
sleep 3 
get-process -id $pid  | select name,WS  
sleep 3 
} | ft
```
with a single ft.
Its the same reason that 
```get-process -id $pid  | select name,WS ; Get-Process -id $pid | select name,BasePriority``` doesn't output a basepriority. One format to rule them all.

**Comment by SetTrend** [comment]
You're describing it correctly.

I feel the current behavior doesn't make any sense. Why should anyone expect a behavior like you described above to occur?

> ```powershell
> & {
>  get-process -id $pid  | select name,WS  
> sleep 3 
> get-process -id $pid  | select name,WS  
> sleep 3 
> get-process -id $pid  | select name,WS  
> sleep 3 
> } | f
> ```

That's exactly my proposal:

Let's …

> ```powershell
> get-process -id $pid  | select name,WS 
> sleep 3 
> get-process -id $pid  | select name,WS 
> sleep 3 
> get-process -id $pid  | select name,WS 
> sleep 3
> ```

… behave like …

> ```powershell
> get-process -id $pid  | select name,WS  | ft
> sleep 3 
> get-process -id $pid  | select name,WS  | ft
> sleep 3 
> get-process -id $pid  | select name,WS  | ft
> sleep 3
> ```

That's what, from my point of view, anyone would expect to occur natively.

**Comment by jhoneill** [comment]
OK.  Should the output of
```
Get-Process pwsh  | select name,wS ; 
Get-Process powershell | select name,ws
Get-Process cmd | select name,ws
```
Look like this 
```
Name              WS
----              --
pwsh       106479616
powershell 101736448
cmd          4673536
```
or like this 

```
Name        WS
----        --
pwsh 110518272


Name              WS
----              --
powershell 101867520


Name      WS
----      --
cmd  4673536
```

Because you're asking for the second although you did say   
> NOOOOO, I DON'T want the first item sent to be output immediately.


> That's what, from my point of view, anyone would expect to occur natively

I think people would expect that if a something outputs 3 objects they go into one table.  And they would not expect a command which returned 3 of something produce one table when the command is a compiled c# cmdlet, but 3 tables when the command is function.  You may well be right that someone taking their first steps with PowerShell _could_ think a function which sends output in 3 places would process the three independently , (and think that PowerShell would also do a better job when the objects were of different types, and wouldn't lose output if an error occurred after the output had been sent.) But when you work through what that would means, they would probably conclude it is better not to do that.

**Comment by SetTrend** [comment]
Yes, I would expect output number 2 to occur.

I wouldn't know of a single use case where output number 1 would feel appropriate and desired. I believe it's quite exotic. If someone would really need such aggregation, there'd be loads of alternatives to use for aggregating the data into one single output.

And I'm quite sure that if there'd be a poll asking 100,000 PowerShell users what they'd expect, at least 99,990 would respond: "output number 2".

**Comment by jhoneill** [comment]
If a poll asked whether `Get-Process` should create  1 table or 317 (I have 317 processes on my system right now) 9999 out of every 10,000 are going say 1,  right ?   
If second questions was "if a command produces custom objects for _n_ processes, 1 table or _n_" it's still going be 1 (these examples use `select` because the objects normally emitted by `Get-Process `have formatting defined for them which gives the columns a fixed width.  We are only talking about objects which have no formatting defined.) 

Not many people are going to answer - it depends what is inside the command.  You're looking inside the function and saying there are 3 calls to compiled blocks of c#, so there should be 3 end-to-end runs of format table - the function shouldn't be treated as an atomic thing that it is now. But really that's not logical - imagine the code as 
``` 
$coreps =  Get-Process pwsh  | select name,wS ; 
$winps = Get-Process powershell | select name,ws
$legacy = Get-Process cmd | select name,ws
````
So far nothing has been output do the following produce the same or different output  
```
$coreps , $winps, $legacy 
```

```
$coreps ;  $winps;  $legacy 
```

```
$coreps 
$winps
$legacy 
```

Why would you have 3 tables for someone who writes their code like this 

```
foreach ($name in @("pwsh","PowerShell","cmd") {
  Get-Process $name | select name,ws
}
```
  
and 1 if they write it like this 
```
  Get-Process  @("pwsh","PowerShell","cmd") | select name,ws
```

Ironically what you're advocating would mean if the author wanted to results displayed as a multi-row table, rather than single rows with their own column headings, their code would need to accumulate all the results and return them in a single operation, so returning results as they are available (and displaying them after 300ms) delaying out rather than having it happen sooner..  

The issued is flagged as declined, and really should be flagged by-design as well. There's not a more I can say.

**Comment by SetTrend** [comment]
I know this issue has been declined. And I disagree, because of common sense.

Yes, aggregating takes aggregation commands. What you're describing is an array of three elements to forward to `Format-Table`, nothing else. There's absolutely no need for PowerShell to assume this desire without being told to do so.

**Comment by SetTrend** [comment]
I know, it's hard to think of this behaviour from a different perspective for those (few) who got acquainted with it over the years. And I comprehend it takes time to overcome this perception bubble that evolved over the years.

Still, I suggest (particularly to @daxian-dbw) to free your mind and look at this issue from a fresh perspective.

**Comment by jhoneill** [comment]
We are turning into an XKCD cartoon https://xkcd.com/386/  

But one last try, because something you said makes me think I can still explain it. 

> aggregating items takes aggregation commands. 

Actually it needs no explicit command.  

When you put multiple commands into a script block (and that includes saving it as script file, or defining it as function) that performs aggregation  

>What you're describing is an array of three elements to forward to `Format-Table`, nothing else.

YES !  
Whatever calls this 
{  
  Get-Process pwsh  | select name,wS ;   
  Get-Process powershell | select name,ws
  Get-Process cmd | select name,ws
}
or this 
```
{
$coreps =  Get-Process pwsh  | select name,wS ; 
$winps = Get-Process powershell | select name,ws
$legacy = Get-Process cmd | select name,ws

$coreps , $winps, $legacy 
}
```
And all the other variations sees an array of three items.  The _output_ is identical, so the process to display it should put the same thing on the console.  

Aggregation means we don't get a change of display type if command outputs file and process objects. This is an accepted consequence of the design - not a design goal - but the behaviour is by design. The pause to allow format-table to size columns better combines with aggregation to mean in a few cases data can be lost or delayed, again that's not a goal but an accepted consequence, and by design.  

I think what you are saying amounts to - these things should not aggregate, they should run as if each was submitted at a prompt and ran to completion before the next started. 

> There's absolutely no need for PowerShell to assume this desire without being explicitly told to do so
.
A script / function / scriptblock multi-part command is treated as one command  _not_ as its constituent parts. Creating one of those IS telling PowerShell to aggregate the output of the parts.  Some languages force aggregation by making "send output" and "exit function" a single return operation. PowerShell does not, and in C# cmdlets it is not a single "return from function" which sends output to the pipeline but a write-object-to-pipeline operation - and there can be be many of those 

> Again, this is unexpected, undesired, unpredictable, confusing, … behavior.

It is completely predictable (including the cases which aren't desirable) and only confusing or unexpected if you don't see functions etc as unifying their parts.

**Comment by SetTrend** [comment]
> I think what you are saying amounts to - these things should not aggregate, they should run as if each was submitted at a prompt and ran to completion before the next started.

Yes, but only in the case of three distinct commands. Like this:

```powershell
Get-Process pwsh | select name,ws
Get-Process powershell | select name,ws
Get-Process cmd | select name,ws
```

These are not to be considered an array but three distinct outputs.

**Comment by mklement0** [comment]
See also:

* #4594
* #13985

**Comment by jhoneill** [comment]
@mklement0     Would value any thoughts on what might be practical to improve things 


To me there seems to be a single core problem - to make good decisions about sizing `format-table` queues some data, and things we might not like can happen while something is in the queue (delay, loss of the queued data, or something overtaking it being main ones).  I think you nailed that in your summary of #4594 on 18 Aug 2017, and I'm not sure much has changed since.

**Comment by mklement0** [comment]
@jhoneill

I can't speak to technical solutions - perhaps @SeeminglyScience  or @jborean93  can - but it's clear that the asynchronous behavior is a perennial headache that ranges from baffling output sequencing to loss of data.

Given that we're talking about _for-display_ formatting, I think it would be acceptable to make the delay _synchronous_.

**Comment by SeeminglyScience** [comment]
The reason that the delay is asynchronous is so that we can get more objects before deciding what the format should be. If it were synchronous, we would simply delay 200ms and then still only take the first object into account.

I can't think of a general solution other than only taking the first object into account (which is not desirable for different reasons).

**Comment by mklement0** [comment]
Thanks, @SeeminglyScience - the synchronous behavior I had in mind relates to cross-stream behavior; that is, all other streams should be blocked while the objects are being collected. Is there no good technical solution for that?

**Comment by SeeminglyScience** [comment]
Not that I can think of personally. None of these systems talk to each other currently so it would be non-trivial to hook that up. Not impossible of course, but there's a solid chance that such a fix would only surface different issues. I'd hesitate to recommend anyone try as a PR for this would be very time consuming to even review.

**Comment by SetTrend** [comment]
> The reason that the delay is asynchronous is so that we can get more objects before deciding what the format should be.

To me the question is: Why is a collection of items happening across distinct commands at all? If that would be dropped, all the headache was gone.

As I wrote in https://github.com/PowerShell/PowerShell/issues/17392#issuecomment-1140441196, no-one expects these to be compiled into a single output.

**Comment by SeeminglyScience** [comment]
> As I wrote in [#17392 (comment)](https://github.com/PowerShell/PowerShell/issues/17392#issuecomment-1140441196), no-one expects distinct commands' output to be compiled into a single output.

Most folks expect that when you output multiple objects they are aggregated into a single table. That is definitely the expectation of the user base, if we switched to outputting a separate table for every object many folks would break.

**Comment by SetTrend** [comment]
@SeeminglyScience: I assume you've not been following this thread.

Outputting a **single collection** (e.g. `Get-Process | select name,ws`) as a single table isn't considered the issue. Yet, outputting **two distinct collections** as a single table, however, is unexpected:

```powershell
Get-Process | select name,ws;
Get-Process | select name,ws;
```
… is supposed to output this:

```
Name             WS
----             --
powershell 83128320

Name             WS
----             --
powershell 83169280
```

… not this:

```
Name             WS
----             --
powershell 83189760
powershell 83193856
```

The first example doesn't require any kind of delay or asynchronicity to occur.

**Comment by SeeminglyScience** [comment]
All output is enumerated across the pipeline, so they aren't really grouped like that. All output is sent item by item so that downstream commands can process it concurrently.

e.g. it's expected that this:

```powershell
$items = Get-ChildItem ./
foreach ($item in $items) {
    [PSCustomObject]@{
        File = $item
    }
}
```

would be emitted the same way that this is:

```powershell
Get-ChildItem ./ | Select-Object @{ Name = 'File'; Expression = { $_ } }
```

This behavior is foundational to PowerShell and heavily relied on.

**Comment by SetTrend** [comment]
Probably, yes.

Still, it doesn't make sense, though.

This is particularly true if you consider the generic case of multiple commands uttering distinct objects' collections:

```powershell
Get-Process powershell | Select-Object name;
Get-Process powershell | Select-Object ws;
```

**Comment by SeeminglyScience** [comment]
> This is particularly true if you consider the generic case of multiple commands uttering distinct objects' collections:
> 
> ```powershell
> Get-Process powershell | Select-Object name;
> Get-Process powershell | Select-Object ws;
> ```

I believe that's more a quirk with `PSCustomObject` specifically. With concrete objects the format view is broken, but there's a significant amount of extra processing that would have to be done every single item to tell that a break is warranted. Every object has the same type identity, so the property bag itself would need to be enumerated and checked against the last object.

A different scenario of `Get-Process pwsh; Get-Item .` causes the formatter to break into a new view as they have different type identities.

There's also the general best practice of only returning one type of object at a time. This makes most folks unlikely to hit this issue in general, making the impact of a fix not worth the potentially substantial performance hit (imo).

Generally if you are hitting this, you aren't actually trying to use the objects as literal output to be consumed by a user, but rather just for display purposes. In that case you can pipe each thing you want to be displayed in a separate view to `Out-Host`.

**Comment by SetTrend** [comment]
> Generally if you are hitting this, you aren't actually trying to use the objects as literal output to be consumed by a user, but rather just for display purposes. In that case you can pipe each thing you want to be displayed in a separate view to `Out-Host`.

Exactly. Yet, (and that's my proposal). for display purposes, this should be done automatically by PowerShell. `Format-Table` only applies for display purposes. So it should be easy to determine the output target and behave accordingly.

Here's another example of unexpected output:

```powershell
Get-Location | Select-Object Path; Get-Process powershell | Select-Object name;
```

**Comment by jhoneill** [comment]
> Here's another example of unexpected output:
> 
> ```powershell
> Get-Location | Select-Object Path; Get-Process powershell | Select-Object name;
> ```

It does exactly what you've asked it to do. Create an object with a path property, and create one or more objects with a name property and output both types as part of a single command , using the default object formatting. It's only "unexpected" if you think `;` should work differently to the way it does.   
 
If you want to see a path and name(s)  you can

1. Run the two parts as separate commands. 

2. Output the property alone, rather than a single property custom object
 ```powershell
Get-Location | % Path; Get-Process powershell | %  name;
 ```

3.  Include formatting in partial commands (it's not needed in the last one) 
```
 Get-Location | Select-Object Path | Out-Default; Get-Process pwsh | Select-Object name | Out-Default;
```
