### ISSUE TITLE
ConvertFrom-Json should have a -AsOrderedDictionary

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#17404]
### Summary of the new feature / enhancement

Currently, when using `ConvertFrom-Json -AsHashtable`, you get an unordered hashtable where the properties don't match the order defined in the JSON.

```powershell
'{ "a": 0, "b": 1, "c": 2 }' | ConvertFrom-Json -AsHashtable
```

Expected:

```output
Name                           Value
----                           -----
a                              0
b                              1
c                              2
```

Actual:

```output
Name                           Value
----                           -----
c                              2
b                              1
a                              0
```

### Proposed technical implementation details (optional)

Proposal is to make `-AsHashtable` actually return an OrderedDictionary.  I believe from PS script usage, there should not be any impact even if the type changes.  Alternative would be to add a `-Ordered` switch used with `-AsHashtable` or a `-AsOrderedDictionary` in a different parameterset from `-AsHashtable` but this seems unnecessary and most of the time, I would expect users converting from JSON would want to preserve order making it more readable.

**Comment by vexx32** [comment]
Wouldn't this be a breaking change?

**Comment by SteveL-MSFT** [comment]
That's the question for the WG.  I believe it's a bucket 3 breaking change in that the type changes but users won't notice other than it works how they probably expect.

**Comment by jhoneill** [comment]
> Wouldn't this be a breaking change?

I'm wondering what code expects a hash table and would fail if it gets an orderedDictionary instead? When I saw this earlier was on the point of saying "that change won't break _anything_"  But something in the back of my mind was saying 'I'm sure changing @{} to ordered by default was discussed, and not done, so would it break stuff?'  
  Because an unordered hash table is - to most intents - random, changing the sequence won't break anything and will help a few things to work.

**Comment by vexx32** [comment]
In general changing the underlying type of an output object is considered a breaking change. Certainly there's a matter of greater or lesser degress (for example, both Hashtable and OrderedDictionary support similar basic IDictionary interfaces and so forth), but if anything happens to be relying on the specific type (e.g., using reflection APIs to do something with the hashtable, or just simply checking the output type for one reason or another) will break.

I'm not against the change at all, but it's worth mentioning it is breaking and tagging it as such, because regardless of whether a large number of users are likely to be impacted, it needs to be documented as such so users know what to expect.

**Comment by vexx32** [comment]
In general changing the underlying type of an output object is considered a breaking change. Certainly there's a matter of greater or lesser degress (for example, both Hashtable and OrderedDictionary support similar basic IDictionary interfaces and so forth), but if anything happens to be relying on the specific type (e.g., using reflection APIs to do something with the hashtable, or just simply checking the output type for one reason or another) will break.

I'm not against the change at all, but it's worth mentioning it is breaking and tagging it as such, because regardless of whether a large number of users are likely to be impacted, it needs to be documented as such so users know what to expect.

**Comment by SteveL-MSFT** [comment]
Any code that checks if it's explicitly a [hashtable] will break so that by itself is sufficient to, unfortunately, consider one of the alternate options.  My preference then is probably `-AsOrderedDictionary` which makes it very clear.  I also found out that Hashtable has a clone() method, but OrderedDictionary does not.

**Comment by 237dmitry** [comment]
> Actual:
![ArcoLinux_2022-05-22_11-35-54](https://user-images.githubusercontent.com/78153320/169686102-b6797405-9bac-4be1-a687-9679069a5d2d.png)

**Comment by jhoneill** [comment]
> In general changing the underlying type of an output object is considered a breaking change. Certainly there's a matter of greater or lesser degress 

I'd say this is lesser... but not zero

> simply checking the output type for one reason or another) will break.

_Sound of palm hitting forehead._ Yeah that would break. Anything written since `[ordered] `was added in V3 _should_ test for both, but I did a search through all the code on my laptop and found one thing I wrote in the last year and various modules which don't. One popular module had this  
```
if ($x -is [HashTable] -or $x.ToString() -eq 'System.Collections.Hashtable' ) {... 
```  
Not sure about the benefit of the second part :-) 
 
But that's also an argument for things to stick to outputting hash tables and _never_ to output ordered dictionary - if I publish something which outputs _ordered_ and someone uses it with a module with a test for `[hashtable]`. they will hit an error. 

The problem with changing the default behaviour to ordered isn't (IMHO) code which says 
```
$stuff =  Get-content $file | convertFrom-Json -asHashTable
if ($stuff -is [hashtable]) 
``` 
Because we don't generally do that,  it's someone calling 
``` 
$s = Get-Stuff  # which now converts to ordered
Invoke-Something -options $s
 ```
Where `Invoke-Something` is 10 years old, not  being updated with an untyped options parameter and code which checks to see if $options is a hash table.  Changing the existing switch (or if the existing switch had been ordered from the start) would mean that everything using ConvertFrom-Json would break  But if there is a new switch for ordered output and I use it in `Get-Stuff` there's still a problem with my code working with `Invoke-Something`.  It narrows the scope, so it's probably the way to go, but it needs to come with a warning - only use this where the order matters because a few things out there will break.

**Comment by iSazonov** [comment]
As you know I have been doing some research on migrating to new .Net JSON API. There are a number of inevitable incompatible changes. Migrating to this new API is inevitable at some time. Maybe now would be a good time to do it as an experimental feature instead of complicating things with a series of incompatible changes spread out over several years?

**Comment by SteveL-MSFT** [comment]
@iSazonov as an ExperimentalFeature makes sense as I agree it makes sense to move all of PS7 JSON usage to the .NET JSON API

**Comment by iSazonov** [comment]
@SteveL-MSFT Good news! Have you a roadmap for the work?

**Comment by SteveL-MSFT** [comment]
It's not something we're planning for 7.3

**Comment by iRon7** [comment]
Related discussion: [`13852` Encourage using IDictionary interface](https://github.com/PowerShell/PowerShell/issues/13852)

**Comment by KevinMarquette** [comment]
I would love this and have had to code around it many times.
