### ISSUE TITLE
Corrupted text provided by command is automatically invoked by PowerShell during an interactive session.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [PowerShell/PowerShell#17467]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to reproduce it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

~~~pwsh
#!/usr/bin/env pwsh
#Requires -PSEdition 'Core'
#Requires -Version 7

$OutFile = "$HOME"
Invoke-WebRequest -URI "https://github.com/PowerShell/PowerShell/files/8815209/1654094598.txt" -OutFile $OutFile
	# The aforementioned is a `Start-Transcript" log.
Set-Location "$OutFile"
cat "$OutFile"
~~~

### Expected behaviour

The file's content should not be passed to the interpreter.

### Actual behaviour

Corrupted text is provided to the interpreter when I observe [the output of invocation of `script -a`](http://github.com/PowerShell/PowerShell/files/8815209/1654094598.txt), via `cat`.

### Error details

Weirdly, nothing erroneous appears to have been recorded, for the undermentioned returns `$Null`:

~~~pwsh
#!/usr/bin/env pwsh
Get-Error
~~~

### Environment data

1.	~~~pwsh
	#!/usr/bin/env pwsh
	$PSVersionTable | Format-Table
	~~~

1.	<blockquote>

	~~~RS
	Name                           Value
	----                           -----
	PSVersion                      7.3.0-preview.4
	PSEdition                      Core
	GitCommitId                    7.3.0-preview.4
	OS                             Linux 5.19.0-0.rc0.20220526gitbabf0bb978e3.4.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu May 26 16:02:31 UTC 2022
	Platform                       Unix
	PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
	PSRemotingProtocolVersion      2.3
	SerializationVersion           1.1.0.1
	WSManStackVersion              3.0
	~~~

	</blockquote>

### Visuals

Watch [`youtu.be/N7Wvo4t4Uas`](https://youtu.be/N7Wvo4t4Uas).

**Comment by daxian-dbw** [comment]
Please provides repro steps. The issue will be closed if repro steps are not provided.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@daxian-dbw, I should have expected that. I apologize. I am able to provide the file, but I know not whether it shall contain any credentials. Are you able to limit observation of it to trusted contributors?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
[This file](http://github.com/PowerShell/PowerShell/files/8856878/PowerShell_transcript.1653307616.%2BSym2k0I.20220601134519.txt) causes this problem when invoked for me, as [this record](https://github.com/PowerShell/PowerShell/files/8856893/1654640138.txt) demonstrates.

(Although "http://github.com/PowerShell/PowerShell/files/8856878/PowerShell_transcript.1653307616.%2BSym2k0I.20220601134519.txt" is not the original file that referenced, it causes the problem identically, so that is probably irrelevant. I am unable to locate the original file.)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@PaulHigin, did you read "https://github.com/PowerShell/PowerShell/issues/17467#issuecomment-1149228070"? "http://github.com/PowerShell/PowerShell/files/8856878/PowerShell_transcript.1653307616.%2BSym2k0I.20220601134519.txt" is able to invoke an identical reaction by the interpreter for me. (I believe that all that is necessary are some corrupted characters at the end of the file.)

**Comment by PaulHigin** [comment]
@BEEDELLROKEJULIANLOCKHART  This issue is not written in the required form, so that it can be easily read and comprehended.  For more information please see PowerShell guidelines for writing issue reports.  Essentially, this is what the issue report needs to contain:

- Short description of issue
- Set of reproducible steps that demonstrate the issue, as short and concise as possible.
- Expected results of reproducible steps
- Actual results of reproducible steps

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@PaulHigin, I adhered strictly to the template that GitHub provided, and consequently attempted to provide all of the information that was requested. I have additionally provided a video that demonstrates the problem, and the original file that causes it, and specified the commands to utilize to reproduce the problem. I am willing to answer any questions of yours.

I consequently do not know how my description of the problem does not adhere to what "https://github.com/PowerShell/PowerShell/issues/17467#issuecomment-1163267570" specifies, so please spsecify.

**Comment by StevenBucher98** [comment]
I believe `cat` does the same thing on linux machines. Would you consider this to be a security issue @PaulHigin? I am not sure if makes sense to changing this behavior

**Comment by PaulHigin** [comment]
@StevenBucher98   Is what a security issue?  What behavior are you thinking about changing?  Please be specific.

**Comment by StevenBucher98** [comment]
@PaulHigin Having `cat` aka `Get-Content` display text from a corrupted file.

**Comment by PaulHigin** [comment]
No, dumping file contents to the terminal, even when it may contain sensitive information, is not a security issue.

**Comment by StevenBucher98** [comment]
Thanks, marking as by design.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This certainly is replicated by `bash`, so I shall close this since you agree that it is desirable. However, I am unable to understand why passing the dumped file's content to the interpreter is desirable. I thought that cat should solely provide the content of the file to the console, rather than attempt to invoke any of what it contains.

Is this not even a bug with cat?

**Comment by RokeJulianLockhart** [comment]
> I thought that `cat` should solely provide the content of the file to the console, rather than attempt to invoke any of what it contains. Is this not even a bug with *it*?

This appears to be expected: [^1]

> If you cat a binary file, there is no knowing what terminal escape sequences you will trigger.

[^1]: [`superuser.com/posts/1268978/timeline#comment_1870035`](https://superuser.com/posts/1268978/timeline#comment_1870035:~:text=If%20you%20cat%20a%20binary%20file%2C%20there%20is%20no%20knowing%20what%20terminal%20escape%20sequences%20you%20will%20trigger.)
