### ISSUE TITLE
Process started by "Start-Process -Wait" cannot start a child process with the 'CREATE_BREAKAWAY_FROM_JOB' flag

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#1748]
Dongbo Wang:
A process started by "Start-Process -Wait" cannot create a child process with 'CREATE_BREAKAWAY_FROM_JOB' flag. The call to create a child process with 'CREATE_BREAKAWAY_FROM_JOB' flag always fails with error code 5 -- Access Denied.

When using 'CREATE_BREAKAWAY_FROM_JOB' flag with 'CreateProcessW', the caller wants the child process of a process associated with a job to not be associated with the job anymore. If any parent process is already associated with a job, then the call with 'CREATE_BREAKAWAY_FROM_JOB' will work only if the job sets the 'JOB_OBJECT_LIMIT_BREAKAWAY_OK' limit. Otherwise, the call will fail with Access Denied error.

"Start-Process -Wait" creates a job without 'JOB_OBJECT_LIMIT_BREAKAWAY_OK' limit and assign the created process to the job. This cause the created process to not be able to create child process with 'CREATE_BREAKAWAY_FROM_JOB' flag.

**Comment by Sum1n** [comment]
https://www.youtube.com/watch?v=8iztXdjBDMw&feature=youtu.be

**Comment by joeyaiello** [comment]
@SteveL-MSFT this one's definitely over my head. Implications? Still relevant?

**Comment by SteveL-MSFT** [comment]
@daxian-dbw what scenario is broken here?

**Comment by daxian-dbw** [comment]
StorSimple team reported an issue over a year ago that they cannot create a process with `CREATE_BREAKAWAY_FROM_JOB` flag in a remote powershell session. It turns out the root cause is that when WinRM creates a powershell process for the remote session, it create a job without the 'JOB_OBJECT_LIMIT_BREAKAWAY_OK' limit and associate the powershell process with the job. Therefore, no child process can be created from a powershell remote session with the `CREATE_BREAKAWAY_FROM_JOB` flag.

I know that `Start-Process -Wait` also creates a job and associate the child process with the job, so the same problem would happen to `Start-Process -Wait` too. However, I'm not aware of any scenario that is blocked by this issue.

**Comment by anmenaga** [comment]
I kind of remember this from WinRM days when we had reliability reports in this area...
Basically, main point of a job is limiting resources (like memory) that can be used by a process/group of processes. So WinRM is restricting PS endpoints using jobs, so that remote PS endpoints would not exhaust machine's resources. (However, this also resulted that in heavy load situations, PS endpoints were getting errors because job's limits were reached)
Another good thing of a job is easy process lifetime management - regardless of how many child processes PS endpoint creates - WinRM can guarantee correct release of resources when endpoint is closed - when it closes the job - all job's processes will be closed.

As I see it - adding 'JOB_OBJECT_LIMIT_BREAKAWAY_OK' flag will basically add a way to client PS code to avoid WinRM's resource and lifetime constraints for PS endpoints.

**Comment by SteveL-MSFT** [comment]
Since we're not making changes to WinRM here, resolving and closing

**Comment by daxian-dbw** [comment]
@SteveL-MSFT this particular issue is not related to WinRM. `Start-Process -Wait` use a job to accurately wait for the child process, so even if you are running in a local powershell console, not a remote session, the child process won't be able to create another child process with `CREATE_BREAKAWAY_FROM_JOB` flag.
