### ISSUE TITLE
Installation Path Changed on Windows Update

### ISSUE THREAD

**Issue by JavaScriptDude** [PowerShell/PowerShell#17490]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I installed pwsh.exe on a custom path on my production server (C:\apps\sdk\pwsh\7\) and I used explicit paths to pwsh.exe in scheduled tasks. After a windows update this weekend, the update for Powershell uninstalled powershell and installed it in the default path (C:\Program Files\PowerShell\7\) by itself. This caused several scheduled tasks to stop.

Is this behavior by design?

### Expected behavior

```console
Installation path should be preserved
```

### Actual behavior

```console
Installation path changed
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### OS Data

```powershell
Version    Caption
-------    -------
10.0.17763 Microsoft Windows Server 2019 Standard
```

### Windows update log

```markdown
tbd
```

**Comment by JavaScriptDude** [comment]
[WindowsUpdate.log](https://github.com/PowerShell/PowerShell/files/8849071/WindowsUpdate.log)

**Comment by kilasuit** [comment]
Currently yes this is by design however it could in future be possible to change this however I do not see this being something that gets a significant amount of engineering effort to accomplish as it is a very niche use case that you have compared to general usage.
Is there a particular reason why you prefer installation in this custom folder other than the default location?
You could always get around this by not allowing Microsoft update to update PowerShell and instead have a process that does this for you via another scheduled task when there is a new update which would resolve your issue entirely & likely mean you get updates quicker than currently possible via Microsoft Update.

Hope the above info helps and can lead to this issue being closed.

**Comment by JavaScriptDude** [comment]
For critical SDK's and tools like python, node.js, Java etc. I like to have easy paths to find and often colocate them. As the option to alter the path for `pwsh` is made available in the installer, I assumed that this would not cause problems. I don't mind using the default path but I suggest removing the option for a customized path until this bug can be fixed as it seem inevitable that this will issue occur with others.

**Comment by jhoneill** [comment]
It's untidy at best, and really if the WU needs the default location, then the initial install shouldn't allow the combination of enabling WU and specifying somewhere else. 

As a workaround to get easy paths create links between where the software wants to go and where you would prefer tit to be.

**Comment by JavaScriptDude** [comment]
I thought of the symbolic links but I believe its possible that WU process would break the symlink. I Instead just put the default install path into the system `PATH` env var to ensure that `pwsh.exe` is resolved automatically when running in `scheduled task`. I'll monitor this over the next few days.

**Comment by MartinGC94** [comment]
"By design"? Surely nobody thought that resetting the user customizable settings on upgrades is a great experience. It feels more like an oversight.

**Comment by adityapatwardhan** [comment]
Currently we do not support updating pwsh installations at a custom path with Windows Update. The Windows Update should not see this installation in update detection, which is a bug.

**Comment by kilasuit** [comment]
Personally I think this issue can be closed but a new one raised (which I will do so) to stop this possibility happening in future so that if you install in a custom path you cannot then make use of Microsoft Update to then update PowerShell as that unfortunately breaks lots of things. Can/will this change? Is a question that I think is outside the scope of the PowerShell Team to answer however they can continue conversations with the Microsoft Update team around this.

**Comment by JavaScriptDude** [comment]
Sounds good.
