### ISSUE TITLE
in renaming, escaping backtick chars, from autocomplete, are kept in the new name

### ISSUE THREAD

**Issue by itmitica** [PowerShell/PowerShell#17591]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have two files:
```
Level[1].html
L1.md
```
I want to rename `L1.md` to `Level[1].md`.

 I type `ren L` and `Tab`:
```
ren .\L1.md
```
I type `Space`, `L` and two `Tabs`:
```
ren .\L1.md '.\Level`[1`].html'
```
I replace `html` with `md` and press Enter:
```
Level[1].html
Level`[1`].md
```

### Expected behavior

```console
Level[1].html
Level[1].md
```
```


### Actual behavior

```console
Level[1].html
Level`[1`].md
```
```


### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
The problem is the tab completer. It assumes that its is completing a PATH parameter that will expand wild cards. 
`Level[12]` is `Level1` or `Level2`  so if the file name is  "level[12]"  it needs to be escaped for use in most places. 

> I type `Space`, `L` and two `Tabs`:

That will call up level[1].html  and ` ren '.\Level`[1`].html' -newName 'somethingelse.html'`  **is** what you'd want    
but ` ren 'somethingelse.html'  -newName '.\Level`[1`].html' ` isn't because newname is treated as a literal path 

Somewhere the argument completer makes an exception if the parameter is named **literalpath** this is what \[Tab\]  fills in 

```
PS> copy -path '.\UwP87`[1`].pdf'

PS> copy -LiteralPath .\UwP87[1].pdf

PS>  function boofar {[CmdletBinding()] Param($LiteralPath) $LiteralPath }

PS>  boofar .\UwP87[1].pdf
```

perhaps the fix is to have the same exception apply to `-NewName` and `-Destination`
