### ISSUE TITLE
Add -NoNewLine to Write-(Information|Warning|Verbose|Debug|Error) Cmdlets

### ISSUE THREAD

**Issue by ev-dev** [PowerShell/PowerShell#17618]
### Summary of the new feature / enhancement

Originally referenced in #5779 

The cmdlet `Write-Host` includes a parameter switch `-NoNewLine` which prevents output of an additional NL character after the string/object is written out, and this parameter should be included with the other `Write-(Information|Warning|Verbose|Debug|Error)` cmdlets. 

Originally, I believed this feature to be a nice-to-have, but more and more I find myself wanting to eliminate this NL when writing output to the alternative streams 2-6 (Error, Warning, Verbose, Debug, Information streams respectively). This is compounded by the fact that PowerShell cannot redirect stream 1 (default success stream) to the alternative streams, which then prevents any hacky way to prevent the NL output.

### Proposed technical implementation details (optional)

Simply include the logic of the `-NoNewLine` switch parameter from `Write-Host` in the cmdlet definitions of:
- [ ] Write-Error
- [ ] Write-Warning
- [ ] Write-Verbose
- [ ] Write-Debug
- [ ] Write-Information

**Comment by jborean93** [comment]
What’s the actual use case here? All these other streams generate an actual object when called and the individual message property inside them does not contain the newline. The newline comes from the relevant `$host.UI.Write[Stream Name]Line()`. Some of the streams prefix the value for each call with the stream name and because this is a host implementation you could find other instances of PowerShell outside of pwsh.exe do something completely different per call, like writing to a log file, create a GUI message box, populate a text box, etc.

The Information stream is a bit more complex still as the record accepts an Object not a string as the record can contain more than just a string. If you are wanting to do custom console/host output with and without newlines you are better off using Write-Host with the colours needed. IMO the other streams should stay as they are.
