### ISSUE TITLE
Add `-MaintainDirectoryStructure` to `Copy-Item`

### ISSUE THREAD

**Issue by WillPittenger** [PowerShell/PowerShell#17615]
### Summary of the new feature / enhancement

When PowerShell replaced cmd.exe, the old `xcopy` command was lost.  Oh, it still works, but doesn't run natively.  We have `Copy-Item`, but it doesn't preserve the directory structure.  All files are simply copied to the destination folder rather than several folders down.  To me, a simple switch solves that problem.

**Comment by iSazonov** [comment]
Doesn't `Copy-Item -Recurse` work for you?

**Comment by WillPittenger** [comment]
As I said, it flattens the structure.

**Comment by iSazonov** [comment]
I guess you catch a bug with coping to root folder.

**Comment by WillPittenger** [comment]
It isn't just roots of drives.  If you search Google for "PowerShell xcopy", you'll see people discussing how to solve the problem.  Did you try it?

**Comment by iSazonov** [comment]
Copy-Item can copy directory structure. But PowerShell providers (including FileSystem provider and Copy-Item cmdlet) have many bugs and many ones already registered in the repository. Please use search. If you can not find please create new issue with clear repro steps and fill all fields in issue template.

**Comment by jhoneill** [comment]
> As I said, it flattens the structure. If you issue `copy ~ v:\ -recurse`, yes, it will recurse. But all items in `~\AppData`, even if several levels down, will be placed directly in `v:\`.

I can't copy all of my windows ~ because it > 100GB but in WSL I tried
```
 New-PSDrive -Name v -PSProvider FileSystem -Root <<temp folder>>
copy ~ V:\ -recurse -verbose 
```
And it copied correctly, creating a <<username>> folder to copy into


Generally I find on windows 
```
copy <somedir> <somewhere> -recurse is fine 
```
Even empty directories are copied. 

In the windows sandbox on windows 11 I tried 
```
copy ~ c:\ -Recurse
```
This gave some errors about permissions to some folders but everything went into c:\WDAGUtilityAccount

Can you give some better repro instructions, because as Ilya says there are some known bugs, but this "flattening" doesn't seem to happen _commonly_ in either 5.1 or 7.2.

**Comment by vexx32** [comment]
Aye, as the others said this sounds more like a bug; `-Recurse` is meant to fill this functionality. Can you please copy the Bug Report template and fill that out so we have better context to address issue here?
