### ISSUE TITLE
Import-Alias suppress errors when same exact alias already exists

### ISSUE THREAD

**Issue by jeffythedragonslayer** [PowerShell/PowerShell#17651]
### Summary of the new feature / enhancement

To cut down on line noise, I think this error should be suppressed when the alias attempting to be imported already exists and is equivalent to what is being imported:

> Import-Alias: The alias is not allowed, because an alias with the name ????? already exists.

**Comment by Pablo1q** [comment]
> ### Summary of the new feature / enhancement
> 
> To cut down on line noise, I think this error should be suppressed when the alias attempting to be imported already exists and is equivalent to what is being imported:
> 
> > Import-Alias: The alias is not allowed, because an alias with the name ????? already exists.
> 
> ### Proposed technical implementation details (optional)
> 
> _No response_


What i have to do?

**Comment by jeffythedragonslayer** [comment]
Hi Pablo,

I'd try adding "if" and "continue" statements to check if the alias that already exists is equivalent to the alias that is trying to be imported around line 154 of this file:

src\Microsoft.PowerShell.Commands.Utility\commands\utility\ImportAliasCommand.cs

**Comment by jhoneill** [comment]
@Pablo1q  - speaking to you in my capacity as a member of the PowerShell Working Group, these bot like posts waste the time of others, so be warned that you may be banned from posting if this is all you post.  
If you have useful contributions to make, those will (of course) be welcome.

**Comment by jhoneill** [comment]
Arguably `New-Alias` and `Import-Alias` should report a warning if the alias exists with the same value, as things are in the state the requested, but no change was required. 
One can run with `-errorAction silentlyContinue` but this will hide errors where the alias is different  or with `-force`  but this will over-write items that are different. 

It should not be silent by default, because warning that the alias exists tells you if you import file A twice, when you intended to import A and then B.   Warnings solve this because you can silence warning and continue to see errors.
