### ISSUE TITLE
Get-Service "sql*" doesn't list SQL Server

### ISSUE THREAD

**Issue by GearTheWorld** [PowerShell/PowerShell#17679]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Windows 11 Pro 

![image](https://user-images.githubusercontent.com/8614008/178843397-bc3eaadd-1e5d-425b-9445-fbb47be0ae27.png)

I am experiencing a problem with Get-Service. I think SQL Server should be listed but I don't see it.

Get-Service "sql*" returns all the sql services except SQL Server which you can see in this screenshot :

![image](https://user-images.githubusercontent.com/8614008/178843419-ebd9d283-bb42-4c7d-bfc1-f5064c85ef36.png)

### Expected behavior

```console
SQL Server should be listed
```

### Actual behavior

```console
SQL Server isn't listed
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.22000.653
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.653
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by jborean93** [comment]
While the `-Name` parameter can find a service by the display name if you use the full name it doesn't do wildcard matching on it. The wildcard matching only occurs on the actual service name and the one you are seeing in the GUI most likely doesn't start with `sql`. If you want to match by displayname you can use the `-DisplayName` parameter which also accepts wildcards.

```powershell
Get-Service -DisplayName 'sql*'
```

This will explicitly match based on the service display name rather than the name itself. As for whether pwsh should match wildcards on displayname using the default `-Name` parameter considering it accepts it as the full value I'm torn. From a consistency it would be nice but it also opens up a whole bunch of problems when it comes to do we display all the matches for both labels or should it keep the matches per type. I personally think it should keep the behaviour as is but maybe expand the docs a bit more to explain it.

**Comment by GearTheWorld** [comment]
If I don't filter and let Get-Service gives me the whole list I still don't see any SQL Server there.

**Comment by GearTheWorld** [comment]
Here's the whole list which SQL Server isn't there

![image](https://user-images.githubusercontent.com/8614008/178882011-c8767dd5-58ad-42d9-b9af-2c12767e7c93.png)

and here's what it looks like in SERVICES

![image](https://user-images.githubusercontent.com/8614008/178882331-9e564973-2481-4bb2-910c-5a6f401afd04.png)

**Comment by GearTheWorld** [comment]
DOH, It's MSSQLSERVER.  oufff ok it's not a bug sorry!

**Comment by GearTheWorld** [comment]
It's horrible that everything starts with SQL except the server.  Shame MS !

**Comment by GearTheWorld** [comment]
Get-Service -DisplayName "*sql*" was a better choice after all ;)
