### ISSUE TITLE
Revisit which assemblies should be crossgen and which should not

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#17732]
### Summary of the new feature / enhancement

PS7 package has gotten quite large.  We should review the list of assemblies we crossgen as part of the build process and see if any that don't affect startup perf should stay MSIL.  Perhaps even assess the startup difference between pure MSIL and crossgen to see if .NET JIT has improved it to the point that it makes more sense to prioritize size over a small perf improvement (of course if the difference is large, we'll need to keep crossgen)

**Comment by iSazonov** [comment]
Since all .Net Runtime dlls are distributed now as crossgened which is 90% of distributive size I would not expect a noticeable reduction in the size of the distribution.

Also it is not clear what is the request about - about package size or unpacked size on disk?

**Comment by SteveL-MSFT** [comment]
The on disk size is the major factor not the pkg size pre-install.   I believe if the build doesn't target a specific runtime, it should not use the crossgen .NET runtime assemblies otherwise it wouldn't work.

**Comment by iSazonov** [comment]
The only way to make pwsh small and fast is to use _shared_ .Net Runtime. That's the only thing we didn't do - we already have an FX distribution and a compiled one too.

**Comment by SteveL-MSFT** [comment]
FX dependent packages can help in some scenarios where .NET Runtime can be installed as a dependent package or it's already there.  However, we have partner scenarios where PS7 is the only .NET app so there's no savings there.

**Comment by iSazonov** [comment]
> However, we have partner scenarios where PS7 is the only .NET app so there's no savings there.

Can you describe the kind of such applications? 
I can assume that this application does not use all the features of the .Net Runtime. (Otherwise there is no way to reduce the size of the application at all.) And if so, we could think of trimming unused dlls.
This in turn brings us back to a project of pwsh partitioning into _subsystems_.
This in turn leads us again to the idea of creating an experimental project of the new generation pwsh (vNext PowerShell) in which gradually implement new (and not so new) ideas for 3 - 5 years.
Now obviously a lot is blocked for the simple reason that we are only working for today. PowerShell was once a technological breakthrough. Perhaps it is time for a new leap into the future? :-)

**Comment by SteveL-MSFT** [comment]
There's a significant savings just by shipping MSIL vs crossgen assemblies.  I'm not sure why you're so against that.  Some of the previous discussions/ideas like subsystem, etc... have turned out to be significant efforts that also have higher risks in terms of regressions.  Our build script used to have a list of assemblies to crossgen while currently it's either compile to ReadyToRun for everything or nothing (fxdependent and forminimalsize pkgs).  I think we can consider a hybrid approach where the assemblies that impact startup should be ReadyToRun and everything else is MSIL.  If we can get a 25-30% size reduction, wouldn't that be worthwhile?

**Comment by iSazonov** [comment]
> I'm not sure why you're so against that

I don't mind :-) I'd prefer a more fundamental solution. :-)

> have turned out to be significant efforts that also have higher risks in terms of regressions.

I understand that and so does your situation. That's why I'm talking about the need for an experimental project. From it, some ideas can be transferred back to pwsh, or backward compatibility elements can be added to adapt it to consumers. This is roughly what happens with the .Net Framework and .Net Core.
I think the ideas in PowerShell are only partially implemented. And I believe that at some point the next era will come.

> If we can get a 25-30% size reduction, wouldn't that be worthwhile?

I think you are too optimistic. 
If we remove crossgen code from pwsh dlls - it is too small effect.
If we remove crossgen code from all dlls including .Net - this reduces size significant but we will have to re-sign the dlls. Then make another package? Is it worth it? Wouldn't it be easier if this partner just repackaged the existing package and removed unnecessary dlls and even crossgen code from it?

Notice, pwsh distributes about 430 dlls but only 69 dlls are loaded at (interactive) startup. So the partner has a great ability to remove unused dlls.
