### ISSUE TITLE
`-Replace` should (be able to easily) `[Regex]::Unescape` the `<substitute>`

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#17826]
### Summary of the new feature / enhancement

Maybe it even qualifies as a bug but it will likely require a break change to correct it and therefore unlikely being resolved as that.
As with this [Powershell script regex single and double quotes](https://stackoverflow.com/questions/73216245), I have seen similar questions before and dealt with this myself a few times.

The [`-Replace` operator](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_comparison_operators#replacement-with-regular-expressions) un-escapes the first parameter `<regular-expression>` but  doesn't do that the same way for the second `<substitute>` parameter:

```PowerShell
'Example: →' -Replace '\u2192', '\u2190'
```
### Expected:
```PowerShell
Example: ←
```
### Actual:
```PowerShell
Example: \u2190
```

You might workaround this by use double quotes and (inconsistently) use the PowerShell escape syntax (e.g. using a backtick `` ` ``):

```PowerShell
'Example: →' -Replace '\u2192', "`u{2190}"
```

But this will also automatically resolve the dynamic substitution (e.g. `$1` as implied by the warning in the [<strike>Regular</strike> expressions substitutions](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7.2#regular-expressions-substitutions) description:

### ⚠️ Warning

The `$` character has syntactic roles in both PowerShell and regular expressions:

> In PowerShell, between double quotation marks, it designates variables and acts as a subexpression operator.
> In Regex search strings, it denotes end of the line.
> In Regex substitution strings, it denotes captured groups. Be sure to either put your regular expressions between single quotation marks or insert a backtick (`` ` ``) character before them.

```PowerShell
'→Example←' -Replace '\u2192(.+)\u2190', '\u2192 $1 \u2190'
```
### Expected:
```PowerShell
→ Example ←
```
### Actual:
```PowerShell
\u2192 Example \u2190
```
To workaround this use double quotes and the *PowerShell* escape syntax which also requires to escape the dollar sign (`$`) in the substitution with a backtick (`` ` ``):
```PowerShell
'→Example←' -Replace '\u2192(.+)\u2190', "`u{2192} `$1 `u{2190}'
```

Which could also be worked around with a longer but more consistent syntax using the [`[Regex]::Unescape` method](https://docs.microsoft.com/dotnet/api/system.text.regularexpressions.regex.unescape):
```PowerShell
'→Example←' -Replace '\u2192(.+)\u2190', [Regex]::Unescape('\u2192 $1 \u2190')
```

### Proposed technical implementation details (optional)

Let the `-Replace` operator accept a `[Regex]` type as an actual *regular expression* for the `<Substitution>` and not blondly convert it to a string.

Wishful thinking:
```PowerShell
'→Example←' -Replace '\u2192(.+)\u2190', [Regex]'\u2192 $1 \u2190'
→ Example ←
```

**Comment by mklement0** [comment]
While it's understandable to want regex escape sequences such as `\u2192` to work in the substitution string, it is important to note that substitution strings by design aren't and _shouldn't be_ regexes themselves, not least because most of the regex constructs would make no sense there.

`[regex]::Unescape()` is _not_ a general solution, because it would result in interpreting `\` instances as part of regex escape sequences, which either inappropriately modifies the string or breaks altogether; e.g.:

```powershell
[Regex]::Unescape('\u2192 a\b') # !! -> '→ a' - \b became "`b", i.e. a backspace
[Regex]::Unescape('\u2192 a\z') # !! -> exception: ... Unrecognized escape sequence \\z."
```

I don't think there's a good solution to this problem: users will have to understand the distinct concepts involved:
* regexes passed as strings to the .NET regex engine
* substitution strings that have a minimal grammar of _only_ recognizing `$`-prefixed tokens as capture-group references (and treating everything else, including `\` verbatim), with `$$` required for escaping a verbatim `$`; that these tokens _look like_ PowerShell variable reference is unfortunate, but here to stay.
* PowerShell string literals that require `"..."` for string interpolation, which requires escaping `$` chars. meant for the .NET regex engine to be escapes as `` `$ ``

**Comment by iRon7** [comment]
@mklement0,
 
> `[regex]::Unescape()` is _not_ a general solution

You're right, I needed some time think this through and see if there weren't some other escapes for this.
But I guess there is indeed no other solution to this problem and my purpose is indeed to simplistic.
