### ISSUE TITLE
`get-help` only reveals the `uri` of the first `navigationLink`

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#17901]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```PowerShell
Get-Help Get-Help
```
```Console
...
RELATED LINKS
    Online Version: https://docs.microsoft.com/powershell/module/microsoft.powershell.core/get-help?view=powershell-7.2&WT.mc_id=ps-gethelp
    about_Command_Syntax
    about_Comment_Based_Help
    Get-Command
    Supporting Updatable Help
    Update-Help
    Writing Comment-Based Help Topics
    Writing Help for PowerShell Cmdlets
...
```
```PowerShell
(Get-Help Get-Help).relatedLinks.navigationLink.foreach{ $_ }
```
```Console
uri                                                                                                                     linkText
---                                                                                                                     --------
https://docs.microsoft.com/powershell/module/microsoft.powershell.core/get-help?view=powershell-7.2&WT.mc_id=ps-gethelp Online Version:
                                                                                                                        about_Command_Syntax
                                                                                                                        about_Comment_Based_Help
                                                                                                                        Get-Command
                                                                                                                        Supporting Updatable Help
                                                                                                                        Update-Help
                                                                                                                        Writing Comment-Based Help Topics
                                                                                                                        Writing Help for PowerShell Cmdlets
```

### Expected behavior

A `uri` listed for each `navigationLink`

### Actual behavior

Only the `uri` of the first `navigationLink` is listed

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
This looks like a problem with the Tools which build the MAML xml, rather than with the `Get-Help` cmdlet. 

For `Get-Help` itself the maml is in ` System.Management.Automation.dll-Help.xml` 

On my system this is in <profile dir>\help\en-us    if I search for `<command:name>Get-Help</command:name>` and then the next set of `relatedlinks` I find this 

```xml
    <command:relatedLinks>
      <maml:navigationLink>
        <maml:linkText>Online Version:</maml:linkText>
        <maml:uri>https://docs.microsoft.com/powershell/module/microsoft.powershell.core/get-help?view=powershell-7.2&amp;WT.mc_id=ps-gethelp</maml:uri>
      </maml:navigationLink>
      <maml:navigationLink>
        <maml:linkText>about_Command_Syntax</maml:linkText>
        <maml:uri></maml:uri>
      </maml:navigationLink>
      <maml:navigationLink>
        <maml:linkText>about_Comment_Based_Help</maml:linkText>
        <maml:uri></maml:uri>
      </maml:navigationLink>
      <maml:navigationLink>
        <maml:linkText>Get-Command</maml:linkText>
        <maml:uri></maml:uri>
      </maml:navigationLink>
      <maml:navigationLink>
        <maml:linkText>Supporting Updatable Help</maml:linkText>
        <maml:uri></maml:uri>
      </maml:navigationLink>
      <maml:navigationLink>
        <maml:linkText>Update-Help</maml:linkText>
        <maml:uri></maml:uri>
      </maml:navigationLink>
      <maml:navigationLink>
        <maml:linkText>Writing Comment-Based Help Topics</maml:linkText>
        <maml:uri></maml:uri>
      </maml:navigationLink>
      <maml:navigationLink>
        <maml:linkText>Writing Help for PowerShell Cmdlets</maml:linkText>
        <maml:uri></maml:uri>
      </maml:navigationLink>
    </command:relatedLinks>
```

So `Get-Help` is correctly showing the links as empty, and  when I hand hacked the last link `Get-Help` showed it correctly.  

The  markdown help at https://github.com/MicrosoftDocs/PowerShell-Docs/tree/main/reference/7.2/Microsoft.PowerShell.Core has this 
```Markdown
## RELATED LINKS

[about_Command_Syntax](About/about_Command_Syntax.md)

[about_Comment_Based_Help](./About/about_Comment_Based_Help.md)

[Get-Command](Get-Command.md)

[Supporting Updatable Help](/powershell/scripting/developer/module/supporting-updatable-help)

[Update-Help](Update-Help.md)

[Writing Comment-Based Help Topics](/powershell/scripting/developer/help/writing-comment-based-help-topics)

[Writing Help for PowerShell Cmdlets](/powershell/scripting/developer/help/writing-help-for-windows-powershell-cmdlets)
```

**So the links which are specified in the markdown help don't make it to the maml file**

Note that 
1.  The `Online Version` link isn't in the markdown and appears to be added at build time (which makes sense as the URL is version specific but we want the same help files to be usable in multiple versions with changes) 
2. When the HTML is built to appear at https://docs.microsoft.com/powershell/module/microsoft.powershell.core/get-help it needs to process relative paths and transform links to a .MD file to links to a help topic  
3.  There is no "PowerShell help" url type (AFAIK) so creating links from MAML help to another local help topic is problematic, and the user needs to request help again, but the process could create a link to on-line help quite easily. 
4. The MAML help builder does not recognise things like "/powershell/scripting/developer/module/supporting-updatable-help" as links which should be built relative to the on-line help link

For my own modules markdown is transformed to MAML with PlatyPS but I don't know what the process is for PowerShell's own help (platyPS alone, platyPS plus something extra or using totally different code) . But **I would say there is definitely a bug somewhere in the MD to MAML Process**  There is no point in including the names of links which are _not_ help topics without their corresponding URI, so either links which do not end .MD should be filtered out, or the correct URI should be built at least for those.

**Comment by jhoneill** [comment]
I've opened bugs for these at https://github.com/PowerShell/platyPS/issues/584  (and 580, 581, 582, and 583)

**Comment by iRon7** [comment]
@jhoneill, Thank you for you investigation and passing this on.

**Comment by daxian-dbw** [comment]
@jhoneill Thanks for the detailed investigation!
