### ISSUE TITLE
Dynamic variable scope is broken for +=

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#17911]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This code now only executes correctly when there's a breakpoint on it.

### Expected behavior

```PowerShell
function Test-Recursively {
    [CmdletBinding()]param($InputObject)
    if ($t -is [string] -and [string]::IsNullOrWhiteSpace($t)) {
        $t += "  "
    } else {
        $t = "  "
    }
    $result = "$t.`n"

    $null, $InputObject = $InputObject
    if ($InputObject) {
        $result += Test-Recursively $InputObject
    }
    $result
}

Test-Recursively 1,2,3
```

Should Output:

```console
  .
    .
      .
```

### Actual behavior

The `if` block doesn't work as expected:

```console
Test-Recursively 1,2,3
  .
  .
  .
```

If I put the code in a file and set a breakpoint on line 4, it works again:

```PowerShell
Set-PSBreakpoint Repro.ps1 4 -Action {}
Test-Recursively 1,2,3
  .
    .
      .
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22622
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/192942/185032828-b5915c9e-4dff-4d1b-b8e2-acdf8bb227c8.png)

**Comment by Jaykul** [comment]
Note that if I change line 4 from:
```PowerShell
        $t += "  "
```
To:
```PowerShell
        $t = $t + "  "
```

This problem goes away. 

It seems like this has been a bug for a long time, but I just don't understand the conditions that cause "+=" to just completely stop doing it's thing.

**Comment by jhoneill** [comment]
I think I have seen this before but it needs someone with better search skills than me - search doesn't like being asked for issues containing += 

```
$i = $i + 1 
$i ++ 
$i += 1 
```
Should be the same.  

The first is `$local:i = $whatever:i + 1 ` 
The last is  `$local:i = $local:i + 1`  and so fails 
I would expect the middle one to work like the last but it works like the first.

Weirdly it is different if I run it in Windows Powershell normally, and `powershell -version 2 -noprofile` 

```
PS>  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22000.832
...

PS>  function Test-Recursively {
>>     param($InputObject)
>>       Write-Verbose -Verbose "t was $t" ; $t += 1
>>      Write-Verbose -Verbose $t
>>      $null, $InputObject = $InputObject
>>      if ($InputObject) { Test-Recursively $InputObject}
>>      $t
>>  }

PS>  test-Recursively 1,2,3
VERBOSE: t was
VERBOSE: 1
VERBOSE: t was 1
VERBOSE: 1
VERBOSE: t was 1
VERBOSE: 1
1
1
1

PS>  powershell -version 2 -noprofile
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.

PS> function Test-Recursively {
>>     param($InputObject)
>>       Write-Verbose -Verbose "t was $t" ; $t += 1
>>      Write-Verbose -Verbose $t
>>      $null, $InputObject = $InputObject
>>      if ($InputObject) { Test-Recursively $InputObject}
>>      $t
>>  }
>>

PS > test-Recursively 1,2,3
VERBOSE: t was
VERBOSE: 1
VERBOSE: t was 1
VERBOSE: 2
VERBOSE: t was 2
VERBOSE: 3
3
2
1
```

**Comment by SeeminglyScience** [comment]
We talked this over a bit over discord and it seems like this is a bug that has existed for a long time, but in this case was masked by Pester code coverage adding breakpoints.

The bug being that the code gen for `+=` statements assumes that the current value is also an optimized local.

So in the case of this scriptblock:

```powershell
$n += 1
```

The optimized code gen will look like this:

```csharp
locals.Item009 = Fake.Dynamic<Func<CallSite, object, object>>(PSVariableAssignmentBinder.Get())(
    Fake.Dynamic<Func<CallSite, object, int, object>>(
        PSBinaryOperationBinder.Get(ExpressionType.Add, ignoreCase: true, scalarCompare: false))(
            locals.Item009,
            1));
```

When it should look like this:

```csharp
locals.Item009 = Fake.Dynamic<Func<CallSite, object, object>>(PSVariableAssignmentBinder.Get())(
    Fake.Dynamic<Func<CallSite, object, int, object>>(
        PSBinaryOperationBinder.Get(ExpressionType.Add, ignoreCase: true,scalarCompare: false))(
             VariableOps.GetVariableValue(Fake.Const<VariablePath>("n"), context, Fake.Const<VariableExpressionAst>("$n"),
             1));
```

The workaround is to use `$n = $n + 1` or `$n++` instead which should be equivalent, but is not in this case due to this bug.

---

Note that this bug also exists in 5.1 (and possibly earlier). Opening up to the Engine WG to discuss as it would be a breaking change.

**Comment by mklement0** [comment]
I think the original issue is #11297 - backstory starts [here](https://github.com/PowerShell/PowerShell/issues/11297#issuecomment-564224819).

**Comment by vexx32** [comment]
WG-Engine discussed this and the related issue #11297 yesterday.

We agree that is is somewhat buggy and inconsistent behaviour that `$a += $b` does not behave the same as `$a = $a + $b` in some circumstances. However, given this was a change made in PowerShell v3 and has remained the same way in the years since, we do not think this level of a breaking change can be accepted. 

Rather, we should look to update our documentation so that users are as aware as possible that this discrepancy exists and know the right ways to work around it when they need to do so.

@sdwheeler I am unsure which document this information should go into, but we need to capture and possibly expand on the notes linked in #11297 - https://github.com/nightroman/PowerShellTraps/tree/main/Basic/Compound-assignment-operators.

Currently it seems as though the only place this is documented is the WMF v3 release notes, so we need to call this out in (I guess?) our operator documentation. I believe this will affect all compound assignment operators (`+=`, `*=`, `-=`, and `/=`) as well.

However, for these issues specifically we determined that there is not going to be an opportunity to change the behaviour, and that doing so is extremely non-trivial due to the nature of how and why the change was introduced. As such, we will be closing these issues as Won't Fix.

**Comment by sdwheeler** [comment]
This is documented in https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_assignment_operators

Please open a Docs issue and provide the information needed in the changes to docs.

**Comment by dkaszews** [comment]
@vexx32 Can we at least get a `Set-StrictMode` error `"use $x = $x + 1 instead of $x += 1"` `$x` is in outer scope? It should be relatively easy to implement in all `op=` operators.

`Set-StrictMode` is such an awesome tool for helping users not to fall into known pitfalls without introduction breaking changes, we should use it more.

**Comment by vexx32** [comment]
Other folks would know better than I do on that, but I don't think there's a reliable way StrictMode could enforce that short of just preventing usage of `+=` and other compound operators completely, without introducing the potential for excessive slowdowns on parsing/running most scripts.

**Comment by dkaszews** [comment]
I can look into it and try to create a PoC that could be measured. Just comparing the target variable scope to the current one sounds like it would work.

**Comment by dkaszews** [comment]
Actually, I did more testing and I think the proper resolution is to add new `Set-StrictMode` version to not allow compound assignment operate on non-existent variables. Since compound assignment have to retrieve the value anyway, it would see it does not exist and error out, without any performance impact. In the error, we could say that it does not use dynamic scope, so use long form instead if you want this behavior:

```pwsh
> function Test-Increment { $x++; $x }
> function Test-Assign { $x = $x + 1; $x }
> function Test-CompoundAssign { $x += 1; $x }
> Set-StrictMode -Version 3.0
> Test-Increment
InvalidOperation: The variable '$x' cannot be retrieved because it has not been set.
InvalidOperation: The variable '$x' cannot be retrieved because it has not been set.
> Test-Assign
InvalidOperation: The variable '$x' cannot be retrieved because it has not been set.
> Test-CompoundAssign
1
```

I can create a new issue with feature request for the `Set-StrictMode -Version 4.0`, and we can keep this one closed as won't fix to not introduce breaking behavior without opt-in.

**Comment by sdwheeler** [comment]
@vexx32 Is the null-coalescing assignment operator `??=` considered a compound operator? For example, does is support dynamic scoping?
