### ISSUE TITLE
Cleanup volume requires root? Please direct 

### ISSUE THREAD

**Issue by Ray0light** [PowerShell/PowerShell#17950]
https://github.com/Ray0light/docker-cleanup-volumes/blob/1.7.0/docker-cleanup-volumes.sh

**Comment by StevenBucher98** [comment]
Please follow our issue creation [templates](https://github.com/PowerShell/PowerShell/issues/new?assignees=&labels=Needs-Triage&template=Bug_Report.yaml). We are unable to properly help unless we know clearly what the expected behavior, problem occuring, reproducing step and relevant environment information.
