### ISSUE TITLE
`ls` breaks down when path name contains hyphen enclosed in escaped brackets

### ISSUE THREAD

**Issue by LqkUWp** [PowerShell/PowerShell#17992]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a file `.\o\abc [defg-0 hijk -lmn].pdf`. Then I try all commands below to `ls` it. The first char y/x represents that the corresponding command works or not, i.e. prints the file or throw out error which is in 'Error details' part. 

```
y ls '*`[defg*0 hijk -lmn`].pdf' -Recurse
y ls '*defg-0 hijk -lmn*.pdf' -Recurse
x ls '*`[defg-0 hijk -lmn`].pdf' -Recurse
```

### Expected behavior

```console
All three commands above work fine, i.e. print the file specified.
```

### Actual behavior

```console
Just as the first char y/x in each command line shows. It seems that hyphen is recognized as a special char although brackets are escaped.
```

### Error details

```console
Get-ChildItem: Cannot retrieve the dynamic parameters for the cmdlet. The specified wildcard character pattern is not valid: *\[defg-0 hijk -lmn\].pdf
```
```


### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by iSazonov** [comment]
I think this was already covered by https://github.com/PowerShell/PowerShell/issues/12168#issuecomment-611241092 and should be reported there.

**Comment by jhoneill** [comment]
@iSazonov  looking at the error, it seems that somewhere in processing the parameters something is not seeing ``` `[  ``` and ``` `] ``` as escaped and is trying to process what is inside the ` [   ... ] ` as a wildcard expression

@LqkUWp  specifying -LiteralPath will prevent this happening.

**Comment by iSazonov** [comment]
@jhoneill If I remember correctly PowerShell doesn't use exact parser for wildcards to get perf win. As result there are some problems. Also there is an conceptual problem since PowerShell allows wildcards in LiteralPath.

**Comment by iSazonov** [comment]
> > Also there is an conceptual problem since PowerShell allows wildcards in LiteralPath.
> 
> Note that on Unix-like platforms `*` and `?` are legitimate filename characters, so `-LiteralPath` _should_ (and does) allow them.

So question is does it make sense to allow wildcards in LiteralPath if we have Path?

**Comment by jhoneill** [comment]
> 

We have `filter`  which passes the characters to the Windows API which treats `*` and `?` but not `[ ]` as wildcards (not sure what happens on linux but it may treat them differently)

We have `literalpath` which should treat _nothing as wildcards_ even though on windows * and ? are forbidden by the filesystem, on linux that would be how you request a file with those characters. 

And `path` which treats all 3 as wildcards, unless they are backquoted (the backquote is a requirement of the class, not PowerShell syntax). However backquoted characters are not always processed correctly. 

Since `-literalpath`  does not work with -recurse ,  `-filter`  will work for this case, but the -path won't because of the backquote problem.

**Comment by mklement0** [comment]
@iSazonov, it's implied by @jhoneill's comment, but to spell it out: 
* On Unix, it absolutely makes sense, because you can have files literally named `a*b.txt` for instance (though it's probably not a good idea.
* On Windows, _as a nicety_, we could perform a formal check up front to preclude use of `*` and `?` in `-LiteralPath` arguments, given that from the perspective of the file-system APIs no such files can exist, but I personally don't think that's necessary and I'm not even sure what would happen if you tried `-LiteralPath a*b.txt` on a file share hosted on a Unix server where such a file could exist (I don't know enough about APIs, SMB protocols, ... to know that).

@jhoneill, good points, but I don't understand what you mean by `-LiteralPath` not working with `-Recurse`. Note that if you want to use _PowerShell_'s wildcards in this scenario, use `-Include` rather than `-Filter`. Not sure if the backtick problems affect `-Include` too, but at least it works with the failing command in the initial post: ``gci -include '*`[defg-0 hijk -lmn`].pdf' -Recurse``

**Comment by jhoneill** [comment]
@mklement0   The literal path thing
From my powershell directory  `dir -LiteralPath "profile.ps1" `  finds my profile. From there if I do. 

```
 cd ..  
dir -LiteralPath "profile.ps1" -Recurse
```
gives error `dir : Cannot find path 'C:\Users\me\Documents\profile.ps1' because it does not exist.`

` dir -Filter "profile.ps1" -Recurse` works and passes the text to the underlying API (so on Windows `*` and `?` are wildcards and ``` ` ``` and . `[  ]` have no meta-functions)
`dir -include "profile.ps1" -Recurse ` also works and I haven't checked what the wild cards and escapes do

**Comment by mklement0** [comment]
Unlike `-Filter`, `-Include` and `-Exclude` use _PowerShell_ wildcards and therefore also support `[...]` constructs.

> `dir -LiteralPath "profile.ps1" -Recurse`

if `profile.ps1` isn't in the current dir., that is the expected - and sensible - behavior: you're specifying the literal paths to match in the _current_ directory, and recursion is then to be performed on whatever matches _there_.

That `dir -Path profile.ps1 -Recurse` _does_ find `profile.ps1` in _subdirectories_ is highly unfortunate and can have destructive consequences - see
 * https://github.com/PowerShell/PowerShell/issues/5699

**Comment by iSazonov** [comment]
(We could make `dir -Recurse "profile.ps1"` (that is `dir -Recurse -Path "profile.ps1"`) equivalent to `dir -Recurse -Include "profile.ps1"` by new parameter set.)

**Comment by jhoneill** [comment]
> > `dir -LiteralPath "profile.ps1" -Recurse`
> 
> if `profile.ps1` isn't in the current dir., that is the expected - and sensible - behavior: you're specifying the literal paths to match in the _current_ directory, and recursion is then to be performed on whatever matches _there_.

Yes. I forget this and rediscover it about once every couple of years. I asked a group of experts and everyone initially thought literal path is just path without wildcard processing.

`dir -Recurse -Path  "profile.ps1" `  works like  `dir  -Recurse -Include "profile.ps1" ` ,   and 
`dir -Recurse -LiteralPath "profile.ps1" `  does something different.    
The help descriptions of `path` and `literalPath` don't lead people to understanding the difference and there are no `literalpath` examples. It is working as designed, but the design comes as a surprise to many.  

` dir -Recurse -literalpath .\PowerShell\readme.md `  tries to recurse through  a non-existent readme.md directory but   
` dir -Recurse -path .\PowerShell\readme.md ` recurses through all subdirectories looking for readme.md  -path seems to split into parent and child parts, and do different things if the child is a file or a directory. 

`Include` has its own annoyances
1. without `-recurse` neither  `dir -include profile.ps1` nor `dir  . -include profile.ps1` return a file from the current directory, one must specify `dir * -include profile.ps1` (assuming * here would not break anything). 
2.  `dir -path .\PowerShell\,.\WindowsPowerShell\ -Include profile.ps1` returns nothing (it requires `.\PowerShell\*,.\WindowsPowerShell\*`  and again * could be assumed) but...
3.  `-Include` and `-exclude` don't apply when used with literalpath  (`dir -LiteralPath .\PowerShell -Include *.psm1`  returns everything)

Fortunately the bug in this issue - which I think is validating the path parameter - does not affect `-Include` so        
`dir -include '* `[defg-0 hijk -lmn`].Txt' -Recurse`  works 

This is all harder than it needs to be :-(

**Comment by mklement0** [comment]
> This is all harder than it needs to be :-(

Amen to that.

If backward compatibility weren't in the picture, I would eliminate the implicit recursion based on the leaf component of the `-Path` component altogether - it is simply too treacherous and confusing.

That is, the only way to search for a name or pattern in _all_ directories of the subtree would then be to use either `-Filter` or `-Include`, and both `-Path` and `-LiteralPath` would consistently only specify the _starting point_ for `-Recurse`.

Therefore, @iSazonov, backward compatibility also gets in the way of your suggestion, because you can (unfortunately) currently do something like `Get-ChildItem $Home/*.txt -Recurse` too look for `*.txt` files in the entire subtree, which would break if `$Home/*.txt` were to bind to `-Include`.
