### ISSUE TITLE
.Split([Environment]::NewLine not splitting by new lines

### ISSUE THREAD

**Issue by stephen147** [PowerShell/PowerShell#18010]
### Prerequisites

- [x] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`Split([Environment]::NewLine` doesn't work as it should. 

In v5.1 of  PowerShell returns 3 from the code below whereas in v7 it doesn't

### Expected behavior

```console
PS > ("test`rtest`rtest".Split([Environment]::NewLine,[StringSplitOptions]::None)).count
3
```

### Actual behavior

```console
PS > ("test`rtest`rtest".Split([Environment]::NewLine,[StringSplitOptions]::None)).count
1
```

### Environment data

```powershell
PSVersion                      5.1.19041.1682                                                      
PSEdition                      Desktop                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                             
BuildVersion                   10.0.19041.1682                                                     
CLRVersion                     4.0.30319.42000                                                     
WSManStackVersion              3.0                                                                 
PSRemotingProtocolVersion      2.3                                                                 
SerializationVersion           1.1.0.1
```

**Comment by 237dmitry** [comment]
```powershell
PS > [int[]][char[]][environment]::NewLine    # `r`n
13
10

PS > [int[]][char[]] "`r`n"
13
10
```

**Comment by jhoneill** [comment]
There are multiple .SPLIT methods and if you pass a string a different one gets select in PowerShell 5/ .NET Framework 4 compared with PowerShell 6/7 and .NET core / .NET 6

```
>  ("test`rtest`rtest".Split("`r`n",[StringSplitOptions]::None)).count
3

"123456789".Split("369")
12
45
78
```
There it splits by 3 or 6 or 9 -  "369" is **converted to a [char[]]**

In PowerShell 6 or 7  (.NET core / .NET 6) it split by 369 - (i.e. it doesn't split 123456789  , but will split 123694578 ) because "369" **remains as a string** . I can't say *why* this is but to me, passing the string when it is accepted (not changing type) looks like the more correct behaviour.    

To make 6/7 behave like 5 needs
```
 ("test`rtest`rtest".Split([char[]][Environment]::NewLine,[StringSplitOptions]::None)).count
```

However this will not work on mac/linux PowerShell where `[Environment]::NewLine` is only ``` `n```

A more reliable way is to use the split operator  ``` -split "`r`n|`n|`r" ```  to keep blank lines or  ``` -split "[`r`n]+```  to treat multiple line breaks as one. The first says "try for cr lf first, then lf, then cr" the second says any sequence of cr and lf

**Comment by stephen147** [comment]
Thanks all,

I've ended up using `-split '\r?\n'` as this seems the most robust method.
