### ISSUE TITLE
CIM-Session through SMB port 445 (RPC over SMB)

### ISSUE THREAD

**Issue by TomaszPograniczny** [PowerShell/PowerShell#18073]
### Summary of the new feature / enhancement

Hey,
I'm using CIM-Sessions to spare resources it works really nice because it is possible to use DCOM (RPC port 135) so i don't need to enable wsman, i used wireshark to look how works sc.exe and i saw that it uses first RPC port 135 when it doesn't work it switch to RPC over SMB at port 445. I Through that it might be possible to use New-CIMSession through RPC over SMB (port 445) but here in New-CIMSession -protocol is not possible to set SMB.

Thanks in advice

### Proposed technical implementation details (optional)

$SessionOption = New-CimSessionOption -Protocol **SMB**
New-CimSession -ComputerName Server1 -SessionOption $SessionOption

**Comment by jborean93** [comment]
A CIM session is different from an RPC over SMB port. They use different protocols to format the messages and aren’t really comparable. The RPC stuff is also not generic across protocols as it requires you to send very specific payloads to specific endpoints depending on what you are talking to. What you are looking for isn’t really possible to do in a session like interface which is why the common method these days is to use Invoke-Command to run whatever PowerShell code you want on the target. This can be done through WinRM on Windows hosts but also now support SSH for non-Windows and Windows hosts with both ssh installed/configured + pwsh 6+.

**Comment by TomaszPograniczny** [comment]
Thanks for info. 
I Through that if sc.exe can communicate through port 135 as RPC and 445 RPC over SMB than maybe it could be possible to send another commands through RPC over SMB to read data or make changes to remote server. Like Invoke-CimMethod or Get-CimInstance. If CIM Sessions can't have so possibility is another command in powershell which can get data from RPC over SMB? 
I found that sc.exe and get-printer can use RPC over SMB. RPC over SMB communication could be nice alternative to WinRM or RPC both are mostly blocked with firewall but SMB is in use and RPC over SMB works.

**Comment by jborean93** [comment]
> I Through that if sc.exe can communicate through port 135 as RPC and 445 RPC over SMB than maybe it could be possible to send another commands through RPC over SMB to read data or make changes to remote server

It is possible but those APIs must be exposed through an RPC mechanism. Unlike WMI/CIM/PSRemoting there isn’t a common mechanism. Some things have it while others don’t. For example the API to manipulate services and to get remote processes might both run over RPC through SMB but the actual bytes that are exchanged is not unified and varied based on the API.

> RPC over SMB communication could be nice alternative to WinRM or RPC both are mostly blocked with firewall but SMB is in use and RPC over SMB works.

It is certainly possible to use this through PowerShell, in Windows PowerShell (5.1 and earlier) the service cmdlets could do this with the `-ComputerName` parameter. While this parameter is not longer present on pwsh 6+ you can still use the relevant dotnet APIs instead. Ultimately they aren’t very flexible because the number of things you can do over RPC is far lower than CIM/WSMan. Your best bet is to actually enable the ports needed for PSRemoting/CIM rather than try to use RPC over SMB. You’ll be able to do so much more with it, e.g. run any powershell command you want.

**Comment by TomaszPograniczny** [comment]
Ok, thanks for info, so i need to look at .NET and Windows API
