### ISSUE TITLE
Incorrect error position reported when $ErrorActionPreference = 'Stop' and [Parameter(Mandatory)] exists

### ISSUE THREAD

**Issue by shinfd** [PowerShell/PowerShell#18097]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I ran the following PowerShell script

```powershell
$ErrorActionPreference = "Stop" # (A)
function Inner2 {
	param (
		[SecureString] $SecureName
	)
}
function Inner1 {
	param (
		[Parameter(Mandatory)] # (B)
		[string] $Name
	)
	Inner2 -SecureName $Name # ParameterArgumentTransformationError
}
function Func {
	param (
		[string] $Name
	)
	Inner1 -Name $Name # Unless (A) or (B) is commented out, PowerShell points to this line as source of error
}
Func -Name Hello
```

### Expected behavior

Below error is shown, regardless of the existence of $ErrorActionPreference or [Parameter(Mandatory)].

```console
Line |
  13 |      Inner2 -SecureName $Name # ParameterArgumentTransformationError
     |                         ~~~~~
     | Cannot process argument transformation on parameter 'SecureName'. Cannot convert the "Hello" value of
     | type "System.String" to type "System.Security.SecureString".
```

### Actual behavior

PowerShell interpreter points to wrong line as the source of the error.

```console
Line |
  19 |      Inner1 -Name $Name # Unless (A) or (B) is commented out, PowerShe …
     |      ~~~~~~~~~~~~~~~~~~
     | Cannot process argument transformation on parameter 'SecureName'. Cannot convert the "Hello" value of
     | type "System.String" to type "System.Security.SecureString".
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Details

The above symptom looks very similar to one reported in #14308 which also involves `$ErrorActionPreference = "Stop"`, but this one uses `[Parameter(Mandatory)]` instead.

**Comment by jhoneill** [comment]
Annoying as it seems this is by design. 

When you call a cmdlet and there is an **unrecoverable** error it doesn't tell you where in the cmdlet the error occurred, you just get  "there was an error running  cmdlet Get-Widget ..."  

`$ErrorActionPreference = 'stop'` makes errors which would be **recovered** simply by printing the message unrecoverable

When you have a  _basic_  function like this 
```
function one {
1/0
}
```
an unrecoverable error is reported as the line of PowerShell code where it happened. 
```
PS> $ErrorActionPreference = 'stop' 
PS> one

ParentContainsErrorRecordException:
Line |
   2 |  1/0
     |  ~~~
     | Attempted to divide by zero.
```
but if the function is made into advanced function / script cmdlet for example, like this 
```
function one { [cmdletbinding()] Param()
1/0
}
```
the unrecoverable error is reported **as it would be for a compiled cmdlet.** 
```
PS> $ErrorActionPreference = 'stop' 
PS> one
one: Attempted to divide by zero.
```
In other words "the cmdlet had an error and there is no point in telling the details because you can't recover from it"     
but if we make the error **recoverable:**
```
PS>  $errorActionPreference = "Continue"
PS>  one
RuntimeException:
Line |
   2 |  1/0
     |  ~~~
     | Attempted to divide by zero.
```
That is : "Here are the details, so something can decide what to do next"  

You don't have `[cmdletBinding()]` in your code but if any of the parameters in a function have attached attributes `[alias()]`, `[Validatexxx()]`, `[Allowyyy()]` or `[paramater()]` **then  `[cmdletBinding()]` is implied.**

Recoverable errors are either handled are passed up to the caller for handling, 
$ErrorActionPreference = `continue`, means that when the error can't be passed up any further, printing the message is considered to be sufficient handling to continue at the next line, and  `silentlycontinue` considers doing nothing is sufficient.   

In this 
```
 function one { [cmdletbinding()] Param()
1/0 ; "One finished"
}
function two   {one    ; "Two   Finished"}
function three {two    ; "Three Finished"}

PS> $ErrorActionPreference = "Continue"
PS> three


RuntimeException:
Line |
   2 |  1/0 ; "One finished"
     |  ~~~
     | Attempted to divide by zero.
One finished
Two   Finished
Three Finished
```
The recoverable error in `one` passes up to `two`, `two` doesn't handle it so it goes up to `three` which doesn't handle it either so there error is passed back to the PowerShell session which says "Print the message and tell everything to continue"

if we put 
```
PS> try {three ; "message"} catch {"error occurred"}
error occurred
``` 
Now, handling the recoverable error which bubbled up results in the text output but `catch` means execution **stops**
   
When a recoverable error is passed up and error action is `stop` that it is wrapped in an unrecoverable error. 

Although the display is different if you run your inner1 from the prompt, 
```
PS> $errorActionPreference = "stop"
PS>   Inner1 -Name hello
Inner1: Cannot process argument transformation on parameter 'SecureName'. Cannot convert the "hello" value of type "System.String" to type "System.Security.SecureString".
```

You can see the command considered to be behind the error being received  through `$error[0].errorrecord.InvocationInfo` (it's inner1 -name Hello) and you can get to wrapped error like this:
```
PS>  $Error[0].innerException.errorrecord
Inner2:
Line |
   6 |  Inner2 -SecureName $Name # ParameterArgumentTransformationError
     |                     ~~~~~
     | Cannot process argument transformation on parameter 'SecureName'. Cannot convert the "hello" value of type "System.String" to type "System.Security.SecureString".
```

 Yes it's frustrating that the error is "something wrong inside this 200 line function", but no-one has yet figured out a good way to decide if using an inner exception (and there may be more than one) gives more useful information.
