### ISSUE TITLE
Piping ssh output to cmdlet with debug breakpoint crashes PowerShell

### ISSUE THREAD

**Issue by hmmwhatsthisdo** [PowerShell/PowerShell#18117]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Piping output from `ssh` (more specifically `cat`ing some syslogs) into a cmdlet with a breakpoint set causes PowerShell to crash as soon as the breakpoint is hit.

I hit this while trying to debug my [`ConvertFrom-RegEx` module](https://github.com/hmmwhatsthisdo/ConvertFrom-RegEx), but given that I have a 100% crash-rate no matter where the breakpoint is I don't think this is something to do with my code. (Even then, the debugger/pwsh executable crashing isn't ideal.)

Storing `ssh` output into a variable and piping that variable into the cmdlet with breakpoints works normally. Perhaps `ssh` is preventing the debugger from calling ReadKey()?

### Expected behavior

```console
PS> pushd $HOME\source\repos
PS> ipmo .\ConvertFrom-RegEx\ConvertFrom-RegEx # repo hmmwhatsthisdo/ConvertFrom-RegEx, commit f18a0a46
PS> Set-PSBreakpoint -Script .\ConvertFrom-RegEx\ConvertFrom-RegEx\Public\ConvertFrom-RegEx.ps1 -Line 135 
PS> ssh $remoteuser@$remoteip -i $HOME\.ssh\$remoteuser-id_rsa cat /var/log/syslog | ConvertFrom-RegEx -Pattern '^(?<month>\S+)'
# [PowerShell hits debugger breakpoint]
```

### Actual behavior

```console
Debugger crashes upon hitting breakpoint
```

### Error details

```console
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception. System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadOneOrMoreKeys()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKeyThreadProc()
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()
```

### Environment data

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/2093321/190854706-7279366b-1618-4b09-8726-dae23e57ea21.png)

**Comment by dkaszews** [comment]
Have you tried saving the ssh output to a variable and then piping that variable into your script? I would guess the issue is that ssh intercepts your input, and because you are piping it's output into the script, it is still active when the breakpoint hits, causing the issue. By saving to a variable first, you ensure that only one interactive process runs at a time.

If that is indeed the case, I don't see how PowerShell can handle it, it's the same why I don't expect `vim | vim -` to ever work. Though you may raise a bug in ssh that they shouldn't do any terminal intercepts when running a command instead of interactive prompt.

**Comment by hmmwhatsthisdo** [comment]
> Have you tried saving the ssh output to a variable and then piping that variable into your script?

I did, and it worked as expected.

> If that is indeed the case, I don't see how PowerShell can handle it, 

I agree with you that the situation leading this behavior is non-ideal, but the impetus behind filing an issue is that there are several more-graceful ways to handle the situation than crashing the PowerShell process. For comparison, PS 5.1 is able to enter the debugger (and accept keyboard debugger input) at the specified breakpoint without crashing.

If the debugger can't attach to the console input due to another process, then there should be a [non-fatal] error indicating the debugger cannot be initialized in that manner. Alternatively, if an external debugger is attached via PSES/etc., then it's possible (maybe even likely) the console debugger interface isn't being used at all.

> you may raise a bug in ssh

Again, I don't think this is ssh's "fault" - any other process could lock stdin. The issue here is that when the debugger is running alongside, PowerShell crashes.

**Comment by hmmwhatsthisdo** [comment]
@iSazonov, would this be more appropriate for WG-Interactive-Debugging instead of WG-Remoting? I know the screenshot mentions `ssh`, but PowerShell is running entirely locally and it's highly unlikely this is germane to `ssh` itself (versus any other process that captures terminal input).

**Comment by dkaszews** [comment]
> there are several more-graceful ways to handle the situation than crashing the PowerShell process

@hmmwhatsthisdo Fair point, even if some process locks input, debugger could try to detect it and show an error "Unable to debug interactive process" instead.

**Comment by jhoneill** [comment]
> there are several more-graceful ways to handle the situation than crashing the PowerShell process.

There are.  `An error has occurred that was not properly handled... The PowerShell process will exit.` Is the generic "we didn't anticipate this...", now it's been pointed out, something that causes PowerShell to crash should be trapped. . 

> For comparison, PS 5.1 is able to enter the debugger (and accept keyboard debugger input) 

I'm surprised that something has changed so that it stopped working - I would have expected never to have worked. Possibly whatever 5.1 did can be brought into 7 to allow you to enter the debugger, possibly there has been a change where the best you'll get is the error being properly handled.

> If the debugger can't attach to the console input due to another process, then there should be a [non-fatal] error indicating the debugger cannot be initialized in that manner. 

This sounds ideal, but as you said, there's more than one way.  

> I don't think this is ssh's "fault" 

You're correct.  The unhandled error is "Cannot read keys when either application does not have a console or when console input has been redirected" so this could come from _anything_. ssh is **unusual** in doing this for one scenario (a terminal session) where you wouldn't have output to pipe, AND supporting running a command whose output might go into a pipeline. But I doubt if it is **unique**.  
Changing ssh to work differently, is a large change that is difficult to make, changing PowerShell to not crash is smaller, easier to change and applies to other things. No prizes for guessing what the right thing to do is, this isn't a common scenario so I don't see it jumping to the front of the queue, but it should be accepted that it's a bug.

**Comment by PaulHigin** [comment]
Removing the WG-Remoting tag because this does not involve PowerShell remoting, and appears to be a bug in PowerShell during command line debugging.

**Comment by hmmwhatsthisdo** [comment]
Still reproduces on 7.3.9:
![image](https://github.com/PowerShell/PowerShell/assets/2093321/e85f9691-7305-4df1-8dd1-90e1c9229535)

**Comment by JamesWTruher** [comment]
I tried the following on 7.4.0 and all seems well

```powershell
PS> cat /tmp/file.txt
this is line 1
this is line 2
<snip for space>
this is line 15
this is line 16
PS> cat /tmp/readit.ps1
[CmdletBinding()]
param ([Parameter(ValueFromPipeline=$true)]$line)

PROCESS {
    if ( $line -match "15") {
        wait-debugger
    }

    if ( $line -match "8") {
        "This is a special line"
    }
    "I received line: '$line'"
}
PS> get-psbreakpoint

  ID Script                                                 Line Command                                               Variable                                              Action
  -- ------                                                 ---- -------                                               --------                                              ------
   1 readit.ps1                                               10

PS> ssh localhost cat /tmp/file.txt | /tmp/readit
I received line: 'this is line 1'
<snip for space>
I received line: 'this is line 7'
Hit Line breakpoint on '/tmp/readit.ps1:10'

At /tmp/readit.ps1:10 char:9
+         "This is a special line"
+         ~~~~~~~~~~~~~~~~~~~~~~~~
PS> c
This is a special line
I received line: 'this is line 8'
<snip for space>
I received line: 'this is line 14'
At /tmp/readit.ps1:6 char:9
+         wait-debugger
+         ~~~~~~~~~~~~~
PS> c
I received line: 'this is line 15'
I received line: 'this is line 16'
```

I didn't try reproducing this with your script.
I'm also running on a MAC which might have different behavior
Could you try reproducing this on 7.4?
