### ISSUE TITLE
Putting 'winget upgrade | Out-String' in a var result with bad character (i'm using french Windows)

### ISSUE THREAD

**Issue by ernest33** [PowerShell/PowerShell#18156]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```PoweShell
winget upgrade | Out-String
```

### Expected behavior

```console
winget upgrade
Nom                                                          ID                           Version          Disponible   Source
------------------------------------------------------------------------------------------------------------------------------
Stardock Curtains                                            Stardock.Curtains            1.2              1.19.1       winget
Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.30501 Microsoft.VC++2013Redist-x64 12.0.30501.0     12.0.40664.0 winget
JetBrains ETW Host Service (x64)                             JetBrains.ReSharper          2022.2.2         2022.2.3     winget
Windows Software Development Kit - Windows 10.0.19041.685    Microsoft.WindowsSDK         < 10.0.22000.832 10.0.22621.1 winget
MSYS2 64bit                                                  msys2.msys2                  20220603         20220904     winget
Windows Software Development Kit - Windows 10.0.17763.132    Microsoft.WindowsSDK         < 10.0.22000.832 10.0.22621.1 winget
MySQL Installer - Community                                  Oracle.MySQL                 1.6.3.0          8.0.30       winget
Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.30501 Microsoft.VC++2013Redist-x86 12.0.30501.0     12.0.40664.0 winget
8 des mises à niveau sont disponibles.
1 package(s) have version numbers that cannot be determined. Use "--include-unknown" to see all results.
```

### Actual behavior

```console
Nom                                                   ID                           Version          Disponible   Source
-----------------------------------------------------------------------------------------------------------------------
Stardock Curtains                                     Stardock.Curtains            1.2              1.19.1       winget
Microsoft Visual C++ 2013 Redistributable (x64) - 12ÔÇª Microsoft.VC++2013Redist-x64 12.0.30501.0     12.0.40664.0 winget
JetBrains ETW Host Service (x64)                      JetBrains.ReSharper          2022.2.2         2022.2.3     winget
Windows Software Development Kit - Windows 10.0.1904ÔÇª Microsoft.WindowsSDK         < 10.0.22000.832 10.0.22621.1 winget
MSYS2 64bit                                           msys2.msys2                  20220603         20220904     winget
Windows Software Development Kit - Windows 10.0.1776ÔÇª Microsoft.WindowsSDK         < 10.0.22000.832 10.0.22621.1 winget
MySQL Installer - Community                           Oracle.MySQL                 1.6.3.0          8.0.30       winget
Microsoft Visual C++ 2013 Redistributable (x86) - 12ÔÇª Microsoft.VC++2013Redist-x86 12.0.30501.0     12.0.40664.0 winget
8 des mises ├á niveau sont disponibles.
1 package(s) have version numbers that cannot be determined. Use "--include-unknown" to see all results.
```

### Error details

```console
By exemple check the line about 'Microsoft Visual C++ 2013 Redistributable (x64)'
Expected 
Windows Software Development Kit - Windows 10.0.17763.132    Microsoft.WindowsSDK         < 10.0.22000.832 10.0.22621.1 winget
But currently i got 
Windows Software Development Kit - Windows 10.0.1904ÔÇª Microsoft.WindowsSDK         < 10.0.22000.832 10.0.22621.1 winget
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.8
PSEdition                      Core
GitCommitId                    7.3.0-preview.8
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
When PowerShell runs a native command the raw output from that command is seen as a bunch of bytes. It needs to have a way to convert those bytes to a string using an encoding format. In PowerShell's case it uses the value of `[System.Console]::OutputEncoding` which based on your error I guess is the code page `850`. The trouble here is it looks like `winget` is always outputting the bytes using the UTF-8 encoding. We can see this by looking at the expected output

> 8 des mises à niveau sont disponibles.

This is seen as the following string value in PowerShell when it decodes those bytes

> 8 des mises ├á niveau sont disponibles.

We can see that `à` now becomes `├á`. By testing this assumption, the UTF-8 byte encoding of [à U+00E0](https://www.compart.com/en/unicode/U+00E0) is `0xC3, 0xA0`. On a French system the default console codepage is [850](https://en.wikipedia.org/wiki/Code_page_850) and by using the character map we can see the bytes `0xC3 0xA0` map to `├á` giving us the string we see in PowerShell. You'll find the other differences are also caused by chars beyond the standard ASCII range (0-127) being encoded with UTF-8 but being read using the default console code page of 850 causing these problems.

The workaround this problem is to either get the native application to respect the console code page setting, or by explicitly telling PowerShell what encoding to use by setting `[System.Console]::OutputEncoding`. For your case you can do

```powershell
$origEncoding = [System.Console]::OutputEncoding
try {
    [System.Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
    winget upgrade | Out-String
}
finally {
    [System.Console]::OutputEncoding = $origEncoding
}
```

If you don't care about preserving the existing value you can just do

```powershell
[System.Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
winget upgrade | Out-String
```

Keep in mind this is a process wide setting and not something scoped inside PowerShell itself.

**Comment by jhoneill** [comment]
@jborean93  I don't think it is a code page thiing 

```
> winget list
... 

Microsoft ASP.NET Core 6.0.9 - Shared … Microsoft.DotNet.AspNetCore.6
```

Note the file is clipped and the ellipsis is a 16 bit character.  (8230 decimal) 

```
$v = winget list
$v[-2]
Microsoft ASP.NET Core 6.0.9 - Shared ÔÇª Microsoft.DotNet.AspNetCore.6           6.0.9   ...
```
Bring the text in as 8-bit ASCII and the ellipsis and the 2 byte character becomes ` ÔÇª ` .

**Comment by jborean93** [comment]
Your example shows that it is. An [ellipsis](https://www.compart.com/en/unicode/U+2026) when encoded through UTF-8 (what winget does) is `0xE2 0x80 0xA6` (note 3 bytes not 2). These bytes when encoded using the 850 codepage is `ÔÇª` as you've seen in the output.

**Comment by jhoneill** [comment]
I'm going to have to improve my understanding of code pages  :-(  
This isn't a French code page which was one thing I _read_ but I don't think was meant.  

If I run **cmd** and send the output of winget to a file and then type the file the same ` …` -->  `0xE2 0x80 0xA6`  happens and `cmd`  prints these using the table  at  https://en.wikipedia.org/wiki/Code_page_850#Character_set   0xE2 = Ô ,  0x80=Ç and 0xA6=ª     The same" misinterpretation" happens if I do `winget list | more` in **cmd** 
chcp tells me on my machine (en-GB) the code page is 850 (en-gb). I can change it to to 437 (en-US) I get the same result, but   chcp 65001 causes **cmd** to interpret those 3 bytes correctly. The 4 high order bits in E2 say this characters is expressed in 3 bytes, and the 4 lower order bits, and the 6 low order bits from the second and third bytes give 16 bits for the unicode character U+2026 
 
I'm reading this as _when winget output is redirected ellipsis is always sent as as the 3 bytes_ `0xE2 0x80 0xA6` and **cmd** _writing to the console interprets those depending on the current code page._ 
If **PowerShell** types the file it is processed as UTF-8  so unlike cmd it renders the ellipsis in the file

But if I do `$psversionTable | clip`  PowerShell sends the ellipsis in `PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}`  as the 3 UTF Bytes and clip assumes it is getting codepage 850 characters and they paste like this  
```
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
```

But if I do `[System.Console]::OutputEncoding = [System.Console]::OutputEncoding = [System.Text.UTF8Encoding]::new() `
The 3 bytes are understood as their UTF-8 meaning. 
```
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
```

It seems when data is piped in PowerShell assumes the bytes mean what the console encoding says the should mean, but going out I'm I don't think the bytes leaving PowerShell are changing, but it's not clear how `clip` comes to process them correctly because setting console encoding doesn't change the result of running chcp from within PowerShell.

**Comment by jborean93** [comment]
@jhoneill there are 3 things at play here

* No redirection in cmd - output is written directly to the console like with PowerShell so no encoding problems
* Redirected to a file `... > stdout` - The stdout is redirected but the raw bytes is whatever the native app writes the output as
  * This is why the file contains UTF-8 bytes and confirms that it is ignoring the console codepage setting and always uses UTF-8
  * Note in pwsh redirecting to a file still goes through pwsh, cmd is special in that the stdout pipe of the new process is a HANDLE to that file
* Piped to another command `... | clip` - This depends on app you are piping to
  * Typically this is a direct pipe connection so clip is getting the raw bytes
  * If the 2nd exe tries to read this as a string then it typically also tries to read it based on the console codepage set
  * Other exe might just read the raw bytes and won't worry about the encoding, like clip
  * Once again pwsh is different where it actually converts this to a string and vice versa to input to clip.exe

> The same" misinterpretation" happens if I do winget list | more in cmd chcp tells me on my machine (en-GB) the code page is 850 (en-gb). I can change it to to 437 (en-US) I get the same result, but chcp 65001 causes cmd to interpret those 3 bytes correctly. The 4 high order bits in E2 say this characters is expressed in 3 bytes, and the 4 lower order bits, and the 6 low order bits from the second and third bytes give 16 bits for the unicode character U+2026

Typically exe's use the console code page setting which is why things usually just work but when they don't you have problems. So unless the codepage was set to `65001 (utf-8)` then more will fail to decode those 3 bytes properly as it's using a different encoding than what it actually was to encode that string in the first place.

> I'm reading this as when winget output is redirected ellipsis is always sent as as the 3 bytes 0xE2 0x80 0xA6 and cmd writing to the console interprets those depending on the current code page.
If PowerShell types the file it is processed as UTF-8 so unlike cmd it renders the ellipsis in the file

Sure, in pwsh it will read files as UTF-8 by default so those raw bytes are read correctly. PowerShell does not read output from a native exe as UTF-8 by default, it's dependent on the setting of `[Console]::OutputEncoding` which can be UTF-8 but it could also be something else.

> But if I do $psversionTable | clip PowerShell sends the ellipsis in PSCompatibleVersions {1.0, 2.0, 3.0, 4.0…} as the 3 UTF Bytes and clip assumes it is getting codepage 850 characters and they paste like this. It seems when data is piped in PowerShell assumes the bytes mean what the console encoding says the should mean, but going out I'm I don't think the bytes leaving PowerShell are changing, but it's not clear how clip comes to process them correctly because setting console encoding doesn't change the result of running chcp from within PowerShell.

Sending input to a native command is dependent on the value of `$OutputEncoding` (I know confusing name). So depending on what this is and how the native exe reads the stdin this may or may not work properly. The problem could either lie in how the native exe is reading those bytes or how pwsh reads the output. Both unfortunately will need to line up and also align with how `clip.exe` is expecting it to work.

I've documented this behaviour in this gist https://gist.github.com/jborean93/44b4688cc518d67bd7bc2192648384a3. It's not fully complete but it goes over all this in more depth and the various encoding options used by native applications.

@ernest33 see below for replies to your comments

When you don't pipe or capture output of a native command in PowerShell the native application has direct access to the console and when it writes output it is written to the console directly using an API where encoding is less of a problem. This is why this works as the output doesn't go in PowerShell at all. I can't fully explain why the ellipsis aren't present here but at a guess winget tries to adjust the column sizes based on whether stdout is redirected or not. If it's redirected then it's using a pre-set column width which then uses the ellipsis but now has to deal with the encoding problem because pwsh needs to read those bytes

**Comment by jhoneill** [comment]
@jborean93  Thanks for the explanation.  I'm not sure if I was misremembering or misunderstanding, but I appreciate  the clarification

**Comment by jhoneill** [comment]
> Sending input to a native command is dependent on the value of `$OutputEncoding` (I know confusing name). So depending on what this is and how the native exe reads the stdin this may or may not work properly. The problem could either lie in how the native exe is reading those bytes or how pwsh reads the output. **Both unfortunately will need to line up and also align with how `clip.exe` is expecting it to work.**

I think in this case PowerShell 7 sets `$OutputEncoding` to  UTF-8 (PowerShell 5 sets it to ASCII), and the console is set to CodePage 850 on my personal Windows 11 machine  and CodePage 437 on my client-provided windows 10 one (the two have different system locales) so we get a mismatch. 

I'm trying to think of a reason why  keeping `[System.Console]::OutputEncoding`   and `$OutputEncoding`  in sync _wouldn't_ be a good idea,  the ellipsis in `$psversionTable`  will get corrupted because pwsh is doing what `$OutputEncoding` says it should and `clip.exe.` is doing what `[System.Console]::OutputEncoding` tells _it_ to do and they're diverging. 

This is a different issue to winget ignoring the codepage when output is piped or redirected. But to my mind the creators of winget already had their own special circle of hell :-)

**Comment by jborean93** [comment]
There's https://github.com/PowerShell/PowerShell/issues/14945 which I've opened before about `$OutputEncoding` and `[Console]::InputEncoding` not lining up (they should). It would be nice if `[Console]::OutputEncoding` also lined up but it's somewhat less of an issue as most console apps respect the console output codepage that pwsh will use to decode the bytes it receives.
