### ISSUE TITLE
prevent PowerShell autocomplete from adding dot prefix

### ISSUE THREAD

**Issue by garretwilson** [PowerShell/PowerShell#18180]
### Summary of the new feature / enhancement

Please provide an option or configuration to prevent PowerShell from prefixing every relative file path (even program arguments!) with a `.\` without my asking it to

I understand why PowerShell requires that I prefix a command `foo.exe` with `.\foo.exe` when I run it. So if I am typing a command `fo` and hit `Tab`, autocomplete changes what I typed to `.\foo.exe`. I can live with that, even though I find it annoying and patronizing.

The problem is when `foo.exe` takes command-line arguments, and one of them is the `bar.dat` file. If I'm typing `.\foo.exe ba` and hit `Tab`, I want to get `.\foo.exe bar.dat`. I do _not_ want to get `.\foo.exe .\bar.dat`. Not only is this irritating as heck (not to mention ugly), it actually breaks some of my commands, which don't allow any directory (even the current directory) to be specified in the argument.

How do I turn off this PowerShell quirk of adding a `.\` to every single autocomplete for a relative path? As far as I'm concerned, I'd like it to be turned off everywhere—I can remember to type `.\foo.exe` instead of `foo.exe` for the initial command. As I mentioned earlier, I can partially understand that PowerShell wants to add the `.\` to the initial command, because it's required to run a program in the current directory. But I'm dumbfounded as to why PowerShell is so unintelligent that it blindly adds the `.\` prefix to all relative paths, even where it's not required, not needed, and certainly not desired.

I opened [prevent PowerShell autocomplete from adding dot prefix](https://superuser.com/questions/1741125/prevent-powershell-autocomplete-from-adding-dot-prefix) on Super User, but no one had any solutions.

**Comment by MartinGC94** [comment]
I like the automatic addition of `.\` but if you want to work around this you can use the following modified tabexpansion2 function:

```
function TabExpansion2
{
    <# Options include:
         RelativeFilePaths - [bool]
             Always resolve file paths using Resolve-Path -Relative.
             The default is to use some heuristics to guess if relative or absolute is better.

       To customize your own custom options, pass a hashtable to CompleteInput, e.g.
             return [System.Management.Automation.CommandCompletion]::CompleteInput($inputScript, $cursorColumn,
                 @{ RelativeFilePaths=$false }
    #>

    [CmdletBinding(DefaultParameterSetName = 'ScriptInputSet')]
    [OutputType([System.Management.Automation.CommandCompletion])]
    Param
    (
        [Parameter(ParameterSetName = 'ScriptInputSet', Mandatory = $true, Position = 0)]
        [string] $inputScript,

        [Parameter(ParameterSetName = 'ScriptInputSet', Position = 1)]
        [int] $cursorColumn = $inputScript.Length,

        [Parameter(ParameterSetName = 'AstInputSet', Mandatory = $true, Position = 0)]
        [System.Management.Automation.Language.Ast] $ast,

        [Parameter(ParameterSetName = 'AstInputSet', Mandatory = $true, Position = 1)]
        [System.Management.Automation.Language.Token[]] $tokens,

        [Parameter(ParameterSetName = 'AstInputSet', Mandatory = $true, Position = 2)]
        [System.Management.Automation.Language.IScriptPosition] $positionOfCursor,

        [Parameter(ParameterSetName = 'ScriptInputSet', Position = 2)]
        [Parameter(ParameterSetName = 'AstInputSet', Position = 3)]
        [Hashtable] $options = $null
    )

    End
    {
        $CompletionOutput = if ($psCmdlet.ParameterSetName -eq 'ScriptInputSet')
        {
            [System.Management.Automation.CommandCompletion]::CompleteInput(
                <#inputScript#>  $inputScript,
                <#cursorColumn#> $cursorColumn,
                <#options#>      $options)
        }
        else
        {
            [System.Management.Automation.CommandCompletion]::CompleteInput(
                <#ast#>              $ast,
                <#tokens#>           $tokens,
                <#positionOfCursor#> $positionOfCursor,
                <#options#>          $options)
        }

        if ($inputScript -and
            !$inputScript.Contains('.\') -and
            $CompletionOutput.CompletionMatches.Count -gt 0 -and
            $CompletionOutput.CompletionMatches[0].ResultType -eq [System.Management.Automation.CompletionResultType]::ProviderContainer -or
            $CompletionOutput.CompletionMatches[0].ResultType -eq [System.Management.Automation.CompletionResultType]::ProviderItem
        )
        {
            [System.Object[]]$NewCompletionList = foreach ($Item in $CompletionOutput.CompletionMatches)
            {
                if ($Item.CompletionText.Contains('.\'))
                {
                    [System.Management.Automation.CompletionResult]::new($Item.CompletionText.Replace('.\',''), $Item.ListItemText, $Item.ResultType, $Item.ToolTip)
                }
                else
                {
                    $Item
                }
            }
            $CompletionOutput.CompletionMatches = $NewCompletionList
        }

        return $CompletionOutput
    }
}
```

**Comment by mklement0** [comment]
Nicely done, @MartinGC94.
I suggest tweaking the code a bit (I've done it below) so as to match `.\` only at the _start_ of a completion result, and so as to treat `./` the same.

<Details>

```powershell
function TabExpansion2 {
  <# Options include:
         RelativeFilePaths - [bool]
             Always resolve file paths using Resolve-Path -Relative.
             The default is to use some heuristics to guess if relative or absolute is better.

       To customize your own custom options, pass a hashtable to CompleteInput, e.g.
             return [System.Management.Automation.CommandCompletion]::CompleteInput($inputScript, $cursorColumn,
                 @{ RelativeFilePaths=$false }
    #>

  [CmdletBinding(DefaultParameterSetName = 'ScriptInputSet')]
  [OutputType([System.Management.Automation.CommandCompletion])]
  Param
  (
    [Parameter(ParameterSetName = 'ScriptInputSet', Mandatory = $true, Position = 0)]
    [string] $inputScript,

    [Parameter(ParameterSetName = 'ScriptInputSet', Position = 1)]
    [int] $cursorColumn = $inputScript.Length,

    [Parameter(ParameterSetName = 'AstInputSet', Mandatory = $true, Position = 0)]
    [System.Management.Automation.Language.Ast] $ast,

    [Parameter(ParameterSetName = 'AstInputSet', Mandatory = $true, Position = 1)]
    [System.Management.Automation.Language.Token[]] $tokens,

    [Parameter(ParameterSetName = 'AstInputSet', Mandatory = $true, Position = 2)]
    [System.Management.Automation.Language.IScriptPosition] $positionOfCursor,

    [Parameter(ParameterSetName = 'ScriptInputSet', Position = 2)]
    [Parameter(ParameterSetName = 'AstInputSet', Position = 3)]
    [Hashtable] $options = $null
  )

  # Original code.
  $CompletionOutput =
    if ($psCmdlet.ParameterSetName -eq 'ScriptInputSet') {
      [System.Management.Automation.CommandCompletion]::CompleteInput(
        <#inputScript#>  $inputScript,
        <#cursorColumn#> $cursorColumn,
        <#options#>      $options)
    }
    else {
      [System.Management.Automation.CommandCompletion]::CompleteInput(
        <#ast#>              $ast,
        <#tokens#>           $tokens,
        <#positionOfCursor#> $positionOfCursor,
        <#options#>          $options)
    }

  # Custom post-processing to remove a .\ or ./ prefix, if present.
  if ($inputScript -and
    $inputScript -notmatch '^.[/\\]' -and
    $CompletionOutput.CompletionMatches.Count -gt 0 -and
    $CompletionOutput.CompletionMatches[0].ResultType -in [System.Management.Automation.CompletionResultType]::ProviderContainer, [System.Management.Automation.CompletionResultType]::ProviderItem
  ) {
    $CompletionOutput.CompletionMatches = 
      foreach ($Item in $CompletionOutput.CompletionMatches) {
        if ($Item.CompletionText -match '^.[/\\]') {
          [System.Management.Automation.CompletionResult]::new(($Item.CompletionText -replace '^.[/\\]'), $Item.ListItemText, $Item.ResultType, $Item.ToolTip)
        }
        else {
          $Item
        }
      }

  }

  return $CompletionOutput
}
```
</Details>

**Comment by garretwilson** [comment]
> … use the following modified tabexpansion2 function …

How do I use this ~~monstrous~~ marvelous workaround? Do I install it? Do I copy it some where? Do I make sure it runs every time I go into PowerShell?

**Comment by mklement0** [comment]
To answer your <del>flippant</del> question, which exhibits commendable consistency with your overall <del>abrasive</del> style of communicating: check [the updated answer to your superuser.com](https://superuser.com/a/1742406/139307) question; in short: copy & paste the function definition at the prompt to define it for the _current_ session and/or paste it into your `$PROFILE` file to make it take effect for all future sessions.

**Comment by dkaszews** [comment]
@mklement0 Is `TabCompletion2` one of those magic functions you can overwrite to change behavior of PowerShell REPL? Like `prompt`? What happened to `TabCompletion`?

**Comment by mklement0** [comment]
@dkaszews, I don't know the history, but, yes, `TabExpansion2` (not `TabCompletion2`)  is defined by default in an interactive session and called by PowerShell in order to obtain completion results, and there is no `TabExpansion` (anymore).

[Source-code link](https://github.com/PowerShell/PowerShell/blob/fd67038ed88a844c51bcadbd720e6c2335fa4900/src/System.Management.Automation/engine/InitialSessionState.cs#L3988) to the function definition, current as of this writing.

**Comment by kilasuit** [comment]
@mklement0 you mentioned in the SU post this has been like this since v7.2.6 - though I can also repro in v5.1

@dkaszews - TabExpansion2 has been around IIRC since v3 and is an internal function to PowerShell, it's prior version tabExpansion is used with hosts still running PowerShell v2 [as per this comment](https://github.com/PowerShell/PowerShell/blob/7c624902e1dbb165b1fa0700df498a22c567b9f8/src/System.Management.Automation/engine/remoting/server/serverremotesession.cs#L818-L819)

**Comment by mklement0** [comment]
@kilasuit, the SU answer states _as of_ 7.2.6, implying all versions _up to_ it.

Good to know about the history of `TabExpansion` vs. `TabExpansion2`.

**Comment by iSazonov** [comment]
> But I'm dumbfounded as to why PowerShell is so unintelligent that it blindly adds the `.\` prefix to all relative paths, even where it's not required, not needed, and certainly not desired.

It is a compromise. Tab completion works smart only if there is a meta data - type inference. If no type inference is possible the tab completion uses last resort - path completion because this is the most common case. Of course, it is not ideal, but until there is no meta information it is almost impossible to do something smarter, only to add workarounds for special cases. It is not always worth the cost.

**Comment by jhoneill** [comment]
> it actually breaks some of my commands, which don't allow any directory (even the current directory) to be specified in the argument.

Sounds like the real problem lies with the design of those. 

TBH PowerShell completes more things than I was used to before I used it, I don't normally like things sticking extras in (like the .\) but I hardly noticed and now it seems odd to drop into CMD and not have tab expansion for anything other than file names, and for those to be "naked".  Changing the default behaviour is likely to annoy a lot more people than it pleases, but as has been shown already tab support comes from a customizable function.

**Comment by mklement0** [comment]
@iSazonov, the complaint isn't about situations where  filename completion isn't appropriate (that's a separate issue, e.g. #14147, #7215), it is about the unnecessary prefixing of completed names with `.\` or `./` (depending on platform).

However, to me that applies to _arguments_ only, not _command names_, as something like `.\foo` is _required_ in order to execute a command / open a document named `foo` that is located in the _current directory_ (as opposed to being executable via `$env:PATH`; that _documents_ can be opened via `$env:PATH` is a problem in its own right: #12632):
 
  * Curiously, Bash's tab-completion gets this wrong in that it completes executables in the current directory _without_ a prefix (as it generally does), meaning that the invocation would fail unless `./` is manually prepended.
 
 * Another option would be for PowerShell to complete command names via `$env:PATH` only, _unless_ the user has explicitly typed `.\` or `./` at the start of their command name.

My personal preference is for the prefix  to be _omitted_ for arguments, primarily to cut down on the visual noise (as @jhoneill's comment implies, most commands treat the prefixed form as equivalent, so the problem is primarily an aesthetic one).

As for changing the existing behavior: We have no _strict_ backward-compatibility concern here, given that no existing code would be affected, but, as @jhoneill points out, such a change might annoy / confuse users.

Thus, this comes down to:

* Is it worth implementing a preference variable or, perhaps better, a PSReadLine option to allow prefix-less completion on an _opt-in_ basis?

* Or is the workaround shown in this post - a custom `TabExpansion2` function - good enough?

The latter would be less obscure if it were discussed in a - hypothetical, future - `about_Command_Completion` help topic, which I feel is called for either way (it should cover `TabExpansion2`, `Register-ArgumentCompleter` and the `ArgumentCompleter` attribute).

**Comment by garretwilson** [comment]
Before jumping back in here, I want to stress that I appreciate those who have gone to the trouble to provide a creative workaround. (I haven't got a chance to try it yet; I'll report back when I do. Conceptually I can already imagine a couple of corner cases where it does the wrong thing, but it's likely good enough in the interim.) I'm adding comments not to be argumentative but to add to the discussion so that you can make the best decision on what to do.

> Bash's tab-completion gets this wrong in that it completes executables in the current directory without a prefix ...

I understand what you're saying, but another way to look at it would be that in the case of the executable, it's the user who got it wrong: Bash correctly _completed_ what they started, it's just that the user started typing something that wouldn't work to begin with. (Personally I would be fine with that behavior. I'm suspicious of software in general trying to correct my mistakes, as many times the software gets it wrong.)

In fact it's arguable that PowerShell doesn't get it 100% right even with commands. Do the following (based on something I found out just last night in the latest _Powershell Cookbook_):

```powershell
$env:Path += ';.'
```

You've just told PowerShell that it's OK to invoke commands in the current directory without the `.\` prefix. That is, you can type `foo.ps1 bar.dat` and it will run `foo.ps1` just fine. But guess what? If you type `fo` and then to tab completion, _PowerShell still changes it to `.\foo.ps1`_!

So I would argue that there is virtually no intelligence (in the literal software meaning) to what PowerShell is doing. It's just blinding prefixing relative paths with `.\`, regardless of whether the path is a command or an argument, and regardless of whether the command even needs it. And that irks me, especially since it clutters up a simple thing I'm trying to type.

It wouldn't be so bad if the workaround were two or three lines, or if there were a `tab.expansion.prefix.relative.paths` setting as I might expect to add to `.gitconfig` if this were a Git problem. But it doesn't seem correct that I would essentially have to reprogram tab expansion, using a very hackish approach (in no way belittling the people who wrote it --- that's probably the only way to do it) which itself will likely have bugs without further handling of corner cases (e.g. if the user actually typed the path starting with `.\` to begin with, or if the path has been quoted, etc.). In my mind this all comes down to: PowerShell is doing something I didn't ask it to do (and doing it in a very unintelligent way at that) and it shouldn't be so hard to get it to stop.

**Comment by mklement0** [comment]
Thanks for being willing to engage constructively.

* Indeed PowerShell currently _blindly_ prepends `.\` or `./`
* I argue that in the case of completing a _command_ name that is useful (more on that below).
* Yes, the workaround is obscure and so complex that whenever you need to apply it, you'll have to go back to the source and copy the code, which is unfortunate.
* I would personally welcome a simple, configuration-based opt-in way of no longer prefixing _argument_ completions, but I have no say in whether that will happen. (And I would personally also be OK with simply changing the default behavior, but I understand that not everyone would be.)

---

> Bash correctly _completed_ what they started,

This behavior is useless, as the reasonable expectation of a tab-completed value is that it works _as is_.

What if the user _wants_ completion based on the current directory, and only typed `foo` _as a convenience_, (`.\` and `./` are awkward to type) relying on the tab-completion logic to turn it into `./foo`? After all, tab-completion is about _interactive convenience_.

In fact, I routinely rely on this technique: Say I want to open file `readme.txt` in the current directory: I start typing `read`, and rely on PowerShell to turn this into `./readme.txt`.

Note that in general what the user typed is (fortunately) not necessarily honored _verbatim_; e.g. typing `*.txt` and tab-completing that would (eventually) get me to `./readme.txt` too.

  * This doesn't work in Bash if typed as the _command_, btw, so Bash _does_ treat command-name completions differently, so it's unfortunate that it doesn't prepend `./` automatically when needed; curiously, `*.txt` doesn't expand at all, while typing `*` does expand, but only _directories_, but starting a command line in Bash with anything other than an _executable_ doesn't make sense.

---

> `$env:Path += ';.'`

* This is generally ill-advised, as it makes the execution environment less predictable and opens the door for maliciously placed executables to preempt execution of the intended ones, so I see no reason for tab-completion to accommodate such a configuration.

**Comment by garretwilson** [comment]
> This [Bash] behavior is useless, as the reasonable expectation of a tab-completed value is that it works as is.

That's a reasonable conclusion, and I'm not saying that PowerShell should remove its more helpful behavior in relation to the initial command. I was just saying it's not necessarily "wrong" to do it the other way. Both Bash and PowerShell take a "I'll blindly do path completion the same way for all relative paths." I guess my point is that if it has to be all or nothing, I much prefer the Bash approach, which results in fewer things I didn't ask for.

But we shouldn't be stuck with two blind approaches. I'm sure PowerShell can be made smart enough to figure out if the path relates to the initial command or an argument. (And I think it's worth noting that **the logic to avoid this behavior surely would be many times shorter than the workaround**.)

> This [adding the current directory to the command search path] is generally ill-advised ...

I don't disagree. The point I was making is that the purported purpose of adding `.\` to the command is because it is necessary for functionality, and I was noting that PowerShell is adding it even when it's not necessary for functionality. If someone still wants PowerShell to add the prefix because it looks prettier to them, that's a valid opinion, but that's a different argument than functional utility.

I also want to say that your four points at the start of your comment above are an excellent summary, and I agree with them all.

**Comment by jhoneill** [comment]
> that irks me, especially since it clutters up a simple thing I'm trying to type.
> 
> It wouldn't be so bad if the workaround were two or three lines, or if there were a `tab.expansion.prefix.relative.paths` setting as I might expect to add to `.gitconfig` if this were a Git problem. But it doesn't seem correct that I would essentially have to reprogram tab expansion, using a very hackish approach

It's very clear you're irked, 

TabExpansion is implemented as a pair of PowerShell functions (and not as compiled code) precisely to allow for people who do not like the way things have been done to get something different, and lots of things in PowerShell have a similar philosophy. Personally I would like the code for tab expanding files and folders to be as easy to change, I have my own (e.g. it fixes ~ not expanding, expands  .... to ..\..\.. yada yada yada) and it has has to be bound to the command/parameter where I want it, it can't be a drop in replacement. At least _this_ wish can be achieved by fixing the returned responses, mine generates extra/different responses 

Now, if there many people feeling as you do, the functions would have been modified to support an option to conditionally run code like that which appears above, or to run as things have worked since ~2006. So far yours is a lone voice, but maybe this thread will reveal some more.  In that situation resources won't get allocated to making the change, there is a work round (take the script you've been given, load it from your profile).  You can have what you want today, if you managed to persuade the team to change the product you wouldn't see the change this year.

**Comment by dkaszews** [comment]
@jhoneill Can you recommend some resources or tutorial how to modify the completion function (other than to just look at the default and examples in this thread)? I would like to try and replicate behavior of bash, which stops on first distinct character of ambiguous completion.

**Comment by garretwilson** [comment]
I've upgraded to PowerShell 7.x and set up a profile and done initial testing of the workaround. Another day I'll have feedback and provide my own improvements. It's been an incredibly long day and I'm trying to find a stopping point.

My next step was to be to installing [posh-git](https://github.com/dahlbyk/posh-git), as Git autocomplete was one of the primary reasons for using PowerShell (which I can actually get in Git Bash, but that brings other difficulties). So I wondered, how does posh-git do its magic? And is it compatible with this workaround? I quickly stumbled upon a few things:

* posh-git seems to use `TabExpansion` in [`GitTabExpansion.ps1`](https://github.com/dahlbyk/posh-git/blob/master/src/GitTabExpansion.ps1), which above someone mentioned was outdated. But that actually seems to be a fallback (caveat: I'm tired and I haven't explored the code thoroughly): it first tries to use something called `Register-TabExpansion`.
* #2130 was moved to MicrosoftDocs/PowerShell-Docs/issues/747, which along with MicrosoftDocs/PowerShell-Docs/issues/2325 seem to indicate that even `TabExpansion2` is obsolete.
* MicrosoftDocs/PowerShell-Docs/issues/2325's reference link is broken, but it a quick search brings up [`Register-ArgumentCompleter`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter).

I'm too tired to read those documents tonight, but I'll note them in case some experts here already have the answers: Are we even using the correct approach for the workaround, or should we be instead be using `Register-TabExpansion` or `Register-ArgumentCompleter`? And is this workaround compatible (i.e. won't break or vice-versa) posh-git?

I'll investigate more after a good night's sleep. Apologies in advance if all this is irrelevant or misinterpreted.

**Comment by mklement0** [comment]
My presumption about `Register-ArgumentCompleter` (fully) obsoleting `TabExpansion2` wasn't correct: `Register-ArgumentCompleter` defines custom completion for the _arguments_ of _specific commands_ - it is what you typically use. However, to modify completion behavior _globally_, including for _command names_, you still need `TabExpansion2`.

**Comment by theJasonHelmick** [comment]
Thanks for the issue and the lively conversation, especially the workaround.  To be clear regarding this issue: "Please provide an option or configuration to prevent PowerShell from prefixing every relative file path ". This was discussed by the Working Group.  We don’t see an overwhelming increased value in making a change here.  Thank you for the input and issue.

**Comment by garretwilson** [comment]
> Thanks for the issue and the lively conversation, especially the workaround.

Actually the workaround was buggy and far from complete. @mklement0 provided more work, and came up with a [more extensive workaround](https://superuser.com/a/1742406), which unfortunately is still incomplete.

```powershell
# Adapted from: https://github.com/PowerShell/PowerShell/issues/18180#issuecomment-1261140386
# Credit belongs to MartinGC94 (https://github.com/MartinGC94)
function TabExpansion2 {
  <# Options include:
        RelativeFilePaths - [bool]
            Always resolve file paths using Resolve-Path -Relative.
            The default is to use some heuristics to guess if relative or absolute is better.

      To customize your own custom options, pass a hashtable to CompleteInput, e.g.
            return [System.Management.Automation.CommandCompletion]::CompleteInput($inputScript, $cursorColumn,
                @{ RelativeFilePaths=$false }
    #>

  [CmdletBinding(DefaultParameterSetName = 'ScriptInputSet')]
  [OutputType([System.Management.Automation.CommandCompletion])]
  Param
  (
    [Parameter(ParameterSetName = 'ScriptInputSet', Mandatory = $true, Position = 0)]
    [string] $inputScript,

    [Parameter(ParameterSetName = 'ScriptInputSet', Position = 1)]
    [int] $cursorColumn = $inputScript.Length,

    [Parameter(ParameterSetName = 'AstInputSet', Mandatory = $true, Position = 0)]
    [System.Management.Automation.Language.Ast] $ast,

    [Parameter(ParameterSetName = 'AstInputSet', Mandatory = $true, Position = 1)]
    [System.Management.Automation.Language.Token[]] $tokens,

    [Parameter(ParameterSetName = 'AstInputSet', Mandatory = $true, Position = 2)]
    [System.Management.Automation.Language.IScriptPosition] $positionOfCursor,

    [Parameter(ParameterSetName = 'ScriptInputSet', Position = 2)]
    [Parameter(ParameterSetName = 'AstInputSet', Position = 3)]
    [Hashtable] $options = $null
  )

  Set-StrictMode -Version 1

  # The original TabExpansion2 code.
  $completionOutput =
    if ($psCmdlet.ParameterSetName -eq 'ScriptInputSet') {
      [System.Management.Automation.CommandCompletion]::CompleteInput(
        <#inputScript#>  $inputScript,
        <#cursorColumn#> $cursorColumn,
        <#options#>      $options)
    }
    else {
      [System.Management.Automation.CommandCompletion]::CompleteInput(
        <#ast#>              $ast,
        <#tokens#>           $tokens,
        <#positionOfCursor#> $positionOfCursor,
        <#options#>          $options)
    }

  # Custom post-processing that removes a .\ or ./ prefix, if present.
  $completionOutput.CompletionMatches = @(
    foreach ($item in $CompletionOutput.CompletionMatches) {
      $isFileOrDirArg =
        if ($item.ResultType -in [System.Management.Automation.CompletionResultType]::ProviderContainer, [System.Management.Automation.CompletionResultType]::ProviderItem) {
          # A file / directory (provider item / container) path, 
          # though we must rule out that it acts *as a command*,
          # given that the "./" \ "\." prefix is *required* when invoking files located in the current dir.

          # Tokenize the part of the input command line up to the cursor position.
          $pstokens = [System.Management.Automation.PSParser]::Tokenize($inputScript.Substring(0, $cursorColumn), [ref] $null)

          # Determine if the last token is an argument.
          switch ($pstokens[-1].Type) {
            'CommandArgument' {
              # An unquoted argument.
              $true; break 
            } 
            { $_ -in 'String', 'Number' } { 
              # Either:
              #  * A quoted string, which may be an argument or command;
              #    Note that in the end it is only treated as a command if preceded by '.' or '&'
              #  * A number which matches a filename that starts with a number, e.g. "7z.cmd"
              switch ($pstokens[-2].Type) {
                $null { $false; break } # Token at hand is first token? -> command.
                'Operator' { $pstokens[-2].Content -notin '.', '&', '|', '&&', '||'; break } # If preceded by a call operator or an operator that starts a new command -> command
                'GroupStart' { $false; break } # Preceded by "{", "(", "$(", or "@(" -> command.
                'StatementSeparator' { $false; break } # Preceded by ";", i.e. the end of the previous statement -> command
                Default { $true } # Everything else: assume an argument.
              }
            }
          }
        }
      if ($isFileOrDirArg) {
        # A file / directory (provider item / container) path acting as an *argument*
        [System.Management.Automation.CompletionResult]::new(($item.CompletionText -replace '^([''"]?)\.[/\\]', '$1'), $item.ListItemText, $item.ResultType, $item.ToolTip)
      } 
      else {
        # Otherwise, pass through.
        $item
      }
    }
  )
  return $completionOutput
}
```

This is truly getting closer to the "monstrous" adjective I jokingly used earlier in this ticket. It appears not possible to completely "undo" these changes PowerShell is doing arbitrarily to non-initial arguments without my asking for it.

**Comment by Kaarel** [comment]
This auto expansion on auto completion gets really annoying when using history search with prefix filter. I frequently use `cd p<Up>` to search and filter through commands I've used in the past. I often navigate to sub-directories from my current project root so this `history <Up>` makes my workflow so much faster and smoother. Though `cd` of course can be any command.

**Scenario 1**
I'm working on `service_foo`. I navigate between the service path and project root path a lot.
1. I type or copy paste while in project root directory `cd sub\directory\service_foo`
2. Next time I'm in the active project root directory I just do `cd s<Up>` to get to `service_foo`. Nice!

But then I need to work on `service_bar`
1. I type `cd s<Up>` to find `sub\directory\service_foo`
2. I delete `foo` and type `b<tab>` to expand to `sub\directory\service_bar`. But this adds the prefix `.\` which will also be added to history.
3. Next time I want to navigate to `service_bar` I type `cd s<Up>` but this obviously does not list `.\sub\directory\service_bar` even though I know I recently used it. Annoying.

**Scenario 2**
Using env variables.
1. I type `cd $HOME\app<tab>` to list directories in my HOME
2. On Windows gets expanded to `C:\Users\user_name\app`.
3. I select `cd C:\Users\user_name\AppData\<Enter>`
4. The above command with fully expanded path gets added to history. I can't use `cd $HOME<Up>` to scroll through my recent history. I have to know to do `cd C:\<Up>`. Or rather `cd C:\Users\...<Up>` to apply a filter. Very annoying.

As a workaround sometimes after finding the path I'm interested in I go back to the beginning of path and replace the expanded section with the variable token so next time when I do `cd $HOME<Up>` I can quickly find my recent commands related to `$HOME`. `$HOME` of course could be any variable.

**Scenario 3**
Spaces in paths.
1. I type `cd $HOME\app<tab>` to list all directories in my HOME
2. On Windows gets expanded to `C:\Users\user_name\`.
3. I select `cd 'C:\Users\user_name\Application Data\'<Enter>`

Now, in order to use the <Up> history search with a prefix filter I have to know and remember to start with `cd 'C:<Up>` in order to quickly find from my recent history what really should be ``$HOME\Application` Data``. But now the filter does not include `AppData` from Scenario 2 even though it is under the same path filter. Triple annoying.

**Comment by iliqiliev** [comment]
I think this should be reopened.

> This issue has been marked as declined and has not had any activity for **1 day**. It has been closed for housekeeping purposes.

This seems too funny to me.
