### ISSUE TITLE
"Set-Location" don't change in directory with symlink on Windows

### ISSUE THREAD

**Issue by theuserbl** [PowerShell/PowerShell#18200]
### Summary of the new feature / enhancement

I have tesed also the NuShell. It have the nice possibility to change in a symlink-directory.

For example on a german Windows 10.
If I start cmd.exe and go to "C:\\" and type there "dir /a" there is listed
`02.10.2021  20:42    <JUNCTION>     Dokumente und Einstellungen [C:\Users]`
If I want to go in it with "cd", I don't end in C:\Users.

In PowerShell 7.3.0-preview 8 is the same behavior.
If I type there "Get-ChildItem -Hidden", there is listed this entry
`l--hs          02.10.2021    20:42                Dokumente und Einstellungen -> C:\Users`
But when I move in it, I don't change to the Users-directory:
```
PS C:\> Set-Location '.\Dokumente und Einstellungen\'
PS C:\Dokumente und Einstellungen> Get-ChildItem
Get-ChildItem: Access to the path 'C:\Dokumente und Einstellungen' is denied.
PS C:\Dokumente und Einstellungen>
```

I think it would be nice, if that would be implemented in "Set-Location".
On the NuShell on the other side, it works.
```
C:\〉cd `Dokumente und Einstellungen\`
C:\Users〉  
```

**Comment by 237dmitry** [comment]
I believe that this particular example cannot be considered a rule. If you create a junction with the same name, target and attributes elsewhere, then everything will work fine. Maybe for full access is not enough privileges or maybe this is not a junction but file type hidden from common users. ))
```powershell
> cd ~\Desktop

> New-Item -ItemType Junction -Name "Documents and Settings" -Target "C:\Users"

> (Get-Item '.\Documents and Settings\').Attributes = 9238

> # test cd, dir

> del "~\Desktop\Documents and Settings" -Force
```

**Comment by mklement0** [comment]
These special, hidden, system-defined junctions exist solely for pre-Windows-Vista compatibility, and I suggest not using them, as they're specifically designed to prevent enumeration of their contents (except, surprisingly, during remoting: see #13348). Thus, the problem here are the specific permissions associated with these system-defined junctions, not the fact that their path isn't resolved to the target path.

Generally, when you target a symlink / junction with `Set-Location` you _do_ want its path to be used as-is rather than resolving it to its target path.
