### ISSUE TITLE
PassThru Parameter not found for Update-Module

### ISSUE THREAD

**Issue by huigguijt** [PowerShell/PowerShell#18234]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Running Update-Module for any PowerShell module in combination with the -PassThru parameter returns an error message.

### Expected behavior

```console
Update-Module -Name Az.Accounts -PassThru
[an object representing the item with which you are working'.]
```

### Actual behavior

```console
Update-Module -Name Az.Accounts -PassThru
Update-Module : A parameter cannot be found that matches parameter name 'PassThru'.
```
Neither does tab-completion offer suggestion for this function.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.22000.832
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.832
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by dkaszews** [comment]
Invalid issue, `$PSVersionTable` shows 5.1.

Please read the prerequisites before opening an issue.

**Comment by kilasuit** [comment]
Hi @huigguijt 

I've had a look into this and the root cause is that this is an issue with the `PowerShellGet` Module & specifically the `v1.0.0.1` version of the module which is the default version available on all versions of Windows that it has been included with. On looking at the source code for this module across a number of my machines this parameter doesn't exist in this version.
I dug into the history of the [PowerShellGet Module](https://github.com/PowerShell/PowerShellGetv2/) and found that to use that parameter you will need to update PowerShellGet to version `2.1.5`.

That fixes your issue however raises a question that I am going to pass to the documentation team as current documentation only shows the latest version and not historic versions.

**Comment by sdwheeler** [comment]
https://learn.microsoft.com/powershell/scripting/gallery/installing-psget

> Windows PowerShell 5.1 comes with version 1.0.0.1 of PowerShellGet preinstalled. This version of PowerShellGet has a limited features and doesn't support the updated capabilities of the PowerShell Gallery. To be supported, you must update to the latest version.
