### ISSUE TITLE
$? is not set to $False even command fails

### ISSUE THREAD

**Issue by sumit-kakadiya** [PowerShell/PowerShell#18343]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

facing issue in version: Powershell version powershell-7.2 and on powershell-7.1.3
OS: centos 7
module used : ExchangeOnlineManagement
Issue: I connected o365 via powershell using application. I connected succesfully. I tried to fetch any connector exists or not. 
That gets failed. But "$?" was not set to False. It always remains True. Earlier it was set to False in such a case.
Same issue I faced when I create any connector. IF connector creations fails, "$?" remains True instead of False.

In below code sample: 
1. connector1 does not exist in my o365 exchange. 
2. "myrule" as not created as account has reached limit to no. of rules already.

code sample:
$EncPassword = ConvertTo-SecureString -String 'passowd' -AsPlainText -Force 
Connect-ExchangeOnline -AppId 'appid of mine' -CertificateFilePath '/home/cert.pfx' -CertificatePassword $EncPassword -Organization 'myorgdomain.onmicrosoft.com'
 write-host "connected"
 Get-InboundConnector 'connector1' 
if ($? -eq $True) 
{ 
    write-host "inbound connector exist"
  }
  else
{
   write-host "inbound connector does not exist"
}
     try 
    {
      New-TransportRule -Name 'myrule' -FromScope NotInOrganization -SentToScope InOrganization  -Enabled $true  -Priority 0 -SetSCL -1
       if ($? -eq $True)
        {
         write-host "inbound rule created"
         } 
        else
         {
              write-host "inbound rule creation failed"
         }
       } 
       catch 
       { write-error "This is exception" }

### Expected behavior

```console
$? should be set to $False as both commands were actually failed. It was working before few days but suddenly behaviour looks changed.

Expected output:
connected
inbound connector does not exist
inbound rule creation failed
```

### Actual behavior

```console
$? always set to $True even both commands were actually failed. It was working before few days but suddenly behaviour looks changed.

actual output:
connected
inbound connector exist
inbound rule created
```

### Environment data

```powershell
actual output:
connected
inbound connector exist
inbound rule created
```

**Comment by jhoneill** [comment]
The value of erroractionPreference and what happens inside the command being called will impact $?


```
function one {
[CmdletBinding()]
param()
1/0
"This line runs"
}

PS>  one
RuntimeException:
Line |
   4 |  1/0
     |  ~~~
     | Attempted to divide by zero.
This line runs

PS>  $?
True
```
 There was an error but the command still ran to completion - this is the test for "succeeded"  

```
PS>  one -ErrorAction stop
one: Attempted to divide by zero.

PS>  $?
False
```

"Did what I wanted", "Ran without raising any error", and "Succeeded" are not not the same, and the difference is a surprise sometimes.

**Comment by mklement0** [comment]
If I understand correctly, what sets `$?` to false is _any_ error record being written to the caller's error stream - which can be a non-terminating error (`Get-Item NoSuch`) or a statement-terminating error (`Get-Item -NoSuch`).
(As such `$?` only ever tells you that _some_ error occurred, not whether the command failed entirely or should still be considered successful overall.)

However, for commands written _in PowerShell_, statement-terminating errors or `Write-Error` calls _inside_ them do _not_ cause `$?` to be set to `$false`. The only way to currently achieve that is by making your script or function an _advanced_ one and to use `$PSCmdlet.WriteError()` (non-terminating error) or `$PSCmdlet.ThrowTerminatingError()` (statement-terminating error, from the caller's perspective).

That `Write-Error` currently doesn't set `$?` is unfortunate, and a known problem:
 * https://github.com/PowerShell/PowerShell/issues/3629

Additionally, the ability for scripts and function to set `$?` _explicitly_ has been green-lighted a while back, but isn't yet implemented (a new public API to be surfaced via a new cmdlet):  
 * https://github.com/PowerShell/PowerShell/issues/10917#issuecomment-550550490

Therefore, `$?` in your code should only be `$false` if BOTH of the following conditions are met:

* The preceding command emitted (at least one) error.
* The command is implemented as a _binary cmdlet_ OR it is implemented as an advanced function and uses `$PSCmdlet.WriteError()` and `$PSCmdlet.ThrowTerminatingError()` to emit its error.

**Comment by jhoneill** [comment]
> for commands written _in PowerShell_, statement-terminating errors or `Write-Error` calls _inside_ them do _not_ cause `$?` to be set to `$false`. The only way to currently achieve that is by making your script or function an _advanced_ one and to use `$PSCmdlet.WriteError()` (non-terminating error) or `$PSCmdlet.ThrowTerminatingError()` (statement-terminating error, from the caller's perspective).


@mklement0    `throw` works, and if error action preference is set to `stop` other errors act _like_ throw. 

```
PS>  function two {"a"; throw; b;}

PS>  two
a
Exception: ScriptHalted

PS>  $?
False

PS>
```
 
 
Using my other example
```
function one {
[CmdletBinding()]
param()
1/0
#  $? will now be false
"This line runs"
#  $? will now be true because the string was output
}

PS>  one
RuntimeException:
Line |
   4 |  1/0
     |  ~~~
     | Attempted to divide by zero.
This line runs

PS>  $?
True      # even if the error is the last line the function, it is still true  
```

divide by zero is a terminating error, but when ErrorActionPreference is "continue" it is considered to have been handled after printing it. So the function exits normally and $? says "true"

**Comment by mklement0** [comment]
@jhoneill 

Quick terminology note: There are _two types_ of terminating errors:

* A _statement_-terminating error (pipeline-terminating) occurs in an expression such as `1 / 0`, an exception thrown by a .NET method, an reported by a compiled cmdlet with `.ThrowTerminatingError()` (which, as noted, you can also do in PowerShell code with `$PSCmdlt.ThrowTerminatingError()`, but it is cumbersome and rarely done in practice).
  * As the name implies, the scope of what is terminated by default is the current _statement_ , meaning that execution continues with the next statement.

* A _script_-terminating error (runspace-terminating, fatal) `throw` by default produces ; you can promote non-terminating errors to script-terminating ones with `-ErrorAction Stop`. 

  * As the name (imperfectly) implies, the scope of what is terminated by default is the current _script_ - at least - but actually the entire _runspace_ the script and its callers). (In an earlier discussion, it was decided that "script" was good enough, and easier to understand than "runspace").
  
  * You can also promote _non_-terminating errors to script-terminating ones with `-ErrorAction Stop`. You can _additionally_ promote statement-terminating ones to script-terminating ones with `$ErrorActionPreference = 'Stop`.

This terminology isn't official but it's useful for making sense of what PowerShell does, and I've used it here and on Stack Overflow. (The names could be revisited, should they became part of the official docs; speaking of:
A while back I've attempted a comprehensive overview of PowerShell's error handling: [Our Error Handing, Ourselves](https://github.com/PowerShell/PowerShell-Docs/issues/1583))

**Comment by mklement0** [comment]
@jhoneill, as for your examples:

Your `throw` example:

Inside a script or function there's no point in combining `throw` with `$?`,
because `throw` either terminates the runspace, so no further code gets to execute, or you must use `try` / `catch`, in which case the fact that the `catch` block is triggered _by definition_ means that an error occured.

(_Interactively_, `throw` fortunately does _not_ terminate the entire session, which is what your example relies on)

---

Your `1 / 0` example:

What `$?` is _inside_ a script or function is irrelevant _to the caller_.

That is, whether or not you follow `1 / 0` with another statement that _function-internally_ resets `$?` before returning makes no difference:

```powershell
function foo { 1 / 0 }; foo; $? # -> $true
```

**Comment by SteveL-MSFT** [comment]
@sumit-kakadiya so for your original issue, does setting `$ErrorActionPreference = 'Stop'` address your issue?  It seems that the generated proxy functions do not generate a terminating error such that `$?` gets set.

**Comment by mklement0** [comment]
@SteveL-MSFT:

Switching to `-ErrorAction Stop` isn't a _general_ solution, as with multiple inputs you may want to _continue_ processing of the remaining inputs, even if an earlier one resulted in a non-terminating error, and check `$?` afterwards.

Also, `-ErrorAction Stop` could only be handled with a `try` / `catch` - a directly following `if ($? -eq $true)` would not get to execute.

Unless there is truly a bug here, the fact hat `if ($? -eq $true)` _did_ get to execute and was `$true` implies one of two things:
* _No_ error was emitted.
* A _non_-terminating error was emitted, but it didn't cause `$?` to be set to `$false`. (_Statement_-terminating errors _always_ set `$?` to `$false`; _functions_ can only emit such errors via `$PSCmdlet.ThrowTerminatingError()`).
  * As discussed, this can be the case for _functions_ that use `Write-Error` (rather than `$PSCmdlet.WriteError()`) to emit non-terminating errors.

You mention _proxy_  functions: do they use `Write-Error`? Normally, proxy function, i.e. ones that use a steppable pipeline, _do_ set `$?` to `$false` for relayed non-terminating errors, at least if the command being proxied is a _binary_ cmdlet.

Is there an aspect we're not considering, such as CDXML / implicit remoting?

**Comment by SteveL-MSFT** [comment]
@mklement0 since this is ExchangeOnline, it's using implicit remoting so proxy functions are generated locally, hence was looking for a workaround in the interim.

**Comment by mklement0** [comment]
Thanks, @SteveL-MSFT, so just to clarify:

Auto-generated functions created in the context of implicit remoting have the same problem that local functions that use `Write-Error` do, i.e. they do not properly set `$?` to `$false` if (at least one) non-terminating error is emitted?

If (distant) memory serves, the only  way to get implicit remoting functions to generate a terminating error is to set `$ErrorActionPreference` in the _global_ scope, otherwise the module in which the functions run doesn't see it: `$global:ErrorActionPreference = 'Stop'`; saving and restoring the previous global setting is advisable.

**Comment by jhoneill** [comment]
TBH  I think as a way of testing whether ANY command had an error `$?` is flawed. It indicates "ran to completion" rather than "success", and   `try {foo}  catch {bar}`  is _more_ reliable , though it sometimes needs `-erroraction`  Style wise  we can see "I'm going to run some code and do something if there is an error" as soon as we see `try`   but 
```
foo
if (-not $?) {bar}
```
Requires us to think back to foo when our brains fill in the $? means "previous-ran-to-completion"  The behaviour of $? making us write clearer, code which isn't actually any more typing isn't a bad thing.

**Comment by mklement0** [comment]
@jhoneill, yeah, `$?` is only a very abstract way to test if _some_ error occurred.
In fact, it does _not_ necessarily indicate "ran to completion", given that a _statement_-terminating error also sets it to `$false`:

```powershell
Get-Item -NoSuchParameter  # a statement-terminating error reported by the parameter binder.
$? # -> $false
```

`$?` can be handy as a shortcut for `$LASTEXITCODE -eq 0` when calling _external programs_ (but a bug relating to `2>` redirections in _Windows PowerShell_ makes that unreliable).

`$?` is now _indirectly_ useful, as its value in effect is the basis of the pipeline-chain operators, `&&` and `||`:

```powershell
Get-Item NoSuchFile || 'dang!'   # with non-terminating error -> 'dang!' prints (too)
Get-Item -NoSuchParameter || 'dang!'  # with statement-terminating error -> 'dang!' prints (too)
# Unfortunately, does NOT work with functions that use Write-Error, as discussed
function foo { Write-Error 'non-terminating error' }; foo || 'dang!'  # !! 'dang!' does NOT print
```

To distinguish between non-terminating and terminating errors (whether statement- or script-terminating), you need `try` / `catch`:

```powershell
# With non-terminating error -> error prints, try / catch is IGNORED
try { Get-Item NoSuchFile } catch { 'I AM NEVER CALLED' }   
# With terminating errors -> no error output, catch block is called.
try { Get-Item -NoSuchParameter } catch { 'CAUGHT!' }  # statement-terminating error - 'CAUGHT!' prints
try { throw 'A fit' } catch { 'CAUGHT!' }  # script-terminating error - 'CAUGHT!' prints
```

---

As an aside:

* In the context of `$PSNativeCommandUseErrorActionPreference = $true`, the error that is emitted in response to a child process (external program) reporting a nonzero exit code, should be a statement-terminating one, so it can be also be caught with `try` / `catch`, which is currently not the case:
  * #18368

**Comment by jhoneill** [comment]
> distinguish between non-terminating and terminating errors (whether statement- or script-terminating), you need `try` / `catch`:
> 
> ```powershell
> # With non-terminating error -> error prints, try / catch is IGNORED
> try { Get-Item NoSuchFile } catch { 'I AM NEVER CALLED' }   
> # With terminating errors -> no error output, catch block is called.
> try { Get-Item -NoSuchParameter } catch { 'CAUGHT!' }  # statement-terminating error - 'CAUGHT!' prints
> try { throw 'A fit' } catch { 'CAUGHT!' }  # script-terminating error - 'CAUGHT!' prints
> ```


It gets complicated because we have 
-  non-terminating which just write a message to the error channel but don't terminate and can't be caught.   Since the next step runs the $? will end up as true. 
- "Statement terminating" which will normally be handled according to the value of `$errorActionPreference` in force (which may be locally set by `-errorAction`). The terminating error is treated as "caught"  simply by printing if the value is continue or not even printing it if it is silently continue. 
- "script terminating" one of the terminating commands - which won't be treated as caught simply by printing the message. 
- The powershell `throw` statement. Can be script-terminating, but if error-action is set to silently continue is considered to be handled. 
![image](https://user-images.githubusercontent.com/16209593/198239417-96f7ef0c-245d-448f-a69b-25f169dc66d8.png)

**Comment by mklement0** [comment]
My examples assume the _default_ value for `$ErrorActionPreference`, `'SilentlyContinue'`

> Since the next step runs the $? will end up as true.

Immediately after a cmdlet call that produced at least one non-terminating error (error records written to the error stream), `$?` is _`$false`_; the `try` / `catch` enclosure doesn't change that:

```powershell
try { Get-Item NoSuchFile } catch { 'I AM NEVER CALLED' }
$? # -> $false
```

>  will normally be handled according to the value of $errorActionPreference in force (which may be locally set by -errorAction)

`$ErrorActionPreference` and `-ErrorAction` are NOT equivalent, which is highly unfortunate: the former acts on _all_ error types (as you demonstrate with `throw`), the latter only on _non-terminating_ ones.

Resolving this asymmetry is being considered, but it would be a substantial breaking change:

* #14819

> "script terminating" one of the terminating commands - which won't be treated as caught simply by printing the message.

I don't understand.

**Comment by jhoneill** [comment]
> `$ErrorActionPreference` and `-ErrorAction` are NOT equivalent, which is highly unfortunate: the former acts on _all_ error types (as you demonstrate with `throw`), the latter only on _non-terminating_ ones.

No,  -ErrorAction definitely changes the behaviour for terminating errors. 
```
Function Get-Tangent {
     [cmdletbinding()]
     param ($a)
     $t = [math]::Tan($a)
     $t
     Write-Verbose "tan of $a  is $t"
}

PS>  try {Get-Tangent "hello" -verbose }  catch {"Problem finding tangent"}  #   terminating error catch works
Problem finding tangent   

PS>  Get-Tangent "hello" -verbose    # Error action continue verbose line runs 
MethodException:
Line |
   4 |      $t = [math]::Tan($a)
     |      ~~~~~~~~~~~~~~~~~~~~
     | Cannot convert argument "a", with value: "hello", for "Tan" to type "System.Double": "Cannot convert value "hello" ...
VERBOSE: tan of hello  is                     

PS>  Get-Tangent "hello" -verbose  -ea Stop   # terminating error is no longer handled by print and continue
Get-Tangent: Cannot convert argument "a", with value: "hello", for "Tan" to type "System.Double": "Cannot convert value "hello" 
...
```

And for throw 
```
 function throwSomething {
 [cmdletbinding()]
 param()
 throw "something"
 "This should not run"
}

PS>  throwSomething
Exception:
Line |
   4 |  throw "something"
     |  ~~~~~~~~~~~~~~~~~
     | something

PS>  throwSomething -ErrorAction SilentlyContinue
This should not run

```

Which is why I advise people to follow throw with return. 



> * [](https://github.com/PowerShell/PowerShell/issues/14819)
> 
> > "script terminating" one of the terminating commands - which won't be treated as caught simply by printing the message.
> 
> I don't understand.

OK. You have an old fashioned batch file. In it you have ping with invalid parameters. But the next line of the batch file runs. Even though ping terminated unless the next line is "check what happened and abort if ping failed" the rest of the script runs. So here there is no such thing as a script terminating error. An error might terminate a command, but it can't stop the batch file that called it.   

In a C# program you might have the equivalent of `[int]::Parse($s)` if s contains "one" this will cause a terminating error, the C# program can catch the error, but if it does not the program exits with a run time failure. So all terminating errors are the same - if they are not caught errors exit the program there and then. 

PowerShell has something different again. 
`[int]::Parse($s)`  is still a terminating error. We can still catch it, it's not just information going to the error channel. 
 `$errorActionPreference` (whether it is a global variable or set via the common parameter) decides whether and how that error will be trapped. Continue is "Print-message resume-next".  And its value in different scopes can change behaviour. 

```
 Function Get-Tangent {
    [cmdletbinding()]
    param ($a)
     $ErrorActionPreference = "stop"
    $t = [math]::Tan($a)
     $t
    Write-Verbose "tan of $a  is $t"
}
  
>  $ErrorActionPreference = "continue"

PS>  get-Tangent "hello" -verbose  ; "boo"
Get-Tangent: Cannot convert argument "a", with value: "hello", for "Tan" to type "System.Double": "Cannot convert value "hello" to type "System.Double". Error: "The input string 'hello' was not in a correct format.""
boo

```
Having action preference set to stop causes the function to exit without writing the verbose message, but when the message bubbles up to the command line where action is continue, it is printed and the next command runs. 

This is what I mean by printing the message is a treated as catching it 

But `write-error` with `-ea stop` or erroractionpreference set  the next command doesn't run
```
PS>  function one {
>> write-error "Stop" -ea stop
>> "this won't run"
>> }


PS>  one  ; "two"
one: Stop
```
This makes write error return a pipeline terminating error, we can only catch it...

**Comment by mklement0** [comment]
`-ErrorAction Stop` has no effect on your example:

```powershell
# Prints the error message and continues. Omitting -ErrorAction Stop behaves the same.
Get-Tangent "hello" -verbose -ErrorAction Stop; 'after'

# As opposed to (prints "caught!" only, 'after' doesn't get to execute)
try { Get-Tangent "hello" -verbose -ErrorAction Stop; 'after' } catch { 'caught!' }

# Ditto, via $ErrorActionPreference  = 'Stop' (but UNLIKE -ErrorAction Stop)
& {
  $ErrorActionPreference = 'Stop'
  Get-Tangent "hello" -verbose; 'after'
}
```

**Comment by mklement0** [comment]
As for the rest of your previous comment: no argument there, but it also drives home the point for _specific terms_ for  the _two kinds_ of _terminating errors_ that can occur in PowerShell, based on the _what the unit of execution is_ that they terminate.

> [int]::Parse($s) is still a terminating error. 

I'm calling this a _statement_-terminating error, because (by default) it terminates _just that statement_, and continues execution.

By contrast, `throw` creates a _script_-terminating error (not a precise term, as discussed; perhaps _fatal_ would be more descriptive, without having to get too technical about what the unit of executions).

It's interesting to note that binary cmdlets cannot themselves create such errors; `.ThrowTerminatingError()` is (by default) a _statement_-terminating error.

**Comment by jhoneill** [comment]
Lets out big sigh

> ```powershell
> # Prints the error message and continues. Omitting -ErrorAction Stop behaves the same.
> Get-Tangent "hello" -verbose -ErrorAction Stop; 'after'
> ```

No it doesn't 
<img width="565" alt="image" src="https://user-images.githubusercontent.com/16209593/198336840-25fa6db8-1d2b-4261-9554-9f41fed2cd9d.png">

As far as I can tell `-ErrorAction  x` / `warningAction x`, `-verbose` , and `-confirm` does is to set the value of the preference variable in the scope of that command.  

`-ErrorAction stop` in the function's scope causes the function to exit as soon as it hits an error, but outside the function where the value of `ErrorActionPreference` is different (continue), the error is printed and execution continues. 

And it doesn't matter whether $errorActionPreference is set by specifying -ErrrorAction as above  or as  variable as below
<img width="535" alt="image" src="https://user-images.githubusercontent.com/16209593/198340222-c4d1458a-1803-4abc-a5d8-066c7e23b1fe.png">

What I can't figure out is why this varies 

<img width="655" alt="image" src="https://user-images.githubusercontent.com/16209593/198345771-0d672563-c825-474e-a3b8-ed6aab71504d.png">

And if you know I'd love to hear. 

The rest as you say we agree on.   `Throw` is law unto itself. It will create a script / pipeline terminating error UNLESS the local scope has error action = Silently continue. In which case it continues silently.  This is multiple kinds of wrong, but probably too embedded to change.  I'm  not sure that anyone would say ALL of these are consistent 
<img width="424" alt="image" src="https://user-images.githubusercontent.com/16209593/198348016-bef27c0c-ceb4-4bc1-b513-17a53d9ccff4.png">

**Comment by mklement0** [comment]
Yes, good point, I missed one aspect:

An _uncaught_ statement-terminating error (exception) _inside_ a command _that happens to be implemented as a PowerShell script or function_, is susceptible to `-ErrorAction Stop` - indeed because `-ErrorAction Stop` is translated into a function-local `$ErrorActionPreference = 'Stop'` variable that then promotes _any_ error caused inside the function to what would _normally_ become a _script_-terminating one, but _in the context of an ADVANCED function_ turns into a _statement_-terminating one:

```powershell
# !! 'after' still prints.
& { [CmdletBinding()]param() $ErrorActionPreference = 'Stop'; 1 / 0 }; 'after'

# !! Ditto - ErrorAction Stop was NOT effective at the *command level*
& { [CmdletBinding()]param() 1 / 0 } -ErrorAction Stop; 'after'
```

But that is an _implementation detail_ of the command, and, strictly speaking, a statement-terminating error that happens to occur inside a function is not the same as a deliberately emitted statement terminating error, which requires `.ThrowTerminatingError()`.

It fits into the larger theme of cmdlet-like commands _implemented in PowerShell_ not behaving the same as _binary_ cmdlets, as is the case with `Write-Error`'s non-impact on `$?`

However:

* **Your example isn't susceptible to `-ErrorAction Stop` in the way that that parameter is _intended_** and is therefore _not effective_:
  * It only aborts the _internal_ execution of the PowerShell-implemented command (due to an implementation detail), but _does not abort execution overall_ (i.e. no _script_-terminating / fatal error occurs).

* By contrast, the subtlety wouldn't even arise with a _genuine_ statement-terminating error, as emitted via `.ThrowTerminatingError()`, given that it aborts the internal processing of the command right there and then by design.

**Comment by mklement0** [comment]
The bottom line with respect to authoring _advanced functions or scripts_ is:
If you want them to be well-behaved in terms of error handling (on par with _binary_ cmdlets):

* Only ever use `$PSCmdlet.WriteError()` and  `$PSCmdlet.ThrowTerminatingError()` to report errors (non-terminating and statement-terminating ones, respectively).
  * This ensures that `$?` is set correctly (in the _caller's_ scope).

* _Silence or catch_ any errors that may result from calls to others commands in the implementation, and translate them into one of the above calls, as appropriate. 
  * Failure to do so can make your function / script subject to premature termination when invoked with `-ErrorAction Stop`.

Note that while you're still free to use `throw` in such a function in order to emit a _script_-terminating (fatal) error, this would amount to behavior that diverges from that of a _binary_ cmdlet (which cannot emit such errors).

---

Here's a sample function that demonstrates the necessary techniques:

```powershell
Function Get-Foo {

  [CmdletBinding()]
  param(
    [string] $Path = '/',
    [string] $NumString = '0'
  )

  # Relay any non-terminating errors from PowerShell-native commands via
  # $PSCmdlet.WriteError(), and any terminating error (including exceptions
  # from expressions / .NET method calls) via $PSCmdlet.ThrowTerminatingError()

  try {

    # Stderr output need not necessarily be silenced - it isn't 
    # affected by -ErrorAction Stop / $ErrorActionPreference = 'Stop'
    & ($IsWindows ? 'cmd' : 'sh') ($IsWindows ? '/c' : '-c') 'echo stderr output >&2'

    # Handle *non-terminating* errors, as happens when $Path doesn't exist.
    # NOTE: 
    #  * If you don't care about any errors, use just -ErrorAction Ignore
    #  * 2>$null does NOT work, as it would abort processing right away
    #    when invoked with -ErrorAction Stop
    # Any cmdlet call that results in *statement-terminating* error would be 
    # handled in the `catch` block.
    (Get-Item $Path -ErrorVariable errs -ErrorAction SilentlyContinue).FullName
    # If errors were captured, relay them via $PSCmdlet.WriteError()
    if ($errs) {
      foreach ($err in $errs) { $PSCmdlet.WriteError($err) }
    }

    # Handle a potential terminating error.
    # If $NumString can't be parsed as an integer, the
    # resulting exception amounts to a statement-terminating error,
    # which is handled in the `catch` block.
    [int]::Parse($NumString)
    
  }
  catch {
    # Relay as a statement-terminating error.
    $PSCmdlet.ThrowTerminatingError($_)
    # Note: To emit a *script*-terminating error instead, use:
    #  throw $_
  }

  'Done.'

}
```

Some sample calls:

```none
# No errors.
PS> Get-Foo; $?
stderr output
/
0
Done.
True
```

```none
# Non-terminating error - note that $? is $False, function runs to completion.
PS> Get-Foo NoSuchFile; $?
stderr output
/
0
Done.
False
```

```none
# Statement-terminating error - note that $? is $False and 'Done' doesn't get to print.
PS> Get-Foo / NotANumber; $?
stderr output
/
Get-Foo: Exception calling "Parse" with "1" argument(s): "The input string 'NotANumber' was not in a correct format."
False
```

```none
# Both types of errors - note that $? is $False and 'Done' doesn't get to print.
PS> Get-Foo NoSuchFile NotANumber; $?
stderr output
Get-Foo: Cannot find path '/Users/mklement/Desktop/pg/NoSuchFile' because it does not exist.
Get-Foo: Exception calling "Parse" with "1" argument(s): "The input string 'NotANumber' was not in a correct format."
False
```

```
# Effect of -ErrorAction Stop on a *non-terminating* error:
#  Becomes *script*-terminating (fatal):
#  * Instantly aborts the function-internal processing.
#  * $? result does not get to print, because execution was aborted overall.
PS> Get-Foo NoSuchFile -ErrorAction Stop; $?
stderr output
Get-Foo: Cannot find path '/Users/mklement/Desktop/pg/NoSuchFile' because it does not exist.
```

```
# Effect of -ErrorAction Stop on a *statement-terminating* error:
#  NO effect - $? still gets to print - execution continues.
PS> Get-Foo / NotANumber -ErrorAction Stop; $?
stderr output
/
Get-Foo: Exception calling "Parse" with "1" argument(s): "The input string 'NotANumber' was not in a correct format."
False
```
