### ISSUE TITLE
More compact Get-ChildItem output

### ISSUE THREAD

**Issue by theuserbl** [PowerShell/PowerShell#18347]
### Summary of the new feature / enhancement

The output of Get-ChildItem is VERY wide.
Especially on Unix.

<img width="516" alt="pwsh" src="https://user-images.githubusercontent.com/8337032/197284313-032f0338-65f2-42bc-8bf0-f31e5ff713e6.png">

There are so much space between the username and the group name. Most times the standard width of a terminal window on Linux isn't width enough.

On Windows are only four rows (Mode, LastWriteTime, Length and Name) instead of the six on Unix (UnixMode, User, Group, LastWriteTime, Size and Name), so it haven't so much effect. But it is also more width then needed.

<img width="516" alt="pwsh2" src="https://user-images.githubusercontent.com/8337032/197287846-3d4918b3-7b7f-4fb5-a565-ea1dd7707e3f.png">

Btw: Why is the same column with the same thing on Unix called "Size" and on Windows called "Length" ?

**Comment by 237dmitry** [comment]
> Especially on Unix.

This is depends on your custom settings of format data output. `Get-Command *-FormatData`

![ArcoLinux_2022-10-22_00-27-26](https://user-images.githubusercontent.com/78153320/197291395-fb98ee22-c6bd-48db-8d76-4b412eaf0917.png)

**Comment by MartinGC94** [comment]
There was a recent update to address this: https://github.com/PowerShell/PowerShell/pull/18183 so the next preview will probably include this change.

**Comment by jhoneill** [comment]
This is a duplicate. 
I've posted a replacement of for the file XML 
https://gist.github.com/jhoneill/4b74aa82cb5b4608687b24dddef293f8 
This removes some columns but you can have exactly the columns you wish.  Because the `get-childitem` outputs file and directory objects and they go through a generic formatter, it is preferable to make the columns fixed width, so user, group and size are wider than they need to be.

**Comment by SteveL-MSFT** [comment]
Unix and Windows have different format definitions for `FileSystemInfo` type as Unix has the additional properties.  However, it seems that it should be `Length` instead of `Size` to be consistent.  The Cmdlets WG should discuss.  Since this is formatting only, it's not considered a breaking change.

As noted, the format definition takes either no column width or a fixed width.  It's dynamic only if you specify no column width and determines the appropriate width based on a few instances then uses that for the rest.  So this means that if `root` (4 chars) is the first few instances, then something longer, you'll get a truncated name for anything > 4 chars.

It might make sense to reduce the column width for user/group to maybe 8 chars?  It's currently set to 10 chars (https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs#L49-L50)

**Comment by JamesWTruher** [comment]
the reason it's size is because that's how this value is referred to on Unix. It can also be different than length. Or rather, size is completely legitimate for a directory on Unix where the property `Length` is not even present for DirectoryInfo. I would rather keep these separate as there may be some code that uses this missing property to disambiguate between directories and files.

**Comment by SteveL-MSFT** [comment]
The Cmdlets WG reviewed this and regarding the width, we agree to reduce the user and group columns to 8 instead of 10.  Note that users can get more tight formatting using `dir | ft -autosize` already.  Regarding `Size` vs `Length` we recommend opening a new issue to discuss that if anyone feels passionately about it.  The summary is that `Size` is only applicable to Unix since directories have size while Windows directories do not have length and the name `Size` is consistent with ls output.

**Comment by daxian-dbw** [comment]
Closed as fixed by #18183
