### ISSUE TITLE
Mandatory param HelpMessage not working in Powershell 7.2.7

### ISSUE THREAD

**Issue by garretwilson** [PowerShell/PowerShell#18387]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The [parameters documentation](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.2) says that if a mandatory parameter is missing, the help message is shown as a prompt. (Various web sites imply this as well.)

> The `HelpMessage` argument specifies a string that contains a brief description of the parameter or its value. PowerShell displays this message in the prompt that appears when a mandatory parameter value is missing from a command.

I'm a PowerShell newbie, but "PowerShell displays this message in the prompt that appears when a mandatory parameter value is missing from a command" is pretty unambiguous. It says that 1) if there is a mandatory parameter, and 2) the value is missing, then 3) the specified help message will be displayed, and 4) that help message will be displayed at the prompt that appears asking for the missing value. I'm not sure how I could be misinterpreting that.

This is the example given in the official documentation, verbatim:

```powershell
Param(
    [Parameter(Mandatory,
    HelpMessage="Enter one or more computer names separated by commas.")]
    [string[]]
    $ComputerName
)
```

### Expected behavior

```console
PS> .\test-param-help-message.ps1

Enter one or more computer names separated by commas.
```

### Actual behavior

```console
PS> .\test-param-help-message.ps1

cmdlet test-param.ps1 at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
ComputerName[0]:
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
I think this behavior was always. The same is in Windows PowerShell. Enter `!?` and get help message.

**Comment by mklement0** [comment]
Related:
* #7093
* All open issues related to prompts for mandatory parameters:
  * https://github.com/PowerShell/PowerShell/issues?q=is%3Aissue+is%3Aopen+mandatory+parameter+prompt+in%3Atitle+

**Comment by kilasuit** [comment]
@garretwilson PowerShell is trying to tell you **slowly** that you have missed the mandatory parameter & that if you want to learn more then you must enter `!?` to learn more.

This is a design decision due to the fact that PowerShell can be used to change state, and in many cases the operator, not the script author, may be rushing and not taking that much needed step back to ensure that the changes they want to enact are actually correct. It is also why we have Confirm & WhatIF built into the language, which when used properly is to help reduce accidental harms in System Administration, like an accidental deletion of everything in the C Drive.

To get your expected behaviour you should not use parameters but instead in the script make use of the `Read-Host` cmdlet however you'd lose the ability to run this non-interactively unless you made the parameter non-mandatory and then equated for either it being provided when called or after it was called. This is where you'll start to find you need to make choices whilst authoring scripts, dependant on how it is to be run and who is intended to run it & what skill level with PowerShell they have. 

I'd strongly suggest as someone new to PowerShell to come join the [PowerShell Slack](https://aka,ms/psslack) or [PowerShell Discord ](https://aka,ms/psdiscord) servers (which are bridged together so slack users can interact with discord users & vice versa) where you could ask a question like this

**Comment by garretwilson** [comment]
Thank you for addressing _correctness of behavior_, by explaining that PowerShell here is functioning as (someone) intended. But your response failed to address _consistency with documentation_ and _usefulness_.

### Consistency with Documentation

The documentation clearly and unambiguously says that PowerShell "displays this message in the prompt that appears". It doesn't say "displays this message in a separate help screen that the user may access by pressing additional keystrokes at the prompt that appears". The current behavior directly contradicts the documentation.

### Usefulness

Users will not actually use the feature as implemented. Don't take my word for it. Let me just quote from `powershell.org`, [A Helpful Message about HelpMessage](https://powershell.org/2013/05/a-helpful-message-about-helpmessage/) (bold in the original):

> Here’s my help message about HelpMessage:
> **Don’t use it**! Users can’t see it. It does no harm, but it has no value. Danger lurks in writing a HelpMessage instead of writing help that users can see. … The language permits it. But it’s not useful).
> …
> When you omit a mandatory parameter, you get a message like this one: … `(Type !? for Help.)`
> And then you type “!?” to get the HelpMessage value.
> You’ve never done that? Me neither!

Note specifically "it has no value" and "it’s not useful".

You also say:

> To get your expected behaviour you should not use parameters but instead in the script make use of the `Read-Host` cmdlet …

Well actually [`Read-Host` would have been my first choice](https://stackoverflow.com/a/8184861), but [other discussion](https://stackoverflow.com/a/8236524) was adamant that this was an anti-pattern. I was only try to use best practices.

**Comment by mklement0** [comment]
@garretwilson

Good point about the documentation: I've submitted https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9365 to get that fixed, and I encourage you to open documentation issues yourself in the future.

As for whether `HelpMessage` is worth using:

Personally, I'd go further and say that automatic prompting as a whole is not worth using, given its many current limitations, detailed in https://github.com/PowerShell/PowerShell/issues/7093

Unfortunately, the only way to currently opt out is with the following, which uses `throw` to create a (script-terminating) error when a (conceptually) mandatory parameter is passed:

```powershell
function foo {
  [CmdletBinding()]
  param(
    [Parameter()] # # NO 'Mandatory' property
    [string] $MustHave = $(throw "Must have -MustHave") # Use default value to throw
  )
}
```

What I personally think would make sense, going forward:

* Disable automatic prompting by default, and report a (statement-terminating) error if a mandatory argument is missing, as you would get with _invalid syntax_ (such as trying to run `Get-ChildItem -Path` without an argument).

  * Since this change affects only _interactive_ behavior, it shouldn't be considered breaking.

* Make prompting _opt-in_ (though given its current limitations, I suspect few people would use that; it may become useful if and when the limitations are fixed, which is  a nontrivial effort) perhaps via a new common parameter (potential name collisions are a concern, perhaps a `PS` prefix helps, though it would be inconsistent with existing common parameter names).

**Comment by garretwilson** [comment]
> Personally, I'd go further and say that automatic prompting as a whole is not worth using …

Oh, wow, OK. Thanks for being up-front about that.

As I said my first inclination was to just ask the user, but most of the times when I ask questions like this, the answer is, "No, you're thinking in the old DOS/Bash mindset; do it the PowerShell way", and often the response comes with "and you should be using `Param`, because they are awesome and take care of all your problems". So I was trying to get on board, especially reading [things like this](https://stackoverflow.com/a/8236524) (against use of `Read-Host`:

> Using parameter binding is definitely the way to go here. Not only is it very quick to write (just add  `[Parameter(Mandatory=$true)]` above your mandatory parameters), but it's also the only option that you won't hate yourself for later.
> …
> [Read-Host](http://technet.microsoft.com/en-us/library/hh849945.aspx) is, quite simply, bad form.

Anyway it sounds like for a lot of things there isn't agreement on best practices in the Powershell community. Thanks for helping explain that.

(Although I really don't see what is wrong or so difficult about just printing the help message at the prompt. Seems like other experts such as @mklement0 [thought the same thing](https://github.com/PowerShell/PowerShell/issues/7093#issuecomment-420299268). And whoever wrote the documentation obviously thought it worked that way; the documentation isn't a typo—it was very clear and straightforward. But anyway I have more important things to tackle and I'll leave it at that.)

**Comment by garretwilson** [comment]
>  Seems like other experts …

Hahah. Sorry, @mklement0, when I referred to your other comment I didn't realize I was replying to you. I didn't look closely and thought your reply was also from @kilasuit as was the earlier one. Oops.

Have a great day both of you.
