### ISSUE TITLE
Table formatting non-integer numbers in [pscustomobject]

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#18492]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Table formatting of `[pscustomobject]` leads to the output of non-integers ONLY in thousandths. 

```powershell
            
 [pscustomobject] @{
    'a' = 1.0     
    'b' = 1.12         
    'c' = 1.123  
    'd' = 1.1234
}
```

```
    a     b     c     d
    -     -     -     -
1,000 1,120 1,123 1,123
```

### Expected behavior

```console
Outputting data as is.
```

### Actual behavior

```console
Output of non-integers only in thousandths
```

### Error details

```console
No errors
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-rc.1
PSEdition                      Core
GitCommitId                    7.3.0-rc.1
OS                             Linux 6.0.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Nov 2022 18:01:58 +0000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
After upgrading to `7.3.0`, the problem remained. In Windows, the same problem, but non-integers are rounded to hundredths.

```
 [pscustomobject] @{
 'a' = 1.0     
 'b' = 1.12         
 'c' = 1.123  
 'd' = 1.1234
}
```

```
    a     b     c     d
    -     -     -     -
  1,00  1,12 1,12  1,12
```

**Comment by jhoneill** [comment]
This was changed intentionally to ensure tables format consistently. 

Previously 
 [pscustomobject] @{
 'a' = 1.0     
 'b' = 1.12         
 'c' = 1.123  
 'd' = 1.1234
} ,  [pscustomobject] @{
 'a' = 1.234     
 'b' = 1.123        
 'c' = 1.12  
 'd' = 10/9
}

gave
```
    a     b     c                d
    -     -     -                -
    1  1.12 1.123           1.1234
1.234 1.123  1.12 1.11111111111111
   
```

Which is, frankly , pretty awful

**Comment by 237dmitry** [comment]
`10/9`
I don't even know what to say.

**Comment by sba923** [comment]
> Which is, frankly , pretty awful

There are options for removing the ugliness, while preserving the data:

````
    a      b      c                 d
    -      -      -                 -
1.000  1.120  1.123  1.12340000000000
1.234  1.123  1.120  1.11111111111111
````

or

````
    a      b      c                 d
    -      -      -                 -
1      1.12   1.123  1.1234          
1.234  1.123  1.12   1.11111111111111
````

The current behavior, in Windows PowerShell's or PowerShell 7.3.4's `Out-GridView`, and in PowerShell 7.3.4's `Format-Table -AutoSize`, doesn't preserve the data:

````
   a    b    c    d
   -    -    -    -
1.00 1.12 1.12 1.12
1.23 1.12 1.12 1.11
````

<img width="127" alt="image" src="https://user-images.githubusercontent.com/12860484/234928322-c8dda443-de1a-4aed-8b2a-4a38dd418f58.png">

**Comment by jhoneill** [comment]
@sba923  

The problem is some data is always truncated. 
1/9  or 1/3 truncate after  15 places.   PI isn't stored exactly , which means `[math]::Tan(([math]::pi/2))` has an infinite error. 

Does it matter if we display 3.14159265358979   or 3.14159  / 0.333333333333333  or 0.333   ?  I would argue not. 

OTOH 1/256  doesn't truncate  0.00390625  is the full number If we round it to 2 places we get 0 which is not helpful. 
Dealing with shutter speed times with camera I get 1/8000,  and then doubling the time down to 1/125, and I do need to distinguish between 1/125 (0.008) and 1/100 (0.01).  Any guess PowerShell makes is going to be wrong a percentage of the time.   

here's the old format - note that time rounds at 6 places because it converting the speed from log2 of 1/speed time so 1/30th is stored as   4.906891 - which is 1/30.0000084090856  and f/number rounds at 1 place because that's stored in a similar way. 
```
Get-LightRoomItem -Include london | ft BaseName,ExposureTime,fNumber

baseName      ExposureTime FNumber
--------      ------------ -------
IM100740             0.008     4.5
IM100741             0.008     4.5
IM100742            0.0125     5.6
IM100743              0.01     5.6
IM100744            0.0025     5.6
IM100745            0.0025     5.6
IM100746            0.0025     5.6
IM100747            0.0025     5.6
IM100748             0.002     5.6
IM100749          0.001563     5.6
IM100750          0.001563     5.6
IM100751          0.033333     5.6
IM100756           0.00125      11
```

The exposure time column is next to useless. 
The F/ number is **almost** OK, because photographers know "whole stops" go f/2, f/2.8, f/4, f/5.6, f/8, f/11, f/16 , f/22, and we only write 1 place of decimals for values below 10. (f/5.6 is really f/5.7, f/11 is really, f/11.3, and f/22 should round to f/23). When I convert I could make the f/ number a string but then the sort order would be wrong.  

The new way looks like  this 
```
baseName      ExposureTime FNumber
--------      ------------ -------
IM100740              0.01    4.50
IM100741              0.01    4.50
IM100742              0.01    5.60
IM100743              0.01    5.60
IM100744              0.00    5.60
IM100745              0.00    5.60
IM100746              0.00    5.60
IM100747              0.00    5.60
IM100748              0.00    5.60
IM100749              0.00    5.60
IM100750              0.00    5.60
IM100751              0.03    5.60
IM100756              0.00   11.00
```
The first 4 which had 3 exposure time values have become the same and the next 4 have become zero. And no photographer ever writes f/11.00 or f/5.60  

Using .tostring("n") to apply what the local culture says default number formatting is (two decimal places in most places) is a **the best guess most of the time.** However when most of the values are less than 0.05 , and especially if they are smaller than 0.0001 and would be written in exponent notation, that shows it is a **bad guess some of the time**.  The original lack of formatting "yeah, whatever places for each", was probably a **worse guess more of the time** but was **the right guess sometimes** . 
No default is going to please everyone every time, I thought originally that an easy way to replace the default was needed, at one point I did think changing the default would do it, but I'm back to my original thinking.
