### ISSUE TITLE
Auto conversion of simple functions/scripts into advanced functions

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#18527]
### Summary of the new feature / enhancement

Currently any function/script definition that uses a `[parameter]` attribute auto inherits the `[cmdletbinding]` attribute

Why not just go all the way and make all functions/scripts actually be advanced functions/scripts by default and then let the author **opt-in** to additional advanced features

### Proposed technical implementation details (optional)

This likely would need changes in the engine but would likely lead to simplification of code base

**Comment by mklement0** [comment]
While the simple vs. advanced functions dichotomy is somewhat unfortunate, making _all_ functions/scrpts advanced ones would be a massively breaking change, given that advanced functions do not support `$args`:

```powershell
# OK
& { $args } 'woot!'

# !! FAILS
& { [cmdletbinding()] param() $args } 'oh noes!'
```

**Comment by dwtaber** [comment]
> While the simple vs. advanced functions dichotomy is somewhat unfortunate, making _all_ functions/scripts advanced ones would be a massively breaking change, given that advanced functions do not support `$args`:
> 
> ```powershell
> # OK
> & { $args } 'woot!'
> 
> # !! FAILS
> & { [cmdletbinding()] param() $args } 'oh noes!'
> ```

I guess the obvious—not necessarily easy!—fix for that issue would be to add `$args` support for advanced functions, with some exception for advanced functions that explicitly declare an `$args` parameter of their own.  I mean, I'm sure there would be other significant behavior and performance implications for making all functions advanced functions, but it might be worthwhile to chip away at the differences when possible.

**Comment by mklement0** [comment]
@dwtaber, the crux of the issue is that advanced functions do not support _unbound_ arguments, so the problem isn't `$args` per se, but the fact that - by design - you're only allowed to pass arguments that bind to explicitly declared parameters.

Making existing advanced scripts and functions suddenly support unbound arguments would be both breaking and undesirable.

**Comment by kilasuit** [comment]
I'm not saying it is going to happen, but is a suggestion that may be worthwhile in a way that means that this is a potential `PowerShell 8` feature.

**Comment by dwtaber** [comment]
> @dwtaber, the crux of the issue is that advanced functions do not support _unbound_ arguments, so the problem isn't `$args` per se, but the fact that - by design - you're only allowed to pass arguments that bind to explicitly declared parameters.
> 
> Making existing advanced scripts and functions suddenly support unbound arguments would be both breaking and undesirable.

I feel like I'm overlooking something obvious, but what effect would it have on advanced functions that didn't make use of `$args`?  What effects do unbound parameters currently have on simple functions that don't make use of `$args`?  I'm not necessarily saying this is a change worth breaking anything over; I'm just trying to understand the implications.

**Comment by jhoneill** [comment]
> I'm not saying it is going to happen, but is a suggestion that may be worthwhile in a way that means that this is a potential `PowerShell 8` feature.

A couple of recent issues have mention the Don't show option . 

Consider this 

```
function foo ($a)  {"boo"}

foo -bar aaa  
boo
```

The whole unbound args thing that @mklement0  mentions means that as declared foo doesn't break when called with a non-existent  parameter. So how many "non advanced" functions are out there being called with defunct parameters ? How many rely on `$args. ` ?

Making `[cmdletbinding()]`  opt out instead of opt in would save a few keystrokes and light up -verbose etc but trail of breakages would be too big and you end up with a version people dare not adopt.

**Comment by mklement0** [comment]
To provide another example to illustrate @jhoneill's point: It is also about _interactive_ use:

Say you've authored an advanced function `Get-Foo` in the past that has _no_ mandatory parameters and _no_ positional ones.
Currently, `Get-Foo anything` - sensibly - reports an error and _refuses to run_, because the argument cannot be bound to a declared parameter.
If we started supporting `$args` _by default_, `Get-Foo anything` would have to _succeed_ (with the target function deciding how to act on `$args`), which in this case means _unintended execution_ with arguments that are ignored.

I generally like the idea of providing as much functionality as possible to functions via the "plumbing", by default, but:

* as long as backward compatibility must be maintained, we need to tread carefully, as the `$args` issue shows; another area of concern would be that if previously simple functions suddenly supported common parameters, they could clash with existing parameters of the same name.

* even leaving backward compatibility out of the picture, it makes sense to have two distinct types of functions, targeted to different audiences / use cases: simple in syntax and permissive vs. carefully designed and robust.

On a related note, #8819 proposes syntax and behavioral improvements to _advanced_ functions, specifically.

**Comment by dwtaber** [comment]
>[...]
> _unintended execution_ with arguments that are ignored.
> [...]

That's a good point.  It makes me think of times I've unintentionally launched a program by not using the right name for its executable's help parameter.  I think you've convinced me on the `$Args` sub-issue 🙂

As for the actual issue at hand, I suspect there'd be a noticeable performance hit associated with doing the whole nine yards for every little helper function.  I wonder just how much it would slow things down.
