### ISSUE TITLE
Handling of QUOTATION MARK characters appears to have changed in 7.3.0

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#18540]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The following statement was working under 7.2.

`& svn.exe co `"https://svnrepo.myco.com/db/trunk/$_`"`

GRAVE ACCENT characters not showing up correctly. Sorry for the picture.

![image](https://user-images.githubusercontent.com/2530958/201435638-851d2e52-d156-4bf7-8c33-3f10b05384db.png)

After installing 7.3.0, it produces:

`svn: E170000: Illegal repository URL '%22https://svnrepo.myco.com/db/trunk/Scripts%22`

### Expected behavior

```console
Working copy is checked out.
```

### Actual behavior

```console
Working copy is not checked out.
```

### Environment data

```powershell
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by pinkfloydx33** [comment]
Have noticed this as well; it broke some of our CI scripts that call out to all sorts of executables. Have also experienced slightly different behaviors between windows and Linux depending on the target application (for example ef migration bundles) and sometimes different if I splat arguments. 

So far only when invoking applications and not with commandlets 

I intend on opening issues in a few repos that offer argument completer scripts (Flux, helm, kustomize) as their powershell variants are all broken since 7.3 (with a simple fix)... Will link here once I do. 

I checked release notes and didn't see mention of this behavior.

**Comment by mklement0** [comment]
v7.3 introduced a breaking change with respect to the - previously fundamentally broken - handling of (embedded) `"` chars. in arguments passed to _external programs_.

To make the previous workarounds that build on the broken behavior work, you must (temporarily) set [`$PSNativeCommandArgumentPassing`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Preference_Variables#psnativecommandargumentpassing) to `'Legacy'`.

For a summary of the consequence of the breaking change, see [this comment](https://github.com/PowerShell/PowerShell/issues/13428#issuecomment-1297723605).

**Comment by mklement0** [comment]
As an aside re formatting, @Liturgist: 

You can _double_ the enclosing `` ` `` in order to (in-line) format code that has embedded `` ` ``

E.g., 

```
`` a`b ``
```

renders as `` a`b ``

**Comment by Liturgist** [comment]
@mklement0, is it possible to write a script that will run unchanged on 7.3+ and 7.2- without embedding $PSNativeCommandArgumentPassing`? Is that the only way?

Trying to install 7.2.7 fails because. "A newer version of PowerShell is already installed"  How can I install the earlier version in order to test?

**Comment by mklement0** [comment]
@Liturgist, unfortunately, I don't think that's possible: if you want existing code to run without (other) modifications on both 7.2- / Windows PowerShell and 7.3+, you'll need to deal with `$PSNativeCommandArgumentPassing`.

_Going forward and/or if modifying old code is possible_, for cross-edition / cross-version code you could consider using the `ie` function from my [`Native` module](https://github.com/mklement0/Native) (`Install-Module Native`), which works in both editions and all PS Core versions, irrespective of the effective value of `$PSNativeCommandArgumentPassing`.
Additionally, it incorporates the [proposed-in-vain accommodations for batch files and other high-profile CLIs](https://github.com/PowerShell/PowerShell/issues/15143), so that no workarounds are needed in _most_ cases: just prepend `ie` to your external-program calls.

**Comment by mklement0** [comment]
@Liturgist, as for installing an older version alongside the most recent one: I haven't personally tried, but it looks like [installing via a specific version's `.zip` package](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows#installing-the-zip-package) may do the trick.
