### ISSUE TITLE
Parameter invalid when it contains a colon. Works prior to 7.3.0.

### ISSUE THREAD

**Issue by rmegal** [PowerShell/PowerShell#18554]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Enter:

```
$test = "&sqlcmd -v MDF_FILEPATH=```"C:\Databases\junk.mdf```""
invoke-expression $test
```

### Expected behavior

```console
sqlcmd is launched and you can enter:

select '$(MDF_FILEPATH)'
go

And be presented with:

----------------------------
C:\Databases\junk.mdf
```

### Actual behavior

```console
sqlcmd is no longer able to parse parameter value and you get the following after the invoke-expression:

Sqlcmd: 'MDF_FILEPATH=\"C:\Databases\junk.mdf\""': Invalid argument. Enter '-?' for help.
```

### Error details

```console
n/a
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![PowerShell_7 3](https://user-images.githubusercontent.com/213904/201752880-114f506b-4f3b-494e-8dd3-a9341ece3328.gif)

![PowerShell_prior_to_7 3](https://user-images.githubusercontent.com/213904/201752924-6a4bd8fd-d143-406d-98ab-e53d36783c29.gif)

**Comment by SteveL-MSFT** [comment]
Use:

```powershell
 $PSNativeCommandArgumentPassing = 'Legacy'
```

for now as a workaround.  We probably need to add `sqlcmd` to the legacy list.   cc @JamesWTruher

**Comment by SteveL-MSFT** [comment]
@rmegal if you can confirm using `Legacy` mode works for you, I'll update the list to include sqlcmd

**Comment by rmegal** [comment]
Using $PSNativeCommandArgumentPassing = 'Legacy' **works** for sqlcmd.

I will use Legacy for the scripts I have that use sqlcmd directly. Will I need to keep doing this once sqlcmd is in the legacy list? Not sure how the "legacy list" works.

**Comment by SteveL-MSFT** [comment]
Once we have the list updated and backported to 7.3.x, the idea is that you can keep `$PSNativeCommandArgumentPassing = 'Windows'` (which is the default) and commands in the list automatically use `legacy` when needed for compat.  So you shouldn't have to make any changes.  However, if you uset `legacy` at the top of your script, then the changes we're making should still not break you and you can keep it like that as well.

**Comment by JamesWTruher** [comment]
it is also likely that the triple back-tick is no longer needed (a single might do the trick with this new behavior)

**Comment by jborean93** [comment]
> The original script uses it because the command is dynamically built; there are a bunch of different parameters that might get used.

You can still do that without Invoke-Expression

```powershell
$sqlCmdArgs = @(
    'arg that is always set'
    if ($someCondition) { 'args for sqlcml' }
    'arg that is always set'
)
sqlcmd @sqlCmdArgs 
```

You can also splat multiple arrays or use args inline with splats so you aren't restricted to just this. Using `Invoke-Expression` is dangerous if the data comes from a user source and adds yet another layer you need to deal with when it comes to strings. It is best to try and avoid it in as many cases as you can.

**Comment by mklement0** [comment]
@jborean93 , good point about avoiding `Invoke-Expression`, but quoting `MDF_FILEPATH=c:\test\junk.mdf` doesn't make a difference, because the problem is on the `sqlcmd` side.

@rmegal:

>  if I'm understanding correctly, `sqlcmd` will need the 'Legacy' support unless it is changed to accept `"MDF_FILEPATH=C:\My Databases\junk.mdf"`?

In principle, yes, but there seems to be another wrinkle:

PowerShell - again, justifiably - _never_ uses double quotes _behind the scenes_ if an argument doesn't contain spaces, even if in the original _PowerShell_ command line quotes _were_ used; that is, both `'MDF_FILEPATH=c:\test\junk.mdf'` `"MDF_FILEPATH=c:\test\junk.mdf"` and `MDF_FILEPATH=c:\test\junk.mdf` all end up as _unquoted_ `MDF_FILEPATH=c:\test\junk.mdf` on the process command line.

It seems that `sqlcmd.exe` (which I'm not familiar with) breaks an _unqoted_ value that contains `:` by that character, which is what your error message suggests (the docs don't seem to mention that).

If that is the case, then truly only _partial_ quoting helps; that is, the following must be placed on the process command line: `MDF_FILEPATH="c:\test\junk.mdf"`, which you can only do in one of the following ways:

* with your original legacy workaround that builds on the broken behavior, which now requires you to (temporarily) set `$PSNativeCommandArgumentPassing` to `'Legacy'`

* with `--%`, which comes with pitfalls and fundamental limitations, however
  * `sqlcmd -v --% MDF_FILEPATH="c:\test\junk.mdf"`

* by calling via `cmd /c`
   * `cmd /c 'sqlcmd -v MDF_FILEPATH="c:\test\junk.mdf"'`

**Comment by mklement0** [comment]
@daxian-dbw, it seems to me this issue is entirely unrelated to `Invoke-Expression`:

The legacy workaround places the following on the process command line, which, I presume, _worked_:

```
MDF_FILEPATH="C:\Databases\junk.mdf"
```

In 7.3.0, the following is placed on the process command line:

```
MDF_FILEPATH=\"C:\Databases\junk.md\"
```

If the former worked, why would you expect the latter to work, which is obviously different?

Only if you interpreted the latter _verbatim_ would you end up with `MDF_FILEPATH="C:\Databases\junk.mdf"`, but that is beside the point, given that _syntactically relevant_ `"` characters are the issue here.

**Comment by rmegal** [comment]
@daxian-dbw I agree with @mklement0, the issue is unrelated to `Invoke-Expression` as I can recreate the problem without using it, and using the legacy workaround does allow the command to complete as before.

**Comment by daxian-dbw** [comment]
I'm not saying it's related to `Invoke-Expression`, but just using that as the reported repro to understand the issue. With that specific repro, it looks to be a user error because the extra 2 backticks surrounding `C:\Databases\junk.mdf` seems to be unnecessary even when running on 7.2.x. When the extra 2 backticks are removed, the original repro should just work in 7.3.0, and that's why I asked @rmegal to try if the following works in 7.3.0 after setting `$PSNativeCommandArgumentPassing = 'Windows'`.

```
$test = "&sqlcmd -v MDF_FILEPATH=`"C:\Databases\junk.mdf`""
invoke-expression $test
```

> I can recreate the problem without using it, and using the legacy workaround does allow the command to complete as before.

Can you please provide another repo without using `Invoke-Expression`? We need to evaluate whether this is a user error to decide whether or not `sqlcmd` should be added to the legacy list.

**Comment by mklement0** [comment]
> `$test = "&sqlcmd -v MDF_FILEPATH=`"C:\Databases\junk.mdf`""; `invoke-expression $test`

can be reduced to `&sqlcmd -v MDF_FILEPATH="C:\Databases\junk.mdf"`, which  - due to _not containing spaces_ - is placed as  _unqouoted_, verbatim `MDF_FILEPATH=C:\Databases\junk.mdf` on the process command line.

Since there are no _embedded_ `"` characters to pass,  v7.2- and v7.3 behave the same.

As @rmegal  reports, such an _unquoted_ token appears _not_ to work with `sqlcmd`, because the _unquoted_ `:` appears to have special meaning to `sqlcmd`.

The workaround is to _ensure double-quoting_, selectively around the value part, so that verbatim `MDF_FILEPATH="C:\Databases\junk.mdf"` is placed on the process command line.

* In v7.3, with (effective) `Standard` behavior, _this cannot be done_  - except with the `--%` and `cmd /c` workarounds previously discussed.

* In v7.2, or in v7.3 with `Legacy` in effect, you can build a workaround on the _old, broken behavior_, which is what the command in the OP does:

```powershell
& { $PSNativeCommandArgumentPassing = 'Legacy'; sqlcmd -v MDF_FILEPATH=`"C:\Databases\junk.mdf`" }
```

**Comment by daxian-dbw** [comment]
> In v7.2, or in v7.3 with Legacy in effect, you can build a workaround on the old, broken behavior, which is what the command in the OP does:
> ```
> & { $PSNativeCommandArgumentPassing = 'Legacy'; sqlcmd -v MDF_FILEPATH=`"C:\Databases\junk.mdf`" }
> ```

This is the part that I'm confused with. See my screenshots below (running in 7.2.7, which essentially uses the `Legacy` mode):

![image](https://user-images.githubusercontent.com/127450/202281028-3c2e1b10-0fc8-4f62-aaf0-2944f12c4ba1.png)

I replaced `sqlcmd` with `testexe.exe -echoargs` to print out the passed in arguments. The results show no difference in having ` `"` or `"` surrounding `C:\Databases\junk.mdf`. Both have verbatim `MDF_FILEPATH=C:\Databases\junk.mdf` on the process command line. Did I do something wrong?

**Comment by mklement0** [comment]
You need to look at the _raw command line_ to see the difference, which `test.exe -echoargs` doesn't show.

Allow me to use some canned advice on how to get a utility that _does_:

* If you use [Chocolatey](https://chocolatey.org/), you can use `choco install echoargs -y` from an elevated session to install `echoargs.exe`, which shows the raw command line that PowerShell builds behind the scenes, and how (most) external programs parse it into arguments. Alternatively, you can compile a utility ad hoc: see [this answer](https://stackoverflow.com/a/69832150/45375).

The difference is that your first command places `MDF_FILEPATH="C:\Databases\junk.mdf"` on the process command line (note the double quotes), whereas it is `MDF_FILEPATH=C:\Databases\junk.mdf` for the second command.

To an executable _that uses the runtime-provided  Microsoft C/C++/.NET argument parsing_ of the process command line, as `test.exe -echoargs` does, these two arguments result in the _same_ verbatim argument, namely `MDF_FILEPATH=C:\Databases\junk.mdf` - that is, the (unescaped) `"` characters are assumed to have _syntactic_ function and are _removed_.

However, here we're talking about an executable, `sqlcmd.exe`, that seemingly _defines its own rules_ and treats those raw arguments _differently_ - that is the curse of the anarchy that is argument-passing on Windows, which - rather than passing an _array_ of _verbatim_ tokens, as is the case on Unix - forces each executable to act as its own quasi-shell  and parse its arguments from a _single string_ that encodes all arguments.

To an executable _that uses the runtime-provided  Microsoft C/C++/.NET argument parsing_, _all_ of the following are _equivalent_, but _to `sqlcmd` and other high-profile CLIs such as `msiexec` and `msdeploy`, they aren't_:

* `MDF_FILEPATH=C:\Databases\junk.md`
* `MDF_FILEPATH="C:\Databases\junk.md"`
* `"MDF_FILEPATH=C:\Databases\junk.md"`

The related _executable-agnostic_ accommodation I proposed as part of #15143 focus on values (the argument part to the right of `=`) that _require_ double-quoting, due to _containing spaces_, so that PowerShell would place whatever _PowerShell_ syntax variation results in verbatim value `foo=bar baz` to pass as _selectively double-quoted_ `foo="bar baz"` on the process command line.

However, it seems that `sqlcmd` elevates the anarchy to new heights, by also distinguishing between a _space-less_ argument that is placed on the process command line as `foo=c:\bar` vs. `foo="c:\bar"`

**Comment by daxian-dbw** [comment]
> However, here we're talking about an executable, sqlcmd.exe, that seemingly defines its own rules and treats those raw arguments differently ...
> To an executable that uses the runtime-provided Microsoft C/C++/.NET argument parsing, all of the following are equivalent, but to `sqlcmd` and other high-profile CLIs such as `msiexec` and `msdeploy`, they aren't:

@mklement0 This makes perfect sense to me now, thank you!
So, it makes sense to have `sqlcmd` in the [legacy command list](https://github.com/PowerShell/PowerShell/blob/4ce439ebb7d988101e46eee9c6067b31edac60e1/src/System.Management.Automation/engine/NativeCommandProcessor.cs#LL246-L253C11), and we are all good.

**Comment by daxian-dbw** [comment]
@mklement0 One more question regarding `Environment.CommandLine`.

When using the utility compiled from [this answer](https://stackoverflow.com/a/69832150/45375), the `Environment.CommandLine` shows `raw: ["E:\yard\tmp\echoArgsPause.exe" -v MDF_FILEPATH="C:\Databases\junk.mdf"]`

![image](https://user-images.githubusercontent.com/127450/202319053-9bee85ef-c97d-4773-b765-b8cd68dae377.png)

However, when using the `testexe.exe -echoargs` after updating it to write out `CommandLine`, it shows **different** value: `raw: [testexe.dll -echoargs -v MDF_FILEPATH=C:\Databases\junk.mdf]`

![image](https://user-images.githubusercontent.com/127450/202319584-2dc4102e-808d-4158-a0d6-3f1414fef9f9.png)

Both were on PS 7.2.7.
Do you know why there is such a difference between `echoArgsPause.exe` (built in PowerShell.exe, so targeting .NET Framework) and `testexe.exe -echoargs` (built targeting .NET 7)? Does `Environment.CommandLine` not reflect the _RAW_ process argument anymore?

**Comment by mklement0** [comment]
Indeed, a .NET (Core) application (as opposed to a .NET Framework application)  does _not_ report the true raw command line: see https://github.com/dotnet/runtime/issues/11305#issuecomment-674554010

**Comment by rmegal** [comment]
@daxian-dbw and @mklement0 This was an eye opening conversation. Thanks a ton for weighing in.

**Comment by jborean93** [comment]
@daxian-dbw if it helps this is what I use to test out argv stuff on Windows

```powershell
Add-Type -OutputType ConsoleApplication -OutputAssembly print_argv.exe -TypeDefinition @'
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace PrintArgv
{
    class Program
    {
        [DllImport("Kernel32.dll")]
        public static extern IntPtr GetCommandLineW();

        static void Main(string[] args)
        {
            IntPtr cmdLinePtr = GetCommandLineW();
            string cmdLine = Marshal.PtrToStringUni(cmdLinePtr);

            Console.WriteLine(cmdLine);
            for (int i = 0; i < args.Length; i++)
            {
                Console.WriteLine("[{0}] {1}", i, args[i]);
            }
        }
    }
}
'@
```

This unfortunately needs to run in WinPS but it can be run anywhere. It will output the raw command line value as well as the arguments as parsed by dotnet

![image](https://user-images.githubusercontent.com/8462645/202325179-3f2531b1-659f-4ff2-9d13-c2698ebf934a.png)

_Note I haven't updated to 7.3.0 yet_

For Linux I've also used the following before

```c
#include<stdio.h>

int main(int argc, char *argv[])
{
    int i;
    for(i = 1;i < argc;i++)
    {
        printf("[%d] %s\n", i, argv[i]);
    }
    return 0;
}
```

You can compile it with `gcc print_argv.c -o print_argv`

![image](https://user-images.githubusercontent.com/8462645/202325394-e528fc64-5d83-40ad-9261-2ed0e74adfa8.png)

It is a bit more confusing there because Linux doesn't have a command line string but uses `char *argv[]`.

**Comment by daxian-dbw** [comment]
@jborean93 Thank you for sharing the code!
I submitted https://github.com/PowerShell/PowerShell/pull/18591 to update `testext` with a `-echoraw` switch, to show the raw command line and the individual args.
I think the existing `testexe -echoraw` is sufficient on Unix platforms, but let me know if that's not the case.

**Comment by jborean93** [comment]
Looks good, I have no idea what dotnet does for `Environment.CommandLine` outside of Windows, I'm not as familiar to process args there.

**Comment by mklement0** [comment]
> I think the existing `testexe -echoraw` is sufficient on Unix platforms, but let me know if that's not the case.

I assume you meant `testexe -echoargs` and, yes, that would be sufficient on Unix, given that there is no such thing as a _raw command line_  there (only an _array_ of _verbatim_ arguments passed via the relevant system functions).

However, is there really a need for a new, separate option? 

Can't  the existing `-echoargs` option:

* either: just show the _raw_ command line _on Windows only_?

* or - with an appropriate hint  - on Unix show a _hypothetical_ command line that would work _from a POSIX-compatible shell_?
  * However, note that `[Environment]::CommandLine` does _not_  (robustly) provide such a hypothetical command line, because it doesn't `\`-escape `$`-prefixed tokens, neither in unquoted arguments nor in arguments with spaces, which it invariably encloses in `"..."`, which are _interpolating_ strings in POSIX-compatible shells.
  * For instance, a `test.ps1` file that contains `[Environment]::CommandLine` invoked from Bash with
  `pwsh -file test.ps1 'There is no place like $HOME'` (note that `$HOME` is _not_ expanded, due to use of `'...'`) is echoed as follows, which does _not_ roundtrip properly, because the hypothetical reconstruction results in an _interpolating_ POSIX-shell string (that the `pwsh` executable is reported as a `.dll` is a separate problem - see https://github.com/dotnet/runtime/issues/11305):
    * `/usr/bin/pwsh.dll -nop -file pg.ps1 "There is no place like $HOME"`

**Comment by mklement0** [comment]
@daxian-dbw 

> This makes perfect sense to me now, thank you!

Glad to hear it.

> So, it makes sense to have sqlcmd in the [legacy command list](https://github.com/PowerShell/PowerShell/blob/4ce439ebb7d988101e46eee9c6067b31edac60e1/src/System.Management.Automation/engine/NativeCommandProcessor.cs#LL246-L253C11), and we are all good.

I know I'm repeating myself, but I feel it bears repeating: such a legacy command list [is a terrible idea](https://github.com/PowerShell/PowerShell/issues/15143#issuecomment-833568832); while it may _selectively, obscurely_ help backward compatibility, it guarantees everlasting confusion going forward.

**Comment by daxian-dbw** [comment]
@mklement0 `testexe -echoargs` is used in tests, and the tests only expect the individual arguments, not extra texts for the raw command line. The `-echoraw` flag is only for interactive use in cases like this one.

**Comment by mklement0** [comment]
Thanks for clarifying, @daxian-dbw. 
On second thought re `-echoraw`, showing a hypothetical command line on Unix is probably _not_ called for in a _diagnostic_ utility, given that it would basically arbitrarily have to _pick_ a shell whose syntax to conform to (even though there are only two logical candidates, POSIX-compatible shells and PowerShell) when reverse-engineering a command line that the program itself never saw.

**Comment by Scordo** [comment]
Hi,

we are facing the same problem with msbuild and property values containing a collon or comma.
We have to support powershell 5.1 up to pwsh 7.3 and are using escaped quotes which are breaking in pwsh 7.3.

We dont want to set $PSNativeCommandArgumentPassing script-wide because it may cause incompatibilities when including 3rd party modules/scripts which dont expect this.

So we decided to go with local changes in scripts with the help of the following function:

```powershell
function Use-LegacyNativeCommandArgumentPassing {
  [CmdletBinding()]
  param (
      [Parameter(Mandatory=$true)]
      [scriptblock]
      $Script
  )

  $oldPSNativeCommandArgumentPassing = $PSNativeCommandArgumentPassing

  try {
      $PSNativeCommandArgumentPassing = 'Legacy'
      & $Script
  }
  finally {
      $PSNativeCommandArgumentPassing = $oldPSNativeCommandArgumentPassing
  }
}
```

Which we are using this way:

```powershell
Use-LegacyNativeCommandArgumentPassing {
  & 'msbuild.exe' @('test.target', "/p:Category=`"CI,Nightly`"")
}

```

Hope this helps someone else.
