### ISSUE TITLE
Output of `ls` or ` Get-ChildItem` has unexpected bg color for directories names

### ISSUE THREAD

**Issue by ExtremeGTX** [PowerShell/PowerShell#18550]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hello pwsh team,

Please check the screenshot below:
![image](https://user-images.githubusercontent.com/6371120/201548410-e6ee4be6-3869-43a9-858f-22b793ef8e96.png)

I have empty profile file under `Documents\PowerShell\Microsoft.PowerShell_profile.ps1` also no modules under `Documents\PowerShell\Modules\` .
Could you please tell me where else should i check for such configuration?

Thanks

### Expected behavior

```console
Directories names has a transparent background color
```

### Actual behavior

```console
Directories names has a blue background color
```

### Environment data

```powershell
PS C:\Program Files> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/6371120/201548410-e6ee4be6-3869-43a9-858f-22b793ef8e96.png)

**Comment by 237dmitry** [comment]
Configure `$PSStyle`

**Comment by jhoneill** [comment]
You will discover some other colouring applied to items in directory output - which you probably not either 
```
if ($pstyle) {
  $psstyle.FileInfo.Directory = $psstyle.FileInfo.Executable = $psstyle.FileInfo.SymbolicLink  = "" 
  $PSStyle.FileInfo.Extension.Clear()
  $PSStyle.Formatting.TableHeader       = ""
  $PsStyle.Formatting.FormatAccent      = ""
}
```
Is a useful add on to many profiles.   The powers that be believe _most_ people want their directories to be blue because bash makes them blue, but it blue on black  breaks the accessibility requirements for contrast so they have selected white on blue. A search should find the discussion on this.  The important thing is you can set things exactly how you want them to be.

**Comment by Liturgist** [comment]
If there is a desire to "do it like bash does it," then how about putting a `[System.IO.Path]::DirectorySeparatorChar` at the end of directory names?

**Comment by ThomasNieto** [comment]
> If there is a desire to "do it like bash does it," then how about putting a `[System.IO.Path]::DirectorySeparatorChar` at the end of directory names?

Feel free to open a new issue/discussion on that however, the name of the property for `System.IO.DirectoryInfo` is `Name` which does not contain a `/`. You can however create a new formatter that adds the slash if you so desire.

**Comment by ExtremeGTX** [comment]
Thanks Guys.
so, this blue color is the default of Powershell 7? if not, how can I track down where is the source of this modification?

**Comment by jhoneill** [comment]
> Thanks Guys. so, this blue color is the default of Powershell 7? if not, how can I track down where is the source of this modification?

It's the default in 7.3 yes. Not in 7.2 and earlier (it was an experimental feature in 7.2). See my post above for how to control it.




> > If there is a desire to "do it like bash does it," then how about putting a `[System.IO.Path]::DirectorySeparatorChar` at the end of directory names?
> 
> Feel free to open a new issue/discussion on that however, the name of the property for `System.IO.DirectoryInfo` is `Name` which does not contain a `/`. You can however create a new formatter that adds the slash if you so desire.

It would be pretty easy to add `/` or `\` along with the ansi escapes. But if someone assumes directory names contain a trailing `/` or `\` then they will complain that what is displayed doesn't match the property.

**Comment by ExtremeGTX** [comment]
That's answers my question, Thanks @jhoneill

**Comment by garretwilson** [comment]
I've read this thread but I'm still not clear on the simple answer: how do I _disable_ this feature? Rather than hard-coding the setting to a new color, I want to simply use the _default_ color.

In other words, rather that saying, "here is a new color I like better", how can I say "please don't change the color to begin with, and just use the same color for directories that you are using for all the other object listings"?

It seems so difficult in PowerShell to undo things that PowerShell in its greater wisdom decided was good for me. Rather than simply disabling the feature, PowerShell always seems to make me do some grand workaround that "does something else do undo the thing PowerShell did". #18180 is a prime example.

How can I tell PowerShell, "please don't add a special color to directories to begin with"?

**Comment by ThomasNieto** [comment]
@garretwilson There was no color, the color was determined by your console/terminal text color setting.

**Comment by garretwilson** [comment]
Thanks, @ThomasNieto . So how do I tell PowerShell to go back to using the "no specific color". I don't want to set a new color. I want to tell PowerShell to go back to not having a special color for directories.

**Comment by ThomasNieto** [comment]
@garretwilson look at @jhoneill comment. His code snippet does that.

**Comment by garretwilson** [comment]
Well it's mixed in with several things. Not that it's not helpful. But to clarify, are you saying that it's this part? (I like to separate out and understand what I'm doing.)

```powershell
$PSStyle.FileInfo.Directory = "" 
```

**Comment by jhoneill** [comment]
@garretwilson the to turn all the colours off you can set 
$PSStyle.OutputRendering = "PlainText"

Otherwise the noticeable update in 7.3 is that 
`$psstyle.FileInfo.Directory`, `$psstyle.FileInfo.Executable` and `$psstyle.FileInfo.SymbolicLink` now contain escape sequences for Directories links and executables. You can choose your own if you don't like the PowerShell team's choice, I find _none at all_ is best. 

For other items   `$PSStyle.FileInfo.Extension` holds the file extension and the escape sequence. `Clear()` removes them all.  `$PSStyle.FileInfo.Extension.Add(".JPG","$($PSStyle.Foreground.BrightCyan)")` adds one. Again I find clear() gives the optimal combinations. 

If you don't like column headings and list labels in green then `$PSStyle.Formatting.TableHeader`  and `$PsStyle.Formatting.FormatAccent` contain the ansi sequence for those and I find that no-sequence is better for me 

As with so much, it's very  customizable if (like me) you don't like the defaults.

**Comment by jpomfret** [comment]
This did not work well for me - apparently missed this change and just thought it was broken.

![image](https://user-images.githubusercontent.com/981370/205078647-11fed5b1-6f75-47b5-8dba-bad1fb88fdbc.png)

Unclear why this is closed? Is it being fixed in new version?

**Comment by laporeon** [comment]
> Configure `$PSStyle` For example white directory color:
> 
> ```
> $PSStyle.FileInfo.Directory = "`e[38;2;255;255;255m"
> ```

This worked for me like a charm! 
Thank you so much. This was bothering me for too long.

**Comment by JumBe08** [comment]
Rephrasing out what was said above, for someone who is being bothered by this and is landing here out of the blue, and doesn't quite grasp what is happening, hoping that it is a bit more clear.

- Yes, since 7.3 the PowerShell started to add that background to directories
- If you type in your PShell "$PSStyle", you'll get a list of some variables that you can customize, and the possible color codes
- The variable that you are looking for, in the case of folders, is "FileInfo.Directory"
- If you type what @237dmitry suggested directly in the Powershell, it will clear the background highlighting, while that shell session is active
- To do it permanently, you can add it to your [PowerShell profile](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.3), so that it is loaded every time

**Comment by jhoneill** [comment]
> I found it a bit perplexing that a change like this was added, as the default behavior. Maybe there was a lot of people asking for it. 

I have a problem reading things when there is movement, unexpected colours and a few other things on the screen, and find unix/linux seemingly random use of colours makes it much more difficult to read. There is a demand form people coming from other shells to be able to get the same colours, in particular "blue" for directory. However blue text on black fails accessibility tests for people with more common eyesight problems - who need more contrast, hence this compromise. A decision was "what seemed like a good idea to a dev at the time" colours to be opt out rather than opt in, so that people would know colour was available. I still contend that finding the opt out leaves a few people who want it off frothing-at-the-mouth angry, where an opt in would have left those who missed their linux colours feeling mild disappointment... however that argument was lost long ago.  I turn it off in my profile, and if I need to test with `-noprofile` I work with slight nausea and the reading speed of a small child :-(
