### ISSUE TITLE
Forwarding empty ValueFromRemainingArguments argument using splatting regressed in 7.3.0 to be unintuitive

### ISSUE THREAD

**Issue by scramsby** [PowerShell/PowerShell#18586]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

If you have a function argument that gathers values from remaining arguments, but none are provided by the caller. The behavior is very unintuitive and restoring intuitive behavior requires the developer to provide an explicit default empty array parameter value.

```
function Invoke-Secondary {
    Param(
        [Parameter(ValueFromRemainingArguments = $true)]
        [String[]]
        $Args
    )

	Write-Host $Args.Length
	Write-Host "<$($Args -join ";")>"
}

function Invoke-Primary {
    Param(
        [Parameter(Mandatory = $true)]
        [String]
        $Required,

        [Parameter(ValueFromRemainingArguments = $true)]
        [String[]]
        $Args
    )

	Write-Host $Required
	Invoke-Secondary @Args
}

Invoke-Primary required
```

### Expected behavior

```console
required
0
<>
```

### Actual behavior

```console
required
1
<>
```

### Error details

What appears to be happening here is that if you don't specify a default value for the argument that inherits additional arguments and the caller doesn't include any, it will inherit an implicit default value of $null. When a function then tries to forward this argument list via splatting, this $null is implicitly coerced into a single-item argument list which has a single $null value, rather than being interpreted as an empty collection.

This can be fixed by adjusting the forwarding function to specify a default value for the `ValueFromRemainingArguments` argument that is an explicit empty array, i.e. `@()`. This is quite unintuitive and makes argument forwarding more error prone.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by scramsby** [comment]
Note: It appears that this behavior regressed in 7.3.0. In prior releases forwarding worked as expected.

**Comment by mklement0** [comment]
From what I can tell it has always worked this way.

The root cause is that splatting a variable that contains `$null` _passes a `$null`_.

This, combined with the fact that the variable for a parameter typed as a .NET _reference type_ (such as `[string[]]` in your case) is `$null` if the parameter wasn't bound on invocation, explains your symptom.

A simple repro:

```powershell
$v=$null; & { $args.Count } @v  # -> !! 1, because `$null` was actually passed.
```

I can't speak to the design intent, but I agree that it is unfortunate that a splatting variable containing `$null` causes an actual `$null` to be passed.

**Comment by Scordo** [comment]
I think this is because you've used the automatic variable $args:
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-7.3#args

I would never name a parameter $args because of this.
After renaming the parameter to 'arguments' or something else, the result is as expected.

**Comment by mklement0** [comment]
@Scordo: While it's a good point that  using`$args` for custom purposes should be avoided, the problem at hand is unrelated to that; the root cause is what I've shown in my previous comment (you can also verify it by changing the parameter variable name in the code in the initial post).

**Comment by Scordo** [comment]
> @Scordo: While it's a good point that using`$args` for custom purposes should be avoided, the problem at hand is unrelated to that; the root cause is what I've shown in my previous comment (you can also verify it by changing the parameter variable name in the code in the initial post).

@mklement0 maybe I'm missing something, but I said that changing the parameter args to arguments in the original post produces the expected/correct result. Just test it.

**Comment by mklement0** [comment]
It is what I said _doesn't_ make a difference; try it:

```powershell
function Invoke-Secondary {
  Param(
    [Parameter(ValueFromRemainingArguments = $true)]
    [String[]]
    $MyArgs
  )

  Write-Host $MyArgs.Length
  Write-Host "<$($MyArgs -join ";")>"
}

function Invoke-Primary {
  Param(
    [Parameter(Mandatory = $true)]
    [String]
    $Required,

    [Parameter(ValueFromRemainingArguments = $true)]
    [String[]]
    $MyArgs
  )

  Write-Host $Required
  Invoke-Secondary @MyArgs
}

Invoke-Primary required
```

Do you not get the following?

```none
required
1
<>
```

Again, `$v=$null; & { $args.Count } @v` succinctly demonstrates the root cause; the involvement of `[Parameter(ValueFromRemainingArguments)]` is incidental; `$v=$null; & { param([Parameter(ValueFromRemainingArguments)] $MyArgs) $MyArgs.Count } @v` yields the same result.

**Comment by Scordo** [comment]
Sorry my fault :-(
![image](https://user-images.githubusercontent.com/2535846/203842584-49a1ee85-1dc6-4bd4-a03b-1f91e2f48a29.png)

**Comment by DaDummy** [comment]
Do I understand it correctly, that this issue has been closed without resolution and the best solution is working around the issue?
