### ISSUE TITLE
Update Measure-Object to operate on any type that has the addition operator

### ISSUE THREAD

**Issue by WillPittenger** [PowerShell/PowerShell#18611]
### Summary of the new feature / enhancement

It'd help if `Measure-Object` could handle types like `System.TimeSpan`.  As is, it seems to only handle numbers.  Never mind that a timespan is a number.  Now with some types that don't have multiplication and division operators, Average might not be available.

### Proposed technical implementation details (optional)

Presumably, if some items are timespans, all the objects must be timespans.  That could make things more complicated.

**Comment by jhoneill** [comment]
Strictly - and I think the reason timespans don't convert to numbers - is they are not numbers a number of ticks will convert to a timespan but a time span does not convert back to a number of ticks, we need to ask for the ticks property, but we could just as easily ask for total seconds. Is a timespan a floating point number of seconds (or days) or a longint of ticks ?  

It would certainly be useful to get the sum or average of timespans (and the min / max) , but that produces a timespan object, when Measure-Object returns the measureInfo the values need to be doubles and timespans don't convert to double. 
So the method of using a  property and converting the doubles returned back to timespans if necessary seems to there for good. 

Which is not to say a set of functions which took any object with an ADD method and produced the sum , any object with compare method and produced min / max and any object with ADD and DIVIDE and produced average and standard deviation would not be useful . 

But I can see the cmdlets group reviewing this and saying that would be a great community addition (it may already be out there) rather than a change ideally mad to meaure-object.
