### ISSUE TITLE
`Copy-Item` add support "report progress"

### ISSUE THREAD

**Issue by John0King** [PowerShell/PowerShell#18637]
### Summary of the new feature / enhancement

when copy many files to remote computer ,  it's slow and nothing is report to user

### Proposed technical implementation details (optional)

```powershell
Copy-Item -Path ./* -Destination "D:/Dir" -ToSession $session -Recurse -Force -ReportProgess

Copy-Item -Path ./* -Destination "D:/Dir" -ToSession $session -Recurse -Force -ReportProgess  -ReportStyle "minimal |  filename | full"
```

-  `minimal`  (the default)  is only show a progress of total transfer
-  `filename`   will only show a progress of current processing file, 
-  `full`   will show a total progress bar and a mini progress bar for current file , and leave a log of filename to user when it's done

**Comment by jhoneill** [comment]
I use -verbose for copy progress - but that doesn't show progress copying a big file over a slow link. I'm not at all sure that the .NET copy operation reports progress, so that may not be possible.  And the flow of items piped in means copy may not know how many files or bytes there will be to copy.  
 It certainly _would_ be possible to have a progress indicator displayed after the first file with files & bytes processed. My guidelines are that nothing should go more than couple of seconds without telling the user something is happening. Bulk copies could benefit from adding that, but there may be other details to think about.

**Comment by SteveL-MSFT** [comment]
It would be possible to at least show the total files left to transfer, but as noted you couldn't smoothly report KBs transferred.  I don't think we'd need to support different report styles.

**Comment by John0King** [comment]
@SteveL-MSFT    
> but as noted you couldn't smoothly report KBs transferred

I'm wonder can we have  log style like `scp` command on SSH , it can report progress for each file ， and  plus a  progress bar of  "transfered files / total files "

> I don't think we'd need to support different report styles.  

agreed,  because Powershell have `-Verborse` or `-InformationAction Continue`  to show different level of log
