### ISSUE TITLE
Start a comment line with a double forward slash

### ISSUE THREAD

**Issue by dan-vasilov** [PowerShell/PowerShell#18658]
### Summary of the new feature / enhancement

Right now a single line comment can only start with a pound sign.
Also start a comment line with //

I am proposing this because I often have to work simultaneously with PowerShell scripts and C# code, and I often find myself commenting PowerShell code using // instead of #. 

### Proposed technical implementation details (optional)

# This is a comment line started with a pound sign
// This is a comment line started with //
Write-Host "I can execute, and the line above me was properly ignored"

**Comment by 237dmitry** [comment]
> // This is a comment line started with //

This is file path separator

![dir](https://user-images.githubusercontent.com/78153320/203732995-84885101-666c-4b58-8bcc-3c865a874e8f.png)

**Comment by jhoneill** [comment]
> > // This is a comment line started with //
> 
> This is file path separator
> 
Rarely used in the form you show but  dir //ServerName/shareName  for writing unc paths is out in the wild (although \\server\share is more common). 

If PowerShell had defined  // as comment from day 1 and required "//path"  to be quoted I don't think anyone would have complained, but the scope of the breakage is to great to change, annoying as it is for those with muscle memory of other languages. (The number of times I have slipped PowerShell syntax into SQL statements gives me some sympathy with the OP.)

**Comment by rhubarb-geek-nz** [comment]
I think it would add confusion rather than being a benefit especially if trying to maintain both cross platform PowerShell scripts and ones that will still run on the classic PowerShell.

Remember unlike C, C++, C#, Java etc, with PowerShell and other scripting languages you don't about a syntax error until you try and run the script.

**Comment by kilasuit** [comment]
1- this won't happen.
2 - You shouldn't be editing code in a plaintext like environment like notepad but instead use an editor that understands the languages that you are writing in and has keyboard shortcuts to easily add or remove comments. 

whilst @Northman-de states this
> If you are using Visual Studio and VSCode: both have the same shortcut for commenting the selection `CTRL+K, CTRL+C` and uncommenting `CTRL+K, CTRL+U`. Try to use these shortcuts :-)
> 
> BTW: in VSCode you can also use `CTRL+#`

I've found that isn't always true of `CTRL+#` if you have other software like 1Password installed. So I'd stick to recommending just whatever your editor of choice is and it's keyboard shortcuts

**Comment by jhoneill** [comment]
> You shouldn't be editing code in a plaintext like environment like notepad but instead use an editor that understands the languages that you are writing in....

I think we only need to look at the number of people who use an editor which others can't even exit from to realise that not everyone wants to use a helpful editor. Personally I don't think a language can compel people to use a "suitable" editor (although how any uses something with syntactically-significant-spaces without one is beyond me). 
I've used VS code as my main editor for 4 or 5 years now and I don't think I've ever used ctrl+k ctrl+c  :-)

**Comment by kilasuit** [comment]
> Personally I don't think a language can compel people to use a "suitable" editor 

We don't because technically we can't, we however do **strongly** recommend that for the **best editing experience** that people use a suitable editor with development enhancing functionality with the strong suggestion to look at `Visual Studio Code` or similar editors that have implemented the PowerShell Language server.

>I think we only need to look at the number of people who use an editor which others can't even exit from to realise that not everyone wants to use a helpful editor. 

True people wanna use what is quick for them in many instances, what we need to do to help them understand better that they either need to adapt their muscle memory or we need to make it easier via hardware/software offerings to give them as good an experience as possible, because we can't give everyone everything that they want.

>I've used VS code as my main editor for 4 or 5 years now and I don't think I've ever used ctrl+k ctrl+c :-)

Time to break some of that muscle memory and rebuild it for the better perhaps 😉 & perhaps it may be worth printing this [handy reference out](https://how.com.bd/wp-content/uploads/2020/08/vscode-keyborad-shortcut-reference-2048x1588.png) and pinning it on a wall or on your desk for easy viewing.

**Comment by kilasuit** [comment]
Whilst this is currently resolvable via external means I do think it's worth the language and engine working groups discussing if this ask **could** happen, even though I personally don't think it will
