### ISSUE TITLE
[PSRP over SSH] Invoke-Command -ScriptBlock { Get-ChildItem -Path /tmp } locks up session

### ISSUE THREAD

**Issue by bgelens** [PowerShell/PowerShell#1866]
## Steps to reproduce

Create PSSession over SSH to Linux. Doesn't matter if it's initiated from Linux or Windows.

``` powershell
#works fines
Invoke-Command -Session $session -ScriptBlock { ls /tmp }
#locks up session
Invoke-Command -Session $session -ScriptBlock { Get-ChildItem -Path /tmp }
```

![untitled](https://cloud.githubusercontent.com/assets/10071039/17772708/a505ad9c-654a-11e6-9617-ecfe2701de7f.png)
## Expected behavior

Should work.
## Actual behavior

Locks up.
## Environment data

Linux node is CentOS 72 1511
Windows node is Windows 10 AU 1607
![versiontable](https://cloud.githubusercontent.com/assets/10071039/17772774/ef4cd60a-654a-11e6-8d94-7e076b12e3ac.png)

**Comment by PaulHigin** [comment]
This is an interesting bug.  It is not an error in PowerShell remoting or the serialization layer, or even in PowerShell.  The bug looks to be in the CLR.  This hang only occurs on Linux when enumerating named pipe files (e.g., /tmp/clr-debug-pipe-12555-7925167-in).  

When enumerating files in a directory PowerShell returns System.IO.FileSystemInfo objects.  These objects include custom members, and one (VersionInfo) that returns a System.Diagnostics.FileVersionInfo object via a PowerShell script.

```powershell
[System.Diagnostics.FileVersionInfo]::GetVersionInfo('/tmp/clr-debug-pipe-12555-7925167-in')
```
This causes the process to hang and happens whenever the static method is called with a named pipe file path.  No exception is thrown, just the process/thread hangs.

The reason this hangs PowerShell remoting is that when the FileInfo object is serialized the VersionInfo custom property needs to be evaluated by running the above script.  The hang also occurs if you try to serialize a FileInfo object corresponding to a named pipe file.

```powershell
dir /tmp/clr-debug-pipe-12555-7925167-in | Export-CliXml -Path $home/FI.xml
````
One workaround is to return strings instead of de-serialized objects

```powershell
Invoke-Command -Session $s -Script { Get-ChildItem /tmp | Out-String }
```

Since this is a very specific case I feel it is not a beta-1 bug and am moving it to beta-2 time frame.

This will need to be investigated by the CLR team since it does not appear to be related to PowerShell.

**Comment by SteveL-MSFT** [comment]
@PaulHigin please open a bug for dotnet and link it here

**Comment by PaulHigin** [comment]
Ok, I have created an issue on DotNetCore
https://github.com/dotnet/corefx/issues/18409

**Comment by PaulHigin** [comment]
This has been fixed by the DotNetCore team.
