### ISSUE TITLE
«Invoke-WebRequest» is wrong decoding «text/html; charset=CP1251»

### ISSUE THREAD

**Issue by msps20221129** [PowerShell/PowerShell#18677]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

PowerShell correctly processing of russian pages («http://lib.ru/» with «charset=koi8-r» & «http://lib.ru/win/» with «charset=windows-1251») but wrong processing of ukrainian page («https://www.ukrlib.com.ua/» with «charset=CP1251») – cyrillic characters are not displayed correctly.
The browser «Google Chrome» is correctly processing all of this pages.

### Expected behavior

```console
PS> (Invoke-WebRequest "http://lib.ru/win/").Headers["Content-Type"]
text/html; charset=windows-1251

PS> (Invoke-WebRequest "http://lib.ru/win/").Content.Substring(0,999)
<html><head><title>Lib.Ru: Библиотека Максима Мошкова</title></head><body><pre>
<center><h1><small><a href=http://lib.ru/>Lib.Ru</a>:</small> Библиотека Максима Мошкова<br><font size=-2>При поддержке Федерального агентства по печати и массовым коммуникациям.</font></h1><font size=-1><form action=GrepSearch method=GET><b>Поиск</b>:<INPUT TYPE=text NAME=Search size=9><input type=submit value=search></font> <b><a href=/PROZA/>Проза</a> <a href=/INPROZ/>Переводы</a> <a href=/POEZIQ/>Поэзия</a> <a href=/RUFANT/>Фантастика</a> <a href=/RUSS_DETEKTIW/>Детективы</a> <a href=http://az.lib.ru/>Классика</a> <a href=/HISTORY/>История</a> &nbsp;<a href=/.dir_StripDir.html>И ДР.<small>>>></small></a></b></form></center><center>[<a href=What-s-new><b>НОВИНКИ</b></a>][<a href=/HITPARAD/><b>Хитпарад</b></a>][<a href=http://samlib.ru/>Самиздат</a>][<a href=http://music.lib.ru/>Музыка</a>][<a href=http://www.artlib.ru/>Художники</a>][<a href=http://world.lib.ru>Заграница</a>][<a href=http://turizm.lib.r
```

### Actual behavior

```console
PS> (Invoke-WebRequest "https://www.ukrlib.com.ua/").Headers["Content-Type"]
text/html; charset=CP1251

PS> (Invoke-WebRequest "https://www.ukrlib.com.ua/").Content.Substring(0,999)
<!DOCTYPE HTML>
<html>
<head>
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
    <meta charset="windows-1251">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/favicon.ico">
    <title>��������� ��������� ��������� ���˳�</title>
    <meta name="description" content="�������� ������ �������� ��������� ���������, � ����� �������� ��������� ���������� �����. ��������� ������ ����� �� ��������� ����� ���������� �� ������� ����������� � ������ ���������� �����, �����������, ��������� �������� ��� �����, ��� �� ���.">    <META name="verify-v1" content="9+xsNP+pSW2VFD5RDZIB4/ZFGX1zlebA7uO0WitoNuc=" />
    <meta name='be71e549f9e9dc3567c4f8273a897284' content=''>
    <META NAME="webmoney.attestation.label" CONTENT="webmoney attestation label#1A7FF5E5-C262-41A8-88EC-85623F9C802D">
    <!--7CB8D969C0C63AB91AEF27B8F2210F84-->
    <meta name="spr-verification" content="d4adcc5c2ab59af" />
    <meta nam
```

### Environment data

```powershell
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
Couldn't reach it...
```powershell
PS > (Invoke-WebRequest "https://www.ukrlib.com.ua/").Content.Substring(0,999)
Invoke-WebRequest: No such host is known.
```
Try with different output encodings
```powershell
[Text.Encoding]::GetEncodings()    # list of encodings
[console]::OutputEncoding = [Text.Encoding]::GetEncoding(<code page>)
```

**Comment by msps20221129** [comment]
![2022-11-29_17-29-25](https://user-images.githubusercontent.com/119423257/204556430-2f118930-3b26-4e6d-bbe0-fc68e116fcf0.png)

What can I know the right code page for ANY site?  The browsers (for example, «Google Ghrome») not need PREVIOUSLY known code page.

**Comment by msps20221129** [comment]
1) Try Proxy or VPN.  IPv4=194.54.83.122.  This is current screenshot.
![2022-11-29_18-38-22](https://user-images.githubusercontent.com/119423257/204574627-79bc1e45-fdbe-4d3c-a5b0-aad2c5f9425c.png)

2) By what can I to know the right code page for ANY site?  The browsers (for example, «Google Ghrome») not need PREVIOUSLY known code page.

**Comment by mklement0** [comment]
It looks like the charset identifier `CP1251` is the problem, which isn't in the [list of official identifiers](https://www.iana.org/assignments/character-sets/character-sets.xhtml) - note how it differs from `Windows-1251`, which _does_ work.

Seemingly, because `Invoke-WebRequest`  doesn't recognize the charset, it falls back to UTF-8(?) causing the response to be misinterpreted. The fallback is _not_ Windows-1252, as one might expect, as evidenced by the fact that the mis-decoded response contains instances of the Unicode replacement character, `�` (REPLACEMENT CHARACTER, [`U+FFFD`](http://www.fileformat.info/info/unicode/char/fffd))

Browsers are seemingly more forgiving with respect to non-standard charset identifiers and/or they allow a `<meta charset="...">` element to _override_ the header information - for https://www.ukrlib.com.ua/ this element _is_ correct (`<meta charset="windows-1251">`)

I can't speak to  whether it is reasonable to expect `Invoke-WebRequest` to be similarly forgiving / exhibit the same overriding behavior.

---


@237dmitry, note that `[console]::OutputEncoding` is irrelevant in this context, because it only matters for receiving output from _external programs_.

**Comment by mklement0** [comment]
As an aside: Only in _Windows PowerShell_ is the fallback encoding Windows-1252, and _only there_ can you use the following _workaround_:

```powershell
# !! WinPS only
$response = Invoke-WebRequest "https://www.ukrlib.com.ua/"

$originalBytes = [Text.Encoding]::GetEncoding(1252).GetBytes($response.Content)
$correctedString = [Text.Encoding]::GetEncoding(1251).GetString($originalBytes)

$correctedString.Substring(0, 500)
```

In PowerShell _Core_, due to the apparent UTF-8 fallback, information has already been irretrievably lost in what `.Content` reflects, so the workaround isn't effective there.

**Comment by msps20221129** [comment]
Thank you.

**Comment by CarloToso** [comment]
Workaround for Powershell Core:

```ps1
$response = Invoke-WebRequest "https://www.ukrlib.com.ua/"
$correctedString = [Text.Encoding]::GetEncoding(1251).GetString($response.RawContentStream.ToArray())

$correctedString.Substring(0, 500)
```

**Comment by msps20221129** [comment]
Really works!  Thank you!

**Comment by mklement0** [comment]
Nice, @CarloToso - your workaround also works in Windows PowerShell, and is preferable to the one I suggested above.

Some additional info:

* The change in default / fallback encoding from ISO-8859-1 (loosely speaking, Windows-1252, though the latter is a superset of the former) to UTF-8 happed in v7.3.0:
  * See https://github.com/PowerShell/PowerShell/pull/18219 

* Relevant earlier discussion:

  * #11547

**Comment by CarloToso** [comment]
Another relevant issue:

-  #6110

**Comment by msps20221129** [comment]
Thank you. Very interesting.
I did not know how to perform the transcoding before. Now I know that. Thank you all.

**Comment by mklement0** [comment]
Based on @CarloToso superior workaround I've updated [this Stack Overflow answer](https://stackoverflow.com/a/47961370/45375), so that you could use the `ConvertTo-BodyWithEncoding` convenience function defined there as follows:

```powershell
Invoke-WebRequest https://www.ukrlib.com.ua/ | ConvertTo-BodyWithEncoding 1251
```

The function is also available as [an MIT-licensed Gist](https://gist.github.com/mklement0/209a9506b8ba32246f95d1cc238d564d).
Assuming you have looked at the linked code to ensure that it is safe (which I can personally assure you of, but you should always check), you can directly define it directly as follows (instructions for how to make the function available in future sessions or to convert it to a script will be displayed):

```powershell
irm https://gist.github.com/mklement0/209a9506b8ba32246f95d1cc238d564d/raw/ConvertTo-BodyWithEncoding.ps1 | iex
```

**Comment by msps20221129** [comment]
I will try to figure it out. Thank you.
