### ISSUE TITLE
New-Module inconsistent behavior if the module is then passed to Import-Module

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShell#18673]
## Use Case
As a PowerShell developer, I want to be able to instantiate temporary modules that only live in memory and that I can unload at the end of a script, such as in bootstrap scenarios.

### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`new-module test -ScriptBlock {function test {'ok'};export-modulemember 'test'}`

Module created by new-module not visible in get-module (expected per command help)
![{072A4D12-17EA-439C-ACD0-673748D26C57}](https://user-images.githubusercontent.com/15258962/204381974-872f573a-e8f4-43d3-b71d-b3ba50343dac.png)

Test function still present when module is "removed" (expected: function would go away)
```
new-module test -ScriptBlock {function test {'ok'};export-modulemember 'test'} | Remove-Module

command test

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        test                                               0.0        test
```
Removing export-modulemember makes no difference
![image](https://user-images.githubusercontent.com/15258962/204383917-4a186d0d-83c6-44da-a021-84d0338cc642.png)

## Workaround
If module is imported, then the function goes away as expected (covered in example 4, but why is this necessary? Why doesn't New-Module just place itself in the module registry anyways)
```
new-module test -ScriptBlock {function test {'ok'};export-modulemember 'test'} | Import-Module -PassThru | Remove-Module

command test

Get-Command: The term 'test' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Expected behavior

Per the help, New-Module creates a dynamic module that exports functions by default. It would expect that it would behave much like any other module, yet the help says it cannot be seen by Get-Module, yet I can use import-module to then have it be seen by Get-Module, so is it no longer a dynamic module in this case? Why is get-module not supported for new-module?

### Actual behavior

```console
Creates functions upon new-module invocation in module scope that cannot be removed with remove-module unless the module is first imported.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
It looks like this is a known issue in [the code](https://github.com/PowerShell/PowerShell/blob/8965af3d5201b103971b00f040c13e90ca7b6de6/src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs#L6959-L6963) and based on the comment, there may be unintended side effects by adding the dynamic module to the module table

**Comment by JustinGrote** [comment]
@SteveL-MSFT interesting, why does example #4 recommend using import module then? Maybe it does something special that New-Module does not?

**Comment by SteveL-MSFT** [comment]
`Import-Module` adds it to the module table.  It's possible that the comment is outdated and just works now by adding it to the moduletable.  Alternatively, maybe `New-Module` should just use `Import-Module` directly after creating the module rather than using its own code (although `New-Module` does handle the case of exporting all members if no members are exported explicitly)

**Comment by JustinGrote** [comment]
> `Import-Module` adds it to the module table. It's possible that the comment is outdated and just works now by adding it to the moduletable. Alternatively, maybe `New-Module` should just use `Import-Module` directly after creating the module rather than using its own code (although `New-Module` does handle the case of exporting all members if no members are exported explicitly)

I think you nailed it that the latter behavior is there as a convenience but is poorly implemented or ran into a snag. Piping it to import-module doesn't appear to have any side effects (so far) so that's gonna be my workaround for now, I'll leave this open unless it gets flagged as "wontfix" for breaking compatibility.

**Comment by bpayette** [comment]
Anonymous first-class modules (what New-Module creates) are like anonymous functions (scriptblocks) in that they don't have a name until they are bound into one of the name tables. For functions, this is done with
```function:myfunc = { "Hello" }```
For modules, this is done using 
```import-module $myModuleInfo```
The fact that module members are exported _without_ registration is (IMHO) a bug. The exports should have been done on registration not instantiation. We had a number of design discussions about this but PM felt that they should export on creation. Unfortunately it's too late to change that now.

Note that first-class modules do allow for a number of advanced scenarios such as creating closures or pseudo-objects with their own private storage. In fact, at one point, I prototyped "classes" in PowerShell just using modules. It required a surprisingly small number of changes and a day to implement. However modules are fairly heavy object so we ultimately didn't pursue that route, especially after the CLR team added support for garbage-collected types at which point we could use real classes instead of "faking" it.

For Justin's scenario, I'm _guessing_ that a useful change would be to add a name parameter to `New-Module` so you could do:
```
new-module MyModule {
   .... stuff...
}
```
in which case, everything should work as it does with `Import-Module`.  Justin - can you elabourate a bit more about your scenario? Thanks!

**Comment by bpayette** [comment]
Note: chapters 8 & 9 of the 3rd edition of my book cover the module architecture in considerable detail.

**Comment by kilasuit** [comment]
re this

>Module created by new-module not visible in get-module (expected per command help)

I think that's because the current sessions command cache (or more correct the global cache) hasn't yet been rebuilt which you can force by calling `Get-Module -All -Refresh -ListAvailable`
