### ISSUE TITLE
Add `-ProgressAction` as a common parameter

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#18737]
### Summary of the new feature / enhancement

The other Action preference variables are available on cmdlets, but Progress needs to be set as a variable.  Would be useful to choose when to selectively suppress progress rather than have it globally.

**Comment by MartinGC94** [comment]
Yes please. Also the discussion in this old PR is probably relevant: https://github.com/PowerShell/PowerShell/pull/10238

**Comment by iSazonov** [comment]
I'm guessing it wasn't implemented before for a reason. And the reason is that it is exclusively for interactive scenarios. Do you really believe that the user will type this variable in an interactive scenario?
In my opinion, this API needs to be rethought as a whole. In its present form it has many limitations (there is even a tracking issue) both functionally and in implementation.
https://github.com/PowerShell/PowerShell/pull/18728#issuecomment-1338856926

**Comment by kilasuit** [comment]
@iSazonov we already have global opt out in `$ProgressPreference` that can be set before and reset again after a cmdlet is called.
It was implemented this way to enable choice to the user/administrator in how they want things to run but should have IMO been implemented with additional control at the cmdlet level which this ask would give us
> Do you really believe that the user will type this variable in an interactive scenario?

yes we already do see this happening & that's just from my years of teaching PowerShell to people

**Comment by kilasuit** [comment]
I'd like this to also be aliased (if possible) to both `-quiet` & `-q` to fit in with other tooling expectations elsewhere in the wider tech world & if these change overall (which seems to be how devs would like it to be) we can always change how progress action output works in a later release with this added

**Comment by iSazonov** [comment]
> > Do you really believe that the user will type this variable in an interactive scenario?
> 
> yes we already do see this happening & that's just from my years of teaching PowerShell to people

Your experience as clearly says that you get redundant information when you don't need it and don't get useful information when you need it. This confirms that the current design/implementation is bad. But it in no way suggests that people want to type more characters. On the contrary, you yourself want a new alias - what for? - To type less characters! The conclusion in my opinion is obvious - we need a good design and not another improvement of something that cannot be fixed. Ask yourself whether you prefer that everything works automatically as you like or that you have to do a dance every time, again and again.

**Comment by kilasuit** [comment]
@iSazonov please stop being so absolutist in your comments to me. I see things on balance from all POV's based on my experience so can do so much more fairly than most (thou I can at times fail on that too)

You can say this is a bad design, however I would say that's your opinion and one that I do respect, so please also respect mine here too, in that we should **not** enforce things one way or another on others when there is no need to. We should always find acceptable middle ground and work together, so that we can both have our cakes and eat it, you want total absolute speed, whilst I want to be able to optimise as I see fit, which by having options, gives me choice in how I or others that want a similar experience go about this, because I think whilst the current design isn't perfect it is already great & can be fixed with enough input from the likes of many of us, including yourself and myself.

What you find redundant is not what others, myself included, find redundant, so please try to consider this going forward.

> Ask yourself whether you prefer that everything works automatically as you like or that you have to do a dance every time, again and again.

No I want flexibility and the option to have my cake and eat it if I feel I have enough room for it & deserve it, which most of the time I think I do, don't you too? Plus I dunno about you but I love having a good dance, especially to some of my most favourite music as it helps me relax and releases so much tension in my body.
Also I'll give you huge credit in your ability to type English so well & I so wish I had been given chance in school to learn your native language or other languages of choice so that we could speak better between us using what ever language we so chose to use rather than being reliant on mine or a version of mine that's well used all around the world, if we so desired. 

I have so so much respect for all you do Ilya for the betterment of the PowerShell community at large & whilst we may not always see eye to eye, I love seeing your comments on this repo, even if I don't always agree with them as it lets me understand your POV which is much needed.
I'd love to play some more relaxing games with you in future like chess or snooker if we ever got the chance to do so, but always look forward to seeing the next comment from you.

**Comment by iSazonov** [comment]
@kilasuit Please do not take my words as an attack or imposition of an opinion. I am trying to avoid that. English is not my first language and I cannot properly follow the nuances of the language. I use a translator for complex sentences, but this does not save me from misunderstandings.

**Comment by vexx32** [comment]
This old issue of mine seems pretty relevant here as well: https://github.com/PowerShell/PowerShell/issues/7983

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agreed in the utility of exposing ability to control progress per cmdlet and following the current design of -ErrorAction, -WarningAction, -InformationAction and expose a -ProgressAction parameter accepting any valid ActionPreference value.  We believe this is a bucket 3 breaking change where we found 1 user on GitHub that already has such a parameter defined for this purpose https://github.com/Drjudd1989/Portfolio/blob/9ff6d938b0354c011e1841b00d1347e4b61f1c1d/Scripts/AD/Get-ADHealth.ps1.
