### ISSUE TITLE
Write-Progress drops updates if the calls happen too quickly in succession

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#18848]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note: This is a regression from Windows PowerShell and affects both the `Minimal` and `Classic` views (selectable via `$PSStyle.Progress.View`)

```powershell
$arr = 1..10
$arr | 
  ForEach-Object { 
    [int] $percentComplete = ($_ / $arr.Count) * 100
    Write-Progress -Activity Test -Status "$percentComplete% complete" -PercentComplete $percentComplete
    # !! Without sleeping for a while, the progress display stops updating after the FIRST call.
    # Start-Sleep -Milliseconds 200
  }
Start-Sleep 5 # Ensure that the progress bar stays visible for a while.
```

### Expected behavior

The progress bar should show 100% and stay visible for 5 seconds.

### Actual behavior

The progress bar shows 10% - that is, only the *first* call took effect.

### Environment data

```powershell
PowerShell Core 7.3.1
```

**Comment by SteveL-MSFT** [comment]
I think you're referring to this change https://github.com/PowerShell/PowerShell/pull/2822 which was taken awhile back.  Basically progress isn't updated except once every 200ms.  WinPS had the problem that it would update progress EVERY time an update was available.  The time rendering to the console impacted performance (classic examples is `invoke-webrequest` to download a file took much longer).  So I think this is considered by-design,.

**Comment by mklement0** [comment]
@SteveL-MSFT:

* It's understandable to want to _throttle_ progress updates so as not to unduly impact overall performance.

* However, I don't think it is acceptable  to _ignore_ subsequent updates.

   * Whatever the _last_ update was in the 200-msec. time window should render.

Consider a long-running task with progress reports whose timing is highly variable / unpredictable, especially during _parallel_ processing (`ForEach-Object -Parallel`):

* Say there are _bursts_ of updates followed by long periods of non-updates.
* If the bursts significantly meant to advance the progress display (in small increments), the long period of non-updates will present a distorted view.

**Comment by iSazonov** [comment]
This API is flexible enough to avoid such effects. The script developer just needs to use this API correctly. There are three phases - initialization, loop update and finalization. In this example, you need to execute "Complete" after the loop to display the correct state.
We could make PowerShell smarter, but I don't see the point. I consider this API obsolete to invest in it. It would make sense to create something more modern, productive and convenient. All we need is desire and approval :-)

**Comment by mklement0** [comment]
@iSazonov, the example scenario in my previous comment illustrates that the API is _not_ flexible enough - calling "Complete" in the middle of a long-running operation is obviously both unexpected and inappropriate.

**Comment by mklement0** [comment]
Optimizing is a laudable goal, as long as it doesn't get in the way of the user's intent.
Here, it clearly does.
I haven't looked into the technical challenges, but to me the current behavior is unacceptable.
If a modern API can remedy this, all the better - assuming it every sees the light of day.

**Comment by mklement0** [comment]
And come to think of it: using `-Completed` doesn't display the correct state, it _hides_ the - potentially outdated - progress bar.

**Comment by iSazonov** [comment]
I was talking about a common script that works correctly - init-update-in-loop-fin.
If we're talking about the body of the loop, as indicated, it makes no sense to update the output on the screen every "microsecond". This not only creates a performance problem but also violates the very concept of "Progress Bar".

**Comment by SteveL-MSFT** [comment]
I've noticed that many native tools don't actually clear out progress info once complete (and we'd have to change the code to show the last progress update).  So that could help with this, but would have its own dissenters.

**Comment by iSazonov** [comment]
> I've noticed that many native tools don't actually clear out progress info once complete (and we'd have to change the code to show the last progress update). So that could help with this, but would have its own dissenters.

What kind of script example are you referring to?

**Comment by SteveL-MSFT** [comment]
> > I've noticed that many native tools don't actually clear out progress info once complete (and we'd have to change the code to show the last progress update). So that could help with this, but would have its own dissenters.
> 
> What kind of script example are you referring to?

Not any script example, I'm referring to native commands that emit their own custom progress.  They tend to keep the last progress on the screen rather than clearing it.

**Comment by iSazonov** [comment]
Do you mean PowerShell SDK hosting scenario?

**Comment by SeeminglyScience** [comment]
> Do you mean PowerShell SDK hosting scenario?

`ConsoleHost` clears any remaining progress but *only* between REPL loops. Currently if you want to actually remove progress mid-script, you need a `Completed` record. I believe Steve is saying (and I'd agree with) that not a lot of built-in commands properly emit this record and are not cleared until the next REPL loop.

**Comment by iSazonov** [comment]
I don't know what you're talking about. What are "native commands" and "built-in commands"? Is it ping.exe or cmdlets?
If you say about exe-s they don't create progress bars. I guess you say about broken cmdlets. But this suggests that these are bugs and they need to be fixed.
But the main thing is that this API provokes such bugs. And I've been saying that for years. There's even my tracking issue about Progress API problems. It's been tacitly ignored for years with occasional outbursts like this. This just clearly shows that these problems are considered negligible. And since that's the case, it's not worth wasting time here either. If it is a significant problem, then it should be addressed as a whole, not a private plug. In other words, first we need to create a specification, a design. I have already tried to do this, but is it worth the time?

**Comment by SteveL-MSFT** [comment]
@iSazonov I agree that many scripts/cmdlets don't properly complete progress and relies on PowerShell to do the final cleanup (I still see this in some of our tests when run locally).  I also agree that it's probably not worth the cost/benefit to fix them as the underlying problem is that community scripts/cmdlets probably also have the wrong behavior.  At this time, let's leave it to the WG to discuss.

Regarding native commands, I'm referring to non-cmdlets like `winget` and `brew` which emit their own progress.  `winget` in this case does clear that last progress, but `brew` leaves the last progress update (100% complete, for example) on the screen.

**Comment by mklement0** [comment]
I can't speak to previous design discussions, neither with respect to what prompted https://github.com/PowerShell/PowerShell/pull/2822 nor with respect to a superior successor API.

Note that even leaving the progress bar up after completion and requiring a `-Completed` call (at which point updating could be forced) will _not_ solve the problem described in the initial post, as the following example demonstrates:

```powershell
$arr = 1..3; $sleepIntervals = 50, 50, 30000
$arr | 
  ForEach-Object { 
    [int] $percentComplete = ($_ / $arr.Count) * 100
    Write-Verbose -Verbose "Percent complete: $percentComplete"
    Write-Progress -Activity Test -Status "$percentComplete% complete" -PercentComplete $percentComplete
    
    Start-Sleep -Milliseconds ($sleepIntervals[$_ - 1])

  }
Write-Progress -Activity Test -Completed
```

Output:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/588825/210155643-40dfa961-223e-4d0e-aba4-ef5569e16d6a.png">

Again, with _parallel_ execution this strikes me as a scenario that users may hit in real life.

---

I can't speak to implementation challenges, but to me the current optimization attempt only makes sense if the logic is changed

* from: rendering only the _first_ update in a given 200-msec. window.

* to: renderiong only the _last_ update (which invariably means a 200-msec. _rendering delay_, but I don't think that would be a problem for the human observer).

**Comment by iSazonov** [comment]
@mklement0 The fix you are talking about does not make sense for one simple reason - the problem remains in general, and this is a fundamental property of the progress bar - if there is a delay in the execution of the script/command, the progress bar is not updated, regardless of the presence or absence of optimizations in any way.

@SteveL-MSFT The behavior of native utilities can be determined by the niche for which they are created. For that niche, this behavior may look very acceptable. But most likely it is just a misunderstanding of the concept (as I formulated it below) and substitution of essential messages with informational ones (which is in the progress bar) or mixing them up. As I pointed out this may seem convenient in some niche, but outside of it this immediately becomes a problem or at least perplexes users.
This is especially noticeable in PowerShell where the progress bar stream is separate.
This special status of the progress bar in PowerShell imposes on users the need to follow this concept, and PowerShell itself requires them to be quite smart. If the former and/or the latter are violated, problems begin. If PowerShell was built on a few basic concepts, it should have followed them, implemented them fully, and improved the implementation.
This is closely related to other features we discuss in other issues that we would like to see in a modern console host.
If we moved away from Windows 7 support, we could move entirely to VTY and a unified API (now a port from the old Windows with Unix support split).
This direction could dramatically simplify the host code (and any SDK hosting scenarios) if we implemented a dedicated UI thread (now there is a runspace sitting in the main thread) and used modern C# features. I hope WG has enough time to evaluate all this :-)

---
>>>> **The only purpose of the progress bar, as the name says, is to inform the interactive user that the long process is ongoing.**

This definition is precise enough to formulate a reasonable consequence:
1. Any information displayed in the progress bar is irrelevant by definition, because it will be deleted, and in essence because the user will not use it except for:
2. The user only benefits from the progress bar (1) that the process continues, (2) that it is possible to roughly estimate its duration/time of completion.
3. It makes no sense to output the progress bar if the process is not long for an interactive scenario, i.e. if it is shorter than 5-15 seconds.
4. The progress bar only makes sense for an interactive scenario. For other scenarios, it should have no effect, especially slowing down the script's execution.
5. For the progress bar to honestly show the progress we need to split the process into parts that are known to run for less than 5-15 seconds.
6. Otherwise, if there is an indivisible atomic operation there, the only honest thing we can do is to write a message to the user "The operation will take a long time..."
7. ... We can go on and on to draw conclusions

**Comment by iSazonov** [comment]
> Note: I'm just talking conceptually here;

@mklement0 If you're conceptualizing optimization in this particular scenario, it's a dead end - I doubt that the current implementation will allow us to address even this particular case.
You seem to have missed the history. Compare Windows PowerShell and pwsh loading (large) files with and without the progress bar (you'd be surprised how bad it was) - that's exactly what we were fixing with this optimization. There was quite a long search for a compromise (it was obvious that there would be side effects we considered them). So I doubt that we can change anything there without significant cost, which is what we should be reducing.

If one discusses conceptually, one should discuss the concept as a whole. 
Not only this discussion, but others have convinced me that there are common misconceptions about the progress bar as to its purpose as well as its implementation.
We have to give credit to PowerShell, although it may seem unbelievable in the background of this discussion, _it got the concept right from the start_!
You are an excellent analyst and if you start with the fundamental concept of the progress bar, you will get interesting and useful results.
Good start is [PowerShell stream fundamentals](https://devblogs.microsoft.com/scripting/understanding-streams-redirection-and-write-host-in-powershell/). (Do you see a progress bar stream there? Why? :-) Then, notice, nevertheless it exists in remoting! Why?)

----

> > For the progress bar to honestly show the progress we need to split the process into parts
> 
> Are you saying the progress-bar API should somehow manage to partition arbitrary running code into parts of equal duration? Can you elaborate?

Compare [CopyFile](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-copyfile) and [CopyFileEx](https://learn.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-copyfileexa) - second one allows to "split" atomic operation.

**Comment by mklement0** [comment]
Indeed, I have not paid attention to the history, except that I did notice in practice the unacceptable slowdown caused by the progress display in `Invoke-WebRequest` on Windows PowerShell. Without having looked at the implementation, it seems to me that the problem is the inappropriately frequent use of `.WriteProgress()`, correct?

To me, the proper solution is to fix that problem in the affected cmdlet(s), not to implement optimizations that _mitigate_ the problem, especially given that the overhead of the frequent method calls alone (even if the called method is a no-op due to optimizations) still amounts to an unnecessary slowdown.

That said, there's nothing wrong with optimizations _if they don't impact functionality_, which is currently the case, but - as before - I can't speak to the cost of fixing the optimization as proposed (or whether switching the technical foundation would make such a fix easier).

As for the fundamentals:

* I can see only one case where _PowerShell itself_ can provide a meaningful progress bar (do tell us if there are more):

  * See #13433

* Everything else requires deliberate, custom control of the progress bar by the code that wants to show one, and, beyond what I proposed above, and leaving technological improvements aside,  I don't see what's missing (#18737 has already been green-lit).

Your `CopyFileExe` example amounts to an _inversion_ of the current model, which, when applied analogously to PowerShell, would require the _engine_ to be in control of an operation and know its nature and scope, interspersed with occasional callbacks to user code. That doesn't sound feasible as a general model to me.

**Comment by SteveL-MSFT** [comment]
@mklement0 I believe individual cmdlets that are part of PowerShell have also had improvements to how often they write progress.  However, the perf fix was general such that poorly written scripts and cmdlets would also not incur a perf impact that the author or even user may not have known about.

It may be possible to cache the last progress update (rather than discard it) and on every 200ms if the last progress rendered isn't the same as the last progress written, then update without incurring a regression in perf.  I believe the significant perf impact previous was the time taken to render on the console so doing a bit of progress record comparison, even frequently, might be ok.

**Comment by iSazonov** [comment]
If we talk exclusively about this optimization (although I think we should start the discussion with the _progressbar concept_), I do not think that something can be done there without significant cost and loss of optimization.
We do three expensive things at each step:
1. Creating ProgressRecord
2. Writing this ProgressRecord to the engine buffer with preprocessing
3. Rendering
Now the optimization cuts off steps 2 and 3. To store the "last" ProgressRecord, we will have to do step two and move the thinning to this level. That is, we lose optimization and add complexity.

If we start with the progressbar concept, however, we can get an implementation that eliminates losses not only in step 2 and 3, but in step one as well!

**Comment by iSazonov** [comment]
If we talk about the `progress bar concept`, this is the _correct PowerShell as an idea_.

If we look [PowerShell stream fundamentals](https://devblogs.microsoft.com/scripting/understanding-streams-redirection-and-write-host-in-powershell/) we see 5 PowerShell Streams (Output, Error, Warning, Verbose, Debug) and there is no progress bar. Why? Because progress bar is ephemeral thing, it is psevdo-stream.
We could think of it as sounds or voice messages.
The main point is that this information does not intersect with real streams in any way, is not accumulated anywhere, and is not stored anywhere. All relevant information must be directed to the actual PowerShell streams.
If this antipode to real streams did not exist it should have been created!

[Earlier](https://github.com/PowerShell/PowerShell/issues/18848#issuecomment-1368496789) I have already formulated this concept as:
>>>> The only purpose of the progress bar, as the name says, is to inform the interactive user that the long process is ongoing.

Keys here are "inform", "interactive", "long". It is not to follow these key principles then problems are inevitable.

The PowerShell implementation of this concept is done in the spirit of PowerShell, implying that it is done as cmdlets.

But then we see problems in this implementation (much of this is due to a deviation from key principles):
- it is very expensive, i.e. the cost of creating and displaying the progress bar is too high and can exceed the cost of the main work.
- it is too vague, which provokes developers to misuse it in violation of the concept, i.e. they try to display significant information in the progress bar, when it should be directed to one (or more) real PowerShell streams.

Can PowerShell have a less expensive implementation? Sure.
Could PowerShell be smarter, save the developer from unnecessary work and tricks? Sure.

**Comment by SteveL-MSFT** [comment]
I think the request is reasonable from a user perspective, but also agree with @iSazonov (as I've also poked around the Progress code) that the current design of the code doesn't lend itself for enabling these types of changes easily without risk of regression/impact nor is it more critical than spending time fixing other functional issues.

**Comment by iSazonov** [comment]
Perhaps we should think about and adopt the concept that will allow us to simplify the code and at the same time increase the possibilities of customization.
I was installing an update on Exchange Servers today and there is an instructive progress bar - "this operation will take a few minutes", "this operation will take a long time", etc. - no dots, blinks, flickers or anything else superfluous. Definitely they know how to do things right.

**Comment by mklement0** [comment]
That makes sense, @iSazonov, but it seems that the only thing needed for that kind of abstract display is to fix the regression from Windows PowerShell (simply don't display a  _bar_ if `-PercentComplete` isn't used, as previously noted).

As for the optimization: note that my proposal was - expressed in terms of the 3-step model you describe above - to only do step 1 (repeatedly) in a 200-msec. window and then do steps 2 and 3 only _once_, at the _end_ of that window - but perhaps that indeed complicates things too much, given that that requires the rendering to happen _asynchronously_.

**Comment by iSazonov** [comment]
> given that that requires the rendering to happen asynchronously.

I was hoping this was possible, but it turns out that the progress bar display is done synchronously and directly from the runspaces. 
Moreover, there is no classic dedicated UI thread, the main thread is conhost (UI) and at the same time runs the main runspace.
I think some MSFT teams (as well as other developers) would breathe freer and get rid of headaches if pwsh had a dedicated thread for UI and runspaces were detached from threads. (We can only guess how many resources this eats up in Office365.)
For example, the Exchange Server team migrated code to managed and more so to asynchronous TAP, but obviously other than pwsh related code.
This seems to be a relic of the old development environment limitations.

**Comment by seppo498573908457** [comment]
Hi. I can see Write-Progress is a lightweight progress indicator, thus the update limiter. I run into this problem too. I have a script that checks ~150 items for changes. If there are no changes, it will go through all of them in about 1 second. But if an item has changes, it can take 15 to 20 seconds to process it. So when scanning items, the current displayed item is "always" wrong if it needs to process something. This can lead to much confusion and panic.

My workaround is simple. I added a second progress bar with another -Id, that is displayed only when an item needs to be processed. Clean, fast and simple.

PS. It would be nice to have this update limiter documented in the [Write-Progress](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-progress) documentation and propose a second progress bar as a workaround.
