### ISSUE TITLE
Make 7.3.* and higher not installable under Windows 7.

### ISSUE THREAD

**Issue by ZonderP** [PowerShell/PowerShell#18854]
### Summary of the new feature / enhancement

Currently it is possible to install 7.3.1 under Windows 7.
But then on launch of it, it crashes.
Further reading told me that 7.3.0 and higher doesn't run on Windows 7 anymore.
Thus it would be better, that the installer already tells us so and doesn't allow the installation at all.

### Proposed technical implementation details (optional)

Make the windows installer check the current Windows OS and deny installation in case the OS is Windows 7 (or any other not anymore supported Windows OS.

**Comment by ZonderP** [comment]
Also - in case a 7.2.9 should get issued, it would be good, if that version of Powershell wouldn't display that any new version higher than 7.2.* would be available when it gets executed under Windows 7.
Yes - I know - Windows 7 is since quite some time not supported anymore officially...

**Comment by iSazonov** [comment]
@heaths Could you please look the issue?

**Comment by SteveL-MSFT** [comment]
Windows 8.1 is out of support Jan 10th, 2023, so we should just have the installer only support Win10+

**Comment by xtqqczze** [comment]
> Windows 8.1 is out of support Jan 10th, 2023, so we should just have the installer only support Win10+. However, Windows Server 2012 is supported til Oct 2023.

Support for Windows Server 2012 under [ESU](https://learn.microsoft.com/en-us/lifecycle/faq/extended-security-updates) runs through to October 13, 2026.

**Comment by fMichaleczek** [comment]
Also Support for Windows Server 2008/2008R2 on Azure under ESU runs through to January 14, 2024
[source](https://www.microsoft.com/en-us/windows-server/extended-security-updates)

**Comment by ZonderP** [comment]
I do not know, if support of a specific OS Windows version means, that also the newest versions of Powershell needs to be runable on those OS.
My ticket was more about that if any version of Powershell cannot anymore be successfully used on an OS, then the installer should be aware of that fact and not allow installation anymore.

**Comment by xtqqczze** [comment]
> Also Support for Windows Server 2008/2008R2 on Azure under ESU runs through to January 14, 2024 [source](https://www.microsoft.com/en-us/windows-server/extended-security-updates)

As per [PowerShell Support Lifecycle](https://learn.microsoft.com/powershell/scripting/install/PowerShell-Support-Lifecycle?view=powershell-7.3), support dates are linked to [.NET's support lifecycle](https://dotnet.microsoft.com/platform/support/policy/dotnet-core).

Windows Server 2008/2008 R2 is not a supported platform as it is no longer supported by .NET.

**Comment by heaths** [comment]
@iSazonov @SteveL-MSFT so, to confirm, you want me to block installation on < Win10 (client) and < Server 2012?

**Comment by SteveL-MSFT** [comment]
@heaths don't do anything for now.  Need to discuss w/ Committee what we should do here given the Server skus are under extended support.

**Comment by iSazonov** [comment]
It seems ESU is only for _security_, it is not full support.

**Comment by heaths** [comment]
> @heaths don't do anything for now. Need to discuss w/ Committee what we should do here given the Server skus are under extended support.

Sure thing. Just @mention me again if/when ready so this pops back up in my notifications.

**Comment by ZonderP** [comment]
Why not create an own ticket for the issue on how to deal with (possibly) not anymore supported Windows OS's?
And just fix this ticket for OS's where 7.3.x just cannot be started anymore for whatever reasons?
According to the information here (https://learn.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-73?view=powershell-7.3), Windows 7 is the only Windows OS - apart from even older version - where 7.3.x doesn't run anymore.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee discussed this.  PS7 is limited by what the version of .NET supports, so since .NET 7 doesn't support Win7 and Windows Server 2008/R2, we should update the MSI installer to give an error message that the OS is not supported if it's not Win10 or Server 2012+.  @heaths can you create a PR?

**Comment by heaths** [comment]
Unfortunately, Windows AppCompat is applying a shim to downgrade the OS properties e.g., `VersionNT` to equate to Windows 8.1. The best I can do for Client at least is checking for >= 8.1. I need to look deeper into Server 2012 (Azure VMs don't support that old), but I suspect a similar problem. This is likely because Windows no longer supports APIs that return the actual Windows version since they were abused. The VS Setup engine and WiX itself ran into this problem as well.

Alternative, I could write a custom action that avoids the shim and provides more control. But I'm also curious about whether you use the bundle authored therein i.e., _Bundle.wxs_. @TravisEz13 authored it, but I can't say I've ever seen it used. That said, unless it's used ubiquitously, I wouldn't rely on it.

If we go the custom action route, we'll need an environment that can build either C++ or Rust (I wrote the [msica crate](https://crates.io/crates/msica) that makes this easy. Could use a separate repo that builds a WiX extension you just use rather than having to build it every time here. It's not like it'd change often.

**Comment by iSazonov** [comment]
If we use WiX 3.x maybe migrate to version 4.x? I see latest version uses 
https://github.com/wixtoolset/wix4/blob/240b663ad5fc94ed6d19c966b5c9105a176ecf40/src/libs/dutil/WixToolset.DUtil/osutil.cpp#L241
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlgetversion
Perhaps they bypass the shim.

**Comment by heaths** [comment]
IIRC, that one lies too. They did that circa Win8.1. We wanted to use that for VSSetup as well and when asked, that's what Windows told us. Even if it doesn't (seems I need to install the DDK, which I'm doing now), we don't need to switch to WiX 4. That's much more involved than just writing a CA. A lot has changed, and not everything may be compatible.

**Comment by heaths** [comment]
Perhaps not. Wrote a quick test and it is correct without even manifesting the EXE:

```c
#define _WIN32_WINNT 0x0603
#include <ntddk.h>
#include <iostream>

void main()
{
    RTL_OSVERSIONINFOW info = { sizeof(RTL_OSVERSIONINFOW) };
    auto status = RtlGetVersion(&info);
    if (status == STATUS_SUCCESS)
    {
        printf("%d.%d.%d\n", info.dwMajorVersion, info.dwMinorVersion, info.dwBuildNumber);
    }
}
```

```pwsh
cl main.cpp /I'C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\km' /D_AMD64_ /link 'C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\km\x64\ntoskrnl.lib'
```

Still, switching to WiX 4 is unnecessary. Still would likely have to write our own CA. They use this for existing CAs defined here: https://wixtoolset.org/docs/reference/wixext/wininfo/. They don't return general version information.

**Comment by xtqqczze** [comment]
> @PowerShell/powershell-committee discussed this. PS7 is limited by what the version of .NET supports, so since .NET 7 doesn't support Win7 and Windows Server 2008/R2, we should update the MSI installer to give an error message that the OS is not supported if it's not Win10 or Server 2012+. @heaths can you create a PR?

I would suggest that any PR is _not_ backported to the 7.2 LTS branch. Although unsupported, .NET 6 will likely continue to function on Windows 7, so we should not do anything that would block usage.

**Comment by kilasuit** [comment]
@xtqqczze I disagree from a security perspective and I think many others would agree with my stance on this too

**Comment by xtqqczze** [comment]
Additionally, according to dotnet/core#7556, .NET 8 (LTS) will maintain support for Windows Server 2012 (NT 6.2) and Windows Server 2012 R2 (NT 6.3) throughout the entire ESU period, which will end in _October 2026_.

**Comment by heaths** [comment]
This checks for client >= 8.1 and server >= 2012. If we want to go the custom action route, I'm working on a solution that will be more robust than what Windows Installer or WiX offers currently.

**Comment by iSazonov** [comment]
@heaths Could you please ask in Gihub WiX repository what they think about the problem? Perhaps they know a trick.

**Comment by heaths** [comment]
I honestly don't need to. It's using the DDK to make a kernel-level call. I've already written a CA we could use at https://github.com/heaths/msiverca-rs.

I was on the WiX team and helped write a lot of v3. Migrating to v4 is unnecessary. They're just calling `RtlGetVersion` which only custom actions can call. They're not exposing it (besides SKU properties) in any CAs. My approach is to set properties separately for major, minor, and build versions (in semver, this would be the "patch") so you can compare each instead of the haphazard "major * 100 + minor" approach MSI has always used.

**Comment by iSazonov** [comment]
@heaths My thoughts are that if WiX is on 4 RC1 stage they could add the solution internally - it is better to invest in new version than create a hook for previous version. No doubt they will have to address this problem too, if they haven't. We have over 7 months to test and stabilize before 7.4 RC. Having our CA makes it difficult for us to migrate in the future. WiX 4 supports MSBuild, which is probably more convenient. I don't want to force things, but it's worth thinking about.

**Comment by heaths** [comment]
If you look at their docs, they only publish the same properties - the server SKUs, mainly - they did before. The function you linked before is for custom actions to use - it's not a custom action itself. The only place it's used is to publish those previous server SKU properties: https://wixtoolset.org/docs/reference/wixext/wininfo/#querywindowssuiteinfo

Those are the same properties already available in Wix3, none of which are helpful in this case. I have already reached out to see if they want to explore some options to publish their own `VersionNT`-like properties like I'm doing in my CA.

Wix3 isn't going anywhere. Wix4 has been of RC quality for ages and migration is not straight forward. A lot has changed. Even if/when you migrate, swapping out a CA and a few properties for another isn't difficult.

I leave it up to @SteveL-MSFT and folks if they even want to use a CA right now or take the PR as is, which checks for Win 8.1 or newer client, or Server 2012 or newer. That's the best possible with standard Windows Installer properties and is a close approximation. Win8.1 support drops next Tuesday, but usage numbers are so low (and have been for a long time) it's hardly worth worrying about for now.

**Comment by iSazonov** [comment]
I agree to accept this PR as it is without complications. (After all, we can block pwsh from running in it itself if it is important.)

**Comment by heaths** [comment]
@iSazonov, @SteveL-MSFT seems calling `RtlGetVersion()` won't work anyway as [it gets lied to as well](https://github.com/heaths/msiverca-rs/issues/5). This is in line with what I was initially told many years back when designing the VSSetup engine. I initially thought it might be because of how _msiexec.exe_ is manifested, but after additional testing it appears it's something else - perhaps an AppCompat shim that isn't obvious in the logs like in the example above when using `VersionNT` or `VersionNT64` properties.

/cc @barnson since we were discussing this offline.

**Comment by heaths** [comment]
I'm going to try to follow up with Windows internally, but given my testing it seems that only Windows Installer is being lied to. Direct calls to `RtlGetVersion()` and through `GetProcAddress()` on _ntdll.dll_ work with and without manifesting an application (should probably manifest it, though, based on docs), so any custom bootstrappers like Burn should be able to call `RtlGetVersion()` to check for versions newer than Windows 10, which will likely be required someday. Calling the [helpers](https://learn.microsoft.com/windows/win32/sysinfo/version-helper-apis) is even deprecated as of Windows 10, so there's no telling if `VerifyVersionInfo` will work when the major version is changed in some subsequent Windows version (presumably).

**Comment by heaths** [comment]
At this point - or perhaps in the near future - it seems the only way to detect any version above Win8.1 is to ship a self-contained burn bundle, which you already have authoring for but I find no evidence of currently building or shipping. The MSI would still ship within and handle upgrades, but the bundle would be the delivery mechanism. The MSI can also block direct install with an override so that the bundle can install it and administrators can override for AD deployments or whatever. This is what we used to do in the older VS installers.

@SteveL-MSFT if you want to go that route, we could probably chat over Teams or maybe set up a short team meeting to go through scenarios and make sure we've covered all bases, but I don't anticipate shipping a single-MSI, self-contained bundle instead of the MSI will have any adverse effects. Just have to make sure all deployment scripts are updated, and that winget and other package managers are updated to install an EXE instead of an MSI.

Would OpenSSH be needing any of this treatment as well?

**Comment by iSazonov** [comment]
I think we can use most simple solution today since it is not security hole and wait official MSFT solution.
I think most simple solution is warning message on first msi screen.

---

As side notice. I see .Net uses [RtlGetVersionEx](https://github.com/dotnet/runtime/blob/8d9114b7e4a7937002fb7013f26cdd3e5c9d1446/src/libraries/System.Private.CoreLib/src/System/Environment.Windows.cs#L144) too.

As I mentioned above, this allows us to block pwsh internally, we could put the check on first place in Main.cs if we want.

---

@heaths Thanks for your investigations! Perhaps you have contacts with .Net team who owns .Net msi installer - [if .Net team concluded not support Windows 7 and 8.1](https://github.com/dotnet/core/issues/7556) the problem with msiexec is a headache for them too. /cc @richlander

**Comment by heaths** [comment]
> wait official MSFT solution

I was involved with that world for 15 years at Microsoft (and about 8 before that) - knew the MSI source code front and back, too - and I don't think you're going to see any change. The version lies were done intentionally under protest from a number of product groups, thus forcing chainers to adopt a better solution. I suspect a push to Windows Store.

This is why I brought up that we may need to ship the bundle EXE which does provide its own simple variables with the *real* version that can be conditioned if so desired. It can still be distributed via scoop, winget, downloaded, etc., and upgrade any existing installs. I worked a bunch on burn, especially it's upgrading and servicing logic.

**Comment by iSazonov** [comment]
@daxian-dbw Why do we need new issue if we have here full information about the problem?

**Comment by daxian-dbw** [comment]
Because the issue name and the initial issue description is misleading. If you don't want to use a new issue to track the Win8.1 issue, then please update the issue name and the initial issue description.

**Comment by heaths** [comment]
I talked with @SteveL-MSFT offline and discussed some options. I've opened https://github.com/PowerShell/PowerShell/issues/18909 to track. I will prototype the EXE CA approach but suspect this will work and would be less overall change / cost to all involved.

**Comment by sergeevabc** [comment]
Since you decided to deprive Windows 7 users of the opportunity to use PowerShell 7.3+, then at least have the courage to do it competently, not hiding behind a fig leaf of OS EOL, but issuing a proper error message. At present ([actually for months](https://github.com/PowerShell/PowerShell/discussions/18494#discussioncomment-4123142)) the launch of portable ```pwsh.exe``` leads to the absorption of all system resources and requires a hard reboot of the computer. Long live 7.2.9!

**Comment by TravisEz13** [comment]
@heaths the bundle is used for the Windows Update scenario.

**Comment by heaths** [comment]
@TravisEz13 @SteveL-MSFT then we should use it everywhere. The winget and other providers' manifests could be replaced and because the bundle installs the MSI it will still do a major upgrade of any older versions installed.

That said, I don't know the ramifications of switching everything to the bundle EXE. Ideally, we'd have to stop publishing the MSI standalone and that may mess up a lot of deployment scenarios such as AD GPO some admins might use. I'm sure you agree that's bad; thus, I still recommend having the MSI do the necessary and accurate checks as I described above. The EXE still could so it won't even bother executing the MSI, but I don't think we should leave the discretion solely in the bundle.

**Comment by TravisEz13** [comment]
The last time we looked into it, authoring the GUI for the options was more difficult in the EXE.  So, we aren't using it for initial install.  Perhaps this is wrong and/or poorly documented.
