### ISSUE TITLE
PowerShell Class Not Handle System.Data.DataTable as Function

### ISSUE THREAD

**Issue by cssjun** [PowerShell/PowerShell#18924]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I wrote a code to convert arrays to datatable. However, the codes work when with Function but not working with Class as PowerShell failed to process.

### Expected behavior

```console
return datatable
```

### Actual behavior

```console
failed to return datatable
```

### Error details

```console
Line |
  59 |           Return $DataTable
     |                  ~~~~~~~~~~
     | Cannot convert value "" to type "System.Data.DataTable[]". Error: "Cannot convert the "System.Data.DataRow" value of type "System.Data.DataRow" to type "System.Data.DataTable"."
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

class OutDataTable{
    #define input as array
    [System.Array[]]$source

    #main function to convert array to datatable
    [System.Data.DataTable[]]CovertToDataTable([System.Array]$source){
        #set up colunms
        $columns = $source[0] | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name
        $dataTable = New-Object -TypeName System.Data.DataTable
        foreach ($column in $columns)
        {
         $dataTable.Columns.Add("$($column)")
        }
        #For each row in source, build row and add to DataTable.
        foreach ($entry in $source)
        {
         $dataRow = $dataTable.NewRow()
            foreach ($column in $columns)
            {
            $dataRow["$($column)"] = if($null -ne $entry.$column){$entry.Column}else{$null}
            }
            $DataTable.Rows.Add($dataRow)
        }
        #return datatable
         Return $dataTable
    }
}

$adUser = Get-ADUser test2
$adData = [OutDataTable]::new()
$adDataTable = $adData.CovertToDataTable($adUser)
$adDataTable.Columns.columnname

**Comment by cssjun** [comment]
Hi Michael Klement,

I did appreciate your help. Yes, I'm so surprised about that (I had gone thru for the [Class documentation](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_classes?view=powershell-7.3) on the MS official website for times but found nothing). Now the issue is solved with your suggestion. Thank you again.

**Comment by mklement0** [comment]
You're welcome, @cssjun, but I realized that while my workaround was effective, the explanation needs to be more nunanced:

* You've definitely hit an edge case, because you generally need _not_ worry about preventing enumeration via the `return` keyword in class methods; e.g.:

```powershell
# OK: the [object[]] array effectively created by 1..3 is cast to [int[]] on return.
class Foo { static [int[]] Bar() { return 1..3 } }; [Foo]::Bar()
```

* Using a _single_  `[System.Data.DataTable]` instance as the return value works fine too - and that would have sufficed in your case (see bottom section).

* **The problem is specific to when you're effectively _nesting_ enumerables**, such as using array of elements whose types are themselves enumerables **_and_ you're trying to situationally return just _one_ instance**.

  * The non-obvious fact that PowerShell considers `[System.Data.DataTable]` enumerable obscures that fact, and the fact that it enumerates a _different_ type, namely its _rows_, (`[System.Data.DataRow]`) _breaks_ the cast to `[System.Data.DataTable[]]` that PowerShell attempts (which could be considered a blessing - see below).

```powershell
class Foo {
  static [System.Data.DataTable[]] Bar() { 
    $dt = [System.Data.DataTable]::new()
    $dt.Columns.AddRange(@('one', 'two', 'three'))
    $dt.Rows.Add($dt.NewRow()) # Add at least 1 row to provoke the symptom.
    # !! Breaks, because $dt behaves like $dt.Rows, and the result 
    # !! cannot be cast to (an array of) [System.Data.DataTable] instance(s).
    return $dt # Use `return , $dt` to fix.
  }
}
[Foo]::Bar()
```

  * If you were to return _two or more_ `[System.Data.DataTable]` instances, the problem would go away, because then only _that_ array would get enumerated and cast to the array return type, not also _its elements_. For instance, `return $dt, $dt` above would succeed (though would obviously return _two_ table instances).

 * The fact that `[System.Data.DataTable]` enumerates instances of a _different_ type actually makes the problem more obvious; with other enumerables the problem may go unnoticed:

```powershell
class Foo {
  # Returns an array of lists.
  static [System.Collections.Generic.List[int][]] Bar() { 
    $list = [System.Collections.Generic.List[int]] @(42, 43)
    # !! Does NOT work as expected, because $list gets enumerated
    # !! and *each element* is cast to its own [System.Collections.Generic.List[int]] 
    # !! instance, so that *2* elements are output.
    return $list # Use `return , $list` to fix
  }
}
[Foo]::Bar() | Measure-Object # !! Returns *2*
```

In short:
 * In `class` methods, if the return type is an _enumerable of enumerables_, the case of returning a _single_ enumerable must be special-cased.
 * The unary form of `,` is the only viable solution for returning a _single_ instance of the nested enumerable, as far as I can tell (e.g, `return , $dt`):
   *  `Write-Output -NoEnumerate` to prevent enumeration is _not_ effective in `class` methods (for reasons unknown to me; it works in functions and scripts), 
   *  `@(...)` is _generally_ not effective in creating an array wrapper around something that itself is an enumerable.
   * Even using the method's return type as an explicit cast does _not_ help; e.g, `return [System.Collections.Generic.List[int][]] $list` in the example above still creates a _two_-element array of `[System.Collections.Generic.List[int]]` instances with one number each.

---

A PowerShell-idiomatic reformulation of your code with a _single_  `[System.Data.DataTable]` instance (self-contained example):

```powershell
class OutDataTable {
  #main function to convert array to datatable
  [System.Data.DataTable] CovertToDataTable([System.Array]$source) {
    $dataTable = [System.Data.DataTable]::new()
    #set up colunms
    $columns = $source[0].psobject.Properties.Name
    $dataTable.Columns.AddRange($columns)
    #For each row in source, build row and add to DataTable.
    foreach ($entry in $source) {
      $dataRow = $dataTable.NewRow()
      foreach ($column in $columns) {
        $dataRow[$column] = $entry.$column
      }
      $dataTable.Rows.Add($dataRow)
    }
    #return datatable
    return $dataTable
  }
}
  
[OutDataTable]::new().CovertToDataTable(@(
  [pscustomobject] @{ one = 1; two = 2; three = 3 },
  [pscustomobject] @{ one = 10; two = 20; three = 30 }
))
```

**Comment by nczsl** [comment]
I have also encountered a similar problem
```powershell

function get-table{
param(
[string]$name
)
$table = [System.Data.DataTable]::new($name)
# write-host "Table name: $($table.TableName) show by inner of function"
# write-host $table. GetType()
#return $table
return ,$table
}

$table = get-table 'eastmoney_stocklist'
echo "table is null ? $($table -eq $null)"
echo "Table name: $($table.TableName)"

$table2 = [System.Data.DataTable]::new('eastmoney_stocklist')
echo "table2 is null ? $($table2 -eq $null)"
echo "Table name: $($table2.TableName)"

function Get-ComplexObject {
$list = [System.Collections.Generic.List[string]]::new()
$list. Add("Item1")
$list. Add("Item2")
return $list
}

$complex = Get-ComplexObject
Write-Host "Complex object count: $($complex.Count)"
write-host $complex[0]
write-host $complex[1]
#When adding commas:
table is null ? 
Table name: eastmoney_stocklist
table2 is null ? 
Table name: eastmoney_stocklist
Complex object count: 2
Item1
Item2
#Not adding:
table is null ?  True
Table name:
table2 is null ?
Table name: eastmoney_stocklist
Complex object count: 2
Item1
Item2

```
I think this is a pit; I don't understand what adding commas means;
