### ISSUE TITLE
Get-ChildItem -Filter should accept string array

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/PowerShell#18951]
### Summary of the new feature / enhancement

Sometimes I need to get a list of files of the same category (e.g. images). Currently it's cumbersome to get this.

So, the `Filter` parameter of the `Get-ChildItem` Cmdlet should be able to access a string array.

# Desired Situation

The `Filter` parameter of the `Get-ChildItem` Cmdlet should be able to accept …
- a string array
- _optionally:_ a semicolon separated list of filter strings

### This would allow for the following:

```
PS> Get-ChildItem -Filter '*.png','*.jpg','*.gif'

PS> Get-ChildItem -Filter '*.png;*.jpg;*.gif'
```

### Proposed technical implementation details (optional)

```
PS> Get-ChildItem -Filter '*.png','*.jp*g','*.gif' -Name
MyGif.gif
MyPng.png
MyPng2.png
MyJpeg.jpg
MyJpeg2.jpeg
PS> _
```

**Comment by jborean93** [comment]
AFAIK `-Filter` is special because it essentially is an analogue for the `SearchPattern` on [EnumerateFileSystemEntries](https://learn.microsoft.com/en-us/dotnet/api/system.io.directory.enumeratefilesystementries?view=net-7.0#system-io-directory-enumeratefilesystementries(system-string-system-string)). This accepts a raw string and not an array so PowerShell can't expose an array here. The `-Include` and `-Exclude` parameters are implemented in the provider which is why they support an array of values. You can also just do `| Where-Object { ... }` to filter as you need.

**Comment by scriptingstudio** [comment]
```powershell
Get-ChildItem * -include '*.png','*.jpg','*.gif'
```

**Comment by mklement0** [comment]
Just to add to the previous comments, by pointing out aspects that may not be obvious:
* `-Include` does provide the desired functionality, but it performs filtering _on the PowerShell side_ instead of at the source (file-system APIs), which makes it noticeably slower. Also, it uses PowerShell's own wildcard language, which is both more powerful (due to supporting `[...]` character sets and ranges) and doesn't have `-Filter`'s legacy quirks. The support for `[...]` constructs can also be a pitfall, if the intent is to use `[` and `]` as literal chars. See [this Stack Overflow answer](https://stackoverflow.com/a/60171419/45375) for more information.
* Also, as @scriptingstudio's example implies, `-Include` doesn't work as one would expect, as it is applied to the leaf path component of the _input path itself_, not _its children_ - hence the use of `*` as the (positionally implied) `-Path` argument - see #3304

  * In simple cases you can avoid the problem by passing the multiple patterns directly to the  `-Path` parameter:

       ```powershell
       Get-ChildItem *.png, *.jpg, *.gif  # -Path implied
       ```

**Comment by BrucePay** [comment]
Note that Get-ChildItem is a generic command that talks to *arbitrary* providers. Changing the type of -filter impacts all of the providers.

**Comment by aguzev** [comment]
Could the File System provider implement the requested feature as in the following example? The upright slash should be replaced with an alternative if it is a valid one for filenames in a supported operating system.

```powershell
PS> Get-ChildItem -Filter '*.png|*.jpg|*.gif'
```

**Comment by SetTrend** [comment]
> Note that Get-ChildItem is a generic command that talks to _arbitrary_ providers. Changing the type of -filter impacts all of the providers.

According to [MSDN documentation](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem#-filter), "the [FileSystem](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_filesystem_provider?view=powershell-7.3) provider is the only installed PowerShell provider that supports filters."

**Comment by aguzev** [comment]
> According to [MSDN documentation](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem#-filter), "the [FileSystem](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_filesystem_provider?view=powershell-7.3) provider is the only installed PowerShell provider that supports filters."

This statement does not limit the range of providers supporting filters. Any cmdlet provider may support filters: [CmdletProvider.Filter](https://learn.microsoft.com/dotnet/api/system.management.automation.provider.cmdletprovider.filter), [Provider capabilities](https://learn.microsoft.com/dotnet/api/system.management.automation.provider.providercapabilities).
