### ISSUE TITLE
Support direct implementing of C# interfaces in powershell classes

### ISSUE THREAD

**Issue by rgbav** [PowerShell/PowerShell#19020]
### Summary of the new feature / enhancement

As a user i want to have the ability to use types from assemblies (.dlls) in classes without workarounds.
For example when trying to implement an interface `class Logger : ILoggerFromDll {}`.  "Unable to find type..."
There exist some workarounds:
https://stackoverflow.com/questions/53670021/using-dotnet-interface-in-powershell-class
https://stackoverflow.com/questions/69019962/how-can-i-import-load-a-dll-file-to-use-in-a-powershell-script-without-getting

but it would be nice and cleaner if it would just work without these. I know this isn't a small change because that is how the parser works but maybe there is a possibility to change the behaviour of the parser.

**Comment by iSazonov** [comment]
Dup #2223

**Comment by rgbav** [comment]
> Dup #2223

It is not a duplicate. The other request wants interfaces written in powershell. I want to implement C# interfaces without complicated workarounds to load types. It is already possible for example `CustomCollection : System.Collections.ICollection`. But not with own written dlls.

**Comment by mklement0** [comment]
It is a duplicate of https://github.com/PowerShell/PowerShell/issues/3641#issuecomment-297151112, where the proposal was green-lit to make `using module` / `using assembly`  statements load their types at parse time, so that they can be referenced in `class` declarations.

See also:
* https://github.com/PowerShell/PowerShell/issues/6652

**Comment by rgbav** [comment]
@mklement0 This example works.
```
using assembly 'C:\Program Files\PowerShell\7\System.DirectoryServices.dll'
using namespace System.DirectoryServices.ActiveDirectory

class myDirectoryClass : System.DirectoryServices.ActiveDirectory.DirectoryContext
{

  [DirectoryContext]$domain

  myDirectoryClass([DirectoryContextType]$ctx) : base($ctx)
  {
    $this.domain = [DirectoryContext]::new([DirectoryContextType]$ctx)
  }

}

$myDomain = [myDirectoryClass]::new([DirectoryContextType]::Domain)
$myDomain
```
But if i try this with my own assemblies the types will not be found.
![image](https://user-images.githubusercontent.com/105312229/214325671-6070b486-b973-4a20-a60c-b3e9a603f830.png)

**Comment by mklement0** [comment]
Your example only works because PowerShell itself loads the referenced assembly by default - your `using assembly` call is redundant in that case. 

Conversely, if the assembly isn't loaded yet, `using assembly` would load it _at runtime_, but that is _too late_ - that's what the linked issue is about: in order for your `class` declaration to see the types in the referenced `using assembly` assembly, the latter must be loaded _at parse time too_.

**Comment by rgbav** [comment]
(The working example is from Microsoft https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_using?view=powershell-5.1) And loading assemblies at parse time is currently not possible? (btw. thx for your help)

**Comment by mklement0** [comment]
Re example from the docs: that is unfortunate; it's clearly misleading; I've filed an issue(https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9744).

No,  unfortunately there's no direct solution at the moment, but there are workarounds; an overview is in [this Stack Overflow answer](https://stackoverflow.com/a/69104097/45375).

**Comment by daxian-dbw** [comment]
I believe this is a duplicate of https://github.com/PowerShell/PowerShell/issues/6653, which is supplemented by the comment https://github.com/PowerShell/PowerShell/issues/3641#issuecomment-297151112 that explains why loading assembly should be avoided at parsing time.
