### ISSUE TITLE
Get-AppxPackage and "Creating implicit remoting module ..." and performance

### ISSUE THREAD

**Issue by RobMahn** [PowerShell/PowerShell#19023]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`(Measure-Command {$null = Get-AppxPackage *}).TotalSeconds`
Displays "Creating implicit remoting module ..." on the first call and on subsequent calls runs slower than it does on V5.1.

Measure on V7.x - first call
`pwsh -Command '(Measure-Command {$null = Get-AppxPackage *}).TotalSeconds'`

Measure on V5.1
`powershell -Command '(Measure-Command {$null = Get-AppxPackage *}).TotalSeconds'`

### Expected behavior

```console
Get-AppxPackage should run as fast as it does in V5.1.

I don't understand the need to "Creating implicit remoting module ...".
```

### Actual behavior

```console
On the first call to Get-AppxPackage, the message "Creating implicit remoting module ...", even though it is being run locally.

This causes a several second delay.  Subsequent calls are faster, but still not as fast as running the same command in V5.1.
```

### Environment data

```powershell
V7.3.1
```

**Comment by 237dmitry** [comment]
A function is often slower than a cmdlet. Compare `Get-Command -Module Appx`

**Comment by mklement0** [comment]
The `AppX` module only works in _Windows PowerShell_.

To make its commands accessible in PowerShell Core, implicit remoting has to be employed, which involves cross-process communication involving CLIXML serialization with a hidden `powershell.exe` child process.

Commands provided via this mechanism, documented in the conceptual [about_Windows_PowerShell_Compatibility](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Windows_PowerShell_Compatibility) help topic, are invariably slower than those from natively available modules, and also have limitations with respect to type fidelity.

The "Creating ..." message is shown during on-demand creation of a local, temporary _proxy_ module is created the first time a command from a WinPS-only module is accessed in a session.
That is, you pay a one-time performance penalty for the _first_ call. Subsequent calls are still slower than in WinPS, because of the communication overhead described above.

**Comment by RobMahn** [comment]
Thank you for that explanation, it makes perfect sense.
