### ISSUE TITLE
Progress Bar problems with Remove-AppxPackage

### ISSUE THREAD

**Issue by RobMahn** [PowerShell/PowerShell#19022]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This script will demonstrate the problem by removing and re-installing the Calculator app.  (It requires Administrator privileges to be able to re-install the app.)
[BugInRemove-AppxPackage.zip](https://github.com/PowerShell/PowerShell/files/10491875/BugInRemove-AppxPackage.zip)

The work-around to re-displaying the progress bar is to run the cmdlet in a new shell.  e.g.
`$Env:AppxPackageName = $AppxPackage.Name`
`. (Get-Process -Id $PID).Processname  -Command 'Get-AppxPackage $Env:AppxPackageName | Remove-AppPackage'`

### Expected behavior

```console
The progress bar should honor the ProgressPreference and never re-display after the cmdlet completes.
```

### Actual behavior

```console
Remove-AppxPackage does not honor $ProgressPreference = 'SilentlyContinue'.

Then, the progress bar is re-displayed and remains in view if the command is followed by [System.Console]::ReadKey().

These are probably two seperate bugs, but tied closely together.
```

### Environment data

```powershell
The problem exists in V5.1 and V7.3.1
```

**Comment by mklement0** [comment]
Pragmatically speaking, using `pause` instead of `[Console]::ReadKey()` is a simple workaround that can make a lingering progress bar disappear (though I'm not sure why); a simple demonstration:

```powershell
# With [Console]::ReadKey(), the status bar would linger.
Write-Progress -Activity Test -Status  '100% complete'; Start-Sleep 2; pause
```

The root problem is that the `Appx` cmdlets apparently do not call `Write-Progress -Completed`, which means that PowerShell will _eventually_ hide the progress bar automatically, but not until after the script at hand has terminated.

As for honoring `$ProgressPreference`:

* As a _shell-only_ variable, it isn't available across _process_  boundaries, so the code you're passing to `. (Get-Process -Id $PID).Processname  -Command` will _not_ see the _caller_'s value (btw, a better way to call via a child process is `pwsh { Get-AppxPackage $args[0] | Remove-AppPackage } -Args $AppxPackage.Name`

* Even _in-process_, however, there's a wrinkle: since the `AppX` module in PS Core is loaded via the Windows PowerShell Compatibility feature, it uses implicit remoting via a _script module_, and functions in script modules do _not_ see the caller's preference variables, unless they're defined in the _global_ scope (e.g., `$global:ProgressPreference = 'SilentlyContinue'`), which requires explicitly restoring the previous value afterwards, so as not to affect subsequent code.

  * This is a longstanding problem; see #4568 for details.

**Comment by mklement0** [comment]
I forgot about the alternative: you can call `Write-Progress -Completed` _yourself_, but, unfortunately, this requires you to supply a _dummy `-Activity` argument_; e.g.:

```powershell
Write-Progress -Activity Test -Status '100% complete'; Start-Sleep 2; Write-Progress -Activity '(dummy)' -Completed; [System.Console]::ReadKey()
```

The unexpected need for an `-Activity` argument is the subject of #15252

**Comment by RobMahn** [comment]
I previously tried calling "Write-Progress - Activity 'dummy' -Complete" and that did not work.  I also tried creating a new progress bar and clearing it, but the old progress bar remained.

I also tried using pause right after the call and that did not protect the next ReadKey, which I was using to make a menu selection.  The menu display was trashed.

BTW, thanks for the better code idea, now using:
`. (Get-Process -Id $PID).Processname { $args[0] | Remove-AppPackage } -Args $AppxPackage`

**Comment by mklement0** [comment]
Let's try to narrow this down:

* With _direct_ calls, doesn't setting `$global:ProgressPreference = 'SilentlyContinue'` solve your problem?

It is plausible that the implicit remoting involved in direct calls to (the proxy commands for) the `AppX` module thwarts the `Write-Progress - Activity 'dummy' -Complete` workaround. (I haven't tried, given that you shouldn't expect others to _download_ source code just to reproduce your symptom).

**Comment by RobMahn** [comment]
> Let's try to narrow this down:
> 
> * With _direct_ calls, doesn't setting `$global:ProgressPreference = 'SilentlyContinue'` solve your problem?
> 
> It is plausible that the implicit remoting involved in direct calls to (the proxy commands for) the `AppX` module thwarts the `Write-Progress - Activity 'dummy' -Complete` workaround. (I haven't tried, given that you shouldn't expect others to _download_ source code just to reproduce your symptom).

I just tested $global:ProgressPreference = 'SilentlyContinue' and it does prevent the progress bar from appearing.  I looked in the documentation and saw nothing about when to specify global preference variables.  I did find this came up over 3 years ago in [https://github.com/PlagueHO/CosmosDB/issues/308](url).

The script that I submitted was specifically written to demonstrate the problem and short enough to examine before running.  The problem does not present itself outside of a script and describing how to write the script seemed too cumbersome.  But I understand your reluctance, especially with the Administrator requirement to replace the deleted app.

**Comment by mklement0** [comment]
First, a meta comment:

* I dug deeper, and realized that I had some misconceptions and that some of what I suggested wouldn't help.

  * Notably, I found `$global:ProgressPreference = 'SilentlyContinue'` _not_ to be effective: while the point about _script_ modules only seeing preference variables if they're defined in the _global_ scope is correct (see #4568), it seems that the additional factor of _implicit remoting_ being involved makes the workaround ineffective.
  * I _think_ it is due to the fact that the progress display must be silenced _at the source_, and the automatically generated local proxy script module makes no attempt to pass the local value on.
    * This may be worth reporting as a separate bug.
  * On a side note, a `-ProgressAction` common parameter is coming (though it wouldn't help here): see #18887

* I've hidden my previous comments and will post a - hopefully  now correct - summary below.

* It is commendable that you prepared detailed code to demonstrate the problem, but to make it easier for others to run it, please in general add it directly to your post, not as an attachment, ideally in the form of a minimal example.

**Comment by mklement0** [comment]
The root problem is that the `Appx` cmdlets apparently do not call `Write-Progress -Completed` (or make an equivalent `.WriteProgress()`  method call, given that they are _binary_ cmdlets) in order to remove the progress bar on completion, which means that PowerShell will _eventually_ hide the progress bar automatically, but not until _after the script at hand has terminated_.

 * As such, the problem should be reported against the  `Appx` module, which is _not_ maintained in this repo. The [module's doc page](https://learn.microsoft.com/en-us/powershell/module/appx/?view=windowsserver2022-ps) has a "Feedback" section that suggests [the Feedback Hub app should be used](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).

* Given that properly removing a progress bar isn't enforced by syntax / tooling, the problem is likely to affect other modules as well.

In your case, since you're using an _interactive_ feature that delays completion of the script - `[Console]::ReadKey()` - the progress bar lingers at that point.
(Interactive features provided by _PowerShell_ - such as `pause` - _may_ mask the problem, because they _temporarily_ hide a progress bar, but they actually _restores_ it afterwards).

As for *workarounds*:

* _Silencing_ the progress display altogether with `$ProgressPreference = 'SilentlyContinue'` is normally an option, but _not_ in this particular case, given that the `Appx` module is loaded via the [Windows PowerShell Compatibility feature](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Windows_PowerShell_Compatibility), which involves _implicit remoting_ via a proxy script module that is generated on demand, and this module seemingly does _not_ relay the preference, even if set _globally_ (which _script_ modules in general require, unfortunately (see #4568)).

* However, the workaround you came up with - calling via a _child PowerShell process_, using PowerShell's CLI - is effective, and even allows you to choose to _display_ the progress bar, relying on the fact that the PowerShell child process automatically _hides_ it on exiting:

   * In this case, given that _Windows PowerShell_ is ultimately called anyway, the workaround can be optimized by always calling `powershell.exe`. Aside from paying a performance penalty (if you call more than once), no functionality is lost. 
   
       ```powershell
       # With progress display
       powershell.exe -NoProfile { Get-AppxPackage $args[0] | Remove-AppPackage } -args $AppxPackage.Name

       # Without progress display
       powershell.exe -NoProfile { $ProgressPreference = 'SilentlyContinue'; Get-AppxPackage $args[0] | Remove-AppPackage }  -args $AppxPackage.Name
       ```

   * Generally, in cases where implicit remoting is _not_ involved by default, a CLI-based workaround comes with potential loss of type fidelity, however (a price you _invariably_ pay when implicit remoting is involved).

   * Hiding another command's lingering progress bar on demand with `Write-Progress -Activity 'unused' -Completed` works _only_ if the progress bar was put up _from PowerShell code_ with `Write-Progress` too and _without_ using an `-Id` argument.

**Comment by RobMahn** [comment]
Thank you for that detailed resolution.  I have reported this problem on the Feedback Hub as "Remove-AppxPackage does not close the progress bar".
