### ISSUE TITLE
Release .deb packages for Debian Stable

### ISSUE THREAD

**Issue by joakimlemb** [PowerShell/PowerShell#1903]
You have .deb packages for Ubuntu 14.x and 16.x, but not Debian.

In my experience Debian is a more popular for Servers than Ubuntu, so I'm hoping you could also supply .deb packages for Debian or maybe as a "workaround" make sure one of the Ubuntu .deb packages are compatible with the newest Debian Stable.

**Comment by tupcakes** [comment]
I was able to get the 16.x unbuntu release working on debian stretch without much issue. I just did the following:
sudo apt-get install libunwind8
sudo dpkg -i Downloads/powershell_6.0.0-alpha.9-1ubuntu1.16.04.1_amd64.deb

**Comment by cobracmder** [comment]
If you are running Debian Jessie, use the ubuntu 14.04 deb.

**Comment by voltagex** [comment]
https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=834756 for the bug to track in Debian,

**Comment by zaxebo1** [comment]
Please make the .deb packages named as:
dotnet-corefx-....deb   , dotnet-coreclr-....deb and dotnet-cli-......deb and powershell-.....deb 

so that the blocking bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=779970  for acceptance of powershell  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=834756 can be removed

**Comment by voltagex** [comment]
@zaxebo1 Unfortunately it isn't that simple. Debian doesn't just take external packages. While the current packages are fine for personal use, they don't meet Debian's standards, nor do they rebuild from source correctly (they require an internet connection on build, which is a no-no for Debian)

**Comment by zaxebo1** [comment]
**i hope that it does get solved, and powershell comes to debian official repository as soon as possible. i think regarding https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=779970 it is the microsoft's powershell team which has to take action now, not the debian side**

Actually  i use ubuntu and debian; and i only use official repository(of ubutu/debian) packages for global installation
For other packages, like powershell and others, which are not in official repo of debian/ubuntu, i only install them for my own personal usage using AppImage or flatpak and **that too in a separate user's home directory without any global privileges.**

**But, without any package being in official repo (of debian/ubuntu), we can not use the software in our official projects for the organization, as per the organization's IT policy**

**Comment by probonopd** [comment]
> For other packages, like powershell and others, which are not in official repo of debian/ubuntu, i only install them for my own personal curiosity/usage using **AppImage** or flatpak

@zaxebo1 the PowerShell team has been looking at using AppImage, have a look at https://github.com/PowerShell/PowerShell/pull/2082 and let them know if you'd like to use the AppImage.

**Comment by zaxebo1** [comment]
ya, i am fully convinced about advantages of AppImage format, and hence i have done the needful

**Comment by SteveL-MSFT** [comment]
@anmenaga has run our tests against Ubuntu14 build on Debian 8 Jessie and it works.  My suggestion is to rename the Ubuntu14 package to `powershell_6.0.0-alpha.18-1ubuntu1.14.04.1-debian8_amd64.deb` and after we get this package built, update the main readme to include a Debian8 section as well as have a section in the install for Debian8

Later we need to add nightly test runs against Debian8

**Comment by joeyaiello** [comment]
@SteveL-MSFT @anmenaga: I think close this issue constitutes publishing what we have to a deb8 repo for packages.microsoft.com. 

I'm okay with doing that post-beta1, but should try to get it done ASAP. Ideally, everyone on the *nix side should be moving onto repos.

**Comment by regs01** [comment]
And for Debian 9 which is already in RC.

Package libssl1.0.0 => libssl1.0.2
Package libicu55 => libicu57

It launches and works a bit without those, but aborts shortly after with error  
No usable version of the libssl was found
Aborted

**Comment by cobracmder** [comment]
@regs01, wouldn't the Ubuntu16 debs be closer to working on Debian 9 (Stretch) vs using the Ubunt14/Debian 8 debs?

**Comment by regs01** [comment]
@cobracmder that's with Ubuntu16 deb

**Comment by joeyaiello** [comment]
Moving this to 6.1.0 given that the current Ubuntu .deb's work just fine on Debian. Our goal with this issue is to follow all the semantics necessary to be accepted into official Debian repositories. (First step should be integrating with the [official Debian 8 repo on packages.microsoft.com](http://packages.microsoft.com/debian/8/).)

**Comment by zaxebo1** [comment]
> Our goal with this issue is to follow all the semantics necessary **"to be accepted into official Debian repositories"**

+1  
Eagerly awaiting for it to happen
Although had powershell got into debian repo now, then it would have meant that during nov-dec 2017 ubuntu will reimport entire debian testing repo for usage in its ubuntu version 18.04 LTS. So powershell being accepted into debian now would have meant next ubuntu LTS (which will be supported for next five years) will also have powershell in its official repositories. Which means powershell will have greater chance to move into official workflows of organizations, because of it being in "official" repos of linux distributions themselves. 

But still i am happy that even if powershell 6.1.0 also brings it into debian official repo, still i will eagerly wait, so that i can bring it into offical workflow choice of my organization  (as anything hosted on third party repo is strictly denied here )

**Comment by costincaraivan** [comment]
I'd just want to add a comment: if you want to gain a foothold in the realm of enterprise Linux, you need to include .NET Core and Powershell Core in Fedora and Debian. From there the packages will slowly propagate to RHEL and Ubuntu Server.

In many places there are policies against extra repos or external packages, for important servers.

**Comment by iSazonov** [comment]
@SteveL-MSFT @TravisEz13 Can we close the issue?

**Comment by TravisEz13** [comment]
I think this can be considered the request for a Debian 9 package which was released.  We should open a new issues for a Debian 10 package which was just released.
