### ISSUE TITLE
"SilentlyContinue" do not work for command needed "Administrator privileges"

### ISSUE THREAD

**Issue by devyodamaster** [PowerShell/PowerShell#19067]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [x] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing error with "Send-RDUserMessage". It should just run without any warning, but It is showing "WARNING" message.
IT shows warning message only at first time when I am running command next time it is not showing any warning. 
Command work absolutely fine and it send messages always, problem is with hide the warning.
### Expected behavior

```console
PS> Send-RDUserMessage `
 -HostServer $MachineName `
 -UnifiedSessionID $SessionID `
 -MessageTitle "Title" `
 -MessageBody $message `
 -WarningAction:SilentlyContinue
```

### Actual behavior

```console
PS> Send-RDUserMessage `
 -HostServer $MachineName `
 -UnifiedSessionID $SessionID `
 -MessageTitle "Title" `
 -MessageBody $message `
 -WarningAction:SilentlyContinue

WARNING: This module requires Administrator privileges. Please restart this session in elevated mode.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Please note that the [`RemoteDesktop`](https://learn.microsoft.com/en-us/powershell/module/remotedesktop/) module) isn't maintained in this repo, and that you should report problems with via the [Feedback Hub application](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).

 * Incidentally, how did you get this module - which seemingly only comes with _server_ editions of Windows and _isn't_ available in the PowerShell Gallery (there's only an unrelated third-party module with that name) - onto a Windows 10 system?

As for what may be happening and a potential workaround:

* It seems that the warning is issued _when the module is loaded_, which happens implicitly the first time you invoke one of its cmdlets in a session. (I can't speak to the design intent of the warning, and whether it is issued by mistake - perhaps _some_ cmdlets require elevation?)

* Because it isn't `Send-RDUserMessage` itself that issues the warning, `-WarningAction SilentlyContinue` has no effect.

* You can try the following to silence the warning: import the module _explicitly_ and silence warning with `3>$null` (note that using `-WarningAction SilentlyContinue` with `Import-Module` likely won't work either, because again the source of the warning isn't that cmdlet itself; based on a quick test, it seems that `Send-RDUserMessage ... 3>$null` is also not effective):

```powershell
# Call this before calling any of the cmdlets from the module.
Import-Module RemoteDesktop 3>$null
```

**Comment by devyodamaster** [comment]
Yes, like you said it is windows server 2022.

Working method for me is:

`Import-Module RemoteDesktop 3>$null -WarningAction SilentlyContinue`

That has no logic for me but works.

Thank you for your sugestions
