### ISSUE TITLE
Make `ConvertFrom-StringData` and `Import-PowerShellDataFile` return *ordered* hashtables, analogous to how `ConvertFrom-Json -AsHashtable` now works in v7.3+

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#19070]
### Summary of the new feature / enhancement

See also: 
* #19073

Since 7.3, `ConvertFrom-Json -AsHashtable` now  (fortunately) returns a hashtable in which the _definition order of the entries is respected_, courtesy of the new, `[hashtable]`-derived [`System.Management.Automation.OrderedHashtable`](https://learn.microsoft.com/en-US/dotnet/api/System.Management.Automation.OrderedHashtable) type - see https://github.com/PowerShell/PowerShell/issues/18524#issuecomment-1313456611

The `[hashtable]`-outputting  `ConvertFrom-StringData` and `Import-PowerShellDataFile`  cmdlets could benefit from the same improvement - as well as any other standard cmdlets that currently return `[hashtable]` instances.

**Comment by zotabee** [comment]
I would love to have this as an option as well.

**Comment by sean-r-williams** [comment]
This issue came up in #25090 as, today, you can kinda-sorta get ordering on PSD1s by adding the `[ordered]` accelerator on hashtable literals. However:
* It only works on nested hashtables (not the root)
* It only works if `-SkipLimitCheck` is added, which does not indicate/suggest this sort of behavior will be enabled
