### ISSUE TITLE
Get-StorageReliabilityCounter doesn't show temperature values unless selected

### ISSUE THREAD

**Issue by JustinWebDev** [PowerShell/PowerShell#19093]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

run
_Get-Disk | Get-StorageReliabilityCounter_
output:
```
Number Temperature ReadErrorsUncorrected Wear PowerOnHours
------ ----------- --------------------- ---- ------------
2                                        0
0                  0                     0    21001
1                                        0    21061
3                                        0
```

run
_Get-Disk | Get-StorageReliabilityCounter | Select-Object -Property Temperature_
output:
```
Temperature
-----------
         28
         38
         32
         37
```

### Expected behavior

```console
Any available values should always be shown.
```

### Actual behavior

```console
Temperature values will not show unless selected.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
get-disk | Get-StorageReliabilityCounter | gm  

Shows all the properties. Unless you have a very wide screen they can't be show as a table,
get-disk | Get-StorageReliabilityCounter | fl * 
would show them all as a list. 

The formatting of the the object can be changed to a different set of columns depending on your needs, or you could send feedback to the Windows team who own the storage module suggesting a better default set, but the module is part of the PowerShell 7 language, so not something that can be fixed _here_

**Comment by JustinWebDev** [comment]
I don't know what you are talking about.  Temperature column is shown - I know that attribute exists.  That is not the issue.

**Comment by jhoneill** [comment]
1. Get-StorageReliablityCounter is not part of the Powershell 7 language, it is a in PowerShell module bundled with windows.
2. Get-StorageReliablityCounter  does not print text on the screen, it runs an object of type `Microsoft.Management.Infrastructure.CimInstance#ROOT/Microsoft/Windows/Storage/MSFT_StorageReliabilityCounter`
This object has properties 
```
DeviceId
FlushLatencyMax
LoadUnloadCycleCount
LoadUnloadCycleCountMax
ManufactureDate
ObjectId
PassThroughClass
PassThroughIds
PassThroughNamespace
PassThroughServer
PowerOnHours
PSComputerName
ReadErrorsCorrected
ReadErrorsTotal
ReadErrorsUncorrected
ReadLatencyMax
StartStopCycleCount
StartStopCycleCountMax
Temperature
TemperatureMax
UniqueId
Wear
WriteErrorsCorrected
WriteErrorsTotal
WriteErrorsUncorrected
WriteLatencyMax
```

There are too many properties to print them all as a table, but they could all be printed as a list. 

3. The default formatting for a `Microsoft.Management.Infrastructure.CimInstance#ROOT/Microsoft/Windows/Storage/MSFT_StorageReliabilityCounter` object is a table with the five properties you showed, if you want it to be printed using a different set of properties, you can format it as you wish.
4. If you think the default formatting should be different, you need to raise that as Windows feedback, not in this repo because none of the code for that command is in this repo.

**Comment by JustinWebDev** [comment]
Look, I still don't know what you are talking about.  Please re-read the issue.  It is now about formatting.  It is about VALUES for a property.

**Comment by jhoneill** [comment]
In PowerShell formatting means "Which of the property values of the object should be printed if is displayed on the console. It objects are displayed as rows of table, with their properties as columns, how wide should the columns be, should the titles be the same as the property names, should numeric formatting be applied etc.". The authors of the Windows module which implements this command - who are not part of the PowerShell language team who run this repo, decided that `MSFT_StorageReliabilityCounter`  should render as a table with 5 columns and ignore the the other properties I listed. If you want to display different columns you can 
1. Send the outout to Format-Table and give the list of properties you want, and optionally tune the widths, headings etc
2. Replace the default formatting information with your own so this object always displays that column. 
3. If you think everyone would benefit from different columns being selected, send feedback to the team who maintain the command.

**Comment by JustinWebDev** [comment]
You still don't get it.  Look at the two outputs I show and see if something doesn't stand out to you.  I'll give you a hint:  Look at the temperature columns.

**Comment by jhoneill** [comment]
OK. I misread something. The formatting for the temperature column is wrong

```
(Get-FormatData  -TypeName  Microsoft.Management.Infrastructure.CimInstance#MSFT_StorageReliabilityCounter).FormatViewDefinition.control.rows.columns[1] | fl *

Alignment    : Undefined
DisplayEntry : script:
                                 if( $_.Temperature )
                                 {
                                   $_str += $_.Temperature;
                                   $_str += " C"
                                 }
                                 return $_str

FormatString :
```
So when the table is printed that script block is run to put degrees C onto the string. **But it won't work** 


Let's test it outside of the formatting operation
 ```
Get-Disk | Get-StorageReliabilityCounter  | foreach {
                              if( $_.Temperature )
                                 {
                                   $_str += $_.Temperature;
                                   $_str += " C"
                                  }
                                 return $_str
 }
```
Gives
```
InvalidArgument:
Line |
   5 |                                     $_str += " C"
     |                                     ~~~~~~~~~~~~~
     | Cannot convert value "C" to type "System.Byte". Error: "The input string 'C' was not in a correct format."
```

The first $_str += assigns the byte in .temperature to $_str without converting it to string. The second one tries to add " C" to a byte which won't work.  

It should be something like `  if( $_.Temperature ) {"$ $_.Temperature) C"} else {""} ` 


It's still a formatting problem, it's still something that needs to be fixed by the windows folks responsible for the module, not  in this repo (anyone from the team reading - can you give this a push ?)  but I misread your statement of the symptoms multiple times and so was convinced you were being dense, when in fact I was. Sorry about that.  Give me a shout if you want me to post a corrected formatting file.

**Comment by JustinWebDev** [comment]
How does this explain how I get values in one case and not the other?  E.g., if A equals 1:
_A = 1_
 vs
_A =_

Is the same formatting code not being used in both?
When you select a property, it does not go thru the formatting code?
When you don't inform output at all and accept default, it does go thru the formatting code?

A side question: Why don't formatting failures present errors?  (If they did, then maybe this would have been caught a long time ago.)

Quite right about being a Windows-specific module.  Since I have no idea how to report a bug to Windows, I guess it will never get fixed.

**Comment by jhoneill** [comment]
When you select a subset of properties the type of the object changes and the formatting rules no longer apply. 
```
Get-Disk | Get-StorageReliabilityCounter | get-member


   TypeName: Microsoft.Management.Infrastructure.CimInstance#ROOT/Microsoft/Windows/Storage/MSFT_StorageReliabilityCounter

//snip
```

shows the type, and  `
Get-FormatData  -TypeName  Microsoft.Management.Infrastructure.CimInstance#MSFT_StorageReliabilityCounter` 
gets the formatting data for that type, 

After a select the type has "selected" on the front and has lost the info about a CimInstance of _what_

```
> Get-Disk | Get-StorageReliabilityCounter | Select-Object -Property temperature | get-member


   TypeName: Selected.Microsoft.Management.Infrastructure.CimInstance

```
 
Any object can have multiple sets of formatting rules if it is going to a file, the console, or through convertTo-String, PowerShell looks for a set of rules for that type, if it doesn't find any it looks for a default property set as a member of the object, if it doesn't find one it uses all properties. If there are more than 4 properties to display it formats as a list, 4 or fewer and it uses a table. 

I think the errors are supressed because (a) we could create formatting and then drown in the errors, and (b) it's thought better most of the time to display what can be displayed.   It also means bugs like the one you've discovered escape into the wild when they should never have left the programmers desk. 

Window key F and file it as feed back. I'm hoping one of the PowerShell team will push it internally as well, because someone should feel embarrassed about it.

**Comment by JustinWebDev** [comment]
Thanks for the investigation and information.

Feedback Hub doesn't give me warm fuzzies, but maybe I'll do it.
