### ISSUE TITLE
Path returned by external command (wsl.exe) is mishandled by Powershell

### ISSUE THREAD

**Issue by wikiped** [PowerShell/PowerShell#19142]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

With WSL2 enabled and at least one linux distribution installed execute from Powershell prompt:

```powershell
wsl.exe echo "`$(echo `"C:\Windows\System32\wsl.exe`")"
```

```powershell
wsl.exe echo "`$(wslpath `"C:\Windows\System32\wsl.exe`")"
```

The bug only appears in `pwsh.exe` `7.3.*`.

Both commands executed in `pwsh.exe` version 7.2.9 as well as `cmd.exe` and `powershell.exe` (PSVersion: 5.1.19041.2364) produce expected output.

### Expected behavior

```console
PS> wsl.exe echo "`$(echo `"C:\Windows\System32\wsl.exe`")"
C:\Windows\System32\wsl.exe

PS> wsl.exe echo "`$(wslpath -u `"C:\Windows\System32\wsl.exe`")"
/mnt/c/Windows/System32/wsl.exe
```

### Actual behavior

```console
PS> wsl.exe echo "`$(echo `"C:\Windows\System32\wsl.exe`")"
"C:WindowsSystem32wsl.exe"

PS> wsl.exe echo "`$(wslpath -u `"C:\Windows\System32\wsl.exe`")"
"C:WindowsSystem32wsl.exe"
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
The behavior is as designed: Ultimately, you're executing the following in your WSL shell (which is `bash` by default):

```sh
# -> 'C:WindowsSystem32wsl.exe'
$ echo C:\Windows\System32\wsl.exe
```

Unquoted `\` is the _escape_ character in POSIX-compatible shells, and it is only needed to escape `\` itself, `"`, or `'`; it has no effect on any other character that follows, but the `\` is removed.

What you're looking for is:

```powershell
wsl -e wslpath 'C:\Windows\System32\wsl.exe'
```

**Comment by wikiped** [comment]
> The behavior is as designed

I am not sure which *design* you are referring to (considering `cmd.exe` and `powershell.exe` behavior), but here is an output from previous version of `pwsh.exe`:

![image](https://user-images.githubusercontent.com/5990528/218509409-c30d4d4c-85ae-4338-9e63-9afb45c6c107.png)

I will edit the original post to make it clearer that this bug has appeared with a new `7.3.*` version(s) of `pwsh.exe`.

**Comment by mklement0** [comment]
Good point, I forgot about the aspect of the  breaking 7.3 change that corrected the broken-since-v1 argument-passing to external programs with arguments containing embedded double quotes.

To get the old behavior back, use the following.

```powershell
& {
  $PSNativeCommandArgumentPassing = 'Legacy'
  wsl.exe echo "`$(echo `"C:\Windows\System32\wsl.exe`")"
}
```

See https://github.com/PowerShell/PowerShell/issues/18568#issuecomment-1315912404 for the backstory, including how the old behavior will probably become the default again, because the change broke too much code.

**Comment by mklement0** [comment]
P.S.: It's a moot point, but it's baffling to me that your commands _ever_ worked; it seems that `wsl.exe` adds its own quirks:

* With `Legacy` in effect, PowerShell constructs the following raw command line for ``wsl.exe echo "`$(echo `"C:\Windows\System32\wsl.exe`")"``, which is _broken_, because the _embedded_ `"` chars. lack escaping:
  * `wsl.exe echo "$(echo "C:\Windows\System32\wsl.exe")"`

* `wsl.exe` _should_ parse the broken last argument as _verbatim_ `$(echo C:\Windows\System32\wsl.exe)`, with the non-escaped, meant-to-be-embedded `"` chars. getting removed.
   * That is, what _should_ ultimately be executed in `bash` is the equivalent of the following, which does _not_ preserve the ``\`` chars. (-> verbatim `C:WindowsSystem32wsl.exe`):
      * `echo "$(echo C:\Windows\System32\wsl.exe)"`

**Comment by wikiped** [comment]
Thanks for the links with background info. I have actually seen `$PSNativeCommandArgumentPassing` mentioned in one of `7.3.*` releases notes, but the way it was phrased did not raise any red flags for me in terms of path handling.

After reading the info and some experiments it seems the main problem I was having was with paths surrounded by ``"` (escaped double quote). Replacing them with single quotes where bash expansion was not needed solved the problem even without changing `$PSNativeCommandArgumentPassing`.

Thanks for the help.

**Comment by mklement0** [comment]
Yeah, the magnitude of this breaking change wasn't fully considered and it certainly was inadequately announced.

Using `'...'`-quoting is certainly a way to avoid the issue, as also used in the
`wsl -e wslpath 'C:\Windows\System32\wsl.exe'` solution from my earlier comment.

Using `-e` is generally preferable, because it avoids involvement of the _shell_ on the WSL side, which complicates matters; if you do need to use the shell, call its CLI explicitly via `-e`, e.g. 
`wsl -e  bash -c 'wslpath ''C:\Windows\System32\wsl.exe'''`

**Comment by wikiped** [comment]
@mklement0
Appreciate your input, thanks.

**Comment by mklement0** [comment]
Glad to hear it was helpful, @wikiped.

I don't necessarily expect you to be interested in the following, but to further my own understanding I 
dug deeper into `wsl.exe`'s behavior, and why I think in your particular case two broken behaviors canceled each other out to yield the desired result (it's an amended version of my previous comment, which I've hidden):

* With `Legacy` in effect, PowerShell constructs the following _process command line_ for ``wsl.exe echo "`$(echo `"C:\Windows\System32\wsl.exe`")"``, which, is _broken_, because the _embedded_ `"` chars. lack escaping:
  * `wsl.exe echo "$(echo "C:\Windows\System32\wsl.exe")"`

* `wsl.exe` _should_ parse the broken last argument as _verbatim_ `$(echo C:\Windows\System32\wsl.exe)`, with the non-escaped, meant-to-be-embedded `"` chars. getting removed - that's how Windows CLIs based on Microsoft's compilers / the Windows API parse such arguments.

* However, `wsl.exe` apparently does _not_ parse its process command line into _individual arguments_, but passes the relevant part of its process command line _as-is_ to the `bash` CLI (via its `-c` parameter), and _as part of a Bash command line_ `"$(echo "C:\Windows\System32\wsl.exe")"` _does_ work, because the `"` inside `$(...)` do _not_ require escaping (sam as as _inside_ PowerShell).

  * In other words: what is ultimately executed is ``echo "$(echo "C:\Windows\System32\wsl.exe")"`` _as a Bash command_, which happens to work.

  * By contrast, with `Standard` in effect, PowerShell _correctly_ produces the following process command line: `wsl.exe echo "$(echo \"C:\Windows\System32\wsl.exe\")"` - that is, following the most widely observed rules for argument-passing on Windows, the _embedded_ `"` chars. - meant to be a _literal part of the argument_, must be ``\``-escaped, with the target CLI then (a) _retaining _ the embedded `"` as part of the argument and (b) _removing_ `\`, the escape char.

    * However, if that is passed on _as-is_ to Bash, broken behavior ensues, because Bash now considers the `\"` an _escaped_ `"` to be taken literally, prints it, and considers what follows an _unquoted_ string, resulting in the previously discussed ``\`` removal
    * In other words: what is ultimately executed in Bash is ``echo "$(echo \"C:\Windows\System32\wsl.exe\")"``, which yields verbatim (broken) `"C:WindowsSystem32wsl.exe"`

In short:

* **It isn't just PowerShell (in `Legacy` mode) that is broken; `wsl.exe` inappropriately relays part of its raw _Windows_ process command line as-is to Bash**.

* The ``wsl -e  bash -c '...'`` technique avoids this problem on the WSL side:
  *  Its works as-is in `Standard` mode:
      * `wsl -e  bash -c 'echo "$(echo "C:\Windows\System32\wsl.exe")"'`
  * In `Legacy` mode you have the confusing need to _manually_ `\`-_escape_ all `"` chars.:
      * `wsl -e  bash -c 'echo \"$(echo \"C:\Windows\System32\wsl.exe\")\"'`

**Comment by wikiped** [comment]
This is super useful - thank you very much.

It should probably be part of [WSL Tutorial](https://learn.microsoft.com/en-us/windows/wsl/about)
