### ISSUE TITLE
The PowerShell 5 and 7 unsupport Unicode for pipeline input?

### ISSUE THREAD

**Issue by gool123456** [PowerShell/PowerShell#19164]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

It doesn't recognize chinese input pipeline, but is normal on cmd.exe , What is the problem ? 

```
PS C:\Users\Hskyre> chcp
活动代码页: 936
PS C:\Users\Hskyre> "百度网盘", "hello"|findstr /i "百度"
PS C:\Users\Hskyre> "百度网盘", "hello"|findstr 百度

PS C:\Users\Hskyre> echo "百度网盘"|grep 百度
PS C:\Users\Hskyre> echo "百度网盘"|grep -i
File STDIN:
鐧惧害缃戠洏
```

### Expected behavior

```console
PS C:\Users\Hskyre> echo "百度网盘"
百度网盘
PS C:\Users\Hskyre> echo "百度网盘"|grep 百度
File STDIN:
百度网盘

```

### Actual behavior

```console
PS C:\Users\Hskyre> echo "百度网盘"
百度网盘
PS C:\Users\Hskyre> echo "百度网盘"|grep 百度
PS C:\Users\Hskyre>

PS C:\Users\Hskyre> Get-CimInstance Win32_COMClass -filter "caption='百度网盘'"

Caption        : 百度网盘
Description    : 百度网盘
InstallDate    :
Name           : 百度网盘
Status         :
ComponentId    : {679F137C-3162-45da-BE3C-2F9C3D093F64}
PSComputerName :

PS C:\Users\Hskyre> Get-CimInstance Win32_COMClass -filter "caption='百度网盘'"|findstr 百度
PS C:\Users\Hskyre>

PS C:\Users\Hskyre> Get-CimInstance Win32_COMClass -filter "caption='百度网盘'"|findstr /v 百度

Caption        : 鐧惧害缃戠洏
Description    : 鐧惧害缃戠洏
InstallDate    :
Name           : 鐧惧害缃戠洏
Status         :
ComponentId    : {679F137C-3162-45da-BE3C-2F9C3D093F64}
PSComputerName :

**CMD** C:\Users\Hskyre>echo "百度网盘"|grep 百度
File STDIN:
"百度网盘"
```

### Error details

```console
None
```

### Environment data

```powershell
PS C:\Users\Hskyre> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
```
PS C:\ProgramData\kasini3000> echo "百度网盘"|Select-String '百度'

百度网盘

PS C:\ProgramData\kasini3000> echo "百度网盘"|findstr '百度'
[31;1mNativeCommandExitException: [31;1mProgram "findstr.exe" ended with non-zero exit code: 1.[0m
PS C:\ProgramData\kasini3000> $OutputEncoding = [System.Text.Encoding]::GetEncoding(936)
PS C:\ProgramData\kasini3000> echo "百度网盘"|findstr '百度'
百度网盘
PS C:\ProgramData\kasini3000>


```

---

(Get-CimInstance Win32_COMClass -filter "caption='百度网盘'").name |Select-String '百度网盘'

**Comment by jborean93** [comment]
The long and short of it use `Select-String` instead of `findstr` as mentioned above. Using `Select-String` keeps everything in process and you are using the strings as they are. When you use `findstr` you are calling `findstr.exe` which is a native exe and PowerShell needs to encode that string to bytes in a way that `findstr` would understand.

If you really want to get `findstr.exe` working then you should set the following before you call it:

```powershell
$OutputEncoding = [Console]::OutputEncoding = [Console]::InputEncoding = [System.Text.UTF8Encoding]::new()
```

Breaking down here is what each of the 3 settings do

* `$OutputEncoding` 
  * Changes the encoding PowerShell encodes strings into raw bytes when it pipes data into a native exe
  * `"string" | native.exe` - `"string"` will be encoded to bytes with this setting
* `[Console]::OutputEncoding`
  * Changes the encoding PowerShell reads output stdout/stderr from a native exe
  * Also changes the console output codepage for native exe's to use when they write data out
  * $var = native.exe` - the output of `native.exe` is read with this encoding
* `[Console]::InputEncoding`
  * Changes the console input codepage for native exe's to use when they read data in stdin

By changing all 3 you change enough to be able to read and write strings using the UTF-8 encoding which can represent your characters. Even then this may or may not work depending on how `findstr.exe` actually reads the input data. If it ignores the value of the input and output console codepage then it just won't work. This is why using `Select-String` is far more preferable because you don't need to worry about it altogether.

**Comment by gool123456** [comment]
> 

Nice ! 

Thank you for your wonderful replies, it makes my work more convenient!
