### ISSUE TITLE
[UX] Enhanced Object Pretty Printing on Tiny TTYs

### ISSUE THREAD

**Issue by LePichu** [PowerShell/PowerShell#19235]
### Summary of the new feature / enhancement

Hello! I currently use PowerShell on all my systems including my phone but have a tiny complaint. The Terminal is about 60~ columns (Termux) which messes with the object pretty printing in Portait Display mode, however, as expected, it works fine in Landscape Display mode. I was wondering if there could be done to enhance the printing for displays like these.

![image](https://user-images.githubusercontent.com/62379502/221602101-db75a4aa-e2b9-4566-b633-468f9990b74c.png)
![image](https://user-images.githubusercontent.com/62379502/221602235-71619592-6b5f-44a3-bda4-f92042669509.png)

**Comment by 237dmitry** [comment]
you can select only the required columns:

```powershell
 > Get-Childitem $profile/.. | Select-Object Size, Name

Size Name
---- ----
4096 icons
4096 prompts
7600 CustomFormat.FileInfo.ps1xml
8192 CustomFormat.FileInfo.ps1xml.for7.2.7
1935 CustomFormat.MatchInfo.ps1xml
3134 functions.ps1
2201 Microsoft.PowerShell_profile.ps1
 151 powershell.config.json
2396 psstyle.ps1
```

**Comment by vexx32** [comment]
Aye, you can. That doesn't really make the default format here make more sense for narrower consoles though.

**Comment by gimbles** [comment]
You just..can't really fit all the information displayed in such a small display without removing information.

**Comment by vexx32** [comment]
Oh, absolutely, but I do think we need to make more intelligent decisions as to which columns are critical and which are not. I would say omitting the file/folder name column renders that display functionally entirely useless.

**Comment by SteveL-MSFT** [comment]
So PS formatting requires static column widths and it's a best guess by the format author what works best.  If it's too narrow, then some information will get truncated.  If it's too wide, you get lots of whitespace.  However, you can address this yourself by using:

```
dir | ft -a
```

Where `-a` happens to match `-autosize` which will calculate at runtime the minimal width based on some sampling.  The other option as noted above is to explicitly choose the columns you want.

**Comment by mklement0** [comment]
@SteveL-MSFT, to clarify re `Format-Table -AutoSize`:

>  will calculate at runtime the minimal width based on some sampling.

My understanding is the following:

* For output objects that DO have formatting data associated with them, such as `Get-ChildItem`'s (aka `dir`'s) output:
  * There's NO sampling, and there's NO adjusting of column widths.
  * However, inter-column whitespace is reduced to a _single space_.

* For output objects that do NOT have formatting data associated with them:
  * It isn't just _sampling_: ALL input objects are collected _up front_ in order to determine optimal column widths.
  * That is, to-display output doesn't start until then.

**Comment by jhoneill** [comment]
More proof that you can't please all the people all the time :-)  
Firstly I have a 280 column wide screen in front of me and I'd like more formats to use more of the space instead of confining themselves to the leftmost third. That would, obviously, make things worse for anyone working on a narrow screen 

Secondly only a few of the pretty-print formats use _auto-sized_ tables - because (as @mklement0  points out) autosize is _size to fit the widest data item_, and nothing is output until the last item is returned. Not good when recursing through a large file system looking for files which match a template.  If a directory has one file named   
`"file with a crazily long name much longer than is useful really but someone made it this way.txt"`  
autosize will make the "name" column 96 characters wide. As @SteveL-MSFT  says most of the formatting data has guesses by the author for how wide each column should be - with the important exception that something like name can have "all remaining" space.  These guesses CAN be refined but in practice changes are rare.

Thirdly to cope with very long file names the `system.io.fileInfo`  format is told to _wrap lines_. This means on a narrow screen the last column will often wrap - which is what we want for long file names, but becomes a nonsense on narrow screens because... 

Fourthly for pwsh on linux the aim has been to make files and directories look as similar to the output of `ls -l` as practical. This means including the `mode`, `user`, `group`, `last write time`, and `size` on the left of the row,  these columns are assigned 10,16,16,18,and 14 chars respectively, there is extra space after each so the N of `Name` is in column 80.  So on the OPs 60 column screen, name and size are squeezed off to the right and last-write time wraps.  Dynamically size user / group / size might help but this would be a mess with recursive directories.  A few characters could be shaved off size or date with clever formatting but the benefit is marginal. 

The answer is to define and load formats for specific types,  I posted a gist for a file info one last time this discussion came up

https://gist.github.com/jhoneill/4b74aa82cb5b4608687b24dddef293f8

A profile can then have 
```
if ( $host.ui.RawUI.WindowSize.Width -lt 100) { Update-FormatData -PrependPath myNarrowFormats.ps1xml}
```

It would be nice if there was a community effort to create and share such formats for different widths  :-)
