### ISSUE TITLE
Allow enabling experimental features via env var

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#19256]
### Summary of the new feature / enhancement

In CI, if someone wants to use an experimental feature, it currently is inconvenient to write to the `powershell.config.json` file before pwsh starts and then potentially set it back if the container instance is being reused.  Instead, it would be convenient to have pwsh also read from a env var like `POWERSHELL_EXPERIMENTAL_FEATURES` which is a comma separated list of the names of experimental features to enable.

The env var would override `powershell.config.json` for experimental features.

**Comment by iSazonov** [comment]
Maybe enhance Get-ExperimentalFeature cmdlet to generate the string for follow copy-paster.

**Comment by kilasuit** [comment]
I don't see a problem with this

**Comment by iSazonov** [comment]
Given the narrow purpose of this variable, I would suggest that it should be "hidden" with "__" prefix.

---

Once upon a time we breathed a sigh of relief when Registry appeared in Windows and replaced a huge number of configuration files and environment variables. The positive effect was terrific.
It's amazing to see that it's not being ported and there's not even a sign of it. :-(

**Comment by krokofant** [comment]
Is there any chance that this could make it to a release of PowerShell 7.2? I'm very curious about how an upgrade path will be laid out so that PowerShell won't break CI system when the `PSNativeCommandArgumentPassing` feature is enabled by default on CI systems like Github actions.

Being able to enable this feature on 7.2 via environment variable would make it easier to piece by piece migrate scripts to this feature...

**Comment by SteveL-MSFT** [comment]
@krokofant that's a good use case and something that could be considered since it's opt-in

**Comment by daxian-dbw** [comment]
> In CI, if someone wants to use an experimental feature, it currently is inconvenient to write to the powershell.config.json file before pwsh starts and then potentially set it back if the container instance is being reused.

Can you please provide an example to show how inconvenient it is today?

Take Az Pipeline as an example, every `-pwsh: |` step runs in a new `pwsh` process, so you can set experimental features at the first `-pwsh: |` step, then the `-pwsh: |` steps after that will run in the `pwsh` processes with that experimental feature enabled. In the end, the last `pwsh: |` step can restore the experimental features, so the build agent will still have the original experimental feature settings.

This doesn't seem very cumbersome to me ...

**Comment by SteveL-MSFT** [comment]
@daxian-dbw container images get reused sometimes w/o resetting them, so you would need to backup the existing config, if the config is modified, you may want to retain those settings, so you would need to modify the config file rather than clobber it, then restore everything back.  Certainly a worse case scenario, but this is exactly the scenario that was reported to me internally at Msft.

**Comment by JamesWTruher** [comment]
the WG discussed this and weren't quite clear on the scenario, so a little elaboration would be helpful. We also suggested that a parameter to pwsh might be just as effective and reduce the expansion of the environment. There is also a concern about being able to _remove_ the variable(s) from within PS (we _think_ that the way dotnet removes environment variables is to just set them to an empty string, so clearing them _from_ pwsh and then invokign might lead to ambiguity between no experimental features and use the standard config file.
If an environment variable approach was accepted, we also suggested that we should follow the `DOTNET_SettingNameHere` for each experimental feature (rather than a list)

**Comment by SteveL-MSFT** [comment]
A parameter on `pwsh` isn't as easily used in CI where `pwsh` is not called directly by the yaml.  Within PS, you'd remove them as any env var by setting it to `$null`, so not sure how it's different here.  Having individual env vars would be fine as well as long as experimental feature names don't allow for whitespace.

**Comment by JamesWTruher** [comment]
The @PowerShell/wg-powershell-engine discussed this again and before committing engineering effort on this, we would like to have a good discussion on _how_ this should work take place, especially with regard to interaction of environment variables with settings found in the `config.json` file. It has been an issue for us in the past, so having a discussion _before_ the engineering takes place of the behavior would be prudent.
