### ISSUE TITLE
[RFC] Structured data for non-built in commands

### ISSUE THREAD

**Issue by KoviRobi** [PowerShell/PowerShell#19259]
### Summary of the new feature / enhancement

Hi,

I am looking at coming up with a portable way to tell programs that they can output structured data, and telling the shell that the said data is structured according to the given format. For this I have a draft proposal write-up at https://github.com/KoviRobi/structured-shell-stdio but I would like some feedback. Especially as I don't have much experience with PowerShell or Windows, I come from a Linux/nushell background.  I don't know how well the file-descriptor idea could be applied to Windows, so please leave feedback either here or on the proposal.

Thanks,
Robert

### Proposed technical implementation details (optional)

A way to communicate to external programs that they can output JSON, and for the program to communicate to PowerShell that it is receiving JSON, without having to guess.

This should avoid having to define aliases for all the commands that support e.g. JSON, for example
```
ip --json addr | ConvertFrom-Json
```
could become just
```
ip addr
```

**Comment by rhubarb-geek-nz** [comment]
From your specification

> Tell the called program to output JSON
> Tell the shell that the output isn't just plain text but actually JSON

What it sounds like you really want is that the programs support the HTTP protocol over their stdin and stdout so that you can pass in headers like Content-Type and Accepts, and get Content-Type along with the response body.

Alternatively you could look at the [Common-Gateway-Interface](https://en.wikipedia.org/wiki/Common_Gateway_Interface) which uses environment variables to pass the same data.

> The program should ensure the file descriptor is valid at the start,

I am not sure what you mean by valid here. Unless you are running a suid program if you have the rights to read or write then you have the rights to read or write, that does not become an attack. If you fail to read or write then you terminate the program with an error as normal.

> I don't know how well the file-descriptor idea could be applied to Windows

Windows uses file handles rather than file descriptors. In order to share them with another process you normally use DuplicateHandle, including when using CreateProcess in order to indicate the permissions the other process has.

**Comment by rhubarb-geek-nz** [comment]
I would like to focus on the JSON_STDOUT environment variable in the POSIX environment. So assuming everyone has their first edition copy of UNIX Network Programming by W Richard Stevens we should be able to say that.

1. File descriptors, unless you do something (eg set CLOEXEC) are inherited by child processes.
2. Environment variables are also generally inherited, although it does depend on which form of exec you use.

So lets say we have a JSON_STDOUT aware shell, and it wants to use JSON everywhere so it passes JSON_STDOUT with a new pipe to every program that it runs in the hope that it returns JSON.

Those that do write the the JSON_STDOUT file descriptor work, and so do those that don't because the shell can tell the difference.

So the shell happily calls the updated program A which now writes JSON output to the shell. All well and good.

But the shell also calls program B which is not aware of JSON_STDOUT and does nothing with it, it writes its output to stdout. Shell is happy because it knows this is not JSON.

Now, program B uses program A. When program B forks then execs A, it will inherit the original JSON_OUTPUT and file-descriptor from the shell. So now program B no longer gets the output from program A, because program A is writing it to the shell using the pipe that was opened to get the JSON output of program B.

> This is to avoid potential attacks where an attacker will inject the JSON_STDOUT for a shell which doesn't support this

This is exactly what the JSON aware shell did, and now program B passed the JSON_STDOUT to program A because that's how the system works.

**Comment by SteveL-MSFT** [comment]
This is very timely as this is exactly a problem we've been thinking about and I was planning on publishing a proposal for this later this month.  I'll summarize the current thinking and it aligns with some of the thoughts you already have:

- The shell (PowerShell in this case, but can work with any shell) would have an env var called `SHELL_STDOUT_PREFERRED_OUTPUT` that commands would look for.  A value of `json` would tell the command to emit JSON without needing any switches/parameters.  We decided to keep this open ended rather than JSON specific.
- JSON emitted this way would be per line per object.  Any lines that are not valid JSON would be re-emitted to the pipeline as-is (same as it would work today w/o JSON).
- There is nothing in our proposal that is PowerShell specific as we hope other shells and commands adopt this idea

Given that there is other interest in this, I'll make it a priority to have a spec published by middle of this month.

**Comment by rhubarb-geek-nz** [comment]
> The shell (PowerShell in this case, but can work with any shell) would have an env var called `SHELL_STDOUT_PREFERRED_OUTPUT` that commands would look for. 

Wouldn't this have the same environment variable inheritance problem? A shell executes program B with SHELL_STDOUT_PREFERRED_OUTPUT, but program B does not know about SHELL_STDOUT_PREFERRED_OUTPUT and executes program A which does, then B will not get the format of data it used to get when SHELL_STDOUT_PREFERRED_OUTPUT is not set.

> A value of `json` would tell the command to emit JSON without needing any switches/parameters.  We decided to keep this open ended rather than JSON specific.

If the goal is to be open ended then I suggest using MIME types, eg application/json etc would be better.

**Comment by rhubarb-geek-nz** [comment]
As an example of a tool supporting something similar ( but not through environment variables )

[AWS CLI Output format](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-format)

It is an example of a configuring a default output format for when it is not specified on the command line. So this is a tool specific user/installation based default. The supported format as json, yaml, yaml-stream, text and table.

This actually suggests that if you want a reliable portable script you should always specify the format on the command line because any installation could have a different default output format.

**Comment by SteveL-MSFT** [comment]
@rhubarb-geek-nz in your `B->A` use case, that's no different than if A changes its text output and the regex used by B gets broken.  So if B is taking a dependency on A, it needs to be aware of the output.  And if JSON becomes the common output of command-line tools, then it's better for B because it structured than text.

The AWS solution is application specific and also requires the user to manage it which is not ideal for adoption.  Outside of PowerShell, tools like `jq` is already gaining some popularity for tools that can emit JSON.  The difference here is how to inform tools to do it by default.

Reliable scripts already have a problem today if the version of the tool changes and the text output changes.  I understand the transition challenges for tooling expectations of moving from text to JSON, but scripts can also unset that env var.

**Comment by iSazonov** [comment]
> @rhubarb-geek-nz in your `B->A` use case, that's no different than if A changes its text output and the regex used by B gets broken. So if B is taking a dependency on A, it needs to be aware of the output. And if JSON becomes the common output of command-line tools, then it's better for B because it structured than text.

This reminds me of the `PSModulePath` story. A lot of headaches as it was and still is. (If we also assume a utility that hosts PowerShell...)

> Reliable scripts already have a problem today if the version of the tool changes and the text output changes.

I'll remind you of that again [#13428 ](https://github.com/PowerShell/PowerShell/issues/13428)
Users accept and use ready-made things with simple and clear concepts but ignore what takes effort to understand and implement.
For PowerShell to work fully, it needs meta-information which is missing from native apps. This information is best provided in PowerShell concepts. I would suggest the `PowerShell SDK for native apps` so that developers can replace Console.Write() with PSNativeSDK.WriteSerializedPSObject(). (And it doesn't matter if it's XML or Json or whatever.) Without that, you need a PowerShell-inspired wrapper, and a processing type - PSNativeCmdlet. In particular it allows us to specify output parsers for any version-aware utility.

**Comment by SteveL-MSFT** [comment]
@iSazonov requiring a SDK means that tools will have to develop for a specific shell which would impact adoption completely.  Also, `PSModulePath` has specific problems because it's not treated as a pure env var and the host does manipulation to it assuming what the user wanted.

**Comment by iSazonov** [comment]
> Also, `PSModulePath` has specific problems because it's not treated as a pure env var and the host does manipulation to it assuming what the user wanted.

My thought is that there may be a chain/loop of applications that can change the variable.

> @iSazonov requiring a SDK means that tools will have to develop for a specific shell which would impact adoption completely.

There is no other way to do clever things in the shell than to use meta-information. PowerShell has it, but native apps don't. For years there has been a need for native apps to do the same (on all OS-s). They do it either in an application-specific way by reinventing the wheel every time or through specific third party projects which are very limited in scope. 
Where does that leave us? Offer simple and clear templates for PowerShell integration.
It seems that in Windows, almost all utilities are already translated to managed code. That is, there is essentially one step left to make them provide the meta-information PowerShell needs in a standard form.
If MSFT is not willing to do this, then any other approach will suffer the same oblivion.

**Comment by rhubarb-geek-nz** [comment]
> in your `B->A` use case, that's no different than if A changes its text output and the regex used by B gets broken. So if B is taking a dependency on A, it needs to be aware of the output. 

Which is why we don't do it. The UNIX/POSIX/Linux command line tools are incredibly conservative and resistant to change precisely to prevent breaking other scripts. Extensions are typically enabled explicitly by command line options if the output will change.

> And if JSON becomes the common output of command-line tools, then it's better for B because it structured than text.

JSON is good for somethings but it is not the solution to everything. Being simple means it is easy to parse, but likewise has no conventions for dates, for how to include binary data. It has no schema mechanism to validate that all data are present and has no standard for digital signatures to ensure integrity. It is not good for continuous streaming.

> The difference here is how to inform tools to do it by default.

Unfortunately the mechanisms that have been presented are fundamentally flawed. It means the behaviour of the programs will change depending on the environment variable and any application or script that does not handle that environment variable will break. If I have a script C that behaves one way when it is invoked by bash but a different way when invoked by some json-shell then I now have an unreliable script.

> I understand the transition challenges for tooling expectations of moving from text to JSON, but scripts can also unset that env var.

So your proposal is that every program that already optionally supports JSON has to recognise this environment variable, and every other batch file, shell script, Python/Perl/C/C++/PLI/Pascal/Cobol program that already uses those first set of programs has to be modified and/or recompiled? That isn't "tooling expectations" that is "breaking entire ecosystems".

As it is, it is more likely to be a case of "everything breaks when I try to run it with json-shell therefore I won't use json-shell".

The cost of not doing this is just having to use existing programs command line options to select JSON output. The cost of implementing this is chaos.

**Comment by rhubarb-geek-nz** [comment]
> I understand the transition challenges for tooling expectations of moving from text to JSON

I am going the play the Devil's Advocate and challenge the idea that using structured data is automatically better.

Although this example is XML rather than JSON, the principles are the same, and it should look pretty familiar.

[SQLite.Interop.Static.2017.vcxproj](https://system.data.sqlite.org/index.html/file?name=SQLite.Interop/SQLite.Interop.Static.2017.vcxproj)

So that's a Visual Studio project file, it describes a project, how to build it and the various compiler options. It looks fairly modern, as far as I can tell it's the most recent in the file set. It is for Visual Studio 2017 and builds both x86 and x64.

Let's have a look at the equivalent Makefile.

[SQLite.Interop.mak](https://github.com/rhubarb-geek-nz/SQLite.Interop-win/blob/main/SQLite.Interop.mak)

So that looks like it comes from the 1980s, it does not cater for all the build scenarios in the Visual Studio project and looks pretty primitive.

So why bring that up and what has it got to do with PowerShell anyway?

[This](https://github.com/rhubarb-geek-nz/SQLite.Interop-win/blob/main/package.ps1)

This is a PowerShell script that downloads the source, validates it, patches the source and builds four architectures; x86, x64, arm32 and arm64 using Visual Studio 2022 and the simple makefile.

In my opinion the purpose of PowerShell is to orchestrate new and existing tools to solve problems, not demand that all programs change in order to somehow become simpler to use with PowerShell.

**Comment by rhubarb-geek-nz** [comment]
> Tell the shell that the output isn't just plain text but actually JSON

> `SHELL_STDOUT_PREFERRED_OUTPUT` 

The first proposal suggests that it handles both original format and JSON, the second proposal use the term `preferred` which suggests this is optional. What is the behaviour of the shell if the output is not JSON?

If we revisit our good friend the AWS CLI tool ...

```
$ aws --output xml apigateway get-rest-apis
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --output: Invalid choice, valid choices are:

json                                     | text                                    
table                             
```

It is explicit and fails if you ask for a format it does not understand. Do you have to handle multiple formats for each output?

**Comment by KoviRobi** [comment]
First of all, thank you for your interesting points, I want to make it clear that a discussion is what I am after, rather than my solution already being a fully formed one :)

> With stdin/stdout there is nothing that says it plain text at all, they are normally byte streams.

Yeah I agree I phrased it badly, I didn't mean to say it's printable characters/7-bit clean etc, I just meant that usually CLI programs output information for human consumption, which is why the line-oriented format is so pervasive I think, as it's a compromise between human readable, but also for some simple cases not too difficult to manipulate by `grep`/`sed`/`awk` etc.

I also value the mime-type suggestion, I chose JSON because it's output by a fair few of the programs I happen use, but there's downsides to JSON too, plus if you allow me a bit of a segue the other day I was just wanting to transfer a public SSH key to my phone, for which qr-codes should be fine, in fact you can even get phone virtual keyboards that support that, but on the other side, in the shell while I can run `qrencode 'Hello, world!' -o -` it just dumps out a PNG, instead of having something that can be displayed, though
<details>
<summary>❯ qrencode 'Hello, world!' -o - -t utf8</summary>

```
█████████████████████████████
█████████████████████████████
████ ▄▄▄▄▄ █▀▀ ▄ █ ▄▄▄▄▄ ████
████ █   █ █▀▀▄▄ █ █   █ ████
████ █▄▄▄█ █▀▄█▀▄█ █▄▄▄█ ████
████▄▄▄▄▄▄▄█▄▀▄█▄█▄▄▄▄▄▄▄████
████ ▄▄▄ ▀▄▄ █▀▄▀ █▄▀ ▀▄▀████
████▄ ▀▄▄▀▄▀ █▄▀  ▄▀█  ▄█████
██████▄▄▄▄▄█ ▀██▄▀  ▀▀██▄████
████ ▄▄▄▄▄ █▄▀██  ▄ █▀  █████
████ █   █ █ ▀ ▄▄▄▄▀ ▀█▄▄████
████ █▄▄▄█ █ ▀▀▄ ▀▄▄▀▀ ██████
████▄▄▄▄▄▄▄█▄▄█▄██▄█▄██▄█████
█████████████████████████████
█████████████████████████████
```

</details>
does kind of work. But this got me thinking more about what I am after, which is an ability to have smarter terminals/shells that support graphs, images, structured data etc. Kind of like jupyter notebooks I guess, so I should look into how they work too.

Given this, I think I need a better name than structured data, any suggestions.

The comment about A -> B -> C where A and C support this protocol, B doesn't, is very insightful and shows a fundamental weakness, thank you! In my mind, it was only using it as an extra output channel, but even with that it has a problem. Just to translate it to my words, this is bad because supposing you do PowerShell -> bash -> C (where the bash -> C could be just due to running a bash script, e.g. bash gets run transparently due to the shebang), then all the information of your bash script will leak into your powershell which is the very least undesirable, especially if the script C produces a lot of output. For normal shells this would just get lost in the shell history, but the behaviour here could be out of memory which is bad.

I think the SDK could be a good solution, I raised the environment variable as one that I could think of but it is not necessarily the way forward and for me the discussion of that does fall under all of this/the structured shell stdio. I think for the SDK important points are

- portable across systems -- different SDKs for different systems is fine I imagine, as you have different executables anyway
- portable across shells within the same system -- it would be mad to have several different executables depending on the shell, e.g. iproute2-ps and iproute2-nu would just make systems a bit broken. I think this is doable though, I am only envisioning this communication to the calling shell, so the SDK could perhaps just look that up in the process hierarchy?
- small/fast, as I imagine people will only use it if this is the case
- reasonably easy to use for the software/external commands wanting to output more than just byte-streams of unknown data. Of course software will have to have changes to support this, and existing software shouldn't be broken if it doesn't, otherwise we cause chaos. I guess I want the software making use of this SDK to not have much more difficulty than just adding a `--json` flag (or whatever, JSON is just on the tip of my tongue but XML, or SQLite etc work) and then outputting that to stdout (probably via some deserialisation code).

And in some way I wanted to go towards the SDK solution even with my env. var solution, I just thought of it as consistent and easy to use, but if the SDK abstracts away all the platform/shell dependencies then that's grand

So I guess any ideas about how this SDK might work? I don't know how well the discovering parent process to see if it supports this channel works, but I guess it avoids the A->B->C problem as in this case C's parent process is B not A. And if we do want to create a child process C that does structured outputting all the way back to A, then we need to do some extra steps (hopefully small) to do this, which is the right way around, in that defaults should do existing behaviour.

Also apologies for my delayed response, and tendency to ramble, this is a highly speculative side project so I don't always have time for this, and when I do it's often in the evening when I'm a bit lower on energy so my inner editor isn't here to cut things down

**Comment by KoviRobi** [comment]
> Going back to CGI, the HTTP Accept header is more than a suggestion, if a server can't provide what is requested then it would return 406 Not Acceptable.

I've been trying to understand how CGI is applicable, in some ways I see the superficial similarities, but to my understanding CGI is mostly a way to just pass HTTP query parameters, and it expects the output to be HTML?

I guess environment variables would have the same A->B->C problem.

And it wouldn't solve the second part of the communication, communicating back to the shell that the data is more than just a byte-stream? I think CGI has the expectation that every command outputs HTTP, here as you pointed out we cannot be sure there is more to the outputs than byte-streams, some way of communicating back to the shell would be much better than just guessing/libmagic.

**Comment by rhubarb-geek-nz** [comment]
> but to my understanding CGI is mostly a way to just pass HTTP query parameters, and it expects the output to be HTML?

Far from it! With CGI you can implement any HTTP verb and can return any format of data. Its response is a set of headers and the body.

**Comment by SteveL-MSFT** [comment]
| I am going to play the Devil's Advocate and challenge the idea that using structured data is automatically better or necessary.

It's not necessary in that PowerShell already works with non-structured output today already.  However, structured data (whether XML, JSON, or something else) means you can get better discovery (a la `Get-Member`) and consistent access (a la dot-notation).  You can already see this via `ConvertFrom-Json` or using `[xml]` accelerator.

| What is the behaviour of the shell if the output is not JSON?

This was described above in that it behaves like it does today.  By having JSON per line, it's easy to detect if it's valid JSON or not.  Commands that emit JSON via something like `--json` tend to emit pretty print JSON so wouldn't be treated as JSON for the purpose of this discussion.

Also, this behavior would be opt-in (whether via the env var or other means) so existing scripts continue to work as they do today.

| If the goal is to be open ended then I suggest using MIME types, eg application/json etc would be better.

The goal is to standardize on JSON, but allow for other types to be more future proof.  Supporting literal MIME types I think can lead to misunderstanding of what is actually supported.

**Comment by rhubarb-geek-nz** [comment]
> This was described above in that it behaves like it does today. By having JSON per line, it's easy to detect if it's valid JSON or not. Commands that emit JSON via something like `--json` tend to emit pretty print JSON so wouldn't be treated as JSON for the purpose of this discussion.

So the idea is to standardise on JSON by using "JSON per line" which isn't JSON, and existing tools which already support JSON output wouldn't be counted as JSON. 

So an existing tool that uses "JSON per line" but writes just one line, wouldn't be counted as JSON because it is identical to JSON?

**Comment by SteveL-MSFT** [comment]
I've have a spec posted here that includes a proposal for structured data for native commands: https://github.com/PowerShell/PowerShell-RFC/pull/348/files
