### ISSUE TITLE
Is DotNet issue https://github.com/dotnet/runtime/pull/78106 included in the current PowerShell-core and what version?

### ISSUE THREAD

**Issue by MrPippin66** [PowerShell/PowerShell#19285]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

https://github.com/dotnet/runtime/pull/78106 was commit-ed end of last year to resolve a sticky bit issue for /tmp/.dotnet.

Has this been integrated into the current PowerShell-core package, and if so, what's the package version?

### Expected behavior

```console
N/A
```

### Actual behavior

```console
N/A
```

### Error details

```console
N/A
```

### Environment data

```powershell
N/A
```

### Visuals

N/A

**Comment by mklement0** [comment]
Generally speaking:

* Your question is _which specific .NET version_ includes the linked fix.
  * I don't have a definitive answer, but given that the [linked PR](https://github.com/dotnet/runtime/pull/78106) states `8.0.0` under `Milestone` in the sidebar on the right, it sounds like you'll have to wait until _.NET 8.0_ is released.

* On the PowerShell side, in a given version's session, use `[System.Runtime.InteropServices.RuntimeInformation]::FrameworkDescription` to see what .NET version that PowerShell version is based on.
   * Making this information more easily discoverable is the subject of the following proposal:
     * #19121

I don't know if there's an official policy as to how .NET releases are integrated into PowerShell releases, but if there is such a policy, it would be good to know, and especially good to know where it is _documented_.

**Comment by mklement0** [comment]
Per https://learn.microsoft.com/en-us/powershell/scripting/install/PowerShell-Support-Lifecycle?view=powershell-7.3:

* PowerShell LTS releases are built on .NET LTS releases, and their support periods align.
  * Currently PowerShell 7.2.x is the LTS release, built on top of .NET 6.0.x

* As for the most recent _stable_ / _preview_ releases: from what I can tell, they are based on whatever the most recent _stable_ .NET version is at the time.

**Comment by MrPippin66** [comment]
Okay, FYI, this was also fixed toward the end of 2022 in V6 and V7 of DotNet.

https://github.com/dotnet/runtime/pull/78057
https://github.com/dotnet/runtime/pull/78051

So I think my original question remains of if this has been integrated in to the current PowerShell release, or when it can be expected.

**Comment by iSazonov** [comment]
Next pwsh release will be immediately after .Net 8 release.

**Comment by mklement0** [comment]
@MrPippin66, in combination with the information provided above, it sounds like you've answered your own question:

* 7.2.x is the LTS version and the oldest version that is still supported. The latest 7.2.x version is 7.2.10.
* 7.2.10 is built on .NET 6.0.14
* 7.3+ versions are built on .NET 7.0.x

Since you've discovered yourself that the fix in question was back-ported to .NET 6.0 and 7.0, it must be present in all currently supported PowerShell versions.

**Comment by MrPippin66** [comment]
This seems odd. Latest version of PowerShell core for RHEL7 is 7.3.3-1.

Installing that and showing the dotnet release is:

.NET 7.0.3

It's odd, since the latest V7 release on githhub shows 7.0.2, which is supposed to be covered by this fix.

But...the behavior I need resolved (sticky bit not being set on /tmp/.dotnet when the file is initially created) still shows sticky bit not being set.

**Comment by mklement0** [comment]
> It's odd, since the latest V7 release on githhub shows 7.0.2

Yes, that is indeed odd, given that the official download page shows 7.0.3 as of this writing: https://dotnet.microsoft.com/en-us/download

As far as I'm aware, PowerShell incorporates a given .NET release _as-is_, 
so if you find that such a release doesn't include a fix you expected to be there - and you can verify that with a C# application, for instance - I encourage you to raise the issue at https://github.com/dotnet/runtime/issues

Conversely, if you find that something is verifiably fixed in a given .NET version using a C# application, yet the PowerShell version built on that same version does _not_ appear to include the fix, further investigation _here_ is warranted.
