### ISSUE TITLE
any release builds for Win 7?

### ISSUE THREAD

**Issue by evandrix** [PowerShell/PowerShell#1931]
more specifically, Windows 7 Enterprise x64 v6.1 (Build 7601: SP1)

**Comment by kilasuit** [comment]
@evandrix - I believe that the reason for there not being a current build for win7 would be for similar reasons to why to install WMF5 (aka PowerShell v5) requires WMF (& PowerShell v4) installed beforehand.

That said I'm clutching at a straw with that response so hopefully someone else can respond with more details in due course

**Comment by mirichmo** [comment]
@evandrix See #1705. We'd like to produce PowerShell Core for all supported versions of Windows (Win7+), but have a few remaining issues with our packages for Win 7 and Win 8. The fix, once identified, is potentially something that we could include in Alpha.10.

As @kilasuit mentioned, you will need to install a WMF to get PowerShell Core to work as expected on Win 7. Between Win 7 and Win 8, significant changes were made to WMI and WinRM (PowerShell dependencies) that make some form of WMF a pre-requisite. 

I am closing this issue because we already have #1705 to track Win 7 support.
