### ISSUE TITLE
Make "CTRL+ARROW" stops configurable

### ISSUE THREAD

**Issue by onionhammer** [PowerShell/PowerShell#19310]
### Summary of the new feature / enhancement

Currently when you hit ctrl+left arrow (for example), it will move your cursor back by word, stopping at spaces, periods, quotes, etc, but not other symbols like tilda (~).

It would be nice to add support for stopping at additional chars, and make those chars configurable in your powershell profile.

Example of usecase:

```pwsh
> dotnet test --filter FullyQualifiedName~Some.Namespace.ToMyTest|
```

if my cursor is at the end, and I press CTRL+LEFTARROW twice, the cursor will be at `Some.|`, if I press it one more time it will be at `--filter `

THIS behavior differs from bash and chrome and VS Code, etc, which stops at the tilda (~), and feels unnatural

**Comment by jhoneill** [comment]
In my profile I have 
```
Set-PSReadlineOption -BellStyle None  -EditMode Windows -WordDelimiters "`~!£#%^&*()=+[{]}\|;:'`",.<>/?"
```
Which does what you want.  It's a constant annoyance that these change from place to place. Fortunately Windows Terminal and VS Code have similar settings so I'm able to have the same ones everywhere.  Note that **I don't** want $ to be break so that I get a $VarName as one block. **You may** so adjust accordingly.   (Similarly you may not want to force linux pwsh into working like windows, or the mute the bell sound as I do !)

**Comment by onionhammer** [comment]
@jhoneill thank you I didnt know about that option
