### ISSUE TITLE
PowerShell should have a way to download and process XML documentation for .NET types and methods

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#19314]
### Summary of the new feature / enhancement

As a user I want to be able to use .NET methods and types without having to look up documentation online.  
I want to be able to view the XML help when I use `Get-Member` to look at a type.  
I want to be able to view the XML help in the tooltip when I'm completing a type or member.

### Proposed technical implementation details (optional)

Either `Update-Help` should be updated to also download XML documentation for all the types available in PowerShell, and installed modules or a new command should be introduced that does this.  
If the documentation is available on the machine then `Get-Member` and tab completion should use it to provide additional info to the user.  
PowerShell classes should support both comment based help, and of course external XML help files (I think there's already an issue about Comment based help for classes).

**Comment by SteveL-MSFT** [comment]
The request would be useful, but I can see this being challenging to implement particularly if trying to use the xml help contained within a nupkg as first you'd have to map the API to a nupkg and then extract the xml.  It's unlikely we can get them to publish the xml separately that can be downloaded particularly since the user can use arbitrary .NET APIs including ones not owned by the dotnet team.

**Comment by dwtaber** [comment]
As a (hopefully) more feasible starting point, how about limiting the scope to classes defined in [dotnet-api-docs](https://github.com/dotnet/dotnet-api-docs)?
