### ISSUE TITLE
Add a switch parameter to Import-Csv and ConvertFrom-Csv to allow auto-generating headers (column names)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#19334]
### Summary of the new feature / enhancement

`Import-Csv` and `ConvertFrom-Csv` support a `-Header` parameter that allows you to supply headers (column names) _explicitly_, but doing so requires you to at least know the number of columns ahead of time.

It would be convenient if there were a way to generate column names _automatically_, based on the number of fields encountered in the first input row, <del>based on the same naming scheme that is already used when _empty_ header fields are encountered in CSV input (that is, `H` followed by a `1`-based sequence number - `H1`, H2`, ...)</del> On second thought: simply using a `1`-based sequence number _alone_ makes for easier processing later.

That way, you can easily parse arbitrary CSV files that lack a header row without needing to manually construct headers for them; it would be the equivalent of what Python's popular pandas library already supports (`pandas.read_csv('yourFile.csv',  header=None)`

This not only makes supplying headers much more convenient, but also works in case where the column count isn't known in advance, and where you may need to extract field values by column position or iterate over _all_ field values.

### Proposed technical implementation details (optional)

Introduce a new switch, say `-AutoHeader`, that implements the above:

```powershell
# Sample CSV data without a header row
$csv = 
  @'
r1c1,r1c2 
r2c1,r2c2
'@ -split '\r?\n'

# WISHFUL THINKING
$csv | ConvertFrom-Csv -AutoHeader
```

Output - note the auto-generated column names (headers), `1` and `2`:
```csv
1    2
-    -
r1c1 r1c2
r2c1 r2c2
```

That is, the command above would be the equivalent of the following, cumbersome approach that is currently required (this isn't fully robust - a robust solution would be even more cumbersome):

```powershell
$csv = 
  @'
r1c1,r1c2
r2c1,r2c2
'@ -split '\r?\n'

# Infer the count of columns from the first data row...
$colCount = ($csv[0] -split ',').Count
# ... and construct headers for all columns.
$headers = 1..$colCount

$csv | ConvertFrom-Csv -Header $headers
```

**Comment by jhoneill** [comment]
@mklement0  it's late here and my brain might be a bit befuddled. But I'm trying to see how this is really useful 

Today I can copy some rows from Excel and do 
```
$x = Get-Clipboard | ConvertFrom-Csv -Delimiter "`t" -Header Id, Added, Title
```
and then refer to `.Id` `.Added` and/or `.Title` properties. 

What you're saying seems to be that you'd like to be able to do 
```
$x = Get-Clipboard | ConvertFrom-Csv -Delimiter "`t" -autoheader 
```
and then remember that H0 is ID, H1 is Added and H2 is title. In a script that seems to be giving you way to write things in a worse way :-) 

If there are extra columns or I just do ` -Header Id, Added`  I just get the first _n_ If I specify `-Header Id, Added, title, author` and there are only three columns the extra one is null. 
If I don't know what is in each column and need to find out before writing meaningful names I can do 
```Get-Clipboard | ConvertFrom-Csv -Delimiter "`t" -Header @(1..10) | ft -a``` and have 7 empty columns. All this seems to do is handle that case more tidily.

**Comment by mklement0** [comment]
@jhoneill:

Using _just_  sequence numbers as the column headers makes perfect sense, as it makes later processing easier - both for direct access by known column indices and for iterating over all columns, so I've updated the initial post accordingly.

The gist of this proposal is: 

* Don't make me have to specify headers explicitly if I don't care what they are, especially if I don't know how many columns there are.

* The are two reasons I may not care:
  * I know what columns I want to access by *position* rather than by name.
  * I don't now the number of columns and/or their content, but I want to explore them programmatically.

`-Header (1..$n)` may work for the first use case - but is awkward -  and doesn't work for the second one (if you guess too low, data will be missing, if you guess too high, there'll be phantom columns; and `-Header (1..([int]::MaxValue-56))` will grind your session to a halt (assuming you even know the magic number to subtract you can even _submit_ the command)).

**Comment by jhoneill** [comment]
> As with any convenience feature, there _is_ a way to do it differently, but the appeal of the feature is to offer _concision_ and _semantic directness_: it provides a direct expression of the user's intent, which in this case is:
> 
> * Parse this data into objects, using sequence numbers as property names, because I don't know / don't care about symbolic property names.
>   
>   * So the answer to "Wouldn't we always tell people to work with the latter (symbolic names)?" is: no.

I don't think there is any such case . My example with ID, added and title , we might not know the names originally used and we might not care if we refer to columns as "Identity", "Creation Date" and "Name" but to do anything useful we need to know what data is in columns 1,2 and 3 

Someone gave the advice to write code "as if it will be maintained by an axe wielding maniac who knows where you live". I think passing that test depends on giving things sensible names. You can name your variable $v1, $v2 , $v3, $v4 but you don't (I hope) because you know what is in them and you want it to be clear to anyone maintaining the code (I use talk about fixing one's own code, late at night when everything is on fire.).  It's really only the exploring phase where it works. Import fails because the same value appears twice in the first row so you want to have a look at the data to decide what the names should be in the script you're trying to write, and splitting or a opening in something else might be inconvenient compared with a command line exploration. 


> * Not that we necessarily need to follow the lead of other languages / libraries, but the fact that the popular [pandas](https://pandas.pydata.org/pandas-docs/stable/index.html) Python library offers this feature is an indication that there is demand for it.

Yeah, I've just been in another conversation which went "We should not do X in invoke-webrequest, because curl doesn't", and the response was "curl is out of date on this".  I don't know if pandas has it because there was detailed research which showed demand for obfuscated columns, or whether it just seemed like a good idea to a programmer at the time.  We actually do it in `Import-Excel`  I fairly sure Doug Finke implemented that before I was involved. I've never used it, so my natural assumption is no ever uses it. 

 

> * Get the _last_  column (among an unknown number of  columns)

Well OK, if it's a log file that writes Date, ID {some random other columns}, machine name, you might want 0,1 (or 1,2) and Last.  and really we'd want something which gave a 2D array so we could refer to $data[$row][0,1,-1] instead of an array of objects. But I think knowing you want the last column but not how many columns there are is very much a corner case. 

I'll float it with the working group. Notwithstanding my advice not to use numbers for property names it may end up as "up for grabs" rather than a flat no, but I'd be surprised if it got allocated time from the team.
