### ISSUE TITLE
Get the location from context shell in predictors 

### ISSUE THREAD

**Issue by Ashijo** [PowerShell/PowerShell#19391]
### Summary of the new feature / enhancement

Hello 

Having play with [predictors](https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/create-cmdline-predictor?view=powershell-7.3) I feel the need for a new feature.

It seems actually impossible to get the location of the shell calling the predictor, which is very limiting considering how useful it could be.
As an example, if I had the location, I could easily create a predictor suggesting the local git branches after ```git checkout```

### Proposed technical implementation details (optional)

IMO this value should be present in the PredictionClient, or at least I should have access to the PID of the shell. (client.Name only return PSReadLine) 

How exactly do that ? No idea ^^, But I think it would be a change somewhere in PSReadLine

**Comment by SeeminglyScience** [comment]
> It seems actually impossible to get the location of the shell calling the predictor, which is very limiting considering how useful it could be.

It's by design that the predictors do not have access to runspace state. Runspace state is thread based, and for UX predictors must return within ~20ms or their results are not used.

> As an example, if I had the location, I could easily create a predictor suggesting the local git branches after git checkout

I believe you'll have a hard time meeting the 20ms timeout for just about any git command atm. Some stuff like this will be a little bit more possible once async rendering is implemented for predictors. That work is tracked in PowerShell/PSReadLine#3581

> IMO this value should be present in the PredictionClient, or at least I should have access to the PID of the shell. (client.Name only return PSReadLine)

It's not run out of process, so `Environment.ProcessId` will give you the process ID (as your PID will be the same as the shell's)

---

@daxian-dbw feel free to correct me if any of that is incorrect

**Comment by daxian-dbw** [comment]
That's correct. However, you can always get the current working directory of the PowerShell session within your predictor, by syncing with the state of the default PowerShell Runspace.

Check out the `CompletionPredictor` as an example (see the [RegisterEvents](https://github.com/PowerShell/CompletionPredictor/blob/main/src/CompletionPredictor.cs#L32) call), it syncs almost all the states from the default PowerShell session. The same pattern is also used by the `DirectoryPredictor` (see code [here](https://github.com/Ink230/DirectoryPredictor/blob/main/DirectoryPredictor/DirectoryPredictor.cs#L21) and [here](https://github.com/Ink230/DirectoryPredictor/blob/main/DirectoryPredictor/DirectoryPredictorStateSync.cs#L8)) -- it only syncs the current location, which is more aligned with what you need here. For your scenario, you don't need a local Runspace, so you just need to update a local variable to store the latest current working directory.

> I believe you'll have a hard time meeting the 20ms timeout for just about any git command atm.

Right, but for `git`, you can inspect the `.git` folder to get lots of information without needing to invoking the `git` command. For example, you can get the available branches from `.git\refs\heads`. By doing this with the right amount of caching, you should be able to have the predictor work well with the 20ms timeout restriction.

**Comment by daxian-dbw** [comment]
I thought more about this ask, and agree it's probably the right thing to add the current path information, and `PredictionClient` sounds to be the right place for this information since the host should know what the current location is, and whether it's interacting with a local Runspace or a remote Runspace.

So, reopening this issue.
