### ISSUE TITLE
Get-ChildItem and piped rename-item result in iterative renaming 

### ISSUE THREAD

**Issue by PHuhn** [PowerShell/PowerShell#19426]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am trying to rename all files in a directory.  This directory has 99 files in it.  Create an empty folder.  Then the following will create the files:
```
for($i=1; $i -lt 100; $i++) {
  Write-Output $i
  $s = "$i"
  if( $i -lt 10 ) { $s = "0$i" }
  New-Item "$s File $s.mp3" -type file
}
```
After creating files in a folder execute the following command:

```
Get-ChildItem -Path . -file | rename-item -NewName {"Pre $_"}
```

### Expected behavior

```console
I would expect the new file name would be as follows:

Pre 01 File 01.mp3
```
```


### Actual behavior

```console
Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre Pre 01 File 01.mp3
```

### Error details

```console
rename-item : The specified path, file name, or both are too long. The fully qualified file name must be less than 260
characters, and the directory name must be less than 248 characters.
At line:1 char:31
+ Get-ChildItem -Path . -file | rename-item -NewName {"Pre $_"}
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Rename-Item], PathTooLongException
    + FullyQualifiedErrorId : System.IO.PathTooLongException,Microsoft.PowerShell.Commands.RenameItemCommand
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by jhoneill** [comment]
This does not seem to happen on PowerShell 7.3. I notice your version says you are using windows PowerShell 5.1
On the latest released version. `rename-item -NewName {"Pre $_"}` - as shown above - gives an error because $_ is the path not the file name and the new name is trying to be `Pre C:\Temp\test\Pre 01 File 01.mp3` .  Using  `{"Pre $($_.name)"} ` works. as expected


I have used `Get-ChildItem  [something] | ren -new {$_.name -replace [old] [new]} `    
Since PowerShell 1 without hitting this problem. 
If `Get-ChildItem` _is_ finding the renamed Item and passing it down the pipeline -which might not happen in all circumstances - then I have been preventing that behaviour with the file selections I have been making, but I'm fairly sure I have done _get * / replace "IMG","Paris"_ on a folder with hundreds of files. 

Since the problem (I would class it as a bug but it might be by design, or some paging in .NET that PowerShell can't control) seems to be fixed in current PowerShell it's unlikely you'll see any change in PowerShell 5 as that is pretty much frozen except for security issues 

`Get-ChildItem -File * -Exclude "pre*"  | rename-item` 

gives a workaround

**Comment by PHuhn** [comment]
Hey:
I tried it and it doesn't appear to work the same:
> Get-ChildItem -Path . -file | rename-item -NewName {"Pre $_"}Rename-Item: Cannot rename the specified target, because it represents a path or device name.
Stack overflow hasn't helped yet!
Phil==============  Phil Huhn(734) 545-5845============== 

    On Thursday, March 30, 2023 at 08:20:58 AM EDT, Phil Huhn ***@***.***> wrote:  
 
 Hey:
I will attempt ps7.  The rename-item mostly worked for me also, but something about this command went very wrong.  Some edge case!
Phil==============  Phil Huhn(734) 545-5845============== 

    On Thursday, March 30, 2023 at 06:23:33 AM EDT, jhoneill ***@***.***> wrote:  
 
 


This does not seem to happen on PowerShell 7.3. I notice your version says you are using windows PowerShell 5.1
On the latest released version. rename-item -NewName {"Pre $_"} - as shown above - gives an error because $_ is the path not the file name and the new name is trying to be Pre C:\Temp\test\Pre 01 File 01.mp3 . Using {"Pre $($_.name)"}  works. as expected

I have used Get-ChildItem [something] | ren -new {$_.name -replace [old] [new]} 
Since PowerShell 1 without hitting this problem.
If Get-ChildItem is finding the renamed Item and passing it down the pipeline -which might not happen in all circumstances - then I have been preventing that behaviour with the file selections I have been making, but I'm fairly sure I have done get * / replace "IMG","Paris" on a folder with hundreds of files.

Since the problem (I would class it as a bug but it might be by design, or some paging in .NET that PowerShell can't control) seems to be fixed in current PowerShell it's unlikely you'll see any change in PowerShell 5 as that is pretty much frozen except for security issues

Get-ChildItem -File * -Exclude "pre*" | rename-item

gives a workaround

**Comment by StevenBucher98** [comment]
@PHuhn can you try this command `Get-ChildItem -File *.mp3 | Rename-Item -NewName {"Pre $($_.Name)"}`

**Comment by PHuhn** [comment]
I did the following:
```
Get-ChildItem -Path . -file | Select-Object -ExpandProperty Name | rename-item -NewName {"Pre $_"}
```
