### ISSUE TITLE
GUI progress bar when Deleting a folder in Powershell

### ISSUE THREAD

**Issue by jeeveshlodhi** [PowerShell/PowerShell#19538]
### Summary of the new feature / enhancement

It would be good to have a slider of some GUI element when using the command

` remove-item <directory_name> -recurse -force`

I was trying to delete a directory from PowerShell and it does not show how much the process is done or how much time it will take to complete.

If we had this feature it would be more convenient to delete a file as we would know its progress.

**Comment by kasini3000** [comment]
wpf     https://www.powershellgallery.com/packages/PoshProgressBar
or
[system.Console]::title = '57 %'  # deleted  / all

**Comment by jhoneill** [comment]
As a basic principle operations that take more than a couple of seconds _should_ give the user some idea that a long running operation is taking place. 

However writing anything to the console - including progress - or updating a GUI dialog is a slow operation, and taking 2 seconds to do an operation _with_ progress rather than 1 second without is a net loss.  

To show % complete on a delete operation it could take almost as long to discover files to be deleted as to do the deletion so we would have first message "finding what will be deleted" and then 1%, 2% etc. 

With my fairly fast SSD I tried a recursive delete of 500 items and it took 0.1sec to do them so  the times I would need them is pretty small 

But here is a function which you could have 

```PowerShell
function Remove-AllWithProgress {
    param (
        [Parameter(ValueFromPipeline=$true,Position=0)]
        $Path, 
        $Steps = 100
    )
    Remove-Item -Path $Path -Recurse -Force -Verbose 4>&1 | 
        ForEach-Object -begin {$c=0} -Process {
            if (-not (($c ++) % $steps)) {Write-progress -Activity "Deleting" -Status "$c files done" }
        }
}
```
It does -recurse and -force and outputs a verbose message every 100 files saying "n files done so far"

**Comment by doctordns** [comment]
The challenge of presenting useful progress information for long-running operations has always been a challenge. It is easy to know how long you have spent so far, but knowing how long you have to go is challenging in two ways., First, to know how many files are left to delete, for example, you have to know the total number of files in the first place. And that can take a lot of time., Secondly, estimating the time remaining is difficult, especially if you use network storage. 

My view is that PowerShell is about automation which can just delete the files and move on however long it takes. When I need to view the operations, I can use the Windows GUI which does about a good a job as can be done giving feedback.

**Comment by dkaszews** [comment]
> First, to know how many files are left to delete, for example, you have to know the total number of files in the first place.

The new progress bar in 7.4.0 in `Copy-Item` nicely solves it by calculating the total number of files and their size in a separate thread, so it does not impact the actual performance. For deletion of files, their size is likely irrelevant, just the number matters.

And it doesn't really matter that the estimate is not accurate, as it already of value to just display the progress to the user, so that they know that the process did not hang. For example, if recursively deleting a folder they expected to have 100 files but actually has millions, they may abort if it takes longer than couple seconds, but would be happy to wait if we show that there is more work to be done.

**Comment by dkaszews** [comment]
> My view is that PowerShell is about automation which can just delete the files and move on however long it takes.

There are plenty of people who live in terminal, either because they come from Linux where it is the norm (me included), find it more convenient (me included), or because they are remoting to a machine where accessing a GUI is not feasible (also me included). Adding the progress bar to `Copy-Item` has been an awesome inclusion, and I would be happy to see (or even help to develop) one for `Remove-Item`.

**Comment by jeeveshlodhi** [comment]
I am not asking for a heavy GUI feature, something like this or a progress percentage counter should be enough.


![Screenshot 2023-04-30 113341](https://user-images.githubusercontent.com/45370744/235338440-5be53614-b59f-4dc5-b276-29959b66d6f1.jpg)

**Comment by rhubarb-geek-nz** [comment]
> The new progress bar in 7.4.0 in Copy-Item nicely solves it by calculating the total number of files and their size in a separate thread, so it does not impact the actual performance. 

This is not true if it requires reading the filesystem ( or whatever the target is) twice. Think of the worst case of a network mounted drive.

I recommend against this because it won't work with pipelining. One of the major features of PowerShell is the pipelining and commands being able to run in parallel.

Look at the examples at [Remove-Item example 4](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-item?view=powershell-7.3#example-4-delete-files-in-subfolders-recursively)

```
Get-ChildItem * -Include *.csv -Recurse | Remove-Item
```

How can this provide a progress bar when it does not know what will appear in the pipeline in the future?

If it is expected to read all the pipeline first before beginning the delete then that defeats the purpose of pipelining.

**Comment by dkaszews** [comment]
> This is not true if it requires reading the filesystem ( or whatever the target is) twice.

@rhubarb-geek-nz Have you looked at the implementation? It immediately starts copying the files on a single thread as always (multithreaded IO requires something like `ForEach-Object -Parallel`) and spawns a thread for counting files. That separate thread which runs on another core that would otherwise go unused is responsible for displaying the progress bar. The only case where it could measurably impact the performance is on single-core systems, as enumerating a filesystem, even a networked one, should not impact the copying.

> I recommend against this because it won't work with pipelining.

Who cares? This feature request is only about providing progress bar when deleting directories, not individual piped files.

**Comment by rhubarb-geek-nz** [comment]
> > This is not true if it requires reading the filesystem ( or whatever the target is) twice.
> 
> @rhubarb-geek-nz Have you looked at the implementation? It immediately starts copying the files on a single thread as always (multithreaded IO requires something like `ForEach-Object -Parallel`) and spawns a thread for counting files. 

As I said, _if this requires reading the filesystem twice_. In order to manage large datasets it is better to process as you go rather than reading everything into a list first before you start deleting. If you do the thing in parallel reading the list while deleting then you may end up with a continually incorrect progress bar which may always be showing 90% done.

> > I recommend against this because it won't work with pipelining.
> 
> Who cares? 

Consistency.

**Comment by jhoneill** [comment]
> > The new progress bar in 7.4.0 in Copy-Item nicely solves it by calculating the total number of files and their size in a separate thread, so it does not impact the actual performance.
> 
> This is not true if it requires reading the filesystem ( or whatever the target is) twice. Think of the worst case of a network mounted drive.

Actually it does affect performance But getting a list of files in a directory is quick and requires a small number of disk operations relatively speaking a copy operation is slow, and requires many disk operations. 
With a "counting" and a copy it doesn't matter if we count the file after it has been copied, the total to be copied might come in after the 2nd or 3rd or nth file is copied but that's OK, we know we've done n of 10,000

By comparison a delete is fast - it's a single write to a directory structure. so with two threads, one getting the files and one deleting: (a) files might be deleted before they are counted we've deleted n of how many ?
 (b) it's possible the delete operation would finish first or only very shortly after the count operation, so we don't see the progress bar for long. Alternatively we count first then process but the count takes almost as long as the delete so we roughly double the time.   See my comment above that ideally things that wait for a long time display a progress bar, but if the delete takes 10 seconds, and it takes 7 or 8 seconds to find how many files there are _to_ delete then progress is too slow to appear.   
 
> If it is expected to read all the pipeline first before beginning the delete then that defeats the purpose of pipelining.

True. We could have an easy command for that though collect all the pipeline in the process block, then resend it and update a progress bar in the end block.

**Comment by JamesWTruher** [comment]
@WG-Interactive-Console discussed this and agree that it would be a nice enhancement to have this behavior, especially in light of the behavior of https://github.com/PowerShell/PowerShell/pull/18735 which provides a progress bar for copy. Any implementation however, should ensure that progress is not provided during the removal phase only but is also reported during the discovery phase.

**Comment by jhoneill** [comment]
@JamesWTruher  I didn't think copy and delete had discovery phases.  I would expect discovery to take almost as long as deletion (again I could be wrong) but if it is there _already_ then most of my logic for not doing this melts away. Conversely if it is a question of _adding_ a phase, we'd probably want to see the impact before committing to deliver it.  That's probably a useful sanity check anyway because too many progress updates can slug performance - what we don't want is an operation which took 2 seconds to display a progress bar for 10 seconds :-)
