### ISSUE TITLE
GetFullyQualifiedNameTest.ValidateLinuxGetFullyQualifiedDomainName test failed

### ISSUE THREAD

**Issue by ritalin** [PowerShell/PowerShell#1955]
Steps to reproduce
------------------

1. pushd src/libpsl-native
2. cmake -DCMAKE_BUILD_TYPE=Debug .
3. make -j
4. make test

Expected behavior
-----------------

test success

Actual behavior
---------------

test failed

> [  FAILED  ] GetFullyQualifiedNameTest.ValidateLinuxGetFullyQualifiedDomainName

Environment data
----------------

Mac OS X 10.11.4

```powershell
> $PSVersionTable

```

**Comment by ritalin** [comment]
## Reason

In ValidateLinuxGetFullyQualifiedDomainName, 

``GetFullyQualifiedName()`` function of my machine has returned first uppercase phrase (eg: Xxx-Yyy-Zzz).

But expected host name was lowercase phrase(eg: xxx-yyy-zzz).

Therefore, this test has been failed.

## Proposal resolution

Do I convert the result for ``GetFullyQualifiedName()`` function into lowercase string ?

**Comment by andschwa** [comment]
For the resolution, I'm really not sure. This test has been really iffy. The code is [here](https://github.com/PowerShell/PowerShell/blob/master/src/libpsl-native/test/test-getfullyqualifiedname.cpp), and the function it's testing is [here](https://github.com/PowerShell/PowerShell/blob/master/src/libpsl-native/src/getfullyqualifiedname.cpp).

There seems to be much disagreement between `getaddrinfo()->ai_canonname` and `gethostname()`; which, to be fair, is probably to be expected (nodename and canonnname are not necessarily identical).

I think the main problem is [here](https://github.com/PowerShell/PowerShell/blob/master/src/libpsl-native/src/getfullyqualifiedname.cpp#L27), where the library first attempts to get the hostname, and if it looks like an FQDN, uses it; otherwise it attempts to get the cannonname. This logic was implemented in 2d442eb73279a24638e63c4a82344de5717e5a70.

@palladia do you remember why this was done? It's causing problems :smile:

**Comment by JamesWTruher** [comment]
If there is no effect of doing this evaluation as case insensitive, there's no harm in calling ToLower on the string. However, there looks to be a case insensitive assert, so I would suggest ASSERT_STRCASEEQ rather than doing the conversion

**Comment by andschwa** [comment]
@ritalin can you verify if this still reproduces? I've modified the test (and I'm getting sorely tempted to delete it, there are just so many edge cases).

**Comment by ritalin** [comment]
In v6.0.0-alpha.10, all test is green, and  build process has been successful.

Thanks.
