### ISSUE TITLE
`enum <enum-name>` should ConvertFrom `[string]`

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#19625]
### Summary of the new feature / enhancement

As PowerShell is a loosely typed language, I would expect an custom `enum <enum-name>`  to implicitly ConvertFrom a `[string]`.

See related Stackoverflow question: [How to define a type of a bit-combination?](https://stackoverflow.com/questions/76187970/how-to-define-a-type-of-a-bit-combination)

```PowerShell
[Flags()] enum Access {
    Execute = 1
    Write = 2
    Read = 4
}
```

Similar as  `enum <enum-name>`  implicitly casts ***to*** an `[int]`:
```PowerShell
[Int][Access]'Read, Execute'
5
```
I would expect it to be able to implicitly cast ***from*** a `[string]`:
```PowerShell
$Access = [Access]'Read, Execute'
$Access.HasFlag([Access]'read, write') # strictly typed
False
$Access.HasFlag('read, write') # Loosely typed
```

> MethodException: Cannot convert argument "flag", with value: "read, write", for "HasFlag" to type "System.Enum": "Cannot convert value "read, write" to type "System.Enum". Error: "Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true.""

If even possible (see my TypeConverter attempt for a specific `[Access]` enum type: [How to create a Converter for an Enum ](https://stackoverflow.com/q/76198961/1701026))

Or is that because [`HasFlag`](https://learn.microsoft.com/dotnet/api/system.enum.hasflag?view=net-8.0) expects a general `enumType` type rather then the specific custom ("`access`") `enum`?
Which makes this more a `.Net` feature request then a PowerShell feature request...

Based on [StackOverflow answer from **Santiago Squarzon**](https://stackoverflow.com/a/76201582/1701026), wishful thinking:

```PowerShell
[Flags()] enum Access {
    Execute = 1
    Write = 2
    Read = 4
}

$updateTypeDataSplat = @{
    TypeName   = 'Access'
    MemberType = 'ScriptMethod'
    MemberName = 'HasFlag'
    Value      = {
        param([Access] $flag)

        $this.PSBase.HasFlag($flag)
    }
}

Update-TypeData @updateTypeDataSplat

$access = [Access] 'Execute, Read'
$access.HasFlag('Execute, Read')         # true
$access.HasFlag('Execute, Write, Read')  # false
```

**Comment by SeeminglyScience** [comment]
> Or is that because [`HasFlag`](https://learn.microsoft.com/dotnet/api/system.enum.hasflag?view=net-8.0) expects a general `enumType` type rather then the specific custom ("`access`") `enum`? Which makes this more a `.Net` feature request then a PowerShell feature request...

That's correct, PowerShell cannot determine how to convert to `Enum` because it's an abstract class. This method would need to be special cased in order for it to work, there's nothing at a generic level that the binder can use to infer the specific type of enum required.

**Comment by mklement0** [comment]
Conceptually related (but technically distinct):
* #13161

Out of curiosity, @SeeminglyScience, given that an `enum`-derived type isn't generic and neither is the `.HasFlags()` method, what explains the error message (`Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true`)?

**Comment by rhubarb-geek-nz** [comment]
Enums are a bit of a hack in C#. Traditionally a enum should only be one of a set of values, not a bitwise OR. However to be backward compatible with COM and OLE and hence eventually WIN16, the concept of enum has been bent backwards to no longer be a true enumeration, but effectively like the old #define.

Because of this conversion to int hack, C# doesn't do any runtime type checking on enum values because it knows you could OR anything with absolutely anything.

Traditionally enums have been 0,1,2,3,4,5... but to do the bitwise trick OR they have to be 1,2,4,8,16,32 etc. See [BindingFlags](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.bindingflags?view=net-7.0) as an example.

I am not a fan of the comma notation that was suggested, eg,  'Execute, Read', to be honest it should be a vertical bar for bitwise-OR eg, 'Execute|Read'.

Now purely from the definition, if I did have an enum which was

Alpha=1
Bravo=2
Charlie=3

Then `Charlie` would be the same as `Alpha|Bravo` and who could say what the true meaning was?

**Comment by mklement0** [comment]
Note: This is a tangent, given that we already know what the issue at hand is and how - if deemed worthwhile - it would need to be addressed by special-casing the `.HasFlags()` method call.

----

> the comma notation that was suggested, eg, 'Execute, Read'

The `,` notation is built into the .NET APIs, and supported with `[enum]::Parse[Access]('Execute, Read')`, for instance.

As such, this notation is both long-established and language-agnostic (and `|` as the separator wouldn't be appropriate for PowerShell anyway).

Thus, with, say, `[Access] 'Execute, Read'`, PowerShell is just the messenger here (syntactic sugar for the `::Parse` call).

However, PowerShell differs from the .NET APIs / runtime behavior in the following respects:

* It also validates casting from _numbers_, which the runtime doesn't; e.g, while compiling `(Access)42` from C# happily is quietly tolerated, `[Access] 42` in PowerShell fails.
* It allows you to cast from an _array_ of strings (or numbers), e.g. `[Access] ('Execute', 'Read')`

---

The surprising part - and it's not clear to me how that would relate to the backward-compatibility concerns you mention:

The above works also for enumerations with _mutually exclusive_ members, i.e. also for those _not_ marked as _bit fields_ with `[Flags()]`, allowing nonsensical casts / parsing such as the following:

```powershell
enum Foo1 { one=1; two=2; three=3 }
[Foo1] 'one, two, three'  # -> [Foo]:three = 1 -bor 2 -bor 3

enum Foo2 { one=1; two=2; four=4 }
[Foo2] 'one, two, four'  # -> !! Error:  1 -bor 2 -bor 4 == 7, which is NOT part of the enumeration
```

Given that PowerShell already "does its own thing" with respect to permitting only values that exist as members, it would make sense to _categorically_ prevent multi-value strings, array casts for non-`[Flags()]` enumerations - see:

 * #19513

Note: The other perhaps surprising aspect is that on _definition_ using `[Flags()]` does _not_ enforce that the values _share no bits_; however, the presumptive reason for that is the desire to support convenience members that are _combinations_ of the bit-flag members.

**Comment by rhubarb-geek-nz** [comment]
That's interesting!

```
PS> $flags = [System.Reflection.BindingFlags]'Static, NonPublic'  
PS> $flags
Static, NonPublic
PS> $flags.GetType().Name                                       
BindingFlags
```

**Comment by vexx32** [comment]
WG-Engine discussed this issue today. We agree that on first glance, this looks like it could be somewhat useful or at least convenient to make work.

As has been mentioned above by others, making this work would require adding some kind of special casing to the binder in order to feed the enum type information into the method call. We agreed that this level of change and special casing here doesn't really make sense for what would ultimately only provide minimal convenience. All it really permits is the use of these methods without a direct cast to the desired enum type, and in our opinion it's not particularly difficult of a workaround to add a type cast in order to get this pattern working.

As such, we decided to decline this issue. Thank you for raising it!
