### ISSUE TITLE
Add `which` alias for `Get-Command`

### ISSUE THREAD

**Issue by thekeyboardworrier** [PowerShell/PowerShell#19651]
### Summary of the new feature / enhancement

Hi, I like PowerShell and how it has aliases and functions that make it concise like bash commands. But one thing that I miss is the `which` command by default. This is a handy tool that can locate executables in the PATH variable. It matches PowerShell’s `Get-Command` command. (A lot of *commands* in this paragraph.) I think it would be great to have which as an alias for Get-Command in PowerShell. This would make it more convenient and compatible with other shells.

**Comment by ThomasNieto** [comment]
This would shadow the Linux command as such wouldn't be added. You can add the alias yourself in the profile.

**Comment by thekeyboardworrier** [comment]
> This would shadow the Linux command as such wouldn't be added. You can add the alias yourself in the profile.

Yeah, I did add that to my profile. Thank you.

But there is other Linux commands already added to PowerShell, `cd`, `mkdir`, `pwd` to name a few. Those are only used in windows and do not exist in Linux or Mac as aliases. This one (`which`) perhaps could be added like that too.

**Comment by ThomasNieto** [comment]
Those aliases were added in the windows powershell days. There are have been quite a few discussions about removing those as well. For example curl has come to windows and the alias breaks it.

**Comment by mklement0** [comment]
The `curl` alias fortunately doesn't exist in PowerShell _Core_ on Windows (anymore?).

`cd`, `mkdir`, and `pwd` are less problematic, as they refer to _internal_ (built-in) commands of `cmd.exe` rather than _external utilities_; the latter - which includes `which` on Unix-like platforms - are the ones we do _not_ want to shadow with built-in aliases.

In my estimation, such aliases were never a good idea to begin with, given that PowerShell's fundamentally different syntax makes using them the same way as in the shell / utility of origin breaks in all but the simplest calls.

PowerShell has its own aliases, which are (a) unlikely to clash with external programs and (b) (reasonably) predictably formed with _standardized prefixes_ corresponding on the standard verb in the cmdlet being aliased; e.g., `gc` for`Get-Command`, where `g` is the prefix for the `Get` verb (run [`Get-Verb`](https://learn.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Get-Verb) to see all verbs and alias prefixes); while the _noun_ part isn't standardized (it can't be, given its open-ended nature), the letters are can usually be guessed.

In the case at hand, `gcm` is the built-in alias for `Get-Command`: is shorter than `which`, and cannot be mistaken for the latter.

You can discover existing aliases using the `-Definition` parameter of the [`Get-Alias`](https://learn.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Get-Alias) command:

```powershell
PS> Get-Alias -Definition Get-Command

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           gcm -> Get-Command                                            
```

To ensure that you're only seeing _built-in_ aliases, run via the CLI and `-NoProfile`; e.g.
`pwsh -noprofile { Get-Alias -Definition Get-Command }`
