### ISSUE TITLE
'man' should be removed as an alias on Windows installations

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [PowerShell/PowerShell#19652]
### Summary of the new feature / enhancement

The `man` alias on Windows is not needed and adds confusion when using PowerShell with multiple operating systems.

On Windows

```
PS> get-command man

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           man -> help
```

On Linux

```
PS> get-command man

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     man                                                0.0.0.0    /usr/bin/man
```

So depending on the system you are using they return completely different information.

On Linux

```
PS> man pwsh
PWSH(1)                                                                                                       PWSH(1)

NAME
       pwsh - PowerShell command-line shell and .NET REPL

SYNOPSIS
       pwsh  [-NoLogo]  [-NoExit]  [-NoProfile]  [-NonInteractive] [-InputFormat {Text | XML}] [-OutputFormat {Text |
       XML}] [-EncodedCommand Base64EncodedCommand] [-File filePath args] [-ExecutionPolicy  ExecutionPolicy]  [-Com‐
       mand { - | script-block [-args arg-array] | string [CommandParameters] } ]

DESCRIPTION
       PowerShell  is  an automation and configuration management platform. It consists of a cross-platform (Windows,
       Linux and macOS) command-line shell and associated scripting language.
```

But on Windows,

```
PS> man pwsh
Get-Help:
Line |
  64 |      $help = Get-Help @PSBoundParameters
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Get-Help could not find pwsh in a help file in this session. To download updated help topics type: "Update-Help". To get help online, search for the help topic in the TechNet library at https://go.microsoft.com/fwlink/?LinkID=107116.
```

`man` as a command has no historical lineage on Windows except for with Unix/shell emulators. `help` does, and even existed in MSDOS `commmand.com`.

Having `man` as an alias does not "make PowerShell like bash" because it returns completely different information.

### Proposed technical implementation details (optional)

Remove the 'man' alias on windows installations.

**Comment by kborowinski** [comment]
I do not agree. I find having `man` on Windows and non-Windows very convenient.

**Comment by 237dmitry** [comment]
Do not use man alias on Windows. This is the simplest way.

And, man on Linux for pwsh depends on installation.

```
$ man pwsh
No manual entry for pwsh

$ dir /usr/share/man/pwsh* -recurse       # nothing
```

**Comment by rhubarb-geek-nz** [comment]
> I do not agree. I find having `man` on Windows and non-Windows very convenient.

Even though they return completely different help information? So if you switch between Windows and Linux and use man, then you would find no help about PowerShell functions on Linux. So then you realise that on Linux you need to use help or Get-Help to find PowerShell information. So you might as well use help for PowerShell information on everything.

**Comment by mklement0** [comment]
Pragmatically speaking, you can put the following in your `$PROFILE` to also get `man` behavior on Windows - assuming WSL is installed:

```powershell
Remove-Alias man; function man { wsl -e man $args }
```

I was never a fan of aliases named for other platform's utilities  / other shell's built-in commands, but to me the only compelling reason to take an existing alias away is if it shadows a standard utility on a given platform - and even that can be problematic, especially if no PowerShell-native alternative exists (for an infamous case where that happened, see the [`sc` / `sc.exe` fiasco](https://github.com/PowerShell/PowerShell/issues/5862); I advocated for removal at the time, which I regret in hindsight, given that `Set-Content` now has _no_ built-in alias)

While I understand the cross-platform argument, it's important to note that there are plenty of Windows-only users, and the potential confusion doesn't apply to them; they may have come to value this alias.

Note that `man` is only one of quite a few aliases that are Windows-only:

```powershell
# Run on Windows with WSL and a nested PowerShell version installed
$windowsAliases = pwsh -noprofile { (Get-Alias).Name }
$unixAliases = wsl -e bash -ic 'pwsh -noprofile -c ''(Get-Alias).Name'''
Compare-Object $windowsAliases $unixAliases
```

Output:

```none
InputObject SideIndicator
----------- -------------
ac          <=
cat         <=
clear       <=
cnsn        <=
compare     <=
cp          <=
cpp         <=
diff        <=
dnsn        <=
gcb         <=
gin         <=
gsv         <=
gtz         <=
kill        <=
ls          <=
man         <=
mount       <=
mv          <=
ogv         <=
ps          <=
rm          <=
rmdir       <=
sasv        <=
scb         <=
shcm        <=
sleep       <=
sort        <=
spsv        <=
start       <=
stz         <=
tee         <=
write       <=
```

**Comment by jhoneill** [comment]
man is one of the unix commands which Windows PowerShell created a near-equivalent for. Those with a long experience of Windows PowerShell will use cat, ls, man and some others instead of the command.com / cmd.exe style type, dir, and help to save a character. 
Really what is wrong here is the behaviour away from from windows.   `help xx`  should get whatever help is available for xx. If rm is an alias for `remove-item` on windows, _there_ it should get the PowerShell help for `remove-item` and if it runs  `/usr/bin/rm`  on Linux it should fetch the `man` page for `rm` there. 
And vice versa. 
`man rm` works on Linux to get the help for the `rm` command, it works on windows to get the help for the `rm` alias. On Windows `man rv` gets the PowerShell help for `remove-variable`, but not on Linux.  
Why does a linux user need to remember that `rm` is an os-provided command and `rv` is a pwsh-provided one to get their help? _Really_ pwsh on linux should have a `man` function which runs the external `man` command if the name is an external command and runs `get-help | less` if it is a PowerShell one.

**Comment by mklement0** [comment]
I do think that integrating help for external programs - be it in the form of `man` pages on Unix or via command-line switches such as `/?` and `--help` on Windows - into PowerShell's help system would be helpful, but I don't think it should be under the name `man`, given that we explicitly don't want to shadow native utilities with built-in aliases.

Enhancing the built-in `help` function strikes me as the right approach, and here's a simple proof of concept; it works reasonably well,  but lacks tab-completion due to the crude way used to inject the new functionality; only the first argument is considered (and if it refers to an external program, it preempts the fuzzy search in PowerShell's help system), and the pager is hard-coded to `more` on Windows.
Invariably, a heuristic needs to be employed for getting command-line help on Windows, given that there's no standardized method.

Putting the following in `$PROFILE` makes `help` invoke `man` pages for command names that refer to external programs on Unix, and tries to obtain and show command-line help on Windows (if brevity is important, `Set-Alias gh help` would provide a PowerShell-idiomatic alias name that is even shorter than `man`):

```powershell
$function:help = @"
  if ((Get-Command -ErrorAction Ignore `$args[0]).CommandType -eq 'Application') {
    if (`$env:OS -eq 'Windows_NT') {
      `$helpContent = & `$args[0] /? 2>&1
      if (`$LASTEXITCODE) {
          `$helpContent2 = & `$args[0] --help 2>&1
          if (`$LASTEXITCODE -eq 0 -or `$helpContent2.Count -gt `$helpContent.Count) {
            `$helpContent = `$helpContent2
          }
      }
      `$helpContent | Out-String | more
    }
    else {
      man `$args[0]
    }
  } else {    # pass through to the built-in function
    & { 
      $function:help
    } @args
  }
"@
```

**Comment by jhoneill** [comment]
> I do think that integrating help for external programs - be it in the form of `man` pages on Unix or via command-line switches such as `/?` and `--help` on Windows - into PowerShell's help system would be helpful, but I don't think it should be under the name `man`, given that we explicitly don't want to shadow native utilities with built-in aliases.

Generally agree and your code is a good p.o.c.  I would alias that to man (and therefore expand man to to the external app)
there are two conflicting principles with some wiggle room.    
(a) PowerShell commands should not replace native unix ones. (e.g. **don't** have `sort` alias for `sort-object` taking over from `sort` external program.)   
vs  
(b) Don't make users distinguish PowerShell-provided from OS-provided. (i.e. `man rm`  but `help rv` ) and make the commands the same in all shells. (i.e. don't switch to using `help rm` in PowerShell - much as "if you want `ping` use ping in pwsh, not  `tnc`") 

The wiggle room is don't **replace** `man`, put a **proxy** around it. If $args[0] is an external program ran `man $args` otherwise run `help $args`  your p.o.c. proxies `man` so it could me named `man` IMHO,

**Comment by rhubarb-geek-nz** [comment]
These proposals have completely missed the point of "do one thing and do it well", instead it is as if you want PowerShell to be everything for everybody and if you try to do that you will fail.

On UNIX systems sh, bash, csh, ksh, zsh, dash etc don't need to provide a help system at all because all they need to do is add the man page for their small set of features and let the rest of the OS get on doing its own thing. The python help system just provides help for python.

I have no idea what the point of the aliases are, why are there four aliases for Remove-Item ? On Windows there is an alias for "ps" which behaves nothing like "ps" on any other system, and then you have another alias "gps", not for processing NMEA data but for doing Get-Process, exactly the same thing that the ps alias points to.

How can one forget that "ihy" means Invoke-History? Evidently the person who came up with "r" for exactly the same thing. There is a reason military people say "say again" and not "repeat", because repeat is a direct instruction to the artillery to repeat the last fire mission. The is exactly what this "r" does. I hope you don't mistype an "r" by mistake after recovering your system from backup during a disaster recovery, then "r" will happily drop your database and attempt the restore again.

How did we end up with an alias for a reserved word? Yes "foreach" is an alias to ForEach-Object, so now you know why foreach does not behave the same depending on where it is used.

PowerShell has a really strong naming convention based on Verb-Noun, with autocompletion these aliases are really redundant. The sad effect is that these aliases will by now have been treated as true PowerShell and used in scripts published in the PowerShell Gallery that will break when they try and run on Linux or MacOS.

**Comment by mklement0** [comment]
You're preaching to the choir: 

* Aliases named for other utilities / shell-internal commands such as `man` should never have been introduced, for the reasons stated.

* As for single-character aliases: `%` and `?` make sense, given how fundamental they are to pipeline use, `r` and `h` not so much.

* `foreach` as an alias for `ForEach-Object` indeed guarantees everlasting confusion.

----

* v6, with is many breaking changes, offered an opportunity to start fresh:
  * All "borrowed" aliases could have been removed, possibly also `r`, `h`, and `foreach`...
  * ... leaving only aliases formed according to PowerShell's naming conventions, such as `gci` for `Get-ChildItem` - which are much less likely to conflict with external utilities (though it happened with `sc`; introducing `sct` for `Set-Content` instead, and, for symmetry `gct` for `Get-Content`, would have been a reasonable compromise).

The result _could have been_ a consistent cross-platform experience.

Clearly, that opportunity was missed, and I don't think  your proposal to remove `man` - or any other existing aliases - will be considered at this point.
(Clearly not my call; if anything, I'd personally be fine with doing the above, but it's fair to assume that you'll not only break the interactive habits of many, but also existing _scripts_, given that PowerShell places no restrictions on alias use in scripts.)

---

What I proposed had nothing to do with aliases, and is therefore somewhat _tangental_ to your request: it is an attempt to provide an _integrated_ help experience, but _not_ via a "borrowed" alias.

@jhoneill suggested making this integrated functionality available via alias `man`, which I don't think is the right way to go, for the reasons explained, but to recap: a clear separation between PowerShell-native and eternal programs is advisable, given that these two worlds play by very different rules, and being aware of that is important.

Case in point, @jhoneill, here are the syntax diagrams for the native `man` utility on macOS:

```none
     man [-adho] [-t | -w] [-M manpath] [-P pager] [-S mansect]
	 [-m arch[:machine]] [-p [eprtv]] [mansect] page ...

     man -f [-d] [-M manpath] [-P pager] [-S mansect] keyword ...

     man -k [-d] [-M manpath] [-P pager] [-S mansect] keyword ...
```

Unix users have a reasonable expectation to call the actual `man` utility - with all available options - when they submit `man`.

**Comment by rhubarb-geek-nz** [comment]
> What I proposed had nothing to do with aliases, and is therefore somewhat _tangental_ to your request: it is an attempt to provide an _integrated_ help experience, but _not_ via a "borrowed" alias.

Is there really a need for this? This goes back to "do one thing and do it well", don't try and be everything for everyone.

Somebody writing PowerShell scripts should know the difference between a standard operating system command and something provided by PowerShell, if they don't then they have much bigger problems than what help command they should use.

PowerShell should just provide help for PowerShell modules, just like Python only provides help for Python. It keeps the boundaries much cleaner.

Get-Help - gives you help on PowerShell
man - gives you help on macOS and Linux like it always did

Windows command help? You could try %COMSPEC% /C "help topic", but after that you are on your own.

```
This command is not supported by the help utility. Try "topic /?"
```

**Comment by mklement0** [comment]
> Is there really a need for this?

It would be a _convenience feature_ - nothing more and nothing less - it provides a simple, unified way to ask for help, in whatever form it is available for a given command.

And, as proposed, it would only be available via the `help` _function_ - which already has special status due to its built-in paging - whereas `Get-Help` would continue to work as-is (PowerShell commands only), and `man` would continue to refer to `/usr/bin/man` on Unix-like platforms (but the Windows `man` alias will, unfortunately, not go away).

Users definitely need to know the difference between external programs and PowerShell commands when _invoking_ a command  - hence my plea never to name aliases for another platform's / shell's utilities / commands  - but having a unified way to invoke help can help you _discover_ what kind of command you're dealing with.

> Windows command help? 

The only thing worth supporting with `help cmd`  is to call `cmd /?` (just updated the proof-of-concept to handle that case correctly), i.e. to treat `cmd.exe` just like any other _external program_ that may provide command-line help - providing help for `cmd.exe`'s _built-in commands_ (e.g, `setlocal`, `mklink`, ...) is beyond the mandate of the proposed feature, not least because you cannot call such commands _directly_ from PowerShell (the `cmd`-internal `help` system - surprisingly - covers some _external programs_ such as `shutdown.exe` as well, but their command-line help can also be obtained by direct invocation with `/?`, which the proof-of-concept above already does.

**Comment by rhubarb-geek-nz** [comment]
This discussion has been useful.

**Comment by jhoneill** [comment]
> You're preaching to the choir:
> 
> * Aliases named for other utilities / shell-internal commands such as `man` should never have been introduced, for the reasons stated.

They were introduced into windows PowerShell because - for example - someone used to linux would expect to use cp, rm , cat, ls, ps etc. just as someone used to cmd would expect to use copy, del, type dir.  How do I get help on this command ? I type "man commandname" or "Help commandname" depending what my past experience was.  

Like a lot things they seemed like a good idea at the time and remain because once something is provided it becomes impossible to stop providing it. 

> * As for single-character aliases: `%` and `?` make sense, given how fundamental they are to pipeline use, `r` and `h` not so much.

Having used h a lot and never used r - different things make sense to different people. 

> * `foreach` as an alias for `ForEach-Object` indeed guarantees everlasting confusion.
Not _really_  no more than a `[switch]` parameter and a `switch () {}` statement, or `%` as alias and a modulo operator. Or Get-Alias ?    not returning where-object. Or Sort being powershell's `sort-object` on windows and the external `sort` executable on linux 
 
> * v6, with its many breaking changes, offered an opportunity to start fresh:
>   * All "borrowed" aliases could have been removed, possibly also `r`, `h`, and `foreach`...
>   * ... leaving only aliases formed according to PowerShell's naming conventions, such as `gci` for `Get-ChildItem` - which are much less likely to conflict with external utilities (though it happened with `sc`; introducing `sct` for `Set-Content` instead, and, for symmetry `gct` for `Get-Content`, would have been a reasonable compromise).

Uptake of 6 was not great because of the the breakages from Windows PowerShell, and even with 7 adoption is still not as fast as we'd all like. If one took away cat, cp, rm for those who found they were the quicker way to work it, would just add to the "stuff doesn't work in the new version" sentiment. Having spent most of my career battling to get people adopt stuff  if I someone had mooted that and I'd been in the discussion I would have been arguing very strongly that it was a bad idea. 

> The result _could have been_ a consistent cross-platform experience.

Consistency _where_ is a decision `dir` doesn't have the same switches in PowerShell as it does in cmd.  But when muscle memory sends dir [enter] or ls [enter] to the keyboard getting a file listing is better than getting an error. The same for copy  , by having `cp a  b` and `copy a b` both copying a to b is better  even if the switches don't work.  etc.   
Having PowerShell usurp command names provided by the OS is bad. So only simultaneously have an experience which is consistent between bash and pwsh  on linux (cp, cat, ls  etc run external programs)    
**and** between Windows PowerShell and pwsh on windows        
**If** pwsh on windows and pwsh on linux. do slightly different things (alias `cp` or not) and we say that `cp` copying with different options in different places is as consistent as we can achieve.  "cp" working in bash, and pwsh everywhere (only up to a point in windows Powershell, but not cmd.exe) is the best inconsistent consistency we can get.   

> Clearly, that opportunity was missed, and I don't think your proposal to remove `man` - or any other existing aliases - will be considered at this point. (Clearly not my call; if anything, I'd personally be fine with doing the above, but it's fair to assume that you'll not only break the interactive habits of many, but also existing _scripts_, given that PowerShell places no restrictions on alias use in scripts.)

See above for why it's unlikely. There's also an argument that would say linux users don't need the cmd names so get rid of those but until those me like with decades of command.com/cmd.exe before PowerShell die off, dir, type, copy, del, will be used instead gci, gc, cpi, and ri.     

> 
> What I proposed had nothing to do with aliases, and is therefore somewhat _tangental_ to your request: it is an attempt to provide an _integrated_ help experience, but _not_ via a "borrowed" alias.

This would, in my view be a better user experience. Why does help robocopy not work in PowerShell ?  (unless run as help.exe robocopy),  Why does someone using linux on PowerShell need to remember rm uses man, and ri uses help ? 
 
> @jhoneill suggested making this integrated functionality available via alias `man`, which I don't think is the right way to go, for the reasons explained, but to recap: a clear separation between PowerShell-native and eternal programs is advisable, given that these two worlds play by very different rules, and being aware of that is important.

If  `man {args}` produces something in another shell on the current OS it should do the same thing on PowerShell, I think we're agreed on that.  But  having  `man ri` in PowerShell saying "No such command" just a bad user experience that can be fixed without breaking normal operation of man. 
 
> 
> Case in point, @jhoneill, here are the syntax diagrams for the native `man` utility on macOS:
> 
> ```
>      man [-adho] [-t | -w] [-M manpath] [-P pager] [-S mansect]
> 	 [-m arch[:machine]] [-p [eprtv]] [mansect] page ...
> 
>      man -f [-d] [-M manpath] [-P pager] [-S mansect] keyword ...
> 
>      man -k [-d] [-M manpath] [-P pager] [-S mansect] keyword ...
> ```
> 
> Unix users have a reasonable expectation to call the actual `man` utility - with all available options - when they submit `man`.

Even simpler p.o.c. 
```powerShell
function man {
  $path = get-command -Name man -CommandType Application | Select -first 1 -ExpandProperty source
  & $path $args
  if ($LASTEXITCODE) { Invoke-command ([scriptblock]::create("help $($args -join ' ' )"))   } 
}
```
It runs man. with arguments passed. If that results in error it tries help.  
User sees a brief message that this isn't actually a man page and gets their help. 
`man rm` or `man -w rm` or `man ri` all work.

**Comment by rhubarb-geek-nz** [comment]
One gap you will be left with is that while you could then happily get help for "strlen" and "fprintf" you won't be able to get help for dotnet "ToString" or "Replace".

**Comment by mklement0** [comment]
@jhoneill:

> They were introduced into windows PowerShell because - for example - someone used to linux would expect to use cp, rm , cat, ls, ps etc. just as someone used to cmd would expect to use copy, del, type dir. 

Yes, but my argument was: _that was a bad idea_, because while it _initially_ may  ease the migration pain a bit _in the long run_ it gets in the way, because using these aliases as one is used to from the shell / platform of origin _fails in all but the most trivial cases_, given the fundamental syntax differences; e.g. a Unix user typing `ls -l` is in for a surprise.

>  dir [enter] or ls [enter] to the keyboard getting a file listing is better than getting an error.

I don't think it is. In fact, it may induce users to limp along, without fully understanding why some calls work, and others don't. It gets in the way of forming a conceptually clear mental model.

The migration issue could have been addressed with _hints_, similar to the one you get when you try to invoke an executable located in the current directory.

As for the proof-of-concept with `/usr/bin/man` pass-through options:

Combining two completely unrelated syntaxes in a single function to me is reason enough not to implement such a function (it would make for quite a confusing syntax diagram for that function itself).
Perhaps more importantly, it violates the policy of not  shadowing native utilities.

**Comment by mklement0** [comment]
@rhubarb-geek-nz:

As proposed, the integrated `help` function would only support _external utilities_, not _library functions_ such as `strlen` (which `man` _does_ support) - and I think that is a sensible - but debatable - limitation, given that you cannot use such functions _from a shell_.

By contrast, given that PowerShell _can_ call .NET APIs directly, facilitating lookups of the latters' documentation would indeed be helpful, and has been proposed before:

* #11338

* Related: #11339

**Comment by jhoneill** [comment]
> @jhoneill:
> 
> > They were introduced into windows PowerShell because - for example - someone used to linux would expect to use cp, rm , cat, ls, ps etc. just as someone used to cmd would expect to use copy, del, type dir.
> 
> Yes, but my argument was: _that was a bad idea_, because while it _initially_ may ease the migration pain a bit _in the long run_ it gets in the way, because using these aliases as one is used to from the shell / platform of origin _fails in all but the most trivial cases_, given the fundamental syntax differences; e.g. a Unix user typing `ls -l` is in for a surprise.

The arguments about whether the principle is good or bad, and about specific cases were advanced long ago and a way forward was chosen - which was to issue the "You idiot that's not a valid command here" error the smallest number of times possible.   Yes, `ls -l` doesn't do what a unix user expects, and by the same token `dir /s` doesn't do what user of cmd.exe / command.com expects either. But if a high percentage of the time we issue `dir`/ `ls`  or  `copy from to` / `cp from to`  or  `del file` / `rm file`  opting to give "you idiot" errors instead of supporting the limited versions is making the great the enemy of the good. 
 
> > dir [enter] or ls [enter] to the keyboard getting a file listing is better than getting an error.
> 
> I don't think it is. In fact, it may induce users to limp along, without fully understanding why some calls work, and others don't. It gets in the way of forming a conceptually clear mental model.

Provide a crutch and let people limp along, or let them fall over until they can walk properly ? 
If someone gives you a new shell and doing simple tasks leaves you with a bunch of "you idiot" errors you might go back to what you're comfortable with. For me `dir` works like it did in 1987, I've never switched to `gci` and the fact `dir /s` has become `dir -rec` doesn't bother me. I might never have stuck with PowerShell if I had to unlearn dir, copy, del, and type.  

> As for the proof-of-concept with `/usr/bin/man` pass-through options:
> 
> Combining two completely unrelated syntaxes in a single function to me is reason enough not to implement such a function (it would make for quite a confusing syntax diagram for that function itself). Perhaps more importantly, it violates the policy of not shadowing native utilities.

If one asks "What does the user wants?" one gravitates towards that as  solution.  When did a user ever say "I want to have two different help commands".  I've yet to meet the user who says "I like using `help ri` but `man rm`".   

I always like to say policy isn't law, it's just aggrandizes things we choose to do. 
And in this case Policy is that adding a command should never remove functionality only add it.  
Adding `man` as an alias in windows doesn't stop anything which would have worked in Windows before, (btw on aliases in windows making rm an alias which does something similar to what it does on unix stops it being used for something like Remove-Module. Adding a command which wasn't on that OS, but does something totally different elsewhere is a bad idea)
Commands which _remove_ functionality result in "you idiot" messages when someone issues a command which would work in another shell on the same OS instance.   Making man ONLY an alias for the PowerShell `help` function in linux would go against this. 
But  Proxy functions which call the original are good and encouraged, and this is just a proxy function for `man`.  It doesn't even hide the message which says "really you shouldn't use `man` for this"  it just stops `man ri`  saying `No manual entry for ri` and stopping there, so going with the policy of calling the user an idiot the absolute minimum number of times.

**Comment by rhubarb-geek-nz** [comment]
Although the horse has well and truly bolted, in many ways PowerShell is more like Python that any traditional shell. Python seems to be doing well despite the following

```
$ python3
Python 3.9.14 (main, Feb  8 2023, 03:39:52) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> dir
<built-in function dir>
>>> help dir
  File "<stdin>", line 1
    help dir
         ^
SyntaxError: invalid syntax
>>> man dir
  File "<stdin>", line 1
    man dir
        ^
SyntaxError: invalid syntax
>>>      
```

While superficially PowerShell shares many things in cmd.exe and sh/bash/ksh/zsh/csh in common such as having pipes, they don't behave at all like byte stream pipes causing much confusion.

Likewise "csh" behaves completely differently to "ksh" and is not embarrassed to admit it.

Do I use different help mechanisms depending on what I am looking for? Absolutely!

**Comment by mklement0** [comment]
> Provide a crutch and let people limp along, or let them fall over until they can walk properly ?
> a bunch of "you idiot" errors

The hints I suggested are neither "you idiot errors" nor do they let the user fall over.
Rather, they would _guide them toward learning how to use the new shell properly_, along the lines of:

> `dir` is not a PowerShell command, but it corresponds to `Get-ChildItem`, whose alias is `gci`, but its syntax is different.
> `gci -?` shows the syntax and basic help, `help gci` shows full help.

> "I like using help ri but man rm"

The proposed `help` function would still give you the _basic_ integration of help for external utilities (executable name only; that is, `help ri` and `help rm` would both work), 
but it wouldn't try to _selectively impersonate_ `/usr/bin/man`, with all the conceptual confusion that entails.

>  `man ri` saying `No manual entry for ri` and stopping there

That's what it _should_ do, because `man` should only ever call `/usr/bin/man`.
That's the - sensible - policy we've been pursuing, by removing aliases  that shadow a given platform's stock utilities, and it's a simple rule for users to remember.
Don't overload it with PowerShell functionality that no one should be expecting _under that name_.
(And, as argued, even the _cross-platform_ aliases such as `man` on Windows were a bad idea - too late to fix that).

**Comment by mklement0** [comment]
@rhubarb-geek-nz

> Although the horse has well and truly bolted

Undoubtedly, but to me such discussions are still worthwhile, as it can bring conceptual clarity that may come in handy in future cases where the horse is still in the barn, if you will.

> PowerShell is more like Python that any traditional shell.

PowerShell is undoubtedly a shell (with an infinitely more capable scripting language compared to traditional shells), which Python is definitely not.

While it retains the basic characteristics of a shell, its fundamental difference - and great evolutionary leap - was to make the pipeline (data streams) _objects_ with rich data-type support rather than raw bytes / text-only.

The non-support for raw byte streams _is_ problematic, but it sounds like it will be addressed soon:

* #17857
