### ISSUE TITLE
Cmdlet for Get-Sessions

### ISSUE THREAD

**Issue by blackops786187** [PowerShell/PowerShell#19673]
### Summary of the new feature / enhancement

Much like the capabilities of qwinsta.exe, quser, it would be benifical to have cmdlets to get all the sessions on the machine. The issue with qwinsta/quser is that the output is not parsable as its in a string format. An object format would be easy to filter

**Comment by kilasuit** [comment]
If this is going to be feasible it will need to be something that works across Windows Linux & MacOS & as such wouldn't just be limited to how qwinsta works

Have you searched in the PowerShellGallery for any community modules that do this of which from [this search ](https://www.powershellgallery.com/packages?q=quser) I found a few already published to the Gallery

There is also this [Stack Overflow answer](https://stackoverflow.com/a/23454741) that points to other possible ways that you can work around this for windows for now

**Comment by jhoneill** [comment]
On Windows: Get-CimInstance win32_session | Get-CimAssociatedInstance -ResultClassName win32_userAccount 

Not about the feasibility of a cross platform one. Can't speak for the other members of the WG, but my take would be this can come from the community without adding a cmdlet for it.

**Comment by blackops786187** [comment]
@jhoneill your command gives me odd output and not the info that quser gives.

@kilasuit Pretty much all of the community solutions i've seen were using some form of regex to parse stuff and had edge cases where the parsing is incorrect which made it less robust. I am looking for a more native approach

**Comment by kilasuit** [comment]
@blackops786187 - I didn't close it because I understood your ask, though was giving you potential options that may work for now because what you are asking by a Get-Sessions cmdlet is in my mind not fleshed out enough. Does it need RDP sessions, SSH, WinRM or other sessions. All of these points were missed in your Feature request and are ones that I would want if there was a generic get-sessions cmdlet bundled in with PowerShell. Also please bear in mind what you are asking for with the info provided is in my view unlikely to be taken on by the PowerShell team due to there being some community solutions out there, which if there are issues with then these should have issues raised to them as they may be able to fix them quicker and then you can use them without fear of them being brittle. Also I'm a big believer that the community is needed to provide these solutions too especially as every other programming/scripting language uses community tooling somewhere, as does just about every OS too, even those used in locked down secure environments

**Comment by JamesWTruher** [comment]
The cmdlet WG has discussed this. Tools like quser.exe target operating system-specific features that do not translate easily to other operating systems. That's why PowerShell supports both cmdlets and native commands (for example, Stop/Restart-Computer for generic cross-platform functionality and shutdown.exe covering operating-system specific extra functionality). Applications by nature return unstructured text which can be a disadvantage compared to cmdlets. To overcome, you can either use PowerShell's text-parsing features (i.e. (quser).TrimStart('>') -replace '\s{2,}', ',' | ConvertFrom-Csv), or use object-oriented .NET API calls in the first place, then incorporate this into your own cmdlets and modules. We believe the requested functionality should not be part of the standard set of cmdlets that ship with PowerShell but encourage you and other community members to implement and share functions like this via the PowerShell Gallery.
