### ISSUE TITLE
Get-Content -Head and -Tail should behave like head and tail with negative parameters

### ISSUE THREAD

**Issue by CarloToso** [PowerShell/PowerShell#19710]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce
[SYSTEMATIC REVIEW](https://github.com/PowerShell/PowerShell/issues/19710#issuecomment-1562959738) by @mklement0

Get-Content -Head and -Tail should behave like head and tail with negative parameters, I checked the code and this is by design but I think its not the corect behaviour.

https://www.gnu.org/software/coreutils/manual/html_node/head-invocation.html
https://www.gnu.org/software/coreutils/manual/html_node/tail-invocation.html

Create txt file:
```ps1
@"
1
2
3
4
5
6
"@ | Set-Content file.txt
```

### Expected behavior

```console
Get-Content file.txt -Head -3
head file.txt -n-3

4
5
6

Get-Content file.txt -Tail -3
tail file.txt -n-3

1
2
3
```

### Actual behavior

```console
Get-Content file.txt -Head -3
Get-Content file.txt -Tail -3

1
2
3
4
5
6
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
What's the point of that? It provokes the creation of trick code, which is bad UX/

**Comment by CarloToso** [comment]
It would follow the behaviour of the original tools. If we don't want to do that I think we should add a `[ValidateRange(0, MaxValue)]` for `-Head` and `-Tail`. Now `Get-Content file.txt -Head -1` and `Get-Content file.txt -Head -10` do the same thing and that's counterintuitive.

**Comment by 237dmitry** [comment]
> and that's counterintuitive

Use `-First` and `-Last` aliases

**Comment by CarloToso** [comment]
@237dmitry I don't understand what you are saying.
I don't think that `Get-Content file.txt -First -1` and `Get-Content file.txt -First -10` should have the same output, throwing and error for negative values would be a better choice (if we don't want to follow my initial suggestion)

**Comment by 237dmitry** [comment]
> throwing an error for negative values
>> negative values

What is this for?

**Comment by jhoneill** [comment]
> Use `-First` and `-Last` aliases

At the moment `head -5` or Or `-First -5` return the whole file  The problem is **negative values are ignored** .

`Select-object` gives an error if  `-index` `-first` or `-last` is negative.  Arguably    
`GC "foo.txt" -first $x`  and `Gc "foo.txt | select -first $x`  should do the same for all values of $x. 
So EITHER Get-Content should validate the parameters and reject negative values 
OR both should be updated to process negative numbers

When I just tried  `head -5`  is treated as `head 5` but `head -n -5`   gives lines 0 to length -5.  
however `tail -5` and `tail -n -5` both return the last 5 lines.  
(in other words you can get first n lines, last n lines, and all but the last n lines, but not all but the first n) 

So a user might reasonably expect any of:  

- error for numbers less than 0 -like `select-object`
- `-head x` / `-first x`  and `-tail x`  / `last x`  work with (abs(x) ) -like the `head` command _without_ `-n` and the `tail` command _with or without_ `-n`
- `-head -n` / `first -n` is read as (length - n )"  -like the `head` command _with_ `-n` and `-last`/`-tail` does the same - _which is different from the tail command._ 
- half and half with `-First`/`-Head` doing (length -n)  for negatives and `-Last`/`-Tail` doing abs().  
- `-first -n`  is actually `-last +n`  (and vice versa)  -like `(gc ...)[-1..-n]` but unlike `head` and `tail` commands. 

The first two give consistent behaviour. The last two are horrible and really just for completeness.  
Whether making `-Tail` work like `head -n` and not like `tail` / `tail -n`  is something people will doubtless argue over. I think modifying GC so it can easily get the first n, or remove the first n, get the last n or remove last n. is functionally better despite that. Technically it's a breaking change but it's unlikely anyone relies on current behaviour, bringing the same thing to 
Select-Object would also be useful but is a slightly worse breaking change (with `$files | select -first $n | del` if an error says $n is -1, nothing is selected, but  if `select-object` treats -1 as 'all but the last 1' lots gets deleted). 

I think the cmdlets wg should have a look at this and I'll try to get in on the agenda.

**Comment by mklement0** [comment]
Here's a systematic overview of what the `head` and `tail` do with negative numbers and what `tail -n +$n` does (explicit `+` prefix), along with the equivalent PowerShell commands:

```powershell
# `tail`, curiously, treats negative numbers the same as
# unsigned positive ones: -n $n and -n -$n both mean:
# Get the last $n lines.
tail -n -3 file.txt # same as: tail -n 3 file.txt
# PowerShell equivalent
Get-Content file.txt -Last 3 
# Q: Should `-Last -3` be supported too, with the same meaning?

# `head` treats negative numbers (-n -$n) as: 
# Return all but the last $n lines. 
# (Not supported by the stock `head` utility on macOS)
head -n -3 file.txt
# PowerShell equivalent
Get-Content file.txt | Select-Object -SkipLast 3
# Q: Should `Get-Content -First -3 file.txt` be supported too, with the same meaning?
#      Not intuitive; introducing -SkipLast to Get-Content directly would be more PowerShell-idiomatic.
#     (Note that -First and -Last already duplicate Select-Object features).

# tail treats -n +$n, i.e. an explicit "+" prefix as:
# Skip the first $n-1(!) lines, i.e. start with line $n.
tail -n +3 file.txt
# PowerShell equivalent
Get-Content file.txt | Select-Object -Skip 2
# Q: Should `Get-Content -Last +3 file.txt`  be supported too, with the same meaning?
#      Not intuitive, and since -Last is [int]-typed, this wouldn't currently work, 
#      because the "+" wouldn't reach the cmdlet.
#      Introducing -Skip to Get-Content would be more PowerShell-idiomatic.
```

Note that in the syntax form `head -5`  and `tail -5` the `-` doesn't actually indicate a _negative_ number, but is the _option ID char_ - syntactic sugar that is a shortcut to `head -n 5` and `tail -n 5` (`head --lines=5` and `tail --lines=5`).

One possible resolution:

* Disallow negative numbers consistently.
* For feature parity with `head` and `tail`, introduce `-Skip` and `-SkipLast` parameters to `Get-Content`
  * I know there's concern about duplication of functionality, but we already have it in the `-First` and `-Last` parameters: in this case it isn't just about convenience and concision, but also about performance.

**Comment by CarloToso** [comment]
@jhoneill Maybe the cmdlets wg should also look into setting `Tail` to `long` instead of `int` just like `Head`

**Comment by jhoneill** [comment]
@CarloToso  I'll see if I can get it on the agenda for the cmdlets working group - they could both be int, or both long but one of each doesn't make any sense. 
  
I think the WG should also be confirming that negative values won't be allowed , and possibly adding `-skip` / `-skiplast`. to be like `select-object`  I can see arguments for and against each of the options, so we'll see what consensus emerges.
