### ISSUE TITLE
Explicitly added relative directories to environment path are ignored by Powershell >= 7.1

### ISSUE THREAD

**Issue by Anthony-Breneliere** [PowerShell/PowerShell#19732]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Add `./node_modules/.bin` directory to the system environment path variable.

Open a node.js project.

Run a command from `./node_modules/.bin`.

### Expected behavior

```console
PS D:\Projets\toto> ngc
```
The command ngc should be found, as `./node_modules/.bin` directory is explicitly added to the environment path.

### Actual behavior

```console
PS D:\Projets\toto> ngc
ngc: The term 'ngc' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
The command is not found.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

It seems the default behavior is for security concerns of system administrators, but developers are currently stuck to Powershell 7.0 to run project relative commands without having to type long paths.

**Comment by 237dmitry** [comment]
> Add ./node_modules/.bin directory to the system environment path variable.

How did you add? Did you restart pwsh?

**Comment by Anthony-Breneliere** [comment]
> > Add ./node_modules/.bin directory to the system environment path variable.
> 
> How did you add? Did you restart pwsh?

Yes, in the procedure, opening a new VS Code with a terminal restarts pwsh. Only paths starting like ./xxx/yyy are ignored.

**Comment by mklement0** [comment]
This is a known problem, and the specifics of the bug are discussed in:

* #15795

The linked issue only talks about `.`, but it applies to all relative paths.
In short: it seems that the relative path is unexpectedly resolved to a full one, on assignment.

As for workarounds:

* General: https://github.com/PowerShell/PowerShell/issues/12662#issuecomment-1145903240

* Node.js-specific: use `npx ngc` to execute the project-specific `ngc` binary.

**Comment by jhoneill** [comment]
See also #14106

Quick history lesson - from PowerShell 1.0, Powershell has not automatically run executables in the current directory. If an attacker could put a malevolent ping.ps1 in the user's default directory, it would be run with cmd if they try use ping, but not with PowerShell  

This is inconvenient for some people and I am not alone in having something in my profile to add ` . ` to my path. This worked in Windows PowerShell and still does. It worked in PowerShell 6.  Something changed in 7. 

It appears PowerShell now caches the value of `$env:path` when it changes,  so adding `.` in a profile will add the directory where PowerShell starts and adding ` "./node_modules/.bin"` is equivalent to adding  `"$Pwd/node_modules/.bin"` 
 
AKAIK the previous issues opened on this have not had any input those who made/approved making this change. If it was done in the name of "security" the team may not be receptive to requests to go back to what we were happy with before. I would like to know if it is an accident from adding caching and therefore a bug, or broken by design.
