### ISSUE TITLE
Class Constructor Error - Can't Set Variable Values

### ISSUE THREAD

**Issue by aksarben** [PowerShell/PowerShell#19757]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I’m writing a PowerShell class as follows:

```
class FileTransferStatus {

    [System.IO.FileInfo[]]$files
    $totalBytesToTransfer
    $bytesLeftToTransfer

    FileTransferStatus([System.IO.FileInfo[]]$files)
    {
        this.$totalBytesToTransfer = 0
        foreach ($file in $files) {
            this.$totalBytesToTransfer += $file.length
        }
        this.$bytesLeftToTransfer = this.$totalBytesToTransfer
    }
}
```

### Expected behavior

```console
No error message
```

### Actual behavior

```console
Visual Studio Code reports an error on the last line of the constructor, which tries to initialize $bytesLeftToTransfer. The message is:

**Variable is not assigned in the method.**
```

### Error details

```console
The error is from Visual Studio Code during editing, not from running the script.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/6260602/9447ee06-1de1-4098-94e8-6f6e0c720c03)

**Comment by mklement0** [comment]
@santisq has already pointed out the problem with your code on Stack Overflow: `this.$totalBytesToTransfer` should be `$this.totalBytesToTransfer` 

The syntax of `class` definitions is documented in [about_Classes](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Classes).

---

As for why only the _last_ instance of `this.$totalBytesToTransfer` is marked as an error in VSCode:

Perhaps surprisingly, `this.$totalBytesToTransfer` is valid as a _verbatim command name_, so there's no syntax problem. (Try `function this.$totalBytesToTransfer { 'hi!' }; this.$totalBytesToTransfer`)

However, when the same token is used as a command _argument_, `$totalBytesToTransfer` _would_ get expanded (interpolated), and the absence of a variable by that name previously declared in the method is what causes the error.

**Comment by aksarben** [comment]
Wow. I feel like I’m sipping from the proverbial fire hose.

I must have stared at documentation for an hour without seeing this misplaced dollar sign. Glad your eyes are better than mine.

I don't know who at Microsoft edits documentation, but this is a good example of where clear error messages are invaluable.

Thanks for the help!

**Comment by mklement0** [comment]
Glad to hear it helped, @aksarben - the syntax takes some getting used to with respect to knowing when to use `$`.

As for the error message: 

PowerShell - deftly, given the challenge - marries two distinct syntax worlds: _shell commands_ (commands followed by whitespace-separated arguments)  vs. _expressions_ (operator-based operations and method calls, as in traditional programming languages), necessitating two distinct _parsing modes_: see [about_Parsing](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Parsing).

I've posted an [an answer to your Stack Overflow question](https://stackoverflow.com/a/76418667/45375) that explains in more detail why you saw the error message you did.

While I agree that the error message happens not to be particularly helpful _in this case_, I don't think there's a good solution to this problem.

**Comment by jhoneill** [comment]
> Wow. I feel like I’m sipping from the proverbial fire hose.
> 
> I must have stared at documentation for an hour without seeing this misplaced dollar sign

Easily done. We've all had a space in the wrong place, a comma where a semicolon was needed, and in one case which still haunts me I wrote `"prefix2".   "prefix3"`   in a list which was piped into "delete all files starting"  - it returned the "prefix3" property of the string "prefix2" which was null. So all files were deleted.  

When I first worked with classes I didn't understand _why_ properties which declared as `$Name` are not in-scope with that name throughout an instance of the class.  **Outside** the class if we do `$M = [MyClass]::new() ` we expect to refer to `$M.Property` and I just accepted `$this` was a special variable (therefore begins with `$`)  which gives an object a name for _itself_  this works when you add a script property to an object too - and then we refer to the properties of the object as we would from outside using that name.  In a constructor it still jars a bit because in my head the constructor isn't part of the object it constructs, meaning `$this` only should work for methods.  I've been writing something on classes for a book in recent days, and I haven't yet got a way to explain this that I like.   Unless `this` is the name of function which returns a property and `$tbtt` is a variable which holds a property name we would see `this.$tbtt` normally, so a practiced eye that looks wrong. Most of the time :-)

**Comment by aksarben** [comment]
Heartily agree with your musings on why a $this prefix is needed in a class method referencing class variables.

It's been a while since I worked in Java or C++, but I don't recall them having that requirement (which greatly reduced the code clutter), so I guess it's possible for language designers to find a way to work without it.
___________________________

The Cyber Hymnal™ <><
http://www.hymntime.com/tch
________________________________

**Comment by mklement0** [comment]
Reflecting more on the potential to improve the error message: I think it can:

* #19767
