### ISSUE TITLE
Provide a syntax to call native binaries when its name is aliased

### ISSUE THREAD

**Issue by be5invis** [PowerShell/PowerShell#1975]
Like, if I have **both** `gsn` (as an alias) and `gsn` (as a script on Linux with Shebang), the latter one is unaccessable (unless you provide its full path).

**Comment by lzybkr** [comment]
On Windows, it's common to use an extension, e.g. `gsn.exe`, but obviously that won't help on Linux.

A full path (or relative path) is the most obvious way to invoke an external command, but we do have a syntax (admittedly obscure) if you don't know the path:

```powershell
& (Get-Command -CommandType Application gsn)
```

The `&` operator is the invocation operator - which is more often used to invoke commands with spaces in the path or to execute a command whose name is in a variable. In my example above, because of strong typing, the invocation operator recognizes the output of Get-Command (an instance of something deriving from `System.Management.Automation.CommandInfo`) and correctly calls that command, allowing you to override the default command resolution algorithm.

That said, I agree a better syntax is needed for Linux.

**Comment by be5invis** [comment]
@lzybkr How about “:gsn”? I am not sure whether this prefix is occupied...

**Comment by lzybkr** [comment]
That would be a breaking change - admittedly unlikely to cause problems, but a breaking change nonetheless:

```powershell
function :gsn { 'in gsn' }
:gsn
```

The above has worked since V1 - it likely wasn't intentional - I can't say for sure, I joined the team during V2.

**Comment by be5invis** [comment]
@lzybkr Are there anyone hsing `:gsn` now?
If no, it is not “breaking”.
And you can treat this prefixed names as a “last-resort” binding mechanism, identical to the existing variable resolution rules: when a name is not bound to anything else, try to find a native program with the same name.

**Comment by ForNeVeR** [comment]
What about `@`? It seems that you aren't allowed to call a function using `@`. Although it already have a meaning of splat operator. E.g. `get-childitem @ls` will now be ambiguous.

**Comment by BrucePay** [comment]
The ability to use ":gsn" was intentional. Per POSIX, any valid file name character can be used in a command name (where the legal filename characters varying between file systems). 
With respect to @gsn, you can always use quoting to disambiguate e,g, Get-ChildItem "@gsn".  
We do have an existing notation --% which tells parser to stop quote and expansion processing - we might be able to tweak that though it would be technically breaking but probably wouldn't really break anything, One other possibility is to simply keep using the .exe suffix syntax and give it the semantic that it looks for a native command without the suffix on *NIX systems e.g. 'gsn.exe' is mapped to "gsn"

**Comment by GeeLaw** [comment]
Start-Process abc I guess this should work if you have proper file association, or Invoke-Item. If those are not available on PowerShell for *nix that's bad.

**Comment by ForNeVeR** [comment]
Probably something like this could do the trick even without language changes (we need to add only one new command and convenience alias):

```powershell
function Call-NativeCommand ($cmd) {
    & (Get-Command -CommandType Application $cmd) @args
}

New-Alias ^ Call-NativeCommand
```

After that you'll be able to do the following:

```console
$ New-Alias curl echo # ensure that curl has an alias
$ curl --version # the alias got called
--version
$ ^ curl --version # the real binary got called
curl 7.28.1 (i386-pc-win32) [...]
```

**Comment by iSazonov** [comment]
[Bash workarounds](https://unix.stackexchange.com/questions/39291/run-a-command-that-is-shadowed-by-an-alias):
```
\ls
"ls"
'ls'
/usr/bin/ls
command ls
unalias ls; ls

**Comment by riotrah** [comment]
Hi, I hate to be that "updates" guy, but given the sheer amount of time and the abrupt drop-off in comms here (ie, nothing suggesting any show-stoppers etc), I can't tell if work has moved elsewhere without updating this issue, or if this is in fact the state of affairs still.

(fwiw I think the latter is alright, though I'd love to then know if there's a way the community can help move this forward that y'all can advise on)

**Comment by vexx32** [comment]
WG-Engine discussed this today.

We don't think the value of the proposed feature here meets the bar for making a potentially breaking language-level change. There are workarounds available that folks here have mentioned, and there are also arguments to be made about avoiding such name collisions in the first place whenever possible.

Thanks for submitting this request, but ultimately we feel this is not something that we could accept as a language change.
