### ISSUE TITLE
APPEXECLINK reparsepoints do not show target and link type

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#19760]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

No target shown for APPEXECLINK type reparse points:
See visual below

### Expected behavior

```console
Can see target of the APPEXECLINK reparsepoint
```

### Actual behavior

```console
No target shown
```

### Error details

```console
No error
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.3
PSEdition                      Core
GitCommitId                    7.4.0-preview.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/12820925/69fa7994-0e23-4a28-bb45-1adf644bff9c)

**Comment by mklement0** [comment]
While I agree that this would be helpful, please note the following comment from the .NET team, after they had talked to the Windows team; from https://github.com/dotnet/runtime/pull/58233#issuecomment-911971904

> We had a conversation with the Windows team that owns AppExecLinks. They explained that we are not supposed to care about the target path. AppExecLinks are meant to work seamlessly as any other executable. Hence why they never exposed the APIs that we were adding in this PR, and which PowerShell is also calling.

> ... 

> We also had a conversation with @SteveL-MSFT , @rjmholt, @daxian-dbw from the PowerShell team to let them know what the Windows people told us, so they make adjustments to their code if needed.

This led to the following (already merged) PR:

* #16044

So it sounds like simply removing the ` -> ` from the `Name` column for AppX reparse points is called for (the `l` in the `Mode` would still indicate the presence of a reparse point; that, combined with _not_ having a target displayed would then imply that the file at hand is an AppX reparse point).

**Comment by mklement0** [comment]
@daxian-dbw, I think there's still something actionable here:

* Fix the formatting data to omit the ` -> ` suffix for AppX reparse points - so that user won't wonder why there's nothing to the right of the arrow.

* Amend the documentation to explain why AppX reparse points have `l` in their `Mode` output column, yet do not list a target path.

**Comment by 237dmitry** [comment]
> Hence why they never exposed the APIs that we were adding in this PR, and which PowerShell is also calling.

fsutil.exe shows target:
```
fsutil reparsePoint query .\AppData\Local\Microsoft\WindowsApps\notepad.exe
```
_And this output can be parsed as string_

**Comment by mklement0** [comment]
@237dmitry, the point isn't whether the target _can_ be determined, the point is that _it shouldn't be attempted_, because it isn't officially supported, and the underlying data structure may change without notice, at least hypothetically.

Clearly, how to do it _is_ known, via _unsupported APIs_ that were _explicitly removed_ when the fact that they're unsupported came to light.

It's fair to assume that this code will _not_ be put back in, for the reasons stated.

Those who - despite the caveats - want to implement their own target-finding code nonetheless, can adapt the removed code or, less efficiently, can indeed parse the output from `fsutil reparsePoint query`.

The latter approach is used by a custom `Resolve-AppXExePath` function shown in [this Stack Overflow answer](https://stackoverflow.com/a/71758499/45375).

Note, however, that for _some_ AppX reparse points the target listed in the `fsutil reparsePoint query` output is a _generic launcher_: e.g., for `MicrosoftEdge.exe` the target is reported as `C:\Windows\system32\SystemUWPLauncher.exe`, even though the true ultimate target is `C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe`.

**Comment by daxian-dbw** [comment]
Opened #19794 to track the formatting change proposal.

> Amend the documentation to explain why AppX reparse points have l in their Mode output column, yet do not list a target path.

@mklement0 Can you please open a doc issue for this?

**Comment by mklement0** [comment]
@daxian-dbw, I've opened the following:

* https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10168

**Comment by mklement0** [comment]
@237dmitry, I think the decision by the Windows team is unfortunate, as it is helpful to be able to determine the path of the executable that is eventually launched, but this decision isn't related to open-source vs. closed-source (which Windows itself is).
