### ISSUE TITLE
[enhancement] unix-like shortcut for the last argument in a shell command

### ISSUE THREAD

**Issue by myyc** [PowerShell/PowerShell#1977]
bash and zsh have a handy `Esc .` shortcut  to get the last argument of a shell command, useful in circumstances like

```
rm /very/very/long/path/even/with/completion
sudo rm /very/very/long/path/even/with/completion
```

is there a way to get something similar on powershell?

**Comment by ygra** [comment]
Press the ↑ key to get the last executed command line (e.g. to prepend ` sudo`  like here).

The variable ` $$`  contains the last token of the last command, e.g. in your case `/very/very/long/path/even/with/completion`, so you could do ` sudo rm $$`.

You could easily create such a thing as a custom binding with PSReadLine.

**Comment by lzybkr** [comment]
PSReadline implements Emacs key bindings.  ESC . should work, Alt+. definitely does, I use it all the time.

**Comment by myyc** [comment]
Thanks both, I'm obviously extremely two days old to PowerShell, seems very nice so far.

**Comment by Carringguns** [comment]
Same here. But i didnt a different way. Copy and paste to itself. So far so good. Thanks guys
-------- Original message --------From: myyc <notifications@github.com> Date: 8/20/16  10:44 AM  (GMT-05:00) To: PowerShell/PowerShell <PowerShell@noreply.github.com> Subject: Re: [PowerShell/PowerShell] [enhancement] unix-like shortcut for the
  last argument in a shell command (#1977) 
Thanks both, I'm obviously extremely two days old to PowerShell, seems very nice so far.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PowerShell/PowerShell","title":"PowerShell/PowerShell","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PowerShell/PowerShell"}},"updates":{"snippets":[{"icon":"PERSON","message":"@myyc in #1977: Thanks both, I'm obviously extremely two days old to PowerShell, seems very nice so far."}],"action":{"name":"View Issue","url":"https://github.com/PowerShell/PowerShell/issues/1977#issuecomment-241203912"}}}
