### ISSUE TITLE
Unexpected Select-String behavior

### ISSUE THREAD

**Issue by lelik107** [PowerShell/PowerShell#19866]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

With version 7.2.12 (LTS) this command

`winget list | Select-String -Pattern 'Winrar'`
gives me highlighted result

> WinRAR 6.22 (64-разрядная)             RARLab.WinRAR                             6.22.0                      winget

while current version 7.3.5 gives me some strange symbols instead of highlighting.

> [7mWinRAR[0m 6.22 (64-разрядная)               RARLab.WinRAR                             6.22.0                      winget

I showed winget for example PS 7.3.5 does so with any external program. I used Select-String extensively while migrating
from openssl 1.1.1 to 3.1.1 (openssl windows x64 slproweb). And had same behavior.
It's same PC and same PS profile.

### Expected behavior

```console
Highlighted result
```

### Actual behavior

```console
Strange symbols
```

### Environment data

```powershell
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![PS7 2 12](https://github.com/PowerShell/PowerShell/assets/128335446/d1e48e52-2cd7-4cb6-873a-35197b5f44ca)
![PS7 3 5](https://github.com/PowerShell/PowerShell/assets/128335446/9356ad17-0294-46ff-8b51-2c6276555b7e)

**Comment by kilasuit** [comment]
I can repro this on 7.3.5 and have a few workarounds that may help though used this to search the package repo not installed packages as I don't use winget for install
This is due to returning ANSI Escape sequences which you can find out more about in [about_ansi_terminals help doc](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_ansi_terminals?view=powershell-7.2)

## Workaround 1 - Add -Raw to Select-String call

```powershell
winget search Winrar | Select-String -Pattern 'Winrar
```
Adding `-Raw` to Select-String like this `winget search Winrar | Select-String -Pattern 'Winrar -Raw' returns as expected 


![image](https://github.com/PowerShell/PowerShell/assets/6355225/a8edcc71-6cec-434d-9d65-e22239931c27)

## Workaround 2 - Change $PSStyle.OutputRendering

As per the above about doc - this is something that you can control
I found setting `$PSStyle.OutputRendering = 'PlainText'` removed the ANSI chars from output and showed the below which is slightly different to your desired output but I think acceptable compared to current output

![image](https://github.com/PowerShell/PowerShell/assets/6355225/4a5bd363-82f4-4ea7-8e5c-0472fdeab419)

I'm not sure when this became an issue but will check the PR's for when this occurred and find out for you.

Hope the workarounds help for now

**Comment by lelik107** [comment]
Thank you. I knew about -raw argument so I used exactly it. I don't use Windows Terminal but it's seems to work just fine as you clearly show. But why PS 3.5.x doesn't highlight the text in the system console is still a question.

**Comment by lelik107** [comment]
>     * [Selective disabling/re-enabling of VT support (ANSI escape sequences) is broken #19425](https://github.com/PowerShell/PowerShell/issues/19425)
You are right - this is the same thing just another example. It's a bit strange that it doesn't affect PS 7.2 LTS.

**Comment by lelik107** [comment]
OK, i'm closing the issue as a dublicate of https://github.com/PowerShell/PowerShell/issues/19425
