### ISSUE TITLE
select-string  is missing output when there's no match?-Quiet False

### ISSUE THREAD

**Issue by sgq1219** [PowerShell/PowerShell#19894]
### Summary of the new feature / enhancement

'a' | select-string -Pattern 'b' -Quiet -OutVariable s
what is $s?

### Proposed technical implementation details (optional)

$s -is [bool]

**Comment by fflaten** [comment]
Issue is kinda light on content. Summary: `-Quiet` is missing `False` output when there's no match?

**Comment by kilasuit** [comment]
Can confirm this affects LTS 7.2.12 (which docs show should return false) as well as 7.3.5 and 7.4.0.preview4

**Comment by kasini3000** [comment]
input：
string or array on left of pipe ，or select-string -file

output with -Quiet：
true，or null if not match

version：
psv5，psv7

What I mean is:
Mark bugs carefully. For PS5, this is a break change. 
This will result in inconsistent behavior between PSv5 and PSv7. It is also difficult to fix on PSv5 .

I personally suggest returning false ,and suggesting that everyone discuss and come to a conclusion.

**Comment by fflaten** [comment]
> Mark bugs carefully. For PS5, this is a break change. 

The issue is still a bug even though the fix would be a bucket 2 or 3 (most likely) breaking change, isn't it?

The expected output has two values, but only one is used unlike other cmdlets like `Test-Connection -Quiet`. So clear breach of public contract already.

> I personally suggest returning false

+1. It'd only be breaking for explicit null-check (and the broken false-check). I doubt anyone's using that, but maybe search through some GitHub repos to verify. 

This has been reported in 2011 in the old MSConnect-portal as mentioned here https://social.technet.microsoft.com/Forums/en-US/44d6e95d-1df7-4e16-b1e4-100a303d68e1/b-selectstring-a-quiet?forum=winserverpowershell so curious to why MS didn't fix it at that point. 

More importantly. This is a duplicate issue, see #16681 🙂

**Comment by sgq1219** [comment]
It's weird when testing
```
Describe "Select-string" {
    $a = 'a' | Select-String -Pattern 'b' -Quiet
    It ‘a’ {
        #$s | Should Be $false
        $s | Should Be 
    }
    $b = 'b' | Select-String -Pattern 'b' -Quiet
    It 'b'{        
        $s1 | Should Be $true
    }
}
```

**Comment by sgq1219** [comment]
> 问题在内容上有点轻。摘要：当不匹配时是否缺少输出？`-Quiet``False`

Thanks, I'm Chinese and don't speak much English

**Comment by sgq1219** [comment]
> Issue is kinda light on content. Summary: `-Quiet` is missing `False` output when there's no match?

Thanks, I'm Chinese and don't speak much English

**Comment by kilasuit** [comment]
> What I mean is: Mark bugs carefully. 

This is a bug **either** in the docs, which we can fix there or in the cmdlet, in which we can fix here, either way it's still a bug & is already raised as highlighted by @fflaten & as such this is a duplicate

**Comment by fflaten** [comment]
> It's weird when testing
> 
> ```
> 
> Describe "Select-string" {
> 
>     $a = 'a' | Select-String -Pattern 'b' -Quiet
> 
>     It ‘a’ {
> 
>         #$a | Should Be $false
> 
>         $a | Should Be 
> 
>     }
> 
>     $b = 'b' | Select-String -Pattern 'b' -Quiet
> 
>     It 'b'{        
> 
>         $b | Should Be $true
> 
>     }
> 
> }
> 
> ```

In Pester I'd replace it all with `'a' | Should -Match 'b'` 🙂
