### ISSUE TITLE
Powershell does not expand '~' for external programs

### ISSUE THREAD

**Issue by xudyang1** [PowerShell/PowerShell#20031]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```pwsh
PS: ~ > pwsh --version
PowerShell 7.3.6
PS: ~ > cd .config/nvim
PS: .config/nvim > nvim ~/.bashrc # or code ~/.bashrc
```
- The last command opens an empty `.bashrc` file in current directory in neovim/vscode

### Expected behavior

```console
`~` should be expanded to `$HOME`
```

### Actual behavior

```console
pwsh does not expand `~` for external command
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by xudyang1** [comment]
The bug was previously discussed in #10675 and #11386 and was fixed by #12386, but version 7.3.6 breaks it again.

**Comment by 237dmitry** [comment]
Could not be reproduced on either Windows (with the forward-slash  path separator) or Linux. For testing used micro editor on both platforms.

```
# on Windows
$ micro ~/Desktop/desktop.ini  # open
$ micro ~\Desktop\desktop.ini  # not open
Could not find user: user: unknown user \Desktop\desktop.ini

Press enter to continue
```
```
# on Linux
$ micro ~/.bashrc  # open
```

**Comment by xudyang1** [comment]
> 

Did you type `<Tab>` to expand the path manually? `<Tab>` works, but the literal string `~/../file` does not work without `<Tab>`. 

I even tested them (string, non-string, forward-slash, backslash) with an empty `$PROFILE` in pwsh, none of them worked.

**Comment by xudyang1** [comment]
I downloaded pwsh from Microsoft Store. Is it possible that the bug only appears in the store version?

**Comment by 237dmitry** [comment]
Just tried in other editor (internal Far manadger's editor `far -e` ) and behavior as in your issue. I think `micro` itself parse filepath. And your issue is right.

**Comment by mklement0** [comment]
@xudyang1, you pointed to the relevant issues, but the behavior isn't _broken_; rather, _on Windows_ `~` expansion was never officially implemented.

* #12386 implemented an _experimental feature_ (`PSNativePSPathResolution`), which, after the discussion in #13644, was _removed_ (#13734)
* You can still enable the experimental feature up to PowerShell 7.2.x, but it is no longer present since v7.3 

However, the ship hasn't fully sailed yet, given @SteveL-MSFT's comment [here](https://github.com/PowerShell/PowerShell/issues/13644#issuecomment-1244399036):

> maybe someone can take my PR and address the edge cases in the future

----

For now:

* Only _on Unix_ do you get `~` expansion, namely _if_ the `~` is _unquoted and followed by `/` (notably, this means that something like `~<username>` to refer to a given user's home dir. is _not_ supported - see #12387)

* On _Windows_, `~` expansion is _not_ implemented (nor is automatic globbing, though the latter sensibly so).

---

 Note that the scope of #12386 was larger than just `~` expansion: It tried to automatically convert paths based on _PowerShell_ drives  to _file system-native_ drives, given that native (external) utilities don't know about PowerShell drives; e.g. `temp:/foo.txt` would be converted to ` C:\Users\jdoe\AppData\Local\Temp\foo.txt`


If done _robustly_ - and fully doing so is ultimately impossible - PowerShell on Unix would benefit from this conversion too.

It's also worth noting that the never-introduced implementation in #12386 handled `~` on Windows _differently_ than the already-implemented `~` expansion on Unix: 
  * Unlike the Unix implementation, `~` _inside `"..."`_ was - surprisingly also expanded (only `'...'` quoting prevented the expansion).
  * E.g.,  `~` in `cmd /c echo "~"` _was_ expanded on Windows, whereas `/bin/echo "~"` on Unix is _not_.

**Comment by xudyang1** [comment]
> 

Thanks for the very detailed information! The `~` expansion in Windows should be a feature request instead of a bug.

**Comment by rkeithhill** [comment]
The Engine WG reviewed this issue today.  As @mklement0 notes above, the original `PSNativePathResolution` experimental feature, which implemented `~` expansion for native apps on WIndows, had a number of issues that resulted in it being removed.  Good news is that there is a [PR ](https://github.com/PowerShell/PowerShell/pull/20402) to bring back this support on Windows (`~` expansion for native apps is already available on Linux and macOS).
