### ISSUE TITLE
Tab completion replaces tilde with full path

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#20033]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

If you type `~\` then `Tab` the home directory symbol will be converted into the full provider path instead of retaining the `~`.

### Expected behavior

```console
# ~ is retained
```

### Actual behavior

```console
# Provider path is used
```

### Error details

```console
N/A
```

### Environment data

```powershell
7.4-preview4
```

**Comment by jhoneill** [comment]
This seems to be a damned if they do and damned if they don't thing. There is another recent issue complaining that external windows exes don't understand ~ in a path. Tab expanding ~ helps to ensure a working path gets sent to things but it annoyed me until I grew used to it.  There's probably a wider issue about making ~ work everywhere so that it can happily stay unexpanded by tab

**Comment by mklement0** [comment]
As noted, with `~` _on Windows_, when calling _external programs_, the behavior happens to be _somewhat_ of a blessing currently, as `~` isn't _automatically_ expanded on invocation.

  * See https://github.com/PowerShell/PowerShell/issues/20031#issuecomment-1653984644

In general, however, I agree that the behavior is unhelpful:
 * It is visually somewhat jarring.
 * It interferes with the ability to retain a path in its _abstract_ form, which is important if you want to copy the path to, say, sample code in a tutorial.

Note that the problem is more general, in that it also affects (environment) _variable-based_ paths; e.g., on Windows:

```powershell
# Pressing TAB at the end of this line expands to a literal, user-specific path; e.g.
#  'C:\Users\jdoe\AppData\Roaming\Microsoft\'
Get-ChildItem $env:APPDATA\Mi
```

**Comment by ThomasNieto** [comment]
For the external programs issue, I would expect PowerShell should expand ~ from a PSPath (Temp: / ~) to a provider path (C:\temp) when calling external programs since they don't know what a PSPath or may not have a concept of `~`.

This issue is specifically just for tab completion and command history so that what the user typed in is preserved. In my use case it creates a long command with the full path when I'm looking back and just need the relative path from `~`.

What prompted me originally to log this was when my custom PSDrive `GitHub` got changed to the provider path but found it was `TabCompletionPlusPlus` custom `TabExpansion2` that was messing with PSDrives and with no profile worked as expected but ~ still was changed.

**Comment by MartinGC94** [comment]
Strange, you say this is happening in preview 4 but this was actually fixed in the preview 4 release by this PR: https://github.com/PowerShell/PowerShell/pull/19489  
It works as expected on my PC:
<img width="550" alt="image" src="https://github.com/PowerShell/PowerShell/assets/42123497/651c8d60-f342-4965-a205-e3380660a1fb">

Have you tried loading PS without a custom profile?

**Comment by ThomasNieto** [comment]
@MartinGC94 you're right, I must have accidently ran pwsh stable when loading my test with no profile. I can't reproduce on 7.4-preview 4. I can still reproduce the example using environment variables though. Did you fix that as well in your PR?

**Comment by mklement0** [comment]
@MartinGC94, that's great news, but I can confirm @ThomasNieto's finding that _environment_ variables are still converted to literal paths.

Looking at your PR, I see that the issue at hand has a duplicate dating back to 2017:
* #5350

Once the environment-variable issue is also handled, both this and the aforementioned issue should be closed.

**Comment by MartinGC94** [comment]
Great, I was afraid there was some weird edge case I had missed. As for the variable replacement, I have some WIP code locally to fix that, I've just been too lazy to finish it. Expect to see a PR for that in the near future.

**Comment by ThomasNieto** [comment]
Closing as a duplicate of #5350.
