### ISSUE TITLE
Problem with "negative index notation"

### ISSUE THREAD

**Issue by RomingGnome** [PowerShell/PowerShell#20045]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When trying to use the "negative index notation" to get the last key from a hashtable, it doesn't work. I've tried this same example in both of the following versions of PS.

Example:
```
C:\Temp> $hash = [ordered]@{
>>     "a" = 1;
>>     "b" = 2;
>>     "c" = [ordered]@{
>>         "d" = 3;
>>         "e" = 4;
>>         "f" = [ordered]@{
>>              "g" = 5;
>>              "h" = 6;
>>         };
>>     };
>>     "i" = 7;
>> }
```
C:\Temp> $hash.Keys[-1]
C:\Temp> $hash.Keys
a
b
c
i

Why isn't $hash.Keys[-1] not working but "$hash.Keys | Select-Object -Last 1" does?

Here's the example function where it's being applied:

```
function Print-HashTable ($hash, $indent = 0) {
    $lastKey = $hash.Keys[-1] # This is supposed to store the last key of the hash table
	foreach ($key in $hash.Keys) {
		$value = $hash[$key]
		$spaces = " " * $indent
		#if ($value -is [hashtable]) {
		if ($value -is [System.Collections.Specialized.OrderedDictionary]) {
			Write-Host "$spaces$key :"
			Print-HashTable $value ($indent + 4)
		}
		else {
			Write-Host "$spaces$key :" -NoNewline
			Write-Host "$value"
		}
                if ($key -eq $lastKey) { # This is supposed to check if the current key is the last key
                        Write-Host "" # This will add a blank line only after the last parent key/value pair
                }
	}
}
```

### Expected behavior

```console
The desired output from "$hash.Keys[-1]" should be "i". The desired output from the function should be (where there's only a newline after the last key/value pair):

C:\Temp> $hash.Keys[-1]
i

C:\Temp> Print-HashTable $hash
a : 1
b : 2
c : 
  d : 3
  e : 4
  f :
    g : 5
    h : 6

i : 7
```

### Actual behavior

```console
C:\Temp> $hash.Keys[-1]

C:\Temp> Print-HashTable $hash
a : 1
b : 2
c :
    d :     3
    e :     4
    f :
        g :         5
        h :         6
i : 7
```

### Environment data

```powershell
>  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


>  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by IISResetMe** [comment]
PowerShell-based array indexing work on _lists_ - types that implement the `System.Collections.IList` interface.

`OrderedDictionary.Keys` does _not_ implement the `System.Collections.IList` interface, hence the unexpected behavior.

If you wrap the items from the key collection in an array, it'll work:

```
@($hash.Keys)[-1]
```

**Comment by RomingGnome** [comment]
> PowerShell-based array indexing work on _lists_ - types that implement the `System.Collections.IList` interface.
> 
> `OrderedDictionary.Keys` returns a `OrderedDictionaryKeyValueCollection` which does _not_ implement the `System.Collections.IList` interface, hence the unexpected behavior.
> 
> If you wrap the items from the key collection in an array, it'll work:
> 
> ```
> @($hash.Keys)[-1]
> ```

SOB!
I didn't even pay attention to that. Thanks for spotting that for me. Appreciate the help 👍

**Comment by IISResetMe** [comment]
Any time, happy to help clear that up! 

FWIW, for `OrderedDictionary` specifically, you _can_ use an array indexer directly on the dictionary itself (which may or may not help with your use case): 

```
PS ~> $dict = [ordered]@{A=123;B=456;C=789}
PS ~> $dict[-1]
789
```

**Comment by mklement0** [comment]
Let met add to @IISResetMe's comments:

The `.Keys` collection of  type `[ordered]` ([`System.Collections.Specialized.OrderedDictionary`](https://learn.microsoft.com/en-US/dotnet/api/System.Collections.Specialized.OrderedDictionary)) now implements the `IList` interface and therefore _does_ support indexing:

```powershell
 ([ordered] @{ foo=1; bar=2 }).Keys[1]   # -> 'bar'
```

(As an aside: other ordered / sorted dictionary types could benefit from the same improvement: see https://github.com/dotnet/runtime/issues/63537)

Unfortunately, however, using _negative_ indices doesn't currently work in the above scenario:

```powershell
 ([ordered] @{ foo=1; bar=2 }).Keys[-1]   # !! $null
```

* See #19167

---

As for the strange behavior of, e.g.. `@{ foo=1; bar=2 }.Keys[-1]` returning `foo` and `bar`, i.e. _all_ keys:

PowerShell treats an object that lacks its own indexer as if it were a _single object_ (the `.Keys` collection implements `IEnumerable` and `ICollection`, but not `IList`), and then applies PowerShell's "scalar indexing" to it, i.e. the ability to treat even a single object _as if it were a list_, just like  `(42)[-1]` is the same as `42`, for instance.

The `[-1]` in the above expression therefore has _no effect_.
If you were to use any index other than `0` or `-1`, you'd get _no_ output (`$null`), because a "single object" by definition has only index `0` aka `-1`.
