### ISSUE TITLE
VerbInfo class has public setters

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#20061]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The `VerbInfo` class has public setters for the public properties.

### Expected behavior

```console
Get-Verb | gm

   TypeName: System.Management.Automation.VerbInfo

Name        MemberType Definition
----        ---------- ----------
Equals      Method     bool Equals(System.Object obj)
GetHashCode Method     int GetHashCode()
GetType     Method     type GetType()
ToString    Method     string ToString()
AliasPrefix Property   string AliasPrefix {get;}
Description Property   string Description {get;}
Group       Property   string Group {get;}
Verb        Property   string Verb {get;}
```

### Actual behavior

```console
Get-Verb | gm

   TypeName: System.Management.Automation.VerbInfo

Name        MemberType Definition
----        ---------- ----------
Equals      Method     bool Equals(System.Object obj)
GetHashCode Method     int GetHashCode()
GetType     Method     type GetType()
ToString    Method     string ToString()
AliasPrefix Property   string AliasPrefix {get;set;}
Description Property   string Description {get;set;}
Group       Property   string Group {get;set;}
Verb        Property   string Verb {get;set;}
```

### Error details

```console
N/A
```

### Environment data

```powershell
7.4-preview4
```

**Comment by SeeminglyScience** [comment]
The Engine WG reviewed this and agreed that the setters do not need to be public.

**Comment by ThomasNieto** [comment]
I'll get a PR created for this.

**Comment by StartAutomating** [comment]
I mentioned this on the PR as well:

I don't see any benefit here, and I see that it takes away what could be useful (under some circumstances)

The two that jump right into mind are:

* Providing an augmented internal description:  e.g. "In company X, we prefer to not make every command an Invoke-, so please consider use of this verb carefully"
* Providing a preferred internal prefix

The other "gotcha" is that it makes verbs a bit harder to expand than they currently are.

So, since this would be a breaking change and there's not an attached "must do this because....", let's just not.

**Comment by ThomasNieto** [comment]
@StartAutomating in your examples, how is the organization persisting the verb description or other metadata? These properties do not modify PowerShell's state with the new values. The way that comes to mind on how your example works is that the org creates a proxy function with the new values, but this could also be accomplished by using a PSObect with the appropriate PSTypeName.

I also don't understand how it prevents adding verbs in the future. `Get-Verb` just pulls the values from a static list. Its not like you can create a new `VerbInfo` and import into PowerShell.

**Comment by StartAutomating** [comment]
@ThomasNieto in the cases where I've seen customers doing this, they normally enforce a profile for all users that makes this sort of a change.

I've advised exactly what you've said (basically, build your own "Get-Verb")

(I should also note that I wrote the original Get-Verb in PowerShell v2 timeframe)

There are a few high level "why nots" I see here:

1. Existing customers use this functionality to help set an internal drumbeat (they're not my favorite customers, but they exist)
2. It doesn't positive impact functionality (nothing new will work because this changes, some things will break)
3. It would be an additional exacerbation of the "verb ivory tower" problem in PowerShell (many people/orgs dislike how sacrosanct verbs are in PowerShell, and bristle at the difficulty in getting new verbs approved, especially when it's made more technically opaque)

All of this stated, while I feel strongly that this doesn't need to happen, I don't feel so strongly as to get into a drawn-out debate over it.

(aka, if you choose to do it anyways, that's the WG's decision, and I won't keep chiming in here)

FWIW, if we wanted to move in a better direction, I think it might be more useful to allow custom verbs to be constructed and easily submitted to the working group.

This would let the type of customer that already sometimes banhammers PowerShell over this point have it "their way in their org", while keeping a clean/happy path to adding new verbs to the ecosystem.

**Comment by kilasuit** [comment]
This probably should be fixed with adding a new mechanism for initialising a custom group/s of verbs that orgs can make use of internally as dynamically as they want to & not need them to be defined as part of the core list of verbs that all other users must make use of & is in my opinion the best middle ground here as can also potentially be shipped as part of a module that adds these additionally needed verbs, what's your thoughts on that as a way forward @StartAutomating that could also allow #20427 to go through too?
