### ISSUE TITLE
[environment]::OSVersion.Version returns a wrong result of the OS

### ISSUE THREAD

**Issue by Golapadeog** [PowerShell/PowerShell#2009]
# Steps to reproduce
`[environment]::OSVersion.Version`

# Expected behavior
Should be return the OS Version

# Actual behavior
- Windows 10 with PowerShell 5 : 10.0.10536.0
- Windows 10 with PowerShell 6 : 6.2.9200.0
- Ubuntu : throw an error

# Potential error of the problem
The method used by PowerShell must be GetVersionInfoEX ([depreciated since Windows 8.1](https://msdn.microsoft.com/en-us/library/windows/desktop/dn302074(v=vs.85).aspx)) instead of GetVersionInfo

# Environment data
```
PS C:\> $PSVersionTable

Name                           Value
----                           -----
CLRVersion
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
PSVersion                      6.0.0-alpha
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
PSEdition                      Core
GitCommitId                    v6.0.0-alpha.9
BuildVersion                   3.0.0.0
```

**Comment by GeeLaw** [comment]
Nah the reason is NOT using GetVersionEx. It works fine in Windows 10. You're referring to a right documentation though. The exe of that PowerShell *lacks manifestation*, as you can see it is reporting Windows 8.1.

GetVersionInfo seems not to be a Win32 API, can you find a documentation on it? As far as I know, Microsoft only recommends using version helper functions (hmmm I'd have to say many programmers aren't logical enough to correctly check version numbers so MS is providing helper functions haha). And for getting the native system information, use GetFileVersionInfo. GetVersionEx returns the compatibility mode version number and if the app is not manifested for Windows 8.1/10, VersionLie shim gets in.

**Comment by daxian-dbw** [comment]
`[environment]::OSVersion.Version` is actually calling .NET Core code:
```
PS C:\> [environment]::OSVersion.GetType().Assembly

GAC    Version        Location
---    -------        --------
       v4.0.30319     C:\Users\dongbow\Downloads\powershell-6.0.0-alpha.9\System.Private.CoreLib.ni.dll

PS C:\>
PS C:\> [environment].Assembly

GAC    Version        Location
---    -------        --------
       v4.0.30319     C:\Users\dongbow\Downloads\powershell-6.0.0-alpha.9\System.Private.CoreLib.ni.dll
```
System.Environment::OSVersion is not exposed in [.NET Core contract](https://docs.microsoft.com/en-us/dotnet/core/api/system.environment), but it's obviously still preserved in the runtime assembly.

.NET Core team will bring back OSVersion and other public surface from `System.Private.Corelib` in .NET Core 1.1 release, see [dotnet-core#6006](https://github.com/dotnet/coreclr/pull/6006)

**Comment by SteveL-MSFT** [comment]
we are doing work to expose OS info in psversiontable #1635 , this is already tracked in dotnet repo

**Comment by mklement0** [comment]
Just a heads-up that, at least as of this writing, while [dotnet-core#6006](https://github.com/dotnet/coreclr/pull/6006) does intend to bring `System.Environment`'s `OSVersion` back:

* its implementation is [not cross-platform yet](https://github.com/dotnet/coreclr/blob/cdff8b0babe5d82737058ccdae8b14d8ae90160d/src/mscorlib/src/System/Environment.cs#L398), 

* and is furthermore currently based on calls to the deprecated-since-Windows-8.1 `GetVersion` and `GetVersionEx` Windows API functions, which as has been pointed out, do _not_ report the true OS version.

  * @GeeLaw: The Core `powershell.exe` does have an (embedded) manifest too, but one without entries targeting specific Windows version, hence it is "stuck" at reporting Windows 8 (6.2), as you state.  
That said, even the _Windows_ PowerShell `powershell.exe`, with its Windows-version-targeting entries [would be lied to _in the future_](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724451(v=vs.85).aspx), _if_ it used `GetVersion(Ex)` _directly_:  
 
  > "Once an application is manifested for a given operating system version, GetVersionEx will always return the version that the application is manifested for in future releases." - 

  * However, it seems that the .NET _Framework_ (I presume) [works around this](https://github.com/dotnet/coreclr/blob/5ec5c2f859f8ff1dc99a2bb95b640b82d2937cc8/src/classlibnative/bcltype/system.cpp#L665):
> /*
> * SystemNative::GetOSVersion - Fcall corresponding to System.Environment.GetVersion
> * It calls clr!GetOSVersion to get the real OS version even when running in 
> * app compat. Calling kernel32!GetVersionEx() directly will be shimmed and will return the
> * fake OS version. In order to avoid this the call to getVersionEx is made via mscoree.dll.
> * Mscoree.dll resides in system32 dir and is never lied about OS version.
> */
 
   * It sounds like .NET _Core_, which I presume doesn't use `mscoree.dll`, cannot take advantage of this, which is why the Core edition reports the fake version.

* It is hard to believe, but [the method that the official docs recommend for determining the _true_ Windows version number](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724429(v=vs.85).aspx) is:

> call the GetFileVersionInfo function on one of the system DLLs, such as Kernel32.dll, then call VerQueryValue to obtain the \\StringFileInfo\\<lang><codepage>\\ProductVersion sub-block of the file version information."

To put it in PowerShell terms (Windows-only):  
`(Get-FileVersionInfo $env:SystemRoot\System32\kernel32.dll).ProductVersion`
