### ISSUE TITLE
why are subfolders not evaluated even though force and recursive are used

### ISSUE THREAD

**Issue by ltappe007** [PowerShell/PowerShell#20138]
### Summary of the new feature / enhancement

This is my command:
Get-ChildItem -Path C:\pdm2\db3\*.* -Recurse -Force -name >> c:\temp\test8.txt

only db3 files are listed not the subfolderfiles

**Comment by mklement0** [comment]
Good find.

* With a `-Path` argument, the wildcard expression at its end (`db3*.*`) is by default recursively looked for on every level of the subdirectory hierarchy with `-Recurse`

  * As an aside: This default behavior can be highly problematic, as it also applies to paths that end in _literal_ names; see:
    * #5699

* The bug is that the addition of `-Name` seemingly deactivates `-Recurse` altogether.

---

The workaround is to specify the wildcard expression via `-Filter` (`-Include` would work too, but is slower, like your original attempt):

```powershell
Get-ChildItem -LiteralPath C:\pdm2 -Filter db3*.* -Recurse -Force -name >> c:\temp\test8.txt
```

This not only speeds up the command, but is arguably conceptually clearer.

**Comment by TobiasPSP** [comment]
The workgroup has reviewed this. The current behavior is by design however this design may not be appropriately documented and lead to confusion. When wildcards are used in -Path, only matching items are evaluated. This includes subfolders for recursive operations. Since the underlying behavior cannot be changed without severe backwards compatibility impact, the workgroup suggests adding distinct examples to documentation that addresses the behavior and provides guidance.

**Comment by mklement0** [comment]
Since I got myself confused in my earlier analysis, let me try a succinct summary of the status quo:

* `Get-ChildItem -Recurse` with a `-Path` argument that _ends in a wildcard pattern_ exhibits different behaviors _depending on whether or not `-Name` is present_.

  * _Without_ `-Name`, recursion is _unconditional_: the pattern is applied at all levels of the target directory's subtree - _whether or not it matches among the immediate children_ of the target directory.

  * _With_ `-Name`, recursion is _conditional_: 
    *  The pattern is _initially_ only applied to the _immediate children_ of the target directory, and recursion - if any - is applied to the _results_.
    * This means that only matching _directories_ - if any - are recursed into (given that _files_ are leaf components).

  * While the decision may be not to change this behavior, it is unlikely that is _by design_, given both the inexplicable inconsistency and the obscurity of the behavior with `-Name`.

* Separately - and it is only due to the above inconsistency that the following pitfall does _not_ apply with `-Name` - what makes combining `-Path` with `-Recurse` so treacherous is that recursion happens even if the last path component is a _literal_ name (doesn't contain wildcard characters) _that happens NOT to match among the immediate children_, which is the subject of #5699:
  *  E.g. assuming a current directory that does _not_ have a `node_modules` subdirector (using a positionally implied `-Path` argument):
      *  `Get-ChildItem .\node_modules -Recurse`  - due to the _absence_ of an _immediate_ subdir. by that name - searches for `node_modules` _at every level of the subtree_.
         * In other words: the semantics of the command are completely different depending on whether an _immediate_ subdirectory with the given, literal name _happens to be present or not_:
           * If one is present, _it_ - and only it - is recursed into and its _content_ is enumerated (unconditionally, irrespective of name).
           * If one is _not_ present, matching items are looked for _on every (deeper) level of the subtree_ and any matching _directories_ are returned as _themselves_ rather than having their content enumerated - with potentially disastrous consequences if the command is piped to `Remove-Item`.
      *  `Get-ChildItem .\node_modules -Recurse -Name` does _not_ - it complains about a missing subdir. (or file) by that name in the current dir. and terminates.

  *  With a literal last path component that matches a _file_, the behavior is:
     *  More predictable, but only _without_ `-Name`:
        *  `Get-ChildItem Makefile -Recurse` finds all `Makefile` files _in the entire subtree_ - whether one is present among the immediate children or not.
     * Buggy _with_ `-Name`:
        * `Get-ChildItem Makefile -Recurse -Name`
          *  reports an error and terminates if there's _no_ `MakeFile` among the immediate children (this is consistent with the overall inconsistency, if you will).
          * is a _quiet no-op_ if there _is_ a `MakeFile` among the immediate children: see #20687

**Comment by mklement0** [comment]
While the summary in my previous comment is largely correct, there is a conceptual clearer way of framing it, which I've now done in
* https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10640#issuecomment-1813197594

**Comment by TobiasPSP** [comment]
Would it be safe to assume that not using wildcards in -Path and only limit the use of wildcards in -Filter or -Include resolves most of the confusing results while at the same time not limiting the user to find what he or she wants to?

I am on the same page with you that there are a lot of confusing results possible when using wildcards in -Path. Reasons for that are historical. The practical takeaway given the ubiquitous use of Get-ChildItem is that there is no feasible way at this time to change anything in the logic without causing severe backwards compatibility issues.

So in order to improve things for users and make results more predictable, I am wondering whether improvements to documentation could be a good step, essentially advising users to not use wildcards with -Path. It is my impression that most of the unexpected results stem from the way how Get-ChildItem handles wildcards in -Path.

Could you mark or list those findings of yours that still apply when NO wildcards are used in -Path? Many thanks!

**Comment by mklement0** [comment]
> essentially advising users to not use wildcards with -Path. It is my impression that most of the unexpected results stem from the way how Get-ChildItem handles wildcards in -Path.

I agree (except that isn't just _wildcards_ that are the problem), and I have already suggested that such advice be given in the documentation: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10640#issuecomment-1813212516

I see that you've since commented there too, so let's continue the conversation there.
