### ISSUE TITLE
`Trace-Command` should default to PSHost

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#20158]
### Summary of the new feature / enhancement

Currently, the user has to explicitly use `-PSHost` to see output on the console.  However, a user can run `Trace-Command` and not see any output and needs to look at help to see they should have specified the `-PSHost` switch.  To preserve some app compat, we should make `-File` mutually exclusive to default PSHost so it would still need to be specified to get both.

Also, `-Name` is mandatory and will prompt.  We should default to `*` so that the user sees all possible output and can decide to filter out what they don't need.  At the prompt, they can't figure out what value to provide other than `*`.

This means more users are likely to use this cmdlet as it simplifies it to:

```powershell
trace-command { get-help }
```

Whereas today, you'd do something like:

```powershell
trace-command -pshost -name * {get-help}
```

**Comment by TobiasPSP** [comment]
Cmdlet WG has reviewed and agrees that outputting to the host should be default behavior when no output file is specified. 
The parameter -Name though should remain unchanged and be kept mandatory. This parameter has autocompleters and is easily discoverable. Defaulting to * might hurt user experience due to the overwhelming mass of output that this default value can trigger, even more so in the future when tracing detail possibly is further expanded.
