### ISSUE TITLE
Passing native command output with CRLF line endings to powershell creates empty strings

### ISSUE THREAD

**Issue by crnobog** [PowerShell/PowerShell#20284]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Write a small C++ program such as the following:

```
#include <cstdio>

int main(int argc, char** argv*
{
	wprintf(L"Line One\r\n");
	wprintf(L"Line Two\r\n");
	wprintf(L"Line Three\r\n");
	
	return 0;
}
```

Compile it and run it, piping the output to powershell's foreach with `% { $_ }` or with a command such as `measure -sum -property length`

### Expected behavior

```console
The for-each output should write 3 lines.
The measure command should give a count of 3.
```

### Actual behavior

```console
The for-each output writes 6 lines, three of them blank.
The measure command gives a count of 6.
The same empty lines are passed to other commands such as ripgrep.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.8
PSEdition                      Core
GitCommitId                    7.2.8
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
The behavior is by design, although it isn't obvious:

You're outputting wide strings, whereas PowerShell uses the character encoding stored in `[Console]::OutputEncoding` to decode output from native programs.

It is the - otherwise invisible - `NUL` bytes that result from this mis-decoding that cause the extra newlines.

If you (temporarily) set `[Console]::OutputEncoding = [System.Text.Encoding]::Unicode`, PowerShell will interpret the output correctly.

**Comment by crnobog** [comment]
That's interesting, I had assumed it was just the line encodings because if I change the program to: 

```
	wprintf(L"Line One\n");
	wprintf(L"Line Two\n");
	wprintf(L"Line Three\n");
```
Then the powershell pipe just contains three strings. 
Similarly if I change it to 
```
   	printf("Line One\r\n");
	printf("Line Two\r\n");
	printf("Line Three\r\n");
```
I get three strings. 
And that's the same regardless of whether I compile the program with "unicode" or "multibyte" strings in Visual Studio.

**Comment by mklement0** [comment]
The mojibake comes from switching to `printf`, i.e. a single-byte character encoding.
`[Console]::OutputEncoding = [System.Text.Encoding]::Unicode` is only appropriate for native programs that produce wide-character output (e.g. for distro-management `wsl.exe` commands such as `wsl --list`, assuming `$env:WSL_UTF8=1` isn't set).

`[Console]::OutputEncoding` must _match_ whatever the native program in question actually uses to encode its output.

You can visualize the original mis-decoding as follows: ``(wsl --list) -replace "`0", '<NUL>'``

Yes, it is only the `\r` (CR) characters that produce the extra-newline problem, because the mis-decoding cause PowerShell to see the original `\r\n` (CRLF) _sequences_ as _non-adjacent_ CR and LF characters (due to the interspersed `NUL` chars.), and given that PowerShell recognizes CR alone, LF alone, as well as CRLF as newlines, _two_ newlines are the result.

You can read more about this in [this Stack Overflow answer](https://stackoverflow.com/a/64525491/45375).

**Comment by crnobog** [comment]
This explanation still doesn't fully make sense to me because if I change the program to printf, do _not_ change the console output (by default it has set itself to ibm437) and run it, I get the following: 

```
❯ .\x64\Release\CppTest.exe | %{ $_ }
Line One

Line Two

Line Three

❯ .\x64\Release\CppTest.exe
Line One
Line Two
Line Three
```

To try and confirm the encoding of the output, I piped the program to a text file in cmd rather than powershell and found that my lines actually end with 0xD 0xD 0xA so perhaps my issue is actually with the CRT rather than with powershell - it seems like it's expanding \n into \r\n for me, so my program ends up emitting \r\r\n.

**Comment by mklement0** [comment]
Speaking in the abstract: if you think there is a problem with PowerShell, after all, you shouldn't close your issue.

To offer a general pointer: _direct-to-console_ output usually _bypasses_ encoding problems and _prints_ correctly.

As such, examining _direct console (terminal)_ output on Windows won't tell you whether there'll be character-encoding problems if you _capture or redirect_  the output, such as by piping it to `%` (`ForEach-Object`)

**Comment by crnobog** [comment]
I don't think it's an issue with powershell now that I've seen the actual bytes I write to a file from cmd - I've definitely seen other programs react strangely to the sequence \r\r\n and e.g. treat the first \r as an extra newline.
