### ISSUE TITLE
multiple wildcards

### ISSUE THREAD

**Issue by spaette** [PowerShell/PowerShell#20287]
### Steps to reproduce

```
$ cd /tmp
$ curl -s https://julialang-s3.julialang.org/bin/linux/x64/1.9/julia-1.9.3-linux-x86_64.tar.gz \
> | tar -xz -C ~
$ pwsh
PowerShell 7.3.6
PS /tmp> 
```

### Expected behavior

```
PS /tmp> gci -Path $home\julia-1.9.3\share\julia *.jl -File 

    Directory: /home/soeren/julia-1.9.3/share/julia

UnixMode   User             Group                 LastWriteTime           Size Name
--------   ----             -----                 -------------           ---- ----
-rwxr-xr-x soeren           soeren              8/24/2023 10:36           3732 julia-config.jl

PS /tmp> 
```

### Actual behavior

```
PS /tmp> gci -Path $home\julia*\share\julia *.jl -File     
PS /tmp> 
```

### Error details

No output using the two wildcards.

### Environment data

```
PS /tmp> $PSVersionTable                                   

Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Linux 5.15.117 #1 SMP PREEMPT Thu Jun 22 15:39:49 CDT 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /tmp> 
```

**Comment by mklement0** [comment]
When `Get-ChildItem` finds a directory _via wildcard matching_, it reports the directory _itself_, rather than _its children_.

Therefore, the second wildcard expression (which implicitly binds to `-Filter`) applies to the _directory_ path, and results in no output.

If you make the second wildcard pattern _part of your `-Path` argument_, the problem goes away:

```powershell
# Note: "*.jl" is now part of the -Path argument.
gci -Path $home\julia*\share\julia\*.jl -File
```

Another way to solve the problem is to chain two `Get-ChildItem` calls:

```powershell
# Note: "*.jl" is now part of the -Path argument.
gci -Path $home\julia*\share\julia | gci -Filter *.jl -File
```

**Comment by spaette** [comment]
Base is not read-only

`https://github.com/JuliaLang/julia/issues/50810#issuecomment-1718415686`

```
gci -Path $home\AppData\Local\Programs\Julia-1.9.3\share\julia *.jl -r -File | % {$_.IsReadOnly=$True}
```

If factually used and/or modified by the julia/juliaup devs my preference would be to omit the version in the above.

The content after the pipe with `%` I located via an online search which however didn't accompany an explanation.

```
sl $home\AppData\Local\Programs\Julia-1.9.3\share\julia; gci * -r -File | % {$_.IsReadOnly=$True}
```

I'm unclear whether under the share\julia tree subdirs the .dll and .ji files should not have thier perms changed.

In that context at least on Un*x it is unusual to locate .so files under /usr/share.

Emacs of course had byte-compiled .elc files there, and emacspeak has a single .so file, tclespeak.so, located there.

**Comment by mklement0** [comment]
My previous comment tried to explain why the `gci -Path $home\julia*\share\julia *.jl -File` command in your initial post produces no output, and how to fix that.

I'm unclear on how your follow-up comment relates to that. 

Note that if you add `-Recurse` (`-r`) to your original command in order to look for `*.jl` files _recursively_, it would work without the suggested workarounds.

If you want to include _multiple_ filters, replace `*.jl` (implied `-Filter `*.jl`) with, say, `-Include *.jl, *.dll`

**Comment by spaette** [comment]
This works well, as I would presume using the wildcard for a specific file type.

```
PS /tmp> gci -Path $home/julia*/share/julia | gci -fi * -r -File | % {$_.IsReadOnly=$True}                  
PS /tmp> 
```

And I appreciate your mention of `-Include` followed by a comma separated list of file types!

**Comment by mklement0** [comment]
Glad to hear it helped, @spaette.
Final thought: to make `Get-ChildItem` include _hidden_ items too, add `-Force`.

**Comment by spaette** [comment]
Whether to convert the julia files to read-only and which file types to convert is not my call.

In the share\julia subdirectory tree there are some .ci and .github directories and .gitignore and .*.yml files.

**Comment by spaette** [comment]
Settled on this which doesn't affect the `.dll` and `.ji` files under the share\julia\compiled subdirectory tree.

`gci -Path $home\julia*\share\julia -ex compiled | gci -fi * -r -File | % {$_.IsReadOnly=$True}`
