### ISSUE TITLE
7.3.7 not available through Windows Update (WSUS)

### ISSUE THREAD

**Issue by Jelle-Dirk** [PowerShell/PowerShell#20342]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

7.3.7 is not available through WSUS
https://www.catalog.update.microsoft.com/Search.aspx?q=powershell

### Expected behavior

```console
7.3.7 being available through WSUS
```

### Actual behavior

```console
Update is not available
```

### Environment data

```powershell
na
```

### OS Data

```powershell
na
```

### Windows update log

```markdown
na
```

**Comment by kilasuit** [comment]
This takes roughly about a week for it to be made available via Microsoft Update services so should become available in the next few days.

**Comment by Jelle-Dirk** [comment]
Thank you for taking the time!

Would it be possible to make that shorter?
What if there's a CVE 9 vulnerability, do we then have to wait a week too for the update to become available through WSUS?

**Comment by kilasuit** [comment]
> Would it be possible to make that shorter?
> What if there's a CVE 9 vulnerability, do we then have to wait a week too for the update to become available through WSUS?

As far as I know (not a PowerShell Team Member) this is not currently possible as things stand, at least not via WSUS due to how update publishing to Microsoft Update & then out to the world works.

However there are other ways to install a critical update if there was a need to, including via a installer script of some sorts like some of the ones that are maintained in this repo. 


You however can make use of the installer files and push out your own instll. 
The reason why it takes time via Microsoft Update, is due to how it goes through additional testing.

You can download the installer and install it manually if you need to

**Comment by Jelle-Dirk** [comment]
Yes, it's possible to push the update through other means, but that means in an enterprise setting you can't rely on WSUS to update Powershell in a timely fashion because it takes a week before the update becomes available.
