### ISSUE TITLE
powershell start-process issue

### ISSUE THREAD

**Issue by QingyuQingxue** [PowerShell/PowerShell#20382]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Issue：using start-process does not run the specified powershell script properly if there are spaces in the file path or filename.

### Expected behavior

```console
PS> start-process powershell "D:\tools\t st.ps1" –verb runAs
Ability to run D:\tools\t st.ps1 with administrator privileges

PS> start-process powershell "D:\too ls\tst.ps1" –verb runAs
Ability to run D:\too ls\tst.ps1 with administrator privileges
```

### Actual behavior

```console
PS> start-process powershell "D:\tools\t st.ps1" –verb runAs


PS> start-process powershell "D:\too ls\tst.ps1" –verb runAs
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.25951.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.25951.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by QingyuQingxue** [comment]
I am very sorry, I will test it in the latest release.

**Comment by QingyuQingxue** [comment]
I am very sorry, I will test it in the latest release.

**Comment by QingyuQingxue** [comment]
Hello，powershell 7has the same problem。

Name                           Value
----                           -----
PSVersion                      7.3.7
PSEdition                      Core
GitCommitId                    7.3.7
OS                             Microsoft Windows 10.0.25951
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by 237dmitry** [comment]
`-Verb Runas` works as expected:

![Screenshot 2023-09-27 125200](https://github.com/PowerShell/PowerShell/assets/78153320/a5e036aa-83f1-4907-b799-83ddc02eb082)

**Comment by QingyuQingxue** [comment]
> `-Verb Runas` works as expected:
> 
> ![Screenshot 2023-09-27 125200](https://user-images.githubusercontent.com/78153320/270939444-a5e036aa-83f1-4907-b799-83ddc02eb082.png)

Thanks, I'm sorry to take up your time. Have a Nice Day!

**Comment by QingyuQingxue** [comment]
> `-Verb Runas` works as expected:
> 
> ![Screenshot 2023-09-27 125200](https://user-images.githubusercontent.com/78153320/270939444-a5e036aa-83f1-4907-b799-83ddc02eb082.png)

Hello, there still seems to be some problems when there are spaces in the file path.
![image](https://github.com/PowerShell/PowerShell/assets/75031753/3d02b5e4-9c04-4ecc-b361-3fcbe6d7690f)

**Comment by 237dmitry** [comment]
```
Start-Process  -FilePath pwsh.exe -ArgumentList '-file "Path\with spaces\file.ps1"' -Verb Runas
Start-Process  -FilePath pwsh.exe -ArgumentList "-file ""Path\with spaces\file.ps1""" -Verb Runas
```

**Comment by mklement0** [comment]
It is implied by @237dmitry's comments, but to spell it out:

With `powershell.exe`, you need to use the `-File` [CLI](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe) parameter in order to target a script path enclosed in `"..."` only.

While `pwsh.exe`, the PowerShell (Core) CLI, now defaults to `-File`, in _Windows PowerShell_ (`powershell.exe`) `-Command` (`-c`) is the default.

`-Command` removes unescaped `"` chars. on the command line and _then_ interprets the result as PowerShell code, which in your case means that verbatim, unquoted `D:\tools\t st.ps1` is executed, which predictably fails.

If you did want to use (implied) `-Command`, you'd have to _escape_ the `"` chars. as `\"` _and_ you'd have to use `&`, the call operator in order to treat the resulting double-quoted string as a _command_, i.e. to execute the file it refers to.

```powershell
start-process powershell '& \"D:\tools\t st.ps1\"' –verb runAs
```

However, script-file invocation is best done with `-File`, not just to avoid the quoting problem, but because it allows you to pass arguments to the script without subjecting them to evaluation by PowerShell (when doing so, it's best to specify them as part of a _single_ string passed to `-ArgumentList`, as shown in @237dmitry's most recent comment, to avoid the bug descrribed in #5576).

**Comment by QingyuQingxue** [comment]
Thank you very much for your answer. As a matter of fact, I was writing a script file and found that there was an execution error, and through troubleshooting I located that it had to do with spaces in the file path. In the code, the file path is a variable: $PSCommandPath .
I will make further changes based on the information I have obtained so far. If you are interested in my code, it would be my pleasure. Thank you again.
May you have a wonderful day.


if( [Security.Principal.WindowsIdentity]::GetCurrent().Groups -contains 'S-1-5-32-544' )
{
}
else
{
    start-process pwsh $PSCommandPath –verb runAs
    break
}

cd $PSScriptRoot

Write-Output "Hello,world!"

**Comment by mklement0** [comment]
Glad to hear it, @QingyuQingxue.
For discoverability of your issue, could you please fix the typo in its title? (`start-progress` -> `start-process`)

I forgot to mention that #5576 does come into play here, after all, if you use `start-process pwsh $PSCommandPath –verb runAs`, and you (unfortunately) must use ``start-process pwsh "`"$PSCommandPath`"" –verb runAs`` instead, i.e. you must use _embedded_ double-quoting.

**Comment by QingyuQingxue** [comment]
@mklement0 Yeah, I've made the changes and tried to run it and it's perfect now.
Thank you very much for your help. I hope to have the opportunity to learn more from you in the future.
