### ISSUE TITLE
Unexpected behaviour when using Set-Strict latest and $PScmdlet.ShouldProcess

### ISSUE THREAD

**Issue by Nippius** [PowerShell/PowerShell#20393]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hi,

I'm learning how to use $PSCmdlet.ShouldProcess() by following this guide: [Everything you want to know about ShouldProcess](https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-shouldprocess?view=powershell-7.3) and there's a section about implementing the -Force switch so that it behaves correctly with ShouldProcess.

Following the guide I created a function like this:

```
function Test-Confirm { 
    [CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'high')]   
    param (        
        [switch]$Force    
    )       
    begin { 
        if ($Force -and -not $Confirm) 
        { $ConfirmPreference = 'None' } 
    }       
    process {
        if ($PSCmdlet.ShouldProcess("Hello"))
        { Write-Host "World" } 
    }  
}
```

This works as expected when Set-Strict mode is not used but when strict mode is enabled, I get an error saying "The variable '$Confirm' cannot be retrieved because it has not been set.".

I understand why the error happens but I'm not sure if it should happen? I have no control over the $Confirm parameter so it pretty much means that I'm can't support ShouldProcess and -Force and have the function work in strict mode.

### Expected behavior

```console
PS C:\Users\tiago> Test-Confirm -Force
World
```

### Actual behavior

```console
PS C:\Users\tiago> Test-Confirm -Force
InvalidOperation:
Line |
   7 |          if ($Force -and -not $Confirm)
     |                               ~~~~~~~~
     | The variable '$Confirm' cannot be retrieved because it has not been set.

Confirm
Are you sure you want to perform this action?
Performing the operation "Test-Confirm" on target "Hello".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): l
```

### Error details

```console
Exception             :
    Type        : System.Management.Automation.RuntimeException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The variable '$Confirm' cannot be retrieved because it has not been set.
            HResult : -2146233087
        TargetObject          : Confirm
        CategoryInfo          : InvalidOperation: (Confirm:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : VariableIsUndefined
        InvocationInfo        :
            ScriptLineNumber : 7
            OffsetInLine     : 30
            HistoryId        : -1
            Line             :         if ($Force -and -not $Confirm)

            PositionMessage  : At line:7 char:30
                               +         if ($Force -and -not $Confirm)
                               +                              ~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at Test-Confirm<Begin>, <No file>: line 7
                                at <ScriptBlock>, <No file>: line 1
    TargetSite  :
        Name          : GetVariableValue
        DeclaringType : System.Management.Automation.VariableOps, System.Management.Automation, Version=7.3.7.500,
Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The variable '$Confirm' cannot be retrieved because it has not been set.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.VariableOps.GetVariableValue(VariablePath variablePath, ExecutionContext
executionContext, VariableExpressionAst varAst)
   at System.Management.Automation.Interpreter.FuncCallInstruction`4.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : Confirm
CategoryInfo          : InvalidOperation: (Confirm:String) [], RuntimeException
FullyQualifiedErrorId : VariableIsUndefined
InvocationInfo        :
    ScriptLineNumber : 7
    OffsetInLine     : 30
    HistoryId        : -1
    Line             :         if ($Force -and -not $Confirm)

    PositionMessage  : At line:7 char:30
                       +         if ($Force -and -not $Confirm)
                       +                              ~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at Test-Confirm<Begin>, <No file>: line 7
                        at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.7
PSEdition                      Core
GitCommitId                    7.3.7
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Note that `-Force` is meant to be used with `.ShouldContinue()`, not `.ShouldProcess()`

`-Confirm`, as a [common parameter](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_CommonParameters) is an _implicitly_ supported parameter and therefore doesn't show up as a _variable_ corresponding to the parameter name.

PowerShell automatically translates such common parameters into function-scoped preference-variable counterparts, so that `-Confirm` turns into a local `$ConfirmPreference` variable with value `'Low'`.

They are also reflected in `$PSBoundParameters`.

The safe way to determine if `-Confirm`  was passed is `$PSBoundParameters.ContainsKey('Confirm')`
However, note that`-Confirm:$false` may have been passed too, in which case then checking `$PSBoundParameters.Confirm` (or `$PSBoundParameters['Confirm'])` gives you the effective value (`$true` or `$false`)

**Comment by Nippius** [comment]
> Note that -Force is meant to be used with .ShouldContinue(), not .ShouldProcess()

Hope this doesn't come out wrong but, why is that? The article specifically mentions both cases.  Is this because one uses the $Confirm variable and the other uses the return value of .ShouldContinue()?

> -Confirm, as a [common parameter](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_CommonParameters) is an implicitly supported parameter and therefore doesn't show up as a variable corresponding to the parameter name.

> PowerShell automatically translates such common parameters into function-scoped preference-variable counterparts, so that -Confirm turns into a local $ConfirmPreference variable with value 'Low'.

I think this is the point I was trying to make. If powershell defines these variables implicitly and I have no control over them, shouldn't they also be defined implicitly when running in strict mode? As a user, I'm not expecting a "core" behaviour of powershell to change when running in strict mode.

> The safe way to determine if -Confirm was passed is $PSBoundParameters.ContainsKey('Confirm')
However, note that-Confirm:$false may have been passed, in which case then checking $PSBoundParameters.Confirm (or $PSBoundParameters['Confirm']) gives you the effective value ($true or $false)

Thanks I'll give this a try!

 (but as I said, I'm still learning so if this is the expected behaviour then it's ok. This is just something that tripped me up)

**Comment by mklement0** [comment]
> why is that?

* `.ShouldProcess()` behavior is fully controlled by `-Confirm` / `$ConfirmPreference` / `-WhatIf` / `$WhatIfPreference`, i.e. by the common-parameter / preference-variable infrastructure.

* By contrast, the _recommended_ way to override `.ShouldContinue()` is to implement your own `-Force` switch.

> If powershell defines these variables implicitly and I have no control over them, shouldn't they also be defined implicitly when running in strict mode?

In PowerShell code, you shouldn't need to interact with common parameters as such, as they are automatically translated into local preference variable values; e.g., `-Confirm` causes a local `$ConfirmPreference` variable with value `Low` to be defined, so you can work with that.
(If you need to know whether a common parameter was explicitly passed - as opposed to having inherited a preference from an ancestral  preference variable - check via `$PSBoundParameters`).

There is still a small caveat: If `-Confirm` is _not_ used, you'll see the `$ConfirmPreference` from an ancestral scope, such as the one in the _global_ scope, and - surprisingly - that one can be _removed_. In other words: If `-Confirm` isn't used, and someone (unexpectedly) removed the ancestral `$ConfirmPreference`  variable, you'll still have a strict-mode problem.

On a side note: Be sure not to use `Set-StrictMode -Version Latest` in production code, because future PowerShell versions may introduce additional checks that could break your code.

**Comment by Nippius** [comment]
Thank you! 

I've playing around with this for the last few days and I'm getting the hang of it but for now, I'm going to let powershell handle things and if I need to force something I'll just use -Confirm:$false.

> On a side note: Be sure not to use Set-StrictMode -Version Latest in production code, because future PowerShell versions may introduce additional checks that could break your code.

I was indeed doing this 🤭 Thank you for the heads up.

Anyway, I've learned a lot and I don't think I have anything else to add to this issue so I'll go ahead and close it. Thank you once again.
