### ISSUE TITLE
Missing sha256sum for source tarball

### ISSUE THREAD

**Issue by wahlstros** [PowerShell/PowerShell#2040]
Missing the sha256 checksum/hash for the source tarball (v6.0.0-alpha.9.tar.gz) isn't listed on the page:  https://github.com/PowerShell/PowerShell/releases/

Many thanks for making this opensource!

**Comment by andschwa** [comment]
Resolved.

Note that I don't feel 100% comfortable providing the checksum, as I didn't originally create the tarballs (GitHub did). Since I only have access to it by downloading it, providing the checksum doesn't secure against getting a bad download from GitHub in the first place (in other words, if they're compromised, my checksum is useless; they'd need to provide one). But that's like a 1% worry.
