### ISSUE TITLE
Whitelisted scripts with cmdletbinding cannot be executed by `pwsh -File <Path>` when applocker is enabled

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#20508]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Step 1: Create a script with the cmdletbinding attribute and a type that hasn't been whitelisted in constrained language mode. Demo script:
```
[cmdletbinding()]
param()
$null = [System.Collections.Generic.List[string]]::new()
pause
```
Step 2: Enable applocker with the default rules for scripts and add a whitelist rule for the test script.
Step 3: Try to launch a new instance of pwsh where the File parameter points to the test script, for example: `Start-Process -FilePath pwsh.exe -ArgumentList ("-ExecutionPolicy", "Bypass", "-File", "C:\Test\TestScript.ps1") -RedirectStandardOutput $Home\Desktop\Error.txt` (Redirected output to make it easier to see the error message).

The error message will say:
`[31;1mTestScript.ps1: [31;1mCannot dot-source this command because it was defined in a different language mode. To invoke this command without importing its contents, omit the '.' operator.[0m`

Step 4: Edit the script to remove the cmdletbinding attribute and try to run it again. This time it will succeed.

A simple workaround is to replace the `-File` parameter with `-Command` and run the script with `&` like this: `Start-Process -FilePath pwsh.exe -ArgumentList ("-ExecutionPolicy", "Bypass", "-Command", "& C:\Test\TestScript.ps1")`.  
I would imagine the fix for this is to just not dot-source the scripts specified by the `-File` parameter unless `NoExit` has also been specified (there's no point in dot-sourcing if the process stops after script execution anyway).  
If that's considered too big of a breaking change then a new parameter could be added to allow users to explicitly tell PS to not dot-source the script.  
For what it's worth, Windows PowerShell suffers from the same issue.

### Expected behavior

```console
N/A
```

### Actual behavior

```console
N/A
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.6
PSEdition                      Core
GitCommitId                    7.4.0-preview.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SydneyhSmith** [comment]
@MartinGC94 is correct in describing the expected behavior of this cmdlet

In terms of the feature request "If that's considered too big of a breaking change then a new parameter could be added to allow users to explicitly tell PS to not dot-source the script."  We determined that this is not a security feature so we would defer to the interactive console WG-- thanks!

**Comment by SteveL-MSFT** [comment]
I discussed this with @TravisEz13, `-f` and `-c` are working as documented, but it's understandable that the current behavior might be a surprise to users that expect an allowed script to not work because it wasn't obvious that `-f` will dot-source.

What we propose is that if `pwsh` knows that it is in system lockdown mode (AppLocker/WDAC) then it should emit a warning message when used with `-f` that the file will be dot-sourced and run in constrained language mode regardless if it's allowed to run in full language mode (use `-c` for that).  `-nologo` would suppress this message.

**Comment by TravisEz13** [comment]
> I discussed this with @TravisEz13, `-f` and `-c` are working as documented, but it's understandable that the current behavior might be a surprise to users that expect an allowed script to not work because it wasn't obvious that `-f` will dot-source.
> 
> What we propose is that if `pwsh` knows that it is in system lockdown mode (AppLocker/WDAC) then it should emit a warning message when used with `-f` that the file will be dot-sourced and run in constrained language mode regardless if it's allowed to run in full language mode (use `-c` for that). `-nologo` would suppress this message.

The issue is that dotsourcing a whitelisted (FLM) script into the CLM interactive scope is not allowed as it can expose trusted objects.

**Comment by theJasonHelmick** [comment]
Thank you @MartinGC94 for reporting this issue.  As stated by Travis above "The issue is that dot-sourcing a whitelisted (FLM) script into the CLM interactive scope is not allowed as it can expose trusted objects."  The dot-source behavior of `-f` is documented here: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_pwsh#-file---f

**Comment by jborean93** [comment]
The responses here don't make too much sense to me, how would the addition of the `[CmdletBinding()]` attribute affect what `-File` allows or does not allow to be run.

For example I have two scripts which output `"Test $($ExecutionContext.SessionState.LanguageMode)"` but script2 has `[CmdletBinding()] param()` as well. Both these scripts are signed but only the one without the `[CmdletBinding()]` attribute runs when starting in a new process.

![image](https://github.com/user-attachments/assets/05beb929-5839-4ee5-92fe-d4717151941e)

We can see that `script1.ps1` without the `[CmdletBinding()]` attribute runs just fine but `script2.ps1` does not. This is the same behaviour as `powershell.exe`.

Compare that to just invoking the script in an existing CLM session where both work just fine.

![image](https://github.com/user-attachments/assets/6b0e39f5-7429-4458-b987-bac739ea4457)

I would understand the failure if you did `-NoExit -File ...` where you don't want to leave open a shell that has dot sourced a FLM file but that doesn't work anyway with an understandable error around dot sourcing.

![image](https://github.com/user-attachments/assets/1daaef32-0c5a-4480-969b-3b11924a4024)

**Comment by sfcmgr** [comment]
I found this bug report after running into this issue with WDAC Script Enforcement blocking PSAppDeployToolkit running in our environment in Powershell 5, due to it having a [CmdletBinding()] and it runs with the -file augment on powershell.exe when deploying from Intune

The other problem we noticed while seeing the errors for PSAppDeployToolkit was from Microsoft Defender Advanced Threat Protection, which seems to be generating unsigned scripts with parameters for it's remote telemetry and control, those scripts are allowed via path rules in our environment, but as they are being called in the same way, they are being blocked by this feature.

this isn't my report, but I found this existing github ticket which mentions some of the behaviour
https://github.com/mttaggart/wtfbins/issues/43

It might want to be reconsidered if this behaviour is by-design, or passed back to the Defender team to work out if they need to change how they are working so that they can function in a WDAC environment with Script Enforcement enabled - given the bug with Windows 11 24H2 Applocker not enforcing Constrained Language mode (https://patchmypc.com/windows-11-24h2-applocker-powershell-constrained-language-broken) and the only fix is to use WDAC for Script Enforcement or a 3rd party allow listing tool, this is probably fairly important?

**Comment by sfcmgr** [comment]
A colleague has made me aware of a small note in this documentation that does mention that Defender for Endpoint has issues with devices running in constrained language mode, so this may already be known about by the Defender team - https://learn.microsoft.com/en-us/intune/intune-service/protect/mde-security-integration#microsoft-defender-for-endpoint-and-powershell

This issue does mean that customers need to choose between WDAC Script Enforcement or Defender for Endpoint if they use only Microsoft technologies - or are forced to find a 3rd party for either their AV/EDR solution or application allow listing solution if they want working products for both?

While maybe outside of the scope of this issue report on PowerShell, this seems like a fairly fundamental incompatibility that should be mentioned more prominently in both the WDAC and Defender for Endpoint documentation at least?
