### ISSUE TITLE
Question: Are module manifest keys (other than marked) specific to Windows?

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell#2064]
Are these keys specific to Windows PowerShell or do we need to delete the "Windows"?

Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = ''

Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''

**Comment by kilasuit** [comment]
These are just the comments that are spat out as default by New-ModuleManifest & Update-ModuleManifest so should be no issue in removing Windows from them at all.

**Comment by juneb** [comment]
Unless they're really specific to Windows.

**Comment by kilasuit** [comment]
Currently they are but thats only really because we only have had the different hosts available on windows with the main ones being the ConsoleHost and Windows PowerShell ISE Host

However going forward we may have a wider variety of hosts available on the other platforms and we could then have modules that are specifically built for those platforms.

So I think the removal of Windows from the comments is a good idea

**Comment by juneb** [comment]
I also want to clarify the explanation of HelpInfoUri so it's not confused with HelpUri.

**Comment by juneb** [comment]
@mirichmo, if I can figure this out, will you guys take a PR on the New-ModuleManifest user messages?

**Comment by SteveL-MSFT** [comment]
@juneb I think we would take it, I don't see any reason it should say Windows, should I assign to you?

**Comment by iSazonov** [comment]
Fixed by #4758
