### ISSUE TITLE
Allman style in ForEach-loop

### ISSUE THREAD

**Issue by JohnKesko** [PowerShell/PowerShell#20661]
### Summary of the new feature / enhancement

As a C# developer using Allman style, I find that Powershell ForEach-loops always trips me up where curly braces needs to be on the same line. 

For instance:

//... some other code

![image](https://github.com/PowerShell/PowerShell/assets/87022265/a2ab2c59-0331-45ea-b441-38bd147f83b0)

**Comment by 237dmitry** [comment]
I think this is because this script block is the value for the `Process` parameter, and the parameters are specified on one line. For example, the same in `Where-Object` (parameter `FilterScript`)

**Comment by mklement0** [comment]
The desire is understandable, but it is at odds with PowerShell's hybrid nature of being both a shell and a scripting language.

_Commands_ such as `ForEach-Object` (as opposed to _language statements_ such as `foreach`) are parsed  in [argument mode](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Parsing#argument-mode), i.e, like a _shell command line_, which means:
* The command _and its arguments_ must be specified on the same line, ...
* _unless_:
  * line continuation is explicitly requested via a `` ` `` at the (very) end of a line.
  * the line is _syntactically incomplete_ from a _language_ perspective.

`ForEach-Object` on its own _is_ syntactically complete from a language perspective, so the script-block  must at least _start_ on the same line in order to be recognized as an _argument_ (as shown in your first statement).

By contrast, the script block _itself_, due to being parsed in [expression mode](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Parsing#expression-mode), may span any number of lines, given that where it ends is unambiguously implied by the closing `}`. The same applies to language statements , such as `if`  in your example: there, `{ ... }` isn't a script-block _argument_, but a part of the statement syntax itself.

**Comment by jhoneill** [comment]
In addition to what has already been said - that the foreach-object cmdlet,  needs the script blocks which form its parameters to begin on the same line  like all other parameters so 
```
foreach-object  -process
{ script block }
```
has exactly the same problem as 
```
Get-ChildItem -Path
$env:temp
```
This does not apply to language statements , `while`, `switch`, `if` , `for` , `foreach`
SO this is valid
```
foreach 
 (
$x 
 in 
 @(
 1..   
 3  
 ) 
 ) 
 { 
 $x *
 $x
 } 
```
In the example in the first post 
``` $Variable | foreach-Object ```  
_may_ not be the best way to write it.
```
foreach($v in $variable)
{
$v *$v
}
``` 
may be preferred IF the output is not piped into another cmdlet
and if piping is required the foreach _method_ can be used - it unclosed `(` tells PowerShell the line is not complete -  similar to the operators with the second operand on a new line   
```
$variable.foreach(
{
$_ * $_ 
}
)  | sort-object -desc
```

Although it probably isn't what's required here you can also write 

``` 
$variable | 
    foreach-object {
   ....   

```
Because the lack of anything between the | and the line break means the line automatically continues.

**Comment by JohnKesko** [comment]
I see, thanks for all the answers.

I think we can close the issue. This...

foreach ($thing in $things)
{
    // do stuff 
}

... was appropriate for the task I was doing. 

However, ForEach-Object seems to have some overhead due to pipline vs the other.
So in summary if I got it right, use ForEach-Object for large collections and foreach for smaller if memory is important since foreach has space complexity of O(n).

**Comment by jhoneill** [comment]
>  ForEach-Object seems to have some overhead due to pipline vs the other. So in summary if I got it right, use ForEach-Object for large collections and foreach for smaller if memory is important since foreach has space complexity of O(n).

There IS an overhead to pass objects down the pipeline but usually time running the process block is much greater so 
```
$x = 1..1000000 
$timer.Start() 
$x | foreach-object {do-nothing} 
$timer.Start()
```
Takes many more microseconds than
```
$x = 1..1000000 
$timer.Start() 
foreach ($item in $x) {do-nothing} 
$timer.Start()
```

when do-nothing is replaced with something to real work, the extra microseconds are usually insignificant. 

depending on that is being fetched 
```
$x = get-Stuff 
foreach($item in $x) ...
``` 
May need a lot more memory - because all the items go into X  - than 
`get-stuff  | foreach-object ...` 
and the latter may display the first output sooner.
