### ISSUE TITLE
Stale issue bot should not close up-for-grab issues

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#20695]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The newly implemented 6-month stale bot should not apply to issues tagged with `up-for-grabs` this is because the problem indicated by the team is to reduce the number of open issues that need to be triaged/worked by the team/WG. However, `up-for-grabs` label has already been triaged and indicated that a PR should be opened by the community.

### Expected behavior

```console
Stale up-for-grabs issues should not be closed
```

### Actual behavior

```console
up-for-grabs issues are being closed
```

### Environment data

```powershell
N/A
```

**Comment by ThomasNieto** [comment]
Duplicate of #20693

**Comment by gerardog** [comment]
This is not a real duplicate of #20693, and that one derailed into nothing. This problem is real, and happening now, see https://github.com/PowerShell/PowerShell/issues/19827#issuecomment-1988038596

This ticket must be reopened and addressed @SteveL-MSFT @StevenBucher98, before the bot 
alienates more community members.
