### ISSUE TITLE
Sort order difference between PowerShell 5 and PowerShell 7

### ISSUE THREAD

**Issue by jason-nyc** [PowerShell/PowerShell#20730]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I experienced a slightly different sort order when sorting a list of files (strings) by name. Upon further review, I found that, for instance, the underline (95) and the period (46) are sorted differently. 

In PowerShell 5, the underline sorts before the period.
In PowerShell 7, the underline sorts after the period.

This is on the same machine, the same `get-culture`.

I solved this by converting to an ArrayList and performing an Ordinal sort.
`$list = New-Object System.Collections.ArrayList;$list.AddRange($mystrings )
$list.Sort([System.StringComparer]::Ordinal)`

If I need to stick with Sort-Object, I convert the string to Hex strings of Unicode bytes and sort by that.
`$mystrings | Sort-Object {[system.Text.Encoding]::UTF8.GetBytes($_)|ForEach-Object ToString X2}`
Note that Sort-Object has a [-culture](https://learn.microsoft.com/en-us/dotnet/api/system.string?view=net-8.0#ordinal-vs-culture-sensitive-operations) option, but I couldn't find an InvariantCulture to use.

### Expected behavior

```console
# PowerShell 5
#
PS> "_" -gt "."
True
PS> $mystrings = "A","B","C","a","b","c","_","."
$mystrings | Sort-object
.
_
A
a
B
b
C
c
PS> $mystrings | Sort-object | %{[int][char]$_}
46
95
65
97
66
98
67
99
```

### Actual behavior

```console
# PowerShell 7
#
PS> "_" -gt "."
False
PS> $mystrings = "A","B","C","a","b","c","_","."
PS> $mystrings | Sort-object
_
.
A
a
B
b
C
c
PS> $mystrings | Sort-object | %{[int][char]$_}
95
46
65
97
66
98
67
99
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

$PSVersionTable

Name                           Value                                                                                                                                
----                           -----                                                                                                                                
PSVersion                      5.1.22621.2506                                                                                                                       
PSEdition                      Desktop                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                              
BuildVersion                   10.0.22621.2506                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                      
WSManStackVersion              3.0                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                  
SerializationVersion           1.1.0.1
```

**Comment by mklement0** [comment]
In short: The difference in behavior with respect to sorting and string comparisons is owed to the difference in internationalization libraries used in the legacy _.NET Framework_ (underlying _Windows PowerShell_, whose latest and last version is 5.1.x) and _.NET_ 5+ (underlying _PowerShell (Core)_). See [.NET globalization and ICU](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu) and the following issues:
* #14757
* #19736

**Comment by 237dmitry** [comment]
> but I couldn't find an InvariantCulture to use

Result is the same. `-Culture 'inv'` or `-Culture 127`

**Comment by jason-nyc** [comment]
mkelement0 is right - sort order difference is an expected compromise as they expand PowerShell to more OS implementations etc.  I was hopeful for `Sort-object -Culture Inv` but as 237dimtry points out, it doesn't help for this issue.

It's unfortunate that you have to build your own sort key if you expect the same sort across versions, even on the same machine.

**Comment by mklement0** [comment]
@jason-nyc, on Windows you can use the NLS opt-in (setting env. var. `DOTNET_SYSTEM_GLOBALIZATION_USENLS` to `1` beforehand) to get the old behavior back, but note that it invariably applies to the _whole session_ (and if you _persistently_ set this env. var., it applies to ALL sessions).

---

As an aside re the _invariant culture_ (which indeed doesn't help):

`Sort-Object -Culture 127` seems to be the only way to _directly_ request `[cultureinfo]::InvariantCulture` via _its LCID_ - its _name_ is actually the _empty string_, so another way to obtain it is with ` [cultureinfo]::new('')`.

Thus, you would _expect_ `-Culture ''` to work, but it doesn't - see:
* #18655

By contrast, `-Culture Inv`, `-Culture InvariantCulture` or `-Culture Bogus` only _accidentally_ works from what I can tell:
 * It is the equivalent of, say, `[cultureinfo]::new('Bogus')`, which creates a _custom culture ad hoc_ (with catch-all LCID `4096`), which happens to use the invariant culture's settings _by default_.
 * It is unfortunate that names that don't match a _predefined_ culture are _quietly accepted_ and result in this behavior - a simple typo can result in subtle bugs.
 * A more sensible approach would be to accept only the names of _predefined_ cultures, while allowing for the possibility of passing a _custom_ culture _as a `[cultureinfo]` object_ - which currently isn't supported, because the `-Culture` parameter is `[string]`-typed, as discussed in the linked issue.
