### ISSUE TITLE
`Get-Help`: parameter aliases are (again) missing from local help display with `-Full` and `-Parameter`

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#20787]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Judging by https://github.com/MicrosoftDocs/PowerShell-Docs/issues/1638#issuecomment-366519989, this was fixed at least at some point in PS Core, but the problem is back.

Only the _online_ versions of the cmdlet help topics list parameter aliases such as `-lp` and `-PSPath` for `-LiteralPath`.

```powershell
# With -Full
Get-Help Get-ChildItem -Full | Out-String -Stream | Select-String '^\s+-LiteralPath' -context 0, 9

# Parameter-individual
Get-Help Get-ChildItem -Parameter LiteralPath
```

### Expected behavior

```console
>     -LiteralPath <System.String[]>
          Specifies a path to one or more locations. The value of LiteralPath is used exactly as it's typed. No characters are interpreted as wildcards. If the path includes escape characters, enclose it in single quotation marks. Single quotation marks tell PowerShell to not interpret any characters as escape sequences.
          
          For more information, see about_Quoting_Rules (../Microsoft.Powershell.Core/About/about_Quoting_Rules.md).
          
          Required?                    true
          Position?                    named
          Default value                None
          Accept pipeline input?       True (ByPropertyName)
          Aliases                      PSPath, LP



-LiteralPath <System.String[]>
    Specifies a path to one or more locations. The value of LiteralPath is used exactly as it's typed. No characters are interpreted as wildcards. If the path includes escape characters, enclose it in single quotation marks. Single quotation marks tell PowerShell to not interpret any characters as escape sequences.
    
    For more information, see about_Quoting_Rules (../Microsoft.Powershell.Core/About/about_Quoting_Rules.md).
    
    Required?                    true
    Position?                    named
    Default value                None
    Accept pipeline input?       True (ByPropertyName)
    Accept wildcard characters?  false
    Aliases                      PSPath, LP
```

### Actual behavior

The `Aliases` line is missing in both cases.

### Environment data

```powershell
PowerShell 7.4.0
```

**Comment by sdwheeler** [comment]
`Get-Help` gets the information but the formatter isn't displaying the aliases.

```powershell
(get-help Get-ChildItem).parameters.parameter | select name, aliases

name          aliases
----          -------
Attributes    none
Depth         none
Directory     ad
Exclude       none
File          af
Filter        none
FollowSymlink none
Force         none
Hidden        ah, h
Include       none
LiteralPath   PSPath, LP
Name          none
Path          none
ReadOnly      ar
Recurse       s
System        as
```

**Comment by kilasuit** [comment]
I can't replicate this as shown below using the store installed version with updated help
![image](https://github.com/PowerShell/PowerShell/assets/6355225/e5ac1707-fcd6-415d-b0a9-0b7e565ecaf6)

**Comment by mklement0** [comment]
Interesting, @kilasuit - there must be something in your environment that either overrides the built-in formatting definitions, or selects  a different one: there are _two_ built in definitions, one in [`Help_format_ps1xml.cs`](https://github.com/PowerShell/PowerShell/blob/4200af132836747a786bf0c5ec28c985aa1b522d/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/Help_format_ps1xml.cs#L338) and another in [`HelpV3_format_ps1xml.cs`](https://github.com/PowerShell/PowerShell/blob/4200af132836747a786bf0c5ec28c985aa1b522d/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/HelpV3_format_ps1xml.cs#L498)

Only the _latter_ includes aliases, and it seems to be selected _conditionally_ - but I know neither the logic behind this selection nor the backstory.

For me - on any platform - and seemingly also for @sdwheeler, it is the _former_ that seems to take effect, resulting in the absence of aliases in the formatted output.

It looks like `HelpV3_format_ps1xml.cs` is the more modern definition, as it also includes information about whether the parameter is dynamic and the name of the parameter set.

Perhaps the mechanism that selects the `HelpV3_format_ps1xml.cs` definition over the `Help_format_ps1xml.cs` one is broken.

**Comment by theJasonHelmick** [comment]
Thank @mklement0 for reporting this issue -- and thank you for the excellent response to @sdwheeler - which has helped us understand where the issue might be occurring.  We agree that this is a bug and needs to be corrected.

**Comment by daxian-dbw** [comment]
I did some investigation, and it turns out to be by design (maybe).
The parameter properties shown up in the help output is different depending on whether the help content is from MAML or is from content auto generated from the command syntax. The latter happens when there is no MAML help content yet (Update-Help never runs, for example). 

When the help content is from MAML, the object returned from `Get-Help` has the `MamlCommandHelpInfo#` prefix in its `PSTypeNames`, for example:

![image](https://github.com/PowerShell/PowerShell/assets/127450/83faba79-d73d-4c14-8bc0-ec309653dee3)

In this case, the format definition to be used in formatting does **NOT** contain the following information: _"Parameter Set Name"_, _"Alias"_, and _"Dynamic?"_.

When MAML content is not available and `Get-Help` is using auto generated content from the command syntax, the object returned from `Get-Help` has the `ExtendedCmdletHelpInfo#` prefix in it's `PSTypeNames`, and in that case, the format definition to be used will contain the _"Parameter Set Name"_, _"Alias"_, and _"Dynamic?"_ information. That's why @kilasuit cannot reproduce the issue in https://github.com/PowerShell/PowerShell/issues/20787#issuecomment-1875745810.

-----------------------

That being said, it's easy to add the _"Alias"_ property to the format definition of the `MamlCommandHelpInfo#` ps type, as the MAML content seems to have this information. However, MAML content doesn't have information about _"Parameter Set Name"_ and _"Dynamic?"_, so we cannot add them for sure.

**Comment by mklement0** [comment]
Thank you, @daxian-dbw.

Just to avoid to confusion: This means that the _opposite_ of @kilasuit's statement is true:

* Only in the _absence_ of downloaded MAML help content do the `Aliases`, `Dynamic?` and `Parameter set name` currently show up.

   * On macOS, for instance, this can be verified by temporarily renaming the `$HOME/.local/share/powershell/Help` directory, which contains the downloaded help content.

* This raises the following question:

  * Given that this information is useful, can the MAML tooling be enhanced to include this information too?
