### ISSUE TITLE
set-content needs to perform more like > for simple redirection scenarios

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#2087]
## Steps to reproduce

get-content <large file bigger than ram> | set-content foo.txt
get-content <large file bigger than ram> > bar.txt
## Expected behavior

both succeed with similar performance
## Actual behavior

first one fails due to memory usage

Reported from:
https://twitter.com/troyhunt/status/769108300973563904

I think the meta issue is discovery for end users.  This may be a common obvious operation for many.

**Comment by mklement0** [comment]
At least conceptually, `Set-Content` should always be faster, because it needn't involve the default output formatter.
A quick, informal test on my macOS 10.12.6 machine shows that `Set-Content` is indeed about twice as fast as `>` (though note that as of beta.6 `>` still produces UTF16-LE, while `Set-Content` produces UTF-8).

With output from an external utility - which is invariably _text_ - `Set-Content` is arguably the better tool, though `>` / `Out-File` work fine _functionally_ too (encoding differences in Windows PowerShell aside, `Set-Content` / `Out-File` produce the same output with _string_ input).

That `Set-Content` would involve array allocation is somewhat baffling (haven't looked at the source yet).

The error aside, it's fair to say that PowerShell has a performance problem here.

Let's compare commands that write a 1-million-element array to a file (sample timings from my machine):

PowerShell:

```powershell
> $a = 1..1000000; Measure-Command { $a > t.txt } | % TotalSeconds 
83.074664  # as stated, with Set-Content this would roughly be halved on my machine
```

Bash:

```sh
$ a=( {1..1000000} ); time printf '%s\n' "${a[@]}" > t.txt
real	0m6.342s
...
```

That's a factor of 13.
