### ISSUE TITLE
System.OutOfMemoryException thrown by Out-String in PS 7.4

### ISSUE THREAD

**Issue by slavizh** [PowerShell/PowerShell#20904]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing this strange issue with Out-String in PS 7.4 giving System.OutOfMemoryException in certain situations. I think it is the size of the object I am inputting for the cmdlet. I will try to provide steps for reproduction but it is hard as I can reproduce this on Azure Pipelines Hosted agents which run on containers. The issue appeared when we upgraded PS on the hosted agents from 7.2 to 7.4. Same code with same input was working fine before that. The code we run is the following:

```powershell
$whatIfResult = Get-AzDeploymentWhatIfResult @deploymentParameters
($whatIfResult | Out-String).replace("$e[38;5;208m", "$($PSStyle.Foreground.Red)").replace("$e[38;5;77m" , "$($PSStyle.Foreground.Green)").Replace("$e[38;5;141m", "$($PSStyle.Foreground.Magenta)").Replace("$e[38;5;246m", "$($PSStyle.Foreground.BrightBlack)")
```

I have removed the replace part and still getting error: Error: Exception of type 'System.OutOfMemoryException' was thrown.
The error is not thrown every time if the results in variable whatIfResult are not big everything works. But as soon as the variable has some big results the error appears. If needed I can share more details but it needs to be in private as the parameters for cmdlet Get-AzDeploymentWhatIfResult are something I cannot share in public. I can also reproduce it with a file that I have downloaded from the pipeline logs that is in size 1.57 GBs. When I reproduce it I run it on my laptop with may more memory and it is on Windows but also PS 7.4. If I do `Get-Content <file name> |  Out-String` I get the same error I am hoping that this was working fine in PS 7.2 can help you find what in the code of PS 7.4 for Out-String is causing it. I am not sure if it somehow depended on the Memory where PS 7.4 runs but as I have mentioned same machines with same capacity did not had the problem with 7.2. 

### Expected behavior

```console
Out-String to succeed.
```

### Actual behavior

```console
Error: Exception of type 'System.OutOfMemoryException' was thrown.
```

### Error details

```console
CategoryInfo          : NotSpecified: (:) [Out-String], OutOfMemoryException
FullyQualifiedErrorId : System.OutOfMemoryException,Microsoft.PowerShell.Commands.OutStringCommand
InvocationInfo        :
    MyCommand        : Out-String
    ScriptLineNumber : 1
    OffsetInLine     : 91
    HistoryId        : 13
    Line             : Get-Content "C:\Users\stanislav.zhelyazkov\Downloads\logs_200053\1_Deploy solution.txt" | out-st
ring
    Statement        : out-string
    PositionMessage  : At line:1 char:91
                       + … .zhelyazkov\Downloads\logs_200053\1_Deploy solution.txt" | out-string
                       +                                                              ~~~~~~~~~~
    InvocationName   : out-string
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Ubuntu 20.04.6 LTS
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
> I can also reproduce it with a file that I have downloaded from the pipeline logs that is in size 1.57 GBs.

That looks like part of the problem. You are using [System.String.Replace](https://learn.microsoft.com/en-us/dotnet/api/system.string.replace?view=net-8.0) so the whole file needs to be read into memory and converted to a single string.

Then during the conversion a completely new string is created in memory.

It would be better if you could have a proper pipeline where the replace works on a line-by-line basis rather than on the whole file

**Comment by slavizh** [comment]
@rhubarb-geek-nz do you have an example? Line by line sounds like more time to process? As I have mentioned though. This was never a problem with Out-String in 7.2 so definitely there is some bug or 7.4 introduces some limit that is not documented or at least I have not seen documentation for it.

**Comment by rhubarb-geek-nz** [comment]
> so definitely there is some bug or 7.4 introduces some limit that is not documented

Holding a string in memory requires space for that string. Returning a string that is different also requires memory for that string. Working space my be required for equivalent of a StringBuilder during the replacement operation.

It is generally bad practice to work with large files in memory especially in an environment where memory is limited ( like in a Docker or other VM) or shared between multiple users and processes ( any standard server ). Historically it is the case that tools can work with files that are many times larger than the total memory size of the machine, by treating the content in a stream or pipeline ( hence UNIX [sed](https://man7.org/linux/man-pages/man1/sed.1p.html) which can operate on streams rather than just files )

**Comment by 237dmitry** [comment]
>  If I do `Get-Content <file name> |  Out-String` I get the same error

How big is this file? I took the first one so it would be big enough:

![ss](https://github.com/PowerShell/PowerShell/assets/78153320/ee9f1b3a-2d2a-4fba-9575-544558bfd511)

**Comment by slavizh** [comment]
@237dmitry as mentioned in the description 1.57 GBs.

**Comment by rhubarb-geek-nz** [comment]
> @rhubarb-geek-nz ok but you do not propose how I should replace this code.

$whatIfResult = Get-AzDeploymentWhatIfResult @deploymentParameters

According to the [documentation](https://learn.microsoft.com/en-us/powershell/module/az.resources/get-azdeploymentwhatifresult?view=azps-10.4.1) the returned object is a [PSWhatIfOperationResult](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.resourcemanager.cmdlets.sdkmodels.deployments.pswhatifoperationresult?view=az-ps-latest), not a string of any kind.

I don't know what kind of results you get or what they contain.

You might need to enumerate over the [Changes](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.resourcemanager.cmdlets.sdkmodels.deployments.pswhatifoperationresult.changes?view=az-ps-latest#microsoft-azure-commands-resourcemanager-cmdlets-sdkmodels-deployments-pswhatifoperationresult-changes) property after validating the [Error](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.resourcemanager.cmdlets.sdkmodels.deployments.pswhatifoperationresult.error?view=az-ps-latest#microsoft-azure-commands-resourcemanager-cmdlets-sdkmodels-deployments-pswhatifoperationresult-error) and [Status](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.resourcemanager.cmdlets.sdkmodels.deployments.pswhatifoperationresult.status?view=az-ps-latest#microsoft-azure-commands-resourcemanager-cmdlets-sdkmodels-deployments-pswhatifoperationresult-status).

**Comment by rhubarb-geek-nz** [comment]
This is speculative, but you might get something presentable with

```
$whatIfResult = Get-AzDeploymentWhatIfResult @deploymentParameters
.... validate status ...
$whatIfResult.Changes | Format-Table
```

**Comment by 237dmitry** [comment]
> mentioned in the description 1.57 GBs

Sorry, I didn't notice. Yes, there is the error:

`Out-String: Exception of type 'System.OutOfMemoryException' was thrown.`

if I use `Get-Content file -raw` to get sting on output then:

 `Get-Content: Exception of type 'System.OutOfMemoryException' was thrown.`

file 1.6Gb, RAM 32Gb.

PS. Without optimization, as it out of issue.

**Comment by slavizh** [comment]
@rhubarb-geek-nz  not sure why you point to Get-AzDeploymentWhatIfResult cmdlet documentation. I know that the cmdlet is returning object. That is the reason I am using Out-String so I can pre-format the output so it looks prettier in Azure Pipelines as they support 4-bit ANSI colors where the output of the cmdlet 8-bit. As I have mentioned there were no changes in the cmdlets I use. This appeared as soon as I moved from PS 7.2 to PS 7.4. Not sure why you look for problems in all other places besides Out-String and PS 7.4.

**Comment by slavizh** [comment]
@237dmitry could be some bug in .net as well if it is present in Get-Content as well.

**Comment by rhubarb-geek-nz** [comment]
> Not sure why you look for problems in all other places besides Out-String and PS 7.4.

`Out-String` depends on the content. The content came from `Get-AzDeploymentWhatIfResult` according to your post.

**Comment by slavizh** [comment]
@rhubarb-geek-nz you can see that @237dmitry has reproduced it as well. Also I have mentioned that the size is likely to be the problem not so much the content. I have mentioned that not every result of Get-AzDeploymentWhatIfResult is actually producing the error.

**Comment by rhubarb-geek-nz** [comment]
> @rhubarb-geek-nz you can see that @237dmitry has reproduced it as well. 

I am not the least surprised that trying to create a single string over a gigabyte long in memory causes an OutOfMemoryException. My approach would be to start at what the content is and how to deal with it so that you are not dealing with strings that are over a gigabyte long.

**Comment by slavizh** [comment]
@rhubarb-geek-nz this is the last time I responding to you. This is clearly a bug. Works in PS 7.2, fails in PS 7.4. For what I am trying to do there is no other way to do it. You also haven't provided a way when I asked you two times. My suggestion is stop commenting on this issue.

**Comment by jhoneill** [comment]
Someone else might now better but I think 

$x.replace( ).replace( ).replace() 

Won't dispose of the first replace until last replace has run.  So the code as shown has one copy of the variable in a large object, 
another copy in ($object | out-string)  and multiple copies at each of the replacement steps 

I would  try  
 ```
Get-AzDeploymentWhatIfResult @deploymentParameters | Out-String -stream | foreach-object {$_ -replace '\$e\[38;5;208m' $PSStyle.Foreground.Red -replace "\$e\[38;5;77m" , $PSStyle.Foreground.Green  } 
```
I'm assuming the azure command returns multiple objects, this way each one goes into Out-String , is output as multiple small strings (that's `-stream`) and each  of those is processed .   (Not that `-replace` uses regular expressions so `$` and `[` need to be escaped with `\`

Possibly something has changed in .NET rather than what the PowerShell commands do, possibly some other change means you have less memory available or the objects are generating bigger output.  But making enough copies of a big enough string will cause you to run out of memory.  (and as @rhubarb-geek-nz  has said, if you read a 1GB ascii text or UTF 8 encoded file it becomes 2GB of UTF-16 in memory. )

**Comment by jhoneill** [comment]
I'm also doing a Sanity check here - if there's over 1GB of data, and the OP is pushing ANSI prettification strings around, that means this file of several million lines - perhaps upwards of 10 million lines - is intended for a human to look at .  A quick search says the bible is only about 4 million letters so 8MB of UTF-16,  who's going to be reading > 100 bible's worth on screen . (Another search tells me War and Peace is about 2/3 of the length of the bible).

**Comment by jhoneill** [comment]
Having posted from the train mentally done the sanity check on the drive home, I also has this idea.
```
> $x = New-Object -TypeName System.Text.StringBuilder
> $x.Append("ABCD")
> $x.Append($x.ToString())   # 8 chars in the builder. 

>> repeat  until   $x.Append($x.ToString()) says we  have a big string

> Capacity MaxCapacity     Length
  -------- -----------     ------
1073741824  2147483647 1073741824

> $y = $x.toString().replace("a","z").replace("b","y").replace("c","x")

MethodInvocationException: Exception calling "ToString" with "0" argument(s): "Exception of type 'System.OutOfMemoryException' was thrown."

>> $psversionTable

Name                           Value
----                           -----
PSVersion                      7.3.10

``` 
It's not a 7.4 thing.  In fact it doesn't even need the replace operations. A string builder can build a string that is too big to go into a string variable ,or to pass to `set-content`   

```
#525 [——€] PS7 ~\Documents\PowerShell> $s = $x.ToString(0,1023.9mb)
#526 [——€] PS7 ~\Documents\PowerShell> $s = $x.ToString(0,1024mb)
MethodInvocationException: Exception calling "ToString" with "2" argument(s): "Exception of type 'System.OutOfMemoryException' was thrown."
```
It looks like the maximum size of a string is 2GB @ 2 bytes per character.  But a string builder can build a 4GB one ( again @ 2 bytes per char). The only way to get the data out is specify subsets.

**Comment by iSazonov** [comment]
@slavizh Could you please download and check 7.4 previews (from 1 up to rc1) and point version where you see the issue?

**Comment by slavizh** [comment]
@iSazonov  really? How about someone from the PS team troubleshoot this instead. If I do not get support here I will log official case anyway.

**Comment by iSazonov** [comment]
@slavizh This is a community project, and no one (including MSFT members) has an obligation to others. Even if you open a case in official MSFT support, they will ask you to do additional steps (and most likely you will have to pay for their work if it is not a bug).

There was one change in pipeline so that could be the source of the problem.
/cc @SeeminglyScience

**Comment by jhoneill** [comment]
@iSazonov   I just tried the test I have above with **PowerShell 6.2**  
```
#553 PS6 ~\Documents\PowerShell> $y = $x.ToString(0,(1gb - 33))
#554 PS6 ~\Documents\PowerShell> $y = $x.ToString(0,(1gb - 32))
Exception calling "ToString" with "2" argument(s): "Exception of type 'System.OutOfMemoryException' was thrown."
```
So there maximum size of a string doesn't seem to have changed materially from 6 to 7.3.10,  possibly the format applied by 
`Out-String` has changed for the OP in 7.4  causing what is being returned by the  "AzureCmdlet | out-String" is to be too big for one string in some cases where it was not before.  

> . If I do Get-Content <file name> |  Out-String I get the same error I am hoping that this was working fine in PS 7.2 

No that hasn't changed since at least 6.2 either  with 256MB in the string builder $x 
```
#530 PS6 ~\Documents\PowerShell> set-content bigfile.txt $x.ToString()
#531 PS6 ~\Documents\PowerShell> Add-Content bigfile.txt $x.ToString()
#532 PS6 ~\Documents\PowerShell> get-item .\bigfile.txt

-a----        13/12/2023    08:03      536,870,916 bigfile.txt

#533 PS6 ~\Documents\PowerShell> $y = get-content bigfile.txt | out-string
#534 PS6 ~\Documents\PowerShell> Add-Content bigfile.txt $x.ToString()
#535 PS6 ~\Documents\PowerShell> get-item .\bigfile.txt

-a----        13/12/2023    08:04      805,306,374 bigfile.txt

#536 PS6 ~\Documents\PowerShell> $y = get-content bigfile.txt | out-string
#537 PS6 ~\Documents\PowerShell> Add-Content bigfile.txt $x.ToString()
#538 PS6 ~\Documents\PowerShell> get-item .\bigfile.txt

-a----        13/12/2023    08:04     1,073,741,832 bigfile.txt

#539 PS6 ~\Documents\PowerShell> $y = get-content bigfile.txt | out-string
out-string : Exception of type 'System.OutOfMemoryException' was thrown.

### nothing special about | out-string

#540 PS6 ~\Documents\PowerShell> $y = get-content bigfile.txt -Raw
get-content : Exception of type 'System.OutOfMemoryException' was thrown.

```
Again unchanged since 6.2 not new in 7.4

**Comment by slavizh** [comment]
@jhoneill yes it is some kind of combination. Thankfully trough your help to read this as -Stream has helped overcome it. I still use .replace instead of -replace as those two have difference and never got regex to work properly with ANSI characters. Overall I just need plane replace without doing patterns.

As you have mentioned it is most likely due to the ANSI characters and the size of the file. I am pretty sure it is some bug or undocumented "feature" as some prefer to say done in either PS 7.3 or PS 7.2 as we literally we were running the same pipeline with same input and this started as soon as we moved the hosted agents from PS 7.2 to PS 7.4. Also if the output was not so big the code is running without error in PS 7.4, only certain pipelines were failing that had bigger output.

Most likely will not be fixed if someone else does not log a case or complains but scenario with reading ANSI characters is not something that is quite common.

Again thank you for your input as you have really tried to dig into the actual problem and provide specific guidance.

**Comment by iSazonov** [comment]
Does the result depend on the contents of the file? Can you share the test file? We need _exact_ repro steps.
Do you see the same in Windows PowerShell?

**Comment by slavizh** [comment]
As mentioned I cannot share the file publicly as it contains sensitive information. Can only be shared with Microsoft representative. Usually when working with different Azure related repositories I am used to folks from Microsoft to step in when it is not some kind of question towards the service/tool but rather bug reported. 
The result not so much depends on the contents of the file but that it contains ANSI characters. No idea about Windows PowerShell. Stopped using that long time ago. Does not care about Windows Powershell as that one does not work on Linux which is the OS we use for the hosted agents. As mentioned several times before it worked in PS 7.2.

**Comment by daxian-dbw** [comment]
Changes were made to the formatting system in PowerShell v7.3 to properly handle string values that contain VT sequences, for [text truncation](https://github.com/PowerShell/PowerShell/pull/17251), [word wrapping](https://github.com/PowerShell/PowerShell/pull/17316), and more, during the formatting. That could result in increased memory usage for formatting and thus for `Out-String`. That's probably why `$whatIfResult | Out-String` worked for you in v7.2 but not in v7.4, especially that `$whatIfResult` holds string values with VT sequences according to your description.

The increased memory usage due to VT sequence handling in formatting is by design. As suggested in the comments above, it's recommended to use `Out-String -Stream` to prevent creating large string objects.
