### ISSUE TITLE
Strange behavior when using misplaced Continue keyword

### ISSUE THREAD

**Issue by Shayan-To** [PowerShell/PowerShell#21057]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run this: `$a = 1..5 | % { If ($_ % 2 -eq 0) { Continue }; $_ }; $a`

### Expected behavior

```console
Throws an error. Misplaced Continue. No enclosing loops.
```

### Actual behavior

```console
-- Nothing is printed.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Only ever use `break` and `continue` inside `switch` and loop statements (`while`, `do`, `for`, `foreach`). 

Otherwise, PowerShell looks up the call stack for such a statement and exits the first one it finds; if there is none, the current runspace is terminated; that is, at the very least the enclosing script terminates as a whole. 

See the relevant section of the conceptual [about_Break](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Break#do-not-use-break-outside-of-a-loop-switch-or-trap) topic.

**Comment by jhoneill** [comment]
The expectation seems to be that this would be considered  a syntax error.  This trivial example shows it being used as expected.  
```
> 'process {If ($_ % 2 -eq 0) { Continue }; $_ }' > c.ps1
> foreach ($i in 1..5) {$I  | .\c.ps1}
1
3
5
```

Now,  the it would be more **expected** in a longer script for someone to put     
`if (some condition for running is not met) {break}` 
But  that does this
``` 
> 'process { If ($_ % 2 -eq 0) { break }; $_ }' > b.ps1
> foreach ($i in 1..5) {$I  | .\b.ps1}
1
```

So `continue` looks better practice than `break` - but really _neither_ is good practice because if the foreach-object _cmdlet_ is used instead of the _statement_ it doesn't loop. 
```
> 1..5 | % {$_ | .\c.ps1}
1
```

Terminating the block which runs in a loop (with multi-item inputs `switch` loops), but looping through remaining objects, with `continue` is really "goto end of block" and as such annoys computer scientists. `Break` for goto end of block and don't process remaining items is a "super goto".  But avoiding them completely makes for longer and harder to follow code

**Comment by Shayan-To** [comment]
Thanks for your explanation. I now understand what PowerShell is doing.

But that does not dampen my feelings about this. I mistyped `Return` and wrote `Continue` in a 200-line script (and you can see why my brain did that mistake, the command is actually called `ForEach-Object`), and around 6 hours of my time went down the drain trying to debug the strangest bug (the kind I used to manage to get by accessing invalid memory in C or C++). And, I really expected **ANY** programming language to give me a runtime error (if not a compilation one) for this kind of mistake.

(Sorry if I was upset explaining the story.)

I have two suggestions:

1. When the `Continue` or `Break` cannot do what they're expected to, and this happens:

   > if there is none, the current runspace is terminated; that is, at the very least the enclosing script terminates as a whole.

   Then give me a warning at least, if not a runtime error.

2. Add a PSScriptAnalyzer rule that gives a warning (if not an error) if a `Continue` or `Break` is not enclosed within an actual loop.

And, if I dare suggest, deprecate this behavior of going up the call stack (by emitting a warning when it happens). It is super confusing when a keyword, that in any language I know, is interpreted at syntax level and decided to which loop it belongs, will actually act like `Throw` would, and would tear down the whole call stack to find some loop to terminate, or kill the whole script if it cannot. I really used to think that only `Throw` would ever have that kind of behavior (And I think vast majority of programmers would expect that as well).

**Comment by Shayan-To** [comment]
And BTW, `Continue` does have much more very strange behaviors.

Run these lines **ONE-BY-ONE** inside a shell:

```
Function F { 1..5 | % { If ($_ % 2 -eq 0) { Continue }; $_ } }
# Outputs nothing, expected.
F
# Outputs `1`. Thinking about what you said above, expected.
$a = F
# Outputs nothing, expected.
$a
# Outputs nothing. Again, thinking about what you said above, expected. Although strange behavior.
dir | select -First 1 | % FullName | % { "'$_'" }
# Outputs `'D:\1.txt'`, very normal.
dir | select -First 1 | % FullName | % { "'$_'"; F }
<#
Outputs this: (Which is super unexpected and the weirdest thing ever.)
'D:\1.txt'
1
''
1
#>
```

**Comment by mklement0** [comment]
I empathize: 

* The behavior is counter-intuitive, and the silent overall exit is particularly problematic.

* However, for this to go anywhere I suggest the following:

  * _Perhaps_ it is possible to implement a warning of sorts in the latter, case assuming it amounts to a [bucket 3: Unlikely Grey Area](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area)  change .

    * I encourage you to open a _feature request_ to that effect.

 * A PSScriptAnalyzer rule has actually been proposed before, and there are two rule request (apparent duplicates), labeled "Up-for-Grabs", so a community contribution would be welcome:
   * https://github.com/PowerShell/PSScriptAnalyzer/issues/1507
   * https://github.com/PowerShell/PSScriptAnalyzer/issues/1544

* As for the last example, `dir | select -First 1 | % FullName | % { "'$_'"; F }`: this is unequivocally a _bug_.
  * Given that exotic scenario, this will likely be considered low-priority, but, now that this issue has been closed and given that the bug is buried in a larger discussion, it may be worth opening a new, focused bug report for it.
