### ISSUE TITLE
Get-Package -ProviderName not working with comma separated values

### ISSUE THREAD

**Issue by darkseid4nk** [PowerShell/PowerShell#21107]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

get-package -ProviderName msi,Programs

### Expected behavior

```console
get-package -ProviderName msi,Programs
Name                                                                     ProviderName
----                                                                     ------------
Adobe Acrobat Reader MUI                                                 msi
Adobe AIR                                                                Programs
```

### Actual behavior

```console
get-package -ProviderName msi,Programs
get-package : Unable to find package providers (msi Programs).
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...lets.GetPackage:GetPackage) [Get-Package], Exception
    + FullyQualifiedErrorId : UnknownProviders,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackage
```

### Error details

```console
get-package : Unable to find package providers (msi Programs).
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...lets.GetPackage:GetPackage) [Get-Package], Exception
    + FullyQualifiedErrorId : UnknownProviders,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackage
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.3803
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3803
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by 237dmitry** [comment]
`(Get-PackageProvider).Name` ?

**Comment by darkseid4nk** [comment]
(Get-PackageProvider).Name
msi
msu
NuGet
PowerShellGet
Programs


so you see msi and Programs are valid options.

**Comment by mklement0** [comment]
Please note:

* From what I can tell, the problem does _not_ occur in Windows PowerShell (which your post references), because the specified providers _do_ exist there.

  * Aside from that, please note that this repo is for PowerShell (Core) (v6+) issues only and that some modules that ship with PowerShell are maintained in separate repositories, as in the case at hand.

* For reasons I'm personally unaware of, PowerShell (Core) doesn't come with these providers, and that's why you're seeing the (unfortunately worded) error message - which, regrettably, only surfaces if _none_ of the specified providers are available.

* In general, the [PackageManagement (fomerly: OneGet)](https://github.com/OneGet/oneget?tab=readme-ov-file#packagemanagement-aka-oneget) module that `Get-Package` is a part of is _no longer maintained_.

* Its successor is [Microsoft.PowerShell.PSResourceGet](https://github.com/PowerShell/PSResourceGet), which is focused on _PowerShell_ resources only.

[This blog post](https://devblogs.microsoft.com/powershell/powershellget-in-powershell-7-4-updates/) provides background information.

**Comment by ThomasNieto** [comment]
There is a community replacement for PackageManagement (OneGet) called AnyPackage which I maintain that has most of the core providers. You can try that to use the Programs provider.

**Comment by mklement0** [comment]
That sound great, @ThomasNieto; let me provide the links:

* [PowerShell Gallery](https://www.powershellgallery.com/packages/AnyPackage)
* [Repository](https://github.com/AnyPackage/AnyPackage)

**Comment by darkseid4nk** [comment]
Thank you both for that information. You went above and beyond.  

I was able to use each of the providers as a single argument and get a returned list. So i know they exist. I was just not able to pass both as a string array.  I looked into one of the unit tests for get-package and saw the following: 

`
Describe "Get-package" -Tags "Feature" {
    # make sure that packagemanagement is loaded
    It "EXPECTED: Get-package accepts array of strings for -providername parameter" -Skip {
        $x = (get-package -providername Programs,Msi)
    }
} 
 `

So my command should have worked. 

I ended up just pulling keys from the registry to get what i needed. 

If AnyPackage is supplied by default in my work environment I would be happy to implement that.  I'm unable to side load any additional gallery cmdlets or 3rd party cmdlets with the constraints I have. 

But given that the cmdlet I initially wanted to use is deprecated and no longer maintained, I won't try to use it, or push for a bug fix. I'll utilize the different method I implemented so my script can maintain compatibility with the certain update to powershell 7.

Thank you both for your swift responses and the resources you provided.
