### ISSUE TITLE
Feature Request: powershell native  `su` and `sudo` 

### ISSUE THREAD

**Issue by John0King** [PowerShell/PowerShell#21100]
### Summary of the new feature / enhancement

although  `su` and `sudo`  available on linux natively , but it only allow for application command,  the powershell CmdLet won't work !
this issue is about impelment a powershell native `su/sudo`  CmdLet  for both windows and linux

```powershell

sudo  -Script {  get-content  /otheruser/o.txt }
```

**Comment by jborean93** [comment]
This is already possible, on non-Windows at least, by doing

```powershell
sudo pwsh { get-content /otheruser/o.txt }
```

Anything else is going to essentially do the equivalent to that as it will require starting a new process and serializing the data back and forth. At least with the above syntax it is clear you are running another processes whereas people using a builtin cmdlet might expect something like the below to work:

```ps
$proc = sudo-cmdlet { Get-Process -Id 1234 }
$proc.WaitForExit()
```

This won't ever be possible because you cannot transfer "live" objects between processes. Getting it to work on Windows is a whole other story as typically you cannot share the same console between and non-elevated and elevated process. There are third party tools like [gsudo](https://github.com/gerardog/gsudo) which are quite popular who work around these limitations in interesting ways.

**Comment by 237dmitry** [comment]
I use [gsudo](https://github.com/gerardog/gsudo) on Windows. It can elevate script-blocks, create gsudo cache to avoid pressing button in UAC dialog.

**Comment by John0King** [comment]
the problem of `sudo pwsh`  is that it lose status/variables,  
on windows ,there is a `WindowsIdentity.RunImpersonated`  , and it seems can change user

on linux, maybe powershell can use multiple process model ,  a main powershell process , and a set of user identity sub process,  and use someof RPC to transifer the  variable/env.
```

$a = "a.txt"   // runs on main process
su-admin  {  Get-Content $a }   //  transfer all variables/env  and start a   [sudo-subprocess]  and execute the script and transfer back the result

su-user -user 'user2'   //    transfer all variables/env  and start a   [user(user2)-subprocess] 

get-content $a    //  run script on [user(user2)-subprocess]  and transfer back the result
```

**Comment by rhubarb-geek-nz** [comment]
> the problem of `sudo pwsh` is that it lose status/variables

In UNIX the user-id and group-id are associated with the process. Although UNIX has [setegid and seteuid](https://linux.die.net/man/2/setegid) these can only really be used by a root process, and really for restricting access, not expanding it.

There is also the security risk of having a single process gaining privileged access in some threads and not in others while sharing the same memory. Having the process boundaries enforces security and prevents information being accessed by less privileged code.

**Comment by 237dmitry** [comment]
> on linux

One way or another, under the hood there will still be the same sudo|doas, and they only understand executable files.

**Comment by SteveL-MSFT** [comment]
We've discussed this in the past and the main problem is the OS really needs to support `sudo` concept.  There has been some discussion in the Windows/Terminal repo on this topic https://github.com/microsoft/terminal/issues/146

**Comment by floh96** [comment]
FYI there is now an official sudo from Microsoft available, see https://github.com/microsoft/sudo
