### ISSUE TITLE
管理员运行与非管理员运行的界面标题是一样的，这不正常

### ISSUE THREAD

**Issue by heham** [PowerShell/PowerShell#21215]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

管理员运行与非管理员运行的界面标题是一样的，这不正常，应该是以管理员运行的时候标题上有管理员的提示。

### Expected behavior

```console
管理员运行与非管理员运行的界面标题是一样的，这不正常，应该是以管理员运行的时候标题上有管理员的提示。
```

### Actual behavior

```console
管理员运行与非管理员运行的界面标题是一样的，这不正常，应该是以管理员运行的时候标题上有管理员的提示。
```

### Environment data

```powershell
管理员运行与非管理员运行的界面标题是一样的，这不正常，应该是以管理员运行的时候标题上有管理员的提示。
```

**Comment by mklement0** [comment]
On a general note, please:

* Report your issues in English.
* Fill in the template sections properly - don't just paste the same text over and over.

---

As for the issue at hand:

* Based on the translation of your text, I suspect that PowerShell isn't the problem here, because it is the _console_ (terminal) application that prepends prefix `Administrator: ` to the the window title for elevated shell processes, irrespective of what shell is being run (e.g., you get the same behavior with `cmd.exe`)

* In the event that this prefix is unexpectedly missing for PowerShell processes _only_, please update your original post (in English) with detailed information about your environment and how to reproduce the problem.

**Comment by daxian-dbw** [comment]
The issue will be closed because the template sections are not filled in properly.
