### ISSUE TITLE
PowerShell not recognized as the PowerShell profile in the Windows Terminal

### ISSUE THREAD

**Issue by Neme12** [PowerShell/PowerShell#21289]
### Prerequisites

- [x] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I wasn't sure whether to file this issue here or with the Windows Terminal, but I figured probably here because this issue only occurs with PowerShell Core, not with the Command Prompt or with Windows PowerShell.

Today, I installed PowerShell 7.4.1 via WinGet from the Microsoft Store source (Package ID: 9MZ1SNWT0N5D). It automatically appeared as a new profile in my Windows Terminal when clicking the new tab dropdown menu, and everything works, great! I customized this profile a little. But then I realized that when I open PowerShell 7 directly from the Start Menu, it *is* opened in Windows Terminal as expected, however it's not recognized as the new PowerShell profile from the dropdown menu. :( It's missing the "PowerShell" title (instead, it shows file location of the exe), missing the icon and missing my customizations that I set for the new profile.

I attached two screenshots below. In the first tab you can see what it looks like when I open PowerShell from the Start Menu, and the second tab is what it looks like when I open PowerShell from inside the Terminal. The second one looks as expected.

I noticed that when I open Terminal Settings and choose the PowerShell profile, it shows file location as `C:\Users\<username>\AppData\Local\Microsoft\WindowsApps\Microsoft.PowerShell_8wekyb3d8bbwe\pwsh.exe`. This is in contrast to the file location from `C:\Program Files\WindowsApps` that is shown in the first tab - the one opened from the Start Menu. I guess this might be the problem, that these locations are different? And that either the Terminal profile should have file location set to the Program Files one as well to match the one from the Start Menu, or the Start Menu should have the AppData path to match the one from the Terminal profile?

This issue doesn't occur with Windows PowerShell. That one is always recognized as one and the same profile whether launched from the Start Menu or from the Terminal dropdown.

### Expected behavior

The tabs match (title, icon, customizations) whether launched from the Start Menu or from the Terminal dropdown.

### Actual behavior

They don't match. When launched from the Start Menu, there isn't even a proper title.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/11444821/201108fc-d34f-45ef-8b85-dbd909cf2793)
![image](https://github.com/PowerShell/PowerShell/assets/11444821/84bdd9a1-bbf5-4211-8e0d-63cf84997b3a)

**Comment by Neme12** [comment]
I tried uninstalling the Store version and installing the one from winget source and now it is recognized correctly. Although the title is still different between the 2 startup options for some reason (and think it'd be nice for it to be consistent and have the same title for both cases). Regardless, I think this should be fixed for the Store version.
![image](https://github.com/PowerShell/PowerShell/assets/11444821/5d41be38-9125-4729-bdfa-f74c9360f19f)

**Comment by mklement0** [comment]
These are issues you should definitely raise in the WT (Windows Terminal) repo, because the behavior is exclusively controlled by the latter - https://github.com/microsoft/terminal/issues

To provide some pointers and a workaround:

* By current design, it seems that an invocation that doesn't explicitly specify a target profile uses either the target executable's path _as specified_ as the tab title (e.g., `wt.exe pWsH.exe` will make `pWsH.exe` the tab title) or - if launched from a _shortcut file_, as in your case - uses the latter's file name (without the `.lnk` extension).
  
  * That is, in neither case do you get the _inferred_ profile's usual tab title, and my _guess_ is that this behavior won't change, at least not by default.

  * By contrast, you do get the usual title if you specify a profile _explicitly_, e.g., `wt.exe -p PowerShell` (must match an existing profile name exactly, even in terms of case), so one workaround is to modify the shortcut file to use this call instead (or create a separate shortcut file).

* When WT _infers_ what profile to use based on the executable path it is passed (possibly behind the scenes), and is given a _full_ path that doesn't match any of the profiles, it uses the _default settings_ - this is what happened in the case of the Microsoft Store-installed version, whose profile was defined in terms of the user-specific AppX application entry point in `$env:LOCALAPPDATA`, but invocation via the shortcut was seemingly resolved to the _ultimate_ executable path in `$env:ProgramFiles\WinApps`.

  * You could open an issue to request that WT recognize such path pairs as effectively the same (or at least define the auto-created profile in terms of the ultimate path).

**Comment by Neme12** [comment]
@mklement0 Thanks for the info, I'll open an issue there.

**Comment by Mist-Hunter** [comment]
For me the issue is with the winget package. When installed via the store everything works, so I changed to this:

```
winget search "PowerShell" --source msstore
 Name                                 Id             Version
 -----------------------------------------------------------
 PowerShell                           9MZ1SNWT0N5D   Unknown
 PowerShell Preview                   9P95ZZKTNRN4   Unknown
 PowerShell to exe&msi Converter free XPDCHZH119SRT8 Unknown
```

```
winget install --id "9MZ1SNWT0N5D" --source msstore
```
