### ISSUE TITLE
The splatting operator '@' cannot be used to reference variables in an expression. '@trigger' can be used only as an argument to a command. To reference variables in an expression use '$trigger'

### ISSUE THREAD

**Issue by deadcoder0904** [PowerShell/PowerShell#21291]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Open Powershell 7 in Windows Terminal
2. Type `pnpm dlx @trigger.dev/cli@latest init -k tr_dev_1213241234zxcz -t https://cloud.trigger.dev` in Terminal & hit Enter

### Expected behavior

```console
It should create a folder that is created by https://trigger.dev when successful like others like Git Bash do.

Just sign up for Trigger Dev & the first command if you select through Next.js in Onboarding would be above. Also, select `pnpm`.
```

### Actual behavior

```console
ParserError:
Line |
   1 |  pnpm dlx @trigger.dev/cli@latest init -k tr_dev_1213241234zxcz  …
     |           ~~~~~~~~
     | The splatting operator '@' cannot be used to reference variables in an expression. '@trigger' can be used only
     | as an argument to a command. To reference variables in an expression use '$trigger'.
```

### Error details

```console
$ Get-Error

Type        : System.Management.Automation.ParseException
Errors      :
    Extent  : @trigger
    ErrorId : SplattingNotPermitted
    Message : The splatting operator '@' cannot be used to reference variables in an expression. '@trigger' can be
used only as an argument to a command. To reference variables in an expression use '$trigger'.
Message     : At line:1 char:10
              + pnpm dlx @trigger.dev/cli@latest init -k tr_dev_1213241234zxcz  …
              +          ~~~~~~~~
              The splatting operator '@' cannot be used to reference variables in an expression. '@trigger' can be
used only as an argument to a command. To reference variables in an expression use '$trigger'.
ErrorRecord :
    Exception             :
        Type    : System.Management.Automation.ParentContainsErrorRecordException
        Message : At line:1 char:10
                  + pnpm dlx @trigger.dev/cli@latest init -k tr_dev_1213241234zxcz  …
                  +          ~~~~~~~~
                  The splatting operator '@' cannot be used to reference variables in an expression. '@trigger' can be
used only as an argument to a command. To reference variables in an expression use '$trigger'.
        HResult : -2146233087
    CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    FullyQualifiedErrorId : SplattingNotPermitted
    InvocationInfo        :
        ScriptLineNumber : 1
        OffsetInLine     : 10
        HistoryId        : 12
        Line             : pnpm dlx @trigger.dev/cli@latest init -k tr_dev_1213241234zxcz -t
https://cloud.trigger.dev
        Statement        : @trigger
        PositionMessage  : At line:1 char:10
                           + pnpm dlx @trigger.dev/cli@latest init -k tr_dev_1213241234zxcz  …
                           +          ~~~~~~~~
        CommandOrigin    : Internal
TargetSite  :
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation,
Version=7.4.1.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
Source      : System.Management.Automation
HResult     : -2146233087
StackTrace  :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown,
ExecutionOptions options)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
Try to escape command line arguments of `pnpm`:

```
pnpm --% dlx @trigger.dev/cli@latest init -k tr_dev_1213241234zxcz -t https://cloud.trigger.dev
```

**Comment by mklement0** [comment]
To add to @237dmitry's comment:

* Indeed, use of `--%`, the [stop-parsing token](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Parsing#the-stop-parsing-token) is an option, but note that it comes with many limitations, notably the inability to reference PowerShell variables.

* The problem is that `@` -  unlike in other shells - is a metacharacter at the start of arguments in PowerShell, used for [splatting](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Splatting) - that's what the error message is referencing.
  * Additional characters that you may not expect to be metacharacters are `` { } , ; ` `` (see full list below).

* Therefore a `@` (or any  other metacharacter)  that is to be used _verbatim_ at the start of an argument must either inside a _quoted string_ or must be individually escaped with `` ` ``, the so-called backtick, PowerShell's escape character.

Applying the latter technique to your command (note how only the _initial_ `@` need be escaped, though escaping both would work too):

```powershell
# Note the ` before the first @
pnpm dlx `@trigger.dev/cli@latest init -k tr_dev_1213241234zxcz -t https://cloud.trigger.dev

# Alternative with a quoted string
# Note the ` before the first @
pnpm dlx '@trigger.dev/cli@latest' init -k tr_dev_1213241234zxcz -t https://cloud.trigger.dev
```

The list of PowerShell metacharacters in [argument-parsing mode](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Parsing#argument-mode) is:

```none
<space> ' " ` , ; ( ) { } | & < > @ #
```

Note: 
 * Of these, `< > @ #` are only special at the _start_ of an argument.
 * _Situationally_, `.` (dot) requires escaping too, namely if the argument can syntactically be interpreted as accessing a variable's property (e.g., `Write-Output $env:computername.csv` outputs nothing - see [this answer](https://stackoverflow.com/a/66161666/45375)). 
 * If you want a `$` to be treated verbatim rather than refer to a variable or subexpression, you must escape it too.
 * For a complete overview of how unquoted command arguments are parsed in PowerShell, see [this answer](https://stackoverflow.com/a/41254359/45375).

**Comment by deadcoder0904** [comment]
I think this should work by default as countless npm modules will start from `@` as more packages are used.

I'd rather want `@` to work than remember to escape it.

Otherwise, I have to open another terminal with Git Bash which is not convenient.

**Comment by MartinGC94** [comment]
The parsing seems to already handle other special characters like: `ls @Test\` or `ls @Test*` so it doesn't seem unreasonable to think it should handle `.` as well, considering that it isn't possible to access a member from a splatted variable anyway.

**Comment by mklement0** [comment]
Good point, @MartinGC94.

There's several awkward behaviors around argument mode - both with native PowerShell commands and native (external) programs, and it may be worth revisiting _all_ of them in the context of a focus feature request, so they can be addressed with a _single change_, which will at least technically amount to breaking changes.

Using the case at hand as an example:

Here, the issue is that the `.dev` part of `@trigger.dev` is considered a _property access_, which triggers the error message:

* _Without_ splatting, such a property access _does_ work, and is useful _in isolation_:

  * E.g., `Write-Output $HOME.Length` works and reports the value of `$HOME.Length`, i.e. the count of characters in the value of the `$HOME` variable.

* In a _compound_ argument, it technically still "works", but exhibits behavior that is unlikely to be helpful in practice:

  * E.g., `Write-Output $HOME.Length/foo` is the same as `Write-Output $HOME.Length /foo`, i.e. whatever follows the property reference _becomes a separate argument_.

Given that `@trigger.dev`  _never_ makes sense as a property access, it is reasonable to fall back to treating it as a _verbatim string_, especially in native program calls.

Arguably, also treating `$HOME.Length/foo` as `"$($HOME).Length/foo"` makes more sense than the current behavior.

However, even in native program calls treating an isolated argument such as  `@trigger` _verbatim_ is _not_ an option, because splatting _does_ work with external programs (often seen with `@args`), albeit only meaningfully with _arrays_ rather than hashtables.

Currently, something like `cmd /c echo @foo` effectively passes _no_ arguments to the external program, if no `$foo` variable exists.

Perhaps `@foo` is a rare use case and having subsequent characters, such as a filename extension (e.g, `@foo.txt`) is the typical use case, in which falling back to _verbatim_ use is safe.

But the point is that all these behaviors and edge cases need to spelled out and agreed upon in detail before potentially making changes.

---

See also:

* #6467
* https://github.com/MicrosoftDocs/PowerShell-Docs/issues/3440#issuecomment-478206280
* With respect to `@{ ... }` in native-program calls: #1761
* With respect to `{ ... }` (script blocks) in native-program calls (to me, clearly a bug): #4973

**Comment by SteveL-MSFT** [comment]
There seems to be two possible options here and both might be bucket 3 in terms of a breaking change.

- since we have a specific error here, we could simply treat the "splatting" as literal instead of returning an error
- if the variable being splatting doesn't exist, then it becomes literal to avoid accidental splatting

**Comment by MartinGC94** [comment]
A reddit thread indicates that there's also been some parsing regression between 5.1 and 7 when `=` is used in the string. Where `npm config set @scope:registry=https://www.myregistry.com/` works in 5.1 but not 7 see: https://www.reddit.com/r/PowerShell/comments/1b85las/npm_works_different_in_51_vs_7/ for more details.

**Comment by mklement0** [comment]
Yes, it looks like WinPS - sensibly - falls back to treating the whole argument like an expandable string (`"@scope:registry=https://www.myregistry.com/"`), whereas PS Core expands `@scope:registry` to the empty string, and therefore passes only `=https://www.myregistry.com`:

`@scope:registry` is technically the splatted form of `$scope:registry`, which is technically a valid variable reference, using _namespace variable notation_, and "splatting" `@scope:registry` _alone_ results in _no_ argument getting passed, in both editions.

(Unhelpfully), in both editions something like `@env:PATH` _does_ splat, and - because a `[string]` is enumerably and therefore triggers _array_-based splatting - passes the _individual characters_ in `$env:PATH` as separate arguments.

When you follow a "splatted" namespace variable reference with a non-variable-name character _other_ than `=` (e.g, `#`, `%` or `!`), the whole argument is (sensibly) interpreted like an expandable string in _both_ editions.

However - in PS Core only - a subsequent `=` still triggers the splatting, and directly concatenates the `=` and whatever follows to the result. In the case at hand, since `$scope:registry` doesn't exist, the `@scope:registry` part effectively expands to the _empty string_, leaving only `=https://www.myregistry.com/`

**Comment by JamesWTruher** [comment]
The WG discussed this and believe that this is operating as it was designed. You will need to either quote or escape in order to avoid the variable parsing behavior.

**Comment by mklement0** [comment]
@deadcoder0904, perhaps the following translation  of the WG decision helps:

> The WG discussed this and believe that this is operating as it was designed

This means (do tell me if I got things wrong):

* "Even though we've been told that there are at least _two_ versions of 'as designed' that changed over time, we chose not to address that in our decision."

* "Even though we've been pointed to a better way forward, we chose to ignore that in our decision."

This is very much in the spirit of https://github.com/PowerShell/PowerShell/issues/18502#issuecomment-1314583418

**Comment by MartinGC94** [comment]
Yeah, I'm a bit confused about the WG decision as well. One of the recent goals in PowerShell was to make native program arguments "just work" to make it a nicer shell to use, hence all the PSNative* experimental features we've seen over the last couple of releases.  
I'm not a web guy, but npm seems quite popular in that world and if those users are having problems using pwsh then I think it's worth looking into how we can improve that situation (but of course without making it worse for others).  
If we think `Command @Identifier1.Identifier2` can be a meaningful syntax in the future then of course we should keep the existing behavior so we can reserve that syntax for later but I don't read that WG conclusion as if that was a consideration at all.

**Comment by kilasuit** [comment]
I agree that this is working as currently designed like the WG have said but do wonder if it could it be possible in future for in scenarios like this to have the engine ignore specific symbols like `@` when used in a line like the one referenced here for specific executables, instead of how we have it now & have this be an easily configurable list of executables via a env var or other method

**Comment by mklement0** [comment]
> configurable list of executables

Frankly, this will lead to ever-lasting confusion as to which executable exhibits which behavior in which specific version.

It is highly regrettable that a similar dance has already been started with respect to the ill-fated `Windows` mode of `$PSNativeCommandArgumentPassing` - see https://github.com/PowerShell/PowerShell/issues/18554#issuecomment-1314547572
