### ISSUE TITLE
Issue importing PKI module when using pwsh -command

### ISSUE THREAD

**Issue by jalkire** [PowerShell/PowerShell#21319]
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [x] Search the existing issues.
- [x] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [x] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Install PowerShell 7.4.1 on Windows
2. Attempt to use `pwsh -command` to use the PKI module (for example `> pwsh -c "Import-Module PKI"`)

Note that the import works fine when run directly (`> Import-Module PKI`). `pwsh -c "Import-Module PKI"` also works fine in PowerShell 7.3.1. I was able to reproduce the same behavior in an Azure DevOps pipeline as well (not public), so I don't think it has to do with my machine. 

I was able to work around this by setting the `$env:PSModulePath = [Environment]::GetEnvironmentVariable('PSModulePath', 'Machine')`, like 
`pwsh -c { $env:PSModulePath = [Environment]::GetEnvironmentVariable('PSModulePath', 'Machine') ; Import-Module PKI }`

I realize PKI is a Windows PowerShell module, but the above scenario was working in PowerShell Core until 7.4.1.

### Expected behavior

PS> pwsh -c "Import-Module PKI"
\* silently succeeds, just like when running:
PS> Import-Module PKI

### Actual behavior

PS> pwsh -c "Import-Module PKI"
Import-Module: The module to process 'Microsoft.CertificateServices.PKIClient.Cmdlets', listed in field 'NestedModules' of module manifest 'C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\PKI\PKI.psd1' was not processed because no valid module was found in any module directory.

### Error details

no output

### Environment data

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### Visuals

![Screenshot showing that the pwsh -c "Import-Module PKI" command fails but simply running Import-Module PKI works](https://github.com/PowerShell/PowerShell/assets/4615491/33c46480-c78c-4c2d-b1d5-860da3fd34ff)

**Comment by rhubarb-geek-nz** [comment]
I have replicated the same error with the PKI module on Windows with 7.4.1

This is similar to [#20740](https://github.com/PowerShell/PowerShell/issues/20740) where 

- the module loading behaviour is different between interactive and command line invocation
- the problem was not present prior to 7.4

I don't know if this is because of PowerShell 7.4.* or due to changes in .NET Core 8.

**Comment by daxian-dbw** [comment]
I cannot reproduce the issue with v7.4.1, OS version 10.0.22631.0.

![image](https://github.com/PowerShell/PowerShell/assets/127450/28571574-8378-40cf-9b2e-bc70aee12d96)

How did you install the v7.4.1? Store, MSI, or from a ZIP?

**Comment by rhubarb-geek-nz** [comment]
> How did you install the v7.4.1? Store, MSI, or from a ZIP?

I installed from MSI. The problem I suggest is that you are already running powershell when you run powershell, so all the environment variables have been set up.

Run directly from a simple traditional CMD.EXE command prompt without any powershell environment in the current session.

**Comment by rhubarb-geek-nz** [comment]
![image](https://github.com/PowerShell/PowerShell/assets/94297700/e4452286-5dbd-4ed9-8e84-146b14249fc1)

**Comment by jalkire** [comment]
I also installed from the MSI, but I experience the same issue on a preconfigured VM where PS 7.4.1 was already installed.

**Comment by daxian-dbw** [comment]
We've found a consistent repro: `pwsh -exe bypass -nop -c "ipmo pki"`. The root cause is that the native lib resolver and GAC assembly resolvers are not yet registered when running `Import-Module` in this way. It's an unexpected regression from the PR https://github.com/PowerShell/PowerShell/pull/18356, specifically [this line of change](https://github.com/PowerShell/PowerShell/commit/1688b0fc356af9f2f9f8bae1e8304bc0929d51a5#diff-20df6f18d8f50364843dfabc414eaed80bbc46ea342e042baaac6a888867f380L518) in `ExternalScriptInfo`.

We depend on `ClrFacade` to be referenced early at startup, but seemingly unrelated change could break that assumption.
