### ISSUE TITLE
Get-Service treats -Name parameter like a -DisplayName

### ISSUE THREAD

**Issue by AaronMargosis** [PowerShell/PowerShell#21312]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Get-Service -Name Browser

### Expected behavior

```console
If SMBv1 is not installed, it should report, “Cannot find any service with service name ‘Browser’”

If SMBv1 is installed, it should show results from the Computer Browser service.
```

### Actual behavior

```console
Always reports about the bowser kernel driver (display name = “Browser”).
```

### Error details

```console
Get-Service is being excessively flexible about treating the -Name parameter as a key name or a display name, and it should treat it strictly as a key name. There is a separate -DisplayName parameter. From the Get-Help:

-DisplayName <System.String[]>
    Specifies, as a string array, the display names of services to be retrieved. Wildcards are permitted.
 
-Name <System.String[]>
    Specifies the service names of services to be retrieved. Wildcards are permitted.
 
This is problematic because the Center for Internet Security’s recommended baselines for Windows includes ensuring that if the Computer Browser service is present, it should be disabled. The following line shouldn’t disable the bowser.sys driver, but it does:
 
Get-Service -Name Browser | Set-Service -StartupType Disabled
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![getservicebug](https://github.com/PowerShell/PowerShell/assets/24351128/ec7eb56d-2f6d-4e01-a1fc-f89fbbcb73fe)

**Comment by jborean93** [comment]
Changing this behaviour would probably have quite a large impact where people currently expect the `-Name` to match the display name. I see two potential options:

+ Add a `-ServiceName` parameter which only matches by the service name
+ Add a switch parameter like `-SearchByNameOnly` (or something along those lines) to only search by the service name

As for workarounds for this particular scenario you could:

+ Filter after the search `Get-Service -Name Browser | Where-Object { $_.Name -eq 'Browser' }`
+ Search by display name only `Get-Service -DisplayName 'Computer Browser'`
  + This has the downside if the display name is localised and you need to deal with different languages
+ Use the .NET API instead of these cmdlets

**Comment by AaronMargosis** [comment]
I agree that backward compatibility concerns make properly fixing the behavior of the `-Name` parameter less than feasible. But the Get-Help can at least be corrected to describe what the existing behavior is. (And if not actually backport that fix to Windows PowerShell, at least fix the documentation online.)

**Comment by iSazonov** [comment]
These parameters are definitely different.
https://github.com/PowerShell/PowerShell/blob/ad2bf787e4e7dfde9123a67349cf1ae6ccdfc984/src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs#L574-L589

https://github.com/PowerShell/PowerShell/blob/ad2bf787e4e7dfde9123a67349cf1ae6ccdfc984/src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs#L197-L210

And they are handled differently
https://github.com/PowerShell/PowerShell/blob/ad2bf787e4e7dfde9123a67349cf1ae6ccdfc984/src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs#L331-L349

Although it's not clear why the algorithms are different
https://github.com/PowerShell/PowerShell/blob/ad2bf787e4e7dfde9123a67349cf1ae6ccdfc984/src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs#L372

https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs#L435

I guess that's why we're getting weird results.
And that's not the only case. For example:
```powershell
Get-Service -Name Browser

Status   Name               DisplayName
------   ----               -----------
Running  bowser             Browser


Get-Service | where Name -eq browser

<empty>
```

**Comment by AaronMargosis** [comment]
Also strange that I normally can't get Get-Service to return kernel drivers by name unless I explicitly provide the key name, or by display name at all:
Get-Service -Name b* doesn't return any drivers, just services.
Get-Service -DisplayName 'Browser' doesn't return the bowser driver.
Get-Service -Name 'Browser' returns the bowser driver, as does Get-Service -Name 'Bowser'.
This is just pretty badly broken.

**Comment by AaronMargosis** [comment]
Get-Service -Name 'Browser' | ?{ $_.Name -eq 'Browser' }

This is pretty bad.

**Comment by rhubarb-geek-nz** [comment]
I suggest compare it with "sc query", for instance

```
PS> sc query | findstr SERVICE_NAME | findstr bowser
```

does not return "bowser"

but asking specifically does get it

```
PS> sc query bowser | findstr SERVICE_NAME
SERVICE_NAME: bowser
```

PowerShell is not magic and does rely on the underlying APIs and commands

**Comment by AaronMargosis** [comment]
sc.exe is not an API. And the underlying APIs are not the problem -- it's how the provided cmdlets are calling them.

**Comment by rhubarb-geek-nz** [comment]
> sc.exe is not an API. 

DESCRIPTION:
        SC is a command line program used for communicating with the
        Service Control Manager and services.

I did say "API and commands". If one is writing a batch file then `sc.exe` is effectively an API. If you can call RESTful services an API then invoking an exe with a well documented interface can certainly be counted as an API.

sc.exe is also a good example of how the underlying API is expected to be used, If "sc query" does not return "bowser" then there must be a good reason why. Perhaps there may be a high cost to an exhaustive search for services that querying directly by name avoids. 

Also, file system drivers might not be considered services in the true sense.

For instance

```
sc query | findstr FILE_SYSTEM_DRIVER
```

does not return any.

**Comment by rhubarb-geek-nz** [comment]
Looks like Get-Service finds more services than "sc query"

```
PS> (Get-Service).Count
Get-Service: Service 'McpManagementService (McpManagementService)' cannot be queried due to the following error: PermissionDenied
Get-Service: Service 'NPSMSvc_ef99075 (NPSMSvc_ef99075)' cannot be queried due to the following error: PermissionDenied
Get-Service: Service 'WaaSMedicSvc (WaaSMedicSvc)' cannot be queried due to the following error: PermissionDenied
292
PS> (sc query | findstr SERVICE_NAME).Count
130
```

**Comment by AaronMargosis** [comment]
The problem isn't the Win32 APIs. The PowerShell cmdlets are built on the .NET Framework and the ServiceController class in particular. 

The ServiceController.GetServices() method correctly documents that it enumerates only services and not drivers. (The GetDevices() method retrieves drivers.) The ServiceController constructor that takes a string parameter documents that the input string can be the service name or its display name, and (although not explicitly documented) can refer to a service or a driver. 

In the Get-Service implementation, if a supplied -Name parameter doesn't contain wildcard characters, the cmdlet doesn't call GetServices and filter its results; instead it uses the ServiceController constructor with the -Name parameter, resulting in incorrectly treating it as a service name or as a display name. The ServiceController class doesn't provide a constructor or method that explicitly takes just a service name. The "doesn't contain wildcard characters" shortcut is where the bug is. I think it would have been correct had the -Name parameter had been treated as a pattern.

**Comment by SteveL-MSFT** [comment]
@AaronMargosis as noted, this is the same behavior in WinPS5.1 so it would be a breaking change.  However, as suggested by @jborean93 it may make sense to have a new switch (seems like `-ServiceName` is already an alias) to have it match ServiceName only (filtered within the cmdlet since the .NET API is too broad).  Will have Cmdlets WG review.

**Comment by AaronMargosis** [comment]
How about changing `-ServiceName` from an alias to its own parameter. It shouldn't be a back-compat problem to make `-ServiceName` work the way it should, right? Today, `Get-Service -ServiceName 'Browser'` incorrectly returns the bowser.sys driver if the Computer Browser service isn't present.

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets reviewed this.  As this cmdlet behaves the same as 5.1 and has a strong chance of users depending (knowingly or not) on current behavior, we can't make any changes.  However, we should improve our documentation to specify:

- Enumeration does NOT include device driver services
- When wild card is specified, the cmdlet performs filtering ONLY on Windows services (device services are NOT included)
- If you specify the name which is an exact device service name or exact display name, then that instance will be returned

**Comment by SteveL-MSFT** [comment]
Doc bug https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10966

**Comment by TuemmlerKelch** [comment]
Is this really it? This is the equivalent of airbus adding "plane might lose a wing mid-flight" to the manual instead of making sure the wing sticks to the plane.
Is there any way to escalate or reevaluate this?
I get the argument that fixing this would break backwards compatibility for people that didn't use the command as they were intended and removing something that might have been designed as a fallback.

But just neglecting the idea to add another parameter to enforce correct behavior? I cannot wrap my head around that.
Please reconsider.

**Comment by AaronMargosis** [comment]
> Is this really it? This is the equivalent of airbus adding "plane might lose a wing mid-flight" to the manual instead of making sure the wing sticks to the plane. [...]

It _totally_ sucks that this bug exists, but to be fair: at this late date, I think lots more planes will fall out of the sky (metaphorically) by fixing the bug now than by living with the bug.

**Comment by coolcoder250** [comment]
The "bowser" service name in Windows 10 is a typo of "browser". While "bowser" refers to the "Computer Browser" service in Windows, the correct and more common name would be "Browser".

**Comment by AaronMargosis** [comment]
@coolcoder250 , that's incorrect.

**Comment by AaronMargosis** [comment]
Here's the background on "bowser:"
https://learn.microsoft.com/en-us/archive/blogs/larryosterman/fun-with-names

**Comment by AaronMargosis** [comment]
The service with the key name "Browser" (and display name "Computer Browser") exists only when SMBv1 is installed. The driver with the key name "Bowser" and display name "Browser" is always present and several services depend on it.

**Comment by coolcoder250** [comment]
Excuse me I couldn't explain my comment completely.  It's a common question, and the name "Bowser" for the Browser service in Windows can indeed seem confusing at first. I found that the name "Bowser" is an intentional and historical naming convention used by Microsoft. The name "Bowser" has been used since the early days of Windows networking. It dates back to the days of NetBIOS and the LAN Manager, which were the predecessors to the current Windows networking stack. The term "Bowser" is a play on words, derived from the word "Browser." It is a common practice in software development to use internal names that are slightly different from the display names to avoid conflicts and to add a bit of humor or inside joke. The "Browser" service (internally named "Bowser") is responsible for maintaining a list of computers on a network and providing this list to other computers. So it seems the name "Bowser" is not a typo or a mistake. It is a deliberate and historical choice by Microsoft engineers.

**Comment by AaronMargosis** [comment]
So you didn't read the link I provided, with the explanation from the individual responsible, who was actually there?

**Comment by coolcoder250** [comment]
I read the link, interesting story, :)
