### ISSUE TITLE
Iterator variable `$_` is `$null` in process block when parameter is provided as argument instead of pipeline

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/PowerShell#21327]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

## MRE

```powershell
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version '3.0'


function Test-Something
{
  param
  ( [Parameter(Mandatory = $true, Position = 0, ValueFromPipeline = $true)][hashtable[]]$Assertions
  )

  begin { [hashtable[]]$retValue = @{} }

  process
  {
    [hashtable] $assertion = $_

    $retValue += $assertion
  }

  end { $retValue }
}



[hashtable[]]$test =
@(
  @{
    IntValue = 123
    HashValue =
    @{
      HashIntValue = 456
    }
  }
)

Test-Something -Assertions $test
```

### Expected behavior

```console
`$_` should be equal to `$Assertions[0]`
```

### Actual behavior

```console
`$_` is `$null`
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core 
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![VS Code debugging session](https://github.com/PowerShell/PowerShell/assets/9283914/c18953b8-a09f-41bd-a0c0-6b8f039b7b6b)

**Comment by mklement0** [comment]
* `$_` only has a meaningful value with _pipeline input_, not also when input is provided via _arguments_.

* Fundamentally, do _not_ rely on `$_` in the `process` block of advanced script functions / scripts that explicitly declare pipeline-binding parameters - only use the latter.

In your case, this means that your `process` block should (a) only act on `$Assertions`, and (b) be aware of the fact that `$Assertions`, due to its declaration as `[hashtable[]]`,  is always an _array_ of `[hashtable]` instances, even if `[hashtable]` instances are provided _one by one_ via the pipeline.

**Comment by SetTrend** [comment]
Thanks a lot for enlightening me, @mklement0!

Would you agree that this important fact should be mentioned in the docs at
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_methods#process

**Comment by mklement0** [comment]
Glad to hear it helped, @SetTrend , and I agree re the docs; see:
* https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10944

**Comment by sdwheeler** [comment]
The documentation for the [process][1] block says:

> The automatic variable `$_` or `$PSItem` contains the current object in the pipeline for use in the process block. 

Since you are calling the function with a parameter, there is nothing in the pipeline. The function needs to handle the parameter variable. This version of the function works for both pipeline input and parameter input.

```powershell
function Test-Something {
    param (
        [Parameter(Mandatory = $true, Position = 0, ValueFromPipeline = $true)][hashtable[]]$Assertions
    )

    begin { [hashtable[]]$retValue = @{} }

    process
    {
       foreach ($assertion in $assertions) {
           $retValue += $assertion
       }
    }

    end { $retValue }
}
```


[1]: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_advanced_methods#process

**Comment by mklement0** [comment]
For context, @sdwheeler:

* [This previous comment](https://github.com/PowerShell/PowerShell/issues/21327#issuecomment-1987487196) already explains the issue, and it makes it clear that _you shouldn't use `$_` in the `process` block of advanced functions_ - use the _parameter (variable)_ declared to be pipeline-binding. 
  *  https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10944#issuecomment-1992062041 explains why in more detail.

* @SetTrend had run into the original problem because had _relied_ on the documentation, which confusingly _actively suggests using `$_`_ (which is only appropriate for _non_-advanced functions).

  * The fact that the passage you quote from the documentation only mentions the  _pipeline_ is technically correct, but doesn't prevent conceptual confusion, as evidenced by the case at hand.

* He then suggested that the documentation be amended, causing me to create https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10944, which you've recently closed as `resolution-wont-fix`, which is inappropriate in my estimation.
