### ISSUE TITLE
Return statement assigned to a variable behaves different on recent versions 7.4 and 7.5

### ISSUE THREAD

**Issue by marchese** [PowerShell/PowerShell#21340]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Following script produces inconsistent results in recent versions (v7.5.0-preview.2 and 7.4.1) when compared to previous LTS versions (7.2 and 5.1).

To reproduce this issue, save the following code to a file:

test.ps1
```
$data = return 1
Write-Host "data: $data"
return 2
```

Then, run the script on the PowerShell versions 5.1, 7.2, 7.4, and 7.5.
7.4 and 7.5 versions don't return anything (not even an error), while previous versions 5.1 and 7.2 return 1.
This breaks backward compatibility for existing scripts to work with recent versions.

Was this change intentional? if yes, please link the documentation for further reference, thanks

### Expected behavior

```console
PS> .\test.ps1
1
```

### Actual behavior

```console
PS> .\test.ps1
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.5.0-preview.2
PSEdition                      Core
GitCommitId                    7.5.0-preview.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
That is unfortunate; the behavior has been discussed before:

* https://github.com/PowerShell/PowerShell/issues/20739#issuecomment-1821358286

**Comment by rhubarb-geek-nz** [comment]
I would not expect the assignment of return to execute at all. Return should be a flow control change.

Would you expect assignment to work with throw?

```
PS> $foo = throw 'bar'
bar
At line:1 char:8
+ $foo = throw 'bar'
+        ~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (bar:String) [], RuntimeException
    + FullyQualifiedErrorId : bar

PS> $foo
```

**Comment by marchese** [comment]
> Would you expect assignment to work with throw?

No

**Comment by mklement0** [comment]
@rhubarb-geek-nz:

* The problem, as also discussed in the linked issue, is that an - unacknowledged -  _breaking change_ occurred between 7.3.x- and below and 7.4.0+

* Indeed, `return` _itself_ has no "return value" (success-stream output) -  as opposed to its optional argument, which is sent to the success output stream first. However, that is a _moot point_: the _assignment never happens_, because `return` _instantly exits the enclosing script block_, so no assignment ever happens  (note that functions and script files are script blocks too, just named ones).

* While the minimal example of `$data = return 1` doesn't make sense in terms of the _assignment_ (as noted, it never happens), the pre-7.4 behavior was definitely meaningful in terms of _control flow_ and _success-stream output_ - and the latter is now _broken_.

Here's an example closer to real life:

```powershell
function Foo {
  $a = 
    if ($true) { # simulate some condition that may or may not be true
       # Short-circuit further processing and return here.
       return 1
    } else {
      2 
    }
 $a + 1  # output, based on further processing of $a
}
```

`Foo` - sensibly returns `1` in v7.3x-, but unexpectedly outputs nothing in 7.4+

**Comment by rhubarb-geek-nz** [comment]
If you split the return 1 into two lines you get the equivalent behaviour

```
function Foo {
  $a = 
    if ($true) { # simulate some condition that may or may not be true
       # Short-circuit further processing and return here.
		1
		return
    } else {
      2 # assign to $a
    }
 $a + 1  # output, based on further processing of $a
}
```

So it looks like in 7.3* the assignment is capturing all the success stream whether return is called or not,, moving the assignment gets the desired behaviour

```
function Foo {
    if ($true) { # simulate some condition that may or may not be true
       # Short-circuit further processing and return here.
		1
		return
    } else {
      $a = 2 # assign to $a
    }
 $a + 1  # output, based on further processing of $a
}
```

**Comment by mklement0** [comment]
@rhubarb-geek-nz, just to be clear: while your reformulation may serve as a _workaround_, the point is that _it shouldn't be necessary_, and there was _never a good reason for the previous behavior to change_.

**Comment by rhubarb-geek-nz** [comment]
>there was _never a good reason for the previous behavior to change_.

On the other hand you have an inconsistent situation and undocumented behaviour where you are expecting the output of the `if` to go to both the assignment _and_ the output of the function itself.

**Comment by mklement0** [comment]
No, no one is expecting that, and no, there is no inconsistency in the previous behavior, surprising though as it may be.
The `return` has nothing to do with the incidental `if` it happens to be a part of.

**Comment by rhubarb-geek-nz** [comment]
> The `return` has nothing to do with the incidental `if` it happens to be a part of.

It may not be the return flow-control but it is the success-stream, the documentation describes using Write-Output as equivalent

> Write-Output with NoEnumerate parameter.

```
function Test-Return
{
    $array = 1, 2, 3
    return Write-Output -NoEnumerate $array
}
```

So the return valuie is actually written to the output stream. For the assignment to work the it must be treated as a nested statement to capture the output.

**Comment by mklement0** [comment]
On a meta note, @rhubarb-geek-nz:

* It's good to know when something is _undocumented_ - potentially leading to this deficiency getting addressed.

* In the absence of documented behavior, users take advantage of _de facto_ behavior - we now have two issues confirming just that.

* The latter needs to be taken into account if and when making breaking changes, and such changes must be clearly announced and documented.

That said, in the case at hand:

* no breaking change was announced

* there is _no_ discernible reason for the breaking change that occurred - suggesting it was accidental and therefore amounts to a _bug_.

**Comment by mklement0** [comment]
@rhubarb-geek-nz, let me stress again: In `$a = return 1`, _there is no assignment_ - there never was, and there isn't now. However, there _should be success-stream output_, as seen _by the caller_ - as has always been the case up to v7.3.x - but is inexplicably no longer the case in v7.4+

**Comment by rhubarb-geek-nz** [comment]
> @rhubarb-geek-nz, let me stress again: In `$a = return 1`, _there is no assignment_ - there never was, and there isn't now. 

I am happy that the assignment never occurred because the return changed the flow ( like a longjmp ). 

The inconsistency was that.

1. an assignment means take all the output of the statement to the right and put it into this variable
2. a return statement with value is logically a Write-Object followed by a longjmp

```
PS> $foo = Write-Object 'bar'
PS> $foo
bar
```

So of you use Write-Object and make it throw an exception, to be the equivalent of the return exiting the function

```
trap
{
        throw $PSItem
}

$ErrorActionPreference = 'Stop'

$foo = Write-Object -InputObject 'bar' -NoSuchArgument
```

The assignment  also does not occur, but it would not write to the output of the function or script because the output of the statement goes to the assignment.

```
Exception: foo.ps1:10
Line |
  10 |  $foo = Write-Object -InputObject 'bar' -NoSuchArgument
     |         ~~~~~~~~~~~~
     | The term 'Write-Object' is not recognized as a name of a cmdlet, function, script file, or executable program.
     | Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

If you replace the "return 1" with "return Write-Output 1" in the original script you still get the same behaviour, so it is not the return that is making the difference it is how the success-stream is managed for an assignment.

**Comment by rhubarb-geek-nz** [comment]
If you take the model that return is Write-Object followed by an equivalent of longjmp then the if shouldn't be writing to two different places, either to the value that gets put in the assignment, or the success stream of the function.

This now has if false condition

```
function Foo {
  $a =
    if ($false) { # simulate some condition that may or may not be true
       # Short-circuit further processing and return here.
      return 1
    } else {
      2 # assign to $a
    }
 $a + 1  # output, based on further processing of $a
}

Foo

```
So this does not return both 2 and 3, only 3. So the result of the if only goes to the assignment, not the output of the function.

If you change the code to

```
function Foo {
  $a =
    if ($true) { # simulate some condition that may or may not be true
       # Short-circuit further processing and return here.
        3
        return 1
    } else {
      2 # assign to $a
    }
 $a + 1  # output, based on further processing of $a
}


Foo
```

Then 5.1 prints

```
3
1
```

and 7.4 prints nothing because the output went to the assignment that never occurred. It also shows that it is not just the return value that is affected, it is all the output within the if.

**Comment by rhubarb-geek-nz** [comment]
If you replace the return with throw, which is also like a longjmp then the 3 never gets output

```
function Foo {
  $a =
    if ($true) { # simulate some condition that may or may not be true
       # Short-circuit further processing and return here.
       3
       throw 1
    } else {
      2 # assign to $a
    }
 $a + 1  # output, based on further processing of $a
}


Foo
```

7.4 prints only the exception

5.1 prints 1, which is "$null + 1", so it aborted the assignment leaving it with a value of $null

So although the behaviours are different, they are both internally consistent that throw and return both act like a longjmp.

**Comment by mklement0** [comment]
* The behavior of `return` mustn't change: it is and always has been _unrelated to assignments_: it _unconditionally_ exits the script block at hand, while optionally also writing output to the success output stream.

* _Combining_ assignments and `return` in the same script block (be it an anonymous one or a  named one (`function`, script file)) makes `return` _preempt_ the assignment, simply due to the fact that execution of the script block _ends right there and then_.

* It is therefore the script block's _caller_ that should receive the success output, as it has always worked (whether or not an assignment was involved) and as it should definitely continue to work - see illustration below. 

  * To me, the v7.4+ behavior of quietly _discarding_ the success output produced via `return` is therefore unequivocally a _bug_.

 
* From a code-maintenance perspective (conceptual clarity), It is probably not a great idea to combine `return` with assignments that way, given the confusion it may engender, but, as the two issues here show, code like that is out there, and I don't think there's a good reason to _disallow_ the practice, especially not now, given that it breaks existing code.

To me, the upshot in terms of actionable items is:

* Fix the bug introduced in 7.4.0, i.e. restore the usual, assignment-unrelated  `return` behavior
* Amend the [about_Return](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Return) help topic to explain how combining assignments with `return` works, and possibly advise against it.



----

To illustrate the assignment-independent output logic of `return`:

```powershell
# Should store 1 in $outputFromScriptBlock
# Script block is instantly exited, so no assignment takes place, 
# and no more code in the script block is run.
$outputFromScriptBlock = 
  & {
     $neverGetsAssigned = return 1
     'never get here'
  }
```

_should_ be in effect the same as the following, and _was_ until 7.3.x; 7.4 broke that:

```powershell
$outputFromScriptBlock = 
  & {
     return 1
  }
```

**Comment by mklement0** [comment]
> a PowerShell assignment should really be considered as the right hand side running in its own scope 

It definitely does _not_ run in its own scope, and that's the crux of the issue:

`$a = return 1` is most definitely _not_ shorthand for `$a = & { return 1 }` and it isn't even shorthand for `$a = . { return 1 }` (dot-sourcing), due to the involvement of a (by definition _nested_ inside the enclosing script block in which the assignment takes place) script block, which the embedded `return` then exits from.

> both 5.1 and 7.4 implement assignment with return badly and inconsistently.

WinPS 5.1 and  PS Core 7.3- exhibit _consistent_ behavior, which, while potentially confusing, can be understood [if properly framed](https://github.com/PowerShell/PowerShell/issues/21340#issuecomment-1997377649).

v7.4+ behavior is unequivocally broken.

**Comment by rhubarb-geek-nz** [comment]
> `$a = return 1` is most definitely _not_ shorthand for `$a = & { return 1 }` 

Absolutely true, and that is what makes it a mess.

**Comment by mklement0** [comment]
> I was saying it should have been/should be its own scope.

Frankly, even if backward compatibility weren't a concern: what you're proposing strike me as creating a bigger mess: why would you need `return` in order to assign a value to a variable (except potentially from a nested script block)? Why should the scope of a `return` statement change based on whether or not it is part of a assignment?

Currently, the rules - once properly framed - are simple: 

 * Any given statement behaves the same, including with respect to flow-control keywords such as `return` - whether or not its output happens to be captured in (assigned to) a variable.

 * Flow-control keywords (`return`, `exit`, `throw`, `break`, `continue`) can therefore _bypass_ assignments and always cause instant exit from the _enclosing_ scope or loop (in the `break` or `continue` case).

However, we're in agreement that combining assignments with flow-control keywords is _best avoided_, due to the confusion it can create - it obviously makes no sense in the minimal `$a = return 1` example, but as shown [earlier](https://github.com/PowerShell/PowerShell/issues/21340#issuecomment-1995879173), there are cases where it can be leveraged meaningfully, and seemingly has been in existing code, namely taking advantage of PowerShell's - generally beneficial - ability to capture output from entire so-called language statements in a variable (e.g., the output from an entire `if`, `foreach` or, as in the linked issue, `switch` statement).


I've amended my list of actionable items [above](https://github.com/PowerShell/PowerShell/issues/21340#issuecomment-1997377649) to suggest possibly implementing a new PSSA rule that would warn in such cases.

That, in combination with updating `about_Return` - and, obviously, fixing the 7.4+ bug - strikes me as sufficient.

**Comment by rhubarb-geek-nz** [comment]
Although UNIX shell return is a different beast because it affects the return code., not stdout, I thought you might like

```
$ FOO=$( return 1 )
-bash: return: can only `return' from a function or sourced script
```

**Comment by mklement0** [comment]
Makes sense in POSIX-like shells. Despite the overlap in syntax, PowerShell is often a very different beast:

PowerShell's `$(...)`, while it creates a nested _pipeline_, doesn't create a _new script block_ (and also no subshell (child process)), so `$a = return 1` and `$a = $(return 1)` behave the same.

However, as I've just discovered, the 7.4+ bug also plagues `@(...)` in earlier versions; the following assigns "nothing" (`[System.Management.Automation.Internal.AutomationNull]::Value`) to `$a`, in _all_ versions (whereas switching to `$(...)` works as expected in 7.3-):

```powershell
# Should be '$a: [1]', but is '$a: []'
$a = & { $bypassed = @(return 1); 'never get here' }; "`$a: [$a]"
```

**Comment by daxian-dbw** [comment]
@SteveL-MSFT Can you please share the link to the duplicate issue here? Thanks!

**Comment by mklement0** [comment]
@daxian-dbw, I'm pretty sure @SteveL-MSFT means the previously mentioned duplicate:

* #20739
