### ISSUE TITLE
[Improvement Request] Remedy the execution differences between providing an argument either by pipeline or command line argument to the same function parameter

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/PowerShell#21354]
### Summary of the new feature / enhancement

Concluding from the discussion with @mklement0 and @sdwheeler at [https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10944](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10944#issuecomment-1992607384), I'd like to propose to have PowerShell drop the execution differences between providing an argument to a `ValueFromPipeline = $true` advanced function parameter either by pipeline input or command line argument.

## Current Situation

Provided we have an advanced function like this:

```powershell
function Get-Function
{
  param
  ( [Parameter(ValueFromPipeline = $true)] [int[]]$PipelineArgument
  )

  begin { [int]$i = 1 }
  process { $i += 1 }
  end { $i }
}
```

… then calling it either by …

```powershell
1..10 | Get-Function
```

… or …

```powershell
Get-Function -PipelineArgument 1..10
```

… yields two very different execution workflows and, thus, results in different output in above example.

The current situation leads to complex boilerplate code to provide for both variants of calling the same function.

## Desired Situation

Both types of calling the same function should result in a single, deterministic execution flow.

## Proposed technical implementation details (optional)

I created a repository providing an analysis and a solution proposal:
- https://github.com/SetTrend/PowerShell---Pipeline-vs-Argument

**Comment by theJasonHelmick** [comment]
Hi @SetTrend  -- thank you for this suggestion.  The advanced function arguments `valuebypipeline` and `valueFromPipelineByProprtyName` are by design.

**Comment by rhubarb-geek-nz** [comment]
As @mklement0  would say, it is all about the story you tell.

Command line arguments work well with single objects, even when those single objects are arrays. They stay as single array objects.

Pipelines work well with multiple records and are the most efficient way of processing multiple elements.

The problem is not with the function itself but how the pipeline is written to the function.

In this case the array is automatically enumerated on the pipeline write, this can be circumvented.

With you exact function on 7.4.1

```
'expanding array as stdin'

1..10 | Get-Function

'single typed argument'

Get-Function -PipelineArgument ([int[]](1..10))

'single array as stdin'

Write-Output -InputObject ([int[]](1..10)) -NoEnumerate | Get-Function

```
You get

```
expanding array as stdin
11
single typed argument
2
single array as stdin
2
```

So you can get consistent results between pipeline and arguments if you want it.

The trick is to use arguments or the input pipeline depending on the result you want. They are not automatically interchangeable.

In much the same way that assignment to get the output does not always give the same results as pipeline output to another element.

**Comment by SeeminglyScience** [comment]
> Pipelines work well with multiple records and are the most efficient way of processing multiple elements.

If you're talking about CPU time then a `foreach` statement would be the most efficient option as it's a direct language element and doesn't involve the same context switching that invoking a process block does. If you're talking about memory efficiency, that can be true but only if the pipeline is actually utilized (e.g. `Get-Function -PipelineArg (Get-ChildItem)` will still run `gci`, create an array with the results, and pass it as-is as an argument)

> The problem is not with the function itself but how the pipeline is written to the function.
> (...)

I'm not entirely sure what you're trying to convey with the rest. If you're suggesting that a cast be used to opt out of the change, it's still breaking by default for many commands that rely on the behavior.

I'd suggest just adding a `foreach` in your process block to get the same effective behavior, or simply always pipe.

**Comment by rhubarb-geek-nz** [comment]
> I'm not entirely sure what you're trying to convey with the rest.

I was trying to say that you can pass in an array in with a pipe by using Write-Object -NoEnumerate to get the same behaviour as a single command line argument.

>  it's still breaking by default for many commands that rely on the behavior.

I'm not suggesting any breaking behaviour because I am not asking for any changes.

> I'd suggest .. simply always pipe.

Absolutely, if pipes give you the behaviour you want them use them.

**Comment by jhoneill** [comment]
Cmdlets and functions which take pipeline input SHOULD as general rule work so 

`$Array | command  -operationalParameters` 
is the same as 
`command -Target $array  -operationalParameters `

inside a function it is usually as easy as 
```
process { foreach ($t in $Target) {
  do stuff with $t instead of $Target
}}
```

However there cases where we don't want that behaviour.  For example 
`$a | Get-Member`  processes each item in the array. `Get-Member -InputObject $a` processes the array itself. 

A global change to make the `for` loop redundant would mean we couldn't have that functionality. So things which aren't terribly well implemented do work.

**Comment by SetTrend** [comment]
@theJasonHelmick: 

> Changing that would be a breaking change.

Why would this be a breaking change? I don't see any reason why a programmer explicitly wanted his/her advanced function to behave differently and provide different results when being called via pipeline than via command line argument. I've never seen such behavior being documented or commented in any officially released Cmdlet.

I suppose, any existing Cmdlet providing an `ValueFromPipeline = $true` attributed parameter comes with boilerplate code to remove the existing distinction.

Anyway, harmonizing this by internally converting an `ValueFromPipeline = $true` attributed command line argument into a pipeline argument wouldn't break anything as the pipeline execution workflow already runs flawlessly in any of the Cmdlets. We would just be cutting of the other, redundant, execution workflow.

Please reconsider and reopen.

**Comment by SeeminglyScience** [comment]
> Why do you believe this would be a breaking change? I don't see any reason why a programmer explicitly wanted his/her advanced function to behave differently and provide different results when being called via pipeline than via command line argument. I've never seen such behavior being documented or commented in any officially released Cmdlet.

`Get-Member` is the easiest and most common example

```powershell
$list = [System.Collections.Generic.List[string]]::new()
Get-Member -InputObject $list
# vs
$list | Get-Member
```

Some folks also use it for performance reasons, if we instead called the process block for every single item it would be a huge perf regression.

---

Other questions that complicate it:

- How does `InvocationInfo.ExpectingInput` change
- What happens when you have two parameter that can take pipeline input, there is an upstream command, and one of the parameters is specified. Do you run the process block for every upstream item *and* every item passed explicitly?
- How does `ValueFromPipelineByPropertyName` factor in?

**Comment by mklement0** [comment]
@SetTrend:

* I am sympathetic to the intent of harmonizing by-argument and by-pipeline input, and the current asymmetry is what led me to  open #4242 (almost 7 years ago).

* It is clear by now that changing the _default_ behavior is not an option, which leaves the question whether implementing what you propose is worth doing as an _opt-in_ behavior, as explored below.

---

I see two main motivations for supporting `<cmd> -InputObject $array` as interchangeable with `$array | ... <cmd>`:

* Simplify the _implementation_ of cmdlets / advanced functions, which is what you're proposing. That is, make it easier for command _authors_.

* Support `<cmd> -InputObject $array` _for performance reasons_: That is, avoid _per-object (array-element)_ `process` block invocations, and _explicitly loop_ over the input array _in the one and only invocation_.
  * For instance, `Set-Content /dev/null -Value (1..1e6)` is _much_ faster than `1..1e6 | Set-Content /dev/null`
  * Unless a given pipeline-binding parameter is _array_-typed or is a _strongly typed scalar_, you cannot reliably infer whether direct-argument use is meaningfully supported; that is, an `[object]` or `[psobject]`-typed parameter - due to also accepting arrays - could still perform explicit looping.
     * Doing so actually helps parameter-binding performance in the pipeline, but at the expense of type safety.
     * Conversely, the explicit-looping approach with an _array_-typed parameter slows the pipeline down: each individual input object must be _wrapped in a single-element array_.
     * In short: Performance-optimizing with direct array arguments is invariably a _trade-off_ in that it slows the pipeline down: with array-typed parameters _both_ in the parameter binder _and_ the explicit looping; with an `[object]`-typed parameter it is only the latter (though if `[object]` isn't actually the appropriate type, there's an additional penalty for type-checking).

  * As an aside: 
    * The syntax diagrams currently do not even tell you which parameters are pipeline-binding - see #4135.
   
Unfortunately, implementing the former precludes the latter, because it invariably entails per-object `process` calls.

Even if you deem the former worth implementing in its own right  - as noted, by _opt-in_ - despite performing worse than explicit looping,  it would come with many conceptual challenges and would require changes to many components, including the parameter binder and syntax diagrams, primarily because you'd need to declare your parameters as _scalars_ (e.g. `[int]`) - because that's how your `process` block will then see them, but the parameter binder would have to accept `[int[]]` as direct arguments, and also reflect that in the syntax diagrams.

---

As for the performance aspect:

The following sample code and benchmarks illustrate the performance trade-offs of the various approaches, via variations of a cmdlet that sums all input integers given; `Get-Sum_ImplicitLoop` emulates the unified processing you tried in https://github.com/SetTrend/PowerShell---Pipeline-vs-Argument

On my Mac, I get the following timings, for example, with `100,000` input integers, averaged over 15 runs:

```none
Factor Secs (15-run avg.) Command                         TimeSpan
------ ------------------ -------                         --------
1.00   0.005              Get-Sum_ManualLoopUntyped $a    00:00:00.0050429
1.07   0.005              Get-Sum_ManualLoop $a           00:00:00.0054002
14.34  0.072              $a | Get-Sum                    00:00:00.0723123
17.37  0.088              $a | Get-Sum_ManualLoopUntyped  00:00:00.0875962
18.27  0.092              $a | Get-Sum_ImplicitLoop       00:00:00.0921211
18.38  0.093              Get-Sum_ImplicitLoop -Number $a 00:00:00.0926784
19.45  0.098              $a | Get-Sum_ManualLoop         00:00:00.0980678
```

As you can see:

* Invocation by direct argument is by far the fastest - except with the unified handling provided by `Get-Sum_ImplicitLoop`.
* With pipeline input, `Get-Sum` is fastest (the traditional, pipeline-input-only approach), and the unified `Get-Sum_ImplicitLoop` approach is actually faster than the strongly typed explicit loop, `Get-Sum_ManualLoop`, presumably because the former doesn't need to loop in the `process` block (`$Number[0]` is sufficient).


Code (requires use of [`Time-Command`](https://gist.github.com/mklement0/9e1f13978620b09ab2d15da5535d1b27); you can install it with `irm https://gist.github.com/mklement0/9e1f13978620b09ab2d15da5535d1b27/raw/Time-Command.ps1 | iex`):

```powershell
# With pipeline-only input (no meaningful direct use of -Number)
function Get-Sum {
  param([Parameter(ValueFromPipeline, Mandatory)] [int] $Number)
  begin { [decimal] $sum = 0 }
  process {
    $sum += $Number
  }
  end {
    $sum
  }
}

# Argument support, with manual loop inside `process`, strongly typed.
function Get-Sum_ManualLoop {
  param([Parameter(ValueFromPipeline, Mandatory)] [int[]] $Number)
  begin { [decimal] $sum = 0 }
  process {
    # Must explicitly loop over $Number
    foreach ($n in $Number) {
      $sum += $n
    }
  }
  end {
    $sum
  }
}

# Argument support, with manual loop inside `process`, untyped ([object])
function Get-Sum_ManualLoopUntyped {
  param([Parameter(ValueFromPipeline, Mandatory)] [object] $Number)
  begin { [decimal] $sum = 0 }
  process {
    # Must explicitly loop over $Number
    foreach ($n in $Number) {
      $sum += $n
    }
  }
  end {
    $sum
  }
}


# Argument support, implicit re-invocation via the pipeline.
function Get-Sum_ImplicitLoop {
  param([Parameter(ValueFromPipeline, Mandatory)] [int[]] $Number)
  begin { 
    if ($done = -not $MyInvocation.ExpectingInput) {
      $Number | & $MyInvocation.MyCommand
    }
    [decimal] $sum = 0
  }
  process {
    if ($done) { return }
    # Note that $Number is now *always* as single-element array, and
    # explicit indexing is still needed.
    $sum += $Number[0]
  }
  end {
    if ($done) { return }
    $sum
  }
}

# Run benchmarks with 100,000 numbers.
[int[]] $a = 1..1e5
Time-Command `
  { Get-Sum_ManualLoop $a },
  { Get-Sum_ManualLoopUntyped $a },
  { Get-Sum_ImplicitLoop -Number $a }, 
  { $a | Get-Sum }, 
  { $a | Get-Sum_ManualLoop }, 
  { $a | Get-Sum_ManualLoopUntyped }, 
  { $a | Get-Sum_ImplicitLoop }
```

**Comment by SetTrend** [comment]
> Some folks also use it for performance reasons, if we instead called the process block for every single item it would be a huge perf regression.

Good point. Well, the best solution then would be to do it the other way around and convert pipeline input into a command line argument, drop the `process` loop and have the programmer manually iterate over all the arrays in a single `process` iteration:

![Harmonize pipeline arguments](https://github.com/PowerShell/PowerShell/assets/9283914/0b35d768-9b14-425b-8b5a-4103da3be6d0)

In this case, taking a function like this one:

```powershell
function Get-Function
{
  param
  ( [Parameter(Mandatory = $true, Position = 0, ValueFromPipeline = $true)] [int[]]$PipelineArgument1
  , [Parameter(Mandatory = $true, Position = 1, ValueFromPipeline = $true)] [string[]]$PipelineArgument2
  )

  begin { [int]$i = 1 }
  process { $i += 1 }
  end { $i }
}
```

... would always yield "2", no matter how the function would be called:

```powershell
PS> 1..4 | Get-Function -PipelineArgument2 'a'..'d'
2
PS> 'a'..'d' | Get-Function -PipelineArgument1 1..4
2
PS> Get-Function -PipelineArgument1 1..4 -PipelineArgument2 'a'..'d'
2
```

Moreover, this would render `begin` and `end` redundant then.

I think this may also answer your other questions.

**Comment by mklement0** [comment]
> drop the `process` loop

For proper, _streaming_ processing in the pipeline (one of its core features), _per-input-object_ invocation of `process` is a must, so I think what you're proposing is fundamentally unviable, even with a hypothetical opt-in.

**Comment by SetTrend** [comment]
> For proper, _streaming_ processing in the pipeline (one of its core features), _per-input-object_ invocation of `process` is a must, so I think what you're proposing is fundamentally unviable, even with a hypothetical opt-in.

Yes, you are perfectly right. I missed that. I was too fast in my reply.

So, I would greatly support your suggestion to get an opt-in option, perhaps an attribute to apply to the function. Something like `[EnforceExecution(Pipeline)]` `[EnforceExecution(Argument)]`.

**Comment by SeeminglyScience** [comment]
> So, then I would support your suggestion to get an opt-in option, perhaps as an attribute to apply to the function. Something like `[EnforceExecution(Pipeline)]` `[EnforceExecution(Argument)]`.

So just to clarify, instead of doing

```powershell
function Test-Function {
    param(
        [Parameter(ValueFromPipeline)]
        [int[]] $Number
    )
    process {
        foreach ($singleNumber in $Number) {
            $singleNumber
        }
    }
}
```

You want to do

```powershell
function Test-Function {
    param(
        [Parameter(ValueFromPipeline = 'Pipeline, Argument')]
        [int] $Number
    )
    process {
        $Number
    }
}
```

That's the ask right?

**Comment by SetTrend** [comment]
Yes, right.

That'd make it clear to the garden-variety PowerShell programmer (like I admittedly am) that there may be two different workflows to expect.

```powershell
function Test-Function
{
  param
  ( [Parameter(ValueFromPipeline = 'Pipeline')] [int[]]$Number )
  process { $Number }
}
```
… would then behave like this:

```powershell
function Test-Function
{
  param
  ( [Parameter(ValueFromPipeline = 'Pipeline')] [int[]]$Number )
  begin { if ($Number) { $Number | Test-Function; exit } }
  process { $Number }
}
```

**Comment by mklement0** [comment]
> `[Parameter(ValueFromPipeline = 'Pipeline, Argument')`

takes us back to:

> ...  would require changes to many components, including the parameter binder and syntax diagrams, primarily because you'd need to declare your parameters as scalars (e.g. `[int]`) - because that's how your process block will then see them, but the parameter binder would have to accept `[int[]]` as direct arguments, and also reflect that in the syntax diagrams.

If this route is taken:

* it should be made clear that this opt-in's primary purpose is one of _implementation convenience_ rather than performance gain (though _binary_ cmdlets would presumably be affected _less_ by the overhead of _per-element_ invocation).

* that said, the _pipeline-input_ case could benefit performance-wise, if there's no longer a need to wrap each input object in a single-element arrary.

**Comment by SetTrend** [comment]
>     * it should be made clear that this opt-in's primary purpose is one of _implementation convenience_ rather than performance gain (though _binary_ cmdlets would presumably be affected _less_ by the overhead of _per-element_ invocation).

Right. But there's one more thing:

Currently, you cannot tell for sure if a parameter has been set by pipeline or by argument, so you cannot act appropriately.

This case, for instance, seems impossible to distinguish:

```powershell
function Test-Function
{
  param
  ( [Parameter(Mandatory = $false, ValueFromPipeline = 'Pipeline')] [int[]]$Number = @(1) )
  begin { if ($Number) { $Number | Test-Function; exit } }
  process { $Number }
}
```

… will cause and endless loop.

>     * that said, the _pipeline-input_ case could benefit performance-wise, if there's no longer a need to wrap each input object in a single-element arrary.

👍

**Comment by jhoneill** [comment]
> Yes, right.
> 
> That'd make it clear to the garden-variety PowerShell programmer (like I admittedly am) that there may be two different workflows to expect.
> 
> On the other hand:
> 
> ```powershell
> function Test-Function
> {
>   param
>   ( [Parameter(ValueFromPipeline = 'Pipeline')] [int[]]$Number )
>   process { $Number }
> }
> ```
> 
> … would then behave like this:
> 
> ```powershell
> function Test-Function
> {
>   param
>   ( [Parameter(ValueFromPipeline = $true)] [int[]]$Number )
>   begin { if ($Number) { $Number | Test-Function; exit } }
>   process { $Number }
> }
> ```
> 
> … by making sure that only a particular workflow will be followed. (Vice versa for `ValueFromPipeline = 'Argument'`, which would cache pipeline input first.)

If you want to pipe into a function but NOT populate a parameter with the pipeline input why not use `$_` ? 

```PowerShell
function Test-Function
{
  param
  ( [Parameter(ValueFromPipeline = $true)] [int[]]$Number )
  begin { if ($Number) { $Number | Test-Function; exit } }
  process { $Number }
}

> 1,2,3 | Test-Function           
1
2
3
> Test-Function 1,2,3  
1
2
3
```

For me there are stages of development for someone writing PowerShell. 

1.  I can pass parameters 
2. OK, one parameter is the target to work on and the others are how to do the work. Instead of  `$stuff | foreach { Myfunction -target $_  -other -parameters} `  I should support `$stuff | Myfunction -other -parameters` 
3. Darn. Now I have to use a process block if the user sends multiple items
4. Oh Some of my process belongs in begin / end 
5. I guess  -Target should handle an array.  so `$stuff = get-stuff;  myfunction $stuff`  works like `get-Stuff | myfunction`  so my process  needs `foreach ($t in $target)` and to work on $t instead of the $target variable.  

Sometimes changing the language to help beginners is good. But here you're asking for something people would still need to learn about, which would produce code that doesn't work on all versions and which most programmers learn they need a loop or to use $_ for.

**Comment by SetTrend** [comment]
> If you want to pipe into a function but NOT populate a parameter with the pipeline input why not use `$_` ?

This issue is not about what *I* want as a programmer of the script but to make sure my script works for *users* of the script no matter how it is being called.

This currently is pretty cumbersome and requires loads of boilerplate "spaghetti" code (= `if`s).

**Comment by mklement0** [comment]
@SetTrend:

> This case, for instance, seems impossible to distinguish.

As shown in the `Get-Sum_ImplicitLoop` function above, `$MyInvocation.ExpectingInput` tells you whether there's pipeline input in a given invocation.
To test whether a given parameter was bound explicitly (rather than by default value), use `$PSBoundParameters.ContainsKey('Number')`, for instance.

However, the questions raised by @SeeminglyScience [above](https://github.com/PowerShell/PowerShell/issues/21354#issuecomment-2009710822) would still need to be worked out, notably how to handle _multiple_ pipeline-binding parameters.

Also:

*  I don't think `PipelineWorkflowOption.Argument` as a stand-alone option is a good idea, because in an invocation such as `1..10 | Test-Function`, users will justifiably expect that _streaming_ processing will occur (except in those cmdlets that _of conceptual necessity_ buffer all input first, such as `Sort-Object`).

* `PipelineWorkflowOption.Pipeline` should be the same as `ValueFromPipeline = $true`

Therefore, the enum could be:

```powershell
enum PipelineWorkflowOption
{
  None = 0   # default - same as [ValueFromPipeline =] $false
  Pipeline = 1 # same as $true
  PipelineOrArgument = 2  # translate array *arguments* into per-element `process` calls
}
```

**Comment by SetTrend** [comment]
Yes, but still that's boilerplate code.

> notably how to handle multiple pipeline-binding parameters.

I've been trying to find any documentation on that but ended up with statements that suggested there should be only one pipeline parameter per parameter set.

> I don't think `PipelineWorkflowOption.Argument` as a stand-alone option is a good idea, because […] users will justifiably expect

Nonetheless, the programmer of the script should have the choice. A well-bred script still chould avoid to use this option. However, there might be cases where it's desired to have things not being streamed, as @SeeminglyScience stated in his comment above.

**Comment by rhubarb-geek-nz** [comment]
> The current situation leads to complex boilerplate code to provide for both variants of calling the same function.

Given the objection is to duplicating boiler-plate code I would point out that Write-Output already has this boiler-plate code implemented, so simply re-use that rathe than duplicating it.

So instead of

```
$myList = 1...10
myFunction $myList myOtherArgs....
```

Simply use

```
Write-Output $myList | myFunction myOtherArgs...
```

Which in PowerShell shorthand becomes

```
$myList | myFunction myOtherArgs
```

Given PowerShell already has a lot of existing inconsistent behaviour, eg single item lists magically becoming single items, and single items being treated as arrays of one by having Count and index operations added, I fear this proposal will just add to the complexity and confusion.

I suggest use PowerShell as it was designed to be used and no need for duplicating the boiler plate which then makes your functions inconsistent in behaviour with the existing gallery of cmdlets and functions. Restrict your function to doing one thing well and allow the caller to invoke it in the manner they need depending on if they have single items or multiple items.

**Comment by SetTrend** [comment]
Let me point out that my proposal doesn't change *any* existing behavior. It's not breakting anything that's existing. It just adds a new option.

These two values are equivalent and lead to existing behaviour:
```powershell
(ValueFromPipeline = $false)  ≡  (ValueFromPipeline = None)
(ValueFromPipeline = $true)  ≡  (ValueFromPipeline = Pipeline+Attribute)
```

**Comment by rhubarb-geek-nz** [comment]
> (ValueFromPipeline = $false)  ≡  (ValueFromPipeline = None)
> (ValueFromPipeline = $true)  ≡  (ValueFromPipeline = Pipeline+Attribute)

[ValueFromPipeline](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.parameterattribute.valuefrompipeline?view=powershellsdk-7.4.0#system-management-automation-parameterattribute-valuefrompipeline)  is already defined as bool so cannot be changed to an enumeration, it is part of the binary contract. You would need a new [ParameterAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.parameterattribute?view=powershellsdk-7.4.0) property.

**Comment by rhubarb-geek-nz** [comment]
A couple more observations...

> (ValueFromPipeline = $true)  ≡  (ValueFromPipeline = Pipeline+Attribute)

Do you mean Pipeline+Parameter or Pipeline+Argument? I interpret the parameter is for the cmdlet but on the command line it is given arguments.

Secondly, with pipelines, the invoker is in control by being able to say "Write-Output -NoEnumerate" to control whether an item is interpreted as single record or multiple items from a list. How would the caller have the same control with your proposal for argument handling? Would the cmdlet need a "-NoEnumerate" standard argument to match Write-Output ?

**Comment by mklement0** [comment]
@rhubarb-geek-nz, fair point about `ValueFromPipeline`; a pragmatic solution would be to add another `[bool]` property, say, `ValueFromPipelineOrArgumentArray` or `ValueFromPipelineOrArray` - while this wouldn't _technically_ prevent specify _both_ this new property and `ValueFromPipeline`, that could be handled with documentation.

Also, fair point about distinguishing between a _parameter_ - the formal placeholder declared by a cmdlet - from an _argument_, i.e. the concrete value bound to the former on invocation. The two are often conflated, unfortunately, leading to ambiguity around whether "parameter" refers to the parameter itself or its situational _value_ - see https://github.com/PowerShell/PowerShell/issues/8839#issuecomment-1385986759 for a previous discussion.

However, we're getting into bike-shedding territory, and it's worth remembering that the proposal was already declined, and that this entire thread may be an academic exercise (which, however, isn't necessarily wasted effort - it can inform future design decisions and, at least hypothetically, future PowerShell versions allowed to break backward compatibility - see https://github.com/PowerShell/PowerShell/issues/6745).

---

With that out of the way:

* Your concerns don't apply, as the proposal changes nothing from the _caller's_ perspective. It is solely about streamlining the _implementation_ of cmdlets, to make it easier to support by-pipeline and by-argument-array interchangeably. 
  * As discussed, the proposal would actually noticeably _slow down_  by-argument-array processing, while slightly speeding up by-pipeline processing.

* > has a lot of existing inconsistent behaviour, eg single item lists magically becoming single items, 

  * With the proper framing, the behavior is neither inconsistent nor is there inexplicable ("magic") behavior: PowerShell _auto-enumerates_ enumerables (and enumerators) in the pipeline and _streams_ the resulting objects. The pipeline itself has no concept of lists; it is an open-ended stream of an indeterminate number of objects.

  * It is only when you _capture_ the success output  stream's output that - of necessity - list-like data structures come into play: a single object can be captured as-is, but multiple objects need a list-like container, which PowerShell provides in the form of `[object[]]` arrays.

* > and single items being treated as arrays of one by having Count and index operations added 

  * This is a _helpful abstraction_ that saves you from having to worry about whether a given command invocation happened to return a single or multiple objects; the explicit alternative is to wrap a command invocation in `@(...)` which wraps a single output object in an `[object[]]` array.

  * In combination with [member-access enumeration](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Member-Access_Enumeration), PowerShell does an admirable  job of _unifying_ the processing of scalars and arrays/list, pitfalls notwithstanding.

**Comment by jhoneill** [comment]
> > If you want to pipe into a function but NOT populate a parameter with the pipeline input why not use `$_` ?
> 
> This issue is not about what _I_ want as a programmer of the script but to make sure my script works for _users_ of the script no matter how it is being called.

They're really one and the same 

There is basic expectation from users. 

If (e.g.) I want to delete 10 files    `$files | foreach {del $_}` , or  `$files | del` or `del $files` all work in the same way, and I can replace $files with `Get-Childitem xxx | where {yyyy} `     
In this case $files goes into the path parameter which accepts an array .  

Inside the command the operations is either going to be
```
begin { $InputArray = @()  }
process  {$inputArray += $Path } 
end { delete everything in $inputArray}
```

or 
process  {foreach ($p in $Path()) ;  { delete $p } } 


> This currently is pretty cumbersome and requires loads of boilerplate "spaghetti" code (= `if`s). Due to this fact, the process is pretty error prone.

Sorry but that is wrong all points. It's neither cumbersome, no ifs are required,  and nor spaghetti is generally not conditions, but pseudo goto commands.  building a loop in the process block to use in end, or putting a for loop  in process doesn't have a lot of scope for errors. 

TBH the most common error I see in other people's functions in this area is not writing  process block (or switching from function to filter)  so that the only one item can be piped into the function. Would the coder who has grasped the need to do this welcome an addition to parameter declaration to  save the a `for` ?  Not greatly.

**Comment by mklement0** [comment]
As for the desire to provide _aggregation_ support by the engine, i.e. to make implementation of cmdlets easier that - of conceptual necessity - need to _collect all input first_, even when received via the pipeline:

* The [automatic `$input` variable](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Automatic_Variables#input) already provides aggregation support without needing to manually build up a list of inputs, albeit not in the most straightforward way: do not consume parameter values in a `process` block, and enumerate `$input` in the `end` bock; this awkwardness is arguably _of conceptual necessity_, however - see below.

* Conceivably, the proposed feature could tie into that by making `$input` enumerate the elements of a by-argument array 

The following illustrates the use of `$input` in an advanced function's `end` block:

```powershell
function Sort-Foo {
  [CmdletBinding(DefaultParameterSetName = 'Numeric')]
  param(
    [Parameter(ValueFromPipeline, ParameterSetName = 'Numeric')] [double] $Number,
    [Parameter(ValueFromPipeline, ParameterSetName = 'String')] [string] $String
  )
  end {
    if ($PSBoundParameters.ContainsKey('Number') -and $PSBoundParameters.ContainsKey('String')) {
      # A *mix* of -Number and -String input - must use [object[]] array
      [object[]] $collected = $input # or: $collected = @($input)
    } elseif ($PSBoundParameters.ContainsKey('Number')) {
      # -Number input only -> strongly type as [double[]]
      [double[]] $collected = $input
    }
    else { # if ($PSBoundParameters.ContainsKey('String')) {
      # -String input only -> strongly type as [string[]]
      [string[]] $collected = $input
    }
    [pscustomobject] @{
      Type   = $collected.GetType()
      Values = $collected
    }
  }
}
```

Try it with the following sample calls - note the different types:

```powershell
1, 2 | Sort-Foo  # -> [pscustomobject] @{ Type = [double[]]; Values = (1, 2) }
'one', 'two' | Sort-Foo  # -> [pscustomobject] @{ Type = [string[]]; Values = ('one', 'two') }
1, 'two' | Sort-Foo  # -> [pscustomobject] @{ Type = [object[]]; Values = (1, 'two') }
```

The above illustrates important subtleties of pipeline-parameter binding:

* With _mixed-type_ pipeline input, _different_ parameters may bind for each input object:
  * This is not only reflected in the aggregate in `$PSBoundParameters` in the `end` block (all parameters that were bound across all input objects), ...
  * but also means that inside a `process` block `$PSCmdlet.ParameterSetName` may indicate a different parameter set for each input object.

**Comment by jhoneill** [comment]
@SetTrend  If it has been marked as declined there's very little point. It's working as a designed, and you'll go on thinking the design should have been different in 2008, and the people with the power to change it will go on seeing the design as a good one. You can argue with no one listening in a closed item just as well as an open one :-)

**Comment by SeeminglyScience** [comment]
@SetTrend The original ask was very different, if you'd like the WG to review a new proposal I'd recommend creating a new issue with all your thoughts organized.

---

That said, this is a really tough sell due to the amount of work required for the impact it would have. My estimate would be at least a month or two of someone's time nailing down all the design questions and eliminating alternatives. That's just in the design part, and would need to be done even if the community was willing to provide a PR. So you'd really be asking for the feature to be funded, and that would require a very large impact to be considered.

If you believe it to have that level of impact, I'd recommend you bring examples of existing projects where the benefit is most obvious and transformative.

**Comment by SetTrend** [comment]
@SeeminglyScience: To which regard was the OT different? "Remedy the execution differences between providing an argument either by pipeline or command line argument to the same function parameter"

Which title would you suggest instead?

Using an `enum` in lieu of a Boolean is the requested remedy.

I very much comprehend the effort of testing the change in the PowerShell repository itself, yet _none_ of the existing code outside of PowerShell needs to be amended [see here](#issuecomment-2016444977). It's only _new_ code that may very much benefit from the change.

As you can see from the following flowchart, existing code would just run through this suggested pre-process code (follow the red rabbit):
![ValueFromPipeline suggested workflow](https://github.com/PowerShell/PowerShell/assets/9283914/b0e02e72-04de-4c5d-a216-82d242972b8d)

I apprehend that I takes some effort to implement the _"Cache pipeline input and call function with argument filled with result"_ step.

The final implementation may vary. Yet, the `ValueFromPipelineAttribute` constructor could easily be complemented with an additional constructor, accepting an `enum`.

## Benefits

- Vista in intentionally expecting two distinct workflows by setting `ValueFromPipeline = Pipeline + Argument`
- New option for creating a single, deterministic workflow, regardless of whether an argument will be provided by pipeline or command line argument

**Comment by SeeminglyScience** [comment]
> @SeeminglyScience: To which regard was the OT different? "Remedy the execution differences between providing an argument either by pipeline or command line argument to the same function parameter"

The original issue description was about changing the behavior, you revised to a different proposal after that was declined. The longer the issue - the longer it takes to convey to everyone in the WG. If you have a new proposal, it's best to create a fresh issue with all your thoughts gathered.

> I very much comprehend the effort of testing the change in the PowerShell repository itself, yet _none_ of the existing code outside of PowerShell needs to be amended [see here](#issuecomment-2016444977). It's only _new_ code that may very much benefit from the change.

Sorry I'm not sure if this was directed at me as I don't see where I mentioned testing. That said, the new feature would still need to work so it would definitely need to be tested.

I do understand what you're asking for though, I just think the benefit it would provide is very small compared to the work involved. That's why I'm suggesting that if you do decide to write a new issue with a full proposal, you bring a lot of real world examples of code that can be vastly improved - and a full exploration of the caveats and questions I've brought up. Without that the proposal will likely be quickly declined. I do have to unsub from this thread now, but I wish you luck!

**Comment by SetTrend** [comment]
Ah, I see … Thanks for clarifying  😊👍 

I'll transfer my thoughts to a new issue then.

**Comment by RalfReddings** [comment]
I just spent the day trying to figure this out and throw in the bucket and finally asked for help on SO. In any case, I hope its addressed in the future as a Opt-in and a middle ground is found.

**Comment by SetTrend** [comment]
Thank you for taking your time!

Currently, I'm in the end phase of a customer project, so I won't be able to create an updated copy of this issue before mid of August. But it surely is in my personal task pipeline, though.

**Comment by jhoneill** [comment]
TBH I think this will struggle to get traction.

As you said   _This issue is not about what I want as a programmer of the script but to make sure my script works for users of the script no matter how it is being called._

And if code it written properly it does. The main problem is people who write commands without thinking about what a user might pass, and whatever extension to PowerShell you come up with which is tidy / doesn't break current code / doesn't require years of coding effort to do, (and good luck satisfying all three) still won't be used by the people who don't use the techniques which have been around since V1 of PowerShell 

As  I said there is a user expectation  `$files | foreach {del $_}` , or `$files | del` or `del $files`  all work in the same way, and I can replace `$files` with `command to get files`  
In this case `$files` goes into the `path` parameter which accepts an array .

Programmer X comes along and says  "paths are strings therefore my `path` parameter will be `[String]`$Path`"  and array of string gets converted into one string.  That programmer might have written a `process` block because the pipeline iterates through files `$files`   using `$files | new-command`  works for an array and `new-command $files` breaks. 

But it's really down to the function writer. 
I've used 
```
If ($path.count -gt 1) {$path | new-command} 
else {
    #  the real body
}
```
Which will unroll arrays of arrays
And 
```
foreach ($p in $path)  {

    # do the real body using P instead of path

}
```
Which will unroll arrays but not nested ones.  And commonly the real body needs things to say "did we get an object, or did we get a string or ID we need to translate into one" 

and also 
```
begin { $everythingToProcess = @() }
process {$everythingToProcess += path} 
end {
    foreach ($item in $everything to process)  {
        # do the real body using item instead of path
    }
}
  
```

Because the need for forms of those is widely, but not universally understood, you're looking to target those people who (a) understand that users of their code might expect it to handle all kinds of things and not just the one they had in mind when they wrote it (b) know that PowerShell doesn't do it for them by default (c) aren't already handling it, and (d) are happy to target only PowerShell after a particular version.  And I think the response will be "It's too small a group"
