### ISSUE TITLE
Change binary assembly info to have a better name than `pwsh`.

### ISSUE THREAD

**Issue by mjr4077au** [PowerShell/PowerShell#21351]
### Summary of the new feature / enhancement

Currently, the binary's AssemblyInfo is giving pwsh.exe and pwsh.dll a title of `pwsh`. For situations where I might be using something like a `[System.Windows.Forms.NotifyIcon]` object, this name will reflect in the resulting BalloonTip:
![image](https://github.com/PowerShell/PowerShell/assets/48643140/22bf30b0-aa55-495e-9d08-b3e1c8adea9b)
For Windows PowerShell, its simply `Windows PowerShell`, which looks a lot more professional on an end user's computer. See the below for a comparison:
| PowerShell 5.x  | PowerShell 7.4.1 |
|------------------|-------------------|
| ![image](https://github.com/PowerShell/PowerShell/assets/48643140/672cc90c-e5f5-4232-99c2-b23a1b6eb63e) | ![image](https://github.com/PowerShell/PowerShell/assets/48643140/81c14bf5-46aa-4726-a0ab-b74426c8a3ec) |

### Proposed technical implementation details (optional)

Change the AssemblyInfo for the project to something "friendlier" like `PowerShell 7`, rather than something like `pwsh`.

**Comment by rhubarb-geek-nz** [comment]
Given the version number is already in the information then the name "PowerShell Core" would also be a good candidate presentation name to compare with the existing "Windows PowerShell".

**Comment by mklement0** [comment]
@rhubarb-geek-nz, while the _Core_ qualifier is still convenient as informal shorthand for distinguishing the two PowerShell editions, note that it was dropped in v7, analogous to how .NET Core became just .NET in v5.

**Comment by rhubarb-geek-nz** [comment]
The MSI subject says "PowerShell package", so no "Core" or version in the name there.

![image](https://github.com/PowerShell/PowerShell/assets/94297700/8785dae7-7df2-430e-915f-82b1e7f67b3e)

**Comment by mklement0** [comment]
Makes sense; that dropping the "Core" part of the name was an explicit decision spelled out in the following, from the [7.0 release announcement](https://devblogs.microsoft.com/powershell/announcing-PowerShell-7-0/) (emphasis added):

"
After three successful releases of PowerShell Core, we couldn’t be more excited about PowerShell 7, the next chapter of PowerShell’s ongoing development.
[...]

**Wait, what happened to PowerShell “Core”?**

Much like [.NET decided to do with .NET 5](https://devblogs.microsoft.com/dotnet/introducing-net-5/), we feel that PowerShell 7 marks the completion of our journey to maximize backwards compatibility with Windows PowerShell. To that end, we consider PowerShell 7 and beyond to be the one, true PowerShell going forward.

**PowerShell 7 will still be noted with the edition “Core” in order to differentiate 6.x/7.x from Windows PowerShell, but in general, you will see it denoted as “PowerShell 7” going forward**.
"

**Comment by SteveL-MSFT** [comment]
It probably makes sense to rename from `pwsh` to `PowerShell 7`

**Comment by mklement0** [comment]
@SteveL-MSFT, given that there also `FileVersion` and `ProductVersion` fields, I suggest keeping the version number out of the description field, not least because having to update the major version number in the latter too is both a maintenance hassle and a potential obstacle to programmatic analysis of the latter.
