### ISSUE TITLE
New-LocalUser should support a -GeneratePassword switch

### ISSUE THREAD

**Issue by CamyDee** [PowerShell/PowerShell#21366]
### Summary of the new feature / enhancement

As an alternative to -NoPassword or -Password, New-Local user should support -GeneratePassword.
This switch cannot be used with the other two parameters.
If Specified, a secure password (conforming to the rules in place) would be generated and returned in the return object as a secure string.

Currently, there is no good way to generate a password securely for use with a newly-created local account, which is a huge stumbling block for automation scenarios. 

### Proposed technical implementation details (optional)

There already exists a password property to the returned user object. This should be populated with the new SecureString value that was generated.

This avoids the often-used approach of generating a password in plain text, then using ConvertTo-SecureString -AsPlainText, which as you know is highly discouraged and insecure. Currently, there is no good alternative.

**Comment by mklement0** [comment]
That sounds like a worthwhile improvement, but please note that `New-LocalUser` is from the `Microsoft.PowerShell.LocalAccounts` module, which isn't being maintained in this repo.

The official advice for reporting issues with / suggesting features for modules that ship with Windows (rather than as part of PowerShell) and aren't open-source is, taken from the now _obsolete_ [PowerShellModuleCoverage](https://github.com/PowerShell/PowerShellModuleCoverage) repo (emphasis added):  

> NOTE To **report problems with _modules that ship in Windows_, use the _Windows Feedback Hub_**. For more information, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).
