### ISSUE TITLE
Unexpected quotes in variable expansion in inline commands

### ISSUE THREAD

**Issue by prayaas-a** [PowerShell/PowerShell#21394]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

An inline command that contains two PowerShell string variables is being expanded in a nonstandard way. Assigning the command as a string to another variable and executing that with `Invoke-Expression` works just fine. To demonstrate this, we can execute a simple `git clone` command.

```pwsh
$repoUrl = "https://example.com"
$branchConfig = "--branch examplebranch --single-branch"

git clone $repoUrl $branchConfig
```

Note that enabling git tracing reveals the source of this problem.
```
13:28:55.146935 git.c:463               trace: built-in: git clone https://example.com '--branch examplebranch --single-branch'
```
Notice the quote marks around the expansion of the `$branchConfig` variable. This does not happen when `Invoke-Expression` is used.
```pwsh
...
$command = "git clone $repoUrl $branchConfig"
Invoke-Expression $command
...
13:22:56.895361 git.c:463               trace: built-in: git clone https://example.com --branch examplebranch --single-branch
...
```
Notice the lack of quotes around the `$branchConfig` expansion.

### Expected behavior

```console
Cloning into ...
```

### Actual behavior

```console
error: unknown option `branch examplebranch --single-branch'
...
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
Using [print_argv_generator.ps1](https://gist.github.com/jborean93/d45fcf5eca04dfe79dadb2e0c8c584c2#file-print_argv_generator-ps1) on Windows PowerShell (5.1) you can generate an exe that helps to explain this behaviour.

In PowerShell when you invoke an external binary it will bind the values you give to it as positional and treat them as their own distinct argument. In Windows this means that the value specified by that argument should be quoted. For example

```powershell
$arg1 = 'foo'
$arg2 = 'hello world'

.\print_argv.exe $arg1 $arg2

"C:\temp\print_argv.exe" foo "hello world"
[0] foo
[1] hello world
```

Notice how `hello world` is quoted in the final command line. This is done because `$arg2` is treated as a single argument in PowerShell so it attempt to do the same in your git example. Using `print_argv.exe` we can see that behaviour

```powershell
$repoUrl = "https://example.com"
$branchConfig = "--branch examplebranch --single-branch"

.\print_argv.exe clone $repoUrl $branchConfig

"C:\temp\print_argv.exe" clone https://example.com "--branch examplebranch --single-branch"
[0] clone
[1] https://example.com
[2] --branch examplebranch --single-branch
```

You can see the whole value of `$branchConfig` is in a quoted argument in the command line string.

When you use `Invoke-Expression` what PowerShell is doing is it is taking the value of that string and treating it as a PowerShell statement to run. So `Invoke-Expression $command` will be like doing `PS C:\> git clone https://example.com --branch examplebranch --single-branch`. There are now no quotes in the example so each argument is provided positionally and will be treated separately.

You don't want to use `Invoke-Expression` here (or really ever for invoking an exe) as it just adds another layer for things to go wrong. What you want to do is to specify your arguments as an array and splat them

```powershell
$repoUrl = "https://example.com"
$branchConfig = @("--branch", "examplebranch", "--single-branch")

.\print_argv.exe clone $repoUrl @branchConfig

"C:\temp\print_argv.exe" clone https://example.com --branch examplebranch --single-branch
[0] clone
[1] https://example.com
[2] --branch
[3] examplebranch
[4] --single-branch
```

When you splat (or even just provide an argument as an array), PowerShell will treat them as separate arguments and thus won't quote the whole array value.

**Comment by mklement0** [comment]
To complement @jborean93's comment:

> `git clone $repoUrl $branchConfig`

In PowerShell - unlike in POSIX-compatible shells such as Bash - you're asking for the values of variables `$repoUrl` and `$branchConfig` to be passed as a _single argument each_ to the target command.  

The advantage of this approach is that you never need to worry about enclosing arguments in `"..."`, depending on their value.

Therefore, **do NOT use a _single string_ to encode _multiple_ arguments - instead, use an _array_,** as shown - _splatting_ isn't even strictly needed when calling _external (native) programs_; e.g., the following examples are effectively the same:

```powershell
cmd /c echo foo 'bar baz' qux

$arr = @('foo', 'bar baz', 'qux')

cmd /c echo $arr
cmd /c echo @arr
```

---

 [`Invoke-Expression` (`iex`) should generally be avoided](https://stackoverflow.com/a/51252636/45375); except in unusual circumstances, [don't use it to invoke an external program or PowerShell script / command](https://stackoverflow.com/a/57966347/45375).

**Comment by prayaas-a** [comment]
Thanks @jborean93 and @mklement0 🙂 Looks like this is by design and while I don't find it super intuitive, I understand the rationale behind it. Please feel free to close this issue appropriately.
