### ISSUE TITLE
Allow parameter `HelpMessage` to be displayed as autocompletion tooltip

### ISSUE THREAD

**Issue by totkeks** [PowerShell/PowerShell#21444]
### Summary of the new feature / enhancement

As a user I want PowerShell to show more information about my script parameters when using autocompletion, so I see at a glance what data I could or should provide, without having to go extraneous steps to call `Get-Help` with `-Detailed` or `-Full` on them.

### Proposed technical implementation details (optional)

When calling a script from the command line and using autocompletion, the suggestions for parameters are only showing the parameter declaration in the tooltip.

E.g. a parameter `MyParameter` declared as below will show up in the autocompletion menu as `MyParameter` with a tooltip of `[string] MyParameter`. The `HelpMessage` is ignored and only shown when using `Get-Help`.
```powershell
param (
	[Parameter(HelpMessage = "More details about my parameter")]
	[string]$MyParameter
)
```

Instead, it should show the help message as well, either replacing the type information or complementing it. So, in this example it would show like this.
```powershell
[string] MyParameter - More details about my parameter
```
Or using two lines for the tooltip, if technically feasible - up for discussion.
```powershell
[string] MyParameter
More details about my parameter
```

Furthermore, it could be considered to use the (first line of the) parameter comment-based help text in `.PARAMETER` or the comment following the parameter declaration `[string]$MyParameter # my help text` to avoid duplication of information, if only the `HelpMessage` is used.

**Comment by MartinGC94** [comment]
It would be very easy to add it based on the HelpMessage property, see this for an example: https://github.com/PowerShell/PowerShell/compare/master...MartinGC94:PowerShell:ParamHelpMessage
![image](https://github.com/PowerShell/PowerShell/assets/42123497/88503e83-3434-4721-8df8-2c065ffd020e)

I'm not really a fan of having to write the parameter text twice as an author though and I doubt most module authors will go back and populate this property after this change. Reading the help would be best but that's more challenging.

**Comment by totkeks** [comment]
Wow that was quick. Thanks for providing a proof of concept.

Would it be possible to access the `HelpSystem` APIs to gather the other sources for the tooltip?

**Comment by MartinGC94** [comment]
I'm not very familiar with the help system but I took a look after I left my comment and it doesn't seem too bad actually. I will (probably) take a deeper look at it tomorrow.

**Comment by MartinGC94** [comment]
Now I've got it working:
![image](https://github.com/PowerShell/PowerShell/assets/42123497/d10c2964-5671-400e-8b0b-97c1f63774c1)
This needs to be a user specified option though because querying the help system noticeably slows down the tab completion. Completing `Set-Disk -<Tab>` went from 1-2 ms to about 300 ms on my system.
The challenge is that it needs to be changeable on the fly so PSReadLine or VS code can be configured to to skip the help for normal tab completion but show it for menu tab completion. But it also needs to be easy to change by the user so users can completely opt out of it if they have a slow computer.  
The Options parameter for TabExpansion2 doesn't seem like a good fit for this because it's hard for users to configure it.

**Comment by totkeks** [comment]
Thanks again for the quick work on the proof of concept!

I also found the keybinds mentioned in your edits after digging a little more. I guess those are fine to get the advanced help text.

With those performance issues of course, it is only reasonable not to invoke the help system and focus on the `HelpMessage` attribute instead.

While this does not help (pun intended 😉) with existing scripts, it could be a good and useful recommendation going forward to put a short, simple, concise message there and full-blown details in the regular comment-based help.

Just looking at the script in front of me, this short message could help clarify what kind of `string` I expect, e.g. an URL or a path, without going a bit overboard with descriptive parameter naming - `Repository` vs `RepositoryUrlOrPath`.

**Comment by daxian-dbw** [comment]
The dynamic help feature in PSReadLine allows you to ["get focused parameter help"](https://learn.microsoft.com/en-us/powershell/scripting/learn/shell/dynamic-help?view=powershell-7.4#getting-focused-parameter-help), which is exactly for this scenario.

With the `Windows` and `Emacs` edit mode, the "parameter help" feature is bound to the <kbd>Alt+h</kbd> key by default. So, after you tab complete on the parameter to get `Get-ChildItem -Depth` for example, just press <kbd>Alt+h</kbd> and you will see the help content for that parameter, assuming you have updated the help content.

Here is an example to show the use of `HelpMessage`:

![image](https://github.com/PowerShell/PowerShell/assets/127450/c10ece9a-d136-4cb6-b2af-f51ad50045b9)

**Comment by totkeks** [comment]
No, unfortunately it is exactly not for this scenario.

Because a) it needs another key press (two actually) and b) provides more information than necessary.

The idea behind my suggestion is, that you do *not* have to press an additional key and only get a small, concise piece of information, not the full `.parameter` block from the comment-based help.

**Comment by theJasonHelmick** [comment]
Thank you @totkeks for the suggestion. The Dynamic Help feature that @daxian-dbw described is the design we support for this scenario.  Remember, from the information here, you could build your own module, even share it on the gallery, if you would like.

**Comment by totkeks** [comment]
Thanks for the reply. Sad to see it rejected though. 

> Remember, from the information here, you could build your own module, even share it on the gallery, if you would like.

I would love to do that, but I don't fully understand how that would be possible, since the changes made by @MartinGC94 are in the Powershell engine `src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs`.

How could/would a module overwrite that behavior and add the tooltip as per his proof of concept?

**Comment by MartinGC94** [comment]
> How could/would a module overwrite that behavior and add the tooltip as per his proof of concept?

While far from ideal, you could create a module that exports a function named "tabexpansion2" to override the default one included with the engine. Inside this function you'd just call the standard completion code and check the results, if the results include a command parameter result you can analyze the Ast to find out which command it provided completions for, run `Get-Command` to get the command data and loop through the parameter attributes and update the tooltip in the completion results as needed.  
This is not ideal for 2 reasons, the first reason being that if you override the tabexpansion2 function then you could potentially be overriding the customization other users have done to that same function. Secondly, you need to perform basically the same work that the existing tab completion code does which takes effort and slows down tab completion (because you are doing unnecessary work).

**Comment by totkeks** [comment]
@theJasonHelmick would it be okay to ask you to reconsider your decision when taking Martin's comment above into consideration?

From my understanding a module based solution for my suggestion doesn't seem feasible.

Looking at the PoC, the changes to add the help message to the tooltip should only have a miniscule performance impact.

And for users that don't use the menu complete, nothing would change.
For the ones that use it, they would get the help message (if available) in addition to the data they are currently getting. Nothing is taken away in that regard.
And the ones that prefer to use alt + h for the additional parameter help, can also still do so.

**Comment by FriedrichWeinmann** [comment]
A module based solution is viable, by overriding the tabexpansion2 function.
Here's an example:
https://github.com/FriedrichWeinmann/LocalizedCompletion/blob/master/LocalizedCompletion/expander/TabExpansion3.ps1
