### ISSUE TITLE
Umlaute brake when using curl.exe

### ISSUE THREAD

**Issue by kort3x** [PowerShell/PowerShell#21456]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I did this
`curl https://slftool.github.io/data.json`

then

`(curl https://slftool.github.io/data.json)`

### Expected behavior

For both commands Umlaute should work like in this line from the output of the first command
`"stadt": ["Zweibrücken (Deutschland)", "Zwiesel (Deutschland)", "Zwickau (Deutschland)", "Zürich (Schweiz)", "Zabol (Iran)", "Zagreb (Kroatien)"]`

### Actual behavior

Umlaute are broken in the output of the second command, the one with parentheses
`"stadt": ["Zweibr├╝cken (Deutschland)", "Zwiesel (Deutschland)", "Zwickau (Deutschland)", "Z├╝rich (Schweiz)", "Zabol (Iran)", "Zagreb (Kroatien)"],`

As soon as you touch the output of curl they brake.

### Environment data

```powershell
curl -V
curl 8.7.1 (x86_64-w64-mingw32) libcurl/8.7.1


$PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
When you run an executable in PowerShell there are two ways the executable can output text

+ To the console directly
+ To the process' stdout pipe

The first example is what happens when you execute something in PowerShell without capturing or redirecting the output in any way, for example

```powershell
PS C:\> curl.exe https://slftool.github.io/data.json
````

The second example is what happens when the process' output is redirect by PowerShell as the data is going to be captured by PowerShell. This can occur in any of the cases like setting it to a var, pipelining data, redirection, or in your case grouping, for example

```powershell
PS C:\> $out = curl.exe https://slftool.github.io/data.json
PS C:\> curl.exe https://slftool.github.io/data.json | Out-String
PS C:\> (curl.exe https://slftool.github.io/data.json)

# This example no longer applies in pwsh 7.4+ but older ones do
PS C:\> curl.exe https://slftool.github.io/data.json > C:\test.txt
```

This is important because the second scenario will have PowerShell convert the raw bytes of the process' stdout pipe using the encoding of `[Console]::OutputEncoding` which on Windows will not default to UTF-8. This explains why running curl just by itself works just fine because curl is writing to the console directly but `(curl.exe ..)` does not.

What you need to do is ensure that `[Console]::OutputEncoding` is set to the correct encoding that curl will use to output it's data, most likely you'll need to set it to UTF-8 as most modern applications will default to that to support unicode characters

```powershell
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
curl.exe ... | Out-String
```

It's also goo practice you set the `[Console]::InputEncoding` and `$OutputEncoding` to the same value, e.g.

```powershell
$OutputEncoding = [Console]::OutputEncoding = [Console]::InputEncoding = [System.Text.UTF8Encoding]::new()
```

**Comment by mklement0** [comment]
@jborean93's helpful comment was posted while I was in the middle of composing mine, but perhaps the following provides a slightly different angle / supplemental information that may be helpful:

In short:

* `[Console]::OutputEncoding` must match the actual character encoding emitted by an external (native) program in order for PowerShell to decode it correctly.

  * Without PowerShell involvement, namely when directly printing to the console (terminal), this aspect doesn't come into play, so in that things _print_ correctly on Windows.

* Unfortunately, on Windows `[Console]::OutputEncoding` still defaults to the legacy OEM code page associated with the legacy system locale, such as CP437 on US-English systems - see #7233

* _`(...)` use_ necessitates decoding by PowerShell, as does _assignment to a variable_, and _sending output to another command through the pipeline_ (`|`), and - in v7.3- only - using `>` / `>>` to redirect to a file (in v7.4+, direct use of `>` / `>>` relays an external program's _raw byte output_ to the target file).

* Thus, to capture an external program's UTF-8 output _for programmatic processing_, you must (temporarily) set `[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()`

---

Note that there is a way to _avoid_ the need for the above:
  * Assuming you're an administrator, you can configure your system to use UTF-8 _system-wide_ (run `intl.cpl`, activate tab `Administrative`, press button `Change system locale...` and activate checkbox `Beta: Use Unicode UTF-8 for worldwide language support`, then reboot).
  * This sets both the OEM and the ANSI code pages to `65001` (BOM-less UTF-8),  but note that doing so has _far-reaching consequences that must be carefully considered_:  see https://github.com/PowerShell/PowerShell/issues/21437#issuecomment-2040704408

**Comment by rhubarb-geek-nz** [comment]
The standard encoding for JSON files is Unicode, typically UTF8. 

https://www.json.org/json-en.html

> A string is a sequence of zero or more Unicode characters, wrapped in double quotes, using backslash escapes. A character is represented as a single character string. A string is very much like a C or Java string.

When curl is writing data to stdout it should be writing verbatim binary content and not doing any character translation.

**Comment by kort3x** [comment]
Thank you all.

**Comment by kort3x** [comment]
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
helps with utf8 and external binaries
