### ISSUE TITLE
Keep Same Folder When Splitting Terminal

### ISSUE THREAD

**Issue by VikramNaik26** [PowerShell/PowerShell#21455]
### Summary of the new feature / enhancement

![image](https://github.com/PowerShell/PowerShell/assets/142835605/956b9196-617f-4208-883e-2f1d490b0a5b)
What It Does:
When you split your terminal window, the new split will open in the same folder as the original one. So if you're comparing stuff or running commands in one folder, the split will stay in sync without you having to navigate again.

Why It Matters:
It saves time and hassle. You can focus on what you're doing without worrying about keeping track of folders in multiple windows.

Who Benefits:
Anyone who uses terminal splits, especially in Windows PowerShell. It makes things smoother and more convenient for everyone.

For example, imagine you're working on a web development project. You've got your terminal open in the main folder of your project where all your code lives. Now, you need to make some changes to a specific section of your website, so you want to open another terminal window to run some commands or check some files.

With the new feature, when you split your terminal, the new split will automatically stay in the same project folder. So if you're comparing files or running commands in one split, the other split will be right there in the project folder too. You don't have to navigate back to the project folder again in the new split. It keeps everything tidy and saves you time flipping between folders.

### Proposed technical implementation details (optional)

Identify Current Working Directory: When the user initiates a split, the application needs to identify the current working directory (the folder the user is currently in) of the active terminal window.

Create New Split: Upon splitting the terminal window, the application should create a new split window and ensure that it opens in the same current working directory as the original window.

Replicate Path: The new split window should replicate the path of the original window, essentially staying in sync with it. This can be achieved by setting the path of the new split window to match that of the original window.

User Interaction: Ensure that users have the option to toggle this feature on or off according to their preference. Some users may prefer the traditional behavior of splits opening in the default directory, so providing an option to enable or disable this feature would be beneficial.

Testing and Refinement: Thoroughly test the implementation across different scenarios and platforms to ensure compatibility and reliability. Gather feedback from users to refine the feature and address any potential issues or improvements.

**Comment by kilasuit** [comment]
Hi, I am going to mark this as resolution external as this is an issue that should be raised in the [Terminal Repo](https://github.com/microsoft/terminal/) for consideration

**Comment by rhubarb-geek-nz** [comment]
If you want exactly that behaviour right now, then use Visual Code. 

Within Visual Code use "Terminal" -> "New Terminal" and once that is opened select "Terminal" -> "Split Terminal",

**Comment by rhubarb-geek-nz** [comment]
I had made a post that said to use Visual Code because Split Terminal would use the directory from the terminal session, not the profile. However your request wants to track directory changes between split panes, so some agent is monitoring the "current directory" within PowerShell and updating it in each other pane that was split from it.  So some component needs to track what panes are related and updating the current locations.

PowerShell ( or any console shell or application) should not care about what terminal is hosting it, and likewise, a terminal should not be responsible for knowing details about whatever program is running within it. There are some existing communications between applications and their terminal host, for example window size, title and certain terminal properties, but that is about it.

**Comment by MartinGC94** [comment]
I think you can implement this yourself as a PSReadLine custom action: `Set-PSReadLineKeyHandler -Chord ctrl+i -ScriptBlock {wt.exe --window 0 split-pane "pwsh.exe -WorkingDirectory $PWD"}` this doesn't work because I don't know how to specify which shell to launch and the parameters to use but I hope you get the idea and can look into that yourself.

**Comment by mklement0** [comment]
Good point, @MartinGC94; both 
`wt.exe --window 0 split-pane -d $PWD pwsh.exe`
and 
`wt.exe --window 0 split-pane pwsh.exe -WorkingDirectory $PWD`
would work.
In the former case, with `-d` use, you needn't specify a shell executable, in which case the default profile's shell is used (use `--profile`, `-p` to select a _profile_ explicitly, which then implies the associated shell, unless overridden by specifying a shell executable explicitly)

More fundamentally, building on @rhubarb-geek-nz's comments:

* Making split panes _inherit_ the current shell's working directory relies on _shell integrations_ supported by the hosting terminal application, which are unrelated to PowerShell per se.

   * As noted, _Visual Studio Code_ provides fairly comprehensive _automatic_ shell integrations, including for PowerShell; see https://code.visualstudio.com/docs/terminal/shell-integration

   * _Windows Terminal_'s support for shell integrations appears to be in its infancy, judging by https://learn.microsoft.com/en-us/windows/terminal/tutorials/shell-integration

   * On macOS, _automatic_ shell integrations are only provided for a _subset of POSIX-compatible shells_; supporting PowerShell requires adding something like the following to the [`prompt`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Prompts) function to at least notify the terminal application of the _working directory_, which _may_ also work on Linux distros:

			[Console]::Write(
			  "`e]7;{0}`a" -f 
			  (([uri] ('file://dummy' + (Get-Location -PSProvider FileSystem).ProviderPath)).AbsoluteUri -replace '(?<=^.+?)dummy', [Net.Dns]::GetHostName())
			)


* The desire to _keep split panes in sync_ with respect to their working directories exceeds not only PowerShell's mandate, but also that of terminal applications' shell integrations.

**Comment by VikramNaik26** [comment]
> wt.exe --window 0 split-pane -d $PWD pwsh.exe

Is there any way to explicitly split pane horizontal or vertical according to my need using this command

**Comment by 237dmitry** [comment]
Add to prompt function `OSC 9;9`:

```powershell
function prompt {

    $prompt = "`e[38;5;29m $"
    $prompt += "`e]9;9;${PWD}`e\`e[0m "
    return $prompt
}
```

**Comment by mklement0** [comment]
@VikramNaik26, the WT CLI documentation is [here](https://learn.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows).

You can follow `split-pane` with `-H` (`--horizontal`) or `-V` (`--vertical`)

@237dmitry, it typically won't matter, but it's more robust to explicitly refer to the current _file-system_ location, so that duplicating a tab, for instance, doesn't break while you're in, say, the `HKLM:` drive:

```powershell
"`e]9;9;$((Get-Location -PSProvider FileSystem).ProviderPath)`a"
```

The previously linked https://learn.microsoft.com/en-us/windows/terminal/tutorials/shell-integration has PowerShell code that includes an OSC 9 command as well as additional ones for more shell integrations, which are seemingly still classified as experimental, however, and require manual opt-in via the JSON configuration file.

The OSC 9 is seemingly only honored when you right-click a tab and select either `Duplicate Tab` or `Split Tab`, but now with the `Split pane *` commands from the command palette.

**Comment by 237dmitry** [comment]
> when you right-click a tab and select either Duplicate Tab or Split Tab

I think `OSC 9` has to work in Windows Terminal properly. On Linux it works.

**Comment by kilasuit** [comment]
This as shown above is easily done in via cli (thanks all for your samples) but I felt that the ask was more for achieving via Terminal UI & I think this is a worthwhile ask if so which is why their repo is the right one for raising this in.

**Comment by kilasuit** [comment]
FYI this ask is already in https://github.com/microsoft/terminal/issues/3158

**Comment by rhubarb-geek-nz** [comment]
> On Linux it works.

IFF your terminal emulator supports the OSC 9 codes, so I expect that would not include [xterm](https://www.x.org/archive/X11R6.8.1/doc/xterm.1.html) or [dtterm](https://man.freebsd.org/cgi/man.cgi?query=dtterm&sektion=5&manpath=FreeBSD+12.1-RELEASE+and+Ports).

It would also be suspect if you had remoted using ssh from one shell to another system, then the prompt would be from the remote system, not the shell immediately within the terminal emulator.

> This as shown above is easily done in via cli (thanks all for your samples) 

None of the solutions meet the goal of automatically updating related panes with the new directory. The OSC escape codes go from the hosted shell (or other process) to the Terminal emulator. There is nothing changing an existing shells directory as far as I can see.

**Comment by 237dmitry** [comment]
> IFF your terminal emulator supports the OSC 9 codes

Well, that goes without saying.

> f you had remoted using ssh from one shell to another system, then the prompt would be from the remote system, not the shell immediately within the terminal emulator.

I do not know. Between two laptops on the desk I use only `scp` and `mc` to exchange files.

**Comment by rhubarb-geek-nz** [comment]
> I do not know. Between two laptops on the desk I use only `scp` and `mc` to exchange files.

Yes, it is common practice when doing remote administration to ssh from one machine to another where the machine you are typing on is the one generating the prompt.

**Comment by mklement0** [comment]
I don't know how it behaves in practice, but the `[Console]::Write()` command above at least _potentially_ works also for remote `ssh` sessions, as it includes the hostname in the `file://` URI it constructs and communicates via OSC 7.

As noted, this works on macOS (at least locally)  - and possibly also on Linux for terminal apps that understand OSC 7 - but I'm unclear on even what the expected behavior would be if you, say, open a new split from one running a remote `ssh` session.
