### ISSUE TITLE
Get-AzureRmStorageAccountKey missing online help URI

### ISSUE THREAD

**Issue by v2kiran** [PowerShell/PowerShell#2146]
Steps to reproduce
------------------
help Get-AzureRmStorageAccountKey -Online

Expected behavior
-----------------
open default browser and display online help.

Actual behavior
---------------
Get-Help : The online version of this Help topic cannot be displayed because the Internet address (URI) of the Help topic is not specified in the command code or in the help file for the command.
At line:55 char:5

Environment data
----------------

Name                           Value
----                           -----
PSVersion                      5.1.14393.82
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.82
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by vors** [comment]
Based on PSVersion 5.1.14393.82 it looks like you are running **Windows Powershell**. Refer to Terminology section in this blog post announcement for the differences https://blogs.msdn.microsoft.com/powershell/2016/08/18/powershell-on-linux-and-open-source-2/

The problem is in the azure module. It misses HelpUri in the corresponding psd1 file. Please, report the issue in https://github.com/Azure/azure-powershell

**Comment by v2kiran** [comment]
thanks you. i will reopen this on the azure-powershell page.
