### ISSUE TITLE
Autocompletion does not happen for GetTypeCode() on an Array

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#2178]
Autocompletion does not appear to work for GetTypeCode on a char array.
Typing only "$d.GetTy<tab>" will autocomplete with GetType( successfully.

However, typing "$d.GetTypeC<tab>" will not autocomplete.

Steps to reproduce
------------------

```
PS C:\src\powershell> $e = "now"
PS C:\src\powershell> $d = $e.ToCharArray()
PS C:\src\powershell> $d
n
o
w
PS C:\src\powershell> $d.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Char[]                                   System.Array


PS C:\src\powershell> $d.GetTypeCode()
Char
Char
Char
PS C:\src\powershell> $d | Get-Member

```Expected behavior
-----------------

The method name GetTypeCode would be autocompleted after pressing TAB.

Actual behavior
---------------

Autocompletion does not appear to do anything.

Environment data
----------------

PS C:\src\powershell> $PSVersionTable.PSVersion

Major Minor Patch Label
----- ----- ----- -----
    6     0     0 alpha

**Comment by vors** [comment]
Thank you for reporting the issue!

Let's take a look.

`GetTypeCode()` that is called above is [`IConvertible.GetTypeCode()`](https://msdn.microsoft.com/en-us/library/system.iconvertible.gettypecode(v=vs.110).aspx)
It comes from `IConvertible` interface that `Char` implements and `Char[]` doesn't.

```
PS /Users/vors> $d.GetType().ImplementedInterfaces                                                                                           

IsPublic IsSerial Name                                     BaseType                                                                         
-------- -------- ----                                     --------                                                                         
True     False    IList                                                                                                                     
True     False    ICollection                                                                                                               
True     False    IEnumerable                                                                                                               
True     False    IStructuralComparable                                                                                                     
True     False    IStructuralEquatable                                                                                                      
True     False    IList`1                                                                                                                   
True     False    ICollection`1                                                                                                             
True     False    IEnumerable`1                                                                                                             
True     False    IReadOnlyList`1                                                                                                           
True     False    IReadOnlyCollection`1                                                                                                     


PS /Users/vors> $d[0].GetType().ImplementedInterfaces                                                                                        

IsPublic IsSerial Name                                     BaseType                                                                         
-------- -------- ----                                     --------                                                                         
True     False    IComparable                                                                                                               
True     False    IConvertible                                                                                                              
True     False    IComparable`1                                                                                                             
True     False    IEquatable`1       
```

PowerShell has a **fall-back method call** logic for collections. If `$foo.bar()` was invoked and `$foo` is a collection (implements `ICollection`) and doesn't have a method `bar()` then powershell tries to execute equivalent of `$foo | Foreach-Object {$_.bar()}`.

Now the question is "should PowerShell try to offer IntelliSense for collection elements as well a collection itself since it has this fall-back logic"? I think it should not:

* It would be confusing because there would be no way to distinguish collection methods and elements methods.
* If elements have different types, then it became even messier: should ps offer the union of all methods from all elements? It could be huge.
* If a collection is big it could be a perf problem too: engine would need to enumerate all elements, do an expansive reflection call on all of them and then merge results. 

IntelliSense is very convenient. It allows to type less, make fewer mistakes and explore the objects structure. So I'd like to share a way that I use when dealing with collections.

If I know that `$d` is a collection and all elements have the same type and I want to call a method on all of them, I usually start with finding it **on the first element**:

```
> $d[0].GetTy<press Tab few times>
> $d[0]. GetTypeCode()
```

Then I can just remove `[0]` part and call it on all elements.

**Comment by Liturgist** [comment]
Ok, @vors. You have explained it clearly and well. I appreciate that.

I am not sure that I am plussed by the "fallback" method approach. If a collection $foo does not have a bar() method, then using $foo.bar() would not seem to be valid. Automagically turning this into a foreach seems like creeping elegance. Perhaps I can find out on my own what happens if one of the elements of a collection does not have a bar() method.

**Comment by vors** [comment]
That's how PowerShell works.
I understand your concerns. Personally, I find this very useful. It greatly simplifies ad-hock scripting. This is one of the aspects where PS is more IT-Pros oriented then developer oriented.

**Comment by vors** [comment]
Going  to close it, please re-open if you want to continue the discussion.
