### ISSUE TITLE
the default typing color for text is yellow in centos, barely visible

### ISSUE THREAD

**Issue by garegin16** [PowerShell/PowerShell#2183]
I didn't try other linuxes, but the default typing color for centos 7 in gnome terminal is yellow.

**Comment by vors** [comment]
Does it look like these screenshots #1036 ?

**Comment by garegin16** [comment]
Yes. It's even worse on my screen. It looks bright yellow. I can't see anything

**Comment by vors** [comment]
Can you post a screenshot? 

As a workaround, you can set background color to black or anything dark.

**Comment by Jaykul** [comment]
Can we turn this into a request for PSReadline to detect the background and choose an appropriate default set of colors -- unless they have been set by the user?  

For that matter, is there any chance that we could get PSReadline to use some sort of configuration file rather than needing a long profile script to set all the colors?  Especially now that we have (potentially) access to 256 xterm colors or even 16bit full color, and/or support for bold, etc...

Yellow on white is not right,
Nor is blue on black.
Wise color choices are great.
-- The PSReadLine limerick.

**Comment by drwill-ms** [comment]
Same for me on OSX. Very bright yellow text on a white background. Only text I type.

**Comment by garegin16** [comment]
Huh. It didn't do that on my os x install. The text is black by default.

**Comment by SteveL-MSFT** [comment]
@Jaykul I like your suggestion, can you open an issue in http://github.com/lzybkr/psreadline

**Comment by fnvogt1954** [comment]
Power Shell command background seems to take on the value of the most recently used color of the screen background.
Discovered this by accident. 
I can see my yellow commands against a darker background. I was using white as my background, then I changed it to a darker green, too dark, so I lightened it up to a nice shade of blue. Screen Snippet attached , 
![ps_yellow_command_letters_on_dark_background](https://cloud.githubusercontent.com/assets/20746666/20031410/5c9eea64-a34d-11e6-991b-d4baa0595ebe.PNG)
PS_Yellow_command_letters_on_dark_background.png.
Now that I have something that is workable, but not great, I am afraid to tweak it more, have to move on to more urgent work.
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  206

**Comment by lzybkr** [comment]
This issue was moved to lzybkr/PSReadLine#464

**Comment by milindsaraswala** [comment]
I am late to the party but I found the article which make your mac terminal window same like windows PowerShell. By Setting Profile. Please follow this below article
https://info.sapien.com/index.php/quickguides/setting-up-powershell-on-your-mac
