### ISSUE TITLE
Non admins (e.g.students) should be able to download/use the latest help files

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#2190]
Currently HELP files are a system-wide resource which requires ADMIN privs to update.

Student laptops are not allowed admin access so they are unable to download & use the latest help files.

We should fix that.

One mechanism would be to support -SCOPE CurrentUser for the help cmdlets.

**Comment by Jaykul** [comment]
Seems like you should just put the help in C:/ProgramData (that is to say, in an "all users" writable location), because the idea of having lots of copies of the help is annoying, and frankly, the idea of the help cmdlets having to search in an _additional_ location, and pick the _most up to date_ help just reminded me of how slow help search is already...

**Comment by rkeithhill** [comment]
You need reminding?  ;-)

**Comment by joeyaiello** [comment]
I'd say this is important no matter what, but it's *especially* important as long as `sudo Update-Help` doesn't work.

**Comment by SteveL-MSFT** [comment]
We need to relnote that on Unix systems, you have to `sudo powershell` to run `Update-Help`
