### ISSUE TITLE
-f different between windows and linux

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#2194]
## Steps to reproduce

"{0:p}" -f 0.95

powershell on windows return(i think return is right):
95.00%

powershell on centos 7.2 return:
95.000%
## Environment data

win:

Name                           Value
---

PSVersion                      5.1.14393.103
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.103
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

centos 7.2:

Name                           Value                                                                                                             
---

PSVersion                      6.0.0-alpha  
PSEdition                      Core  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}  
BuildVersion                   3.0.0.0  
GitCommitId                    v6.0.0-alpha.9  
CLRVersion  
WSManStackVersion              3.0  
PSRemotingProtocolVersion      2.3  
SerializationVersion           1.1.0.1 

LANG=zh_CN.UTF-8

**Comment by GeeLaw** [comment]
Hi chuanjiao10,

Could you please report a bug with the template, including necessary environment parameters?

I have to first point out that, on Windows PowerShell 5.1.14393.103, default in locale en-US, region en-US, the result of `'{0:p}' -f 0.95` gives `95.00 %` instead of `95.00%`. You missed a space character here. As **on Windows, it is up to you how the number is formatted by default.** To edit your settings, go to `Control Panel > Clock, Language, and Region > Region > Additional Settings...`, and you can edit `No. of digits after decimal`. If you change the number to three (3), restart PowerShell, you should see `95.000 %` for `'{0:p}' -f 0.95`.

I wonder if you can include your regional preferences on CentOS 7.2? (Or perhaps PowerShell has to fallback to a default set of settings due to unavailability of such APIs cross *nix platform?)

The following content is in Chinese as the issue reporter speaks Chinese.

---

Hi，请 **按照模板** 提交 bug report，并且附上`$PSVersionTable`等必要的环境参数。

我必须首先指出，在 Windows PowerShell 5.1.14393.103 上，如果 locale 是美国，地区格式是英语（美国），在默认情况下，`'{0:p}' -f 0.95` 给出的结果应该是`95.00 %`，你丢了一个空格。以及，**在 Windows 上，你可以决定数字在默认情况下如何格式化。**要更改这个设置，进入“控制面板 - 时钟、语言和地区 - 地区 - 更多设置…”，然后更改小数点后的位数。如果你把这个数改成 3，并重启 PowerShell，`'{0:p}' -f 0.95`将会给出`95.000 %`。

请一并提供你的 CentOS 7.2 上的区域偏好设置。（或许，PowerShell 会回退到一个默认参数，因为没有在 *nix 上统一获取用户区域偏好的 API，或者没有实现？）

**另外，请从 issue 中删除 QQ 群广告，谢谢。**

**Comment by chuanjiao10** [comment]
as your wish. i redo it.

**Comment by GeeLaw** [comment]
In reply to @chuanjiao10 : Have you checked regional format settings?

![Regional Format Settings available on Windows](https://cloud.githubusercontent.com/assets/4462444/18301519/af38fffc-7504-11e6-9922-40b9d1e2d46e.png)

**Comment by chuanjiao10** [comment]
The value is 2 on Windows,Default value.
How to find the settings for CentOS?

**Comment by GeeLaw** [comment]
In reply to @chuanjiao10 

You can see the number of digits output by CLR with `[System.Globalization.NumberFormatInfo]::CurrentInfo.PercentDecimalDigits`. If this value matches **your settings**, then the behavior is expected.

Another possibility is that CLR doesn't know your culture, therefore populating the default values. However, this seems not to be the case since digging into the code, we find that the default percent decimal digits comes from the default number digits, which is `_iDigits` field and has value `2` for invariant culture. See [here](https://github.com/dotnet/coreclr/blob/dff1a185802abd109371f0317ce84d290c6675f6/src/mscorlib/corefx/System/Globalization/CultureData.cs#L439). I went to `Double.ToString`, which gives hint on `NumberFormatInfo.CurrentInfo`, then I'm guided to `CultureInfo`, then I reached `_iDigits`.

Since CLR isn't using `2` on CentOS, it must have retrieved the value from your regional settings.

I'm not a CentOS user, therefore cannot give help on how to find the settings. Perhaps you need to refer to CentOS documentation.

Steps you might want to check:

```PowerShell
[CultureInfo]::CurrentCulture
[System.Globalization.NumberFormatInfo]::CurrentInfo.PercentDecimalDigits
```

Does the first line give `en-US` culture, or `zh-CN`/`zh-Hans` culture? Does the second line give value `3` on CentOS, and `2` on Windows?

**Comment by chuanjiao10** [comment]
yes!
It looks like you found the root cause.

PS /root> [System.Globalization.NumberFormatInfo]::CurrentInfo.PercentDecimalDigits                                                               
3
PS /root> [CultureInfo]::CurrentCulture                                                                                                           

LCID             Name             DisplayName                                                                                                    
----             ----             -----------                                                                                                    
                 zh-CN            中文（中国）    
------------------------------------
PS C:\Windows\system32\WindowsPowerShell\v1.0> [CultureInfo]::CurrentCulture

LCID             Name             DisplayName
----             ----             -----------
2052             zh-CN            中文(简体，中国)


PS C:\Windows\system32\WindowsPowerShell\v1.0> [System.Globalization.NumberFormatInfo]::CurrentInfo.PercentDecimalDigits
2

**Comment by GeeLaw** [comment]
Well. The only question is now whether you can set this value in CentOS (user level, not process level), and whether PowerShell respects this value. I suggest you look for CentOS documentation on customizing locale/regional settings.

**Comment by iSazonov** [comment]
Why this issue doesn't close?

**Comment by chuanjiao10** [comment]
Version v6.0.0-alpha.14 based on .Net core 1.1 , i retested this issue,problem is still.

**Comment by iSazonov** [comment]
May be better open issue in CoreFX?

**Comment by chuanjiao10** [comment]
report: The problem is still in powershell beta1(.net core 2.0)

**Comment by SteveL-MSFT** [comment]
@chuanjiao10 if you want this addressed, you need to open an issue in the [corefx repo](https://github.com/dotnet/corefx)

**Comment by chuanjiao10** [comment]
3q
