### ISSUE TITLE
Support user defined parameter aliases, e.g. -F to -Force for Remove-Item

### ISSUE THREAD

**Issue by be5invis** [PowerShell/PowerShell#2199]

**Comment by lzybkr** [comment]
Having `Remove-Item -F` work just like `Remove-Item -Force` seems like a good idea.

There is a small concern - `Remove-Item` is a cmdlet that is implemented by providers (like the file system, registery, environment, etc) and providers can add dynamic parameters.  Providers that add dynamic parameters aren't all that common, but there is a risk that a provider adds a dynamic provider with an identical alias `-F` which would be masked by this change.

In an ideal world, this wouldn't break scripts because they should be using full parameter names, but we don't live in that ideal world.

It feels like an unlikely breaking change, but we should have data to confirm that assumption before considering this enhancement.

**Comment by be5invis** [comment]
@lzybkr The current Remove-Item’s -f is... ambiguous (-Force and -Filter), so scripts cannot use it directly.

**Comment by lzybkr** [comment]
That's not necessarily true if, as I previously stated, a provider adds a dynamic provider with an alias.

**Comment by be5invis** [comment]
@lzybkr At least can alias `-f` for file provider, or other existing providers with only `-Force`.

**Comment by lzybkr** [comment]
@be5invis - in theory, sure, but I think that would be difficult to implement correctly.

Dynamic parameters don't support adding an alias to an existing parameter and we couldn't move `-Force` to be dynamic for a specific set of providers because the parameter must exist for all providers.

**Comment by GeeLaw** [comment]
I'm proposing a way to implement this... Allow specifying the precedence of a parameter when ambiguity happens. E.g. `[Parameter(Precedence = 1)][switch]$Force, [Parameter(Precedence = 0)][string]$Filter`, then `-F`, if not otherwise resolved, would be `-Force`.

For backward compatibility, `Precedence` should be `System.Nullable<System.Int32>` or `System.Nullable<System.UInt32>`. Resolution step **regarding precedence** (of course full name and aliases should be used to resolve parameters before we come to this step) should be:

1. If no parameter candidate has `Precedence.HasValue`, the resolution fails;
2. Collect all parameter candidates with `Precedence.HasValue` that has the largest `Precedence.Value`, say this is collection `A`;
3. If the size of `A` is 1, the parameter resolves to the only element in `A`;
4. Otherwise, the resolution fails.

This won't break current providers that adds a dynamic parameter / an alias of a dynamic parameter `-F`, and is consistent in all providers -- You don't lose `-F` as an alias for `-Force` magically because you are not using built-in providers, you lose it because `-F` resolves before it reaches `-Force` and `-Filter`.

**Comment by lzybkr** [comment]
@GeeLaw - that might work, but the parameter binder is already too complicated, so it's hard to say if it'd be worth adding this complexity.

**Comment by iSazonov** [comment]
Using aliases degrades readability of scripts.
Using Foreach-Object better using foreach. 
Using Where-Object better using where. 
Using -Force better using -F.

**Comment by GeeLaw** [comment]
In reply to @iSazonov : If you read carefully enough, you would find that the proposed alias `-F` for `-Force` is intended to be used interactively, shortening the type for a often-used switch.

**Comment by KirkMunro** [comment]
I'd vote against building in a shorthand aliases for parameters (such as -F for -Force) because it could lead to accidents.. It's pretty well known that you can abbreviate any parameter using the minimum number of characters required to unambiguously identify that parameter.  If -F is explicitly aliased to -Force, and someone forgets about the conflict between -Force and -Filter because there aren't multiple parameters that start with -F on every command that has a -Force parameter, suddenly they may invoke a command with -Force when they really meant to invoke it with -Filter.

A better solution for this problem would be to unlock parameter aliases in PowerShell (they currently cannot be modified by end users), allowing PowerShell users to add parameter aliases that they want to use in their interactive work to their profile,  much like they can add command aliases today.  Then if someone specifically wants -F to be an alias for -Force in Remove-Item for ad-hoc work, they can make that decision and change it for themselves without forcing a potentially unwanted change on the rest of the community.

In this particular scenario, having to type ri -fo vs just ri -f isn't really that bad IMHO.

**Comment by RichardSiddaway** [comment]
I agree with Kirk that the present capabilities of abbreviating parameters to the minimum that is unambiguous is sufficient. Add aliases to parameters is an unnecessary complication

**Comment by iSazonov** [comment]
An user can add parameter alias by means of proxy function.

**Comment by KirkMunro** [comment]
@RichardSiddaway: Being able to add aliases to parameters is not unnecessary. I've run into multiple scenarios where I would gladly have added an alias to a parameter if I could; however, adding shorthand aliases seems like the wrong thing to do.

@iSazonov: Creating a proxy function (that must be then kept up to date over time as commands evolve) is a lot of work just to add a parameter alias. I would greatly prefer being able to simply add an alias to a command via .NET or via a PowerShell command. For example:
```
$cmd = Get-Command -Name Select-Object
if ($cmd.Parameters['First'].Aliases -notcontains 'Top') {
    $cmd.Parameters['First'].Aliases.Add('Top')
    if (-not ($cmd.Parameters['First'].Attributes | Where-Object {($aliasAttribute = $_ -as [System.Management.Automation.AliasAttribute]) -and ($aliasAttribute.AliasNames -contains 'Top')})) {
        $aliasAttribute = New-Object -TypeName System.Management.Automation.AliasAttribute -ArgumentList Top
        $cmd.Parameters['First'].Attributes.Add($aliasAttribute)
    }
}
gps | sort WorkingSet64 -desc | select -top 10 # This fails, so the added alias isn't being recognized
```
I'd like to see that actually work since the collections can be updated, but PowerShell must be using cached metadata for the command when the parser resolves the parameters, so maybe all that's missing is an additional call that would update that command in the command cache.

**Comment by HemantMahawar** [comment]
@PowerShell/powershell-committee agree that it is useful and should be done generically (enable things like ls -al, rm -rf etc.).

**Comment by rkeithhill** [comment]
But didn't this sort of thing get us into trouble with curl/wget?  Wouldn't this further trick folks into thinking that by executing `rm -rf` they're using a *nix utility instead of PowerShell's `Remove-Item`?  And when I'm on Linux, `ls` and `rm` better be invoking the native Linux utilities.  

So this seems to apply only to Linux folks moving over to Windows.  For that scenario, it seems better to supply a module that provides better emulation of the Linux utilities they are used to.  Perhaps using @KirkMunro suggestion of parameter alias modification.  Then if they wind up writing scripts that rely on these *nixy parameter aliases, they can require that module for portability.

**Comment by be5invis** [comment]
@rkeithhill We can write a different `rm`, a different function that is parameter-compatible WITH Linux `rm`.

**Comment by rkeithhill** [comment]
I'm fine with that as long as it's in an optional module.  As a 11+ year user of PowerShell, my muscle memory doesn't include `rm -f`, `rm -rf` or `ls -al`, etc.  :-)

**Comment by iSazonov** [comment]
Up to now I see beginners in Powershell and never heard from them that they find it difficult to understand Powershell. Powershell is great because it has clear idea and it's strange to refuse this and turn it into a half-baked bash. We all once migrated from VBS and no one simulates the VBS in Powershell.

**Comment by KirkMunro** [comment]
@HemantMahawar To be clear, which part of this did the @PowerShell/powershell-committee agree is useful?

**Comment by SteveL-MSFT** [comment]
@KirkMunro the committee agreed that user defined parameter aliases would be useful for interactive use (aliases should never be used in scripts and we should have a corresponding rule for this) where `rm` is aliased to `remote-item` and `-rf` is aliased to `-recurse -force`.  seemsl like this should be a RFC to get more feedback.

**Comment by dragonwolf83** [comment]
Limiting to interactive scenarios would be most important for this to work. I'm not a Bash user. If I inherit a script that someone wrote with Linux aliases, it would make it much harder to understand the script. 

PowerShell needs to maintain consistency with scripts across platforms in order to make it easier for scripters to maintain in the long-term.

**Comment by jdhitsolutions** [comment]
I don't see any reason to invest resources into providing this feature. Parameter aliases add an unnecessary layer of complexity. Going back to the original post, there's no reason to run a command like 'rm -f', when you can just as easily type `rm -f<tab>` and autocomplete the parameter. I'd make a case for tab-completing the cmdlet name as well. If there are parameter aliases that a user might be expecting to use, that should be well documented.

**Comment by SteveL-MSFT** [comment]
Upon further thinking on this, I don't know if this is worth a feature to enable custom parameter aliases if the primary (only?) use case is `rm -rf`.  So a feature would not be trivial and currently without other real world scenarios, seems potentially little benefit vs the cost.  For `Remove-Item` specifically, I have personally encountered the displeasure of having to use `rm -r -fo` (since `-filter` conflicts) and prefer `rm -rf` for expedient typing when used interactively. 

So one possible alternate solution is to add a new `-RecurseForce` switch in a new parameterset which has the `-rf` alias.  This should be a pretty small change.  I think there is a question whether this sets a bad precedent.

**Comment by iSazonov** [comment]
> I think there is a question whether this sets a bad precedent.

Yes. Users can create any wrappers based on functions in their profiles.

**Comment by SeeminglyScience** [comment]
> So one possible alternate solution is to add a new `-RecurseForce` switch in a new parameterset which has the `-rf` alias. This should be a pretty small change. I think there is a question whether this sets a bad precedent.

It does, but I think if it solved the problem it would be worth it. I would bet that just about every single person who used PowerShell extensively has been annoyed by this at some point.

That said, I think the main frustration is "I feel like should be able to do *this* but that throws, now I gotta do *that*".  I don't think the pain point is specifically the extra character, so I'm not sure how much this would actually help in the end.

**Comment by vexx32** [comment]
It is worth discussing whether the parameter binder should, as a final fallback if nothing matches the given parameter name unambiguously, mimic behaviour from how these tools handle shorthand switches?

e.g., `Remove-Item -rf` where `-rf` is not able to be matched to any singular parameter name, should it enumerate switch parameters and see if it can unambiguously assign _multiple_ parameters, one to each character specified?

**Comment by joeyaiello** [comment]
@PowerShell/wg-powershell-cmdlets has discussed this, and despite the fact that a couple of us have the `rm -rf` muscle memory, we are rejecting this proposal for the following reasons:
* it creates an unreasonable expectation of consistency between platforms (e.g. `rm -rf` on macOS/Linux actually executes `/bin/rm` while it would execute `Remove-Item` on Windows)
* the implementation is complex and rife with potential for regression around the parameter binder

We also don't want to pursue the `-RecurseForce` as a one-off for `Remove-Item` because of the precedent that it sets with creating arguments like that for other cmdlets

If folks feel very passionately about having this functionality, the community is welcome to create a Gallery module that has well-formed wrapper functions for common scenarios like this. That module could even end up being configurable for folks with slightly different muscle memory requirements
