### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by mjyeaney** [PowerShell/PowerShell#2214]
I hope I'm not missing the obvious, but where are the un-install instructions for OSx/Linux?

I can figure out the high-level pieces (remove symlink, remove /usr/local/microsoft/powershell/*, etc.), but it would be nice to have an official guide.

Thanks.

**Comment by MaximoTrinidad** [comment]
Very Good question Michael!  

I already want thru one newer version but I use a new Ubuntu VMN for it.

The question would be if the upcoming newer releases are going to be available thru repositories for both "apt-get' and 'yum-yum' (or any other)?  

I'm sure they are working on it. 
:)

**Comment by ealexjordan** [comment]
If you installed using the .deb package, normal Linux .deb uninstallation instructions should apply. http://askubuntu.com/questions/22200/how-to-uninstall-a-deb-package

@MaximoTrinidad - does `sudo apt-get remove powershell` not work for uninstalling powershell? 

As far as OSX goes, there is no default package manager that I'm aware of for uninstallation, it will need to be manually uninstalled.

**Comment by andschwa** [comment]
Likewise for `yum` on CentOS/RHEL: `sudo yum remove powershell` per [RedHat's docs](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/sec-Removing.html).

In essence, when you install a Linux package, you then uninstall it using the Linux package manager.

OS X's packages are notoriously annoying because they don't support automatic removal; but this is another issue (and we intend to replace PKGs with brewfiles).

Thanks for your interest!

**Comment by feelosophy13** [comment]
This is the best uninstall instruction I found so far for MacOS: https://www.chubbydeveloper.com/powershell-on-macos/
