### ISSUE TITLE
Properties with accessor and mutator methods

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2219]
Copied from TFS 3231229

We should be able to do something along these lines

``` powershell
class foo
{
  [string]$bar {
    get { 
      #getter code
    }
    set {
      # setter code
    }  
  }
}
```

**Comment by iSazonov** [comment]
@vors  This is interesting. Could you clarify: this requires not only changes in the parser?

**Comment by vors** [comment]
It will be at least these places:
- Parser
- ASTs
- PSType.cs

**Comment by iSazonov** [comment]
@vors Thanks! I went thinking :-)

**Comment by iSazonov** [comment]
@PowerShellTeam Please assign me.

**Comment by powercode** [comment]
Are we sure this is the syntax we want?
How does it interact with existing syntax?
What about the following:
``` 
# readonly property
class A {
   [int]$i {get;} # ??? explicit backing property
   A($i){
      $this.i = $i
   }
}
# getter setter: do we have a private backing field?
class A {
   [int]$i {
        get {
           # what here?
        } 
        set {
            if ($value -lt 0) {throw 'x'}
            $i_ = $value
         }
   } = 4 # default value 
}
```

There's been a lot of work done i C# to handle a lot of these cases, and I think it is worth to take some time to think through what we want to achieve here. And I think there is a lot to learn from other languages here.

Let us list and discuss the scenarios before jumping to implementation.

**Comment by iSazonov** [comment]
@powercode I am full agree.
Now I am preparing the **base** for these enhancements. I am on parser step and completed a parser for `get/set {...}` (Parser error recovery takes a long time).
I can inform you that the original code already does implicit get/set and backing field, and attribute processing.
Now I plan to do as soon as possible a PR with the parser and get feedback. Then do next step and make AST and compile for  `get/set {...}`. If this discussion will adopt new features, then I can always add them immediately or in subsequent PRs because the base will be ready.

**Comment by iSazonov** [comment]
It seems the code is ready for testing.
I remember that @lzybkr  spoke about the specifics of these tests.
Where will we locate these tests? In Scripting.Classes.BasicParsing.Tests.ps1?
Any advise before I begin?
Do it makes sense to make PR now and add tests later?

**Comment by lzybkr** [comment]
Sorry, I missed commenting on this. I don't have a strong preference on tests.  BasicParsing.Tests.ps1 is probably not the place for anything that tests semantics.

You can submit a PR whenever you like - but if there aren't any tests, of course you'll be asked to add them.

**Comment by SeeminglyScience** [comment]
I have this mostly done.  Implementation needs some cleaning up, may need some design changes, and still needs tests and semantic checks, but it all works.  Aiming to get a PR up this weekend or next.

Progress in [this branch](https://github.com/SeeminglyScience/PowerShell/tree/custom-property-accessors).

**Comment by iSazonov** [comment]
@SeeminglyScience I have very old (2 year) implementation (90%) in the branch https://github.com/iSazonov/PowerShell/tree/classgetset-4
You can (must :smile:) grab tests from the branch. 
Also I quickly look your implementation and think you could find useful ideas in my branch too.

**Comment by SeeminglyScience** [comment]
@iSazonov Hmm looking at your branch now, I don't think these tests have a ton of overlap.  Your design is very clever, though I was looking for a more traditional implementation.

**Comment by iSazonov** [comment]
Re design. I tried to cover all the options that users can type that is very user-friendly. I hope I achieved it. 
I also tried to cover it all with tests which can save you a lot of time.

Re implementation. It was my first exercise. I did not know C# at all, do not know PowerShell insides, and haven't programmed for more than twenty years. So your implementation is in more right direction. Using a tokenizer is exactly the right way. 

Re details. 
- I explicitly used $PSItem/$_ as parameter in setter (analogue of "value" keyword in C#).
- I explicitly used method like return in getter

**Comment by SeeminglyScience** [comment]
> Re implementation. It was my first exercise. I did not know C# at all, do not know PowerShell insides, and haven't programmed for more than twenty years.

Very impressive! Bravo 🙂 

> I explicitly used $PSItem/$_ as parameter in setter (analogue of "value" keyword in C#).

Yeah I went with `$value` but I'll definitely change that to dollar under.  `$value` feels very out of place.  I'm sort of inclined to go for all three, but that's almost definitely overkill.

I really like the design but I think it's conceptually more difficult than you might think.  It took me a solid minute or so looking at the tests to understand that it's basically just altering the input/output of an auto backing field.  I'm not sure if it's possible to use a lot of the patterns I want accessors for with that design.

I basically implemented a clone of C#'s accessor declarations. We can't define fields but hidden properties work just as well (mostly).  It would be awesome if there was a way to do both though, maybe a keyword or attribute?  It's hard to think of a pattern where that's easily understood.

> I explicitly used method like return in getter

👍

**Comment by iSazonov** [comment]
> I'm sort of inclined to go for all three, but that's almost definitely overkill.

I considered "$value" too and rejected because we all expect $_ in PowerShell and that's enough.

> I really like the design but I think it's conceptually more difficult than you might think.

Sorry, I don't understand that you mean. Could you share more information and samples?

> It would be awesome if there was a way to do both though, maybe a keyword or attribute? It's hard to think of a pattern where that's easily understood.

I stopped on this (and did not even bother to support "private"). 
It is fascinating, but it is not clear how necessary. Therefore, I stopped at the simplest case. For the same reason, I rejected parametric properties and indexers, although I initially implemented them.

**Comment by SeeminglyScience** [comment]
> Sorry, I don't understand that you mean. Could you share more information and samples?

From the tests:

```powershell
class foo
{
    [string]$bar {
        set { return "---$PSItem---" }
        get { return "+++$PSItem+++" }
    }
}
```

I think that's a lot harder to understand what's going on versus this:

```powershell
class foo
{
    hidden [string] $_bar

    [string] $bar {
        get { return '+++' + $this._bar + '+++' }
        set { $this._bar = "---$PSItem---" }
    }
}
```

**Comment by iSazonov** [comment]
Thanks for clarify. I see you point. Your option is easier to implement. I tried it and refused for the same reasons (harder to understand :-) ). In my opinion, this requires more user training and makes more mistakes. Also your option gives users too much freedom and provokes side effects. 
In general, I believe that this backfield should appear in an explicit form only when it is really impossible to do without it - but we can.

@SeeminglyScience Have you other thoughts to share? I think we need to get a community feedback.

/cc @vors @lzybkr @mklement0 @rjmholt @daxian-dbw @SteveL-MSFT

**Comment by SeeminglyScience** [comment]
Seeing a setter that returns feels off.  It took me a little bit to get what was happening, and I imagine it would be harder for other folks who aren't as familiar with the behind the scenes. Speculation of course, could just be me.

> Also your option gives users too much freedom and provokes side effects.

I think that type of freedom fits well in PowerShell.  Even so, I don't think we need to be more strict than C#.

> In general, I believe that this backfield should appear in an explicit form only when it is really impossible to do without it - but we can.

I can't think of many instances where I would implement an accessor that fits neatly into that mold.  If it's not generated per call (where I wouldn't need backing field) or lazy init then I'm not likely to need accessors.

**Comment by rjmholt** [comment]
Wow! Really amazing you guys have tackled this. Feel like I'm quite late to this discussion.

I personally found the usage of `$PSItem` took me a while to understand in the example above. The `get`/`set` syntax being basically C# I think creates the expectation of C#-like semantics where you have to explicitly create your own backing property if you want something more than just assignment and dereference of a backing field.

The thing is that PowerShell classes don't really have fields &mdash; properties with no `get` or `set` are equivalent to C# classes with `{ get; set; }` &mdash; so `get` and `set` must have non-trivial bodies. But not all getters and setters need backing fields (they might be what EF calls a "computed property"), so `$PSItem` doesn't apply in all cases (not really a big problem -- this is true in other usages of $PSItem in PowerShell).

I think part of the issue is that having syntax so close to C#'s creates an expectation of everything being like C#, but because .NET has getters and setters baked into it I think the syntax proposed is the most sensible. Which basically means I think we should go with @SeeminglyScience's version where `$PSItem` only applies as the value in a setter.

**Comment by ThomasNieto** [comment]
@SeeminglyScience / @iSazonov good work on this. I've been wanting this feature for a while. Do either of you have any updates on the progress of this feature?

**Comment by iSazonov** [comment]
I feel we don't get a progress until we design in-depth. Minor enhancements do not look so useful.

**Comment by SeeminglyScience** [comment]
@ThomasNieto I stopped working on this awhile ago.  The actual code [is mostly done](https://github.com/SeeminglyScience/PowerShell/tree/custom-property-accessors) if anyone else wants to build off of it.  I'm not going to have the spare time for the design debates/probably RFC, so anyone else who wants to take this on is welcome to.

**Comment by JohnFAsh** [comment]
Forgive my ignorance of Powershell internals, but on the face of it could we not make use of the facts that (a) (hidden) get_ and set_<property> methods are automatically created for each property; (b) it is syntactically allowed to user-define the same methods, but (c) this seems to have no effect - the user definition does not override the system-generated one. If it did, that would allow as much flexibility as we could want; but I don't know what other consequences might flow from this.

**Comment by SeeminglyScience** [comment]
> but I don't know what other consequences might flow from this.

Some change would still need to be made to enable that. The biggest consequence is just having to support that forever. Plus you would need some way to annotate that it's for a property, otherwise it would be a breaking change (imagine someone using a snake_case naming convention, while not particularly popular in pwsh it's not unheard of). At that point you might as well add proper language support.

**Comment by JohnFAsh** [comment]
@ SeeminglyScience Thanks for the feedback. 
"... otherwise it would be a breaking change...": I agree it's theoretically a breaking change, but in order for it to have any actual impact, someone would need to have written a get_/set_ method and left it there even though it hasn't ever worked (it's been masked by the system version) - not a likely occurrence, I would suggest.
"...having to support that forever...": surely there are lots of instances where a system default can be over-ridden by writing something with the same name; in fact that's more common than the reverse situation. What is different here?
Thanks for your patience.

**Comment by SeeminglyScience** [comment]
> @ SeeminglyScience Thanks for the feedback.
> "... otherwise it would be a breaking change...": I agree it's theoretically a breaking change, but in order for it to have any actual impact, someone would need to have written a get_/set_ method and left it there even though it hasn't ever worked (it's been masked by the system version) - not a likely occurrence, I would suggest.

I'm thinking it's not too unlikely that some folks *happened* to name a method `get_something` in the same way one might name a method `invoke_the_thing`.

> "...having to support that forever...": surely there are lots of instances where a system default can be over-ridden by writing something with the same name; in fact that's more common than the reverse situation. What is different here?

So ideally it would be implemented inline, so you don't have to define a property and then separately define it's getters and setters as individual methods. If the proposed workaround were implemented then it would need to continue to be supported even after the ideal solution is also implemented.

**Comment by JohnFAsh** [comment]
@SeeminglyScience Thanks  again.

> ...not too unlikely that some folks happened to name a method get_something...

So you're suggesting (are you?) that this might happen when there isn't a property called 'something'; and later the 'something' property gets added, and attempting to access it behaves oddly. That might be puzzling, but it doesn't actually break anything that worked before. Incidentally, I suppose I'm assuming that accessing a property via dot notation gets translated to a get_/set_ method call (because that's probably how I would do it, and the two behave the same at the moment); but I don't know whether that is true.

> ...ideally it would be implemented inline...

Agreed; and I take the point that there might be strange consequences if a user used both techniques on the same property. If necessary this could either be prevented as invalid syntax, dealt with on a 'defined priority' basis (like function definitions in different scopes), or just treated like other duplicate function definitions, i.e. "last one wins".
Incidentally, I made the suggestion simply because the good work you did seems to be in limbo for want of someone to take it forward, and I thought this might be related to the perceived complexity of your solution; so it seemed sensible to ask "what is the simplest thing that might work?" - and that is what came to mind.

**Comment by RalfReddings** [comment]
what became of the plan to implement this feature for classes? I have been asking how to do this in PowerShell on Reddit and StackOverflow and I was reccomended to do it in C#, as PowerShell does not support.

Please consider adding this to PowerShell 7. I dont know any C# and I want to take advantage of this feature in Powershell.
