### ISSUE TITLE
Make Install-Module automatically install in CurrentUser scope for non admin users

### ISSUE THREAD

**Issue by ffeldhaus** [PowerShell/PowerShell#2292]
This is a feature request. Currently `Install-Module` gives a warning in Windows PowerShell if it is not run with admin privileges and `-Scope CurrentUser` is not specified.

As many users just expect `Install-Module` to work and as the ability to install Modules in the current users scope is one of the key advantages of PowerShell, it would be a great enhancement if the default behaviour of `Install-Module` would be to automatically install the Module in the current user scope if it is run with non admin privileges.

**Comment by andschwa** [comment]
Doing it specifically for "non-admin" users would not be a correct approach on Linux. Unlike Windows, Linux permissions are wildy varied, and changing behavior based on root/non-root user is generally regarded as incorrect. If you absolutely must adapt a behavior, you do so based on the result of first trying the operation (rather than guessing if you're going to succeed, you test instead), as it may be that a particular non-root user was given permissions to install to `AllUsers` scope. So we purposefully did not implement this logic.

That said, it may make sense to change the default *regardless of current user or permissions* to be `CurrentUser`, as it is a) far more likely to succeed, and b) probably what the user wants in the first place. What do you think @bmanikm?

So change:

> the default behaviour of Install-Module would be to automatically install the Module in the current user scope if it is run with non admin privileges.

to just:

> the default behaviour of Install-Module would be to automatically install the Module in the current user scope

and then I agree 😄 

I also agree with @ffeldhaus's other issue https://github.com/PowerShell/PowerShell/issues/2286 that the current presented error when installing to `AllUsers` scope fails is confusing. Instead of `System.IO.DirectoryNotFoundException` the error should be something like "you don't have the required permissions".

**Comment by JKeithB** [comment]
It seems like the right/better solution is described in this comment:
_If you absolutely must adapt a behavior, you do so based on the result of first trying the operation (rather than guessing if you're going to succeed, you test instead), as it may be that a particular non-root user was given permissions to install to AllUsers scope_

Working from that, it seems more appropriate to 

1. Always try to install to the privileged location. 
2. If the user lacks permissions, the action fails with an error message that says to use -Scope CurrentUser

That seems easier to implement and more technically accurate. If we take the approach of installing to the current user's location by default, we end up with the problem that all code referencing that module must reference it within that user's location. 

Are we missing something?

**Comment by JKeithB** [comment]
(Reopening issue. Should not have closed it)

**Comment by andschwa** [comment]
I'd say that's more in line with my final comment:

> the current presented error when installing to AllUsers scope fails is confusing. Instead of System.IO.DirectoryNotFoundException the error should be something like "you don't have the required permissions"

Fail more gracefully than currently (but don't attempt the installation *automatically* a second time at a different scope).

**Comment by bmanikm** [comment]
I agree, we need to improve the error messages to fail more gracefully.

**Comment by kilasuit** [comment]
As PowerShellGet has been decoupled to its own Repository in line with #1979 (almost complete as I have a PR coming shortly to finish this move) I have created this issue in the PowerShellGet Repository where further discussions around this issue can occur if required which means we can close this issue in this repository.
