### ISSUE TITLE
Powershell under Linux fails to provide requested exit code

### ISSUE THREAD

**Issue by AdamHepner** [PowerShell/PowerShell#2328]
Steps to reproduce
------------------
`powershell -command {exit 1} && echo $?`
results in output

> exit 1
> 0

Another suggested way:
`powershell -command {throw "exception"} && echo $?`
results in

> throw exception
> 0

Expected behavior
-----------------
In both of the cases I expected the exit code to be 1

Actual behavior
---------------

Environment data
----------------

```powershell
> $PSVersionTable                                    

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.9                                  
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1   
```

Additionally: GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)
OS: Ubuntu 16.04.1

**Comment by SteveL-MSFT** [comment]
The correct usage is:

powershell -command "& {exit 1}"
powershell -command "& {throw 'exception'}"

exit code is 1 as expected on Windows and Linux

**Comment by SteveL-MSFT** [comment]
This functions the same way as Windows PowerShell.  Perhaps @lzybkr knows why powershell -command {get-process} doesn't actually execute get-process

**Comment by daxian-dbw** [comment]
running `powershell -command {get-process}` from bash or cmd.exe actually just creates a script block and writes it out. It's like running `{get-process}` in an interactive powershell console.

What interest me is that `powershell -command 'exit 1' && echo $?` output nothing, while do it like following output 1 as expected.
```
powershell -command 'exit 1'
echo $?
```

so , how do we use the `<native> && <name>` syntax in bash with `powershell -command`?

**Comment by lzybkr** [comment]
@SteveL-MSFT - the syntax `powershell -command "& {exit 42}"` is a little more than necessary - `powershell -command "exit 42"` is sufficient.

Note that `&&` short circuits when the return code is non-zero, so you'd use `powershell -command "exit 42" || echo $?`.

@daxian-dbw is correct about why `powershell -command {exit 42}` doesn't work - from bash/cmd, the curly braces are just random text, they know nothing about script blocks.

In PowerShell, we know what a script block is, and when we know we're calling another native executable that understands script blocks (these days, basically just powershell, but the deprecated mini-shells worked the same), we are smart enough to drop the curly braces.

It's true that this can be confusing - the same command line will do something different b/w powershell and bash/cmd, but it is useful syntax in PowerShell because you get syntax highlighting and parse time checking before running the script.

**Comment by daxian-dbw** [comment]
> Note that && short circuits when the return code is non-zero, so you'd use powershell -command "exit 42" || echo $?.

Ah, thanks @lzybkr, that explains 😄 

```
linux:~$ powershell -command "write-output hello" && echo world
hello
world

F:\temp>powershell -command "write-output hello" && echo world
hello
world
```

**Comment by SteveL-MSFT** [comment]
Submitted doc fix to make the example more clear which led to this misunderstanding 
https://github.com/PowerShell/PowerShell-Docs/pull/649

**Comment by rsalinas** [comment]
I was very shocked by the importance of the quote type:

```
C:\Users\salinas>powershell -command "throw 1" && echo ok
1
En línea: 1 Carácter: 1
+ throw 1
+ ~~~~~~~
    + CategoryInfo          : OperationStopped: (1:Int32) [], RuntimeException
    + FullyQualifiedErrorId : 1


C:\Users\salinas>powershell -command 'throw 1' && echo ok
throw 1
ok
```

**Comment by daxian-dbw** [comment]
@rsalinas CMD strips off the double quotes and keeps the single quotes
```none
C:\>E:\PowerShell\test\tools\TestExe\bin\Debug\netcoreapp2.1\win10-x64\testexe.exe -echoargs 'qrr'
Arg 0 is <'qrr'>

C:\>E:\PowerShell\test\tools\TestExe\bin\Debug\netcoreapp2.1\win10-x64\testexe.exe -echoargs "fafa"
Arg 0 is <fafa>
```
