### ISSUE TITLE
'screen' is incompatible with PowerShell

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#2364]
Repro:

Ubuntu 14.04

``` powershell
powershell
sudo apt-get install screen
screen
ls
```

Expected:
prompt to come back

Actual:
hangs on output

Removing PSReadline doesn't change the result.  Ctrl-A then k to kill the current screen session.

``` powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.10
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by MaximoTrinidad** [comment]
I will have to say that's possible nothing is wrong because PowerShell version 6.0.0-Alpha.10 doesn't include the Alias " ls " for Get-ChildItem. It may be implemented later

You can do a "Set-Alias ls Get-ChildItem"  and then you can run " ls " at the PowerShell prompt.

This is on my Ubuntu 16.04.1 LTS Desktop.

![setaliasls](https://cloud.githubusercontent.com/assets/19892435/18855371/26631b24-8420-11e6-935d-a3dfe65635fc.png)

![setaliasls2](https://cloud.githubusercontent.com/assets/19892435/18855472/04dbf218-8421-11e6-9109-0a319ee5f3c6.png)

**Comment by SteveL-MSFT** [comment]
@MaximoTrinidad the issue is specific to using native commands within PowerShell within Screen

**Comment by MaximoTrinidad** [comment]
Thanks for clarifying! 
:)

**Comment by andschwa** [comment]
Ah, I was able to repro this. Definitely strange.  But it does work correctly inside `tmux`.

Even weirder: executing `$env:TERM` totally worked: it executed, printed `screen` as expected, and the prompt displayed afterward no problem.

**Comment by MaximoTrinidad** [comment]
Ah! I didn't have 'screen' installed.  After I install it, I went through the steps:

1. Open Terminal
2. Run powershell
3. At powershell prompt, execute screen
4. in screen Bash prompt (within powershell)
5. Run a Linux command ' ls ' then exit.
6. Goes back to powershell prompt.

It works for me without any additional changes after installing 'screen'.

This is on my Ubuntu 16.04.1 LTS Desktop, and PowerShell 6.0.0-alpha.10.

![screenissue](https://cloud.githubusercontent.com/assets/19892435/18896365/3bb3c1de-84ef-11e6-8dd4-61c665d3c49d.png)

**Comment by SteveL-MSFT** [comment]
doesn't repro on Ubuntu 16.04 for me either

**Comment by SteveL-MSFT** [comment]
@MaximoTrinidad in your repro screenshot, it shows that "screen is terminating" which may explain why it didn't repro for you

**Comment by MaximoTrinidad** [comment]
Hi Steve!  

You have to forgive me. I've been working with Linux for the since and learn a lot.  Before, I didn't that Screen installed and when I typed Screen nothing happen (no errors).  

So, after I installed Screen, I thought the behavior of [screen is terminating] within PowerShell was correct.  Now, I can use Screen within PowerShell.  Is cool to go back and forth with it.  

:)

**Comment by ealexjordan** [comment]
Only native commands hang, due to an escape character being improperly read by screen. Can repro this in Mobaxterm on Centos and Ubuntu, and on bare metal Ubuntu.  Cannot repro this in Hyper-V, tmux, dvmt, and cannot repro on anything with term set to xterm-256color (or term other than screen) in .screenrc. 
There are a number of bugs filed with GNU screen that this could be related to (https://savannah.gnu.org/bugs/?42342).

I'm reassigning to documentation. It should be documented that term needs to be properly set in .screenrc for the PowerShell console to properly work.

**Comment by SteveL-MSFT** [comment]
This is no longer repro'ing for me on Ubuntu16 and alpha.18.  TERM is set to xterm-256color, so maybe Ubuntu changed the default on an update.
