### ISSUE TITLE
iex (new-object net.webclient).downloadstring

### ISSUE THREAD

**Issue by gearcapitan** [PowerShell/PowerShell#2383]
![kali 2016-2016-09-28-23-06-16](https://cloud.githubusercontent.com/assets/13740942/18940699/342c3d24-85d0-11e6-8887-4cba45c1d917.png)

please any advice?

**Comment by andschwa** [comment]
@gearcapitan PowerShell Core is built with .NET Core, which is a different language (or as different as you can get, like `python2` vs `python3`) from .NET 4.5.

For .NET Core **1.0.0**, which is what PowerShell is currently using, you're probably looking for [`System.Net.Http.HttpClient`](https://github.com/dotnet/corefx/blob/release/1.0.0/src/System.Net.Http/ref/System.Net.Http.cs).

That said, the `master` branch of .NET Core looks like it [brought back `System.Net.WebClient`](https://github.com/dotnet/corefx/commits/master/src/System.Net.WebClient/ref/System.Net.WebClient.cs), which means this will change yet again with the next release of .NET Core.

So anyway, this isn't working because the type you're trying to use doesn't exist in the language you're using (.NET Core). But apparently its existence was missed, and it looks like it'll come back. Thus I don't really know what to recommend here. Does `Invoke-WebRequest` not fulfill your need?
