### ISSUE TITLE
Get-Content corrupts PowerShell when binary content is encountered

### ISSUE THREAD

**Issue by Josephur** [PowerShell/PowerShell#23965]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run Get-Content on a binary file such as: Get-Content C:\Windows\Explorer.exe

Your PowerShell prompt is now all corrupted and must be closed and a new session initiated.

### Expected behavior

```console
PowerShell should prevent this kind of corruption, and return the user to a normal PowerShell prompt, even if binary data was spit out.

You may ask yourself, why in gods name is this guy using Get-Content on binary data??  Well I was recovering files from a corrupted file system, and actually was printing out the contents of a .txt file that had malformed binary data in it, thus I found the issue.
```

### Actual behavior

```console
The shell gets corrupted, and you can no longer read text.
(see attached images)
```

### Error details

```console
No Get-Error is raised
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/6666442/2d52c54f-0795-43a2-b44e-2da128eff9bd)

![image](https://github.com/PowerShell/PowerShell/assets/6666442/18b5c8c3-d69e-401c-8e6e-011e8d3a3823)

**Comment by dwtaber** [comment]
I'm not yet able to reproduce anything quite as messy as what you got, but I do think I've found something. Running `Get-Content c:\windows\explorer.exe`, some kind of escape sequence spills over as input on the subsequent prompt. Testing with conhost.exe and Windows Terminal on Win10 and Win11, I get:

|OS|Terminal|Sequence|
|-|-|-|
|Win10 | conhost.exe | (nothing in this case)|
|Win10 | Windows Terminal | `[?61;6;7;14;21;22;23;24;28;32;42c`|
|Win11 | conhost.exe | `[?1;0c`|
|Win11 | Windows Terminal | `[?61;6;7;21;22;23;24;28;32;42c`|

Behavior is otherwise normal, _unless_ I stop execution early with CTRL+C. In that case, the exact behavior seems to vary (perhaps based on what exactly is being output when I interrupt it), but it mostly seems to consist of backslash characters displaying as something else. They still work normally, however, and if I rerun the command and let it finish, normal appearance is restored.

So far, this behavior seems to be consistent between current and older versions of PowerShell 7, as well as 5.1.

**Comment by dwtaber** [comment]
Doing a little more research, it looks like what's happening here (in my case, at least) is that, somewhere in the binary content, something is being parsed as a "Return Terminal ID" control character. The same sequence shows up as input on the next prompt if your command contains `` `eZ``.

**Comment by rhubarb-geek-nz** [comment]
The three components involved are all doing exactly what they have been told to do.

1. Get-Content is writing the contents of a file to the output stream
2. PowerShell is sending that stream to the console
3. The console is interpreting the characters and control codes.

The various control codes that terminals respond to include changing modes and character sets, reporting the terminal type and location of the cursor.

You would get exactly the same behaviour in `bash` if you used `cat` to write a binary executable to the output.

The reason this doesn't happen in cmd.exe (eg type c:\windows\explorer.exe) is likely that type stops as soon as it sees the legacy control-Z which used to be used in the days of CP/M as end-of-file marker.

> Get-Content corrupts PowerShell

PowerShell is not corrupted, the current console output just looks different to what you might have been expecting.
