### ISSUE TITLE
`PSCustomObject` unnoticeably merges similar keys

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#23986]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The `PSCustomObject` constructor (the `[PSCustomObject]` type initializer and `New-Object -TypeName PSCustomObject`) unnoticeably merging similar (case sensitive and different type) keys:

```PowerShell
$dictionary = [System.Collections.Specialized.OrderedDictionary]::new()
$dictionary['One'] = 1
$dictionary['TWO'] = 2
$dictionary['two'] = 2  # case variation
$dictionary['Three'] = 2

[PSCustomObject]$Dictionary

One TWO Three
--- --- -----
  1   2     2
```

```PowerShell
$Json = '{
  "One": 1,
  "two": 2,
  "Two": 2,
  "three": 3,
  "Three": 3,
  "THREE": 3
}'
$OrderedHashTable = $Json | ConvertFrom-Json -AsHashTable

[PSCustomObject]$OrderedHashTable

One two three
--- --- -----
  1   2     3

New-Object -TypeName PSCustomObject -Property $OrderedHashTable

One two three
--- --- -----
  1   2     3
```

```PowerShell
[PSCustomObject]@{ [Int]1 = 'Int'; [Long]1 = 'Long' }

1
-
Long
```

### Expected behavior

An (runtime) error or at least a warning (The fact that the keys are merged might be **by-design** but it shouldn't happen unnoticed.)
Similar to (knowing that error actually comes from the `hashtable` parser):
```PowerShell
[PSCustomObject]@{ '1' = 'String'; 1 = 'Number' }
ParserError:
Line |
   1 |  [PSCustomObject]@{ '1' = 'String'; 1 = 'Number' }
     |                                     ~
     | Duplicate keys '1' are not allowed in hash literals.
```

### Actual behavior

The similar (but different case or type) properties disappear with no warning.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

<sup>I Couldn't find a duplicate (but if there is, please don't hesitate to close this issue as a duplicate)</sup>

**Comment by mklement0** [comment]
Just to spell out the de facto behavior:

When a case-sensitive dictionary is cast to `[pscustomobject]` and it has keys that are _case variations_ of each other:
* It is the _first_ key among them that becomes the property _name_.
* It is the _last_ case-variant key's  associated _value_ that becomes the property _value_.

This happens quietly.

By contrast, when such a situation is _indirectly_ encountered in the context of `ConvertFrom-Json`, an _error_ is reported; e.g., `'{ "foo": 1, "FOO": 2 }' | ConvertFrom-Json` results in:
`ConvertFrom-Json: Cannot convert the JSON string because it contains keys with different casing. Please use the -AsHashTable switch instead. [...]`

Making a `[pscustomobject]` cast fail with a similar error in the analogous situation would technically be a breaking change.
The question is whether that change would fall into [bucket 3](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area) or not.

**Comment by iRon7** [comment]
> Making a `[pscustomobject]` cast fail with a similar error in the analogous situation would technically be a breaking change.

Agree, but I think that there is also an option to just **warn** upon a value that already exists and been overwritten, which makes it less servere than an error.

**Comment by SteveL-MSFT** [comment]
It makes sense to have this behavior better documented.  Please open an issue in https://github.com/MicrosoftDocs/PowerShell-Docs and point to https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pscustomobject?view=powershell-7.4 regarding case-sensitivity and keys.

The quiet behavior, I believe is `by-design` as the intent is that the keys are case-preserving, but not case-sensitive, so any subsequent assignment to a key would override the previous value (last one wins).

Note that casing a hashtable with keys differing by case already fails as expected:

```console
> [pscustomobject]@{a=1;A=2}
ParserError:
Line |
   1 |  [pscustomobject]@{a=1;A=2}
     |                        ~
     | Duplicate keys 'A' are not allowed in hash literals.
```
