### ISSUE TITLE
Powershell Update: Why not offering simple security processes?

### ISSUE THREAD

**Issue by schittli** [PowerShell/PowerShell#23983]
### Summary of the new feature / enhancement

As we all know, Microsofts PowerShell update "Concept" is a shame:
> For best results when upgrading, you should use the same install method you used when you first installed PowerShell. The update method is different for each platform and install method.

Of course, it would be easy to offer a solution that meets the current state of the art and, above all, proven security procedures.

It is a shame that an important component, even a script & automation environment such as PowerShell, cannot be updated automatically with a simple command. Particularly because this can pose major security risks if users are unable to update PowerShell with the help of Google.

### Proposed technical implementation details (optional)

The Use-Case is pretty simple:
1. `Get-PowerShell` to get information about PowerShell, e.g. which version is installed, to which release-channel the version belongs, etc.
2. `Update-PowerShell -Channel <beta|mature> [-UpdateModules] [-Force] [-ErrorAction SilentlyContinue]`
    * to update PowerShell using the beta or mature release-channel
    * to do nothing (SilentlyContinue) if everything is up to date
    * it would be great if the module-update process could be initialized, too

It's a shame that M$ has no inner motivation to make sure M$ customers gets state-of-the-art Software for all the billions they pay every month.

**Comment by SteveL-MSFT** [comment]
@schittli please review our [Code of Conduct](https://github.com/PowerShell/PowerShell/blob/master/CODE_OF_CONDUCT.md).  Inflammatory language is not welcome.  I've modified your issue title as an example for others instead of what you originally wrote so that others don't see that as being acceptable.

There are already existing issues regarding a built-in update mechanism for PS7 so I suggest you visit those to see the pros/cons and conversation with the community.  PowerShell 7 is updated via the mechanism you installed it whether that's msix, MSI (which adds Microsoft Update support), apt, yum, brew, etc...
