### ISSUE TITLE
Enter-PSSession with VMName gives cast error

### ISSUE THREAD

**Issue by nils-trustnode** [PowerShell/PowerShell#24014]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Enter-PSSession -VMName 'testvm' -Credential $credential ends with an error message. Changing the VMName or omit the Credential flag doesn't fix it. 

### Expected behavior

```console
Shell into guest vm
```

### Actual behavior

```console
Error: "Enter-PSSession: Unable to cast object of type 'System.String' to type 'VMState'."
```

### Error details

```console
Exception             :
    Type       : System.InvalidCastException
    TargetSite :
        Name          : GetRunspaceForVMSession
        DeclaringType : [Microsoft.PowerShell.Commands.EnterPSSessionCommand]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message    : Unable to cast object of type 'System.String' to type 'VMState'.
    Source     : System.Management.Automation
    HResult    : -2147467262
    StackTrace :
   at Microsoft.PowerShell.Commands.EnterPSSessionCommand.GetRunspaceForVMSession()
   at Microsoft.PowerShell.Commands.EnterPSSessionCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Enter-PSSession], InvalidCastException
FullyQualifiedErrorId : System.InvalidCastException,Microsoft.PowerShell.Commands.EnterPSSessionCommand
InvocationInfo        :
    MyCommand        : Enter-PSSession
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 9
    Line             : Enter-PSSession -VMName 'testvm' -Credential $credential
    Statement        : Enter-PSSession -VMName 'testvm' -Credential $credential
    PositionMessage  : At line:1 char:1
                       + Enter-PSSession -VMName 'testvm' -Credential $credential
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Enter-PSSession
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
Can you share the value of `(Get-VM -Name testvm).VMState`? The code can certainly be improved to handle an unknown value rather than throwing an exception here but knowing what the current state is would be helpful to understand why it might be failing.

**Comment by nils-trustnode** [comment]
(Get-VM -Name testvm).State is running. The command works fine with PS 5.1.14393.6343, so the cause can not be the vm.

**Comment by jborean93** [comment]
I think I see what the problem is, the code is failing in the method [GetRunspaceForVMSession](https://github.com/PowerShell/PowerShell/blob/2d83b95539e2cee0e41a75887a5cf97a0150a793/src/System.Management.Automation/engine/remoting/commands/PushRunspaceCommand.cs#L934-L1102). Based on the error message it is failing at the line

```csharp
if ((VMState)results[0].Properties["State"].Value != VMState.Running)
```

The value of `results[0].Properties["State"].Value` is the same as `(Get-VM -Name $vmName).State` and in normal circumstances this is going to be a enum value of the type `Microsoft.HyperV.PowerShell.VMState` but in your case it's a `System.String` hence the failure

> Unable to cast object of type 'System.String' to type 'VMState'

The reason why you have a string here and not the enum type is because the Hyper-V module that is imported is running in an implicit remoting session because the Windows version you are running against doesn't ship with an updated version of the Hyper-V module that is compatible with newer versions of .NET. Because it's run in the implicit remoting session the enum value is being serialised to a string rather than the enum value itself causing a failure during the cast.

Essentially as the Hyper-V module cannot be natively loaded PowerShell 7 on your Windows build it is doing the following when it imports it

```powershell
$winPS = New-PSSession -UseWindowsPowerShell
Import-Module -Name Hyper-V -PSSession $winPS

(Get-VM -Name testVM).State.GetType().FullName
# System.String
```

Unfortunately there's not much you can do to workaround this problem as Server 2016 (build 14393) won't ship with the updated Hyper-V module that is present in newer versions so it cannot be loaded in the process. I can try and submit a change in PowerShell to make the check a bit more lenient for this scenario but I cannot guarantee it'll be looked at. Your only real solution at this point in time is:

+ Use Windows PowerShell to call `Enter-PSSession` as it can load the Hyper-V module directly
+ Upgrade the Windows OS to Server 2019 where the Hyper-V module is natively compatible with the newer .NET versions used by PowerShell 7 - https://learn.microsoft.com/en-us/powershell/windows/module-compatibility?view=windowsserver2022-ps

**Comment by jborean93** [comment]
PR to handle when Hyper-V can only be imported using the implicit remote session on older hosts https://github.com/PowerShell/PowerShell/pull/24032. While I don't have a Server 2016 host to test with, this does still continue to work on Server 2022 where the module can be imported natively.
