### ISSUE TITLE
🔴 Lnk shortcut tragetPath not showing emoji/space character in powershell output

### ISSUE THREAD

**Issue by nitin2953** [PowerShell/PowerShell#24066]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

if targetPath of a Lnk shortcut file have emoji/space characters, then it is not showing in the powershell output

```
Desktop
├── lnk-test 😀
│   └── file.txt
└── file.txt.lnk
```

1. make folder with emoji/space characters in it's name
2. place a file in it
3. create a shortcut of the file outside or somewhere else
4. try to get `targetPath` of the shortcut like this:

```powershell
PS \Desktop> (New-Object -ComObject WScript.Shell).CreateShortcut("file.txt.lnk").TargetPath

C:\Users\xxx\Desktop\lnk-test\file.txt # actual output
C:\Users\xxx\Desktop\lnk-test 😀\file.txt # expected output
```

This issue is also present in Powershell 5

### Expected behavior

```console
C:\Users\xxx\Desktop\lnk-test 😀\file.txt
```

### Actual behavior

```console
C:\Users\xxx\Desktop\lnk-test\file.txt
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
It's an unfortunate bug, but PowerShell isn't to blame here (you'd see the same symptom in VBScript, for instance).

I suggest using the [Feedback Hub app](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) to report the problem.

Specifically, the problem is that a string decoded from the _ANSI_-encoded form of the target path is reported. The ANSI-encoded form cannot encode most of the characters outside the 8-bit Unicode subrange, so the two code units that make up your `😀` emoji are lossily converted to verbatim `?` characters (in my experiments).

Curiously, a UTF-16-encoded form of the path - by definition capable of representing _all_ Unicode characters - is _also_ contained in the `.lnk` file, but seemingly not used.

**Comment by nitin2953** [comment]
@mklement0 Thank you very much for explanation

**Comment by mklement0** [comment]
[This Stack Overflow answer](https://stackoverflow.com/a/74734553/45375) shows a **workaround**; in a nutshell:

```powershell
$shortcutFile = Convert-Path 'c:\path\to\your\shortcut.lnk'

$targetPath = & {
  $shell = New-Object -ComObject Shell.Application
  $fileObject = $shell.Namespace((Split-Path $shortcutFile)).ParseName((Split-Path -Leaf $shortcutFile))
  $fileObject.ExtendedProperty('System.Link.TargetParsingPath')
}

# Print
$targetPath
```

**Comment by nitin2953** [comment]
Thank you very much for your help @mklement0
