### ISSUE TITLE
Powershell package is missing in Ubuntu 24.04 repo

### ISSUE THREAD

**Issue by horvatal** [PowerShell/PowerShell#24198]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Tried to install powershell following the docu: https://learn.microsoft.com/en-gb/powershell/scripting/install/install-ubuntu?view=powershell-7.4#installation-via-package-repository-the-package-repository but package is missing.

### Expected behavior

```console
$ sudo apt install -y powershell
--> latest package is installed
```

### Actual behavior

```console
$ sudo apt install -y powershell
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package powershell
```

### Environment data

```powershell
package not listed in https://packages.microsoft.com/ubuntu/24.04/prod/dists/noble/main/binary-amd64/Packages
```

**Comment by rhubarb-geek-nz** [comment]
Given that the current Debian build does not install on Ubuntu can I recommend you now do a special build for Ubuntu where...

1. fix the libicu dependencies to depend on versions available on Ubuntu 24.04 
2. fix the libssl dependencies, eg needs libssl3t64 on armhf
3. fix the libssl/libcrypto symbolic links patched in the init script to point to shared libraries that actually exist
4. depend on and use the existing dotnet-runtime-8.0 from the Ubuntu repository rather than duplicate dotnet runtime in the powershell package
5. build in a manner that it can be handed-over/reused by Canonical to eventually include in their own repository just like they do with the dotnet-sdk

**Comment by kilasuit** [comment]
Currently waiting on [this issue](#21385) to be resolved so marking this as resolution-duplicate

**Comment by oraclejavanet** [comment]
Hello. Any updates? Just installed a new version of Ubuntu 24.04 and was looking forward to pwsh.

**Comment by rhubarb-geek-nz** [comment]
> Hello. Any updates? Just installed a new version of Ubuntu 24.04 and was looking forward to pwsh.

Alas no. Various workarounds are listed at https://github.com/PowerShell/PowerShell/issues/23197

**Comment by oraclejavanet** [comment]
> > Hello. Any updates? Just installed a new version of Ubuntu 24.04 and was looking forward to pwsh.
> 
> Alas no. Various workarounds are listed at #23197

Thank you for the update. I just reinstalled Ubuntu Desktop 22.04.5.
