### ISSUE TITLE
Why does a class that inherits `PSObject` always return type `PSCustomObject`?

### ISSUE THREAD

**Issue by mdaneri** [PowerShell/PowerShell#24210]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm trying to restrict the object types I can pass to a function in PowerShell. I want to retain the benefits that come with `PSCustomObject`, so I created a custom class that inherits from `PSObject`. However, when I instantiate this custom class and check its type, it always returns as `PSCustomObject` instead of the custom class type.

Here's the code I used:

```powershell
class PSNewType : PSObject {
    PSCustomType([hashtable]$properties) : base() {
        foreach ($key in $properties.Keys) {
            $this.PSObject.Properties.Add([psnoteproperty]::new($key, $properties[$key]))
        }
    } 
}
```

I instantiate it like this:

```powershell
$testPscustomtype =[pscustomtype]::new(@{s=1;b=2})
```

But when I try to get the type using `$testPscustomtype.GetType()`, it returns `PSCustomObject`.

### Expected behavior

```console
The custom class should return its own type (`PSNewType`) when calling `GetType()`.
```

### Actual behavior

```console
The custom class returns `PSCustomObject` when calling `GetType()`.
```

### Environment data

```powershell
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.4
PSEdition                      Core
GitCommitId                    7.4.4
OS                             Darwin 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

1. Define the custom class as shown above.
2. Instantiate the class with a hashtable.
3. Call `GetType()` on the instance.
4. Observe the returned type.

**Comment by MartinGC94** [comment]
You can add a PSTypeName attribute to restrict values to objects with the right typename:
```
function Verb-Noun
{
    [CmdletBinding()]
    Param
    (
        [PSTypeName("MyCustomType1")]
        [Parameter()]
        $Param1
    )
    $Param1
}

$Test = [pscustomobject]@{Test1="Hello"}
Verb-Noun -Param1 $Test #Fails
$Test.psobject.TypeNames.Add("MyCustomType1")
Verb-Noun -Param1 $Test #Works
```

Might be a better idea than what you are trying to do.

**Comment by mdaneri** [comment]
Thanks I was not aware of the PSTypeName existence.

**Comment by mklement0** [comment]
* **You're seeing a _bug_**: a PowerShell custom `class` should always reports its own type, even if it is derived from another class.

* The simplest **workaround** is to omit the inheritance specifications in your case (`: PSObject`) and `: base()`, which aren't needed - _any_ instance of a .NET type can be decorated with ETS properties via `.psobject`.

**Comment by mklement0** [comment]
As for using _ETS_ (Extended Type System) type names, to add to @MartinGC94's comment:

`PSTypeName` can also be used as a hashtable key, allowing you to build the desired (ETS) type name into hashtable literals:

```powershell
$o = [pscustomobject] @{ PSTypeName = 'PSNewType'; Test1 = 'Hello' }
```

The above is the equivalent of:

```powershell
$o = [pscustomobject] @{ Test1 = 'Hello' }
$o.pstypenames.Insert(0, 'PSNewType')
```

The intrinsic [`.pstypenames`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Intrinsic_Members#type-information) property contains a  list-like data structure that contains the .NET inheritance hierarchy of the type of the instance at hand by default, but can be augmented with ETS type names, as shown above.

Note, however, that the ETS type names are only honored in the following contexts:

* when binding to a parameter decorated with a `[PSTypeName()]` attribute, as shown in Martin's comment.
* when selecting [formatting definitions](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Format.ps1xml), which is based on (ETS or true .NET) type names.

By contrast, such ETS type names:

*  Can _not_ be used as parameter types (those must be true .NET types)
*  Do _not_ work with the `-is` and `-as` operators (ditto)

PowerShell `class`  definitions _do_ produce true .NET types, so these restrictions don't apply to them.

**Comment by mklement0** [comment]
Makes sense not to derive from `PSObject`, which makes the problem of `.GetType()` reporting the wrong type moot.

It is implied by @SeeminglyScience's comment, but since it only just now clicked for me, let me spell it out: 

Because member access on `PSObject`(-derived) instances _delegates to the base object_ and the base object is the `PSCustomObject` singleton for "base-less" instances, `.GetType()` reports the _latter_'s type rather than that the enclosing `PSNewType` (this wouldn't happen in C# code).

Similarly, `[psobject]::new().GetType().FullName` reports `System.Management.Automation.PSCustomObject`, not `System.Management.Automation.PSObject`.

As an aside:

This is less surprising in `([pscustomobject] @{ }).GetType().FullName`, but only because `[pscustomobject]` pretends not to be `[psobject]`, even though it is : _both_ `[psobject]` and `[psobject]` refer to `System.Management.Automation.PSObject`- see #4344.

However,  `[pscustomobject]` or `[psobject]` are _not_ interchangeable in one respect: the syntactic property-bag construction sugar `[pscustomobject] @{ ... }` only works with `[pscustomobject]`

Sadly, `-as [pscustomobject]` does _not_ work meaningfully (it considers an instance of _any_ type as being of that type),  (and neither does `-as [System.Management.Automation.PSCustomObject]`, which doesn't work for _any_ type, even true custom objects, i.e. "base-less" `[psobject]` instances): see https://github.com/PowerShell/PowerShell/issues/4343#issuecomment-348724275).

**Comment by mdaneri** [comment]
I think I can close it. My curiosity has been satisfied
