### ISSUE TITLE
PS 7.4.5 regkey installerproperties with psremoting with '0' value

### ISSUE THREAD

**Issue by musklor** [PowerShell/PowerShell#24298]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When I upgrade from 7.2.19 to 7.4.5, I have three keys with '0' value. (In reg key installerproperties)

### Expected behavior

```console
All values with '1' because it is my setup.
```

### Actual behavior

```console
It's like a default installation. PSRemoting disable and two others things disabled.
```

### Environment data

```powershell
All OS
```

**Comment by musklor** [comment]
So, if I use msi for the 7.2.x version, I have :
- ENABLE_PSREMOTING : 1 (default 0)
- ADD_EXPLORER_CONTEXT_MENU_OPENPOWERSHELL : 1 (default 0)
- ADD_FILE_CONTEXT_MENU_RUNPOWERSHELL : 1 (default 0)

When I use exe, or wsus update or windows update (who use exe), I have the default values.
- ENABLE_PSREMOTING : 0
- ADD_EXPLORER_CONTEXT_MENU_OPENPOWERSHELL : 0
- ADD_FILE_CONTEXT_MENU_RUNPOWERSHELL : 0

The only solution is : 
- no auto update?
- no patching?
- uninstall ps7.2.x and use msi ? (If I use the exe, I can't upgrade with msi because it can't uninstall the 7.2.x version)

**Comment by SteveL-MSFT** [comment]
I believe starting with 7.4.4, the installer options are preserved in the registry so that updates after that will keep what you previously selected.  However, prior to that no installer options were preserved so when updating to 7.4.4+, you would get the defaults.  The next update after will reuse the stored options (which you can change if you go through one interactive install).  The installer doesn't have a way to know what options you previously chose nor what configuration you've set after install.
