### ISSUE TITLE
foreach -parallel is awsome...then it isn't

### ISSUE THREAD

**Issue by rodmarten** [PowerShell/PowerShell#24336]
### Summary of the new feature / enhancement

I think parallel foreach is a huge thing.  Documentation is great.  I can see it exists in 5.4  Only one problem.  in 7.x and other versions it still shows as reserved for future use.  Why do you document a feature that doesn't exist.  Really?

**Comment by MartinGC94** [comment]
Newer versions of PowerShell has `gci C:\ | ForEach-Object -Parallel {}` `foreach -Parallel ($x in $y)  {}` was only a thing in workflows so it wasn't even useful when it was supported.

**Comment by mklement0** [comment]
To add to @MartinGC94's comment:

[_PowerShell (Core) 7_](https://github.com/PowerShell/PowerShell/blob/master/README.md) introduced the `-Parallel` parameter to the [`ForEach-Object`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/foreach-object) _cmdlet_, and it is documented in the linked help topic.

> I can see it exists in 5.4 

There is no 5.4 version - 5.1.x is the latest and _last_ version of _Windows PowerShell_  - the legacy, Windows-only, ships-with-Windows edition - and it does _not_ support `ForEach-Object -Parallel`.

> in 7.x and other versions it still shows as reserved for future use.

**You're seeing an _obscure and obsolete error message_, and _it_ is the only real problem here** (note that Windows PowerShell workflows, where `foreach -parallel` _was_ supported, were [intentionally never ported to PowerShell 7](https://blogs.msdn.microsoft.com/powershell/2018/01/10/powershell-core-6-0-generally-available-ga-and-supported/)):

Somewhat confusingly, `foreach` is _situationally_ either the [`foreach` _language statement_](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Foreach) or an _alias_ of the `ForEach-Object` _cmdlet_.

If you submit something like `foreach -Parallel ($x in $y) {}` _stand-alone_, i.e. _without pipeline input_, it is interpreted as the _language statement_ rather than as `ForEach-Object` (and _with_ pipeline input, the `($x in $y)` part would cause a _syntax error_, because  the `ForEach-Object` cmdlet wouldn't recognize it).

---

In terms of what is actionable here:

In the context of PowerShell 7, the `The foreach '-parallel' parameter is reserved for future use.` error message no longer makes sense and should be replaced with a syntax error.

Based on the error message you currently get with random parameter names, this error should be `The parameter parallel is not valid for the foreach statement.`

That said, even that is somewhat confusing, given that `foreach`, like _all but one_ language statements, doesn't accept _parameters_ - the only exception to that is the [`switch` statement](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Switch).

**Comment by MartinGC94** [comment]
> given that foreach, like all but one language statements, fundamentally doesn't accept parameters - the only exception to that is the [switch statement](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Switch).

There's actually one more exception: The data keyword. See this example:

```
data MyVariable -SupportedCommand Get-ChildItem, Get-Item
{
    @{
        Cmd1Items = Get-ChildItem C:\
        Cmd2Items = Get-Item 'C:\$Recycle.Bin' -Force
    }
}
```
