### ISSUE TITLE
Make it clear that powershell 7 can't replace the version that comes with windows.

### ISSUE THREAD

**Issue by tommyhome** [PowerShell/PowerShell#24371]
### Summary of the new feature / enhancement

Hi,
When reading the docs it looks like powershell 7 is a replacement for the default powershell that comes with windows, but it is not.
There is no way to replace the old one with the new, you can't even replace the link to powershell that is when you rightclick the windowslogo button aka start on your windows machine.

### Proposed technical implementation details (optional)

Stop calling powershell 7 an upgrade when it clearly isn't. It is a new additional program. If it was an upgrade the old version that comes with windows would be overwritten, or at least come with the option to replace it as default.

Why someone thought it was a good idea to name a new program that can't replace the old the same name is beyond my understanding. If I would guess someone really must hate powershell, since it only adds confusion and miscommunication.

Yeah, I'm mad, I spent time trying to understand why my "upgraded" powershell wasn't used. When in reality it isn't an upgrade.
like for instance why my new powershell spawned blue powershell windows when I started a new window from a powershell 7 window (yeah I know now it was the old powershell that got started and that the new powershell has another name to be used with start-Process).

And, since powershell is made by some really smart persons perhaps someone might figure out how to add the powershell 7 to the right click on the windowslogo button aka start on your windows desktop, yes add, not replace. Shouldn't it be easy to use the new version or why are you messing with ppl?

One, really easy fix would be to make the included powershell (that comes with windows) start by stating its version number the same way powershell 7 does (when opening a new window), that would make it clearer to identify that you are not using the new but rather the old. That one would have saved me alot of headache and confusion, I'm guessing I'm not alone.

Yeah, I'm a bit pissed of, I really don't like wasting time for no good reason. 
It is however a rather nice program that has made my life easier. so, thanks for the great work.

**Comment by kilasuit** [comment]
Hi,

Having been an open source developed product since its release in 2016, there is a huge amount of history and decisions as to why PowerShell 6+ ended up using `pwsh` and not `powershell` for the executable name, which goes against the direct in place upgrade experience I think you'd expected. However, to summarise, it was to aid in a number of area's like in deployment to and from package management tooling & to aid in discoverability and ease of use across all platforms and to provide a way for users to slowly shift across to this new version, and enable a better experience for developing it.

PowerShell 7 is an upgrade replacement for Windows PowerShell 5.1 going forward, and whilst there are some differences in features, (mostly lots of new and improved ones and a few removed) it acts as a replacement due to the upgraded but familiar experience it has kept having been built upon the existing prior years of the products development. Whilst it's not a drop in replacement for the older version like you had expected & assumed it should be, this was done for a number of additional good reasons too including for being able to better gain metrics around the new versions use vs the older versions use.

> And, since powershell is made by some really smart persons perhaps someone might figure out how to add the powershell 7 to the right click on the windowslogo button aka start on your windows desktop, yes add, not replace. Shouldn't it be easy to use the new version or why are you messing with ppl?

[This has been asked for as part of the installer in this issue](https://github.com/PowerShell/PowerShell/issues/7794) - which I've reopened to look at it getting implemented in future. Depending on which version of Windows you are using and whether or not you are using the new [Windows Terminal](https://github.com/microsoft/terminal) you may find that the experience is better in the new Windows Terminal for using powershell

We aren't "messing" with people, but I can see how it can seem that way when the changes like this come across in the way that they have.

> One, really easy fix would be to make the included powershell (that comes with windows) start by stating its version number the same way powershell 7 does (when opening a new window), that would make it clearer to identify that you are not using the new but rather the old. That one would have saved me alot of headache and confusion, I'm guessing I'm not alone.

This is something I control with this little snippet in my [CurrentUserAllHosts Profile Script](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.4) to remind me that I am running the older version, even if my mistake 

```powershell
if ($PSVersionTable.PSVersion.Major -match 5) {  Write-Host 'Why you in PowerShell 5 - go into 7'
```
Another way to sometimes tell is that the Window Title will show Windows PowerShell as opposed to PowerShell. 

With any change to experience it can be really tough for us to find the correct changes and ensure that these are properly communicated out to the community. This repo has had ongoing development in it since August 2016 and a number of blog posts, conference & user groups sessions & podcasts over the years, but I appreciate that it's easy to miss this sorta stuff if you have more important things to get on with and using PowerShell is just a small part of your life, compared to many of ours.

We have a number of community resources for learning more, starting with [all the documentation on learn.microsoft.com ](https://learn.microsoft.com/en-us/powershell/) and the [GitHub disucssions feature](https://github.com/PowerShell/PowerShell/discussions) as well as plenty of [places where you can come and connect and ask questions](https://learn.microsoft.com/en-us/powershell/#community-resources)

None of us using PowerShell like wasting time, and whilst perhaps a little frustrating to begin with, I hope going forward it wont be as frustrating as it just had been for you to feel the need to raise this, which I do thank you for (as would the team too) and I hope that's answered all your points, at least for now.

**Comment by kilasuit** [comment]
@237dmitry - today you can almost if not completely replace Windows PowerShell use on Windows with the current PowerShell 7 supported releases, thanks to the interoperability layer where if there are modules that still need v5.1 features or have not been upgraded to support PowerShell 7 [can be imported into a v7 session using this new functionality](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility?view=powershell-7.4)

> Did I translate correctly that in the future PowerShell Core will replace Windows PowerShell? 

There's this discussion about [adding it into Windows](https://github.com/PowerShell/PowerShell/discussions/24340) but that doesn't mean it will replace Windows PowerShell 5.1 but I'm guessing will likely be shipped alongside it, 

Also note we no longer suggest to use PowerShell Core as a term - that was a choice during v6 and was dropped with release to v7 to be called PowerShell

**Comment by 237dmitry** [comment]
Thanks for explanation

> Also note we no longer suggest to use PowerShell Core as a term

I used it for clearance, like `$PSVersion.PSEdition`. It would probably be logical to use the term `Desktop` as well. But the main thing is that it is clear what was meant.

**Comment by tommyhome** [comment]
Thanks for your detailed reply.
I now know, but everyone that starts out as I did will probably face similar challenges.
Especially when you call it an upgrade when it upgrades nothing. It is a fresh install of a new program.
When i upgrade to the latest powershell 7 from an old powershell 7 it doesn't keep that old version, that is the expected behaviour for an upgrade.

The command to tell you that you use the old one is smart, but if powershell 5 displayed the version number right when it starts like powershell 7 does then the confusion would be a lot less for new users. The fact that even you need it is an indication that clarification by putting the version number would make it clearer even for users like yourself.

Inspired by you I opted to do the following
"


Powershell " +$PSVersionTable.PSVersion.Major+"."+$PSVersionTable.PSVersion.Minor+"."+$PSVersionTable.PSVersion.Build
if ($PSVersionTable.PSVersion.Major -match 5) {  
start-Process pwsh
}
I put it in my Microsoft.PowerShell_profile.ps1 script.

that makes it kind of start powershell 7 when klicking on powershell on the start-button right-click list and it makes powershell 5 show its versionnumber like powershell 7 does.

I considered adding stop-Process -name powershell 
but decided against it since it might cause me headache in the future, its not that hard to just close it.

thanks for your time.

**Comment by rhubarb-geek-nz** [comment]
The prompt from PowerShell Desktop is

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows
```

If you follow the link it makes it clear they are two separate versions:

- PowerShell 7 is designed to coexist with Windows PowerShell 5.1. 
- Separate installation path and executable name
- PowerShell 7 installs to a new directory, enabling side-by-side execution with Windows PowerShell 5.1.
- Separate PSModulePath
- Separate profiles
- Separate Event Logs

**Comment by tommyhome** [comment]
@rhubarb-geek-nz 
No, on the latest stable version of Windows 10 it says: "Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6"

And Powershell 7 says it is PowerShell followed by version.

But as we all know Powershell != Powershell.

Clear, where? Not on the page you get to with that link. 
The fact that it doesn't redirect to the same landing page adds even more confusion, since we are getting different information and comparing different stuff.

The link in the powershell 5 window leads to a page with the title "install Powershell on Windows, Linux and macOS". If you go to their suggested way to install it, they recommend using 
winget search Microsoft.PowerShell to find the latest version of Powershell.

on the top to the right on the page the link leads to is a headline "Additional resources" The first link right now is  "Review Windows Powershell - Training". That does add to the confusion.

version 5 is called Windows Powershell and version 7 Microsoft Powershell, for me its the same thing. I get that they call it Microsoft since its available on multiple platforms, but surely if I install powershell on Windows i get a Windows powershell. But, No, I do not. Windows Powershell is as we know another product than Powershell 7 on Windows. or simply Powershell != Powershell.

When I think about it Powershell 7 really should say Microsoft Powershell followed by version number since that is its name.

If you tried really hard you would have a hard time making it more confusing.

back to the windows 10 link, if you scroll down to the headline "install msi package" then there is a note that it installs to a new directory.  But if you read the whole thing it gets even more confusing "PowerShell 7.4 is an in-place upgrade that removes previous versions of PowerShell 7." 
 in-place yeah, but only for version 7, that is a rather interesting way to use that term.

And the note ends with "If you need to run PowerShell 7.4 side-by-side with other versions...", confusion again, I don't need powershell 5 so surely it can be removed I would think. 
But, no, as we know Powershell != Powershell.

I did however solve it for me, thanks to the suggestion about a message in the first reply to my original suggestion.
Now my Windows Powershell, says Powershell 5.1.19041 (or whatever the current version is in the future) when it starts and I also made it start a Microsoft Powershell instance. By doing it that way, I can right-click on the start button and klick powershell and now get a window of both Powershell 5 and Powershell 7. At least less confusion on all my machines.

**Comment by 237dmitry** [comment]
> Try the new cross-platform PowerShell

But it does not replace the old one. PowetShell v.7+ is not a replacement for the old v.5.1, just an alternative. We are all waiting for a full, comprehensive replacement, but as I understand it, this is not in the near future. We are waiting for Windows with open source code.

**Comment by rhubarb-geek-nz** [comment]
> We are all waiting for a full, comprehensive replacement, but as I understand it, this is not in the near future.

I don't see the need for a replacement. Windows has a long history of legacy components living side by side with newer implementations, and if it does include PowerShell 7(or 8) I expect it will be side-by-side.

My system already has three versions of PowerShell Desktop for backward compatibility

```
c:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe
c:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe
c:\Windows\SysArm32\WindowsPowerShell\v1.0\powershell.exe
```

I suggest the fix would be to update the URL used by PowerShell Desktop on Windows 10 to the same URL used on Windows 11. Perhaps the bigger mistake was having adverts in system programs to start with.

**Comment by 237dmitry** [comment]
> I don't see the need for a replacement

Indeed, as a technical side. But it would be better to have one version in use, combine everything that is changed or newly introduced in PowerShell v.7 and access to the system capabilities of Windows PowerShell. Is this a bad fantasy? Why do we, you and me, need two versions that live in parallel? If you are not in the subject, it causes confusion.

**Comment by rhubarb-geek-nz** [comment]
> Why do we, you and me, need two versions that live in parallel?

Windows has been around for forty years, in it's current incarnation for 30 years (dating back to Windows NT 3.1). It has a completely different philosophy to FOSS. To the majority of end users, Windows is just the operating system on every computer that isn't an Apple. It has lasted this long because binary software packages from over twenty years ago still work. People know they can just keep using the same programs that they have always been using. To do this the operating system does summersaults internally, that is why 32 bit code is in a directory called SysWOW64 and 64 bit code in a directory called system32.
It is far more important for Windows that things that work today also work tomorrow.
So it is far better to keep Windows PowerShell 5.1 exactly as it is, just in maintenance mode. So everything that works with it now will continue to work. If you want to do new things, absolutely fine, join the new kids on the block with PowerShell 7. Even though everyone has switched to Edge (if not Chrome or something else), Internet Explorer is still there because it is needed for some sites.

**Comment by 237dmitry** [comment]
> So it is far better to keep Windows PowerShell 5.1 exactly as it is

This does not solve the incompatibility problem with PowerShell v7, which is getting bigger and bigger with each new release. It also confuses new users who see two icons with the same names. And of course there are such crutches as `-UseWindowsPowerShell`. I don't care, I don't use Windows at all, you just need to strive for the best, and not look for excuses in the past, as you do.

**Comment by rhubarb-geek-nz** [comment]
> This does not solve the incompatibility problem with PowerShell v7

It means it is a complete non-issue. The two are not the same thing so can diverge.
 
>  It also confuses new users who see two icons with the same names.

What are the icons you speak of? Current I have four in the start menu, three of them are from Windows PowerShell

- PowerShell 7(x64)
- Windows PowerShell
- Windows PowerShell ISE
- Windows PowerShell (x86)

> I don't use Windows at all

Have you looked in /etc/shells recently? sh, bash, ksh, zsh, dash, pwsh, csh etc, 

> you just need to strive for the best

The best result is that after the monthly "update Tuesday" every Windows machine works as it did before the update.

**Comment by 237dmitry** [comment]
> It means it is a complete non-issue. The two are not the same thing so can diverge.

Why two shells with similar names? I can't understand it. My initial assumption was that PowerShell 7 was supposed to eventually replace Windows PowerShell, and there was talk about it, but many years have passed and the misunderstanding with the names remains. That's the problem. Don't look for any technical aspects here, it's more of a marketing question.

**Comment by rhubarb-geek-nz** [comment]
> Why two shells with similar names?

Or in the case of Linux, why twenty shells with similar names? They have similar names because they are part of a family. 
Same with "PowerShell 7" and "Windows PowerShell", or Coke and Diet Coke.

In the most part PowerShell 7 is backward compatible, but not enough to not break things. With PowerShell 7 decisions have been made with the full knowledge that they are breaking changes (eg JSON conversions and defaulting to UTF-8). 

Breaking things that currently work is simply not an option available for Windows as an operating system used by millions every single day.
