### ISSUE TITLE
Need support

### ISSUE THREAD

**Issue by moazzem-pixel** [PowerShell/PowerShell#24416]
> Need support
> 
> 
> 
>  

 _Originally posted by @moazzem-pixel in [ae3f180](https://github.com/PowerShell/PowerShell/commit/ae3f180145a288e93406dc48454501fe32d29a84#commitcomment-147844757)_

**Comment by iRon7** [comment]
@moazzem-pixel,

❓ Please elaborate on your issue.

The title of your issue is very general and suggest a [PowerShell Support](https://github.com/PowerShell/PowerShell/blob/master/.github/SUPPORT.md) issue:

> # PowerShell Support
>
> If you have any problems, please consult the [known issues][], developer [FAQ][], and [GitHub issues][].
> If you do not see your problem captured, please file a [new issue][] and follow the provided template.
> Also make sure to see the [Official Support Policy][].
> If you know how to fix the issue, feel free to send a pull request our way. (The [Contribution Guides][] apply to that pull request, you may want to give it a read!)

[Official Support Policy]: https://learn.microsoft.com/powershell/scripting/powershell-support-lifecycle
[FAQ]: https://github.com/PowerShell/PowerShell/tree/master/docs/FAQ.md
[Contribution Guides]: https://github.com/PowerShell/PowerShell/tree/master/.github/CONTRIBUTING.md
[known issues]: https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell
[GitHub issues]: https://github.com/PowerShell/PowerShell/issues
[new issue]: https://github.com/PowerShell/PowerShell/issues/new/choose

I don't feel like clicking on an unknown link without any description but In case you looking for [Developing and Contributing](https://github.com/PowerShell/PowerShell#developing-and-contributing) to PowerShell:

> ## Developing and Contributing
> Please look into the [Contribution Guide](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md) to know how to develop and contribute. If you are developing .NET Core C# applications targeting PowerShell Core, [check out our FAQ](https://github.com/PowerShell/PowerShell/tree/master/docs/FAQ.md#where-do-i-get-the-powershell-core-sdk-package) to learn more about the PowerShell SDK NuGet package.
>
> Also, make sure to check out our [PowerShell-RFC repository](https://github.com/powershell/powershell-rfc) for request-for-comments (RFC) documents to submit and give comments on proposed and future designs.
