### ISSUE TITLE
I got an error when running C++ code using PowerShell 7.4.5 on Visual Studio Code

### ISSUE THREAD

**Issue by leij0318** [PowerShell/PowerShell#24469]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have made sure that the tasks.json and launch.json required by visual studio code are written correctly, but when I run the code in the terminal, I get an error.
`Incorrect parameter format：--Command`

This is the run command parameter displayed in the terminal of visual studio code.

```D:\Program Files\PowerShell\7\pwsh.exe '-NoLogo -NoExit -Command chcp.com 65001 -Command D:\msys64\ucrt64\bin\g++.exe D:\Desktop\Codes\cpp\g++/fib.cpp -fdiagnostics-color=always -o D:\Desktop\Codes\cpp\g++/build/fib.exe -fexec-charset=GBK -g -std=c++17 --target=x86_64-w64-mingw'```

### Expected behavior

```console
Done
```

### Actual behavior

```console
Failed
```

### Error details

```console
Incorrect parameter format：--Command
```

### Environment data

```powershell

Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

 This is the terminal settings section of my user settings profile in visual studio code

```
 "terminal.integrated.profiles.windows": {
    "PowerShell": {
      "source": "PowerShell", 
      "overrideName": true,
      "args": ["-NoLogo", "-NoExit", "-Command", "chcp.com 65001"],
      "icon": "terminal-powershell"
    },
    "Command Prompt": {
      "path": ["${env:windir}\\System32\\cmd.exe"],
      "args": ["/K",  "chcp 65001"],
      "icon": "terminal-cmd"
    }
  }
```

**Comment by mklement0** [comment]
Generally, note that this repo is only for reporting issues with PowerShell itself. While https://github.com/Microsoft/vscode/issues would be the right place to report issues with Visual Studio Code (as opposed to needing support), I suspect you'll have a better chance of solving your problem by asking a question on [Stack Overflow](https://stackoverflow.com/) or [Super User](https://superuser.com/).

As for the command line your'e using, it is broken in two ways:

* `-NoLogo`, `-NoExit`, and `-Command` must be individual arguments in order to be recognized; by including them in single string passed (positionally) to `pwsh.exe`, that single string is implicitly treated as a `-File` argument (i.e. needs to be the name or path of a _script file_.

* The `-Command` parameter is only supported _once_  per command line - all subsequent arguments are considered to be part of the command (piece of PowerShell source code) to execute.

Note that the command line isn't consistent with the error message you're quoting, and that, similarly, the `settings.json` excerpt wouldn't explain the creation of such a command line.

It sounds like your problem is in your `launch.json` file.
