### ISSUE TITLE
New-CIPolicy failed to generate new file with Rules

### ISSUE THREAD

**Issue by shubhayu222** [PowerShell/PowerShell#24494]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

For Windows PowerShell 5.1 issues
 
$rules = New-CIPolicyRule -DriverFilePath '.\bootstrapper.exe' -Level Publisher
echo $rules
New-CIPolicy -FilePath '.\FinalNewPolicy.xml' -Fallback Hash -Level Publisher -Rules $rules
"Scan completed successfully"

Name           : DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1
Id             : ID_SIGNER_S_2
TypeId         : Allow
Root           : 65B1D4076A89AE273F57E6EEEDECB3EAE129B4168F76FA7671914CDF461D542255C59D9B85B916AE0CA6FC0FCF7A8E64
FileVersionRef : 
AppIDRef       : 
Wellknown      : False
Ekus           : 
Exceptions     : 
FileAttributes : 
FileException  : False
UserMode       : True
attributes     : {[CertPublisher, PTC Inc.]}

New-CIPolicy : Parameter set cannot be resolved using the specified named parameters.
At line:3 char:1
+ New-CIPolicy -FilePath '.\FinalNewPolicy.xml' -Fallback Hash -Level P ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-CIPolicy], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.SecureBoot.UserConfig.NewCIPolicy
 

### Expected behavior

```console
Expected new policy file will be generated
```

### Actual behavior

```console
New-CIPolicy : Parameter set cannot be resolved using the specified named parameters.
At line:3 char:1
+ New-CIPolicy -FilePath '.\FinalNewPolicy.xml' -Fallback Hash -Level P ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-CIPolicy], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.SecureBoot.UserConfig.NewCIPolicy
```

### Environment data

```powershell
N/A
```

### Visuals

![image](https://github.com/user-attachments/assets/59090123-8708-423c-ad4d-85032f3962e3)

**Comment by mklement0** [comment]
The command in question isn't being maintained in this repository, and your screenshot suggests that you're calling it from Windows PowerShell (note that this repo is only for PowerShell 7 issues).

Please follow the guidance in [Can Windows/Non-Core PowerShell 5 bugs be reported here?](https://github.com/PowerShell/PowerShell/discussions/24299) to determine the appropriate place to report your issue.

If you think that the issue is specific to PowerShell 7, after all, because in Windows PowerShell (v5.1) you observe the expected behavior, please elaborate - but note that this assumes that the module in question loads _directly_ in PowerShell 7 (as opposed to via the [Windows Compatibility Feature](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Windows_PowerShell_Compatibility)) and that the difference in behavior isn't already explained by the differences between Windows PowerShell and PowerShell 7 linked to above.

If you end up creating an issue in the Feedback Hub (on Windows), please share a link to it here.

**Comment by mklement0** [comment]
Taking a step back: The problem may be just one with the specific set of parameters you have passed rather than a problem with the command itself (which I'm not familiar with).
Perhaps the [help topic](https://learn.microsoft.com/en-us/powershell/module/configci/new-cipolicy) helps.

**Comment by shubhayu222** [comment]
@mklement0  I resolved it anyways.
Thanks for your quick response. I missed "+" sign means append while creating  New-CIPolicyRule
