### ISSUE TITLE
Lisp/Guile/Racket integration

### ISSUE THREAD

**Issue by lz5ev-tech** [PowerShell/PowerShell#24540]
### Summary of the new feature / enhancement

Its is possible, Steel Bank Common Lisp or Guile or Racket functionality to be embedded in powershell and the oportunity powershell to produce fully executable native binary output?

**Comment by IISResetMe** [comment]
Why not just install the relevant compiler toolchain and invoke it from PowerShell? Can you expand on what you mean by "be embedded" and why you think that's important?

**Comment by rhubarb-geek-nz** [comment]
The four main ways of integrating other languages with PowerShell are

1. Execute PowerShell script in a separate process like any other fork/exec/spawn and use stdin/stdout pipes to communicate.

2. Execute your program from PowerShell treating your program as an executable and use stdin/stdout to communicate.

3. Load the dotnet CLR into your process and use the PowerShell SDK to invoke PowerShell scripts/commands within your process

4. Use a dotnet assembly to a shared library using Interop into the PowerShell process and invoke C level API exports from that shared library.

All of those things can be done, and don't need further support from PowerShell itself. I would not recommend either loading complex shared libraries into dotnet unless they were self contained and could execute in their own Assembly Load Context. Likewise, loading the dotnet CLR into another complex foreign process is not for the feint of heart, dotnet has it's own view of the world which is very different to the classic POSIX model, you will end up with contention over resource management within that process.

There is no equivalent ability to convert a PowerShell script into a compiled binary other than writing a dotnet application using the PowerShell SDK and invoking the script, possibly loading as a resource rather than a file. Currently PowerShell SDK does not compile into a single executable. This process would not package dependent modules, you would need to manage that in your app.
