### ISSUE TITLE
0..100 | Add-Member @{a=1} tattoos those integers

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#24565]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The following code adds a note property to a range of integer literals.  That note property is tested for on the same integer literal.  The integer is then output if the note property is present indicating that the integer literal now has the property as a member.  Only integers 0 through 100 end up with that member as a property.  The rest do not.

```PowerShell
$integers = @(
    0..((1 -shl 7)-1) # 0..127

    7..31           | # sparse values up to 32 bits
    % { 1 -shl $_ }
)

$code =
    @( $integers |
       % {"
           $_ | Add-Member @{augmentation='value'}
           if(Get-Member -InputObject $_ -Name augmentation) {$_}"}) -join
     ([System.Environment]::NewLine)

$scriptblock = [scriptblock]::Create($code)

. $scriptblock
```

This leads me to the following questions:

1. What is special about integers 1 through 100 that causes this to happen?
2. Are there other such objects to whose literal or underlying value a property can be added?

### Expected behavior

```console
PS>.\repro.ps1
PS>
```

### Actual behavior

```console
PS>.\repro.ps1
1
2
3
...
100
PS>
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
> What is special about integers 1 through 100 that causes this to happen?

"boxed" copies of those literals in particular are cached in the compiler for performance reasons. This is a weird, but expected, result of that optimization.

> Are there other such objects to whose literal or underlying value a property can be added?

Yeah for sure. Types come to mind, like `[object]`. Not exactly a literal in the same sense, but similar.

**Comment by alx9r** [comment]
@SeeminglyScience Thank you for the reply.

>"boxed" copies of those literals in particular are cached...

By "boxed" do you mean [the C# boxing described here](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/types/boxing-and-unboxing)?

**Comment by SeeminglyScience** [comment]
> By "boxed" do you mean [the C# boxing described here](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/types/boxing-and-unboxing)?

Yep! Also worth referencing [`I.8.2.4` Boxing and unboxing of values](https://github.com/stakx/ecma-335/blob/master/docs/i.8.2.4-boxing-and-unboxing-of-values.md) from the spec ECMA 335 (The link is to an unofficial markdown copy of it because linking to part of a PDF is annoying but [here's the original](https://www.ecma-international.org/wp-content/uploads/ECMA-335_6th_edition_june_2012.pdf)).

**Comment by mklement0** [comment]
Allow me to recycle some advice with respect to attaching instance ETS properties to _value type_ instances, as well as _strings_ (from [this Stack Overflow answer](https://stackoverflow.com/a/77167480/45375)).

---

***Avoid* attaching ETS _instance_ members in the following cases**:

* to **`[string]` instances**, because they require an _invisible `[psobject]` wrapper_ that is _easily lost_, such as during string operations and strongly-typed parameter binding, resulting in loss of the ETS members; e.g.:

```powershell
$s = "hi there"

# Add a .Length2 alias property that refers to .Length
$s = Add-Member -InputObject $s -MemberType AliasProperty -Name Length2 -Value Length -PassThru -Force

# OK: access the property directly on the decorated instance.
$s.Length2 # -> 8, same as $s.Length

# LOSS OF THE PROPERTY due to string operation.
$s = $s -replace '$', '!'
$s.Length2 # !! Property was LOST in the -replace operation.

# LOSS OF THE PROPERTY during strongly typed parameter binding
$s = Add-Member -InputObject $s -MemberType AliasProperty -Name Length2 -Value Length -PassThru -Force
& { param([string] $str) $str.Length2 } $s
```

* to **instances of [*.NET value types*](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-types)** (e.g, `[int]` (`System.Int32`); call `.IsValueType` on a type to check) for similar reasons: they too can be lost during strongly-typed parameter binding _and_, conversely - because PowerShell internally caches `[int]` instances from `0` to `100`, inclusively - can make the ETS member surface unexpectedly when these numbers are used _as literals_.

```powershell
$n = 42

# Add a .Foo instance property of type NoteProperty with value 'Bar'
$n = Add-Member -InputObject $n -MemberType NoteProperty -Name  Foo -Value Bar -PassThru

# OK: access the property directly on the decorated instance.
$n.Foo # -> 'Bar'

# LOSS OF THE PROPERTY during strongly typed parameter binding
& { param([int] $num) $num.Foo } $n

# UNEXPECTED SURFACING OF THE PROPERTY in *integer literals*,
# because the value is between 0 and 100.
[int] $nCopy = 42
$nCopy.Foo # !! -> 'Bar'
```

Note:

* It is the necessity of an invisible `[psobject]` wrapper that requires the use of `-PassThru` in the `Add-Member` calls above, along with _re-assigning the result to the original variable_ (`$s = Add-Member -PassThru -InputObject $s ...`)

* By contrast, this invocation form is _not_ necessary for decorating instance of [.NET *reference types*](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/reference-types) _other than `[string]`_, and such instances aren't affected by the problems above.

**Comment by alx9r** [comment]
Thanks @SeeminglyScience  and @mklement0.  I expect the documentation above is adequate work around this surprising behavior.

**Comment by alx9r** [comment]
Thanks @SeeminglyScience  and @mklement0.  I expect the documentation above is adequate work around this surprising behavior.
