### ISSUE TITLE
Getting deprecated data when using MS Graph

### ISSUE THREAD

**Issue by mwghadsd** [PowerShell/PowerShell#24609]
### Steps to reproduce

- We are trying to get all calendars from a shared mailbox through MS Graph
- When using "Get-MgUserCalendar" from the module Microsoft.Graph.Calendars, we only get deprecated data
- When using "Get-MailboxFolderStatistics" from the module "ExchangeOnlineManagement" to query Exchange Online directly (and not via MS Graph) we get the correct data

### Expected behavior

```console
(Get-MailboxFolderStatistics UserA -FolderScope Calendar | select -ExpandProperty Identity).Count

= 27
```

### Actual behavior

```console
(Get-MgUserCalendar -UserId <Id from UserA> -Top 1000).Count

= 14
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![grafik](https://github.com/user-attachments/assets/c2ad022d-27c5-4b57-a6d5-3ed3c19f3627)

**Comment by mklement0** [comment]
The commands in question aren't being maintained in this repository.

Please follow the guidance in [Can Windows/Non-Core PowerShell 5 bugs be reported here?](https://github.com/PowerShell/PowerShell/discussions/24299) to determine the appropriate place to report your issue.

If you think that the issue is specific to PowerShell 7, after all, because in Windows PowerShell (v5.1) you observe the expected behavior, please elaborate - but note that this assumes that the module in question loads _directly_ in PowerShell 7 (as opposed to via the [Windows Compatibility Feature](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Windows_PowerShell_Compatibility)) and that the difference in behavior isn't already explained by the differences between Windows PowerShell and PowerShell 7 linked to in the initial post.

If you end up creating an issue in the Feedback Hub (on Windows), please share a link to it here.
