### ISSUE TITLE
C:\program files\windowsPowerShell appears to not be included in the PSModulePath

### ISSUE THREAD

**Issue by Tarjei-stavanger** [PowerShell/PowerShell#24603]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

BTW. loading PowerCLI works on PowerShell 5.1.19041.5007.

I am trying to load PowerCLI in Powershell 7.4.6 with the command "`import-module Vmware.powerCLI;`"
The command is failing with the error message :  Import-Module: The specified module 'Vmware.powerCLI' was not loaded because no valid module file was found in any module directory.

After investigating, I found that the path to PowerCLI is not in the PSModulePath for some reason.  However,the x86 version is in the module path.

```
PS C:\Users\myUser>  $env:PSModulePath.split(';');
\\svgkomm.svgdrift.no\Users\sk5042445\Documents\PowerShell\Modules
C:\Program Files\PowerShell\Modules
c:\program files\powershell\7\Modules
C:\Program Files (x86)\WindowsPowerShell\Modules
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin
PS C:\Users\myUser>
```

I think it is a bug that C:\Program Files\WindowsPowerShell\Modules is not part of the PSModulePath by default.

BTW I have not touched this variable. But I will after this.

### Expected behavior

```console
as shown above
```

### Actual behavior

```console
as shown above
```

### Error details

```console
as shown above
```

### Environment data

```powershell
PS C:\Users\MyUser> $psversiontable;

Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
You could look PSModulePath in cmd.exe - it should contain `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`.
pwsh will _enherit_ the values.

**Comment by Tarjei-stavanger** [comment]
BTW I'm using Windows 10 Enterprise currently. I just updated a second Windows 10 machine with 7.4.6.  It still missing the part of the PSModulePath.

![image](https://github.com/user-attachments/assets/a5d1fb2b-9cbc-4350-bd6a-659900570f45)

**Comment by cmkb3** [comment]
Heads up -- domain info in your image.

I still think it's a local config issue. Verify against a non-domain-joined machine -- re: a test VM with a fresh install (default Windows ISO, not a customized deployment image) and no GPOs applied that could be modifying it.

**Comment by Tarjei-stavanger** [comment]
I've done some editing to make the output readable.

```
PS C:> [Environment]::GetEnvironmentVariable('PSModulePath', 'Machine') ?? 'Env Machine is unset'
   C:\Program Files (x86)\WindowsPowerShell\Modules;
   C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;
   C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin;

PS C:> [Environment]::GetEnvironmentVariable('PSModulePath', 'User') ?? 'Env User is unset'
Env User is unset

PS C:> pwsh -NoProfile -Command '$env:PSModulePath'
   \\DomainName\Users\sk5042445\Documents\PowerShell\Modules;
   C:\Program Files\PowerShell\Modules;
   c:\program files\powershell\7\Modules;
   C:\Program Files (x86)\WindowsPowerShell\Modules;
   C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;
   C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin;


PS C:> $machineConfigPath = Join-Path $PSHome 'powershell.config.json'
PS C:> if (Test-Path -LiteralPath $machineConfigPath) {
>>     $machineConfig = Get-Content -LiteralPath $machineConfigPath | ConvertFrom-Json
>>     if ($config.PSModulePath) {
>>         "All Users PSModulePath - $($config.PSModulePath)"
>>     }
>> }
PS C:>
PS C:> $userConfigPath = Join-Path (Split-Path $PROFILE.CurrentUserCurrentHost) 'powershell.config.json'
PS C:> if (Test-Path -LiteralPath $userConfigPath) {
>>     $config = Get-Content -LiteralPath $userConfigPath | ConvertFrom-Json
>>     if ($config.PSModulePath) {
>>         "Current User PSModulePath - $($config.PSModulePath)"
>>     }
>> }
PS C:>
```

**Comment by jborean93** [comment]
The reason for this is because you have a machine scoped `PSModulePath` with

```
PS C:> [Environment]::GetEnvironmentVariable('PSModulePath', 'Machine') ?? 'Env Machine is unset'
   C:\Program Files (x86)\WindowsPowerShell\Modules;
   C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;
   C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin;
```

What happens at startup when there is an existing `PSModulePath` env var set is

+ It starts with `$MyDocuments\PowerShell\Modules`
+ Then adds `$ProgramFiles\PowerShell\Modules`
+ Then adds `$PSHome\Modules` (`$ProgramFiles\PowerShell\7\Modules`)
+ Adds the `User` scoped `PSModulePath` env var if present
+ Adds the `Machine` scoped `PSModulePath` env var if present

In normal cases the `Machine` scoped `PSModulePath` env var has at least the following 2 entries

+ `C:\Program Files\WindowsPowerShell\Modules`
+ `C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`

In your case something has edited that env var to be what you see it is. You'll have to edit it back to change `Program Files (x86)` to just `Program Files` and have it act like expected. At a guess whatever added `C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin` also changed the entry for the `WindowsPowerShell` program files entry.

**Comment by jborean93** [comment]
It's a good thing to point out that, at least on my Windows host, the raw environment value before expansion is

```powershell
$key = Get-Item 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment'
$key.GetValue('PSModulePath', '', 'DoNotExpandEnvironmentNames') -split ';'

%ProgramFiles%\WindowsPowerShell\Modules
%SystemRoot%\system32\WindowsPowerShell\v1.0\Modules
C:\Program Files\WindowsPowerShell\Modules
```

This is why on a 32-bit process it appears with `C:\Program Files (x86)\WindowsPowerShell\Modules` whereas a 64-bit process has `C:\Program Files\WindowsPowerShell\Modules` in the first entry. I'm unsure whether this is the actual default on a fresh new install but I assume it's there so that the process arch and the 64-bit one are always available.

**Comment by mklement0** [comment]
Interesting, @jborean93; on my W11 machine, running a 32-bit _Windows PowerShell_ instance, without having ever modified the definition, your code returns _only_:

```none
%ProgramFiles%\WindowsPowerShell\Modules
%SystemRoot%\system32\WindowsPowerShell\v1.0\Modules
```

However, I haven't installed a 32-bit _PowerShell Core_ instance to see what happens then.

**Comment by jborean93** [comment]
Potentially mine was modified when building the image, I'm honestly unsure and not confident what I have is the default setup for hosts. Still I think this might be straying beyond the problem at hand in that `C:\Program Files\WindowsPowerShell\Modules` doesn't appear in their `PSModulePath` because it's not part of the machine scoped `PSModulePath` that it typically is in some shape or form.

**Comment by Tarjei-stavanger** [comment]
BTW. The installation kit only installs the x64 version of PowerShell 7. The executable in the menues is labelled x64, so it is hard to mistake one for the other.

I tested the PSmodulepath on Windows 11 and it is OK. It is smaller than expected since I'm supposed to get the same stuff. I'm looking into that.

**Comment by Tarjei-stavanger** [comment]
I got hold of a third PC with Windows 10 and it has the correct PSModulePath. 

I agree with the suggestion from **jborean93**.  Some of the other software installed on my two previous Windows 10 PCs messes up the PSModulePath.

Thank you all very much for your help in determining what has happended!

**Comment by mklement0** [comment]
Glad to hear it, @Tarjei-stavanger.

I'm mentioning the following only as an aside, given that this would require a separate issue, but I don't feel inspired to go down that rabbit hole:

* The 32-bit versions of both PowerShell editions - surprisingly - expand `%ProgramFiles%` references in the `REG_EXPAND_SZ` registry value (defining the persistent, machine-scope value of `PSModulePath`) _as if they were 64-bit values_, i.e. typically as `C:\Program Files` rather than as the 32-bit-appropriate `C:\Program Files (x86)` (which is what the .NET APIs would do).

* Not sure if this is by design, and, glancing at the source code, it's also not obvious to me _where_ that happens.

**Comment by jborean93** [comment]
> The 32-bit versions of both PowerShell editions - surprisingly - expand %ProgramFiles% references in the REG_EXPAND_SZ registry value (defining the persistent, machine-scope value of PSModulePath) as if they were 64-bit values, i.e. typically as C:\Program Files rather than as the 32-bit-appropriate C:\Program Files (x86) (which is what the .NET APIs would do).

I do not see that as in https://github.com/PowerShell/PowerShell/issues/24603#issuecomment-2487172276 unless I’m misreading what you are saying.

PowerShell doesn’t do any conversion on getting the env vars, it just expands it using the .NET function.

**Comment by mklement0** [comment]
@jborean93, all I can say is that _in practice_ the `%ProgramFiles%`-based entries end up expanded as `C:\Program Files` in the 32-bit versions - if you're interested enough, I encourage you to (a) verify that assertion yourself (add, say, `%ProgramFiles%\foo` to the registry value and see what it gets reported as in `$env:PSModulePath` in a 32-bit version) and (b), assuming you find my claim to be true, weigh in on _why_ this is happening and what the _design rationale_ may be.

**Comment by jborean93** [comment]
I stand corrected, I thought I tested it out yesterday and saw the correct `x86` path but trying again today it's not there. I'll have to dig into it to see what is happening.

**Comment by jborean93** [comment]
You can also see the raw process env var before PowerShell goes to process the extra settings and see the inheritance in action

![image](https://github.com/user-attachments/assets/5605c3d8-e081-446e-bdfc-5bd22bcc3cb2)

**Comment by mklement0** [comment]
> if spawned from a 64-bit process

Indeed, that was the piece I missed - thank you for clearing that up.

Pragmatically speaking, the upshot is:

* The _usual_ methods of starting a 32-bit process on 64-bit systems are _mediated by a 64-bit process_ (e.g., starting the 32-bit process from a 64-bit shell, or using <kbd>WinKey+R</kbd> to launch a process), meaning that the inheritance you're describing _does_ apply by default.

* _Avoiding_ this inheritance requires a deliberate effort to _disregard the caller's environment_, such as using `Start-Process -UseNewEnviroment` - which, as a side effect, may result in ignoring env. vars. whose preservation is _desirable_.

**Comment by Tarjei-stavanger** [comment]
BTW.

`%programfiles%` is a standard environment variable. So is also `%programfiles(x86)%`. They expand to their respective folders.

So, the expansion is not much of a surprise.

**Comment by mklement0** [comment]
@Tarjei-stavanger,  what `%ProgramFiles%` expands to _depends on the bitness of the process_: it expands to (typically) `C:\ProgramFiles (x86)` in a 32-bit process (on a 64-bit system) and `C:\ProgramFiles` in a 64-bit process.

By contrast, (on 64-bit systems) `%ProgramFiles(x86)%` expands bitness-independently to `C:\ProgramFiles (x86)`.

As Jordan has demonstrated, a 32-bit process still sees `C:\ProgramFiles` in the values of environment variables defined as `REG_EXPAND_SZ` that reference `%ProgramFiles%` _if it inherited its environment from a 64-bit process_ (as the latter then performed the original expansion and passed the value on).
