### ISSUE TITLE
Add 7zip and rar support to the -Archive cmdlets

### ISSUE THREAD

**Issue by AdreKiseque** [PowerShell/PowerShell#24614]
### Summary of the new feature / enhancement

With 24H2 adding native support for the 7zip and rar formats, it only makes sense for PowerShell to be able to natively make use of that functionality and provide a way to interact with those formats through the command line. New cmdlets could be added, but it seems more reasonable to simply update the existing commands for working with zip files to also work with these.

**Comment by jborean93** [comment]
The cmdlets live at https://github.com/PowerShell/Microsoft.PowerShell.Archive so this issue needs to be filed there. The repo is currently archived because the pwsh team don’t have any current plans on updating it so even raising an issue won’t really lead anywhere.

Your best bet is to hope someone creates a custom module which adds support for it.

**Comment by MatejKafka** [comment]
PowerShell is cross-platform now, so it would probably have to support both even on Linux/Mac. I agree it would be a nice-to-have feature, but the engineering effort is pretty high – afaik, the current `Expand-Archive` implementation uses the .NET Zip API, which does not support other archive formats, so adding support for other formats would require a ground-up rewrite, and a dependency on a native library such as libarchive.

**Comment by AdreKiseque** [comment]
@MatejKafka Hm, I guess it could be a lot of work to get it implemented whilst keeping it tidy and such, yeah. I'd certainly imagine there are certain standards to the implementations of code that gets added to PowerShell.

@jborean93 That's interesting, thanks for letting me know.
