### ISSUE TITLE
Add -Top parameter to Sort-Object

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#2462]
As per the discussion on pull request #2446 that I recently closed, it would be very useful to have a -Top parameter on Sort-Object. This parameter would allow users to indicate they only want the top N results from their sort. The original pull request I referenced tried to address the need for -Top by adding -Top and -Bottom parameter aliases to Select-Object, but as @lzybkr pointed out, it makes more sense to have a new -Top parameter (not alias) on Sort-Object instead since Top implies sorting.

This issue should be marked as Issue-Enhancement and I would like it to be assigned to me as I have already started work on it. See the discussion on #2446 for details.

The current syntax of Sort-Object is as follows:

```
Sort-Object [[-Property] <Object[]>] [-Descending] [-Unique] [-InputObject <psobject>]
[-Culture <string>] [-CaseSensitive] [<CommonParameters>]
```

The new syntax I would like to propose is as follows:

```
Sort-Object [[-Property] <Object[]>] [-Descending] [-Unique] [-Top <int>] [-InputObject <psobject>]
[-Culture <string>] [-CaseSensitive] [<CommonParameters>]
```

This design approach avoids making assumptions about what -Top means in a given data set, requiring users to control what is top by using the -Descending parameter (e.g. in some data sets, the top items may be the lowest values in the set, such as priority, while in others, the top items may be the highest values in the set, such as workingset64). I believe this is really the only syntax that makes sense for this cmdlet.

**Comment by iSazonov** [comment]
@KirkMunro Thanks for the offer!
You skip **Bottom** parameter. It cannot be replaced by a Top + Descending.
```powershell
1,2,3,4,5,6,7,8,9 | Sort-Object -Top 2
1
2

1,2,3,4,5,6,7,8,9 | Sort-Object -Top 2 -Descending
9
8

1,2,3,4,5,6,7,8,9 | Sort-Object -Bottom 2
8
9

1,2,3,4,5,6,7,8,9 | Sort-Object -Bottom 2  -Descending
2
1
```

**Comment by KirkMunro** [comment]
@iSazonov Ok, you're right, there are some sorts that can't be done without a -Bottom parameter, and for those cases with my proposal you would have to use Select-Object to get those results.

The question I need to ask before I would add -Bottom to this enhancement as well is: does it matter?

I don't think it does, which I think is why I felt -Top N covered all of the use cases. In Select-Object, -First and -Last are both needed and there are use cases for both parameters (e.g. $path -split '\\' | select -last 2). In sorted data, there isn't really such a need. I believe that's why in modern SQL servers, they don't have a bottom N command. Instead they suggest using a top N -Descending sort (e.g. http://stackoverflow.com/questions/1876606/how-to-select-bottom-most-rows).

Further, adding -Bottom would require an additional parameter set in Sort-Object, which is trivial to implement but adds complexity that should be avoided unless it's really necessary. I don't believe it should be added just for completeness if the recommendation for people looking for bottom N would most likely be to use -Top N -Descending instead. If someone can demonstrate a real-world use case where -Bottom N would be useful in PowerShell, then I'll happily include it here. I don't think there is such a use case, but feel free to prove me wrong.

**Comment by iSazonov** [comment]
The -Bottom parameter can be replaced by select-object -Last as the -Top parameter can be replaced by select-object -First. Therefore, this Issue is not critically necessary change. But here we are only talking about Sort-Object and should forget about Select-Object. Let's consider only the Sort-Object UX.
If we consider the sort-object as a whole then saying 'Top' we should say 'Bottom'.
I do not see any difficulties to do Top and Bottom because the sort-object is already doing "sorted-array" as result and we can only add sorted-array[1..Top] or sorted-array[length-Bottom..length].

Sample:
`dir filelogs | sort-object -Property createddate -Desc | Select-Object -First 10 | Sort-Object  -Property createddate | "process last logs in history order"`

New UX:
`dir filelogs | sort-object -Property createddate -Bottom 10 | "process last logs in history order"`

Otherwise I have to:
`dir filelogs | sort-object -Property createddate -Top 10 -Desc | Sort-Object  -Property createddate | "process last logs in history order"`

Moreover I can:
`dir filelogs | sort-object -Property createddate  | Select-Object -Last 10 | "process last logs in history order"`

Top removes one operator, the Bottom also removes one operator. The absence of Bottom leading to +1 operator. Why should we exclude Bottom? The full symmetry!

**Comment by KirkMunro** [comment]
For the last two examples you provided @iSazonov, I wouldn't sort the sorted data because you already know the data is sorted and you just want to reverse it. Instead I would just store the results in an array and then:
```
foreach ($item in $results[-1..-$results.Length]) {
    ....
}
```
(or I would just call .reverse() on the array if I was using TypePx).

Internally if I was to implement bottom, this is exactly what bottom would do: invoke top with the appropriate value for -descending and then return the reversed results.

Anyhow, I have reached out to @lzybkr for comment so that I can get his perspective as well since I'm still a little concerned with adding a second parameter set to Sort-Object unless it's really necessary.

**Comment by lzybkr** [comment]
Some very quick comments before I disappear for a week.

I'm ambivalent about `-Bottom` vs. reversing w/ `-Descending`. I do think `-Bottom` is a good example of why we proposed mutually exclusive parameters in a parameter set.

If I say - give me the least ..., I probably do want `-Top -Descending` order, not `-Bottom` order, so maybe maybe I'm leaning towards not needing `-Bottom`.

**Comment by vors** [comment]
I see pros and cons in both approaches

### Why `-Bottom`

* Symmetry as @iSazonov pointed out. I like it too.
* In my opinion, the main use-case for `-Top` is not to avoid one extra `| Select-Object -First`, but to avoid the performance cost that is associated with piping a big amount of objects. Hence introducing more piping in the `-Bottom` case compare to `-Top` case is undesirable and `-Bottom` should be it's own parameter
* `Sort -Top 10 -Descending | Sort` (or equivalent) is kind of ugly and hard to read. Maybe if we introduce a `Reverse-Object` at the same time as one of the core cmdlets, it would be fine.

### Why not `-Bottom`
* These parameters are mutually exclusive and adding both of them multiplies the parameter sets count by 2. In this case, I think it's acceptable. There is only 1 parameter set currently.
* Introducing `-Bottom` will make parameter sets asymmetrical: there should be an optional named parameter `Top` and mandatory named parameter `Bottom` in non-default parameter set. Asymmetry!

### Summary
I'm almost ambivalent with a slight preference toward including `-Bottom` or not adding it, but adding `Reverse-Object` at the same time.

**Comment by iSazonov** [comment]
@vors  Reverse-Object  is an interesting direction. I don't like this because with the end user's point of view it is another new cmdlet  in addition to **thousands** of other already existing in the (Windows) system. Users are well aware of Sort-Object, they will look for opportunities just inside it and ignore the new cmdlet. 
Top and Bottom are symmetry for end users. Its good UX. And users don't think about any asymmetry or problems within internal code.

@lzybkr Without Bottom, we will deprive users of one case. This is rare, but it will be bad for UX. We add Top to exclude excessive pipeline, but still leave one case... This is annoying.

**Comment by iSazonov** [comment]
Need to close the Issue. @PowerShellTeam
