### ISSUE TITLE
Cannot run wsl -d when remote by Enter-PSSession

### ISSUE THREAD

**Issue by LiuZHolmes** [PowerShell/PowerShell#24642]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Remote to a Windows by Enter-PSSession
2. Run wsl -d to enter the VM in remote pc

### Expected behavior

```console
Enter the shell of remote pc vm
```

### Actual behavior

```console
PS > wsl -d podman-machine-default
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
Unfortunately this is expected. While `Enter-PSSession` creates an interactive session for the target host it is done so through the PSRemoting protocol and not the traditional console/stdio interactive session you would expect from a tool like `ssh`. A PSRemoting session has no ability to run native executables that rely on console interaction, it can only run an executable and read the output data. Because `wsl -d ...` is running an executable and trying to take over the console handles which are not present it will fail.

There is nothing you can do here except

+ Use something else for creating an interactive remote session like `ssh`
+ Run `wsl.exe` as a non-interactive command, for example have it run the command you want to in wsl

**Comment by LiuZHolmes** [comment]
Thank you! I will leave my temp solution here for reference since I am not going to use ssh:
You can run command like
`wsl -d podman-machine-default -- bash -c "your command"`

**Comment by kasini3000** [comment]
老刘：
win2win by winrm，就用kasini3000。搜所引擎搜：kasini3000

#win被控机上，又安装了wsl：
powershell v5 命令行即可。也支持ps v7。
$被控机上结果返回到了主控机 = ./k_run_ip -ip '这里写win被控机ip'   { 
wsl -d 'win被控机中的-wsl-linux虚拟机名' -- bash -c "uname -a"
}
