### ISSUE TITLE
Enhancement request: Get-ItemProperty should return value type for registry items

### ISSUE THREAD

**Issue by bcdady** [PowerShell/PowerShell#2514]
This is a copy of Get-ItemProperty in registry should return value type. - by Bartek Bielawski, as logged to connect.microsoft.com 12/19/2010 1:51:48 PM
https://connect.microsoft.com/PowerShell/feedback/details/632464/get-itemproperty-in-registry-should-return-value-type

I haven't yet tested on the latest WMF 5, but these symptoms are consistent on WMF 3 and 4.

If it's not a bug, please remove the template and elaborate the issue in your own words.
## Expected behavior

PS .> Get-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\SecurityPr
oviders\SCHANNEL\Protocols\SSL 3.0\Client" -Name 'Enabled'

Enabled      : 0
PropertyType : Microsoft.PowerShell.Core\Registry::DWORD
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL3.0\Client
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL3.0
PSChildName  : Client
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry
## Actual behavior

Enabled      : 0
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL3.0\Client
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL3.0
PSChildName  : Client
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry
## Environment data

``` powershell
> $PSVersionTable

PS .\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

**Comment by iSazonov** [comment]
@bcdady Thanks for open the Issue.

Need more information why it causes problem because there is an easy way to find out the type of object:
```powershell
$a=Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer" -Name 'ErrorControl'
$a

ErrorControl : 1
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanServer
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services
PSChildName  : LanmanServer
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry

$a.ErrorControl.gettype()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Int32                                    System.ValueType


```

**Comment by charleswj** [comment]
@bcdady's suggestion does work since a REG_DWORD value of 0x2 will return as 2, and gettype() will then show it as an int. Additionally, int isn't even a registry value type.

**Comment by mklement0** [comment]
`Get-ItemProperty` with the registry provider not including information about the underlying registry-value data type (corresponding to `REG_*` values in the Windows API and .NET `[Microsoft.Win32.RegistryValueKind]`) in the custom object it returns is indeed a curious omission.

(On a side note, that the actual _data_ is returned via a _variably named_ property named for the _registry value_ rather than via a _fixed_ property name such as `.Data` is a curious choice as well; it is what may have inspired the addition of cmdlet `Get-ItemPropertyValue` in v5, which returns the _data_ (value) only.)

The cumbersome **workaround** is to use `Get-Item` instead and call the `.GetValueKind()` method on the resulting `[Microsoft.Win32.RegistryKey]` instance, which yields a `[Microsoft.Win32.RegistryValueKind]` enumeration value:

```powershell
# Get the data type of HKEY_CURRENT_USER\Console\ScreenBufferSize
> (Get-Item HKCU:\Console).GetValueKind('ScreenBufferSize')
DWord 
```

Given the above, if a new property is introduced, perhaps it should be named `.ValueKind` and return a `[Microsoft.Win32.RegistryValueKind]` enumeration value (while possibly also adding a `.Data` property to reflect the actual data in a property with a _fixed_ name; naming the property `.Value` is also an option, but perhaps confusing from a terminology standpoint).
