### ISSUE TITLE
Import Custom Powershell Modules in Linux and OSX

### ISSUE THREAD

**Issue by kktam** [PowerShell/PowerShell#2553]
Requesting if current Powershell release has capability of importing custom powershell modules into Linux and OSX, and create documentation on how to do this (as compared to Windows , any similarity or difference).

If this feature is not currently available, is there any plan to include it, in any of the future release?

**Comment by vors** [comment]
Hi @kktam 

It's exactly the same as on windows: `Import-Module <name>` or `Import-Module <path>`. Did you have problems with import?
It's worth mentioning that not all modules are compatible with linux. It's mostly because of the differences between FullCLR and CoreCLR, but also due to the platform specific things: i.e. case-sensitive file-system, no registry, etc.
