### ISSUE TITLE
Mark PR for future documentation

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#2566]
Some PR require not only updating the changelog, but also a documentation. For example #2506.

Maybe mark such PR by new label (`Doc-Needed`)?

**Comment by lzybkr** [comment]
Starting with the changelog, it's relatively easy to decide what needs documentation updates, right

In other words, maybe a label is useful, but the changelog might be simpler to maintain than labels.

**Comment by iSazonov** [comment]
My thought was about the _comfort of GitHub filter to find the PRs_, say half a year later, when we will change documentation. (All the more so because the changelog does not contain numbers of PRs).
I would like to clarify the purpose of `Changelog Needed`. If we need to make changes in the changelog, we set the label. After changing log we need to close the process and change the label to another `Changelog Done`.
Hence the need other tags for documenting `Doc-Needed`, `Doc-Fixed`.
If PG uses this label `Changelog Needed` for all of this, then of course the new tags are not needed. But it is not very convenient to search as I mentioned above.

**Comment by joeyaiello** [comment]
The original intent of our [pull request process](https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/pull-request-process.md) was to require that documentation changes were made as part of the pull request. Unfortunately, our docs exist in another repo, PowerShell/PowerShell-Docs, and the docset for 6.0 isn't yet there. 

I'm working with @JuanPabloJofre to spin up a 6.0 docset [here](https://github.com/PowerShell/PowerShell-Docs/tree/staging/reference) so that we can enforce this requirement.

**Comment by joeyaiello** [comment]
I've added the requirement to add docs when necessary in the PR, we might still need a label. Input anyone?

**Comment by SteveL-MSFT** [comment]
`Documentation Needed` label was added
