### ISSUE TITLE
Get to single Windows package

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#2608]
We should have a single Windows package for all supported platforms

**Comment by mirichmo** [comment]
For each supported architecture; the way CoreCLR does it.

**Comment by SteveL-MSFT** [comment]
Yes, x86 x64, etc..., but we shouldn't have win8.1 win10, etc...

**Comment by DarwinJS** [comment]
Actually, due to the way the "64-bit enabled" "switch" works in MSI you *must* have two installers to support both bitnesses.  At least that's what it says in this book: https://smile.amazon.com/Deploying-Supporting-Applications-64-bit-Windows-ebook/dp/B0098P9Z22/  ;)

However, like a setup.exe wrapped around a 32-bit and 64-bit MSI, the chocolatey package will be able to sort out bitness specific installers automatically.

Since the existing MSI simply copies files, it is ok if the chocolatey package just installs one of them for both win 8 and win 10 ?

**Comment by joeyaiello** [comment]
@DarwinJS I think you're agreeing with @SteveL-MSFT and @mirichmo on this one: we should have a universal installer for each bitness (so two total).

**Comment by DarwinJS** [comment]
@joeyaiello I am actually pointing out that when the installation technology is MSI - you don't have any other choice than to do it per-bitness.

However, even if you did setup.exe, probably still best to have 2 because the only way to make one is to make the kicker 32-bit and Nano and many installations of Server Core won't have the 32-bit subsystem installed.

FYI - chocolatey handles the switch between bitness specific installers transparently.

**Comment by joeyaiello** [comment]
I think this is dependent on #3747

**Comment by mirichmo** [comment]
Yes, it is now

**Comment by SteveL-MSFT** [comment]
We should do the same as https://github.com/PowerShell/PowerShell/issues/3961 which is to have a package with all dependencies

**Comment by daxian-dbw** [comment]
I think now this issue depends on #4665. I will leave this issue open and let @mirichmo and @adityapatwardhan decide when this should be closed.

**Comment by adityapatwardhan** [comment]
@daxian-dbw Can we close this issue? Both #4665 and #4315 are closed now?

**Comment by daxian-dbw** [comment]
@adityapatwardhan Sure, closed.
