### ISSUE TITLE
Send-MailMessage throw error and send the email

### ISSUE THREAD

**Issue by EliadTech** [PowerShell/PowerShell#2646]
Steps to reproduce
------------------
Run Send-MailMessage with CC or BCC, but without TO, and with BodyAsHTML.

Expected behavior
-----------------
Either throw error and break (because TO is empty) or send the email (to CC or BCC) without an error.

Actual behavior
---------------
You get an error that the email address is invalid and the email is sent but empty.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.0.9740.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34014
BuildVersion                   6.3.9740.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.2

```

**Comment by SteveL-MSFT** [comment]
Just tried this on PS5.1 and can't replicate as TO cannot be empty

```powershell
PS C:\Users\slee\repos\PowerShell> Send-MailMessage -Cc foo@bar.com -BodyAsHtml

cmdlet Send-MailMessage at command pipeline position 1
Supply values for the following parameters:
From: test@test.com
Subject: test
To[0]:
Send-MailMessage : Cannot validate argument on parameter 'To'. The argument is null, empty, or an element of the
argument collection contains a null value. Supply a collection that does not contain any null values and then try the
command again.
At line:1 char:1
+ Send-MailMessage -Cc foo@bar.com -BodyAsHtml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Send-MailMessage], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.SendMailMessage
```

**Comment by EliadTech** [comment]
That's because you left BodyAsHtml empty.
I've just tested it again on PS 5.1.

**Comment by dayroncj** [comment]
For future readers...

The error is because "-To" parameter cant be null or empty.  If the intend is to use "-Bcc" rather "-To", you can use a dummy email address like 'noreply@noreply.com' and set the "-Bcc" paramter with all the recipients.

For last, -BodyAsHtml is a boolean parameter thus no value is neccesary.

**Comment by ThreeFive-O** [comment]
To summarize the issue:
The cmdlet was used in a wrong way where the Boolean switch `-BodyAsHtml` was used in a similar fashion like `-Body`.
Since the switch `-BodyAsHtml` takes no input object, the positional parameters kicks in. As all other parameters are named, the first positional parameter will be `-To`.
Hence the provided sample call
```powershell
Send-MailMessage -Cc foo@bar.com -BodyAsHtml 'Blablabla' -smtpserver exchange.bar.com -subject test -from tester@bar.com
```
could be written as
```powershell
Send-MailMessage -Cc foo@bar.com -BodyAsHtml -To 'Blablabla' -smtpserver exchange.bar.com -subject test -from tester@bar.com
```

Input 'Blablabla' can be bound to parameter `-To` as it is of type string. No problem occurs during binding. 
Later the string values for `-To`,`-Cc` and `-Bcc` are checked for correct format. This happens in the following lines of code in `Send-MailMessage`:

https://github.com/PowerShell/PowerShell/blob/1abf290f839f766400a64ddd8b853709489c8aa5/src/Microsoft.PowerShell.Commands.Utility/commands/utility/Send-MailMessage.cs#L286-L319

It can be seen that in Line 315 an error is written, but the cmdlet won't terminate because of this error.

Ultimately the mail will be sent, though the "To" member of the `_mMailMessage` object is empty.

Possible solutions:

1. Make cmdlet parameters for `-To`,`-Cc` and `-Bcc` of type `System.Net.Mail.MailAddress`. This would perform a format check right away and abort the action if not all provided mail addresses are valid.
This definitely would be a breaking change, since the current behavior allows invalid mail addresses to be specified, where PS will provide an error, but the mail could still be sent to all other addresses.
This current behavior can be convenient if you have a list of mail addresses, but at least one mail address is not in the correct format, e.g.
```powershell

**Comment by adityapatwardhan** [comment]
@ThreeFive-O Thanks for the detailed analysis. Can this issue be closed since, the cmdlet is behaving as expected?

**Comment by ThreeFive-O** [comment]
@adityapatwardhan In my opinion this issue can be closed. But another issue or PR should be made to improve the user experience when using non-valid email addresses in `-To`, `-Cc` and `-Bcc`.
It's on my To-Do, but other PRs for this cmdlet are more important, which I want to fix first.
