### ISSUE TITLE
New-Object : Unable to load DLL 'api-ms-win-core-com-l1-1-0.dll': The specified module could not be found.  (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by jonathannarzo** [PowerShell/PowerShell#2706]
New-Object : Unable to load DLL 'api-ms-win-core-com-l1-1-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
**Ubuntu 14.04**
**Sample code:**
```
$Folder = '/home/FolderName/SubFolderName'
$File = 'videofile.mp4'
$LengthColumn = 27
$objShell = New-Object -ComObject Shell.Application
$objFolder = $objShell.Namespace($Folder)
$objFile = $objFolder.ParseName($File)
$Length = $objFolder.GetDetailsOf($objFile, $LengthColumn)
Write-Output $Length
```

**Comment by JeremyBidet** [comment]
Hello everybody, i am encountering the same issue.
I need to convert some old PDF files (encoded with word 2006 .xml schema) as PDF.
I already used PowerShell and ComObject to do this on a Windows system with :

```ps
$word = New-Object -ComObject Word.Application
$word.Documents.Open(filename).SaveAs(pdf_filename, 17)
```

but now I have to automate this process on a Linux system (every XML files are generated onto).
PowerShell on Linux able to me to use these commands but not ComObject due to a missing of api-ms-win-core-com-l1-1-0.dll

Is there any way to load this dll into a Linux system ?

**Comment by SteveL-MSFT** [comment]
Unfortunately, COM is not supported on non-Windows, so this dll is not sufficient to get it working
