### ISSUE TITLE
Get-Process $pid should suggest using -Id $pid

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#2722]
The default parameter set for `Get-Process` accepts `-Name` by position.

Maybe it's just me, but I forget this all the time, and expect `Get-Process 1234` to work.

I think we can make it work in a reasonable way too. If Name is a positive integer and we do not find a process by that name, search again assuming it was a ProcessId.

Edit: instead of making this work (which might not be a good idea always) - I like the suggestion from @rkeithhill to give a better error message.

**Comment by iSazonov** [comment]
It's unbelievable but user can actually catching process with **name** `1234` and actually get a process with **Pid** `1234`. It's bad.

**Comment by lzybkr** [comment]
Right, if finding the process by name fails, only then look by id. Is that not safe and reasonable?

**Comment by powercode** [comment]
I think he means that there is a risk that I have been really clever and created 
1234.exe.

It is not running, but when I do 
```
Get-Process 1234 | Stop-Process
```
I kill MySuperimportantProcess.exe, with pid 1234.

**Comment by powercode** [comment]
Maybe there should be a defaulted parameterset NameOrID with this behavior, so that you can specify -Name or -ID and _only_ get by name or by id.

**Comment by rkeithhill** [comment]
> Maybe there should be a defaulted parameterset NameOrID 

That won't help if the arg is specified by position but at least it A) gives a way to specify that you really want to match *just* by name and B) gives a more correct name for the parameter.  

Conceivably this could be a breaking change if a script does not use the `-Name` parameter and there just happens to be a process with a name that corresponds to a PID you want Stop (or otherwise interrogate).   That said, it is pretty uncommon to run across processes' with a name that parses as a integer.  And the workaround is simple - use the `-Name` parameter.  I'd be willing to risk the back compat issue for the convenience provided.

BTW why not give `Stop-Process` the same treatment?  Make a new NameOrId parameter and make it the default parameterset.  It annoys me that GPS defaults to name but SPPS defaults to PID.  I'm always forgetting to specify the -Name parameter to Stop-Process when I want to stop all instances of an app.

**Comment by SteveL-MSFT** [comment]
The risk is similar to the discussion the committee had with (RFC0011)[https://github.com/PowerShell/PowerShell-RFC/blob/master/1-Draft/RFC0011-Dot-Referencing-With-Static-Integers.md] where files named as integers can produce unexpected results.  Perhaps a safe middle ground might be to just tell the user that a process with name 1234 wasn't found and that they should try `get-process -pid 1234`

**Comment by iSazonov** [comment]
Based on the above. This is absolutely unacceptable in the script. 
And looks very tasty for user input but really requires of informing the user. 
I think it makes no sense to do this for a _single_ cmdlet. Let's try to generalize the situation. This is an area of parameter binding. We now offer an alternative parameters before the input of a value, and here we need to offer alternatives after the input of a value (insert a parameter name before the value by tab). Is it possible to do this?

**Comment by lzybkr** [comment]
This dovetails nicely into the parameter alias discussion in #2199.

If a user can extend the parameter metadata for other commands, they can add aliases or even an `ArgumentTransformationAttribute`, which would solve this problem nicely without explicitly opting into the potentially destructive and possibly surprising behavior that I'd like.

**Comment by rkeithhill** [comment]
Regardless of the outcome here, I'd love to see more PowerShell cmdlets do this:
> ... tell the user that a process with name 1234 wasn't found and that they should try get-process -pid 1234

I like it when I get that sort of helpful message on Ubuntu e.g. when I run a command that isn't available, Ubuntu tells how to install that command with `apt-get`.

**Comment by powercode** [comment]
How about something like this?

```
PS> get-process 19432

Confirm
Are you sure you want to perform this action?
Performing the operation "The process with name '19432' was not found but devenv (19432) was found. Continue?" on target "devenv (19432)".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
   4860     641  1841044    1036488   3 789,36  19432   1 devenv
```

**Comment by iSazonov** [comment]
Looks good, if it only is in interactive mode but not in script.

**Comment by KirkMunro** [comment]
This reminds me of Get-Service.  Get-Service has -Name and -DisplayName in different parameter sets, yet you can use either when you use the -Name field.

e.g.
```
Get-Service wuauserv
Get-Service 'Windows Update'
```

I agree with @lzybkr's original issue, and wish Get-Process worked this way as well because it would be very convienient; however, in this case I would be satisfied with a shorthand alternative made capable via parameter alias modification or if PowerShell just included a function like this by default for ad-hoc use since looking up the current process by id is a relatively common task:
```
function pid {
    [CmdletBinding()]
    [OutputType([System.Diagnostics.Process])]
    param()
    Get-Process -Id $pid
}
```

It's nice and easy to remember too.

**Comment by KirkMunro** [comment]
Just to add to this, where this particular issue drives me the most is that Stop-Process uses a default parameter set that requires Id rather than name.  I *always* try something like this first:

```
spps *edge*
```

Then I _sigh_, then I re-run the command, explicitly using the -Name parameter.

I would much prefer if this set of commands simply had a consistent rule among them that made ad-hoc use more palatable.

**Comment by lzybkr** [comment]
I'm convinced that the default behavior should not be changed, but I'm leaving this open until we have a better error message than `Cannot find a process with the name "1234"`.

**Comment by rkeithhill** [comment]
Agreed. At the very least, the error message could say `Cannont find a process with the name "1234".  If 1234 is a process Id, use Get-Process -Id 1234.`  Of course, you would only use **that** error message with the Name parameter value is all digits.

**Comment by lzybkr** [comment]
Note that #2199 might as well be the issue to cover customizing parameter metadata.

**Comment by MohiTheFish** [comment]
I am working on this with @TylerLeonhardt  and @rjmholt  at HackIllinois 2019. Here is the PR: https://github.com/PowerShell/PowerShell/pull/8959

**Comment by KirkMunro** [comment]
If `Get-Process` and `Stop-Process` were both changed to have their parameter sets designed like Debug-Process and Wait-Process, where the Name and Id parameters are positional, wouldn't that resolve this problem entirely while making -Process cmdlets consistent in design without introducing breaking changes?

i.e. Today these work:

```
Get-Process pwsh
Stop-Process $pid
```

and these don't:

```
Get-Process $pid
Stop-Process pwsh
```

If both `Get-Process` and `Stop-Process` had positional Id and Name parameters, respectively, wouldn't that make both scenarios work without breaking existing scripts that use positional parameters? I think it would at least resolve the `Stop-Process` issue without issue, since strings would be automatically mapped to the Name parameter set. I haven't thought all of the paths for this through, and I have my head half paying attention to a debugger right now, but it seems like a possible solution for this.

**Comment by iSazonov** [comment]
@KirkMunro As discussed above user can fool himself typing without quotes `Stop-Process 1234` and kill process with pid 1234 instead of process with name 1234.

**Comment by KirkMunro** [comment]
Too bad, makes for annoying parameter sets.

**Comment by SteveL-MSFT** [comment]
We could add something to the suggestion framework when a process named `1234` doesn't exist and suggest using the pid if the value is numerical.

**Comment by iSazonov** [comment]
I wonder - what can this system return better than the current message?

**Comment by SteveL-MSFT** [comment]
@iSazonov Current error looks like:

```none
get-process : Cannot find a process with the name "1234". Verify the process name and call the cmdlet again.
At line:1 char:1
+ get-process 1234
+ ~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (1234:String) [Get-Process], ProcessCommandException
+ FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.Commands.GetProcessCommand
```

It could look like:

```none
get-process : Cannot find a process with the name "1234". Verify the process name and call the cmdlet again.
At line:1 char:1
+ get-process 1234
+ ~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (1234:String) [Get-Process], ProcessCommandException
+ FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.Commands.GetProcessCommand

Suggestion: Did you mean: Get-Process -id 1234 ?
```

**Comment by iSazonov** [comment]
For clarify, now the error measseage is "Cannot find a process with the name "{0}". Try running with -Id to search by Id of processes"
