### ISSUE TITLE
Rewrite Get-FileHash on C#

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#2731]
As approved in #2718  Get-FileHash should be rewritten on C#.

**Comment by rkeithhill** [comment]
BTW, any chance we could add a Get-Hash command as well that would operate on strings instead of files?  This comes in handy.  See the PSCX impl for[ Get-Hash ](https://github.com/Pscx/Pscx/blob/master/Src/Pscx/Commands/IO/GetHashCommand.cs)as an example.  Of course, if I were writing this command from scratch today, I would default to SHA256 instead of MD5.  :-)

**Comment by iSazonov** [comment]
> default to SHA256 instead of MD5

I agree but 
Is this a breaking change or not?

**Comment by rkeithhill** [comment]
`Get-Hash` doesn't exist right now so no worries about a breaking change.  And the default Algorithm for `Get-FileHash` is SHA256.  My only point is that it would be nice to have a cmdlet that hashes strings instead of files.  

It is a drag that if you want to hash a string, you have to write it to a file.  OK that is not entirely true, you *can* hash a string directly but not many folks will figure this out:
```powershell
Get-FileHash -InputStream ([System.IO.MemoryStream]::new([System.Text.Encoding]::ASCII.GetBytes("open sesame")))
```

**Comment by iSazonov** [comment]
@rkeithhill Great idea! 
So maybe make new `Get-Hash` cmdlet with support file and string sources and make `Get-FileHash` as wrapper for it?

**Comment by iSazonov** [comment]
@PowerShellTeam I started working on this, please assign me.
