### ISSUE TITLE
Get-Service cmdlets needs a Credential parameter

### ISSUE THREAD

**Issue by lw-schick** [PowerShell/PowerShell#2761]
> The Get-Service cmdlet has a Computername parameter in v2, but without support for supplying credentials, this is of limited use in non-domain or cross-domain scenarios. Please add a Credentials parameter that works similarly to the one on Get-WMIObject

Copied from https://connect.microsoft.com/PowerShell/feedback/details/567007/get-service-cmdlets-needs-a-credential-parameter

I really would like to have this feature!

**Comment by SteveL-MSFT** [comment]
Rather than add more remoting parameters, maybe this is the issue where we discuss having cmdlets that support -computername use PSRP instead of .net remoting.  Alternatively, perhaps we should deprecate -computername and recommend use of invoke-command instead of having partial remoting support in some cmdlets and not others.

**Comment by SteveL-MSFT** [comment]
Get-Process is another cmdlet where .Net remoting causes user confusion as some properties are not supported remotely.  Using PSRP would solve that problem.

**Comment by ThomasNieto** [comment]
Do we need this issue open anymore since PS 7.1 does not have `-ComputerName` parameter anymore?

**Comment by ThomasNieto** [comment]
@iSazonov can this issue be closed?

**Comment by iSazonov** [comment]
I think having generic and transparent remoting for all cmdlets would be great feature.
