### ISSUE TITLE
PS class cannot have two methods on the same line

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2779]
Steps to reproduce
------------------

```powershell
class Foo {a() {}; b() {}}
```

Motivation:

It's allowed to have properties on the same line:

```
class Foo {$a; $b}  # no error
```

Expected behavior
-----------------

No error

Actual behavior
---------------

```
At line:1 char:12
+ class Foo {a() {}; b() {}}
+            ~~~~~~
Missing closing '}' in statement block or type definition.
At line:1 char:22
+ class Foo {a() {}; b() {}}
+                      ~
An expression was expected after '('.
At line:1 char:26
+ class Foo {a() {}; b() {}}
+                          ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEndCurlyBrace

```

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by lzybkr** [comment]
Just like C#, a semi-colon is not needed, so the error (which could be better) is expected.

**Comment by vors** [comment]
Oh indeed.

I'm constantly having troubles with this.
It feels very natural to put `;` between things, when you are trying to write one-liner.

Could we support this syntax?

**Comment by lzybkr** [comment]
I don't think it's worth it - you'd need to represent that empty statement somehow in the AST which I think is not worth it.

**Comment by iSazonov** [comment]
I scanned the parser.cs file and did not found that the semicolon is included in any ASTs, except in one case for class property extend.
Since I'm working on improving classes this last fact prompted me to raise this topic again.
Class member definition makes no distinction between properties and methods:
```powershell
            //G  class-member-list:
            //G      class-member  new-lines:opt
            //G      class-member-list   class-member
```
Moreover parsing is performed by the same function `ClassMemberRule`.
(I looked up the formal description for [C# 5.0]() and there's also no differences in the definition of properties and methods. I don't know where this distinction originated.)

So in terms of formal definitions it looks as inconsistence. Anyone who studies the language using its formal specification will meet difficulties.

It also seems it is a bad UX (I and @vors both drew attention to that). If the statements in line are always separated by a semicolon, then users will expect the same in this case.
It would be good to preserve consistence here. Otherwise, it is not clear why we can `f(){} g(){}` and cannot `$f=1 g(){}`.
