### ISSUE TITLE
Add a script debugger "break on error"

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#2830]
It would be good to have the ability to drop into the script debugger on error.  This is relatively easy for non-terminating errors since the PowerShell engine continues to run and so the debugger runs.  But exceptions are trickier since the process state is unknown.  For exceptions thrown by PowerShell (ErrorAction: "Stop") we could stop in the debugger before throwing the exception.  It might be possible to have an unhandled exception handler to allow inspection of the runspace on a thrown exception.

**Comment by rkeithhill** [comment]
I'd love to wire such a feature up to Visual Studio Code's exception breakpoints.

**Comment by SteveL-MSFT** [comment]
Consider exposing this as `set-psbreakpoint -breakonerror`

**Comment by rkeithhill** [comment]
Seems like you could install an unhandled exception filter to catch the exception during the first pass - in which case, process state should still be known.  I particularly like this old Matt Pietrek article on the subject - https://www.microsoft.com/msj/0197/Exception/Exception.aspx

**Comment by PaulHigin** [comment]
@SteveL-MSFT  Agreed.
@rkeithhill It turns out we already have this in the expression IL for exception handling routing (try/catch, trap) and we can use this to hook into the debugger.  Still lots of details to work out but this looks very doable.

**Comment by PaulHigin** [comment]
Thanks to @lzybkr  for pointing this out.

**Comment by TylerLeonhardt** [comment]
@SteveL-MSFT alternative:

`Debug-Runspace -BreakOnError`
`Set-Runspace Debug -BreakOnError`

**Comment by JustinGrote** [comment]
I was watching @TylerLeonhardt PSConfEU presentation on debugging and it got me thinking about a workaround.

**launch.json**
```powershell
        {
            "name": "Powershell Break Current Script on Error",
            "type": "PowerShell",
            "request": "launch",
            "script": "./BreakOnError.ps1",
            "args": ["${file}"],
            "cwd": "${file}"
        }
```
**BreakOnError.ps1**
```
try {
    . $args[0]
} catch {
    function VSCodeBreakOnError ($Exception) {
        throw $Exception
    }
    VSCodeBreakOnError $Exception
}
```

Then set a function breakpoint for VSCodeBreakOnError in vscode, and whenever whatever script you run throws a terminating error (doesn't break on non-terminating errors without erroractionpreference = stop), the script will stop at the VSCodeBreakOnError function, and you can click back up to call stack to where the exception occured.

The main limitation of this approach is that you "lose" what $PSItem was, since it gets reassigned at the catch, so if you're debugging a loop you should use foreach to assign the loop variable to something other than the automatic PSItem, or make it your first line in the script. Maybe someone smarter than me knows some other PSCmdlet or something where you can find the PSItem value at this point.

**Comment by PaulHigin** [comment]
This has been implemented by Kirk as an experimental feature.
