### ISSUE TITLE
Get-ChildItem on Linux terminates abruptly when accessing directory fails with access denied or file not found

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#2856]
```powershell
PS > /home/<user>/ dir

dir : Access to path '/home/<user>/.gvfs' is denied

PS >
```

Result:
------
Enumeration of paths and files terminates on access denied error

Expected
------
Get-ChildItem should skip inaccessible paths (with error) and continue enumerating files and paths that are accessible.

**Comment by MaximoTrinidad** [comment]
Question: Which version of OS(Ubuntu/RedHat,Fedora...), and version PowerShell?
Ubuntu 16.04.1 on PowerShell v6.0.0.0-Alpha-13 works fine. 
![ubuntudirfine](https://cloud.githubusercontent.com/assets/19892435/20992361/b35e5718-bcb1-11e6-81ac-c49158077a06.png)

**Comment by SteveL-MSFT** [comment]
This repro'd for me on Ubuntu16.04 with alpha.16.  It may depend on if you have a .gvfs directory in your home directory.  `dir -force` works, but that's not user friendly particularly when `ls` works happily without issue.

**Comment by PaulHigin** [comment]
Agreed.  We need to make "cannot access" errors non-terminating.

**Comment by SteveL-MSFT** [comment]
No longer repro'ing for me on Ubuntu16 with alpha.17

**Comment by SteveL-MSFT** [comment]
I'm hearing this also repros if the file gets renamed or deleted while get-childitem is running.  Generally, get-childitem shouldn't be throwing terminating errors.

**Comment by jeffbi** [comment]
I have not be able to repro this as originally described, using this environment
```PowerShell
PS> $PsVersionTable
Name                           Value                                                     
----                           -----                                                     
PSVersion                      6.0.0-alpha                                               
PSEdition                      Core                                                      
BuildVersion                   3.0.0.0                                                   
CLRVersion                                                                               
GitCommitId                    v6.0.0-alpha.18-58-g8d744f2517c047a9d02b79c65a574741110...
OS                             Linux 4.8.0-51-generic #54~16.04.1-Ubuntu SMP Wed Apr 2...
Platform                       Unix                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                   
PSRemotingProtocolVersion      2.3                                                       
SerializationVersion           1.1.0.1                                                   
WSManStackVersion              3.0                                                       
```

I believe that I have been able to reproduce the scenario in which a file is deleted or renamed during the course of the `Get-ChildItem` process. The cmdlet is not actually throwing a terminating error, it just looks like it is. What actually happens is that when an error is encountered, the error is written and the cmdlet stops processing the specific directory it is currently processing.

Consider the following directory tree:
```
 tmp
 |-- alpha
 |   |-- file1
 |   |-- file2
 |   `-- file3
 |-- beta
 |   |-- file4
 |   `-- file5
 `-- gamma
     `-- file6
```
where our current directory is `tmp.` When a "flat" `Get-ChildItem` is run and during processing the directory `beta` is renamed or deleted, the error is written and the cmdlet stops processing the `tmp` directory and it looks like a terminating error.

If instead we ran a deeper `Get-ChildItem -Recurse`, and while processing the `alpha` directory one of the files within that directory were renamed or deleted, an error would be written and the cmdlet would stop processing the `alpha` directory then return up to continue processing the `tmp` directory which would continue processing the `beta` and `gamma` directories.

I've made a couple of changes that allow processing of a directory to continue if a condition like this occurs. I'm working now on what happens when while processing a directory, that directory itself is deleted.

**Comment by PaulHigin** [comment]
Thanks @jeffbi .  I am not able to repro this any more.  Now when I enumerate a directory on Ubuntu with inaccessible sub directories I get expected behavior ... a full enumeration with error on directories that couldn't be accessed.

I don't know if this was fixed at some point.  But I wonder if this was just a case where an unexpected exception is thrown and not handled.  Do we catch specific exceptions during enumeration?  If so then that might account for the directory enumeration terminating abruptly under certain error conditions.

Regarding enumerating directories that have changed.  It seems to me that this behavior is correct, to abandon that directory since it is in an inconsistent state.

**Comment by jeffbi** [comment]
@PaulHigin The function that walks directories does handle specific exceptions: `ArgumentException`, `IOException` and `UnauthorizedAccessException`. I'm going to be adding additional try/catch handlers for more specific IO exception types a little deeper in scope within the function.

I'm thinking what we would want is if a single file or sub-directory within a directory triggers an error we should not abandon that directory, just write an error and move on to the next entry. If, however, the "current" directory *itself* goes away mid-process then we abandon that directory and go back up to the parent if present. Does that make sense?

**Comment by PaulHigin** [comment]
@jeffbi Yes, I agree.  This sounds like the right behavior.
