### ISSUE TITLE
Need documentation for SDK: Hosting PS runspace

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell#2879]
Need API/SDK documentation for hosting PowerShell runspaces in another application.

**Comment by Jaykul** [comment]
There is now a [host app in the documentation](https://github.com/PowerShell/PowerShell/tree/master/docs/host-powershell) ... it's using PowerShell.Create() so it's the simplest possible host (and it's 82MB  and 250 files) ....

Despite all that, there's no persistence, and it's missing many modules (CimCmdlets, Archive, Security, PackageManagment, PowerShelLGet, PSDiagnotics, etc) ...

@joeyaiello not sure who to follow up with from the meeting last week ... 

We need some help with the persistent hosting APIs because when I try to host using (for instance) `InitialSessionState.CreateDefault2` it gets **a lot** more complicated than hosting Windows PowerShell:

1. I have to copy the Modules folders from my installed copy of PowerShell Core and ship them? I'm not sure if I need to ship different modules folders for each OS I support ... 
2. I'm not sure about PSModulePath -- based on my experience with Windows PowerShell, I assumed that my local path isn't in the PSModulePath, which probably means none of the core modules will load if you don't set it.
3. ExecutionPolicy isn't inherited from my installed pwsh -- even Microsoft.PowerShell.Utility wouldn't import! 

Still more experimenting for me.
