### ISSUE TITLE
Add -Path alias to -FilePath parameter for Out-File command

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#2923]
The `Out-File` command has a mandatory `-FilePath` parameter. The name of the `-FilePath` parameter is a bit redundant, given that the command's noun is `File`. I'd recommend adding a parameter alias `-Path` to the `-FilePath` parameter, to remove the requirement to have this redundancy.

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by BrucePay** [comment]
FWIW- It's not an accident that Out-File uses -FilePath instead of Path. It was intended that commands which take -Path should work against any provider supporting the underlying operations. Out-File explicitly and only works against the file system hence -FilePath instead of the more general -Path.

**Comment by pcgeek86** [comment]
That makes sense.
