### ISSUE TITLE
Powershell not parse mixed single and double quotes [found via: -command Set-Location]

### ISSUE THREAD

**Issue by NearTox** [PowerShell/PowerShell#2926]
Steps to reproduce
------------------
1. execute:
```powershell
>powershell.exe -noexit -command Set-Location "X:\I'll do"
```

Expected behavior
-----------------
open powershell in "X:\I'll do" location

Actual behavior
---------------
powershell return:

The string is missing the terminator: '.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
CLRVersion
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
PSVersion                      6.0.0-alpha
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
GitCommitId                    v6.0.0-alpha.14
PSEdition                      Core
WSManStackVersion              3.0
BuildVersion                   3.0.0.0
```

**Comment by chuanjiao10** [comment]
i think it's not a bug.

$a = "A:\pscode\temp184\aaa'b"
cd -LiteralPath $a
cd ..
pwd
$b = "aaa'b"
cd -LiteralPath $b
pwd

get-command -ParameterName LiteralPath

Merry Christmas to every American,happy new year to you.

**Comment by NearTox** [comment]
i think that the problem is from System.Management.Automation
a tokenizer problem (i'm not a C# programer, sorry if fail)
![powershell bug 2](https://cloud.githubusercontent.com/assets/3236398/21487110/49c297c6-cb87-11e6-948c-a1fe0a25eba3.PNG)


And Merry Christmas and new year.

**Comment by lzybkr** [comment]
This is not a PowerShell bug - the command line you've passed will not contain the double quotes.

```
C:\>echoargs -noexit -command Set-Location "X:\I'll do"
arg 0: <-noexit>
arg 1: <-command>
arg 2: <Set-Location>
arg 3: <X:\I'll do>

CommandLine:
echoargs  -noexit -command Set-Location "X:\I'll do"
```

Notice that `arg 3` is a single argument (because you used quotes), but the actual argument does not contain the quotes.

This is how argument parsing works.

PowerShell tries to be help and concatenates all of the argument after `-Command`, but in cases like this, it can be a bit confusing because values get processed by the shell you use (in your case cmd) before PowerShell gets a chance to parse the concatenated command line.

Here is one possible solution (assuming your shell is `cmd`, it may work in other shells as well):

```
powershell -noexit -command "Set-Location \"X:\I'll do\""
```

**Comment by NearTox** [comment]
thanks @lzybkr
