### ISSUE TITLE
Will invoking of external bash command throw exception?

### ISSUE THREAD

**Issue by jianglibo** [PowerShell/PowerShell#2930]
The lines bellow should catch an exception?
I had wrote Powershell for months, It's not Powershell way.

```
try {
  "/opt/oozie-build/oozie/bin/mkdistro.sh -DskipTests >/tmp/tmpJylOol.tmp 2>&1" | Invoke-Expression
}
 catch {
            $Error | Write-HostIfInTesting
 }

Or

try {
  "/opt/oozie-build/oozie/bin/mkdistro.sh -DskipTests" | Invoke-Expression
}
 catch {
            $Error | Write-HostIfInTesting
 }
```

Even invoke code like this, it won't throw an exception. Does Powershell handle Java thread special?
```
try { "bash xx" | Invoke-Expression} catch { "yyy"}
```

**Comment by BrucePay** [comment]
External commands can't throw exceptions. They can only write to the error stream and return an exit code. If the exit code is non-zero then the value of $? will be false. The specific exit code is available in the variable $EXITCODE. Also, you don't need to use Invoke-Expression to execute an external command. You can execute them directly as in
`bash -c "exit 1" ; if ( -not $?) { "Cmd exited with an error status" }`
(NOTE: In general, Invoke-Expression should be avoided except for a few rare cases since it opens the doors to script injection attacks.)
