### ISSUE TITLE
New-Object doesn't work with classes in nested modules

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell#2963]
Steps to reproduce
------------------
1. Define some PowerShell classes in a module file (ClassTester.psm1).
2. In the manifest, leave RootModule empty and place the module name in the NestedModules key value.
```
ModuleToProcess = ''
NestedModules = 'ClassTester.psm1'
```
3. In a script, use a Using module statement to import the module and its classes, use the New static method to instantiate one of the classes defined in ClassTester.psm1, and then use New-Object on the same class. 

```
using module ClassTester
$myDog = [Dog]::New('Fido')
$myDog.Bark()

New-Object -TypeName Dog -ArgumentList 'Fluffy'
$myDog.Bark()
```

Expected behavior
-----------------
Both the New method and New-Object cmdlet should work.

Actual behavior
---------------
New works, but New-Object generates an error.

```
'Woof!,' said Fido  # New method works
New-Object : Cannot find type [Dog]: verify that the assembly containing this type is loaded.
At C:\ps-test\Test-ClassTester.ps1:22 char:11
+ $fluffy = New-Object -TypeName Dog -ArgumentList 'Fluffy'
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
```

Environment data
----------------

```
Name                           Value
----                           -----
GitCommitId                    v6.0.0-alpha.14
PSRemotingProtocolVersion      2.3
BuildVersion                   3.0.0.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSVersion                      6.0.0-alpha
PSEdition                      Core
CLRVersion
```

**Comment by xavylon** [comment]
Solution: The issue is that you must call the constructor via a method call when you invoke the New-Object cmdlet. See the attached example code.

#A constuctor is a method. It must be called as such.
#you cannot use a argument list for this.

$dog = New-Object Dog("Fido")
$dog.bark()

**Comment by mklement0** [comment]
@xavylon: 

There is _no_ syntax issue here:

`New-Object -TypeName Dog -ArgumentList 'Fido'` _is_ the proper (if verbose) way to call a constructor via `New-Object`; its concise equivalent is `New-Object Dog Fido` (yes, the quotes are optional here).

In your example, `Dog("Fido")` is _not_ a method call; it's a syntax based on a misconception that's unfortunately very common and persists because it just so _happens_ to work:

`New-Object` is a _command_ and therefore accepts _arguments_ in _argument mode_, not expression mode (you can only perform method calls in the latter).

`Dog` and `("Fido")` are therefore separate _positional arguments_, which bind to `-TypeName` and `-ArgumentList`, respectively.

**Comment by mklement0** [comment]
@juneb:

From what I can tell - at least as of PowerShell Core v6.0.2 - even the static `::new()` method doesn't see classes from nested modules.

It looks like the crux of the issue is that nested modules are imported with the (equivalent of) `Import-Module` rather than `using`, rendering any of the nested module's classes inaccessible - whether via `::new()` or via `New-Object`.
