### ISSUE TITLE
Get-Process Cmdlet discrepancies displaying information (CPU, Responding)

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#2975]
Steps to reproduce
------------------
Using PowerShell Open Source,  type the following one liner on local Windows 10 computer:
Get-Process | Select name, CPU, Responding

Then, using the "-ComputerName" parameter:
Get-Process -ComputerName Server1 | Select name, CPU, Responding 

Expected behavior
-----------------

Should Display all selected properties values, 

Actual behavior
---------------

In PowerShell Open Source, in local computer it will only display the CPU values but not the Responding values.  Then, when using the "-ComputerName" parameter, both CPU and Responding are blank.

In Windows PowerShell version 5.1, in local computer it will display both CPU and Responding values.  Then, when using the "-ComputerName" parameter, both CPU and Responding are blank.

Environment data
----------------

```powershell
PS C:\Program Files\PowerShell\6.0.0.14> $PSVersionTable

Name                           Value
----                           -----
CLRVersion
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
PSEdition                      Core
BuildVersion                   3.0.0.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
GitCommitId                    v6.0.0-alpha.14
PSVersion                      6.0.0-alpha

```
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14986.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14986.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

![get-process_2017-01-07_5-14-02](https://cloud.githubusercontent.com/assets/19892435/21741128/0d123314-d49b-11e6-9508-a6f74e758e54.jpg)

**Comment by SteveL-MSFT** [comment]
This is unfortunately due to the .Net Process class.  On CoreCLR, Responding doesn't exist (it's dependent on specific Windows GUI apis) so it'll always be empty.  The remoting behavior on FullCLR is entirely based on the Process class.

On both full and CoreCLR, per the documentation, CPU (which is just a formatted TotalProcessorTIme) is only supported on the local computer.  Workaround is to use Invoke-Command for remoting rather than the built in .Net remoting.  https://github.com/PowerShell/PowerShell/issues/2761 would solve the remoting discrepancy.
