### ISSUE TITLE
Add support to set line breaks within a scriptblock for invoke-command

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#3000]
When debugging invoke-command, today you have to set a breakpoint on invoke-command while it would be easier and perhaps more intuitive to be able to set a breakpoint to a line within the scriptblock passed to invoke-command.

**Comment by lzybkr** [comment]
This shouldn't require any UI changes - Invoke-Command can check if there are any local breakpoints in the script file/scriptblock, and set the remote breakpoints as needed.

**Comment by KirkMunro** [comment]
Thanks @iSazonov.

@SteveL-MSFT: I don't really know how this would work.

Would you expect that to work no matter which of the many `Invoke-Command` parameter sets are used? With so many different scenarios/protocols involved when you use `Invoke-Command`, including WinRM, SSH, commands invoked in a VM over the VM bus, etc., is setting remote breakpoints that are actionable in each of those scenarios even possible?

What happens when a breakpoint is hit inside of a script block running in a VM in Hyper-V? Is the debugger able to pick up on that and enter a remote debugging session over the VM bus? I don't think that works today.

And if PowerShell did enter a remote debugging session with the breakpoint on the appropriate line, and you start stepping over lines, would it step out at the end of that script block and come back to stepping through the client?

Or if you were using step into while in the client, would a step into call into `Invoke-Command` when no breakpoints are set in the script block result in stepping into the remote session on the server?

I think this is an interesting idea with a lot of complications behind it. That doesn't mean it should be dismissed outright, but it definitely does not seem as simple as checking for local breakpoints and setting remote breakpoints.

**Comment by SteveL-MSFT** [comment]
The transport shouldn't matter as the PSRP is the same.  I would expect the experience to be no different than if you manually set the remote breakpoints.

**Comment by KirkMunro** [comment]
@SteveL-MSFT I didn't quite see how that would work when I originally posted my earlier reply, but I do now. I love that this could work in all of those remoting scenarios. That's very cool.
