### ISSUE TITLE
[Feature Request] Allow support for PowerLine Fonts in PowerShell

### ISSUE THREAD

**Issue by avdaredevil** [PowerShell/PowerShell#3010]
Could you please allow for [PowerLine Patched fonts](https://github.com/powerline/fonts) to be enabled in PowerShell so that customizations and interactivity such as [Oh-My-Zsh](https://github.com/robbyrussell/oh-my-zsh) could be brought right into PowerShell!

**Comment by lzybkr** [comment]
I don't think this is a PowerShell issue - we rely on the underlying console subsystem for fonts.

I thought powerline fonts worked, this comment suggests they do: https://github.com/Microsoft/BashOnWindows/issues/279#issuecomment-218726174

If you do have issues with the powerline fonts, I suggest searching https://github.com/Microsoft/BashOnWindows/issues to see if the issue is known/solved and open a new issue if you don't fine an existing one.

**Comment by Jaykul** [comment]
Yeah, they work. Some of them may not show up in the conhost properties dialog because they're not truly monospaced ... https://github.com/jaykul/powerline

**Comment by avdaredevil** [comment]
Gotcha, sorry for misunderstanding the problem... I realized that PowerShell_ISE is able to render much more characters than the Shell counterpart, as it creates its own shell. Hence, the confusion.

Thanks, it still looks awesome!
![AP's PowerShell](https://cloud.githubusercontent.com/assets/5303018/22073153/90a6add8-dd72-11e6-9f01-c89bf716286e.png)
