### ISSUE TITLE
Check for invalid exported commands in Test-ModuleManifest

### ISSUE THREAD

**Issue by chunqingchen** [PowerShell/PowerShell#3016]
This is a customer feedback according to issue
https://github.com/PowerShell/PowerShellGet/issues/87

when user input CmdletsToExport = '@() ' in module manifest, test-modulemanifest suppose to give friendly warning about this.

Environment data
----------------
```
Name                           Value
----                           -----
PSVersion                      5.1.15007.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15007.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by lzybkr** [comment]
I'm not sure I understand what the proposed warning should be.

I don't think we should test for a specific string, e.g. `'@()'`, that seems like too much of a special case.

Ideally we could warn on exported commands that don't exist, though that's harder or impossible to implement for modules that dynamically define commands.

As a compromise, we could warn if any of the exported commands don't match a regex, something like `^\w+-\w+$' for cmdlets and `^\w+$` for functions, variables, and aliases. This would just be a warning though, so if the regex is too aggressive, we don't cause problems for valid scenarios.

**Comment by Jaykul** [comment]
How about if Test-ModuleManifest just issues the same warning Import-Module would about the name not having a valid verb ;-)

**Comment by BrucePay** [comment]
Module manifests, by design, are aggregators of modules. You can have a module that contains nothing but a manifest. That manifest then imports (multiple) other modules and re-exports all, some or none of the imported elements. (This is why Import-Module -verbose shows both import and export messages). Assigning an empty array explicitly means "export no cmdlets/variables/aliases" i.e. it's an explicit valid value. That said, it's also unlikely to be used so having Test-ModuleManifest (and Update-ModuleManifest) emit a warning when any of the export field _values_ are set to empty array i.e. @() makes sense.  It's a simple value test that I think we should take.

**Comment by lzybkr** [comment]
I updated the title - because it confused both @BrucePay and myself.

@Jaykul - a warning on invalid verbs would work for `CmdletsToExport`, but functions and aliases do not necessarily need a verb at all.

As it's just a warning - it seems fine to warn on any exported commands that don't match some regex, something like `'^\w(-\w)?$'`.
