### ISSUE TITLE
Invoke-WebRequest errors if Internet Explorer is not installed

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#3042]
By default, Invoke-WebRequest relies on Internet Explorer components to parse the html (user retrieves it via the .parsedhtml property), however in Azure Functions and Containers, IE is not present so if -UseBasicParsing is not specified, you get an error saying that IE is not installed.

Expected behavior is for Invoke-WebRequest to default to -UseBasicParsing if IE is not present (perhaps output a warning if that switch is not specified as ParsedHtml property will be null)

**Comment by daxian-dbw** [comment]
Is this bug specific to Windows PowerShell?

Currently in powershell core, we always use basic parsing because we haven't figure out a way to depend on mshtml.dll in CoreCLR. See the code [here](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebResponseObjectFactory.CoreClr.cs#L20). It would be great that we resolve this dependency issue so that `Invoke-WebRequest` can continue to use IE to parse html response when IE is available.

**Comment by SteveL-MSFT** [comment]
Based on the code, this appears to be a Windows PowerShell specific issue (as Azure Functions uses Windows PowerShell v4 today).  We won't be making this fix in Windows PowerShell v5, so resolving.

**Comment by iSazonov** [comment]
Tracked in #2867
