### ISSUE TITLE
Get-Help -online is broken on Azure VMs

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#3079]
Steps to reproduce
------------------
Get an Azure VM - Server 2016
```Powershell
PS C:\> get-help -Online gps
```
Expected behavior
-----------------
Opens default browser with help content

Actual behavior
---------------
```Powershell
get-help : Starting a browser to display online Help failed. No program or browser is associated to open the URI
https://go.microsoft.com/fwlink/?LinkID=113324.
At line:1 char:1
+ get-help -Online gps
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-Help], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.GetHelpCommand
```

Environment data
----------------

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
PSVersion                      6.0.0-alpha
PSEdition                      Core
CLRVersion
PSRemotingProtocolVersion      2.3
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.14-59-g14311052514b2626a00eafeae14978c7dac7867c
```

**Comment by daxian-dbw** [comment]
**Important:** PR #3051 was merged as a temporary workaround to avoid the test failure. When fixing this issue, please make sure the changes in PR #3051 is reverted.

**Comment by daxian-dbw** [comment]
#3051 introduced the `if((-not ($skipTest)) -and $IsWindows)` block in `test/powershell/engine/Help/HelpSystem.OnlineHelp.Tests.ps1` because our default-browser-discovery code, which was used in `Get-Help -Online`, didn't work correctly on the Azure code-coverage VM.

After #3281, that code was replaced by calling into `ShellExecuteEx`. We need to verify if `Get-Help -Online` works fine now on the Azure code-coverage VM, and if it does then this `if` block should be removed completely.

**Comment by SteveL-MSFT** [comment]
Just created a WS2016 VM in Azure and `get-help -Online gps` works as expected although you do get a bunch of warning dialog boxes due to `Internet Explorer Enhanced Security Configuration` (which is expected).  However, if we use Server Core VMs, then I expect there to be no web browser (or GUI) available, so it depends on the type of VM we use for our nightly runs.

Closing this issue as the original issue doesn't repro.

**Comment by daxian-dbw** [comment]
@SteveL-MSFT do you think the `if((-not ($skipTest)) -and $IsWindows)` block should be removed?

**Comment by SteveL-MSFT** [comment]
cc @JamesWTruher are we using Server Core for CC?

**Comment by daxian-dbw** [comment]
@SteveL-MSFT that makes sense.
