### ISSUE TITLE
Releases should include the test logs for the release

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#3087]
When we release a build, we should ensure that the test log for the release is part of the release. This will provide a quality measurement as part of the release. We should be doing a run of all our tests, not just CI tests.

**Comment by lzybkr** [comment]
Do you mean a file in the packages people install? That feels somewhat wasteful of network and disk resources because the file would rarely be accessed.

I can see including a link in the release notes though - which we'd also use on our [release tab](https://github.com/PowerShell/PowerShell/releases).

**Comment by iSazonov** [comment]
Is the issue still needed? /cc @SteveL-MSFT @TravisEz13

**Comment by SteveL-MSFT** [comment]
Currently, I believe we internally retain test logs to compare results for a release.  However, we should really be fixing the tests or product so that all tests pass 100% on every distro so there should be a need to retain this after we get there.
