### ISSUE TITLE
Add *-EnvironmentVariable cmdlets

### ISSUE THREAD

**Issue by charub** [PowerShell/PowerShell#3108]
MSFT:10836263
Add following cmdlets :
1. Get-EnvironmentVariable
Syntax :  
   Get-EnvironmentVariable [[-Name] <string[]>] [-ValueOnly] [-Scope {Process | Machine | User}]  
   [<CommonParameters>]

2. Set-EnvironmentVariable
Syntax : 
   Set-EnvironmentVariable [-Name] <string> [[-Value] <string>] [-Force] [-PassThru] [-Scope {Process |   
   Machine | User}] [-WhatIf] [-Confirm]  [<CommonParameters>]

3. New-EnvironmentVariable
Syntax : 
   New-EnvironmentVariable [-Name] <string> [[-Value] <string>] [-Force] [-PassThru] [-Scope {Process | 
   Machine | User}] [-WhatIf] [-Confirm]  [<CommonParameters>]

4. Add-EnvironmentVariable
Syntax : 
   Add-EnvironmentVariable [-Name] <string> [-Value] <string> [-Force] [-Prepend] [-PassThru] [-Scope   
   {Process | Machine | User}] [-WhatIf] [-Confirm]  [<CommonParameters>]

5. Remove-EnvironmentVariable
Syntax : 
   Remove-EnvironmentVariable [-Name] <string[]> [-Scope {Process | Machine | User}] [-WhatIf] 
   Confirm]  [<CommonParameters>]

**Comment by joeyaiello** [comment]
This will almost certainly require an RFC [here](https://github.com/powershell/powershell-rfc), following up offline as well. :)

**Comment by jdhitsolutions** [comment]
Submitted to the Cmdlet Working group for discussion

**Comment by TobiasPSP** [comment]
https://github.com/orgs/PowerShell/teams/wg-powershell-cmdlets reviewed this:

Managing environment variables is an OS-specific task, and i.e. on Windows OS, the suggested cmdlets would just be a thin wrapper around easily accessible  .NET calls like [System.Environment]::GetEnvironmentVariable() et al. While it would be awesome to have easily discoverable cmdlets for more tasks, the PowerShell engine needs to focus on fundamental OS-agnosic functionality. That's why cmdlets like these should be added by the community and published to the Gallery.
