### ISSUE TITLE
Move build to csproj/msbuild

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#3140]
This more of a placeholder issue than anything right now. Today, the build uses `dotnet-cli` and the `project.json` schema for managing the build. In the future, [.NET Core is moving back to MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-tools-msbuild-alpha/), which we'll need to use if we want to leverage .NET Standard 2.0 (which we want to do in the 6.0.0 timeframe). 

I have no idea what the work entails right now (or if we can get started yet), but I wanted to get it on everyone's radar.

**Comment by iSazonov** [comment]
I see that .Net team is actively seeking the experience of such migration. Maybe they will be happy to provide direct assistance to us.
http://landinghub.visualstudio.com/migrate-dotnetcore

**Comment by lzybkr** [comment]
The biggest issue is likely on our side - we depend on the `project.json` files to produce the list of assemblies that go into our type catalog for type resolution. We have a proposed temporary solution - to just check in the generated type catalog - but that's not a long term solution because it won't work when we update which assemblies we pull in.

We also need to merge https://github.com/PowerShell/PowerShell/pull/3066 to reduce the effort to migrate.

**Comment by joeyaiello** [comment]
@lzybkr can't we also solve the same problems that #3066 alleviates (namely, a dependency on Win10 SDK) by moving native binary compilation out of this repository? (i.e. since those aren't getting touched quite as much, build them in another repo and pull them in through a Nuget feed?)

**Comment by lzybkr** [comment]
#3066 saves effort in migrating by building less **and** having simpler build files (one target - `netstandard1.x` instead of two.)

Moving native binary compilation should also help (building less!), but it is slightly different.
