### ISSUE TITLE
-OutVariable doesn't unwrap single-object output and creates [System.Collections.ArrayList] values rather than [System.Object[]]

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3154]
<sup>Note: Also affects other common parameters: see #3773</sup>

Steps to reproduce
------------------

```powershell
$null = Get-Date -OutVariable ov; $ov.GetType().FullName
```

Expected behavior
-----------------

Type name `System.DateTime`

Actual behavior
---------------

Type name `System.Collections.ArrayList`

That is, the single-object output stored in the variable targeted with `-OutVariable` received an _array list_ rather than a scalar (the single-element collection wasn't unwrapped).

Also, it is type `[System.Collections.ArrayList]` that is always used, in contrast with the `[System.Object[]]` instances you get with _regular_ assignments.

See also: http://stackoverflow.com/a/40666568/45375

Environment data
----------------

```powershell
PowerShell v6.0.0-alpha (v6.0.0-alpha.15) on Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64
PowerShell v5.1.14393.693 on Microsoft Windows 10 Pro (64-bit; v10.0.14393)
```

**Comment by BrucePay** [comment]
IIRC it's been this way since version 1. Changing it now would be a breaking change.

**Comment by PetSerAl** [comment]
Note that `-OutVariable` produce live collection, you can reference to it while pipeline is still working:
```
1..10 | echo -OutVariable a | % { "$a" }
```
Using not resizable `[System.Object[]]` instead of `[System.Collections.ArrayList]` would be bad performance choice.

**Comment by lzybkr** [comment]
The behavior is surprising, and possibly falls into the [unlikely grey area](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area) bucket.

Tagging for committee review.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agree with the expected result even though it is a breaking change

**Comment by Jaykul** [comment]
While I agree that it's weird that this doesn't behave like pipeline output....

## The **_only_** thing that PowerShell does this collection/single behavior for is pipeline output

These have been collections since the very beginning. 

You'll be _potentially_ breaking every single use of these in the history of PowerShell.

**Comment by rjmholt** [comment]
Please see [this RFC proposal](https://github.com/PowerShell/PowerShell-RFC/pull/120) for comments on this breaking change.

**Comment by mklement0** [comment]
@Jaykul  (Cross-posting this from the related, generalized #3773)

> The only thing that PowerShell does this collection/single behavior for is pipeline output

That is not much of a restriction, however, given the pervasive use of pipelines, even in places where it is not obvious:`$(...)`, `@(...)`, `&`, `.`,  script-block arguments.

To give a few examples, all of which output `$True`:

```powershell
$(, 1) -is [int]
(. { , 1 }) -is [int]
(& { , 1 }) -is [int]
('' | Select-Object @{ n='foo'; e = { , 1 } }).foo -is [int]
```

<sup>There is no `@(...)` example, because `@(...)` by design ensures _array-valued_ output - though it would still recreate any input collection as a `[object[]]` array.</sup>

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee agrees on followig the RFC process specifically the RFC that @rjmholt published

**Comment by mklement0** [comment]
As an afterthought, given that I just stumbled upon it:

`Tee-Object -Variable` exhibits pipeline, logic, as expected - unlike `-OutVariable`:

Single-object output produces a _scalar_:

```powershell
# Capture output from a command that outputs a *single* object
PS> $null = Get-Item / | Tee-Object -Variable out; $out.GetType().FullName
System.IO.DirectoryInfo  # *scalar* was captured
```

Multi-object output creates a `[object[]]` array.

```powershell
# Capture output from a command that outputs a *multiple* objects
PS> $null = Get-ChildItem / | Tee-Object -Variable out; $out.GetType().FullName
System.Object[]
```

**Comment by ratijas** [comment]
After all this time, is this still a desired feature?

**Comment by rjmholt** [comment]
As far as I could tell at the time with the RFC, any change to the existing behaviour would be controversial and the current behaviour is considered a feature by some. More importantly, it's public behaviour that users depend on, so I suspect it's something we can't change and we should close this issue.

**Comment by mklement0** [comment]
It is a candidate for #6745 (in the sense that a hypothetical future PowerShell version not beholden to backward compatibility should reconsider this behavior).

**Comment by UberKluger** [comment]
It seems that no-one picked up on what might be the basic reason for using an `[ArrayList]` (even for single objects),

> To add the output to the variable, instead of replacing any output that might already be stored there, type a plus sign (+) before the variable name.

Using an (immutable) `[Object[]]` could result in a performance degradation as it would have to be copied to a new `[Object[]]` every time it was updated. @PetSerAl did give some insight but the example usage would be rare compared to `-OutVariable +name` (IMO).

As for storing a single object as a scalar, there would be no guarantee that a single object output stored in `-OutVariable` would not subsequently have later output appended. As with the issue of single items from pipelines being stored as scalars but possibly being used later as arrays (hence the advice about using the array subexpression operator `@()` in such cases), it would be cumbersome to have to check whether a `-OutVariable` contained a scalar or collection, or at least it would have been before PS3.0 added indexing of scalars, thereby somewhat obscuring the difference. Still, "Once an `[ArrayList]`, always an `[ArrayList]`".

Note: `Tee-Object -Variable` does not have the option to append with `+` and so can make assumptions about the intended use of the variable and produce a result identical to that which would be stored by a variable capturing the pipeline output from `Tee-Object`. Further, if a variable containing a scalar or an `[Object[]]` is used as an appending `-OutVariable` then it is first converted to an `[ArrayList]` of the same length (1 or many), whether or not anything is appended, thereby maintaining the "flat" collection in a consistent container after use of `-OutVariable`.
```
PS > 1,2 | Tee-Object -Variable tee1
1
2
PS > $tee1.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Object[]                                 System.Array

PS > $tee1.Length
2
PS > @() | Tee-Object -Variable tee2 -OutVariable +tee1
PS > $tee1.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     ArrayList                                System.Object

PS > $tee1.Count
2
PS >
```
(Tested on 5.1.18362.145)

**Comment by KingAl** [comment]
Agreed with @UberKluger, it's very sensible to have Pipeline-native accumulation supported in some way in Powershell; and currently `-OutVariable +var` is the only way to accumulate multiple separate outputs in a performant way, without dropping into .NET ArrayList syntax.

I don't think altering the behaviour on a singleton would be a problem, although there are potential pitfalls - if an iteration produces lists, and the first list is unwrapped into the same variable, then subsequent lists would be appended to the end of the first list instead of alongside it.

However, with respect to the other observation, Array vs ArrayList type, OutVariable behaviour should emphatically not be changed from appending to ArrayLists to appending to Arrays - that would be a huge performance hit for code correctly using the parameter. Arrays and ArrayLists are comparable for appending about 1000 elements, but once you're dealing with 40,000 items there's a factor of 12 difference (10 seconds vs 2 minutes), and 80,000 it's a factor of 24, etc. So the current behaviour is the difference between a script quite handily processing millions of items in a minute versus taking hours. (Of course, appending to an array is not a typical Powershell idiom - I'll get to that.)

I think at the very least, OutVariable behaviour should be very clearly documented - it's evident that that's not the case currently, I can only imagine there was some intention to transparently handle Arrays and ArrayLists the same way in earlier design stages that never came to fruition. Note of course that _deliberate_ unwrapping of an ArrayList is very easy, `$($var)` will give us a Singleton for a one-element ArrayList and an Object[] otherwise.

With respect to the need for separate accumulations, as facilitated by OutVariable: Ideally, tasks can be broken down into separate pipelines so that separate accumulations can be performed each with a single pipeline, but some tasks don't lend themselves to this, particularly when there's variegated interdependent checks where a value from one output will influence another; in those circumstances, the alternatives without OutVariable are using Out-File, which loses type information and is disk bound (but at least can append in constant time, and clearly specifies a 'separate' output), or writing to the common output stream and performing a post-hoc Where filter, which requires a great deal more coordination and setting of metadata to facilitate a filter than would simply accumulating to separate variables.

If I had to design an alternative to supersede -OutVariable it'd be named streams - `$var = Create-Stream; @(1,2,3) | Write-Stream $var` etc. This maps to natural Powershell idioms (including writing values directly to the pipe) and reflects how people will often use Out-File naturally without the performance hit of writing to disk. Unlike an `Out-` cmdlet the OutVariable parameter allows output to pass through, which means in practice you have to deliberately redirect to $null if you just wanted it accumulated in the ArrayList; not a pretty idiom.

**Comment by vexx32** [comment]
> Agreed with @UberKluger, it's very sensible to have Pipeline-native accumulation supported in some way in Powershell; and currently -OutVariable +var is the only way to accumulate multiple separate outputs in a performant way, without dropping into .NET ArrayList syntax.

You can collate pipeline objects pretty easily with neither of those:

```powershell
$results = @(
    Get-ChildItem $folder1
    Get-ChildItem $folder2
    Get-ChildItem $folder3
)
```

This produces a flat array with all the results of the three commands in it.

**Comment by Jaykul** [comment]
> This produces a flat array with all the results of the three commands in it.
As long as you can put all of the outputting lines together in one place...

**Comment by vexx32** [comment]
IMO it's less common to _not_ be able to do that, but it does happen. In those instances, I don't think the -OutVariable or equivalent usage of List types is a huge burden.

**Comment by KingAl** [comment]
> You can collate pipeline objects pretty easily with neither of those:

Yeah sorry, I could have been clearer. Absolutely, that way is the best approach in general where it fits the use case; it's what Powershell encourages you to use and is the idiom people should use by default. (When people don't, it's normally because they're expecting Powershell to work like some other language with which they're more familiar.)

However, if you have three categories of thing, say line 1 went to $a, line 2 went to $b, line 3 went to $c, Out-Variable is the most efficient way of doing this. It's better to use three different pipelines, but sometimes the three outputs are interrelated enough that it's difficult to extricate easily, and outputting each from within the same loop is the most sensible way to keep the code simple and efficient.
