### ISSUE TITLE
Ctrl + L in Python inside Powershell fails to clear the screen

### ISSUE THREAD

**Issue by dalyIsaac** [PowerShell/PowerShell#3175]
Steps to reproduce
------------------
Enter `python` in PowerShell
Enter some code: `print("Hello, world!")`
Press Ctrl + L

Expected behavior
-----------------
Screen clears to `>>>` (or scrolls up so the previous shell input and output can no longer be seen)

Actual behavior
---------------
`^L` prints to the console

Environment data
----------------

```powershell
> $PSVersionTable

```Name                           Value
----                           -----
PSVersion                      5.1.15031.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15031.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by MaximoTrinidad** [comment]
Hum! I don't think is PowerShell but the Windows version of Python.  Please include the version of Python. 

The actual behavior in Ubuntu using Ctrl-L is to move the code up and it looks like it cleared the screen but it didn't.  As, you can scroll-Up and see the code again.

By the way, the same error happens when you execute Python from the DOS command prompt.

![python_c trll_2017-02-20_22-27-36](https://cloud.githubusercontent.com/assets/19892435/23149788/7ff4238a-f7bc-11e6-8a83-32c877465aec.jpg)
![python_c trll_2017-02-20_22-27-37](https://cloud.githubusercontent.com/assets/19892435/23149798/8737d74a-f7bc-11e6-9a77-a1c7e4883337.jpg)

**Comment by dalyIsaac** [comment]
Python 3.6.0

**Comment by MaximoTrinidad** [comment]
Found out to clear the whole Python code during the session could use the following:

import os
var=os.system("tput reset")

I know is not pretty but it works. The purpose of the variable var is to hide the "0" result value.

Below is the reference link: http://stackoverflow.com/questions/27420880/how-to-clear-python-console-i-e-ctrll-command-line-equivalent
:)

**Comment by BrucePay** [comment]
There is no magic processing going on here. ctrl-L is the ASCII form-feed character. Sending that character to a terminal causes it to jump one screen forward. The Windows console subsystem is not a terminal and doesn't respond to ctrl-L. I'm closing this as resolution-external since the console would have to be enhanced to understand ctrl-L.

**Comment by blisksolutions** [comment]
Can't be more boring, since other technologies like MySQL, MongoDB, NodeJS, etc have Ctrl+L support.
But as I am used to exit(), why not clear()?

At every session I just past this:

`def clear(): import os; os.system("tput reset")`

That's a great case to use semicolons in Python 😄 !
