### ISSUE TITLE
Import-PowerShellDataFile incorrectly assumes psd1 is a single hashtable

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#3213]
The cmdlet `Import-PowerShellDataFile` incorrectly assumes a `psd1` file is a simple hashtable like most typical module manifests.

The `psd1` file format actually allows many other things - the data could be a simple expression, array, etc.

And in fact, a valid module manifest can also be more complicated.  For example, the following is a valid module manifest:

```PowerShell
@{} + @{ RootModule = ".\foo.psm1"; ModuleVersion = "1.0.0" }
```

The above may seem contrived, but it end up being a useful way of conditionally including keys in a module manifest, e.g. based on an environment variable.

**Comment by AlanMcBee** [comment]
I have a less-contrived exampled that is hurting me now.

MS Documentation says (see [Modules with compatible PowerShell Editions](https://docs.microsoft.com/en-us/powershell/scripting/gallery/concepts/module-psedition-support?view=powershell-7.2#option-2-use-psedition-variable-in-the-psd1-file-to-load-the-proper-dlls)) that a recommended way to create modules with support for multiple editions (Core + Desktop) is to use a check for `$PSEdition` in the `psd1` file. 

This works fine for regular module usage. The `psd1` passes the `Test-ModuleManifest` check, and it imports and works just fine.

However, I am trying to automate parts of the process of updating the manifest. Specifically, bumping the version number and rebuilding the various *ToExport keys (e.g. `FunctionsToExport` etc.). For this, I've been trying to use the safe(r) Import-PowerShellDataFile, but it complains with `InvalidOperationException`: `Cannot generate a PowerShell object for a ScriptBlock evaluating dynamic expressions.`

In my case, I can more or less ignore the offending entries in the `psd1` file (I'll be using `Invoke-Expression` when `Import-PowerShellDataFile` fails). But I need to use Option 2 (i.e. using the `$PSEdition` check) because I am using newer code syntax (null-coalescing) in the `ScriptsToProcess` script file for the Core edition, and a backward-compatible shim for the Desktop edition.

Perhaps a simple switch on the `Import-PowerShellDataFile` that allows a minimal evaluation, such as only the AST that allows either this $PSEdition check, or simple string manipulation, etc.?

**Comment by potatoqualitee** [comment]
Import-PowerShellDataFile isn't really useful anymore now that I'm using PSEdition :/ Good call on invoke expression, ill have to see what i can do with that.

**Comment by doctordns** [comment]
What is the use case? ANd how do you use $PSEdition? Just trying to understand the requirement.

**Comment by potatoqualitee** [comment]
I ended up abandoning it because it caused too many issues but this is what i was doing

```
 RequiredModules        = @( 
     if ($PSEdition -eq 'Core') { 
         @( 
             @{ ModuleName = 'dbatools.core.library' } 
         ) 
     } else { 
         @( 
             @{ ModuleName = 'dbatools.library' } 
         ) 
     } 
 ) 
```

**Comment by doctordns** [comment]
Thanks.

**Comment by doctordns** [comment]
The WG has reviewed this and feel it would be very complex to implement and complex for the user to use.  A module manifest is a specialized version of a PowerShell data file, and as such, Import-PowerShellDataFile is incompatible. We are closing this as Decline.
