### ISSUE TITLE
start-process -wait and -verb runAs does not work together

### ISSUE THREAD

**Issue by throwable-one** [PowerShell/PowerShell#3220]
Steps to reproduce
------------------

From cmd.exe launch ``powershell -Command "start cmd.exe -wait"``
It starts cmd.exe and waits for it. Works.

From cmd.exe launch ``powershell -Command "start cmd.exe -verb runAs"``
It starts cmd.exe and asks for credentials. It works.

Now try 
``powershell -Command "start cmd.exe -verb runAs -wait"``

Expected behavior
-----------------
cmd.exe is launched as admin and shell waits for it.

Actual behavior
---------------
cmd.exe launched, but instead of wait I got
```
start : Access is denied
At line:1 char:1
+ start cmd.exe -verb runAs -wait
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-Process], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.StartProcessCommand
```

Environment data
----------------
```
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.2.9200.16481
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2
```

**Comment by mklement0** [comment]
@throwable-one:

Since you've observed this  in _Windows PowerShell_, you should report it at [uservoice.com](https://windowsserver.uservoice.com/forums/301869-powershell).

_This_ repo is for bugs / issues that are (still) present in PowerShell _Core_.

I can't speak to whether _v3_ bugs are still being fixed.
Also note that I cannot reproduce your issue with v3 on Window 7.
