### ISSUE TITLE
Failed to load the dll - 0x80070057

### ISSUE THREAD

**Issue by Yousha** [PowerShell/PowerShell#3246]
Steps to reproduce
------------------
Just downloaded PS 6.0.0.16 Alpha x64 then install... when I tried to open it, got this error:
```
Failed to load the dll from [C:\Program Files\PowerShell\6.0.0.16\hostfxr.dll], HRESULT: 0x80070057
The library hostfxr.dll was found, but loading it from C:\Program Files\PowerShell\6.0.0.16\hostfxr.
dll failed
```

Expected behavior
-----------------

Actual behavior
---------------

Environment data
----------------
x64 based system - Windows 7 64bit SP 1 (no updates) - PS 6.0.0.16 Alpha x64

Error
---------------
Failed to load the dll from [C:\Program Files\PowerShell\6.0.0.16\hostfxr.dll], HRESULT: 0x80070057
The library hostfxr.dll was found, but loading it from C:\Program Files\PowerShell\6.0.0.16\hostfxr.
dll failed

**Comment by mirichmo** [comment]
Hi @Yousha. I'm assuming that you are missing the necessary dependencies because you indicated "no updates" in the environment data section. Our downlevel packages have dependencies on components beyond what we ship. You can either install the 
[VC++ redistributable package](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/windows.md#msi) directly or install the [Universal C Runtime](https://www.microsoft.com/en-us/download/details.aspx?id=50410).

I recommend installing the Universal C Runtime to resolve this issue. It is packaged and distributed by Microsoft as an optional package via Windows Update, so you will pick it up automatically if you fully patch your Windows 7 system.

**Comment by Yousha** [comment]
Hi

I have already installed VC++ Runtime libs 2008 to 2015, and both x64 and x86.
Also **Universal C Runtime** **requires Windows updates**, that I didn't install them

I'm using Windows 7 SP1 without any patch/update. (Just like many other people!)

**[NOT A BUG]**
Thanks.
