### ISSUE TITLE
Remove warnings when we run the AppImage format of Powershell

### ISSUE THREAD

**Issue by zaxebo1** [PowerShell/PowerShell#3315]
appimage format of powershell was developed in the issue https://github.com/PowerShell/PowerShell/issues/2024

BUT, Currently when i run (on Debian testing and ubuntu 16.04 both) the downloaded file "PowerShell-x86_64.AppImage" from url https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-alpha.17, **then it first gives the some warnings and then successfully launches Powershell** 

````
myuser1@my-machine1:~$ chmod a+x *.AppImage
myuser1@my-machine1:~$ ./PowerShell-x86_64.AppImage
/bin/bash: /tmp/.mount_kvGjoY/usr/lib/libtinfo.so.5: no version information available (required by /bin/bash)
$XDG_DATA_DIRS is missing. Please run /tmp/.mount_kvGjoY/usr/bin/powershell.wrapper from within an AppImage.
PowerShell 
Copyright (C) Microsoft Corporation. All rights reserved.
PS /home/myuser1> 
````

Are these above warnings OK? **Is there anything which still needs to be done to remove these warnings?**
/bin/bash: /tmp/.mount_kvGjoY/usr/lib/libtinfo.so.5: no version information available (required by /bin/bash)
$XDG_DATA_DIRS is missing. Please run /tmp/.mount_kvGjoY/usr/bin/powershell.wrapper from within an AppImage.

**Comment by TravisEz13** [comment]
@probonopd FYI

**Comment by probonopd** [comment]
This is what I get on `ubuntu-16.04-desktop-amd64.iso`:

```
me@host:~$ /home/me/Downloads/PowerShell-x86_64.AppImage 
PowerShell 
Copyright (C) Microsoft Corporation. All rights reserved.

PS /home/me> cat /etc/lsb-release                                               
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
PS /home/me> exit   
```

So I currently cannot reproduce this, at least not on Ubuntu 16.04.

In any case, I don't think these warnings come from PowerShell itself but rather from the bash script that asks the user whether a menu entry should be installed.

**Comment by probonopd** [comment]
As to the messages themselves:

```
/bin/bash: /tmp/.mount_kvGjoY/usr/lib/libtinfo.so.5: no version information available (required by /bin/bash)
```
This is likely because the `AppRun` script exports `LD_LIBRARY_PATH` to make PowerShell find the bundled libraries that it needs to run. While this works great for PowerShell itself, it may lead to the message above if the system's `bash` from the system is invoked (which it is by the `usr/bin/powershell.wrapper` script that asks the user to install a menu entry) while `LD_LIBRARY_PATH` is set. A cleaner solution may be to set `[rpath](https://enchildfone.wordpress.com/2010/03/23/a-description-of-rpath-origin-ld_library_path-and-portable-linux-binaries/)` inside the PowerShell executable to make it load the bundled libraries,  and not use a `LD_LIBRARY_PATH` at all. This would also have the advantage that `LD_LIBRARY_PATH` would not leak into processes launched from within PowerShell.

```
$XDG_DATA_DIRS is missing. Please run /tmp/.mount_kvGjoY/usr/bin/powershell.wrapper from within an AppImage.
```

This may be a bug in the `usr/bin/powershell.wrapper` bash script. But as mentioned above, I cannot reproduce this. That script could probably be stripped down, rewritten in PowerShell (wouldn't that be cool?) or removed altogether, if it proves to be problematic.

**Comment by zaxebo1** [comment]
some other softwares(other than powershell) while packaging as AppImage had encountered same warnings. Probably links to these discussion with same warnings may help here:
https://debian-facile.org/viewtopic.php?id=15563
https://github.com/probonopd/AppImageKit/issues/208
https://github.com/electron-userland/electron-builder/issues/682
https://github.com/zeit/hyper/issues/551

**Comment by rliessum** [comment]
It also seems to be relevant to Ubuntu 17.04. I just fetched the latest AppImage bin from Github and it produces the same message on two separate Ubuntu 17.04 installations:

richard@Lannister:~/Downloads$ ./PowerShell-6.0.0-alpha.18-x86_64.AppImage 
/bin/bash: /tmp/.mount_Nz8cFY/usr/lib/libtinfo.so.5: no version information available (required by /bin/bash)
PowerShell 
Copyright (C) Microsoft Corporation. All rights reserved.

PS /home/richard/Downloads> cat /etc/lsb-release                                                                                                                                             
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
PS /home/richard/Downloads> exit
