### ISSUE TITLE
Module not found after successful Install-Module

### ISSUE THREAD

**Issue by f0rt** [PowerShell/PowerShell#3338]
Team,

**System**: Windows 10 + Anniversary update, PS 5.1.  

**Issue**: Install-Module cmdlets completes successfully but the installed module is not found after installation. After a short research I've found that the $env:PSModulePath variable doesn't contain the installation path (in this case "C:\Users\<username>\Documents\WindowsPowerShell\Modules").  The variable $env:PSModulePath is not modified by the user. Adding the path to $env:PSModulePath resolves the issue. Let me know if you need more information.

Thanks,
Nedko

**Comment by systemmetaphor** [comment]
I think I have a similar issue. 

I use Install-Module to deploy xWebAdministration and after successfull installation I am able to generate the configuration mof file but when I try to apply the configuration LCM returns an error indicating the module does not exist. All happens in the same machine.

This is with powershell 5.0.10586.117

**Comment by systemmetaphor** [comment]
Just for the reference I realized this is kind of by design because when the configuration is being applied it runs in system context and it can only see the $env::programfiles modules.

https://blogs.msdn.microsoft.com/powershell/2013/12/05/how-to-deploy-and-discover-windows-powershell-desired-state-configuration-resources/


Basically I need to deploy the modules to the correct path manually, make sure LCM is correctly configured or use a pull server.

**Comment by joeyaiello** [comment]
@f0rt This looks like a problem with your `PSModulePath` rather than PowerShellGet. 

The default state of `PSModulePath` is for the system variable to point to `%SystemRoot%\system32\WindowsPowerShell\v1.0\Modules\`, and the user variable should not exist. At runtime, we prepend `$env:PSModulePath` with `C:\Users<username>\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules`. 

If that's not happening on your end, I'd really appreciate some more info on:
* how you're launching PowerShell (is it from a shortcut on the taskbar or the start menu? Or is it from the Start->Run/Win+R?) 
* What your system and user environment variables for PSModulePath look like, preferably from the System GUI, e.g. 
![image](https://cloud.githubusercontent.com/assets/1255187/24052989/b112d6d2-0af4-11e7-9180-cd276c94212b.png)

**Comment by harre096** [comment]
My standing workaround is `$env:PSModulePath += ";C:\Users\$($env:UserName)\D
ocuments\PowerShell\Modules"`.

**Comment by bdwakefield** [comment]
> My standing workaround is `$env:PSModulePath += ";C:\Users\$($env:UserName)\Documents\PowerShell\Modules"`.

Added this to my profile; works like a charm. Fought with this for over an hour. Couldn't figure out why the modules would install but not import.

**Comment by mamhh** [comment]
@joeyaiello @harre096 .. I'm facing the same issue .. please elaborate more in order to fix it
