### ISSUE TITLE
Question: Performance impact of large module manifests

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#3340]
Are there any recommendations on the maximum number of PowerShell functions / cmdlets that should exist inside of PowerShell module manifests? Say, for example, that you put 300,000 items without wildcards in the `FunctionsToExport` manifest key. Would this be expected to have a serious, negative impact on performance of the shell? Why or why not?

I'm less interested in the discussion around module design (eg. "*why would you even do that?*"), and more interested in discussion of performance around this scenario.

Cheers,
Trevor Sullivan

**Comment by SteveL-MSFT** [comment]
Cc @PowerShell/area-performance

**Comment by lzybkr** [comment]
This is a rather open ended question, so, I'll do my best.

First, I'll assume we're talking about a script module because you mentioned `FunctionsToExport`.

There are many scenarios to consider. I'll start with - module is installed but not used in the first PowerShell session on the box or after the module is installed *and* you run `& "command doesn't exist" `  so that it searches all modules for this fictional command.

In this scenario, most of the overhead will come from parsing.

A large module manifest is most likely better than a wildcard because PowerShell tries to discover what commands are in the module before considering other modules. When the manifest can't answer that question, PowerShell falls back to analyzing the `psm1`.

If the `psm1` defines all of those functions (possibly dot sourcing many files) or uses `Export-ModuleMember` without wildcards, parsing the `psm1` and included `ps1` files will be roughly as much or more work than parsing the manifest alone.

If the functions are defined dynamically or some other way that command discovery cannot statically determine the commands, then a script module may be a performance win in this scenario, though I think such a module would not work with auto-loading.

The trade-offs might be different if you expect the module is used in every session. I won't attempt to describe other scenarios without better understanding more about how such a module might be used.

I will say that you should be prepared for many performance issues with such a module beyond the manifest - PowerShell has not been tuned for this scenario.

**Comment by pcgeek86** [comment]
Good points, Jason.

- I am actually referring to either binary or script modules, with a manifest. Good catch though. I mentioned `FunctionsToExport`, because that's the one I most commonly use.
- Thanks for confirming my suspicion that a large module manifest is better than using wildcards.
- We are not interested in creating modules, of either script or binary type, without manifests, so this scenario isn't relevant.

The reason I'm approaching this is because right now, certain PowerShell modules with large numbers of cmdlets (single-digit thousands) do not have their commands exposed in the module manifest. This means that tab-completion for those commands is not available, unless the user explicitly imports the module that contains the commands.

Some people have expressed concern around putting thousands of cmdlet names into a module manifest, suggesting that it could impact performance.

I am simply attempting to dispel those concerns through testing and validation from the PowerShell team. So far, we haven't seen any major PowerShell Core startup performance impact by placing thousands of commands into a module manifest, using a test build.

I figured that the PowerShell team had already discussed this scenario extensively internally, over the years that PowerShell has existed, and am just trying to leverage that knowledge.

Cheers,
Trevor Sullivan
