### ISSUE TITLE
The windows installer should create a common path you can run the latest powershell from

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#3464]
Steps to reproduce
------------------
Install multiple versions of powershell

Expected behavior
-----------------
The should be a common path where you can run the latest version of powershell.  Linux does this by creating a symbolic link.  We do it in the windows docker files by creating a symbolic link to the latest version.

Actual behavior
---------------
you have to figure out the latest version

**Comment by SteveL-MSFT** [comment]
Currently on Windows, you have to do something like:

```powershell
C:\> c:\pro<tab>\pow<tab>\6<tab>\powershell
```

And if you have multiple versions installed (which is currently the default), you have to tab through the older ones first (if you didn't uninstall them).  Would prefer something like:

```powershell
C:\> c:\pro<tab>\pow<tab>\l<tab>\powershell
```

We can even save typing `l` for latest by having it `.latest` to ensure it's first.

Another pain point is that powershell.exe is third file to be tab completed under it's version folder.  Perhaps what we really need is something like `set-defaultpowershell` which creates/updates a symlink that is in the user path so `win+r->powershell` starts it.

**Comment by SteveL-MSFT** [comment]
CC @joeyaiello

**Comment by iSazonov** [comment]
We need to take into account that initially PowerShell 6 Core will coexist with Windows PowerShell. There may be a conflict with paths (to modules including).

**Comment by mirichmo** [comment]
#1192 is somewhat related where we played around with the idea of a common executable or script.

C:\program files\powershell\powershell.exe as a symbolic link to a version-specific instance of PowerShell Core would satisfy the requirement.

@iSazonov - We constructed the module paths so that the default paths do not overlap. Path resolution conflicts for executables are handled in a first-come-first-served, so users will have to include the path to PowerShell Core's exe first if they want it to be their default powershell.

**Comment by TravisEz13** [comment]
In docker containers, we are using `C:\program files\powershell\latest` as symbolic link to the version we installed

**Comment by iSazonov** [comment]
I agree that it should be `symbolic link to folder`.

**Comment by TravisEz13** [comment]
fixed by https://github.com/PowerShell/PowerShell/pull/6442
