### ISSUE TITLE
Allow Enums to be Nullable

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#3542]
Got this one [filed on UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11454600-bug-nullable-enum-dsc-property-throws-system-n) and discussed it again at PS Summit NA 2017. It seems like a small thing, but it's blocking usage of class-based resources to the point that they have to install WMF 5 Production Preview on their build servers in order to compile their MOFs. They have no problem using PowerShell 6 on their build servers to do the same if we make the fix here. 

Steps to reproduce
------------------
Create a new DSC Resource module called `EnumTest`. Create your module manifest and set the .psm1 file content to:

```powershell
enum MyEnum { 
    Test 
    Setting 
}

[DscResource()] 
Class MyTestResource { 
    [DscProperty(Key)] 
    [String] $MyKey

    [DscProperty()] 
    [nullable[MyEnum]] $MyEnum

    [Void] Set() { 
        $null 
    }

    [Boolean] Test() { 
        return $true 
    }

    [MyTestResource] Get() { 
        Return [MyTestResource] 
    } 
}
```

Following, try to create a Configuration with the following code and the 'Import-DscResource' keyword will be underlined with an error.

```powershell
Configuration MyEnumTest { 
    Param ( 
    [Parameter(Mandatory=$true)] 
    [string]$ComputerName 
    )

    Import-DscResource -ModuleName EnumTest

    Node $ComputerName { 
        EnumTest Test { 
            MyKey = 'Blah' 
            MyEnum = 'Setting' 
        }
    } 
}

$null = MyEnumTest -ComputerName $env:COMPUTERNAME
```

Expected behavior
-----------------
The configuration should compile into a MOF document. 

Actual behavior
---------------
The `Import-DscResource -ModuleName EnumTest` is underlined in red and the configuration does not compile. 

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSRemotingProtocolVersion      2.3
GitCommitId                    v6.0.0-alpha.17
CLRVersion
PSEdition                      Core
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
PSVersion                      6.0.0-alpha
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
```

**Comment by Soolkiki** [comment]
I see this hasn't been touched in 3 years. Is there any other way to work around this? I'm using 5.1 since it's what comes with Windows Server 2019 and this is really breaking things.

**Comment by jzabroski** [comment]
@Soolkiki I doubt you'll see any traction on this.  Yes, it sucks, because it feels like every desired state configuration tool (Chef, Puppet, SaltStack) has some ugly usability issues tied to the programming environment (e.g., for years Chef used a version of Ruby that did not ship with any easy way to output logs to standard out...).  As much has been said about DevOps, little gets done, especially on Windows, which is why Hashicorp TerraForm became so popular, because it actually works, unlike stuff Microsoft started and then abandoned.

**Comment by Soolkiki** [comment]
That is frustrating...I suppose I'll just add a None first value to my enums to get around it.
Thank you

**Comment by schittli** [comment]
While we customers pay M$ so many billions of US$ that no human can count it, M$$ fails to hire developers so that meaningful suggestions from customers don't take 1/2 decade?

Just FYI:
The shame is not minor when a robot closes such feedback just because not so many customers study and vote for Issues all the time.

It would be great if M$ actually shows interest in having satisfied customers.
Guess what: just pretending to be interested is also a shame.
