### ISSUE TITLE
Characters taking more than one cell space on buffer, with overlapping text. [Since Creator's Update]

### ISSUE THREAD

**Issue by avdaredevil** [PowerShell/PowerShell#3601]
_**Note:** This issue has surfaced on my console, after my computer updated with the **Creator's Update**_

Steps to reproduce
------------------
- Install https://github.com/nicolalamacchia/powerline-consolas/blob/master/consola.ttf
- Set font to Consolas (not **BOLD**)
- I do it by:
    ```
    item HKCU:\Console\%SystemRoot%_System32_WindowsPowerShell_v1.0_powershell.exe | Set-ItemProperty -Name FaceName -Value "Consolas"
    ```
- Then run:
    ```
    $c=[Char]57520;Write-Host "Test${c}Test${c}${c}${c}a"
    ```
- Now use your cursor to select some of them. I have the character selecting 2 cells at once! (Or at least seeming like 1 character is taking up 2 cells, which I don't think was even possible in the previous versions of PowerShell)

Expected behavior
-----------------
- All of these symbols are single-spaced, and when selected and printed should only take one cell, and not look like they have a *ghost space* after them.

Actual behavior
---------------
| After print: | On Selection: | On different Selection: |
| --- | --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/5303018/25206963/4ed688ec-2539-11e7-82c2-f8df84310963.png) | ![image](https://cloud.githubusercontent.com/assets/5303018/25206970/6880a944-2539-11e7-8dd6-7a2271cbb053.png) | ![image](https://cloud.githubusercontent.com/assets/5303018/25206978/7a346824-2539-11e7-9e1c-8b512798f8fa.png) |

Environment data
----------------
- Background: `Black`
- Foreground: `DarkYellow` (which always looks white)

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.138
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.138
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by lzybkr** [comment]
Based on the repro, I would say this issue has nothing to do with PowerShell.

I'm not installing the font, but I have another font (Fira Code) that renders those characters correctly, and I can't repro.

I'm guessing the problem is either the font or conhost. You should try to narrow down where the problem is, e.g. try to repro in cmd (maybe write a C# program to print those characters).

Also try changing the font after the characters are on the screen, if selection works as expected with one font, but not your version of Consolas, I might suspect the font.

If you narrow it down to conhost, you can report it [here](https://github.com/microsoft/bashonwindows).
