### ISSUE TITLE
Implement Enable-SSHRemoting cmdlet

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#3616]
We need an Enable-SSHRemoting cmdlet, similar to existing Enable-PSSession cmdlet for WinRM based remoting, to set up SSH remoting on supported platforms.  This would make using SSH remoting easier to use and also allow automated testing of SSH remoting.

https://github.com/PowerShell/PowerShell-RFC/blob/master/1-Draft/RFC0012-Enable-SSH-Remoting.md

**Comment by RichardSiddaway** [comment]
Agreed

Configuring SSH for remoting is tsk that is better automated if at all possible

**Comment by joeyaiello** [comment]
Per conversation with @SteveL-MSFT, we might want to push this out depending on how the Win32-OpenSSH work lands. 

It might even make sense to push this work out to after the OpenSSH work lands to make sure that we don't end up having to do breaking changes if/when the configuration mechanisms for Win32-OpenSSH change.

**Comment by SteveL-MSFT** [comment]
I think what we may end up doing is just having a setup script in the demo folder and we can blog about it to inform users of it's existence who don't work out of GitHub

**Comment by PaulHigin** [comment]
I am working on a set up script right now as a prototype for the Cmdlet.  I don't think we should worry about Win32-OpenSSH breaking PowerShell remoting since it is intended to be closely compatible with other platform versions of SSH.

**Comment by SteveL-MSFT** [comment]
I think we can publish this in PowerShellGallery initially and target inclusion in the package for 6.1.0

**Comment by soul4soul** [comment]
Two years later I'm still hoping this is implemented. I just had to write PS scripts to do this while provisioning Windows 7 and Windows 10 PCs. For windows 10 I followed several articles on docs.microsoft.com [[1]](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-6#how-to-create-a-remoting-endpoint)[[2]](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse). For Windows 7 I used chocolatey.

For configuring the keys I followed the guide at https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement. It'd be nice to see `Repair-AuthorizedKeyPermission` fixed with this effort too.

**Comment by SteveL-MSFT** [comment]
@PaulHigin has a working version, just need to publish to PSGallery.  Won't be in PS7, but can be in 7.1.

**Comment by PaulHigin** [comment]
A version 0.1.0 of PowerShell remoting tools module has been published, and which contains the Enable-SSHRemoting cmdlet.

https://www.powershellgallery.com/packages/Microsoft.PowerShell.RemotingTools/0.1.0
