### ISSUE TITLE
Require Docs to Be Available Online

### ISSUE THREAD

**Issue by michaeltlombardi** [PowerShell/PowerShell#3636]
## Expected Behavior
When using PowerShell of any version, I should be able to review published online documentation for the version of PowerShell I am using in an easily discoverable location.

## Current Behavior
Documentation exists online in properly published formats for PowerShell versions `5.1` and below.
Currently, the documentation for `6.x` lives only in the markdown documents of the repository and is not published outside of this.

## Possible Solution
Publish the documentation, but be clear that `6.x` is not released yet (as currently done in the docs inside the repo).

## Context
A naive user of PowerShell, particularly cross-platform PowerShell v6, may not necessarily know to go check the repository for documentation. Moreover, if the docs are not easily discoverable from a google search of "PowerShell Docs version 6" or similar, they may as well not exist for a segment of the user base.

Publishing the documentation makes it easier for folks to dive into the documents and to provide feedback/actually use the documents in testing scenarios. Of course, avoiding a conflict with the documentation for released PowerShell versions is a concern, but being clear and up front about v6's state in the docs will help with this.

**Comment by zjalexander** [comment]
Thanks for posting this - I was hitting the Twitter character limit :)

There are several issues here.

1) PowerShell 6 has [some, but not all, documentation here ](https://github.com/PowerShell/PowerShell-Docs/tree/staging/reference/6). It's a work in progress, as to be expected from an alpha.

2) PowerShell 6 has [some other documentation here](https://github.com/PowerShell/PowerShell/tree/master/docs) - this is intended to be more specific for a developer audience and not intended to go into the console help.

3) PowerShell-Docs [does not yet flow into get-help](https://github.com/PowerShell/PowerShell-Docs/issues/1073). This is a known issue and actively being worked on. When the issue is addressed, PowerShell 6 help in the PowerShell-Docs/reference/6 folder will reach the console.

**Comment by michaeltlombardi** [comment]
Is there a plan for the second set of docs to be published via a method other-than-repo-markdown files? It sounds like the first and third pieces are going to be addressed.

I also strongly encourage the second set of docs - essentially, concept guides for contributing to and understanding PowerShell at a deeper level - make their way into `about_` files readable from the console. If I'm working on something and I can get 80% of my docs locally but have to reach out to a repo for the other 20%, that's not a great story.

**Comment by joeyaiello** [comment]
Yeah, we know we need to do it. There's a [6.0 reference set over in PowerShell-Docs right now](https://github.com/PowerShell/PowerShell-Docs/tree/staging/reference/6), we're starting to make progress in moving stuff over there. (/cc @juanpablojofre)

There's still a few docs, though, that I think ultimately should not be included in PowerShell (e.g. running our repo-specific build/tests, governance of the project, etc.) Unless you disagree, I think it's acceptable that those are brought down at repo-clone time.

**Comment by michaeltlombardi** [comment]
Repo specific build and test docs are probably best left to here, not sure about governance though. That might not make sense to have available via `Get-Help`, but should probably be available if only as github pages or on https://docs.microsoft.com

But those are all a secondary concern to getting the core set of docs (reference and concept both) published and available.
