### ISSUE TITLE
enable support for chocolately delivered shims

### ISSUE THREAD

**Issue by surlypants** [PowerShell/PowerShell#3672]
enable support for chocolately delivered shims (https://chocolatey.org/docs/features-shim)

path set as:
$env:Path = "C:\Program Files\PowerShell\6.0.0-alpha.18;C:\Program Files\OpenSSH-Win64"

allows new-pssession to successfully call ssh.exe (directly)

path set as:
$env:Path = "C:\Program Files\PowerShell\6.0.0-alpha.18;C:\ProgramData\chocolatey\bin;C:\Program Files\OpenSSH-Win64"

prevents new-pssession from calling ssh.exe (via chocolately-delivered shim), with error:

The background process reported an error with the following message: The SSH client session has ended with error message: The input line is too long..

$psversiontable

Name                           Value
----                           -----
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-alpha.18-39-gc0aafdb3d034ccc5d2e1d0744...
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSEdition                      Core
PSRemotingProtocolVersion      2.3
PSVersion                      6.0.0-alpha
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

(Get-Command ssh).Path
C:\ProgramData\chocolatey\bin\ssh.exe

ssh -V
OpenSSH_7.5p1, OpenSSL 1.0.2d 9 Jul 2015

**Comment by iSazonov** [comment]
@DarwinJS   Could you please comment the Issue?

**Comment by DarwinJS** [comment]
@surlypants this is happening because you also have the "OpenSSH (mls-software)" chocolatey package installed which puts those shims in place. (https://chocolatey.org/packages/mls-software-openssh).

Please uninstall openssh (mls-software) with `choco install mls-software-openssh` and then ensure $env:chocolateyinstall\bin does NOT have any shims for any file like "ssh*.exe"

The OpenSSH package from the PowerShell open source project does not create shims (https://chocolatey.org/packages/openssh)

@iSazonov - this could be an ongoing issue for people who have installed more than one SSH client.  Maybe new-pssession should check and report on which ssh.exe it finds.  If PS remoting is only supported with Microsoft's client - you could give an error.

**Comment by surlypants** [comment]
it would appear to me that https://chocolatey.org/packages/openssh does in fact deliver shimmed EXEs. hence this report.

$ choco search ssh |grep mls

mls-software-openssh 7.5.1.1 [Approved] Downloads cached for licensed users


$ choco list -lo |grep ssh

openssh 0.0.12.0

**Comment by DarwinJS** [comment]
In your original post `ssh -V` delivered `OpenSSH_7.5p1` so I assumed it was that package - good work finding the original culprit.

For anyone else following or finding this thread - the openssh chocolatey package does not generate shims.

Apologies @bagajjal - I have to loop in our conversation here https://github.com/DarwinJS/ChocoPackages/issues/28 to add a case in point of why I am not a fan of using the path for critical software dependencies.

**Comment by iSazonov** [comment]
@DarwinJS Thanks for comments!
@surlypants Nothing can be done in the repo. We close the Issue as External.
