### ISSUE TITLE
Strange Get-Random Input-Object parameter behaviour

### ISSUE THREAD

**Issue by KacperMucha** [PowerShell/PowerShell#3682]
Steps to reproduce
------------------
```powershell
Get-Random -InputObject @('zzz', 'aaa', '')
Get-Random @('zzz', 'aaa', '')
```
Expected behavior
-----------------
InputObject parameter position value is 1, so these command should work the same way and return one of the array elements.

Actual behavior
---------------
While the second command works, first command produces error:
```powershell
Get-Random : Cannot validate argument on parameter 'InputObject'. The argument is null or empty. Provide an argument th
at is not null or empty, and then try the command again.
At line:1 char:25
+ Get-Random -InputObject @('zzz', 'aaa', '')
+                         ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Random], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.GetRandomCommand
```
Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.3
BuildVersion                   3.0.0.0
WSManStackVersion              3.0
PSVersion                      6.0.0-alpha
CLRVersion
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
GitCommitId                    v6.0.0-alpha.18

Name                           Value
----                           -----
PSVersion                      5.1.15063.138
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.138
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by benny-gold** [comment]
I'm seeing this behaviour too. 
```powershell
$DomainListSource = "https://raw.githubusercontent.com/opendns/public-domain-lists/master/opendns-top-domains.txt"
$domainlistMaster = (Invoke-RestMethod -useBasicParsing -uri $domainListSource) -split "`n"
Get-Random $domainlistMaster -Count 50 
Get-Random : Cannot validate argument on parameter 'InputObject'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

```

```powershell
Name                           Value                                                                                                                                                                                 
----                           -----                                                                                                                                                                                 
PSVersion                      5.0.10586.117                                                                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                               
BuildVersion                   10.0.10586.117                                                                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                                                                       
WSManStackVersion              3.0                                                                                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                                                                                   
SerializationVersion           1.1.0.1                                                                                                                                                                               
```

**Comment by iSazonov** [comment]
This is a nasty bug in parameter binding.

@SteveL-MSFT @daxian-dbw @mklement0  for information.

**Comment by SteveL-MSFT** [comment]
This isn't an issue in the parameter binder.  The default parameter set is for `-Maximum`, not `-InputObject`.  `InputObject` [has](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs#L278) `[ValidateNotNullOrEmpty]` whereas `Maximum` does not.  This attribute also checks if the collection contains `$null` (or empty string which is equivalent for strings).  And this is what's causing the error message.  Removing that attribute "fixes" this issue.  Would need to think through any side effects.  Since that parameter is mandatory, you can't pass in `$null` anyways.

**Comment by mklement0** [comment]
@benny-gold: Your example is missing the `-InputObject` parameter for reproducing the symptom; as an aside: given that the list you're retrieving by definition has no line-internal spaces, the better command to use is `$domainlistMaster = -split (Invoke-RestMethod -useBasicParsing -uri $domainListSource)`, which bypasses the bug.

@SteveL-MSFT:

* Removing the `ValidateNotNullOrEmpty` strikes me as the right thing to do, because there is no reason to prevent pulling random elements from collections only because they happen to have empty elements.

  * Perhaps the intent was to prevent passing an empty _scalar_ (e.g., `Get-Random -InputObject $null`), but (a) with an `[object[]]`-typed parameter that emptiness check is invariably also applied to the _elements_ of the array individually; and (b), even an empty scalar isn't worth preventing.

As for what parameter is bound with a _positional_ argument:

* Due to trickery in [GetRandomCommand.cs](https://github.com/PowerShell/PowerShell/blob/eb2220632cf43d40273844ff98b162e704286900/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs#L60) `-Maximum` is _ultimately not_ bound if its argument is an _array_: the code checks for an array-valued argument and, if so, assigns to `InputObject` instead.

* The upshot is:

  * Using an array _positionally_ accidentally _bypasses_ the `ValidateNotNull` validation attribute, because the argument is _initially_ bound to `-Maximum`, which doesn't have this attribute; therefore, it is only positional use with an array that currently - accidentally - exhibits the desired behavior.

  * The trickery enables questionable commands such as `Get-Random -Maximum (1..10) -Count 3`, which is effectively the same as `Get-Random -InputObject (1..10) -Count 3`

**Comment by SteveL-MSFT** [comment]
I'm also thinking that removing `[ValidateNotNullOrEmpty]` is the right thing and shouldn't have any negative side effects.  I'll submit a PR.

**Comment by DougChandler** [comment]
I am seeing this bug in PS 5.1. Very strange behaviour.
```
Name                           Value                                                                                                                                                              
----                           -----                                                                                                                                                              
PSVersion                      5.1.14393.3866                                                                                                                                                     
PSEdition                      Desktop                                                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                            
BuildVersion                   10.0.14393.3866                                                                                                                                                    
CLRVersion                     4.0.30319.42000                                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                                
SerializationVersion           1.1.0.1      

```
I am passing in an array which contains an empty string as an element as that is one of the choices I want to be chosen.

**Comment by mklement0** [comment]
@DougChandler, please note that this is repo is for PowerShell (Core) only (v6+).

For Windows PowerShell, you can file an issue at its [UserVoice forum](https://windowsserver.uservoice.com/forums/301869-powershell), but note that Windows PowerShell is no longer actively developed and will likely only receive critical security fixes.
