### ISSUE TITLE
Bash Commands in Quoted Subexpression Operator Replaces Newlines With Spaces

### ISSUE THREAD

**Issue by bigboy-pdb-spam** [PowerShell/PowerShell#3702]
Steps to reproduce
------------------
- Create a file called test.txt containing the following contents: a&lt;tab&gt;b&lt;newline&gt;c
(where &lt;tab&gt; is the tab character and &lt;newline&gt; is the newline character).
- Open PowerShell in the same directory.
- Run the following Bash commands where the output (listed below each command) is labelled as incorrect.
- The PowerShell output with the string "a&#96;tb&#96;nc", which is equivalent to the file contents, is listed below the Bash examples.

`# Bash cat output (INCORRECT)`

`PS > "$(cat test.txt)"`
`# Output:`
`a<tab>b c`

`# Bash cat output piped to octal dump (INCORRECT)`

`PS > "$(cat test.txt)" | od -c`
`# Output:`
`0000000   a  \t   b  <space>   c  \n`
`0000006`

`# PowerShell string output (CORRECT)`

`PS > "$("a`&#96;`tb`&#96;`nc")"`
`# Output:`
`a<tab>b`
`c`

`# PowerShell string output piped to octal dump (CORRECT)`

`PS > "$("a`&#96;`tb`&#96;`nc")" | od -c`
`# Output:`
`0000000   a  \t   b  \n   c  \n`
`0000006`

Expected behavior
-----------------
`PS > "$(cat test.txt)"`
`# Output:`
`a<tab>b`
`c`

`PS > "$(cat test.txt)" | od -c`
`# Output:`
`0000000   a  \t   b  \n   c  \n`
`0000006`

Actual behavior
---------------
`PS > "$(cat test.txt)"`
`# Output:`
`a<tab>b c`

`PS > "$(cat test.txt)" | od -c`
`# Output:`
`0000000   a  \t   b  <space>   c  \n`
`0000006`

Environment data
----------------
Dell Vostro 1400
Linux Mint 18.1 Serena Cinnamon 64bit

# Linux System Information
$ for i in m p o s r v; do echo "uname -$i: $(uname "-$i")"; done
uname -m: x86_64
uname -p: x86_64
uname -o: GNU/Linux
uname -s: Linux
uname -r: 4.4.0-72-generic
uname -v: #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017

```powershell
> $PSVersionTable

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.18                                 
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1
```

**Comment by mklement0** [comment]
This is actually by design, though it may not be obvious:

PowerShell collects stdout output from calls to external utilities as an _array of lines_.

Thus, your `cat test.txt` command results in 2-element array `` "a`tb", "c" ``.

In the context of string interpolation, PowerShell represents an array as the concatenation of its elements separated by `$OFS`, which defaults to a single space.

In other words, the string-interpolated value of array `` "a`tb", "c" `` is `` "a`tb c" ``, which is what you saw.
Incidentally, you'd get the same result with `Get-Content` without the `-Raw` switch.

There are several ways around this:

* Use `Get-Content -Raw`, which reads the entire file as a single string:

`"$(Get-Content -raw test.txt)"`

* Use the `-join` operator on the output captured from `cat`:

`"$((cat test.txt) -join "`n")"`

* Set `$OFS` to a newline - note the call via a script block and `&` to ensure that the `$OFS` change is localized:

`& { $OFS="`n"; "$(cat test.txt; )" }`

**Comment by bigboy-pdb-spam** [comment]
Thank you for the response. I was testing how easy it was to use bash commands within PowerShell. The join method appears to work well when data needs to be modified further. For example, if you're using the find command to perform a search that cannot be easily replicated in PowerShell.

`` PS> touch "a`nb.txt" 'ab.txt' ``
`` PS> (find -name 'a*b.txt' -print0) -join "`n" -replace "`0`$" -split "`0" | ``
`ForEach { "File: $_" }`
`# Output:`
`# File: ./ab.txt`
`# File: ./a`
`# b.txt`
