### ISSUE TITLE
The automatical completion of powershell do not work wilk

### ISSUE THREAD

**Issue by Qinka** [PowerShell/PowerShell#3737]
When using auto-completion in powershell at Windows to compress the file with tar and xz, installed in msys2. 
The powershell will add .\ to the file name. And the "prefix" will be considered as the part of the name not the path.
For example, when the dir, named eg, needed to be compresses with tar and xz, will type in

```powershell
> tar cvf eg.tar e
```

And then, press the TAB.
Then : 

```powershell
> tar cvf eg.tar .\eg
```

Then at the other system, such as macOS:
```bash
tar tf eg.tar.xz
```

THE OUTPUT is
```
.\eg/
.\eg/some/files
```

And I thought that is the bug of the gnu's tools, but I can not find where to report the bug, so I here report the bug.

I am using Windows 10 Pro (insider), and msys2.

**Comment by SteveL-MSFT** [comment]
Didn't notice you were using Windows PowerShell.  Since you are running this on Windows, the backslash is the appropriate path separator.  PowerShell can't know that tar expects forward slashes (note that when running PSCore6 on Mac/Linux, it will auto-complete with the correct slash).  Unfortunately the change would have to be in tar.
