### ISSUE TITLE
Common parameters -OutVariable, -ErrorVariable, -WarningVariable, and -InformationVariable always return a [System.Collections.ArrayList] instance, even with a single object

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3773]
Note: The problem was first discovered with `-OutVariable`  - see  #3154.  
The problem applies to all `-*Variable` common parameters, however, with the exception of `-PipelineVariable` (which inherently captures a _single_ item at time).

To recap the problem:

* Even if only a _single_ value is captured by these parameters, an _array list_ rather than a scalar is returned (the single-element collection isn't unwrapped - a deviation from PowerShell's normal collection handling).

* Also - another deviation from usual PowerShell behavior - it is type `[System.Collections.ArrayList]` that is always used, in contrast with the `[System.Object[]]` instances you get with _regular_ assignments.

Steps to reproduce
------------------

```powershell
# Adv. function that outputs a single item of each type.
function foo {
  [CmdletBinding()]
  param()
  
  Write-Warning 'warn'
  Write-Information 'info'
  Write-Error 'err'
  'out'
}

foo -OutVariable ov -ErrorVariable ev -WarningVariable wv -InformationVariable iv  *>$null

$ov, $ev, $wv, $iv | % GetType | % Name
```

Expected behavior
-----------------

```
String
ErrorRecord
WarningRecord
InformationRecord
```

Actual behavior
---------------

```
ArrayList
ArrayList
ArrayList
ArrayList
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta (v6.0.0-beta.1)
```

**Comment by Jaykul** [comment]
While I agree that it's weird that this doesn't behave like pipeline output (and I insist that the *only* thing that PowerShell does this for is pipeline output) ...

It has been like this since the beginning.

Changing it at this point doesn't help much, and risks breaking all existing code that relies on these common parameters ...

**Comment by mklement0** [comment]
@Jaykul: If the consensus is that this change is too risky, so be it, and _documenting_ the issue is the best we can do.
Personally, I think it's a wart that warrants removal - it can trip up new users (as it did me).

> and I insist that the only thing that PowerShell does this for is pipeline output

That is not much of a restriction, however, given the pervasive use of pipelines, even in places where it is not obvious:`$(...)`, `@(...)`, `&`, `.`,  script-block arguments.

To give a few examples, all of which output `$True`:

```powershell
$(, 1) -is [int]
(. { , 1 }) -is [int]
(& { , 1 }) -is [int]
('' | Select-Object @{ n='foo'; e = { , 1 } }).foo -is [int]
```

<sup>There is no `@(...)` example, because `@(...)` by design ensures _array-valued_ output - though it would still recreate any input collection as a `[object[]]` array.</sup>

**Comment by Jaykul** [comment]
The point is: you're saying you want to change 4 common parameters (two of which have been around since the beginning) to change their type after the end of the pipeline (they obviously still have to be an Arraylist within the pipeline). That's a serious breaking change.

Your justification is just that you want it to be more like pipeline output.

My point is that making these common parameters more like pipeline output doesn't seem like a useful goal. They are not _like_ pipeline output -- they are output _parameters_. In fact, sometimes (when you use the +name syntax) they are actually _reference_ parameters. Additionally, _they exist within_ the pipeline. -- where they are more like streams than a finished output collection -- and changing them from the live stream type to something else at the end would just be confusing.
