### ISSUE TITLE
Get-ACL doesn't support -Credential? 

### ISSUE THREAD

**Issue by PsychoData** [PowerShell/PowerShell#3777]
How come Get-ACL doesn't have -Credential support?

**Comment by mklement0** [comment]
Your question will probably get more attention if you explain _why_  `Get-Acl` should have that parameter.

Run `Get-Acl` from an _elevated_ session to avoid problems stemming from lack of permissions.

**Comment by PsychoData** [comment]
Here is my thing. My regular account doesn't have credentials to get into
even the root folder holding our home network drives.

If I had -credential I could prompt or pass my file system admin or domain
admin credential object to it and get in their content

On May 13, 2017 12:55 PM, "Michael Klement" <notifications@github.com>
wrote:

Your question will probably get more attention if you explain *why* Get-Acl
should have that parameter.

Run Get-Acl from an *elevated* session to avoid problems stemming from lack
of permissions.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PowerShell/PowerShell/issues/3777#issuecomment-301260436>,
or mute the thread

**Comment by mklement0** [comment]
To _generalize_ your requirement: you want an on-demand method for invoking a given command _with elevation_, similar to what `sudo` does in the Unix world.

That would indeed be helpful, and is already being discussed in #3232.

Unless this anticipated _generic_ mechanism still wouldn't meet your needs, I suggest you close this issue.

**Comment by PsychoData** [comment]
I don't see why you wouldn't want to have -Credential on it so you can call
it as another user?

Like how you can say 'Get-Aduser username -Credential $DAcred'

I also have fields hidden from my regular, daily driver user that are
visible from my admin account. Like employee number and Administrator
password are visible to my server admin account and above, but not that
lower account.

Same type of thing, just filesystem right now instead of AD.

**Comment by mklement0** [comment]
I just realized that far more cmdlets that I was aware of in fact do have a `-Credential` parameter:

    $VerbosePreference = 'Continue'
    Get-Command -type cmdlet | ? { $c = $_; try { $_.Parameters.ContainsKey('Credential') } catch { write-verbose "Failed with: $c" } }

Still:

* It's not readily obvious to me which cmdlets were given this parameter vs. which were not.

*  It seems to me that solving this problem at the level of _individual cmdlets_ is the wrong approach.

That said, I'll leave it to someone more knowledgeable to take it from here.

**Comment by rahulduggal18** [comment]
Can't use the Invoke-Command to elevate ?
Example,  Invoke-Command -ComputerName . -ScriptBlock {get-acl} -Credential (Get-Credential)

**Comment by SotoDucani** [comment]
I'll agree and bump this a little. Unlike #2761 and #2975 (similar -Credential requests), there doesn't seem to be any restriction that prevents a -Credential parameter from being implemented. I only took a quick look through the .NET docs on ACL classes, so I very well could be wrong on that.

While Invoke-Command would work, it would force a weird usage in my opinion. Everything I've used so far supports -Credential, then all of a sudden for working with ACL's I'd have to shove the ~10 lines of logic into a scriptblock and either choose to invoke it against localhost or the remote computer that holds the file shares (since Invoke-Command requires a -ComputerName when -Credential is used). That's not a fantastic option since it additionally requires remoting to be available when Get-ACL only requires Share\NTFS permissions regardless of local vs remote file locations.

**Comment by charltonstanley** [comment]
I agree with others on this thread: A `Credential` parameter that accepts type `[System.Management.Automation.PSCredential]` would be extremely useful for the `Get-ACL` (and associated) cmdlets.

**Comment by mklement0** [comment]
I realize that I've conflated two things earlier:

* running in the context of a given user account
* running _with elevation_ (as admin, of necessity in a separate process)

If no actual elevation is required - just a different user's context - then I can see the value of adding this parameter to `Get-Acl`

**Comment by charltonstanley** [comment]
> If no actual elevation is required - just a different user's context - then I can see the value of adding this parameter to `Get-Acl`

That is exactly it. I don't need a `Credential` parameter to elevate. However I do need it to leverage an account that has the required permissions necessary to read the ACL of the target path.

**Comment by iSazonov** [comment]
Users will expect that elevation works. It is bad UX.

**Comment by dogfish182** [comment]
I just ran into this with 'set-acl' and my script that runs otherwise unpriviliged/lower privileged needs to elevate to provision control over an OU that I create with some automation. how would I solve this?

**Comment by iSazonov** [comment]
The Get-Acl cmdlet uses reflection to invoke a method to get acl
```c#
PSMethodInfo methodInfo = _inputObject.Methods["GetSecurityDescriptor"];
```

So you should previously create the input object with elevated permissions.

**Comment by dogfish182** [comment]
makes things hugely difficult. i'm running a script that's delivered by aws systems manager agent. this runs as 
'nt authority\system'
so my script passes around a credentials object. Except when it gets here. Now i'm in a rabbithole of trying to run the function using 

1. start-job (so I can pass cred) - works when i use my own login on a test machine, fails with access denied when the system user calls this
2. Attempting 'invoke-command' seems to actually run the command as the user I want, however doing 
`if ([adsi]::Exists("LDAP://" + $OUPath))`
fails with 
```
Exception calling "Exists" with "1" argument(s): "An operations error occurred.
"
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DirectoryServicesCOMException
    + PSComputerName        : localhost
```
so when you say 'you should previously create the input object with elevated permissions'. I agree with you. but HOW? 
@iSazonov

**Comment by iSazonov** [comment]
You could use `[adsi]::new(string path, string username, string password)` to make elevated binding.

**Comment by dogfish182** [comment]
I solved my issue which was quite specific. 
I found that to invoke a command while running as system on a windows system, you need to enable credssp and enable the server component of Credssp aswell as the client portion so the system can pass credentials to itself. Then you can invoke command with a service Account that has AD access. 

```
# enable the box to accept credentials 
Enable-WSManCredSSP -role server
# enable the box to trust itself 
Enable-WSManCredSSP -Role "Client" -DelegateComputer "$env:computername.$env:userdnsdomain"
```
you can also force the command so it's possible in a script. 
Credssp has some security implications and warnings about security, so for my scope since i'm running a system via SSM and I trust myself, I enable credssp at the start, do my work and disable again at the end. Hope this helps someone one day, it cost me 2 days of confusion.

**Comment by MaBauMeBad** [comment]
Bump up this.

I ran also in this issue and also missing -server Argument when working with two different AD Domains and try to query the current ACLs for Objects ( for example Groups or OUs).

**Comment by allasto** [comment]
Hi @dogfish182 I am having the same issue trying to run SSM docuement on a windows system that suppose to give permission to an account on the computer OU
It is failing to run due to SYSTEM , I tried your solution and it is not working , might be I am missing something ? 

Import-Module AWSPowerShell
Enable-WSManCredSSP -role server -force
Enable-WSManCredSSP -Role "Client" -DelegateComputer "$env:computername.$env:userdnsdomain" -force

$Domains = 'test.local'
$user = GET-SECSecretValue -SecretId arn:somearn -Select SecretString | ConvertFrom-Json | Select -ExpandProperty adminDomainUsername
$pass = GET-SECSecretValue -SecretId arn:somearn -Select SecretString | ConvertFrom-Json | Select -ExpandProperty adminDomainPassword | ConvertTo-SecureString -asPlainText -Force
$DomainUser = "$Domains\$user"
$Cred = New-Object System.Management.Automation.PSCredential($DomainUser,$pass)



$Script= {
Import-Module ActiveDirectory
$AccountName = 'demo'
$Domain = Get-ADDomain -Identity test.local -ErrorAction Stop 
$BaseDn = $Domain.DistinguishedName
$ComputersContainer = $Domain.ComputersContainer
$SchemaNamingContext = Get-ADRootDSE | Select-Object -ExpandProperty 'schemaNamingContext'
[System.GUID]$ServicePrincipalNameGuid = (Get-ADObject -SearchBase $SchemaNamingContext -Filter { lDAPDisplayName -eq 'Computer' } -Properties 'schemaIDGUID').schemaIDGUID
$AccountProperties = Get-ADUser -Identity $AccountName 
$AccountSid = New-Object -TypeName 'System.Security.Principal.SecurityIdentifier' $AccountProperties.SID.Value
$ObjectAcl = Get-ACL -Path "AD:\$ComputersContainer"
$AddAccessRule = New-Object -TypeName 'System.DirectoryServices.ActiveDirectoryAccessRule' $AccountSid, 'CreateChild', 'Allow', $ServicePrincipalNameGUID, 'All'
$ObjectAcl.AddAccessRule($AddAccessRule)
Set-ACL -AclObject $ObjectAcl -Path "AD:\$ComputersContainer"
}

Invoke-Command -Computer localhost -ScriptBlock $Script -Credential $Cred
Write-Output "Content of variable Script"
Write-Host $Script

**Comment by lazurwolf1** [comment]
Alto, I was trying to do the same thing.  Slightly different script.

Import-Module ActiveDirectory
        New-ADOrganizationalUnit -Name $newOU -Path "OU=example,DC=example,DC=com" -Description $ServiceUserName -PassThru -Credential $credential
        New-ADUser -Name $ServiceUserName -Accountpassword (ConvertTo-SecureString "Password1!" -AsPlainText -force) -Enabled $true -Credential $credential
        $OrganizationalUnit = "OU=" + $newOU + ",OU=example,DC=example,DC=com"
        Set-Location AD:
        $Group = Get-ADuser -Identity $ServiceUserName 
        $GroupSID = [System.Security.Principal.SecurityIdentifier] $Group.SID
        $ACL = Get-Acl -Path $OrganizationalUnit 
        $Identity = [System.Security.Principal.IdentityReference] $GroupSID
        $Computers = [GUID]"bf967a86-0de6-11d0-a285-00aa003049e2"
        $ResetPassword = [GUID]"00299570-246d-11d0-a768-00aa006e0529"
        $ValidatedDNSHostName = [GUID]"72e39547-7b18-11d1-adef-00c04fd8d5cd"
        $ValidatedSPN = [GUID]"f3a64788-5306-11d1-a9c5-0000f80367c1"
        $AccountRestrictions = [GUID]"4c164200-20c0-11d0-a768-00aa006e0529"
        $RuleCreateAndDeleteComputer = New-Object System.DirectoryServices.ActiveDirectoryAccessRule($Identity, "CreateChild, DeleteChild", "Allow", $Computers, "All") 
        $RuleResetPassword = New-Object System.DirectoryServices.ActiveDirectoryAccessRule ($Identity, "ExtendedRight", "Allow", $ResetPassword, "Descendents", $Computers) 
        $RuleValidatedDNSHostName = New-Object System.DirectoryServices.ActiveDirectoryAccessRule ($GroupSID, "Self", "Allow", $ValidatedDNSHostName, "Descendents", $Computers) 
        $RuleValidatedSPN = New-Object System.DirectoryServices.ActiveDirectoryAccessRule ($GroupSID, "Self", "Allow", $ValidatedSPN, "Descendents", $Computers) 
        $RuleAccountRestrictions = New-Object System.DirectoryServices.ActiveDirectoryAccessRule ($Identity, "ReadProperty, WriteProperty", "Allow", $AccountRestrictions, "Descendents", $Computers) 
        $ACL.AddAccessRule($RuleCreateAndDeleteComputer)
        $ACL.AddAccessRule($RuleResetPassword)
        $ACL.AddAccessRule($RuleValidatedDNSHostName)
        $ACL.AddAccessRule($RuleValidatedSPN)
        $ACL.AddAccessRule($RuleAccountRestrictions)
        Set-Acl -Path $OrganizationalUnit -AclObject $ACL
        
Did you ever get yours to work?

**Comment by allasto** [comment]
Yes.
add the following before the script to enable credssp:
      Enable-WSManCredSSP -role server -force
      Enable-WSManCredSSP -Role "Client" -DelegateComputer "$env:computername.domain.com" -force

      New-Item -Path HKLM:\SOFTWARE\Policies\Microsoft\Windows\CredentialsDelegation -Name AllowFreshCredentialsWhenNTLMOnly -Force
      New-ItemProperty -Path HKLM:\SOFTWARE\Policies\Microsoft\Windows\CredentialsDelegation\AllowFreshCredentialsWhenNTLMOnly -Name 1 -Value "wsman/$env:computername.domain.com" -PropertyType String


and add this at the end to the invoke command:  -Authentication Credssp

Like:
Invoke-Command -Computer localhost -ScriptBlock $Script -Credential $Cred -Authentication Credssp
