### ISSUE TITLE
string.split('') doubt

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#3809]
string.Split('') different between .net4.62 and .net core2.0

I am not sure if this is .Net core version of the problem,or fixed already. somebody help me to see,please.
If yes, it is best to help submit the bug to. Net issue, thank you! (i don't know issue to dotnetfx or stand )
If not,where is the problem?

Steps to reproduce
------------------
```
$a = 'aaa bbb	ccc     ddd  eee           fff    ggg'  #TAB between bbb and ccc
$b = $a.Split('',[System.StringSplitOptions]::RemoveEmptyEntries) #YES,i want remove both SPACE and TAB
$b[2]
$c = $a.Split(' ',[System.StringSplitOptions]::RemoveEmptyEntries)
$c[2]
```

powershell 5.1 on win10 return:
ccc
ddd

powershell 6.0 beta1 on win10,and 
powershell 6.0 beta1 on centos return:
ddd

Expected behavior
-----------------
can return ddd.YES,i want remove both SPACE and TAB

Environment data
----------------
centos 7.3 1611

Name                           Value                                                                                                             
----                           -----                                                                                                             
PSVersion                      6.0.0-beta                                                                                                        
PSEdition                      Core                                                                                                              
BuildVersion                   3.0.0.0                                                                                                           
CLRVersion                                                                                                                                       
GitCommitId                    v6.0.0-beta.1                                                                                                     
OS                             Linux 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017                                              
Platform                       Unix                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                               
SerializationVersion           1.1.0.1                                                                                                           
WSManStackVersion              3.0   

reporter
----------------
By the chinese powershell study & research group. QQ group No. is 183173532

in 'vscode' or other open source project,in version release notes,bug reporter should be thank.
So I left a group name.

**Comment by mklement0** [comment]
First, _pragmatically_ speaking, PowerShell's own `-split` _operator_, in its _unary_ form, will treat any run of spaces and/or tabs as a separator, similar to the default behavior of `awk` on Unix:

The following commands work the same in Windows PowerShell and PowerShell Core:

```powershell
> (-split  'aaa bbb	ccc     ddd  eee           fff    ggg' ).Count
7   # count of whitespace-separated tokens, meaning any mix of spaces and/or tabs

> (-split  'aaa bbb	ccc     ddd  eee           fff    ggg' )[2]
ccc
```

Note, however, that the _binary_ form of the `-split` operator uses _regular expressions_, as opposed to the _literals_ that the `.Split()` method operates on. See [`Get-Help about_Split`](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.core/about/about_split)

---

As of this writing, to achieve the same result _consistently_ with the `[string]` method's `.Split()` method, you have to cast the 1st argument to `[char[]]`):

```powershell
> ('aaa bbb	ccc     ddd  eee           fff    ggg'.split([char[]] '',  [System.StringSplitOptions]::RemoveEmptyEntries)).Count
7

> ('aaa bbb	ccc     ddd  eee           fff    ggg'.split([char[]] '',  [System.StringSplitOptions]::RemoveEmptyEntries))[2]
ccc
```

---

Your example can be reduced to the following:

```powershell
# Yields *1* in PS *Core*, *2* in *Windows* PS
> ('a  b'.split('', [System.StringSplitOptions]::RemoveEmptyEntries)).Count  # Note the *2* spaces
```

Why do they behave differently?

.NET _Core_ has _new overloads_ for the `[string]` type's `.Split()` method that aren't currently present in the _full_ (Windows-only) .NET framework (see [the .NET Core docs](https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=netcore-2.0), but note that these overloads (a) lack a _description_ at this point and (b) do not yet show in the .NET _Standard_ view, as of this writing):  
Both new overloads take a `[string]` value as their first parameter, unlike any previous overloads.

As a consequence, `'a  b'.split('', [System.StringSplitOptions]::RemoveEmptyEntries)` is bound to:

* .NET *Core*: overload `Split(​String, ​String​Split​Options)`, which with an _empty string_ always returns the _entire input string_ as a _single-element array_.

* _Full_ framework: overload `Split(​Char[], ​String​Split​Options)`, which, with an _empty array_ returns an array of the  whitespace-separated tokens in the input string, with each whitespace instance separating a token, because "white-space characters are assumed to be the delimiters."

A quick way to compare the available overloads is to run the following in PS:

```powershell
# On PS *Core*: Note the two `Split(string separator...` overloads.
> ''.Split

OverloadDefinitions                                                                                                                                                                
-------------------                                                                                                                                                                
string[] Split(char separator, System.StringSplitOptions options)                                                                                                                  
string[] Split(char separator, int count, System.StringSplitOptions options)                                                                                                       
string[] Split(Params char[] separator)                                                                                                                                            
string[] Split(char[] separator, int count)                                                                                                                                        
string[] Split(char[] separator, System.StringSplitOptions options)                                                                                                                
string[] Split(char[] separator, int count, System.StringSplitOptions options)                                                                                                     
string[] Split(string separator, System.StringSplitOptions options)                                                                                                                
string[] Split(string separator, int count, System.StringSplitOptions options)                                                                                                     
string[] Split(string[] separator, System.StringSplitOptions options)                                                                                                              
string[] Split(string[] separator, int count, System.StringSplitOptions options)                                                                                                   
                                                                                                                                                                                   
```

Note:

* The above has been arrived at by trial and error. I tried to trace parameter binding, but was unsuccessful. Lots of type-conversion magic and matching goes on behind the scenes in PS, which is generally very helpful, but can be hard to understand in edge cases like these.

* Curiously, even a _single-argument_ invocation shows framework-specific behavior, even though there's no _single-parameter_ overload with `[string]` as the first and only parameter:  
`'a  b'.split('').Count` yields `1` in PS *Core*, and `3` with the _full_ framework.

---

What does this all mean in the grand scheme of things?

I don't know, but I sure hope someone else does :)

**Comment by SteveL-MSFT** [comment]
@mklement0 great analysis, I'm not sure what we can/should do about this

Cc @PowerShell/area-language

**Comment by iSazonov** [comment]
In PowerShell '' is a string. So I agree with @mklement0 we have explicitly cast to call needed method overload.
I believe a resolution is "By design".

**Comment by SteveL-MSFT** [comment]
Agree it's working as intended, but the corefx change introduces unexpected results and I'm wondering if there are other corefx api changes that could break existing scripts

**Comment by iSazonov** [comment]
Oh, CoreFX has tons of changes, non-implemented and depredicated APIs...
We will know all breaking changes in time when CoreFX 5.0 version outs 😄 

Our test set is too small to detect these issues.

**Comment by lzybkr** [comment]
New overloads in the CLR can break PowerShell scripts at any time because PowerShell is late-bound. This has happened in the past with this example:

```
PS> [System.Runtime.InteropServices.Marshal]::sizeof([int])
Exception calling "SizeOf" with "1" argument(s): "Type 'System.RuntimeType' cannot be marshaled as an unmanaged structure; no meaningful size or offset can be computed."
```

This example worked before CLR 4.5.1 - but in that release, they added this [overload](https://msdn.microsoft.com/en-us/library/dn261467(v=vs.110).aspx) which turns out to be a better match than [this one](https://msdn.microsoft.com/en-us/library/5s4920fa(v=vs.110).aspx).

The choice is:
```
int Sizeof<T>(T t);  // New in 4.5.1
int Sizeof(System.Type t);
```

The argument `[int]` is a `System.RuntimeType` which is more specific than `System.Type` and hence a better match, so we chose the generic if it is present, resulting in this error.

So the bottom line here - new overloads in the CLR are beyond PowerShell's control and breakages like this are always possible. This is one example of how it is difficult for platforms and languages to interop nicely - it might work well most of the time, but there will always be corners like this that are unavoidable.

**Comment by mklement0** [comment]
@lzybkr: That's a great, concise summary.

Another way of putting it: _for predictable results, stay in the realm of PowerShell_, if you can.

Sometimes, using the underlying framework directly is unavoidable (and PowerShell _even supporting that at all_ sets its apart from other shells), but there are many cases where PowerShell's own features will not only do just fine, but offer a _higher level of abstraction_.

`String.Split` vs. `-split` and `String.Replace` vs. `-replace` are two examples where PowerShell offers more power, yet there are (too) many examples out there relying on the `String` type's methods.

**Comment by chuanjiao10** [comment]
as mklement0 say:
('aaa1bbb2ccc').split("12")
windows return: #only one parameter,default parameter type [char]
aaa
bbb
ccc

linux return: #only one parameter,default parameter type [string]
aaa1bbb2ccc

For compatibility, I write it:
('aaa1bbb2ccc').split([char[]]"12") 

But very uncomfortable,oh shit.

And as time goes by, more and more people will find this problem.
Now my question is,Will default parameter type keep [string]?  ---only one parameter

**Comment by mklement0** [comment]
@chuanjiao10:

PowerShell uses a generic algorithm to dynamically find the best method overload to call, and
* I presume that no changes are being planned to this generic algorithm,
* and hard-coding type/method-specific behavior sounds like a bad idea.

To repeat @lzybkr's bottom line:

> new overloads in the CLR are beyond PowerShell's control and breakages like this are always possible.

To recap the solutions:

* If there's a native PowerShell alternative, use it instead.

   * In this case: use PowerShell's `-split` _operator_.

* Use explicit casts to unambiguously and robustly force selection of the desired overload.

  * In this case: `('aaa1bbb2ccc').split([char[]]"12")`

  * It may be cumbersome, but it clearly expresses the intent and is future-proof.

 The implication is that for maximum robustness you should _always_ use explicit casts when calling .NET methods (you never know what new overloads may be added in the future, though there are definitely gradations of likelihood), but the inconvenience and "non-PowerShellness" of that just reinforce the point that it's better to use PowerShell's own features whenever possible.

**Comment by chuanjiao10** [comment]
Users usually say "no reason, give me the old,What i am familiar things."

Do you know why I do not use the -split operator?I do not want to use regular engine.

Thanks again, as a user, i'm going to curse .net developer, are you willing to follow? ;)

**Comment by mklement0** [comment]
> why I do not use the -split operator?

Yes, it's not the exact equivalent, but in the cases where you do need to worry about accidental regex metacharacters, you can use `[regex]::Escape()` (which itself is pretty much guaranteed _not_  to break in the future, as counter example); and, generally, I consider it an advantage that `-split` is regex-based.

> Thanks again, as a user, i'm going to curse .net developer, are you willing to follow? ;)

While it's always unpleasant when code that used to work breaks, I don't think anybody deserves cursing here.

Remember that we are talking about _edge cases_ here, and that there's no good generic solution to this problem when different worlds such as PowerShell and .NET (the CLR) interface directly.

**Comment by chuanjiao10** [comment]
Translation is not accurate, curse should be scold
