### ISSUE TITLE
TAB Completion in nested mode doesn't work for some variables

### ISSUE THREAD

**Issue by luctalpe** [PowerShell/PowerShell#3810]
Steps to reproduce
------------------
```console
PS C:\Users\luct\Downloads\PowerShell-6.0.0-beta.1-win10-win2016-x64> cd \temp
PS C:\temp> .\1.ps1
DEBUG: Is it a problem ?

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): S
PS C:\temp>> type 1.ps1
[CmdletBinding()]
param()

$TestArray = @(1..10)
write-debug -Debug "Is it a problem ?"


PS C:\temp>> $testarray
1
2
3
4
5
6
7
8
9
10
```

Even if we are able to display the $testarray variable but entering the complete name, tab completion doesn't work. The problem is only visible with powershell.exe and not for powershell_ISE.exe

Expected behavior
-----------------

Be able to autocomplete testarray variable for inner scope (0,...) in nested mode 

Actual behavior
---------------
Autocompletion 

Environment data
----------------

```powershell
> $PSVersionTable

S C:\temp>> $psversiontable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-beta.1
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by luctalpe** [comment]
Actual behavior:
Autocompletion doesn't work for $testarray variable

**Comment by MaximoTrinidad** [comment]
Hi @luctalpe,

Looking at the sample you provided, seems to me you are trying to access the array variable after the script has executed.  If this is the case, then $testarray won't be available any more.

You may need to use $global:testarray in order for the variable to be accessible after the script has ended. Only then the autocompletion should work.

I'm hoping this makes sense. 

![posh_array_2017-05-18_8-54-19](https://cloud.githubusercontent.com/assets/19892435/26203041/ae945e06-3ba7-11e7-8f9d-fe2f460ee210.jpg)

**Comment by luctalpe** [comment]
Hi Maximo,

Thanks but there is a misunderstanding . The issue is during script execution, not after script execution.

When we are in the nested mode ( see >> prompt), you can display the variable typing $testarray, but if you try to expand it at this point (and not after script  has executed), tab completion doesn't work.

**Comment by MaximoTrinidad** [comment]
@luctalpe,

My apologies! Now I understand what you're talking about. I haven't had the need for it but I gave it a test. 

By the way, the behavior is in both Windows PowerShell (Ver. 5.1.16193.1001) and PowerShell Core (Ver. 6.0.0-beta.1).  I'm on Windows Insider Build 16193.

I may suggest to also post this incident at Windows PowerShell UserVoice site at: https://windowsserver.uservoice.com/forums/301869-powershell/category/148044-powershell-engine

![nestedtab_2017-05-18_13-45-48](https://cloud.githubusercontent.com/assets/19892435/26216084/cff5d8c6-3bd0-11e7-8996-fda2bf1b1082.jpg)

**Comment by davidBar-On** [comment]
I am trying to resolve this issue, and I believe I understand what is causing the problem but I would **appreciate some direction on were to look** to resolve it.

What I found so far is that normally with command prompt, the `global` and `local` (and `script`) **variables scopes** are the same.  However, when a script is run, a separate `local` variables scope is used.  Therefore, in the suspend mode of `Write-Debug`, the command prompt is using **separate** `local` and `global` scopes.

It seems that when `ReadLine` is called, a **new** `local` variable scope and the `global` scope are passed to it.  Therefore, `ReadLine` does **not** have access to the local variables defined by the script.

Since the **tab-completion** is done **from `ReadLine`**, it also does **not** have access to the script's `local` variables.

My issue is that I am not able to find where the `local` variables scope for `ReadLine` is defined, assuming that this is where a change can be done to resolve this issue.  **Any help in identifying where this is done will be appreciated**.

**Comment by iSazonov** [comment]
> Since the **tab-completion** is done **from `ReadLine`**

There are two code paths - PowerShell implementation and PSReadline implementation - see using TryInvokeUserDefinedReadLine method.

**Comment by davidBar-On** [comment]
> There are two code paths - PowerShell implementation and PSReadline implementation - see using TryInvokeUserDefinedReadLine method.

Thanks for the help.  I believe I found the root cause of the issue and submitted PR #15529 with a suggested fix.
