### ISSUE TITLE
SupportsPaging does not generate help

### ISSUE THREAD

**Issue by lipkau** [PowerShell/PowerShell#3840]
### Description
implementing `[CmdletBinding(SupportsPaging = $true)]` does no generate the help of the parameters for Paging

### Steps to reproduce
1. load the following function to the session:
https://github.com/Microsoft/Windows-classic-samples/blob/master/Samples/PowerShell/SupportsPaging/SupportsPaging01/cs/SupportsPaging01.ps1
2. `Get-Help Get-Numbers`

### Expected behavior
See the doc on the parameters `-Skip`, `-IncludeTotalCount` and `-First`

### Actual behavior
Help is not generated

**Comment by Jaykul** [comment]
Same problem with _SupportsShouldProcess_ -- the optional but _common_ parameters are added, but help isn't automatically generated. You _could_ write the help yourself. 

But since there is inherent meaning, and inherent default values (`-Skip` defaults to `0`, and `-First` defaults to `[UInt64]::MaxValue` etc., it would make sense if these parameters had automatic help. At least for script functions, at least when the help is comment-based...

```

**Comment by powercode** [comment]
Anyone who has understood how `-IncludeTotalCount` is supposed to be used?

**Comment by lipkau** [comment]
@powercode it prints a line with the total count of entries.
In case of `[double]$Accuracy = 0.0`, it will print a line saying that the total count is unknown

**Comment by Jaykul** [comment]
@powercode yeah, `-IncludeTotalCount` determines whether you're supposed to try to figure out how many total items there are, and output that with your page of results. You implement it by calling `$PSCmdlet.PagingParameters.NewTotalCount(` --and as @lipkau mentioned, you can indicate that you don't know, if you don't know.

**Comment by powercode** [comment]
@Jaykul Well, that is how to implement it, but how can you make real world use of it as a caller?
A stray integer in the beginning of a sequence of objects doesn't help me much.
