### ISSUE TITLE
Please stop deploying PowerShell so that "Run as Admin" use system32 as WorkDir

### ISSUE THREAD

**Issue by schittli** [PowerShell/PowerShell#3880]
Good evening

I wonder that starting a PowerShell Session (and cmd, too, but thats another inexplicable annoyance) as Administrator uses System32 as it's working Directory. 
I'm pretty sure there is almost no situation where the User will have to work in System32 and we probably never change Files in this directory by an interactive PowerShell Session.

Therefore it makes no sense to use this Directory.
The Linux way is once more much more useful: /root. I can even delete /root - and there is no danger for the System. If I make a mistake in System32 - which can happen - then I've probably got a problem.

Maybe, you could use something like 
`Join-Path $env:USERPROFILE 'PowerShell'
`
or just
`c:\Temp
`
Kind regards, Tom

Steps to reproduce
------------------
Ctrl-Click the PowerShell Icon

Expected behavior
-----------------
Use a save working place (working directory) if PowerShell is started. Always.

Actual behavior
---------------
If PowerShell is started, it uses System32 as it's working directory.

**Comment by lzybkr** [comment]
I think this is by design, see [here](https://blogs.msdn.microsoft.com/oldnewthing/20071211-00/?p=24223/) for an explanation.

You'll note that this design only applies to Windows binaries. PowerShell Core is not a Windows binary, so your "Start In" directory will be honored if the shortcut points to PowerShell Core instead of Windows PowerShell.

**Comment by rkeithhill** [comment]
I've wondered about that. @lzybkr Thanks for the pointer.
