### ISSUE TITLE
Launching with shebang does not work (hangs)

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#3959]
Powershell Beta 2 on Ubuntu 16.04

Steps to reproduce
------------------
Create a file hello
#!/opt/microsoft/powershell/6.0.0-beta.2/powershell
gps i*

----------
Then chmod +x it
and run it ./hello

It hangs

Expected behavior
-----------------
Not hanging :-)

Actual behavior
---------------

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by chuanjiao10** [comment]
i help test in centos 7.3,powershell beta2 with shebang from bash:
1 utf8+noneBOM:normal

2 utf8+BOM:
/powershell/2017-06-07.ps1:行1: ﻿#!/opt/microsoft/powershell/6.0.0-beta.2/powershell: 没有那个文件或目录
/powershell/2017-06-07.ps1:行2: gps: 未找到命令

3 utfl6le+BOM:
-bash: /powershell/2017-06-07-u16.ps1: 无法执行二进制文件

**Comment by SteveL-MSFT** [comment]
@jpsnover current workaround is to rename your script to have the .ps1 extension.  the problem seems to be that the OS calls `powershell hello`.  PowerShell doesn't know that `hello` is a script, so it executes `hello` which then spawns another `powershell hello` recursively thus the "hang".  We probably need to peek into the command given to us to see if it's a shebang and if it's calling powershell, we just treat it like a script file rather than executing it natively.

**Comment by SteveL-MSFT** [comment]
https://github.com/PowerShell/PowerShell/issues/1103

**Comment by mklement0** [comment]
While the proper solution is being debated in #3963, let me make the following aside:

* **Do _not_ use the value of `$PSHOME` as the path to the binary in the shebang line**, because:

   * scripts will only function _with that very specific version_ (e.g., beta.2, with `#!/opt/microsoft/powershell/6.0.0-beta.2/powershell`)

   * scripts _won't be portable_ across Unix platforms

* Instead, **use the following, portable shebang line**:

      #!/usr/bin/env powershell
