### ISSUE TITLE
Call operator and Get-Command ignore .cmd file in current directory

### ISSUE THREAD

**Issue by stej** [PowerShell/PowerShell#3976]
Steps to reproduce
------------------

```powershell
PS D:\temp\powershell-600beta2> sl d:\temp
PS D:\temp> [System.Environment]::CurrentDirectory
# returns d:\temp\powershell-600beta2
PS D:\temp> [System.Environment]::CurrentDirectory = 'd:\temp'
PS D:\temp> [System.Environment]::CurrentDirectory
# returns d:\temp
PS D:\temp> "echo im from temp!" | sc bb.cmd
PS D:\temp> gcm bb
#returns 
# CommandType     Name                                               Version    Source
# -----------     ----                                               -------    ------
# Application     bb.cmd                                             0.0.0.0    C:\Users\testu\AppData\Roaming\npm\...

PS D:\temp> & bb
# returns 
# Bobril-build 0.70.0 - D:\temp
```

Expected behavior
-----------------

`& bb` should type call bb.cmd from d:\temp

Actual behavior
---------------

`& bb calls` completely different bb.cmd that is found on one path from `$env:path`

When I specify directory, it works
```powershell
PS D:\temp> & $pwd\bb.cmd
# returns D:\temp>echo im from temp!
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-beta.2
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
That is by design and a security feature (an intentional deviation from `cmd.exe`, but in line with POSIX-like shells): if you really want to invoke an executable located in the _current_ location, you must explicitly signal that intent by using a _path_; `.\bb` in the simplest case.

_Filename-only_ invocations by design only work with executables located in one of the `$env:PATH` directories.

In your case, the behavior isn't obvious, but had you tried to invoke an executable that _only_ exists in the current directory (not also in the PATH), you'd have seen this suggestion (following the error message):

> Suggestion [3,General]: The command bb was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\bb". See "get-help about_Command_Precedence" for more details.

**Comment by stej** [comment]
Ok, got it. I might have read it loong time ago, but forgot since then. 
If intended, there is nothing more to do ;)

Thanks for clarification, helped me with my problem!
