### ISSUE TITLE
Tab completion not working for Import-Module '.\partialname'

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#4011]
Steps to reproduce
------------------
Navigate to the root of the powershell repo
ipmo .\bu{tab}

Expected behavior
-----------------
.\bu followed by a tab is completed with .\build.psm1

Actual behavior
---------------
Nothing happens.

Note that dir .\bu{tab} and impo -FullQualifiedName .\bu{tab} do complete as expected.

Environment data
----------------
Repro'd with a build sync'd 6/14/2017

PSVersion                      6.0.0-beta
PSEdition                      Core
CLRVersion
GitCommitId                    v6.0.0-beta.2-32-g8731747c3e412edf537c3dc0b4ce6a09e6fd7d95
OS                             Microsoft Windows 10.0.16202
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by daxian-dbw** [comment]
Found it stopped working since Jun 7, 2017.
By looking at the commits on Jun 7, 2017, I believe it's broken by either https://github.com/PowerShell/PowerShell/commit/a52adcd3cf4f87f474131f0d3421841c39cf09c0 or https://github.com/PowerShell/PowerShell/commit/312576447637a7c12c622e8984ea091dc699a868. The former commit is more suspicious.
