### ISSUE TITLE
Refactor /docs and /demos directories

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#4111]
We need to refactor a lot of the outdated content from the docs and demos folder. Some of it should go into PowerShell-Docs, some of it should remain here, some of it should be removed. 

Depending on what it is it should be:
* migrated into PowerShell-Docs
* reworded and remain here
* deleted altogether

Ultimately, I'll probably end up doing a first pass here. 😄

**Comment by zjalexander** [comment]
i can squeeze it in, yeah. what's the timeframe?

**Comment by zjalexander** [comment]
* Building 
  * STAY
  * Linux.md – needs a quick editing pass
  * Macos.md – needs a quick editing pass
  * Windows-core.md – needs a quick technical pass since it looks like https://github.com/PowerShell/PowerShell/issues/3400 is almost complete
  * Windows-full.md – needs a quick editing pass given the heavy discussion of “Full CLR” – want to make sure this is consistent
* Community
  * Possibly merge with maintainers, or bring maintainers content in here
  * Content is OK.
* Debugging
  * Potentially merge in with another folder, only 1 item here
  * If debug experience has changed at all in last 9 months, we should do a technical pass. Otherwise it’s fine
* Dev-Process
  * STAY. Maybe bring debugging in here.
  * Breaking-change-contract.md – I’d like to see an editing pass here to make this clearer and more consistent.
  * Coding-guidelines.md – I think it would be useful to have a technical pass on this to understand if these guidelines have changed at all over the past year.
* Git
  * STAY
  * Host-PowerShell: We need to talk to Eric to see if this should merge with the Windows PowerShell developer docs. 
  * This seems pretty well maintained, I don’t think the content needs much work
  * We should have a cleanup/retention policy – do we really need the beta1 docs to lay around?
* Installation
  * We should consider merging this into Docs.
* Learning-PowerShell
  * We should strongly consider merging this into Docs.
  * Readme.md – should get merged into our [getting started guide](https://msdn.microsoft.com/en-us/powershell/scripting/getting-started/getting-started-with-windows-powershell). (side note: clean up https://msdn.microsoft.com/en-us/powershell/scripting/getting-started/fundamental/using-windows-powershell ) 
  * Create-powershell-scripts.md – we don’t have this content today!
  * Debugging – we don’t have this content today!
  * Powershell-beginner’s-guide – This should be merged with the readme / getting started guide.
  * Using-code – we don’t have this content today! We should have a reference to it on the ISE pages as well.
  * Working-with-powershell-objects - https://msdn.microsoft.com/en-us/powershell/scripting/getting-started/fundamental/using-variables-to-store-objects has some content we should merge in with
* Mantainers
  * STAY (but potentially merge with another folder) 
  * Readme.md – should be updated – I think we have non-MSFT maintainers now
* Testing-guidelines
  * I think we should do an overall review to make sure this section is still necessary and helpful
Powershellcoreteststatus – this hasn’t been updated in a year.

* FAQ – I’m… not sure. What to do with this
* Known issues – same.

**Comment by zjalexander** [comment]
I also looked at demos, I don't think it belongs in docs right now. We might want to link to it from docs, maybe?

**Comment by zjalexander** [comment]
@eslesar @sdwheeler @juanpablojofre We discussed this issue in our last meeting - here's what I had based on this conversation
