### ISSUE TITLE
powershell core version name should rename,synchronized with the .net core name

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#4125]
Hello, welcome to Microsoft renamed center ;). It is now possible to meet and vote.
A good name is very important to powershell. Now is the best chance to rename, I hope you take seriously.

Do you know .net core 1.0 old name ? Perhaps .NET framework 5.0 core or Core 5.0.
Should powershell core version name follow ? This is what we now want to discuss.

Our principle is
------------------
Powershell 6.0: leave it to release of windows 11，6 --- 8 years after.
Powershell core version of the name, should be synchronized with the .net core version of the name.

It is now July, from September 15,.Net core will release.there are two months,time just enough.

The details are discussed below
------------------

date             | .net core version name       | new powershell version name | old powershell version name
---------------  | ---------------------------- | --------------------------- | -------------
past             |.net core 1.x                 | powershell core 1.x         | from powershell 6.0 alpha1 -----to---->  alpha19
now              |.net core 2.0.x               | powershell core 2.0.x       | from powershell 6.0 beta1  -----to---->
In mid-September |.net core 2.1.x               | powershell core 2.1.x       | null

Roughly like this.What do you think of it?
If you do not think it's a clown joke, Now is best time. welcome to discuss.

**Comment by dragonwolf83** [comment]
I disagree. PowerShell is it's own product and a consumer of .NET Core so it should not sync with .NET Core versioning. Should every 3rd party product built on .NET sync their version to .NET Core just because they switched to latest .NET Core version? Semantic Versioning should be based on the product's own semantics, not that of it's underlying technologies.

The version change and name change in .NET Core made sense for that team because it was a major rewrite of .NET Framework. A lot of things broken because it was truly a 1.0 release of something new. Much of what a developer expected from a .NET 4.7 release would not work the same in a .NET Core. One could argue that maybe .NET Core 2.0 fixes that to some degree, but I think it still made since for that team to do a new version for a rewritten framework. I should also note that C# itself has not reset it's versioning. They are continuing on with 7.0+ plus because they have not fundamentally rewritten C#.

For PowerShell, the language and semantics all work the same. There are some breaking changes, but that is why a major point release from 5.0 to 6.0. I don't get the feel that PowerShell Core is a true rewrite of PowerShell but more of an evolution of it much like C#. The language is the same, just enhanced. All of my scripting knowledge would be the same so sticking with 6.0 makes the most sense.

I would argue they could even drop Core from the name if they can get FullCLR modules to work in #4062 in time for 6.0. The name change from Windows PowerShell to just PowerShell is enough of a difference for the new cross-platform and deployment strategy.

**Comment by SteveL-MSFT** [comment]
The team had discussed this way before we went public last Aug.  @dragonwolf83 covered many of the points we discussed internally.  We even discussed "PowerShell" vs "PowerShell Core" and although I don't remember the exact reasoning now, but it might be that "PowerShell" wasn't distinct enough and may cause confusion with "Windows PowerShell".

If @joeyaiello remembers, maybe he can add more details.

**Comment by chuanjiao10** [comment]
The additional options are:
Synchronize the major version number.
Use the major version number alternately.
Now, the synchronization major version number program is executed.

**Comment by iSazonov** [comment]
Currently CoreFX is very unstable. Now we have just use unsync CLI and SDK versions. So it may be good later (CoreFX 3.0 ?) but not now.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee discussed this and prefers not to introduce more confusion as we've been using the PowerShell Core 6.0 branding for some time and thus not considering new names
