### ISSUE TITLE
Split-Path -Parent treats paths of root-location items inconsistently across providers

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4130]
Steps to reproduce
------------------

```powershell
# Get the list of drives (using only 1 filesystem and only 1 registry drive)
(Get-PSDrive | ? { $_.Provider.Name -notin 'FileSystem', 'Registry' -or $_.Name -in 'C', '/', 'HKLM' }).Name | % {
  # Construct a (dummy) path to an item in the root location; e.g., "C:\Foo"
  $path = $(if ($_ -eq '/') { $_ } else { $_ + ':/' }) + 'Foo'
  [pscustomobject] @{ 
    Command = "Split-Path -Parent $path"
    Result = Split-Path -Parent $path
  }
}
```

Expected behavior
-----------------

On Windows:

```none
Command                  Result
-------                  ------
Split-Path Alias:/Foo    Alias:\
Split-Path C:/Foo        C:\
Split-Path Cert:/Foo     Cert:\
Split-Path Env:/Foo      Env:\
Split-Path Function:/Foo Function:\
Split-Path HKLM:/Foo     HKLM:\
Split-Path Variable:/Foo Variable:\
Split-Path WSMan:/Foo    WSMan:\
```

Actual behavior
---------------

```none
Command                  Result
-------                  ------
Split-Path Alias:/Foo
Split-Path C:/Foo        C:\
Split-Path Cert:/Foo     Cert:\
Split-Path Env:/Foo
Split-Path Function:/Foo
Split-Path HKLM:/Foo     HKLM:\
Split-Path Variable:/Foo
Split-Path WSMan:/Foo    WSMan:\
```

Some drives unexpectedly report the _empty string_.

Unix systems have only a subset of these drives, but the shared subset behaves the same.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.3 on macOS 10.12.5
PowerShell Core v6.0.0-beta.3 on Ubuntu 16.04.1 LTS
PowerShell Core v6.0.0-beta.3 on Microsoft Windows 10 Pro (64-bit; v10.0.14393)
Windows PowerShell v5.1.15063.413 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by BrucePay** [comment]
Here's what's happening: Path parsing is handled by the underlying provider infrastructure since each provider can have its own notion of what constitutes a path. There are different types of providers including ones that don't support the notion of paths within their namespace. This is the case for the function, alias, env and variable providers. They are not NavigationProviders which means they don't support (nested) paths, just a flat list of names. As such, these providers don't implement the path parsing APIs. When Split-Path tries to split a "path" in these providers it gets a PSNotSupportedException and explicitly returns the empty string. The comment from the code is as follows:

```
                            // Since getting the parent path is not supported,
                            // the provider must be a container, item, or drive
                            // provider.  Since the paths for these types of
                            // providers can't be split, asking for the parent
                            // is asking for an empty string
```

**Comment by mklement0** [comment]
Thanks, @BrucePay, that's illuminating.

For consistency, I think it would make sense - and would be less surprising to users - to conceive of flat-list providers simply as a special case of a hierarchical providers whose hierarchy just happens to be confined to a single level.

**Comment by mklement0** [comment]
The alternative is to surface the exception as an error, if the conception is that applying path operations doesn't make sense for such providers.
