### ISSUE TITLE
Add tests for *-Item and Get-ChildItem cmdlets

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#4148]
Add tests for *-Item cmdlets. Missing areas are: 

- [x] Literal paths
- [x] Error cases
- [ ] AccessDenied Error
- [ ] SessionStateItem and SessionStateContainer error cases
- [x] Dynamic parameters
- [x] *-Item for alternate streams
- [x] Get-ChildItem for file
- [x] Rename-Item for directory
- [x] Copy-Item over remote session
- [x] *-Item for Registry provider
- [x] *-Item for Function provider
- [ ] Mapped network drive

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.3
OS                             Microsoft Windows 10.0.16204
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by jeffbi** [comment]
@adityapatwardhan What are you looking for regarding tests for "Get-ChildItem for file"? Just that it will return information about the file specified?

What is the expected behavior if, for example, `Get-ChildItem` is given a specific, non-globbed file name and also the `-Directory` parameter? Should it return information about the file anyway or return nothing because the file is not a directory?

Also, regarding "Rename-Item for directory", do you just mean that the cmdlet can rename a directory, or something more involved than that?

**Comment by adityapatwardhan** [comment]
@jeffbi We are interested covering the missing code paths at: https://codecov.io/gh/PowerShell/PowerShell/src/master/src/System.Management.Automation/namespaces/FileSystemProvider.cs

The list above is a summary of what is missing. So some tests might not look very useful, but there is untested code that exists and hence we need to exercise those code paths.

**Comment by jeffbi** [comment]
Thanks, @adityapatwardhan, I'll look that over.

**Comment by SteveL-MSFT** [comment]
I think the remaining items can be pushed to MQ

**Comment by TravisEz13** [comment]
@kalgiz I recommend looking at the function provider first.  Work with @adityapatwardhan  to figure out what tests are needed.
After that, you could work on the remoting tests.  @PaulHigin  would be a good resource for showing you how to use remoting in a test.

**Comment by PixleProgrambetaxl** [comment]
+1
