### ISSUE TITLE
Prompt function with Write-Host on MacOS 10.12.5

### ISSUE THREAD

**Issue by mikederksen** [PowerShell/PowerShell#4191]
Steps to reproduce
------------------
When overwriting the prompt function as follows:

```powershell
function prompt {
    Write-Host "Something> "
    " "
}
```

The reason why one would want to manually use Write-Host for outputting prompt values, is to be able to use colors. This is done in posh-git for example. In windows this works as expected.

Expected behavior
-----------------

```powershell
Something> --input goes here--
```

Actual behavior
---------------

```powershell
Something>
 Something>
--cursor position--
```

When i start typing the input appears as follows:

```powershell
Something>
--input appears here--
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-beta                                      
PSEdition                      Core                                            
BuildVersion                   3.0.0.0                                         
CLRVersion                                                                     
GitCommitId                    v6.0.0-beta.1                                   
OS                             Darwin 16.6.0 Darwin Kernel Version 16.6.0: F...
Platform                       Unix                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1                                         
WSManStackVersion              3.0 
```

**Comment by alexandair** [comment]
Don't use Write-Host at all. Just specify a string.
Or, use Write-Host -NoNewLine.

**Comment by mikederksen** [comment]
Write-Host -NoNewLine gives the same result. Returning a string is fine for normal text, but when one wants colored text this method doesn't suffice.

**Comment by rkeithhill** [comment]
> but when one wants colored text this method doesn't suffice.

Sure it does.  Try `` "`e[32mMy Green prompt>`e[0m "``.  See the MSDN docs on the rest of the [VT seqs](https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032(v=vs.85).aspx).  Oh, and you can test if the current host supports these with `$host.UI.SupportsVirtualTerminal`

**Comment by mikederksen** [comment]
Oh, didn't know that! Thanks for the advice. We can consider this issue resolved.

**Comment by mikederksen** [comment]
Oke, using `"`e[32mMy Green prompt>`e[0m "` works, untill i start typing. Once i start typing the prompt changes to ` [32mMy Green pro   `

**Comment by rkeithhill** [comment]
There is a known issue with the ESC sequences used on the same line where input happens **and** you have PSReadline imported.  You can read about the issue here https://github.com/PowerShell/PowerShell/pull/3867 and here https://github.com/lzybkr/PSReadLine/issues/470.  

On my Ubuntu VM, I split my prompt to two lines and put all the colored stuff on the first line and then I put an uncolored `> ` on the second line.  It's a workaround until PSReadline is fixed. 

Also consider moving to beta.3.  :-)

**Comment by jpogran** [comment]
FWIW, on beta.3 this is still an issue. This shows up on Terminal.app and iterm2 with just PSReadline and the example prompt in this issue. Things are resolved if PSReadline module is removed, but all history, tab completing, etc functionality is gone (obviously).

```
PowerShell v6.0.0-beta.3
Copyright (C) Microsoft Corporation. All rights reserved.

PS /Users/jpogran> function prompt {                                                                                                   >>     Write-Host "Something> "                                                                                                        >>     " "                                                                                                                             >> }
Something>
 Something>
Something>
 "foo"
foo
Something>
 $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.3
OS                             Darwin 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELE...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Something>
 Something>

```

**Comment by electricduck** [comment]
This happens on Linux too, just to be aware

**Comment by lzybkr** [comment]
This is https://github.com/lzybkr/PSReadLine/issues/468

I'm quite far along with the real fix - the ansi_render branch fixes the problem on Windows, but that branch still has some Windows specific code, I haven't finished porting everything yet.

**Comment by stuartleeks** [comment]
I'm not clear why this issue is closed.

In PowerShell on Windows (either powershell or pwsh) I can set the prompt with `function prompt {Write-Host "myprompt>" -NoNewline; ' '}` and the prompt that I will get is `myprompt>`

If I try this on Linux then then prompt that I get is `myprompt> myprompt>`

Since this is a difference in behaviour from the full powershell, *and* pwsh on Windows is consistent with the previous behaviour, this feels like it is broken on Linux/macOS.

Looking back at the thread it seems that @lzybkr is having to work around this in PSReadline. I'm a big fan of posh-git and want to set this up for pwsh in WSL and on native Linux, but not fixing this in pwsh means that any libs that depend on the pre-existing behaviour are broken on pwsh on mac/Linux :-(

Look forward to your thoughts

**Comment by stuartleeks** [comment]
Ah, ok... I missed the initial PSReadline reference - thanks :-)
