### ISSUE TITLE
DSC Support for $null optional parameters on configurations (Composite Resources)

### ISSUE THREAD

**Issue by darrenstarr** [PowerShell/PowerShell#4206]
Steps to reproduce
------------------
See [my respository for tests for reproduction](https://github.com/darrenstarr/cDayZeroDeploy/tree/master/PowershellVerification)

I have written four tests (with documentation in the README.md which describe the issues with using optional parameters within Configuration. 

Expected behavior
-----------------

It should be possible to support $null as a value for parameters on Configurations. So for example :
```
Configuration Bob {
  Param(
    [Parameter(Mandatory)]
    [string]$Kevin,
    [Parameter()]
    [string]$Stuart = $null
  )

  cMyFancyResource Minions {
    Name = $Kevin
    FriendsName = $Stuart
  }
}
```

should pass the value of $Kevin to $Name on cMyFancyResource and should pass $null to $FriendsName on cMyFancyResource

Actual behavior
---------------
$Stuart (if type[string])is initialized to a zero-length string causing optional parameters on cMyFancyResource to fail

$Stuart (if type [int]) is initialized to a Zero value integer causing optional parameters on cMyFancyResource to fail

Environment data
----------------

```
Name                           Value                                                                                                                                                              
----                           -----                                                                                                                                                              
PSVersion                      5.1.14393.1358                                                                                                                                                     
PSEdition                      Desktop                                                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                            
BuildVersion                   10.0.14393.1358                                                                                                                                                    
CLRVersion                     4.0.30319.42000                                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                                
SerializationVersion           1.1.0.1    
```

P.S. - I have put a few hours of effort into making series of tests. Please reference the link provided above to clarify as there's a possibility that I haven't done this problem justice in my wording above. The code on that repository is thorough

**Comment by mklement0** [comment]
PowerShell generally won't let you store `$null` in a `[string]`-typed parameter/variable (unlike in C#).

An unbound `[string]` parameter defaults to the _empty string_ (`''`).   
Similarly, on assigning `$null` to a `[string]`-typed variable, the empty string is stored instead.

`[string]` appears to be special in this regard, because other reference types (as opposed to value types) do default to a genuine `$null`.

You can work around the problem by not specifying a type (or using `[psobject]` instead).
If you want to enforce that if a value is passed that it be of type `[string]` use a  `[ValidateScript()]` parameter attribute as follows:

```powershell
[ValidateScript({ $_ -is [string] }, ErrorMessage='A -Stuart value must be a string.')]
$Stuart = $null
```
Note that you need PS _Core_ for the `ErrorMessage` attribute to be honored (Windows PowerShell as of v5.1 will ignore it).

**Comment by darrenstarr** [comment]
Thanks for the quick feedback and I appreciate the clarification. I'm doing a lot of coding on Powershell these days and am trying to be a "Powershell purest" which of course is easier when your competent in a language but as most Powershell code out there is scripting code as opposed to programming, it is often difficult to find good role models to follow.

Since I'd like to know whe a variable was set or not as well as knowing the value set, I tend to like having $null as an option. Since this seems to not be the case, is there something like a [string?] where I can do something like :

  Param (
    [string?] $bob
  )

  if($bob.HasValue) {
    Write-Verbose -Message ($bob.Value + ' rocks the minion world')
  }

Then when passing a [string?] to another function with a [string?] function, the value and presence would carry?

**Comment by mklement0** [comment]
You can use the automatic `$PSBoundParameters` variable to check whether a value was explicitly passed for a given parameter:

```powershell
> & { param($bob) $PSBoundParameters.ContainsKey('bob') }
False

> & { param($bob) $PSBoundParameters.ContainsKey('bob') } 'alice'
True
```

However, typing your parameter `[string]` is not an option, because its implicit default value will be `''`, not `$null`, as discussed.

You can use _splatting_ (passing parameters via a hashtable/array variable prefixed with `@`) to pass the bound parameters on to another function (note, however, that `$PSBoundParameters` only contains _explicitly_ bound values, not those stemming from _default values_ - see #3285).

```powershell
# Pass all explicitly bound parameters through to Foo2 using splatting
Function Foo { param($bob, $alice) Foo2 @PSBoundParameters }
Function Foo2 { param($bob, $alice) $PSBoundParameters }
```

With the above, you get:

```powershell
> Foo -alice 1
Key   Value
---   -----
alice     1
```

Note how `$bob` was not bound in `Foo2` either.

**Comment by darrenstarr** [comment]
I see... food for thought. Again, thanks a lot for the follow up. 

I've moved to using [string]::IsNullOrEmpty($bob) as opposed to ($null -eq $bob). I've managed to write a composite resource which I think should work for me. I'm still 100% dependent on integration tests as I haven't figured out how to mock class module functions yet. So, I think it should be ok for now.
