### ISSUE TITLE
Produce ref assembly for PowerShell Standard 5.1 to enable portable modules

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#4374]
EDIT by @joeyaiello: this is for PowerShell Standard 5.1 now. We need to make the definition *and* publish it.

Intent is to enable module authors to target this library to build portable modules that work across different versions of Windows PowerShell and PowerShell Core.  Tests would need to validate against Windows PowerShell 5.1 and PSCore6 Windows/Linux/Mac.

**Comment by SteveL-MSFT** [comment]
Published as https://www.nuget.org/packages/PowerShellStandard.Library/3.0.0-preview-01

**Comment by iSazonov** [comment]
Should we document the fact in our guides?

**Comment by SteveL-MSFT** [comment]
Yes, reopening this to make sure we have docs and sample

**Comment by joeyaiello** [comment]
This is a dupe of #4809, I'm repurposing this one for 5.1.

**Comment by rkeithhill** [comment]
We could really use this.  Been hitting issues trying to get PSReadLine to compile on Linux as a netstandard2.0 library.  It doesn't work against PS.L v3 because the module uses debugger properties that were added after v3.  Also been trying to get PSES to compile as netstandard2.0 on Linux and I run into a missing property (SupportsVirtualTerminal) on the PSHostUserInterface interface.

BTW should the current library be renamed `PowerShellStandard.3.Library` and the new one be called `PowerShellStandard.5.1.Library`?  Kind of like you've done with the ref assemblies. It's a little weird using the version of the package to indicate the version of PowerShell it targets.  Just sayin'.  :-)

**Comment by jherby2k** [comment]
Would also love to see/test this soon, as you're at "RC" stage now but don't even have a preview library for creating PowerShell 6/5.1 binary modules.

**Comment by SteveL-MSFT** [comment]
@JamesWTruher is actively working on this, but it's not that simple.  We'll likely have a PSStd6-Preview by GA and 5.1 after that.  He needed to create tooling to generate these reference assemblies as the PSStd3-preview was created manually by hand.

**Comment by powercode** [comment]
I would like to see `IArgumentCompleter` interface added to the ref assembly. The absense of it breaks most of my modules :(

**Comment by Jaykul** [comment]
Definitely still need this.

**Comment by iSazonov** [comment]
We have PR #5894

**Comment by jherby2k** [comment]
Any plans for an RTM version?

**Comment by SteveL-MSFT** [comment]
Closing this issue as the working is being done here: https://github.com/powershell/powershellstandard
