### ISSUE TITLE
MSI package should perform pre-req checks

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#4458]
Windows Package has some [pre-reqs](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/windows.md#prerequisites) required.  MSI package should give a good error message directing user to download and install pre-reqs rather than failing at runtime with an unactionable error message.

**Comment by bergmeister** [comment]
OK, so to summarize:

- [Universal C Runtime](https://www.microsoft.com/en-us/download/details.aspx?id=50410) prior to Windows 10
- Visual C++ Redistributable for VS2015 (the [link ](https://my.visualstudio.com/Downloads?pid=2082)to it in the [pre-reqs](https://my.visualstudio.com/Downloads?pid=2082) does not work for people without an MSDN subscription by the way)

@SteveL-MSFT @adityapatwardhan  I think I might be able to help with the 2nd item by following [this](http://wixtoolset.org/documentation/manual/v3/howtos/redistributables_and_install_checks/install_vcredist.html) approach from the official WiX guideline, which is to include and install the Visual++ as part of the installer. WDYT?

**Comment by adityapatwardhan** [comment]
@bergmeister I think that might work. Thanks!

**Comment by bergmeister** [comment]
Due to the fact that the Visual C++ team has made significant refactorings in 2015 (see [here](https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/)), the initial approach of including them as a merge module in the MSI has been deprecated. The alternatives are complex and therefore I think it is best to go back to just giving an error message as initially proposed by Steve.

**Comment by bergmeister** [comment]
@adityapatwardhan : I created the pull request #4602 for it.

**Comment by SteveL-MSFT** [comment]
There's an open issue https://github.com/PowerShell/PowerShell/issues/4665 for this, but we can consider this one closed.
