### ISSUE TITLE
The term 'Subsystem' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by makruiten** [PowerShell/PowerShell#4495]
I'm trying to get Linux to Windows SSHRemoting to work using this guide: https://github.com/PowerShell/PowerShell/tree/master/demos/SSHRemoting. I'm stuck at this step (of course with the correct PowerShell path):

```Subsystem    powershell c:/program files/powershell/VERSION/powershell.exe -sshs -NoLogo -NoProfile```

If I run this command on the Windows 2012 R2 server, it says:

```Subsystem : The term 'Subsystem' is not recognized as the name of a cmdlet, function, script file, or operable program.```

Am I missing something? Is this a PATH issue?

**Comment by makruiten** [comment]
It was not clear to me that this step refers to the sshd configuration.

**Comment by allquiet-hub** [comment]
> How was the problem solved? Why is it closed?

The issue is closed because that is not a command to be executed, but it indicates how the configuration file sshd_config has to be modified.
By default it is:
# override default of no subsystems
Subsystem	sftp	sftp-server.exe

and you have to edit it to:
Subsystem powershell c:/progra~1/powershell/7/pwsh.exe -sshs -nologo
