### ISSUE TITLE
Basic filesystem tests fail intermittently

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#4561]
Example:
https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-beta.5-4620/tests

```
Basic FileSystem Provider Tests.Validate behavior when access is denied.Access-denied test for 'Move-Item -Path C:\Windows\appcompat\Programs -Destination bar
Pester 442 ms
Error message:
Expected string length 70 but was 65. Strings differ at index 0.
Expected: {MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand}
But was:  {RenameItemIOError,Microsoft.PowerShell.Commands.RenameItemCommand}
-----------^
Error stack trace:
at line: 241 in C:\projects\powershell\test\powershell\Modules\Microsoft.PowerShell.Management\FileSystem.Tests.ps1
241:             $err | Should Be $expectedError
```

**Comment by dantraMSFT** [comment]
Leave a comment

**Comment by dantraMSFT** [comment]
We're still seeing intermittent failures due to PowerShell running longer than 10 seconds.  When this occurs, the remaining tests in the context can fail due to the previous PowerShell instance completing after the next test starts (i.e., the $donefile and $errFile from test 1 are not created until test 2 starts, defeating the AfterEach cleanup and the wait logic in the subsequent test.

The fix should address this by using a unique done and error file as well as increasing the timeout.
