### ISSUE TITLE
WindowsInstaller.Tests.ps1 failed on windows 

### ISSUE THREAD

**Issue by chunqingchen** [PowerShell/PowerShell#4720]
Similar to issue #4663

Only this time it repros on windows and affects daily appveyor.

TEST FAILURES
Description: Should have download link about Universal C runtime that is reachable
Name:        Windows Installer.Universal C Runtime Download Link.Should have download link about Universal C runtime that is reachable
message:
Error 404 - Not FoundWarning: This site requires the use of scripts, which your browser does not currently allow.See how to enable scripts

Should we set the tests to be pending until we can stabilize the result?

**Comment by markekraus** [comment]
@TravisEz13 It looks like the `Get-Content` test was set to pending, but not the `Invoke-WebRequest` test which is causing the 404. https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-beta.6-4971

**Comment by bergmeister** [comment]
@chunqingchen : The reason why it failed now was because [this](https://github.com/PowerShell/PowerShell/commit/d5521beb18f5269a1cd4e4bcb122ed65f45a05db) commit did not adapt the test. But it was OK that you set the tests to 'Pending' at the moment, because I am going to issue a new PR with a fix that and will remove the 'Pending' attribute as part of it.
