### ISSUE TITLE
Method members shadow property members of the same name in Get-Member output

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4724]
`[System.Globalization.UnicodeCategory]` has both a `Format` _method_ and a `Format` _property_ (enum value).

While both members can be _called_, `Get-Member` only shows the method member.

Steps to reproduce
------------------

```powershell
[int] [System.Globalization.UnicodeCategory]::Format
[System.Globalization.UnicodeCategory] | Get-Member -Static -Name Format | Select-Object Name, MemberType
```

Expected behavior
-----------------

```none
15

Name   MemberType
----   ----------
Format     Method
Format   Property
```

Actual behavior
---------------

```none
15

Name   MemberType
----   ----------
Format     Method
```

Only the method was reported.

Similarly, `[System.Globalization.UnicodeCategory] | Get-Member -Static -Name Format -Type Property` outputs nothing.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.6 on macOS 10.12.6
PowerShell Core v6.0.0-beta.6 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.0-beta.6 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.502 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by MartinGC94** [comment]
I've looked into this a bit. It seems the issue is caused by `PSMemberInfoInternalCollection` storing the members in a dictionary where the name of the member is the key. We can choose whether or not to replace existing entries, so we can make it prioritize properties over methods, but we can't make it store both without redesigning how `PSMemberInfoInternalCollection` works.

Here's the relevant class: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/MshMemberInfo.cs#L4009 and here's one of the methods that adds methods to that kind of collection: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/CoreAdapter.cs#L3797
