### ISSUE TITLE
Release Notes for 6.0.0 final release

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#4734]
Perhaps one - two years later,then powershell 6.0 will final release.

From now on, We should proceed to sort out a "what is new.md"，(in project docs folder).
Then put new features into it,Stored together, rather than scattered storage.eg:

engine
------------------
add xxx ,from version xxx.

cmdlet
------------------

Is that okay?

**Comment by SteveL-MSFT** [comment]
We have a changelog with every release where we try to summarize the commits targeting use by end users

**Comment by chuanjiao10** [comment]
Yes, but it is decentralized. In the powershell 6.0 final release, the new features, one-time combination together?

**Comment by SteveL-MSFT** [comment]
We would certainly have Release Notes and a blog post for the 6.0.0 final release.  We can use this issue to track that.

**Comment by markekraus** [comment]
Limitations of PowerShell Core 6.0.0 on the macOS platform. Limitations being defined as features that are already included in pwsh but either do not work at all or work partially on macOS (probably due to CoreFX limitations). 

* [ ] Web Cmdlet Client Certificate Authentication Support #4650
* [ ] Web Cmdlet Multiple `-SslProtocol` Support #5329

**Comment by SteveL-MSFT** [comment]
Need to document differences in cmdlets on the different platforms.  ref https://github.com/PowerShell/PowerShell/issues/5448

**Comment by SteveL-MSFT** [comment]
https://blogs.msdn.microsoft.com/powershell/2018/01/10/powershell-core-6-0-generally-available-ga-and-supported/
