### ISSUE TITLE
 Set-AuthenticodeSignature (Unkown Error)

### ISSUE THREAD

**Issue by lbertolotti** [PowerShell/PowerShell#4753]
Set-AuthenticodeSignature is giving me UnkownError. This looks serious.

**Comment by iSazonov** [comment]
What about repo steps, platform and version?

**Comment by george-chakhidze** [comment]
Let me guess: code signing certificate is expired.

**Comment by mattifestation** [comment]
@lbertolotti You're getting UnkownError because your self-signed certificate isn't trusted in the Root certificate store. While New-SelfSignedCertificate won't let you store in the Root store, you can do it with Export/Import-Certificate. Here's some repro code:

```powershell
$Params = @{    
Subject           = "CN=Test Code Signing"
Type              = "CodeSigningCert"    
KeySpec           = "Signature"     
KeyUsage          = "DigitalSignature"    
FriendlyName      = "Test code signing"    
NotAfter          = [datetime]::now.AddYears(5)    
CertStoreLocation = 'Cert:\CurrentUser\My' }

$TestCodeSigningCert = New-SelfSignedCertificate @Params

Export-Certificate -FilePath exported_cert.cer -Cert $TestCodeSigningCert
Import-Certificate -FilePath exported_cert.cer -CertStoreLocation Cert:\CurrentUser\Root

Set-AuthenticodeSignature -Certificate $TestCodeSigningCert -FilePath HelloWorld.exe
```

Upon calling Import-Certificate, you'll get a prompt. Click yes and your file will sign just fine.

**Comment by iSazonov** [comment]
UnkownError looks bad.

**Comment by mattifestation** [comment]
It doesn't bother me because the `StatusMessage` property is very descriptive: `A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.`

**Comment by SteveL-MSFT** [comment]
If `UnknownError` is coming from the cmdlet, then I agree that wrapping it with that exception is not useful and we should fix that so that the detailed message shows up by default on the console.  If that is the case, we can reopen this and repurpose it to get a better error message.  If that error is coming from the cert api, I'd rather than add code to work around their issue.

**Comment by thadfield** [comment]
> It doesn't bother me because the `StatusMessage` property is very descriptive: `A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.`

How would I get to StatusMessage? I can't seem to find a way of getting to that information.

**Comment by mattifestation** [comment]
Hey @thadfield. You'll get that message in the StatusMessage property of the object returned by Set-AuthenticodeSignature or Get-AuthenticodeSignature (a `System.Management.Automation.Signature` object instance). 

```powershell
$Signature = Get-AuthenticodeSignature C:\Windows\System32\kernel32.dll
$Signature.StatusMessage
```

A StatusMessage of `A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider` will indicate that the certificate used to sign the code being validated does not chain to a trusted root certificate, which is often the case when signing with a self-signed certificate. If you're encountering that message, then assuming you accept the risk of trusting your cert, you can follow along with the instructions in the thread above.

I hope that helps!

Cheers,
Matt

**Comment by codaamok** [comment]
I just received this where the property value was `No provider was specified for the store or object` while using `Set-AuthentiCodesignature`. Root cause was that the user didn't have the private key of the code signing certificate in any of their stores, despite trying to sign with a certificate in the LocalMachine store where it did have the private key.

Who do we ask politely to correct throw or feedback to the user the real error?

@SteveL-MSFT  @iSazonov

**Comment by jolting** [comment]
@begemott 
I am using a PFX file, so I am using Get-PfxCertificate.

Try importing it into the keystore too. That should import the private key too.
```
Import-PfxCertificate -FilePath cert.pfx -CertStoreLocation Cert:\\LocalMachine\\My -Password $pass
```

Then call Set-AuthenticodeSignature.

I think it's a Windows bug because that shouldn't be necessary.

I'm using Windows Server 2022 as a jenkins worker on ec2 and I was having trouble with signtool as well in case that information is relevant.

**Comment by begemott** [comment]
Thanks for the replay
I'll try it.

**Comment by achimismaili** [comment]
> I just received this where the property value was `No provider was specified for the store or object` while using `Set-AuthentiCodesignature`. Root cause was that the user didn't have the private key of the code signing certificate in any of their stores, despite trying to sign with a certificate in the LocalMachine store where it did have the private key.
> 
> Who do we ask politely to correctly throw or feedback to the user the real error?
> 
> @SteveL-MSFT @iSazonov

For me, this problem was resolved by executing the command in an admin-powershell. 
It seems, when running the powershell as normal user, there is no access to the private key available ...

**Comment by SetTrend** [comment]
> For me, this problem was resolved by executing the command in an admin-powershell. It seems, when running the powershell as normal user, there is no access to the private key available ...

Shouldn't this cause rather be output as error message than the currently rather cryptic one? IMHO, error messages should help being able to resolve an issue.

**Comment by antonKrouglov** [comment]
I am experiencing the same issue. I have an exe to sign with the specific certificate (pfx file).

Certtool is working flawlessly without any error messages. 

Set-AuthenticodeSignature produces UnknownError with StatusMessage "A certificate chain could not be built to a trusted root authority". BUT exe is becoming signed despite all errors.

Machine where I am trying to sign has no trusted root installed. This is by design.
