### ISSUE TITLE
New-CimSession failing on AppVeyor

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#4819]
Not repro'ing on Win10, maybe WS2012/R2 specific

Steps to reproduce
------------------

```powershell
New-CimSession
```

Expected behavior
-----------------

```none
CimSession created
```

Actual behavior
---------------

```none
Method not found: 'Void System.Security.SecureStringMarshal.ZeroFreeCoTaskMemUnicode(IntPtr)'.
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.6
OS                             Microsoft Windows 10.0.16285
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
I remember seeing this and the issue with MI.net was fixed last year. I will update the Microsoft.Management.Infrastructure.dll in the nuget package.

**Comment by daxian-dbw** [comment]
We use Windows Server 2016 for AppVeyor CIs, and I just logged on an AppVeyor builder and `New-CimSession` works just fine on it. However, we got the failure when running the tests.
This may not relate to the need to update `Microsoft.Management.Infrastructure.Native.dll` in our nuget package because I remember without the fix MMI.Native.dll, `New-CimSesison` won't work on win10. More inveatigation is needed.

**Comment by adityapatwardhan** [comment]
I have tried on Windows Server 2012 R2 and New-Cimsession works fine.

**Comment by SteveL-MSFT** [comment]
@adityapatwardhan Server Core?

**Comment by SteveL-MSFT** [comment]
Going to close this as we no longer rely on AppVeyor.
