### ISSUE TITLE
Promoting a statement-terminating error to a script-terminating one results in unhelpful $Error entry.

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4837]
Note: The behavior may be an indication that there never should have been _statement_-terminating errors to begin with, only _script_-terminating ones, as reflected in [the current documentation neglecting to make this important distinction](https://github.com/PowerShell/PowerShell-Docs/issues/1583).

In practice, an (uncaught) statement-terminating error (e.g., `1 / 0` or `Get-Item -NoSuchParam`) does _not_ terminate the script, but _can_ be made to do so via `$ErrorActionPreference = 'Stop'`, against documented behavior (but _not_ with `-ErrorAction Stop`).

If you do, you get:

* the usual error record reflecting the statement-terminating error  in `$Error`
* an _additional, unhelpful_ `$Error` entry that is simply a _part_ of the statement-terminating-error record, namely the _underlying exception_.

In other words: you get _2_ `$Error` entries, with the exception-only entry coming after (reflected in `$Error[0]` immediately after, with `$Error[1]` containing the statement-terminating-error record.

The exact relationship is:

```powershell
[object]::ReferenceEquals($Error[1].exception, $Error[0]) # -> $True
```

Contrast this with promoting a _non-terminating_ error to a script-terminating one, where you also get _2_ entries, but the extra entry is a _helpful_ exception (`[System.Management.Automation.ActionPreferenceStopException]`) whose message reflects the fact of the promotion:

```powershell
# Promote a non-terminating error to a script-terminating one.
> $Error.Clear(); Get-Item -ErrorAction Stop /NoSuchItem
Get-Item : Cannot find path '/NoSuchItem' because it does not exist.
...
# Print the message of the extra $Error entry that was recorded.
# (exception System.Management.Automation.ActionPreferenceStopException)
> $Error[0].Message
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path '/NoSuchItem' because it does not exist.
```

Steps to reproduce
------------------

```powershell
$Error.Clear(); $ErrorActionPreference = 'stop'; Get-Item -NoSuchSwitch
'---'
$Error | % GetType | % Name
```

Expected behavior
-----------------

I'm describing expected behavior from the perspective of consistency with how things work with _non-terminating_ errors:

```none
Get-Item : A parameter cannot be found that matches parameter name 'NoSuchSwitch'.
...
---
ActionPreferenceStopException  # indicate promotion to script-terminating error
ErrorRecord
```

Actual behavior
---------------

```none
Get-Item : A parameter cannot be found that matches parameter name 'NoSuchSwitch'.
...
---
ParameterBindingException # !! Simply duplicated the .Exception value of $Error[1]
ErrorRecord
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.6 on macOS 10.12.6
PowerShell Core v6.0.0-beta.6 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.0-beta.6 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.502 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by KirkMunro** [comment]
Wouldn't a more appropriate expected behavior for this be a single entry in `$error` consisting of the `ErrorRecord` that identifies the error, with Exception referencing an `ActionPreferenceStopException` that has an `InnerException` of `ParameterBindingException`?

i.e. Why are we generating two entries in `$error` for what an end user perceives as a single error?

Similarly, when you have a `ParseException`, why are we adding an exception of type `ParseException` to that contains an `ErrorRecord` with an Exception of type `ParentContainsErrorRecordException` to `$error`? Why don't we simply add an `ErrorRecord` that contains an exception of type `ParseException` instead?

In either case, these changes could possibly be breaking for anyone who had built tooling that processes `$error` or that performs error handling, so does it matter? I'm not asking that because I feel these changes should be made -- the fact that raw exceptions are added to `$error` and they way they are added makes it more difficult to process errors since the contents of the collection are inconsistent -- but I do wonder if it's worth my time to go through and try to correct such issues (which I would do, because I'm spending a lot of time with the PowerShell parser and debugger right now). I suppose an RFC is in order to discuss the collection of issues and propose a fix that would be beneficial enough to implement.
