### ISSUE TITLE
Guidance on redirecting Console.Out to PowerShell output stream

### ISSUE THREAD

**Issue by ebekker** [PowerShell/PowerShell#4849]
This is not an issue or bug, but I'm looking for some *official* guidance -- if I'm writing a binary module, in general, what would be the proper or recommended way to redirect data sent to a `TextWriter` to a PowerShell output stream?

Specifically, let's say I've included a 3rd-party library in my PS module that happens to write normally to `Console.Out`.  If I want all that output to go to PowerShell's Output stream instead so that it can be *seen* by the environment and the runspace pipeline -- how should I go about this?

The naive approach would be to replace `Console.Out` via `Console.SetOut(...)` with my own `TextWriter` instance, say a `StringWriter` that buffers all the output and then I can spit it out all out at once via `WriteObject`.  A more elegant approach would be to implement my own `TextWriter` whose `Write(...)` methods do an immediate write out via `WriteOutput`.

But my intuition tells me there must be a more *standard* approach to this?

**Comment by ebekker** [comment]
Someone mentioned that @dlwyatt's [PowerShellLoggingModule](https://github.com/dlwyatt/PowerShellLoggingModule) may already be doing something like this, but taking a quick look through the code, it appears this is doing capture and redirection of the Host's output, which is on the "PowerShell side" of things, not in the Console IO of the underlying .NET runtime.

**Comment by SteveL-MSFT** [comment]
Cc @lzybkr might be the best person to give guidance here

**Comment by lzybkr** [comment]
If the 3rd-party code is wrapped in an `exe` - it might be easiest to run the exe directly to get the output back in a PowerShell friendly way, something like:

```c#
var ps = PowerShell.Create(RunspaceMode.CurrentRunspace);
ps.AddCommand("your_command.exe");
var output = ps.Invoke();
foreach (var o in output) {
    WriteObject(o);
}
```

Otherwise I think your approaches are reasonable options.

It sounds like you are wrapping some 3rd-party code - so you might consider structured output instead of the strings the 3rd-party code is writing. If parsing the text output from that 3rd-party code, then you save the users of your command the trouble of parsing the text (possibly incorrectly) themselves.

**Comment by ebekker** [comment]
Thanks!  I'll go with that.
