### ISSUE TITLE
Allow per-connection remote server certificate validation

### ISSUE THREAD

**Issue by xuesongyuan** [PowerShell/PowerShell#4893]
Steps to reproduce
------------------

```powershell

```

Expected behavior
-----------------

There should be a way to specify RemoteCetificateValidationCallback in a similar fashion to HttpWebRequest.RemoteCertificateValidationCallback. This will allow a per-connection certificate validation instead of the per-process validation via ServicePointManager.RemoteCertificateValidationCallback. This will be extremely useful for a service that is establishing PSH connection to many hosts.

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by SteveL-MSFT** [comment]
This is in the context of the web cmdlets.  What @xuesongyuan is asking for is a way to inspect the server cert and approve or deny

**Comment by markekraus** [comment]
This seems doable, with [`HttpClientHandler.ServerCertificateCustomValidation`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.servercertificatecustomvalidationcallback?view=netcore-2.0#System_Net_Http_HttpClientHandler_ServerCertificateCustomValidationCallback).

It expects a `Func<HttpRequestMessage,X509Certificate2,X509Chain,SslPolicyErrors,Boolean>`. But if I'm not mistaken that can easily be made to work with a `ScriptBlock`. 

I guess the question is how to set it. It could be supplied as a parameter or perhaps exposed as a public static property on `WebRequestPSCmdlet` or somewhere else (maybe its own singleton?). I imagine that most users would want this as a sort of `set and forget` for the duration of the thread as the callback could contain the logic for all their calls to the Web Cmdlets. 

Making it a parameter is the easy route, but then user would have to supply it every call or set it as a `$PSDefaultParameterValues` entry. That might be a bit inconvenient, but it is definitely a pattern most PowerShell users are familiar with. If the Parameter is acceptable, this could be implemented fairly quick.

**Comment by SteveL-MSFT** [comment]
I think a scriptblock parameter is fine for now.

**Comment by markekraus** [comment]
Is this one up for grabs or will the Microsoft team be taking this one?

**Comment by xuesongyuan** [comment]
Just wanted to make sure that this callback will be available through System.Management.Automation.Runspaces, e.g., WSManconnectionInfo, or something similar.

**Comment by markekraus** [comment]
@xuesongyuan  You are not referring to `Invoke-WebRequest` and `Invoke-RestMethod`? I'm not sure I follow the connection between legacy `HttpWebRequest.RemoteCertificateValidationCallback` and runspaces.

**Comment by xuesongyuan** [comment]
It seems useful to support Invoke-WebRequest and Invoke-RestMethod. However, the one we are looking for is to provide callback overriding capability so that it is not just SkipCA/SkipCN on WSManConnectionInfo.

Basically, we would like to do a server certificate validation when opening a remote runspace. So far, we have been using either SkipCA or SkipCN. It would be much better if we can check thumbprint of the certificate since we provision VM with a specific certificate protecting WinRM over HTTPS. This can somewhat be achieved through ServicePointManager.RemoteCertificateValidationCallback however it affects all SSL connections.

**Comment by SteveL-MSFT** [comment]
@markekraus in general, I've been marking issues as `Up-for-grabs` to indicate both that the Microsoft PowerShell Team doesn't intend to implement it AND that it's relatively easy for someone new to pick it up.  Contributors, such as yourself, can pick up any issue that isn't assigned to someone.  Expectation is that my team members assign issues to themselves if they are actively working on it.  Unassigned means anyone can take it.  Since GitHub doesn't allow assigning to contributors not in the PowerShell Org, make a statement here if you intend to take it (awesome!) and I can assign it to myself so we don't get duplicate work.

**Comment by markekraus** [comment]
@SteveL-MSFT Thanks for clarifying, Unfortunately, it looks like we missed the mark on what @xuesongyuan was requesting. It looks like they are referring to remoting. I believe the web cmdlets are completely decoupled from that in Core. `HttpClient` _only_ uses per-connection validation callbacks, but I'm not familiar with anything in the remoting code to be of use there and at glance it is not using `HttpClient`.

I can see value in supplying a callback for the web cmdlets, so I will create a new issue to track that. 

As for assigning issues to contributors, @iSazonov has been able to [assign to me](https://github.com/PowerShell/PowerShell/issues?q=is%3Aissue+assignee%3Amarkekraus+is%3Aclosed) in the past.

@xuesongyuan It would be possible in 5.1 to create validation logic that would accommodate both remoting and web requests by including checks on the `sender` object. I don't think `ServicePointManager.RemoteCertificateValidationCallback` works at all in Core.

**Comment by xuesongyuan** [comment]
@markekraus I saw ServicePointManager remote cert validation callback mechanism mentioned but have never tried it out since it does not fit our requirement. As to 5.1, what is the timeline? What does the API look like?

**Comment by markekraus** [comment]
@xuesongyuan I think we are on different topics. The feature available in 5.1 already is the `ServicePointManager.RemoteCertificateValidationCallback`. This is not available in 6.0. I do not know how or if this impacts remoting. But if it does impact both web requests and remoting in 5.1, the logic in the callback can handle both but you would need to do checks on the `sender` object to determine what is calling it. I'm not meaning to suggest this is possible, but that it is something you could test now in Windows PowerShell 5.1.

I apologize for the confusion. I only jumped into the thread because of the mention of Web Cmdlets. remoting topics are a bit out of my depth.

**Comment by SteveL-MSFT** [comment]
If this is needed at the api level, we wouldn't start looking at it until after 6.0.0 ships and no commitment to doing it in 6.1.0

**Comment by xuesongyuan** [comment]
What are timeframes for 6.0.0 and 6.1.0?

**Comment by SteveL-MSFT** [comment]
Expectation is that 6.0.0 is final by end of this year, 6.1.0 is undefined at this time but starts after 6.0.0
