### ISSUE TITLE
Automatic -PSSession parameter  

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#5016]
We should implement  automatic `-PSSession` parameter to expose direct remoting support in all cmdlets.

**Comment by SteveL-MSFT** [comment]
The only minor complication is for cmdlets that already expose it.  Specially the *-PSSession cmdlets.  However, I think it'd be nice to be able to target any cmdlet remotely without having to use Invoke-Command.

**Comment by RichardSiddaway** [comment]
Is this a replacement for the current computername parameter that a number of cmdlets e.g. Get-Process have.  Unifying the remoting approach to remove the DCOM\RPC type emoting would be a good approach

**Comment by SteveL-MSFT** [comment]
@RichardSiddaway yes, that is the thinking.  Remove the existing `-ComputerName` parameters that go over RPC (now) and introduce automatic `-PSSession` parameter for a unified remoting experience

**Comment by RichardSiddaway** [comment]
Good. gets my vote.  Thanks for clarifying.

**Comment by SteveL-MSFT** [comment]
There's a couple of interesting aspects about this we should consider:

1. if the target doesn't have the cmdlet, can we proxy or install it?
2. can we make this pluggable so modules can participate.  For example, imagine a future AzureRM.NetCore module where you can get an automatic `-azureComputerName` type parameter so you can more easily run commands against Azure targets

**Comment by iSazonov** [comment]
PowerShell Virtual Machine?

**Comment by RichardSiddaway** [comment]
Automatically installing a cmdlet on a remote machine isn't a good thing. Do you install the module containing the cmdlet or just the module. What's the impact is something goes wrong. In the event of a problem on the remote machine how do you stop the automatic install of a cmdlet being blamed  - - "well it was the last change so it must have caused the problem" type argument. 
Proxying the cmdlet - sort of reverse implicit remoting - so that nothing is left behind when the remote session finishes is a much cleaner and safer approach.

**Comment by iSazonov** [comment]
Do "pluggable" needs a public API in SDK?

**Comment by SteveL-MSFT** [comment]
@iSazonov yes, pluggable means public api

**Comment by RichardSiddaway** [comment]
The bottom line is that -force is a "just do it" option. It has various connotations depending on scenario but in all cases you're over-riding whatever is stopping the action. PowerShell users have got used to -Force so it would be the logical option.
