### ISSUE TITLE
Fix or remove scripts that install powershell on openSUSE

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#5023]
> **Note:** When installing the SDK, SUSE and OpenSUSE may report that nothing provides libcurl. libcurl should already be installed on supported versions of both distros. Run zypper search libcurl to confirm. The error will present 2 'solutions'. Choose 'Solution 2' to continue installing .NET Core.

A manual step is required for install powershell on openSUSE (same as `dotnet-sdk-2.0.0`), so the current scripts that automatically set up powershell on OpenSUSE don't work.
Two scripts are affected:
- tools/download.sh
   It will continue to install the beta.6 powershell openSUSE package.
- tools/installpsh-suse.sh
   It's already broken since beta.7, because we stopped publishing suse.42.1 package in beta.7 because openSUSE 42.1 has reached the end of the lifecycle.

So we need to update those two scripts or remove them.

**Comment by daxian-dbw** [comment]
A related issue: #5023

**Comment by DarwinJS** [comment]
@daxian-dbw - I would like to make an installer for amazon linux based on this script.
I see some zypper packages in here and amazon linux uses yum.

It *seems* like I should just be able to change that section to yum because the packages are still RPMs right?

Also, besides distro detection logic, can you think of anything else that would need adaptation?

**Comment by daxian-dbw** [comment]
For Amazon Linux, you can use [community/amazonlinux/Dockerfile](https://github.com/PowerShell/PowerShell/blob/master/docker/community/amazonlinux/Dockerfile) as an example.
The RPM package doesn't work on Amazon Linux because Amazon Linux doesn't have the package 'openssl-libs'. See #5027 for more information.
