### ISSUE TITLE
Transcript doesn't capture warnings and verbose output when remoting with invoke-command

### ISSUE THREAD

**Issue by kwint** [PowerShell/PowerShell#5063]
Currently this script:
```
Start-Transcript D:\temp.txt

$script = { Write-Host "Write-Host"; Write-Warning "Write-Warning"; Write-Verbose "Write-Verbose" -Verbose}
Invoke-Command -ComputerName RemoteComputer -ScriptBlock $script

Stop-Transcript
```
Produces this output in the shell/host (which is expected):
```
Transcript started, output file is D:\temp.txt
Write-Host
WARNING: Write-Warning
VERBOSE: Write-Verbose
Transcript stopped, output file is D:\temp.txt
```
But the transcription doesn't capture the warning and verbose output:
```
Transcript started, output file is D:\temp.txt
INFO: Write-Host
```

**Comment by SteveL-MSFT** [comment]
This doesn't repro for me on PSCore6 beta.8, need more info:

```powershell
PS C:\> Start-Transcript .\test.log
Transcript started, output file is .\test.log
PS C:\> & $script
Write-Host
WARNING: Write-Warning
VERBOSE: Write-Verbose
PS C:\> stop-transcript
Transcript stopped, output file is C:\test.log
PS C:\> cat test.log
**********************
PowerShell transcript start
Start time: 20171009090103
Configuration Name:
Host Application: C:\Program Files\PowerShell\6.0.0-beta.8\powershell.dll
Process ID: 3040
PSVersion: 6.0.0-beta.8
PSEdition: Core
GitCommitId: v6.0.0-beta.8
OS: Microsoft Windows 10.0.17010
Platform: Win32NT
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
**********************
Transcript started, output file is .\test.log
PS C:\> & $script
Write-Host
WARNING: Write-Warning
VERBOSE: Write-Verbose
PS C:\> stop-transcript
**********************
PowerShell transcript end
End time: 20171009090111
**********************
```

**Comment by poshcodebear** [comment]
I know this was opened (and closed) 3 years ago, but I'm able to reproduce it in 7.0.3:

```powershell
PS C:\Users\<username>\Desktop\test> Start-Transcript temp.txt
Transcript started, output file is temp.txt
PS C:\Users\<username>\Desktop\test>
PS C:\Users\<username>\Desktop\test> $script = { Write-Host "Write-Host"; Write-Warning "Write-Warning"; Write-Verbose "Write-Verbose" -Verbose}
PS C:\Users\<username>\Desktop\test> Invoke-Command -ComputerName <remote-machine> -ScriptBlock $script
Write-Host
WARNING: Write-Warning
VERBOSE: Write-Verbose
PS C:\Users\<username>\Desktop\test>
PS C:\Users\<username>\Desktop\test> Stop-Transcript
Transcript stopped, output file is C:\Users\<username>\Desktop\test\temp.txt
```

And here's the transcript:

```powershell
**********************
PowerShell transcript start
Start time: 20200831102919
Username: <DOMAIN>\<username>
RunAs User: <DOMAIN>\<username>
Configuration Name: 
Machine: <localmachine> (Microsoft Windows NT 10.0.17763.0)
Host Application: C:\Program Files\PowerShell\7\pwsh.dll -NoProfile
Process ID: 1016
PSVersion: 7.0.3
PSEdition: Core
GitCommitId: 7.0.3
OS: Microsoft Windows 10.0.17763
Platform: Win32NT
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.3
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
**********************
Transcript started, output file is temp.txt
PS C:\Users\<username>\Desktop\test> $script = { Write-Host "Write-Host"; Write-Warning "Write-Warning"; Write-Verbose "Write-Verbose" -Verbose}
PS C:\Users\<username>\Desktop\test> Invoke-Command -ComputerName <remotemachine>> -ScriptBlock $script
Write-Host
PS C:\Users\<username>\Desktop\test> Stop-Transcript
**********************
PowerShell transcript end
End time: 20200831102922
**********************
```

I came across this issue specifically because I was tracking down why I couldn't redirect Warning output from Exchange, the only thing it seemed to respect was -WarningAction which let me suppress warnings, though what I was really looking for was to capture them so I could address them.  I suspect it's happening for the same reason this is, that it has to do with the fact that Exchange is a remote PS connection and remote connections are having this issue.  It appears to be putting Warning data into the Warning stream (it shows up like that's where it is), but it cannot be manipulated like the Warning stream (even redirecting all streams does not affect Warnings).

Additional information that might prove useful for replicating the problem: the remote systems I replicated it with were an Exchange server running on Server 2016 (1607), and a Windows 10 (1909) desktop, using both PowerShell 7.0.3 (and 7.0.2; I need to update one of my systems) and PowerShell 5.1.  The PS 7 test against the Win10 box is the one that ran on 7.0.2.

I don't have any machines left running PS 6 to test to see if it behaved differently with that release.

This appears to generally affect data streams 3, 4, and 5 when they come from a remote session.  Streams 1, 2, and 6 appear to redirect as expected.  A much easier way to replicate this is just try using direct stream redirection, like this `icm -comp <remote>  -ScriptBlock {Write-warning 'test'} 3> warn.txt`.  If you leave out -ComputerName, redirection of streams 3, 4 ,and 5 work as expected, but not when received from a remote connection.

This also affects -<Stream>Variable: the affected streams still display on the host console but are not added to the variable as requested.  -<Stream>ActionPreference works as expected.

Let me know if you need any more help replicating this issue; it breaks the stream model in PowerShell and is generally frustrating, and makes certain things impossible to automate.
