### ISSUE TITLE
ServerCertificateValidationCallback has no effect on Invoke-WebRequest/RestMethod

### ISSUE THREAD

**Issue by snobu** [PowerShell/PowerShell#5098]
Referencing the open issue here - https://github.com/PowerShell/PowerShell-Docs/issues/1753
Is this a bug or is it by design?

**Comment by markekraus** [comment]
This is `By Design`. PowerShell core uses `HttpClient` which does not make sue of any of the settings available in `[System.Net.ServicePointManager]`. 

A new feature is in the works. see #4899

**Comment by snobu** [comment]
This is Windows PowerShell 5.1 (full framework) that i'm using to repro. Should i open the issue somewhere else?

**Comment by markekraus** [comment]
So that API is not native to powershell. It is a part of the .NET framework and is expecting a certain type of .NET delegate to be supplied. I have seen workarounds for it where thy declare a very simple C# class with `Add-Type` or by using reflection to modify the internals of `System.Net.ServicePointManager`. Generally, a script block does not work here.

**Comment by SteveL-MSFT** [comment]
@snobu Windows PowerShell issues/suggestions should be posted on [Uservoice](https://windowsserver.uservoice.com/forums/301869-powershell)
