### ISSUE TITLE
Keep PowerShell settings (theme, colors, fonts, sizes etc) on Windows upgrade

### ISSUE THREAD

**Issue by regs01** [PowerShell/PowerShell#5111]
With every Windows update all PS settings gets reset to blue background, little font and window. Can those settings be preserved?

**Comment by markekraus** [comment]
You could add code to your `$profile` to set most of these:

```powershell
$console = $host.UI.RawUI
$console.ForegroundColor = "black"
$console.BackgroundColor = "white"
...
```

**Comment by SteveL-MSFT** [comment]
For Windows PowerShell, those settings aren't set to be preserved and no plans to change.  For PSCore6, I would expect the shortcut settings to be preserved since it's not part of Windows.  As @markekraus provided, a better option might be to set it in your profile.  Something I've seen people do is have a line in their profile which actually points to a profile stored in the cloud (OneDrive, Azure blob, whatever), then you can have a "roaming" profile where every machine you're on has the same profile (not useful unless you use different machines)
