### ISSUE TITLE
Add "Describe" as an approved Verb

### ISSUE THREAD

**Issue by nanalakshmanan** [PowerShell/PowerShell#5245]
Describe is currently not an approved verb. However it is widely used in the AWS CLI. The way the AWS PowerShell modules get around this is by changing the noun to include a list. 

Here is an example of the AWS CLI and PowerShell equivalent for describe

```
PS /> aws ssm describe-automation-executions                                    
```

```PowerShell
PS /> Get-SSMAutomationExecutionList 
```

Here is an example for AWS CLI and PowerShell example for the Get API

```
PS /> aws ssm get-automation-execution  
```

```PowerShell
Get-SSMAutomationExecution
```
Essentially, you do a describe by doing a Get and adding List to the noun. This can be avoided and the command can be truly PowerShell style if Describe is an approved verb.

Environment data
----------------

```powershell
PS /> $PSVersionTable                                                           

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-beta.8                                    
PSEdition                      Core                                            
GitCommitId                    v6.0.0-beta.8                                   
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: T...
Platform                       Unix                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1                                         
WSManStackVersion              3.0    

```

**Comment by nightroman** [comment]
Why not `Show-X` instead of `Get-XList`?

**Comment by markekraus** [comment]
`Describe` to me is an active verb, not a passive one when I see the word I think if will be defining or scaffolding something. 

To me, `describe-automation-executions` and `get-automation-execution` should both be `Get-SSMAutomationExecution` where the default of `Get-SSMAutomationExecution` would return all and `Get-SSMAutomationExecution -ExecutionId $value` or something would return the specific one.

**Comment by FireInWinter** [comment]
@nanalakshmanan I believe that Get is the correct verb mapping from AWS describe.  Adding describe to PowerShell just because AWS uses it, isn't the best reason for adding a new approved verb.  It doesn't really define something new that isn't already included in what Get does.  

I've worked a LOT with AWS and find the mapping works fairly well.  Some of their design choices don't yet match with PowerShell totally, but they have been getting better over the years. In this case, their design decision used *List instead of something else.  Also, some of their commands only have a "describe-" options.  For example for "aws ec2 describe-instances" doesn't have a "get-instance" to go with it, so now you would have a PowerShell Describe-EC2Instance without a Get-EC2Instance.  It would be very confusing.

@markekraus Your design makes sense.  Maybe AWS will eventually do something similar.

@nightroman The "Show" verb "Makes a resource visible to the user. This verb is paired with Hide." from https://msdn.microsoft.com/en-us/library/ms714428(v=vs.85).aspx.  This doesn't match with how AWS uses "describe".

**Comment by nightroman** [comment]
> The "Show" verb "Makes a resource visible to the user. This verb is paired with Hide."

In reality, `Show` is used almost as authors want and find it suitable. I never saw it paired with `Hide` yet, too.
