### ISSUE TITLE
Remove the workaround to enable macOS launcher

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#5262]
The change was reverted to unblock PRs being blocked in packaging. 

https://github.com/PowerShell/PowerShell/pull/5259

Further investigation should be done to re-enable macOS launcher.

**Comment by thezim** [comment]
Looks like a [permissions](https://github.com/PowerShell/PowerShell/blob/8234e3cd19a0eda96e494217f6973c91b23be188/tools/packaging/packaging.psm1#L665) issue to me. Is the account doing the build (owner) the same as who created the inital file structure. I could rewrite it so it builds the app in a user space temp folder such as `TMPDIR` to avoid conflicts.

**Comment by adityapatwardhan** [comment]
@thezim yes it is the same account. It would be great if you could send a PR to resolve this.

**Comment by thezim** [comment]
### Issue ###

@adityapatwardhan so I found out what is going on. When the the installation of PowerShell occurs it is actually recognizing the app that exists in the packaging folder and updating the copy there `tools/packaging/macos/launcher/ROOT/Applications/PowerShell.app` instead of installing it to `/Applications` as you would think. Since it gets installed as root:wheel 755 you lose access to the files.

This issue only occurs on a machine with build on it. I verified that a vanilla High Sierra does not have this issue with just the installation from .pkg.

I'm afraid moving it to different temporary folder will probably not work as it will get picked up there too. My intuition is one the the identifiers in Info.plist is triggering its pickup. Removing the `tools/packaging/macos/launcher/ROOT/Applications/PowerShell.app` folder prior to installation does fix the issue.

### Possible solutions ###

1. Remove the macOS app folder just after `fpm` runs [here](https://github.com/PowerShell/PowerShell/blob/a8008f8cbb588f8d4278107964c6ab6396ba838f/tools/packaging/packaging.psm1#L638). Not the best but maybe good enough for getting past CI.
2. Have packaging build the macOS app procedurally as it is simple a few files and folders then remove the folder after packaging, same as in 1. This has the advantage of not having the folder structure and files in the repo directly as they can be generated at will.
3. Figure out what is triggering the capture of the build staging launcher and make a change to the plist and/or structure to prevent if from being picked up post `fpm`.

Also for anyone wanting to try to repro this to uninstall PowerShell from OS you should be using the following. I will get documentation updated soon with the below.

```bash
sudo rm -rf /usr/local/microsoft /usr/local/bin/pwsh /Applications/PowerShell.app /usr/local/share/man/man1/pwsh.1.gz
sudo pkgutil --forget powershell
```

/cc @TravisEz13

**Comment by TravisEz13** [comment]
@thezim If you enable travis-ci or your branch, it will attempt to build the package each time you attempt to push.  I don't have any preference between 1 & 2.  Although, we are getting close to release.  We should probably be looking for a simple solution.  It seems to me 1 is simpler (if it works.)

**Comment by thezim** [comment]
After digging in to it option 1 wasn't really viable because subsequet package builds would fail as the structure it needs would be gone. Option 2 was the most work so I first tried Option 3 and was able to get it working. PR #5291 has been submitted.

/cc @adityapatwardhan
