### ISSUE TITLE
Get-Content not support -Encoding Byte in beta 9

### ISSUE THREAD

**Issue by SyuichiMurashima** [PowerShell/PowerShell#5279]
Steps to reproduce
------------------
$ByteData = Get-Content $Path -Encoding Byte
```powershell

```

Expected behavior
-----------------
beta 8 supported -Encoding Byte
beta 9 support too.
```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by iSazonov** [comment]
Please try new parameter `-Byte`.

**Comment by mklement0** [comment]
@iSazonov: It is actually `-AsByteStream`.

@SyuichiMurashima: Presumably because a raw byte stream is not technically a character encoding, a decision was made to give it its own switch and to no longer support `-Encoding Byte` - see https://github.com/PowerShell/PowerShell/pull/5080#issuecomment-337757723 (the new switch name has since been changed to `-AsByteStream`).

**Comment by SyuichiMurashima** [comment]
Oh !!
Thank you.
