### ISSUE TITLE
Trap statement doesn't take effect when dot-sourced

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#5342]
Defining a `Trap` statement via a dot-sourced script does not work, which is surprising, given that dot-sourcing<sup>[1]</sup> is generally equivalent to including the referenced script's content directly in a script.

Steps to reproduce
------------------

Setup:

Content of `t1.ps1`:

```powershell
. ./t2.ps1
1 / 0
'after'
```

Content of `t2.ps1`:

```powershell
Trap { 'Shame.'; exit 1 }
```

Command that reproduces the symptom:

```powershell
> ./t1.ps1`
```

Expected behavior
-----------------

```none
Shame.
```

The `Trap` handler should take effect, output the specified string, and exit with exit code `1`.

Actual behavior
---------------

```none
Attempted to divide by zero.
At /Users/jdoe/t1.ps1:5 char:1
+ 1 / 0
+ ~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException
 
after
```

The `Trap` handler was ignored altogether, due to being dot-sourced rather than being included directly in the script.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.9 on macOS 10.13
PowerShell Core v6.0.0-beta.9 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.0-beta.9 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.674 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

---

<sup>[1] Nomenclature quibble: Why is `.` called the _dot_-sourcing operator, and not just _sourcing_ operator? Contrast this with `&`, the _call operator_, which is mercifully not called the "ampersand call operator". Including the somewhat arbitrary _syntactic form_ in the name seems unnecessary.</sup>

**Comment by iSazonov** [comment]
With t1.ps1
```
. ./t2.ps1
1 / 0
Trap { '!!!!! Shame.'; exit 1 }
'after'

```
I get strange result too.

**Comment by mklement0** [comment]
@iSazonov:  

Strange in what way? 

When I try your snippet, the in-script `Trap` takes effect (it's fine to place it after the offending statement), and the sourced one is still ignored.

So it seems to me that both snippets demonstrate the same problem.

**Comment by iSazonov** [comment]
I don't see an error for previous command `1/0`.

**Comment by BrucePay** [comment]
@mklement0 @iSazonov  `trap` is a lexical construct, scoped to the compile unit (i.e. the script). This is why dot-sourcing a file with a `trap` statement doesn't introduce a trap into the caller's environment. When the dot-sourced script exits, its traps are removed. This is also why defining a `trap` by itself on the command line
```
PS[1] (39) > trap { Write-Host Hello }
PS[1] (40) >
```
appears to do nothing. The command executes and then the trap is removed.

NOTE: In V1, we did consider allowing traps defined in dot-sourced scripts or on the command line to persist in the caller's environment however this would have required additional commands to enumerate and manage traps.  Due to a lack of time/resources, this was not implemented for V1 and it would be a significant breaking change to do so now.

**Comment by BrucePay** [comment]
No additional updates so I'm closing this.

**Comment by mklement0** [comment]
@SteveL-MSFT: Can you please add the `Documentation Needed` label so that @BrucePay's explanation can be rescued from obscurity?
