### ISSUE TITLE
Unpredictable ordering of native command output when merging the error stream into the success output stream

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#5424]
Steps to reproduce
------------------

```powershell
bash -c 'echo a; echo b >&2; echo c' 2>&1
```

On Windows, use `cmd /c 'echo a & echo b >&2 & echo c' 2>&1`.
Additionally, in _Windows PowerShell_, append `| % tostring`.

Note that it is the addition of `2>&1` that triggers the problem.

Expected behavior
-----------------

```none
a
b
c
```
That is, the output lines should be printed in the order written, across streams.

Actual behavior
---------------

_Intermittently_, the output order is unexpected in that the stderr output line is printed out of order; e.g.:

```none
a
c
b
```

or 

```none
b
a
c
```

If you have trouble seeing the symptom, try something like the following

Unix:

```powershell
while ($true) { if (($a = bash -c 'echo a; echo b >&2; echo c' 2>&1)[1] -notmatch 'b') { $a; break} }
```

Windows:

```powershell
while ($true) { if (($a = cmd /c 'echo a & echo b >&2 & echo c' 2>&1 | % tostring)[1] -notmatch 'b') { $a; break}  }
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.9 on macOS 10.13
PowerShell Core v6.0.0-beta.9 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.0-beta.9 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.674 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by PetSerAl** [comment]
I do not think this is really solvable. Either you redirect stdout and stderr separately. That allows you to distinguish them, but you will not be able to guaranty, that receiving side will handle them in the same order. Either you join stdout and stderr in one destination, that guaranty that you see data in the same order, but you will not be able to distinguish them.

**Comment by redvers** [comment]
This is normal and expected behaviour for stdout and stderr on UNIXes.  The assumption that it is predictable by the original reporter is wrong, and the example provided isn't a legitimate test.  This is why.

Buffering.

The output gets pushed into the string when the stderr or stdout is flushed.  When does that happen?
i. When it feels like it.[0]
ii. When the program explicitly flushes.
iii. When a program exits.

Take a closer look at the example given:

```bash
bash -c 'echo a; echo b >&2; echo c' 2>&1
```
This example is actually _FOUR_ programs, not one.

bash is the parent, and it spawns three __serial__ echo commands.  Each echo is a separate process, typically /bin/echo.

That means that, in the above example - the command "/bin/echo a" has to execute, complete, flush, and exit before the "/bin/echo b" is executed.

This results in the ONLY possible ordering being:
a
b
c

To get the output the OP desires, they need to explicitly flush in their application when they want it.  Languages tend not to autoflush as it causes their performance to sink into the dirt (although some give the option).

I would assume that there's a function that can be called to flush the output of stdout and stderr.  If there isn't, that's a feature you probably want - but it's not a bug.


Red

[0] There are actually hard and fast rules, but they're nondeterministic.

**Comment by redvers** [comment]
I just examined the syscalls executed in the above example and need to correct myself, in this environment bash used internal echo.

Something to bear in mind from the POSIX standard:

```
       At  program start-up, three streams shall be predefined and need not be opened explicitly:
       standard input (for reading conventional input), standard output (for writing conventional
       output),  and  standard	error  (for writing diagnostic output). When opened, the standard
       error stream is not fully buffered; the standard input and  standard  output  streams  are
       fully  buffered if and only if the stream can be determined not to refer to an interactive
       device.
```

So stderr is unbuffered, stdin/stdout is buffered.

The OP may get the desired behaviour by executing a flush after printing their stdout.

[Console]::Out.Flush() maybe?

**Comment by SteveL-MSFT** [comment]
@redvers thanks for your insights into this.  Your explanation makes sense and consistent with the behavior observed.

**Comment by redvers** [comment]
You're welcome.  This is Day 0 for me with Powershell, off to a good start I guess :-)

Later

**Comment by mklement0** [comment]
@redvers:

> This results in the ONLY possible ordering being:
a
b
c

And that is precisely the order that PowerShell is _not_ providing, as demonstrated in my original example.

Bash _always_ gets this ordering right, PowerShell _frequently_ does _not_.

You can verify this by letting _Bash_ rather than PowerShell do the stream merging: The following loop _never_ exits, because the order is _always_ as expected:

```powershell
while ($true) { if (($a = bash -c '{ echo a; echo b >&2; echo c; } 2>&1')[1] -notmatch 'b') { $a; break} }
```

Note how `'echo a; echo b >&2; echo c' 2>&1` from the original example was replaced with `'{ echo a; echo b >&2; echo c; } 2>&1'`; i.e., _Bash_ does the merging (replacing the `echo` builtin call with external-utility call `/bin/echo` doesn't change the behavior).

If you want a more striking example, consider this behavior of the `$(....)` operator:

```powershell
> $(/bin/echo "1st stdout line"; /bin/echo "files in /nosuch"; ls /nosuch)
ls: /nosuch: No such file or directory
1st stdout line
files in /nosuch
```

Note how the stderr line comes _first_, despite being output _last_ - even without stream redirections.
Needless to say, such output is unexpected and confusing, making it hard to understand at what point errors occurred.

(By contrast, using `& { ... } ` in lieu of `$(...)` works as expected.)

@SteveL-MSFT: There may be a need to split this into multiple issues, but please don't consider this matter closed.

**Comment by mklement0** [comment]
@PetSerAl:

> Either you join stdout and stderr in one destination, that guaranty that you see data in the same order, but you will not be able to distinguish them.

Seeing the data in the same order is precisely the part that is _not_ working.

While with `2>&1` in a POSIX-like shell you would indeed lose the ability to determine which output line came from what stream, PowerShell actually still allows you to make that distinction:

```powershell
> bash -c 'echo stdout; echo stderr >&2' 2>&1 | % { $_.GetType().Name } 
String
ErrorRecord
```

**Comment by PetSerAl** [comment]
> While with 2>&1 in a POSIX-like shell you would indeed lose the ability to determine which output line came from what stream, PowerShell actually still allows you to make that distinction:

That is because PowerShell do not actually join sdtout and stderr of called application. It still use two separate anonymous pipe streams for redirection. You should give ability to distinct output up, if you want order. You can not have both.

> If you want a more striking example, consider this behavior of the `$(...)` operator:

That is expected (for me) behavior of `$(...)` or plain `(...)`:
```powershell
$(1; Write-Error 2; 3)
(&{1; Write-Error 2; 3})
```

**Comment by mklement0** [comment]
> It still use two separate anonymous pipe streams for redirection. 

Thanks for explaining that. It sounds like that's the technical crux of the problem.

> You should give ability to distinct output up, if you want order. You can not have both.

Giving up distinct output is perfectly fine and - in line with traditional shells - what one should be accepting as a side effect of merging the two streams in order to gain predictable ordering.

(I didn't realize that ordering is mutually exclusive with distinguishability. This issue is definitely about ordering.)

> That is expected (for me) behavior of $(...) or plain (...):

Please explain why you expect this behavior, _without relying on knowledge of PowerShell internals_ - just tell us why you think this behavior _makes sense_.

**Comment by PetSerAl** [comment]
> Please explain why you expect this behavior, *without relying on knowledge of PowerShell internals* - just tell us why you think this behavior *makes sense*.

`$(...)` and `(...)` first collect all the output, and only then write its own result. So you can split it in two:
```powershell
$Result = $(1; Write-Error 2; 3) # collect output
$Result                          # writing own result
```
On the first step all non stdout output will escape collecting and will be printed. And only on second step collected stdout output will be printed. It is working same way in the Bash, by the way:
```bash
echo $(echo 1; echo 2 >&2; echo 3)
```

**Comment by mklement0** [comment]
That indeed makes perfect sense, and excellent point about `$(...)` in Bash (though not `(...)`).

So, with that cleared up, the original issue remains:

With _native utilities_, PowerShell doesn't truly _merge_ the error stream into the success stream with `2>&1` and therefore _doesn't provide predictably ordered output_.

Even though [`about_redirection`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_redirection) makes no mention of ordering, this behavior is an unexpected departure from long-standing `>&` semantics in traditional shells, both on Windows and on Unix.  
_In these shells, only ordered output is expected, not the ability to distinguish which lines came from what stream of origin._

By contrast, with _PowerShell_-native commands, output ordering _is_ preserved (while _also_ preserving the ability to detect error-stream-originated output by testing for `-is [System.Management.Automation.ErrorRecord]` - though that's not entirely foolproof, given that someone could send such instances directly to the success stream).

Do you think this is a fair summary?

Given that with native utilities PowerShell has to choose between providing either ordering or distinguishability, to me the choice is clear: ordering.

**Comment by iSazonov** [comment]
I have to remind #2450

**Comment by redvers** [comment]
> Even though about_redirection makes no mention of ordering, this behavior is an unexpected departure from long-standing >& semantics in traditional shells, both on Windows and on Unix.
> In these shells, only ordered output is expected, not the ability to distinguish which lines came from what stream of origin.

Umm, please cite a source for that, specifically the UNIX side which says "In these shells, only ordered output is expected".  POSIX directly contradicts that.

When you use 2>&1, you are literally saying "read from stderr and output it directly, unbuffered into stdout".  You're not going to be able to identify the source because you explicitly chose to throw the information away.

Taking a step back, if ordering or knowing what data came from where is a requirement of yours then why don't you fork the child from your program and then read the child's stdout and stderr separately?

Then you'll not only know WHERE the data comes from, but you'll also have full control as to how you want it re-assembled.

> So I think the buildup in the pipe is not very good

That "buildup in the pipe" is what gives you your performance.  Default UNIX semantics are that stdout is either block or line buffered, stderr is unbuffered.  stdout is only line-buffered if you're outputting directly to the screen.

As an example - try piping a long-running, high text output commmand into tee.  You'll notice that tee will pause and not display anything until the buffers of the feeding program are full.  That is because tee isn't interactive, so it's block buffered.

If you want, you can flush stdout after every line you print but calling the flush command.

Another option you could have is to see if there is a way to get Powershell to Autoflush stdout at runtime.  In some languages there is a setting to affect a program globally, for example - in Perl, it's the rather intuative command:

`$|++;`

Enabling autoflushing by default in the language would be a mistake.  I mean, you can if you want but the performance penalty would be insane.

**Comment by mklement0** [comment]
@redvers:

It took us a while to narrow this issue down, and I contributed to the confusion with my incorrect `$(...)` example; let me clarify:

### What this issue is NOT about:

* This issue has nothing to do with _buffering_. The premise of this issue - `bash -c 'echo a; echo b >&2; echo c'` - is a series of predictably sequenced outputs, as you've explained yourself.

* This issue is _not_ about the ability to identify which pieces of data came from what stream of 
origin when merging streams.

   * If you opt into _merging_ streams with `2>&1`, you opt out of that ability - and that is expected and perfectly fine.

  * Note that PowerShell doesn't actually allow you to make that distinction either; it's just that you can _make a reasonable guess_ based on the _type_ of an object in the merged stream that it came from the error stream. (It's only a guess, because it is possible to send error objects directly to the success output stream.)

### What this issue IS about:



* `cmd.exe` and POSIX-like shells merge the streams _in output sequence_ when you use `2>&1`.

* PowerShell does so with _PowerShell-native_ commands (good!), but _NOT with [system-]native commands (external utilities)_ (woe is us!), for the reason @PetSerAl has explained ("still use[s] two separate anonymous pipe streams for redirection").
   * The unpredictable output sequence with streams merged from an external-utility call is demonstrated in the initial post; here is a command that demonstrates that it works fine with PowerShell commands: the following loop never exits, because the output order remains stable:  
`while ($true) { if (($a = & { 'a'; write-error 'b'; 'c' } 2>&1)[1] -notmatch 'b') { $a; break} }`

A common use case for `2>&1` with external utility is to get a transcript of sorts from running a _script_: you want to capture that script's output in a single stream, as it would have printed to the console.

PowerShell's current behavior gets in the way of that, by unpredictably capturing the output out of sequence.

**Comment by redvers** [comment]
Thanks for the clarification @mklement0, now I better understand what you were getting at I've written what I believe to be the simplest use-case / illustration to show the bug.  Please forgive the post length:

```
#include <stdio.h>
#include <unistd.h>

int main() {
  const void *s   = "OOOOOO";
  const void *scr = "OOOOOO\n";
  const void *e   = "EEEEEE";
  const void *ecr = "EEEEEE\n";

  write(1, s, 6);
  write(2, ecr, 7);
  write(1, s, 6);
  write(2, e, 6);
  write(1, scr, 7);
  write(2, e, 6);
  write(1, s, 6);
  write(2, e, 6);
  write(1, s, 6);
  write(2, e, 6);
  0;
}
```

It doesn't get simpler than that (note, we have to use write instead of fprintf to ensure that libc doesn't do buffering for us).

Compiling with gcc and examining the ASM shows that the ASM is sending the data in the correct order:

```
p2 powershell-src # gcc -S -O0 -o tt.S tt.c
p2 powershell-src # grep edi tt.S
        movl    $1, %edi
        movl    $2, %edi
        movl    $1, %edi
        movl    $2, %edi
        movl    $1, %edi
        movl    $2, %edi
        movl    $1, %edi
        movl    $2, %edi
        movl    $1, %edi
        movl    $2, %edi
p2 powershell-src #
```

So, how does our executable behave?

Shell:
```
p2 powershell-src # ./tt 2>&1
OOOOOOEEEEEE
OOOOOOEEEEEEOOOOOO
EEEEEEOOOOOOEEEEEEOOOOOOEEEEEEp2 powershell-src #
```

You can see the output is interlaced exactly as the code says it should be.

From Powershell:
```
PS /home/red/projects/powershell-src> ./tt 2>&1
OOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEE
```

Interesting huh?  Seems that STDOUT takes priority over STDERR.

Hope that helps,


Red

**Comment by SteveL-MSFT** [comment]
Parking this in 6.2.0 for now, not sure if we'll get around to it for 6.1.0 unless someone from the community takes this one.

**Comment by npodbielski** [comment]
I run on similar problem here. https://github.com/PowerShell/PowerShell/issues/10539
I think that most problematic in this is that how unpredictable it is. I would not matter really even if similar command output would be different in bash then in PS but at leas it should be **deterministic**

**Comment by iSazonov** [comment]
If we run
```powershell
bash -c 'echo a; echo b >&2; echo c'
```
do we get desired result?

In the case PowerShell does automatic merging standard output and error streams to Out-Default.
In a case with explicit redirection:
```powershell
bash -c 'echo a; echo b >&2; echo c' 2>&1
```
PowerShell add an data event handler for error stream and implicit stream merging command at end of the pipeline. As result error data events is collected in separate pipe buffer and wrote to output after native command exit.
Look useful comments in 
https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/NativeCommandProcessor.cs#L1182

**Comment by iSazonov** [comment]
Perhaps @PaulHigin could be add more info and code references how redirection works by default and with explicit redirection commands.

**Comment by beatcracker** [comment]
Another user story: I can't reliably output Docker container logs from PowerShell. Something like this results in log messages out of order if app(s) inside container use `stderr`:
```pwsh
docker logs some-container | Write-Host
```
This is extremely annoying since then commands like this need to be shelled out and it's PITA to support on multiple platforms (cmd/bash/etc).

**Comment by vexx32** [comment]
That particular use case is going to run into issues in any case; PowerShell doesn't pass error data over pipelines / to commands, only output / stdout (generally). If an application is writing to stderr, Write-Host will never see it. You can try merging the streams as many examples here have done.

Not sure if there's a better way to approach that particular use case at the moment, though 🤔

**Comment by beatcracker** [comment]
> @vexx32 
> If an application is writing to stderr, Write-Host will never see it.

I have to disagree :). This works, but the ordering is messed up:

```
docker logs kafka | ? { $_ -is [System.Management.Automation.ErrorRecord] } | Write-Host
  16:29:51.63
  16:29:51.63 Welcome to the Bitnami kafka container
 ...
```

I've settled for now on just dropping `Write-Host` and polluting pipeline which I don't like but it's acceptable in my case. No ordering issues that way.

**Comment by mklement0** [comment]
@beatcracker, `Write-Host` indeed doesn't receive stderr input; the latter prints straight to the host, which is why it may _appear_ that it is being relayed by `Write-Host`; the following command demonstrates that that is not the case: despite applying the suppress-all output redirection (`*>$null`) to `Write-Host`, the stderr output still prints to the display:

```powershell
# Still prints 'stderr' to the display
& ('/bin/sh', 'cmd')[$env:OS -eq 'Windows_NT'] ('-c', '/c')[$env:OS -eq 'Windows_NT'] 'echo stderr >&2' | 
  Write-Host *>$null
```
