### ISSUE TITLE
Receive-Job should have a -Timeout parameter to complement -Wait

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#5433]
`Receive-Job -Wait` is a convenient way of receiving job output (almost) as it is being produced, but it waits indefinitely for the job to complete.

Having `Receive-Job -Wait -Timeout <secs>` would be handy to enforce a timeout.

(`Wait-Job` already has a `-Timeout` parameter, but it doesn't support receiving job output)

Environment data
----------------

Written as of beta.9

**Comment by davidBar-On** [comment]
Is this issue still relevant or a workaround such as `$j="job7"; Wait-Job $j -Timeout 5 >$null; Receive-Job $j` is considered good enough?

I am asking partly because PR #5471 that resolves a related issue was submitted some years ago but was never merged. Therefore it seems that the [suggested workaround](https://github.com/PowerShell/PowerShell/pull/5471#pullrequestreview-77138717) in this PR is practically considered good enough.

**Comment by doctordns** [comment]
The PowerShell Cmdlet Working Group has reviewed this issue and has decided to close it as:  Won't Fix. We have seen very little community input that this is a needed feature. And as pointed out in the issue thread, there is a good workaround should the need arise.

**Comment by mklement0** [comment]
The alleged workaround isn't one (it relates to a different cmdlet, `Start-Process`).

Dismissing suggestions solely based on how much community input has been received rather than on their merits is unfortunate in general.

Specifically, by the standards of this repo, I don't think that an issue having garnered 4 up-votes (though I'm unsure of the timing) qualifies as "very little community input".

**Comment by aarismendi** [comment]
I would like to have this as well. Would like to receive background job output in real time with an optional timeout.

**Comment by somescout** [comment]
I agree, I just faced a situation when one of 400 jobs froze, I had to interrupt the script, and the result of all other jobs disappeared. Workarounds can be used of course, but there are already too many of them - I would like to just write working code.

**Comment by Makumasa** [comment]
Everyone keeps talking about a workaround, but could someone enlighten me as to what the workaround actually is? As mentioned by mklement0, the workaround linked in an earlier comment doesn't apply here and something like `$j="job7"; Wait-Job $j -Timeout 5 >$null; Receive-Job $j` doesn't actually address the original issue since output isn't returned until after the job completes (or the timeout expires). As far as I can tell, we can either wait for a job with a timeout or wait for a job and poll it for output, but not both.

I feel like most users will simply resort to crude solutions like busy wait loops that repeatedly call Receive-Job and manually track runtime for each job, which is frustrating since PowerShell already implements much better solutions to these problems under the hood, they just aren't exposed to the user in a way that addresses this fairly common use case.
