### ISSUE TITLE
'ToString' method is case sensitive when getting default rendering of a type

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#5599]
When the definition of `ToString` is spelled `toString`, we get the type name instead of the result of `ToString`. It works when spelled `ToString`.

Steps to reproduce
------------------

```powershell
class X{
    [string] $A
    [string] toString() {return $this.A}
}


gci | foreach {[X] @{A = $_.Name}} | group A

```

Expected behavior
-----------------

```none
Count Name                      Group                                                                                                    
----- ----                      -----                                                                                                    
    1 file1                     {file1}                                                 
    1 file2                     {file2}  
```

Actual behavior
---------------

```none
Count Name                      Group                                                                                                    
----- ----                      -----                                                                                                    
    1 file1                     {X}                                                 
    1 file2                     {X}  
```

Environment data
----------------

```powershell
All versions

```

**Comment by daxian-dbw** [comment]
I think this is by design. `toString()` in the repro is a different method from `ToString()`. The formatting code calls `ToString()`, and thus `toString()` won't be used for sure.

It's the same in C# code:
```CSharp
    public class Test
    {
        public string Name;
        public string toString()
        {
            return Name;
        }
    }

    public static void Main(string[] args)
    {
        Test test = new Test() { Name = "YAY" };
        Console.WriteLine(test.toString());
        Console.WriteLine(test);
    }

> YAY
> ConsoleApp.Test
```

PowerShell populates method tables ignoring the cases of method names. So in case you have `toString()` and `ToString()`, only one of them will show up in the method table, which will be the first one returned by reflection.

**Comment by markekraus** [comment]
may be by design, but there is a fault with that. this is invalid:

```powershell
Class Test {
    Test () {}
    [string] toString() {
        return 'lower case "t"'
    }

    [string] ToString() {
        return 'lower case "t"'
    }
}
```

It produces 

```none
The member 'ToString' is already defined.
```

but of you use just `toString()` you get that there is no way in PowerShell to call the `ToString()` without reflection which makes it appear as though it is the only "tostring" available, until you get the unexpected results of the underlying .NET calling `ToString()`:

```powershell
Class Test {
    Test () {}
    [string] toString() {
        return 'lower case "t"'
    }
}

$Test = [Test]::new()
$Test.toString()
$Test.ToString()
'{0}' -f $Test
```

Result:

```none
lower case "t"
lower case "t"
Test
```

Since case sensitivity is not a thing of concern in PowerShell, perhaps overriding an existing method with matching case would make sense... but then if the class has multiple methods with mixed casing, it would be ambiguous. :(

I guess overriding methods is just an instance where case sensitivity has to matter....

**Comment by iSazonov** [comment]
I wonder - do we know any public popular APIs with methods in different cases? 
I believe .Net haven't such methods.

**Comment by markekraus** [comment]
@iSazonov Probably not. Arguably, anyone who made mixed cased method is "doing it wrong". In the rare instance that they do have mixed case, the class can be inherited by a PowerShell class, and the method can be overridden, then it would be ambiguous as to which methods PowerShell was overriding. While in PowerShell, it would only override the method is available in PowerShell, if that object gets passed to .NET it would not override all cased versions of the method.

Maybe a PowerShell Method should override all cased versions of an existing method as well as add a new case if it doesn't exist? For example, `toString()` in PowerShell would override `ToString()` as well as create a `toString()` in .NET. 

If a .NET class had `badMethod()` and `BadMethod()` and the PowerShell class had `badmethod()`, the PowerShell class would override `badMethod()` and `BadMethod()` and add a `badmethod()`.

**Comment by iSazonov** [comment]
I think we shouldn't override all cased versions - really it is different methods. We shouldn't fix alien "doing it wrong". If anybody catch such bad API he can use reflection for workaround.

**Comment by markekraus** [comment]
@iSazonov it makes sense in PowerShell to do so, though. since there is only 1 method available in PowerShell if the user overrides a all of the cased methods, then it produces expected results form a PowerShell perspective. 

The example in this issue of `toString()` is not the first I have seen this exact one come up. PowerShell's case insensitivity is great except in this area. To a PowerShell user it makes no sense. they access `$object.tostring()`,  `$object.toString()`, `$object.ToString()`, `$object.TOSTRING()`, and they get the same result. but they do 

```powershell
class X{
    [string] $A
    [string] toString() {return $this.A}
}
```

and suddenly it doesn't play nice at all. PowerShell shows one thing and .NET another. 

Since mixed cased methods are probably and edge-case, it probably makes sense for PowerShell to override all of the methods as well as add one with the ps defined casing. in the rare case that someone has a ,NET class like this:

```csharp
using System;

namespace Test
{
    public class Test
    {
        private bool init;

        public Testy () { init = true; }
        
        public string test()
        {
            return "test";
        }
        
        public string Test()
        {
            return "Test";
        }
    }
}
```

Overriding `Test()` and `test()` when inheriting would make the class behave the same in .NET and in PowerShell.

**Comment by iSazonov** [comment]
I see:
```powershell
PS> [bigint]::Pow

OverloadDefinitions
-------------------
static bigint Pow(bigint value, int exponent)


PS> [bigint]::pow

OverloadDefinitions
-------------------
static bigint Pow(bigint value, int exponent)

**Comment by markekraus** [comment]
```powershell
$code = @'
using System;

namespace Test
{
    public class Test
    {
        private bool init;

        public Test () { init = true; }
        
        public string testString()
        {
            return "test";
        }
        
        public string TestString()
        {
            return "Test";
        }
    }
}
'@
Add-Type -Language CSharp -TypeDefinition $code -IgnoreWarnings
Class MyTest : Test.Test {
    MyTest () {}

    [String] TESTString() {
        return 'TEST'
    }
}
$MyTest = [MyTest]::New()
$code2 = @'
using System;

namespace Test
{
    static public class Test2
    {
        public static string GetString(object input)
        {
            dynamic test = input;
            return String.Format("testString: {0}; TestString {1}; TESTString {2}", test.testString(), test.TestString(), test.TESTString());
        }
    }
}
'@
Add-Type -Language CSharp -TypeDefinition $code2 -IgnoreWarnings -ReferencedAssemblies "Microsoft.CSharp"
[Test.Test2]::GetString($MyTest)
```

result:

```none
testString: test; TestString Test; TESTString TEST
```

if what I'm proposing ere put in place:

```none
testString: TEST; TestString TEST; TESTString TEST
```

**Comment by pemo11** [comment]
I would suggest that Add-Type should issue a warning when a class contains methods with the same name but different cases.

Here is another example based on RC1 that shows that even both version of getInfo are listed as members only the first one can be called.

```
$Code = @"
    public class CSTest
    {
        // This one will be called by PowerShell
        public string GetInfo() 
        {
            return "this is GetInfo()";
        }
        public string getInfo()
        {
            return "this is getInfo()";
        }
    }
"@

Add-Type -TypeDefinition $Code  -PassThru

# both getInfo and GetInfo get listed
[CSTest].GetMethods().Name

$ct = [CSTest]::new()
# calls the first method in the class definition
$ct.getInfo()
$ct.GetInfo()
```

**Comment by markekraus** [comment]
@pemo11 as that is separate from this issue, please open a new issue. I'd love to discuss this, but do not want to veer off topic with the issue addressed here.
