### ISSUE TITLE
Set-Location preserves case instead of matching filesystem on case-insensitive/preserving system

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PowerShell#5678]
Steps to reproduce
------------------

```powershell
mkdir Foo
cd foo
```

Expected behavior
-----------------

```none
    Working directory ends in `\Foo`.
```

Actual behavior
---------------

```none
    Working directory ends in `\foo`. (note the difference in case)
```

Remarks
---------------
I originally thought this issue belonged with #1273, but that is about tab completion and globbing on non-Windows platforms, whereas this does not involve tabbing or globbing, and is on Windows.

This problem can cause problems with git and [other things](https://github.com/vuejs/vue-cli/issues/648#issuecomment-350622047).

If I use cmd.exe instead, it gives the expected/desired results.

On case-**sensitive** systems, I don't know what the correct behavior should be (reject it if the path doesn't exist, or automagically switch to the fs-matching case)... perhaps it should be controlled by the same settings as in #1273.

Environment data
----------------

```powershell
PS C:\Users\danthom> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17047.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17047.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by SteveL-MSFT** [comment]
Unfortunately, this has turned out to be much more complicated than I anticipated.  [DirectoryInfo]::GetFiles() and GetDirectories() aren't working correctly on macOS.  I'll need to open a issue for corefx.

**Comment by iSazonov** [comment]
DotNet Issue was closed without resolution. :confused:

**Comment by iSazonov** [comment]
Maybe we need to follow C# as discussed in #6833 and develop language means for creating portable scripts.

**Comment by mklement0** [comment]
@jazzdelightsme:

> On case-**sensitive** systems, I don't know what the correct behavior should be (reject it if the path doesn't exist, or automagically switch to the fs-matching case)...

There's at least one case in which the path should be _rejected_:
If there's ambiguity due to the presence of more than 1 case-variant folder: e.g, if you specify `test` and both `TEST` and `Test` exist.

If there is no ambiguity - just 1 case-variant match - I suppose targeting that automatically is an option, but note that for consistency we'd then have to implement the same logic wherever file/directory paths are accepted, such as `Get-Content`.

I suspect that that behavior would ultimately be too obscure and I suggest we keep a clean separation between:

* _literal_ names that _must_ be case-exact on case-sensitive filesystems.

* (possibly opt-in) case-_insensitive_ tab-completion and wildcard matching, where ambiguity can be resolved by cycling through / returning multiple matches.

**Comment by mklement0** [comment]
As for the issue at hand:

**macOS**:

https://github.com/dotnet/corefx/issues/26797 is indeed resolved, but the issue at hand persists, and it is _PowerShell_ that is the culprit (in the following examples, a `Test` directory is created, and it is accessed via its all-lowercase variant, `test`):

```powershell
PS> mkdir -p /tmp/Test; Set-Location /tmp/test; $PWD.Path
/tmp/test # !! *input* case was preserved, even though the actual name is a case variant
```

Using .NET Core does NOT exhibit this behavior:

```powershell
PS> mkdir -p /tmp/Test; [Environment]::CurrentDirectory = '/tmp/test'; [Environment]::CurrentDirectory
/private/tmp/Test  # OK: actual dir. name is reflected in the last path component
```

(Note that `/tmp` is a symlink to `/private/tmp` on macOS.)

**Windows**:

Unlike on macOS, it is _.NET itself_ and, I suspect, ultimately the Windows API that behaves this way, so if we want to fix this behavior, we'll have to do it in PowerShell (as `cmd.exe` apparently does):

```powershell
PS> $null = mkdir -Force $env:TEMP\Test; [Environment]::CurrentDirectory = "$env:TEMP\test"; [Environment]::CurrentDirectory
C:\Users\jdoe\AppData\Local\Temp\test  # !! *input* case was preserved.
```

---

Note that the behavior doesn't just affect `Set-Location` (`cd`), but also other cmdlets such as `Get-Item`.

**Comment by iSazonov** [comment]
@mklement0 Thanks! I agree that it is PowerShell issue.
Perhaps we should ask a more general question -see #1273 and #7221 last comment) - how much should we be case-sensitive/-insensitive on every platform?

- on Windows, API preserves case but all comparisions is case-insensitive. PowerShell follow this.
- on MacOs, API preserves case but all comparisions is case-insensitive. Currently PowerShell doesn't follow this. Bug? Should? I think yes.
- on Linux, API preserves case and all comparisions is case-sensitive. PowerShell follow this. Here is the quesion - how much should we be case-sensitive on Linux taking #1273 into consideration? Perhaps we could be case-insensitive on Linux in other scenarios too. 
For example, if a user accidentally types `dir /Etc` we could test that `/Etc` doesn't exists and then try `/etc` - is the behavior acceptable for Linux users? If yes, we could easily resolve the Issue and  #1273 in that way I suggested in  #7221.

**Comment by mklement0** [comment]
@iSazonov: Please see https://github.com/PowerShell/PowerShell/issues/5678#issuecomment-418155458 above.

In short: 

* I think _literal_ names should never be automatically case-corrected on case-sensitive filesystems, to avoid ambiguity.

* It makes sense to offer case-_insensitivity_ for (a) tab-completion and (b) filename globbing, but it I wonder if it should require an _explicit opt-in_ (perhaps via preference variables), at least for _globbing_.

   * Otherwise, users may be surprised if `Get-Item test` doesn't find `.\Test`, but `Get-Item test*` does, for instance.

  * For ad-hoc use (as well as for [internal use in generating completions](https://github.com/PowerShell/PowerShell/issues/1273#issuecomment-320696245)), adding a `-CaseInsensitive` switch to `Resolve-Path` does make sense.

That said, as stated in https://github.com/PowerShell/PowerShell/issues/1273#issuecomment-324398879, the tricky thing is that a preference variable that controls globbing case-sensitivity, if set in the global scope, would potentially change the behavior of all _scripts_ run in-process, unless they explicit set the preference variable to the default in their scope.

Given that, perhaps the answer is to:

* categorically use case-_insensitive_ globbing (and tab-completion) on all platforms, even on Linux.

* offer case-_sensitive_ globbing, if desired, _only_:
  * via the filesystem provider's `-Filter` parameter (though that could be confusing) 
  * via a `-CaseSensitive` (sic) switch added to `Resolve-Path` - for consistency, that switch would then have to be honored on Windows and macOS too, however (just documenting it as being ignored on these platform may not be enough to avoid confusion).

**Comment by iSazonov** [comment]
> categorically use case-insensitive globbing (and tab-completion)

I agree with tab-completion but globbing - I think users will be surprised that `Copy-Item -Path $env:TEMP\T*` will copy `$env:TEMP\test` on Linux.

**Comment by mklement0** [comment]
There ultimately is no _good_ solution here, but what appeals to me about the latter solution is its simplicity:

* As a user, all you need to remember is that PowerShell wildcards are case-_insensitive_ _everywhere_ by default.

  * Getting case-_sensitive_ filename globbing, if needed (probably rarely), must be requested explicitly with `-Resolve-Path -CaseSensitive` and _perhaps_ also the filesystem provider's `-Filter` parameter.
    * I'm starting to think that the latter is not a good idea, though: on the one hand, there already are differences between `-Filter` and PS wildcards on Windows, but they are subtle and don't affect the majority use cases; on the other hand, `-Filter` is often used for _performance_ reasons alone, and having it be case-sensitive is then an inconvenience at best, and a subtle source of bugs at worst.

* No new preference variables and therefore no associated issues with global state ("convention over configuration").

Obviously, the behavior would need documenting in [about_wildcards](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_wildcards).
