### ISSUE TITLE
Get-ChildItem -Recurse treats literals passed to -Path like wildcard expressions

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#5699]
The 1st positional argument passed to `Get-ChildItem` binds to `-Path`, meaning that wildcard expressions _are_ supported.

However, values that are _literal_ paths - values that do not contain wildcard metacharacters such as `*` - should be treated as such.

* _Without_ `-Recurse`, that is already the case: A nonexistent literal path triggers an error.

* _With_ `-Recurse`:

   * The nonexistent path (assuming that it is a mere filename or its parent path exists) is treated like a wildcard expression that happens to match nothing.
   * Additionally, this matching is apparently performed in _all_ the directories in the subtree.

Workaround (and generally the better choice if you know a path to be a literal one):  
`Get-ChildItem -Recurse -LiteralPath <path>`

_Update_: `Get-ChildItem -Recurse <name>` may also yield _false positives_, by matching `<name>` _anywhere in the subtree_ rather than just in the current location - see below.

Steps to reproduce
------------------

```powershell
Get-ChildItem NoSuch
Get-ChildItem NoSuch -Recurse
```

Expected behavior
-----------------

Both commands should report an error re nonexistent item `NoSuch`.

Actual behavior
---------------

`Get-ChildItem NoSuch -Recurse` produces no output at all (neither success nor error), and `$?` is set to `$True`.

Environment data
----------------

```powershell
﻿PowerShell Core v6.0.0-rc.2 (v6.0.0-rc.2) on Microsoft Windows 7 Enterprise  (64-bit; v6.1.7601)
Windows PowerShell v5.1.14409.1012 on Microsoft Windows 7 Enterprise  (64-bit; v6.1.7601)
```

**Comment by SteveL-MSFT** [comment]
The inconsistent behavior is wrong, but with the `-literalpath` workaround and checking the returned count, I'm not sure if we would change this.  It seems to me that if this was v1, I would have `-Path` and `-LiteralPath` be the root of the search and require `-Filter` for filtering rather than mixing it with the path.

**Comment by mklement0** [comment]
I understand that the behavior is useful if the only / last path component is an actual wildcard pattern (e.g., `Get-ChildItem *.txt -Recurse` - though it gets confusing with `Get-ChildItem /tmp/*.txt -Recurse`), but with literal components you not only may get quiet no-ops when there should be an error, **you may also get _false positives_, which is more problematic:**

```powershell
> mkdir -p /tmp/sub/tmp2; sl /tmp; Get-ChildItem -Recurse tmp2  | % fullname
/tmp/sub/tmp2
```

Note how `tmp2` is unexpectedly matched  _anywhere in the subtree_ of `/tmp` instead of complaining that `/tmp` has no child item named `tmp2`.

Needless to say, this can have grave consequences.

It's fine to keep the existing behavior with actual wildcard expressions in the last path component, but my vote is to fix the behavior with literals.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee discussed this and is concerned about the compatibility risk with existing scripts.  We acknowledge that the behavior is surprising and would defer to potentially writing a new FileSystemProvider in the future to resolve these types of issues.  Feel free to mention me on other ones that should be addressed in FileSystemProvider v2.

**Comment by marckassay** [comment]
#5896

**Comment by powercode** [comment]
Work on a new FileSystemProvider should probably wait until all the changes to System.IO in .NET core is shipped. They are doing lots on high perf/low allocation wrt file system. Can barely wait! :)

**Comment by nightroman** [comment]
It works as expected in v2. As far as I remember, per the PowerShell Team explanation, this was a design decision in order to match CMD `dir` behaviour and improve the user experience. There was an issue Microsoft Connect [766100](https://connect.microsoft.com/PowerShell/feedback/details/766100) but half of Connect issues were removed, including this one.

**Comment by BrucePay** [comment]
@PowerShell/powershell-committee  -  @nightroman 100% is correct.  _**This is a deliberate feature**_ implemented to make it easier (and more friendly to cmd users) to recursively search for a file name. It is extremely useful, likely broadly used and consequently extremely likely to break both scripts and the user experience if it is changed.

**Comment by mklement0** [comment]
If the consensus is that the risk of breaking existing scripts is too high, the best we can do is to _document_ the pitfalls - and the pit can be deep, as my example with the false positives shows.

But let's be clear that while the ability to match on all levels of the subtree is indeed very useful, it is regrettable that such a treacherous implementation was chosen (even if as a nod to `cmd` users) - all the more so, given that the correct implementation of the feature is _also_ available (`-Filter`, `-Include`).

**Comment by SteveL-MSFT** [comment]
It seems that if we know the path is literal (`c:\foo` or even `.\foo`) we shouldn't treat that as a search and that might be acceptable from a compatibility point of view

**Comment by mklement0** [comment]
@SteveL-MSFT: I agree, and note that that is the very thing my original post asked for:

>  values that are _literal_ paths - values that do not contain wildcard metacharacters such as `*` - should be treated as such.

**Comment by mi-hol** [comment]
A really dangerous bug open for an eternity :(
Is it so hard to fix?
Would a headline like 'PowerShell killed all my data' be good marketing?

**Comment by nightroman** [comment]
@SteveL-MSFT This new feature in v3 was breaking for v2 scripts, too. And lots of people were surprised right from the beginning. Unfortunately the history on Connect (mentioned above issue) was erased.

**Comment by powercode** [comment]
Is there some way to have new behavior behind a flag/version? So we somehow could opt in to fixed, otherwise breaking changes?

A bit like what @daxian-dbw did with experimental feature, but for production? Or does it become a maintenance hell?

**Comment by SteveL-MSFT** [comment]
@powercode We could certainly put this behind an experimental feature flag (which is opt-in by definition and thus less people will use it).  We currently don't have a good solution as to when something goes from experimental to stable in the case where it's a breaking change.  I'm concerned that having something that is breaking that is opt-in will fragment the community.

For the argument that v3 broke v2, I don't think we can use that as justification to break v3, v4, v5 by itself.

**Comment by nightroman** [comment]
> For the argument that v3 broke v2, I don't think we can use that as justification to break v3, v4, v5 by itself.

Not at all, of course. I mentioned the history just as the precedent of making breaking changes for the greater good. Justifications should be different, something like "potentially dangerous feature", "violation of the least surprise principle", etc.

**Comment by SteveL-MSFT** [comment]
@nightroman Agree 100%.  v3 was before my time on this team, so I don't know the history of it whether the break was intentional or a mistake (feels like the latter).

**Comment by EklipZgit** [comment]
Agreeing with @Atheuz here, we just encountered this for the second time in 6 months. 

It is insane that 
`$Output = '\\s-buildserv\C$\Agents\Agent2\_work\1228\s\Output'`
`Get-ChildItem -Path $Output -Directory -Recurse |`
`    Remove-Item -Recurse -Force -ErrorAction 'Ignore'`
deletes 
\\s-buildserv\C$\Agents\Agent2\_work\1228\s\Tests\Data\output
\\s-buildserv\C$\Agents\Agent2\_work\1228\s\Tests\DataDNSExtract\output
\\s-buildserv\C$\Agents\Agent2\_work\1228\s\Tests\DataTemplateDedupe\output

I see this as an exceptionally dangerous bug that at the very least should have a stopgap fix to recognize non-wildcard paths and refuse to recurse from one level up.

**Comment by KevinMarquette** [comment]
This is dangerous and very hard to track down. The only reason that we found it this time is because we have ran into this several times before.

If someone runs gives a path to  `.\source\Output`, why should it ever consider looking in `.\source\Tests` and every other folder in `.\source`.

The other scenario that we run into this as an issue is when that parent folder is very large. Like when it sits in `C:\Windows`. Not only does it take forever, you also often get access denied error for completely unrelated paths. If it is in the root of a company share with millions of files, this command will appear to never return. Both scenarios are very hard for the inexperienced to troubleshoot.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee due to the breaking change nature of this request, we would recommend making the behavior change in a FileSystemProvider v2 implementation

**Comment by iSazonov** [comment]
The code which implement the behavior is [here](https://github.com/PowerShell/PowerShell/blob/4d702e010d656681e42164ad02344883836668c9/src/System.Management.Automation/engine/SessionStateContainer.cs#L1320-L1371)

Comments in the code says the current behavior is **explicit design**:
"If we're recursing, do some path fixups to match user _expectations_:"

There are two base scenario:
1. Get-ChildItem -Recurse searchname  (searchname is not an absolute or relative path)
2. Get-ChildItem -Recurse searchpath    (searchpath is <path>\searchname)

Let's see what is **real** user expectations for these scenarios.
1. Using simple search name with Recurse parameter says that we want to find the name in all directory tree. The expectation looks very native.
2. If I use a path I expect it works as path
Before the issue I didn't even know `dir -Recurse c:\name` is transforming into `dir -Recurse c:\ -Include "name"`. The behavior is unexpected for me. If I came across this, I would consider it a bug and use a final slash to fix the situation `dir -Recurse c:\name\`.

It is clear why this design arose - this is a generalization of the first scenario - if an user is on C:\ and want to search on D:\ the user uses `dir -Recurse c:\name` instead of `dir -Recurse name`.
_The key here is that the user must explicitly know how it works._ I could speculate that no one knows about this since it is not documented and you can only find out about it from the comments in the code. This is an incredible situation.

Also as said above https://github.com/PowerShell/PowerShell/issues/5699#issuecomment-380827924 the design (for second scenario) has a dangerous side effect because the behavior differ if <searchpath> is existence container or no. Thus, if an user create a script with confidence that the path exists the script works well until somebody removes the directory, after that, the script will unexpectedly enumerate whole directory tree which can lead to disastrous consequences.

That we see for second scenario:
- unexpected
- dangerous
- users don't know the design and therefore cannot rely on it

Thus, we can conclude that:
- this should be fixed
- this is not a breaking change
- if you still believe it is a breaking change it is a breaking change under Bracket 3.

**Comment by mklement0** [comment]
Hear, hear, @iSazonov.

I think that even letting `Get-ChildItem name -recurse` - i.e. searching by _literal_ item _name_ (or _relative_ path) only (bound to `-Path` by default) -  in the entire subtree is ultimately too treacherous, which is why I originally suggested that only _wildcard patterns_  (e.g., `name*.txt`) trigger this at-every-level-of-the-subtree matching.

Ultimately, however, I think that even wildcard patterns shouldn't trigger this behavior, to avoid everlasting confusion and prevent unexpected, potentially destructive results.

Instead, I think the fix should be:

* Only ever treat `-Path` arguments as recursion _starting_ points (the way `-LiteralPath` arguments are already treated).
  * That is, an argument - _if_ it contains wildcards - should be globbed as-is (which in the name-only and relative-path cases means _relative to the current directory only_), and recursion should then only be performed on the _resulting, literal path(s)_.

* For at-every-level-of-the-subtree matching, `-Filter` or `-Include` must be used.
  * Given that `-Filter` is the second positional argument, that is not much of a hardship: `gci . name*.txt -r`

Yes, that is more of a breaking change than the previously proposed fixes, but to me is justified by:

* then having consistent behavior that is easily conceptualized and documented.
* avoiding unexpected, potentially destructive behavior.

---

Also, @SteveL-MSFT, quoting from the committee decision [above](https://github.com/PowerShell/PowerShell/issues/5699#issuecomment-355157333):

> would defer to potentially writing a new FileSystemProvider in the future to resolve these types of issues.

Can you please clarify what that means in practical terms? Different cmdlet names? ...?

**Comment by iSazonov** [comment]
> > would defer to potentially writing a new FileSystemProvider in the future to resolve these types of issues.
> 
> Can you please clarify what that means in practical terms? Different cmdlet names? ...?

In threory, we should convert FileSystemProvider in an loadable PowerShell subsystem. But I think it is impossible since most of issues is not in FileSystem class only but in Globber, cmdlets and other parts - we would have to rewrite whole PowerShell :-)

**Comment by iSazonov** [comment]
> Yes, that is more of a breaking change than the previously proposed fixes, but to me is justified by:

It is clear from the previous discussion that it is unbelievable it will even be approved, not just implemented.

I'd suggest to open new issue for second scenario from my previous post. I suppose the removal of this unpleasant side effect will be approved quickly.

**Comment by mklement0** [comment]
> we would have to rewrite whole PowerShell :-)

Great idea! I have a few issues lined up in #6745 that we could then address too. (Just kidding.)
That is unfortunate. 

Personally, I'm only interested in the [_fundamental_ fix proposed above](https://github.com/PowerShell/PowerShell/issues/5699#issuecomment-824182728).

So I'll leave it to you or someone else to write up a new issue for the _partial_ fix you propose.

**Comment by whitTech** [comment]
If you won't implement a breaking change (just think, if you'd bitten the bullet when this first issue was raised...waiting is only compounding the issue further), please do something to prevent users from accidentally deleting all their data. I nearly just destroyed our entire fleet. This is madness. 

(PS 7.1.3)

**Comment by sdwheeler** [comment]
FWIW, the behavior of using recursion with a literal path (no wildcards) is not without precedent. You get the same behavior in MSDOS or Windows CMD.

Here is the CMD example:
```cmd
D:\temp>tree test /F
Folder PATH listing for volume DATA
Volume serial number is 6466-2168
D:\TEMP\TEST
│   fizzbuzz.txt
│
├───buzz
│       buzz.txt
│       fizzbuzz.txt
│
└───fizz
        buzz.txt

D:\temp>dir /s test\fizzbuzz.txt
 Volume in drive D is DATA
 Volume Serial Number is 6466-2168

 Directory of D:\temp\test

11/15/2023  02:13 PM                10 fizzbuzz.txt
               1 File(s)             10 bytes

 Directory of D:\temp\test\buzz

11/15/2023  02:11 PM                10 fizzbuzz.txt
               1 File(s)             10 bytes

     Total Files Listed:
               2 File(s)             20 bytes
               0 Dir(s)  1,915,708,940,288 bytes free
```

Here is PowerShell (7.4):

```powershell
PS> Get-ChildItem -Path .\test\fizzbuzz.txt -Recurse


    Directory: D:\temp\test\buzz


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        11/15/2023   2:11 PM             10 fizzbuzz.txt


    Directory: D:\temp\test


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        11/15/2023   2:13 PM             10 fizzbuzz.txt
```
