### ISSUE TITLE
Links for code style and review

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#5723]
@daxian-dbw @adityapatwardhan I collected from PR discussions useful links for possible future additions in our guidelines. Feel free to close after read.

- Sorts class elements according to StyleCop guidance https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1201.md
- Sorts within the same elements by access type according to StyleCop guidance https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1202.md
- https://smartbear.com/learn/code-review/best-practices-for-peer-code-review/
- https://www.codefactor.io

**Comment by markekraus** [comment]
If someone could figure out how to get [StyleCop.Analyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) working in our project, that would be great. I gave it a full days worth of effort and came back empty handed. It is supposed to be as simple as adding the package reference, but I ran into weird dependency conflicts. We would need to ignore some of the rules unless we are willing to change some of our guidelines. (for example, separating private fields backing properties from the properties). And maybe it doesn't need to be in every assembly. Or maybe it can be added through some empty project trickery and run ad hoc instead of every build.

**Comment by bergmeister** [comment]
I agree with @markekraus to rather use the stylecop linter because then you get errors in Visual Studio (and you can even do Ctrl+'.' to auto-fix it). I have used that already in a .Net Core solution but remember that there were some gotchas and limitations (e.g. one could only have one global stylecop.json instead). I can take a stab on it if you want to. I don't know if it integrates well with VSCode or if it only works with Visual Studio because of the way it hooks into .Net Core MSBUILD under the hood. Maybe it requires [PR 5209](https://github.com/PowerShell/PowerShell/pull/5209), because at the moment, compilation is disabled for all *.cs files in the csproj files.

**Comment by markekraus** [comment]
@bergmeister Thanks! 

If we can at least get it hooked into the Microsoft.PowerShell.Commands.Utility assembly as a start. That is where the heaviest amount of community contributions seem to go (by my impression only and no solid analytics 😏 ). And I have WIP for refactoring/organizing the web cmdlets (that's where much of this is stemming from). 

For vscode, I believe the only current support is for compile time warnings, which is why I suggested possibly a pseudo-project... or maybe even a build configuration? I dunno.. I'm very new to this so whatever makes it work without impacting normal build processes until we can get the code to a state where we CAN flip it on for builds and serve as a fail detector.

**Comment by iSazonov** [comment]
[StyleCops.Analyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCopTester/StyleCopTester.csproj#L6) depends on Net452 😕

**Comment by markekraus** [comment]
what about this https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/DotNetCli.md is that the same thing?

**Comment by iSazonov** [comment]
ASP.NET Core depends on Net452 too. 😕

**Comment by markekraus** [comment]
@iSazonov I was able to get it to work with this https://carlos.mendible.com/2017/08/24/net-core-code-analysis-and-stylecop/ in a `netcoreapp2.0` targeted app. 

modifying it slightly to 

```
dotnet add package Microsoft.CodeAnalysis.FxCopAnalyzers -v 2.3.0-beta1
dotnet add package StyleCop.Analyzers -v 1.1.0-beta004
```

after some toying around with it... I was able to get a beautiful sea of red StyleCop errors when running 

```powershell
Start-PSBuild -Clean -Configuration Style
```


https://github.com/PowerShell/PowerShell/compare/master...markekraus:StyleCop

**Comment by iSazonov** [comment]
@markekraus Great news! Do this work on Unix too?

**Comment by markekraus** [comment]
I tried doing a very basic console project in Ubuntu and it failed with `Feature 'IOperation' is disabled.` errors, so I'm guessing it would only work on Windows. that means we could have it run only in the Windows CI and adjust Start-PSBuild to error when `Style` is used on linux.

Right now... it would be painful to have it run at all. For just the files in the Web Cmdlets folder there are over [1419 issues](https://gist.github.com/markekraus/5746e0240c86c0869a8b4ad910028b31). But.. some of these may not really apply. For example

```none
.\commands\utility\WebCmdlet\Common\BasicHtmlWebResponseObject.Common.cs(5,1): error SA1200: Using directive should appear within a namespace declaration
```

We don't enforce that in this project, In fact [our guidance](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/coding-guidelines.md#layout-conventions) says to do the opposite. 

> Namespace imports should be specified at the top of the file, outside of namespace declarations.

I read through [SA1200](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1200.md) and tend to agree with it. *shrugs

**Comment by markekraus** [comment]
actually.. after some google-fu I was able to get StyleCop working on linux on a simple console project (needed `<Features>IOperation</Features>` added to a property group). But, I have no clue how to make this work with our project. Supplying `Style` as the configuration results int `Linux` configuration being chosen. I don't understand our build internals well enough to try this manually. One would think you could just run `dotnet build` in the assembly directory, but that doesn't work.

**Comment by bergmeister** [comment]
@markekraus : Haha, that brings back memories of a question that I asked about the roslyn analyzers half a year ago: https://github.com/dotnet/roslyn-analyzers/issues/1151#issuecomment-303509027
I am not sure if it is worthwhile just waiting until the whole build system has switched to MSBUILD per the PR that I mentioned above.

**Comment by iSazonov** [comment]
@markekraus Thanks for great research! If MSFT team approve this we'll continue to resolve minor problems.
I like the idea to turn on some StyleCops.Analyzers rules in the PowerShell repo.

**Comment by xtqqczze** [comment]
We enabled StyleCop.Analyzers package in #13963 and I have submitted PRs for various rules.

There are a huge number of issues though, see https://www.codefactor.io/repository/github/powershell/powershell/issues, any help would be appreciated!
