### ISSUE TITLE
Support Fedora 27

### ISSUE THREAD

**Issue by franklinyu** [PowerShell/PowerShell#5744]
[Fedora 27 has been released on November 14th](https://fedoraproject.org/wiki/Releases/27/Schedule). Any plan to support this platform (or has it already been supported)? Current README and installation instructions only mention Fedora 25 and 26.

**Comment by markekraus** [comment]
I haven't tried it, but the instruction 25 and 26 look to be the same and I don't see anything in the Fedora 27 release notes that stick out as an issue. (If anything, the fact that libcurl now uses OpenSSL instead of NSS in 27 is a good thing). Assuming the kernel is not extremely different between 26 and 27, the instructions for 26 should probably work for 27.

**Comment by franklinyu** [comment]
I thought so; I was just wondering whether Fedora 27 is left out intentionally.

Then I expect that Fedora 27 would also be tested, and bug of PowerShell on Fedora 27 (if any) would be fixed (or at least accept pull request)?

**Comment by markekraus** [comment]
> I was just wondering whether Fedora 27 is left out intentionally.

Probably not! It is a new OS version and much of the Microsoft Team's focus has been on getting 6.0.0 read for GA release. 

> PowerShell on Fedora 27 (if any) would be fixed (or at least accept pull request)?

At the very least, we would check if the bug is reproducible on one of the listed OS's. I suspect that any bug that shows up in 27 would reproduce in 26. At least until 27 is added to the list. Regardless, if a bug is discovered in 27 and it can be fixed without regression in other OSes, than it could still be valuable. Even if MS doesn't official support it, the Community may have interest in resolving the bug.

**Comment by franklinyu** [comment]
Good to hear that. Looking forward to the GA release, and thanks for all the efforts.
