### ISSUE TITLE
Why do we have dependency of .Net framework for Powershell?

### ISSUE THREAD

**Issue by joshidp** [PowerShell/PowerShell#5769]
Hi

Thanks for the effort.

I want to know why do we need  .Net framework for Powershell?

Thanks

**Comment by SteveL-MSFT** [comment]
A decision was made very early on for PowerShell to build it on top of dotnet rather than C/C++ due to several reasons:

1. C# being a managed language allows for more rapid development compared to native languages like C as you worry less about resource management
2. dotnet framework provides an abstraction over many OS constructs.  So on Windows, you don't need to understand the idiosyncrasies of win32 apis for Processes vs Services and instead work with a consistent OO api.  With dotnetcore, we now how an abstraction over different operating systems.
3. the breadth of dotnet framework means you can access many apis for various things as well as call into native apis like COM and C style exported functions

**Comment by joshidp** [comment]
Thanks
