### ISSUE TITLE
Add a -NoNewLine to Write-Verbose

### ISSUE THREAD

**Issue by StingyJack** [PowerShell/PowerShell#5779]
A -NoNewLine would be nice here since the usual convention in .net languages is WriteLine to include crlf and Write to not.

This is probably true for the other Write-* functions (except Write-Output).

**Comment by bergmeister** [comment]
Can you please give an example of a use case where this is needed/helpful and concatenating the string before calling `Write-Verbose` is not possible? Or is this only for convenience?

**Comment by StingyJack** [comment]
Any place where you would use normally use Debug.Write, Trace.Write, or Console.Write in .net languages.  Its not often, but is useful sometimes when trying to produce coherent output and you dont want a bunch of stringbuilders/etc, because all the `|Out-Null` just makes more visual cruft to deal with, or because you cant (or shouldnt) wait until a full "sentence" is formed to emit a diagnostic message

**Comment by fvanroie** [comment]
I came accross the same issue, wanting to update log messages on the same line, as the cmdlet progresses. This would be a nice feature indeed.

**Comment by bergmeister** [comment]
This should be relatively easy to implement. Do you approve @SteveL-MSFT ?

**Comment by bergmeister** [comment]
@SteveL-MSFT I have done a quick hacky PoC where I just change the `WriteVerboseLine` method in the `ConsoleHostUserInterface` class [here](https://github.com/PowerShell/PowerShell/blob/c1c5344a8897262433141ecbc13bb06ac2c4bbef/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L1242) to call the `Write` instead of the `WriteLine` method.
If I then execute a script with the content `Write-Verbose foo -Verbose; Write-Verbose foo -Verbose`, I get `VERBOSE: fooVERBOSE: foo` as an output. Clearly the problem is that we would have to remove the `VERBOSE: ` string that is always pre-pended but then one would not see whether it is a verbose message or not. Maybe it is better to add the `-NoNewline` switch to `Write-Information`? Similar problems with pre-pended text apply to `Write-Debug` and `Write-Warning`. What are your thoughts?

**Comment by fvanroie** [comment]
I have this process that receives log data in bits and pieces. Using Verbose this is also echoed to the user. The only issue I had was that the last line has to be buffered since an incoming message could be split halfway a line that continues in the next update. So that's what led me to searching for a -NoNewline option.

Write-Verbose it great to output continuous long text blocks.
Write-Progress is more fitting for shorter status messages as opposed to long scrolling text.

Anyway, it's not that big of a deal too me. I didn't want to mix Write-Verbose for full lines and Write-Progress for split lines, so I just buffer the last line now and output it when each line is complete.

**Comment by StingyJack** [comment]
> This is exactly what we have Write-Progress for. Does it not work for your scenarios?

 `$global:ProgressPreference = 'SilentlyContinue'` ends up in most of my scripts as Write-Progress seems to just slow things down.  Perhaps its just that modules misuse it. 

> For that purpose, you would use Write-Host...

Yes and have to listen to every cargo cult parrot - and PSScriptAnalyzer - tell me how awful I am for using Write-Host. I like _less_ aggravation. More importantly, I dont want a script or module emitting verbose messages all the time, I just want them emitted when i ask for them.  Write-Host doesn't do that.

> A graphical host might pop up a dialog instead. Also consider the impact of action preferences on their presentation. 

If the calling application is not a console, it has already got some kind of handling for displaying the output streams. Along with the ability to display a stream, comes the responsibility of rendering it sensibly.   If someone makes an application that shows a popup for every verbose message, they deserve that special place in hell where they must play "punch the monkey" but can never win.

**Comment by SteveL-MSFT** [comment]
@StingyJack `Write-Progress` in PSCore6 was fixed awhile back to only update on a timer (rather than on every update) which improved perf significantly.

**Comment by ev-dev** [comment]
Yikes! stumbled over here _way_ past the party but still just want to mention that this is definitely one of the random little inconsistencies of the core cmdlets that seems to have been thrown on the 'Some Day' pile (deservedly so), but now has been lost to the sands of time...

Considering the `Write-Host` cmdlet was given the `-NoNewline` switch for a reason, it seems pretty rational to me that the switch should belong in the parameters of all of the `Write-(Information|Warning|Verbose|Debug|Error)` cmdlets as well.

Indeed, it's a pretty trivial feature, but I did find myself in a situation where I wanted to condense my console output as much as possible, but I also wanted to see info messages which I couldn't write to stream #1 (success) since I was relying storing return/output Objects in a variable.

Could be an easy win for someone familiar with the codebase (wish I was)!
