### ISSUE TITLE
Update MSI packaging for new version

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#5821]
https://github.com/PowerShell/PowerShell/blob/master/build.psm1#L2071

We need to consider what combinations of `productCode` and `upgradecode` needs to be changed for 6.1

As @bergmeister  noted, ProductCode is automatically changed:
> ... the `productCode` is always a new Guid when being called from`Start-PSPackage` higher up [here](https://github.com/PowerShell/PowerShell/blob/master/tools/packaging/packaging.psm1#L246).  

 See the docs about preparing an upgrade: https://msdn.microsoft.com/en-us/library/windows/desktop/aa370837(v=vs.85).aspx

**Comment by TravisEz13** [comment]
- ProductCode: https://msdn.microsoft.com/en-us/library/windows/desktop/aa370854(v=vs.85).aspx
- ProductId:  https://msdn.microsoft.com/en-us/library/windows/desktop/aa370855(v=vs.85).aspx
- UpgradeCode: https://msdn.microsoft.com/en-us/library/windows/desktop/aa372375(v=vs.85).aspx

We call `productCode` `ProductGuid` in New-msiPackage.  We should fix this so the next person doesn't have to dig through to figure it out like I had to.

**Comment by bergmeister** [comment]
@TravisEz13 : your reference code line with the default for product code is misleading because the `productCode` is always a new Guid when being called from `Start-PSPackage` higher up [here](https://github.com/PowerShell/PowerShell/blob/master/tools/packaging/packaging.psm1#L246) .

**Comment by TravisEz13** [comment]
@bergmeister, thanks

**Comment by bergmeister** [comment]
If I understand correctly then the current behaviour in terms of product code and upgrade code is OK, i.e. it is correct to always auto-generate a new GUID because otherwise you get an error of the kind 'another version of this product is already installed' but the upgrade code must remain constant (per architecture) if you want to allow direct upgrades, which you definitely want for patch version updates and proabably also for minor version updates.
The official WiX documentation about it is [here](http://wixtoolset.org/documentation/manual/v3/howtos/updates/major_upgrade.html) and seems to confirm that but it also says `Test upgrade scenarios before you ship version 1`

**Comment by TravisEz13** [comment]
PowerShell/PowerShell-RFC#115 is addressing this
