### ISSUE TITLE
Environmental variable not reflected

### ISSUE THREAD

**Issue by LawrenceHwang** [PowerShell/PowerShell#5863]
I can’t seem to think of valid use case for the reported steps (running Windows PowerShell from PowerShell Core console). However, it’s something unexpected so bringing it to your attention. 

Steps to reproduce
------------------
Environment: PowerShell Core 6 (GA) on Windows

In the pwsh: 
1. run `powershell`
1. $env:psmodulepath

Expected behavior
-----------------
The psmodulepath should be the value from Windows PowerShell.

Actual behavior
---------------

The value is from the pwsh session.

**Comment by bergmeister** [comment]
As far as I know this is by design. Despite the version number of 6 implying that it is a successor, PowerShell 6 is meant to be looked at as if it was a new, different product. Some modules are not compatible in PowerShell 6 and this is just one of many reasons why you do not want to share a common path by default. If you wish then you can still add your Windows PowerShell modules path to the one of PowerShell Core.

**Comment by iSazonov** [comment]
If you first run Windows PowerShell do you see `$env:psmodulepath`?

**Comment by markekraus** [comment]
I can repro this. PS Core has a separate PSModulePath env var because of the seperateion from windows POwerShell module. unfortunately, when you start windows PowerShell from PowerShell Core, it sees the PSModulePath environment path and adopts it. If you do this the other way around and start PowerShell Core from Windows PowerShell, powershell core ignores the PSModulePath environment variable and uses it's own.

in PowerShell Core:

```powershell
$env:PSModulePath; powershell -c '$env:PSModulePath'
```

```none
C:\Users\username\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\6.0.0-rc.2\Modules
C:\Users\username\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\6.0.0-rc.2\Modules
```

In Windows PowerShell:

```powershell
$env:PSModulePath; pwsh -c '$env:PSModulePath'
```

```none
C:\Users\username\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files\Intel\;C:\opscode\chefdk\modules\
C:\Users\username\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\6.0.0-rc.2\Modules
```

**Comment by iSazonov** [comment]
Yes, I semms mixed the directions.

It is dup #2636

**Comment by LawrenceHwang** [comment]
Thank you guys. I checked the discussion in #2636. I see the behavior is caused from the subprocess inherits the variable from its parent now. Wondering why it's does not behave the same the other way around though (launching PowerShell Core from Windows PowerShell)? Launching Windows PowerShell from PowerShell Core may be a less common use case. However, it definitely cause inconsistent user experience.

**Comment by markekraus** [comment]
@LawrenceHwang Because PowerShell core needs to ignore the Windows PowerShell. `PSModulePath` is set on your system and passed to Windows PowerShell when it starts you can see this by starting cmd.exe form start and running `echo %PSModulePath%`. PowerShell Core needs to ignore this by default to prevent Windows Powershell Modules from loading by default and to find the PowerShell Core modules.
