### ISSUE TITLE
module with a exported aliase don't auto import that alias if conflicting native command exists

### ISSUE THREAD

**Issue by KevinMarquette** [PowerShell/PowerShell#5877]
I created the suggested module in #5866 to create an alias for `SC` and to act as a placeholder for other aliases. I discovered that it will not auto import the alias module when calling `sc` because of the `sc.exe` conflict. If I import the module any other way, then the alias works as expected. I suspect that if I had a non-conflicting alias that was called the module would import and then the original alias would work as expected.

psd1
```
@{
        RootModule        = 'PowerShell-Core-Compatibility-Alias.psm1'
        ModuleVersion     = '0.1.0'
        GUID              = '14905138-6639-4c1c-8297-e587f27dc943'
        Author            = 'Kevin Marquette'
        CompanyName       = 'Unknown'
        Copyright         = '(c) Kevin Marquette. All rights reserved.'
        Description       = 'Adds aliases to PowerShell Core that were removed from Windows PowerShell'
        FunctionsToExport = @()
        CmdletsToExport   = @()
        VariablesToExport = @()
        AliasesToExport   = @('sc')
    
        PrivateData       = @{
            PSData = @{        
            }
        }
    }
```
psm1
```
Set-Alias -Name sc -Value Set-Content -ErrorAction Ignore
```

Steps to reproduce
------------------

```powershell
PS:> Install-Module PowerShell-Core-Compatibility-Alias
PS:> Get-module PowerShell-Core-Compatibility-Alias
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.1.0      PowerShell-Core-Compatibility-Alias sc

PS:> SC -Path $env:temp\test.txt -Value 'test'
```

Expected behavior
-----------------
That calling the exported `sc` alias would import the module and create the alias.
Then the `sc` alias for `Set-Content` would create a file with the value `test`
```none

```

Actual behavior
---------------
The windows `sc.exe` is called and gives it's output
```none
ERROR:  Unrecognized command

DESCRIPTION:
        SC is a command line program used for communicating with the
        Service Control Manager and services.
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Jaykul** [comment]
That's the expected behavior --regardless of whether the command in the module is a function, cmdlet, or alias-- a module will only be autoloaded to satisfy the command if the command cannot be found at all without loading the module. If you think about it, you'll realize it couldn't be any other way, or we'd never be able to safely write modules that overwrite existing commands.

For example, in Windows PowerShell `glg` is an alias for `Get-LocalGroup` -- try making a glg.cmd file in your path:

```posh
New-Item .\Scripts -Type Directory -Force
$Env:Path += ";" + (resolve-path .\Scripts\).Path
Set-Content .\Scripts\glg.cmd "@echo Hello World"
Get-Command glg*
```

You'll see that glg shows up as an alias _without a definition_, and also as an Application: glg.cmd

It will look like the alias comes first in the output of Get-Command, which would mean that it would be what's executed -- but that's only because we triggered Get-Command's _search_ mode by using a wildcard, try this:

```posh
Get-Command glg
```

And you'll see that the alias _does not show up_.  In the first output, the fact that the alias had no definition (i.e., it shows an arrow -> with nothing on the right) should have been our clue. If you run `glg` you'll get the batch file ... _unless_ you first import the module:

```posh
Import-Module Microsoft.PowerShell.LocalAccounts
Get-Command glg*
```

Now you'll see the alias has a definition, so it's going to _actually_ win when we run it --which we can tell by running:

```posh
Get-Command glg
```

**Comment by KevinMarquette** [comment]
That's perfectly logical when you break it down that way. It kills the value of the module that I was going to create because of a specific conflict, but PowerShell is not wrong here.

**Comment by iSazonov** [comment]
@KevinMarquette The module is useful - simply we should import it manually, in profile files or in engine. See suggested roadmap in https://github.com/PowerShell/PowerShell/issues/5870#issuecomment-357240591

**Comment by Jaykul** [comment]
@KevinMarquette did you see my jump-start? I still need to dump the defaults from PS6 on LInux & Windows and then break this list up based on that, but: https://gist.github.com/Jaykul/2c10404e13f6ae82e20abec4fa756bb3
