### ISSUE TITLE
Using Xml Serializer Generator for .NET Core

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#5882]
Can we improve PowerShell Core startup with [.NET Core Xml Serializer Generator](https://github.com/dotnet/announcements/issues/39)?

**Comment by bergmeister** [comment]
@iSazonov Good idea. I tried this in my branch [here](https://github.com/bergmeister/PowerShell/commit/7d3e202d653defb60a39840e43af4db317e4bb78) but I don't think it worked since there was no `*.XmlSerializers.dll` file in the publish folder. Maybe this is because we haven't fully switched to msbuild yet or because I don't have enough understanding of how the current build works.

**Comment by iSazonov** [comment]
@bergmeister You're awesome!

Currently .Net Core and CLI use _ported_ MSBuild.

I think we should ask MSFT experts whether we get any benefits from this.
