### ISSUE TITLE
start menu folder includes version number

### ISSUE THREAD

**Issue by Stanzilla** [PowerShell/PowerShell#5884]
I installed the 6.0 release and the start menu folder that is created is called `PowerShell-6.0.0` will the folder name change with future versions? Is this because side-by-side installs are possible? Wouldn't it be better to just have it called `PowerShell 6`? The dash makes it look a bit weird as well.

**Comment by iSazonov** [comment]
Yes, it is for side-by-side installs - you can easily install preview versions side-by-side with the release version.
I believe the directory name is good until anybody discover a broken scenario.

**Comment by Stanzilla** [comment]
Well, may I suggest just removing the hyphen then? Probably looks better :)

**Comment by bergmeister** [comment]
The reason why there is a folder is not only side by side but also that the folder can contain e.g. an x64 and x86 version. For 6.0 it is a known issue that the start menu will contain only either x64 or x86 but this has already been fixed for the upcoming version. But I think we can consider replacing the dash with a space (I removed the dash already from the short cut name itself already). It is good to include the full version because it makes it easy for non-technical people to figure out their exact version should a patch be required at some point (e.g. due to new security vulnerabilities in .Net Core).

**Comment by bergmeister** [comment]
@Stanzilla The fix with the hyphen would be very easy. Do you want me to guide you? The fix would be on [this](https://github.com/PowerShell/PowerShell/blob/master/assets/Product.wxs#L178) line to replace the `ProductSemanticVersionWithName` variable with `ProductSemanticVersionWithNameAndOptionalArchitecture`

**Comment by Stanzilla** [comment]
@bergmeister Here, right? https://github.com/PowerShell/PowerShell/blob/bb09b88390607945fa5d65bffd621f9264135f36/assets/Product.wxs#L28

**Comment by bergmeister** [comment]
No, line 178 as per the link in my comment.
