### ISSUE TITLE
Detecting Default Indexer: Why is [array].GetDefaultMembers() empty?

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#5902]
I'm experimenting with writing unit tests that involve detecting whether an underlying object has a default indexer.  In other words, I'm trying to test whether `$obj[$index]` is a meaningful statement for a given `$obj`.  It seems like this should be possible based on [this article](https://msdn.microsoft.com/en-us/library/kz0a8sxy(v=vs.110).aspx) which includes the following statements:

> ...Visual C# ... have simplified syntax for accessing indexed properties and allow one indexed property to be a default for its type.
>...
>By default, a C# indexer appears in metadata as an indexed property named "Item".
>...
>To determine whether a type has a default property, use the GetCustomAttributes(Type, Boolean) method to test for the DefaultMemberAttribute attribute. If the type has DefaultMemberAttribute, the MemberName property returns the name of the default property.

Based on that and some experimentation, it seems like `.GetDefaultMembers()` could be used to detect whether an object has a default indexer.  For example,

```PowerShell
[hashtable].GetDefaultMembers()
[string].GetDefaultMembers()
[int].GetDefaultMembers()
```

outputs `[MemberInfo]` for the `Item` and `Chars` properties of the `[hashtable]` and `[string]` types, respectively, and nothing for `[int]`.  This seems consistent with `[string]` and `[hashtable]` but not `[int]` being indexable. `[array].GetDefaultMembers()`, however, returns nothing despite that it supports indexing.

1. Why is `[array].GetDefaultMembers()` empty?
2. Is there a better general way to test whether an object has a default indexer in PowerShell?

**Comment by lzybkr** [comment]
I wasn't aware of `GetDefaultMembers`. It looks like it can help answer your question, but it's not sufficient, you'll have to check that you have a viable method considering the number of arguments vs. the number of parameters (and to be thorough, considering default arguments).

PowerShell relies on the `DefaultMemberAttribute`

```
PS> ([string].GetCustomAttributes([System.Reflection.DefaultMemberAttribute], $false)).MemberName
Chars
PS> ([hashtable].GetCustomAttributes([System.Reflection.DefaultMemberAttribute], $false)).MemberName
Item
```

You'll see that `Array` has no such attribute - because array indexing is implemented in IL, not by a method.

You can find PowerShell's logic [here](https://github.com/PowerShell/PowerShell/blob/c8ccb376b489bc17c76b94a60ce218f023c936bd/src/System.Management.Automation/engine/runtime/Binding/Binders.cs#L3888).

I do see one corner case that is not an Array and there is no `DefaultMemberAttribute`. If the type implements `IDictionary<K,V>`, PowerShell will use `TryGetValue` - the type need not have a "default member" even though it commonly will.

**Comment by alx9r** [comment]
FWIW, I did not find a way to implement `IsIndexable` because I did not find a general way to determine whether `TryGetValue` would succeed _a priori_.  I did, however, implement `MightBeIndexable` which I'm finding almost as useful for my use (unit testing).  `MightBeIndexable` simply returns true iff an object is `[array]`, `[Generic.IDictionary]`, or has a default member attribute.
