### ISSUE TITLE
Shouldn't App Paths registration be done for HKLM?

### ISSUE THREAD

**Issue by saschanaz** [PowerShell/PowerShell#5905]
https://github.com/PowerShell/PowerShell/blob/bb09b88390607945fa5d65bffd621f9264135f36/assets/Product.wxs#L120-L124

pwsh is installed globally so shouldn't it be on HKLM?

**Comment by bergmeister** [comment]
Because the base code for adding the start-menu shortcut was already there before I made modifications to it, I never noticed that it was `HKCU` but @saschanaz  is absolutely right because the install scope is per machine and not per user. I was about to ask at some point if the installer should rather install only on a per user basis (or give the option) but for the moment, `HKLM` is the better thing to do.
