### ISSUE TITLE
Add Direct Evaluation of Web Content as PS Code

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#5909]
This is a common code scenario:

```powershell
iex (iwr $uri).content
```

It is debatable whether this is good or bad practice,... but it is common enough that I think it may be worth adding this feature natively. I don't believe it changes the existing security landscape as you can already do the above. It would only make it easier. 

This could be accomplished by either adding a parameter to `Invoke-WebRequest` (Perhaps, `-EvaluateContent` or something) or perhaps through a new web cmdlet (something like `Invoke-WebExpression`).

Anyway, I'm opening this issue to discuss the merits and possibilities of adding this feature as well as possible design and implementations.

**Comment by iSazonov** [comment]
I'd expect that `Issue-Enhancement` is for approved features.

**Comment by markekraus** [comment]
@iSazonov https://github.com/PowerShell/PowerShell/blob/31f76395525e526f140d8cfef6b070287e51bce4/docs/maintainers/issue-management.md#issue-and-pr-labels

> `Issue-Enhancement:` the issue is more of a feature request than a bug.

This is a feature request.

**Comment by Jaykul** [comment]
I'd rather discourage people from doing that, rather than make it easier...

**Comment by SeeminglyScience** [comment]
👍  to everything @Jaykul said. Additionally, it would be awesome if it we could get a confirmation prompt with an option to view the content of the script similar to chocolatey.

**Comment by al-ign** [comment]
> It is debatable whether this is good or bad practice

It is definitely a bad practice, but oh so common nowadays, for ex. look at Ruby's rvm.

Personally, I would object adding -EvaluateContent parameter to iwr, because it will change what cmdlet **does** (it works with web resources, not executes some arbitrary code).
Also, I can't see a reason to create new cmdlet for that (Invoke-WebExpression), because at minimum it will duplicate full IWR functionality (you will need all that session, certificate and proxy parameters), without any real improvement to usage case.
Finally, you can add some parameter to iex, but - you will need all that iwr stuff here (certs, session, proxy) too. 

So, IMHO, it does not worth the hassle.

(And mandatory "If you want to 'simplify' your life - just make a wrapper function, and make sure it will be available everywhere where you need it")

> Although, if this new cmdlet or feature enforced code signing checks, execution policy, and scope (e.g. by downloading the file to disk, properly marking it as remote, and executing it without dot-sourcing)

i.e. everybody just ignore it and will continue to use 'iex (iwr $uri).content'. So why waste time and resources?

**Comment by markekraus** [comment]
> It is definitely a bad practice

This argument fails when you realize that so many practices fall in this paradigm and the only difference is the protocol (HTTP/HTTPS vs SMB, SSH, SCP, etc). Even installing modules from the PS gallery fits this paradigm. Running code from sanctioned repos fits this paradigm.... really it exists in so many forms but people only complain about HTTP/HTTPS. *shrugs

> Personally, I would object adding -EvaluateContent parameter ...

I agree with that.

> Also, I can't see a reason to create new cmdlet for that (Invoke-WebExpression), because at minimum it will duplicate full IWR functionality

So? Its not hard to do. The Web Cmdlet base class is flexible and designed for purpose built spin-offs like this. if I knew how to "dot source" in C# I could have a working cmdlet for this in maybe an hour or two. It's somewhat trivial to implement.

> without any real improvement to usage case.

Downloading and executing code doesn't have a use case?

https://github.com/PowerShell/PowerShell/blob/9bedef0c62614029a8892b0477b15cafbe1040b3/tools/releaseBuild/Images/microsoft_powershell_windowsservercore/dockerInstall.psm1#L28

But seriously, it does. With what @Jaykul discussed implemented, storing signed code on a repo and executing it is a pretty legit use case.

> Finally, you can add some parameter to iex, but

I agree it doesn't belong there.

> So, IMHO, it does not worth the hassle.

You don't have to code it. :) 

> So why waste time and resources?

Let's not let convenience become irrelevant in this project.

One benefit of it being an included command with restrictions in place would be to encourage adoption of better practices. Yes, user can and will always fall back to iex+iwr. Yes, old documentation, misguded blogs, and Open Source Project will still have examples of iex+iwr. But, we have an opportunity to 1) make it easier for doing this kind of thing which is common and necessary (like it or not) 2) recommend best practices.

There is no need to worry about resources. This is an Open Source project. If this cmdlet were even accepted by the PowerShell Team, they would likely not be the ones implementing it. They would put it up for grabs and someone like myself could work on it.

**Comment by iSazonov** [comment]
@markekraus I think you should address security concerns in the initial propose. Currently PowerShell engine keeps remote executions under very strict control.

**Comment by Jaykul** [comment]
> Currently PowerShell engine keeps remote executions under very strict control.

Except when people use Invoke-Expression.

**Comment by lzybkr** [comment]
I suggest adding a new parameter to `Invoke-Expression` that accepts a `HtmlWebResponseObject` so you can do:

```
iwr $url | iex
```

Then you can add all the fancy validation logic in the parameter set that accepts the `HtmlWebResponseObject`.

**Comment by mklement0** [comment]
Great idea, @lzybkr.

I've accidentally created a duplicate issue #8816, where, after some discussion, the proposal is now to to enhance `Invoke-Command`, not `Invoke-Expression` (which, as discussed in the linked issue, has a number of problems and, perhaps more importantly, whose use we generally want to discourage).

https://github.com/PowerShell/PowerShell/issues/8816#issuecomment-460886333 adapts your idea to use with `Invoke-Command`.

**Comment by mklement0** [comment]
Since #8816 was closed as a duplicate, let me summarize it here:

Adding the proposed functionality to `Invoke-Expression` seems ill-advised, for the following reasons:
  * primarily, [we want to discourage `Invoke-Expression` use in general](https://blogs.msdn.microsoft.com/powershell/2011/06/03/invoke-expression-considered-harmful/).
  * (a moot point, based on the above, but there are problems with `exit` handling, the inability to run in a child scope, and a couple of bugs, #8778 and #8815; @SteveL-MSFT came up with a clever workaround that addresses all issues except the `exit` behavior; e.g.: <br>`iex "& { $(irm https://aka.ms/install-powershell.ps1) } -Preview"`)
  *  the command name doesn't quite convey the intent of the operation (that is, invoking a _script_)
  
Enhancing `Invoke-Command` is a more natural fit, given that a(n external) _script_ is a sub-type of a _command_.

Adapting @lzybkr's idea would give us (using the URL of PowerShell's own installation script, and using `-Preview` as a `ValueFromRemainingArguments` pass-thru argument):

```powershell
# with direct argument (-WebRequest could bind positionally).
icm -WebRequest (iwr https://aka.ms/install-powershell.ps1) -Preview

# via the pipeline
iwr https://aka.ms/install-powershell.ps1 | icm -Preview
```
Below is a proof of concept written in PowerShell, temporarily named `icmw` / `Invoke-CommandFromWeb`; if you substitute `icmw` for `icm` in the above commands, it should work on all platforms and also in Windows PowerShell.  
On Windows, the execution policy is enforced, unless `-Force` is passed.


```powershell
Set-Alias icmw Invoke-CommandFromWeb
function Invoke-CommandFromWeb {
  <#
  .SYNOPSIS
    Executes a .ps1 script downloaded via Invoke-WebRequest.
  .DESCRIPTION
    Enables convenient direct execution of .ps1 scripts available online,
    typically for running / bootstrapping installation tasks, via the output
    from an Invoke-WebRequest call that retrieves the script.
  .PARAMETER WebRequest
    The result of an Invoke-WebRequest that downloads a .ps1 script
    as a plain-text resource. Typically passed via the pipeline.
  .PARAMETER ArgumentList
    Arguments to pass to the downloaded script, if any. May be passed
    as an array or as individual arguments.
  .PARAMETER Force
    On Windows, forces execution by bypassing the execution-policy check.
    By default, the downloaded script is considered a remote (downloaded) file.
  .EXAMPLE
    Invoke-WebRequest https://aka.ms/install-powershell.ps1 | Invoke-WebCommand -Preview
  
    Downloads the PowerShell Core installation script and invokes with the -Preview switch.
  #>
    [CmdletBinding(PositionalBinding=$false)]
    param(
      [Parameter(Mandatory, ValueFromPipeline, Position=0)] [Microsoft.PowerShell.Commands.WebResponseObject] $WebRequest,
      [Parameter(ValueFromRemainingArguments)] [Alias('Args')] [string[]] $ArgumentList,
      [switch] $Force
    )
  
    $ErrorActionPreference = 'Stop'
  
    $sourceUri = if ($PSVersionTable.PSEdition -eq 'Desktop') { $WebRequest.BaseResponse.ResponseUri.AbsoluteUri } 
    else                                                      { $WebRequest.BaseResponse.RequestMessage.RequestUri }
    Write-Verbose "Source URI: $sourceUri"
  
    if ($sourceUri -notmatch '\.ps1$') {
      Throw "Resource $sourceUri must be a .ps1 script file."
    }
  
    # Save the web-request content to a temporary script file.  
    $tmpScript = [IO.Path]::Combine([IO.Path]::GetTempPath(), [IO.Path]::GetRandomFileName(), (Split-Path -Leaf $sourceUri))
    $null = New-Item -Type Directory -Path (Split-Path -Parent $tmpScript)
    Write-Verbose "Temporary script path: $tmpScript"
    Set-Content -Encoding Utf8 -LiteralPath $tmpScript -Value $WebRequest.Content
    
    # Unless -Force was passed, mark the script as downloaded from the web (on Windows).
    if (-not $Force -and $env:OS -eq 'Windows_NT') {
      Write-Verbose "Marking as remote file: $tmpScript"
      "[ZoneTransfer]`nZoneId=3`nHostUrl=$sourceUri" | Set-Content -LiteralPath $tmpScript -Stream Zone.Identifier
    }
    
    # Execute the temporary script with the pass-thru arguments.
    try {
      # Note: We need to Invoke-Expression so that the pass-thru args are
      #       properly recognized by the script; just & $tmpScript @ArgumentList
      #       won't work.
      #       To make Invoke-Expression safe, we must ensure that all arguments
      #       (but not parameter names) are single-quoted.
      $cmdLine = "& `"$tmpScript`" $(foreach ($arg in $ArgumentList) { if ($arg -match '^-\w+$') { $arg } else { "'{0}'" -f ($arg -replace "'", "''") } })"
      Write-Verbose "Invoking: $cmdLine"
      Invoke-Expression $cmdLine
    } finally {
      Write-Verbose "Cleaning up."
      Remove-Item -EA Ignore -LiteralPath (Split-Path -Parent $tmpScript) -Recurse
    }
  
}
```

----

As an aside, note @SteveL-MSFT's idea from the closed duplicate:

> Perhaps an alternative would be to have a `HTTP:` and `HTTPS:` drive that would allow any cmdlet accept a file path to `GET` and `POST` to a URL? This would mean `Get-Content https://aka.ms/install-powershell.ps1` would work.

@vexx32 responded:

> implementing such a provider would be interesting to say the least. Love the idea, though!
> [...]
> If it can utilise the web cmdlets' base functionality, we can hopefully avoid having two disparate sets of features for the same thing here.

@iSazonov demonstrated how this could simplify the use case at hand:

```powershell
icm https://aka.ms/install-powershell.ps1

# or even:
& https://aka.ms/install-powershell.ps1
```

He suggests fleshing out the idea in an RFC and has created a reminder issue for one at #8835.

**Comment by douglasparker** [comment]
Well that’s annoying. Can we get this issue reopened? I can’t stand bots that do this.
