### ISSUE TITLE
powershell process has 21 child processes

### ISSUE THREAD

**Issue by sh0375** [PowerShell/PowerShell#5933]
https://github.com/PowerShell/PowerShell/issues/new

Steps to reproduce
------------------

```powershell
Launch jobs in remote sessions with 
New-ComplianceSearch, Get-ComplianceSearch and Start-ComplianceSearch.
```

Expected behavior
-----------------

```
no child processes
```

Actual behavior
---------------

```
a lot of child processes: [https://ibb.co/g5F3SR]
```

Environment data
----------------

```powershell
> $PSVersionTable
PS /home/sh0375> $PSVersionTable
Run 'do-release-upgrade' to upgrade to it.
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
@sh0375 Could you please add more descriptions?

**Comment by sh0375** [comment]
Problem is that powershell process has a lot of child processes. Why this happens and how to avoid it? What description can I add?

**Comment by iSazonov** [comment]
The product uses a number of threads - explain what problems it causes? Which scenario does not work or is slow, failed, bad?

**Comment by iSazonov** [comment]
The processes themselves do not consume a lot of resources. Resources consumes what works within them. In some cases, we really consume a lot of resources when we work with file system or output formatting. Partly it depends on the .Net Core 2.0.0 we use - they are already working on optimization and with release version 2.1.0 we will automatically work faster and better use resources. After that I hope we will also optimize inside PowerShell Core.
Also you use cmdlets from additional modules - they themselves can be implemented so that consume a lot of resources and should be optimized too.
