### ISSUE TITLE
Copy-Item sets the Archive-Bit

### ISSUE THREAD

**Issue by logg-sar** [PowerShell/PowerShell#5993]
Hi there

I have here an file, lets call it sel.txt with no attributes:
**Get-Item .\sel.txt**
**Directory: D:\aaa**
**Mode                LastWriteTime         Length Name**
**----                -------------         ------ ----**
**------       19.01.2018     12:02         228747 sel.txt**

After copying the File Copy-Item .\sel.txt D:\111\

**Get-Item D:\111\sel.txt**
**Directory: D:\111**
**Mode                LastWriteTime         Length Name**
**----                -------------         ------ ----**
**- a----       19.01.2018     12:02         228747 sel.txt**

We are using the archive-bit for some purposes, but independently the copy operation shouldn't alter neither a file nor the attributes. IMHO

Environment data
----------------

> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by markekraus** [comment]
`copy` in `cmd` does the exact same thing. I believe this is expected behavior as a "copy" is an "archive" of the original. If you need to clear the archive bit after a copy you could do:

```powershell
$archive = [System.IO.FileAttributes]::Archive

$Item = Copy-Item .\sel.txt D:\111\ -PassThru
$Item  | Set-ItemProperty -Name attributes -Value  ($Item.Attributes -bxor $archive)
Get-Item $Item
```

**Comment by logg-sar** [comment]
Hi

yes, your´e right. Copying with the commandline also changes the attribute.

However - I don´t understand the sense!
A copied file should be an 100% copy. That he creation date is changed is understandable, but changing of attributes....

IMHO is he archive-attribute a marker for backup/archiving. If every copied/moved file haves this attribute it would mean that every file will be backed up - or I have double work to remove the attribute.

Well - if its so I have to live with it. 
But IMHO it doesn't make any sense.

**Comment by PatrickJD** [comment]
I believe this is more accurately defined as operating system behavior, rather than PowerShell behavior.  The copied file is a new file to the operating system, so the archive bit is set due to this.

> IMHO is he archive-attribute a marker for backup/archiving. If every copied/moved file haves this attribute it would mean that every file will be backed up - or I have double work to remove the attribute.

This is exactly what the archive bit is used for, for backup systems that are archive bit aware.  If you copy a new file in, save a file, move a file, etc, this is set to ensure the file is backed up and makes perfect sense as a default behavior, and I believe your situation where you want the archive bit clear is less common.

If anything, I think the best solution to this problem if any changes were to be made to the copy-item cmdlet, it would be to have an argument that clears the archive bit on copy.  Something like Copy-Item -ClearArchiveBit or something like that.

**Comment by logg-sar** [comment]
>  I think the best solution to this problem if any changes were to be made to the copy-item cmdlet, it would be to have an argument that clears the archive bit on copy. Something like Copy-Item -ClearArchiveBit or something like that.

Agree!

**Comment by markekraus** [comment]
IMO, this doesn't warrant a change to Copy-Item. You can already perform the action with Set-Item. if ease of use was added anywhere, it would be set-item. then you could do `copy-item @params -PassThru | Set-Item -ClearArchiveBit`
