### ISSUE TITLE
Enable-PSRemoting throws error

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#5998]
I get an error when running `Enable-PSRemoting` not only on my Win10 dev machine but also on a clean WinServer 2016 Azure VM. I am sure someone can explain the error and how to resolve, but this is not what the issue is about! The issue that stuff has to work out of the box on on standard environment like Windows images that one gets in Azure.
This is also related to issue #5979 which is the upcoming feature of running `Enable-PSRemoting` in the installer. I do not think it would be good having to always suppress the error just because of that.

Steps to reproduce
------------------
Open pwsh as an Admin (cmdlet requires it)
```powershell
> Enable-PSRemoting
```

Expected behavior
-----------------
No error. I cannot say what the correct behaviour is because it depends on what is 'wrong' here.

Actual behavior
---------------

Error is thrown
````powershell
> Enable-PSRemoting
WinRM is already set up to receive requests on this computer.
Set-WSManQuickConfig : <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault"
Code="2150859113" Machine="localhost"><f:Message><f:ProviderFault provider="Config provider" path=
"%systemroot%\system32\WsmSvc.dll"><f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault"
 Code="2150859113" Machine="VSTS2"><f:Message>WinRM firewall exception will not work since one of the network
 connection types on this machine is set to Public. Change the network connection type to either Domain or Private and try again. 
</f:Message></f:WSManFault></f:ProviderFault></f:Message></f:WSManFault>
At line:116 char:17
+                 Set-WSManQuickConfig -force
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Set-WSManQuickConfig], InvalidOperationException
+ FullyQualifiedErrorId : WsManError,Microsoft.WSMan.Management.SetWSManQuickConfigCommand
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-rc
PSEdition                      Core
GitCommitId                    v6.0.0-rc
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by bergmeister** [comment]
@SteveL-MSFT Could you comment on this please since it is related to your request feature?

**Comment by SteveL-MSFT** [comment]
`Enable-PSRemoting` uses `Set-WSManQuickConfig` which fails if any of the network connections are set to `Public`.  The way to fix this in Windows PowerShell is something like: `Get-NetConnectionProfile | Set-NetConnectionProfile -NetworkCategory Private` (although you should really do this per net connection profile, this is only for testing purposes on a private network you trust...).

The "good news" is that if you add the Windows PowerShell PSModulePath, the *-NetConnectionProfile cmdlets work with PSCore6 (at least for this purpose, haven't tested it beyond that).

`Enable-SSHRemoting` would not depend on `Set-WSManQuickConfig` so it wouldn't encounter this issue.  However, it seems that we should still respect public vs private network connection profiles so that `-AllowRemotingOverPublicNetworks` type of switch would allow manual override.

I don't think there's much we can do about `Set-WSManQuickConfig` as the actual implementation of that cmdlet functionality is within WinRM.

**Comment by alexandair** [comment]
@SteveL-MSFT Enable-PSRemoting has the -SkipNetworkProfileCheck parameter. You don't need to manually change net connection profile.

**Comment by SteveL-MSFT** [comment]
@craiglandis on Server SKUs, PowerShell remoting is enabled by default, so `Enable-PSRemoting` I believe sees that it's enabled and doesn't do anything.  The Firewall Exception for Public networks should still be there so by default won't accept connections from the Public connection.  The error is intended to give a warning like if you are on some Public network.  The wording is about the current state.  I think in general, we don't want to promote `-SkipNetworkProfileCheck` and leave it as an advanced user option to be discovered.
