### ISSUE TITLE
Pipes can't handle inifinite stream

### ISSUE THREAD

**Issue by igrep** [PowerShell/PowerShell#6009]
Steps to reproduce
------------------

1. Install Git for Windows (or other \*Nix compatible tool chains may work too).
2. Run:
    ```powershell
    yes | head
    ```

Expected behavior
-----------------

The `yes | head` command exits after printing `y` 10 times (as bash would do).

Actual behavior
---------------

`yes | head` command doesn't exit after printing `y` 10 times.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I guess this is a problem of design of pipes.
So it might be very hard to fix (and fixing it  causes incompatibility with the existing versions)

**Comment by PetSerAl** [comment]
Native application do not really fit PowerShell single-threaded push pipeline. So PowerShell first collect all input for native application and only then invoke it, thus you can not pass infinite input to native application by PowerShell, although you can use PowerShell own tools to accept infinite input:
```powershell
yes | select -First 10
```

**Comment by igrep** [comment]
I tried `yes | select -First 10`, but `yes` didn't stop after printing `y` 10 times, and `pwsh` kept consuming CPU (perhaps by `select`).
So should this be counted as `select`'s bug?

**Comment by lzybkr** [comment]
`Select-Object -First $n` throws an instance of `StopUpstreamCommandsException`. The upstream commands are responsible for terminating, so the bug isn't in `Select-Object`.

We can verify that upstream PowerShell commands really do stop processing by injecting a sleep, e.g. the following finishes despite the infinite loop:

```powershell
& { 1; while(1){}; 2 } | Select-Object -First 1
```

So it sounds like native commands are not terminated. I would guess the bug is in `NativeCommandProcessor` - specifically I think the method `NativeCommandProcessor.CleanUp` or maybe `NativeCommandProcessor.ProcessRecord`.
