### ISSUE TITLE
pwsh host input redirection and incomplete input

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#6045]
Context https://github.com/vors/jupyter-powershell/issues/9 .

I'm trying to implement a powershell REPL on top of powershell host.
To achive it, I'm running `pwsh -noprofile -File -` and write the input into the stdin pipe.
Problem: there is no way to get out information about incomplete input.
I.e. when I just send `(` and follow it up with many new lines, I will getting just more `>> ` prompts.

I don't know is it solvable and even if it is, does it worth to do it. I'm filling this issue for completeness and cross-linking from the jupyter kernel.

Steps to reproduce
------------------

```powershell
'(\n\n\n' | pwsh -File - -noprofile
```

Expected behavior
-----------------

```none
>>                                                                                                                                     
At line:1 char:2
+ (
+  ~
An expression was expected after '('.
At line:1 char:2
+ (
+  ~
Missing closing ')' in expression.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : ExpectedExpression
```

Actual behavior
---------------

```none
>> 
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                                  
----                           -----                                                                                                  
PSVersion                      6.0.0                                                                                                  
PSEdition                      Core                                                                                                   
GitCommitId                    v6.0.0                                                                                                 
OS                             Darwin 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEA...
Platform                       Unix                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                
PSRemotingProtocolVersion      2.3                                                                                                    
SerializationVersion           1.1.0.1                                                                                                
WSManStackVersion              3.0  
```

**Comment by SteveL-MSFT** [comment]
One of the problems we have with PSEditorServices is that @daviwil had to implement a Host instead of being able to rely on the existing ConsoleHost.  It seems that if we can define a simple api that just communicates to pwsh via stdin/stdout that could solve both problems. cc @tylerl0706 

I guess we can just start with your scenario and expand as needed to support PSEditorServices.

**Comment by SteveL-MSFT** [comment]
Not sure if we have time to work on a proposal for this and should be RFC, so putting in 6.2 for now

**Comment by daviwil** [comment]
What's needed for PSES is much more involved than just an I/O channel for console experience, it requires a more complete set of integration points so that PSES can share access to the runspace that the ConsoleHost creates.  I'd like to take a crack at an RFC for it (or at least help with the authoring of one) at some point in the future when I can really investigate what's needed for it.

@vors, isn't checking for `>>` enough to know that the input is incomplete?  Or is the problem that you need a way to report to the user the syntax that causes the incomplete expression?

**Comment by vors** [comment]
@daviwil correct, I put a detection for `>>`, but I need
a) the correct error message about incomplete input. Guessing would be hard because it could be `(` or `{` and so on.
b) Some way to abort/complete the parsing. At the moment I'm asking the user to restart the kernel.
