### ISSUE TITLE
remove file opt-out from telemetery and only use environment variable

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#6078]
We should only have one opt-out mechanism.  We should remove the file opt-out as it is not flexible enough for all situations.

**Comment by daxian-dbw** [comment]
I agree that we should only have one way to opt-out. If .NET Core uses the environment variable only, then we should do the same.

**Comment by iSazonov** [comment]
I agree - we should not litter the home folder.

**Comment by thezim** [comment]
Is opting out an option during the install now? Personally I would prefer to have to opt in.

**Comment by iSazonov** [comment]
@thezim 
> environment variables are stored in the in registry so this shouldn't be an issue.

We can set environment variable by GPP but security men require _forced security policy_.

**Comment by SteveL-MSFT** [comment]
Let's be clear that any new telemetry will likely be opt-in and be described in a RFC.  The current basic startup telemetry we have now helps provide data of PSCore6 adoption and determines if we increase or decrease our investments.  Since we ship packages outside of GitHub, we can't just track download numbers (which are unreliable anyways).
