### ISSUE TITLE
PowerShell cmdlet(similar to packagemanagement) for Upgrading pwsh 

### ISSUE THREAD

**Issue by kvprasoon** [PowerShell/PowerShell#6080]
@SteveL-MSFT : Just had a though, Why can't we have a PowerShell cmdlet (```Update-PowerShell```) which will update pwsh to the latest available release.

**Comment by SteveL-MSFT** [comment]
Can't find the issue, but we had discussed this previously.  Where we landed is that it would be ideal to have a PackageManagement Provider so that you can run `install-package powershell` and get the latest version.  It's simply a priority and resource problem.  It seems ok to update via the msi on Windows and on Linux we already support updates via apt/yum and on macOS it's published to HomeBrew.

**Comment by SwarfegaGit** [comment]
On the topic of updating.  One annoyance on Windows is that each time I upgrade I have to repin PowerShell to my Start Menu and Taskbar.  This is caused by the fact the default installation path includes the version number.  E.G...

* C:\Program Files\PowerShell\6.0.0-alpha.18
* C:\Program Files\PowerShell\6.0.0-beta.8
* C:\Program Files\PowerShell\6.0.0-rc.2
* C:\Program Files\PowerShell\6.0.0
* C:\Program Files\PowerShell\6.0.1

etc

**Comment by kvprasoon** [comment]
My vote for the above issue

**Comment by SteveL-MSFT** [comment]
@SwarfegaGit can you open a new issue for that?

**Comment by iSazonov** [comment]
Related [comment](https://github.com/PowerShell/PowerShell/issues/6046#issuecomment-360996243) about the default installation path.

**Comment by doctordns** [comment]
As noted in my issue post - this should just be simpler. I should not have to go to GitHub, select the correct file out of a bunch, download it, then run it and re-pin all the shortcuts.

For developers, this workflow may be great - but you can make a lot simpler.

I'd like a fully supported, in the box **Update-PowerShell** cmdlet.

**Comment by iSazonov** [comment]
Fill free to discuss in #8663
