### ISSUE TITLE
Update-Help https is not actually supported

### ISSUE THREAD

**Issue by JhonnyTerminus** [PowerShell/PowerShell#6155]
Steps to reproduce
------------------

```powershell
Import-Module -Name PowerShellGet
$Module = Get-Module -Name PowerShellGet
$Module.HelpInfoUri
Update-Help -Module PowerShellGet   
```

Expected behavior
-----------------

```none
Update help files for PowerShellGet
```

Actual behavior
---------------

```powerhshell
Update-Help : Failed to update Help for the module(s) : 
'PowerShellGet'
The HelpInfoURI https://go.microsoft.com/fwlink/?linkid=855963 does not start with HTTP.
At line:1 char:1
+ Update-Help -Module PowerShellGet 
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (HelpInfoUri:Uri) [Update-Help], Exception
+ FullyQualifiedErrorId : InvalidHelpInfoUriFormat,Microsoft.PowerShell.Commands.UpdateHelpCommand   
```

Environment data
----------------

```powerhshell
Name                            Value                 
----                            -----                  
PSVersion                       5.1.14393.1944        
PSEdition                       Desktop                
PSCompatibleVersions            {1.0, 2.0, 3.0, 4.0...}
BuildVersion                    10.0.14393.1944        
CLRVersion                      4.0.30319.42000        
WSManStackVersion               3.0                    
PSRemotingProtocolVersion       2.3                    
SerializationVersion            1.1.0.1                
```

Screenshoot
----------------
![screenclip](https://user-images.githubusercontent.com/17069425/36207986-e714cd58-1197-11e8-8e99-b4d37f327e91.png)

**Comment by mmims** [comment]
I ran into this issue with PowerShellGet as well. Following the URI redirects to <https://pshelp.blob.core.windows.net/powershell/help/6/PowerShellGet/> which presents a `BlobNotFound` error. So I'm wondering whether the fact that the updateable help file doesn't exist is contributing to the error.

**Comment by tlindsay42** [comment]
I just reproduced this as well in my open source module project ([Armor](https://github.com/tlindsay42/ArmorPowerShell)) while working on setting up updatable help for both a HTTPS URL and a HTTP URL with a 301 redirect to HTTPS on PowerShell versions: `5.1.14393.2248` & `6.0.2`.

**Comment by MaximoTrinidad** [comment]
@JhonnyTerminus,

Just a reminder! Windows PowerShell issues need to posted under UserVoice site (https://windowsserver.uservoice.com/forums/301869-powershell) as stated in the PowerShell Core landing page: https://github.com/PowerShell/PowerShell#windows-powershell-vs-powershell-core 

Issues posted here are only directed to PowerShell Core and not Windows PowerShell, as they are handle by different teams.

Please repost this issue in UserVoice so the correct team can take action on it.

:)

I repo the steps on PowerShell Core 6.1.0-Preview.2 and it's working. No errors!

```
PS C:\Program Files\PowerShell\6-preview> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Microsoft Windows 10.0.17686
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS C:\Program Files\PowerShell\6-preview> Update-Help Powershellget
PS C:\Program Files\PowerShell\6-preview>
PS C:\Program Files\PowerShell\6-preview>
```
![updatehelp_ok_2018-06-11_20-39-49](https://user-images.githubusercontent.com/19892435/41263899-c978b8fa-6db7-11e8-9917-a2821127693f.jpg)

This issue can be close!

PS. And this issue seems corrected in latest RTM Windows 10 (> & Insider Build 17686)

**Comment by JhonnyTerminus** [comment]
@MaximoTrinidad Yeah I did not read that, seems a bit redundant but it's probably for centralized issue management,
Thanks :)

**Comment by JhonnyTerminus** [comment]
Fixed in latest PS closing
