### ISSUE TITLE
Please support Set-TimeZone

### ISSUE THREAD

**Issue by AceHack** [PowerShell/PowerShell#6165]
Please support Set-TimeZone

**Comment by iSazonov** [comment]
TomeZone names is different on Windows and Unix. 
Have we API for this in CoreFX?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Is this issue for addition of support for Set-Timezone via Linux and/or macOS?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@iSazonov, are you certain that #3605 removed this? 'http://github.com/PowerShell/PowerShell/issues/1109' as the culprit appears to be more probable.

**Comment by iSazonov** [comment]
> is systemd a prerequisite of PowerShell via Linux?

No, PowerShell has no specific prerequisites (but .Net Runtime and MMI have).

PowerShell follow .Net to reduce complicity and increase reliability. If .Net hasn't API to set timezone PowerShell can not set timezone too. Sometimes PowerShell uses OS specific p/invokes but only if they is a standard like POSIX, otherwise it would be very difficult to implement, test and support.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PowerShell/PowerShell/issues/6165#issuecomment-1030672595

~~@iSazonov, should we file an issue at the .NET Core repository then?~~

If we remain mindful of https://stackoverflow.com/questions/54798183/set-global-timezone-in-net-core#comment103371480_54798293, https://stackoverflow.com/a/54798293/9731176 seems like it should work:

```.CS
Install-Package TimeZoneConverter
TimeZoneInfo tzi = TZConvert.GetTimeZoneInfo("Europe/London");
```

...meaning that we wouldn't even need to go as far down as the admittedly high-level abstractions that `timedatectl` provide.
