### ISSUE TITLE
Get-Help $commandName -Online redirects to version 5.1 help

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#6187]
`Get-Help $commandName -Online` links redirect to links displaying the help of PowerShell 5.1

Steps to reproduce
------------------

```powershell
Get-Help Get-ChildItem -Online
Get-Help New-Item -Online
```

This affects possibly most cmdlets.

Expected behavior
-----------------
Redirects to e.g.
https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Get-ChildItem?view=powershell-6
https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/New-Item?view=powershell-6

Actual behavior
---------------

Redirects to
https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Get-ChildItem?view=powershell-5.1
https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/New-Item?view=powershell-5.1

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.582
PSEdition                      Core
GitCommitId                    v6.1.0-preview.582
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jonathanmedd** [comment]
I had the same issue while presenting a session last night on changes in the web cmdlets in PowerShell Core and looking for the online help for Invoke-RestMethod. Couldn't find one of the new parameters listed and then realised the web page was for 5.1, not 6.0


Steps to reproduce
------------------

```powershell
Get-Help Invoke-RestMethod -Online
```

Expected behavior
-----------------

Redirects to: https://docs.microsoft.com/en-gb/powershell/module/Microsoft.PowerShell.Utility/Invoke-RestMethod?view=powershell-6

Actual behavior
---------------

Redirects to: https://docs.microsoft.com/en-gb/powershell/module/Microsoft.PowerShell.Utility/Invoke-RestMethod?view=powershell-5.1

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Looks like it's being tracked here already, https://github.com/PowerShell/PowerShell/issues/2616#issuecomment-301927380, and was on the 6.0.0-NiceToHave milestone.

**Comment by guitarrapc** [comment]
Is this issue will resolve in near future version?
It redirects to even not 5.1 url with ja-JP UI Culture for several cmdlets. (others are redirects to 5.1 url)

Actually, it's harmful redirecting to wrong version help page for PowerShell Core changed cmdlets. Many users will confuse at the first time and only few will check for 6.0 help.

Steps to reproduce
----

Set your System Language to Japanese and Non-Unicode to Japanese.

```powershell
help Out-File -Online
```

Expected behavior
----

Redirects to : https://docs.microsoft.com/ja-jp/powershell/module/Microsoft.PowerShell.Utility/Out-File?view=powershell-6

Actual behavior
----

Redirects to: https://technet.microsoft.com/ja-JP/library/dd315303.aspx

Environment data
----

```powershell
PS>$PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
