### ISSUE TITLE
Get-Command does not return HelpUri for all cmdlets.

### ISSUE THREAD

**Issue by thezim** [PowerShell/PowerShell#6188]
This also affects Get-Help -Online on the specific cmdlets.

Steps to reproduce
------------------

```powershell
Get-Command -CommandType Cmdlet | Where-Object { [string]::IsNullOrEmpty($_.helpuri) } | ft Name, HelpUri
```

Expected behavior
-----------------
HelpUris are returned.

Actual behavior
---------------

```none
Name                     HelpUri
----                     -------
ConvertFrom-SecureString
ConvertTo-SecureString
Get-Credential
Get-ExecutionPolicy
Get-PfxCertificate
Remove-Alias
Set-ExecutionPolicy
Start-Transcript
Stop-Transcript
```

Environment data
----------------
```powershell
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Darwin 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RE...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
The issue is that _if a given cmdlet's module happens not to be imported at the time you run your command_, its `.HelpUri`, as reported by `Get-Command`, erroneously returns `''` (the empty string).

You can verify this by directly invoking a cmdlet in question - which implicitly forces importing of its module - and then running your command again:

```powershell
ConvertFrom-SecureString -?  # forces import of underlying module 'Microsoft.PowerShell.Security'
```

Now, re-running your command should eliminate all cmdlets from module `Microsoft.PowerShell.Security` from your list (meaning that their `.HelpUri` property now contains the expected value), which in your case should only leave:

```powershell
Remove-Alias       # from module Microsoft.PowerShell.Utility
Start-Transcript   # from module Microsoft.PowerShell.Host
Stop-Transcript    # ditto
```
