### ISSUE TITLE
Handling ActionPreferenceStopException looses the actual exception

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#6200]
# Exception Handling in PowerShell is the pits (part 1)
### I am _re-filing_ this from Connect from as it appears to have gone missing again.

Steps to reproduce
------------------

```powershell
try {
   get-content nosuchfile -ErrorAction Stop
} catch [System.Management.Automation.ActionPreferenceStopException] {
   $_.PSTypeNames, $_.Exception.PSTypeNames, $_.Exception.InnerException.PSTypeNames
} 
```

Output:
```
System.Management.Automation.ErrorRecord
System.Object
System.Management.Automation.ItemNotFoundException
System.Management.Automation.SessionStateException
System.Management.Automation.RuntimeException
System.SystemException
System.Exception
System.Object
```

Expected behavior
-----------------

Since I "caught" an ActionPreferenceStopException, I should be able to see the ActionPreferenceStopException.

Actual behavior
---------------

PowerShell unwrapped the exception and gave me only what *caused* the exception. If I wanted that, I *would have* said so, since this works (and produces the same output as above)

```powershell
try {
   get-content nosuchfile -ErrorAction Stop
} catch [System.Management.Automation.ItemNotFoundException] {
   Write-Host "It's an ItemNotFoundException, obviously"
   $_.PSTypeNames, $_.Exception.PSTypeNames, $_.Exception.InnerException.PSTypeNames
} 
```

## NOTE: THE REAL PROBLEM

It is *not* possible to catch the specific type explicitly, and **also** handle the generic case:

```powershell
try {
   get-content nosuchfile -ErrorAction Stop
} catch [System.Management.Automation.ItemNotFoundException] {
   Write-Host "It's an ItemNotFoundException, which I can fix ... "
}  catch [System.Management.Automation.ActionPreferenceStopException] {
   $_.PSTypeNames, $_.Exception.PSTypeNames, $_.Exception.InnerException.PSTypeNames
} 
```

Environment data
----------------

This has *always* been a problem, and it persists in PowerShell 6.

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by BrucePay** [comment]
@Jaykul Yes - this behaviour that's been around since the very beginning of PowerShell. Basically the pipeline uses `ActionPreferenceStopException` to wrap the exception that has the actual error in it then throws the wrapper. Consequently, if it wasn't automatically unwrapped in try/catch/trap you would never be able to catch the underlying exception since all you'd ever see would be the wrapper. So your example:
```
try {
   get-content nosuchfile -ErrorAction Stop
} catch [System.Management.Automation.ItemNotFoundException] {
   Write-Host "It's an ItemNotFoundException, obviously"
   $_.PSTypeNames, $_.Exception.PSTypeNames, $_.Exception.InnerException.PSTypeNames
} 
```
wouldn't work. 

Why do you want to catch this exception?

**Comment by Jaykul** [comment]
Because I want to handle:

1. The specific exception that I am expecting
2. Some other exception that is caused by the ErrorActionPreference
3. Other exceptions which might be thrown within the try block (i.e. a generic catch handler)

This is particularly the case when I'm using `trap` to basically wrap the entire scope of a process / end block, **or** when the ErrorPreference is being set _inside_ the function that I'm calling (possibly in multiple places, but not in all places which might throw exceptions).

**Comment by Jaykul** [comment]
Isn't it enough to say: **SOMETIMES** I can catch this type, but if I catch some other type, then **SUDDENLY** I cannot catch this type anymore!

How is that not a bug? Why I want to catch that type is irrelevant.

**Comment by vexx32** [comment]
Yeah, that's completely fair. 😄 

Whether or not this "should" be catchable, the behaviour should remain consistent.

**Comment by KirkMunro** [comment]
> Whether or not this "should" be catchable, the behaviour should remain consistent.

That's my thinking on this one: that it shouldn't be catchable, and that maybe PSScriptAnalyzer should flag if/when someone tries to catch a `System.Management.Automation.ActionPreferenceStopException`, because the intent of `-ErrorAction Stop` is to promote a non-terminating exception to terminating. Unless the fact that `ActionPreferenceStopException` is used as a wrapper to carry the non-terminating exception to the appropriate catch handler is relevant (I personally don't see the value in that though).

**Comment by KirkMunro** [comment]
Assuming the desired consistency is for internal wrappers such as `System.Management.Automation.ActionPreferenceStopException` to be used only to promote a non-terminating exception to terminating (as mentioned in my last comment), then the resolution of this issue is simply the addition of a PSScriptAnalyzer rule that identifies the anti-pattern and explains to users why they shouldn't catch `System.Management.Automation.ActionPreferenceStopException`.

@jaykul If you could comment for or against this as a resolution, since you're the OP, it would be appreciated. Then we can either discuss further or close this issue out and log an issue for the PSSA rule to be created.
