### ISSUE TITLE
Packaging: RegisterManifest.ps1 to have an unregister switch for uninstallation and possible conversion to cmdlet

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#6215]
From [this](https://github.com/PowerShell/PowerShell/pull/5999#discussion_r169779708) comment in [PR 5999](https://github.com/PowerShell/PowerShell/pull/5999):

- In order to have a cleaner (Windows) un-installation, means of undoing the action are needed, i.e. something like an `Unregister` switch.
- At the moment the script gets shipped in the installation folder but a conversion to a cmdlet was proposed as well in the referenced PR above.

**Comment by Robo210** [comment]
Currently RegisterManifest.ps1 attempts to uninstall the manifest before installing it (again). If it is possible that the provider GUID or channel names/types have changed since the manifest was previously installed, then it is not safe to uninstall the new manifest without first uninstalling the old manifest. For this reason it would be best to always uninstall the current manifest when uninstalling the MSI or before overwriting the manifest with a new version.
