### ISSUE TITLE
[Question] why import-module can load a .ps1 file ?

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PowerShell#6259]
```powershell
cd c:\Temp
@'
function Demo {
 'Demo'
 }
'@ > .\script.ps1
ipmo .\script.ps1 -verbose
# VERBOSE: Loading module from path 'C:\Temp\script.ps1'.
# VERBOSE: Dot-sourcing the script file 'C:\Temp\script.ps1'.
get-module -name script
# 
# ModuleType Version    Name                                ExportedCommands
# ---------- -------    ----                                ----------------
# Script     0.0        script
```
I found this [note](https://github.com/PowerShell/PowerShell/blob/c1c5344a8897262433141ecbc13bb06ac2c4bbef/src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs#L5874), but not sure if the created module is really a module.

**Comment by bergmeister** [comment]
Why not? You can also import a DLL and then call it's .net methods or PowerShell cmdlets (that's actually how I debug PSSA).

**Comment by LaurentDardenne** [comment]
In this case, the functions are not exported and are not related to the module :
```powershell
dir function:\demo|select mo*
# ModuleName Module
# ---------- ------
```
When I remove the module the functions are not deleted :
```powershell 
remove-module script
demo
#Demo
```
and when I add export-modulemember the script can not be imported anymore because it is not a module:
```powershell 
cd c:\Temp
@'
function Demo {
 'Demo'
}
Export-modulemember -function Demo
'@ > .\script.ps1
ipmo .\script.ps1
#export-modulemember : The Export-ModuleMember cmdlet can only be called from inside a module.
```
A curious behavior for a module.

**Comment by BrucePay** [comment]
Hi @LaurentDardenne  Some background: module manifests have a `ScriptsToProcess` field. The thing to know about `ScriptsToProcess` is that these scripts are executed (dot-sourced) _before_ the module proper is loaded i.e. they are invoked in the module context of the caller of `Import-Module`. This was done as a way to have a kind of "pre-action" mechanism in case anything needed to be prepared in the caller's module context. (In practise, I don't believe this was ever used much). 

Anyway, IIIRC paths passed to `Import-Module` are processed in a way that corresponds to their entries in the module manifest. Assemblies and .psm1 scripts get loaded as modules and .ps1 scripts are simply dot-sourced. Note that in all cases a module gets created, but it's empty for scripts. Because the script is executed outside of the module context, removing the module will have no impact on anything defined in those scripts which accounts for the behaviour you're seeing.

**Comment by LaurentDardenne** [comment]
Thank you.
