### ISSUE TITLE
Plan for open issues in milestone 6.0.0-NiceToHave?

### ISSUE THREAD

**Issue by mi-hol** [PowerShell/PowerShell#6267]
There are still many open issues in milestone 6.0.0-NiceToHave that I'd love to see included in 6.1.
What is the plan for them?

**Comment by iSazonov** [comment]
Plan is "nice to have" 😄 We want implement but _haven't resources_ - feel free to contribute or at least vote.

**Comment by iSazonov** [comment]
For me it is ok. I'd rename only 6 -> 7 when the time comes.

**Comment by mi-hol** [comment]
@iSazonov is this list of issues not actually the Backlog?

**Comment by SteveL-MSFT** [comment]
I'd like to get rid of the `6.0.0-NiceToHave` milestone as it's no longer relevant.  Going forward, rather than putting a bunch of issues in 6.x only to move them to 6.x+1, all non-critical issues that we believe should be addressed will be in the `Future` milestone.  There is no guarantee *when* an issue will be fixed, but the more up votes the higher the priority (depending on risk of changes, even a high priority issue may not be fixed quickly).  I'll review all the current `6.0.0-NiceToHave` issues and will move them either to `Future` or no milestone (which means undetermined).

**Comment by iSazonov** [comment]
I believe if you reviewed an issue it is better assign it to a milestone in any case to indicate that you already reviewed. For "no milestone" it can be `No milestone`, `Undetermine` or `No plans`.

**Comment by SteveL-MSFT** [comment]
@iSazonov that is a fair point.  cc @joeyaiello
