### ISSUE TITLE
Make PowerShell Classes Exportable Module Members

### ISSUE THREAD

**Issue by ephos** [PowerShell/PowerShell#6293]
Steps to reproduce
------------------

Currently when classes are defined within a module it seems the best way to access them us with the following.

```powershell
using module ModuleName
[Foo]::new()
Get-Module ModuleName
```

Expected behavior
-----------------

Like other module members (functions, cmdlets, variables, aliases, etc) it would be helpful to be able to declare classes and export them as module members.  Module manifests could have a section for this.

```powershell
ClassesToExport = @()
```

Using them would feel more in line with how the rest of the language works.  With the current implementation I find myself creating C# classes and importing the _.cs_ file with `Add-Type`.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.909
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.909
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
Dup #4112

**Comment by rockarruda** [comment]
@iSazonov This reads more of a feature request to me rather than a bug report.

**Comment by iSazonov** [comment]
It related with how we plan to design class visibility (public/private).

**Comment by BrucePay** [comment]
In PowerShell today, **all** public types are global. For example, when you import a binary module all of the public types defined in that assembly are globally visible in their declared namespaces. PowerShell classes work the same way. All types (classes) defined in a module are global, namespace qualified by the module name. (Side note: using `Add-Type` without namespace qualification is bad idea when creating reusable code as the types will be created in the top level namespace so your [foo] and my [foo] will collide.)

There is a plan to support type name aliases with the `using` statement to simplify some scenarios. That said, making PowerShell types work differently from the rest of .NET seems undesirable. (I supposed Export-Type could just export type name aliases into the context where the module is being imported.)

WRT the private type comment, remember how the debugger works - it's just PowerShell. If a type is not accessible from PowerShell, it's not accessible from the debugger either (which is why we have hidden rather than private members).

**Comment by adrian-andersson** [comment]
Bumping this issue
Can we also have the same for ENUMS, and REQUIREDRUNTIMES

**Comment by User1785604260** [comment]
I just stumbled upon a really easy way to export PowerShell classes from modules:

```powershell
# Export module classes
[psobject].Assembly.GetType("System.Management.Automation.TypeAccelerators")::Add("PSUtils", [PSUtils])
```

I add that at the bottom of my module where I have a PSUtils class defined, and now everything works just the way I've always wanted. Import-Module and #Requires -Modules work as-is, and my code that requires the class available at parse time also works. No more slow and limited "using module" needed!

Obviously this is still just a workaround to missing functionality, but it seems to do everything I need in the meantime.

**Comment by gabriel-vanca** [comment]
Any progress on this?
