### ISSUE TITLE
Would it be possible to have --help as an alias of -?

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#6397]
In linux, obviously `--help` (or `-h`) is more common than `-?` as a way to get help

Since it doesn't currently seem possible to name a parameter such that this would collide, it seems like a change like this wouldn't break anything, right?

Any reason this _should not_ be done?

**Comment by DWSR** [comment]
It would be great to get this via `CmdletBinding()`.

Also a potentially separate issue, but it seems as though `Get-Help` won't parse comment based help or `ParameterAttribute` based help for script files, which would probably reduce the usefulness of this.

**Comment by BrucePay** [comment]
@Jaykul It is possible to define a script/function parameter `--help` as in   `function foo ( ${-help} ) { ... }`. I bet no one actually does this but maybe we should check around.

> Any reason this should not be done?

The usual I suppose. It's work (open-source somewhat mitigates that). It clutters up the code with another special case in command processing (internally 'foo -?' gets rewritten as 'get-help foo'). Do we think it will bring sufficient benefit to warrant the code changes, that kind of thing.

**Comment by Jaykul** [comment]
No @BrucePay, the reason I said it doesn't seem possible is _that it won't work_:

```posh
function Test-Help {
[CmdletBinding()]
param(
[switch]${-help}
)
$PSBoundParameters
}
```
```
C:\PS> Get-Command Test-Help -Syntax

Test-Help [--help] [<CommonParameters>]

C:\PS> Test-Help --Help
Test-Help : A positional parameter cannot be found that accepts argument '--Help'.
At line:1 char:1
+ Test-Help --Help
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Test-Help], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Test-Help
```

You can pass `--Help` to a non-advanced function (and look for it in `$Args`), but you can't specify `-Help` as a parameter name (I suppose you can't use - as the first character of a parameter anymore).

**Comment by BrucePay** [comment]
@Jaykul Yes - there definitely seems to be a bug in the parameter binder here.

**Comment by chuanjiao10** [comment]
Have you ever thought about it?
why? Linux must have the same function, long name, short name parameter. Such as:
Ls -R, --recursive recursively displays subdirectories
-h,--help
Why does powreshell not support "--"? , all parameters use "-"?

Suppose there is such a command:
Mysql -u xxx #linux format
Mysql --username xxx #linux format
Mysql -username xxx #ps format


Because regardless of the linux command, or write their own linux script, do not support both parameter names, and parameter values, tab completion! ! ! (only support for command completion)
Most people, of course  want to use fewer keyboards and want to use mysql -u xxx.
However, short parameter names are not well understood. So there was "the same function, long name, short name parameter."

Powershell does not have this problem. In ps, regardless of the ps command developed by Microsoft, a command developed by a third-party company, a function written by itself, or a script written by itself.
You can use -u<tab key> to complete the parameter -username. Or use:
- <tab key> to complete parameter -username.

So i think ,  “ command **-help** ”  is enough

**Comment by Jaykul** [comment]
Yeah, so ... obviously PowerShell cannot emulate Linux-stype parameter binding, because in linux executables, `--long` parameters require double dashes because they're completely separate from the single-character versions, which can be _combined_ so e.g.:  `docker run -i -t` is _the same_ as `docker run -it`.  

In order to pull that off, you have to name the parameters with that in mind. Most PowerShell commands have multiple parameters that start with the same letter, like: 
```posh
Get-ChildItem -Filter *.png -Force -FollowSymlink -File
```

## However, there are a couple of exceptions

1. **Help for commands**, `--help` could be like `-?` -- a special parameter that could be intercepted by the shell and converted to `Get-Help <command>`.  We know it won't clash with any existing parameters, because it's not currently possible to write a function that takes `--help` as a parameter (but it **is** possible to write one that takes `-help`, so it's probably not a good idea to use that).
2. **pwsh** itself. Unlike commands _within_ PowerShell, the pwsh command is obviously actually a `linux` command, that has to work _in linux_ and behave properly.  Now, perhaps we can't quire fix all the parameter handling so it's compatible with the normal linux parameter binding (and still keep backwards compatibility), but we _could_ easily add `--help`.
