### ISSUE TITLE
Wrong Platform in $PSVersionTable for macOS High Sierra

### ISSUE THREAD

**Issue by bmkaiser** [PowerShell/PowerShell#6513]
`$PSVersionTable` is returning an incorrect platform for macOS High Sierra 10.13.3.

Source: [Engine Update Release Notes for PowerShell Core 6.0](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-6#engine-updates).

Steps to reproduce
------------------

```powershell
> $PSVersionTable.Platform
```

Expected behavior
-----------------

```none
MacOSX
```

Actual behavior
---------------

```none
Unix
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value                                                                                                                                                     
----                           -----                                                                                                                                                     
PSVersion                      6.0.2                                                                                                                                                     
PSEdition                      Core                                                                                                                                                      
GitCommitId                    v6.0.2                                                                                                                                                    
OS                             Darwin 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64                                             
Platform                       Unix                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                                                   
WSManStackVersion              3.0              

> $IsMacOS

True                                                                                           
```
```bash
$ system_profiler SPSoftwareDataType | grep "System Version"
      System Version: macOS 10.13.3 (17D102)
```

**Comment by mklement0** [comment]
Unfortunately, the release notes are incorrect.

What is correct is that PowerShell takes the information from `[System.Environment]::OSVersion.Platform`, i.e., from CoreFX and there, 
perhaps confusingly, **the behavior is by design** (from https://github.com/dotnet/platform-compat/issues/29, emphasis added):

> My main concern is with PlatformID.MacOSX. Back in the Silverlight days, `Environment.OSVersion.Platform` returned `PlatformID.MacOSX` on OSX. **However, on .NET Core it returns `PlatformID.Unix` on macOS to match Mono's behavior.**

> Code that compares Environment.OSVersion.Platform to PlatformID.MacOSX should use the newer RuntimeInformation.IsOSPlatform(OSPlatform.OSX) API instead.

More backstory at https://github.com/dotnet/corefx/issues/19694

--- 

The unfortunate thing is that the `[System.PlatformID]` enum that `[System.Environment]::OSVersion.Platform]` return values are instances of  still contains `MacOSX` as a value, but only for historical reasons.

The upshot is:

* `[System.Environment]::OSVersion.Platform]` is only useful to contrast platforms with Unix _heritage in the abstract_ with Windows - i.e., to distinguish Linux and macOS on the one hand from Windows on the other.

   * Perhaps we should therefore also introduce an automatic `$IsUnix` variable to reflect this distinction.

* `$IsMacOs` is therefore the best way to determine if you're running on macOS.

* `$PSVersionTable.OS` - which contains the value of  `[System.Runtime.InteropServices.RuntimeInformation]::OSDescription`- also reflects the specific platform, but only in a semi-structured way that furthermore refers to macOS as _Darwin_, the open-source OS on which macOS is based.

**Comment by SteveL-MSFT** [comment]
Thanks for noticing this.  I submitted a fix: https://github.com/PowerShell/PowerShell-Docs/pull/2227

Note that you can always click the `Edit` link on the doc page which will take you to GitHub and submit a fix yourself.  Thanks!

**Comment by mklement0** [comment]
@SteveL-MSFT: 

Thanks - hadn't even realized that it was a living document.

I think it's also important to document the behavior in `about_Automatic_Variables`, so I've created https://github.com/PowerShell/PowerShell-Docs/issues/2229
