### ISSUE TITLE
Need feedback for ported Test-Connection cmdlet

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#6557]
Currently we merged new ported version of Test-Connection cmdlet. See description in #5328.

The cmdlet has some issues on Unixes because of .Net Core API gaps. I'll open issues in .Net Core repo.

Now we need feedbacks for Test-Connection cmdlet.
 I think we should break the feedback into two parts:
1. scripting functionality
- Is the design good?
- Does the cmdlet work as expected?

2. interactive functionality (display output)
- Now we have implemented the output to the screen as progress bar and as text (without ETS) - we have to decide what is best to use.
- There is also a question about output headers and footers - should we emulate Windows/Linux output or should follow PowerShell output style?

**Comment by iSazonov** [comment]
@ConstantineK Thanks! Any feedback is accepted. Please add in your post that is behavior you expect.

**Comment by ConstantineK** [comment]
It might be confusing to a user, but I would argue that if they provide an additional parameter to Quiet the output, they are concretely asking for it to not present output except for true and false (as the docs say). 

The use case is writing some basic application logic in PowerShell where I specifically want to suppress output, progress bars, and the rest, and just be able to simply say "is this ip address available, true or false" 

I will take a look at that host helpers, thanks!

**Comment by ConstantineK** [comment]
So I was thinking something along the lines of this test passing  https://github.com/ConstantineK/PowerShell/commit/36aafe937fea5c6fe339cc25da025f27d6c44321

**Comment by ConstantineK** [comment]
I got you, but in that case then at least my original feedback is probably valid - in PS 5.1 -Quiet does not write to the console.

**Comment by vexx32** [comment]
I got curious about the behaviour here thanks to issue #7685 being raised. The main points raised there seem to be:

* Progress bar display is very much counter to expected display. There may be some circumstances where it is *useful*, but at present it is only duplicating console display unnecessarily.
* Console display is giving information that could be used programmatically, which is only being output at the end instead of outputting individual objects that could be used.
* Per the above point, all the useful information is buried in a subproperty, and the default display of the summary objects gives absolutely no information
* It was also raised that the current console display probably should be moved to the `Verbose` stream rather than being always output to host.

I have most of this laid out in code form as a bit of a proof-of-concept (see [this comment](https://github.com/PowerShell/PowerShell/issues/7685#issuecomment-431627292) for sample output), and I feel it is more responsive and easier to understand interactively *and* work with programmatically where needed... though I'm sure my code leaves something to be desired.

@iSazonov's point about this potential halting condition giving no output is very much valid:
```powershell
Test-Connection $UnreachableAddress -Count 1000 -Quiet
```

I would suggest that ``WriteProgress` only be used in cases where it can be *reasonably expected* that output will take some time -- for example, when `-Count` is supplied a value that is expected to take some time (e.g., any value higher than 15, or something).

**Comment by RichardSiddaway** [comment]
I think the progress bar should be an opt in feature.  while

Test-Connection $UnreachableAddress -Count 1000 -Quiet

could be run its much more likely that -Count will be set to a much lower value.   If I was waiting on a system becoming available I'd just test once with the test in a loop I could break out of when I got a successful result

**Comment by iSazonov** [comment]
> Perhaps -Count and -Quiet should be in different parameter sets?

User might want to programmatically measure delays or lost packets.
There are still many conflicting scenarios. Otherwise, I would have done it. :-)

> If I was waiting on a system

Is the Ctrl-C stopping not working?

**Comment by vexx32** [comment]
Well, in those instances I don't think anyone would want to use `-Quiet` in most cases... but yes, I agree that in general we shouldn't place arbitrary restrictions like that.

From my testing, Ctrl+C can *seem* like it isn't stopping for several seconds; the standard timeout seems to be a few seconds, and the cancellation isn't registered until the next response is received or the timeout expires. So it seems sluggish but does eventually stop.

**Comment by iSazonov** [comment]
> From my testing, Ctrl+C can seem like it isn't stopping for several seconds; 

We do -Count in cmdlet cycle and 4 attempts per second in CoreFX if I remember right.

**Comment by RichardSiddaway** [comment]
-Count and -Quiet need to be in the same parameter set as

test-Connection <computer> -Count 1 -Quiet  

is a common scenario especially in scripts where you're running against a large number of machines and want to determine if you can reach a machine before proceeding with next steps
