### ISSUE TITLE
Import-CliXml, Import-Csv, Import-PowerShellDataFile mishandle wildcard-based -Path arguments

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6583]
<sup>Supersedes #4472</sup>

In said cmdlets, `-Path` is declared as `[string[]]`, so these cmdlets are capable of accepting multiple files, if passed an _array_ of paths; ditto for `-LiteralPath`.

Passing a (single) _wildcard expression_ that itself resolves to _multiple_ files unexpectedly breaks, however.

The culprit may be that  [`ReportMultipleFilesNotSupported()`](https://github.com/PowerShell/PowerShell/blob/c1c5344a8897262433141ecbc13bb06ac2c4bbef/src/System.Management.Automation/utils/PathUtils.cs#L276) is called, whose purpose is to prevent resolution to _multiple_ paths, but whose use is not appropriate in this case.

Note: Potentially, additional cmdlets are affected - you can find the list of _candidates_ (some of which are definitely _not_ affected) as follows:

```powershell
gcm -parametername path | ? { $_.parametersets.parameters.parametertype -eq [string[]] }
```

Steps to reproduce
------------------

```powershell
"one,two`nuno,due" > file1.csv
"one,two`nun,deux" > file2.csv

Import-Csv -LiteralPath file1.csv, file2.csv
' vs. '
Import-Csv -Path file[12].csv
```

Expected behavior
-----------------

```none
one two 
--- --- 
uno due 
un  deux
 vs. 
uno due 
un  deux
```

Actual behavior
---------------

```none

one two 
--- --- 
uno due 
un  deux
 vs. 
Import-Csv : Cannot perform operation because the path resolved to more than one file. This command cannot operate on multiple files.
At /foo.ps1:21 char:1
+ Import-Csv -Path file[12].csv
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Import-Csv], PSInvalidOperationException
+ FullyQualifiedErrorId : ReadWriteMultipleFilesNotSupported,Microsoft.PowerShell.Commands.ImportCsvCommand
```

Environment data
----------------

```powershell
PowerShell Core v6.0.2 on macOS 10.13.3
PowerShell Core v6.0.2 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.2 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.674 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by BrucePay** [comment]
Since `Import-CSV` already supports reading from multiple files, it seams reasonable to make this change.

What's happening is that, in the `ImportCsvCommand` class, the `ProcessRecord` method calls `PathUtils.OpenStreamReader` which does both path expansion and opens the `StreamReader`.
```
StreamReader streamReader = PatthUtils.OpenStreamReader(this, path, this.Encoding, _isLiteralPath
```
Obviously, since only a single stream reader can be returned, the call has to error out if wildcards expand to more than one path. The solution would be to process the paths in two passes. Pass one expands the wildcards and pass 2 does the actual processing (using `LiteralPath`). 

Note that this is specific to the `Import-Csv` cmdlet implementation, so I'm not sure we can make any general assumptions about the others. However @mklement0 If you do have the time/inclination/patience to check them out, that would be cool.
