### ISSUE TITLE
Write-Verbose should be controllable

### ISSUE THREAD

**Issue by schittli** [PowerShell/PowerShell#6587]
Hello

Usually, the `-verbose` switch is used if one would like to get more information about _one_ module or script.
The reality is, however, that we're flooded with verbose messages.

Therefore it would be great if `-verbose` could be controlled. Just two ideas:

- By specifying a nesting level, e.g. `-Verbose <NestingLevel>`
`-Verbose 2` would activate verbose messages in the directly called script and in all commands which are called by the script itself.
- By specifying a script / module filter, e.g. `-Verbose @('Build.ps1', 'Invoke-Build')`
This would activate verbose messages in the script `Build.ps1` and in the command `Invoke-Build` itself.

Kind regards, 
Thomas

**Comment by iSazonov** [comment]
`-Verbose` is not inherited.
Have you give an example of this flood?

**Comment by mklement0** [comment]
@iSazonov:

`-Verbose` _is_ inherited, but _inconsistently_: The inheritance via advanced functions relies on implicitly set _local_ preference variables, `$VerbosePreference` in the case at hand:

  * binary cmdlets invoked from such an advanced function _do_ honor this preference variable.
  * advanced functions _implemented in a (different) module_ do _not_ - this is actually what #3106 complains about, and as such it is the _opposite_ of what @schittli is asking for.

This problematic inconsistency is the subject of #4568, but it is ultimately a separate issue.

@schittli: 

I understand the desire to have this, but the proposed syntax can't work, because `-Verbose` is a _switch_ parameter and can therefore not accept an argument other than `$True` or `$False` _if_ directly appended with `:` (e.g., `-Verbose:$False`).

Something like `-Verbose 2` would break backward compatibility; allowing something like`-Verbose:2` may work, but it would be a first for the PowerShell language: a parameter with an _optional_ argument (other than the implied Boolean for switches).   
With an array argument it gets even trickier, because the value must be a single token: `-Verbose:('build.ps1', 'Invoke-Build')`

**Comment by BrucePay** [comment]
@iSazonov No, not a dup - this is related to #3106 but is it's own issue since it applies to scripts and functions as well.

@mklement0 as daunting as it sounds, a new ubiquitous parameter`-VerboseLevel N` would be fine.

> This problematic inconsistency is the subject of #4568, but it is ultimately a separate issue.

The issue discussed in #4568 is actually an example of an "unfortunate" _consistency_ :-) Local preference variables are still just local variables. Modules provide isolation and so, by design, local variables never cross the module barrier. This includes preference variables. 

@schittli 
> By specifying a script / module filter, e.g. -Verbose @('Build.ps1', 'Invoke-Build')
This would activate verbose messages in the script Build.ps1 and in the command Invoke-Build itself.

You can do this (to some extent) today with `$PSDefaultParameterValues `. For example:
```
PS[1] (34) > $PSDefaultParameterValues = @{'Copy-Item:Verbose'=$true}
PS[1] (35) > copy xxx yyy
VERBOSE: Performing the operation "Copy File" on target "Item: C:\temp\xxx Destination: C:\temp\yyy".
PS[1] (36) >
```
Now the core issue,  the verbose (and debug, log, etc.)  message flood, is definitely a problem but I've always thought of the solution being something more like **Just My Code** in the VS debugger. (In fact it would nice to have it in the PowerShell debugger too.) @lzybkr and I have discussed this a few times.

**Comment by mklement0** [comment]
@iSazonov: 

> From this point of view, the inheritance of preference-variable values (in other scopes) looks dangerous.

The behavior _defaulting_ to inheritance is crucial, not just with respect to inheritance of common parameters, but also with respect to directly set preference variables, and that is currently broken, as discussed in #4568:  

* It is crucial for behavior-controlling parameters `-ErrorAction`, `-Confirm`, and `-WhatIf`.  
(To recap the problem with the current behavor: `-ErrorAction Stop` / `$ErrorActionPreference = 'Stop'`, `-WhatIf` / `$WhatIfPreference = $True` not taking effect just because a command such as `Expand-Archive` happens to be implemented as an advanced function is surprising and potentially destructive.)
* Inheritance-by-default is perhaps debatable for diagnostic/supplemental-output parameters such as `-Verbose`, `-Debug`, `-InformationAction`, and `-WarningAction`, but:
   * Changing their default behavior would certainly be a breaking change (and note that with a value of `Stop` you can even make these parameters behavior-controlling).
   * Inheritance _can_ be desirable, as #3106 shows.
   * Also note that the output-_collecting_ common parameters (`-OutVariable`, `-ErrorVariable`, `-InformationVariable`, `-WarningVariable`) exhibit _effective_ inheritance behavior too (by simply collecting stream output across all calls that happen in the advanced function's scope).

To _complement_ the default behavior with _opt-in_ mechanisms for limiting the scope of common-parameter inheritance such as `-Verbose`, `-Debug`, `-InformationAction`, `-WarningAction` and/or apply filtering makes sense.
