### ISSUE TITLE
Need review SslProtocol and others

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#6589]
From https://github.com/dotnet/corefx/#build--test-status
>To get the default OS best choice, if possible, don't use the method overloads of SslStream that take an explicit SslProtocols parameter. Otherwise, pass SslProtocols.None. We recommend that you don't use Default; setting SslProtocols.Default forces the use of SSL 3.0 /TLS 1.0 and prevents TLS 1.2.

It is for .NET Framework 4.7 - I don't know whether it applicable to .Net Core. /cc @TravisEz13 @PaulHigin

**Comment by markekraus** [comment]
This is the reason I added `Microsoft.PowerShell.Commands.WebSslProtocol`. The WebSslProtocol.Default is equivalent to SslProtcols.None. There is no SSL 3.0 on WebSslProtocol because HttpClient and WeRequest do not support SSL 3.0 in CoreFX (though it's not clearly documented anywhere I could find).

That Flags enum may or may not be useful for other APIs.

**Comment by TravisEz13** [comment]
I think I agree with the comment that @iSazonov  quotes.  Here are the guidelines:

- TLS 1.2 must be enabled.
- TLS 1.1, and TLS 1.0 may be enabled for backward compatibility only.
- SSL 3 and SSL 2 must be disabled by default.

**Comment by SteveL-MSFT** [comment]
The [default](https://github.com/dotnet/corefx/blob/3cc6fda0c6abe76eea222c165ebdf816e83df564/src/Common/src/System/Net/SecurityProtocol.cs#L11) for corefx is TLS, TLS11, and TLS12.

The default for .Net Framework for compatibility reasons includes SSL and doesn't include TLS12.
