### ISSUE TITLE
[bool]"false" and [bool]"true"

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#6639]
I was talking to @BrucePay about the idea of supporting [bool]"false" resolving to the boolean value $False.

This mainly affects when calling PowerShell scripts from DSLs and other shells.  There is no problem with this when calling a powershell script from powershell as it understands it's own boolean type.

I am mainly interested in [bool]"false" resolving to $False.  I don't have strong feelings on whether to change the behavior [bool]"anyotherstring" resolving to "true".

These are some of the issues this would seem to help with:
- DSLs that commonly use the string "true" when they do not have a true boolean (e.g. CloudFormation)
- The problem of passing booleans across shells because there is no standard "boolean" type between shells
- The problem of composing powershell command lines in code that use powershell switches - omitting or including the switch depending on the desired result is a pain.  Being able to always specify the switch , but control it's value with a variable makes things a lot less complex.

In some cases this *could* be resolved with using 0 and 1 - but the other problem is extant code and coding skills - for example for me to get everyone in our huge organization to change their true / false strings to 0 and 1 is a monumental effort that would never fully take.  Just fixing this in PowerShell would mean not having to re-code people's defacto practices.

**Comment by mklement0** [comment]
> I don't have strong feelings on whether to change the behavior [bool]"anyotherstring" resolving to "true".

Certainly in _implicit_ Boolean conversions it is important to retain the existing behavior, because simply using a command's output - which may be a string, notably always one when calling external utilities - as an implicit conditional for "Was there any output?" is a common idiom (`if (<command>) ...`)

With respect to _explicit_ Boolean conversions (casts):  At least personally I've written code such as `$hadOutput = [bool] (<command>)`, so a string other than `'true'` / `'false'` breaking the cast is problematic.

Thus, one approach would be to simply special-case string `'false'` (and its case variants) and convert that to `$False`, while keeping the existing empty/non-empty dichotomy in all other cases.

That has the advantage of not needing to introduce a potentially awkward distinction between implicit and explicit (cast-based) conversions.

Technically, it's a breaking change, but it probably falls into [Bucket 3: Unlikely Grey Area](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area).

**Comment by markekraus** [comment]
I have run into situations where I thought this would be excellent, bu I have also run into situations where this would have been breaking.

The breaking examples are those that work on the `$null` possibility where there is a tri-state `"true"`/`"false"`/`$null` on a string result. 

```powershell
if($result){
    $IsSet = $true
    $IsTrue = [Bool]::Parse($result)
} else {
    $isSet= $false
}
```

I think it was the Reddit API where I was having to do that because it returns string literals instead of Boolean literals and the condition is different whether the string is present or not (bad API design... gripe for another day). In any case, I'm not sure if this proposed change would actually break that or not. if the string is `"false"` and the condition coerces the string to boolean false, code that depended on the existence of string to return true would break. But I did want to point out that this would be a breaking change and I think it is a steep above bucket 3.

That said, I'm on board with this change even though I know it will break my code.

**Comment by DarwinJS** [comment]
Interesting use case. I guess you could move the coercion from the parameter to a compare statement and you would be able to preserve the string but retain a true Boolean compare?

**Comment by markekraus** [comment]
Yea, there are workarounds like switching to `[String]::IsNullOrEmpty()`.

I've seen this elsewhere but I can't remember an specific instances. In any case, it will break any situation where a conditional is being done on a string that may potentially contain `"false"` (assuming conditionals coerce to a boolean). Code that used to go one path would now go another. I'm not really sure how to do some anayltics to see how prevalent an issue it would be. I think it would be a step above rare though.

On the other hand. i have also run into code that was already going the wrong path because the author assumed `"false"` would be `$false`.. so this change may actually fix some already broken code. 🤣

**Comment by DarwinJS** [comment]
@markekraus  - you comment brings up that I should clarify I am advocating that the cast only work on the EXACT string "false" (case insensitive) - not on a substring that finds that value in the string.  I assumed this is how a cast of a string would work - but clarifying in case that assumption is incorrect.

**Comment by markekraus** [comment]
I used "contain" because I think of strings and variables as containers. I have updated it tot he following:

>  In any case, it will break any situation where a conditional is being done on a string that may potentially be `"false"` (assuming conditionals coerce to a boolean).
