### ISSUE TITLE
Loading Native Binaries in cross platform modules

### ISSUE THREAD

**Issue by adamdriscoll** [PowerShell/PowerShell#6642]
When taking dependencies (like ASP.NET Core), it may be required to load a native binary. This requires determining the correct runtime identifier and loading the correct binary at runtime. 

![image](https://user-images.githubusercontent.com/1256531/38702800-2868d712-3e67-11e8-989a-0ef62d6c2a87.png)

Determine the RID:
![image](https://user-images.githubusercontent.com/1256531/38702786-1e39dc00-3e67-11e8-8baf-ae324d6e8c4f.png)

Load the binary: 
![image](https://user-images.githubusercontent.com/1256531/38702809-2fa589f8-3e67-11e8-914e-26257bfbf8b8.png)

It would be great to either have some sort of capability in PowerShell to help alleviate this issue. 

Another recommended approach was to update Install-Module to behave more like NuGet where it will only install the binaries required for a particular operating system or platform.

**Comment by iSazonov** [comment]
You could use .Net Core APIs and Add-Type cmdlet.

**Comment by Jaykul** [comment]
This is related to #3091 XPLAT: RequiredAssemblies must automatically consider lib\framework

**Comment by iSazonov** [comment]
Until now, we do not have unified support in .Net Core for argument conversions. Without this, it makes no sense to do something here. Even the simplest type `int` can be implemented differently on different platforms. It can even have an inverted order of bytes. This is even more unpredictable for `struct`-s.

**Comment by Jaykul** [comment]
@iSazonov what does that have to do with anything? This is not an issue of types or unified anything.

We need PowerShell to do _at run time_ the same thing that nuget does at compile time:

1. Developer ships set of runtime-specific folders with assemblies in them
2. Developer documents the RootModule or RequiredAssembly
3. User just Imports the module
4. PowerShell picks the right folder, because it knows what OS/framework/runtime it is.

Note that this is NOT only a linux vs Windows vs mac problem. PowerShell Core on Windows requires different assemblies than Windows PowerShell, even for _formerly simple_ things shipped by Microsoft (e.g. for [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/).

**Comment by SteveL-MSFT** [comment]
Off the top of my head (aka not fully thought through), it seems we can try loading from a `runtimes` folder in the module base otherwise fallback to looking in the module base folder (and finally the GAC where appropriate).  This would make it compatible with existing modules and Windows PowerShell.

**Comment by Jaykul** [comment]
Actually, other portable projects (like PowerShell itself) using p/invoke do not have this problem, but that's because they only package the right binaries for the right platform, and have separate packages...

Despite that, I think @iSazonov is probably right -- I would be happy to amend my earlier post to say that _PowerShellGet_ should do it at **install** time, instead of PowerShell doing it at runtime. Then it's just a _packaging_ problem: [#PowerShellGet/273](/PowerShell/PowerShellGet/issues/273)

**Comment by SteveL-MSFT** [comment]
I would suggest continuing discussion in the PSGet issue.
