### ISSUE TITLE
Invoke-Command/Enter-PSSession using SSH hostname - prompting for finger print

### ISSUE THREAD

**Issue by thenecroscope** [PowerShell/PowerShell#6650]
I'm using the new Invoke-Command -hostname option over SSH, which is working well. It would be great to have a -Force option or something similar to prevent it from prompting to verifying the SSH Key/fingerprint, which is slightly preventing my automated Scripts. Many thanks

**Comment by SteveL-MSFT** [comment]
The prompt is coming from SSHD and no client can prevent it if the appropriate authentication data isn't presented (like pubkey). For automation, you should have sshd configured to not require an authentication mode that would prompt.

**Comment by thenecroscope** [comment]
Hi Steve, thanks for getting back to me on this. I've configured SSHD not to use password auth but keys only. It's working well for me, it's just the initial/first connection when I build up a new VM from a template. I can script around this using a combination of adjusting the known_hosts files, ssh-keyscan and the linux style Expect command. IMO it would be good to have an easier option to get round this issue, either a new command like Expect or perhaps a Force parameter that would bypass any issues with the known_hosts file or the initial prompt for connecting first time? Thanks again

**Comment by SteveL-MSFT** [comment]
Ok, it wasn't clear that you were referring to the server fingerprint (would have helped to provide the actual text output...).  There are [articles](https://linuxcommando.blogspot.com/2008/10/how-to-disable-ssh-host-key-checking.html) on how to suppress host key checking which is a VERY bad security practice as it opens you up to man-in-the-middle attacks.  If you are in a trusted environment, then I suppose you could use the trick in that article with just `ssh` first so that the host is "trusted" then use PowerShell remoting over SSH.

**Comment by thenecroscope** [comment]
Thanks again for your response. After reading the article that you referred to and also this one:
https://serverfault.com/questions/132970/can-i-automatically-add-a-new-host-to-known-hosts

I think I can achieve what I need to do by using the below 2 additional lines of code in my pwsh script:

 ssh-keygen -R [ip_address] (removes entry from the known_hosts file)
 ssh-keyscan -H [ip_address] >> ~/.ssh/known_hosts (adds an entry to known hosts file)

 invoke-command -hostname (Connect to the host without prompting for the fingerprint)

This should resolve my automated deployment issue, I will test it shortly...

Perhaps a force command to bypass the 2 other steps would be good option? Not sure. I guess see how much interest there is in this post.

Thanks again Steve,
Steve

**Comment by thenecroscope** [comment]
OK, that does not work, running 
  ssh-keygen -R 127.0.0.1 

Gives the following warning:
"Updating known_hosts is not supported in Windows yet."

Just have to use another pwsh command instead to remove the details from the known_hosts file.

**Comment by JustinGrote** [comment]
For others coming here from google, here's a function to pre-trust a host that works cross-platform.

https://gist.github.com/JustinGrote/fd09df8e7ef2018dced73c22cfa870d2

Since we can do this anyways, don't see why we don't make this "easier" by allowing -force to override the checking (like we allow for removing all files of a filesystem, not necessarily a good idea but trusts the user to know what they are doing if they use -force)
