### ISSUE TITLE
Test-ModuleManifest needs specific error messages

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6683]
Follow-up from #6676:

A single catch-all error is currently reported for problems relating to a module manifest's nonempty `RootModule` entry:

* ~~The `RootModule` entry has no filename extension~~ _Update_: specifying `.psm1` should _not_ be a requirement - see #8388
* It does have extension `.psm1`, but the referenced file doesn't exist.
* ~~The `*.psd1` file is not located in a folder named for its base name (e.g., `test.psd1` must be inside a folder named `test`)~~ _Update_: Such a test isn't actually being performed - see #8391

The unhelpful current error message:

>    Test-ModuleManifest : The module manifest 'foo.psd1' could not be processed because it is not a valid PowerShell module manifest file. Remove the elements that are not permitted: /path/to/foo.psd1

It's probably worth checking if all error scenarios have specific, helpful error messages.

Additionally, the behavior regarding requiring the extension to be specified may have changed compared to Windows PowerShell.

Environment data
----------------

```powershell
PowerShell Core v6.0.2 on macOS 10.13.4
PowerShell Core v6.0.2 on Ubuntu 16.04.4 LTS
PowerShell Core v6.0.2 on Microsoft Windows 10 Pro (64-bit; Version 1709, OS Build: 16299.371)
```

**Comment by Persistent13** [comment]
@SteveL-MSFT @mklement0 I'd like to tackle this if there is no prior work in progress.

**Comment by SteveL-MSFT** [comment]
@Persistent13 consider it yours!  Thanks!

**Comment by jzabroski** [comment]
@Persistent13 
Just to repeat what I said in #6818 :

This block of code in the PowerShell engine needs to be removed or refactored before you can 100% eliminate any bugs in Test-ModuleManifest.

https://github.com/PowerShell/PowerShell/blob/79f21b41de0de9b2f68a19ba1fdef0b98f3fb1cb/src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs#L345-L352

The problem is that, at least 3 years ago (per Blame), an engineer added a caching service to avoid re-loading modules that have already been seen in the same session.  This caching service is vulnerable to attack, as explained by me and summarized in #6818

**Comment by Persistent13** [comment]
@jzabroski That's for bringing that to may attention! I'll see what I can do about it.

**Comment by mklement0** [comment]
@Persistent13: Please also note the updates to my initial post, which now indicate dependencies on other issues.
