### ISSUE TITLE
The FileSystem provider does not reliably report invalid wildcard patterns

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6733]
See also: #12168

Note: This is an obscure edge case. 

~~For the most part, malformed wildcard patterns are _quietly ignored_ and fall back to _literal_ treatment (e.g., `Get-Item a].txt` matches a file literally named `a].txt`) - that inconsistency could be considered problematic in itself, however.~~

_Update: A pattern such as `a].txt` is actually valid, because the `]` is not special unless preceded by `[`. However, patterns such as `a[].txt` and `a[.txt` and `a[foo.txt` are invalid, and the problem is that they are not consistently reported as such. The rest of this post has been revised accordingly._

When an invalid wildcard pattern - e.g., one that ends in `[]`  before the filename extension - is passed to `Get-Item` or `Get-ChildItem`, the error that _should_ occur occurs _only_ if at least two files exists that have the same matching prefix (the exact logic is not clear to me).

(@BrucePay states that the source of the error is the FileSystem provider itself, not the cmdlets mentioned.)

Steps to reproduce
------------------

```powershell
# Assume that no `tmp*.txt` files exist.
Get-Item tmp[].txt
'---'
$null = New-Item -Force tmp.txt; Get-Item tmp[].txt
```

Expected behavior
-----------------

```none
Get-Item : Cannot retrieve the dynamic parameters for the cmdlet. 
The specified wildcard character pattern is not valid: tmp[].txt
---
Get-Item : Cannot retrieve the dynamic parameters for the cmdlet. 
The specified wildcard character pattern is not valid: tmp[].txt
```

That is, two instances of the same `The specified wildcard character pattern is not valid` error should occur, irrespective of whether any `tmp*.txt` files exist or not.

Actual behavior
---------------

```none
---
Get-Item : Cannot retrieve the dynamic parameters for the cmdlet. 
The specified wildcard character pattern is not valid: tmp[].txt
```

That is, in the absence of any `tmp*.txt` files, the invalid wildcard expression was not reported as invalid.

Environment data
----------------

Originally reported for 6.0.2, updated for:

```powershell
PowerShell Core v7.0.0
```

**Comment by BrucePay** [comment]
@mklement0  Just FYI, there is a single wildcard library that is used by everything handling wildcards so the behaviour will be the same everywhere. As a consequence, there is no need to report `-like` as a separate case. 

WRT your first issue, the character ']' is only special if preceded by '[' which is fine and by design. Regular expressions behave the same way
```
PS[1] (351) > "abc]def" -match "abc]"
True
PS[1] (353) > "abc]def" -like "abc]*"
True
```
Similarly, empty character classes are (and should be) an error both in wildcards and in regular expressions:
```
PS[1] (354) > "abc]def" -like "abc[]*"
The specified wildcard character pattern is not valid: abc[]*
At line:1 char:1
+ "abc]def" -like "abc[]*"
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordExcepti
   on
    + FullyQualifiedErrorId : RuntimeException

PS[1] (355) > "abc]def" -match "abc[]"
parsing "abc[]" - Unterminated [] set.
At line:1 char:1
+ "abc]def" -match "abc[]"
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException
```

The patterns are well-formed but invalid.

> As with other malformed wildcard patterns

What other malformed wildcard patterns? The only other wildcard metacharacters are * and ? which,  tautologically, cannot be malformed.

**Comment by mklement0** [comment]
>  a single wildcard library that is used by everything handling wildcards so the behaviour will be the same everywhere.

That's good to know.
(A notable exception is the `FileSystem` provider's  `-Filter` parameter.)

> What other malformed wildcard patterns? 

I meant any use of wildcard metacharacters that do not participate in a valid expression.

As you point out, `*` and `?`, due to their being single-character constructs, are by definition valid, and `]` without a preceding `]` is treated as a literal.

That leaves us with `[`  variations: any `[`-initiated construct that is either immediately followed by `]` or has no closing `]` is invalid; to give a few examples, all of which fail with `The specified wildcard character pattern is not valid:`

```powershell
'a' -like 'a[]' 
'a' -like 'a[' 
'a' -like 'a[whatever' 
```

Note, however,  that while these patterns cause errors with `-like`, they  do _not_ do so (unconditionally) with `Get-Item -Path` / `Get-ChildItem -Path`.

**For instance, `Get-Item a[.txt` and `Get-Item a[].txt` do not  _generally_ fail, despite the patterns being invalid - and, as it turns out, that's the true problem here.**

(Contrast this with my original example, `Get-Item a].txt`, in which, based on your explanation, `a].txt` is rightfully considered a _literal_ name and matched accordingly).

**Comment by mklement0** [comment]
@BrucePay: 

I've revised the original post to reflect the new understanding.
Unless you see a flaw in my reasoning, please re-label this issue as a bug.

**Comment by BrucePay** [comment]
> I'm curious what you mean by well-formed in this context, given that these patterns result in a syntax error.

No - they result in a `WildcardPatternException` which is documented as "Thrown when a wildcard pattern is invalid."

**Comment by BrucePay** [comment]
> For instance, Get-Item a[.txt and Get-Item a[].txt do not generally fail, despite the patterns being invalid - and, as it turns out, that's the true problem here.

For the core cmdlets, wildcard processing is handled by the underlying providers. Providers are funny beasts because they try to use the much faster native globbing capabilities of the underlying store (e.g. on Windows, where the files system API directly understands '*'). However these native capabilities don't match our wildcards so there are inconsistencies. Also quoting in the file system provider is fiercely broken - so much so that we added `-Literalpath` in V2 as a workaround for these issues after giving up on trying to fix the providers (ok - and probably concerns about breaking changes.)   So in summary, it's a problem with the filesystem provider, not the cmdlets.  Perhaps the bug should be re-titled "The Filesystem provider does not reliably report invalid wildcard patterns." or some such. And while actually fixing the existing provider's general behaviour seems unlikely but it should be possible to make it error out consistently (though that is a breaking change.) Out of curiosity - have you seen similar inconsistencies in the other providers e.g. the registry ?

Anyway, if you'll update the title (and description?) , I'll mark it appropriately. Thanks.

> So, to return to the question, what does well-formed mean in this context?

Syntactically valid but semantically useless.

**Comment by mklement0** [comment]
As for the change being breaking:

I don't think that's too much of a concern, because something like `Get-Item tmp[].txt` never did anything _useful_: When it doesn't complain about the invalid pattern, it just fails quietly - it doesn't even match a file _literally_ named `tmp[].txt`.

**Comment by SteveL-MSFT** [comment]
The topic of a square bracket in filenames and paths keeps coming up.  I'm wondering if the following proposal makes sense:

1. if the path exists, then use it before analyzing for any wildcard characters
2. if the path contains invalid wildcard characters, treat as literal rather than returning an error about invalid wildcards
3. otherwise, current behavior

**Comment by vexx32** [comment]
Yeah, I think that makes the most sense, @SteveL-MSFT.

**Comment by mklement0** [comment]
Please see the discussion in https://github.com/PowerShell/PowerShell/issues/12168#issuecomment-604383872
