### ISSUE TITLE
Need port Clear-RecycleBin cmdlet

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#6778]
We need port Clear-RecycleBin` cmdlet.

We already have Clear-RecycleBin code for Windows but we should fix issue #6743.
On Linux and MacOs we should implement the cmdlet.

Related links from Electron
- for MacOs https://github.com/aichingm/electron/blob/893fc2cd539cb4ccef01833a1209696e448df8d9/atom/common/platform_util_mac.mm#L155
- for Linux https://github.com/aichingm/electron/blob/893fc2cd539cb4ccef01833a1209696e448df8d9/atom/common/platform_util_linux.cc#L91

MacOs API https://developer.apple.com/documentation/foundation/nsfilemanager/1414306-trashitematurl?language=objc

From @mklement:
> However, the Cocoa Foundation framework only supports _moving an item_ to the trash, it doesn't support _emptying_ the trash.

>Hence my suggestion to [use command-line utility `osascript` with a piece of AppleScript](https://github.com/PowerShell/PowerShell/issues/6743#issuecomment-385289473) for simplicity.

>We _could_ do it in-process, because you can [call AppleScript from Cocoa too](https://stackoverflow.com/a/5334535/45375), but I'm not sure it's worth the effort - unless it's trivial to call Cocoa from .NET Core - I have not looked into it.

**Comment by johncwelch** [comment]
So a couple things. The finder supports directly emptying the trash. Single command: tell application "finder" to empty. so a call to osascript -e works there

Since the cocoa frameworks allow moving to trash easily, i'd use them, as using osascript -e for that gets a little weird since you have to have a file object which you then use in: tell application "finder" to move <thing> to trash. You can play some games with posix file et al, but any time the frameworks will do it, that's the better way to go.
