### ISSUE TITLE
Remove webcmdlet tests validating `http_proxy` and `https_proxy` env vars

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#6804]
Currently, we have tests specifically validating env vars for defining http and https proxies.  However, these env vars are simply a side effect of corefx using libcurl on non-Windows and not something explicitly supported by corefx nor the webcmdlets.  We should remove these tests as we're not testing libcurl directly.

**Comment by iSazonov** [comment]
I am full agree that this env variables are only for `curl`. Current .Net Core 2.1 socket based http client don't use `curl` so we can safely remove the tests.

**Comment by markekraus** [comment]
hmmm @iSazonov and @SteveL-MSFT have a look at  #3112

This missed my radar because it was not labeled. But After considering it... I'm on board with supporting these directly in the Web Cmdlets code.

I think it _may_ be surprising that these env vars are suddenly ignored on Linux. I'm not sure if these env vars were ever documented with PowerShell 6.0.0. But perhaps in the 6.1.0 documentation we should call this out as a breaking change with the workaround of `-Proxy $env:http_proxy` or `$PSDefaultParameterValues["invoke-webrequest:proxy"] = $env:http_proxy`. At least until we consider adding support or not.

**Comment by iSazonov** [comment]
Thanks for catching this!
Given that users can directly use dotnet `HttpClient`, I guess we should not focus on it at all because `HttpClient` no longer use `curl`. Best to open a feature request in dotnet repo. We can consider this as a _regression_ in dotnet.

**Comment by markekraus** [comment]
@iSazonov 

>  I guess we should not focus on it at all because HttpClient no longer use curl.

Except that there is an ask to support it generally on both Windows and Linux. I will consider that request, but not in the 6.1.0 time frame.

**Comment by SteveL-MSFT** [comment]
@markekraus forgot I opened that a long time back :)  I don't believe we ever ended up documenting these env vars in PowerShell-Docs.  We can just leave the tests as they are for now particularly if there's interest to adding formal support in the future.
