### ISSUE TITLE
Eventually make PowerShell Core the default on Windows

### ISSUE THREAD

**Issue by JVimes** [PowerShell/PowerShell#6805]
Once PowerShell Core is mature enough, suggest making it the default shell on Windows. Otherwise it'll never get much adoption among Windows users and many developers.

I can't send someone a script or command, but have to say, "it'll probably work, but if it doesn't you have to install the _other_ PowerShell..."

To work towards this, **everyone please up-vote the [UserVoice suggestion](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/34191670-merge-windows-powershell-and-powershell-core)**.

**Comment by iSazonov** [comment]
It is impossible today because we still don't port about 40% core cmdlets and many modules are also still not ported. Community should press product (MSFT) teams to get them.

**Comment by JVimes** [comment]
Do you mean porting to PowerShell Core, or from it? What's a good way to press the product teams? Thanks @iSazonov

**Comment by iSazonov** [comment]
Porting to PowerShell Core.

You could use UserVoice to ping product teams and vote.

**Comment by JVimes** [comment]
Thanks, @iSazonov. Linked to the UserVoice post in edit, above.

**Comment by iSazonov** [comment]
@JVimes Also you could look https://github.com/PowerShell/WindowsPowerShellCompatibilityPack - it is expected that this will improve compatibility.

**Comment by bergmeister** [comment]
At psconf.eu it was also mentioned that the community could compile PowerShell 6 against the full .net framework to re-enable the disabled cmdlets but there is no interest from the MSFT side on this since .Net Core is the future. At the conference a demo of 'rModule' was given (which is not released yet) that will enable calling e.g. some CIM cmdlets in PowerShell Core (the module works by using implicit remoting)

**Comment by iSazonov** [comment]
Currently we use more and more possibilities of .Net Core and compile against .Net Framework can be difficult.
