### ISSUE TITLE
Strange behavior of the function

### ISSUE THREAD

**Issue by eosfor** [PowerShell/PowerShell#6814]
Function returns nothing but should return an empty list

![image](https://user-images.githubusercontent.com/9363027/39588003-8860841a-4f03-11e8-80f9-df89134b437b.png)

![image](https://user-images.githubusercontent.com/9363027/39588082-b2617530-4f03-11e8-892c-53529c3f027a.png)

**Comment by mklement0** [comment]
By default, function outputs are _enumerated_ if they are collections, and enumerating an empty list yields "nothing" (more precisely, a special "null collection" value,  `[System.Management.Automation.Internal.AutomationNull]::Value`).

In order to output your list as-is, as a _single object_, wrap it in an auxiliary array:

```powershell
function foo { 
    $ret = [System.Collections.Generic.List[long]]::new()
    , $ret  # construct a single-element wrapper array around the list
}

$k = foo
$k.GetType().Name
```

The above yields ``List`1``, proving that the list was returned.
The aux. wrapper array was enumerated, outputting just the list.

Do note that the conceptually cleaner approach would be to use `Write-Output -NoEnumerate`, but `Write-Output` is currently broken - see #5955 

```powershell
function foo { 
    $ret = [System.Collections.Generic.List[long]]::new()
    # This SHOULD work, but is currently BROKEN - see #5955 
    Write-Output -NoEnumerate $ret
}
```

As of PowerShell Core v6.0.2, the above yields an empty `[psobject[]]` array in lieu of the list.

**Comment by eosfor** [comment]
Hm, ok, seems reasonable. But to me using either one is kind of unexpected. I'd prefer it to return a value, even it is is an empty collection.

**Comment by mklement0** [comment]
@eosfor:

Your being surprised is understandable if you're used to function semantics from other languages, but in PowerShell functions integrate tightly with the _pipeline_, a salient feature of which is _implicit_ enumeration of collections.

Thus, unlike in other languages, you have to _opt out_ of this automatic enumeration.

Note that _expressions_, by contrast, are not affected:

```powershell
$k = [System.Collections.Generic.List[long]]::new()
$k.GetTyp().Name
```

The above yields ``List`1``; that is, no enumeration was performed.

**Comment by eosfor** [comment]
@mklement0 
Yes, that is true, and i knew that pipeline "unwraps" a collection which comes out of a cmdlet. At the same time i expected that, if i explicitly return something to the pipeline, then i should get it as an output of a function. 

Imagine a situation when we were processing something and adding it to a collection. We didn't know how many elements would fall into it. With PowerShell we can get one of tree:

1. object[] if a collection was not empty
2. single element of, if there was a single element in the collection
3. null if there were no elements

**Comment by eosfor** [comment]
Yes, i agree? i know about this feature. However when you create a collection and expect it to be returned as is, wrapping it into a single-value array is, kind of, counterintuitive, IMHO.

I'd say, the solution you proposed in #5955 is a good idea.
