### ISSUE TITLE
Test-ModuleManifest working sporadically on v6.1.0-preview.2

### ISSUE THREAD

**Issue by larssb** [PowerShell/PowerShell#6818]
If it is a bug report:
- make sure you are able to repro it on the latest released version.  **I'm able to reproduce it in the latest version.**
You can install the latest version from https://github.com/PowerShell/PowerShell/releases
- Search the existing issues. **Tried that. No open issues matched. Allthough this closed one is quite similar #6676**
- Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md). **not related to this issue**
- Refer to the [known issues](https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md). **no known issues matches this one**
- Fill out the following repro template:
--------

Steps to reproduce
------------------

```
PS > pwsh
PS > Test-ModuleManifest -Path /reposDir/MyModule/Builds/BuildOutput/Mymodule/MyModule.psd1 -Verbose
```

N.B. This is a sporadic issue.

- As I have been troubleshooting this I worked on it in the morning. Then when I come home, my laptop hibernating, the exact same command might work again.
- In VS Code I have setup a build task which basically copies the necessary module files, leaving .gitignore, logs and other files I don't want included when publishing the module. If I run the `Test-ModuleManifest` cmdlet against the files that was written via the "build" task. It might fail. However, if I run `Test-ModuleManifest` against the .psd1 file in the root of the repo it might work. And vice versa.
- I have read > https://msdn.microsoft.com/en-us/library/dd878337(v=vs.85).aspx ... 
- I compared my manifest against the manifest of public and solid modules such as Pester and Plaster. I cannot see any issues with my manifest. And! As I've stated, sometimes `Test-ModuleManifest` works on the MyModule.psd1 manifest. Without me chaning anything in the MyModule.psd1 file.
- I've tried to execute `Import-Module` on both the MyModule.psm1 and the MyModule.psd1 files and they successfully import.
- For good meassure here is the manifest of my module. Which `Test-ModuleManifest` sometimes an test successfully and sometimes not.

```
@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'MyModule.psm1'

    # ID used to uniquely identify this module
    GUID = 'c1e187cd-222f-4df6-8238-88f90f0284ff'

    # Version number of this module.
    ModuleVersion = '0.0.12'

    # Author of this module
    Author = 'https://github.com/larssb | https://bengtssondd.it'

    # Company or vendor of this module
    CompanyName = 'Bengtsson Driven Development'

    # Copyright statement for this module
    Copyright = '(C) https://github.com/larssb | https://bengtssondd.it. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'A project containing helper functions and other utilities to make your life programming PowerShell easier.'

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Add-ScheduledTask'
        'get-environmentOS'
        'get-hostname'
        'Get-PSProgramFilesModulesPath'
        'Get-PublicFunctions'
        'Get-xScheduledTask'
        'initialize-log4net'
        'New-ScheduledJob'
        'out-functionHierarchy'
        'Set-xScheduledTask'
        'start-externalSoftware'
        'test-powershellRunMode'
        'import-jsonFile'
        )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Variables to export from this module
    #VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            # Tags = @()

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            # ProjectUri = ''

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = False

            # External dependent modules of this module
            # ExternalModuleDependencies = ''

        }
    }
}
```

Expected behavior
-----------------

That `Test-ModuleManifest` does not throw (as long as you really have a valid manifest file)

Actual behavior
---------------

```
Throws: Test-ModuleManifest : The module manifest 'MyModule' could not be processed because it is not a valid PowerShell module manifest file. Remove the elements that are not permitted: /reposDir/MyModule/Builds/BuildOutput/Mymodule/MyModule.psd1
At line:1 char:1
+ Test-ModuleManifest -Path /MyModule/Builds/BuildOutput/Mymod ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (/MyModule/MyM...d.psd1:String) [Test-ModuleManifest], ArgumentException
+ FullyQualifiedErrorId : Modules_InvalidRootModuleInModuleManifest,Microsoft.PowerShell.Commands.TestModuleManifestCommand
```

Environment data
----------------
OS: MacOS
OS v.: 10.13.5 Beta

```
PS > pwsh
PS > $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Darwin 17.6.0 Darwin Kernel Version 17.6.0: Fri Apr 13 19:57:44 PDT 2018; root:xnu-4570.60.17.0.1~3/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Any help is appreciated. Thank you very much.

**Comment by daxian-dbw** [comment]
This is not a recent regression. It repros in PS Core 6.0.1.

**Comment by daxian-dbw** [comment]
> Test-ModuleManifest : The module manifest 'MyModule.psm1' could not be processed because it is not a valid PowerShell module manifest file.

@larssb I tried your `.psd1` on my machine, and it failed because it `Test-ModuleManifest` cannot find the root module file `MyModule.psm1`. The fact that you observe this failure inconsistently might suggest that the `MyModule.psm1` file is not deployed by the "build" task when `Test-ModuleManifest` runs.

The error message should be improved to say "it is not a valid PowerShell module file or the file cannot be found".

**Comment by larssb** [comment]
Hi @daxian-dbw,

Thank you for troubleshooting and sorry for the late reply. 

Hmm...:
1. The *.psm1 file is included in the build output.

In order to correctly test it don't you have to:
- Have a folder named as the module. So have the "MyModule.psm1" file in a folder named MyModule. And also have the .psd1 file named MyModule.psd1 as well.

And agree any error message improvements, and those can be had, would be great.

Thank you.

**Comment by larssb** [comment]
Any news on this.?

**Comment by marckassay** [comment]
@daxian-dbw, I'm experiencing similar behavior, if not the same as @larssb has mentioned. Currently I'm working on [PowerShellGet #294](https://github.com/PowerShell/PowerShellGet/issues/294) issue for Update-ModuleManifest which uses Test-ModuleManifest internally.

When I'm stepping thru Update-ModuleManifest, I'll introspect the data going into Test-ModuleManifest and it looks good. But the data that it returns is missing or strangely in some cases, reverted to previous values. 

After glancing into [Test-ModuleManifest](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/Modules/TestModuleManifestCommand.cs) source code several times I have a couple of questions.

1. What's the need for checking multiple files in the directory of this cmdlet's Path parameter, while it seems to test just one?  [These comments and if statements.](https://github.com/PowerShell/PowerShell/blob/ef104601727745f357bc95f32d4a43c6df2a54f1/src/System.Management.Automation/engine/Modules/TestModuleManifestCommand.cs#L76)
2. Also, Update-ModuleManifest performs several IO operations and in doing so creates a temp file (with .psd1 extension) in the same directory as the file to be updated. Is this something that should be considered risky when using Test-ModuleManifest?  Because it seems that Test-ModuleManifest is retrieving data perhaps somewhere else in some cases as @larssb and I have noticed.  And risky considering my 1st question.
3. And finally, what's the intention of Import-PowerShellDataFile command?  Should that be used instead of Test-ModuleManifest for accessing data? I see in PowerShellGet source code that Test-ModuleManifest is used to access data for its output.  Which seems weird considering its verb name, 'Test'.

Hopefully that is explained clearly, if not please let me know.

**Comment by jzabroski** [comment]
I believe I have run into this issue on PowerShell v5 and I don't think it's a recent regression. I think it's been buggy since PowerShell v2.

The crux of the problem is the C# code inherits from ModuleCmdletsBase class, which is apparently stateful.

See my bug report in Powershellget here https://github.com/PowerShell/PowerShellGet/issues/321#issuecomment-419614919

Suffice to say, this could be a major security vulnerability.

**Comment by jzabroski** [comment]
How do I test against older versions of PowerShell?  I believe I can 100% reproduce this issue, and that it is not at all "sporadic" in nature.  The issue is that ModuleCmdletBase caches stuff stupidly, and is poorly written and/or doesn't make sense when you're doing local development on a new module.

**Comment by mklement0** [comment]
@daxian-dbw, @larssb: Re improving the error message: please see #6683

**Comment by jzabroski** [comment]
@mklement0 Thank you. I humbly suggest I owe you a beer, for simply doing your job correctly.

**Comment by kilasuit** [comment]
@jzabroski - I may be wrong here but I don't think `The ONLY way to clear your AnalysisCache is to restart PowerShell.exe ` is correct 

`Get-Module -Refresh` should force a module cache update within the same session as per the parameter help included which has been around since v3

**Comment by mklement0** [comment]
@kilasuit, that's good to know, but I think the bigger question here is why caching is in the picture at all; from what I can tell, it shouldn't be, given that you're statically analyzing files, file content, and their relationships, none of which relates to the runtime state.

**Comment by jzabroski** [comment]
@kilasuit I did not know about that.  The idea of "module cache" is not documented _anywhere_.  Plus, to "refresh" 123 modules, it takes 4 seconds on my [middle-of-the-line workstation specs](https://www.userbenchmark.com/UserRun/12649055).

This is some really dumb, obscure, annoying crap.  I literally abandoned all PowerShell development because of this issue.  I was kind enough to put together repros before moving back to my C# world, and the Microsoft team responded to my repro and effectively said, "Hey! Thanks! Why don't you fix our bad code?"  To which I thought, "Oh my god.  Your whole team needs to pause for a week and do a code review, because you have no idea how much work you just asked me to do to _really fix all this mess_, and how unhappy you will be with a commit request that completely deletes half of all the code you wrote over the last 9 years."

**Comment by jzabroski** [comment]
@kilasuit I found [About Windows PowerShell 5.1](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_windows_powershell_5.1?view=powershell-5.1#module-analysis-cache), which explains that the cache is not thread-safe (emphasis mine):

> Starting with WMF 5.1, PowerShell provides control over the file that is used to cache data about a module, such as the commands it exports.
> 
> By default, this cache is stored in the file `${env:LOCALAPPDATA}\Microsoft\Windows\PowerShell\ModuleAnalysisCache`. *The cache is typically read at startup while searching for a command and is written on a background thread sometime after a module is imported.*

This is completely ridiculous if true. Even more so the use of the word "typically".

**Comment by jzabroski** [comment]
@mklement0  It appears @kilasuit  has indirectly led to an interesting workaround you might want to try.

In your PowerShell Profile, you might be able to **disable the cache** (rather than ever clearing it) by doing:
```powershell
$env:PSModuleAnalysisCachePath = 'nul'
```

I can't say for sure this will work, though, as the code I highlighted above in ModuleCmdletBase.cs is clearly incorrect (and the comments above the code don't actually match what the code is doing, at all).

I still think the behavior is rather bad/sub-optimal, since there is definitely analysis that is still being cached. Note in my example below how a WARNING is only emitted the first time:

```powershell
PS C:\WINDOWS\system32> $env:PSModuleAnalysisCachePath = 'nul'
PS C:\WINDOWS\system32> cd c:\source\Infrastructure\SqlClone\
PS C:\WINDOWS\system32> Test-ModuleManifest SqlClone.psd1
WARNING: The module manifest member 'ModuleToProcess' has been deprecated. Use the 'RootModule' member instead.

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0        SqlClone           {Get-ScriptDirectory, Get-SvnRootDirectory}

PS C:\WINDOWS\system32> Test-ModuleManifest SqlClone.psd1

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0        SqlClone           {Get-ScriptDirectory, Get-SvnRootDirectory}
```

**Comment by alexandair** [comment]
'nul'? Maybe $null?

**Comment by jzabroski** [comment]
@alexandair Read the official documentation I linked to, it says to pass 'nul' (weird, i know).

That said, I still had my PowerShell session open, so I have added this additional command sequence to prove that neither way works:

```powershell
PS C:\source\Infrastructure\SqlClone> $env:PSModuleAnalysisCachePath = $null
PS C:\source\Infrastructure\SqlClone> Test-ModuleManifest SqlClone.psd1

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0        SqlClone           {Get-ScriptDirectory, Get-SvnRootDirectory}
```

**Comment by alexandair** [comment]
@jzabroski 
From the doc: "To disable the file cache, set this value to an **invalid** location, for example: `$env:PSModuleAnalysisCachePath = 'nul'`"


It can be even `'foo'`. It doesn't even matter as long as it's not a valid path.

**Comment by jzabroski** [comment]
@alexandair OK, it still doesn't work as described.   Setting the file cache to an invalid location does not completely disable the cache.  It is probably because the cache file is written to on a background thread, and the packing of the cache data structure into a blob of bytes occurs *AFTER* the fact, so disabling the _file cache_ does not disable the _cache_.  Just guessing.  Either way, the code is totally bonkers.

The first steps here in my mind is an engineer at Microsoft should create a flow chart or some kind of architecture diagram to disect how this SHOULD work, since the code is completely crazy and full of micro-optimizations that probably don't add a lot of value for the complexity it adds.

**Comment by kilasuit** [comment]
this is something that has been in since at **least** v3 and is the basis behind being able to do `Module Auto Loading` and is why `$PSModuleAutoLoadingPreference` came in v3 - which is not set to any value by default but IIRC takes `Off` as a value when you set it

In versions prior to v3 you needed to explicitly load modules into the session to be able to even begin to discover them, whereas v3+ you can more easily discover commands in modules in the 3 main PSModulePaths -  Sys32, ProgramFiles, UserHomeFolder

I think this was something that I think @lzybkr had originally done alot of the work on this area originally back in the v2-v3 timeline

`probably don't add a lot of value for the complexity it adds.` - I'll have to disagree on this but that's because it's a feature that I use everyday and since I remember the days prior to the Cache being implemented I can only say that this is a feature that is akin to running items on Ubuntu that searches apt-get for commands that you could install that aren't installed (though this would need to be plumbed into PowerShellGet for feature parity with apt-get)

**Comment by ChrisLGardner** [comment]
So the original issue is that the error reports from `Test-ModuleManifest` aren't very useful, so can we look at improving those? 

The talk about the module cache should probably belong in it's own issue.

**Comment by TheIncorrigible1** [comment]
Annoyingly, I'm experiencing this with Plaster 1.1.3 on Core 6.2.  Loading the same module in PowerShell 5.0 works without issue.

I tried adding

```
Get-Module -ListAvailable -Refresh
Import-Module -Name Plaster -Force
```

in my 6.2 profile, but it doesn't work.  If I enter the commands interactively... magic.

**Comment by jzabroski** [comment]
@TheIncorrigible1  DId you read me notes on this issue?

**Comment by TheIncorrigible1** [comment]
> @jzabroski 
> DId you read me notes on this issue?

Yes, I read your responses, but the only thing that worked for me was using `Get-Module -Refresh`.

**Comment by jzabroski** [comment]
The only way to clear your module analysis cache is to close your pwsh.exe process.  This will terminate the cache, since the cache is in-process and not global to the OS.  I'm not sure why `Get-Module -Refresh` worked for you - are you able to consistently reproduce that behavior?

**Comment by TheIncorrigible1** [comment]
@jzabroski Again, didn't work.  None of the remediation worked except what I noted.  It wasn't consistent that it resolved the issue; I ended up manually changing the call to the cmdlet to use `Import-PowerShellDataFile` instead.

**Comment by jzabroski** [comment]
@TheIncorrigible1 I think I see the nuance - in your case, you've installed a module locally, and you are using `Import-Module YourModule -Force` to clear the old module from the local disk cache (as opposed to memory cache)?  Do I have it right?  I think the pain in the ass part for me is that -Verbose on these commands is not helpful

**Comment by iSazonov** [comment]
@jzabroski Please follow [Code of Conduct](https://github.com/PowerShell/PowerShell/blob/master/CODE_OF_CONDUCT.md) Be respectful.
