### ISSUE TITLE
ConvertTo-Json Honors JsonPropertyAttribute

### ISSUE THREAD

**Issue by adamdriscoll** [PowerShell/PowerShell#6847]
In PowerShell v6, Convert(To\From)-Json uses Newtonsoft.Json. ConvertTo-Json acknowledges JsonIgnoreAttributes but does not honor JsonPropertyAttributes.  have some objects that are decorated with these attributes and serialize differently between ASP.NET and PowerShell. I've had to make a hacked version of ConvertTo-Json to support these attributes. For me, it results in a difference in casing which causes my JavaScript code to fail. 

I propose that the JSON cmdlets honor the JsonPropertyAttributes placed on properties.

**Comment by iSazonov** [comment]
@adamdriscoll Thanks for you report! Please add simple repo steps.

**Comment by adamdriscoll** [comment]
```
PS C:\Program Files\PowerShell\6.0.1> Add-Type 'public class MyClass { [Newtonsoft.Json.JsonProperty("myProperty")]publi
c string MyProperty {get;set;} }' -ReferencedAssemblies 'Newtonsoft.Json'
WARNING: (1) : Assuming assembly reference 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Newtonsoft.Json' matches identity 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy

(1) : >>> public class MyClass { [Newtonsoft.Json.JsonProperty("myProperty")]public string MyProperty {get;set;} }

WARNING: (1) : Assuming assembly reference 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Newtonsoft.Json' matches identity 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy

(1) : >>> public class MyClass { [Newtonsoft.Json.JsonProperty("myProperty")]public string MyProperty {get;set;} }

PS C:\Program Files\PowerShell\6.0.1> $Class = New-Object MyClass
PS C:\Program Files\PowerShell\6.0.1> $Class | ConvertTo-Json
{
  "MyProperty": null
}
PS C:\Program Files\PowerShell\6.0.1> [Newtonsoft.Json.JsonConvert]::SerializeObject($Class)
{"myProperty":null}
```

**Comment by iSazonov** [comment]
@markekraus Could you please comment the Issue?

**Comment by markekraus** [comment]
It looks like instead of letting Newtonsoft  handle the serialization, we hit this code path

https://github.com/PowerShell/PowerShell/blob/0f036d9939d2d6ba4430baf73dc3c11ebd46e241/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertToJsonCommand.cs#L398

Which essentially converts the object to a dictionary and striping it of the any useful JSON attributes.

At this point, I'm already convinced the right direction for JSON is to just wrap Newtonsoft and stop using our own logic as well as make some of the newtonsoft features available. This probably needs to be new cmdlets. Because pretty much everything we do at this point is a breaking change in the current cmdlets. 

As for fixing this in the current cmdlets... I have some (bad) ideas such as re-inventing the wheel to inspect the attributes on the object properties.. Maybe before we make the object ditcionary, we test the object for Json related attributes and pass the object directly to NewtonSoft... but that has depth issues.

**Comment by iSazonov** [comment]
@markekraus Thanks!

>serialize differently between ASP.NET and PowerShell

What does ASP.NET use? Newtonsoft?

**Comment by adamdriscoll** [comment]
Yeah, it uses NewtonSoft.

**Comment by felixfbecker** [comment]
Using NewtonSoft directly would be awesome because almost all API C# clients use it to decorate their attributes - in C#/PowerShell they will be PascalCased, but for JSON they usually need to be lowercased. So to support proper interop with APIs honoring `JsonPropertyAttribute` is crucial.

**Comment by iSazonov** [comment]
@markekraus What scenarios we break if we move to Newton serialization? 
Will this affect only Convert(To\From)-Json cmdlets?
It would be great if you wrote RFC. 
This will allow us to move.
We could enter a new parameter to support backward compatibility  and not create new cmdlets.
