### ISSUE TITLE
Cleanup lbucrul and openssl installation from brew formula, mac build scripts, and bootstrap

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#6848]
since libcurl+ openssl + gssapi are no longer needed, we can remove these from the brew formula and the bootstraps. The brew formula can't be changed until we ship with .NET Core 2.1.

**Comment by vitorgalvao** [comment]
Homebrew maintainer here. [We’ve removed the OpenSSL 1.0 formula because it’s EOL](https://github.com/Homebrew/homebrew-core/pull/46876). [That broke the `powershell` cask](https://github.com/Homebrew/homebrew-cask/issues/78085#issuecomment-594682198) (which is what I assume you’re referring to).

[I was pointed to this issue](https://github.com/Homebrew/homebrew-cask/issues/78085#issuecomment-594682198) which [led to a PR to remove the dependency](https://github.com/Homebrew/homebrew-cask/pull/78101).

Is our understanding correct that we can remove the `openssl` dependency from the cask?

**Comment by iSazonov** [comment]
@TravisEz13 Could you please comment?

**Comment by TravisEz13** [comment]
openssl is only need for libmi, which is broken on macos.  It's okay to remove it.
