### ISSUE TITLE
Add curly brackets to the ForEach method error message.

### ISSUE THREAD

**Issue by sethvs** [PowerShell/PowerShell#6936]
When calling `Where` method of the array without parameters, we get following error message:
```
$array = 1, 2, 3
$array.Where()
```
```
Cannot find an overload for ".Where({ expression } [, mode [, numberToReturn]])" and the argument count: "0".
At line:1 char:1
+ $ps.Where()
+ ~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodException
+ FullyQualifiedErrorId : MethodCountCouldNotFindBest
```

When we do the same for `ForEach` method, we get:

```
$array.ForEach()
```

```
Cannot find an overload for ".ForEach(expression [, arguments...])" and the argument count: "0".
At line:1 char:1
+ $ps.ForEach()
+ ~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodException
+ FullyQualifiedErrorId : MethodCountCouldNotFindBest
```

I believe, for consistency we should encase `expression` in curly brackets in `ForEach`, as it is in `Where` method error message.

**Comment by BrucePay** [comment]
@sethvs There aren't braces around `expression` in the `ForEach()`  message because, unlike `Where()` which requires a scriptblock, `ForEach()` can also take a string as in `(ls).foreach("length")`. In this example, `ForEach()`will iterate over the collection of `FileInfo` objects, returning the value of the `length` property.

**Comment by sethvs** [comment]
Thanks for clarification.
It seems reasonable.
Closing.
