### ISSUE TITLE
Search verb description is confusing

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#6999]
In PowerShell 6 we've finally gotten descriptions with our verbs to help us understand when to use them, but sometimes, they're just not helpful:

```
PS C:\> Get-Verb Get, Find, Select, Search

Verb   AliasPrefix Group  Description
----   ----------- -----  -----------
Find   fd          Common Looks for an object in a container that is unknown, implied, optional, or specified
Get    g           Common Specifies an action that retrieves a resource
Search sr          Common Creates a reference to a resource in a container
Select sc          Common Locates a resource in a container
```

What's does "creates a reference" mean? I know that description has been used before -- but it was confusing then, too.

Shouldn't `Search` be something more like: "Searches a container for an object"?

While we are at it:

* Shouldn't the description for `Get` be just "Retrieves a resource" to maintain consistent language?
* Shouldn't the description for `Select` be about reshaping objects, or selecting _part_ of an object? I'm not aware of any use of the verb "Select" to locate things _in containers_ -- it's used to pick a few properties from an object, or pick a few nodes from an xml document, or pick a few strings from a file ... etc.

**Comment by dragonwolf83** [comment]
`Select-String` does fit the description of locating a resource in a container considering it uses wildcard and regex to "locate". I guess you could extend that into `Select-Object` because it uses wildcards to "locate" properties. However, I agree the definition is incomplete because it is primarily used to reshape objects and choose a subset of properties.

`Search` and `Find` are both very confusing and too similar in verbs. I would even argue one of those verbs is better than `Select-String`.

Too many similar verbs and not enough clarity and examples on why they differ is the biggest problem with most of the verbs.

**Comment by Jaykul** [comment]
It's worth noting that the original (PowerShell 1 era) verb list specifically said that "Get" replaced both "Search" and "Find" 😉  but the description for `Search` in particular is just confusing.

And yes, I think `Select-String` should have been called `Find-String` ... as evidenced by the fact that it's main use parallels the old `find` command.

The key problem I have with the description of `Select` is that this verb is not for locating things. If it were for locating, then surely it would be redundant with `Search`, `Find`, and `Get` 🙁 In fact, it also generally operates on a pipeline, not a container ...  and it's best use is for reshaping, as people are used to using it in many query languages.

**Comment by Jaykul** [comment]
Can we _please_ change this description to "Looks for a resource in a specific container" instead of "creates a reference..."

It doesn't create references.
