### ISSUE TITLE
Get-ChildItem c: throws an error.

### ISSUE THREAD

**Issue by sethvs** [PowerShell/PowerShell#7032]
When using Get-ChildItem with drive name without a backslash, i.e. `c:` the error is thrown.

Steps to reproduce
------------------

```powershell
Get-ChildItem c:
```

Expected behavior
-----------------

```none
Lists the content of current directory on the specified drive.
```

Actual behavior
---------------

```none
Get-ChildItem : Cannot find path 'C:\C:\' because it does not exist.
At line:1 char:1
+ Get-ChildItem c:
+ ~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\C:\:String) [Get-ChildItem], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.701
PSEdition                      Core
GitCommitId                    v6.1.0-preview.701
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
It is a regression after 6.0.1 - we should find the bad commit before fix.

**Comment by sethvs** [comment]
Can it be #6774 ?

**Comment by sethvs** [comment]
@MaximoTrinidad  Yes, on 6.1.0-Preview.2 it works.

**Comment by iSazonov** [comment]
@MaximoTrinidad Could you please help to find the post Preview2 broken commit? We could use saved artifacts from CI Appveyor.

**Comment by sethvs** [comment]
@iSazonov I believe it is b101d523346abebc2d2a9ef6e230f544d7c11eb7

**Comment by iSazonov** [comment]
PR with regression is #6774

**Comment by mcbobke** [comment]
Thank you for informing me of this issue. I will investigate it as time permits.

**Comment by mcbobke** [comment]
In #6774 we resolved the issue with a new check in `SessionStateLocationAPIs.cs` that determines if the path given to `Set-Location` is a drive name terminated by a colon. If so, it changes the desired path to be the new drive's current working directory. Would it be appropriate for the same path transformation to occur in `SessionStateContainer.cs`?

Because the current working directory of the specified drive is not used in place of the given path, [line 1643 of `SessionStateContainer.cs`](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/SessionStateContainer.cs#L1643) will determine that the absolute path is `C:\C:\` incorrectly. Another concern is that if the `-Name` parameter is specified, the same issue will occur. It might make more sense to transform the path at a higher level to avoid the same path transformation actions occurring in two different places.

**Comment by iSazonov** [comment]
I think the code path should be the same for all providers - compare `dir c:`,`dir alias:`, `dir hklm:`.
