### ISSUE TITLE
test-path -pathtype seems to fail in strange ways over the pipe

### ISSUE THREAD

**Issue by jszabo98** [PowerShell/PowerShell#7044]
test-path -pathtype seems to fail in strange ways over the pipe.  "$_  | test-path -pathtype container" works ok.  I actually first noticed this in writing a script with a process block.

Steps to reproduce
------------------

```powershell
mkdir foo\foo2\foo3
ls -r foo | foreach { test-path $_ -pathtype container }
```

Expected behavior
-----------------

```none
True
True
```

Actual behavior
---------------

```none
True
False
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by BrucePay** [comment]
The `-Path` parameter on `Test-Path` takes a string as it's argument and the `.ToString()` on a `DirectoryInfo` is the _base_ name of the directory. This means that you are testing the paths "foo2" and "foo3". "foo2" exists in the current directory and so `Test-Path` returns true but "foo3" doesn't exist in the current directory and so returns false. If you use the `FullName` property instead:
```powershell
PSCore >  ls -rec foo | foreach { test-path $_.fullname -PathType Container }
True
True
```
you will get the result you expect. Alternatively you can just pipe directly into `Test-Path` and it will work:
```powershell
PSCore (1:135) >  ls -rec foo | test-path -PathType Container
True
True
```
This is because the parameter binder binds to `PSPath` on the input object which is the full path to the  target.

**Comment by jszabo98** [comment]
Thanks.  I should have caught what string $_ was becoming.  I think it tends to throw people though that the get-childitem object only becomes the basename when converted to a string.
