### ISSUE TITLE
PSCore-Preview.3 - Instructions missing to install PowerShell in Ubuntu 18.04

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#7063]
Steps to reproduce
------------------
Following current documentation link Ubuntu 18.04 from the landing page in the "Instruction" section:
https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-linux?view=powershell-6#ubuntu-1804 

```powershell

```

Expected behavior
-----------------
To show PowerShell Core installation instructions for Ubuntu 18.04.
```none

```

Actual behavior
---------------
Information is missing.
```none

```

Environment data
----------------

```powershell
> $PSVersionTable

```
![docmissing ubun1804_2018-06-13_19-44-23](https://user-images.githubusercontent.com/19892435/41384164-44adb2ba-6f42-11e8-91e5-81c43f8c7da2.jpg)

**Comment by MaximoTrinidad** [comment]
Please include the Ubuntu 18.04 repository information.

I try the following but didn't work.
```
curl -o /etc/apt/sources.list.d/microsoft.list https://packages.microsoft.com/config/ubuntu/18.04/prod.list

```

**Comment by MaximoTrinidad** [comment]
Guys! Is the documentation also only be update when the product has reached GA?

**Comment by MaximoTrinidad** [comment]
Hi @iSazonov 

I will open the issue in PowerShell-Docs.

Thanks!

**Comment by alexandair** [comment]
@iSazonov I think PowerShell-Docs repo should contain only GA-related information. Ubuntu 18.04 is not supported for PowerShell Core 6.0.2.

**Comment by markekraus** [comment]
@alexandair PowerShell-Docs has a branch for the 6.1.0 release where these vNext issues can be addressed. https://github.com/PowerShell/PowerShell-Docs/tree/release-ps61

**Comment by MaximoTrinidad** [comment]
I would expect some type of documentation to be provided for the Preview releases instead of doing trial and error figured out yourself kind-of-thing.

If is not documented in the Microsoft Docs, then why not create another doc section on Github for updated Preview installation instructions?

:)

**Comment by kilasuit** [comment]
as per @markekraus point above this is already in place with v6.1 branch of the docs with the benefit that when 6.1 GA's then the docs are already there

**Comment by markekraus** [comment]
IMO, preview releases are intended for a technical audience that should not require specific documentation on installation unless there is some major change to the installation process. That kind of information should be present in the release notes for the RC/Preview release. 

The 6.1.0-preview.3 release page provides links to deb packages and the installation of deb  packages is pretty straight forward. IMO, There should be a realistic expectation from technical users testing Preview and RC releases that live documentation will reflect the latest GA release, and not the RC and preview releases.

As the information relevant to this issue is [already present in the correct documentation branch](https://github.com/PowerShell/PowerShell-Docs/blob/release-ps61/reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md#ubuntu-1804) in PowerShell-Docs I am closing this issue.
