### ISSUE TITLE
MSI installer doesn't enable remoting even after selecting it

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PowerShell#7118]
Steps to reproduce
------------------
1.  Check the current available endpoints using **Windows PowerShell**
```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.112
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.112
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

# Lists the default endpoints
Get-PSSessionConfiguration | ft Name

Name
----
Microsoft.PowerShell
Microsoft.Powershell.Workflow
Microsoft.PowerShell32
```

2. Install the PS Core 6.1.0-preview 3 using the MSI and select _Enable PowerShell remoting_
![capture](https://user-images.githubusercontent.com/11988952/41616789-b5a58144-73b3-11e8-8eb7-e50de7348376.PNG)

Expected behavior
-----------------
New remoting endpoint(s) are **PRSENT** on the system as done by _Install-PowerShellRemoting.ps1_ script in $PSHome

```powershell

# From Windows PowerShell
Get-PSSessionConfiguration | ft name

Name
----
Microsoft.PowerShell
Microsoft.Powershell.Workflow
Microsoft.PowerShell32
PowerShell.6
PowerShell.6.1.0-preview.3

# From PowerShell Core
Get-PSSessionConfiguration |ft name

Name
----
PowerShell.6
PowerShell.6.1.0-preview.3

```

Actual behavior
---------------
New remoting endpoint(s) are **ABSENT** 

```powershell

# From Windows PowerShell
Get-PSSessionConfiguration | ft name

Name
----
Microsoft.PowerShell
Microsoft.Powershell.Workflow
Microsoft.PowerShell32

# From PowerShell Core
Get-PSSessionConfiguration 
```

**Comment by bergmeister** [comment]
Due to https://github.com/PowerShell/PowerShell/issues/5998 it was decided to not make the installer fail if `Enable-PSRemoting` fails, which can happen for various (see issue for details). Can you try to repro and possibly make the issue more detailed/useful by making `Enable-PSRemoting` (or how it is called) the centre of this issue since I believe it is not a problem of the installer itself

**Comment by HemantMahawar** [comment]
I don't know how to make it more specific. I tried running the following command from **elevated Windows PowerShell** to mimic elevated installer action and it succeeded

```powershell
PS C:\WINDOWS\system32> & 'C:\Program Files\PowerShell\6-preview\pwsh.exe' -noprofile -executionpolicy bypass -command 'Enable-PSRemoting'
```
Could it be because **Enable-PSRemoting** on PowerShell Core takes too long - 76 sec

```powershell
PS C:\WINDOWS\system32> measure-command {& 'C:\Program Files\PowerShell\6-preview\pwsh.exe' -noprofile -executionpolicy bypass -command 'Enable-PSRemoting'}


Days              : 0
Hours             : 0
Minutes           : 1
Seconds           : 16
Milliseconds      : 558
Ticks             : 765582470
TotalDays         : 0.000886090821759259
TotalHours        : 0.0212661797222222
TotalMinutes      : 1.27597078333333
TotalSeconds      : 76.558247
TotalMilliseconds : 76558.247
```

**Comment by HemantMahawar** [comment]
@bergmeister Is there anything in MSI log that I should look for to help diagnose this issue. I generated one using ```msiexec /L*V foo.log /i PowerShell-6.1.0-preview.3-win-x64.msi``` but not sure what to look inside it to know is the command ```Enable-PSRemoting``` is even called or not

**Comment by bergmeister** [comment]
@HemantMahawar OK. Let's debug it one by one:
- For inspecting the WiX Log, look for custom actions/properties like `EnablePSRemoting` and `ENABLE_PSREMOTING`. In general I suggest to use  `/L*VX` to get as much logging info as possible but the options that you specified are probably sufficient.
- If you suspect that the wiring up of the checkbox is broken, then build a custom installer that modifies [this](https://github.com/PowerShell/PowerShell/blob/master/assets/Product.wxs#L66) line to create a dummy file so that you know that the checkbox is wired up correctly and you could also pipe/redirect the output of `Enable-PSRremoting` to a log file that you can then inspect afterwards. I case you wonder: `&quot` is just the WiX escape character for a double quote.
- Maybe the time issue is a separate, independent issue. I did some quick research and it seems that the custom action that we use has a non-configurable 1 minute timeout: https://github.com/wixtoolset/issues/issues/601/

**Comment by HemantMahawar** [comment]
@bergmeister I tried your first suggestion w.r.t searching for ```EnablePSRemoting``` and ```ENABLE_PSREMOTING``` in the WiX log (I ran with ```/L*VX``` as you suggested). And below are the messages for **EnablePSRemoting**

MSI (s) (BC:74) [15:41:54:034]: Doing action: SetEnablePSRemoting

MSI (s) (BC:74) [15:41:54:034]: Note: 1: 2205 2:  3: ActionText 

Action 15:41:54: SetEnablePSRemoting. 

Action start 15:41:54: SetEnablePSRemoting.

MSI (s) (BC:74) [15:41:54:036]: PROPERTY CHANGE: Adding EnablePSRemoting property. Its value is '"C:\Program Files\PowerShell\6-preview\pwsh.exe" -NoProfile -ExecutionPolicy Bypass -Command "Enable-PSRemoting"'.

Action ended 15:41:54: SetEnablePSRemoting. Return value 1.

MSI (s) (BC:74) [15:41:54:036]: Skipping action: EnablePSRemoting (condition is false)

MSI (s) (BC:74) [15:41:54:036]: Doing action: SetRegisterManifest

**Comment by SteveL-MSFT** [comment]
@HemantMahawar the log says that `Enable-PSRemoting` was executed, but failed with exit code 1.  My guess is that if you run the equivalent command line in an elevated cmd: "C:\Program Files\PowerShell\6-preview\pwsh.exe" -NoProfile -ExecutionPolicy Bypass -Command "Enable-PSRemoting"

It will tell you why it failed.  Usually it's because some network interface is set to Public.

**Comment by SteveL-MSFT** [comment]
@HemantMahawar is this still an issue?  I don't think we want to use `-SkipNetworkProfileCheck`.

**Comment by nathankascopgr** [comment]
> 

@SteveL-MSFT 
Gearing up to look at deploying this to machines in my environment and want to make sure remoting gets enabled, am I correct in assuming that I will need a separate Enable-PSRemoting -Force -SkipNetworkProfileCheck if I suspect machines have public network interfaces? Or will newer 7.x MSI installs handle this cleanly/silently?

**Comment by SteveL-MSFT** [comment]
@nathankascopgr The checkbox in the MSI (or using the [cmdline option](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2#install-the-msi-package-from-the-command-line)) simply runs `Enable-PSRemoting` without any additional parameters as that is the safest.  If it fails, you'll have to explicitly run with `-Force` or `-SkipNetworkProfileCheck` in the case that you are ok with the system having public network profiles.  That is the intended behavior to be secure by default.   At this point,  I believe this is by-design.
