### ISSUE TITLE
Enable-PSRemoting and Install-PowerShellRemoting.ps1 create version specific endpoints with different names

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PowerShell#7119]
Steps to reproduce
------------------
0. Run **elevated** pwsh.exe

1. Unregister any existing PowerShell Core remoting endpoint
```powershell
Get-PSSessionConfiguration | Unregister-PSSessionConfiguration
```

2. Run _Install-PowerShellRemoting.ps1_ from **$PSHome**
```powershell
& $PSHome\Install-PowerShellRemoting.ps1
```

3. List the remoting endpoints
```powershell
Get-PSSessionConfiguration | ft name
```

4. Unregister any existing PowerShell Core remoting endpoint from step 2
```powershell
Get-PSSessionConfiguration | Unregister-PSSessionConfiguration
```

5. Run _Enable-PSRemoting_ cmdlet
```powershell
Enable-PSRemoting
```

6. List the remoting endpoints
```powershell
Get-PSSessionConfiguration | ft name
```

Expected behavior
-----------------
After steps 3 and 5, the endpoint names should be same:
  - **PowerShell.6**
  - **PowerShell.6.1.0-preview.3**

Actual behavior
---------------
Endpoint names are **different** after steps 3 and 5

**After Step 3**
  - PowerShell.6
  - **PowerShell.6.1.0-preview.3**

**After Step 5**
  - PowerShell.6
  - **PowerShell.v6.1.0-preview.3** (extra 'v' before version number)

**Comment by HemantMahawar** [comment]
FYI .. @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
Thought this was already fixed.  I'll also fix it so that for `Preview` releases, it'll be `PowerShell.6-Preview`.  I also wonder if we need to keep `Install-PowerShellRemoting.ps1` as the only use different from `Enable-PSRemoting` is supporting specifying the location of PowerShell different than the running PowerShell, but I think you can just do:

> pwsh -c enable-psremoting

Need to verify that works on Win10 IoT where you've had to use `Install-PowerShellRemoting.ps1`

**Comment by SteveL-MSFT** [comment]
@iSazonov brought up a good issue, currently if you run `Enable-PSRemoting` or `Install-PowerShellRemoting.ps1` we setup the generic endpoint `PowerShell.6` as well as the version specific endpoint `PowerShell.v6.1.0-blah` (using `Enable-PSRemoting`) or `PowerShell.6.1.0-blah` (using `Install-PowerShellRemoting.ps1`).  Intent of this issue was to have `Enable-PSRemoting` and `Install-PowerShellRemoting.ps1` standardize on the non `v` naming of the version specific endpoint to match the generic one.

However, the end result is that every script that wants to use the version specific one needs to apply the same formula:

> "PowerShell." + $PSVersionTable.GitCommitId.ToString().SubString(1)

This strips the `v`.  It seems we should simplify this to make it predictable for automation.  Options:

1. Change `PSVersionTable.GitCommitId` to not start with a `v` (then we have to decide whether on `pwsh` start we emit "PowerShell v<GitCommitId>" or just "PowerShell <GitCommitId>"
2. Add a new `ShellName` or `EndpointName` property to PSVersionTable that is exactly the same as the version specific endpoint
3. Update `Install-PowerShellRemoting.ps1` to put back the `v` so it's consistent with GitCommitId but inconsistent with PSVersion

Personally, I don't think we need the `v` at all so I'd go with option 1.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and would prefer to drop the `v` from GitCommitId and have the version specific endpoint match GitCommitId.  @TravisEz13 can you verify that there is no functional/packaging concern with removing the `v`?

**Comment by SteveL-MSFT** [comment]
I talked to @TravisEz13 and he's not aware of any reason the `v` is necessary.  I'll update the PR to standardize on no `v`.
