### ISSUE TITLE
Stringification behavior of FileInfo / Directory instances has changed since v6.0.2

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7132]
How `FileInfo` / `DirectoryInfo` instances stringify implicitly used to depend on the specifics of the `Get-ChildItem` call that emitted them.

Previously, a `Get-ChildItem` command that targeted a directory path only would yield child items that stringified to their mere _name_ rather than to their full path.

This now behaves differently in PowerShell Core v6.1.0-preview.3.

While the new behavior is more predictable and would actually resolve part of #6057, it is a - presumably unintended - breaking change.

Steps to reproduce
------------------

Create a temp. dir `tmpDir` with single file `tmpFile`, then use `Get-ChildItem` to enumerate `tmpDir` and stringify the resulting item:

```powershell
$null > (Join-Path (New-Item -force -Type Directory tmpDir) tmpFile); Get-ChildItem tmpdir | % { "$_" }
```

Expected behavior
-----------------

```none
tmpFile
```

That is, only the file's _name_ is reported.
This is what happened up until at least v6.0.2, and still happens in Windows PowerShell.

Actual behavior
---------------

```none
/Users/jdoe/tmpdir/tmpFile
```

That is, stringification now results in the _full path_.

Environment data
----------------

```powershell
PowerShell Core v6.1.0-preview.3
```

**Comment by iSazonov** [comment]
I think it come from .Net Core 2.0 -> 2.1 update.

```powershell
$a=[io.fileinfo]::new("C:\Windows\explorer.exe")
$a.ToString()
```

**Comment by mklement0** [comment]
@iSazonov:

Probably not, given that the behavior in your examples is no different from the one in Windows PowerShell v2 - v5.1 .

**Comment by iSazonov** [comment]
I can confirm that now we call obj.ToString() for FileInfo objects but I can't find what's changed in code.

**Comment by SeeminglyScience** [comment]
Just ran into this as well.

[Here's the commit in corefx where the ToString behavior was changed](https://github.com/dotnet/corefx/commit/e2cd5a8fc468b63255f91f4f28bccddb3bb31e8f).

[Here's that line specifically](https://github.com/dotnet/corefx/blob/6182c9c53f3931461b228fed963e44c0c16d5c45/src/System.IO.FileSystem/src/System/IO/FileSystemInfo.cs#L108).

**Comment by mklement0** [comment]
@SeeminglyScience:

Thanks, but I don't think that explains it. The only `.ToString()-`relevant change in that commit is to remove the transformation of a path like `c:` (i.e., a drive-letter-only path) to `.` via the now-removed `ShouldReviseDirectoryPathToCurrent()` method, something that the commit message calls a "limited trust holdover".

The fundamental behavior hasn't changed: whatever path you pass in to _construct_ the instance is output by `.ToString()`.

Thus, something on the PowerShell side must have changed:

@iSazonov, when you say "now we call obj.ToString()", can you tell us what we did before, and perhaps point us to the code?

**Comment by iSazonov** [comment]
I don't remember already but seems it is here https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/MshObject.cs#L1244
and in the case we do https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/MshObject.cs#L1332

**Comment by rjmholt** [comment]
Copying some things from the duplicate issue I just closed...

[Looks like .NET is leaning toward WontFix.](https://github.com/dotnet/corefx/issues/38215)

We should:

- Investigate changing LanguagePrimitives so that converting a DirectoryInfo to a string uses Name rather than ToString()
- Investigate investment in @rkeithhill's suggested [Path()] attribute (or a similar parameter processing attribute)
- Update any relevant documentation


More info in https://github.com/dotnet/corefx/issues/38215.

/cc @SteveL-MSFT and @joeyaiello since we should amend changelogs.

Also tagging for @PowerShell/powershell-committee review

**Comment by rjmholt** [comment]
> Thus, something on the PowerShell side must have changed:

.NET team verified a change of theirs broke this

**Comment by rkeithhill** [comment]
> Investigate investment in @rkeithhill's suggested [Path()] attribute (or a similar parameter processing attribute)

This would be awesome and could GREATLY simplify writing advanced functions that require paths.  @oising wrote this version for PSCX back in the day:

https://github.com/Pscx/Pscx/blob/master/Src/Pscx.Core/PscxPathAttribute.cs
https://github.com/Pscx/Pscx/blob/master/Src/Pscx.Core/IO/PscxPathInfo.cs
https://github.com/Pscx/Pscx/blob/master/Src/Pscx.Core/IO/PscxPathInfo.ResolvedPscxPathImpl.cs
https://github.com/Pscx/Pscx/blob/master/Src/Pscx.Core/IO/PscxPathInfo.UnresolvedPscxPathImpl.cs

Used simply like this:

```
        // protected (derived classes may replace Path and LiteralPath)
        protected PscxPathInfo[] _paths;
        protected PscxPathInfo[] _literalPaths;

        [Parameter(
            ParameterSetName = ParameterSetPath,
            Position = 0, 
            Mandatory = true, 
            ValueFromPipeline = true, 
            ValueFromPipelineByPropertyName = true,
            HelpMessage = "Specifies the path to the file to process. Wildcard syntax is allowed."
        )]
        [AcceptsWildcards(true)]
        [PscxPath(Tag="PathCommand.Path")]
        public virtual PscxPathInfo[] Path
        {
            get { return _paths; }
            set { _paths = value; }
        }

        [Parameter(
            ParameterSetName = ParameterSetLiteralPath,
            Position = 0, 
            Mandatory = true, 
            ValueFromPipeline = false, 
            ValueFromPipelineByPropertyName = true,
            HelpMessage = "Specifies a path to the item. The value of -LiteralPath is used exactly as it is typed. No characters are interpreted as wildcards. If the path includes escape characters, enclose it in single quotation marks. Single quotation marks tell Windows PowerShell not to interpret any characters as escape sequences."
        )]
        [Alias("PSPath")]
        [PscxPath(NoGlobbing = true, Tag="PathCommand.LiteralPath")]
        public virtual PscxPathInfo[] LiteralPath
        {
            get { return _literalPaths; }
            set { _literalPaths = value; }
        }
```

**Comment by iSazonov** [comment]
If Core team says about security it is important for PowerShell too and we shouldn't "revert" this too.
It seems unlikely that somebody __explicitly__ use DirectoryInfo.ToString() or FileInfo.ToString() in scripts. It is used as last resort in output only. The output we could easily fix (I am not sure that we should).

**Comment by rjmholt** [comment]
> If Core team says about security it is important for PowerShell too and we shouldn't "revert" this too.

Yeah basically it's because relative paths might be relative to somewhere else, whereas absolute paths are canonical. I suspect it's a bigger issue in ASP.NET than for us, but I agree that it's the better choice.

Still we must weigh that against the break.

**Comment by iSazonov** [comment]
> it's a bigger issue in ASP.NET than for us

What is difference C# code and script code in the context? Modern management interfaces is Web - that is ASP.Net and internally it use PowerShell (EAC - Exchange Admnistrative Console, WAC - Windows Admnistrative Console).

**Comment by rjmholt** [comment]
Essentially my thinking is that public-facing websites often serve static content, and [path traversal is a classic attack](https://www.owasp.org/index.php/Path_Traversal) ([here](https://www.blackhat.com/docs/us-17/thursday/us-17-Tsai-A-New-Era-Of-SSRF-Exploiting-URL-Parser-In-Trending-Programming-Languages.pdf)'s another fun one).

That scenario is distinguished because:
- The path input comes from a public-facing, untrustable endpoint
- A chroot-like environment is in effect
- There's arguably no good reason to use relative paths at all (especially since webapps are "stateless")

Compare this to PowerShell, where:
- User input should not come from public-facing endpoints (and if it does, path handling is relatively low on the list of concerns)
- PowerShell itself doesn't have a chroot responsibility; we leave it to the containing environment to sandbox the user
- We have a concept of a current working directory, which changes, so relative paths have a meaningful use

> Modern management interfaces is Web

This is true, but the vast majority of websites are not for system management. PowerShell on the other hand is mostly for machine management and automation.

**Comment by iSazonov** [comment]
> Compare this to PowerShell, where:

:-) You say about ideal world where attacks don't exist. One mistake in public level code and attacker gets possibility to inject specific data and exploit relative path feature. 
I mean that we should reduce the attack area.

**Comment by rjmholt** [comment]
> I mean that we should reduce the attack area.

Sure, on paper that's an easy decision.

But we're currently talking about removing a form of relative path handling from an interactive shell. Is bash or Python having a debate about that?

I'm not saying we should strip out security features, but this is a relatively large breaking change that affects (breaks) official Microsoft-shipped tools.

Windows PowerShell doesn't consider this a security issue and isn't going to change it. So why should PowerShell Core? If .NET hadn't silently broken this, would we have asked them to or let them?

In the real world, attacks exist but so does the usability/security tradeoff. PowerShell already bends over backward trying to manage security boundaries that other applications never contemplate, threading the needle between being able to manage a machine and not being able to do anything bad to it. We have a whole suite of established mechanisms in and around PowerShell to control the power of the user, and I'm not convinced that making this change really enhances that. Factoring in that it's a relatively serious breaking change, I wouldn't endorse it.

Anyway, it's all academic, since the change is already upon us. The question is, what do we do with it? For PowerShell 7 to live up to its compatibility promise, I think we have to seriously consider changing the string coercion logic of `FileInfo` and `DirectoryInfo`.

**Comment by iSazonov** [comment]
> The question is, what do we do with it? 

Do you know scripts affect by the change? 
I look some my scripts and I never used the ToString conversion - only Name or FullName. So for me it is only formatting issue.

**Comment by rjmholt** [comment]
According to https://github.com/PowerShell/PowerShell/issues/9800#issue-451162995, [this](https://github.com/microsoft/vcpkg/blob/master/scripts/bootstrap.ps1) is an example.

So it turns out not as production-oriented as I thought, there.

> I never used the ToString conversion

It's automatic because of `LanguagePrimitives`' automatic string conversion logic. So any script that takes `$item = get-childitem` and passes it to a `-Path` or a `-LiteralPath` (`gcm | ? { $_.Parameters.Keys -contains 'Path' } | % Name`, 51 commands) will be affected

**Comment by iSazonov** [comment]
Thanks! I see now how the problem arises:

https://github.com/microsoft/vcpkg/blob/3e1b8afb189a78666e2851524ca888b8173daea4/scripts/bootstrap.ps1#L226-L231

It is the __bad__ pattern but it can be used in many scripts.
_I think this is happening because of the display of the short name in default output_ - users do "dir", see short names and trying use its in interpolated strings directly instead of using `$_.Name` and `Join-Path`.

**Comment by mklement0** [comment]
I should have made it clearer that the _old_ behavior resulted in hard-to-predict behavior that was the cause of many bugs, namely when passing `System.IO.FileInfo` or `System.IO.DirectoryInfo` instances as _direct arguments_ to cmdlets' `-Path` or `-LiteralPath` parameters, which _situationally_ - depending on the specifics of the `Get-ChildItem` call - caused name-only stringification - see https://stackoverflow.com/a/53400031/45375

In short: while it is a breaking change (that we've lived with for quite some time now), the new behavior to me is unquestionably preferable.

As an aside, the problem described above would be mitigated if `System.IO.FileInfo` or `System.IO.DirectoryInfo` arguments were bound via their `.PSPath` property, just as with pipeline input, which is part of a fundamental asymmetry - see #6057

**Comment by iSazonov** [comment]
> https://stackoverflow.com/a/53400031/45375

It looks awful! Perhaps reference to security (in Core issue) is best time to unify the behavior.

**Comment by oising** [comment]
We struggled with this a decade ago when it first started rearing its ugly head:

![image](https://user-images.githubusercontent.com/1844001/59132040-12eed680-8942-11e9-888a-f1161241c24e.png)

**Comment by oising** [comment]
@rkeithhill Not to hijack the thread, but maybe we could collaborate on an RFC for this. Now that the source is open, we could improve on the PscxPath stuff (by extending PathInfo to handle non-existant paths, for example.)

**Comment by daxian-dbw** [comment]
Quoted from https://github.com/PowerShell/PowerShell/issues/7132#issuecomment-499852757
> which situationally - depending on the specifics of the Get-ChildItem call - caused name-only stringification

Just want to point out that the previous behavior was resulted by the inconsistency in `FileInfo` -- for `FileInfo` objects retrieved by `DirectoryInfo.EnumerateFiles()`, calling `ToString()` on them will return the simplified file name; while for the `FileInfo` object created using the public constructor, calling `ToString()` returns the full path. This is why this behavior happens only when running `Get-ChildItem` targeting a directory.

The inconsistency was fixed in .NET Core -- `FileInfo.ToString()` object always return the full path, unless it's representing a path that cannot be resolved.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agrees that the old behavior is inconsistent, however, backwards compatibility is a major concern.  Recommendation is to explore an ETS solution and measure the level of compatibility as well as the perf impact before agreeing that would be the final solution.  If the ETS solution is insufficient for compatibility or there is significant perf impact, @PowerShell/powershell-committee will revisit this issue.

**Comment by iSazonov** [comment]
> backwards compatibility is a major concern

If .Net Core found this accessible we could do the same.

Perhaps PSSA could help. /cc @rjmholt @bergmeister 

Not clear about ETS. I'd expect that we fix only `dir` output in formatting system.

**Comment by rjmholt** [comment]
> explore an ETS solution

ETS meaning extended type system? So some kind of script method override? (This is what I was imagining too).

PSScriptAnalyzer doesn't currently have any single rule tracking semantic changes in PowerShell. I think that kind of effort could only really proceed with help from PowerShell. I think we've discussed exactly this before, the idea where we have a big rule that just looks up the PowerShell version and checks the particular syntax.

If we can at least catalogue the nature of any and all breaking changes in one place, such a rule would be feasible to write.

Also, I feel I should register that despite making the opposing case, I'm actually in favour of the new behaviour.

**Comment by iSazonov** [comment]
> ETS meaning extended type system?

Yes.

> I think we've discussed exactly this before

Have we a tracking issue?

**Comment by daxian-dbw** [comment]
> Recommendation is to explore an ETS solution and measure the level of compatibility as well as the perf impact before agreeing that would be the final solution.

ETS won't be helpful to retain the old behavior in PowerShell. As described in https://github.com/PowerShell/PowerShell/issues/7132#issuecomment-501451500, the root cause of the original inconsistent behavior in PowerShell is the inconsistency in returning result of `FileInfo.ToString()`. When invoking `Get-ChildItem` against a directory, it uses `DirectoryInfo.EnumerateFiles()` to get the `FileInfo` objects, which return the file name only when calling `ToString()` on them. When invoking `Get-ChildItem` against files directly, it uses the public constructor `new FileInfo(string fileName)` to create the `FileInfo` objects, which return the full path when calling `ToString()` on them.

So to retain the old _wrong_ behavior, we will have to put some hacky code in `FileSystemProvider` to differentiate the `FileInfo` objects generated from `Get-ChildItem <dir>` and `Get-ChildItem <file>` and `Get-Item <file>`. That code would be definitely confusing and I don't think we should do that just in order to retain an unfavorable existing behavior. Since .NET accepted the breaking change by fixing the inconsistency, it's a good chance for us to do the same.

**Comment by vexx32** [comment]
I don't think it makes sense to retain the more confusing behaviour just because people are accustomed to dealing with it.

Keeping this change means some scripts will break, maybe, but in fixing those we'd just be removing additional workaround logic that was probably more annoying to have around anyway.

Maybe a small handful of edge cases where it really was helpful, but there is no shortage of available alternatives for those, either. 🙂

**Comment by rjmholt** [comment]
> Have we a tracking issue?

https://github.com/PowerShell/PowerShell/issues/9138

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this.  The work involved to maintain compatibility is not worth the effort as the underlying platform has introduced a change to fix an inconsistency problem.  This results in a breaking change for some PowerShell users, but detecting of this will be quick and using `.FullName` or `.Name` as appropriate is the right thing to do.  We could make a change in `Join-Path` to support joining two absolute paths to make this simpler for scripts, but that would be a separate issue.
