### ISSUE TITLE
Why is ([System.Collections.ObjectModel.Collection[psobject]]1)[0] a string?

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#7154]
I've been using this conversion to pass objects to `PowerShell.Invoke()` like this:
```PowerShell
PowerShell.Invoke([System.Collections.ObjectModel.Collection[psobject]]$obj)
``` 
I'm puzzled by this conversion from `[int32]` to `[string]`.

Steps to reproduce
------------------

```powershell
([System.Collections.ObjectModel.Collection[psobject]]1)[0].GetType().Name
```

Expected behavior
-----------------

I expected `1` to remain an `[int32]`.

```none
int32
```

Actual behavior
---------------

`1` is converted to a `[string]`

```none
string
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.688
PSEdition                      Core
GitCommitId                    v6.1.0-preview.688
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
I have no explanation, but 2 quick additional observations:

* It only happens when you cast a _scalar_; `([System.Collections.ObjectModel.Collection[psobject]] (, 1))[0].GetType().Name` yields `Int32`, as expected.


* It also happens with `[System.Collections.Generic.List[object]]`; by contrast:
  * casting a scalar to `[System.Collections.ArrayList]` _fails_,
  * but works _correctly_ with `[object[]]`

**Comment by alx9r** [comment]
It looks like `{ Write-Object $obj -NoEnumerate }.Invoke()` is a more reliable way to convert to `[Collection[psobject]]`.  Or at least is was before #2038, and (hopefully) will be again once those issues are corrected.  In the meantime `Write-Output2` from [6451(comment)](https://github.com/PowerShell/PowerShell/issues/6451#issuecomment-375111813) seems to work.

**Comment by mklement0** [comment]
If you're not concerned about the intermediate, transient `[object[]]` array that is invariably constructed, you can also do `[System.Collections.Generic.List[object]] @($obj)`

**Comment by PetSerAl** [comment]
It seems that given conversion covered here:
https://github.com/PowerShell/PowerShell/blob/bbb4f2ea84f6c4a8e8775978178826b61db20bda/src/System.Management.Automation/engine/LanguagePrimitives.cs#L5399
And `ConvertNumericIConvertible` specifically do conversion thru string:
https://github.com/PowerShell/PowerShell/blob/bbb4f2ea84f6c4a8e8775978178826b61db20bda/src/System.Management.Automation/engine/LanguagePrimitives.cs#L3858-L3859

**Comment by alx9r** [comment]
```none
 // If the original object was a number, then try and do a conversion on the string 
 // equivalent of that number... 
```

Interesting.  That is clearly deliberate.  But why do that?

**Comment by lzybkr** [comment]
I'm not sure this really is deliberate, I think another explanation is that this is just a symptom of PowerShell being especially permissive with conversions.

Based on this [check](https://github.com/PowerShell/PowerShell/blob/bbb4f2ea84f6c4a8e8775978178826b61db20bda/src/System.Management.Automation/engine/LanguagePrimitives.cs#L5395), it feels like an oversight to have allowed the conversion to collections other than array.

**Comment by KnowledgeNerd** [comment]
I feel like this isn't purposeful and some if going on weird here.   This is a PowerShell code equivalent since you are invoking it in PowerShell.

Code
`
 $orig_notworking = ([System.Collections.ObjectModel.Collection[psobject]]1)
 echo "orig_notworking - $($orig_notworking[0].GetType().Name)"

 $orig_working = (New-Object -TypeName System.Collections.ObjectModel.Collection[psobject])
 $orig_working.Add([psobject]1)
 echo "orig_working - $($orig_working[0].GetType().Name)"
 
 #Weird behavior, can't chain together
    # Err: Cannot index into a null array.

 $orig_work_but_not_working =((New-Object -TypeName System.Collections.ObjectModel.Collection[psobject]).Add([psobject]1))
 echo ('orig_work_but_not_working - Code [ $orig_work_but_not_working[0].GetType().Name ] - Error:Cannot index into a null array')


 #Shows that the original creation of the psobject is equivalent
 echo '(New-Object -TypeName PSObject  -ArgumentList @(1)) -eq [psobject]1)'
 (New-Object -TypeName PSObject  -ArgumentList @(1)) -eq [psobject]1

 $notworking = ([System.Collections.ObjectModel.Collection[psobject]](New-Object -TypeName PSObject  -ArgumentList @(1)))
 echo "notworking - $($notworking[0].GetType().Name)"
 
 $working = (New-Object -TypeName System.Collections.ObjectModel.Collection[psobject])
 $working.Add((New-Object -TypeName PSObject  -ArgumentList @(1)))
 echo "working - $($working[0].GetType().Name)"
`

Output
`
orig_notworking - String
orig_working - Int32
orig_work_but_not_working - Code [ $orig_work_but_not_working[0].GetType().Name ] - Error:Cannot index into a null array
(New-Object -TypeName PSObject  -ArgumentList @(1)) -eq [psobject]1)
True
notworking - String
working - Int32
`

Sorry for the terrible code and the old post revival, but I got interested.

**Comment by KnowledgeNerd** [comment]
ahhhh thanks  ill remove

**Comment by KnowledgeNerd** [comment]
Gotta say I revisited this again and was appalled at my code... But I still think something is weird.

Check out this ~slightly~ better and cleaner code to see what's going on:

`
$testobj = New-Object -TypeName PSObject -ArgumentList @(1)
$testobj2 = [psobject]1
$testobj3 = 1

$test = New-Object -TypeName System.Collections.ObjectModel.Collection[psobject]
$test.Add($testobj)
$test[0].gettype().name

$test2 = [System.Collections.ObjectModel.Collection[psobject]]($testobj)
$test2[0].gettype().name

$test3 = New-Object -TypeName System.Collections.ObjectModel.Collection[psobject]
$test3.Add($testobj2)
$test3[0].gettype().name

$test4 = [System.Collections.ObjectModel.Collection[psobject]]($testobj2)
$test4[0].gettype().name

$test5 = New-Object -TypeName System.Collections.ObjectModel.Collection[psobject]
$test5.Add($testobj3)
$test5[0].gettype().name

$test6 = [System.Collections.ObjectModel.Collection[psobject]]($testobj3)
$test6[0].gettype().name
`

Output
--------
`
Int32
String
Int32
String
Int32
String
`
