### ISSUE TITLE
basic problem mixing byvalue and bypropertyname parameters in pipes

### ISSUE THREAD

**Issue by jszabo98** [PowerShell/PowerShell#7159]
Steps to reproduce
------------------

Can't use a bypropertyvalue parameter in a pipe when a parameter that can be byvalue in a pipe is not supplied.  Powershell ends up converting the bypropertyvalue parameter into a string that looks like a hash table, which is never useful, in this case '@{type=cmdlet}'.  get-command is a good example of this.  A lot of its parameters can be sent over the pipe bypropertyvalue.  -name can be sent byvalue.  So the -name parameter is "greedy" in the pipeline, to the point of messing up the -type parameter.

```powershell
[pscustomobject]@{type='cmdlet'}  | get-command       
```

Expected behavior
-----------------

```
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Add-Content                                        3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Add-History                                        6.1.0.0    Microsoft.PowerShell.Core
Cmdlet          Add-Member                                         3.1.0.0    Microsoft.PowerShell.Utility
...
```

Actual behavior
---------------

```
get-command : The term '@{type=cmdlet}' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:37
+ [pscustomobject]@{type='cmdlet'}  | get-command
+                                     ~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (@{type=cmdlet}:String) [Get-Command], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Get-Process is another one that has an issue with this, from memory. It's very frustrating -- there's no good reason that after the byvalue fails, a bypropertyname shouldn't be attempted.

**Comment by mklement0** [comment]
@vexx32:

The problem isn't that the by-property-name parameter _isn't_ bound - it is - it's that the by-value parameter is _also_ bound, which, with `[string]` / `[object]` / `[psobject]` by-value parameters happens _invariably_ - unless you bind these parameters by _argument_ rather than via the pipeline (as @jszabo98 implies).

Just to spell it out for the example command:

```powershell
# Binding -Name *by argument* makes the problem go away. 
[pscustomobject]@{type='cmdlet'}  | get-command -Name * 
```

The parameter binder is designed to bind input to _all_ suitable pipeline-binding parameters, even though the typical use case is for pipeline input to bind to just _one_ parameter.

---

The behavior is certainly frustrating, and the workaround isn't obvious, but a generic solution would require changes to the parameter binder, which, apart from backward-compatibility concerns, raises tricky conceptual issues:

* For `[object]` / `[psobject]`-typed parameters, there is no solution -  by their nature (everything is derived from them), they should continue to bind everything.

   * Cmdlet authors should simply not bind such parameters by value if they also want to support other pipeline parameters that should bind in isolation.

* For `[string]`-typed parameters and other specific types, conceivably a `StrictType` attribute argument could be introduced that binds only if the input object is of the target type (or a derived type); e.g.:  
`[Parameter(ValueFromPipeline, StrictType)] [string] $Name]`, which would then only bind `[string]` input objects, and not also instances of other types, such as `[pscustomobject]@{type='cmdlet'}`.

---

For now, the only options I see are:

* For cmdlets that do use `[string]` / `[object]` / `[psobject]` by-value parameters alongside other, conceptually independent pipeline-binding parameters, _document_ the pitfall and workaround.
   * Among the cmdlets affected are `Get-Command`, as demonstrated here, and, on Windows PowerShell, `Get-Service` which also has a `-ComputerName` parameter there that clashes with `-Name` - see this [SO question](https://stackoverflow.com/a/50341501/45375).
   * Others?

* When authoring new cmdlets, avoid use of such parameters, if possible.

* Document guidelines for cmdlet authors.
