### ISSUE TITLE
Add support for cd (Set-Location) to path with spaces without requiring quotes

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#7190]
We should consider updating `Set-Location` to not require quotes for paths.  If I fire up CMD.exe I can do this:
```
C:\Users\hillr>cd c:\program files

c:\Program Files>
```
but in PS Core this fails:
```
06-26 15:56:33 1> cd c:\program files
Set-Location : A positional parameter cannot be found that accepts argument 'files'.
```
Set-Location takes only a single path.  It would be nice if a user could type the path without having to quote the path.  

I imagine this would have to be its own parameter set as I'm not sure how this feature would work in the presence of parameters like -PassThru or -StackName.  But I think far and away the common use case is someone wanting to `cd c:\program files`, `cd c:\program files (x86)` or `cd ~\Visual Studio 2017`.  Not sure how that `(x86)` bit would work out given that PS will think that starts an expression.  Hmm...

**Comment by mklement0** [comment]
While I'm personally always happy to throw off the shackles of unnecessary quotes, I don't think it's a good idea in this case:

* It encourages "fuzzy thinking" with respect to argument-mode syntax, which can get in the way when using other cmdlets.

* As time goes on, the need to make seasoned `cmd.exe` users comfortable will go away.

---

As for easing the pain:

* Tab-completion helps to an extent - e.g., `cd C:\Program<tab>` - but if you want to type a prefix that includes _spaces_ before pressing `<tab>`, there is no way around knowing that you need to `` ` ``-escape such spaces, e.g., ``cd C:\Program` <tab>``

* For special folders such as `C:\Program Files` and `C:\Program Files (x86)`, a namespace with symbolic identifiers (which by definition do not contain spaces and therefore do not need quoting) could help; e.g.,
`cd $sf:ProgramFiles` or `cd $sf:ProgramFilesX86` for changing to the locations that are `C:\Program Files` and `C:\Program Files (x86)`, respectively, in a default Windows installation.

  * As it turns out, someone has already suggested that: #6966

**Comment by dragonwolf83** [comment]
I would prefer consistency with other cmdlets and parameters. If I discovered I could pass a Path to `cd` without quotes, then I would think it would be ok to do that with other cmdlets that take a Path parameter. For that matter, why not be able to do it with passing arguments to executables or when using `Start-Process`.

Mastering of quotes is so crucial to those other functions that I think adding a special case just makes things more confusing.

**Comment by rkeithhill** [comment]
Upon further reflection (and reading over issue feedback), I believe I should just close this.  The biggest mitigation is tab-completion supplying the quotes.  Plus I'm really not sure how you'd handle an unquoted `(x86)`  That would be interpreted as an expression which tries to invoke the command `x86`.  No bueno.
