### ISSUE TITLE
PowerShell in Docker container does not map container drive mounts at start-up

### ISSUE THREAD

**Issue by PetSerAl** [PowerShell/PowerShell#7212]
Steps to reproduce
------------------

```powershell
"'$('-' * 100)'",
'dir V:\',
"'$('-' * 100)'",
'dir FileSystem::V:\',
"'$('-' * 100)'",
'New-PSDrive V FileSystem V:\',
'dir V:\' | docker run -i --rm -v C:\Host\Path:V: microsoft/powershell pwsh -Command -
```

Expected behavior
-----------------

`V` drive should be mapped at PowerShell start-up.

Actual behavior
---------------

```none
Attempting to perform the InitializeDefaultDrives operation on the 'FileSystem' provider failed.
----------------------------------------------------------------------------------------------------
dir : Cannot find drive. A drive with the name 'V' does not exist.
At line:1 char:1
+ dir V:\
+ ~~~~~~~
+ CategoryInfo          : ObjectNotFound: (V:String) [Get-ChildItem], DriveNotFoundException
+ FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

----------------------------------------------------------------------------------------------------


    Directory: V:\


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        6/30/2018   5:37 AM              0 Host file.txt


----------------------------------------------------------------------------------------------------

Name           Used (GB)     Free (GB) Provider      Root
----           ---------     --------- --------      ----
V                 156.80       1705.68 FileSystem    V:\




    Directory: V:\


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        6/30/2018   5:37 AM              0 Host file.txt
```

Environment data
----------------

```cmd
>ver

Microsoft Windows [Version 10.0.17134.112]

>docker --version
Docker version 18.03.1-ce, build 9ee9f40
```

**Comment by alexandair** [comment]
I think this is expected. PowerShell drives created with the New-PSDrive command exist only in the PowerShell session used to create them unless they are mapped drives with the -Persist parameter.

**Comment by TravisEz13** [comment]
this is an actual drive... you shouldn't have to create the drive...

**Comment by TravisEz13** [comment]
Although, as a new platform, I'll classify it as an enhancement.

**Comment by oising** [comment]
I was logged [an issue](https://github.com/MicrosoftDocs/azure-docs/issues/31016) when I noticed this behavior when using Azure Storage File Shares with a Windows Container flavored App Service. The problem stems in InitializeDefaultDrives failing, but the operating system mounted drive is mountable with New-PSDrive manually even though I.D.D. fails. 

The guts of the problem seem to be that there is an [#ifdef UNIX](https://github.com/PowerShell/PowerShell/blob/06391330533c65b464e0c5a62bc3303564ccd324/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L993) put in place for the FileSystemProvider when running on Unix/Linux that bypasses the problem of auto mounting azure file shares in Cloud Shell pwsh (which always runs on Unix now), but now that the App Service guys have added preliminary support for mounting storage file shares in Windows Containers, remoting into the container with pwsh gives a new context for this issue. 

```c#
                        if (newDrive.DriveType == DriveType.Network)
                        {
                            // Platform notes: This is important because certain mount
                            // points on non-Windows are enumerated as drives by .NET, but
                            // the platform itself then has no real network drive support
                            // as required by this context. Solution: check for network
                            // drive support before using it.
#if UNIX
                            continue;
#else
                            displayRoot = GetRootPathForNetworkDriveOrDosDevice(newDrive);
#endif
``` 

So the problem is now the _#else_ clause is running in this new container/docker context with a Windows base OS and an Azure Storage File Share because while `[System.IO.DriveInfo]::GetDrives()` returns the file share mounted drive, the code path for `GetRootPathForNetworkDriveOrDosDevice` blows up.

I guess we need some new runtime logic to harden this latter path from Azure file share pseudo network drives.

**Comment by oising** [comment]
@TravisEz13 A year ago this probably had little visibility. It's about to get a whole lot worse when Azure Storage File Shares come out of preview for Windows Container App Services, so if I may suggest you re-prioritize this. I've already seen some people move away from App Services to VMs to get past this problem because it didn't seem surmountable to them.

**Comment by oising** [comment]
@alexandair The issue is that the file share is seen as a native windows drive by powershell's filesystemprovider and it attempts to create a PSDrive for it in the provider's startup, but it fails. But if we use `new-psdrive z filesystemprovider -root z:\` it actually works.

**Comment by TravisEz13** [comment]
@oising Does this issue only occur in docker mapped drives or is it specific to Azure Storage File Share.  If it's the later, you should file a new feature request.
