### ISSUE TITLE
An ArgumentCompleter script block returning no results should not result in falling back to the default tab-completion behavior

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7215]
Currently, if you attach an `ArgumentCompleterAttribute` to a parameter and its script block happens to return no completions, tab completion falls back to the _default_ behavior, i.e., completion of item names in the current location (which, in a filesystem location, cycles through the names of all files and directories in the current directory).

However, it makes more sense to _not complete_ in this event, given that the intended completions may be unrelated to provider items altogether.

Steps to reproduce
------------------

Assume that the current location is a filesystem location and that no `*.ext` files are present.

```powershell
function foo {
  param(
    [ArgumentCompleter({
      Get-ChildItem -Name *.ext
    })]
    [string] $Bar
  )

  $Bar
}

foo # <-- press TAB here
```

Expected behavior
-----------------

A no-op: given that the argument-completer script block outputs no completions, nothing should happen.

Actual behavior
---------------

Tab completion falls back to the default behavior and cycles through the names of all files and subdirectories in the current dir.

Environment data
----------------

Written as of:

```powershell
PowerShell Core v6.1.0-preview.3
```

**Comment by Betoz** [comment]
Attaching `ArgumentCompletions` attribute with empty string as the only tab completion value, i.e. `[ArgumentCompletions('')]`, in addition to `ArgumentCompleter` attribute, results in no completion when `ArgumentCompleter` script block returns no completions.

I agree with it making more sense to not complete when `ArgumentCompleter` script block returns no completions, or at least to handling the return of empty string as a valid completion, like it does for the `ArgumentCompletions` attribute.

Maybe it is a design decision to use `ArgumentCompletions` for static completions in the case of `ArgumentCompleter` script block returning no completions?
If so, I want this information in the `about_functions_argument_completion` documentation, e.g.

> Hey! You can block tab completion with `[ArgumentCompletions('')]`.

Note that the `ArgumentCompletions` attribute was introduced in PowerShell `6.0`.

I confirmed usage of `[ArgumentCompletions('')]` to work with PowerShell `7.1.2`, and to not work with `5.1` (breaks, because not supported).
