### ISSUE TITLE
Location of build artifacts for native Windows binaries

### ISSUE THREAD

**Issue by PetSerAl** [PowerShell/PowerShell#7219]
Recently tried to compile PowerShell native Windows binaries and this last copy operation:
https://github.com/PowerShell/PowerShell/blob/d04fef469b774ffa63536ad460aff3708642999a/build.psm1#L307-L311
of `Start-BuildNativeWindowsBinaries` failed due to absence of file in expected location.

For me file (result of compilation) was located in `\src\PowerShell.Core.Instrumentation` relative to repo root, but not in `$HOME\source` as stated in the comment. Is that error here or location was changed or is dependent of environment? Should build script be fixed or enhanced to cover other location of build artifacts?

**Comment by bergmeister** [comment]
I can confirm the same happens on my machine. I have to say though that I have never used this function and also don't know its purpose...
I should add though that when I first ran it, I had problems due to missing `atlbase.h` headers, which I could fix by installing the optional Visual Studio component `Visual C++ ATL support`

**Comment by iSazonov** [comment]
We should clean up the script - native binaries was moved to https://github.com/PowerShell/PowerShell-native.

**Comment by PetSerAl** [comment]
It seem the other repo have this exact lines commented out and use different logic to locate build artifacts.

**Comment by daxian-dbw** [comment]
I also ran into this issue. I submitted PRs to fix it both in powershell repo (#7226) and the powershell-native repo (https://github.com/PowerShell/PowerShell-Native/pull/3).
