### ISSUE TITLE
Cannot create two nested arrays with only one element at the top level

### ISSUE THREAD

**Issue by flxflx** [PowerShell/PowerShell#7223]
Steps to reproduce
------------------

```powershell
$x = @(@(1,2))
$x[0][1]
```

I also tried different variants of that using [array] etc.

Expected behavior
-----------------

Should output '2'

Actual behavior
---------------

Doesn't output anything, as the two arrays are being folded into one.

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by mklement0** [comment]
This is by design:

`@(...)` doesn't _construct_ an array, it _ensures_ that its operand is an array (i.e., loosely speaking, it wraps a scalar in a single-element array and leaves something that already is an array alone).

Thus, nesting `@(...)` is pointless and invariably has the same effect as a _single_ `@(...)`.

What you need instead is the array construction operator: `,`

```powershell
PS> $x = , (1, 2); $x[0][1]
2
```

Also note that you do not need `@(...)` to construct (non-nested) literals: instead of `@(1, 2)` use just `1, 2`, and use `(...)` to clarify precedence, as shown above.

See also: #6329

**Comment by flxflx** [comment]
Great, thanks!
