### ISSUE TITLE
Cleanup throw in PsUtils.GetModuleManifestProperties

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#7262]
PsUtils.GetModuleManifestProperties() throws an exception that is not used. Suggesion is to convert the method to PsUtils.TryModuleManifestProperties()

**Comment by Jawz84** [comment]
I looked into this because it looked like an easy issue to do. I found three files where `PsUtils.GetModuleManifestProperties` is called from:  
1. [/DscSupport/CimDSCParser.cs](https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/System.Management.Automation/DscSupport/CimDSCParser.cs)
2. [/engine/Modules/AnalysisCache.cs](https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/System.Management.Automation/engine/Modules/AnalysisCache.cs)
3. [/engine/Modules/ModuleIntrinsics.cs](https://github.com/PowerShell/PowerShell/blob/a96b4c040492e4e8f79ba243af6d43206fcd8791/src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs)

In the `ModuleIntrinsics` file, the calls are in a `try` block with an empty `catch` block. In the other two files, the error _is_ used, and written to tracer or to log: 

In the `CimDSCParser` file:

```csharp
            catch (PSInvalidOperationException ex)
            {
                s_tracer.WriteLine(
                    "DSC GetModuleVersion: Error evaluating module manifest file '{0}', with error '{1}'. Skip the module '{2}'.",
                    manifestPath, ex, moduleName);
            }
```

In the `AnalysisCache` file:

```csharp
            catch (Exception e)
            {
                if (etwEnabled) CommandDiscoveryEventSource.Log.ModuleManifestAnalysisException(modulePath, e.Message);
                // Ignore the errors, proceed with the usual module analysis
                ModuleIntrinsics.Tracer.WriteLine("Exception on fast-path analysis of module {0}", modulePath);
            }
```

Based on this, I'm unsure what should be done. Options I see:
- This issue should maybe just be closed.
- Maybe it is an option to add a comment in the empty `catch` block in `ModuleIntrinsics` file with an explanation why the error is just suppressed?

What do you think @iSazonov ?

**Comment by iSazonov** [comment]
@Jawz84 the idea is to replace try-catch with condition block like:
```c#
if ( !TryGetModuleManifestProperties() && etwEnabled )
{
    CommandDiscoveryEventSource.Log.ModuleManifestAnalysisException(modulePath, e.Message);
    // Ignore the errors, proceed with the usual module analysis
    ModuleIntrinsics.Tracer.WriteLine("Exception on fast-path analysis of module {0}", modulePath);
}

**Comment by Jawz84** [comment]
Ok thanks for giving an example. Will look at that.
