### ISSUE TITLE
Invoke-WebRequest fails to establish connection

### ISSUE THREAD

**Issue by kvprasoon** [PowerShell/PowerShell#7314]
Steps to reproduce
------------------

```
Invoke-WebRequest -Uri "https://api.github.com/repos/PowerShell/PowerShell/releases"
```

Expected behavior
-----------------
Below output is of 6.1.0-Preview.2

![image](https://user-images.githubusercontent.com/12897753/42962631-af80eef2-8baf-11e8-8960-9bc556839dbd.png)

Actual behavior
---------------

![image](https://user-images.githubusercontent.com/12897753/42962665-bf415c6e-8baf-11e8-89b9-c9550e359541.png)

Environment data
----------------

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Microsoft Windows 10.0.16299 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0



```

**Comment by iSazonov** [comment]
@kvprasoon I can not repo with latest builds.

**Comment by kvprasoon** [comment]
@iSazonov Repro for me in another Server with Preview 4

![image](https://user-images.githubusercontent.com/12897753/42984222-1fcd18e4-8c09-11e8-81a2-bb3ec7617594.png)

**Comment by markekraus** [comment]
@kvprasoon are you sure it's not a connectivity issue between your servers and github?

if you enable TLS 1.2 and run the same commands on 5.1, do you get the same result?

**Comment by kvprasoon** [comment]
@markekraus - I'm sure its not a connectivity issue. It works till 6.1.0-preview 2.
Once I upgrade to preview 3/4 from 2, I get this error.

**NOTE: TLS1.2 by is enabled**

**Comment by markekraus** [comment]
Right, but does it work in 5.1 still after the upgrade (enabling TLS 1.2 before trying)? Since you can run 5.1 and 6.1.0 side-by-die, I'm trying to establish where the fault is. So I'm asking you to test it in 5.1 on the same machine where it is failing with 6.1.0. Can you confirm, please?

I ask because I am unable to reproduce this anywhere. Since the underlying .NET Calls also fail, I suspect this is a system/environment issue. This kind of error can occur if you have networking tools between the client (CoreFX) and the server. These could be anything from firewalls, monitoring software, silent proxies, proxies, intrusion detection, antivirus, etc.

**Comment by kvprasoon** [comment]
I think its because of proxy, even with 5.1 i'm facing issues. I have tested the same in another Win 10 and works fine.
Thanks @markekraus .

**Comment by hurricanehrndz** [comment]
I have this same issue, and definitely going through an IPS. To add though, it seems like 6.0.4 works without issue. I'm just testing against the releases url as well.
