### ISSUE TITLE
. (source dot operator) breaks UNIX and Linux semantics, expected behaviour

### ISSUE THREAD

**Issue by PeterWhittaker** [PowerShell/PowerShell#7319]
Steps to reproduce
------------------

```powershell
PS > new-item -type file -value 'Write-Host("Hello")' -path afile
PS > . ./afile
```
*A new window opens and Hello is displayed therein.*
```
PS > mv afile afile.ps1
PS > . ./afile.ps1
Hello
```

*NOTE: Under Windows, without an extension, a GUI window is raised asking what app should be used to open "./afile"*

Expected behavior
-----------------

```
PS > . afile
Hello
PS > . ./afile
Hello
PS > . afile.ps1
Hello
PS > . ./afile
Hello
```

In UNIX and Linux shells, the extension is irrelevant: All of
 - ". afile",
 - ". ./afile",
 - ". afile.ps1", and
 - ". ./afile.ps1"

would have exactly the same effect: Hello should be displayed in the current window (provided afile contained shell-appropriate commands, e.g., "echo Hello" in bash.

Actual behavior
---------------

```
As described above, with the following additions:
". afile" raises an error
". ./afile" raises an error
". afile.ps1" open a new window
Only ". ./afile.ps1" behaves as expected.
```

Environment data
----------------

```powershell

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.2                                           
PSEdition                      Core                                            
GitCommitId                    v6.0.2                                          
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: T...
Platform                       Unix                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1                                         
WSManStackVersion              3.0                                             


```

**Comment by iSazonov** [comment]
@mklement0 Could you please comment?

**Comment by mklement0** [comment]
@PeterWhittaker:

I don't think you should expect the behavior you're describing, and I don't see the actual behavior you're describing on macOS, at least not on PowerShell Core v6.1.0-preview.3 (see what you get with my code at the bottom).

As for your expectations:

`. ./afile` would only _execute_ something if there's either an extension-less _but executable_ `aFile` in the current dir, or a (not-required-to-be-executable) `afile.ps1` file, with the former taking precedence if both are present; if the file exists, but is neither executable nor has extension `.ps1`, it is opened as if it were a _document_.

`. <filename>` with `<filename>` being a mere name (no path component) by (security-minded) design only ever looks for a file of that name in the directories listed in `$env:PATH` (see below), not in the _current_ directory.

(As an aside: The syntax of`Write-Host("Hello")` suggests a misconception; as a command, you shouldn't invoke `Write-Host` with _method_ syntax (parentheses around argument list, `,`-separated  arguments); use _argument_ syntax (command-line syntax) instead: `Write-Host "Hello"` (no parantheses, whitespace-separated arguments), or, if something should just display in the terminal by default, `"Hello"` - no explicit output command needed, unless you specifically want to bypass PowerShell's success output stream.)

----

Some background:

It is true that on Unix-like platforms the filename extension is irrelevant with respect to whether a file is _executable_, but in order to execute a file you must specify its _exact_ filename, so if it happens to have an extension (which is rare, but (unfortunately) does happen with `.sh` used for shell scripts), it _must_ be specified.

Therefore, in a POSIX-like shell (such as `bash`), if the script name is `afile.sh`, you can _not_  invoke it with `./afile` or `. ./afile` (in the current directory).

This is where PowerShell's behavior differs: it _does_ implicitly look for its _own_ scripts and, if no `afile` - without extension is present - looks for `afile.ps1` and executes that, _in-process_ and - if `. ` was used - in the current scope.
(As in POSIX-like shells, the script file need not have the executable permission bit(s) set in that case.)

That you must use `./` in order to target `afile` / `afile.ps1` _in the current dir._ (as opposed to finding a file of that name somewhere in `$env:PATH`) - whether with direct invocation or via "dot-sourcing" (`.  `) or via `&` - is a sensible security measure that is actually [mandated by POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#dot), and `bash` happens to be in violation of it (though it does look in `$env:PATH` _first_).

An additional difference is that in PowerShell you can invoke _anything_ with `.`, not just PowerShell _scripts_ (whereas POSIX-like shells invariably interpret the filename operand as a _script written in that shell's language_ and choke on binaries, for instance); if the operand happens not to be a PowerShell script, `.` behaves as if you had invoked the operand directly (or as if you had used `&` - the distinction between `&` and `.` only matters for (in-process) PowerShell code)).

I don't see any problems with these selective differences between PowerShell and POSIX-like shells - they strike me as useful extensions.

----

Let me give examples that you can run as-is:

Setup:

```powershell
# Create extension-less script with shebang line and make it executable.
"#!/usr/bin/env pwsh`n'hi from out-of-process t'" > t; chmod a+x t
# Create a regular *.ps1 file
'"hi from in-process t.ps1"' > t.ps1
# Create text file.
'foo' > t.txt
```

Tests:

```powershell
# Invoke by name "t" only; this should invoke the extension-less, executable file with the shebang line
PS> . ./t
hi from out-of-process t

# Invoke with exact file name.
# Note that if you were to delete "t" (the executable file with the shebang line), 
# then . ./t would be sufficient to target "t.ps1"
PS> . ./t.ps1
hi from in-process t

# Invoke a document (something that is neither executable nor has extension .ps1)
# Equivalent of: Invoke-Item t.txt
# Note that Invoke-Item does *not* require the ./ prefix to target a file in the current dir., 
# because *opening* documents is not a security risk, but it's fair for .  and &  - whose main
# purpose is *execution* - to require it.
PS> . ./t.txt
# opens t.txt in the default text editor.
```

**Comment by PeterWhittaker** [comment]
Please reread the original report: The file was created WITHOUT an extension and PWSH opened a new window instead of running it in the exiting window. When mv was to add the extension, PWSH behaved as expected, running the file within the current window.

Under both Windows and UNIX, without an extension, PWSH does not know what to do with the file. While this may be expected behaviour under Windows, it is NOT under UNIX and Linux.

I am looking for workarounds, I have one, add the PS1 extension. But that is a workaround, because the expected UNIX and Linux behaviour is to source the file, provided it is fully named: in all cases it was.

PWSH ONLY sources it in the expected way (in current window) when the filename includes an extension.

I do not know how I can be any clearer about this: At no point was a file whose pathname included an extension sourced without the extension.

**Comment by PeterWhittaker** [comment]
I'll have to wait for PWSH to be updated or install the preview, then: Under my version (documented above), I see very odd behaviour indeed: Create an ordinary file called "fred" with content "Hello", then dot source it as described below:

```
PS > . ./fred
# PS opens a new window, writes Hello there - not at all expected
PS > chmod +x fred
PS > . ./fred
# nothing appears to happen - there is no output in the current PWSH, no windows open
PS > mv ./fred ./fred.ps1 # fred.ps1 still executable
Hello
# as expected, at last
PS > chmod -x fred.ps1
PS > . ./fred.ps1
Hello
# as expected
```

Now open a shell in the same folder, add echo to the beginning of the file, as in

```
echo "Hello"
```

and repeat all four tests, and do four more: without the leading ./ on the file name, as in

```
sh $ . fred
```

The result? Hello is displayed all eight times.

So maybe this is a known bug, corrected in the preview edition. We'll see.

**Comment by mklement0** [comment]
> `PS > . ./fred`

As stated, given that the file neither has extension `.ps1` nor is marked as executable, it is treated as a _document_, as if you had run `Invoke-Item ./fred` or, using the native `open` macOS utility, `open ./fred`.

What that does specifically depends on what default programs you've set up; on my machine, for instance, it opens the file in Visual Studio Code.
It's unclear what you mean by "opens a new window", but I suspect that the file is opened in TextEdit.app, the macOS default text editor (check the menu bar while the window is up).

Given the extended mandate of `.` in PowerShell - the ability  to invoke _anything_ - it makes sense to reserve the assumption that the target file contains PowerShell source code to be sourced to _files with extension `.ps1` only_.

You could argue that this extended mandate should be revoked and that `.` should _only_ support sourcing PowerShell source code, and - like POSIX-like shells, analogously - should _blindly assume_ that whatever file argument is passed contains PowerShell sourced that should be "dot-sourced", whereas currently this assumption is currently reserved solely for file arguments _with extension `.ps1`_. Consider this, however:

* Changing the behavior of `.` would be a breaking change.

*  It's unlikely that you'll want to create _extension-less_ PowerShell source-code files _for the purpose of "dot-sourcing"_; instead, extension-less PowerShell source-code files are most likely _executable scripts with a shebang line_, which are designed to run _out-of-process_, which contradicts the purpose of "dot-sourcing".

> `PS > chmod +x fred`
> `PS > . ./fred`

Now the file is executable, so an _attempt_ is made to execute it.
_Presumably_ (someone familiar with the code should correct me, if necessary), PowerShell delegates execution to the _system_, which _fails_ in this case, because the plain-text file that is marked as executable _lacks a shebang line_ that specified the interpreter to pass the file to.

That said, it shouldn't fail _quietly_, so that is worth creating a separate issue for.

> `PS > mv ./fred ./fred.ps1 # fred.ps1 still executable`
> `Hello`
> `# as expected, at last`
> `PS > chmod -x fred.ps1`
> `PS > . ./fred.ps1`
> `Hello`

As stated, `.ps1` files are special in PowerShell: you can invoke or "dot-source" them at will, whether they're executable files or not.

---

As for your `sh` commands:

Yes, as stated, POSIX-like shells _blindly_ assume that files you pass to `.` contain code in _their_ shell language - PowerShell deviates from that (see above). Also note that POSIX-like shells have no "native" filename extension, so they - unlike PowerShell with its `.ps1` -  _cannot_ infer from a given filename whether it contains shell code or not (the ill-advised, unofficial, non-shell-specific `.sh` convention notwithstanding).

`bash`, as stated, _in violation of POSIX_, allows you to do `. fred` _without needing to refer to a file in the current directory with prefix `./` - this is _not_ worth supporting in PowerShell.

For _direct_ invocation, POSIX-like shells also have a _fallback mechanism_, if delegating to the system to invoke an _executable_ file fails due to _absence of a shebang line_. They default to executing such a file as either _themselves_ or with `/bin/sh`.

That strikes me as another practice that is _not_ worth adopting in PowerShell: reporting an error seems more sensible to me - as noted, PowerShell currently fails _silently_, which should be fixed.

**Comment by PeterWhittaker** [comment]
Great explanation, thanks. Makes the overall design approach clear.

Re the separate issue: Since you have the preview, can you try the "fail quietly" case and let me now the outcome? If it is "fail quietly", I'll open an issue; if it is otherwise, I'll either get the preview or wait for the general update, then open the issue: I'm not sure it is worth opening an issue for something fixed in the preview.

**Comment by mklement0** [comment]
@PeterWhittaker: Glad to hear it was helpful.

Yes, the quiet-failure issue exists even in the latest preview release (PowerShell Core v6.1.0-preview.3), but I've actually just created an issue for it myself: #7336

Note that while there is no _error message_, it is possible to detect the failure by querying `$LASTEXITCODE` (which is `8` in this case).

**Comment by PeterWhittaker** [comment]
@mklement0 : #7336 is an excellent bug report, far better than I could have written at this stage.

Re this report, it seems to me it can be closed as in effect "working by design", but I'd appreciate guidance on how to proceed and remain "on side" for this repo: Should I close, and with what labels/status, should someone close, etc. Thanks!

**Comment by mklement0** [comment]
Thanks, @PeterWhittaker.

@iSazonov has already added the label `Resolution-Answered`, so I think all that's left to do is for you to close the issue.

**Comment by PeterWhittaker** [comment]
Perfect, done!

**Comment by darthwalsh** [comment]
For anybody who'd rather pwsh worked like you expect your shell to work, instead of how shells are "supposed" to work, you can use a cludge like this:

```pwsh
function Source-Anything($path) {
  $tempFile = (New-TemporaryFile).FullName + ".ps1"
  Copy-Item $path $tempFile
  . $tempFile
}
```

I don't think you can hack pwsh to make `. afile` work, but now you can run `Source-Anything afile`

**Comment by mklement0** [comment]
To recap, @darthwalsh: There is no benefit, only drawbacks, to making `. afile` work: 

Requiring `./afile.ps1` 

* (a) prevents accidental execution of a different executable `afile` somewhere in `$env:PATH` if no `afile` executable happens to be present in the current dir., and 
* (b) there's never a reason to author a PowerShell script that you want to execute _in-process_, via sourcing, _without_ the helpfully descriptive `.ps1`  extension.
