### ISSUE TITLE
Remove the type catalog generator

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#733]
The type catalog generator was written by @daxian-dbw because we do not have `AppDomain.GetAssemblies()`, which is tracked in dotnet/corefx#1784. If we can get this API exposed by .NET Core, then the entire type catalog generator can go away.

**Comment by HemantMahawar** [comment]
@andschwa : Is this still relevant

**Comment by andschwa** [comment]
@HemantMahawar Yes; assigning to @daxian-dbw for any further follow-up.

**Comment by joeyaiello** [comment]
Workaround in place, not ideal, but no pressing need to do this work yet.

**Comment by iSazonov** [comment]
@daxian-dbw Could you please add comment why we can not remove the type catalog and close the issue?

**Comment by daxian-dbw** [comment]
PowerShell Core allows the user to use any .NET Core framework built-in types without knowing whether the assembly containing that type is loaded. Also, tab completion for type names also depends on it.

If the assembly is not loaded, powershell load the assembly for you because it's able to figure out which assembly the type is in through the type catalog.

`AppDomain.GetAssemblies` cannot help us do that because it only returns loaded assemblies. Therefore, we need to keep the type catalog.
