### ISSUE TITLE
Make pdbs available for released builds

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#7348]
A lot of tooling (performance/debugging) are helped by debug symbols.

Can we publish these, preferably on the microsoft public symbol server, or, worst case as a downloadable symbol package?

**Comment by SteveL-MSFT** [comment]
For GA builds, we should see about minimally providing a downloadable symbol package (needed for non-Windows anyways) and also see about publishing to Msft symsrv.

**Comment by rjmholt** [comment]
I've been looking into this and there are a couple of things:
- Because we crossgen PowerShell, PDBs would only be available on Windows with a normal release (see https://github.com/dotnet/coreclr/pull/4572 and https://github.com/dotnet/coreclr/issues/3131)
- We're currently not generating those PDBs and aren't quite set up to publish them. So it would take a little bit of work to do that.
- Either way, the only way to support debugging on Linux is to release a whole new Debug build, which would be considerably more work.

So it may be possible for us to generate and publish PDBs on Windows only, but two counter points are:
- Debugging support wouldn't be cross platform
- Being open source, it's relatively straightforward to get a Debug build the old fashioned way

@powercode I'm guessing the main reason for wanting PDBs of published releases is to do performance analysis on optimised (i.e. crossgenned) builds?

**Comment by iSazonov** [comment]
@rjmholt If customers use PowerShell Core SDK they can analize _their_ applications and they need to see PowerShell Core symbols too.

**Comment by rjmholt** [comment]
The SDK PDBs may be a different ask, since the SDK is built differently. I'm following up with @adityapatwardhan.

**Comment by rjmholt** [comment]
Just found a relevant comment in the source (and documenting it here):
https://github.com/PowerShell/PowerShell/blob/f858e6d2073c71a85e1a5e830c39a589bf88f3ad/build.psm1#L2246-L2252

**Comment by SteveL-MSFT** [comment]
Given the work needed and limited value due to current constraints, I'm moving this to `future`.

**Comment by rjmholt** [comment]
Just to document what I've discovered so far:

- `crossgen.exe` needs to be run twice:
    + once to generate the NGEN binaries
    + once *on the NGEN binaries* to generate the PDB files
- To do this, it should be a simple matter of uncommenting the comment I linked above and wrapping it with `if ($Environment.IsWindows) { }`.
- However, I'm currently hitting an issue where `crossgen.exe` doesn't like `Microsoft.CodeAnalysis.CSharp.ni.dll`:
    ```
    Error generating PDB for 'Microsoft.CodeAnalysis.CSharp.ni.dll': The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    Error: file "Microsoft.CodeAnalysis.CSharp.ni.dll" or one of its dependencies was not found
    ```
- I've verified that `Microsoft.CodeAnalysis.CSharp.ni.dll`, `Microsoft.CodeAnalysis.CSharp.dll` and `Microsoft.CodeAnalysis.dll` are all present in `$platformAssembliesPath`.
- Note that `/MissingDependenciesOK` [cannot be used with `/CreatePDB`](https://github.com/dotnet/coreclr/blob/fde763073fcce978141bf0b31e4479df507acfb8/src/tools/crossgen/crossgen.cpp#L751-L755).

**Comment by iSazonov** [comment]
I wonder how PerfView get crossgened PDBs on the fly.

**Comment by powercode** [comment]
@rjmholt My use case is to be able to ask users to capture traces with WPR/XPerf and be able to analyze the captured traces.

I have no problem doing profiling on my one box with my own build, but there are many scenarios where that isn't practical.
