### ISSUE TITLE
Update $env:PSModulePath to include an OS package manager PowerShell module location

### ISSUE THREAD

**Issue by liger1978** [PowerShell/PowerShell#7372]
Here is `$env:PSModulePath` on CentOS:

```
/home/user/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/6-preview/Modules
```

It would be nice if  `/usr/share/powershell/Modules` could be added to this list of directories on *nix systems so that modules can be installed using the OS package manager (e.g. rpm, deb, etc). Typically it is not good practice for these package managers to write to `/usr/local`.

**Comment by DHowett** [comment]
This may be the maintainer's responsibility. They know better than PowerShell where the distribution-managed modules will be installed.

Where they can configure that depends on the user's login manager; systemd-logind supports drop-in files in `/etc/environment.d`, which a powershell package could place per-distribution and standard _login_ (from shadow) may get env vars from `/etc/environment` (because of _pam_env.so_, which is broadly enabled by default.)

Since anything that exists in `$Env:PSModulePath` before powershell loads seems to be combined with the user's local module path, this shouldn't present an integration issue.

**Comment by liger1978** [comment]
OK, well can this be add to the RHEL/CentOS RPMs that are distributed by Microsoft then?
