### ISSUE TITLE
Should we remove the -pssnapin parameter for #requires statement?

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell#7412]
As custom snap-ins are not supported in PowerShell Core, is there still a need for #requires -snapin?

**Comment by bergmeister** [comment]
I just noticed today that although there is still some `#if !CORECLR` code there, the implementation of `PSSnapin` is completely missing. In general I would favour leaving things there for a backport to full .Net but since Snapins are not supported any more (which is good), I would be OK with removing all code related to Snapins.

**Comment by iSazonov** [comment]
@SteveL-MSFT Should we cleanup this? Please set right label or close the Issue.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agree to remove `-pssnapin` from `#requires`

**Comment by joeyaiello** [comment]
Additionally, per @JamesWTruher 's point we should add an error message when using `-pssnapin` that tells users that snap-ins are no longer supported, and that they should try to use `-module foo` instead of `-pssnapin foo` as it might fix their problem.

**Comment by aguzev** [comment]
Anyway, `#Requires -PSSnapin` doesn't work in PSM1 files even on PS 5.1.

```powershell
#Requires -PSSnapin Microsoft.Exchange.Management.PowerShell.SnapIn -Version 1000.0
```
