### ISSUE TITLE
PowerShell Core servicing release for v6.0.4

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#7479]
From:  https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/releasing.md

- [X] Create a private branch named `release-v6.0.4` in VSTS repository.
   All release related changes should happen in this branch.
- [x] Run tests on all supported Linux distros and publish results
- [x] Prepare packages
   - [x]  Build release packages
   - [x]  Sign the MSI packages and RPM package.
   - [x]  Install and verify the packages.
- [x]  Update documentation, scripts and Dockerfiles
   - [x]  Update [CHANGELOG.md](../../CHANGELOG.md) with the finalized change log draft.
   - [x]  Update other documents and scripts to use the new package names and links.
- [x]  Create NuGet packages and publish them to `powershell-core` feed.
- [x]  Publish Linux packages to Microsoft YUM/APT repositories.
- [x]  Create the release tag and push the tag to `PowerShell/PowerShell` repository.
- [ ]  Create the draft and publish the release in Github.
- [ ]  ~Merge the release branch to Github `master` with a merge commit. Then delete the release branch.~
- [x]  Trigger the release docker builds for Linux and Windows container images.

**Comment by chuanjiao10** [comment]
hi ,Please https://packages.microsoft.com administrators pay attention to packagename .  see: #7385

**Comment by chuanjiao10** [comment]
1 Congratulations, you deleted the package prew.2     ，i tested，it work fine.
2 However, due to historical reasons, it cannot be used from prew.2
Yum install -y powershell, or yum update -y powershell upgrade. Because prew.2 is newer than the 6.04 version.
3 need yum remove -y powershell ; yum install -y powershell . Can it be added to the document（ release note ）?
4 If not included in the documentation, prew2 will be the most used version.

**Comment by chuanjiao10** [comment]
ubuntu has same problem.

**Comment by tmknight** [comment]
Will there be a build for Ubuntu 18.04?  17.04 went EOL Jan 2018.

**Comment by adityapatwardhan** [comment]
@tmknight Ubuntu 18.04 is supported on PowerShell Core version 6.1.*.
