### ISSUE TITLE
Add Subset Operator ($Array -IsSubset $Array)

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#7559]
At the moment, PowerShell doesn't really have any reliable and syntactically tidy methods of comparing two arrays.

There is probably a lot more that could be done in this area, but one possible addition is a subset operator. We can -contains and -in, but they only work for arrays being compared against singletons; what we need is a `-subset` operator or similar.

Is `-Intersects` an appropriate verb there?

The standard operators could definitely use better collection against collection comparisons.

**Comment by BrucePay** [comment]
@vexx32 You might want to adjust the title - to me, 'subset' means 'subset of the members of the collection' which is expressed in PowerShell as `$myarray[$start..$end]`.   I would also suggest against using`Intersect` ([System.Linq.Enumerable.Intersect](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.intersect?redirectedfrom=MSDN&view=netframework-4.7.2#System_Linq_Enumerable_Intersect__1_System_Collections_Generic_IEnumerable___0__System_Collections_Generic_IEnumerable___0__)) since set intersection is a different concept. The name for the LINQ comparison operator is `SequenceEquals` (since `Equals` by default means "reference equals"). Note: as a simple workaround for now, you can define an `Eq` method on arrays that compares them:
```powershell
Update-TypeData -MemberType ScriptMethod -MemberName Eq -TypeName System.Array -Value {
    param ($x)
    [System.Linq.Enumerable]::SequenceEqual([object[]] $this, [object[]] $x)
}
```
which is used like:
```
PSCore (1:185) >  $a=1,2,3
PSCore (1:186) >  $b=1,2,3
PSCore (1:187) >  $a.eq($b)
True
PSCore (1:188) >  $a.eq((2,3))
False
PSCore (1:189) >
```
Ultimately, I don't like introducing a new operator for something so basic. The current behaviour for `-eq` with two arrays is to do a reference comparison of the RHS against the members of the LHS. The _only_ time you get a positive result is if you do something like:
```
$a=1,2,3
 , $a -eq $a
```
(note the leading comma) which is pretty obscure. Obviously changing the behaviour of `-eq` is a breaking change. The question is is it worth it? My gut feel is that we should at least have the discussion.

**Comment by vexx32** [comment]
You misunderstand, I think. I don't need an $array -isexactly $otherarray. It'd be interesting to have, perhaps, but that might be about it.

I'm looking for:
```powershell
$SmallArray = 1,2
$BigArray = 1,2,3,4,5

> $SmallArray -issubsetof $BigArray
$true
```

**Comment by BrucePay** [comment]
Raw LINQ will look like
```powershell
$bigArray = 1..10
$smallArray = 6,4,5
if ($smallArray.Intersect($bigArray))
{"it's a subset"}
else
{"It's not a subset"}
```
with a predicate, it would look like
```powershell
 (gps sm*).Intersect((gps s*), {param ($x, $y) $x.processname -eq $y.processname})
```
or maybe
```powershell
(gps sm*).Intersect((gps s*), {$1.processname -eq $2.processname})
```
if we finally get around to implementing $1, $2, $3, ... for positional arguments :-)

**Comment by mklement0** [comment]
Thanks for the LINQ examples, @BrucePay.

We've talked about method vs. query LINQ syntax [before](https://github.com/PowerShell/PowerShell/issues/2226#issuecomment-385399325).

Despite the proliferation, I'd love to see _all_ the  [LINQ set operations](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/set-operations) - `Distinct`, `Except`, `InterSect`, `Union` - as _operators too_ (even though these aren't available in C# _query syntax_); e.g.:

```powershell
$array1 -intersect $array2
$array1 -union $array2
$array1 -except $array2
-distinct $array
```

I wonder if it's worth also implementing the optional equality-comparer script block as the 2nd RHS operand, or whether to leave this advanced feature to the methods only.

As such, I think of the `Compare-Object` enhancements in #4316 as the argument-mode (pipeline) _complement_ to these operators, not as an _alternative_.

---

As for a _Boolean_ form a la `-issubset`:

I don't have the full picture, but ideally we would enhance the existing `-contains` and `-in` operators to accept an array-valued RHS / LHS:

```powershell
1..4 -contains 3, 2  # -> $True - a RHS is subset of LHS
3, 2 -in 1..4        # -> $True - LHS is subset of RHS
```

What happens currently is that the unsupported array operand is quietly _stringified_ as it would be inside an expandable string, as the following examples demonstrate:

```powershell
3, 2 -in 1, '3 2', 4       # -> $True: 3, 2 was stringified to "3 2"
1, '3 2', 4 -contains 3, 2 # -> $True; ditto.
```

This sounds like a [Bucket 3: Unlikely Grey Area](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area) change to me - i.e., it is unlikely that users depend on this current behavior.

That said, I may be missing important aspects.

**Comment by mklement0** [comment]
@vexx32:

The problem with the 2nd RHS operand is that it's potentially ambiguous:

```powershell
{ 'foo' }, { 'bar' }, { 'baz' }  -contains { 'baz' }, { 'foo' }, { <# ... #> }
```

How do you determine whether the last script block passed is part of the array or whether it is the 2nd operand,  the equality-comparer?

To avoid ambiguity you'd have to _nest_ the RHS array (1st operand), which is awkward.

```powershell
{ 'foo' }, { 'bar' }, { 'baz' }  -contains (, { 'baz' }, { 'foo' }), { <# equality comparer #> }
```

**Comment by mklement0** [comment]
@vexx32: 

Yes, calling _methods_ can be tricky business, given that you're entering a world that wasn't designed with PowerShell in mind. Generally, PowerShell is helpful in anticipating what your intent is when you call methods, but there are definite pitfalls, some of them unavoidable, because they are outside of PowerShell's control, as [this striking example](https://github.com/PowerShell/PowerShell/issues/3809#issuecomment-302804271) demonstrates.

Thus, PowerShell-native features are always preferable.

In this case, however, it seems to me that the only way to get a familiar and predictable PowerShell experience is by _not_ exposing the advanced equality-comparer feature - unless there is a syntax we haven't considered yet that is more PowerShell-like.

Even the awkward _nested_  passing of the RHS array from my previous comment  is ultimately ambiguous.

Consider that all operators that currently accept multiple RHS operands (`-replace`, `-split`, am I missing any?) treat the list of operands as an _array_ and rely on the operands themselves to be _scalars_, which avoids any ambiguity.

So, unless we can come up with an unambiguous syntax that doesn't require unfamiliar syntax for the majority uses cases (where the default equality comparer will do), I suggest we leave the advanced use case of a custom equality comparer to the realm of methods.

**Comment by vexx32** [comment]
I don't think there's a really good way to do this without altering the default array syntax, honestly, or creating a distinct difference between method parameter delimiters and array item delimiters, e.g.,

```powershell
[string]::Split('a', 'b', 'c' | 4 | [System.StringSplitOptions]::None)
```
(That would also be terrible because pipeline, but I'm not sure there're *any* good candidates for such a thing.)
