### ISSUE TITLE
Add a feature that splits an array into arrays each not exceeding the given size.

### ISSUE THREAD

**Issue by mazzy-ax** [PowerShell/PowerShell#7565]
Please, add a feature that splits an array into arrays each not exceeding the given size. 

Analogs:
http://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/chunked.html
http://php.net/manual/en/function.array-chunk.php
https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.array_split.html#numpy.array_split

**Comment by BrucePay** [comment]
Oddly enough, I've been implementing just such a thing related to Task-based programming in PowerShell (see #6716):
```powershell
PSCore (1:191) >  (1..10).PartitionData(3).foreach{"$_"}
1 2 3
4 5 6
7 8 9
10
```
This method creates `ArraySegment[object]` instances for each partition rather than actually building new arrays thus avoiding a lot of copying.
  
Note that there are two ways to do partitioning:

1. Number of items in a partition
2. Total number of partitions.  

Total number of partitions is arguably better for parallel execution since you can number your partitions to match the number of cores on your machine e.g. on a 4-core machine:
```powershell
# count words in 'Way and Peace'
[System.IO.File]::ReadAllLines("WarAndPeace.txt").
    PartitionData(4).
        foreachparallel{
            (-split $_).
                 Count}.
                      Sum()
```
@mazzy-ax  Is this your scenario? Or do you have other things in mind? If so, please share.

**Comment by mazzy-ax** [comment]
@BrucePay, yes, it's my scenario. And parallel processing too :)

> I've been implementing

is it implemented in Powershell or LINQ? 

> foreachparallel

is it PLINQ?

if it is a LINQ/PLINQ then what about a [Restricted and Constained langage](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes)?
I would like to have this basic feature in these modes too.

**Comment by BrucePay** [comment]
@mazzy-ax It's a PowerShell "extension method" (i.e. built-in and implemented in C#) that uses PLINQ for its implementation. Note however, that once you have `Task` support, it can also be implemented as a script method:
```powershell
Update-TypeData -TypeName Object -Force -MemberType ScriptMethod -MemberName foreachparallel  -Value {
    param ([scriptblock] $body)

    $p = [linq.parallelenumerable]::AsParallel(@($this))
    [linq.parallelenumerable]::Select($p, [func[object,object]] $body)
}
``` 
`foreachparallel` wouldn't be available in Restricted language but it might be there in Constrained language as long as we can ensure there are no security holes (e.g. language mode would have to propagate into Tasks created by PLINQ)..
