### ISSUE TITLE
Logon script PS

### ISSUE THREAD

**Issue by domsheldon1** [PowerShell/PowerShell#7568]
Hello,
Below is my logon script on PS command.

The code works very well.

But! All users have shared folders at Windows logon (with rights and no access rights).

How can I view only users' shared folders with access to the directory.

I am sorry for my bad english.

$ndriveobj = New-Object -Com wscript.network
$ndriveobj.RemoveNetworkDrive("G:", $true, $true)
$ndriveobj.MapNetworkDrive("G:", "\\TRIESTE\home", $true)
$ndriveobj.RemoveNetworkDrive("H:", $true, $true)
$ndriveobj.MapNetworkDrive("H:", "\\TRIESTE\Secteur accompagnement", $true)
$ndriveobj.RemoveNetworkDrive("I:", $true, $true)
$ndriveobj.MapNetworkDrive("I:", "\\TRIESTE\PARAMEDICAUX", $true)
$ndriveobj.RemoveNetworkDrive("J:", $true, $true)
$ndriveobj.MapNetworkDrive("J:", "\\TRIESTE\SECRETARIAT", $true)
$ndriveobj.RemoveNetworkDrive("K:", $true, $true)
$ndriveobj.MapNetworkDrive("K:", "\\TRIESTE\Secrétariat Direction", $true)
$ndriveobj.RemoveNetworkDrive("M:", $true, $true)
$ndriveobj.MapNetworkDrive("M:", "\\TRIESTE\LIBRE2", $true)

**Comment by MaximoTrinidad** [comment]
First, as required when submitting issues for PowerShell Core, you need to provide the $PSVersion for either  GA or Preview in order to make sure it can be address properly.

As in mention in the PowerShell Core landing page under section "Windows PowerShell vs PowerShell Core" https://github.com/PowerShell/PowerShell#windows-powershell-vs-powershell-core.   If this is a Windows PowerShell issue, please create the issue under the Uservoice forum at: https://windowsserver.uservoice.com/forums/301869-powershell

Thanks!

**Comment by domsheldon1** [comment]
Thank you for your interest. I am in "Windows PowerShell"

**Comment by KevinMarquette** [comment]
@domsheldon1 It looks like you have a question about how to perform a certain task in PowerShell. I recommend you post your question in a PowerShell support forum like [TechNet](https://social.technet.microsoft.com/Forums/en-US/home?forum=winserverpowershell), [PowerShell.org](https://powershell.org/forums/), or [/r/PowerShell](https://www.reddit.com/r/PowerShell/)
