### ISSUE TITLE
Add `-IgnoreCase` switch to Get-Item and Get-ChildItem

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#7578]
Linux is inherently case-sensitive while Windows and macOS are case-preserving.  To make it easier to work with Linux, consider adding `-IgnoreCase` switch to `Get-Item` and `Get-ChildItem`.  Of course, we would need to pass this to Providers so they work correctly (Environment Variables, for example, are also case-sensitive on Linux).

**Comment by edyoung** [comment]
What about Remove-Item, Get-Content, and other base cmdlets which take paths as input?

**Comment by SteveL-MSFT** [comment]
This issue was brought up internally, would like to see more community feedback to justify further investigation.

**Comment by mkarbo** [comment]
I support this initiative, and have myself spent time trying work around this. It should be default

**Comment by SteveL-MSFT** [comment]
We've fixed the issue with tab-complete to be case-insensitive on Linux, so this should be less of an issue.  Since this was opened almost a year ago, I haven't seen much feedback that this is an issue, so closing it.

**Comment by Luso0** [comment]
(7.2.5) Might still be a problem on Windows. 

Seems fixed on [Linux](https://cdn.discordapp.com/attachments/435586261529395232/1000120808531836968/unknown.png), but [Windows ](https://cdn.discordapp.com/attachments/435586261529395232/1000123326401888286/unknown.png) is still confused. Might just be a Windows problem for being case insensitive.

**Comment by okibcn** [comment]
@SteveL-MSFT I don't think case-insensitive tab completion is enough to close this issue. I find this different behavior between the Windows and Linux implementation of Powershell Core is too relevant. I find it very difficult to make scripts compatible with Linux and Windows because of this. I was hoping to see pwsh more coherent in all the implementations.

**Comment by aguzev** [comment]
1. With the `-IgnoreCase` switch a file name becomes a wildcard for a case-sensitive provider, e.g. Linux file system, SQL Server for a case-sensitive instance. Supporting wildcards may involve different cmdlet behavior and scripts.

1. How deep should it go into the wonderful world of string comparison issues like Unicode normalization or distinction between hyphen and Em dash?

**Comment by okibcn** [comment]
Not really, a ignore case would affect only those codepoints that have capital letters. So, no dash/em dash or other side effects. Actually, it is already implemented in Windows Powershell. There are other different behaviors between the Linux version and the Windows version of the pwsh shell. For instance, the wildcard expansion behaves differently too. In Linux some wildcard requires being within quotes or double quotes for them to work properly in all cases, something not required when pwsh runs on Windows.

The main point here is that pwsh should be as close as possible, and the cases sensitive thing is fixable.

**Comment by aguzev** [comment]
@okibcn, sorry for bad wording. 

My first point was that `-IgnoreCase` is just another wildcard mechanism, and it brings trouble since it results in multiple items being returned.

The second point was not about `-IgnoreCase` effect on dashes. Dashes were just a little example of many string comparison issues besides case sensitivity.
