### ISSUE TITLE
SDK question / comment regarding Write methods

### ISSUE THREAD

**Issue by jherby2k** [PowerShell/PowerShell#7668]
using the SDK, I can:

WriteError(new ErrorRecord(…));
WriteInformation(new InformationRecord(…));
WriteProgress(new ProgressRecord(…));

but I can't do that with a DebugRecord or WarningRecord (WriteDebug and WriteWarning only accept a string). Any good reason for this?

**Comment by jherby2k** [comment]
Furthermore (and recognizing that backwards compatibility has to be preserved) why aren't these all just Write() overloads?

**Comment by SteveL-MSFT** [comment]
@BrucePay, @JamesWTruher, or @HemantMahawar may have some historical context.

**Comment by BrucePay** [comment]
@jherby2k First

> why aren't these all just Write() overloads?

`WriteObject()` takes all objects and writes them to the output stream, regardless of type. Think about how `2>&1` works - error records are routed into the output stream and written to output along with everything else. (As an aside - note that the API is `WriteObject()` but the corresponding cmdlet is `Write-Output`. Originally they were both 'Object'. We changed the cmdlet but didn't get around to changing the API.)

As to why the others take strings rather than complex objects, at the time (version 1)  we were focused on ease-of-use of the APIs over pretty much everything else.  (Remember we got into the PowerShell business because teams kept telling us it was to hard to write command line tools for Windows. Making things as easy as possible was a key driver.)  In retrospect, this was a mistake. We should have had specific types for each stream and still kept the ease of use with overloads. In fact we retrofitted a `VerboseRecord` type into PowerShell in V2(?). Originally it was just a string too. And in the `[PowerShell]` API, everything is strongly typed. So why not just change all of the remaining APIs? IIRC it had to do with not breaking public APIs (specifically ICommandRuntime). Now we essentially did that with `ICommandRuntime2` to accommodate the Information stream so maybe it's not something we should be so worried about now.
