### ISSUE TITLE
ConvertTo-Json string escaped handling differs between PS and PSCore

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/PowerShell#7693]
Steps to reproduce
------------------

On PowerShell Core 6.0.4
```powershell
ConvertTo-Json -InputObject @{ 'abc' = "'def'" }
```

Expected behavior
-----------------

Windows PowerShell 5.x returns:
```none
{
    "abc":  "\u0027def\u0027"
}
```

Actual behavior
---------------

PowerShell Core 6.0.4 returns:
```none
{
  "abc": "'def'"
}
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.4
PSEdition                      Core
GitCommitId                    v6.0.4
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

This would appear to be because the `StringEscapeHandling` setting is set to `Default` in https://github.com/PowerShell/PowerShell/blob/667175767c6a28846280d6102b4bd95f5103412b/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertToJsonCommand.cs#L128

If the `StringEscapeHandling` setting is set to `[Newtonsoft.Json.StringEscapeHandling]::EscapeHtml` then the JSON string that is generated matches what is returned by Windows PowerShell.

![image](https://user-images.githubusercontent.com/7589164/44967263-093fd900-af94-11e8-9d40-31e5c3903485.png)

**Comment by iSazonov** [comment]
@markekraus Please look the Issue.

**Comment by mkht** [comment]
Is not it a destructive change to change this behavior?

How about add parameter to change behavior like below ?

```PowerShell
ConvertTo-Json -InputObject @{ 'abc' = "'def'" } -EscapeHandling Default
ConvertTo-Json -InputObject @{ 'abc' = "'def'" } -EscapeHandling EscapeNonAscii
ConvertTo-Json -InputObject @{ 'abc' = "'def'" } -EscapeHandling EscapeHtml
```

**Comment by SteveL-MSFT** [comment]
This has been the behavior since we changed to using NewtonSoft.JSON from the .NET Framework JSON serializer and would be a breaking change to change it back.  @mkht's suggestion to add a parameter would work and give more flexibility to the user.  However, are there other settings that should be exposed via the cmdlet?

**Comment by mkht** [comment]
Confirmed NewtonSoft's [reference](https://www.newtonsoft.com/json/help/html/Properties_T_Newtonsoft_Json_JsonSerializerSettings.htm).
I think that there is no other setting that needs to be exposed.
Other handling settings such as `DateFormatHandling` can be replaced by formatting the properties of the object to be passed in advance.

If you are adding parameters for escape handling, it will be necessary to discuss how to do the default value.
I think it should be `[Newtonsoft.Json.StringEscapeHandling]::EscapeHtml`. That's because JSON standard requires that quotation marks must be escaped. However, to avoid destructive changes, it should be `[Newtonsoft.Json.StringEscapeHandling]::Default`.

**Comment by mkht** [comment]
Sorry, I had a misunderstanding.

Latest JSON standard (RFC 8259) requires that the `QUOTATION MARK (U+0022)` must be escaped.
But, other quotation marks such as `RIGHT SINGLE QUOTATION MARK (U+2019)` or `APOSTROPHE (U+0027)` is not required to be.
Now, I think that the default setting should be `[Newtonsoft.Json.StringEscapeHandling]::Default`.

https://tools.ietf.org/rfc/rfc8259.txt
> All Unicode characters may be placed within the quotation marks, except for the characters that MUST be escaped: quotation mark, reverse solidus, and the control characters (U+0000 through U+001F).

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agrees that `Default` should stay as default and we should expose `-EscapeHandling` as an optional parameter.
