### ISSUE TITLE
Cannot override DefaultCommandPrefix with empty prefix

### ISSUE THREAD

**Issue by cspotcode** [PowerShell/PowerShell#7753]
I can't figure out how to import a module without a command prefix, when the module's manifest specified a `DefaultCommandPrefix`.  Passing the empty string to `Import-Module -Prefix` does not work.  I also tried passing `[string]::empty`.

Steps to reproduce
------------------

Create the following script module.
```powershell
# test.psd1
@{
    ModuleVersion = '0.0.1'
    FunctionsToExport = '*'
    RootModule = 'test.psm1'
    DefaultCommandPrefix = 'Foo'
}
```

```powershell
# test.psm1
Function Test-Function {}
```

```
Import-Module ./test.psd1 -Prefix ''
(Get-Command -Module test).Name
```

Expected behavior
-----------------

```none
Test-Function # <- does not have a prefix
```

Actual behavior
---------------

```none
Test-FooFunction # <- DefaultCommandPrefix is applied
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Linux 4.4.0-17134-Microsoft #112-Microsoft Thu Jun 07 22:57:00 PST 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by cspotcode** [comment]
This might be the culprit, but I've barely scratched the surface of Import-Module's code, so I'm sure there's a lot I'm missing.

https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs#L6928

**Comment by iSazonov** [comment]
I don't see feedbacks for the scenario. We need to have a real business scenario to understand if a fix needed.

**Comment by drmacro** [comment]
Business Scenario:

I just implemented a module for a non-trivial system we're implementing. The module defines a default prefix to ensure there are no conflicts from a naive import of the module but in fact the module's cmdlets do not conflict with anything we normally have installed, so it would be convenient to be able to override the default module with an empty prefix.

Of course we could define the module with no prefix but then any import would need to specify a module prefix explicitly, which we could not guarantee.

**Comment by iSazonov** [comment]
@drmacro I see a contradiction:
- in fact the module's cmdlets do **not conflict** with anything
- we could define the module with no prefix but then **any import** would need to specify a module prefix explicitly

**Comment by drmacro** [comment]
It's not a contradiction because there's *no guarantee* that our cmdlet names don't conflict with anything in a given user's environment--our names are pretty generic and so could easily conflict.

But the bigger point is putting the burden on users to 1) know they need to specify a prefix at import time and 2) do it is a pretty high bar when we can easily set a default prefix, which ensures that *by default* there are no conflicts.

The documentation for our module reflects the default prefix.

But a user who understands what they're doing and is therefore able to:

1) Determine that this module has no name conflicts
2) Set the -prefix value on their import, wherever it might be

Should be able to *remove* the prefix, which they cannot do today.

That is, setting a default prefix for a module should, I think, be the norm, with removing it being a special action.
