### ISSUE TITLE
Dot-Property Access for Hashtable/Dictionary keys HIDES property values

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#7758]
@PowerShell/powershell-committee
@rjmholt (I can't tag them, apparently, heh!~)

Per discourse in #7736, opening this for hashtable key > property precedence and dynamic binding issues.

Steps to reproduce
------------------

```powershell
$Hash = @{
    Keys = "No keys for you!"
}
```

Expected behavior
-----------------
When accessing .Keys property, the keys of the hashtable should be listed. Properties (statically-bound, part of the parent object) should have *higher* precedence than keys in the hashtable, which are d

```none
PS> $Hash.Keys
Keys
```

Hashtable keys *should be* lower precedence, because the native key access syntax `$Hash['Keys']` is already an alternative and should be preferred in most cases regardless. The key->dot-property mapping is syntactic sugar and should not override actual object properties.

Actual behavior
---------------
The key named 'keys' is accessed instead, preventing listing of the hashtable keys without some trickery in amongst `.PSObject.Properties`
```none
PS> $Hash.Keys
No keys for you!
```
This behaviour is reflected the same way for all hashtable object properties -- specifying a key in the table that has the same name as a property will mask the property and make it inaccessible, with the *sole exception* of the hidden `.psobject` property.

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Interestingly, the logic is _reversed_ in the context of _member enumeration_ (collection-level properties shadow element properties), which prompted #7445 (see https://github.com/PowerShell/PowerShell/issues/7445#issuecomment-411206651 in particular).

To spell out the - obscure - workarounds:

```powershell
# Simplest: .get_Keys()
PS> @{ Keys = "No keys for you!"; Foo = 'bar' }.get_Keys()
Keys
Foo

# Via .psobject.properties
PS> @{ Keys = "No keys for you!"; Foo = 'bar' }.psobject.properties['Keys'].Value
Keys
Foo
```

**Comment by BrucePay** [comment]
The current behaviour is by design and has been this way since V1. And while the behaviour is problematic in some cases (e.g. accessing the `Keys`, `Values` and `Count` properties), changing it would be a significant breaking change. Also, the workarounds, while obscure, are not difficult: `.get_Count()`, `.get_Keys()`, `.get_Values()`.

@mklement0 
> Interestingly, the logic is reversed in the context of member enumeration (collection-level properties shadow element properties), 

These are two entirely unrelated things. The hashtable behaviour predates member enumeration by about a decade. 

Historical note:  this behaviour dates from the earliest iterations of the language, modeled on Perl's hashtable/object behaviour. In these very early versions, hashtables were written as
```powershell
@{
    one => 1
    two => 2
    method => { ... }
}
```
At this point, the fact that there was a .NET class underlying hashtables was not really relevant (hence the hiding of the .NET properties). Hashtables were pseudo-objects which included "methods": assigning a scriptblock to a key allowed you to invoke that key as `$table.method(...)`.  Later on, where we introduced the ability to add instance members with `Add-Member` the "method" mechanism was removed. Around this time, the separator was also changed from `=>` to `=` but the property hiding was never cleaned up.

**Comment by mklement0** [comment]
Thanks for giving us the history, @BrucePay.

> These are two entirely unrelated things. The hashtable behaviour predates member enumeration by about a decade.

Unfortunately, that still makes it an inconsistency that can trip people up, because _conceptually_ these things _are_ similar.

With a commitment to backward compatibility, there is no good solution. Yes, the workaround is simple, but it being obscure is bad enough in itself.

For member enumeration, the proposed `@.` offers a clean solution, but, due to the reversed logic, that is not an option for hashtables.

**Comment by mklement0** [comment]
Good point about index notation being an unambiguous way to target _entries_, @vexx32.

While I too wish we could change the current logic, I think the backward-compatibility problem is more serious than you think:

>  in the way that is likely to be expected by anyone who knows the barest basics of hashtables.

In the context of _PowerShell_, you may never need to access any of a hashtable's _properties_ from your code, which means existing code may live happily - without symptoms - with hashtables such as the following:

```powershell
$ht = @{ Values = 'values'; Keys = 'keys'; Count = 'chocula'  }
```

Only if the code uses dot notation _and expects it to give precedence to the hashtable's own properties_ do you have a problem, and that code would _currently_ be broken. 
And you can definitely use hashtables without ever touching the type's instance properties directly.

Conversely, someone using `$ht.Values` in their code to target the _entry_ will see their code break, if we reverse the logic.

Someone who knows that dot notation targets _entries_ first would probably not construct such a hashtable (though may still be _given_ one), but given that we're discussing this only now, the behavior is probably not widely known - and one of the nice things about PowerShell is that you don't _have_ to be intimately familiar with the underlying .NET types.

Ultimately, only a dedicated entry-accessor syntax form solves the problem - which we do have in `[...]` for hashtables, and which is proposed as `@.` for list-like collections (member enumeration) - but taking away dot notation for entry access now can definitely break things.

You could argue that dot notation should never have been implemented for hashtable-entry access and member enumeration, but those ships have clearly sailed, and the flip sides are convenience and familiarity.

The member-enumeration case is less problematic, because it does give precedence to the list's own properties (and you can use enumeration to ensure that you're targeting _entries_), but it sounds like we'll have to live the `.get_<propName>()` workaround for hashtables, unless someone conducts thorough analysis to demonstrate that little code, if any, is likely to break.

**Comment by adamedx** [comment]
What a surprise in a bad way -- I can't believe the language would do something like this. I filed a doc bug to make this more visible, we probably need to add any property accessors like `keys` to the linter for PowerShell in tools like vscode if they don't already catch that (I have not seen that they do).

Languages should not have non-deterministic behavior, especially if it's not documented. At this point I understand the arguments about not just "fixing" it due to the fix itself breaking code, but if we can't invent a mode called "don't alter the behavior of .net types at runtime", then at the very least let's identify a syntax for accessing collections without strange workarounds. If I add `get_Keys()` to my code everywhere, someone else is likely to come along and change it back to `Keys` because they have no idea about this unexpected (and frankly crazy) behavior.

**Comment by rkeithhill** [comment]
Another option is to create a `PSScriptAnalyzer` rule that flags hashtable property names that correspond to underlying .NET properties like `Keys` and `Values`.
