### ISSUE TITLE
[PSCore 6.1] In WSL, PSReadLine color for parameter values is black (doesn't work on default black background)

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell#7785]
After updating PowerShell Core 6.0.4 to 6.1 in WSL (Ubuntu distro), I've noticed that I don't see what I type when I type parameter values.
Changing background color not to be black (default) revealed that parameter values are printed in black thanks to PSReadLine module.
Removing PSReadline module made everything visible again.

**Comment by rkeithhill** [comment]
I think this is an issue with the Windows WSL default console color scheme.  If you look at the color properties:

![image](https://user-images.githubusercontent.com/5177512/45563333-444ed180-b80a-11e8-9b8d-a91ad8c85a49.png)

You'll probably see that DarkGray (index 8) is set to the same value as Black (index 0).  Try lightening the index 8 color (DarkGray) to 169,169,169 (hex a9a9a9).  That's why you can't see parameters (and operators) because PSRL is configured by default to use index 8 (or `` "`e[90m"`` - bright foreground).

**Comment by alexandair** [comment]
@rkeithhill All I know is that it worked with PowerShell Core 6.0.4. And I haven't played with console properties.
Proposed values 169,169,169 are too light on my system. 
<img width="284" alt="properties" src="https://user-images.githubusercontent.com/3135708/45564483-884bd180-b81e-11e8-8d51-675639ae666f.png">

**Comment by rkeithhill** [comment]
Make sure you set the `Screen background` back to index 0 before closing the dialog.  Then it should look better.  But ultimately, perhaps PSRL should use a different parameter/operator fg color.

**Comment by alexandair** [comment]
@rkeithhill I forgot to mention that I don't see the same issue on PSCore 6.1 installed on Windows where background color is also black. Parameter values are here printed in bright color and are visible.

**Comment by rkeithhill** [comment]
The PowerShell Core console configuration is different by default than the WSL color config.  So that doesn't surprise me.  I, OTOH, don't use the default PS Core color config.  I use `colortool` to set my color scheme to `OneHalfDark` and that does exhibit this same issue - Black and DarkGray use the same color value.

**Comment by taladar** [comment]
The same issue (DarkGray being displayed as black) also affects Windows Powershell on Windows Server 2016 when used via Win32-openssh (as of version 8.9) and Powershell Core (as of 7.2.2) on Windows Server 2012 R2 and 2016.

A workaround is to add

```
Set-PSReadLineOption -Colors @{ "Parameter" ="`e[39m"; "Operator" = "`e[39m";"InlinePrediction" = "`e[39m" }
```

to your Powershell Core profile and

```
Set-PSReadLineOption -TokenKind Operator -ForegroundColor Gray\nSet-PSReadLineOption -TokenKind Parameter -ForegroundColor Gray
```

to your Windows Powershell profile on the affected systems.
