### ISSUE TITLE
Add parameter name and value completion for hashtables used for splatting

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#7789]
When getting completion results while in a hashtable that is used for splatting, completion should treat keys as parameter names and values as arguments.

This would be easiest supported easiest when

1. The `HashtableAst` is on the RHS of an `AssignmentStatementAst`
1. A `VariableExpressionAst` is on the LHS
1. The same variable is splatted in a `CommandAst`

Ideally completion features would be the same as when in the `CommandAst`, such as

1. Keys are completed as parameter names
1. Values would take `ArgumentCompleter`, `ValidateSet`, `Enum` typed parameters, etc into account
1. Parameters already bound in the `CommandAst`  would be excluded

/cc @TheIncorrigible1

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
@BrucePay 

Using this example

```powershell
$splat = @{
    Pa
}

Get-ChildItem @splat
```

If tab was pressed with the cursor after `Pa` then `Path` would be a completion result.

**Comment by mklement0** [comment]
@SeeminglyScience: Because it took me a while to figure out the intent myself, via the linked VSCode issue, let me try to clarify if my understanding if what you're asking for is correct:

Given a hashtable literal assigned to a variable (`$splat`) that is _later_ used for splatting (`Get-ChildItem @splat`), you want tab completion _inside the hashtable literal_ to complete the parameter names of the cmdlet in whose context said splatting later happens.

Correct?

**Comment by SeeminglyScience** [comment]
@mklement0 Exactly! Thanks for clarifying :)

**Comment by rjmholt** [comment]
This and a few other ideal features (like for `Add-Type`, `Import-Module` and `Get-Command`) would probably benefit from some kind of constant-folding analysis. Which starts to blur the lines on what PowerShell ought to be doing, because it's not really responsible for that kind of optimisation. But just thought I'd mention it, since I keep seeing similar scenarios for it.

**Comment by JustinGrote** [comment]
For reference, tab completion of hashtable properties for a later-splatted command was implemented in PS7.2+ and this can probably be closed.
