### ISSUE TITLE
Start-Process -WindowStyle Minimized steals focus

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7790]
It's fair to assume that you typically do _not_ want the newly created, minimized window to steal focus from the calling application when you use `Start-Process -WindowStyle Minimized`.

That is, the calling application (console window) should remain the active application and continue to receive keyboard output.

Currently, `-WindowStyle Minimized` invariably focuses the minimized window - while the calling window is by definition not _obscured_, it loses _keyboard focus_ that way.

Two possible enhancements:

* Change `-WindowStyle Minimized` to _not_ steal focus.

* Since that is technically a breaking change - someone may rely on the old behavior, though I have trouble picturing why - alternatively introduce a new style, `MinimizedNoFocus` similar to Visual Basic's [`[AppWinStyle]`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.appwinstyle) enumeration. 
  * Conceivably, `NormalNoFocus` could be implemented too (that is, start a process with normal window size, but without giving it focus).

_Update_:

A related, but distinct issue is #3028, which concern's the CLI's (the `pwsh` executable's) `-WindowStyle` parameter, notably the ability to start PowerShell as a whole _hidden_.

Environment data
----------------

Written as of:

```powershell
PowerShell Core 6.1.0
```

**Comment by BrucePay** [comment]
This is basically the same issue as #3028 and the solution is the same: create a windows host for PowerShell as opposed to the existing console host.

**Comment by mklement0** [comment]
@BrucePay:

This issue and #3028 are distinct use cases:

* #3028 is about launching _PowerShell itself_,  _completely and persistently hidden_, which is currently impossible without the help of a non-console-subsystem entry point, as proposed in the linked issue.

* _This_ issue is about launching processes _from PowerShell_ (a visible console window) in a way that:

  * launches them asynchronously, _initially out of sight_ 
  * yet still allows inspecting their output _interactively, on demand_

**Comment by mklement0** [comment]
Thus - unless you see a flaw in my clarification - please remove the `Resolution-Duplicate` label from this issue, @BrucePay.

**Comment by BrucePay** [comment]
@mklement0 You didn't mention `Start-Process` in the issue so I assumed you were talking about `pwsh` itself. Thanks for clarifying. Perhaps you could update the issue text to include this information. As to supporting this functionality, the API you mentioned is only available by including the VisualBasic assembly which isn't likely in Core.  It should be possible to use interop to implement the equivalent in pwsh but it would be better if it were supported in CoreFx since it is a base OS kind of thing. I'm inclined to mark it as "resolution external" but I suppose some enterprising individual could decide to do it in PoweShell instead.
