### ISSUE TITLE
Invoke-WebRequest keeps downloading a file way beyond its size

### ISSUE THREAD

**Issue by noserati** [PowerShell/PowerShell#7822]
To repro:

`powershell wget https://storage.googleapis.com/chrome-infra/depot_tools.zip`

The file size is ~19MB, but the download progress goes way beyond and has to be manually stopped.
At the same time, `(New-Object System.Net.WebClient).DownloadFile()` works correctly.

**Comment by BrucePay** [comment]
HI @noserati  I tried this out and it definitely repros on Windows PowerShell (5.1) but not on PowerShell Core 6. Since this repo is for the development of PowerShell 6, it's not the right place to file issues for PowerShell 5 or earlier. For those versions, please use [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell) . Thanks.

**Comment by noserati** [comment]
Hi @BrucePay, thanks, [done](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/35465590-bug-invoke-webrequest-keeps-downloading-beyond-th), please up-vote there.
