### ISSUE TITLE
Changing console window properties are not being saved

### ISSUE THREAD

**Issue by NJ-Dude** [PowerShell/PowerShell#7825]
Steps to reproduce
------------------

```powershell
1. Open the PowerShell Core console
2. Click on the PS icon on the left top corner
3. Click on Properties
4. Change the Font size (whatever value you like)
5. Click OK
```

Expected behavior
-----------------

```none
The values will be saved.
```

Actual behavior
---------------

```none
The following error occurs and no changes are saved:
```
![capture](https://user-images.githubusercontent.com/38812914/45791572-3ceb5600-bc58-11e8-902b-63959c2eca4d.PNG)
Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by NJ-Dude** [comment]
![capture](https://user-images.githubusercontent.com/38812914/45791502-ea119e80-bc57-11e8-876f-89ad5de0bcc4.PNG)

**Comment by NJ-Dude** [comment]
I don't know why the picture is not showing but this is the error:

![capture](https://user-images.githubusercontent.com/38812914/45791677-a5d2ce00-bc58-11e8-946d-44b8598a2c5d.PNG)

**Comment by mklement0** [comment]
Re formatting:

The picture isn't showing in your initial post, because you placed the markdown expression _inside a fenced code block_ (e.g., `` ```powershell...``` ``), where it isn't recognized and treated as a literal.

Generally, please only put _code_ or _code output_ in fenced code blocks, not images and prose such as "The values will be saved."

**Comment by mklement0** [comment]
The **problem** stems from the fact that the shortcut that you're trying to modify is located in a folder that requires _elevation_ (running as an administrator) in order to write to it (`"$env:ProgramData\Microsoft\Windows\Start Menu\Programs\PowerShell"`)

In other words: this is a permissions problem, but the error message is woefully inadequate.

Note that the issue only occurs if you launch PS Core from the _Start Menu_.

---

As for **workarounds**:

If you copy the shortcut file (`*.lnk` file) to a user location, the problem goes away, and this can be done _implicitly_:

* Either:  Launch PS Core via the Start Menu, pin it to the Task Bar, and launch PS Core from there in the future.

* Or: Drag the PS Core shortcut file from the Start Menu to your Desktop, for instance, and launch PS Core from there in the future.

Future windows launched this way will _not_ exhibit the problem, because their originating shortcut is now in a location that even your non-elevated processes can write to.

An ad-hoc alternative is to stick with the Start Menu shortcut, but invoke it _as an administrator_ in order to change the window properties (right-click on the icon in the Start Menu and select `Run as Administrator`) - but note you'll have to do that _every time_ you want to make changes.

---

As for **what needs fixing**:

* The PowerShell installer could create a _per-user_ Start Menu shortcut for PS Core instead of a single, shared one that requires elevation to modify (as an aside, if multiple users try to customize the shortcut, the customizations could collide).

  * This is how `cmd.exe` already does it for its `Command Prompt` shortcut, which is placed in `"$env:APPDATA\Microsoft\Windows\Start Menu\Programs\System Tools"` - for every user.

* The Windows (GUI) Shell should improve the wording of the error message - not sure where to report that.

**Comment by mklement0** [comment]
@NJ-Dude: P.S.: To avoid confusion, please change "session" to "console window" in the issue title.

**Comment by thezim** [comment]
You can also explore using HKCU:\Console in the interim which is under your control.

https://blogs.msdn.microsoft.com/commandline/2017/06/20/understanding-windows-console-host-settings
