### ISSUE TITLE
SDK WriteInformation vs Write-Host

### ISSUE THREAD

**Issue by jherby2k** [PowerShell/PowerShell#7837]
I understand that, via PowerShell 5+, Write-Host is now the same as Write-Information but with $InformationAction = 'Continue'. But how can I achieve the same result as Write-Host from a binary module?

I'd prefer my Information messages to be opt-out, not opt-in. That's what Debug messages are for, IMO.

**Comment by vexx32** [comment]
Debug messages are pseudo-breakpoints, really. So... not the same thing.

And having information messages be opt out is generally considered a bad idea because PS is an automation tool. If you want to code a wrapper function that provides a more user-focused interface, which automatically enables verbose or information streams as it runs subcommands, that's up to you, but it's generally considered best practice to expose automation-focused commands that do not pollute the output stream or the host environment with text the user hasn't explicitly asked for.

That out of the way... I'm not super familiar with how it works, but here's the file for Write-Host (took a bit of searching and digging, but there it is): https://github.com/PowerShell/PowerShell/blob/0f0c46dfe51440470b86f67b258e14aea32fa0aa/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WriteConsoleCmdlet.cs

If you use that as a base, I'm sure you can implement something similar. 😄

**Comment by vexx32** [comment]
You're not entirely wrong; there are some tasks where it's *helpful*... but I wouldn't say it's always needed or should be enabled by default -- personally.

In general, I think it more valuable for PS modules to be *consistent*, but... that's a personal opinion of mine, so if you have something you feel it's needed for, go for it. 😄
