### ISSUE TITLE
PSMore

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#7857]
@lzybkr Could you please share more information about [PSMore](https://github.com/lzybkr/PSMore/) status?

- Can now we integrate the code in PowerShell Core? Step-By-Step or as experimental feature?
- What benefits we expect?
   - Less resource consumption? Less memory allocations? Less CPU consumption?
   - More fast startup?
   - More convenient use for users?
   - Empowerment?

**Comment by lzybkr** [comment]
Status - no progress since the last commit.

The initial idea is basically a console version of `Out-GridView` combined with `less`, then I let myself get sidetracked into the formatting subsystem.

So for I have a prototype of a new way of specifying formatting that:
* uses no xml (so faster startup/module loading)
* uses attributes, so can be specified inline with the type to be formatted
* or can, via proxy, specify formatting on another type
* use code gen with dynamic sites so it's extremely fast

What I probably need the most to continue is some external motivation and some dedicated time. I have other projects I've started - a PowerShell profiler and a PowerShell script formatter, so clearly I have a problem starting projects but not finding time to move them along.

One thought I had on external motivation was to start a charity fundraiser - I'd commit to a project if the charity gets funded. I haven't worked out the charity or the funding target though.

**Comment by iSazonov** [comment]
Thanks! I can not help with  external motivation but I could help with the progress of these projects.

- for PSMore we could continue in the PowerShell repo step by step replacing existing code.
- for PowerShell script formatter we could start adding Trivia like [Roslyn](https://github.com/dotnet/roslyn/wiki/Roslyn-Overview#syntax-trivia). Maybe RFC is right start.
- for PowerShell profiler I don't know what we can do to help the project, perhaps add an API to measure script blocks that can be useful for performance dev test too. /cc @daxian-dbw

**Comment by lzybkr** [comment]
Trivia might make a formatter simpler to implement, but it isn't necessary. The full trivia can be synthesized from the tokens and ast. I have implemented what I think is critical to the formatter - a tree comparer so you can check the formatting won't change the semantics.

As for formatting - I'm not keen on the step by step replacement which is why I started a standalone project. At some point it will make sense to replace existing code, but that's a tricky work that isn't much fun - I speak from experience. Rewarding when it's done, but it takes motivation.

And profiling - I should talk with @daxian-dbw - he might be interested to pick it up.

**Comment by daxian-dbw** [comment]
@lzybkr I'd love to pick up the profiler work. Will sync with you offline on it.

**Comment by iSazonov** [comment]
> Trivia might make a formatter simpler to implement

I think this is enough to do it. In addition, it will not only simplify but also add more features and flexibility. 
If @SteveL-MSFT approves I could start RFC for trivia.

> As for formatting - I'm not keen on the step by step replacement which is why I started a standalone project. 

Do you want to keep this project as personal or maybe make it public like PowerShell/NextEFS?

> And profiling 

The same question - will the project MSFT internal or public like PowerShell/Profiler?

**Comment by iSazonov** [comment]
Related comment from Jason 
https://github.com/PowerShell/PowerShell/issues/4347#issuecomment-434561158
