### ISSUE TITLE
Is it possible to make PsRemoting session interactive and a simple full console editor

### ISSUE THREAD

**Issue by copdips** [PowerShell/PowerShell#7894]
Hello @PowerShellTeam,

I use vim and python repl in windows local session, both work fine.

But over PsRemoting session, none of them works, it seems that this is because Powershell PsRemoting session is not interactive by design. This design makes our windows admin life a little bit tough.

PsEdit for remote editing is not easy to use, and doesn't work for every circumstances.

Would you plan to make PsRemoting interactive in the future ?

Or would you plan to release a simple console mode editor? I'm not expecting to have the same features as vim, just search, edit is largely enough for beginning.

**Comment by copdips** [comment]
Yes, I'd like to raise this issue to call Powershell.team's attention, because I've never heard from their voice about this topic. I really hope of being informed if there's any blueprint.

**Comment by iSazonov** [comment]
> Or would you plan to release a simple console mode editor?

PowerShell is a shell and engine not editor. PSReadline allow to edit history script blocks. For other scenarios, you can always run a more suitable external editor and vim too.

**Comment by copdips** [comment]
I agree that Powershell is not an editor, this is not its job. But I haven't found an editor that works over WinRM so far. Maybe it's impossible for the current version or maybe it's very difficult to implement. 

Perhaps Powershell team (or WinRM team as my wish only refers to the remote session) could release some guidelines to give the developers some ideas how to design a pure Windows console editor. That would be great.

BTW, I love PSReadline a lot, it makes our Windows admin life much happier, thanks for the great work.

**Comment by copdips** [comment]
I found [this blog](https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/) from @bitcrazed talking about the ConPTY, maybe this is the light that we're always looking for.

**Comment by iSazonov** [comment]
Thanks for link to Win32 ConPTY. 
A problem is that the API is only on latest Windows preview builds and PowerShell Core should works from Windows 7 version. We could use winpty and then migrate to ConPTY. Although it looks too difficult to support. On the other hand, it could be an independent project in which an alternative conhost will be implemented (as well as a GUI). All this is said for the local console.
And again, as for remote console, current PowerShell remoting is engine-engine object oriented. Although we use implicitly pty on Unix if transport is SSH there can not be two foreground applications by design. So we'll need to switch between foreground and background on local and remote systems synchronously. This means that we will need to completely remake our conhost, which will require several ported APIs that are not yet available (not only ConPTY).

**Comment by SteveL-MSFT** [comment]
This is a known limitation of PSRP.  However, if you don't need to remote objects from A to B and just want an interactive remote shell that you can use PowerShell, you can always just use ssh and start pwsh on the remote side.

**Comment by copdips** [comment]
Thx for the confirmation, ssh is indeed my current workaround.

**Comment by SteveL-MSFT** [comment]
@copdips there have been discussions and even some experiments to enable console GUIs in PowerShell Core, however, it's not a focus at this time but would love to see it enabled in the future
