### ISSUE TITLE
ValidateRange 

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#7947]
with ValidateRange. You can specify in a convenient new syntax that the value must be positive or negative.

```powershell
[ValidateRange('Positive')]$i = 7
[ValidateRange('Negative')]$i = -3
```
but the result is wrong if one or more space is added between - and number

Steps to reproduce
------------------

```powershell
PS C:\> [ValidateRange('Negative')]$i = - 3
```

Expected behavior
-----------------

```none
PS C:\> [ValidateRange('Negative')]$i = - 3
The variable cannot be validated because the value 3 is not a valid value for the i variable.
At line:1 char:1
+ [ValidateRange('Negative')]$i = 3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
+ FullyQualifiedErrorId : ValidateSetFailure
```

Actual behavior
---------------

```none
NONE
```

Environment data
----------------

```powershell
> $PSVersionTable
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
I don't see a difference in behavior between `[ValidateRange('Negative')]$i = -3` and `[ValidateRange('Negative')]$i = - 3` - and there shouldn't be: it's fine to have whitespace between the unary `-` operator and its operand, and both commands succeed, as expected.

Your "Expected behavior" code contains command `[ValidateRange('Negative')]$i = 3`, which fails, as expected (the number is positive).

Can you clarify what doesn't work as expected?
