### ISSUE TITLE
Enable pwsh ReadLine to use PSReadLine

### ISSUE THREAD

**Issue by edyoung** [PowerShell/PowerShell#7971]
In pwsh on linux, hold down a key, and observe the rate at which characters are added. Then run Read-Host and observe the rate at which characters are added - it is much slower. In both cases I'm just holding down the f key. This is even slower in Cloud Shell, but the issue is reproducible in a regular terminal on ubuntu. The characters are also buffered differently - if you hold down a key and then release it in the normal terminal, input stops quickly after you release it. In Read-Host, the characters are still being added to the input and displayed several seconds after you release the key.

Why does it matter? Several customers have complained. This also shows up when using Get-Credential.

Screen recording below

![read-host](https://user-images.githubusercontent.com/45578/46621935-bd75d780-cadd-11e8-8e77-887e49ac942e.gif)

```powershell
> $PSVersionTable
PSVersion 6.1.0
PSEdition Core
OS Linux 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018
```

**Comment by dend** [comment]
This is affecting the customers' experience with the Cloud Shell on docs.microsoft.com, especially in cases where we work with them to provision Azure resources and they need to specify information such as VM names, passwords or resource group.

**Comment by jianyunt** [comment]
I think I discussed it with @BrucePay before. We also observed the issue. 

These interactive cmdlets including read-host, get-credential are handled by pwsh, yes?
I noticed that if you remove-module psreadline, regular stdout becomes lagging. The behavior is much like read-host and get-cred. Does this mean the lagging could be caused by powershell engine? Of course pwsh depends PSReadline which should not be removed.

**Comment by SteveL-MSFT** [comment]
The issue here is that PowerShell Core ConsoleHost has a very simple synchronous readline implementation.  When you use `Read-Host`, it calls back into the host's `ReadLine()` implementation which is not designed to be performant.  PSReadLine on the other hand is what you use in the console when not using `Read-Host`.  PSReadLine buffers the input asynchronously and renders them on a different thread.

**Comment by vexx32** [comment]
In the efforts of a (hopefully) simple fix, is it possible for PSReadLine to override the Read-Host with a function/cmdlet/alias that works in a similar fashion to how it handles standard input?

**Comment by iSazonov** [comment]
I started some ConHost optimizations, but my PR for ConHost has been awaiting a review for _several months_. I could continue these optimizations, but reviews is required.

**Comment by lzybkr** [comment]
`PSReadLine` could be modified to support `Read-Host`, but it might be simpler and/or smarter to better understand why `Console.ReadLine` is so slow.

To modify PSReadLine to support `Read-Host`, you'd need to:

* Not use the PowerShell syntax coloring
* Not share history, possibly not use history at all
* Add support for reading a secure string
* Disable completion

I've briefly considered a readline implementation that implements parts of the [LSP](https://langserver.org/) for reuse in other tools like `csi` and `fsi`, if that ever gets built, then I think `Read-Host` would be a great use case.

**Comment by SteveL-MSFT** [comment]
I don't think it's Console.ReadLine itself that is slow, but the ReadLine loop in ConsoleHost that is slow.  It's single threaded and does a bunch of processing per key press.

**Comment by iSazonov** [comment]
A tracking issue in .Net Runtime repo https://github.com/dotnet/runtime/issues/800
