### ISSUE TITLE
Removal of "Encoding Byte" is a breaking change

### ISSUE THREAD

**Issue by LeeHolmes** [PowerShell/PowerShell#7986]
The PS Core breaking change guidance is here: https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md

Removal of '-Encoding Byte' is a breaking change from Windows PowerShell. Although certainly a cleaner implementation, it does not meet the bar for breaking changes as identified by the guidance above.

Even if fixing this causes a breaking change for PowerShell Core, that would be far less impactful than the breaking change for users coming from Windows PowerShell.

**Comment by vexx32** [comment]
Are you suggesting that the parameter be restored *alongside* the newer syntax for backwards compatibility? Just trying to clarify what your desired outcome is, really. 😄 

But really, now... can't make an omelette without breaking some eggs. 😉

**Comment by iSazonov** [comment]
The breaking change was approved in #5080

**Comment by LeeHolmes** [comment]
New functionality is great (-AsByteStream is cool). Breaking changes that are not in line with the breaking change contract are not cool - even if previously approved.

**Comment by vexx32** [comment]
Again, what would you suggest? Restoring the `-Encoding` parameter to a loosely-typed collection and add `Byte` back in as an option? I can see why it might be nice to have for backwards-compatibility purposes on occasion, but have people actually *used* `-Encoding Byte` commonly? I really can't say I've ever seen it (not that that means it *shouldn't* be restored, just trying to gauge how serious this issue could be in practice, really).

**Comment by LeeHolmes** [comment]
It's used 161 times in the PowerShell Corpus. (http://aka.ms/powershellcorpus)

![image](https://user-images.githubusercontent.com/11475352/46887516-aeab5f80-ce12-11e8-8cf1-c31867457ea2.png)

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this.  This change occurred prior to the PSCore 6.0 GA where our philosophy included taking opportunity to fix issues that were known to be breaking but improving the platform.  The breaking change contract was authored after 6.0 GA and we certainly have been applying it since.  At this time, without additional customer feedback, it seems that the number of hits in the corpus based on the size of the corpus doesn't justify spending effort to add this back.
