### ISSUE TITLE
Add -LiteralPath parameter to Set-PSBreakpoint

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#7995]
`Set-PSBreakpoint` currently doesn't have a `-LiteralPath` parameter to set breakpoints in scripts. This means that setting a breakpoint in strangely named files like `hello [there].ps1` or on *nix `whoisth*s?.ps1` is harder than it should be.

See https://github.com/PowerShell/PowerShellEditorServices/pull/765 for a scenario where this has caused issues.

**Comment by KirkMunro** [comment]
`Set-PSBreakpoint` doesn't have a path parameter either. It just has `-Script` (which is poorly named, given the confusion with the `ScriptBlock` type).

To resolve this, I propose the following:

1. Treat paths passed into `Get-PSBreakpoint` and `Set-PSBreakpoint` as literal paths.
1. Update the `-Script` parameter on those cmdlets to accept pipeline input by property name.
1. Add `PSPath` as a parameter alias for the `-Script` parameter on each of those cmdlets.
1. Consider renaming `-Script` as `-FilePath` to match other PowerShell cmdlets that accept a literal path with no wildcard support, and add `-Script` as an alias for backwards compatibility.
1. Consider adding a `-Script` (`-FilePath`) parameter that accepts pipeline input by property value with a `PSPath` alias in a new parameter set that would be added to `Enable-/Disable-/Remove-PSBreakpoint` to make it easier for users to turn breakpoints on or off or remove them according to their path with less pipelining.

Rationale:

* Since the `-Script` parameter (or `-FilePath` parameter if we rename it) accepts multiple values, it is trivial for users who actually want to set a breakpoint on multiple files to do so using other cmdlets that support wildcard paths, in a pipeline.
* Today if someone wants to get/set/enable/disable/remove a breakpoint on multiple files, since `-Script` does not support pipeline input, and since that parameter isn't on the enable/disable/remove cmdlets, it is much harder than it should be to do that, requiring all files to be in the same folder or using a loop to set the breakpoints. These changes would make that much easier.

As for risk, these are breakpoint cmdlets, which are intended for interactive use. Someone could have an automated process to set breakpoints on a bunch of files though as part of their dev/test cycle, and be interrupted by such a change. Still, that's dev/test, not production, and I think the risk is pretty low and worth considering.

Thoughts?

**Comment by rkeithhill** [comment]
Maybe these cmdlets should just define the normal `Path/LiteralPath` parameters and configure `Script` as an alias for one of the two?

**Comment by KirkMunro** [comment]
My hesitancy there is:

1. Parameter set bloat. 
1. The breakpoints that are created are associated with actual files, not wildcards, 
1. I sincerely doubt setting a breakpoint using a wildcard adds value today. It certainly doesn't for me, and if it does for others, it's limited to a single folder (i.e. if you want to limit breakpoints to your module, you need to use pipelines/other commands anyway to get all of the files in a folder hierarchy). Also, since it results in one breakpoint being created _per file_ that matches the wildcard, it's not that user friendly. The only use case I can come up with where I might restrict breakpoints to certain files would be if I'm debugging a module and I want to scope breakpoints to all files within that module, which means structure, which means pipelining actual files, not wildcards.

**Comment by rkeithhill** [comment]
Good point on not needing for wildcard support. So OK, only need a `Path` parameter with the appropriate pipeline bindings and aliases for PSPath and Script.

**Comment by rjmholt** [comment]
Wouldn't it be nice if a `-Path` parameter (perhaps with a certain attribute) implicitly included a `-LiteralPath` parameter. I'm sure there are flaws to that idea and here's probably a bad place to discuss it all in full, but just felt I should blurt it out.
