### ISSUE TITLE
Request: DNSServer module for powershell on Linux

### ISSUE THREAD

**Issue by archmangler** [PowerShell/PowerShell#8011]
Getting powershell running on Linux is straightforward. 

Unfortunately this is based on .NetCore which excludes a lot a important functionality and modules e.g the DNSServer module. It's not installable on Linux using powershell gallery:

```
PS /home/gmonkey> Install-Module -Name DNSServer -Scope CurrentUser
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'DNSServer'. Try Get-PSRepository to see all available registered module repositories.
At /opt/microsoft/powershell/6/Modules/PowerShellGet/PSModule.psm1:9491 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

Is there a workaround to obtain a fully functional PowerShell installation on linux including modules that don't appear in .NetCore (specifically DNSServer) ?

**Comment by SteveL-MSFT** [comment]
The current DNSServer PowerShell module that is in Windows is specific to managing Windows DNS Server and wouldn't work on Linux.  If you want to manage Windows DNSServer using the PowerShell module from Linux, you can do this via PowerShell remoting.  Using [implicit remoting](https://technet.microsoft.com/en-us/library/ff720181.aspx) you can run scripts locally on Linux that actually execute remotely on the Windows target (after setting up the PSSession).

If the ask is to manage Linux DNS servers, then that would need to be a completely different module that someone would have to author.

**Comment by SteveL-MSFT** [comment]
You can always use `ssh` to execute remote commands without using PowerShell remoting.  It's more of a user choice which experience they want.

**Comment by aaronk1** [comment]
@SteveL-MSFT do I understand correctly the recommendation is to connect to a Windows machine to run the DNS cmdlets instead of running them locally on a Linux machine?  Agree it would be nice to have this functionality on Linux.  We have the same need as @archmangler and are currently connecting over WinRM with our ansible installation using pywinrm to access the DNS cmdlets with Powershell.  In ansible it can be as simple as using this (URL below), but it's better to avoid WinRM as it has a laundry list of its own problems.  

@archmangler FYI I was able to get nsupdate to work at Linux command line a while back with Windows DNS Server.  Again, not "Windows-specific" and not supported by MSFT, though.

https://docs.ansible.com/ansible/latest/modules/win_command_module.html
