### ISSUE TITLE
PS Remoting: New-PSSession with -HostName and -SSHTransport doesn't support non-interactive credentials

### ISSUE THREAD

**Issue by archmangler** [PowerShell/PowerShell#8035]
Powershell doesn't seem to support non-interactive provision of password+username with the New-PSSession and -HostName parameters. This makes it virtually impossible to script a non-interactive PSSession solution meant to operate within a larger automated system (e.g Terraform or Ansible wrapper).

Steps to reproduce
------------------

```powershell
PS /home/gmonkey/scripts> $session = New-PSSession -HostName windns -Credential $cred -SSHTransport
New-PSSession : Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
At line:1 char:12
+ $session = New-PSSession -HostName windns -Credential $cred -SSHTrans ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [New-PSSession], ParameterBindingException
+ FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.PowerShell.Commands.NewPSSessionCommand
```

Expected behavior
-----------------

```none
Following credential creation like this:

$cred = new-object -typename System.Management.Automation.PSCredential -argumentlist "Administrator",$pw

The following command should accept credentials non-interactively:

$session = New-PSSession -HostName windns -Credential $cred -SSHTransport

```

Actual behavior
---------------

```
New-PSSession doesn't accept credentials with the  -HostName parameter, which makes it difficult to script PSSremoting solutions interactively.
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Linux 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by Justiii3** [comment]
Hello,

As per my knowledge so far about PS remoting over SSH -Credentials is not supported, not sure when this will be fixed, however my workaround is to enable public key authentication, creating SSH RSA key from the source server and using it to connect this way(removes the need for credentials). Please be advised that If you try to host Powershell core remoting scripts in dotnet core console app using C# this may not work because in my case AddScript Method does nothing and does not execute the remoting  scripts . Have an issue raised for this https://github.com/PowerShell/PowerShell/issues/7984 . 

Here is a guide that will help you configure key based authentication: http://www.centinosystems.com/blog/powershell/using-passwordless-powershell-remoting-using-openssh-on-windows/

FYI: Once you have this configured you can just move the keyfile somewhere and ask the remoting command to use it by using -KeyFilePath parameter.

Hope this helps.

**Comment by archmangler** [comment]
@Justiii3 - thanks for the feedback. I was hoping to avoid key based authentication (though in my opinion it is much better). The problem is that in many large organisations, the teams responsible for managing windows systems are not familiar with key-based authentication, their operations are limited purely to passwords and username based credentials allocated via AD. Which means that all access they're willing to provide will be in the form of a username and password.

**Comment by SteveL-MSFT** [comment]
Public key auth is the recommended way to go.  To support `-Credential` for username/password, we need https://github.com/PowerShell/PowerShell/issues/5782

**Comment by chuanjiao10** [comment]
As far as I know, the third-party ssh client module **winscp** supports passwords pre-saved in text.

**Comment by ShowMeTheGita** [comment]
This issue is still up. I cannot use the solution proposed by @Justiii3 due to having my script on an Azure Automation runbook. Locally, via prompt credentials it works perfectly. Using -HostName and -Credential flag does not:
`New-PSSesion -HostName $hostpublicip -Credentials $creds`

Ends with error:
`New-PSSession: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.`

**Comment by niko-la-petrovic** [comment]
@ShowMeTheGita Same issue here. Running 
`
Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

`

**Comment by SteveL-MSFT** [comment]
#5782 is what you folks want

**Comment by G31st** [comment]
This must be a joke right ? How can they not support credentials via variable ?!
