### ISSUE TITLE
Introduce some kind of sanity to coercions

### ISSUE THREAD

**Issue by masaeedu** [PowerShell/PowerShell#8043]
In order to manipulate some config files, I need to deserialize some JSON that represents an array of strings, apply a transformation to each string, and serialize the resulting array back to JSON.

Most of my time on this task has been spent discovering the many wonderful surprises in Powershell's system of coercions between arrays of various lengths, non-arrays, and nulls.

```powershell
#!/usr/bin/env pwsh
# Let's try an array with two elements
$x = '["foo", "bar"]'
$result = ConvertTo-Json ((ConvertFrom-Json $x) | % { "Hello, $_" })
echo $result
# [
#  "Hello, foo",
#  "Hello, bar"
# ]

# So far so good

# But what about a 1-element array?
$x = '["foo"]'
$result = ConvertTo-Json ((ConvertFrom-Json $x) | % { "Hello, $_" })
echo $result
# "Hello, foo"

# So apparently a 1-element array of strings just turns into a string

# 0-element arrays?
$x = '[]'
$result = ConvertTo-Json ((ConvertFrom-Json $x) | % { "Hello, $_" })
echo $result
# <no output>

# A 0-element array turns into $null, which in turn can't be serialized at all
```

I appreciate that a scripting language has slightly different concerns than a full blown programming language, but this is basically bizarro-world. I don't know what the solution is exactly, but a sense of consistency and type-safety in the primitive data structures is sorely missing when trying to use PowerShell for non-trivial tasks.

**Comment by mklement0** [comment]
To add to @vexx32's comments:

In a nutshell, the price of using PowerShell's pipeline - both on input and output processing - is that you lose the distinction between:

* a single item and single-element array
* nothing / `$null` and an empty array

It is a slight irony that `ConvertFrom-Json` is _not_ a good pipeline citizen in that it actually sends arrays as a _single object_ through the pipeline as opposed to _enumerating its elements_, the way cmdlets usually do:

```powershell
PS>  '[]' | ConvertFrom-Json | ConvertTo-Json
[]  # !! empty array was preserved
```

Because `%` (`ForEach-Object`) was also involved in your case, however, you saw the usual enumeration behavior; also note that even enclosing a command in `(...)` by itself forces enumeration too:

```powershell
PS>  ('[]' | ConvertFrom-Json) | ConvertTo-Json
 # !! No output - (...) forced enumeration, so no element was sent to ConvertTo-Json
```

While you could argue that  `ConvertFrom-Json`'s current behavior is valuable for its ability to round-trip without loss of information, that ability is easy to disrupt, as demonstrated here, and overall it is more important for `ConvertFrom-Json` to exhibit _standard_ behavior - though a change may not be made for the sake of backward compatibility - see https://github.com/PowerShell/PowerShell/issues/3424

@vexx32  has already mentioned `@(....)`, the array-subexpression operator that forces interpretation of a result as an array, unless it already is one.

`ConvertTo-Json` has recently gained a similar ability with its `-AsArray` switch:

```powershell
PS> 1 | ConvertTo-Json -AsArray -Compress
[1]
```

Applied to your command:

```powershell
PS> ConvertFrom-Json $x | % { "Hello, $_" } | ConvertTo-Json -AsArray
[
  "Hello, foo"
]
```

While this is not automatic round-trip behavior, at least you can predictable output JSON arrays if you know that they're expected.

**Comment by vexx32** [comment]
In all your examples from other languages, this is only doable on values that can be *confirmed to be collections* at every part of the sequence. 

PowerShell fundamentally isn't like that with its pipeline. Collections are broken apart, and there *is fundamentally no difference* between one item and many.

Consider:

```powershell
$Value = 1
$Result = $Value | ForEach-Object {$_}

$Value = 1, 2
$Result = $Value | ForEach-Object {$_}
```
What you're suggesting is for *both* of these to result in arrays, even when the original item is *not* an array.

C#, Haskell, none of the other languages do *this*.

PowerShell, frankly, isn't particularly comparable to them in this regard.

**Comment by masaeedu** [comment]
> ```
> $Value = 1
> $Result = $Value | ForEach-Object {$_}
> ...
> ```
> What you're suggesting is for both of these to result in arrays, even when the original item is not an array.

Wrong. I am not suggesting that `1 | ForEach-Object {$_}` should be an array. I am suggesting that `@(1) | ForEach-Object {$_}` should be an array. In other words, whenever it is the case that the output of `$x.GetType()` is:

```
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Object[]                                 System.Array
```

then the output of `$x | % {$_}` should similarly have type `Array`. You can apply this check yourself to `@(1)` and `1` to see the difference.

> In all your examples from other languages, this is only doable on values that can be confirmed to be collections at every part of the sequence.

This sounds like nonsense. There's no repeated confirmation of the input value being an array in any of the examples I posted above. `[].map(x => x * 2).map(x => x * 3)` works identically to `[1].map(x => x * 2).map(x => x * 3)` works identically to `[1, 2, 3].map(x => x * 2).map(x => x * 3)`: all three examples produce an array.

**Comment by vexx32** [comment]
Correct. All of those methods, however, are only valid on collections themselves. You cannot take a scalar value as you can in PowerShell and apply such a method.

PowerShell *intentionally* doesn't keep track of the fact that the original item is an array or not. I don't think there is a solution to your quandary, save keeping track of it yourself. 😄

**Comment by masaeedu** [comment]
To make this more precise, currently neither `$Result` in:

```
$Value = 1
$Result = $Value | ForEach-Object {$_}

$Value = @(1)
$Result = $Value | ForEach-Object {$_}
```

is an array. The second should be, the first should not. Since this isn't the case, it should at least be possible to construct your own `map` function to provide the desired behavior as `@(1) ?? map(...) ?? map(...)`. If we try to use `|` we're foiled again, since PowerShell won't leave arrays alone.

So we should perhaps have some other operator that acts as simple function application to allow working around this behavior with userland libraries.

**Comment by vexx32** [comment]
There is such a thing, sort of, and it's quite close to hand.

You're looking for `.ForEarch{}` and `.Where{}` -- PowerShell magic methods. They can be applied to literally any object in PowerShell, just like their pipeline cousins. However, they too are not *perfect*.

Counter to the pipeline, using these methods will *always* result in a collection. Seems to be a generic collection, from what I can see.

Example:
```powershell
PS> @(1).ForEach{$_}.GetType().FullName
System.Collections.ObjectModel.Collection`1[[System.Management.Automation.PSObject, System.Management.Automation, Version=6.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]

PS> (1).ForEach{$_}.GetType().FullName
System.Collections.ObjectModel.Collection`1[[System.Management.Automation.PSObject, System.Management.Automation, Version=6.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]
```
Although both cases require parentheses due to how PS handles parsing on decimal numerals (yes, that also is weird and strangely not exhibited by hexadecimal literals, but that's a story for another time), only the first is actually an array.

And yes, both result in a generic `Collection[PSObject]`. Effectively the reverse of the pipeline methods.

In *this* case, perhaps you could argue that PS could remember if the value was scalar and return a scalar value, but it's also not possible to know whether or not in the `.ForEach{}` method you opt to return multiple values for each input... so, I suppose, it's the most elegant solution to simply return a collection.

**Comment by SeeminglyScience** [comment]
> You're looking for `.ForEach{}` and `.Where{}` -- PowerShell magic methods. They can be applied to literally any object in PowerShell

Small note here, they can also be applied to `$null` (e.g. `$null.ForEach{}.GetType().FullName` returns the same)

Also they can't be applied to objects that already have a `Where` or `ForEach` method (e.g. using `ForEach` on `List<>`  will call `List<T>.ForEach(Action<T>)` instead of the magic method)
