### ISSUE TITLE
better dynamicparam 

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#8049]
hello

its possible to reinvent the concept of dynamic param fo better and simple  use 

Steps to reproduce
------------------

```powershell
dynamicparam {
  param(
    [parameter(mandatory)]
    $param1,
    [switch]
    $param2,
    [validateSet('a','b','c')]
    [char]$letter
  )

  # and here the logic

  return $dynamicObject
}
```

**Comment by lzybkr** [comment]
How about this:

```powershell
[cmdletbinding()]
param()

dynamicparam {
    class MyDynamicParams {
        [Parameter()][string]$ABC
    }

    return ($dynamicParams = [MyDynamicParams]::new())
}

begin {
    $dynamicParams.ABC
}
```

This works today.

**Comment by vexx32** [comment]
Well, it's better than the "standard" implementations we usually see, but it's still very much an arcane syntax -- I don't think I've *ever* seen anyone talk about approaching it like that before.

Additionally, any parameter attributes that need script blocks cannot be used there, as classes prevent you from supplying script blocks to member attributes. So that rules out `[ValidateScript()]`, `[ArgumentCompleter()]` and I think a few others. I can think of a few ways to skirt those rules in this specific case, but I think the case can still be made that dynamicparam... leaves a *lot* to be desired, unfortunately. 🙁

**Comment by lzybkr** [comment]
I think @bielawb first proposed this technique, maybe in this [talk](https://www.youtube.com/watch?v=RJ2jFuuaPCU).

Script blocks in attributes can be made to work with classes - it just requires delaying the creation of the scriptblock until the attribute is instantiated.

Dynamic parameters were never meant to be easy. There was always a strong desire for a declarative style, and whenever possible, improving on that instead of making dynamic parameters "easier".

As an example, parameter sets can get unwieldy in some cases. There were some discussions around "mutual exclusion sets" to make it easier to express things like "one of a,b,c and one of d,e,f". I don't recall any concrete proposals from those discussions, but it's an example of the strong desire to remain as declarative as possible.

**Comment by vexx32** [comment]
Declarative is great, it doesn't have to be "easy". But I think dynamicparam strongly tends towards more "obscure" than "declarative", really. 😕
