### ISSUE TITLE
Smarter completer for strings that are not file paths

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#8092]
Filesystem paths are strings for parameters.  So for any string parameter that doesn't have `ValidateSet`, tab completion defaults to using the filesystem provider.  For compatibility, we can't ask everyone to decorate parameters that are filesystem paths to indicate they should use the filesystem provider for tab completion.  Instead, we can introduce a new attribute to declare it's NOT a filesystem path so that tab complete doesn't start showing filesystem paths where it isn't appropriate.

Steps to reproduce
------------------

```powershell
Add-Content -Path ./foo.txt -Value # hit tab
```

Expected behavior
-----------------

```none
Tab completion here should do nothing as the parameter is any arbitrary string
```

Actual behavior
---------------

```none
Tab completion enumerates files/folders in the current path
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.1
PSEdition                      Core
GitCommitId                    6.2.0-preview.1
OS                             Darwin 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Why use a whole new attribute? I think predefining some behaviours for ArgumentCompleter would be much more extensible.

```powershell
Param(
    [Parameter(Position = 0)]
    [

**Comment by kilasuit** [comment]
^^^ Totally agree with the above.

This to me makes more sense than a new attribute

**Comment by iSazonov** [comment]
> So for any string parameter that doesn't have ValidateSet, tab completion defaults to using the filesystem provider.

It is fallback. How many we have or can have such fallbacks? My thoughts here is about something like `ArgumentCompleter(SuppressFallback = $true)`

>  For compatibility, we can't ask everyone to decorate parameters that are filesystem paths to indicate they should use the filesystem provider for tab completion. 

Do we really need the fallback and why? 
As minimum I think it would be best practice to do this (to decorate path parameters) for future. We could use `ArgumentCompleter(filesystem)` for path parameters in the repo.

**Comment by vexx32** [comment]
Problem with that is that would throw an immediate error in earlier versions. Ideally, I think we should try to have a solution that simply doesn't function in earlier versions / windows PowerShell, without throwing errors.

**Comment by lzybkr** [comment]
A new attribute or named argument will be an error in older versions when you call the function.

**Comment by vexx32** [comment]
Yes, but passing it a type that doesn't exist will *also* be an error as well, so I don't see it being any better, unless you plan on backporting the proposed types. 

I would think that simply being able to specify a specific PSProvider would be *much* more streamlined in this case; given a string that matches a provider name, it can lookup against available PSProviders and apply completion for that instead of the standard filesystem only completion. 

Otherwise, every single new and existing PSProvider would need its own argumentcompleter attribute class, which strikes me as awkward and unnecessary.

**Comment by lzybkr** [comment]
If you add a named argument, you allow something that is probably nonsense:

```powershell
[ArgumentCompleter([CompleterType], Provider = 'OtherThing')]
```

You could use an unnamed argument so the constructor is overloaded, but I think a new attribute would be clearer than an unnamed argument to `ArgumentCompleter`.

Providers should probably opt-in to completion anyway by implementing `System.Management.Automation.IArgumentCompleter` because some providers are really slow, should use a cache, etc. Then you could write:

```powershell
[ArgumentCompleter([Microsoft.PowerShell.Commands.FileSystemProvider])]
```

But if you really want a single type doing all path completion and supports specific providers, the `ArgumentCompleterAttribute` could support passing arguments to the types constructor, e.g.:

```powershell
[ArgumentCompleter([PathCompleter], "FileSystemProvider")]
```

I will also point out that some people would like a global option to disable the fallback completion e.g. see this [StackOverflow question](https://stackoverflow.com/questions/52874517/powershell-5-psreadline-autocompletion-how-to-ignore-batch-files-cmd-bat).

I think the trivial implementation of such a global setting would not be a good experience, but such an option might make sense once the core commands have an the necessary annotations to complete paths where it makes sense. I do think we'd still need to complete paths for native commands that have no registered argument completers, or maybe this global option has different levels, like `Off`, `NativeCommandsOnly`, `On`.

**Comment by iSazonov** [comment]
>  I do think we'd still need to complete paths for native commands

We could implement default ArgumentCompleter for native commands. It allows to create custom completers for native commands. (Could we use here your idea with proxy classes (psmore)?)

> Providers should probably opt-in to completion anyway by implementing

I like this most. This goes well with previous suggestion. 

I do not like the idea of creating new attributes so we already have a lot of ones. IArgumentCompleter allow address all scenarios in modern way.

**Comment by iSazonov** [comment]
For reference https://github.com/dotnet/runtime/issues/75826
