### ISSUE TITLE
Expose ConvertToJson as an API

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PowerShell#8123]
We have [ConvertFromJson](https://github.com/PowerShell/PowerShell/blob/1243891ea8c04609ce21d0b31d40945fd46a3576/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs#L52) exposed as an API, but not ConvertToJson.

If we had both, folks that are writing apps that host PowerShell could access Convert*Json via the API rather than needing to use a runspace!

I think we could simply convert what's in `ConvertTo-Json` to C# and put it in this `JsonObject`class and then have `ConvertTo-Json` just call that API.

**Comment by iSazonov** [comment]
For new public API we need PowerShell Committee approval. /cc @SteveL-MSFT

**Comment by daxian-dbw** [comment]
The existing `JsonObject.ConvertFromJson` and the proposing `JsonObject.ConvertToJson` are for converting to/from JSON in the PowerShell context, which means it honors the ETS and PowerShell specified type conversions.

**Comment by markekraus** [comment]
@daxian-dbw I understand that. What I'm saying is rather than expose the existing implementation, I would rather see work that replaces the existing implementation and finds some way to more closely wrap NewtonSoft, then expose that as an API. We have a bunch of open issues about lack of support for various things that come natural for NewtonSoft. I'm not discounting ETS, we obviously need to support it. But exposing an API for an implementation we know to be flawed is not my preferred path.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agrees to exposing ConvertToJson public api for the purpose of conversion in PowerShell context

**Comment by iSazonov** [comment]
For information - I see that CoreFX team started and actively develop System.Text.Json. I expect we'll have this in .Net Core 3.0.
