### ISSUE TITLE
Should copy-item perhaps preserve attribute hidden for directories as for files?

### ISSUE THREAD

**Issue by PoshKazun** [PowerShell/PowerShell#8135]
Steps to reproduce
------------------

```powershell
md 1
Set-ItemProperty -Path 1 -Name attributes  -Value Hidden
Copy-Item -Path 1 -Destionation D:\ -Force

```

Expected behavior
-----------------

```none
PS C:\> Get-Item -Path D:\1 -Force


    Directory: D:\


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d--h--         27-Oct-18 12:13 PM                1
```

Actual behavior
---------------

```none
PS C:\> Get-Item -Path D:\1 -Force


    Directory: D:\


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         27-Oct-18 12:13 PM                1
```

Environment data
----------------

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.0-preview.1
PSEdition                      Core
GitCommitId                    6.2.0-preview.1
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
I believe we should follow cmd.exe behavior.

**Comment by SteveL-MSFT** [comment]
cmd.exe copy doesn't copy hidden files, so we can't have parity when using `-force`.  Seems like it would make sense to preserve attributes particularly if you're doing a recursive copy.

**Comment by vexx32** [comment]
Indeed, copy making a proper duplicate would certainly seem desirable.

**Comment by NeoBeum** [comment]
I'm currently working with DISM in WinPE... 
There's no PS equivalent cmdlet for ROBOCOPY or XCOPY

ROBOCOPY /COPY:DATSO /E
ROBOCOPY /DCOPY:DAT /E

XCOPY /CHERKY

**NOTE** - Idea popped in to my head:
I'm just starting to realise, perhaps the folder redirection issues Windows is having is because of the lack of ... There is currently an issue with OneDrive Backups with User Profile... and I'm thinking that directory attributes aren't being taken in to account
