### ISSUE TITLE
Some cmdlets don't respect `-LiteralPath` when it comes to backslashes

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#8158]
Path normalization (fixing of slashes) is happening regardless of whether `-literalpath` is used.  Seen in `Set-Content`, `Get-Content`, `Out-File` (maybe others, search for `NormalizePath()`

Steps to reproduce
------------------

```powershell
# on Unix based system
Set-Content -LiteralPath "\foo.txt" -Value "bar"
```

Expected behavior
-----------------

```none
A file called "\foo.txt" is created with content "bar"
```

Actual behavior
---------------

Path normalization (fixing slashes) doesn't take into account that this is a literal path.

```none
Set-Content : Access to the path '/foo.txt' is denied.
At line:1 char:1
+ Set-Content -LiteralPath "\foo.txt" -Value "bar"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : PermissionDenied: (/foo.txt:String) [Set-Content], UnauthorizedAccessException
+ FullyQualifiedErrorId : GetContentWriterUnauthorizedAccessError,Microsoft.PowerShell.Commands.SetContentCommand
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.1
PSEdition                      Core
GitCommitId                    6.2.0-preview.1
OS                             Darwin 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Given that `\` is not a wildcard-expression metacharacter, I would expect it to be treated as a literal in `-Path` arguments too.

In https://github.com/PowerShell/PowerShell/issues/6833#issuecomment-389690161 you've talked about the need to support _escaping_ `\` in paths, without being specific about `-Path` vs. `-LiteralPath`:

```powershell
Set-Content -LiteralPath '`\foo.txt' -Value "bar"
Set-Content  '`\foo.txt' -Value "bar" # implied -Path
```

To me it makes sense to treat the `\` issue separately from the `-Path` / `-LiteralPath` dichotomy, as the latter is strictly about _wildcards_.

**Comment by mklement0** [comment]
Understood, @SteveL-MSFT. 

My example commands showed how it _should_ work _once fixed_, based on my interpretation of the conclusion reached in #6833 - did I misread that conclusion?

My point was that this escaping should work with both `-Path` and `-LiteralPath` arguments, as the latter distinction - at least so far - relates to wildcards only, and the `\` / `/` issue is conceptually separate.

After all, I shouldn't have to forgo wildcard matching just so I can get my `\` chars. interpreted as-is.

An aside re your example: If you use _double_ quotes, you'll have to use _two_ `` ` `` chars., because a single one is "eaten" by string parsing.

**Comment by SteveL-MSFT** [comment]
@mklement0 ok, I see what you mean.  Yes, if escaped properly, it should work with `-Path` as well.
