### ISSUE TITLE
Select-String -SimpleMatch does only current culture search

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#8180]
We could enhance Select-String -SimpleMatch with  Ordinal and OrdinalIgnoreCase search. It may speed up search in some scenarios up to 10x.

Also currently we can not switch  to another culture if we use `-SimpleMatch`.

Note that without `-SimpleMatch` we use Regex and this new parameter(s) doesn't make sense.

Should we case-insensitive and ordinal by default? It makes sense for searching in logs?

**Comment by iSazonov** [comment]
@mklement0 Could you please look the issue? How we could enhance parameter sets to expose more comparison types and perhaps cultures?
-Cuture en-US
-Comparison [Ordinal | OrdinalIgnoreCase | CurrentCulture | CurrentCultureIgnoreCase | __SimpleCaseFolding__ ]

**Comment by iSazonov** [comment]
@mklement0 Have you thoughts how we could design this?

**Comment by mklement0** [comment]
@iSazonov: Please give me some time to think about this.

**Comment by mklement0** [comment]
Re **cultures**:

Support for arbitrary cultures directly via `-Culture` would follow the model of `Compare-Object`, `Sort-Object`, and `Group-Object`, which also use the current culture by default.

Like the latter, `-Culture` should accept culture names and also - obsolescent - LCIDs, which, unfortunately, is currently the only way to request the _invariant_ culture (`-Culture 127`); `-Culture ''` should be accepted too, analogous to ``), but isn't.
That said, `-Comparison InvariantCulture` (see below) would be the less obscure way to request the invariant culture.

I have no sense of how much demand there is for being able to specify arbitrary cultures.

Re **string-comparison modes**:

Since `Select-String` has an existing `-CaseSensitive` switch, I would omit the case aspect and only support the following, with `InvariantCulture` added:

    -Comparison [Ordinal | CurrentCulture | InvariantCulture | SimpleCaseFolding]

Note that `CurrentCulture` is the default.


`-Comparison` would have to be _mutually exclusive_ with `-Culture` (the latter implying current-culture logic relative to the _specified_ culture).

**Comment by iSazonov** [comment]
@mklement0 Thank for great comment! Please look https://docs.microsoft.com/en-us/dotnet/api/system.stringcomparison?view=netcore-2.1

**Comment by iSazonov** [comment]
Considering the example https://docs.microsoft.com/en-us/dotnet/api/system.stringcomparison?view=netcore-2.1#examples
we could put `-Comparison` and `-Culture` in the same parameter set. Yes?

**Comment by mklement0** [comment]
I don't think so, because:

* Use of  a specific culture with `-Culture` _implies_ comparison mode `CurrentCulture[IgnoreCase]`.

* Conversely, a combination such as `-Culture ru-RU -Comparison Ordinal` makes no sense.

**Comment by vexx32** [comment]
That's certainly true @mklement0, but there may be cases where you do want case-_sensitive_ comparisons relative to a specific culture, which isn't really possible in your suggested setup.

Perhaps applying an argumentcompleter and a transform attribute to permit the use of `Ordinal` / `Invariant` / etc as though it were a true culture would be perhaps the most versatile approach?

**Comment by mklement0** [comment]
@vexx32:

> which isn't really possible in your suggested setup.

It is, using the existing `-CaseSensitive` switch:

```powershell
Select-String -Culture ru-RU -CaseSensitive ...
```

Your suggestion is interesting, but I wonder if it's too obscure, especially for users who aren't looking for a _specific culture_.

**Comment by mklement0** [comment]
P.S.: Even with the suggested argument completer you'd then need a separate mechanism for opting into case-sensitivity (which `-CaseSensitive` could provide) - unless you're thinking that requesting a specific culture should _imply_ case-sensitivity?

**Comment by vexx32** [comment]
Not at all. The proposals here are a bit confusing, just trying to keep track. 😄 

I see the -CaseSensitive vs -Comparison OrdinalIgnoreCase stuff has already been hashed out, I guess I missed it before.

**Comment by iSazonov** [comment]
> a combination such as -Culture ru-RU -Comparison Ordinal makes no sense.

What about the API https://docs.microsoft.com/en-us/dotnet/api/system.string.compare?view=netcore-2.1#System_String_Compare_System_String_System_Int32_System_String_System_Int32_System_Int32_System_Globalization_CultureInfo_System_Globalization_CompareOptions_ ?

**Comment by mklement0** [comment]
@iSazonov: From the linked page, emphasis added:

> The comparison can be further specified by the options parameter, which consists of one or more members of the System.Globalization.CompareOptions enumeration. **However, because the purpose of this method is to conduct a culture-sensitive string comparison, the CompareOptions.Ordinal and CompareOptions.OrdinalIgnoreCase values have no effect.**

**Comment by iSazonov** [comment]
@mklement0 My thoughts is about simplifying parameter sets. We could do the same " values have no effect" behavior. If we want to be more smart we could write warning or just explicitly throw but I think it's overkill.
With `-Culture ru-RU -Comparison Ordinal` I'd expect that Comparison has a priority and Culture ignored.

**Comment by mklement0** [comment]
Is your concern is implementation complexity, or are you worried about the sheer number of parameter sets showing up in the help>

**Comment by iSazonov** [comment]
Currently I am thinking about UX. I expect that Comparison parameter will be used _mainly_. In rare cases, users will want to change the culture - in this special case, I believe they will be experienced enough and will choose the right Comparison.

**Comment by mklement0** [comment]
Well, if we include the existing `-CaseSensitive` switch in the new parameter sets - which makes the most sense to me - there's _no need_ to also use the `-Comparison`  with `-Culture`:

```powershell
# Case-INsensitive Russian-language-sensitive comparison
Select-String -Culture ru-RU ...

# Case-SENSITIVE Russian-language-sensitive comparison
Select-String -Culture ru-RU -CaseSensitive ...
```

Culture-sensitivity in case-INsensitive  comparisons doesn't often make a difference, but:

* There are cases; e.g., `'ss'.Equals('ß')`  returns `$true` for German-language cultures (albeit only on Windows(!)), but with `ru-RU` in effect, for instance, it would return `$false`.

* I recommend against deviating from PowerShell's case-INsensitive default behavior - even if that means interpreting `Ordinal` as the counterpart to .NET's `OrdinalIgnoreCase` enum value (and letting `-CaseSensitive` alone control case-sensitivity).
  * PowerShell users aren't necessarily aware of underlying .NET types (and shouldn't have to be), but they most likely are aware of everything being case-INsensitive by default; we already have similar discrepancies, such as the behavior of `-eq` vs. `.Equals()`.

**Comment by iSazonov** [comment]
I don't want change to case-sensitive
Current default is CurrentCultureIgnoreCase. I'd prefer OrdinalIgnoreCase that is more fast, more expected and more useful for administrators I believe. It is my initial intention. And I hope the new  Comparison parameter could resolve this.

**Comment by mklement0** [comment]
> I don't want change to case-sensitive

Neither do I.  And I don't understand how your comment relates to my previous comment.

Are we in agreement, are we talking about different things, or did you mean to say something else? 

As for what _should_ have been _the default_ (clearly, that ship has sailed): for consistency with _most_ of PowerShell (regrettably, there are many exceptions), notably with `-eq`, it should have been  `InvariantCultureIgnoreCase`.

Frankly, though, I'm unclear on when `InvariantCultureIgnoreCase` differs from `OrdinalIgnoreCase`. Do you know an example of where they differ (where linguistically appropriate behavior is exhibited by `InvariantCultureIgnoreCase`)?

The performance difference between the two is not large, fortunately: `InvariantCultureIgnoreCase` is only about 5 - 17% slower, from what I can tell (using [`Time-Command`](https://gist.github.com/mklement0/9e1f13978620b09ab2d15da5535d1b27) with 100,000 strings, averaged over 10 runs):

```powershell
$a = (, 'hello') * 1e5; Time-Command { $a.Foreach({ $_.Equals('heLLo', 'InvariantCultureIgnoreCase')}) }, { $a.Foreach({ $_.Equals('heLLo', 'OrdinalIgnoreCase')}) }
```

**Comment by iSazonov** [comment]
> And I don't understand how your comment relates to my previous comment.

Sorry, this was my response to:

> I recommend against deviating from PowerShell's case-INsensitive default behavior

> Frankly, though, I'm unclear on when InvariantCultureIgnoreCase differs from OrdinalIgnoreCase. Do you know an example of where they differ (where linguistically appropriate behavior is exhibited by InvariantCultureIgnoreCase)?

You can find a lot of useful in https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings
(Related #8064 - We definitely need to revise the code specially after #8566)
I believe the doc explain why I say about OrdinalIgnoreCase (not InvariantCultureIgnoreCase) for Select-String.

> InvariantCultureIgnoreCase is only about 5 - 17% slower

My motivation to make Select-String faster is that my script parsed logs ~8 hours. I could save a few hours if the cmdlet was faster.  And the cmdlet is significantly slower than native code utilities like grep. So getting 17% would be great!

**Comment by mklement0** [comment]
Thank you for the research and the pointers, @iSazonov.

**Comment by mklement0** [comment]
That's probably a good idea.

Additionally, we'd need a different mechanism if we wanted to make the same functionality available to _operators_:

For _string-comparison_-based operators, it is conceivable to support `CurrentCulture`, `Ordinal` and `SimpleCaseFolding` too:

* `-eq`, `-lt`, `-gt`, `-contains`, `-in`,  `switch` (without `-Wildcard` or `-Regex`), `-split` with the `SimpleMatch` option: 
  * From what I understand, these currently _invariably_ use the _invariant_ culture, correct?

By contrast, PowerShell's _wildcards_ and .NET _regexes_ appear to be limited with respect to linguistic comparisons due to seemingly operating on _one-to-one_ character mapping only:

* wildcard operators: `-like`, `switch -Wildcard`:
  * PowerShell's wildcards use the _current_ culture, but do not support linguistic comparisons due to doing _character-by-character_ comparisons.

* regex operators: (`-match`, `-replace`, `-split`, `switch -regex`)
  * .NET regexes seemingly use the current culture for character-by-character case mapping, right?

For regexes, the only other mode that .NET offers is use of the _invariant_ culture - not also _ordinal_ comparison / simple case-folding.
Among the regex operators listed, it is only `-split` that already offers that, via its third RHS operand; e.g., `'a-b-c' -split '-', 0, 'CultureInvariant'`.

By contrast, for wildcards, which are under PowerShell's control - and currently _invariably_ use current-culture character-individual lowercase conversion - we can conceivably offer both the invariant culture and ordinal comparison / simple case-folding.

**Comment by iSazonov** [comment]
> * `-eq`, `-lt`, `-gt`, `-contains`, `-in`,  `switch` (without `-Wildcard` or `-Regex`), `-split` with the `SimpleMatch` option: 
   From what I understand, these currently _invariably_ use the _invariant_ culture, correct?

I can not confirm. I did not found this in parserutils.cs.

**Comment by mklement0** [comment]
You haven't found the source of the behavior, or you found evidence to the contrary?
I haven't looked at the code, but _de facto_ it appears to be true (using `ı` (`U+0131`)  as an example, which is the lowercase equivalent of `I` only in Turkish and Azeri):

```powershell
[cultureinfo]::CurrentCulture = 'tr' # Turkish
([string] [char] 0x131).equals('I', 'CurrentCultureIgnoreCase') # $true
([string] [char] 0x131).equals('I', 'InvariantCultureIgnoreCase') # $false
([string] [char] 0x131) -eq 'I' # $false too
```

**Comment by iSazonov** [comment]
I considered only `-split` and not found that we set InvariantCulture.

**Comment by mklement0** [comment]
I see, so I shouldn't have lumped in `-split <string>, <n>, 'SimpleMach'` with the the other (non-regex, non-wildcard) equality-based operators  (haven't tested with `-lt`, `-gt` yet).

```powershell
[cultureinfo]::CurrentCulture = 'tr' # Turkish

# invariant
([string] [char] 0x131) -eq 'I'  # always $false
switch ([char] 0x131) { 'I' { 'yes' } default { 'no' } } # always 'no'
, ([string] [char] 0x131) -contains 'I'  # always $false
'I' -in , ([string] [char] 0x131) # always $false

# -split with SimpleMatch is the exception:
(('a' + [char] 0x131 + 'b') -split 'I', 0, 'simplematch').Count -eq 2 #  $true in 'tr' (on Windows)
```

**Comment by iSazonov** [comment]
In Binders.cs I see only InvariantCulture - all operators use seems invariant culture.
