### ISSUE TITLE
"Where-Object -Property ..." should not accept method names because they're not properties

### ISSUE THREAD

**Issue by HumanEquivalentUnit** [PowerShell/PowerShell#8224]
`Where-Object -Property x` if given a property name it casts the value to bool and uses that as the filter test, but if given a method name it seems to check whether the method exists (getting the overload definitions and casting those to bool?), e.g.:
```
# filter out empty string, because Length 0 -> boolean false
PS C:\> "test", "", "test2" | Where -property Length
test
test2
# try with getter method name, by comparison
PS C:\> "test", "", "test2" | Where -property get_Length
test

test2
```

This feels inconsistent one way or another - if it should work with a method name, then it should call the method and use the return value, like `foreach-object -membername` does. But since the parameter is called `-Property` it should only take property names, and have another `-MemberName` property to work on arbitrary members.

With a wildcard:

```
PS C:\> "test" | where -Property L*
where : Input name "L*" is ambiguous. It can be resolved to multiple matched members. Possible matches include: Length LastIndexOf LastIndexOfAny.
```

Why is it matching a "property" wildcard to method names, when it can't use method names sensibly?

**Comment by mklement0** [comment]
Good points;  to align the behavior with `ForEach-Object`, it seems to me  we could:

* add a parameter _alias_  for the existing `-Property` parameter named `-MemberName` and make it support method names too.

* add an `-ArgumentList` / `-Args` parameter to support passing arguments to method calls (in the implicit-Boolean-result scenario that would be fine; the syntax is perhaps a little confusing if an operator such as `-EQ` and operand (`-Value`) are also specified, but it should work).

**Comment by iRon7** [comment]
Interesting...
I was about to create a bug report as I was expecting that `Where-Object` actually *should* accept methods for the property parameter...

This works:

```PowerShell
1,2,3 |ForEach-Object ToString
1
2
3
```

```PowerShell
1,2,3 |ForEach-Object ToString('000')
001
002
003
```

But this doesn't:
```PowerShell
1,2,3 |Where-Object ToString -Eq '2' # |Should -be '2'
```

And this even errors:
```PowerShell
1,2,3 |Where-Object ToString('000') -Eq '002'
```
> Where-Object: A positional parameter cannot be found that accepts argument '002'.

Related stackoverflow answer: [How to check if one line in an array contains something in another array](https://stackoverflow.com/a/76401524/1701026) where I created a custom `ScriptMethod` and was actually expecting to be able to do something like:

```PowerShell
$Cars |Where-Object _Like_($Colors) -eq 'Pixel'
```

**Comment by mklement0** [comment]
@iRon7 

> `1,2,3 |ForEach-Object ToString('000')`

is actually pseudo method syntax that is the equivalent of:

```powershell
1,2,3 | ForEach-Object ToString -ArgumentList 000
```

However, it would also work with `Where-Object` if an `-ArgumentLIst` parameter were added to it for method support, as suggested.

The absence of `-ArgumentList` is what explains the failure of `1,2,3 |Where-Object ToString('000') -Eq '002'` - you get a parameter-binding error, because `('000')` - as a syntactically separate, positional argument - has no parameter to bind to.

However, that `1,2,3 |Where-Object ToString` and `1,2,3 |Where-Object ToString -eq '2'` report _no_ error (as with `"test", "", "test2" | Where -property get_Length` in the initial post) is a manifestation of the issue at hand: 

 * What I _think_ is happening is that the method _definition_ is used instead of _calling_ the method, which I infer from the following:

```powershell
# True for all inputs.
# If you used -is [string], you'd get NO output.
1, 2, 3 | Where-Object ToString -is [System.Management.Automation.PSMethod]
```
