### ISSUE TITLE
[feature] support for invoking a variable function using arguments (the powershell way)

### ISSUE THREAD

**Issue by Meir017** [PowerShell/PowerShell#8272]
right now it's possible to declare a variable as a function and invoke it but it's not very clean:
```powershell
$myFunction = { param( [string]$arg ) "my arg $arg" }

# invocation
$myFunction.Invoke('an arg')
# or
& $myFunction 'an arg'
```
based on https://stackoverflow.com/questions/24798389/can-i-assign-a-function-to-a-variable

the way I expected it to work is the same way functions work:
```powershell
$myFunction -arg 'an arg'
```

**Comment by vexx32** [comment]
Hmm. No, this wouldn't be possible. A variable and a command name are fundamentally different. The variable you have contains a script block, not a function.

If you call `$myFunction.GetType()` you will get `ScriptBlock` back. If you go ahead and create a true function with this script block you will be able to invoke it as a function:

```powershell
New-Item -Path 'Function:\myFunction' -Value $myFunction
myFunction -arg 'an arg'
```

Functions are _not_ synonymous with script blocks in PowerShell. They're two separate objects, though function objects by _definition_ contain a script block with their code stored inside.

For example, if we retrieve that function we just created and stored it in a variable, we can see it's a totally different type of object.

```powershell
$function = Get-Item 'Function:\myFunction'
$function.GetType()
```

This gives us a `FunctionInfo` object. Because objects are always able to be sent as output, we cannot implicitly assume that a variable that happens to contain a function should inherently be executable as that function without some distinction from the user (in this case, it requires use of `.Invoke()` for script blocks, and the `&` call operator for functions and script blocks).

If we wanted something like this I might perhaps suggest that a new syntax could be made available as a very minimal shorthand: `&myFunction` where the `&` replaces the `$` of a variable, but that is itself potentially problematic in other ways.

In brief, functions are objects just like anything else in PowerShell, and there aren't really any exceptions. If we treat variables as potentially directly invokable items, we'd be breaking a _lot_ of things, I think. 😄

**Comment by Meir017** [comment]
I'm was thinking of creating a swagger-client provider that will return an object an then I would be able to invoke function on it and have autocomplete on the arguments

**Comment by vexx32** [comment]
As I've mentioned, you can take a small extra step to create a true function, which will then properly complete arguments. I do agree that the present methods of invoking from a variable are a little lacking in ability to pass arguments easily, though.

**Comment by Meir017** [comment]
can you provide a small sample of that?
assuming I don't know the name of the method in advance and the name of the arguments (generate them based on the input)

**Comment by vexx32** [comment]
Depends precisely how you receive the input, but if you're getting it from outside PowerShell I'd expect it to probably come as a string, so...

```powershell
# store input string into this variable
$String = 'Get-ChildItem $home'

# create script block
$Script = [scriptblock]::Create($String)

# create function with whatever name you like really
New-Item -Path 'Function:\Get-Thing' -Value $Script

# call function
Get-Thing

# use Get-Help to programmatically retrieve parameters
(Get-Help Get-Thing).Parameters

**Comment by Meir017** [comment]
I figure something like this could work
```powershell
$generatedCode = '
function my-function {
  param( [string]$arg )
  "my arg $arg"  
}'
Invoke-Expression $generatedCode

# and then 
my-function -arg "test"
```

**Comment by vexx32** [comment]
Yes, it would... But once again, be wary of running code that comes from elsewhere. If there's any other way to do whatever your ultimate goal is, I would take the other option.
