### ISSUE TITLE
PowerShell-6.2.0-preview.2-win-x64 error on startup (also occurs on upgrade to preview.3)

### ISSUE THREAD

**Issue by najeebanwer** [PowerShell/PowerShell#8289]
Steps to reproduce
------------------
pwsh-preview

Expected behavior
-----------------
Launch PowerShell-6.2.0-preview.2

Actual behavior
---------------
Gives the following error:

> Error:
>   An assembly specified in the application dependencies manifest (pwsh.deps.json) was not found:
>     package: 'System.Private.ServiceModel', version: '4.5.3'
>     path: 'runtimes/win/lib/netstandard2.0/System.Private.ServiceModel.dll'

Environment data
----------------

```powershell
> $PSVersionTable

```
N/A

**Comment by kborowinski** [comment]
**Workaround:**
Run the installer again and use repair function. It will fix the problem.

**Comment by najeebanwer** [comment]
@kborowinski:
Yes, that works. Thanks.
However, it should work after the initial installation and not require a repair.

**Comment by DarwinJS** [comment]
I am having the same problem after an upgrade using the chocolatey package I created for preview.  I will avoid updating the chocolatey.org repo until this is fixed so that I don't get lotsa complaints ;)

**Comment by bergmeister** [comment]
This seems to be an upgrade problem only (I could reproduce when upgrading from `6.2-preview1` to `6.2-preview1`). Uninstalling and reinstalling is fine and fixes it

**Comment by Agazoth** [comment]
I had the same issue upgrading.

**Comment by SteveL-MSFT** [comment]
Will investigate next week

**Comment by damianog** [comment]
Same issue to me from 6.2-preview1 to 6.2-preview2 msi installation

**Comment by SteveL-MSFT** [comment]
Preview.3 is coming out next week, so will wait to see if this repros.

**Comment by DarwinJS** [comment]
It is sort of reproing - though I am going over 6.2 preview 3 and it is a different error:
![image](https://user-images.githubusercontent.com/11597190/49773439-1c62f300-fcbf-11e8-98d6-6ae327f9dcbb.png)

**Comment by MaximoTrinidad** [comment]
Can someone post which build of Windows 10 got the PowerShell Core error??

:)

**Comment by DarwinJS** [comment]
10.0.17134

**Comment by bergmeister** [comment]
I can confirm this happens not only when upgrading `6.2-preview1` to `6.2-preview3` but also `6.2-preview2` to `6.2-preview3`

**Comment by DarwinJS** [comment]
In my case it happened when upgrading `6.2-preview2` **that had been upgraded** from `6.2-preview1`.  I would have to test a `6.2-preview1` to `6.2-preview3` upgrade to know if that path also generates an error.

**Comment by MaximoTrinidad** [comment]
@DarwinJS 

I have confirmed upgrading from Preview.1 to Preview.3, installation complete without any failures but still PowerShell Core won't start.

:)

**Comment by MaximoTrinidad** [comment]
@DarwinJS 

Ah! Just another FYI

Instead of uninstall, you click repair, and the will fix the issue too. 

:)

**Comment by SteveL-MSFT** [comment]
I believe we've found the root cause.  Since we have both stable and preview releases, we've been using the same componentid's for the same set of files.  MSI is trying to be "smart" where if a previously registered component (aka file) is already installed (like you have 6.1.1 installed with same file), then it won't install it again.  So that file is missing from 6.2-preview which causes it to fail to start.  Proposed fix is to generate new componentids for the preview releases so they don't match any of the stable files.

**Comment by MaximoTrinidad** [comment]
@SteveL-MSFT,

No wonder I didn't experience the issue before, as I got the habit of manually uninstall PScore,
I do have both GA and Preview installed. 

I'm glad you found the root cause. Awesome!!

:)

**Comment by SteveL-MSFT** [comment]
@TravisEz13 and I looked at this and we believe the issue is understood.  Basically, MSI is being "smart" keeping track of assemblies being installed along with their ids.  We have two types of packages: stable and preview.  But they both use the same ids for the same assemblies.  So upon installing the preview, MSI sees that the assembly we are going to install is "already installed" because the id matches an assembly that is installed (even though it's in a different target file path).

The fix is to generate a different set of ids for the preview release for the assemblies so they don't match the stable ones.  This is not as trivial as it sounds due to how packaging works today with WIX and we don't want to maintain two separate files.wxs that are 99% the same.  We'll get this fixed for next preview.

**Comment by DarwinJS** [comment]
Maybe use a simple zip - with the assumption of file overwrites - for the preview?

**Comment by SteveL-MSFT** [comment]
@DarwinJS if you use the zip pkg we already release, you already won't have this problem, it's specifically the MSI pkg

**Comment by DarwinJS** [comment]
That's right - I forgot.
What if your team published a ps1 inside the preview folder that "self-installs" - basically does all the little things the MSI does?
This way we could unzip + run self-install and be done.
This would seem to be easy:
- to design and build - last I checked the MSI install was simple (might have changed) and the preview should actually be less integrated anyway
- for the powershell team to leave out unapplicable stuff like adding to the path
- easy for people doing self-installers or wrapping in other packaging technologies to get right
- easy for the preview chocolatey package to leverage
