### ISSUE TITLE
New-FileCatalog -CatalogVersion 2.0 creates a 1.0 cat file

### ISSUE THREAD

**Issue by BladeFireLight** [PowerShell/PowerShell#8349]
# Steps to reproduce

```powershell
New-FileCatalog -CatalogVersion 2.0 -CatalogFilePath c:\test.cat -Path c:\test
```
open c:\test.cat in file explorer look at general tab

# Expected behavior

```powershell
New-FileCatalog -CatalogVersion 2.0 -CatalogFilePath c:\test.cat -Path c:\test
```
open c:\test.cat in file explorer and it shows v2 with a stronger algorithm

# Actual behavior

```powershell
New-FileCatalog -CatalogVersion 2.0 -CatalogFilePath c:\test.cat -Path c:\test
```
open c:\test.cat in file explorer and it shows v1 with a sha1 algorithm

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.1
PSEdition                      Core
GitCommitId                    6.1.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by BladeFireLight** [comment]
i'm not expert but it would seem this code does not do what it says and may be the root cause.
``` c
        // Based on the Catalog version we will decide which hashing Algorithm to use

        private int catalogVersion = 1;

```

**Comment by iSazonov** [comment]
I checked we call native API with right value. 

@SteveL-MSFT Can you ping anybody who know the API?

**Comment by SteveL-MSFT** [comment]
Just tried this.  Even though when you specify `2.0` (or even just `2`), it is a version 2 catalog.  When you open the .cat file, it does show `Version=1` but that's `PublicVersion` which is always 1.  It also shows the algorithm as SHA-1, but if you inspect the individual file hashes, it shows ash SHA-256.  I see the same behavior with makecat.exe.  One small improvement we can make is a validate set for CatalogVersion since it only allows 1 or 2.  I can make this small change.
