### ISSUE TITLE
import-csv, with delimiters that are not visible like tab

### ISSUE THREAD

**Issue by qt3m45su0najc7** [PowerShell/PowerShell#8358]
Provide an best practice example of how to specify the delimiter when it is a non-visible character, like the tab character.

**Comment by vexx32** [comment]
Probably best if something like this is explicitly mentioned in the CSV cmdlet documentation, aye, but it's similar to any escape sequence in PS:

```powershell
Import-Csv -Path $File -Delimiter "`t"
```

**Comment by BrucePay** [comment]
@vexx32 Yes - that sounds right. @qt3m45su0najc7 Can you open a bug in the docs repo saying that the CSV cmdlet documentation should mention and reference the escape character documentation? Thanks.

(Note: you could also do it with something like `([char] 0xA)` but that's a bit more complex.)

**Comment by vexx32** [comment]
🤔 Is it a) possible and/or b) worth it... to add some static members to `[char]` for these sorts of purposes?

``` `t ``` is fine for those of us who know what it means, but it'll have anyone unfamiliar hunting for documentation, and I'm not even sure where to point people on that one. 

`[char]::Tab` or `[char]::LineFeed` would be nice to have! 

(Yes, we have `[Environment]::NewLine` but that's a sequence rather than a single invisible character.)

**Comment by qt3m45su0najc7** [comment]
Thank you all for responding.  Just a footnote,.  I mentioned tab char, but tab may be part of the the input that you want.  Consider other nonprintables, like null (hex 000) or bell (hex 007). 
http://www.asciitable.com/

**Comment by vexx32** [comment]
as mentioned, you could use `([char] 0x0)` or `([char 0x7)` for instances like that to specify the delimiter.

I've yet to see someone using null-delimited CSV files though! 😄

**Comment by MarkPflug** [comment]
I would point out, as currently implemented, the null character '\0' cannot be used as a delimiter as it would result in the default delimiter being used.
