### ISSUE TITLE
Revisit the algorithm used in 'ConvertFrom-SddlString'

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#8365]
The function `ConvertFrom-SddlString` was converted to C# in PR #8341 to improve the startup speed.
The C# code is just a translation of what the script was doing, but there are concerns about the fundamental algorithm used in the original script function (see https://github.com/PowerShell/PowerShell/pull/8341#discussion_r236654820). We need to revisit this cmdlet to make sure it does the right thing.

The review comments in https://github.com/PowerShell/PowerShell/pull/3936 will be valuable when we revisit this cmdlet.

**Comment by KalleOlaviNiemitalo** [comment]
There were comments that `ConvertFrom-SddlString` should use only one access mask enumeration type per invocation, rather than try all of them like it now does if `-Type` is not specified.

That made me wonder how [generic access rights](https://docs.microsoft.com/en-us/windows/win32/secauthz/generic-access-rights) should be supported. [SDDL defines `GA`, `GR`, `GW`, and `GX`](https://docs.microsoft.com/en-us/windows/win32/secauthz/ace-strings#generic-access-rights) for them, but the `FileSystemRights`, `RegistryRights`, `ActiveDirectoryRights`, `MutexRights`, `SemaphoreRights`, and `EventWaitHandleRights` types used by `ConvertFrom-SddlString` do not support these generic access right bits. For example, `FileSystemRights.FullControl` equals `FILE_ALL_ACCESS` = `0x001F01FF`, rather than `GENERIC_ALL` = `0x10000000`; and `ActiveDirectoryRights.GenericRead` equals `DS_GENERIC_READ` = `0x00020094`, rather than `GENERIC_READ` = `0x80000000`.

However, it seems that the Win32 `SetSecurityInfo` function maps the generic access rights to type-specific access rights, so the generic access rights are unlikely to occur in ACEs that have been read from objects, and it is not important whether `ConvertFrom-SddlString` supports them.
