### ISSUE TITLE
Question - Register-ArgumentComplete 

### ISSUE THREAD

**Issue by dfinke** [PowerShell/PowerShell#8433]
This can be installed from `Install-Module PSPulumi`.

Two questions, the module doesn't auto load. I'm not sure what I need to make that happen,

I can `ctrl+space` and autocomplete all of these `pulumi stack ls --all`

I want to be able to `ctrl+space` and get the `--json` to complete `pulumi stack ls --all --json`

Here is the section for the tree.
https://github.com/dfinke/PSPulumi/blob/master/PulumiCompletion.ps1#L177

How do I need to re-work the completer to enable this?

**Comment by lzybkr** [comment]
I don't think auto-loading can be triggered from argument completion - at least in any reasonable sort of way.

I'm not sure where the problem lies or how to change your completer, but I'll point out for anyone wanting to take a look, you'll need to install [TabExpansionPlusPlus](https://github.com/lzybkr/TabExpansionPlusPlus/) before investigating because the sample code use `New-CommandTree` from that module.
