### ISSUE TITLE
Save-Help Needs Ability to Retrieve Help for Modules not on Machine

### ISSUE THREAD

**Issue by PrometheusRising1** [PowerShell/PowerShell#8450]
Please build in the capability to Save-Help -Module * or some form of lookup where it not only pulls help for all modules on a machine, but allows you to pick other modules as well (e.g. IIS, Active Directory, SQL).  Not having this feature makes it very difficult to build a reliable offline, regularly updated repository on a share.

**Comment by vexx32** [comment]
I think this would need some form of centralised repository of at help information or at least a directory of forwarding links, which _might_ already exist, but if it does I've not seen any kind of indication of how you'd go about directly accessing help information like this.

That said, this absolutely should be possible. 😄

**Comment by ThomasNieto** [comment]
The PSGallery exposes the module manifests on the website. `Save-Help` could be updated to check PSGallery for the`HelpInfoUri` link. It doesn't help modules that aren't available on the gallery. The gallery would also need to be updated have a way to expose the raw file instead of the formatted HTML page, for example: https://www.powershellgallery.com/packages/IISAdministration/1.1.0.0/Content/IISAdministration.psd1

**Comment by vexx32** [comment]
There's probably an API call that can be used to retrieve the raw file or something. But as you said, it won't help the Windows subsystem modules which tend not to be on the gallery. 😕
