### ISSUE TITLE
add C# unit tests for the compiler

### ISSUE THREAD

**Issue by Meir017** [PowerShell/PowerShell#8488]
## Question

Is there a reason that all of the tests are written in powershell and there are no tests for the internals? (parser, tokenizer) or is it just for legacy reasons?

Having the tests written in C# will improve the development process since we'll be able to debug the tests properly

**Comment by vexx32** [comment]
I can't say for sure, but I suspect the answer might include the phrase "that's a lot of work". The tokenizer alone is over 7k lines of code, and Parser.cs is somewhere around 12k if memory serves? 

It may also be too time consuming to run tests across the entire codebase in both languages; if the functionality can be assured in the resulting language, that might be sufficient and a little more pragmatic than doubling up on tests; PowerShell is made to run PowerShell script and not just its own C# code, after all, in a sense.

But I would be interested to hear the PS team's perspective, indeed! 😄

**Comment by lzybkr** [comment]
Actually, there were some C# tests for the parser, but they were never open sourced. Coverage was minimal, it turns out to be much easier and expressive to write tests in PowerShell.

Another big issue with C# tests is setting up internal state - something that happens naturally when tests are written in PowerShell. This was a frequent problem when the design of internals changed - tests were broken because they were dependent on that internal state in some not very useful way.

Lastly - the interactive nature of PowerShell combined with an iterative development style with small changes and frequent testing generally makes the development process straight forward. I've personally found many of my own parser bugs because `PSReadLine` was invoking the parser on every key, most of those bugs would be very tedious to write tests for.

Now having said this - there are important scenarios that should not be tested from PowerShell. Hosting applications can use PowerShell without using script. Some bugs were missed because even though we had tests, they were written in PowerShell and did not cover the hosting scenario. This is perhaps orthogonal to the question though because it was specifically about the parser.

**Comment by Meir017** [comment]
@lzybkr Thank you for the detailed answer,

1. could you elaborate a bit about the internal state?
2. how does writing the tests using PowerShell solve this issue?
3. couldn't you just use the same internal state for all of the tests?

**Comment by lzybkr** [comment]
It's been too long so I don't remember specifics about the internal state, just the pain, there was a lot of private reflection used.

One of the goals of the original C# tests was to test in isolation, true unit tests. That turns out to be difficult because there is a lot of coupling between components. Those tests solved that problem by using private reflection to set up the state (e.g. create a minimal runspace) in just the right way to keep the parser happy.

When you write in PowerShell, you typically don't need to do that, the state (like a runspace) is already constructed.

But really - productivity is the biggest reason why the tests are largely PowerShell. I'm a big fan of static languages for reliability, so I'm reluctant to say PowerShell is a clear win for testing the PowerShell parser, but ultimately I think the gain in productivity (no compile and interactive command line development) leads to more tests with better coverage.

**Comment by iSazonov** [comment]
I refreshed xUnit test in last month and catch some race conditions. One was partially fixed (access to powershell.config.json). Second on MacOS is still opened.
So I found these tests useful especially for _hosting scenarios_.
Now I believe that hosting scenarios are not reliable until we increase the number of xUnit tests. (Perhaps this is due to the above internal states.)
It will also allow us to control public interfaces.
I opened #8400 to track xUnit tests.
