### ISSUE TITLE
New-AzureRmWebAppSSLBinding uploads certificate to a different webspace than the App Service hosted in an Azure Service Environment

### ISSUE THREAD

**Issue by yxie97** [PowerShell/PowerShell#8494]
# Steps to reproduce

- Create an Azure Service Environment
- Create an Azure Service Plan inside above ASE
- Create an Azure App Service inside above ASP
- Set WEBSITE_LOAD_CERTIFICATES app setting to "*"
- Call New-AzureRmWebAppSSLBinding with a private certificate (.pfx)

```powershell

```

# Expected behavior
certificate uploaded to the same webspace as the App Service and visible under SSL Settings on the Azure Portal for that App Service
```none

```

# Actual behavior
certificate uploaded to a different webspace than the App Service and not visible from SSL settings for the App Service
```none

```

# Environment data

```none

```

**Comment by MaximoTrinidad** [comment]
I'm assuming this is Windows PowerShell, which we don't 
support in this Github repository.  

zure issue! You need to post it in the Azure PowerShell repository at: https://github.com/Azure/azure-powershell

Make sure to provide all the information required to help troubleshoot the issue with the correct PowerShell and Azure Module version.

On December 18th, the new Azure module was released:
Az Module version 1.0  - new AzureRM module (now called Az) available for both Windows PowerShell and PowerShell Core: https://azure.microsoft.com/en-us/blog/azure-powershell-az-module-version-1/?utm_source=dlvr.it&utm_medium=linkedin

We encourage you to try this new module moving forward.

Instead of using the New-AzureRmWebAppSSLBinding, try using:
New-AzWebAppSSLBinding 

Then, log any issue found in the proper repository.

Thanks for your contribution!
