### ISSUE TITLE
Option to exclude file extensions from tab completion/expansion results

### ISSUE THREAD

**Issue by totkeks** [PowerShell/PowerShell#8539]
# Summary of the new feature/enhancement

As a user I want to have an option to hide the file extensions for executables and executable scripts known to the system, when using the tab expansion feature of Powershell.
This would allow me to use them like I'm used to, because I do not care about the file extension.

# Proposed technical implementation details (optional)

Hide the file extension when using tab expansion to expand commands located in $env:PATH that have extensions listed in the $env:PATHEXT.
This would make the behavior similar to how the search for executable scripts work.

Example 1:
* I have a script called `My-Function.ps1` in a folder in my $env:PATH
* I can run it by typing `My-Function` as the search inside the path includes .ps1 files
* When I type `My<tab>`, it expands to `My-Function.ps1`
* Instead `My<tab>` should expand to `My-Function` as the extension is redundant / not needed

Example 2:
* I type `powersh<tab>` and it expands to `powershell` and not `powershell.exe`

**Comment by kvprasoon** [comment]
How the extension can be ignore, what if there a folder with the same name ?

**Comment by totkeks** [comment]
@kvprasoon powershell already works like this. You don't have to write the extension and it still works. Hence tab completion should work the same way.

Just try it with `cmd`. You can run it like this, but if you press `<tab>`, you get `cmd.exe`, which is the same.

**Comment by vexx32** [comment]
That applies to executables located via `$env:Path`, but I don't know that it applies to all commands or scripts in arbitrary locations?

**Comment by totkeks** [comment]
@vexx32 Actually, that's what I meant. I guess I was not precise enough, going to update the original post.

**Comment by kvprasoon** [comment]
> I type powersh<tab> and it expands to powershell and not powershell.exe

PowerShell do tab complete it to `PowerShell.exe` . What is you PowerShell version ?

**Comment by vexx32** [comment]
@kvprasoon that's the request at hand; he _wants_ it to expand to only `powershell`, not completing the extension, since it will _run_ just fine without it.

**Comment by kvprasoon** [comment]
So the ask is to change tab completion. @vexx32 do you see any ROI for this ?

**Comment by vexx32** [comment]
I suppose it might make some sense in terms of increasing UX consistency between what tab completes and what actually can be executed?

I don't think it's _overly_ complicated to implement, but I'm not sure exactly how this argumentcompleter is handled, so it might wind up being more complicated depending on the existing implementation... Hard to say without digging up the code, unfortunately. 😄

**Comment by kilasuit** [comment]
What's the actual real benefit here? Because TabCompletion is for completing to `Full Command names` which in this case includes the `.exe` or `.ps1` whilst the engine will look to the command values you can see with the below you could technically brake all scripts that don't reference the full `powershell.exe` with the following

``` powershell
function powershell { "Whoops you broke using PowerShell for PowerShell.exe in the terminal due to command preference - for more info run 'Get-Help about_Command_Precedence'"}
```

Then tab complete and you would have a PowerShell Function as well as the PowerShell Application `powershell.exe`
for more info on command preference have a look at ` Get-Help about_Command_Precedence`

Also - `This would make the behavior similar to how the search for executable scripts work.` - technically this is incorrect as per the below tabcompletion for slmgr.vbs which is an executable script and also shows the extension as per mentioned above (and IMO always should)
```Powershell 
Cd C:\
slmg
```

The reason at the prompt I think that you should always be shown the file extension is that you may have scripts in different languages but are still executable scripts and share the same file name - build scripts are like this on xPlat projects

Take the following (in an admin prompt if you have v6 installed then this will work as it's a location on $env:Path)
``` powershell
New-Item "C:\Program Files\PowerShell\6\slmgr.ps1" -Value 'Write-Host "This is not the Slmgr vb executable script"'
```
now in the console type slm and tab complete

That's when you need to have the file extension and why I can't see any real benefit behind removing the extension from the returned completed commands and IMO actually hampers the UX - yes the extension may be surplus to most requirements but as it doesn't impact performance by doing what it's intended to do, whereas your suggested change would add lots of overhead with potential perf losses and be of marginal gain to not only the everyday Windows Scripter but also be a possible downturn on the xPlat ones as well.

Just my thoughts on this :-)

**Comment by slycordinator** [comment]
> @kvprasoon powershell already works like this. You don't have to write the extension and it still works. Hence tab completion should work the same way.
> 
> Just try it with `cmd`. You can run it like this, but if you press `<tab>`, you get `cmd.exe`, which is the same.

For some commands, the behavior when tab-completed is not the same.

I have Debian installed in wsl.

In powershell, when I enter `Debian` or `debian`, I get the Debian running inside the same window as powershell.

But if I type `Debian` or `debian`, then press tab, in either one gets completed to `Debian.bat`. If I then hit enter, a separate console window is spawned and Debian runs inside that instead.
