### ISSUE TITLE
'clear' should leverage tput reset on *nix

### ISSUE THREAD

**Issue by koddebugging** [PowerShell/PowerShell#8554]
# Summary of the new feature/enhancement

As as user, I want the same 'clear' experience in PowerShell on *nix, as I have in Windows. Currently, if I use 'clear' in Windows, this clears the buffer. Currently, in *nix, it appears to create a gap of blank lines and leaves the buffer mostly intact; so, I can scroll up to see the history.

I _believe_ that this is because pwsh is leveraging terminal and when clear is input by the user, it is passed to the terminal. However, the behaviour one would expect should be the equivalent of 'tput reset' in the terminal window - as this would be the same experience seen in PowerShell in Windows.

# Proposed technical implementation details (optional)

Instead of allowing 'clear' to pass to the terminal, translate the command to 'tput reset' and pass that to the terminal.

**Comment by SteveL-MSFT** [comment]
Interestingly, on macOS, `tput reset` doesn't clear the scrollback buffer.  However, if I follow it with "`e[3J" to explicitly clear the scrollback buffer, I believe the result is the desired behavior.  cc @mklement0 who is more of an expert on this

**Comment by koddebugging** [comment]
I wonder if the session manager for OSX is different. If so, you could use something like:

`if($Env:SESSION_MANAGER.Contains("unix")){ tput reset}`

And then case another if statement for OSX. 

I haven't an OSX device, so I can't test what the environment variables would be, to help any further.

**Comment by mklement0** [comment]
To get a consistent clear-screen-and-scrollback-buffer experience, I suggest using `tput clear; $host.ui.Write("`e[3J")`, as suggested in my review comments - this works with both iTerm2.app and Terminal.app on macOS and the standard terminal app on Ubuntu.

That said: While consistency across platform is nice, do note that macOS / Linux users may expect the scrollback buffer NOT to be cleared with `clear`, given that's what the native `/usr/bin/clear` utility does.

So I wonder whether we should simply defer to the native utility on Unix-like platforms (i.e., remove the alias on Unix-like platforms).

If we do that, users who want the Windows clear-screen-and-scrollback-buffer behavior on Unix must - as they currently do:

* use `tput reset` on Ubuntu
* use keyboard shortcut <kbd>Command-K</kbd> on macOS (both iTerm2.app and Terminal.app), because on macOS `tput reset` only clears the screen, without clearing the scrollback buffer.

**Comment by mklement0** [comment]
Assuming that cls is also an alias for Clear-Host currently, we could use that selectively to implement the clear-screen-and-buffer logic on Unix, while making `clear` defer to the native utility

**Comment by SteveL-MSFT** [comment]
@mklement0 you make a good point that Unix users may expect the scroll back buffer not to be cleared since that is the default behavior of `clear`.  Removing the `clear` alias might be the right thing to do while having `cls` aliased to `clear-host` which clears the scrollback buffer to have consistency with Windows.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agrees to remove `clear` alias on non-Windows, but the cmdlet should only be calling [Console]::Clear() and depend on .NET CoreFX to do the "right thing" which is currently terminal specific.

**Comment by mklement0** [comment]
@SteveL-MSFT: It would still be nice to at least allow opt-in via a  switch to also clearing the scrollback buffer on Unix-like platforms - please see #8606
