### ISSUE TITLE
Windows 10 5.1 Custom Powershell repair

### ISSUE THREAD

**Issue by digimbyte** [PowerShell/PowerShell#8565]
I know that this is mostly for V6 development but I'm having an issue with my windows 10 PS, that I can't seem to find help with anywhere.

I don't have access to commands such as "install-Module" or "PSVerstonTable"
I believe I may have installed a version of PS manually in the past, such as PS for windows 8.1 
is there any way to repair, or reinstall the correct version on windows 10 without an OS install?

I have sent a request here https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/36371911-broken-or-incorrect-powershell-on-windows-10

but so far no response.
I tried disabling PowerShell 2.0 in Windows Optional Features but it still runs, so I suspect its installed over the windows association

Name             : ConsoleHost
Version          : 5.1.17763.134
InstanceId       : 4086c4ce-c4dd-418f-99d2-e21781fd6486
UI               : System.Management.Automation.Internal.Host.InternalHostUser
                   Interface
CurrentCulture   : en-US
CurrentUICulture : en-GB
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

**Comment by MaximoTrinidad** [comment]
Unfortunately, this repository is only for PowerShell Core only and not Windows PowerShell.  As in your case, you did post in the already something in UserVoice, which is the place for Windows PowerShell Issues.

But, just in case, have try to install PowerShell Core and see it it also gives you any problem.

Sounds like is something broken (or corrupted) in the OS.

"_... is there any way to repair, or reinstall the correct version on windows 10 without an OS install? .._"

Doing a rebuild or restore of the system will be the only viable solution.  This may be a Operating System issue and not PowerShell.

In order to do a fresh OS installation you will need to find all of the manufacturer instructions and/or products images in order to complete a rebuild.  If the system still under warranty, then call the vendor.

**Comment by SteveL-MSFT** [comment]
@digimbyte Win10 has a repair feature that you should use as Windows PowerShell is part of the OS.
