### ISSUE TITLE
Make Clear-Host clear the scrollback buffer too on all platforms 

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8606]
_Update_:

The decision in #8603 to rely on `Console.Clear()` amounts to inconsistent behavior across platforms, for no good reason (there's no native behavior that needs to be emulated; native behavior, if desired, is accessible via the external `clear` utility).

If there's consensus that the desired behavior is to consistently clear the screen _and_ the scrollback buffer on all platforms, we have two options:

* Wait for  `Console.Clear()` to be fixed, if ever - see https://github.com/dotnet/corefx/issues/34463

* Roll our own solution in PowerShell [in the meantime].

The original proposal below was written under the assumption that platform-dependent behavior was intended, and therefore suggested an opt-in mechanism.

# Summary of the new feature/enhancement

Implement a switch named `-All` to direct `Clear-Host` to clear not only the current screen of terminal (console) hosts but to clear the scrollback buffer (the output history) as well.

`Clear-Host` now uses `[Console]::Clear()` (see #8603), which results in platform-specific behavior:

* Unix-like platforms: clears the current screen (terminal-window content) only.
* Windows: clears the current screen _and_ the scroll-back buffer.

That is, also clearing the scrollback buffer is invariably implied on Windows, whereas it is currently unavailable on Unix-like platforms.

Implementing `-All` would allow users to at least opt into a consistent cross-platform experience, e.g. via  a user-defined function such as `function clsa { Clear-Host -All }`.

Note: As before, this means that in the Windows console you do not have the option to selectively clear the current screen only, without erasing the scrollback buffer.

# Proposed technical implementation details (optional)

If `-All` is specified:

* on Windows: do nothing, because clearing the scrollback buffer is _invariably_ performed anyway.
* on Unix-like platforms, execute ``$host.ui.Write("`e[3J")``  after `[Console]::Clear()` to also clear the scrollback buffer.

**Comment by dhulwells** [comment]
Can I take this one?

**Comment by BrucePay** [comment]
@SteveL-MSFT @mklement0  Since `Clear-Host` on Windows already clears the scrollback buffer, this new switch `-All` would be a useless parameter on Windows resulting in either an error or it being silently ignored if used, neither of which seem undesirable.

> Note: As before, this means that in the Windows console you do not have the option to selectively clear the current screen only, without erasing the scrollback buffer.

We can certainly implement this on Windows if desired, but I don't know that I've ever wanted it. YMMV. 

@JamesWTruher @joeyaiello IIRC, the thrust of what we discussed in the committee meeting is that PowerShell would call `Console.Clear()` on all 'console' platforms and the CoreCLR team would implement the appropriate behaviour on each platform.  If the CoreCLR isn't doing the right thing on a platform, then a bug should be opened in the CoreCLR repo.  ***BUT(!) we do still need to go through the `$Host.UI.RawUI` APIs in order to support 'non-console' platforms like remoting.*** In fact, if the `RawUI` APIs were fully supported on non-Windows console hosts, this whole discussion might be moot.

**Comment by SteveL-MSFT** [comment]
@BrucePay it could be argued (and I expect the corefx team to argue) that [Console]::Clear() has the correct behavior from their point of view today which is terminal specific.  Personally, I prefer to have the scrollback buffer cleared as my typical use case is that I clear the screen so I can output a bunch of content and expect the buffer to only have the new content whereas retaining the buffer means I have to visually determine where the new content exists when I use my scroll wheel.  Having `-All` being no-op on Windows doesn't seem bad to me.

**Comment by mklement0** [comment]
>  Personally, I prefer to have the scrollback buffer cleared as my typical use case is that I clear the screen so I can output a bunch of content and expect the buffer to only have the new content whereas retaining the buffer means I have to visually determine where the new content exists when I use my scroll wheel.

Amen to that.

So, from that perspective the best user experience would be to consistently clear the scrollback buffer too, on all platforms, as originally suggested in #8554.

Your decision was to rely on `[Console]::Clear()`, which, I would argue, shouldn't exhibit platform-specific behavior either (and perhaps should offer a parameter for opting into screen-only clearing).

So, yes, a CoreFx issue should be opened, but if the consensus is that _we_ want buffer clearing  on all platforms, we can certainly make that happen now without having to wait for `[Console]::Clear()` to be fixed.

**Comment by mklement0** [comment]
I've opened a CoreFx issue: https://github.com/dotnet/corefx/issues/34463

**Comment by SteveL-MSFT** [comment]
@mklement0 I had to rollback the change from [Console]::Clear() back to $RawUI since [Console]::Clear() doesn't work remotely when there isn't a physical console (see https://github.com/PowerShell/PowerShell/pull/8609).

**Comment by iSazonov** [comment]
From https://github.com/PowerShell/PowerShell/pull/8609#issuecomment-452855146
>  there's interest to convert this to a C# cmdlet and extend it, so let's defer any enhancements to that effort
> it's implicitly part of #8606 since the way Clear-Host is currently implemented it's impossible to extend

**Comment by SeeminglyScience** [comment]
Is there any reason why these changes wouldn't go into `ConsoleHost` instead of `Clear-Host`?  The host can decide what to do with the current `SetBufferContents` even if it doesn't *really* support the API.  For example, PSES will invoke `Console.Clear` if the args look like it came from `Clear-Host` but will no-op if it's passed anything else.

I realize that #8609 already changes back to using `$Host` for Windows, but is the expectation that custom hosts should replace `Clear-Host` for non-Windows?

**Comment by iSazonov** [comment]
@SeeminglyScience I think this would be in ConsoleHost. Fill free to push PR if you want.

**Comment by SeeminglyScience** [comment]
@iSazonov All of the the changes so far have made within the function `Clear-Host` itself instead of `ConsoleHost`.  There may be a very good reason for this that I'm not aware of, I'd just like to ensure that a custom host can still implement `Clear-Host` support on non-Windows platforms.

**Comment by iSazonov** [comment]
My understanding from PR discussion is that intention is (1) convert Clear-Host to binary cmdlet, (2) enhance rawui apis.

**Comment by joeyaiello** [comment]
I'm not well-versed enough to have any opinion on the `Clear-Host` vs. `ConsoleHost` discussion, but I'm in favor of:
* Clear-Host respecting `Console.Clear()` (and subsequently, the terminal it's being run in)
* `Clear-Host -All` no-op'ing on Windows. Makes it easier for people to add it to their `$PSDefaultParameterValues`

**Comment by mklement0** [comment]
@joeyaiello: 

The CoreFx team has agreed to fix `Console.Clear()` to clear the scrollback buffer too (see https://github.com/dotnet/corefx/issues/34463), where supported - which is pretty much everywhere these days -  which obviates the need for an `-All` switch.
The documented intent was always to clear the scrollback buffer too.

We can either wait for that fix or roll our own in the meantime.

I also can't comment on the `Clear-Host` vs. `ConsoleHost` discussion.

**Comment by mklement0** [comment]
@SteveL-MSFT 

> to have Unix behavior on Windows

The Unix behavior is _accidental_, both in terms of `Console.Clear()` and the native `clear` utility (at least on Linux): the _intent_ has always been to clear the scrollback buffer too; only _technical_ reasons prevented that functionality.

As previously argued by you (and I concur), clearing the scrollback buffer too is the _expected_ and _most useful_ behavior.

Therefore, clearing the screen _only_ - if needed at all - should require _opt-in_, and not vice versa; thus, implementing something like a `-ScreenOnly` switch would make sense.

The advantages are:

* sensible default behavior, on all platforms

* no surprises to Windows PowerShell users

* variant functionality - if needed - available on an opt-in basis

---

If you're really intent on this departure from expected behavior, note that https://github.com/PowerShell/PowerShell/pull/8603 must be revised, given that a fix to `Console.Clear()` is coming.

**Comment by SteveL-MSFT** [comment]
@mklement0 just to be clear, @PowerShell/powershell-committee decisions aren't and don't have to be unanimous but in the end we have to agree and move on.

One of the arguments presented is that Unix has this current behavior and if significant users wanted the scrollback buffer cleared, then we would have expected `clear` to have changed.    Isn't your CoreFx change to add a parameter to allow clearing the scrollback buffer and not clearing it by default?  In anycase, `Clear-Host` can't use [Console]::Clear() since it doesn't work over PowerShell remoting (unless it solely relied on VT100 and/or printing output...).

Personally, I'll have $PSDefaultParameterValues in my $Profile to cover this...

**Comment by mklement0** [comment]
@SteveL-MSFT 

>  Isn't your CoreFx change to add a parameter to allow clearing the scrollback buffer and not clearing it by default?

No, after some discussion, it isn't: the agreement is that clearing the scrollback buffer too was always the intent, so the fix will ensure just that - no additional variations in behavior will be introduced.

---

> if significant users wanted the scrollback buffer cleared, then we would have expected `clear` to have changed.

As for the intent: from `clear`'s  `man` page on Ubuntu:

> clear clears your screen if this is possible, including its scrollback buffer (if the extended “E3” capability is defined).  clear looks in the environment for the terminal type given by the environment variable TERM, and then in the terminfo database to determine how to clear the screen.

As for the practice: 

I'm reminded of the saying "Broken gets fixed, but shoddy lasts forever".
That is, users have probably found platform/terminal-emulator-specific workarounds to get the behavior they desire - yet, they'd probably prefer for `clear` to do the right thing, _if they knew they could rely on it_.

---

> Clear-Host can't use [Console]::Clear() since it doesn't work over PowerShell remoting (unless it solely relied on VT100 and/or printing output...)

That's a separate issue, and I can't speak to that, but limitations due to remoting shouldn't dictate the default behavior for the typical, local case.

---

As for the meta issue:

> in the end we have to agree and move on.

Of course, and you always _do_, by virtue of your ultimate fiat power.

Conversely, if I feel that important issues haven't been addressed, I will attempt to point that out.

You're free to ignore that, but I wish you didn't, for the benefit of the community at large.

Of course, my objections may turn out to be misguided, but whether they are will only emerge in the course of a _discussion_. I recognize that deciding when it's time to stop is a subjective assessment, and you're free to do so anytime (and have decided to do so on several occasions).

On a personal level, however, I frequently find myself thinking that more discussion is needed and that when the fiat decisions are handed down they lack detail / aren't convincing to me personally.

**Comment by SteveL-MSFT** [comment]
@mklement0 PS-Committee decisions should not be taken as absolute.  If more data is available that we didn't have at the time of discussion, we welcome that and certainly can change/update decisions.  I don't imagine any work here will happen in time for 6.2 anyways, so let's revisit this once corefx has the change as that would set some precedent we could consider following.

**Comment by mklement0** [comment]
Sounds good; thanks, @SteveL-MSFT.

**Comment by iSazonov** [comment]
In related CoreFX issue Core team agreed that Console.Clear() must be "clear scroll buffer". So we need wait the fix from .Net Core. Today I reread all about the problem and I agree with @mklement0 that modern expectations is to clear scroll buffer on Unix too.
While we wait CoreFX fix we could implement this in out RawUI API.
As for remoting we should open new issue and fix this using our RawUI API.

**Comment by SteveL-MSFT** [comment]
For remoting, the current architecture expects the RawUI API to be local to the client so it doesn't work remotely as there isn't a RawUI available on the remote system.

**Comment by SeeminglyScience** [comment]
@SteveL-MSFT If the logic for clear host is moved to `ConsoleHostRawUserInterface.SetBufferContents` then the original function will work remotely.  In [PSES we check](https://github.com/PowerShell/PowerShellEditorServices/blob/8730ea45639d20ed63f0ce8a3b12f77b846a35e6/src/PowerShellEditorServices/Session/Host/TerminalPSHostRawUserInterface.cs#L243-L258) for the parameters that the `Clear-Host` function sends:

```csharp
public override void SetBufferContents(
    Rectangle rectangle,
    BufferCell fill)
{
    // If the rectangle is all -1s then it means clear the visible buffer
    if (rectangle.Top == -1 &&
        rectangle.Bottom == -1 &&
        rectangle.Left == -1 &&
        rectangle.Right == -1)
    {
        System.Console.Clear();
        return;
    }


    this.internalRawUI.SetBufferContents(rectangle, fill);
}
```

If similar logic (just now realizing we don't check the fill, that needs to change) is put into `ConsoleHost`, then you could change how `Clear-Host` works without hurting remoting (or other hosts) since `ServerRemoteHost` will send the request back to `ConsoleHost`.

**Comment by dragonwolf83** [comment]
To add some context, there are a several [clear issues](https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is:issue+label:integrated-terminal+cls+) reported in VS Code. A few of them are about scrollback not clearing as expected because of winpty issues. 

From reading the history, not clearing scrollback appears to be broken behavior in `libvte` that has persisted. Since the native `clear` is used, that behavior is respected which gives PowerShell the freedom to implement clear properly with scrollback cleared consistently.

**Comment by iSazonov** [comment]
@mklement0 Console.Clear was fixed in .Net 8.0. Can we close the issue?

**Comment by mklement0** [comment]
@iSazonov, as of .NET 8.0.0-rc.2.23479.6 (the version underlying PowerShell 7.4.0-rc.1), it is _not_ fixed on macOS.

I'm unclear on whether the fix hasn't landed yet, or whether it isn't effective on macOS.

**Comment by iSazonov** [comment]
@mklement0 I added comment in https://github.com/dotnet/runtime/issues/28355

**Comment by mklement0** [comment]
Thanks, @iSazonov - indeed, as you've also found, it has _not_ been fixed on _macOS_.
