### ISSUE TITLE
Test-Path -IsValid -PathType Leaf doesn't correctly recognize a leaf

### ISSUE THREAD

**Issue by fullenw1** [PowerShell/PowerShell#8607]
This issue is about an incorrect validation of the `Test-Path` cmdlet.

When a path ends with a backslash it is supposed to be a **container**.

Furthermore, according to the official documentation:

> -IsValid
> Indicates that this cmdlet tests the syntax of the path, regardless of whether the elements of the path exist. This cmdlet returns `$True` if the path syntax is valid and `$False` if it is not.

and also

> "Leaf. An element that does not contain other elements, such as a file."

[https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-path?view=powershell-6](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-path?view=powershell-6)

However, when using the `-IsValid` parameter combined to the `-PathType Leaf` parameter in order to validate the syntax of a file path, it is incorrectly validated as a **leaf**.

For example, the following command line returns `$true` instead of `$false`.

`PS C:\> Test-Path -IsValid -PathType Leaf -Path 'C:\Something\'`
`True`
`PS C:\>`

It should return false because a leaf path cannot end with a backslash.

This behavior has been tested on PowerShell 5.1 and 6.1.1.

**Comment by fullenw1** [comment]
Thank you for the explanation.
Until now we could assume that both can be used together, and when not, we had to find out which one is overtaking the other.

The breaking change (puting them in separate parameter sets) in the next version would probably be the logical way to go.
And if not, at least the documentation should be updated to avoid the confusion.

**Comment by iSazonov** [comment]
For future breaking change reference #6745

**Comment by iSazonov** [comment]
@fullenw1 Please open issue in PowerShell-Docs repo.

**Comment by fullenw1** [comment]
I have created [pull request #3537](https://github.com/PowerShell/PowerShell-Docs/pull/3537) in the PowerShell-Docs repository.

**Comment by iSazonov** [comment]
Close until we want the breaking change

**Comment by mklement0** [comment]
> Arguably `-IsValid` and `-PathType` should have been in separate parameter sets

I think it makes sense to not only _allow_ this combination (as is currently the case), but to _support it meaningfully_: When `-PathType Leaf` is given, to validate the path as an item _name_, i.e. in the case of the file-system provider as a _file name_ rather than a _path_, using [Path.GetInvalidFileNameChars](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.getinvalidfilenamechars)

 * See also: https://github.com/PowerShell/PowerShell/issues/20847#issuecomment-2004948274

While technically also a breaking change, this could be considered a _bug fix_.
