### ISSUE TITLE
Guys, why you won't do really good and simply shell console?!

### ISSUE THREAD

**Issue by kamilk91** [PowerShell/PowerShell#8830]
Is it really stupid that i cant paste by ctrl + v, i have to open ssh-agent every time i try to connect ssh, i have to have 2 OS on my 3 computers, because copying and pasting of text with returns is nightmare. Please think about that.

**Comment by vexx32** [comment]
Please refer to the issue template; we really need a bit more to go on and specifics of the issues you're having.

We're more than happy to try to help and improve whatever you feel is lacking, but we really need the issues you're having clearly laid out so that we can effectively address them. I think it's fair to say that we cannot implement a fully effective solution without first having a clear description of the problem and how it's impacting what you're attempting to, wouldn't you agree? 🙂

**Comment by rkeithhill** [comment]
If you're using the PowerShell Corec console it supports <kbd>ctrl+v</kbd> for pasting.  Also, newer versions of Windows 10 console (used by both cmd and PowerShell) support paste via <kbd>ctrl+shift+v</kbd>.

ssh issues should be posted to https://github.com/PowerShell/Win32-OpenSSH/issues.  However, I've been using ssh on Windows 10 1803/1809 and is is pretty simple to set ssh-agent to serve your passphrase all the time.  Once you've add the Windows optional feature OpenSSH Client, run this command from an elevated PowerShell console to enable the ssh-agent service:
```
Get-Service ssh-agent | Set-Service -StartupType Automatic -PassThru | Set-Service
```
Then add your private key (supplying your passphrase):
```
ssh-add ~\.ssh\<private-keyfile-name>
```
If you want to use ssh: protocol with Git you will need to also let Git know that it should use the Windows built-in version of openssh instead of the version that ships with Git for Windows.  Do that like so:
```
git config --global core.sshCommand "C:/WINDOWS/System32/OpenSSH/ssh.exe"
```
