### ISSUE TITLE
Compress-Archive -Update deletes the destination if an empty source

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#8840]
_From @bchris999 on January 29, 2019 18:32_

$items | Compress-Archive -DestinationPath Archive.zip -Update

Assuming Archive.zip is already there, if $items contains filenames (e.g. from Get-ChildItem) it works fine. If $items is empty, it deletes the destination archive instead of adding 0 files to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e67ee59-8a3e-59ad-7c8d-a78605f55b66
* Version Independent ID: 3c8b8ee9-6a97-4eda-d184-49e728abf0a6
* Content: [Compress-Archive (Microsoft.PowerShell.Archive)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Archive/Compress-Archive.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Archive/Compress-Archive.md)
* Product: **powershell**
* GitHub Login: @anmenaga
* Microsoft Alias: **anmenaga**

_Copied from original issue: MicrosoftDocs/PowerShell-Docs#3622_

**Comment by sdwheeler** [comment]
@SteveL-MSFT Should this also be a product bug?

**Comment by sdwheeler** [comment]
_From @SteveL-MSFT on February 1, 2019 3:47_

Yes, this is a product bug.  @bchris999 would you mind opening an issue in https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues?

**Comment by sdwheeler** [comment]
Shiproom notes - move to Powershell repo issues

**Comment by stummsft** [comment]
When using Update, the target archive also gets deleted when one of:
1. **All** of the path elements provided are unsuccessful.
2. **Any** file access error occurs after any previous provided path has been successful (when multiple paths are provided in an array)
3. When only one path element is provided and there is a file access error opening it (as a consequence of issues 2 and 1 combining)

To the first issue, a path will be unsuccessful if:
1. It is an empty directory
2. It is a shell glob that does not resolve to a real file or non-empty directory
3. A file access error occurs: statically inaccessible due to permissions or runtime inaccessible due to being in use by another process. There may be other possibilities.

To the second issue, if the file is statically inaccessible due to user permissions or is in use by another process, an exception of CompressArchiveUnauthorizedAccessError will be raised at line 632 but then the constructor at line 808 for System.IO.BinaryReader will raise a "Stream was not readable." exception. This seems to be a stale initialization issue with $currentFileStream because the assignment at 790 never occurs due to the exception raised inside of System.IO.File::Open(). I can put in a tiny PR for it as it's a one-line fix.

If any provided path succeeds, the destination zip's contents will be preserved unless the access issue is triggered. If the access issue is triggered, all prior zip contents will be deleted and none will be added even if a later Path array entry would be successful.
I as yet have not been able to determine why the destination file gets deleted when one of these issues is triggered.

**Comment by sdwheeler** [comment]
This is a product bug. @stummsft  Please openin an issue in https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues
