### ISSUE TITLE
Home, End, Ctr+Arrow don't work (Arch/Linux 4.20)

### ISSUE THREAD

**Issue by ClairelyClaire** [PowerShell/PowerShell#8869]
# Steps to reproduce

  1. type something at the command prompt.
  2. Try to use Home or End to navigate the text.
  3. Try to use Ctrl+Arrow to navigate the text.
  4. Repeat 1-3 with text editor, e.g. nano.
  5. Observe.

# Expected behavior

Home, End, and Ctrl+Arrow should behave as in bash - go to beginning of text, end of text, and skip words left and right.

# Actual behavior

  * Home prints ~
  * End prints ~
  * Ctrl+Arrow does nothing

# Environment data

I used yaourt on Arch to install.

```none
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.2
PSEdition                      Core
GitCommitId                    6.2.0-preview.2
OS                             Linux 4.20.0-arch1-1-ARCH #1 SMP PREEMPT Mon Dec 24 03:00:40 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by lzybkr** [comment]
This is most likely not a PowerShell problem.

Try `[Console]::ReadKey()` then type <kbd>Home</kbd>. Output should look like:

```
KeyChar  Key Modifiers
-------  --- ---------
        Home         0
```

I'm guessing it won't, in which case the problem could be with:

* The setting for `$env:TERM`
* .Net Core
* The terminfo database

**Comment by rkeithhill** [comment]
@lzybkr This is what I see on Ubuntu 18.04 (when I ssh in from Windows PS 7 and then start pwsh):
```
09-01 21:23:44 3> [Console]::ReadKey()

KeyChar    Key Modifiers
-------    --- ---------
       Escape         0
```
This is a real bummer as it makes moving around a command line painful.  Here's the term info:
```
09-01 21:29:01 4> dir env:term*

Name                           Value
----                           -----
TERM                           xterm-256color
```

**Comment by rkeithhill** [comment]
I'm pretty sure this is a PowerShell problem and probably not a PSReadLine problem.  FWIW, I only see this when I SSH into our RedHat or Ubuntu build machines.  I don't see this issue in Bash but I do see it when I then start up pwsh.  I also see it when I start pwsh with `pwsh -noprofile -noni` which, I think, doesn't load PSReadLine.  I see this when using both conhost and WindowsTerminal.  And it is somewhat maddening TBH.  

![PwshHomeEndBug](https://user-images.githubusercontent.com/5177512/64563358-650e1200-d30c-11e9-883c-5763c8c1fbc8.gif)

This shows the issue on 6.2.2 but I just tried PS7-preview.3 and it behaves the exact same way.

**Comment by npodbielski** [comment]
Is there any chance to fix this. I would even try to do it myself since bash is maddeningly hard to do even easiest thing but I cannot swap pwsh because it lacks that little things like arrow keys support :)

**Comment by iSazonov** [comment]
/cc @daxian-dbw @SteveL-MSFT If the problem is in .Net Core we need to get a fix before .Net Core 3.1 LTS.

@rkeithhill Could you please make the test with simple C# app which only output Console.ReadKey()?

**Comment by SteveL-MSFT** [comment]
This seems most likely an issue in .NET Core.  Agree with @iSazonov that a simple C# console app to repro would be ideal.

**Comment by AndrewSav** [comment]
I'm slightly preplexed by these comments. This is an issue that is stabely reproducible in powershell and it does not seem to be reporoducible in a C# console app. Also it does not seem that there is any evidence is given that it is not a Powershell issue. 

Could guys please clarify your line of thinking?

**Comment by SteveL-MSFT** [comment]
@AndrewSav when PSReadLine is not involved as shown in @rkeithhill's example, pwsh has a simple [ReadLine](https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L1886) that doesn't do any translation of keys.  It is whatever the .NET API returns.

**Comment by AndrewSav** [comment]
@SteveL-MSFT thank you for this. Will I be too far off if I conjecture, that these services (Home, End, Ctr+Arrow ) are not provided by [ReadLine](https://docs.microsoft.com/en-us/dotnet/api/system.console.readline?view=netcore-3.0) itself, but by something else, for example on windows by console host?

**Comment by AndrewSav** [comment]
I tested the issue with pwsh 6.2.3 on Windows and Ubuntu Linux 18.04. I also tested it with a simple ReadLine console program. Here are the results.

**pwsh 6.2.3**

|                | Home/End      | Ctrl-Arrows    |
| -------------- | ------------- | ------------- |
| Windows 10     | Works         | Works         |
| Ssh            | Does not work | Does not work |
| gnome-terminal | Works         | Does not work |
| xfce4-terminal | Works         | Does not work |

**.net core 3.0.100  program with Console.ReadLine**

|                | Home/End      | Ctrl-Arrows    |
| -------------- | ------------- | ------------- |
| Windows 10     | Works         | Works         |
| Ssh            | Does not work | Does not work |
| gnome-terminal | Does not work | Does not work |
| xfce4-terminal | Does not work | Does not work |

**Console program text**

```csharp
using System;

namespace readline
{
    class Program
    {
        static void Main(string[] args)
        {

            Console.WriteLine("Hello World!");
            string hello = Console.ReadLine();
            Console.WriteLine(hello);
        }
    }
}
```
In **bash** it works in any combination.

**Comment by iSazonov** [comment]
PowerShell uses ReadConsole P/Invoke on Windows that is power method.
On Unix it emulates a line editor.
Possible fix for local host could be in https://github.com/PowerShell/PowerShell/blob/70a74fbfc891b3b9e8657d314860622cc97b20b8/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L1517

Perhaps @PaulHigin  could add more about ssh scenario.

**Comment by rkeithhill** [comment]
RE the Home/End keys the behavior is slightly different if you don't use PSReadLine but it still inserts a `~` character and the cursor does not move as expected.  This is running ssh.exe and not remoting via ssh.

**Comment by SteveL-MSFT** [comment]
I was able to repro this with ssh.exe we ship in Win10.  However, after using just the ssh.exe from https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.1.0.0p1-Beta, it works as expected.  So the issue appears to be in our Win32 port of ssh.exe.  Work is happening to update the ssh in Windows, but it'll take time to be released.  For now, you can just replace the ssh.exe from our GitHub release.

**Comment by AndrewSav** [comment]
@SteveL-MSFT did you see my matrix above? When I tested it with ssh on windows I tested with:

- ssh that comes with windows
- putty
- mobaxterm
- one from www.mls-software.com

It was exhibintg the problem on all of them, in addition Ctrl-Arrows did not work even without ssh.

I'll try and re-test with 7 but while I'm doing this, are you sure, we are not jumping the gun closing it?

**Comment by SteveL-MSFT** [comment]
@AndrewSav in the cases where your .NET Core 3 app doesn't work, it would have to be an issue in the .NET Runtime repo

**Comment by AndrewSav** [comment]
@SteveL-MSFT which version of powershell did you test this with?

**Comment by AndrewSav** [comment]
Okay, after some testing it does not seem to be fixed.

**PowerShell 7.0.0-rc.1 running on ubuntu 18.04**

|                | Home/End      | Ctrl-Arrows    |
| -------------- | ------------- | ------------- |
| Win32-OpenSSH OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5            | Does not work | Does not work |
| Win32-OpenSSH OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2            | Works  | Does not work |
| Putty  0.73            | Does not work | Does not work |
| MobaXterm 12.4            | Does not work | Does not work |
| git-bash 2.24.1.windows.2            | Works | Does not work |
| www.mls-software.com 8.0p1            | Works  | Does not work |

The ctrl-arrows do not seem to work at all via ssh. Home/End work for some clients but not for other.
bash (unlike powershell) works everywhere

Do you think there is an issue with powershell not suporting these?

**Comment by AndrewSav** [comment]
> @AndrewSav in the cases where your .NET Core 3 app doesn't work, it would have to be an issue in the .NET Runtime repo

How come that this would be an issue with .net runtime for non-ssh cases but would not be for ssh?

E.g. console app readline does NOT work for home/end over, say, with `Win32-OpenSSH OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2` but powershell does. so how come that issues with .net runtime do not affect this case but affect others?

**Comment by SteveL-MSFT** [comment]
PowerShell (specifically PSReadLine) uses [console]::ReadKey().  That may differ from the ReadLine() api that you have as your test app.  Try this instead:

```csharp
using System;

namespace readline
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("ReadKey:");
            var key = Console.ReadKey();
            Console.WriteLine(key.Key.ToString());
        }
    }
}
```

**Comment by AndrewSav** [comment]
Thank you, but wether they are different or not, most of I said is still valid and the questions still stand...

**Comment by iSazonov** [comment]
I think we should reopen.

@AndrewSav Could you please share test matrix for (1) Windows and Linux, (2) Home/End, (3)Right and Left Arrows (Ctrl-B/Ctrl-F), (4) Different terms/apps, (5) for both [Console]::ReadKey() and [Console]::ReadLine() ?

**Comment by AndrewSav** [comment]
@iSazonov I'm not sure how to present 5 dimentional matrix in text, I'm happy for suggestions. I think for ReadLine you already have coverage above, I don't see what's missing. For the ReadKey, results are indeed interesting.

```csharp
using System;

namespace readline
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            while (true)
            {
                ConsoleKeyInfo k = Console.ReadKey();
                Console.WriteLine($"Key:{k.Key}, Modifiers: {k.Modifiers}");
            }
        }
    }
}
```

Here are the obesrvations:

https://docs.google.com/spreadsheets/d/1a5wzdwwOmjsEZxedX3xb6bKhaI7sR5g0Or8iiGxCo34/edit?usp=sharing

**Comment by iSazonov** [comment]
@AndrewSav  Thanks for sharing your tests!

I see ReadKey() returns wrong sequences. 
I guess it is .Net Core _feature_. .Net Core internally load term database and probably uses it in ReadKey() for input transformations. You could try to find that term is detected and used in every case and either add new line in term database or modify exist one.

**Comment by AndrewSav** [comment]
@iSazonov ctrl-arrows do not work regardless ;(

**Comment by iSazonov** [comment]
You could debug the code 
https://github.com/PowerShell/PowerShell/blob/70a74fbfc891b3b9e8657d314860622cc97b20b8/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L1718-L1739

**Comment by SteveL-MSFT** [comment]
@AndrewSav your results are showing that the dotnet app isn't reading some key combinations correct, right?  Seems we should be discussing this in the dotnet/runtime repo unless I'm misunderstanding something.

**Comment by iSazonov** [comment]
@SteveL-MSFT I guess .Net Core can not find these terminals in term database and can not do right translation.

**Comment by AndrewSav** [comment]
@SteveL-MSFT Ctrl-Arrows do not work in powershell via SSH, it does not look like there is problems with Ctrl-Arrows in .net core. Could you please test independently and share your results?

**Comment by SteveL-MSFT** [comment]
@AndrewSav I did a test on Ubuntu 18.04 ssh to itself.  Was able to use Ctrl+LeftArrow within PS7 (I tested it by binding that chord to MenuComplete function in PSReadLine).

**Comment by iSazonov** [comment]
@AndrewSav Since you have repo on C# please open consulting issue in .Net Core runtime repository and share link here.

**Comment by artisticcheese** [comment]
Why this issue is closed when it's obviously still an open problem.

**Comment by iSazonov** [comment]
@artisticcheese See https://github.com/PowerShell/PowerShell/issues/8869#issuecomment-575481777 above - it shows that it is .Net Core issue.

**Comment by artisticcheese** [comment]
Is there an open issue with .NET core we can follow for resolution? I did not find it mentioned.

**Comment by rkeithhill** [comment]
**OpenSSH 8.1.0.0p1-Beta ssh run from a PS 7 GA console  (not Windows Terminal) to Ubuntu 18.04 Bash** - All key combos of Home/End, Arrows and Ctrl+Arrows works.  As soon as I start `pwsh` (v7 GA) on Ubuntu, Home/End continues to work as do arrows but Ctrl+Arrows does not work.  Also, and very infuriatingly, `Esc` does not work so clearing the input line requires pressing `End` and then `Ctrl+u`.

And this experience is even worse and frankly a bit embarrasing: 
**OpenSSH 8.1.0.0p1-Beta ssh run from a PS 7 GA console (not Windows Terminal) to Windows 10 running PS 7 GA and OpenSSH 8.1.0.0p1-Beta** - Ctrl+Arrows and Esc work but Arrows do NOT and neither does Home/End work.  Arrow keys that don't work makes the Windows to Windows SSH line editing and history recall experience awful - almost unusable.

**Comment by artisticcheese** [comment]
My attempt to replace bash with PSCore as default shell in Ubuntu come to screeching halt due to this ug, now not only I'm back to bash as default shell but don't use any powershell at all. For some it's minor issue and for some it's a dealbreaker.

**Comment by npodbielski** [comment]
Watching this issue for like a half a year and its funny and sad at the same time. I was watching in disbelief when maintainers were asking this one reporter to jump through hoops preparing matrices and the likes with keys behaviour  when this is so easy to reproduce. And they blamed external library and marked closed.
There is a name for that kind of behaviour in my language. It is kinda hard to translate but the closest would be: pushologic adapdet - meaning when someone pushes problem away from himself most likely pointing someone  else responsible. Very popular in government agencies and among bureaucrats. Culture changes, language changes, country and timezone but basics of human behaviours does not. **not my problem** summarizes this issue resolution.

**Comment by iSazonov** [comment]
@artisticcheese @npodbielski Do you ready to work on the issue? If yes, current conclusion is that the issue is not in PowerShell code but perhaps in .Net Core code. So please open new issue in .Net Core Runtime repo and work with .Net Core team. If no, please don't speculate - this do not add value in the discussion.

**Comment by npodbielski** [comment]
I certainly could. Probably it would be fun to work on such a big OS project given I would get few pointers, how to start and etc. But I want to picture you my perspective first. 

I did not spend much time using PS and most of it is on Ubuntu lately, but still I observed few strange behaviors:
 
1. PS sometimes shows garbage instead of usual welcome string (current dir and '>'). I think it is connected to not clearing screen correctly after terminating some long running job. You can still work as usual, it do not brake anything, but it does looks strange.
2. Searching through history and reusing some command by clearing some of it often causes strange changes in colors of already printed characters - most notably removing some command entirely can cause to '>' char at the end of welcome string to i.e. became red. It also do not brake shell but also looks strange.
3. Pasting larger chunks of text looks funny because it pastes char by char instead of all of it at once so you paste it and wait till PS will be done with it thinking how and why it is implemented like this. 
4. Keys issue, that you are surely already familiar with.

So PS is a shell and what shell does is basically printing text on screen and reading keyboard. And from my own experience PS is shitty with both for now. Having that in mind why would I invest my own spare time in this project? It is bad with it is most basic functionality. 

Would you i.e. bought a car that does not start like a 10% percent of the time? Or does not turn right? If this would be some other linux shell I would probably, just uninstall it and forgot about it right away. But it is from Microsoft so you do expect something more right? Certainly it is not some OS project maintained by 1 guy in a basement? Such big company have money and resources to do it better, right? Well for now it do not looks like it. 

You say that this discussion is counterproductive. For me it is not counterproductive but it was escalated to the topic how maintainers threats users and other people that want or might be able to help. Should not maintainers want project to succeed? I think they should. Does closing such obvious issue drives you toward such a goal? I do not think so. Then why you did it? Why I should fix it if looks like you (well not you specifically but all people involved in this project) does not care really?

In commercial projects I worked on, usually this works like this:
User or business reports an issue.

1. User or business reports an issue.
2. You check this out and it turns out that it is caused by some external library. 
3. You look for help on their support page, bug reporting software etc for possible solutions workaround.
4. You inform your users that problem was escalated and you are waiting for third party.

Doing otherwise would looks like I am hard to work with and ultimately could cause me being fired if it would occur often or issue would be really major for the users and I would refuse to help them.

Sometimes when I am looking for some tool and it is open source I skim through source code and issues to see if it is maintained and how open, helpful and active is community. IMHO PS is maintained actively but it is not open nor helpful. 
**This do not inspire confidence.** 

In readme it states:

> Welcome to the PowerShell GitHub Community! PowerShell Core is a cross-platform (Windows, Linux, and macOS). 

For now it do not looks like it is cross-platform. If you are asking me for contribution I am asking what is real priority of this project. It do not looks like Linux support is most important. There was recently 7.0 release. Seventh version of PS and it still can't handle basic navigation keys. 

I would certainly switch to PS as my default shell on Ubuntu since IMHO bash is bad for scripting, but PS is painful to use, so I am sticking to bash as shell and PS for some more advanced scripting (so I do not have to use it directly). 

Having that in mind why would I contribute? After all from this issue users are left with impression 'if you have an issue with our project, well... you are alone with that. Good luck fixing it yourself'. 

Do this post is counterproductive? I may certainly look like this for you, but in my opinion this is me contributing. 

**Please change your approach to users, change way how you support this project. 
Please re prioritize.
Please be more helpful and supportive.**

Then maybe people like me will be more likely to contribute to the project.
For now reason says: **do not.**

**Comment by artisticcheese** [comment]
I would create an issue if I understood fully what I need to write and where. I just lack that understanding. So choice for me was either spend unknown amount of time trying to figure out where to write and what to do to create issue or just don't use PS as daily driver. I just chose latter since it's easier since I have no pressing need to have PS as default shell (thought I would like it like I have it on Windows).

**Comment by iSazonov** [comment]
@artisticcheese Never mind. Please continue monitor the issue, try workarounds and share your experience from your scenarios.

@rkeithhill  I found some docs for Windows-OpenSSH https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH
Could you please look the document and try the recommendations?

**Comment by AndrewSav** [comment]
> @artisticcheese See [#8869 (comment)](https://github.com/PowerShell/PowerShell/issues/8869#issuecomment-575481777) above - it shows that it is .Net Core issue.

I still beleive that Ctrl-Arrows is not a .Net Core issue, since I cannot reporoduce it with .Net Core. Yet, it's easily reproducible with powershell.

**Comment by iSazonov** [comment]
@AndrewSav Can you add more info about Ctrl-Arrows? Do you test with and without PSReadline? Did you try `[Console]::ReadKey()` and command line?

**Comment by AndrewSav** [comment]
@iSazonov `[Console]::ReadKey()` returns Control LeftArrow and Control RightArrow as expected, but Ctrl-Arrows do nothing on the command line.

I'm not sure about PSReadline, how do you test with or without it? I installed powershell following instructions [here](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7) and tested with it.

**Comment by rkeithhill** [comment]
Load pwsh like so `pwsh -noprofile -noninteractive` to test without PSRL.

**Comment by AndrewSav** [comment]
It does not work either way, but differently. When runnning `pwsh` Ctrl-Arrows do nothing (do not move cursor), when running `pwsh -noprofile -noninteractive` they act as Arrow keys without Ctrl.

**Comment by iSazonov** [comment]
Ctrl-UpArrow/DownArrow does not implemented in PowerShell on Unix. You could assign a handler for these keys in PSReadline.
https://github.com/PowerShell/PowerShell/blob/70a74fbfc891b3b9e8657d314860622cc97b20b8/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L1742-L1749

**Comment by artisticcheese** [comment]
Slightly offtopic.
What is Crtl-Up/Down arrow is supposed to do in Powershell?

**Comment by AndrewSav** [comment]
>Ctrl-UpArrow/DownArrow does not implemented in PowerShell on Unix

Yep, this is what this issue is about. Why is this closed?

**Comment by lzybkr** [comment]
https://github.com/dotnet/runtime/issues/802 tracks issues with `Console.ReadKey` on Linux.

**Comment by AndrewSav** [comment]
It does not appear that this one is relevant. Firstly in never mentions ctrl-arrow keys, and secondly they seem to be repored as expected by `Console.ReadKey` on Linux.

**Comment by lzybkr** [comment]
@AndrewSav - got it - you should open an issue in https://github.com/PowerShell/PSReadLine for the lack of <kbd>Ctrl+LeftArrow</kbd> and <kbd>Ctrl+RightArrow</kbd> support in Emacs mode.  Better yet, you could submit a PR - it's a trivial fix.

**Comment by AgSync-Aaron** [comment]
Bare with me, this has a point.

I use windows 10 as my daily driver and have used windows as my desktop OS of choice since windows 95. I am a Microsoft fanboy through and through. I've been a developer using Microsoft technologies since the late 90s but have avoided Powershell because it's way too verbose for my liking. A coworker of mine turned me on to it again recently an I have fell in love with the power of the object oriented-ness (is that a word?). I am now a new fan of PowerShell and once you have a hammer everything looks like a nail, am-I-right? I knew Powershell has been cross-platform for a while now so I thought I'd try it out on some of our linux machines to automate some backup processes and it seemed to be working swell. 

Hot damn! I thought to myself this is great, one shell many OSes. Let's checkout the command line shell on Linux and maybe I can go with PS 100%. My glee turned to horror as I discovered that almost nothing works the same from the command-line as what it does in windows. An example is that auto-completion is very buggy with character casing and it doesn't cycle though the entries like it does on windows. PS continues to show all 148 (or whatever) entries as a giant block of text just like bash. "YUCK!" I say to myself upon this discovery, but it's easy to live with. Okay let's try something else. 

```
it@server:~$ sudo pwsh
PowerShell 7.1.0
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /home/it>
```
Um... what user am I again? The default prompt doesn't include the username on linux where the user means everything. This is a windows-ism that _shouldn't_ have been the default in linux. But I think that is changeable, let's move on. As I was exploring I discovered many of the keyboard shortcuts that I use in bash on linux and in powershell on windows **DO NOT** work for powershell in linux. This is a show stopper for me and it completely decimates my productivity. This has to be a config issue on my machine right?

Wrong.

When I discover a trail of issues going back about 2.5 years (at this point) that were closed for technicalities or because of the "it's not my problem" syndrome, _I was crushed_. How could a company that says it's product is cross-platform let something like this slip for over 2 years?  The responses from the Microsoft team members among this trail of issues has left me dejected.

It's issues like this one that really show me how (un)dedicated Microsoft is to cross platform technologies. This ongoing behavior I see from the Powershell team has really made me question whether a future issue that affects my powershell scripts on linux may go unfixed for over 2 years. I cannot justify this with my management. It's my decision to make, but if it breaks, it's my problem to fix and I cannot trust you Microsoft.

**Comment by iSazonov** [comment]
@AgSync-Aaron You could learn how to customize PowerShell prompt and PSReadline - I guess you have no idea what the _latest_ version of PSReadline can do.

**Comment by AgSync-Aaron** [comment]
You completely missed my point. Typical.

**Comment by iSazonov** [comment]
> Thank you for your snarky elitist comment.

Sorry, I didn't try to offend you. My efforts here are to make PowerShell better.
I just pointed out to you that you can easily customize the prompt and you will be pleasantly surprised by the capabilities of the new PSReadline 2.1. If you haven't tried it yet, I highly recommend it (see experimental features too and feedback).

> This issue is STILL an issue 2.5 years later.

PowerShell capabilities are based on .Net capabilities. There are fundamental contradictions in how different OSes work. It is not easy to get over it. Net team is actively planning next 6.0 milestone and you can discuss this and vote in .Net Runtime repository so as to help them prioritize.

**Comment by AgSync-Aaron** [comment]
I accept your apology, thanks. 

I had always figured there was a way to customize the prompt, I wasn't concerned about that. That was one of those imperfections that all software has and that I _wasn't_ concerned about it. It was just a data point in my journey of Powershell discovery that I was trying to share. I was trying to share my experience and how excited I was about the prospect of having one shell and one scripting language across OSes. And how that excitement turned to disappointment over missing basic functionality.  As as customer, _frankly_, I don't care who's team is responsible. Microsoft is my software vendor and my company pays them a _lot_ of money. 

If a member of our support team told our customer "sorry, that's not my problem" and hung up on them. We would probably lose that customer. I am trying to let Microsoft know that is how I was made to feel here by reading these issues and seeing them dismissed out of hand.

I am trying to standardize the languages that my company uses to manage our infrastructure. Microsoft says their "command-line shell" product is "cross-platform" but fails to pass some minimum requirements due to a bug. In all due respect, I cannot recommend ANY product, no matter the vendor, if what we consider basic functionality to be non-existent or buggy. I truly have honest concerns about using cross-platform powershell. This issue is over 2 years old and has been passed off to another team at Microsoft and that [issue](https://github.com/dotnet/runtime/issues/802) that is over FOUR years old!  If I run into a bug in my critical infrastructure that is deemed to be "some other team's" fault. Am I going to have to wait two years for a fix?

**Comment by AndrewSav** [comment]
> I was trying to share my experience and how excited I was about the prospect of having one shell and one scripting language across OSes. And how that excitement turned to disappointment over missing basic functionality. As as customer, frankly, I don't care who's team is responsible. 

Yes, this has been an uphill battle with a lot of finger pointing, and the end result that interactive experience on Linux via SSH from Windows is in a shape, where it cannot be used as the default command prompt. This is very disappointing and frustrating. "It's PSReadline!", "No, it's PowerShell!", "No it's .NET!".

To be completely honest I'm still _not convinced_ that it's .net because as far as I can see the .net bit works as long as it's not called from PowerShell. Yet the issue was closed. I supplied a lot of tests above but all I got in response is asking for _more tests_ and no evidence that someone tested it and it worked differently, no steps to reproduce _that_ were ever published.

In the end we have nothing else to do but to accept, that this is how PowerShell management chose to engage with the community. This is not satisfactory, but it is what it is.

**Comment by pencoe** [comment]
After some investigations i found that Powershell (.NET) uses ncurses, so i got Home and End working by editing Terminfo for the used $TERM (xterm for me) by
 - infocmp $TERM > terminfo.src
 - vi terminfo.src: look for the values of khome and kend. In my case they were \EOH and \EOF and had to be \E[H for khome and \E[F for kend. Be careful to search for this, there must be no second kxxxx entry with this code!
 - tic terminfo.src

After relogin Home and End did work in pwsh as expected.

I did not look for Ctrl-Arrow, but maybe this can be fixed in a similar way... next one please ;-)

Peter

**Comment by steven-willard** [comment]
This seems to be an issue still, I am unable to get ctrl+rightArrow or ctrl+LeftArrow to work in tokenizing the advance of the cursor location.

Here is a quick pwsh function you can dump in your console to confirm the readkey value.
```
function Test-KeyInputOnLinux {
  $key = ""
  while ($key.Key -ne "Enter") {
    $key = [System.Console]::ReadKey()
    $key.Key
  }
}

LeftArrow and RightArrow returned just fine.

Here is my version info, are we sure this is closed, or did I miss something?

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 20…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by AndrewSav** [comment]
@steven-willard yep, it's still broken. If you read the issue history, it seems pretty impossible to get stuff fixed here, and this is not just this issue, it's general attitude towards the community, e.g read [this](https://github.com/PowerShell/PowerShell/pull/10238#issuecomment-826091414) or [this](https://github.com/PowerShell/PowerShell/issues/15143#issuecomment-866317075). I personally abandoned any hope of this being fixed and moved on.

**Comment by npodbielski** [comment]
@AndrewSav @steven-willard 
Yep. I've been watching this thread for 2 years, lately mainly for fun and kicks. There should be banner:

> abandon hope all ye who enter here

PS on Linux is just broken and looks line maintainers want it to work this way. It would be nice to have the same CLI for both OSes but it looks line it won't be PS.
I think it would be easier to use bash via CygWin or something similar than PS on Linux. 
They should be just honest and kill it instead of lie to people that is 'cross-platform'.

**Comment by pencoe** [comment]
@AndrewSav @steven-willard @npodbielski 
> Yep. I've been watching this thread for 2 years, lately mainly for fun and kicks. There should be banner:
> 
> > abandon hope all ye who enter here

Yes, it's a pity... In this case (as far as i can tell) Powershell team and .NET team are playing "pass the buck" on each other.

> PS on Linux is just broken and looks line maintainers want it to work this way. It would be nice to have the same CLI for both OSes but it looks line it won't be PS.

Which is very sad, because PS is more powerful than bash in many ways.

> I think it would be easier to use bash via CygWin or something similar than PS on Linux.

No need to use CygWin since WSL and WSL2. In fact i found myself using bash on Windows more and more, because using PS on Linux isn't that easy as promised...

Peter

**Comment by yodasad** [comment]
There are too many comments in this thread... I cannot figure it out, why was the issue closed?
Home, Ctrl + Arrow are still not working in pwsh on linux.

**Comment by yodasad** [comment]
I've found a workaround: for Home and End you can use Ctrl+A and Ctrl+E respectively.

**Comment by artisticcheese** [comment]
https://twitter.com/artisticcheese/status/1485698470791028741 leave comment below to tell Microsoft that we still care.

**Comment by hepptho** [comment]
On Ubuntu, with PowerShell 7.2, I got the expected behavior by adding the following to my profile.ps1:

```powershell
Set-PSReadLineKeyHandler -Chord Ctrl+LeftArrow -Function BackwardWord

Set-PSReadLineKeyHandler -Chord Ctrl+RightArrow -Function ForwardWord

Set-PSReadLineKeyHandler -Chord Home -Function BeginningOfLine

Set-PSReadLineKeyHandler -Chord End -Function EndOfLine
```

This requires the PSReadLine module to be installed, but I think it always should be by default. You can use Get-Module to check if you are unsure.

To find the profile.ps1 file, you can use the $PROFILE variable or check the docs [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.2).

See also the docs on [Set-PSReadLineKeyHandler](https://docs.microsoft.com/en-us/powershell/module/psreadline/set-psreadlinekeyhandler?view=powershell-7.2) and [PSConsoleReadLine](https://docs.microsoft.com/en-us/dotnet/api/microsoft.powershell.psconsolereadline?view=powershellsdk-1.1.0). The customization options seem extensive; it's pretty neat.

That PSReadLine doesn't offer this behavior by default appears to be intentional, see PowerShell/PSReadLine#668.
Instead (as @yodasad noted) there are Ctrl+a and Ctrl+e for beginning / end of line, as well as alt-b and alt-f for backward word / forward word. Those are Emacs conventions, apparently, but that's where I'm out of my depth.

**Comment by artisticcheese** [comment]
> ```powershell
> Set-PSReadLineKeyHandler -Chord End -Function EndOfLine
> ```
This did not work for me from command line, I'm on 7.2.1 and I just executed those from command line instead of $PROFILE to test

```
PS /home/cloudadmin> import-module PSReadLine
PS /home/cloudadmin> Set-PSReadLineKeyHandler -Chord Home -Function BeginningOfLine
PS /home/cloudadmin> Set-PSReadLineKeyHandler -Chord End -Function EndOfLine
```

**Comment by hepptho** [comment]
Hmm, I'm on 7.2.1 / 20.04 too, and it works directly on command line as well as in profile.ps1.

An alternative that works for me as well is:
```powershell
Set-PSReadLineOption -EditMode Windows
```
The default EditMode on Linux appears to be Emacs, see also [here](https://github.com/PowerShell/PSReadLine/blob/master/PSReadLine/KeyBindings.cs) for a (presumably) comprehensive list of things that _should_ work in different edit modes. It's a nice reference.

If that also doesn't work, then the only idea I have left - and that's a wild guess - is that the keys are hijacked by something else. That sometimes happens to me with shortcuts on Linux, but it would be weird with Home and End.
You could try (if you haven't already) [Console]::ReadKey() followed by Home / End, and see what happens, and if it tells you anything.

**Comment by artisticcheese** [comment]
Interesting per you note for whatever reason my Home/End keys are both sending `Escape` for whatever reason.

```powershell
PS /home/cloudadmin> [Console]::ReadKey()

KeyChar    Key Modifiers
-------    --- ---------
      [0m Escape         0
```

**Comment by rkeithhill** [comment]
@hepptho RE `Set-PSReadLineOption -EditMode Windows` - thanks for that!!!  I can't believe what a dope I've been. I've been fighting the PSRL key bindings on Linux/macOS for a while now.  But my main machine is Windows.  For some reason, it never occurred to me to check/change the PSRL edit mode.  🤦‍♂️

**Comment by DTW-DanWard** [comment]
None of the above worked for me on Mac (PS 7.2.2) but this did - hope it helps someone else.

Create a new Terminal profile (or copy an existing) and add a Keyboard mapping for Home and End:
Home
  Key: Home
  Modifier: None
  Send text: (using Mac keyboard, not external): CTRL+A
  This should produce Send text of \001
End:
  Key: End
  Modifier: None
  Send text: (again on Mac keyboard, assuming no other modifier key changes): CTRL+E
    This should produce Send text of \005

**Comment by Clifra-Jones** [comment]
> ```powershell
> Set-PSReadLineOption -EditMode Windows
> ```
OMG! Thank you. This has been driving me nuts for months!
