### ISSUE TITLE
Allow trailing comma in parameter list

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#8873]
# Summary of the new feature/enhancement

Some languages like `Rust` allow a trailing comma in a parameter or argument list. In PowerShell, this would look like:

```powershell
param($a,)
```

Without allowing a trailing comma, some people resort to formatting like the following:

```powershell
param( [Parameter(Mandatory)][string] $Thing
     , [Parameter()][string] $AnotherThing
     , [Parameter()][string] $YetAnotherThing
)
```

The "leading" comma syntax gets used to minimize the lines changed when adding new parameters.

If a trailing comma was allowed, this style would be replaced with:

```powershell
param( [Parameter(Mandatory)][string] $Thing,
       [Parameter()][string] $AnotherThing,
       [Parameter()][string] $YetAnotherThing,
)
```

This could also be applied to method argument lists:

```powershell
$something.Insert($offset, $value,)
```

This usage might see less use than in parameter lists though as parameter lists usually span multiple lines whereas argument lists often do not.
```

**Comment by Jaykul** [comment]
I would love this. But I'd much rather see the commas be _optional_...

**Comment by timkittel** [comment]
👍 That would be amazing, stumbling the whole time over that missing feature during development.

**Comment by DoloMike** [comment]
Apparently this was a thing in v4 and subsequently taken out in v5 and later

**Comment by majkinetor** [comment]
10 years and almost every day I make this error... On some places you don't even get sensible error (in some pester tests in my case).

**Comment by iSazonov** [comment]
Perhaps PSSA could helps.

**Comment by majkinetor** [comment]
Meh...

**Comment by majkinetor** [comment]
Meh.

The one can edit script in various environments almost all which don't come with PSSA.  
This problem is far from specific to PowerShell, and various languages have the same issue. There is also non 0 number of those who tried to tackle this problem like Rust or Json5.

Futhermore it doesn't break compatibility and its in spirit with other PowerShell features. For example, array elements can be specified with comma or with new lines, also hashtables. That is one of the main reasons for me why are they so enjoyable to work with.
