### ISSUE TITLE
Issues faced in fresh repo till now:

### ISSUE THREAD

**Issue by aneeqhashmi** [PowerShell/PowerShell#8893]
# Issues faced in fresh repo till now:

```powershell
Latest repo should be bug free but I haven't been able to compile the project since Pull due to a number of errors. Some of them are addressed below.

1. Resource not found issues in all projects. 
2. Method definitions are missing. Some of them are InitializeTypeCatalog in CorePsAssemblyLoadContext, StringUtil.Format admbigious issue in multiple files, global::Modules not found in InitialSessionState, 
3. The type or namespace 'NativeMethods' does not exist in the namespace 'Microsoft.PowerShell.Security'

Looking forward to quick fixes.
```

**Comment by iSazonov** [comment]
Please read docs from the repo how clone, install prerequisites and build.

**Comment by vexx32** [comment]
Most if not all of these issues will be primarily due to some build steps not always being taken.

When building pwsh, it's best to use the provided `build.psm1` module located at the root of the repo. The main command from it you'll be using is `Start-PSBuild`

If you encounter any issues when building, I'd also add the `-Clean` switch. This will resolve the first issue, and likely most or all of the others. Not all build steps are taken by default, but a clean build is required at least once, and then often again as needed as you update your local copy of the repo, to ensure you also have an updated copy of all the files, many of which are generated during the build.
