### ISSUE TITLE
Shorthand for defining constants

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/PowerShell#8906]
# Summary of the new feature/enhancement
This is probably going to be a matter of some debate, but I'll propose it anyway. Whenever I create a module in PowerShell I like to use constants at the top of my file for format strings, messages, etc. that I re-use in various functions across my module or just to have a one-stop location to see all my string message related data. It would be nice if there was a more concise way to define a constant than using:
`Set/New-Variable -Name 'SOME_CONSTANT' -Value 'Value' -Option Constant`
`Set/New-Variable 'SOME_CONSTANT' 'Value' -Option Constant`

If there was some keyword that could be interpreted by the compiler it would make such declarations more concise and less cluttered

**Comment by vexx32** [comment]
Constants are pretty rare in PowerShell; once they're defined in a session they're basically impossible to remove no matter what you do. Given an administrative context, true constants are almost never needed or desired in most situations that come to mind as common uses of PowerShell. ReadOnly variables are _much_ more common, because should the need arise you can still remove them from the session using `Remove-Variable -Force`

That being said, however, I agree that Constant and ReadOnly variables should be able to be declared in a more intuitive fashion. In proper terms, these are typically registered as attributes attached to the internal PSVariable object, and their internal representation is _somewhat_ similar to type-constraining a variable (e.g., `[string]$Word = "banana"`). As such, I'd probably think that rather than using up a keyword for this, a specific attribute typing is a little more appropriate to the use here, something along the lines of:

```powershell
[PSConstant]$Million = 1e6
[ReadOnly]$ConfigVar = @{Name = "John"}
```

That's kind of the idea I think would be most straightforward to add in, and is in my opinion one of the more apropos forms this could take. 🙂

**Comment by SeeminglyScience** [comment]
I think the attribute syntax makes the most sense.

For constants, I'd love to see them as a parse time concept.  Define them once per script file and have the compiler use the literal instead of a variable lookup.  Bonus points for allowing them in attribute arguments.  Might be too different from how they currently work though.

**Comment by vexx32** [comment]
That would actually be awesome. I'd love to be able to have that.

**Comment by joeyaiello** [comment]
+1 to the fact that I don't see constants much in PowerShell. Out of curiosity, is there a reason you don't use `.psd1`s for your static strings and messages? ([Example here](https://www.powershellgallery.com/packages/xSQLServer/7.1.0.0/Content/en-US%5CxSQLServer.strings.psd1))

(Ooooh, re-reading @SeeminglyScience's post before I hit post, the parse-time nature of this is potentially compelling for PSSA/Editor Services scenarios...)

But let me have fun talking implementation assuming that there's value for constants beyond my limited understanding: 

Keywords are difficult because neither `const` nor `readonly` is reserved, so someone could have their own `const` or `readonly` functions:

```
C:\Users\jaiello> function const {'const'}
C:\Users\jaiello> const
const
C:\Users\jaiello> function readonly {'readonly'}
C:\Users\jaiello> readonly
readonly
```

Similarly, the provider syntax is going to break if someone has a `const` or `readonly` PSDrive:

```
C:\Users\jaiello> $const:var = 'var'
ObjectNotFound: Cannot find drive. A drive with the name 'const' does not exist.
C:\Users\jaiello> $readonly:var = 'var'
ObjectNotFound: Cannot find drive. A drive with the name 'readonly' does not exist.
```

So, by default, I think attributes would be the way to go. Plus, I think attributes work really well across the board.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this, we agree that attributes is the right solution.  The attributes should have the same semantics as using `Set-Variable` for scoping and behavior (like ability to remove).

**Comment by LethiferousMoose** [comment]
@joeyaiello I was actually not aware of storing strings in `.psd1` files, had I been looking for an i18n solution, I probably would have come across that...

**Comment by mklement0** [comment]
Note that there's now a lengthy debate in effective duplicate #15044 as to whether this syntactic sugar is worth implementing.
