### ISSUE TITLE
Investigate/code clean up ifdef in RemoteSessionNamedPipe.cs

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PowerShell#8925]
As called out in #8889...

in regards to: https://github.com/PowerShell/PowerShell/blob/1be3f4cc0e465ae11ad8e59e9060f5a59e4762eb/src/System.Management.Automation/engine/remoting/common/RemoteSessionNamedPipe.cs#L555-L557

@PaulHigin said:

> This code attempts to dispose the default pipe server on process (appdomain) exit, but it is disabled for CORECLR and so is dead code. This code should be removed or fixed to dispose both the default and custom pipe server objects.

**Comment by iSazonov** [comment]
.Net Core has "context" as appdomain replacement (and 3.0 will support assembly unload.)

**Comment by PaulHigin** [comment]
I don't mean that we need to dispose on AppDomain exit (since there is none) but that we should consider disposing on process exit (`AppDomain.CurrentDomain.ProcessExit` event is supported now).  We don't do it now but should look into whether it is needed, both for Windows and Linux platforms to ensure named pipe is cleaned up.
