### ISSUE TITLE
$Job.Results should be made public

### ISSUE THREAD

**Issue by mkellerman** [PowerShell/PowerShell#8958]
# Summary of the new feature/enhancement

Job objects have a internal property called Results that collects all output streams into one collection. Currently, it is impossible to reconstruct the stream from the split stream collections (Output, Debug, Verbose, Warning, Error...).

Even doing Receive-Job outputs the Write-Host to the host immediately, there is no way to capture this, and 'show' the result later on.

This would allow us to manage/handle the stream as we see fit. Export-Clixml would work beautifully for this purpose, and would allow us to Import-Clixml the stream at a later date. VERY useful for debugging deployments as code on remote servers. Especially when working with ScheduledJobs

This was already raised (see notes IN the code itself):
https://github.com/PowerShell/PowerShell/blob/1be3f4cc0e465ae11ad8e59e9060f5a59e4762eb/src/System.Management.Automation/engine/remoting/client/Job.cs#L526

# Proposed technical implementation details (optional)

It's a simple fix.. just change it to public.. 😄 

https://github.com/PowerShell/PowerShell/blob/1be3f4cc0e465ae11ad8e59e9060f5a59e4762eb/src/System.Management.Automation/engine/remoting/client/Job.cs#L684

**Comment by iSazonov** [comment]
It seems we discussed something related. Perhaps we could do more smart things.

**Comment by iSazonov** [comment]
Since it is new public API we need PowerShell Committee conclusion.

/cc @SteveL-MSFT @daxian-dbw

**Comment by iSazonov** [comment]
Is it good name for the new public property?

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this, we agree with supporting the scenario, however simply making that member public may not be the right design decision.  Instead, it may make sense to have a public member that is readonly that contains the collection of stream objects.  In addition, it would make sense to review if there are other cases (like PowerShell API) where it makes sense to make this collection available instead of separate streams.

**Comment by iSazonov** [comment]
>  In addition, it would make sense to review if there are other cases (like PowerShell API) where it makes sense to make this collection available instead of separate streams.

/cc @mklement0 @KirkMunro who could be interested in this (sorry if I wrong).

**Comment by KirkMunro** [comment]
> Currently, it is impossible to reconstruct the stream from the split stream collections (Output, Debug, Verbose, Warning, Error...).

It isn't impossible, at least not when you're invoking PowerShell using an SDK. You can subscribe to events for each of the different streams using respective stream collection property in `PowerShell.Streams`, and then when you `Receive-Job`, you will get events fired for each of the items returned from the job; however, when you are working from PowerShell itself this may not be a viable solution.

My issue with using jobs from PowerShell, where I want real-time processing of the data coming from the independent streams so that I can do what I want with them, is that there is no way to first create a job, then set up event handlers on that job for the streams, and only _then_ run the job. A job object has all of the `PSDataCollection` streams available, which have the event handlers that I want to subscribe to, but I _cannot_ create the job, then set up my event handlers, and then run the job. This is a much bigger shortcoming from my perspective, and I believe addressing that would also resolve this issue, but in a better way that would work for SDK users and PowerShell scripters, because it would support asynchronous execution, and allow me to manage the memory because I could clear the data stream content as I receive event notifications (which is what I already do). Compare that to the idea of `AggregatedStreams`, and now you have another stream where you need to manage content if you want to keep your memory requirements as low as possible while using background jobs or thread jobs.
