### ISSUE TITLE
Split-Path removes ¨´´ from Service Pathname

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#8980]
_From @francesco1119 on February 25, 2019 3:27_

It´s as simple as that Split-Path is removing the last '"' from every Pathname you query form any service:

```
$service = get-wmiobject -query 'select * from win32_service where name="SQLBrowser"';
Write-output $service.pathname 
Write-output $service.pathname | Split-Path
```

![missing](https://user-images.githubusercontent.com/3397477/53312511-37d2b700-391a-11e9-9bbd-0657a2559bcf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fc8b0a5-8130-a6e3-7e95-92495fbcb605
* Version Independent ID: 7871d186-25d2-78eb-9b50-cd04495ad981
* Content: [Split-Path (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/split-path?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Split-Path.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Split-Path.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

_Copied from original issue: MicrosoftDocs/PowerShell-Docs#3759_

**Comment by sdwheeler** [comment]
This is a bug. Moving this issue to PowerShell/PowerShell/Issue

**Comment by mklement0** [comment]
The underlying issue is how `Split-Path` treats paths that have _embedded_ quotation marks (which they shouldn't):

```powershell
PS> '"c:\tmp\file"' | split-path
"c:\tmp 

PS> "'c:\tmp\file'" | split-path
'c:/tmp
```

**Comment by iSazonov** [comment]
Is the issue related only to Split-Path or to other cmdlets and providers?

**Comment by sdwheeler** [comment]
Based on @mklement0's example, it looks like it is just a problem with Split-Path when the input is a string that contains quotes.

**Comment by iSazonov** [comment]
It seems we had such issue for completions (IntelliSense). It was fixed.

**Comment by mklement0** [comment]
I think this is a fairly exotic problem and I'm not sure we need to do anything about it:

Passing a path _with embedded quoting_ is arguably user error.

`Split-Path` blindly splits by the last `\` or `/` instance, which is normally fine, especially in light of `'/subdir` and `"/subdir` being technically valid paths (the latter only on Unix-like platforms), however unlikely.

`"C:\..."` is _not_ a valid path, however, because `"` cannot be used in paths _on Windows_ (and if it were a legal char., it couldn't be followed by a _drive spec_).

So, if we want to do something about this, we could check for the following specific cases _on Windows_ and report an error:

* if a `"` is present anywhere in the path
* if a an initial `'` is followed by a drive spec / UNC share

> It seems we had such issue for completions (IntelliSense). It was fixed.

In this case it was a _registry value_ that was defined with embedded quoting, not a user typing such a value.

**Comment by iSazonov** [comment]
So use `$service.pathname | Split-Path` instead of `Write-output $service.pathname | Split-Path`.

**Comment by mklement0** [comment]
@iSazonov: 

Your two commands are equivalent. What's needed is to strip the embedded quotes.

```powershell
$service = [pscustomobject] @{ pathname = '"c:\foo\bar baz"' }

$service.pathname -replace '"' | Split-Path
```

**Comment by daxian-dbw** [comment]
> I think this is a fairly exotic problem and I'm not sure we need to do anything about it:
Passing a path _with embedded quoting_ is arguably user error.

Agreed, not sure what we need to do. Checking if a path is valid (not if it exists) is not a trivial thing as one might think.

**Comment by francesco1119** [comment]
I now got it: is not `Split-Path` the problem but how `Get-wmiobject win32_service` handles the Pathname.
Look at this: if you run `Get-Process  | Select-Object Name,Path` each path of each process is printed without double quotes: 
![get-process](https://user-images.githubusercontent.com/3397477/53660689-5393df80-3cc3-11e9-9286-44377ab6d5fe.png)
But if I run `get-wmiobject win32_service | select name, pathname` I now realize that all the services that belongs to `C:\WINDOWS` are listed without double quotes while all the services belonging to `C:\Program Files` have double quotation:
![program files](https://user-images.githubusercontent.com/3397477/53660812-a53c6a00-3cc3-11e9-857f-b45c21c3a3ac.png)
So this is a `Get-wmiobject win32_service` bug.

Can we select the path through Get-Service insted of using `Get-wmiobject win32_service`? I would like to check if the bug persists in Get-Service too or if it's just a win32_service legacy

https://stackoverflow.com/questions/31374644/get-process-location-path-using-powershell

**Comment by sdwheeler** [comment]
I don't think this is a WMI problem. It is not unreasonable to expect that Split-Path should be able to handled quoted paths.

**Comment by mklement0** [comment]
@sdwheeler: 

We're not talking about _quoted paths_ here, we're talking about paths that have _extraneous embedded quotes_.

It's the difference between:

```powershell
$path = "c:\foo\bar"  # quoted path
$path '"c:\foo\bar"' # (quoted) path with extraneous embedded quotes
```

In the first case the `"` have _syntactical function_, and are _stripped_ after parsing, in the 2nd case they're _part of the data_.

As stated, the best we could do in `Split-Path` is to rule out _unambiguous_ errors with embedded `"` or `'`-prefixed paths that are followed by a drive spec. / UNC share - on Windows only.

---

As for the WMI / `Get-Service`'s behavior:

The problem is primarily one of _poor naming_:

What `.pathname` / `.BinaryPathName` / `ImagePath` (the name of the value in a service's registry definition, which is the ultimate source of the information) actually contain is a _command line_, not  a single binary's file path.

Such a command line is designed for parsing by a shell / the Windows API, and of necessity must support _embedded_ quoting.

With that in mind, you can use the following code to extract the binary (executable) file path that is _embedded_ in the command line:

```powershell
    # Sanitize the path:
    # * Some values have encosing "...", so we strip them, 
    # * others have arguments, so we only take the first token.
    $binaryPath = if ($binaryPath -like '"*') {
      ($binaryPath -split '"')[1]
    } else {
      (-split $binaryPath)[0]
    }
```


[This SO answer](https://stackoverflow.com/a/54774884/45375) of mine wraps this functionality in a function, `Get-ServiceFileInfo`.
