### ISSUE TITLE
Input of array type can't convert to string type mandatory parameter

### ISSUE THREAD

**Issue by bingbing8** [PowerShell/PowerShell#8985]
# Steps to reproduce

```powershell
function Test
{
    Param
    (
        [Parameter(Mandatory=$true)]
        #[ValidateNotNullOrEmpty()]
        [String]
        $AccessToken
    )
    write-host "Hello $AccessToken"
}
$a= @("abc")
Test -AccessToken $a

```

# Expected behavior

```none
arrary type should be able to be converted to string type parameter
```

# Actual behavior

```powershell
Test : Cannot bind argument to parameter 'AccessToken' because it is an empty string.
At line:1 char:19
+ test -AccessToken $null
+                   ~~~~~
    + CategoryInfo          : InvalidData: (:) [Test], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Test
```

# Environment data

PS C:\> $PSVersionTable

```none
This also repros on latest ps core.

Name                           Value
----                           -----
PSVersion                      5.1.17134.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by mklement0** [comment]
Your actual behavior doesn't match the premise, because it shows `$null` as the argument.
With an _array_ as the argument you'd get:

```none
Cannot convert value to type System.String.
```

I can't speak to the original design intent, but **since at least PSv2 passing an array to a `[string]`-typed parameter of an _advanced_ function (which your function implicitly is due to use of a `[Parameter]` attribute) resulted in said error**.

You can work around the problem by _not_ typing your parameter (or by typing it `[object]`):

```powershell
PS> & { param([Parameter(Mandatory)] $AccessToken) "Hello, $AccessToken" } ('foo', 'bar')
Hello, foo bar
```

By referencing array `$AccessToken` inside `"..."`, it is implicitly stringified (as usual, by separating the elements with a single space).

By contrast, **a _non-advanced_ function does _not_ requires this** - it happily converts an array to a `[string]`:

```powershell
PS> & { param([string] $AccessToken) "Hello, $AccessToken" } ('foo', 'bar')
Hello, foo bar
```

**Comment by iSazonov** [comment]
Your could turn on trace to see type convertions in bindings.

**Comment by iSazonov** [comment]
Close as stale issue. Feel free to continue discussion.
