### ISSUE TITLE
Send-MailMessage should be update to use a supported API

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#9031]
Send-MailMessage use a depreciated API according to https://github.com/dotnet/platform-compat/blob/master/docs/DE0005.md

We should remove or rewrite Send-MailMessage to use a supported API.

**Comment by pougetat** [comment]
Some quick thoughts after looking into this :
We need to start by adding more exhaustive tests for the cmdlet since the current base of tests is lacking. This can ensure we don't break compatibility with the previous implementation. 
Then the move can be made to the new api. Mailkit seems great in terms of features, documentation and maintenance of the project. 
Since we can now run send-mailmessage tests on devops and other local environments that aren't Linux with a recently checked in PR for this test base it makes the work that much more CI friendly.

**Comment by TravisEz13** [comment]
RFC https://github.com/PowerShell/PowerShell-RFC/pull/160 has been opened on this issue.  I'm going to close this issue.
