### ISSUE TITLE
No any way to pass empty pipeline (AutomationNull) to function parameter

### ISSUE THREAD

**Issue by dmitriyse** [PowerShell/PowerShell#9150]
# Steps to reproduce

```powershell
function Get-A {
    param($a)
    $a | % {Write-Host "Bug!"}
}

$emptyPipeline = (@() | % {})
$emptyPipeline | % {Write-Host "Proof of 100% empty pipeline "}

Get-A $emptyPipeline
#Get-A @($emptyPipeline)  #this trick works, but very frustrating
```

# Expected behavior

```none

```
`$a` parameter contains `AutomationNull` and nothing is printed

# Actual behavior

```none
Bug!
```
`$a` parameter contains $null

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Linux 4.4.0-17763-Microsoft #253-Microsoft Mon Dec 31 17:49:00 PST 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Indeed, passing a "null collection" - `[System.Management.Automation.Internal.AutomationNull]::Value` - as an _argument_ currently converts it to `$null`.

I can't speak to why this behavior was chosen, but hopefully others can. /cc @lzybkr 

Note that you can more simply create this "null collection" value with `. {}`

As for the enumeration behavior:

* `$null` _is_ passed through the _pipeline_, as you've observed.

```powershell
PS> $null | ForEach-Object { 'hi' }
hi
```

* By contrast, it _isn't_ if you use a `foreach` _loop_:

```powershell
PS> foreach ($val in $null) { 'hi' }
 # (no output)
```

While you _can_ use this distinction to prevent enumeration (assuming your function doesn't also need to distinguish between `[System.Management.Automation.Internal.AutomationNull]::Value` and `$null`, which is currently impossible via a _parameter_), I personally find it problematic - see https://github.com/PowerShell/PowerShell/issues/7049#issuecomment-399808799

Of course, you could also use `$null -eq $a`  to test `$a` for being `$null` and thereby avoid further processing.

**Comment by dmitriyse** [comment]
This is 100% abstraction leak. When you just want to write a script, you should always think about $null, [System.Management.Automation.Internal.AutomationNull]::Value and @(). Also about single element enumeration where you cannot get Count = 1.
This is horrible error-prone part of PowerShell.
Hope to see some cleanup here in PowerShell 7.0+

**Comment by dmitriyse** [comment]
The problems of this kind make PowerShell less attractive that it could be and kills many other benefits.

**Comment by dmitriyse** [comment]
As a current workaround, you need always put @(<something>) to force <something> behave as collection.

**Comment by mklement0** [comment]
I hear you, @dmitriyse.

With backward compatibility out of the picture, my vote is for the following:

* Default uninitialized variables to `[System.Management.Automation.Internal.AutomationNull]::Value` rather than `$null`.

* Preserve `[System.Management.Automation.Internal.AutomationNull]::Value` when passed as an _argument_ or used in an _expression_.

* This would allow conditionals to test for `[System.Management.Automation.Internal.AutomationNull]::Value` specifically, with `-eq`.
  * Currently, the unavoidable conversion to `$null` prevents that, because you cannot distinguish between  `[System.Management.Automation.Internal.AutomationNull]::Value`  and `$null`.
  * It's fine to continue to let it be  `-eq` to `$null` as the _RHS_, as long as the two cases can be distinguished.
     * That said, it's better not to use `$null` as the RHS of an `-eq` comparison in general, given that `-eq` exhibits filtering behavior with an array-valued LHS.
  * Perhaps a new automatic variable such as `$nullCollection` or `$nullArray` to more succinctly represent `[System.Management.Automation.Internal.AutomationNull]::Value` is called for, which would only be `-eq` to itself if used as the LHS.

I encourage you to read the discussion at #6745 and to add a comment at that briefly summarizes the issue here and links to it.

**Comment by lzybkr** [comment]
I'm not sure this was intentional, more like an oversight.

I believe the following scenarios differed in V2 and I changed that in V3.

```powershell
# direct piping
Get-EmptyPipeline | Do-Something

# piping after assignment
$something = Get-EmptyPipeline
$something | Do-Something 
```

If my memory is correct, then I just missed the scenario of passing the value as an argument.

**Comment by mklement0** [comment]
Thanks for the insight, @lzybkr.

Indeed, in v2 assigning `[System.Management.Automation.Internal.AutomationNull]::Value` to a _variable_ (such as returned from a pipeline with no output) implicitly converted it to `$null`, so sending such a variable through the pipeline later then unexpectedly resulted in `$null` getting sent as the input object to the next command in the pipeline (rather than not sending anything).

Fixing the _argument case_ too is a breaking change, however, if we leave the aspect of defaulting uninitialized variables to AutomationNull and fixing the `foreach` loop behavior aside, could it be considered a bucket 3 change?

In any event, these fixes are worth considering for a future version that is not beholden to backward compatibility.
