### ISSUE TITLE
Did not work as expect when using echo to append string to txt file

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#9194]
I tried to append one more string to my hosts file , but seems there is something wrong about code.Please bellow!
![code-issue](https://user-images.githubusercontent.com/36788337/54809088-31d3ba00-4cbd-11e9-9f25-fe3db78fce10.PNG)

Any advise ?

![show-code-issue](https://user-images.githubusercontent.com/36788337/54809711-0f42a080-4cbf-11e9-8628-98a3f00cacf0.png)

**Comment by mklement0** [comment]
Please note that this repo:

* is for PowerShell _Core_ issues only
* and not for general support questions.

You're using _Windows PowerShell_, whose default encoding with `>` and `>>` is "Unicode", i.e. UTF-16LE. This encoding defines characters as 2-byte units, with ASCII-range characters containing `NUL` in one of the bytes, which on output gives the appearance of being double-spaced.

To append to an ASCII-encoded file, you need to pipe to `AddContent -Encoding ASCII ...` instead of using `>>`.
