### ISSUE TITLE
Quake Style Drop Down

### ISSUE THREAD

**Issue by att0002** [PowerShell/PowerShell#9226]
# Summary of the new feature/enhancement

It would be nice to have a console drop down key (or combo), where the shell would slide down from the top of the screen. Refer to Linux based terminal emulators such as Tilda for an example.

**Comment by mklement0** [comment]
@att0002, PowerShell is not itself a terminal emulator, it is  a shell that runs _inside_ of one, so this is not the right place for your suggestion.

PowerShell Core works just fine with Tilda - by default, if it is your default shell, or via `Preferences >  Title and Command > Run a custom shell instead of the shell`.

**Comment by HumanEquivalentUnit** [comment]
[ConEmu](https://conemu.github.io/) is a terminal which can do this on Windows.

**Comment by SRGOM** [comment]
Please create this issue in github.com/Microsoft/Console. I'd love to see this too.

**Comment by att0002** [comment]
Thank you all for your replies. It looks like there is already a suggestion for this feature and it is in the backlog for the console. You can view it and vote for it here: https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/6510797-global-hotkey-to-activate-deactivate-running-conso
