### ISSUE TITLE
PS Core 6.2 Install-Module default scope changed

### ISSUE THREAD

**Issue by adubnik** [PowerShell/PowerShell#9248]
Hi,

I've installed new PS Core 6.2 and it does not install modules for all users (tested on Ubuntu) unless specified -scope AllUsers which per documentation is default.

**Comment by iSazonov** [comment]
Please add repo steps and link to the documentation.

**Comment by mklement0** [comment]
The change was intentional and is related to the version of the PowerShellGet module (which comes with PowerShell Core).

PowerShellGet v2.0 or higher now defaults to `-Scope CurrentUser`, and PowerShell Core 6.2.0-rc.1 comes with v2.0.4

In short:

* In PowerShellGet 2.x and going forward, the default is `-Scope CurrentUser`
* In PowerShellGet 1.x, the default is `-Scope AllUsers`
