### ISSUE TITLE
POSIX'ify, ZSH'ify & BASH'ify PowerShell?

### ISSUE THREAD

**Issue by ylluminate** [PowerShell/PowerShell#9296]
# Make PowerShell not only POSIX compliant, but also ZSH & BASH compatible.

I don't want to start any kind of negative feedback loop here, but I'm thinking about a way for folks like me to give PowerShell a chance.  I've used it off and on for years and each time I've used it I have always spit and cursed under my breath about how on earth could MS be pushing backwards vs forging ahead with a proven technology that sys admins and developers already know and love around the globe.  I'm impressed that Microsoft is taking such steps as open sourcing this and I think this kind of an attempt at a visionary movement forward is both honorable and praiseworthy.

In an effort to unify the shell world, I think PowerShell could get really creative by providing a ZSH and BASH compatibility layer.  Frankly I'd probably use PowerShell if I could do this as I'd feel good about it being supported by a serious, large and long term investor like Microsoft - even though it would be on macOS for my OS flavor.

So to this end, could you please implement a POSIX compliant layer in conjunction with ZSH and BASH compatibility that would allow us to bring our decades of accrued shell scripts and configurations over to PowerShell?

**Comment by iSazonov** [comment]
>  please implement a POSIX compliant layer

This has already been done. You can run these scripts from PowerShell just like any other application.

**Comment by chuanjiao10** [comment]
No two leaves in the world are 100% identical. Similarly, sh is not 100% compatible with bash. Run bash in pwsh and bash to run the script. It is a good idea. Please see the example:


Q: How do I embed a shell command in a .ps1 script?
answer:
Never use bash and .sh, there are too many pits inside. You only need to execute the string with bash in the .ps1 script of the Linux version of powershell.
======================
$bashcmd =
@'
Echo 'I am a bash command'
Echo 'command can have single quotes'
Echo "can have double quotes in the command"
Echo 'If you need to parse the variable, use this bracket, pay attention to the end of the line must be wrapped '
Echo '@\"'
Echo '$a'
Echo '\"@'
'@
$powershell variable = /usr/bin/bash -c $bashcmd
#Need to be escaping, a little bad
======================
or
$powershell variable =
@'
Echo 'I am a bash command'
Echo 'command can have single quotes'
Echo "can have double quotes in the command"
Echo 'If you need to parse the variable, use this bracket, pay attention to the end of the line must be wrapped '
Echo '@"'
Echo '$a'
Echo '"@'
'@ | /usr/bin/bash
#No need to escape, recommend
======================

This is a hassle, but using ps1 is easier to debug than using bash. Single step, breakpoint, vscode graphical interface.

**Comment by KirkMunro** [comment]
@ylluminate Even though this has been marked as answered, I'd like to ask you a few questions if you're still paying attention to this thread.

> I've used it off and on for years and each time I've used it I have always spit and cursed under my breath about how on earth could MS be pushing backwards vs forging ahead with a proven technology that sys admins and developers already know and love around the globe.

Can you go into a bit more detail on this point? What about it has made you "spit and curse" when using it? What makes you feel MS is pushing backwards vs forging ahead?

> In an effort to unify the shell world, I think PowerShell could get really creative by providing a ZSH and BASH compatibility layer.

What does such a compatibility layer look like to you? Are there specific things you want added? If so, can you share some examples? Or did the replies above telling you that you could just invoke bash with an inline script really address your concerns? Since you didn't respond, I have no idea if that is all you were looking for or not.

FYI, related to this topic, there are some discussions going on about adding language syntax that has bash users in mind. For example, [this RFC that is currently in a PR](https://github.com/PowerShell/PowerShell-RFC/pull/192). It proposes adding chaining via `&&` and `||`. If it's more features like those that you're looking for, what else?

**Comment by MyriaCore** [comment]
Old post, but as far as I can tell, Powershell is NOT currently POSIX compatible, as @iSazonov suggested. I've been toying around with it since I've been trying out [fvim](https://github.com/yatli/fvim) on windows. There are basic POSIX things that aren't supported and just not there. 

To demystify what "POSIX compatibility" means for users like @KirkMunro, it basically just amounts to support for a subset of functionality called the POSIX Shell, which is laid out in [this document](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/utilities/V3_chap02.html#tag_18). It includes things like, but not limited to:

- `$@`, which is equivalent to `$args`
- `$1`, `$2`, etc to get the first and second arguments, and so on
- `if` / `fi`, `case` /  `esac` syntax

This syntax looks super fugly, especially for those who are used to the way PS does things. However, it's an important stepping stone, because it would attract people from the linux world who may have kept from switching to PS as their main scripting shell because their scripts wouldn't be guaranteed to run in PS.

**Comment by brandones** [comment]
PowerShell does not parse variable assignments in a POSIX-compliant way, see [the same document linked above](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/utilities/V3_chap02.html), section 2.9.1 Simple Commands. `FOO=bar echo "$FOO"` should print `bar`.
