### ISSUE TITLE
PowerShell should set its CWD on *nix

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#9325]
Discussing this with @TylerLeonhardt.

A number of applications and utilities use the process CWD information provided by the OS to do useful things. For example iTerm2 can follow your shell session's CWD in the title.

I feel like there has been discussion of this before but can't provide it anywhere, so opening an issue.

My proposal is:

- PowerShell has multiple runspaces, each of which can be in a different location at the same time
- Therefore PowerShell should expose its CWD as the location of runspace 1, since this is very likely to be the interactive runspace
- This should be available as a simple API internally that is a no-op on other runspaces, and it should be executed beside whatever changes PowerShell's own concept of CWD.

**Comment by rjmholt** [comment]
For reference, this is an ask to implement [`chdir`](http://pubs.opengroup.org/onlinepubs/007904875/functions/chdir.html) calls when runspace 1 changes its working directory. .NET Core exposes it as [`Directory.SetCurrentDirectory()`](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.setcurrentdirectory?view=netcore-3.0).

**Comment by TylerLeonhardt** [comment]
There are a lot of reasons why having this would be good. Pretty much every terminal emulator on non-Windows relies on CWD. Here are some that I wish I could take advantage of:

In [iTerm2](iterm2.com/):

This bullet uses CWD when creating a new tab so that the new tab is in the same directory as the previous tab:
![image](https://user-images.githubusercontent.com/2644648/55765093-ee01e400-5a22-11e9-82ea-a6e6029a66dd.png)

(Note: [Hyper](hyper.is) does the same thing)

The git branch in the status bar at the top uses the CWD to search for a .git folder to see what branch you're on:
![image](https://user-images.githubusercontent.com/2644648/55765114-0bcf4900-5a23-11e9-9b2d-dc51cb9b25f9.png)

There are many other examples across multiple terminal emulators on non-Windows. Using CWD seems to be the way to integrate a rich terminal experience.

**Comment by TylerLeonhardt** [comment]
btw, I attempted to fix this a while back - https://github.com/PowerShell/PowerShell/pull/6824

I like the addition of having it only apply to `Runspace 1`

**Comment by iSazonov** [comment]
cons - there is nested prompts.

**Comment by TylerLeonhardt** [comment]
@iSazonov please elaborate on why that is a con. If you go into a nested prompt, you are still in the same Runspace (Runspace 1) and I would expect CWD changes to be reflected in that nested prompt.

**Comment by rjmholt** [comment]
Had an email thread about this today and just want to write up some arguments against this:
- There’s no formal definition of the canonical runspace, and runspaces can be created and closed on the fly. So setting CWD based on one of them is slightly arbitrary.
- The current CWD setting is the .NET default of “the directory where the process was started”, which is also useful information
- The existing behaviour has been in for some time, and breaking it could cause issues
