### ISSUE TITLE
BUG Mount-DiskImage not usable in a script

### ISSUE THREAD

**Issue by logg-sar** [PowerShell/PowerShell#9380]
# Steps to reproduce

Mount-DiskImage -ImagePath C:\ISO\isofile.iso -PassThru. This is working.
****
cd /d C:\ISO
Mount-DiskImage -ImagePath .\isofile.iso -PassThru. NOT working.
****
$isopath="C:\ISO\isofile.iso"
Mount-DiskImage -ImagePath $isopath -PassThru. NOT working.
***
# Expected behavior
Mount-DiskImage should work, as usuable in any script, with variables without knowing the full path.

# Actual behavior

Cannot bind argument to parameter 'ImagePath' because it is null.

# Environment data

PSVersion 6.2.0
PsEdition Core

**Comment by rjmholt** [comment]
Hi @logg-sar, I assume the same behaviour occurs in Windows PowerShell?

If so, the problem is that `Mount-DiskImage` has not been implemented to resolve paths.

`Mount-DiskImage` is part of the [Storage](https://docs.microsoft.com/en-us/powershell/module/storage/?view=win10-ps) module, and isn't part of PowerShell 6.2 (i.e. it's not in the code base on GitHub here). Instead I believe the module comes with Windows, so the best option is to report this [here](https://windowsserver.uservoice.com/forums/295056-storage) and in Feedback Hub.

**Comment by logg-sar** [comment]
@rjmholt

Yes, your´e right - same behaviour in Powershell 5.*

I´ve already submitted this issue at uservoice but - as your link also shows (the issue you mentioned is 5 years(!!!) old - uservoice is a dead end.
No one reads and reacts or fixes something. Disappointing but true.
I posted here because I know that the developers here hear the user and I hoped for a fix.

Well....
