### ISSUE TITLE
PSImplicitRemotingBatching doesn't work when wrapped in measure-command

### ISSUE THREAD

**Issue by edyoung** [PowerShell/PowerShell#9446]
# Steps to reproduce

```powershell
# I ran this in Cloud Shell
Enable-ExperimentalFeature PSImplicitRemotingBatching
# reset pwsh
Connect-EXoPSSession 
Measure-Command { get-user} # get-user is implicit remoting cmdlet
```

# Expected behavior

```none
runs get-user and prints how long it takes, as it does without the experimental feature enabled.
```

# Actual behavior

```powershell
PS Azure:\> measure-command { get-user }
The syntax is not supported by this runspace. This can occur if the runspace is in no-language mode.
+ CategoryInfo          : ParserError: (measure-command { get-user }:String) [], ParseException
+ FullyQualifiedErrorId : ScriptsNotAllowed
+ PSComputerName        : outlook.office365.com
```

# Environment data

```powershell
PS Azure:\> $psversiontable

Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Linux 4.15.0-1041-azure #45-Ubuntu SMP Fri Mar 15 14:41:00 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Measure-Command is not included in the remote runspace being imported.

**Comment by edyoung** [comment]
FYI @PaulHigin

**Comment by PaulHigin** [comment]
There are a couple of issues here:

1. This experimental feature attempts to batch implicit remote commands so that multiple remoting round trips do not occur, and should in general increase performance.  However, this example has only one remoting command, 'Get-User', so batching will not help here.

2. Measure-Command is currently supported by batching it along with other commands to be run directly on the remote target.  But in this case the remote session is locked down and Measure-Command is not allowed, and is why you get the error.  Measure-Command is convenient but not essential in executing implicit remote commands.  You can still use this batching feature by just running allowed implicit commands, e.g., 'Get-User | Where-Object Name -eq 'User' | Remove-User'.  This will be batched if Get-User, Remove-User are implicit remoting commands and Where-Object is supported on the remote session.

**Comment by edyoung** [comment]
I understand this is not a useful batching scenario and that there are other ways to time things. But since psimplicitremotingbatching is meant to be a transparent optimization I think it's a problem that command-lines which would work when it is off fail with a cryptic message when it's on
