### ISSUE TITLE
PowerShell Daemon/NTService

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#9456]
# Summary of the new feature/enhancement

PowerShell as a Daemon/NTService would help with several things:

  - Startup time will be improved as the console host doesn't need to initialize a runspace as it exists within the Daemon
  - We need some sort of hosting of PowerShell for JEA scenarios which are currently handled by WinRM but is not cross platform and only supports WS-Man and not SSH based remoting
  - Support headless management scenarios where you just want an endpoint to execute a script

**Comment by iSazonov** [comment]
Some MSFT teams already have something like (Exchange server and others).

**Comment by SteveL-MSFT** [comment]
Exchange (unless they did something different since) was using IIS Hosted PowerShell (rather than WinRM).

**Comment by iSazonov** [comment]
Exchange continues using IIS Hosted PowerShell. I think SharePoint and Skype/Team too. We could think about single-on-system hosted solution and share with all applications.

**Comment by JasonFossen** [comment]
Any additional information like this about the future of JEA is good, especially since there was no mention of JEA in the PowerShell 7 roadmap post on May 30th.  Thank You

**Comment by SteveL-MSFT** [comment]
@JasonFossen to be clear, PowerShell Core 6 already supports JEA, but only on Windows via WS-MAN.  Is your interest in JEA for non-Windows (or on Windows via SSH)?  This is a big work item that is currently not in plan for PS7.0.  Perhaps 7.1.

**Comment by JasonFossen** [comment]
@SteveL-MSFT  Yes, thank you, I should have been more specific: JEA over SSH to both Windows and Linux, and also further integration with Windows Admin Center (WAC).  I have difficulty selling PowerShell to Linux people who are already using bash and Python, but SSH+JEA+WAC for both Windows and Linux on-prem targets, preferably with some pre-configured starter JEA endpoint definitions that could be pushed out through WAC itself, would be very nice.  They immediately "get" the idea when shown a diagram of Browser -> TLS -> WAC gateway -> SSH -> Linux/Windows Targets, since this is similar to what they already do for other products, but they key selling point for PowerShell would be the JEA command restrictions enforced on the targets themselves, not in WAC, using analogies from restricted bash, sudo, setuid, seccomp, etc.

**Comment by iSazonov** [comment]
Perhaps this is a reason to port WS-MAN quickly.

**Comment by SteveL-MSFT** [comment]
I've already started a discussion with WAC team on not requiring WMF and instead use PSCore6 if available as a pre-req.  Once they do that, I can see about having them use SSH if available.
