### ISSUE TITLE
Writing Cmdlets in other languages

### ISSUE THREAD

**Issue by fMichaleczek** [PowerShell/PowerShell#9535]
Source : [PowerShell Team Blog/PowerShell on Linux and Open Source](https://devblogs.microsoft.com/powershell/powershell-on-linux-and-open-source-2/)

**Comment by SteveL-MSFT** [comment]
Yes, this was something we thought about very early on, but haven't done anything with.  I think it may be more important initially to make it easier for other languages to call into PowerShell by providing client libraries (local and remote) and then enable cmdlets to be written in other languages (if there is sufficient interest).

**Comment by fMichaleczek** [comment]
@SteveL-MSFT I try Peachpie a php implementation based on dotnet core, but failed because PSCmdlet class need have a constructor less. I also think the Iron(Python) languages will have the same barrier.

I'm studing Cmdletization to find a workaround (as a LanguageCmdletAdapter). 
Another idea ?

**Comment by SteveL-MSFT** [comment]
@fMichaleczek Looking at Peachpie, it converts PHP to .NET IL.  My thinking is that we want to support other languages in their native environment and not require them to be compiled into .NET.  So there would be PowerShell bindings for various languages we'd want to support.  PHP isn't one that came to mind, but Python would probably be something we'd want to support.  So rather than trying to implement PSCmdlet as it is defined today, you would have something equivalent in whatever language you want to use.  We haven't looked at this in detail yet due to other priorities.
