### ISSUE TITLE
get-itemproperty : Unable to cast object of type 'System.Int64' to type 'System.Int32' (Specified cast is not valid).

### ISSUE THREAD

**Issue by jszabo98** [PowerShell/PowerShell#9552]
Netbeans 8.2 (64-bit) installer currently puts a 64 bit integer (1) in a dword in the registry under the name NoModify under HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\nbi-nb-base-8.2.0.0.201609300101.  They don't seem to be in any rush to fix it.  https://netbeans.org/bugzilla/show_bug.cgi?id=251538  In Regedit, it says "(invalid dword (32-bit) value)".  Get-itemproperty could recover from this a bit better.  It doesn't show the other values, and other keys included after don't get displayed.  This is even with -erroraction silentlycontinue.  The error message doesn't point to the offending key.  Unless you pipe an error variable through format-list * -force.  Example superuser thread about it:  https://superuser.com/questions/1352166/how-to-resolve-error-specified-cast-is-not-valid-error-during-installation.  Error in PS 5.1 looks like:  "Specified cast is not valid."

# Steps to reproduce

```powershell
# with 64-bit Netbeans IDE 8.2 installed
get-itemproperty hklm:\software\microsoft\windows\currentversion\uninstall\*
```

# Expected behavior

```none
# display properties of all subkeys
```

# Actual behavior

```none
# displays some key properties, then...
get-itemproperty : Unable to cast object of type 'System.Int64' to type 'System.Int32'.
At line:1 char:1
+ get-itemproperty hklm:\software\microsoft\windows\currentversion\unin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-ItemProperty], InvalidCastException
+ FullyQualifiedErrorId : System.InvalidCastException,Microsoft.PowerShell.Commands.GetItemPropertyCommand
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.2
PSEdition                      Core
GitCommitId                    6.1.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
As a test, you can import this as a .reg file, and it will put a 64 bit integer into a 32 bit dword registry item.  (a 32-bit dword would be "NoModify"=dword:00000001)

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\nbi-nb-base-8.2.0.0.201609300101]
"NoModify"=hex(4):01,00,00,00,00,00,00,00
```

**Comment by jszabo98** [comment]
I found another location that seems to have all invalid dwords.  It seems to be a natural part of Windows 10.

```powershell
get-itemproperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\History\*\0' lParam
```

**Comment by JVimes** [comment]
Also happens with editor settings from Unity 

```pwsh
PS> Get-ItemProperty 'HKCU:\SOFTWARE\Unity Technologies\Unity Editor 5.x\'
Get-ItemProperty: Unable to cast object of type 'System.Int64' to type 'System.Int32'.
```

**Comment by jszabo98** [comment]
PowerShell 7.4.0
reg import badreg.reg
The operation completed successfully.
get-itemproperty HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\nbi-nb-base-8.2.0.0.201609300101
Get-ItemProperty: Unable to cast object of type 'System.Int64' to type 'System.Int32'.

**Comment by iSazonov** [comment]
If I understand correctly we should follow `dir` behavior - write error and continue enumeration.

/cc @mklement0 What do you think?

**Comment by mklement0** [comment]
Yes, I agree that it should be non-terminating error.

**Comment by ArmaanMcleod** [comment]
Thanks @jszabo98 @mklement0 @iSazonov.

I did not originally repro this right originally. After writing a pester test with repro I was able to fix `Get-ItemProperty` to report non-terminating error.

**Comment by AndrewSav** [comment]
Could some one please kindly explain to me, why is this a error? That is, when the patch is applied, I understand the error will become non terminating, but it will still be a error. I'd like to understand why and how to actually get a registry value in this case. Is there a way to specify correct type?

**Comment by IISResetMe** [comment]
@AndrewSav "DWORD" stands for "double word", and "word" in this context means a 16 bit integer. So a DWORD is a 32 bit integer. If the value in the registry is marked as containing a 32-bit integer but actually contains _64 bits_ of information, then the data won't fit into 32 bits, hence the conversion error.

**Comment by jszabo98** [comment]
It's funny that windows even allows entering invalid dword values.  Netbeans still does it by the way.  My install script ends with:

Set-ItemProperty HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\nbi-nb-all-* NoModify 1 -Type DWord

**Comment by AndrewSav** [comment]
> @AndrewSav "DWORD" stands for "double word", and "word" in this context means a 16 bit integer. So a DWORD is a 32 bit integer. If the value in the registry is marked as containing a 32-bit integer but actually contains 64 bits of information, then the data won't fit into 32 bits, hence the conversion error.

So basically, imagine scenario: windows allowing write 64 bit into a data structure marked as 32 bit. Some software we are integrating with using this feature and store there 64 bit of data that it also use. You may consider it's a bug in that software, but that's beside the point. You are requried to integrate with it, and it uses registry in this way you can do nothing about that.

If PowerShell refuses to read this data, then we will have to use something else (Windows API) to work with it. This IMO does not speak for PowerShell.

If Windows registry allows that marked data type does not coincide with actually used data type, this is the abstraction PowerShell should faithfully reflect. It's not up to PowerShell (IMO) to decide what is right and what is not in other parts of the system, its role (in this context) is to faciliate access to what is there.

**Comment by mklement0** [comment]
> If Windows registry allows that marked data type does not coincide with actually used data type, this is the abstraction PowerShell should faithfully reflect.

Indeed, and it should report this _mismatch_ in  the form of a _non-terminating error_, which is what this issue is about.

> It's not up to PowerShell (IMO) to decide what is right and what is not

Indeed it isn't, which is why reporting an error indicating the mismatch is the appropriate thing to do, given that what is there is _unknown_ in the case at hand.

Just because we happen to know the _specific_ mismatch _in the case at hand_, it strikes me as inappropriate to make PowerShell _guess_ what the underlying intent may or may not be: no one can know _in all cases_ what the true data type of the actual data is.

What it comes down to:

* The Windows APIs should never allow creating this kind of mismatch between the _declared_ data type and the _actual data_.

* Absent that, it is any given program's responsibility to avoid creating such a mismatch to begin with.

**Comment by iSazonov** [comment]
> * The Windows APIs should never allow creating this kind of mismatch between the _declared_ data type and the _actual data_.

I guess the API is 25 years old age - from Windows 95 😄 It'd be huge breaking change to change the API.

Since PowerShell is not only management tool but _diagnostics_ too we could consider to introduce new **Raw** switch to return registry property value as raw `Object`. (An alternative for Raw would be to add an extension method for the returned PSCustomObject to get raw data.) If it is acceptable next question would be - should we add Raw for Set-ItemProperty, I think it's unnecessarily dangerous.

**Comment by craiglandis** [comment]
This still repros for me with 7.5.0-rc.1 and 7.4.6. OS is Win11 ENT 24H2 10.0.26100.2605.

It does not repro in 5.1.26100.2161.

It does not repro on all my machines. The machine where it repros has AMD Radeon 780M Graphics (driver 32.0.11037.4004 8/23/2024). The 780M is the integrated GPU for the AMD 7940HS CPU (and other AMD CPUs).

```
PS C:\> Get-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000"
Get-ItemProperty: Unable to cast object of type 'System.Byte[]' to type 'System.Int32'.
```

 -ErrorAction SilentlyContinue doesn't suppress the error - 

```
PS C:\> Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000" -ErrorAction SilentlyContinue
Get-ItemProperty: Unable to cast object of type 'System.Byte[]' to type 'System.Int32'.
```

$ErrorActionPreference = 'SilentlyContinue' does suppress the error, but still nothing is returned. And the key exists and has plenty of subkeys and values, because again, the same command runs without error, and returns the key as expected, when run from PS5.1.

```
PS C:\> $ErrorActionPreference = 'SilentlyContinue'; Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000" -ErrorAction SilentlyContinue
```

**Comment by ArmaanMcleod** [comment]
@craiglandis It will be fixed in the next release. I'm not particularly sure when that will happen.

**Comment by iSazonov** [comment]
> Do you know when the next pre-release will get built?

Traditionally, this is synchronized with the release of new .Net versions - so waiting .Net 9.0.1 later in the January.
But the daily build is always available on the repo main page.
