### ISSUE TITLE
Make methods in custom classes support optional parameters

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#9701]
# Summary of the new feature/enhancement

#9684 shows that while you can _declare_ optional parameters, they are  _in effect_ mandatory, and the default value is _ignored_.

Reporting an error when an attempt is made to declare an optional parameter is one solution, but a better option is to _enable proper support for optional method parameters_, so that the following would work:

```powershell
# Wishful thinking
PS> class Foo { [string] Bar($Baz = 'Bam') { return $Baz } }; [Foo]::new().Bar()
Bam
```

**Comment by iSazonov** [comment]
We need reference this in #6652

**Comment by rjmholt** [comment]
I think this is essentially https://github.com/PowerShell/PowerShell/issues/7534.

**Comment by vexx32** [comment]
@rjmholt it might be related, but that looks to be pretty different; for one, it affects c# classes added with Add-Type, not PS classes,  and the error is different (it actually recognises that there was another argument that is not by default, buy the looks of it).

**Comment by SeeminglyScience** [comment]
Yeah `TypeDefiner` just ignores the assignment in class method parameters. This does bring up an interesting question though.

Method parameter defaults have to be written into metadata, therefore they must be constants.  How will PowerShell handle that?

1. Require parameter defaults to be constants, just like C# does
1. Allow expressions, set the metadata default value to `null` or `default`, and add the expression as the first line in the method body.  Problem is I can't think of a way for the expression to tell if the parameter was not specified, or if a `null` or `default` value was passed specifically.  This seems impossible.

**Comment by rjmholt** [comment]
@vexx32 I'm imagining there are two problems:

- .NET methods with optional parameters don't have those parameters honoured. It doesn't matter whether it's a C# or a PS class, at execution time it's all .NET
- The PS parser does not reject assignment in method parameter specifications, creating the expectation that optional parameters will work (probably because it was planned at some stage). We'd need store the RHS in the AST and hook it into the type generator.

I'd expect the fix for #7534 to make the first part work.

If we just went with ordinary .NET constant expressions, it wouldn't be too difficult to make the second part work either.

But I think it would be worth trying to make arbitrary expressions work:

- Allow the RHS to be any expression, which is an implicit lambda like for function parameters
- Given an argument of type `[T]`, the lambda is compiled as a `[Func[T]]`, wrapping an implicit scriptblock around the expression (since classes are decidedly type-checking)
- When the parameter is supplied on method call, the lambda is not called
- When the parameter is not supplied, the lambda is called (and the script block is dot-sourced into the class method body)
- This could done by adding statements into the top of the class body, like:
    ```
    if (!paramN.HasValue && paramN.DefaultLambda != null)
    {
        $paramN = paramN.DefaultLambda()
    }
    ```

**Comment by SeeminglyScience** [comment]
> This could done by adding statements into the top of the class body, like:

@rjmholt How will you know if the parameter was or wasn't specified though?  If the caller is from PowerShell then that could work, but if the caller isn't then it'll look like `null` or `default` was specified.

**Comment by ALiwoto** [comment]
Any update on this?

**Comment by ALiwoto** [comment]
Is this feature request not-planned to be working on? Or does it accept contribution?

**Comment by vexx32** [comment]
There isn't any active work planned on this one to my current knowledge. It probably isn't marked up for grabs because it's rather an advanced part of the engine, and we tend to not mark an issue up for grabs unless one of these two conditions are met:

- It's a reasonably approachable area of the code that we expect most folks to be able to at least take a stab at
- There's a relatively clear path to follow laid out by someone that has done some investigations

If you think you can take a stab at this one, I won't stop you, and a contribution that adds this functionality has a decent chance of being accepted. However, to set expectations appropriately, I would expect the review process for it to take quite a long time, both because of limitations on the team's time, and because of the relative complexity of the code necessary to make this work in the ways that have been described in this issue and ensuing comments.

For reference, I have had PRs in somewhat less-complex code areas take upwards of 6 months to get merged. It would not surprise me if it took longer than that for this kind of code area.

That said.... it _would_ be appreciated nonetheless, if you can get it to work.
