### ISSUE TITLE
Review PR to only show MeasureInfo with populated values for security concerns

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#9726]
# Summary of the new feature/enhancement

The PR to improve MeasureInfo formatting to only display properties with values creates a new script block.  This api needs to be reviewed to ensure it can't be used as a way to change the language mode in constrained environments.

See https://github.com/PowerShell/PowerShell/pull/7104#discussion_r213178578

cc @PaulHigin

**Comment by PaulHigin** [comment]
@SteveL-MSFT  It looks like the ScriptBlock changes were reverted from the PR you reference (https://github.com/PowerShell/PowerShell/pull/7754).

Passing a string that is converted into a ScriptBlock is *not* acceptable, as this would allow script injection with privilege escalation on locked down systems. However, it is Ok to have the API take a ScriptBlock object (not string), because the script block is marked correctly with the right trust level at creation.

**Comment by iSazonov** [comment]
Should we do anything with #7104 before 7.0 GA?

**Comment by adityapatwardhan** [comment]
@PaulHigin @TravisEz13  Please review for security

**Comment by PaulHigin** [comment]
@adityapatwardhan  What PR needs to be reviewed?

**Comment by iSazonov** [comment]
@PaulHigin Please see the request https://github.com/PowerShell/PowerShell/pull/7104#discussion_r213178578

**Comment by PaulHigin** [comment]
@iSazonov  Can you summarize what the security concerns are?  Is this related to a change in this PR, and if so which one?  Or is there a general security concern in the code which may have always existed?  If so what is the concern?

**Comment by vexx32** [comment]
The PR (which has since been reverted due to the security concern) introduces a public API which allows creation of a scriptblock from a string value as part of the formatting API.

If I'm mistaken, please correct me, but I believe the concern is whether creating a scriptblock in such a manner would potentially create a way to bypass restricted language modes.

**Comment by SteveL-MSFT** [comment]
Since that PR has been reverted, it seems the original concern is no longer valid.

**Comment by vexx32** [comment]
Did we decide that PR is no longer wanted? 😕

**Comment by iSazonov** [comment]
Yes, the same question. The PR was reverted until security review will be done.
