### ISSUE TITLE
Extend the Task bar menu for Windows PowerShell to also include any other PowerShell Versions 

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#9851]
In this menu

![image](https://user-images.githubusercontent.com/6355225/59104025-4fadd400-8928-11e9-880b-a6bc90acd45b.png)

It would be helpful to also include any PowerShell Core Versions installed on the system as well as this will help aid adoption and eases scenarios where users are still switching between versions (like I am)

**Comment by iSazonov** [comment]
Looks like one item for both versions.
/cc @bergmeister Is it possible to implement?

/cc @SteveL-MSFT Make sense to implement in PowerShell Core? It seems it should be in Windows distributive itself.

**Comment by bergmeister** [comment]
For PowerShell Core, I have added the 'Run as Administrator' option. The feature in general is referred to as a jumpstart menu.
The implementation of it calls a very delicate and complex sequence of Windows COM APIs (in Windows PowerShell it is C++ code that can still be seen in the MainEntry.cpp file of the source-depot branch, in PowerShell it is managed C# code).
It works roughly like this: When PowerShell is starting up and the console host is detected to be interactive then it registers this jump start menu with Windows (if it is not already registered). As an aside: You can actually see this by pinning an icon of PowerShell (either Windows PowerShell or PSCore) to the taskbar in a fresh new VM and right-clicking on it and you will observe the jump start menu is not there, only after you have opened PowerShell the very first time, the jump start menu will appear from then on.

Without digging deep into the details of the Windows API calls, I cannot say with certainty whether it would be possible to register a startmenu for the Windows PowerShell binary from PowerShell Core (because I am sure the PowerShell team would be against changing code in Windows PowerShell), therefore one would need to research or PoC this.
If it is possible then there is the complication that if a jump start menu is registered and PowerShell Core is uninstalled (or re-installed using a different path), then the installer would need to clear it.

**Comment by MovGP0** [comment]
I guess this feature should be in Windows Terminal, rather than in PowerShell itself.

**Comment by rkeithhill** [comment]
I'm a little uncomfortable with the jumplist of one app launching other versions of the app.  I realize that the Windows PowerShell jumplist does this by adding ISE but at least the two are related "version-wise".   FWIW I have machines with ~6 versions of Visual Studio installed and none of their taskbar jumplists offer to launch a different version of VS.

@MovGP0 Windows Terminal already offers both Windows PowerShell and PowerShell Core (if it detects it is installed on the machine). You can also customize (add/remove/reorder) this list as I've done here:

![image](https://user-images.githubusercontent.com/5177512/59152189-8c4aff80-89fc-11e9-8041-68ee1e71ed81.png)

**Comment by kilasuit** [comment]
Closing as per comment from @rkeithhill above
