### ISSUE TITLE
Powershell Core 6.2.1 does not work with DOS device paths

### ISSUE THREAD

**Issue by PowershellNinja** [PowerShell/PowerShell#9909]
# Steps to reproduce

```powershell
Get-ChildItem -Path \\?\c:\
```

# Expected behavior
As supported since .NET Core 1.1:
https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#dos-device-paths

```Powershell
    Directory: C:\

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        25.06.2018    15:27                PerfLogs
d-r---        17.06.2019    11:10                Program Files
d-----        13.06.2019    22:04                Program Files (x86)
d-----        15.04.2019    14:03                Temp
d-r---        10.12.2018    17:51                Users
d-----        13.06.2019    19:02                Windows
```

# Actual behavior

No error, no output

# Environment data

```powershell

Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.14393 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
It is not regression. I checked that this does not work in previous versions and Windows PowerShell.

@PowershellNinja Could you add more information why you need this?

**Comment by AikenBM** [comment]
The almost universal reason for needing the `\\?\C:\Path` or `\\?\UNC\servername\share\path` syntax (both known as Long UNC path, as far as I'm aware) is long path support (path length greater than 260 characters). If I remember right, the reason it did not work on PowerShell 5.x and below is because the underlying .Net classes also did not support that syntax. Those .Net classes simply don't use the updated WinAPI calls that support either the Long UNC syntax or paths longer than 260 characters.

I believe that [long path support has changed in the .Net Framework](https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/), but I do not know if the Long UNC syntax works there or not or if Windows PowerShell works under that configuration or not. I have no idea if it works for .Net Core applications, either, but [it looks like they're heading towards long path support](https://github.com/dotnet/corefx/issues/645).

**Comment by iSazonov** [comment]
Thanks!
PowerShell supports long path name but not the DOS-like syntax - we already have a tracking issue #4439

**Comment by PowershellNinja** [comment]
Sorry for the long wait, yes the purpose of this was to be able to work with long path names, for migrations to SharePoint Online for Example.
So if I understand this correctly, PS 6 should already be able to handle long path names?

**Comment by iSazonov** [comment]
@PowershellNinja Yes, PowerShell  6 works with long paths. You need to turn on the feature on Windows 10.

**Comment by rivy** [comment]
@PowershellNinja , this looks more like a globbing issue. `Get-ChildItem -literalPath \\?\c:\` works correctly.
